// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ControlNetLogDataProtoV0001.proto
// Protobuf C++ Version: 4.25.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_ControlNetLogDataProtoV0001_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ControlNetLogDataProtoV0001_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025002 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ControlNetLogDataProtoV0001_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ControlNetLogDataProtoV0001_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ControlNetLogDataProtoV0001_2eproto;
namespace Isis {
class ControlNetLogDataProtoV0001;
struct ControlNetLogDataProtoV0001DefaultTypeInternal;
extern ControlNetLogDataProtoV0001DefaultTypeInternal _ControlNetLogDataProtoV0001_default_instance_;
class ControlNetLogDataProtoV0001_Point;
struct ControlNetLogDataProtoV0001_PointDefaultTypeInternal;
extern ControlNetLogDataProtoV0001_PointDefaultTypeInternal _ControlNetLogDataProtoV0001_Point_default_instance_;
class ControlNetLogDataProtoV0001_Point_Measure;
struct ControlNetLogDataProtoV0001_Point_MeasureDefaultTypeInternal;
extern ControlNetLogDataProtoV0001_Point_MeasureDefaultTypeInternal _ControlNetLogDataProtoV0001_Point_Measure_default_instance_;
class ControlNetLogDataProtoV0001_Point_Measure_DataEntry;
struct ControlNetLogDataProtoV0001_Point_Measure_DataEntryDefaultTypeInternal;
extern ControlNetLogDataProtoV0001_Point_Measure_DataEntryDefaultTypeInternal _ControlNetLogDataProtoV0001_Point_Measure_DataEntry_default_instance_;
}  // namespace Isis
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Isis {

// ===================================================================


// -------------------------------------------------------------------

class ControlNetLogDataProtoV0001_Point_Measure_DataEntry final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Isis.ControlNetLogDataProtoV0001.Point.Measure.DataEntry) */ {
 public:
  inline ControlNetLogDataProtoV0001_Point_Measure_DataEntry() : ControlNetLogDataProtoV0001_Point_Measure_DataEntry(nullptr) {}
  ~ControlNetLogDataProtoV0001_Point_Measure_DataEntry() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ControlNetLogDataProtoV0001_Point_Measure_DataEntry(::google::protobuf::internal::ConstantInitialized);

  inline ControlNetLogDataProtoV0001_Point_Measure_DataEntry(const ControlNetLogDataProtoV0001_Point_Measure_DataEntry& from)
      : ControlNetLogDataProtoV0001_Point_Measure_DataEntry(nullptr, from) {}
  ControlNetLogDataProtoV0001_Point_Measure_DataEntry(ControlNetLogDataProtoV0001_Point_Measure_DataEntry&& from) noexcept
    : ControlNetLogDataProtoV0001_Point_Measure_DataEntry() {
    *this = ::std::move(from);
  }

  inline ControlNetLogDataProtoV0001_Point_Measure_DataEntry& operator=(const ControlNetLogDataProtoV0001_Point_Measure_DataEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControlNetLogDataProtoV0001_Point_Measure_DataEntry& operator=(ControlNetLogDataProtoV0001_Point_Measure_DataEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ControlNetLogDataProtoV0001_Point_Measure_DataEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const ControlNetLogDataProtoV0001_Point_Measure_DataEntry* internal_default_instance() {
    return reinterpret_cast<const ControlNetLogDataProtoV0001_Point_Measure_DataEntry*>(
               &_ControlNetLogDataProtoV0001_Point_Measure_DataEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ControlNetLogDataProtoV0001_Point_Measure_DataEntry& a, ControlNetLogDataProtoV0001_Point_Measure_DataEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(ControlNetLogDataProtoV0001_Point_Measure_DataEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControlNetLogDataProtoV0001_Point_Measure_DataEntry* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ControlNetLogDataProtoV0001_Point_Measure_DataEntry* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ControlNetLogDataProtoV0001_Point_Measure_DataEntry>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ControlNetLogDataProtoV0001_Point_Measure_DataEntry& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ControlNetLogDataProtoV0001_Point_Measure_DataEntry& from) {
    ControlNetLogDataProtoV0001_Point_Measure_DataEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ControlNetLogDataProtoV0001_Point_Measure_DataEntry* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Isis.ControlNetLogDataProtoV0001.Point.Measure.DataEntry";
  }
  protected:
  explicit ControlNetLogDataProtoV0001_Point_Measure_DataEntry(::google::protobuf::Arena* arena);
  ControlNetLogDataProtoV0001_Point_Measure_DataEntry(::google::protobuf::Arena* arena, const ControlNetLogDataProtoV0001_Point_Measure_DataEntry& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataValueFieldNumber = 3,
    kDataTypeFieldNumber = 2,
  };
  // required double dataValue = 3;
  bool has_datavalue() const;
  void clear_datavalue() ;
  double datavalue() const;
  void set_datavalue(double value);

  private:
  double _internal_datavalue() const;
  void _internal_set_datavalue(double value);

  public:
  // required int32 dataType = 2;
  bool has_datatype() const;
  void clear_datatype() ;
  ::int32_t datatype() const;
  void set_datatype(::int32_t value);

  private:
  ::int32_t _internal_datatype() const;
  void _internal_set_datatype(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Isis.ControlNetLogDataProtoV0001.Point.Measure.DataEntry)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    double datavalue_;
    ::int32_t datatype_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ControlNetLogDataProtoV0001_2eproto;
};// -------------------------------------------------------------------

class ControlNetLogDataProtoV0001_Point_Measure final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Isis.ControlNetLogDataProtoV0001.Point.Measure) */ {
 public:
  inline ControlNetLogDataProtoV0001_Point_Measure() : ControlNetLogDataProtoV0001_Point_Measure(nullptr) {}
  ~ControlNetLogDataProtoV0001_Point_Measure() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ControlNetLogDataProtoV0001_Point_Measure(::google::protobuf::internal::ConstantInitialized);

  inline ControlNetLogDataProtoV0001_Point_Measure(const ControlNetLogDataProtoV0001_Point_Measure& from)
      : ControlNetLogDataProtoV0001_Point_Measure(nullptr, from) {}
  ControlNetLogDataProtoV0001_Point_Measure(ControlNetLogDataProtoV0001_Point_Measure&& from) noexcept
    : ControlNetLogDataProtoV0001_Point_Measure() {
    *this = ::std::move(from);
  }

  inline ControlNetLogDataProtoV0001_Point_Measure& operator=(const ControlNetLogDataProtoV0001_Point_Measure& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControlNetLogDataProtoV0001_Point_Measure& operator=(ControlNetLogDataProtoV0001_Point_Measure&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ControlNetLogDataProtoV0001_Point_Measure& default_instance() {
    return *internal_default_instance();
  }
  static inline const ControlNetLogDataProtoV0001_Point_Measure* internal_default_instance() {
    return reinterpret_cast<const ControlNetLogDataProtoV0001_Point_Measure*>(
               &_ControlNetLogDataProtoV0001_Point_Measure_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ControlNetLogDataProtoV0001_Point_Measure& a, ControlNetLogDataProtoV0001_Point_Measure& b) {
    a.Swap(&b);
  }
  inline void Swap(ControlNetLogDataProtoV0001_Point_Measure* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControlNetLogDataProtoV0001_Point_Measure* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ControlNetLogDataProtoV0001_Point_Measure* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ControlNetLogDataProtoV0001_Point_Measure>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ControlNetLogDataProtoV0001_Point_Measure& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ControlNetLogDataProtoV0001_Point_Measure& from) {
    ControlNetLogDataProtoV0001_Point_Measure::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ControlNetLogDataProtoV0001_Point_Measure* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Isis.ControlNetLogDataProtoV0001.Point.Measure";
  }
  protected:
  explicit ControlNetLogDataProtoV0001_Point_Measure(::google::protobuf::Arena* arena);
  ControlNetLogDataProtoV0001_Point_Measure(::google::protobuf::Arena* arena, const ControlNetLogDataProtoV0001_Point_Measure& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  using DataEntry = ControlNetLogDataProtoV0001_Point_Measure_DataEntry;

  // accessors -------------------------------------------------------

  enum : int {
    kLoggedMeasureDataFieldNumber = 2,
  };
  // repeated .Isis.ControlNetLogDataProtoV0001.Point.Measure.DataEntry loggedMeasureData = 2;
  int loggedmeasuredata_size() const;
  private:
  int _internal_loggedmeasuredata_size() const;

  public:
  void clear_loggedmeasuredata() ;
  ::Isis::ControlNetLogDataProtoV0001_Point_Measure_DataEntry* mutable_loggedmeasuredata(int index);
  ::google::protobuf::RepeatedPtrField< ::Isis::ControlNetLogDataProtoV0001_Point_Measure_DataEntry >*
      mutable_loggedmeasuredata();
  private:
  const ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point_Measure_DataEntry>& _internal_loggedmeasuredata() const;
  ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point_Measure_DataEntry>* _internal_mutable_loggedmeasuredata();
  public:
  const ::Isis::ControlNetLogDataProtoV0001_Point_Measure_DataEntry& loggedmeasuredata(int index) const;
  ::Isis::ControlNetLogDataProtoV0001_Point_Measure_DataEntry* add_loggedmeasuredata();
  const ::google::protobuf::RepeatedPtrField< ::Isis::ControlNetLogDataProtoV0001_Point_Measure_DataEntry >&
      loggedmeasuredata() const;
  // @@protoc_insertion_point(class_scope:Isis.ControlNetLogDataProtoV0001.Point.Measure)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedPtrField< ::Isis::ControlNetLogDataProtoV0001_Point_Measure_DataEntry > loggedmeasuredata_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ControlNetLogDataProtoV0001_2eproto;
};// -------------------------------------------------------------------

class ControlNetLogDataProtoV0001_Point final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Isis.ControlNetLogDataProtoV0001.Point) */ {
 public:
  inline ControlNetLogDataProtoV0001_Point() : ControlNetLogDataProtoV0001_Point(nullptr) {}
  ~ControlNetLogDataProtoV0001_Point() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ControlNetLogDataProtoV0001_Point(::google::protobuf::internal::ConstantInitialized);

  inline ControlNetLogDataProtoV0001_Point(const ControlNetLogDataProtoV0001_Point& from)
      : ControlNetLogDataProtoV0001_Point(nullptr, from) {}
  ControlNetLogDataProtoV0001_Point(ControlNetLogDataProtoV0001_Point&& from) noexcept
    : ControlNetLogDataProtoV0001_Point() {
    *this = ::std::move(from);
  }

  inline ControlNetLogDataProtoV0001_Point& operator=(const ControlNetLogDataProtoV0001_Point& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControlNetLogDataProtoV0001_Point& operator=(ControlNetLogDataProtoV0001_Point&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ControlNetLogDataProtoV0001_Point& default_instance() {
    return *internal_default_instance();
  }
  static inline const ControlNetLogDataProtoV0001_Point* internal_default_instance() {
    return reinterpret_cast<const ControlNetLogDataProtoV0001_Point*>(
               &_ControlNetLogDataProtoV0001_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ControlNetLogDataProtoV0001_Point& a, ControlNetLogDataProtoV0001_Point& b) {
    a.Swap(&b);
  }
  inline void Swap(ControlNetLogDataProtoV0001_Point* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControlNetLogDataProtoV0001_Point* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ControlNetLogDataProtoV0001_Point* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ControlNetLogDataProtoV0001_Point>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ControlNetLogDataProtoV0001_Point& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ControlNetLogDataProtoV0001_Point& from) {
    ControlNetLogDataProtoV0001_Point::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ControlNetLogDataProtoV0001_Point* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Isis.ControlNetLogDataProtoV0001.Point";
  }
  protected:
  explicit ControlNetLogDataProtoV0001_Point(::google::protobuf::Arena* arena);
  ControlNetLogDataProtoV0001_Point(::google::protobuf::Arena* arena, const ControlNetLogDataProtoV0001_Point& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  using Measure = ControlNetLogDataProtoV0001_Point_Measure;

  // accessors -------------------------------------------------------

  enum : int {
    kMeasuresFieldNumber = 2,
  };
  // repeated .Isis.ControlNetLogDataProtoV0001.Point.Measure measures = 2;
  int measures_size() const;
  private:
  int _internal_measures_size() const;

  public:
  void clear_measures() ;
  ::Isis::ControlNetLogDataProtoV0001_Point_Measure* mutable_measures(int index);
  ::google::protobuf::RepeatedPtrField< ::Isis::ControlNetLogDataProtoV0001_Point_Measure >*
      mutable_measures();
  private:
  const ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point_Measure>& _internal_measures() const;
  ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point_Measure>* _internal_mutable_measures();
  public:
  const ::Isis::ControlNetLogDataProtoV0001_Point_Measure& measures(int index) const;
  ::Isis::ControlNetLogDataProtoV0001_Point_Measure* add_measures();
  const ::google::protobuf::RepeatedPtrField< ::Isis::ControlNetLogDataProtoV0001_Point_Measure >&
      measures() const;
  // @@protoc_insertion_point(class_scope:Isis.ControlNetLogDataProtoV0001.Point)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedPtrField< ::Isis::ControlNetLogDataProtoV0001_Point_Measure > measures_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ControlNetLogDataProtoV0001_2eproto;
};// -------------------------------------------------------------------

class ControlNetLogDataProtoV0001 final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Isis.ControlNetLogDataProtoV0001) */ {
 public:
  inline ControlNetLogDataProtoV0001() : ControlNetLogDataProtoV0001(nullptr) {}
  ~ControlNetLogDataProtoV0001() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ControlNetLogDataProtoV0001(::google::protobuf::internal::ConstantInitialized);

  inline ControlNetLogDataProtoV0001(const ControlNetLogDataProtoV0001& from)
      : ControlNetLogDataProtoV0001(nullptr, from) {}
  ControlNetLogDataProtoV0001(ControlNetLogDataProtoV0001&& from) noexcept
    : ControlNetLogDataProtoV0001() {
    *this = ::std::move(from);
  }

  inline ControlNetLogDataProtoV0001& operator=(const ControlNetLogDataProtoV0001& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControlNetLogDataProtoV0001& operator=(ControlNetLogDataProtoV0001&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ControlNetLogDataProtoV0001& default_instance() {
    return *internal_default_instance();
  }
  static inline const ControlNetLogDataProtoV0001* internal_default_instance() {
    return reinterpret_cast<const ControlNetLogDataProtoV0001*>(
               &_ControlNetLogDataProtoV0001_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ControlNetLogDataProtoV0001& a, ControlNetLogDataProtoV0001& b) {
    a.Swap(&b);
  }
  inline void Swap(ControlNetLogDataProtoV0001* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControlNetLogDataProtoV0001* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ControlNetLogDataProtoV0001* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ControlNetLogDataProtoV0001>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ControlNetLogDataProtoV0001& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ControlNetLogDataProtoV0001& from) {
    ControlNetLogDataProtoV0001::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ControlNetLogDataProtoV0001* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Isis.ControlNetLogDataProtoV0001";
  }
  protected:
  explicit ControlNetLogDataProtoV0001(::google::protobuf::Arena* arena);
  ControlNetLogDataProtoV0001(::google::protobuf::Arena* arena, const ControlNetLogDataProtoV0001& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  using Point = ControlNetLogDataProtoV0001_Point;

  // accessors -------------------------------------------------------

  enum : int {
    kPointsFieldNumber = 1,
  };
  // repeated .Isis.ControlNetLogDataProtoV0001.Point points = 1;
  int points_size() const;
  private:
  int _internal_points_size() const;

  public:
  void clear_points() ;
  ::Isis::ControlNetLogDataProtoV0001_Point* mutable_points(int index);
  ::google::protobuf::RepeatedPtrField< ::Isis::ControlNetLogDataProtoV0001_Point >*
      mutable_points();
  private:
  const ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point>& _internal_points() const;
  ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point>* _internal_mutable_points();
  public:
  const ::Isis::ControlNetLogDataProtoV0001_Point& points(int index) const;
  ::Isis::ControlNetLogDataProtoV0001_Point* add_points();
  const ::google::protobuf::RepeatedPtrField< ::Isis::ControlNetLogDataProtoV0001_Point >&
      points() const;
  // @@protoc_insertion_point(class_scope:Isis.ControlNetLogDataProtoV0001)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedPtrField< ::Isis::ControlNetLogDataProtoV0001_Point > points_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ControlNetLogDataProtoV0001_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ControlNetLogDataProtoV0001_Point_Measure_DataEntry

// required int32 dataType = 2;
inline bool ControlNetLogDataProtoV0001_Point_Measure_DataEntry::has_datatype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ControlNetLogDataProtoV0001_Point_Measure_DataEntry::clear_datatype() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.datatype_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t ControlNetLogDataProtoV0001_Point_Measure_DataEntry::datatype() const {
  // @@protoc_insertion_point(field_get:Isis.ControlNetLogDataProtoV0001.Point.Measure.DataEntry.dataType)
  return _internal_datatype();
}
inline void ControlNetLogDataProtoV0001_Point_Measure_DataEntry::set_datatype(::int32_t value) {
  _internal_set_datatype(value);
  // @@protoc_insertion_point(field_set:Isis.ControlNetLogDataProtoV0001.Point.Measure.DataEntry.dataType)
}
inline ::int32_t ControlNetLogDataProtoV0001_Point_Measure_DataEntry::_internal_datatype() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.datatype_;
}
inline void ControlNetLogDataProtoV0001_Point_Measure_DataEntry::_internal_set_datatype(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.datatype_ = value;
}

// required double dataValue = 3;
inline bool ControlNetLogDataProtoV0001_Point_Measure_DataEntry::has_datavalue() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ControlNetLogDataProtoV0001_Point_Measure_DataEntry::clear_datavalue() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.datavalue_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline double ControlNetLogDataProtoV0001_Point_Measure_DataEntry::datavalue() const {
  // @@protoc_insertion_point(field_get:Isis.ControlNetLogDataProtoV0001.Point.Measure.DataEntry.dataValue)
  return _internal_datavalue();
}
inline void ControlNetLogDataProtoV0001_Point_Measure_DataEntry::set_datavalue(double value) {
  _internal_set_datavalue(value);
  // @@protoc_insertion_point(field_set:Isis.ControlNetLogDataProtoV0001.Point.Measure.DataEntry.dataValue)
}
inline double ControlNetLogDataProtoV0001_Point_Measure_DataEntry::_internal_datavalue() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.datavalue_;
}
inline void ControlNetLogDataProtoV0001_Point_Measure_DataEntry::_internal_set_datavalue(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.datavalue_ = value;
}

// -------------------------------------------------------------------

// ControlNetLogDataProtoV0001_Point_Measure

// repeated .Isis.ControlNetLogDataProtoV0001.Point.Measure.DataEntry loggedMeasureData = 2;
inline int ControlNetLogDataProtoV0001_Point_Measure::_internal_loggedmeasuredata_size() const {
  return _internal_loggedmeasuredata().size();
}
inline int ControlNetLogDataProtoV0001_Point_Measure::loggedmeasuredata_size() const {
  return _internal_loggedmeasuredata_size();
}
inline void ControlNetLogDataProtoV0001_Point_Measure::clear_loggedmeasuredata() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.loggedmeasuredata_.Clear();
}
inline ::Isis::ControlNetLogDataProtoV0001_Point_Measure_DataEntry* ControlNetLogDataProtoV0001_Point_Measure::mutable_loggedmeasuredata(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Isis.ControlNetLogDataProtoV0001.Point.Measure.loggedMeasureData)
  return _internal_mutable_loggedmeasuredata()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point_Measure_DataEntry>* ControlNetLogDataProtoV0001_Point_Measure::mutable_loggedmeasuredata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Isis.ControlNetLogDataProtoV0001.Point.Measure.loggedMeasureData)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_loggedmeasuredata();
}
inline const ::Isis::ControlNetLogDataProtoV0001_Point_Measure_DataEntry& ControlNetLogDataProtoV0001_Point_Measure::loggedmeasuredata(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Isis.ControlNetLogDataProtoV0001.Point.Measure.loggedMeasureData)
  return _internal_loggedmeasuredata().Get(index);
}
inline ::Isis::ControlNetLogDataProtoV0001_Point_Measure_DataEntry* ControlNetLogDataProtoV0001_Point_Measure::add_loggedmeasuredata() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::Isis::ControlNetLogDataProtoV0001_Point_Measure_DataEntry* _add = _internal_mutable_loggedmeasuredata()->Add();
  // @@protoc_insertion_point(field_add:Isis.ControlNetLogDataProtoV0001.Point.Measure.loggedMeasureData)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point_Measure_DataEntry>& ControlNetLogDataProtoV0001_Point_Measure::loggedmeasuredata() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Isis.ControlNetLogDataProtoV0001.Point.Measure.loggedMeasureData)
  return _internal_loggedmeasuredata();
}
inline const ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point_Measure_DataEntry>&
ControlNetLogDataProtoV0001_Point_Measure::_internal_loggedmeasuredata() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.loggedmeasuredata_;
}
inline ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point_Measure_DataEntry>*
ControlNetLogDataProtoV0001_Point_Measure::_internal_mutable_loggedmeasuredata() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.loggedmeasuredata_;
}

// -------------------------------------------------------------------

// ControlNetLogDataProtoV0001_Point

// repeated .Isis.ControlNetLogDataProtoV0001.Point.Measure measures = 2;
inline int ControlNetLogDataProtoV0001_Point::_internal_measures_size() const {
  return _internal_measures().size();
}
inline int ControlNetLogDataProtoV0001_Point::measures_size() const {
  return _internal_measures_size();
}
inline void ControlNetLogDataProtoV0001_Point::clear_measures() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.measures_.Clear();
}
inline ::Isis::ControlNetLogDataProtoV0001_Point_Measure* ControlNetLogDataProtoV0001_Point::mutable_measures(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Isis.ControlNetLogDataProtoV0001.Point.measures)
  return _internal_mutable_measures()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point_Measure>* ControlNetLogDataProtoV0001_Point::mutable_measures()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Isis.ControlNetLogDataProtoV0001.Point.measures)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_measures();
}
inline const ::Isis::ControlNetLogDataProtoV0001_Point_Measure& ControlNetLogDataProtoV0001_Point::measures(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Isis.ControlNetLogDataProtoV0001.Point.measures)
  return _internal_measures().Get(index);
}
inline ::Isis::ControlNetLogDataProtoV0001_Point_Measure* ControlNetLogDataProtoV0001_Point::add_measures() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::Isis::ControlNetLogDataProtoV0001_Point_Measure* _add = _internal_mutable_measures()->Add();
  // @@protoc_insertion_point(field_add:Isis.ControlNetLogDataProtoV0001.Point.measures)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point_Measure>& ControlNetLogDataProtoV0001_Point::measures() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Isis.ControlNetLogDataProtoV0001.Point.measures)
  return _internal_measures();
}
inline const ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point_Measure>&
ControlNetLogDataProtoV0001_Point::_internal_measures() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.measures_;
}
inline ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point_Measure>*
ControlNetLogDataProtoV0001_Point::_internal_mutable_measures() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.measures_;
}

// -------------------------------------------------------------------

// ControlNetLogDataProtoV0001

// repeated .Isis.ControlNetLogDataProtoV0001.Point points = 1;
inline int ControlNetLogDataProtoV0001::_internal_points_size() const {
  return _internal_points().size();
}
inline int ControlNetLogDataProtoV0001::points_size() const {
  return _internal_points_size();
}
inline void ControlNetLogDataProtoV0001::clear_points() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.points_.Clear();
}
inline ::Isis::ControlNetLogDataProtoV0001_Point* ControlNetLogDataProtoV0001::mutable_points(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Isis.ControlNetLogDataProtoV0001.points)
  return _internal_mutable_points()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point>* ControlNetLogDataProtoV0001::mutable_points()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Isis.ControlNetLogDataProtoV0001.points)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_points();
}
inline const ::Isis::ControlNetLogDataProtoV0001_Point& ControlNetLogDataProtoV0001::points(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Isis.ControlNetLogDataProtoV0001.points)
  return _internal_points().Get(index);
}
inline ::Isis::ControlNetLogDataProtoV0001_Point* ControlNetLogDataProtoV0001::add_points() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::Isis::ControlNetLogDataProtoV0001_Point* _add = _internal_mutable_points()->Add();
  // @@protoc_insertion_point(field_add:Isis.ControlNetLogDataProtoV0001.points)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point>& ControlNetLogDataProtoV0001::points() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Isis.ControlNetLogDataProtoV0001.points)
  return _internal_points();
}
inline const ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point>&
ControlNetLogDataProtoV0001::_internal_points() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.points_;
}
inline ::google::protobuf::RepeatedPtrField<::Isis::ControlNetLogDataProtoV0001_Point>*
ControlNetLogDataProtoV0001::_internal_mutable_points() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.points_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Isis


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ControlNetLogDataProtoV0001_2eproto_2epb_2eh
