// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ControlNetFileHeaderV0005.proto
// Protobuf C++ Version: 4.25.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_ControlNetFileHeaderV0005_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ControlNetFileHeaderV0005_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025002 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ControlNetFileHeaderV0005_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ControlNetFileHeaderV0005_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ControlNetFileHeaderV0005_2eproto;
namespace Isis {
class ControlNetFileHeaderV0005;
struct ControlNetFileHeaderV0005DefaultTypeInternal;
extern ControlNetFileHeaderV0005DefaultTypeInternal _ControlNetFileHeaderV0005_default_instance_;
}  // namespace Isis
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Isis {

// ===================================================================


// -------------------------------------------------------------------

class ControlNetFileHeaderV0005 final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Isis.ControlNetFileHeaderV0005) */ {
 public:
  inline ControlNetFileHeaderV0005() : ControlNetFileHeaderV0005(nullptr) {}
  ~ControlNetFileHeaderV0005() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ControlNetFileHeaderV0005(::google::protobuf::internal::ConstantInitialized);

  inline ControlNetFileHeaderV0005(const ControlNetFileHeaderV0005& from)
      : ControlNetFileHeaderV0005(nullptr, from) {}
  ControlNetFileHeaderV0005(ControlNetFileHeaderV0005&& from) noexcept
    : ControlNetFileHeaderV0005() {
    *this = ::std::move(from);
  }

  inline ControlNetFileHeaderV0005& operator=(const ControlNetFileHeaderV0005& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControlNetFileHeaderV0005& operator=(ControlNetFileHeaderV0005&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ControlNetFileHeaderV0005& default_instance() {
    return *internal_default_instance();
  }
  static inline const ControlNetFileHeaderV0005* internal_default_instance() {
    return reinterpret_cast<const ControlNetFileHeaderV0005*>(
               &_ControlNetFileHeaderV0005_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ControlNetFileHeaderV0005& a, ControlNetFileHeaderV0005& b) {
    a.Swap(&b);
  }
  inline void Swap(ControlNetFileHeaderV0005* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ControlNetFileHeaderV0005* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ControlNetFileHeaderV0005* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ControlNetFileHeaderV0005>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ControlNetFileHeaderV0005& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ControlNetFileHeaderV0005& from) {
    ControlNetFileHeaderV0005::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ControlNetFileHeaderV0005* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Isis.ControlNetFileHeaderV0005";
  }
  protected:
  explicit ControlNetFileHeaderV0005(::google::protobuf::Arena* arena);
  ControlNetFileHeaderV0005(::google::protobuf::Arena* arena, const ControlNetFileHeaderV0005& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTargetRadiiFieldNumber = 10,
    kNetworkIdFieldNumber = 1,
    kTargetNameFieldNumber = 2,
    kCreatedFieldNumber = 3,
    kLastModifiedFieldNumber = 4,
    kDescriptionFieldNumber = 5,
    kUserNameFieldNumber = 6,
    kNumPointsFieldNumber = 7,
  };
  // repeated double targetRadii = 10;
  int targetradii_size() const;
  private:
  int _internal_targetradii_size() const;

  public:
  void clear_targetradii() ;
  double targetradii(int index) const;
  void set_targetradii(int index, double value);
  void add_targetradii(double value);
  const ::google::protobuf::RepeatedField<double>& targetradii() const;
  ::google::protobuf::RepeatedField<double>* mutable_targetradii();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_targetradii() const;
  ::google::protobuf::RepeatedField<double>* _internal_mutable_targetradii();

  public:
  // required string networkId = 1;
  bool has_networkid() const;
  void clear_networkid() ;
  const std::string& networkid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_networkid(Arg_&& arg, Args_... args);
  std::string* mutable_networkid();
  PROTOBUF_NODISCARD std::string* release_networkid();
  void set_allocated_networkid(std::string* value);

  private:
  const std::string& _internal_networkid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_networkid(
      const std::string& value);
  std::string* _internal_mutable_networkid();

  public:
  // required string targetName = 2;
  bool has_targetname() const;
  void clear_targetname() ;
  const std::string& targetname() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_targetname(Arg_&& arg, Args_... args);
  std::string* mutable_targetname();
  PROTOBUF_NODISCARD std::string* release_targetname();
  void set_allocated_targetname(std::string* value);

  private:
  const std::string& _internal_targetname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_targetname(
      const std::string& value);
  std::string* _internal_mutable_targetname();

  public:
  // optional string created = 3;
  bool has_created() const;
  void clear_created() ;
  const std::string& created() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_created(Arg_&& arg, Args_... args);
  std::string* mutable_created();
  PROTOBUF_NODISCARD std::string* release_created();
  void set_allocated_created(std::string* value);

  private:
  const std::string& _internal_created() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_created(
      const std::string& value);
  std::string* _internal_mutable_created();

  public:
  // optional string lastModified = 4;
  bool has_lastmodified() const;
  void clear_lastmodified() ;
  const std::string& lastmodified() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_lastmodified(Arg_&& arg, Args_... args);
  std::string* mutable_lastmodified();
  PROTOBUF_NODISCARD std::string* release_lastmodified();
  void set_allocated_lastmodified(std::string* value);

  private:
  const std::string& _internal_lastmodified() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_lastmodified(
      const std::string& value);
  std::string* _internal_mutable_lastmodified();

  public:
  // optional string description = 5;
  bool has_description() const;
  void clear_description() ;
  const std::string& description() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_description(Arg_&& arg, Args_... args);
  std::string* mutable_description();
  PROTOBUF_NODISCARD std::string* release_description();
  void set_allocated_description(std::string* value);

  private:
  const std::string& _internal_description() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_description(
      const std::string& value);
  std::string* _internal_mutable_description();

  public:
  // optional string userName = 6;
  bool has_username() const;
  void clear_username() ;
  const std::string& username() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_username(Arg_&& arg, Args_... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* value);

  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(
      const std::string& value);
  std::string* _internal_mutable_username();

  public:
  // optional int32 numPoints = 7;
  bool has_numpoints() const;
  void clear_numpoints() ;
  ::int32_t numpoints() const;
  void set_numpoints(::int32_t value);

  private:
  ::int32_t _internal_numpoints() const;
  void _internal_set_numpoints(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Isis.ControlNetFileHeaderV0005)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 8, 0,
      104, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<double> targetradii_;
    ::google::protobuf::internal::ArenaStringPtr networkid_;
    ::google::protobuf::internal::ArenaStringPtr targetname_;
    ::google::protobuf::internal::ArenaStringPtr created_;
    ::google::protobuf::internal::ArenaStringPtr lastmodified_;
    ::google::protobuf::internal::ArenaStringPtr description_;
    ::google::protobuf::internal::ArenaStringPtr username_;
    ::int32_t numpoints_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ControlNetFileHeaderV0005_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ControlNetFileHeaderV0005

// required string networkId = 1;
inline bool ControlNetFileHeaderV0005::has_networkid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ControlNetFileHeaderV0005::clear_networkid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.networkid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ControlNetFileHeaderV0005::networkid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Isis.ControlNetFileHeaderV0005.networkId)
  return _internal_networkid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ControlNetFileHeaderV0005::set_networkid(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.networkid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Isis.ControlNetFileHeaderV0005.networkId)
}
inline std::string* ControlNetFileHeaderV0005::mutable_networkid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_networkid();
  // @@protoc_insertion_point(field_mutable:Isis.ControlNetFileHeaderV0005.networkId)
  return _s;
}
inline const std::string& ControlNetFileHeaderV0005::_internal_networkid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.networkid_.Get();
}
inline void ControlNetFileHeaderV0005::_internal_set_networkid(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.networkid_.Set(value, GetArena());
}
inline std::string* ControlNetFileHeaderV0005::_internal_mutable_networkid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.networkid_.Mutable( GetArena());
}
inline std::string* ControlNetFileHeaderV0005::release_networkid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Isis.ControlNetFileHeaderV0005.networkId)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.networkid_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.networkid_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ControlNetFileHeaderV0005::set_allocated_networkid(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.networkid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.networkid_.IsDefault()) {
          _impl_.networkid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Isis.ControlNetFileHeaderV0005.networkId)
}

// required string targetName = 2;
inline bool ControlNetFileHeaderV0005::has_targetname() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ControlNetFileHeaderV0005::clear_targetname() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.targetname_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& ControlNetFileHeaderV0005::targetname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Isis.ControlNetFileHeaderV0005.targetName)
  return _internal_targetname();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ControlNetFileHeaderV0005::set_targetname(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.targetname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Isis.ControlNetFileHeaderV0005.targetName)
}
inline std::string* ControlNetFileHeaderV0005::mutable_targetname() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_targetname();
  // @@protoc_insertion_point(field_mutable:Isis.ControlNetFileHeaderV0005.targetName)
  return _s;
}
inline const std::string& ControlNetFileHeaderV0005::_internal_targetname() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.targetname_.Get();
}
inline void ControlNetFileHeaderV0005::_internal_set_targetname(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.targetname_.Set(value, GetArena());
}
inline std::string* ControlNetFileHeaderV0005::_internal_mutable_targetname() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.targetname_.Mutable( GetArena());
}
inline std::string* ControlNetFileHeaderV0005::release_targetname() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Isis.ControlNetFileHeaderV0005.targetName)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.targetname_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.targetname_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ControlNetFileHeaderV0005::set_allocated_targetname(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.targetname_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.targetname_.IsDefault()) {
          _impl_.targetname_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Isis.ControlNetFileHeaderV0005.targetName)
}

// optional string created = 3;
inline bool ControlNetFileHeaderV0005::has_created() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void ControlNetFileHeaderV0005::clear_created() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.created_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& ControlNetFileHeaderV0005::created() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Isis.ControlNetFileHeaderV0005.created)
  return _internal_created();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ControlNetFileHeaderV0005::set_created(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.created_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Isis.ControlNetFileHeaderV0005.created)
}
inline std::string* ControlNetFileHeaderV0005::mutable_created() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_created();
  // @@protoc_insertion_point(field_mutable:Isis.ControlNetFileHeaderV0005.created)
  return _s;
}
inline const std::string& ControlNetFileHeaderV0005::_internal_created() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.created_.Get();
}
inline void ControlNetFileHeaderV0005::_internal_set_created(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.created_.Set(value, GetArena());
}
inline std::string* ControlNetFileHeaderV0005::_internal_mutable_created() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.created_.Mutable( GetArena());
}
inline std::string* ControlNetFileHeaderV0005::release_created() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Isis.ControlNetFileHeaderV0005.created)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.created_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.created_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ControlNetFileHeaderV0005::set_allocated_created(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.created_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.created_.IsDefault()) {
          _impl_.created_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Isis.ControlNetFileHeaderV0005.created)
}

// optional string lastModified = 4;
inline bool ControlNetFileHeaderV0005::has_lastmodified() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void ControlNetFileHeaderV0005::clear_lastmodified() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.lastmodified_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& ControlNetFileHeaderV0005::lastmodified() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Isis.ControlNetFileHeaderV0005.lastModified)
  return _internal_lastmodified();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ControlNetFileHeaderV0005::set_lastmodified(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.lastmodified_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Isis.ControlNetFileHeaderV0005.lastModified)
}
inline std::string* ControlNetFileHeaderV0005::mutable_lastmodified() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_lastmodified();
  // @@protoc_insertion_point(field_mutable:Isis.ControlNetFileHeaderV0005.lastModified)
  return _s;
}
inline const std::string& ControlNetFileHeaderV0005::_internal_lastmodified() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.lastmodified_.Get();
}
inline void ControlNetFileHeaderV0005::_internal_set_lastmodified(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.lastmodified_.Set(value, GetArena());
}
inline std::string* ControlNetFileHeaderV0005::_internal_mutable_lastmodified() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.lastmodified_.Mutable( GetArena());
}
inline std::string* ControlNetFileHeaderV0005::release_lastmodified() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Isis.ControlNetFileHeaderV0005.lastModified)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.lastmodified_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.lastmodified_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ControlNetFileHeaderV0005::set_allocated_lastmodified(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.lastmodified_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.lastmodified_.IsDefault()) {
          _impl_.lastmodified_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Isis.ControlNetFileHeaderV0005.lastModified)
}

// optional string description = 5;
inline bool ControlNetFileHeaderV0005::has_description() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void ControlNetFileHeaderV0005::clear_description() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.description_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const std::string& ControlNetFileHeaderV0005::description() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Isis.ControlNetFileHeaderV0005.description)
  return _internal_description();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ControlNetFileHeaderV0005::set_description(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.description_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Isis.ControlNetFileHeaderV0005.description)
}
inline std::string* ControlNetFileHeaderV0005::mutable_description() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_description();
  // @@protoc_insertion_point(field_mutable:Isis.ControlNetFileHeaderV0005.description)
  return _s;
}
inline const std::string& ControlNetFileHeaderV0005::_internal_description() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.description_.Get();
}
inline void ControlNetFileHeaderV0005::_internal_set_description(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.description_.Set(value, GetArena());
}
inline std::string* ControlNetFileHeaderV0005::_internal_mutable_description() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000010u;
  return _impl_.description_.Mutable( GetArena());
}
inline std::string* ControlNetFileHeaderV0005::release_description() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Isis.ControlNetFileHeaderV0005.description)
  if ((_impl_._has_bits_[0] & 0x00000010u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000010u;
  auto* released = _impl_.description_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.description_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ControlNetFileHeaderV0005::set_allocated_description(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.description_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.description_.IsDefault()) {
          _impl_.description_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Isis.ControlNetFileHeaderV0005.description)
}

// optional string userName = 6;
inline bool ControlNetFileHeaderV0005::has_username() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void ControlNetFileHeaderV0005::clear_username() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.username_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline const std::string& ControlNetFileHeaderV0005::username() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Isis.ControlNetFileHeaderV0005.userName)
  return _internal_username();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ControlNetFileHeaderV0005::set_username(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.username_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Isis.ControlNetFileHeaderV0005.userName)
}
inline std::string* ControlNetFileHeaderV0005::mutable_username() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:Isis.ControlNetFileHeaderV0005.userName)
  return _s;
}
inline const std::string& ControlNetFileHeaderV0005::_internal_username() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.username_.Get();
}
inline void ControlNetFileHeaderV0005::_internal_set_username(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.username_.Set(value, GetArena());
}
inline std::string* ControlNetFileHeaderV0005::_internal_mutable_username() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000020u;
  return _impl_.username_.Mutable( GetArena());
}
inline std::string* ControlNetFileHeaderV0005::release_username() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:Isis.ControlNetFileHeaderV0005.userName)
  if ((_impl_._has_bits_[0] & 0x00000020u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000020u;
  auto* released = _impl_.username_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.username_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ControlNetFileHeaderV0005::set_allocated_username(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  _impl_.username_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.username_.IsDefault()) {
          _impl_.username_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Isis.ControlNetFileHeaderV0005.userName)
}

// optional int32 numPoints = 7;
inline bool ControlNetFileHeaderV0005::has_numpoints() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void ControlNetFileHeaderV0005::clear_numpoints() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.numpoints_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::int32_t ControlNetFileHeaderV0005::numpoints() const {
  // @@protoc_insertion_point(field_get:Isis.ControlNetFileHeaderV0005.numPoints)
  return _internal_numpoints();
}
inline void ControlNetFileHeaderV0005::set_numpoints(::int32_t value) {
  _internal_set_numpoints(value);
  // @@protoc_insertion_point(field_set:Isis.ControlNetFileHeaderV0005.numPoints)
}
inline ::int32_t ControlNetFileHeaderV0005::_internal_numpoints() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.numpoints_;
}
inline void ControlNetFileHeaderV0005::_internal_set_numpoints(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.numpoints_ = value;
}

// repeated double targetRadii = 10;
inline int ControlNetFileHeaderV0005::_internal_targetradii_size() const {
  return _internal_targetradii().size();
}
inline int ControlNetFileHeaderV0005::targetradii_size() const {
  return _internal_targetradii_size();
}
inline void ControlNetFileHeaderV0005::clear_targetradii() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.targetradii_.Clear();
}
inline double ControlNetFileHeaderV0005::targetradii(int index) const {
  // @@protoc_insertion_point(field_get:Isis.ControlNetFileHeaderV0005.targetRadii)
  return _internal_targetradii().Get(index);
}
inline void ControlNetFileHeaderV0005::set_targetradii(int index, double value) {
  _internal_mutable_targetradii()->Set(index, value);
  // @@protoc_insertion_point(field_set:Isis.ControlNetFileHeaderV0005.targetRadii)
}
inline void ControlNetFileHeaderV0005::add_targetradii(double value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_targetradii()->Add(value);
  // @@protoc_insertion_point(field_add:Isis.ControlNetFileHeaderV0005.targetRadii)
}
inline const ::google::protobuf::RepeatedField<double>& ControlNetFileHeaderV0005::targetradii() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Isis.ControlNetFileHeaderV0005.targetRadii)
  return _internal_targetradii();
}
inline ::google::protobuf::RepeatedField<double>* ControlNetFileHeaderV0005::mutable_targetradii()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Isis.ControlNetFileHeaderV0005.targetRadii)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_targetradii();
}
inline const ::google::protobuf::RepeatedField<double>& ControlNetFileHeaderV0005::_internal_targetradii()
    const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.targetradii_;
}
inline ::google::protobuf::RepeatedField<double>* ControlNetFileHeaderV0005::_internal_mutable_targetradii() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.targetradii_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Isis


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ControlNetFileHeaderV0005_2eproto_2epb_2eh
