#!/usr/bin/env bash

set -euo pipefail

# Deprecated: this script is intended to be used for generating preserved outputs for the two external-data DOM matching E2E tests, but it is not integrated into the CI and there is a risk of the outputs getting stale and not being updated when changes are made to the codebase. It may be better to remove this script and the preserved outputs, and instead rely on the test logs and artifacts generated by the CI for debugging test failures, to avoid confusion about whether the preserved outputs are up to date or not. If there is still a need to have preserved outputs for these tests, it would be important to ensure that they are regularly updated and maintained, and that it is clear to developers when and how to update them.
# use this default path for preserved E2E outputs if the environment variable is not set, to allow preserving outputs without needing to configure the environment variable, but still allow overriding the root path via the environment variable if needed
DEFAULT_PRESERVED_E2E_OUTPUT_ROOT_ENV = "/media/gengxun/Elements/data/lro/test_controlnet_python/e2e_outputs"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PYTHON_EXECUTABLE="${PYTHON_EXECUTABLE:-/home/gengxun/miniconda3/envs/asp360_new/bin/python}"
OUTPUT_ROOT="${ISIS_PYBIND_E2E_OUTPUT_ROOT:-${DEFAULT_PRESERVED_E2E_OUTPUT_ROOT_ENV}"

usage() {
	cat <<'EOF'
Usage: scripts/controlnet_construct_e2e_unit_test_output.sh

Runs the two external-data DOM matching E2E tests while preserving outputs under
build/test_artifacts/controlnet_e2e by default.

Options:
  -h, --help                      Show this help message.

Environment overrides:
  PYTHON_EXECUTABLE               Python interpreter to use.
  ISIS_PYBIND_E2E_OUTPUT_ROOT     Root directory where preserved E2E outputs are written.
EOF
}

while [[ $# -gt 0 ]]; do
	case "$1" in
		-h|--help)
			usage
			exit 0
			;;
		*)
			echo "Unknown argument: $1" >&2
			usage >&2
			exit 2
			;;
	esac
	shift
done

export ISIS_PYBIND_E2E_OUTPUT_ROOT="${OUTPUT_ROOT}"


echo "Using Python: ${PYTHON_EXECUTABLE}"
echo "Preserved E2E output root: ${ISIS_PYBIND_E2E_OUTPUT_ROOT}"

"${PYTHON_EXECUTABLE}" -m unittest tests.unitTest.controlnet_construct_e2e_unit_test.ControlNetConstructE2eUnitTest.test_lro_dom_matching_pipeline_end_to_end_for_all_overlap_pairs -v
"${PYTHON_EXECUTABLE}" -m unittest tests.unitTest.controlnet_construct_e2e_unit_test.ControlNetConstructE2eUnitTest.test_lro_dom_matching_cli_batch_pipeline_for_all_overlap_pairs -v