Isis Developer Reference: Isis::ProjectItem Class Reference
Isis::ProjectItem Class Reference
Represents an item of a ProjectItemModel in Qt's model-view framework.
#include <ProjectItem.h>
Public Member Functions
ProjectItem ()
Constructs an item without children, a parent, or a model.
ProjectItem (ProjectItem *item)
Contructs a copy of another item.
ProjectItem (BundleResults bundleResults)
Constructs an item from a BundleResults.
ProjectItem (BundleSettingsQsp bundleSettings)
Constructs an item from a BundleSettings.
ProjectItem (BundleSolutionInfo *bundleSolutionInfo)
Constructs an item from a BundleSolutionInfo.
ProjectItem (Control *control)
Constructs an item from a Control.
ProjectItem (ControlList *controlList)
Constructs an item from a ControlList.
ProjectItem (QList< ControlList * > controls)
Constructs an item from a list of ControlList.
ProjectItem (CorrelationMatrix correlationMatrix)
Constructs an item from a CorrelationMatrix.
ProjectItem (Image *image)
Constructs an item from an Image.
ProjectItem (ImageList *imageList)
Constructs an item from an ImageList.
ProjectItem (QList< ImageList * > images)
Constructs an item from a list of ImageList.
ProjectItem (Shape *shape)
Constructs an item from an Shape.
ProjectItem (ShapeList *shapeList)
Constructs an item from an ShapeList.
ProjectItem (QList< ShapeList * > shapes)
Constructs an item from a list of ShapeList.
ProjectItem (GuiCameraQsp guiCamera)
Constructs an item from a GuiCameraQsp.
ProjectItem (GuiCameraList *guiCameraList)
Constructs an item from a GuiCameraList.
ProjectItem (Project *project)
Constructs an item from a Project.
ProjectItem (QList< BundleSolutionInfo * > results)
Constructs an item from a list of BundleSolutionInfo.
ProjectItem (TargetBodyQsp targetBody)
Constructs an item from a TargetBodyQsp.
ProjectItem (TargetBodyList *targetBodyList)
Constructs an item from a TargetBodyList.
ProjectItem (QList< TemplateList * > templates)
Constructs an item from a list of TemplateList.
ProjectItem (Template *newTemplate)
Constructs an item from a Template.
ProjectItem (TemplateList *templateList)
Constructs an item from an TemplateList.
ProjectItem (FileItemQsp filename, QString treeText, QIcon icon)
Constructs an item representing a file in the filesystem.
ProjectItem (FileItemQsp filename, QString treeText, QString toolTipText, QIcon icon)
Constructs an item representing a file in the filesystem.
~ProjectItem ()
Destructs a ProjectItem.
BundleResults bundleResults () const
Returns the BundleResults stored in the data of the item.
BundleSettingsQsp bundleSettings () const
Returns the BundleSettings stored in the data of the item.
BundleSolutionInfo * bundleSolutionInfo () const
Returns the BundleSolutionInfo stored in the data of the item.
Control * control () const
Returns the Control stored in the data of the item.
ControlList * controlList () const
Returns the ControlList stored in the data of the item.
CorrelationMatrix correlationMatrix () const
Returns the CorrelationMatrix stored the item.
Image * image () const
Returns the Image stored in the data of the item.
ImageList * imageList () const
Returns the ImageList stored in the data of the item.
Shape * shape () const
Returns the Shape stored in the data of the item.
ShapeList * shapeList () const
Returns the ShapeList stored in the data of the item.
Project * project () const
Returns the Project stored in the data of the item.
GuiCameraQsp guiCamera () const
Returns the GuiCameraQsp stored in the data of the item.
TargetBodyQsp targetBody () const
Returns the TargetBodyQsp stored in the data of the item.
Template * getTemplate () const
Returns the Template stored in the data of the item.
TemplateList * templateList () const
Returns the TemplateList stored in the data of the item.
FileItemQsp fileItem () const
Returns the FileItemQsp stored in the data of the item.
bool isBundleResults () const
Returns true if BundleResults are stored in the data of the item.
bool isBundleSettings () const
Returns true if BundleSettings are stored in the data of the item.
bool isBundleSolutionInfo () const
Returns true if a BundleSolutionInfo is stored in the data of the item.
bool isControl () const
Returns true if a Control is stored in the data of the item.
bool isControlList () const
Returns true if a ControlList is stored in the data of the item.
bool isCorrelationMatrix () const
Returns true if a CorrelationMatrix is stored in the data of the item.
bool isImage () const
Returns true if an Image is stored in the data of the item.
bool isImageList () const
Returns true if an ImageList is stored in the data of the item.
bool isShape () const
Returns true if an Shape is stored in the data of the item.
bool isShapeList () const
Returns true if an ShapeList is stored in the data of the item.
bool isProject () const
Returns true if a Project is stored in the data of the item.
bool isGuiCamera () const
Returns true if a GuiCameraQsp is stored in the data of the item.
bool isTargetBody () const
Returns true if a TargetBodyQsp is stored in the data of the item.
bool isFileItem () const
Returns true if a FileItemQsp is stored in the data of the item.
bool isTemplate () const
void setProjectItem (ProjectItem *item)
Sets the text, icon, and data to those of another item.
void setBundleResults (BundleResults bundleResults)
Sets the text, icon, and data corresponding to BundleResults.
void setBundleSettings (BundleSettingsQsp bundleSettings)
Sets the text, icon, and data corresponding to BundleSettings.
void setBundleSolutionInfo (BundleSolutionInfo *bundleSolutionInfo)
Sets the text, icon, and data corresponding to a BundleSolutionInfo.
void setControl (Control *control)
Sets the text, icon, and data corresponding to a Control.
void setControlList (ControlList *controlList)
Sets the text, icon, and data corresponding to a ControlList.
void setControls ()
Sets the text, icon, and data corresponding to a list of ControlList.
void setCorrelationMatrix (CorrelationMatrix correlationMatrix)
Sets the text, icon, and data corresponding to a CorrelationMatrix.
void setImage (Image *image)
Sets the text, icon, and data corresponding to an Image.
void setImageList (ImageList *imageList)
Sets the text, icon, and data corresponding to an ImageList.
void setImages ()
Sets the text, icon, and data corresponding to a list of ImageList.
void setShape (Shape *shape)
Sets the text, icon, and data corresponding to an Shape.
void setShapeList (ShapeList *shapeList)
Sets the text, icon, and data corresponding to an ShapeList.
void setShapes ()
Sets the text, icon, and data corresponding to a list of ShapeList.
void setProject (Project *project)
Sets the text, icon, and data corresponding to a Project.
void setResults ()
Sets the text, icon, and data corresponding to a list of Results.
void setGuiCamera (GuiCameraQsp guiCamera)
Sets the text, icon, and data corresponding to a GuiCameraQsp.
void setGuiCameraList ()
Sets the text, icon, and data corresponding to a GuiCameraQsp.
void setSpacecraft ()
Sets the text, icon, and data corresponding to SpaceCraft.
void setTargetBody (TargetBodyQsp targetBody)
Sets the text, icon, and data corresponding to a TargetBodyQsp.
void setTargetBodyList ()
Sets the text, icon, and data corresponding to a TargetBodyList.
void setTemplate (Template *newTemplate)
Sets the text, icon, and data corresponding to a Template.
void setTemplates ()
Sets the text, icon, and data corresponding to a list of TemplateList.
void setTemplateList (TemplateList *templateList)
Sets the text, icon, and data corresponding to an TemplateList.
ProjectItem * findItemData (const QVariant &value, int role=Qt::UserRole+1)
Finds and returns the first item in the model that contains the data in the role.
void appendRow (ProjectItem *item)
Appends an item to the children of this item.
ProjectItem * child (int row) const
Returns the child item at a given row.
void insertRow (int row, ProjectItem *item)
Inserts an item to the children of this item at the row.
ProjectItemModel * model () const
Returns the ProjectItemModel associated with this item.
ProjectItem * parent () const
Returns the parent item of this item.
void setChild (int row, ProjectItem *item)
Sets the child at the given row to an item.
ProjectItem * takeChild (int row)
Removes the child item at the given row and returns the removed item.
void setTextColor (Qt::GlobalColor color)
Detailed Description
Represents an item of a ProjectItemModel in Qt's model-view framework.
Items are stored in a tree structure. A ProjectItem directly stores the Data it corresponds to as well as other display information.
A ProjectItem may have a parent item and children items. An item can add another item as a child using the appendRow() or insertRow() methods on the parent item. Top level items in the model should be added using the corresponding methods in the model. If an item already has a parent or is already added to a model, it must be removed from the parent using the takeChild() method on the old parent item, or the takeItem() method on the model, before it is added to a new parent or model.
A ProjectItem stores text, an icon, and data. These values can be set using the setText(), setIcon(), and setData() methods. The data must be converted to a QVariant before being stored using setData(). There are various convinence methods for setting and accessing data. For example, the setImage() method will set the text, icon, and data appropriately given an Image. Also, the image() method will return the Image if one is stored in the data, or a null pointer if one is not.
ProjectItem does not inherit from QObject. The model associated with the ProjectItem should be used to utilize signals and slots. When a ProjectItem is deleted it deletes all of its children. Top level items are deleted by the model associated with them. To delete an item manually it must first be removed from its parent item or its model with the takeItem() method.
Any type of data that can be converted to a QVariant can be stored in a ProjectItem. If the ProjectItem cannot store the data it represents directly, then the data() method can be overridden in a subclass to access the data where it is stored.
Item selections are handled by the model associated with the item.
Image *image = new Image("example.cub");
ProjectItemModel *model = new ProjectItemModel();
ProjectItem *item = new ProjectItem(project);
model->appendRow(item);
Author
2015-10-21 Jeffrey Covington
Constructor & Destructor Documentation
ProjectItem() [1/26]
Isis::ProjectItem::ProjectItem ()
Constructs an item without children, a parent, or a model.
References setTextColor().
Referenced by ProjectItem(), and setTemplates().
ProjectItem() [2/26]
Isis::ProjectItem::ProjectItem (ProjectItem * item) explicit
Contructs a copy of another item.
The copy will have the same text, icon, and data, and copies of the children. The copy will not have a parent or a model.
Parameters
[in] item (ProjectItem *) The item to copy.
References appendRow(), child(), ProjectItem(), setProjectItem(), and setTextColor().
ProjectItem() [3/26]
Isis::ProjectItem::ProjectItem (BundleResults bundleResults)
Constructs an item from a BundleResults.
Parameters
[in] bundleResults (BundleResults) The BundleResults to construct from.
References bundleResults(), setBundleResults(), and setTextColor().
ProjectItem() [4/26]
Isis::ProjectItem::ProjectItem (BundleSettingsQsp bundleSettings)
Constructs an item from a BundleSettings.
Parameters
[in] bundleSettings (BundleSettingsQsp) The BundleSettings to construct from.
References bundleSettings(), setBundleSettings(), and setTextColor().
ProjectItem() [5/26]
Isis::ProjectItem::ProjectItem (BundleSolutionInfo * bundleSolutionInfo)
Constructs an item from a BundleSolutionInfo.
Parameters
[in] bundleSolutionInfo (BundleSolutionInfo *) The BundleSolutionInfo to construct from.
References Isis::BundleSolutionInfo::adjustedImages(), appendRow(), Isis::BundleSolutionInfo::bundleResults(), Isis::BundleSolutionInfo::bundleSettings(), bundleSolutionInfo(), Isis::BundleSolutionInfo::control(), ProjectItem(), setBundleSolutionInfo(), and setTextColor().
ProjectItem() [6/26]
Isis::ProjectItem::ProjectItem (Control * control)
Constructs an item from a Control.
Parameters
[in] control (Control *) The Control to construct from.
References control(), setControl(), and setTextColor().
ProjectItem() [7/26]
Isis::ProjectItem::ProjectItem (ControlList * controlList)
Constructs an item from a ControlList.
Parameters
[in] controlList (ControlList *) The ControlList to construct from.
References appendRow(), control(), controlList(), ProjectItem(), setControlList(), and setTextColor().
ProjectItem() [8/26]
Isis::ProjectItem::ProjectItem (QList< ControlList * > controls)
Constructs an item from a list of ControlList.
Parameters
[in] controls (QList<ControlList *>) The list to construct from.
References appendRow(), controlList(), ProjectItem(), setControls(), and setTextColor().
ProjectItem() [9/26]
Isis::ProjectItem::ProjectItem (CorrelationMatrix correlationMatrix)
Constructs an item from a CorrelationMatrix.
Parameters
[in] correlationMatrix (CorrelationMatrix) The CorrelationMatrix to construct from.
References correlationMatrix(), setCorrelationMatrix(), and setTextColor().
ProjectItem() [10/26]
Isis::ProjectItem::ProjectItem (Image * image)
Constructs an item from an Image.
Parameters
[in] image (Image *) The Image to construct from.
References image(), setImage(), and setTextColor().
ProjectItem() [11/26]
Isis::ProjectItem::ProjectItem (ImageList * imageList)
Constructs an item from an ImageList.
Parameters
[in] imageList (ImageList *) The ImageList to construct from.
References appendRow(), image(), imageList(), ProjectItem(), setImageList(), and setTextColor().
ProjectItem() [12/26]
Isis::ProjectItem::ProjectItem (QList< ImageList * > images)
Constructs an item from a list of ImageList.
Parameters
[in] images (QList<ImageList *>) The list to construct from.
References appendRow(), imageList(), ProjectItem(), setImages(), and setTextColor().
ProjectItem() [13/26]
Isis::ProjectItem::ProjectItem (Shape * shape)
Constructs an item from an Shape.
Parameters
[in] shape (Shape *) The Shape to construct from.
References setShape(), setTextColor(), and shape().
ProjectItem() [14/26]
Isis::ProjectItem::ProjectItem (ShapeList * shapeList)
Constructs an item from an ShapeList.
Parameters
[in] shapeList (ShapeList *) The ShapeList to construct from.
References appendRow(), ProjectItem(), setShapeList(), setTextColor(), shape(), and shapeList().
ProjectItem() [15/26]
Isis::ProjectItem::ProjectItem (QList< ShapeList * > shapes)
Constructs an item from a list of ShapeList.
Parameters
[in] shapes (QList<ShapeList *>) The list to construct from.
References appendRow(), ProjectItem(), setShapes(), setTextColor(), and shapeList().
ProjectItem() [16/26]
Isis::ProjectItem::ProjectItem (GuiCameraQsp guiCamera)
Constructs an item from a GuiCameraQsp.
Parameters
[in] guiCamera (GuiCameraQsp) The camera to construct from.
References guiCamera(), setGuiCamera(), and setTextColor().
ProjectItem() [17/26]
Isis::ProjectItem::ProjectItem (GuiCameraList * guiCameraList)
Constructs an item from a GuiCameraList.
Parameters
[in] guiCameraList (GuiCameraList *) The list of cameras to construct from.
References appendRow(), guiCamera(), ProjectItem(), setGuiCameraList(), and setTextColor().
ProjectItem() [18/26]
Isis::ProjectItem::ProjectItem (Project * project)
Constructs an item from a Project.
Parameters
[in] project (Project *) The Project to construct from.
References appendRow(), Isis::Project::bundleSolutionInfo(), Isis::Project::controls(), Isis::Project::images(), project(), ProjectItem(), setGuiCameraList(), setProject(), setSpacecraft(), setTargetBodyList(), setTextColor(), Isis::Project::shapes(), and Isis::Project::templates().
ProjectItem() [19/26]
Isis::ProjectItem::ProjectItem (QList< BundleSolutionInfo * > results)
Constructs an item from a list of BundleSolutionInfo.
Parameters
[in] results (QList<BundleSolutionInfo *>) The list to construct from.
References appendRow(), bundleSolutionInfo(), ProjectItem(), setResults(), and setTextColor().
ProjectItem() [20/26]
Isis::ProjectItem::ProjectItem (TargetBodyQsp targetBody)
Constructs an item from a TargetBodyQsp.
Parameters
[in] targetBody (TargetBodyQsp) The target body to construct from.
References setTargetBody(), setTextColor(), and targetBody().
ProjectItem() [21/26]
Isis::ProjectItem::ProjectItem (TargetBodyList * targetBodyList)
Constructs an item from a TargetBodyList.
Parameters
[in] targetBodyList (TargetBodyList *) The list to construct from.
References appendRow(), ProjectItem(), setTargetBodyList(), setTextColor(), and targetBody().
ProjectItem() [22/26]
Isis::ProjectItem::ProjectItem (QList< TemplateList * > templates)
Constructs an item from a list of TemplateList.
Parameters
[in] shapes (QList<TemplateList *>) The list to construct from.
References appendRow(), ProjectItem(), setTemplates(), setTextColor(), and templateList().
ProjectItem() [23/26]
Isis::ProjectItem::ProjectItem (Template * newTemplate)
Constructs an item from a Template.
Parameters
[in] template (Template *) The Template to construct from.
References setTemplate(), and setTextColor().
ProjectItem() [24/26]
Isis::ProjectItem::ProjectItem (TemplateList * templateList)
Constructs an item from an TemplateList.
Parameters
[in] templateList (TemplateList *) The TemplateList to construct from.
References appendRow(), ProjectItem(), setTemplateList(), setTextColor(), and templateList().
ProjectItem() [25/26]
Isis::ProjectItem::ProjectItem (FileItemQsp filename, QString treeText, QIcon icon)
Constructs an item representing a file in the filesystem.
Parameters
[in] filename The full path to the file in the filesystem
[in] treetext The name displayed in the project tree
[in] filename A icon to display next to the treetext
References setTextColor().
ProjectItem() [26/26]
Isis::ProjectItem::ProjectItem (FileItemQsp filename, QString treeText, QString toolTipText, QIcon icon)
Constructs an item representing a file in the filesystem.
Parameters
[in] filename The full path to the file in the filesystem
[in] treetext The name displayed in the project tree
[in] filename A icon to display next to the treetext
References setTextColor().
~ProjectItem()
Isis::ProjectItem::~ProjectItem ()
Destructs a ProjectItem.
Member Function Documentation
appendRow()
void Isis::ProjectItem::appendRow (ProjectItem * item)
Appends an item to the children of this item.
Parameters
[in] item (ProjectItem *) The item to append.
References setTextColor().
Referenced by Isis::ProjectItemProxyModel::addChild(), ProjectItem(), and setTemplates().
bundleResults()
BundleResults Isis::ProjectItem::bundleResults () const
Returns the BundleResults stored in the data of the item.
Returns
BundleResults The BundleResults of the item.
Referenced by ProjectItem(), and setBundleResults().
bundleSettings()
BundleSettingsQsp Isis::ProjectItem::bundleSettings () const
Returns the BundleSettings stored in the data of the item.
Returns
BundleSettingsQsp The BundleSettings of the item.
Referenced by ProjectItem(), and setBundleSettings().
bundleSolutionInfo()
BundleSolutionInfo * Isis::ProjectItem::bundleSolutionInfo () const
Returns the BundleSolutionInfo stored in the data of the item.
Returns
BundleSolutionInfo* The BundleSolutionInfo of the item.
Referenced by ProjectItem(), setBundleSolutionInfo(), and Isis::ProjectItemModel::setData().
child()
ProjectItem * Isis::ProjectItem::child (int row) const
Returns the child item at a given row.
Parameters
[in] row (int) The row.
Returns
ProjectItem* The child item.
Referenced by Isis::ProjectItemProxyModel::addItem(), Isis::ProjectItemModel::clean(), findItemData(), Isis::JigsawSetupDialog::JigsawSetupDialog(), ProjectItem(), Isis::ProjectItemModel::removeItem(), Isis::ProjectItemModel::selectedBOSSImages(), and Isis::JigsawSetupDialog::treeViewSelectionChanged().
control()
Control * Isis::ProjectItem::control () const
Returns the Control stored in the data of the item.
Returns
Control* The Control of the item.
Referenced by Isis::WorkOrder::isExecutable(), ProjectItem(), Isis::Project::setActiveControl(), setControl(), and Isis::WorkOrder::setData().
controlList()
ControlList * Isis::ProjectItem::controlList () const
Returns the ControlList stored in the data of the item.
Returns
ControlList* The ControlList of the item.
Referenced by ProjectItem(), setControlList(), Isis::ProjectItemModel::setData(), and Isis::WorkOrder::setData().
correlationMatrix()
CorrelationMatrix Isis::ProjectItem::correlationMatrix () const
Returns the CorrelationMatrix stored the item.
Returns
CorrelationMatrix* The CorrelationMatrix of the item.
Referenced by Isis::WorkOrder::isExecutable(), ProjectItem(), setCorrelationMatrix(), and Isis::WorkOrder::setData().
fileItem()
FileItemQsp Isis::ProjectItem::fileItem () const
Returns the FileItemQsp stored in the data of the item.
Returns
FileItemQsp The filename stored in the item.
Referenced by Isis::WorkOrder::isExecutable(), and Isis::WorkOrder::setData().
findItemData()
ProjectItem * Isis::ProjectItem::findItemData (const QVariant & value, int role = Qt::UserRole+1)
Finds and returns the first item in the model that contains the data in the role.
Parameters
[in] value (const QVariant &) The data.
[in] role (int) The role.
Returns
ProjectItem* The found item.
References child(), and findItemData().
Referenced by Isis::ProjectItemModel::findItemData(), and findItemData().
getTemplate()
Template * Isis::ProjectItem::getTemplate () const
Returns the Template stored in the data of the item.
Returns
(Template *) The Template of the item.
Referenced by Isis::WorkOrder::isExecutable(), Isis::TemplateEditViewWorkOrder::isExecutable(), and Isis::WorkOrder::setData().
guiCamera()
GuiCameraQsp Isis::ProjectItem::guiCamera () const
Returns the GuiCameraQsp stored in the data of the item.
Returns
GuiCameraQsp The camera stored in the item.
Referenced by Isis::WorkOrder::isExecutable(), ProjectItem(), Isis::WorkOrder::setData(), and setGuiCamera().
image()
Image * Isis::ProjectItem::image () const
Returns the Image stored in the data of the item.
Returns
Image* The Image of the item.
Referenced by Isis::RemoveImagesWorkOrder::execute(), Isis::WorkOrder::isExecutable(), Isis::JigsawSetupDialog::JigsawSetupDialog(), Isis::ProjectItemModel::onSelectionChanged(), ProjectItem(), Isis::CubeDnView::save(), Isis::WorkOrder::setData(), setImage(), Isis::RemoveImagesWorkOrder::setupExecution(), and Isis::JigsawSetupDialog::treeViewSelectionChanged().
imageList()
ImageList * Isis::ProjectItem::imageList () const
Returns the ImageList stored in the data of the item.
Returns
ImageList* The ImageList of the item.
Referenced by Isis::RemoveImagesWorkOrder::execute(), Isis::WorkOrder::isExecutable(), ProjectItem(), Isis::Project::setActiveImageList(), Isis::ProjectItemModel::setData(), Isis::WorkOrder::setData(), setImageList(), and Isis::RemoveImagesWorkOrder::setupExecution().
insertRow()
void Isis::ProjectItem::insertRow (int row, ProjectItem * item)
Inserts an item to the children of this item at the row.
Parameters
[in] row (int) The row.
[in] item (ProjectItem *) The item.
References setTextColor().
isBundleResults()
bool Isis::ProjectItem::isBundleResults () const
Returns true if BundleResults are stored in the data of the item.
Returns false otherwise.
Returns
bool If BundleResults are stored in the data of the item or not.
isBundleSettings()
bool Isis::ProjectItem::isBundleSettings () const
Returns true if BundleSettings are stored in the data of the item.
Returns false otherwise.
Returns
bool If BundleSettings are stored in the data of the item or not.
isBundleSolutionInfo()
bool Isis::ProjectItem::isBundleSolutionInfo () const
Returns true if a BundleSolutionInfo is stored in the data of the item.
Returns false otherwise.
Returns
bool If a BundleSolutionInfo is stored in the data of the item or not.
Referenced by Isis::ProjectItemModel::setData().
isControl()
bool Isis::ProjectItem::isControl () const
Returns true if a Control is stored in the data of the item.
Returns false otherwise.
Returns
bool If a Control is stored in the data of the item or not.
Referenced by Isis::WorkOrder::isExecutable(), Isis::Project::setActiveControl(), and Isis::WorkOrder::setData().
isControlList()
bool Isis::ProjectItem::isControlList () const
Returns true if a ControlList is stored in the data of the item.
Returns false otherwise.
Returns
bool If a ControlList is stored in the data of the item or not.
Referenced by Isis::WorkOrder::isExecutable(), Isis::ProjectItemModel::setData(), and Isis::WorkOrder::setData().
isCorrelationMatrix()
bool Isis::ProjectItem::isCorrelationMatrix () const
Returns true if a CorrelationMatrix is stored in the data of the item.
Returns false otherwise.
Returns
bool If a CorrelationMatrix is stored in the data of the item or not.
Referenced by Isis::WorkOrder::isExecutable(), and Isis::WorkOrder::setData().
isFileItem()
bool Isis::ProjectItem::isFileItem () const
Returns true if a FileItemQsp is stored in the data of the item.
Returns false otherwise.
Returns
bool If a FileItemQsp is stored in the item or not.
Referenced by Isis::WorkOrder::isExecutable(), and Isis::WorkOrder::setData().
isGuiCamera()
bool Isis::ProjectItem::isGuiCamera () const
Returns true if a GuiCameraQsp is stored in the data of the item.
Returns false otherwise.
Returns
bool If a GuiCameraQsp is stored in the item or not.
Referenced by Isis::WorkOrder::isExecutable(), and Isis::WorkOrder::setData().
isImage()
bool Isis::ProjectItem::isImage () const
Returns true if an Image is stored in the data of the item.
Returns false otherwise.
Returns
bool If an Image is stored in the data of the item or not.
Referenced by Isis::CubeDnView::addItem(), Isis::RemoveImagesWorkOrder::execute(), Isis::WorkOrder::isExecutable(), Isis::JigsawSetupDialog::JigsawSetupDialog(), Isis::ProjectItemModel::onSelectionChanged(), Isis::CubeDnView::save(), Isis::ProjectItemModel::selectedBOSSImages(), Isis::WorkOrder::setData(), and Isis::RemoveImagesWorkOrder::setupExecution().
isImageList()
bool Isis::ProjectItem::isImageList () const
Returns true if an ImageList is stored in the data of the item.
Returns false otherwise.
Returns
bool If an ImageList is stored in the data of the item or not.
Referenced by Isis::CubeDnView::addItem(), Isis::RemoveImagesWorkOrder::execute(), Isis::WorkOrder::isExecutable(), Isis::JigsawSetupDialog::JigsawSetupDialog(), Isis::ProjectItemModel::selectedBOSSImages(), Isis::Project::setActiveImageList(), Isis::ProjectItemModel::setData(), Isis::WorkOrder::setData(), Isis::RemoveImagesWorkOrder::setupExecution(), and Isis::JigsawSetupDialog::treeViewSelectionChanged().
isProject()
bool Isis::ProjectItem::isProject () const
Returns true if a Project is stored in the data of the item.
Returns false otherwise.
Returns
bool If a Project is stored in the data of the item or not.
Referenced by Isis::WorkOrder::isExecutable(), Isis::ProjectItemModel::setData(), and Isis::WorkOrder::setData().
isShape()
bool Isis::ProjectItem::isShape () const
Returns true if an Shape is stored in the data of the item.
Returns false otherwise.
Returns
(bool) If an Shape is stored in the data of the item or not.
Referenced by Isis::CubeDnView::addItem(), Isis::WorkOrder::isExecutable(), Isis::CubeDnView::save(), Isis::WorkOrder::setData(), and Isis::CubeDnView::viewportContainsShape().
isShapeList()
bool Isis::ProjectItem::isShapeList () const
Returns true if an ShapeList is stored in the data of the item.
Returns false otherwise.
Returns
(bool) If an ShapeList is stored in the data of the item or not.
Referenced by Isis::CubeDnView::addItem(), Isis::WorkOrder::isExecutable(), Isis::ProjectItemModel::setData(), and Isis::WorkOrder::setData().
isTargetBody()
bool Isis::ProjectItem::isTargetBody () const
Returns true if a TargetBodyQsp is stored in the data of the item.
Returns false otherwise.
Returns
bool If a TargetBodyQsp is stored in the item or not.
Referenced by Isis::WorkOrder::isExecutable(), and Isis::WorkOrder::setData().
isTemplate()
bool Isis::ProjectItem::isTemplate () const
Referenced by Isis::WorkOrder::isExecutable(), Isis::TemplateEditViewWorkOrder::isExecutable(), Isis::ProjectItemModel::setData(), and Isis::WorkOrder::setData().
model()
ProjectItemModel * Isis::ProjectItem::model () const
Returns the ProjectItemModel associated with this item.
Returns
ProjectItemModel* The model.
Referenced by Isis::ProjectItemProxyModel::addChild().
parent()
ProjectItem * Isis::ProjectItem::parent () const
Returns the parent item of this item.
Returns
ProjectItem* The parent item.
Referenced by Isis::ProjectItemProxyModel::addChild(), Isis::ProjectItemProxyModel::addItem(), Isis::ProjectItemModel::removeItem(), and Isis::ProjectItemModel::selectedBOSSImages().
project()
Project * Isis::ProjectItem::project () const
Returns the Project stored in the data of the item.
Returns
Project* The Project of the item.
Referenced by Isis::ProjectItemModel::clean(), ProjectItem(), and setProject().
setBundleResults()
void Isis::ProjectItem::setBundleResults (BundleResults bundleResults)
Sets the text, icon, and data corresponding to BundleResults.
Parameters
[in] bundleResults (BundleResults) The BundleResults.
References bundleResults(), and setTextColor().
Referenced by ProjectItem().
setBundleSettings()
void Isis::ProjectItem::setBundleSettings (BundleSettingsQsp bundleSettings)
Sets the text, icon, and data corresponding to BundleSettings.
Parameters
[in] bundleSettings (BundleSettingsQsp) The BundleSettingsQsp.
References bundleSettings(), and setTextColor().
Referenced by ProjectItem().
setBundleSolutionInfo()
void Isis::ProjectItem::setBundleSolutionInfo (BundleSolutionInfo * bundleSolutionInfo)
Sets the text, icon, and data corresponding to a BundleSolutionInfo.
Parameters
[in] bundleSolutionInfo (BundleSolutionInfo *) The BundleSolutionInfo.
References bundleSolutionInfo(), Isis::BundleSolutionInfo::name(), Isis::BundleSolutionInfo::runTime(), and setTextColor().
Referenced by ProjectItem().
setChild()
void Isis::ProjectItem::setChild (int row, ProjectItem * item)
Sets the child at the given row to an item.
Parameters
[in] row (int) The row.
[in] item (ProjectItem *) The item.
References setTextColor().
setControl()
void Isis::ProjectItem::setControl (Control * control)
Sets the text, icon, and data corresponding to a Control.
Parameters
[in] control (Control *) The Control.
References control(), Isis::Control::fileName(), and setTextColor().
Referenced by ProjectItem().
setControlList()
void Isis::ProjectItem::setControlList (ControlList * controlList)
Sets the text, icon, and data corresponding to a ControlList.
Parameters
[in] controlList (ControlList *) The ControlList.
References controlList(), Isis::ControlList::name(), and setTextColor().
Referenced by ProjectItem().
setControls()
void Isis::ProjectItem::setControls ()
Sets the text, icon, and data corresponding to a list of ControlList.
References setTextColor().
Referenced by ProjectItem().
setCorrelationMatrix()
void Isis::ProjectItem::setCorrelationMatrix (CorrelationMatrix correlationMatrix)
Sets the text, icon, and data corresponding to a CorrelationMatrix.
Parameters
[in] correlationMatrix (CorrelationMatrix) The CorrelationMatrix.
References correlationMatrix(), and setTextColor().
Referenced by ProjectItem().
setGuiCamera()
void Isis::ProjectItem::setGuiCamera (GuiCameraQsp guiCamera)
Sets the text, icon, and data corresponding to a GuiCameraQsp.
Parameters
[in] guiCamera (GuiCameraQsp) The GuiCameraQsp.
References guiCamera(), and setTextColor().
Referenced by ProjectItem().
setGuiCameraList()
void Isis::ProjectItem::setGuiCameraList ()
Sets the text, icon, and data corresponding to a GuiCameraQsp.
References setTextColor().
Referenced by ProjectItem().
setImage()
void Isis::ProjectItem::setImage (Image * image)
Sets the text, icon, and data corresponding to an Image.
Parameters
[in] image (Image *) The Image.
References Isis::Image::fileName(), image(), and setTextColor().
Referenced by ProjectItem().
setImageList()
void Isis::ProjectItem::setImageList (ImageList * imageList)
Sets the text, icon, and data corresponding to an ImageList.
Parameters
[in] imageList (ImageList *) The ImageList.
References imageList(), Isis::ImageList::name(), Isis::ImageList::path(), and setTextColor().
Referenced by ProjectItem().
setImages()
void Isis::ProjectItem::setImages ()
Sets the text, icon, and data corresponding to a list of ImageList.
References setTextColor().
Referenced by ProjectItem().
setProject()
void Isis::ProjectItem::setProject (Project * project)
Sets the text, icon, and data corresponding to a Project.
Parameters
[in] project (Project *) The Project.
References Isis::Project::name(), project(), Isis::Project::projectRoot(), and setTextColor().
Referenced by ProjectItem().
setProjectItem()
void Isis::ProjectItem::setProjectItem (ProjectItem * item)
Sets the text, icon, and data to those of another item.
Parameters
[in] item (ProjectItem *) The other item.
References setTextColor().
Referenced by Isis::ProjectItemProxyModel::addChild(), and ProjectItem().
setResults()
void Isis::ProjectItem::setResults ()
Sets the text, icon, and data corresponding to a list of Results.
References setTextColor().
Referenced by ProjectItem().
setShape()
void Isis::ProjectItem::setShape (Shape * shape)
Sets the text, icon, and data corresponding to an Shape.
Parameters
[in] shape (Shape *) The Shape.
References Isis::Shape::fileName(), setTextColor(), and shape().
Referenced by ProjectItem().
setShapeList()
void Isis::ProjectItem::setShapeList (ShapeList * shapeList)
Sets the text, icon, and data corresponding to an ShapeList.
Parameters
[in] shapeList (ShapeList *) The ShapeList.
References Isis::ShapeList::name(), Isis::ShapeList::path(), setTextColor(), and shapeList().
Referenced by ProjectItem().
setShapes()
void Isis::ProjectItem::setShapes ()
Sets the text, icon, and data corresponding to a list of ShapeList.
References setTextColor().
Referenced by ProjectItem().
setSpacecraft()
void Isis::ProjectItem::setSpacecraft ()
Sets the text, icon, and data corresponding to SpaceCraft.
References setTextColor().
Referenced by ProjectItem().
setTargetBody()
void Isis::ProjectItem::setTargetBody (TargetBodyQsp targetBody)
Sets the text, icon, and data corresponding to a TargetBodyQsp.
Parameters
targetBody Target body to set data from
References setTextColor(), and targetBody().
Referenced by ProjectItem().
setTargetBodyList()
void Isis::ProjectItem::setTargetBodyList ()
Sets the text, icon, and data corresponding to a TargetBodyList.
References setTextColor().
Referenced by ProjectItem().
setTemplate()
void Isis::ProjectItem::setTemplate (Template * newTemplate)
Sets the text, icon, and data corresponding to a Template.
Parameters
[in] shape (Shape *) The Shape.
References Isis::Template::fileName(), and setTextColor().
Referenced by ProjectItem().
setTemplateList()
void Isis::ProjectItem::setTemplateList (TemplateList * templateList)
Sets the text, icon, and data corresponding to an TemplateList.
Parameters
[in] templateList (TemplateList *) The TemplateList.
References Isis::TemplateList::name(), Isis::TemplateList::path(), setTextColor(), and templateList().
Referenced by ProjectItem().
setTemplates()
void Isis::ProjectItem::setTemplates ()
Sets the text, icon, and data corresponding to a list of TemplateList.
References appendRow(), and ProjectItem().
Referenced by ProjectItem().
setTextColor()
void Isis::ProjectItem::setTextColor (Qt::GlobalColor color)
Referenced by appendRow(), insertRow(), ProjectItem(), Isis::Project::setActiveControl(), Isis::Project::setActiveImageList(), setBundleResults(), setBundleSettings(), setBundleSolutionInfo(), setChild(), setControl(), setControlList(), setControls(), setCorrelationMatrix(), setGuiCamera(), setGuiCameraList(), setImage(), setImageList(), setImages(), setProject(), setProjectItem(), setResults(), setShape(), setShapeList(), setShapes(), setSpacecraft(), setTargetBody(), setTargetBodyList(), setTemplate(), and setTemplateList().
shape()
Shape * Isis::ProjectItem::shape () const
Returns the Shape stored in the data of the item.
Returns
(Shape *) The Shape of the item.
Referenced by Isis::WorkOrder::isExecutable(), ProjectItem(), Isis::CubeDnView::save(), Isis::WorkOrder::setData(), and setShape().
shapeList()
ShapeList * Isis::ProjectItem::shapeList () const
Returns the ShapeList stored in the data of the item.
Returns
(ShapeList *) The ShapeList of the item.
Referenced by Isis::WorkOrder::isExecutable(), ProjectItem(), Isis::ProjectItemModel::setData(), Isis::WorkOrder::setData(), and setShapeList().
takeChild()
ProjectItem * Isis::ProjectItem::takeChild (int row)
Removes the child item at the given row and returns the removed item.
Parameters
[in] row (int) The row.
Returns
ProjectItem* The item.
targetBody()
TargetBodyQsp Isis::ProjectItem::targetBody () const
Returns the TargetBodyQsp stored in the data of the item.
Returns
TargetBodyQsp The target body stored in the item.
Referenced by Isis::WorkOrder::isExecutable(), ProjectItem(), Isis::WorkOrder::setData(), and setTargetBody().
templateList()
TemplateList * Isis::ProjectItem::templateList () const
Returns the TemplateList stored in the data of the item.
Returns
(TemplateList *) The TemplateList of the item.
Referenced by ProjectItem(), and setTemplateList().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ProjectItem/ProjectItem.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ProjectItem/ProjectItem.cpp