Isis Developer Reference: Isis::MosaicController Class Reference
Isis::MosaicController Class Reference
#include <MosaicController.h>
Public Slots
void saveProject (QString filename)
void readProject (QString filename)
void openImages (QStringList filenames)
Handle opening cubes by filename.
void openProjectImages (PvlObject projectImages)
Signals
void imagesAdded (ImageList images)
Emitted when new images are available.
void imagesAdded (ImageList *images)
void allImagesClosed ()
Public Member Functions
MosaicController (QStatusBar *status, QSettings &settings)
MosaicWidget constructor.
virtual ~MosaicController ()
Free the allocated memory by this object.
MosaicSceneWidget * getMosaicScene ()
MosaicSceneWidget * getMosaicWorldScene ()
ImageFileListWidget * getImageFileList ()
void addExportActions (QMenu &fileMenu)
Add actions that are export-related to the menu.
QProgressBar * getProgress ()
void saveProject ()
QList< QAction * > getSettingsActions ()
void saveSettings (QSettings &settings)
Detailed Description
Author
????-??-?? Stacy Alley
Constructor & Destructor Documentation
MosaicController()
Isis::MosaicController::MosaicController (QStatusBar * status, QSettings & settings)
MosaicWidget constructor.
MosaicWidget is derived from QSplitter, the left side of the splitter is a QTreeWidget and the right side of the splitter is a QGraphicsView.
Parameters
parent
References imagesAdded().
~MosaicController()
Isis::MosaicController::~MosaicController () virtual
Free the allocated memory by this object.
Member Function Documentation
addExportActions()
void Isis::MosaicController::addExportActions (QMenu & fileMenu)
Add actions that are export-related to the menu.
allImagesClosed
void Isis::MosaicController::allImagesClosed () signal
getImageFileList()
ImageFileListWidget* Isis::MosaicController::getImageFileList () inline
getMosaicScene()
MosaicSceneWidget* Isis::MosaicController::getMosaicScene () inline
getMosaicWorldScene()
MosaicSceneWidget* Isis::MosaicController::getMosaicWorldScene () inline
getProgress()
QProgressBar * Isis::MosaicController::getProgress ()
getSettingsActions()
QList< QAction * > Isis::MosaicController::getSettingsActions ()
References Isis::ImageDisplayProperties::FootprintViewProperties.
imagesAdded [1/2]
void Isis::MosaicController::imagesAdded (ImageList * images) signal
imagesAdded [2/2]
void Isis::MosaicController::imagesAdded (ImageList images) signal
Emitted when new images are available.
Referenced by MosaicController().
openImages
void Isis::MosaicController::openImages (QStringList cubeNames) slot
Handle opening cubes by filename.
This class constructs and owns the actual Cube objects.
openProjectImages
void Isis::MosaicController::openProjectImages (PvlObject projectImages) slot
Referenced by readProject().
readProject
void Isis::MosaicController::readProject (QString filename) slot
References _FILEINFO_, Isis::PvlObject::findObject(), Isis::PvlObject::hasObject(), openProjectImages(), and Isis::IException::Unknown.
Referenced by Isis::MosaicMainWindow::loadProject().
saveProject() [1/2]
void Isis::MosaicController::saveProject ()
Referenced by Isis::MosaicMainWindow::saveProject(), and Isis::MosaicMainWindow::saveProjectAs().
saveProject [2/2]
void Isis::MosaicController::saveProject (QString filename) slot
References Isis::Image::toPvl(), and Isis::Pvl::write().
saveSettings()
void Isis::MosaicController::saveSettings (QSettings & settings)
Referenced by Isis::MosaicMainWindow::closeMosaic().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicMainWindow/MosaicController.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicMainWindow/MosaicController.cpp