Isis Developer Reference: Isis::DisplayProperties Class Reference
Isis::DisplayProperties Class Reference
#include <DisplayProperties.h>
Signals
void propertyChanged (DisplayProperties *)
void supportAdded (int)
Public Member Functions
DisplayProperties (QString displayName, QObject *parent=NULL)
DisplayProperties constructor.
virtual ~DisplayProperties ()
destructor
void fromPvl (const PvlObject &pvl)
void save (QXmlStreamWriter &stream, const Project *project, FileName newProjectRoot) const
Output format:
PvlObject toPvl () const
Convert to Pvl for project files.
void addSupport (int property)
Call this with every property you support, otherwise they will not communicate properly between widgets.
bool supports (int property)
Support may come later, please make sure you are connected to the supportAdded signal.
QVariant getValue (int property) const
Get a property's associated data.
void setDisplayName (QString displayName)
Sets display name.
QString displayName () const
Returns the display name.
Static Public Member Functions
static QColor randomColor ()
Protected Member Functions
void setValue (int prop, QVariant value)
This is the generic mutator for properties.
Detailed Description
Author
2012-??-?? ???
Constructor & Destructor Documentation
DisplayProperties()
Isis::DisplayProperties::DisplayProperties (QString displayName, QObject * parent = NULL)
DisplayProperties constructor.
This sets default values and constructs the Cube *. You cannot have much more than 1K of these without calling closeCube().
Parameters
displayName The filename (fully expanded) of the object.
parent Qt parent object (this is destroyed when parent is destroyed)
References displayName().
~DisplayProperties()
Isis::DisplayProperties::~DisplayProperties () virtual
destructor
Member Function Documentation
addSupport()
void Isis::DisplayProperties::addSupport (int property)
Call this with every property you support, otherwise they will not communicate properly between widgets.
Parameters
prop The property you are adding support for
References supportAdded(), and supports().
Referenced by Isis::ImageTreeWidgetItem::ImageTreeWidgetItem(), and Isis::MosaicSceneItem::MosaicSceneItem().
displayName()
QString Isis::DisplayProperties::displayName () const
Returns the display name.
Referenced by Isis::Directory::addCnetEditorView(), Isis::MosaicSceneItem::contextMenuEvent(), DisplayProperties(), Isis::ImageTreeWidgetItem::ImageTreeWidgetItem(), Isis::Image::initFootprint(), Isis::Shape::initFootprint(), Isis::JigsawSetupDialog::JigsawSetupDialog(), Isis::MosaicSceneItem::MosaicSceneItem(), Isis::GuiCamera::operator==(), Isis::MosaicSceneItem::reproject(), Isis::ControlDisplayProperties::save(), save(), Isis::GuiCameraDisplayProperties::save(), Isis::ShapeDisplayProperties::save(), Isis::TargetBodyDisplayProperties::save(), Isis::SensorInfoWidget::SensorInfoWidget(), setDisplayName(), Isis::ExportControlNetWorkOrder::setupExecution(), Isis::TargetInfoWidget::TargetInfoWidget(), and toPvl().
fromPvl()
void Isis::DisplayProperties::fromPvl (const PvlObject & pvl)
References setDisplayName().
Referenced by Isis::Image::fromPvl(), and Isis::Shape::fromPvl().
getValue()
QVariant Isis::DisplayProperties::getValue (int property) const
Get a property's associated data.
Parameters
prop The property
Referenced by Isis::MosaicSceneItem::color(), Isis::MosaicSceneItem::cubeDisplayChanged(), Isis::MosaicSceneItem::paint(), Isis::ImageListActionWorkOrder::qualifyString(), Isis::MosaicSceneItem::reproject(), Isis::ImageTreeWidgetItem::update(), and Isis::MosaicSceneItem::updateSelection().
propertyChanged
void Isis::DisplayProperties::propertyChanged (DisplayProperties *) signal
Referenced by setValue().
randomColor()
static QColor Isis::DisplayProperties::randomColor () static
save()
void Isis::DisplayProperties::save (QXmlStreamWriter & stream, const Project * project, FileName newProjectRoot) const
Output format:
<displayProperties displayName="..."> Hex-encoded data </displayProperties>
References displayName(), and Isis::ReadWrite.
Referenced by Isis::Image::save().
setDisplayName()
void Isis::DisplayProperties::setDisplayName (QString displayName)
Sets display name.
Parameters
displayName Display name of the object.
References displayName().
Referenced by fromPvl().
setValue()
void Isis::DisplayProperties::setValue (int property, QVariant value) protected
This is the generic mutator for properties.
Given a value, this will change it and emit propertyChanged if its different and supported.
References propertyChanged(), and supports().
Referenced by Isis::ImageDisplayProperties::ImageDisplayProperties(), Isis::ImageDisplayProperties::setColor(), Isis::ImageDisplayProperties::setSelected(), Isis::ImageDisplayProperties::setShowDNs(), Isis::ImageDisplayProperties::setShowFill(), Isis::ImageDisplayProperties::setShowLabel(), and Isis::ImageDisplayProperties::setShowOutline().
supportAdded
void Isis::DisplayProperties::supportAdded (int) signal
Referenced by addSupport().
supports()
bool Isis::DisplayProperties::supports (int property)
Support may come later, please make sure you are connected to the supportAdded signal.
Returns
True if the property has support, false otherwise
Referenced by addSupport(), Isis::ImageList::allSupport(), setValue(), and Isis::ImageTreeWidgetItem::update().
toPvl()
PvlObject Isis::DisplayProperties::toPvl () const
Convert to Pvl for project files.
This stores all of the data associated with all of the properties (but not what is supported). This also stores the cube filename.
References displayName(), and Isis::ReadWrite.
Referenced by Isis::Image::toPvl(), and Isis::Shape::toPvl().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/DisplayProperties/DisplayProperties.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/DisplayProperties/DisplayProperties.cpp