Isis Developer Reference: Isis::MeasureValidationResults Class Reference
Isis::MeasureValidationResults Class Reference
MeasureValidationResults class.
#include <MeasureValidationResults.h>
Public Types
enum Option {
EmissionAngle , IncidenceAngle , DNValue , Resolution ,
PixelsFromEdge , MetersFromEdge , SampleResidual , LineResidual ,
ResidualMagnitude , SampleShift , LineShift , PixelShift
}
Public Member Functions
MeasureValidationResults ()
~MeasureValidationResults ()
bool isValid ()
bool getValidStatus (Option opt)
QString toString ()
QString toString (QString serialNumber, QString pointID)
QString toString (QString sample, QString line, QString serialNumber, QString pointID)
void addFailure (Option opt, double tolerance, const char *compare="less")
void addFailure (Option opt, double computed, double min, double max)
QString getFailurePrefix (Option opt)
Detailed Description
MeasureValidationResults class.
Stores the error/results string of a Measure's Validation
See also
cnetref cnetedit etc.
Author
????-??-?? Unknown
Member Enumeration Documentation
Option
enum Isis::MeasureValidationResults::Option
Enumerator
EmissionAngle
IncidenceAngle
DNValue
Resolution
PixelsFromEdge
MetersFromEdge
SampleResidual
LineResidual
ResidualMagnitude
SampleShift
LineShift
PixelShift
Constructor & Destructor Documentation
MeasureValidationResults()
Isis::MeasureValidationResults::MeasureValidationResults ()
~MeasureValidationResults()
Isis::MeasureValidationResults::~MeasureValidationResults ()
Member Function Documentation
addFailure() [1/2]
void Isis::MeasureValidationResults::addFailure (Option opt, double computed, double min, double max)
References getFailurePrefix().
addFailure() [2/2]
void Isis::MeasureValidationResults::addFailure (Option opt, double tolerance, const char * compare = "less")
References getFailurePrefix().
Referenced by Isis::ControlNetValidMeasure::ValidResidualTolerances(), Isis::ControlNetValidMeasure::ValidShiftTolerances(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
getFailurePrefix()
QString Isis::MeasureValidationResults::getFailurePrefix (Option opt)
References DNValue, EmissionAngle, IncidenceAngle, LineResidual, LineShift, MetersFromEdge, PixelsFromEdge, PixelShift, ResidualMagnitude, Resolution, SampleResidual, and SampleShift.
Referenced by addFailure().
getValidStatus()
bool Isis::MeasureValidationResults::getValidStatus (Option opt)
isValid()
bool Isis::MeasureValidationResults::isValid ()
Referenced by Isis::InterestOperator::FindCnetRef(), Isis::InterestOperator::InterestByMeasure(), Isis::InterestOperator::Operate(), and Isis::InterestOperator::ProcessLocked_Point_Reference().
toString() [1/3]
QString Isis::MeasureValidationResults::toString ()
Referenced by Isis::InterestOperator::FindCnetRef().
toString() [2/3]
QString Isis::MeasureValidationResults::toString (QString sample, QString line, QString serialNumber, QString pointID)
toString() [3/3]
QString Isis::MeasureValidationResults::toString (QString serialNumber, QString pointID)
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/ControlNetValidMeasure/MeasureValidationResults.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/ControlNetValidMeasure/MeasureValidationResults.cpp