Isis Developer Reference: Isis::CubeCalculator Class Reference
Isis::CubeCalculator Class Reference
Math
Calculator for arrays.
#include <CubeCalculator.h>
Public Member Functions
CubeCalculator ()
Constructs a CubeCalculator.
~CubeCalculator ()
Destroys the CubeCalculator object.
void Clear ()
This method completely resets the calculator.
void prepareCalculations (QString equation, QVector< Cube * > &inCubes, Cube *outCube)
This method builds a list of actions to perform based on the postfix expression.
QVector< double > runCalculations (QVector< Buffer * > &cubeData, int line, int band)
This method will execute the calculations built up when PrepareCalculations was called.
Detailed Description
Calculator for arrays.
This class is a RPN calculator on cubes. The base Calculator class is used in conjunction with methods to retrieve data from a cube and perform calculations.
Author
2008-03-26 Steven Lambright
Constructor & Destructor Documentation
CubeCalculator()
Isis::CubeCalculator::CubeCalculator ()
Constructs a CubeCalculator.
~CubeCalculator()
Isis::CubeCalculator::~CubeCalculator ()
Destroys the CubeCalculator object.
Member Function Documentation
Clear()
void Isis::CubeCalculator::Clear () virtual
This method completely resets the calculator.
Frees dynamic memory in container members.
The prepared calculations will be erased when this is called.
Reimplemented from Isis::Calculator.
prepareCalculations()
void Isis::CubeCalculator::prepareCalculations (QString equation, QVector< Cube * > & inCubes, Cube * outCube)
This method builds a list of actions to perform based on the postfix expression.
Error checking is done using the inCubeInfos, and the outCubeInfo is necessary to tell the dimensions of the output cube. Call this method before calling RunCalculations(). This method will also erase all calculator history before building up a new set of calculations to run.
Parameters
equation The equation in postfix notation
inCubes The input cubes
outCube The output cube
Exceptions
IException::Unknown "Invalid file number"
IException::Unknown "Unidentified operator"
References _FILEINFO_, Isis::E, Isis::PI, Isis::Cube::sampleCount(), Isis::IString::ToDouble(), Isis::IString::ToInteger(), Isis::IString::Token(), and Isis::IString::ToQt().
runCalculations()
QVector< double > Isis::CubeCalculator::runCalculations (QVector< Buffer * > & cubeData, int curLine, int curBand)
This method will execute the calculations built up when PrepareCalculations was called.
Parameters
cubeData The input cubes' data
curLine The current line in the output cube
curBand The current band in the output cube
Returns
std::vector<double> The results of the calculations (with Isis Special Pixels)
Exceptions
IException::Unknown "Too many operands in the equation."
References _FILEINFO_, Isis::DataValue::constant(), Isis::DataValue::cubeIndex(), and Isis::DataValue::type().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/CubeCalculator/CubeCalculator.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/CubeCalculator/CubeCalculator.cpp