Isis Developer Reference: Isis::MatrixOptionsDialog Class Reference
Isis::MatrixOptionsDialog Class Reference
This widget allows the user to modify the matrix display.
#include <MatrixOptionsDialog.h>
Public Slots
void applyOptions ()
Send changes back to scene widget (MatrixOptions) so it can redraw the elements in the right color.
void readOptions ()
Get the current options from the matrix scene widget.
void updateCorrelationData (QString currentData)
Update the current correlation information.
void populateParameterComboBox (int index)
Update parameter combo boxes at real time, when the img combo boxes are changed.
Signals
void optionsUpdated ()
Public Member Functions
MatrixOptionsDialog (MatrixOptions *options, QWidget *parent)
Main constructor.
~MatrixOptionsDialog ()
Default Destructor.
Detailed Description
This widget allows the user to modify the matrix display.
This dialog allows the user to select different color schemes and change the focus of the display. The user can select a gradient color scheme, the default, or a two color, good/bad, color scheme that is based on a tolerance. When the matrix is too large to display the whole thing, the user will be able to select which part of the matrix they want to see.
Author
2014-07-14 Kimberly Oyama
Constructor & Destructor Documentation
MatrixOptionsDialog()
Isis::MatrixOptionsDialog::MatrixOptionsDialog (MatrixOptions * options, QWidget * parent)
Main constructor.
Layouts:
Widget TabWidget colorTab (colorOptionsPage) colorToleranceLayout (everything tolerance related) colorToleranceOptionsLayout (not including radiobutton, has slider) colorToleranceEditsLayout (not including slider) colorBadCorrLayout (bad corr label and color button) colorEnterTolLayout (tol label and line edit) colorGoodCorrLayout (good corr label and color button) colorGradientLayout (radiobutton)
focusTab (focusOptionsPage) focusPageLayout focusTolLayout (has tolerance radiobutton) focusTolEditLayout (tolerance label and line edit) elementsLayout focusBadElementsLayout (label and spinbox) focusGoodElementsLayout (label and spinbox) focusOptionsLayout (best, worst radiobuttons) focusSpecParamLayout (radiobutton, img1 label, img2 label) focusSpecParam1Layout (img1 combobox, param1 combobox) focusSpecParam2Layout (img2 combobox, param2 combobox)
currentCorrDataLayout currentCorrLayout (label, value) currentCorrImg1Layout (img1 name, param1 name) currentCorrImg2Layout (img2 name, param2 name)
Parameters
matrixOptionsWidget
parent
References applyOptions(), readOptions(), and updateCorrelationData().
~MatrixOptionsDialog()
Isis::MatrixOptionsDialog::~MatrixOptionsDialog ()
Default Destructor.
Member Function Documentation
applyOptions
void Isis::MatrixOptionsDialog::applyOptions () slot
Send changes back to scene widget (MatrixOptions) so it can redraw the elements in the right color.
This will be called when the appy button is pressed.
References optionsUpdated(), Isis::MatrixOptions::setBadCorrelationColor(), Isis::MatrixOptions::setColorScheme(), Isis::MatrixOptions::setColorTolerance(), and Isis::MatrixOptions::setGoodCorrelationColor().
Referenced by MatrixOptionsDialog().
optionsUpdated
void Isis::MatrixOptionsDialog::optionsUpdated () signal
Referenced by applyOptions().
populateParameterComboBox
void Isis::MatrixOptionsDialog::populateParameterComboBox (int index) slot
Update parameter combo boxes at real time, when the img combo boxes are changed.
Parameters
index The current index of the IMAGE combobox.
readOptions
void Isis::MatrixOptionsDialog::readOptions () slot
Get the current options from the matrix scene widget.
This will be called when the widget is first opened and when the displayed correlation matrix is changed.
References Isis::MatrixOptions::badCorrelationColor(), Isis::MatrixOptions::Best, Isis::MatrixOptions::colorScheme(), Isis::MatrixOptions::colorTolerance(), Isis::MatrixOptions::focusOption(), Isis::MatrixOptions::focusValue(), Isis::MatrixOptions::goodCorrelationColor(), Isis::MatrixOptions::matrixImgsAndParams(), Isis::MatrixOptions::Specific, Isis::MatrixOptions::Tolerance, and Isis::MatrixOptions::Worst.
Referenced by MatrixOptionsDialog().
updateCorrelationData
void Isis::MatrixOptionsDialog::updateCorrelationData (QString currentData) slot
Update the current correlation information.
This slot is called when the m_options signal, changedCurrentCorrData() is emit. This happens when a matrix element is clicked on.
Referenced by MatrixOptionsDialog().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MatrixSceneWidget/MatrixOptionsDialog.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MatrixSceneWidget/MatrixOptionsDialog.cpp