Isis Developer Reference: Isis::PvlFormatPds Class Reference
Isis::PvlFormatPds Class Reference
Parsing
Formats the value of a PvlKeyword into a PDS complient string.
#include <PvlFormatPds.h>
Public Member Functions
PvlFormatPds ()
PvlFormatPds (const QString &file)
PvlFormatPds (Pvl &keymap)
virtual ~PvlFormatPds ()
virtual QString formatValue (const PvlKeyword &keyword, int valueIndex=0)
virtual QString formatName (const PvlKeyword &keyword)
virtual QString formatEnd (const QString name, const PvlKeyword &keyword)
virtual QString formatEOL ()
void add (const QString &file)
void add (Pvl &keymap)
void setCharLimit (const unsigned int limit)
Sets the maximum number of characters in a keyword value that can be printed to a line before it wraps to the next line.
unsigned int charLimit () const
Retrieves the maximum number of characters in a keyword value that can be printed to a line before it wraps to the next line.
virtual KeywordType type (const PvlKeyword &keyword)
virtual int accuracy (const PvlKeyword &keyword)
Protected Member Functions
virtual QString addQuotes (const QString value)
QString formatString (const PvlKeyword &keyword, int num)
QString formatInteger (const PvlKeyword &keyword, int num, int bytes)
QString formatReal (const PvlKeyword &keyword, int num, int precision)
QString formatEnum (const PvlKeyword &keyword, int num)
QString formatBinary (const PvlKeyword &keyword, int num, int bytes)
QString formatHex (const PvlKeyword &keyword, int num, int bytes)
QString formatBool (const PvlKeyword &keyword, int num)
QString formatUnknown (const PvlKeyword &keyword, int num)
bool isSingleUnit (const PvlKeyword &keyword)
Returns true if the units are the same for all value in the keyword otherwise it returns false.
Protected Attributes
QString m_keywordMapFile
Pvl m_keywordMap
unsigned int m_charLimit
Maximum number of characters on a single line of a keyword value.
Detailed Description
Formats the value of a PvlKeyword into a PDS complient string.
This class is used to format a single PVL keyword-value pair. The supported formats are Normal and PDS. The keyword to type mapping is not defined until a Pvl or Pvl formatted file is supplied.
Author
2006-09-05 Stuart Sides
Constructor & Destructor Documentation
PvlFormatPds() [1/3]
Isis::PvlFormatPds::PvlFormatPds ()
PvlFormatPds() [2/3]
Isis::PvlFormatPds::PvlFormatPds (const QString & file)
PvlFormatPds() [3/3]
Isis::PvlFormatPds::PvlFormatPds (Pvl & keymap)
~PvlFormatPds()
virtual Isis::PvlFormatPds::~PvlFormatPds () inline virtual
Member Function Documentation
accuracy()
int Isis::PvlFormat::accuracy (const PvlKeyword & keyword) virtual inherited
References Isis::PvlKeyword::name(), Isis::PvlKeyword::size(), and Isis::toInt().
Referenced by formatValue().
add() [1/2]
void Isis::PvlFormat::add (const QString & file) inherited
References _FILEINFO_.
Referenced by Isis::ProcessExportPds::CreateImageLabel(), Isis::ProcessExportPds::FixedJP2ImageRoot(), Isis::ProcessExportPds::StandardImageImage(), Isis::ProcessExportPds::StandardJP2Image(), and Isis::ProcessExportPds::StreamJP2ImageRoot().
add() [2/2]
void Isis::PvlFormat::add (Pvl & keymap) inherited
References Isis::PvlKeyword::addValue(), Isis::PvlContainer::keywords(), Isis::PvlKeyword::name(), and Isis::PvlKeyword::size().
addQuotes()
QString Isis::PvlFormatPds::addQuotes (const QString value) protected virtual
Reimplemented from Isis::PvlFormat.
Referenced by formatString().
charLimit()
unsigned int Isis::PvlFormat::charLimit () const inline inherited
Retrieves the maximum number of characters in a keyword value that can be printed to a line before it wraps to the next line.
By default, the limit is set to 80 characters.
Returns
unsigned int Maximum number of characters.
References Isis::PvlFormat::m_charLimit.
Referenced by Isis::PvlKeyword::writeWithWrap().
formatBinary()
QString Isis::PvlFormatPds::formatBinary (const PvlKeyword & keyword, int num, int bytes) protected
References Isis::PvlKeyword::clear(), Isis::PvlKeyword::size(), Isis::toBigInt(), and Isis::PvlKeyword::unit().
Referenced by formatValue().
formatBool()
QString Isis::PvlFormatPds::formatBool (const PvlKeyword & keyword, int num) protected
References Isis::PvlKeyword::size().
Referenced by formatValue().
formatEnd()
QString Isis::PvlFormatPds::formatEnd (const QString name, const PvlKeyword & keyword) virtual
Reimplemented from Isis::PvlFormat.
formatEnum()
QString Isis::PvlFormatPds::formatEnum (const PvlKeyword & keyword, int num) protected
References Isis::PvlKeyword::size(), and Isis::PvlKeyword::unit().
Referenced by formatValue().
formatEOL()
virtual QString Isis::PvlFormatPds::formatEOL () inline virtual
Reimplemented from Isis::PvlFormat.
formatHex()
QString Isis::PvlFormatPds::formatHex (const PvlKeyword & keyword, int num, int bytes) protected
References Isis::PvlKeyword::size(), Isis::toBigInt(), Isis::toInt(), and Isis::PvlKeyword::unit().
Referenced by formatValue().
formatInteger()
QString Isis::PvlFormatPds::formatInteger (const PvlKeyword & keyword, int num, int bytes) protected
References Isis::PvlKeyword::size(), and Isis::PvlKeyword::unit().
Referenced by formatValue().
formatName()
QString Isis::PvlFormatPds::formatName (const PvlKeyword & keyword) virtual
Reimplemented from Isis::PvlFormat.
References Isis::PvlKeyword::name().
formatReal()
QString Isis::PvlFormatPds::formatReal (const PvlKeyword & keyword, int num, int precision) protected
References Isis::PvlKeyword::size(), Isis::toDouble(), and Isis::PvlKeyword::unit().
Referenced by formatValue().
formatString()
QString Isis::PvlFormatPds::formatString (const PvlKeyword & keyword, int num) protected
References addQuotes(), Isis::PvlKeyword::size(), and Isis::PvlKeyword::unit().
Referenced by formatValue().
formatUnknown()
QString Isis::PvlFormatPds::formatUnknown (const PvlKeyword & keyword, int num) protected
References Isis::PvlFormat::addQuotes(), Isis::PvlKeyword::size(), and Isis::PvlKeyword::unit().
Referenced by formatValue().
formatValue()
QString Isis::PvlFormatPds::formatValue (const PvlKeyword & keyword, int valueIndex = 0) virtual
Reimplemented from Isis::PvlFormat.
References Isis::PvlFormat::accuracy(), Isis::BinaryKeyword, Isis::BoolKeyword, Isis::EnumKeyword, formatBinary(), formatBool(), formatEnum(), formatHex(), formatInteger(), formatReal(), formatString(), formatUnknown(), Isis::HexKeyword, Isis::IntegerKeyword, Isis::PvlKeyword::name(), Isis::NoTypeKeyword, Isis::RealKeyword, Isis::StringKeyword, and Isis::PvlFormat::type().
isSingleUnit()
bool Isis::PvlFormat::isSingleUnit (const PvlKeyword & keyword) protected inherited
Returns true if the units are the same for all value in the keyword otherwise it returns false.
Parameters
keyword The PvlKeyword to be formatted
References Isis::PvlKeyword::size(), Isis::PvlKeyword::stringEqual(), and Isis::PvlKeyword::unit().
setCharLimit()
void Isis::PvlFormat::setCharLimit (const unsigned int limit) inline inherited
Sets the maximum number of characters in a keyword value that can be printed to a line before it wraps to the next line.
By default, the limit is set to 80 characters.
Parameters
limit The new character limit.
References Isis::PvlFormat::m_charLimit.
type()
KeywordType Isis::PvlFormat::type (const PvlKeyword & keyword) virtual inherited
References Isis::PvlKeyword::name(), Isis::NoTypeKeyword, and Isis::toKeywordType().
Referenced by formatValue().
Member Data Documentation
m_charLimit
unsigned int Isis::PvlFormat::m_charLimit protected inherited
Maximum number of characters on a single line of a keyword value.
Referenced by Isis::PvlFormat::charLimit(), and Isis::PvlFormat::setCharLimit().
m_keywordMap
Pvl Isis::PvlFormat::m_keywordMap protected inherited
m_keywordMapFile
QString Isis::PvlFormat::m_keywordMapFile protected inherited
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/PvlFormatPds/PvlFormatPds.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/PvlFormatPds/PvlFormatPds.cpp