Isis Developer Reference: Isis::MeasureLeafItem Class Reference
Isis::MeasureLeafItem Class Reference abstract
A leaf node in the tree structure that represents a control measure.
#include <MeasureLeafItem.h>
Public Types
enum Column {
PointId = 0 , ImageId = 1 , Sample = 2 , Line = 3 ,
EditLock = 4 , Ignored = 5 , Reference = 6 , Type = 7 ,
Obsolete_Eccentricity = 8 , GoodnessOfFit = 9 , MinPixelZScore = 10 , MaxPixelZScore = 11 ,
SampleShift = 12 , LineShift = 13 , SampleSigma = 14 , LineSigma = 15 ,
APrioriSample = 16 , APrioriLine = 17 , Diameter = 18 , JigsawRejected = 19 ,
ResidualSample = 20 , ResidualLine = 21 , ResidualMagnitude = 22
}
enum InternalPointerType { None , Point , Measure , ImageAndNet }
Public Member Functions
MeasureLeafItem (ControlMeasure *cm, int avgCharWidth, AbstractTreeItem *parent=0)
virtual ~MeasureLeafItem ()
virtual QVariant getData () const
virtual QVariant getData (QString columnTitle) const
virtual void setData (QString const &columnTitle, QString const &newData)
bool isDataEditable (QString columnTitle) const
virtual void deleteSource ()
virtual InternalPointerType getPointerType () const
virtual void * getPointer () const
virtual bool hasMeasure (ControlMeasure *) const
AbstractTreeItem * parent () const
void setParent (AbstractTreeItem *newParent)
int row () const
virtual void addChild (AbstractTreeItem *child)=0
virtual QList< AbstractTreeItem * > getChildren () const =0
virtual AbstractTreeItem * childAt (int row) const =0
virtual int childCount () const =0
virtual AbstractTreeItem * getFirstVisibleChild () const =0
virtual AbstractTreeItem * getLastVisibleChild () const =0
virtual int indexOf (AbstractTreeItem *child) const =0
virtual void setFirstVisibleChild (AbstractTreeItem *child)=0
virtual void setLastVisibleChild (AbstractTreeItem *child)=0
virtual QString getFormattedData () const
virtual QString getFormattedData (QString columnTitle) const
virtual bool hasImage (QString imageSerial) const
virtual bool hasPoint (ControlPoint *) const
virtual AbstractTreeItem * getNextVisiblePeer () const
virtual void setNextVisiblePeer (AbstractTreeItem *next)
virtual void setExpanded (bool newState)
virtual bool isExpanded () const
virtual void setSelected (bool newState)
virtual void setSelectable (bool newSelectable)
virtual bool isSelected () const
virtual bool isSelectable () const
virtual void setVisible (bool newState)
virtual bool isVisible () const
virtual int getDataWidth () const
virtual int getDepth () const
virtual void setLastVisibleFilteredItem (AbstractTreeItem *item)
virtual const AbstractTreeItem * getLastVisibleFilteredItem () const
virtual AbstractTreeItem * childAt (int row) const
virtual QList< AbstractTreeItem * > getChildren () const
virtual int indexOf (AbstractTreeItem *child) const
virtual int childCount () const
virtual void addChild (AbstractTreeItem *child)
virtual AbstractTreeItem * getFirstVisibleChild () const
virtual AbstractTreeItem * getLastVisibleChild () const
virtual void setFirstVisibleChild (AbstractTreeItem *)
virtual void setLastVisibleChild (AbstractTreeItem *)
Static Public Member Functions
static QString getColumnName (Column)
static Column getColumn (QString)
static TableColumnList * createColumns ()
Static Public Attributes
static const int COLS = 23
Protected Member Functions
virtual void sourceDeleted ()
virtual void calcDataWidth (int avgCharWidth)
Static Protected Member Functions
static double catchNull (QString)
static QString catchNull (QVariant)
Detailed Description
A leaf node in the tree structure that represents a control measure.
This class represents a leaf node in the tree model and has a control measure as data. When created, it was used in the point model to show which control measures are in a control point or on an image.
Author
????-??-?? Eric Hyer
Member Enumeration Documentation
Column
enum Isis::AbstractMeasureItem::Column inherited
Enumerator
PointId
ImageId
Sample
Line
EditLock
Ignored
Reference
Type
Obsolete_Eccentricity
GoodnessOfFit
MinPixelZScore
MaxPixelZScore
SampleShift
LineShift
SampleSigma
LineSigma
APrioriSample
APrioriLine
Diameter
JigsawRejected
ResidualSample
ResidualLine
ResidualMagnitude
InternalPointerType
enum Isis::AbstractTreeItem::InternalPointerType inherited
Enumerator
None
Point
Measure
ImageAndNet
Constructor & Destructor Documentation
MeasureLeafItem()
Isis::MeasureLeafItem::MeasureLeafItem (ControlMeasure * cm, int avgCharWidth, AbstractTreeItem * parent = 0)
~MeasureLeafItem()
Isis::MeasureLeafItem::~MeasureLeafItem () virtual
Member Function Documentation
addChild() [1/2]
void Isis::AbstractLeafItem::addChild (AbstractTreeItem * child) virtual inherited
Implements Isis::AbstractTreeItem.
References _FILEINFO_, and Isis::IException::Programmer.
addChild() [2/2]
virtual void Isis::AbstractTreeItem::addChild (AbstractTreeItem * child) pure virtual inherited
Implemented in Isis::PointParentItem, Isis::ConnectionParentItem, Isis::AbstractParentItem, and Isis::AbstractLeafItem.
calcDataWidth()
void Isis::AbstractTreeItem::calcDataWidth (int avgCharWidth) protected virtual inherited
References _FILEINFO_, Isis::AbstractTreeItem::getFormattedData(), and Isis::IException::Programmer.
Referenced by Isis::AbstractImageItem::AbstractImageItem(), Isis::AbstractMeasureItem::AbstractMeasureItem(), Isis::AbstractPointItem::AbstractPointItem(), and Isis::BusyLeafItem::BusyLeafItem().
catchNull() [1/2]
double Isis::AbstractTreeItem::catchNull (QString str) static protected inherited
References Isis::Null.
Referenced by Isis::AbstractTreeItem::getFormattedData(), Isis::AbstractMeasureItem::setData(), and Isis::AbstractPointItem::setData().
catchNull() [2/2]
QString Isis::AbstractTreeItem::catchNull (QVariant data) static protected inherited
References Isis::Double, and Isis::Null.
childAt() [1/2]
AbstractTreeItem * Isis::AbstractLeafItem::childAt (int row) const virtual inherited
Implements Isis::AbstractTreeItem.
References _FILEINFO_, and Isis::IException::Programmer.
childAt() [2/2]
virtual AbstractTreeItem* Isis::AbstractTreeItem::childAt (int row) const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::AbstractTreeItem::hasImage(), Isis::AbstractTreeItem::hasMeasure(), and Isis::AbstractTreeItem::hasPoint().
childCount() [1/2]
int Isis::AbstractLeafItem::childCount () const virtual inherited
Implements Isis::AbstractTreeItem.
childCount() [2/2]
virtual int Isis::AbstractTreeItem::childCount () const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::AbstractTreeItem::hasImage(), Isis::AbstractTreeItem::hasMeasure(), and Isis::AbstractTreeItem::hasPoint().
createColumns()
TableColumnList * Isis::AbstractMeasureItem::createColumns () static inherited
References Isis::TableColumnList::append(), Isis::AbstractMeasureItem::APrioriLine, Isis::AbstractMeasureItem::APrioriSample, Isis::AbstractMeasureItem::Diameter, Isis::AbstractMeasureItem::EditLock, Isis::AbstractMeasureItem::getColumnName(), Isis::AbstractMeasureItem::GoodnessOfFit, Isis::AbstractMeasureItem::Ignored, Isis::AbstractMeasureItem::ImageId, Isis::AbstractMeasureItem::JigsawRejected, Isis::AbstractMeasureItem::Line, Isis::AbstractMeasureItem::LineShift, Isis::AbstractMeasureItem::LineSigma, Isis::AbstractMeasureItem::MaxPixelZScore, Isis::AbstractMeasureItem::MinPixelZScore, Isis::AbstractMeasureItem::Obsolete_Eccentricity, Isis::AbstractMeasureItem::PointId, Isis::AbstractMeasureItem::Reference, Isis::AbstractMeasureItem::ResidualLine, Isis::AbstractMeasureItem::ResidualMagnitude, Isis::AbstractMeasureItem::ResidualSample, Isis::AbstractMeasureItem::Sample, Isis::AbstractMeasureItem::SampleShift, Isis::AbstractMeasureItem::SampleSigma, and Isis::AbstractMeasureItem::Type.
Referenced by Isis::MeasureTableModel::createColumns().
deleteSource()
void Isis::AbstractMeasureItem::deleteSource () virtual inherited
Implements Isis::AbstractTreeItem.
References _FILEINFO_, Isis::ControlPoint::Delete(), Isis::AbstractMeasureItem::getColumnName(), Isis::AbstractTreeItem::getFormattedData(), Isis::ControlMeasure::IsEditLocked(), Isis::ControlPoint::IsEditLocked(), Isis::ControlMeasure::Parent(), Isis::AbstractMeasureItem::PointId, and Isis::IException::User.
getChildren() [1/2]
QList< AbstractTreeItem * > Isis::AbstractLeafItem::getChildren () const virtual inherited
Implements Isis::AbstractTreeItem.
References _FILEINFO_, and Isis::IException::Programmer.
getChildren() [2/2]
virtual QList< AbstractTreeItem * > Isis::AbstractTreeItem::getChildren () const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::TableViewContent::mouseMoveEvent(), Isis::TableViewContent::mousePressEvent(), and Isis::TreeViewContent::mousePressEvent().
getColumn()
AbstractMeasureItem::Column Isis::AbstractMeasureItem::getColumn (QString columnTitle) static inherited
References _FILEINFO_, Isis::AbstractMeasureItem::COLS, Isis::AbstractMeasureItem::getColumnName(), and Isis::IException::Programmer.
Referenced by Isis::AbstractMeasureItem::getData(), Isis::MeasureTableModel::getMeasureWarningMessage(), Isis::MeasureTableDelegate::getWidget(), Isis::AbstractMeasureItem::isDataEditable(), Isis::MeasureTableDelegate::readData(), Isis::MeasureTableDelegate::saveData(), and Isis::AbstractMeasureItem::setData().
getColumnName()
QString Isis::AbstractMeasureItem::getColumnName (Column col) static inherited
References Isis::AbstractMeasureItem::APrioriLine, Isis::AbstractMeasureItem::APrioriSample, Isis::AbstractMeasureItem::Diameter, Isis::AbstractMeasureItem::EditLock, Isis::AbstractMeasureItem::GoodnessOfFit, Isis::AbstractMeasureItem::Ignored, Isis::AbstractMeasureItem::ImageId, Isis::AbstractMeasureItem::JigsawRejected, Isis::AbstractMeasureItem::Line, Isis::AbstractMeasureItem::LineShift, Isis::AbstractMeasureItem::LineSigma, Isis::AbstractMeasureItem::MaxPixelZScore, Isis::AbstractMeasureItem::MinPixelZScore, Isis::AbstractMeasureItem::Obsolete_Eccentricity, Isis::AbstractMeasureItem::PointId, Isis::AbstractMeasureItem::Reference, Isis::AbstractMeasureItem::ResidualLine, Isis::AbstractMeasureItem::ResidualMagnitude, Isis::AbstractMeasureItem::ResidualSample, Isis::AbstractMeasureItem::Sample, Isis::AbstractMeasureItem::SampleShift, Isis::AbstractMeasureItem::SampleSigma, and Isis::AbstractMeasureItem::Type.
Referenced by Isis::AbstractMeasureItem::createColumns(), Isis::AbstractMeasureItem::deleteSource(), Isis::AbstractMeasureItem::getColumn(), Isis::AbstractMeasureItem::getData(), Isis::MeasureTableModel::getMeasureWarningMessage(), Isis::CnetEditorWidget::readSettings(), and Isis::CnetEditorWidget::writeSettings().
getData() [1/2]
QVariant Isis::AbstractMeasureItem::getData () const virtual inherited
Implements Isis::AbstractTreeItem.
References Isis::AbstractMeasureItem::getColumnName(), and Isis::AbstractMeasureItem::ImageId.
getData() [2/2]
QVariant Isis::AbstractMeasureItem::getData (QString columnTitle) const virtual inherited
Implements Isis::AbstractTreeItem.
References Isis::AbstractMeasureItem::APrioriLine, Isis::AbstractMeasureItem::APrioriSample, Isis::AbstractMeasureItem::Diameter, Isis::AbstractMeasureItem::EditLock, Isis::ControlMeasure::GetAprioriLine(), Isis::ControlMeasure::GetAprioriSample(), Isis::AbstractMeasureItem::getColumn(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::ControlMeasure::GetDiameter(), Isis::ControlPoint::GetId(), Isis::CnetDisplayProperties::getInstance(), Isis::ControlMeasure::GetLine(), Isis::ControlMeasure::GetLineResidual(), Isis::ControlMeasure::GetLineShift(), Isis::ControlMeasure::GetLineSigma(), Isis::ControlMeasure::GetLogData(), Isis::ControlMeasureLogData::GetNumericalValue(), Isis::ControlPoint::GetRefMeasure(), Isis::ControlMeasure::GetResidualMagnitude(), Isis::ControlMeasure::GetSample(), Isis::ControlMeasure::GetSampleResidual(), Isis::ControlMeasure::GetSampleShift(), Isis::ControlMeasure::GetSampleSigma(), Isis::ControlMeasure::GetType(), Isis::ControlMeasureLogData::GoodnessOfFit, Isis::AbstractMeasureItem::GoodnessOfFit, Isis::AbstractMeasureItem::Ignored, Isis::AbstractMeasureItem::ImageId, Isis::ControlMeasure::IsEditLocked(), Isis::ControlMeasure::IsIgnored(), Isis::ControlMeasure::IsRejected(), Isis::AbstractMeasureItem::JigsawRejected, Isis::AbstractMeasureItem::Line, Isis::AbstractMeasureItem::LineShift, Isis::AbstractMeasureItem::LineSigma, Isis::ControlMeasureLogData::MaximumPixelZScore, Isis::AbstractMeasureItem::MaxPixelZScore, Isis::ControlMeasure::MeasureTypeToString(), Isis::ControlMeasureLogData::MinimumPixelZScore, Isis::AbstractMeasureItem::MinPixelZScore, Isis::ControlMeasureLogData::Obsolete_Eccentricity, Isis::AbstractMeasureItem::Obsolete_Eccentricity, Isis::ControlMeasure::Parent(), Isis::AbstractMeasureItem::PointId, Isis::AbstractMeasureItem::Reference, Isis::AbstractMeasureItem::ResidualLine, Isis::AbstractMeasureItem::ResidualMagnitude, Isis::AbstractMeasureItem::ResidualSample, Isis::AbstractMeasureItem::Sample, Isis::AbstractMeasureItem::SampleShift, Isis::AbstractMeasureItem::SampleSigma, and Isis::AbstractMeasureItem::Type.
getDataWidth()
int Isis::AbstractTreeItem::getDataWidth () const virtual inherited
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by Isis::AbstractTreeModel::getVisibleSize().
getDepth()
int Isis::AbstractTreeItem::getDepth () const virtual inherited
References Isis::AbstractTreeItem::parent().
Referenced by Isis::AbstractTreeModel::getVisibleSize().
getFirstVisibleChild() [1/2]
AbstractTreeItem * Isis::AbstractLeafItem::getFirstVisibleChild () const virtual inherited
Implements Isis::AbstractTreeItem.
getFirstVisibleChild() [2/2]
virtual AbstractTreeItem* Isis::AbstractTreeItem::getFirstVisibleChild () const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::TreeViewContent::mouseMoveEvent(), and Isis::TreeViewContent::mousePressEvent().
getFormattedData() [1/2]
QString Isis::AbstractTreeItem::getFormattedData () const virtual inherited
References Isis::AbstractTreeItem::catchNull(), and Isis::AbstractTreeItem::getData().
Referenced by Isis::AbstractTreeItem::calcDataWidth(), Isis::AbstractMeasureItem::deleteSource(), Isis::AbstractPointItem::deleteSource(), Isis::MeasureTableModel::getMeasureWarningMessage(), Isis::PointTableModel::getPointWarningMessage(), Isis::MeasureTableDelegate::readData(), and Isis::PointTableDelegate::readData().
getFormattedData() [2/2]
QString Isis::AbstractTreeItem::getFormattedData (QString columnTitle) const virtual inherited
References Isis::AbstractTreeItem::catchNull(), and Isis::AbstractTreeItem::getData().
getLastVisibleChild() [1/2]
AbstractTreeItem * Isis::AbstractLeafItem::getLastVisibleChild () const virtual inherited
Implements Isis::AbstractTreeItem.
getLastVisibleChild() [2/2]
virtual AbstractTreeItem* Isis::AbstractTreeItem::getLastVisibleChild () const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::AbstractTreeModel::getItems().
getLastVisibleFilteredItem()
const AbstractTreeItem * Isis::AbstractTreeItem::getLastVisibleFilteredItem () const virtual inherited
Reimplemented in Isis::RootItem.
getNextVisiblePeer()
AbstractTreeItem * Isis::AbstractTreeItem::getNextVisiblePeer () const virtual inherited
Referenced by Isis::AbstractTreeModel::getVisibleTopLevelItemCount().
getPointer()
void * Isis::AbstractMeasureItem::getPointer () const virtual inherited
Implements Isis::AbstractTreeItem.
getPointerType()
AbstractTreeItem::InternalPointerType Isis::AbstractMeasureItem::getPointerType () const virtual inherited
Implements Isis::AbstractTreeItem.
References Isis::AbstractTreeItem::Measure.
hasImage()
bool Isis::AbstractTreeItem::hasImage (QString imageSerial) const virtual inherited
Reimplemented in Isis::AbstractImageItem.
References Isis::AbstractTreeItem::childAt(), Isis::AbstractTreeItem::childCount(), and Isis::AbstractTreeItem::hasImage().
Referenced by Isis::AbstractImageItem::hasImage(), and Isis::AbstractTreeItem::hasImage().
hasMeasure()
bool Isis::AbstractMeasureItem::hasMeasure (ControlMeasure * m) const virtual inherited
Reimplemented from Isis::AbstractTreeItem.
hasPoint()
bool Isis::AbstractTreeItem::hasPoint (ControlPoint * point) const virtual inherited
Reimplemented in Isis::AbstractPointItem.
References Isis::AbstractTreeItem::childAt(), Isis::AbstractTreeItem::childCount(), and Isis::AbstractTreeItem::hasPoint().
Referenced by Isis::AbstractTreeItem::hasPoint().
indexOf() [1/2]
int Isis::AbstractLeafItem::indexOf (AbstractTreeItem * child) const virtual inherited
Implements Isis::AbstractTreeItem.
References _FILEINFO_, and Isis::IException::Programmer.
indexOf() [2/2]
virtual int Isis::AbstractTreeItem::indexOf (AbstractTreeItem * child) const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::AbstractTreeItem::row().
isDataEditable()
bool Isis::AbstractMeasureItem::isDataEditable (QString columnTitle) const virtual inherited
Implements Isis::AbstractTreeItem.
References Isis::AbstractMeasureItem::EditLock, Isis::AbstractMeasureItem::getColumn(), Isis::ControlMeasure::IsEditLocked(), Isis::ControlPoint::IsEditLocked(), and Isis::ControlMeasure::Parent().
isExpanded()
bool Isis::AbstractTreeItem::isExpanded () const virtual inherited
Referenced by Isis::TreeViewContent::mouseDoubleClickEvent(), and Isis::TreeViewContent::mouseReleaseEvent().
isSelectable()
bool Isis::AbstractTreeItem::isSelectable () const virtual inherited
Reimplemented in Isis::BusyLeafItem.
Referenced by Isis::TreeViewContent::mouseMoveEvent(), and Isis::TreeViewContent::mousePressEvent().
isSelected()
bool Isis::AbstractTreeItem::isSelected () const virtual inherited
Referenced by Isis::AbstractTreeModel::getSelectedItems(), Isis::TableViewContent::mousePressEvent(), and Isis::TreeViewContent::mousePressEvent().
isVisible()
bool Isis::AbstractTreeItem::isVisible () const virtual inherited
parent()
AbstractTreeItem * Isis::AbstractTreeItem::parent () const inherited
Referenced by Isis::AbstractTreeItem::getDepth(), Isis::AbstractTreeModel::getItems(), Isis::PointTableModel::handleTreeSelectionChanged(), and Isis::TableViewContent::mousePressEvent().
row()
int Isis::AbstractTreeItem::row () const inherited
References Isis::AbstractTreeItem::indexOf().
Referenced by Isis::AbstractParentItem::childAt().
setData()
void Isis::AbstractMeasureItem::setData (QString const & columnTitle, QString const & newData) virtual inherited
Implements Isis::AbstractTreeItem.
References Isis::AbstractMeasureItem::APrioriLine, Isis::AbstractMeasureItem::APrioriSample, Isis::AbstractTreeItem::catchNull(), Isis::AbstractMeasureItem::Diameter, Isis::AbstractMeasureItem::EditLock, Isis::AbstractMeasureItem::getColumn(), Isis::CnetDisplayProperties::getInstance(), Isis::ControlMeasure::GetLine(), Isis::ControlMeasure::GetLineResidual(), Isis::ControlMeasure::GetSample(), Isis::ControlMeasure::GetSampleResidual(), Isis::CnetDisplayProperties::getSerialNumber(), Isis::ControlMeasureLogData::GoodnessOfFit, Isis::AbstractMeasureItem::GoodnessOfFit, Isis::AbstractMeasureItem::Ignored, Isis::AbstractMeasureItem::ImageId, Isis::AbstractMeasureItem::JigsawRejected, Isis::AbstractMeasureItem::Line, Isis::AbstractMeasureItem::LineShift, Isis::AbstractMeasureItem::LineSigma, Isis::ControlMeasureLogData::MaximumPixelZScore, Isis::AbstractMeasureItem::MaxPixelZScore, Isis::ControlMeasureLogData::MinimumPixelZScore, Isis::AbstractMeasureItem::MinPixelZScore, Isis::ControlMeasureLogData::Obsolete_Eccentricity, Isis::AbstractMeasureItem::Obsolete_Eccentricity, Isis::AbstractMeasureItem::PointId, Isis::AbstractMeasureItem::Reference, Isis::AbstractMeasureItem::ResidualLine, Isis::AbstractMeasureItem::ResidualMagnitude, Isis::AbstractMeasureItem::ResidualSample, Isis::AbstractMeasureItem::Sample, Isis::AbstractMeasureItem::SampleShift, Isis::AbstractMeasureItem::SampleSigma, Isis::ControlMeasure::SetAprioriLine(), Isis::ControlMeasure::SetAprioriSample(), Isis::ControlMeasure::SetCoordinate(), Isis::ControlMeasure::SetCubeSerialNumber(), Isis::ControlMeasure::SetDiameter(), Isis::ControlMeasure::SetEditLock(), Isis::ControlMeasure::SetIgnored(), Isis::ControlMeasure::SetLineSigma(), Isis::ControlMeasure::SetResidual(), Isis::ControlMeasure::SetSampleSigma(), Isis::ControlMeasure::SetType(), Isis::ControlMeasure::StringToMeasureType(), and Isis::AbstractMeasureItem::Type.
setExpanded()
void Isis::AbstractTreeItem::setExpanded (bool newState) virtual inherited
Referenced by Isis::TreeViewContent::mouseDoubleClickEvent(), Isis::TreeViewContent::mouseReleaseEvent(), and Isis::RootItem::RootItem().
setFirstVisibleChild() [1/2]
void Isis::AbstractLeafItem::setFirstVisibleChild (AbstractTreeItem *) virtual inherited
Implements Isis::AbstractTreeItem.
References _FILEINFO_, and Isis::IException::Programmer.
setFirstVisibleChild() [2/2]
virtual void Isis::AbstractTreeItem::setFirstVisibleChild (AbstractTreeItem * child) pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
setLastVisibleChild() [1/2]
void Isis::AbstractLeafItem::setLastVisibleChild (AbstractTreeItem *) virtual inherited
Implements Isis::AbstractTreeItem.
References _FILEINFO_, and Isis::IException::Programmer.
setLastVisibleChild() [2/2]
virtual void Isis::AbstractTreeItem::setLastVisibleChild (AbstractTreeItem * child) pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
setLastVisibleFilteredItem()
void Isis::AbstractTreeItem::setLastVisibleFilteredItem (AbstractTreeItem * item) virtual inherited
Reimplemented in Isis::RootItem.
References _FILEINFO_, and Isis::IException::Programmer.
setNextVisiblePeer()
void Isis::AbstractTreeItem::setNextVisiblePeer (AbstractTreeItem * next) virtual inherited
setParent()
void Isis::AbstractTreeItem::setParent (AbstractTreeItem * newParent) inherited
Referenced by Isis::AbstractParentItem::addChild().
setSelectable()
void Isis::AbstractTreeItem::setSelectable (bool newSelectable) virtual inherited
setSelected()
void Isis::AbstractTreeItem::setSelected (bool newState) virtual inherited
Referenced by Isis::TableViewContent::mouseMoveEvent(), Isis::TableViewContent::mousePressEvent(), and Isis::TreeViewContent::mousePressEvent().
setVisible()
void Isis::AbstractTreeItem::setVisible (bool newState) virtual inherited
sourceDeleted()
void Isis::AbstractMeasureItem::sourceDeleted () protected virtual inherited
Implements Isis::AbstractTreeItem.
Referenced by Isis::AbstractMeasureItem::AbstractMeasureItem().
Member Data Documentation
COLS
const int Isis::AbstractMeasureItem::COLS = 23 static inherited
Referenced by Isis::AbstractMeasureItem::getColumn().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/MeasureLeafItem.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/MeasureLeafItem.cpp