Isis Developer Reference: Isis::MainWindow Class Reference
Isis::MainWindow Class Reference
Base class for the Qisis main windows.
#include <MainWindow.h>
Public Member Functions
MainWindow (QString title, QWidget *parent=0, Qt::WindowFlags flags=Qt::WindowFlags())
Mainwindow constructor.
virtual ~MainWindow ()
Free allocated memory by from this instance.
Static Public Member Functions
static QString settingsFileName (QString objectTitle)
Protected Member Functions
virtual void closeEvent (QCloseEvent *event)
This method is overridden so that we can be sure to write the current settings of the Main window.
virtual void readSettings (QSize defaultSize=QSize())
This method ensure that the settings get written even if the Main window was only hidden, not closed.
QString settingsFileName () const
Detailed Description
Base class for the Qisis main windows.
Author
????-??-?? Stacy Alley
Constructor & Destructor Documentation
MainWindow()
Isis::MainWindow::MainWindow (QString title, QWidget * parent = 0, Qt::WindowFlags flags = Qt::WindowFlags())
Mainwindow constructor.
Parameters
title
parent
flags
~MainWindow()
Isis::MainWindow::~MainWindow () virtual
Free allocated memory by from this instance.
Member Function Documentation
closeEvent()
void Isis::MainWindow::closeEvent (QCloseEvent * event) protected virtual
This method is overridden so that we can be sure to write the current settings of the Main window.
Parameters
event
Reimplemented in Isis::ViewportMainWindow, and Isis::TableMainWindow.
Referenced by Isis::TableMainWindow::closeEvent(), and Isis::ViewportMainWindow::closeEvent().
readSettings()
void Isis::MainWindow::readSettings (QSize defaultSize = QSize()) protected virtual
This method ensure that the settings get written even if the Main window was only hidden, not closed.
Parameters
event This method is called from the constructor so that when the Main window is created, it know's it's size and location.
References settingsFileName().
Referenced by Isis::PlotWindow::PlotWindow(), Isis::TableMainWindow::TableMainWindow(), and Isis::ViewportMainWindow::ViewportMainWindow().
settingsFileName() [1/2]
QString Isis::MainWindow::settingsFileName () const protected
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by Isis::TableMainWindow::readColumnSettings(), Isis::TableMainWindow::readItemSettings(), Isis::BlinkTool::readSettings(), readSettings(), Isis::BlinkTool::writeSettings(), and Isis::TableMainWindow::writeSettings().
settingsFileName() [2/2]
QString Isis::MainWindow::settingsFileName (QString objectTitle) static
References _FILEINFO_, and Isis::IException::Programmer.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MainWindow/MainWindow.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MainWindow/MainWindow.cpp