Isis Developer Reference: Isis::CnetEditorSortConfigDialog Class Reference
Isis::CnetEditorSortConfigDialog Class Reference
Configure user's sorting settings for the cneteditor widget.
#include <CnetEditorSortConfigDialog.h>
Public Slots
void applySettings ()
Apply the user's current settings to the cneteditor widget.
void readSettings ()
Read the cneteditor widget's current settings and set the widget states to match.
Public Member Functions
CnetEditorSortConfigDialog (CnetEditorWidget *cnetWidget)
Create a config dialog that configures the given FeatureCnetEditorSort.
~CnetEditorSortConfigDialog ()
Clean up allocated memory.
Detailed Description
Configure user's sorting settings for the cneteditor widget.
This dialog enables the user to configure the sorting options in the cneteditor widget.
Author
2012-04-02 Steven Lambright and Jai Rideout
Constructor & Destructor Documentation
CnetEditorSortConfigDialog()
Isis::CnetEditorSortConfigDialog::CnetEditorSortConfigDialog (CnetEditorWidget * cnetWidget)
Create a config dialog that configures the given FeatureCnetEditorSort.
Parameters
tool The tool to read settings from and write settings to.
parent The qt-parent relationship parent.
References applySettings(), and readSettings().
~CnetEditorSortConfigDialog()
Isis::CnetEditorSortConfigDialog::~CnetEditorSortConfigDialog ()
Clean up allocated memory.
Member Function Documentation
applySettings
void Isis::CnetEditorSortConfigDialog::applySettings () slot
Apply the user's current settings to the cneteditor widget.
References readSettings().
Referenced by CnetEditorSortConfigDialog().
readSettings
void Isis::CnetEditorSortConfigDialog::readSettings () slot
Read the cneteditor widget's current settings and set the widget states to match.
References Isis::AbstractTableModel::getVisibleRowCount(), and Isis::AbstractTableModel::sortLimit().
Referenced by applySettings(), and CnetEditorSortConfigDialog().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/CnetEditorSortConfigDialog.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/CnetEditorSortConfigDialog.cpp