Isis Developer Reference: Isis::ControlMeasureEditWidget Class Reference
Isis::ControlMeasureEditWidget Class Reference
Point Editor Widget.
#include <ControlMeasureEditWidget.h>
Public Slots
bool setTemplateFile (QString)
Allows user to choose a new template file by opening a window from which to select a filename.
void setPoint (ControlPoint *editPoint, SerialNumberList *snList)
Set the Control Point for this widget.
void setLeftMeasure (ControlMeasure *leftMeasure, Cube *leftCube, QString pointId)
Set the measure displayed in the left ChipViewport.
void setRightMeasure (ControlMeasure *rightMeasure, Cube *rightCube, QString pointId)
Set the measure displayed in the right ChipViewport.
void colorizeSaveButton ()
Turn "Save Measure" button text to red.
void refreshChips ()
void saveChips ()
Slot to save registration chips to files and fire off qview.
Signals
void updateLeftView (double sample, double line)
void updateRightView (double sample, double line)
void measureSaved ()
void newControlNetwork (ControlNet *)
void setTemplateFailed (QString)
void stretchChipViewport (Stretch *, CubeViewport *)
Public Member Functions
ControlMeasureEditWidget (QWidget *parent=0, bool allowLeftMouse=false, bool useGeometry=true)
Constructs a ControlMeasureEditWidget widget.
~ControlMeasureEditWidget ()
Destructor.
QString templateFileName ()
Returns the template filename used for auto-registration.
void allowLeftMouse (bool allowMouse)
Set the option that allows mouse movements in the left ChipViewport.
void setLeftPosition (double sample, double line)
Set the tack position of the measure in the left ChipViewport.
void setRightPosition (double sample, double line)
Set the tack position of the measure in the right ChipViewport.
Detailed Description
Point Editor Widget.
Author
2008-09-09 Tracie Sucharski
Constructor & Destructor Documentation
ControlMeasureEditWidget()
Isis::ControlMeasureEditWidget::ControlMeasureEditWidget (QWidget * parent = 0, bool allowLeftMouse = false, bool useGeometry = true)
Constructs a ControlMeasureEditWidget widget.
Parameters
parent[in] Parent of widget
allowLeftMouse[in] Allow/Disallow mouse events on Left ChipViewport
useGeometry[in] Allow/Disallow geometry and rotation on right ChipViewport
Author
Tracie Sucharski
References allowLeftMouse().
~ControlMeasureEditWidget()
Isis::ControlMeasureEditWidget::~ControlMeasureEditWidget ()
Destructor.
Member Function Documentation
allowLeftMouse()
void Isis::ControlMeasureEditWidget::allowLeftMouse (bool allowMouse)
Set the option that allows mouse movements in the left ChipViewport.
Parameters
allowMouse Whether or not to allow mouse event on left chip viewport
Author
Tracie Sucharski
Referenced by ControlMeasureEditWidget().
colorizeSaveButton
void Isis::ControlMeasureEditWidget::colorizeSaveButton () slot
Turn "Save Measure" button text to red.
Author
2011-06-14 Tracie Sucharski
measureSaved
void Isis::ControlMeasureEditWidget::measureSaved () signal
newControlNetwork
void Isis::ControlMeasureEditWidget::newControlNetwork (ControlNet *) signal
refreshChips
void Isis::ControlMeasureEditWidget::refreshChips () slot
saveChips
void Isis::ControlMeasureEditWidget::saveChips () slot
Slot to save registration chips to files and fire off qview.
Author
2009-03-18 Tracie Sucharski
References Isis::AutoReg::FitChip(), Isis::ControlMeasure::GetLine(), Isis::ControlMeasure::GetSample(), Isis::AutoReg::RegistrationPatternChip(), Isis::AutoReg::RegistrationSearchChip(), Isis::ProgramLauncher::RunSystemCommand(), Isis::toString(), and Isis::Chip::Write().
setLeftMeasure
void Isis::ControlMeasureEditWidget::setLeftMeasure (ControlMeasure * leftMeasure, Cube * leftCube, QString pointId) slot
Set the measure displayed in the left ChipViewport.
Parameters
leftMeasure[in] Measure displayed in left ChipViewport
leftCube[in] Cube of measure displayed in left ChipViewport
pointId[in] Control point id associated with the left measure
Author
Tracie Sucharski
References Isis::ControlMeasure::GetLine(), Isis::ControlMeasure::GetSample(), Isis::Chip::Load(), Isis::ChipViewport::setChip(), and Isis::Chip::TackCube().
setLeftPosition()
void Isis::ControlMeasureEditWidget::setLeftPosition (double sample, double line)
Set the tack position of the measure in the left ChipViewport.
Parameters
sample[in] Sample of the tack position for the right ChipViewport
line[in] Line of the tack position for the left ChipViewport
References Isis::Chip::TackCube(), and updateLeftView().
setPoint
void Isis::ControlMeasureEditWidget::setPoint (ControlPoint * editPoint, SerialNumberList * snList) slot
Set the Control Point for this widget.
Parameters
editPoint[in] ControlPoint for this widget
snList[in] SerialNumberList associated with the control net containing the ControlPoint
setRightMeasure
void Isis::ControlMeasureEditWidget::setRightMeasure (ControlMeasure * rightMeasure, Cube * rightCube, QString pointId) slot
Set the measure displayed in the right ChipViewport.
Parameters
rightMeasure[in] Measure displayed in right ChipViewport
rightCube[in] Cube of measure displayed in right ChipViewport
pointId[in] Control point id associated with the measure
Author
Tracie Sucharski
References _FILEINFO_, Isis::ControlMeasure::GetLine(), Isis::ControlMeasure::GetSample(), Isis::Chip::Load(), Isis::ChipViewport::setChip(), Isis::Chip::TackCube(), Isis::IException::toString(), and Isis::IException::User.
setRightPosition()
void Isis::ControlMeasureEditWidget::setRightPosition (double sample, double line)
Set the tack position of the measure in the right ChipViewport.
Parameters
sample[in] Sample of the tack position for the right ChipViewport
line[in] Line of the tack position for the left ChipViewport
References Isis::Chip::TackCube(), and updateRightView().
setTemplateFailed
void Isis::ControlMeasureEditWidget::setTemplateFailed (QString) signal
Referenced by setTemplateFile().
setTemplateFile
bool Isis::ControlMeasureEditWidget::setTemplateFile (QString fn) slot
Allows user to choose a new template file by opening a window from which to select a filename.
This file is then registered and set as the new template.
Parameters
fn Template filename
Author
Tracie Sucharski
References _FILEINFO_, Isis::AutoRegFactory::Create(), Isis::IException::Io, setTemplateFailed(), and Isis::IException::toString().
stretchChipViewport
void Isis::ControlMeasureEditWidget::stretchChipViewport (Stretch * , CubeViewport *) signal
templateFileName()
QString Isis::ControlMeasureEditWidget::templateFileName () inline
Returns the template filename used for auto-registration.
Returns
QString Template filename
updateLeftView
void Isis::ControlMeasureEditWidget::updateLeftView (double sample, double line) signal
Referenced by setLeftPosition().
updateRightView
void Isis::ControlMeasureEditWidget::updateRightView (double sample, double line) signal
Referenced by setRightPosition().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ControlMeasureEditWidget/ControlMeasureEditWidget.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ControlMeasureEditWidget/ControlMeasureEditWidget.cpp