Isis Developer Reference: Isis::SurfacePoint Class Reference
Isis::SurfacePoint Class Reference
Geometry
This class defines a body-fixed surface point.
#include <SurfacePoint.h>
Public Types
enum CoordinateType { Latitudinal , Rectangular }
Defines the coordinate typ, units, and coordinate index for some of the output methods.
enum CoordUnits { Degrees , Kilometers , Meters , Radians }
enum CoordIndex { One =0 , Two =1 , Three =2 }
Public Member Functions
SurfacePoint ()
Constructs an empty SurfacePoint object.
SurfacePoint (const SurfacePoint &other)
Constructs a new SurfacePoint object from an existing SurfacePoint.
SurfacePoint (const Latitude &lat, const Longitude &lon, const Distance &radius)
Constructs a SurfacePoint object with a spherical point only.
SurfacePoint (const Latitude &lat, const Longitude &lon, const Distance &radius, const Angle &latSigma, const Angle &lonSigma, const Distance &radiusSigma)
Constructs a SurfacePoint object with a spherical point and its sigmas.
SurfacePoint (const Latitude &lat, const Longitude &lon, const Distance &radius, const boost::numeric::ublas::symmetric_matrix< double, boost::numeric::ublas::upper > &covar)
SurfacePoint (const Displacement &x, const Displacement &y, const Displacement &z)
Constructs a SurfacePoint object with a rectangular point only.
SurfacePoint (const Displacement &x, const Displacement &y, const Displacement &z, const Distance &xSigma, const Distance &ySigma, const Distance &zSigma)
Constructs a SurfacePoint object with a rectangular point and sigmas.
SurfacePoint (const Displacement &x, const Displacement &y, const Displacement &z, const boost::numeric::ublas::symmetric_matrix< double, boost::numeric::ublas::upper > &covar)
~SurfacePoint ()
Destroys a SurfacePoint object/.
void SetRectangular (const Displacement &x, const Displacement &y, const Displacement &z, const Distance &xSigma=Distance(), const Distance &ySigma=Distance(), const Distance &zSigma=Distance())
Set surface point in rectangular body-fixed coordinates wtih optional sigmas.
void SetRectangular (const Displacement x, const Displacement y, const Displacement z, const boost::numeric::ublas::symmetric_matrix< double, boost::numeric::ublas::upper > &covar)
void SetRectangularCoordinates (const Displacement &x, const Displacement &y, const Displacement &z)
Set surface point in rectangular coordinates.
void SetRectangularSigmas (const Distance &xSigma, const Distance &ySigma, const Distance &zSigma)
Set surface point and sigmas in rectangular coordinates and convert to planetocentric.
void SetRectangularMatrix (const boost::numeric::ublas::symmetric_matrix< double, boost::numeric::ublas::upper > &covar, SurfacePoint::CoordUnits units=SurfacePoint::Meters)
Set rectangular covariance matrix and store in units of km**2.
void SetSpherical (const Latitude &lat, const Longitude &lon, const Distance &radius, const Angle &latSigma=Angle(), const Angle &lonSigma=Angle(), const Distance &radiusSigma=Distance())
Set surface point and covariance matrix in planetocentric coordinates and convert to rectangular (Latitude, Longitude in degrees, Radius in meters; matrix in radians and radians**2)
void SetSpherical (const Latitude &lat, const Longitude &lon, const Distance &radius, const boost::numeric::ublas::symmetric_matrix< double, boost::numeric::ublas::upper > &covar)
void SetSphericalCoordinates (const Latitude &lat, const Longitude &lon, const Distance &radius)
Update spherical coordinates (lat/lon/radius)
void SetSphericalMatrix (const boost::numeric::ublas::symmetric_matrix< double, boost::numeric::ublas::upper > &covar, SurfacePoint::CoordUnits units=SurfacePoint::Meters)
Set spherical covariance matrix.
void SetSphericalSigmas (const Angle &latSigma, const Angle &lonSigma, const Distance &radiusSigma)
Set the spherical sigmas into the spherical variance/covariance matrix in diagonal units of radians^2, radians^2, km^2.
void SetSphericalSigmasDistance (const Distance &latSigma, const Distance &lonSigma, const Distance &radiusSigma)
Set the spherical sigmas (in Distance units) into the spherical variance/covariance matrix.
void ResetLocalRadius (const Distance &radius)
This method resets the local radius of a SurfacePoint.
bool Valid () const
void SetMatrix (CoordinateType type, const boost::numeric::ublas::symmetric_matrix< double, boost::numeric::ublas::upper > &covar)
Set the covariance matrix.
std::vector< double > Partial (CoordinateType type, CoordIndex index)
Compute partial derivative of conversion from body-fixed coordinates to the specified.
double GetCoord (CoordinateType type, CoordIndex index, CoordUnits units)
This method returns a coordinate of a SurfacePoint.
double GetSigma (CoordinateType type, CoordIndex index, CoordUnits units)
This method returns a sigma of a SurfacePoint coordinate.
Distance GetSigmaDistance (CoordinateType type, CoordIndex index)
This method returns a sigma of a SurfacePoint coordinate as a Distance.
double GetWeight (CoordinateType type, CoordIndex index)
This method returns the weight of a SurfacePoint coordinate Note: At this time a units argument is not included.
Displacement GetX () const
Displacement GetY () const
Displacement GetZ () const
Distance GetXSigma () const
Distance GetYSigma () const
Distance GetZSigma () const
double GetXWeight () const
Return X weight for bundle adjustment Units are 1/(kilometers)^2.
double GetYWeight () const
Return Y weight for bundle adjustment Units are 1/(kilometers)^2.
double GetZWeight () const
Return Z weight for bundle adjustment Units are 1/(kilometers)^2.
boost::numeric::ublas::symmetric_matrix< double, boost::numeric::ublas::upper > GetRectangularMatrix (SurfacePoint::CoordUnits units=SurfacePoint::Meters) const
Latitude GetLatitude () const
Return the body-fixed latitude for the surface point.
Longitude GetLongitude () const
Return the body-fixed longitude for the surface point.
Distance GetLocalRadius () const
Return the radius of the surface point.
Angle GetLatSigma () const
Distance GetLatSigmaDistance () const
Return the latitude sigma as a Distance.
double GetLatWeight () const
Return latitude weight for bundle adjustment Units are 1/(radians)^2.
Angle GetLonSigma () const
Distance GetLonSigmaDistance () const
Return the longitude sigma in meters.
double GetLonWeight () const
Return longitude weight for bundle adjustment Units are 1/(radians)^2.
Distance GetLocalRadiusSigma () const
double GetLocalRadiusWeight () const
Return radius weight for bundle adjustment Units are 1/(kilometers)^2.
boost::numeric::ublas::symmetric_matrix< double, boost::numeric::ublas::upper > GetSphericalMatrix (SurfacePoint::CoordUnits units=SurfacePoint::Meters) const
double DisplacementToDouble (Displacement disp, CoordUnits units)
This method returns a double version of a Displacement in the specified units.
double DistanceToDouble (Distance dist, CoordUnits units)
This method returns a double version of a Distance in the specified units.
double MetersToLatitude (double latLength)
This method returns an angular measure of a distance in the direction of and relative to the latitude of the SurfacePoint.
double MetersToLongitude (double lonLength)
This method returns an angular measure in radians of a distance in the direction of and relative to the longitude of the SurfacePoint.
double LatitudeToMeters (double latitude) const
This method returns a Displacement of an Angle relative to the current SurfacePoint latitude.
double LongitudeToMeters (double longitude) const
This method returns a length in meters version of a delta longitude angle in radians relative to the current SurfacePoint longitude.
double LatToDouble (Latitude lat, CoordUnits units)
This method returns a double version of a Latitude in the specified units.
double LonToDouble (Longitude lon, CoordUnits units)
This method returns a double version of a Longitude in the specified units.
Distance GetDistanceToPoint (const SurfacePoint &other) const
Computes and returns the distance between two surface points.
Distance GetDistanceToPoint (const SurfacePoint &other, const Distance &sphereRadius) const
Computes and returns the distance between two surface points, assuming both points are on a sphere with the given radius.
std::vector< double > LatitudinalDerivative (CoordIndex index)
Compute partial derivative of the conversion of the latitudinal coordinates to body-fixed rectangular coordinates with respect to the indicated coordinate.
std::vector< double > RectangularDerivative (CoordIndex index)
Compute partial derivative of the body-fixed rectangular coordinates with respect to the indicated coordinate.
void ToNaifArray (double naifOutput[3]) const
A naif array is a c-style array of size 3.
void FromNaifArray (const double naifValues[3])
A naif array is a c-style array of size 3.
bool operator== (const SurfacePoint &other) const
SurfacePoint & operator= (const SurfacePoint &other)
Static Public Member Functions
static CoordinateType stringToCoordinateType (QString type)
This method converts the given string value to a SurfacePoint::CoordinateType enumeration.
static QString coordinateTypeToString (CoordinateType type)
Converts the given SurfacePoint::CoordinateType enumeration to a string.
Detailed Description
This class defines a body-fixed surface point.
This class is a container for body-fixed surface points. It provides methods to set and present the coordinates of surface points in various usable units to support projection of image points to the ground and bundle adjustment.
Author
2010-07-30 Tracie Sucharski, Ken L. Edmunson, and Debbie A. Cook
Member Enumeration Documentation
CoordinateType
enum Isis::SurfacePoint::CoordinateType
Defines the coordinate typ, units, and coordinate index for some of the output methods.
Enumerator
Latitudinal
Planetocentric latitudinal (lat/lon/rad) coordinates.
Rectangular
Body-fixed rectangular x/y/z coordinates.
CoordIndex
enum Isis::SurfacePoint::CoordIndex
Enumerator
One
Two
Three
CoordUnits
enum Isis::SurfacePoint::CoordUnits
Enumerator
Degrees
Kilometers
Meters
Radians
Constructor & Destructor Documentation
SurfacePoint() [1/8]
Isis::SurfacePoint::SurfacePoint ()
Constructs an empty SurfacePoint object.
SurfacePoint() [2/8]
Isis::SurfacePoint::SurfacePoint (const SurfacePoint & other)
Constructs a new SurfacePoint object from an existing SurfacePoint.
SurfacePoint() [3/8]
Isis::SurfacePoint::SurfacePoint (const Latitude & lat, const Longitude & lon, const Distance & radius)
Constructs a SurfacePoint object with a spherical point only.
Parameters
lat The latitude of the surface point
lon The longitude of the surface point
radius The radius of the surface point
SurfacePoint() [4/8]
Isis::SurfacePoint::SurfacePoint (const Latitude & lat, const Longitude & lon, const Distance & radius, const Angle & latSigma, const Angle & lonSigma, const Distance & radiusSigma)
Constructs a SurfacePoint object with a spherical point and its sigmas.
Parameters
lat The latitude of the surface point
lon The longitude of the surface point
radius The radius of the surface point
          The sigmas indicate the accuracy of the point.  For instance,
          a latitude sigma of 5 degrees would indicate that the
          latitiude value could have an error or + or - 5 degrees.
sigmaLat The sigma of the latitude
sigmaLon The sigma of the longitude
sigmaRadius The sigma of the local radius
SurfacePoint() [5/8]
Isis::SurfacePoint::SurfacePoint (const Latitude & lat, const Longitude & lon, const Distance & radius, const boost::numeric::ublas::symmetric_matrix< double, boost::numeric::ublas::upper > & covar)
SurfacePoint() [6/8]
Isis::SurfacePoint::SurfacePoint (const Displacement & x, const Displacement & y, const Displacement & z)
Constructs a SurfacePoint object with a rectangular point only.
Parameters
x The x coordinate of the surface point
y The y coordinate of the surface point
z The z coordinate of the surface point
SurfacePoint() [7/8]
Isis::SurfacePoint::SurfacePoint (const Displacement & x, const Displacement & y, const Displacement & z, const Distance & xSigma, const Distance & ySigma, const Distance & zSigma)
Constructs a SurfacePoint object with a rectangular point and sigmas.
Parameters
x The x coordinate of the surface point
y The y coordinate of the surface point
z The z coordinate of the surface point
      The sigmas indicate the accuracy of the point.  For instance,
      a sigmaX=100 m, would indicate that the x coordinate was accurate
      to within 100 meters.
xSigma The x coordinate of the surface point
ySigma The y coordinate of the surface point
zSigma The z coordinate of the surface point
SurfacePoint() [8/8]
Isis::SurfacePoint::SurfacePoint (const Displacement & x, const Displacement & y, const Displacement & z, const boost::numeric::ublas::symmetric_matrix< double, boost::numeric::ublas::upper > & covar)
~SurfacePoint()
Isis::SurfacePoint::~SurfacePoint ()
Destroys a SurfacePoint object/.
Member Function Documentation
coordinateTypeToString()
QString Isis::SurfacePoint::coordinateTypeToString (SurfacePoint::CoordinateType type) static
Converts the given SurfacePoint::CoordinateType enumeration to a string.
This method is used to print the type of control point coordinates used in the bundle adjustment.
Parameters
type The Coordinate Type enumeration to be converted.
Returns
QString The name associated with the given CoordinateType.
Exceptions
Isis::Exception::Programmer "Unknown SurfacePoint CoordinateType enum."
References _FILEINFO_, and Isis::toString().
Referenced by Isis::BundleSolutionInfo::outputHeader().
DisplacementToDouble()
double Isis::SurfacePoint::DisplacementToDouble (Displacement disp, CoordUnits units)
This method returns a double version of a Displacement in the specified units.
Parameters
disp The displacement to convert to a double
units The units in which to return the displacement (see CoordinateUnits in .h file)
References _FILEINFO_, Isis::Displacement::kilometers(), and Isis::Displacement::meters().
DistanceToDouble()
double Isis::SurfacePoint::DistanceToDouble (Distance dist, CoordUnits units)
This method returns a double version of a Distance in the specified units.
Parameters
dist The distance to convert to a double
units The units in which to return the distance (see CoordinateUnits in .h file)
References _FILEINFO_, Isis::Distance::kilometers(), and Isis::Distance::meters().
FromNaifArray()
void Isis::SurfacePoint::FromNaifArray (const double naifValues[3])
A naif array is a c-style array of size 3.
The element types are double... keep in mind a SpiceDouble is a double. The values' units are kilometers because that is the unit naif works in. The first element is X, the second Y, and the third Z. This loads the naif array into the surface point.
Parameters
naifValues The naif array to use as rectangular coordinates
Referenced by Isis::TriangularPlate::intercept(), Isis::DemShape::intersectSurface(), Isis::EquatorialCylindricalShape::intersectSurface(), Isis::PlaneShape::intersectSurface(), and Isis::TriangularPlate::point().
GetCoord()
double Isis::SurfacePoint::GetCoord (CoordinateType type, CoordIndex index, CoordUnits units)
This method returns a coordinate of a SurfacePoint.
Parameters
type The coordinate type to return (see CoordinateType in .h file)
index The coordinate index to return (1 <= index <= 3)
units The units in which to return the coordinate value (see CoordinateUnits in .h file)
References _FILEINFO_, and Isis::toString().
Referenced by Isis::BundleControlPoint::formatBundleOutputSummaryString().
GetDistanceToPoint() [1/2]
Distance Isis::SurfacePoint::GetDistanceToPoint (const SurfacePoint & other) const
Computes and returns the distance between two surface points.
The average of the local radii will be used.
References GetLocalRadius(), and Valid().
Referenced by Isis::ControlNetFilter::CubeDistanceFilter(), Isis::QnetCubeDistanceFilter::filter(), Isis::QnetPointDistanceFilter::filter(), and Isis::ControlNetFilter::PointDistanceFilter().
GetDistanceToPoint() [2/2]
Distance Isis::SurfacePoint::GetDistanceToPoint (const SurfacePoint & other, const Distance & sphereRadius) const
Computes and returns the distance between two surface points, assuming both points are on a sphere with the given radius.
This uses the haversine formula to compute the distance. Using a spherical model gives errors typically <1%
References GetLatitude(), GetLongitude(), Isis::Angle::radians(), and Valid().
GetLatitude()
Latitude Isis::SurfacePoint::GetLatitude () const
Return the body-fixed latitude for the surface point.
Referenced by Isis::BundleLidarRangeConstraint::applyConstraint(), Isis::CameraGroundMap::EllipsoidPartial(), Isis::AdjustedLatitudeFilter::evaluate(), Isis::APrioriLatitudeFilter::evaluate(), Isis::QnetPointRangeFilter::filter(), Isis::BundleControlPoint::formatBundleLatitudinalOutputDetailString(), Isis::BundleControlPoint::formatBundleRectangularOutputDetailString(), Isis::AbstractPointItem::getData(), GetDistanceToPoint(), Isis::Sensor::GetLatitude(), Isis::Camera::GetLocalNormal(), Isis::BundleSolutionInfo::outputPointsCSV(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::CameraGroundMap::PointPartial(), Isis::AbstractPointItem::setData(), Isis::UniversalGroundMap::SetGround(), Isis::VimsGroundMap::SetGround(), Isis::PushFrameCameraGroundMap::SetGround(), Isis::BundleAdjust::solveCholesky(), Isis::CSMCamera::subSpacecraftPoint(), Isis::ControlNetVersioner::toPvl(), and Isis::LidarData::write().
GetLatSigma()
Angle Isis::SurfacePoint::GetLatSigma () const
Referenced by Isis::ControlPoint::SetAprioriSurfacePoint().
GetLatSigmaDistance()
Distance Isis::SurfacePoint::GetLatSigmaDistance () const
Return the latitude sigma as a Distance.
Referenced by Isis::AdjustedLatitudeSigmaFilter::evaluate(), Isis::APrioriLatitudeSigmaFilter::evaluate(), Isis::AbstractPointItem::getData(), Isis::AbstractPointItem::setData(), and Isis::ControlNetVersioner::toPvl().
GetLatWeight()
double Isis::SurfacePoint::GetLatWeight () const
Return latitude weight for bundle adjustment Units are 1/(radians)^2.
References _FILEINFO_.
GetLocalRadius()
Distance Isis::SurfacePoint::GetLocalRadius () const
Return the radius of the surface point.
Referenced by Isis::BundleLidarRangeConstraint::applyConstraint(), Isis::AdjustedRadiusFilter::evaluate(), Isis::APrioriRadiusFilter::evaluate(), Isis::QnetPointDistanceFilter::filter(), Isis::BundleControlPoint::formatBundleLatitudinalOutputDetailString(), Isis::BundleControlPoint::formatBundleRectangularOutputDetailString(), Isis::AbstractPointItem::getData(), GetDistanceToPoint(), Isis::Sensor::LocalRadius(), operator=(), Isis::BundleSolutionInfo::outputPointsCSV(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::CameraGroundMap::PointPartial(), Isis::AbstractPointItem::setData(), Isis::ControlNetVersioner::toPvl(), and Isis::LidarData::write().
GetLocalRadiusSigma()
Distance Isis::SurfacePoint::GetLocalRadiusSigma () const
Referenced by Isis::AdjustedRadiusSigmaFilter::evaluate(), Isis::APrioriRadiusSigmaFilter::evaluate(), Isis::AbstractPointItem::getData(), Isis::ControlPoint::SetAprioriSurfacePoint(), Isis::AbstractPointItem::setData(), and Isis::ControlNetVersioner::toPvl().
GetLocalRadiusWeight()
double Isis::SurfacePoint::GetLocalRadiusWeight () const
Return radius weight for bundle adjustment Units are 1/(kilometers)^2.
References _FILEINFO_.
GetLongitude()
Longitude Isis::SurfacePoint::GetLongitude () const
Return the body-fixed longitude for the surface point.
References Isis::PI.
Referenced by Isis::BundleLidarRangeConstraint::applyConstraint(), Isis::CameraGroundMap::EllipsoidPartial(), Isis::AdjustedLongitudeFilter::evaluate(), Isis::APrioriLongitudeFilter::evaluate(), Isis::QnetPointRangeFilter::filter(), Isis::BundleControlPoint::formatBundleLatitudinalOutputDetailString(), Isis::BundleControlPoint::formatBundleRectangularOutputDetailString(), Isis::AbstractPointItem::getData(), GetDistanceToPoint(), Isis::Camera::GetLocalNormal(), Isis::Sensor::GetLongitude(), Isis::BundleSolutionInfo::outputPointsCSV(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::CameraGroundMap::PointPartial(), Isis::AbstractPointItem::setData(), Isis::UniversalGroundMap::SetGround(), Isis::VimsGroundMap::SetGround(), Isis::PushFrameCameraGroundMap::SetGround(), Isis::BundleAdjust::solveCholesky(), Isis::CSMCamera::subSpacecraftPoint(), Isis::ControlNetVersioner::toPvl(), and Isis::LidarData::write().
GetLonSigma()
Angle Isis::SurfacePoint::GetLonSigma () const
Referenced by Isis::ControlPoint::SetAprioriSurfacePoint().
GetLonSigmaDistance()
Distance Isis::SurfacePoint::GetLonSigmaDistance () const
Return the longitude sigma in meters.
Referenced by Isis::AdjustedLongitudeSigmaFilter::evaluate(), Isis::APrioriLongitudeSigmaFilter::evaluate(), Isis::AbstractPointItem::getData(), Isis::AbstractPointItem::setData(), and Isis::ControlNetVersioner::toPvl().
GetLonWeight()
double Isis::SurfacePoint::GetLonWeight () const
Return longitude weight for bundle adjustment Units are 1/(radians)^2.
References _FILEINFO_.
GetRectangularMatrix()
symmetric_matrix< double, upper > Isis::SurfacePoint::GetRectangularMatrix (SurfacePoint::CoordUnits units = SurfacePoint::Meters) const
References _FILEINFO_.
Referenced by Isis::ControlPointV0001::ControlPointV0001(), and Isis::ControlNetVersioner::toPvl().
GetSigma()
double Isis::SurfacePoint::GetSigma (CoordinateType type, CoordIndex index, CoordUnits units)
This method returns a sigma of a SurfacePoint coordinate.
Parameters
type The coordinate type to return (see CoordinateType in .h file)
index The coordinate index to return (1 <= index <= 3)
units The units in which to return the coordinate value (see CoordinateUnits in .h file)
References _FILEINFO_, and Isis::toString().
GetSigmaDistance()
Distance Isis::SurfacePoint::GetSigmaDistance (CoordinateType type, CoordIndex index)
This method returns a sigma of a SurfacePoint coordinate as a Distance.
Parameters
type The coordinate type to return (see CoordinateType in .h file)
index The coordinate index to return (1 <= index <= 3)
References _FILEINFO_, and Isis::toString().
Referenced by Isis::BundleControlPoint::formatAdjustedSigmaString(), and Isis::BundleControlPoint::setWeights().
GetSphericalMatrix()
symmetric_matrix< double, upper > Isis::SurfacePoint::GetSphericalMatrix (SurfacePoint::CoordUnits units = SurfacePoint::Meters) const
References _FILEINFO_.
Referenced by Isis::LidarData::write().
GetWeight()
double Isis::SurfacePoint::GetWeight (CoordinateType type, CoordIndex index)
This method returns the weight of a SurfacePoint coordinate Note: At this time a units argument is not included.
If BundleAdjust is modified to allow different distance or displacement units other than kilometers, the units argument can be added similar to the GetCoord and GetSigma methods. Angle weights are in 1/rad^2 and distance and displacements are in 1/km^2
Parameters
type The coordinate type to return (see CoordinateType in .h file)
index The coordinate index to return (1 <= index <= 3)
References _FILEINFO_, and Isis::toString().
Referenced by Isis::BundleControlPoint::setWeights().
GetX()
Displacement Isis::SurfacePoint::GetX () const
Referenced by Isis::DemShape::calculateDefaultNormal(), Isis::EllipsoidShape::calculateLocalNormal(), Isis::BundleLidarRangeConstraint::computeRange(), Isis::ControlPointV0001::ControlPointV0001(), Isis::Sensor::Coordinate(), Isis::PlaneShape::emissionAngle(), Isis::AdjustedXFilter::evaluate(), Isis::APrioriXFilter::evaluate(), Isis::BundleControlPoint::formatBundleLatitudinalOutputDetailString(), Isis::BundleControlPoint::formatBundleRectangularOutputDetailString(), Isis::AbstractPointItem::getData(), Isis::RadarGroundMap::GetXY(), Isis::CameraGroundMap::GetXY(), Isis::ControlPoint::HasAprioriCoordinates(), Isis::PlaneShape::incidenceAngle(), Isis::IsisShape::intersect(), Isis::NaifDskShape::intersectSurface(), Isis::DemShape::intersectSurface(), Isis::Camera::LocalPhotometricAngles(), Isis::PlaneShape::localRadius(), Isis::CameraGroundMap::MeanRadiusPartial(), Isis::AbstractPointItem::setData(), Isis::CSMCamera::SlantDistance(), Isis::Sensor::SlantDistance(), Isis::Sensor::SolarDistance(), and Isis::ControlNetVersioner::toPvl().
GetXSigma()
Distance Isis::SurfacePoint::GetXSigma () const
Referenced by Isis::AdjustedXSigmaFilter::evaluate(), Isis::APrioriXSigmaFilter::evaluate(), Isis::AbstractPointItem::getData(), Isis::ControlPoint::SetAprioriSurfacePoint(), and Isis::AbstractPointItem::setData().
GetXWeight()
double Isis::SurfacePoint::GetXWeight () const
Return X weight for bundle adjustment Units are 1/(kilometers)^2.
References _FILEINFO_.
GetY()
Displacement Isis::SurfacePoint::GetY () const
Referenced by Isis::DemShape::calculateDefaultNormal(), Isis::EllipsoidShape::calculateLocalNormal(), Isis::BundleLidarRangeConstraint::computeRange(), Isis::ControlPointV0001::ControlPointV0001(), Isis::Sensor::Coordinate(), Isis::PlaneShape::emissionAngle(), Isis::AdjustedYFilter::evaluate(), Isis::APrioriYFilter::evaluate(), Isis::BundleControlPoint::formatBundleLatitudinalOutputDetailString(), Isis::BundleControlPoint::formatBundleRectangularOutputDetailString(), Isis::AbstractPointItem::getData(), Isis::RadarGroundMap::GetXY(), Isis::CameraGroundMap::GetXY(), Isis::ControlPoint::HasAprioriCoordinates(), Isis::PlaneShape::incidenceAngle(), Isis::IsisShape::intersect(), Isis::NaifDskShape::intersectSurface(), Isis::DemShape::intersectSurface(), Isis::Camera::LocalPhotometricAngles(), Isis::PlaneShape::localRadius(), Isis::CameraGroundMap::MeanRadiusPartial(), Isis::AbstractPointItem::setData(), Isis::CSMCamera::SlantDistance(), Isis::Sensor::SlantDistance(), Isis::Sensor::SolarDistance(), and Isis::ControlNetVersioner::toPvl().
GetYSigma()
Distance Isis::SurfacePoint::GetYSigma () const
Referenced by Isis::AdjustedYSigmaFilter::evaluate(), Isis::APrioriYSigmaFilter::evaluate(), Isis::AbstractPointItem::getData(), Isis::ControlPoint::SetAprioriSurfacePoint(), and Isis::AbstractPointItem::setData().
GetYWeight()
double Isis::SurfacePoint::GetYWeight () const
Return Y weight for bundle adjustment Units are 1/(kilometers)^2.
References _FILEINFO_.
GetZ()
Displacement Isis::SurfacePoint::GetZ () const
Referenced by Isis::DemShape::calculateDefaultNormal(), Isis::EllipsoidShape::calculateLocalNormal(), Isis::BundleLidarRangeConstraint::computeRange(), Isis::ControlPointV0001::ControlPointV0001(), Isis::Sensor::Coordinate(), Isis::PlaneShape::emissionAngle(), Isis::AdjustedZFilter::evaluate(), Isis::APrioriZFilter::evaluate(), Isis::BundleControlPoint::formatBundleLatitudinalOutputDetailString(), Isis::BundleControlPoint::formatBundleRectangularOutputDetailString(), Isis::AbstractPointItem::getData(), Isis::RadarGroundMap::GetXY(), Isis::CameraGroundMap::GetXY(), Isis::ControlPoint::HasAprioriCoordinates(), Isis::PlaneShape::incidenceAngle(), Isis::IsisShape::intersect(), Isis::NaifDskShape::intersectSurface(), Isis::DemShape::intersectSurface(), Isis::Camera::LocalPhotometricAngles(), Isis::PlaneShape::localRadius(), Isis::CameraGroundMap::MeanRadiusPartial(), Isis::AbstractPointItem::setData(), Isis::CSMCamera::SlantDistance(), Isis::Sensor::SlantDistance(), Isis::Sensor::SolarDistance(), and Isis::ControlNetVersioner::toPvl().
GetZSigma()
Distance Isis::SurfacePoint::GetZSigma () const
Referenced by Isis::AdjustedZSigmaFilter::evaluate(), Isis::APrioriZSigmaFilter::evaluate(), Isis::AbstractPointItem::getData(), Isis::ControlPoint::SetAprioriSurfacePoint(), and Isis::AbstractPointItem::setData().
GetZWeight()
double Isis::SurfacePoint::GetZWeight () const
Return Z weight for bundle adjustment Units are 1/(kilometers)^2.
References _FILEINFO_.
LatitudeToMeters()
double Isis::SurfacePoint::LatitudeToMeters (double relativeLat) const
This method returns a Displacement of an Angle relative to the current SurfacePoint latitude.
It should only be used to convert relative latitudes near the SurfacePoint latitude. Typical usage would be to convert latitude sigmas and point corrections for the SurfacePoint.
Parameters
latRadians The latitude in Angle units to convert to Displacement units
Returns
LatDisp The converted latitude in displacement units at the SurfacePoint latitude
References Isis::IsSpecial(), and Isis::Null.
Referenced by Isis::BundleControlPoint::formatBundleLatitudinalOutputDetailString().
LatitudinalDerivative()
std::vector< double > Isis::SurfacePoint::LatitudinalDerivative (CoordIndex index)
Compute partial derivative of the conversion of the latitudinal coordinates to body-fixed rectangular coordinates with respect to the indicated coordinate.
Parameters
index Coordinate index
Returns
std::vector<double> The derivative of the latitudinal to body-fixed vector
References _FILEINFO_.
Referenced by Isis::CsmBundleObservation::computePoint3DPartials().
LatToDouble()
double Isis::SurfacePoint::LatToDouble (Latitude lat, CoordUnits units)
This method returns a double version of a Latitude in the specified units.
Parameters
lat The latitude to convert to a double
units The units in which to return the latitude (see CoordinateUnits in .h file)
References _FILEINFO_.
LongitudeToMeters()
double Isis::SurfacePoint::LongitudeToMeters (double deltaLonRadians) const
This method returns a length in meters version of a delta longitude angle in radians relative to the current SurfacePoint longitude.
It should only be used to convert delta longitudes relative to the SurfacePoint longitude.
Typical usage would be to convert longitude sigmas and point corrections for the SurfacePoint.
Parameters
lonRadians The delta longitude in radians to convert to meters
Returns
relativeLonDist The delta longitude in meters from the SurfacePoint longitude
References Isis::IsSpecial(), and Isis::Null.
Referenced by Isis::BundleControlPoint::formatBundleLatitudinalOutputDetailString().
LonToDouble()
double Isis::SurfacePoint::LonToDouble (Longitude lon, CoordUnits units)
This method returns a double version of a Longitude in the specified units.
Parameters
lon The longitude to convert to a double
units The units in which to return the longitude (see CoordinateUnits in .h file)
References _FILEINFO_.
MetersToLatitude()
double Isis::SurfacePoint::MetersToLatitude (double latLength)
This method returns an angular measure of a distance in the direction of and relative to the latitude of the SurfacePoint.
It should only be used to convert lengths relative to the SurfacePoint and in the direction of latitude. Typical usage would be to convert latitude sigmas and point corrections for the SurfacePoint.
Parameters
latLength The latitude in meters to convert to radian units
Returns
LatDispAngle The converted linear measure in radian units
References Isis::IsSpecial(), and Isis::Null.
Referenced by Isis::BundleControlPoint::setSigmaWeightFromGlobals().
MetersToLongitude()
double Isis::SurfacePoint::MetersToLongitude (double deltaLonMeters)
This method returns an angular measure in radians of a distance in the direction of and relative to the longitude of the SurfacePoint.
It should only be used to
convert lengths relative to the SurfacePoint and in the direction of longitude. Typical usage is to convert longitude sigmas and point corrections for the SurfacePoint.
Parameters
lonLength The delta longitude distance in meters to convert to radians
Returns
LonDistAngle The converted delta length in radians
References Isis::IsSpecial(), Isis::Null, and Isis::PI.
Referenced by Isis::BundleControlPoint::setSigmaWeightFromGlobals().
operator=()
SurfacePoint & Isis::SurfacePoint::operator= (const SurfacePoint & other)
References GetLocalRadius().
operator==()
bool Isis::SurfacePoint::operator== (const SurfacePoint & other) const
Partial()
std::vector< double > Isis::SurfacePoint::Partial (CoordinateType type, CoordIndex index)
Compute partial derivative of conversion from body-fixed coordinates to the specified.
Compute partial derivative of the conversion of the body-fixed surface point coordinate to the specified coordinate type.
Parameters
covar variance/covariance matrix
Returns
void
References _FILEINFO_, and Isis::toString().
Referenced by Isis::IsisBundleObservation::computePoint3DPartials().
RectangularDerivative()
std::vector< double > Isis::SurfacePoint::RectangularDerivative (CoordIndex index)
Compute partial derivative of the body-fixed rectangular coordinates with respect to the indicated coordinate.
Parameters
index Coordinate index
Returns
std::vector<double> The derivative of the body-fixed vector
References _FILEINFO_.
ResetLocalRadius()
void Isis::SurfacePoint::ResetLocalRadius (const Distance & radius)
This method resets the local radius of a SurfacePoint.
Parameters
radius The new local radius value to set
References _FILEINFO_, Isis::Distance::isValid(), Isis::Distance::kilometers(), and Isis::Angle::radians().
Referenced by Isis::BundleAdjust::solveCholesky().
SetMatrix()
void Isis::SurfacePoint::SetMatrix (CoordinateType type, const boost::numeric::ublas::symmetric_matrix< double, boost::numeric::ublas::upper > & covar)
Set the covariance matrix.
Set covariance matrix in km.
Parameters
covar variance/covariance matrix
Returns
void
References _FILEINFO_, and Isis::toString().
SetRectangular() [1/2]
void Isis::SurfacePoint::SetRectangular (const Displacement & x, const Displacement & y, const Displacement & z, const Distance & xSigma = Distance(), const Distance & ySigma = Distance(), const Distance & zSigma = Distance())
Set surface point in rectangular body-fixed coordinates wtih optional sigmas.
Parameters
x x value of body-fixed coordinate of surface point
y y value of body-fixed coordinate of surface point
z z value of body-fixed coordinate of surface point
xSigma x sigma of body-fixed coordinate of surface point
ySigma y sigma of body-fixed coordinate of surface point
zSigma z sigma of body-fixed coordinate of surface point
Returns
void
References Isis::Distance::isValid().
Referenced by Isis::ControlPoint::ComputeApriori(), and Isis::ControlPointV0001::ControlPointV0001().
SetRectangular() [2/2]
void Isis::SurfacePoint::SetRectangular (const Displacement x, const Displacement y, const Displacement z, const boost::numeric::ublas::symmetric_matrix< double, boost::numeric::ublas::upper > & covar)
SetRectangularCoordinates()
void Isis::SurfacePoint::SetRectangularCoordinates (const Displacement & x, const Displacement & y, const Displacement & z)
Set surface point in rectangular coordinates.
Parameters
x x value of body-fixed coordinate of surface point
y y value of body-fixed coordinate of surface point
z z value of body-fixed coordinate of surface point
Returns
void
Referenced by Isis::AbstractPointItem::setData().
SetRectangularMatrix()
void Isis::SurfacePoint::SetRectangularMatrix (const boost::numeric::ublas::symmetric_matrix< double, boost::numeric::ublas::upper > & covar, SurfacePoint::CoordUnits units = SurfacePoint::Meters)
Set rectangular covariance matrix and store in units of km**2.
Parameters
covar Rectangular variance/covariance matrix
units Units of matrix are units**2
Returns
void
References _FILEINFO_.
SetRectangularSigmas()
void Isis::SurfacePoint::SetRectangularSigmas (const Distance & xSigma, const Distance & ySigma, const Distance & zSigma)
Set surface point and sigmas in rectangular coordinates and convert to planetocentric.
Set the rectangular sigmas into the rectangular variance/covariance matrix with diagonal element units of km^2, km^2, and km^2.
Parameters
xSigma x sigma of body-fixed coordinate of surface point
ySigma y sigma of body-fixed coordinate of surface point
zSigma z sigma of body-fixed coordinate of surface point
References _FILEINFO_, Isis::Distance::isValid(), and Isis::Distance::meters().
Referenced by Isis::AbstractPointItem::setData().
SetSpherical() [1/2]
void Isis::SurfacePoint::SetSpherical (const Latitude & lat, const Longitude & lon, const Distance & radius, const Angle & latSigma = Angle(), const Angle & lonSigma = Angle(), const Distance & radiusSigma = Distance())
Set surface point and covariance matrix in planetocentric coordinates and convert to rectangular (Latitude, Longitude in degrees, Radius in meters; matrix in radians and radians**2)
Set surface point in spherical body-fixed coordinates (lat/lon/radius) wtih optional sigmas.
Parameters
lat Body-fixed latitude of surface point
lon Body-fixed longitude of surface point
radius Local radius of surface point
latSigma Latitude sigma of of spherical coordinate of surface point
lonSigma Longitude sigma of of spherical coordinate of surface point
radiusSigma Local radius sigma of of spherical coordinate of surface point
References Isis::Angle::isValid(), and Isis::Distance::isValid().
Referenced by Isis::ControlNetFilter::PointDistanceFilter(), and Isis::ControlNetFilter::PointLatLonFilter().
SetSpherical() [2/2]
void Isis::SurfacePoint::SetSpherical (const Latitude & lat, const Longitude & lon, const Distance & radius, const boost::numeric::ublas::symmetric_matrix< double, boost::numeric::ublas::upper > & covar)
SetSphericalCoordinates()
void Isis::SurfacePoint::SetSphericalCoordinates (const Latitude & lat, const Longitude & lon, const Distance & radius)
Update spherical coordinates (lat/lon/radius)
Parameters
lat
lon
radius
Referenced by Isis::AbstractPointItem::setData().
SetSphericalMatrix()
void Isis::SurfacePoint::SetSphericalMatrix (const boost::numeric::ublas::symmetric_matrix< double, boost::numeric::ublas::upper > & covar, SurfacePoint::CoordUnits units = SurfacePoint::Meters)
Set spherical covariance matrix.
Parameters
covar Spherical variance/covariance matrix (radians**2 for lat and lon)
Returns
void
References _FILEINFO_, Isis::Distance::kilometers(), and Isis::Angle::radians().
SetSphericalSigmas()
void Isis::SurfacePoint::SetSphericalSigmas (const Angle & latSigma, const Angle & lonSigma, const Distance & radiusSigma)
Set the spherical sigmas into the spherical variance/covariance matrix in diagonal units of radians^2, radians^2, km^2.
Parameters
latSigma Latitude sigma of body-fixed coordinate of surface point
lonSigma Longitude sigma of body-fixed coordinate of surface point
radiusSigma Radius sigma of body-fixed coordinate of surface point
References Isis::Angle::isValid(), Isis::Distance::isValid(), Isis::Distance::meters(), and Isis::Angle::radians().
SetSphericalSigmasDistance()
void Isis::SurfacePoint::SetSphericalSigmasDistance (const Distance & latSigma, const Distance & lonSigma, const Distance & radiusSigma)
Set the spherical sigmas (in Distance units) into the spherical variance/covariance matrix.
Parameters
latSigma Latitude sigma of body-fixed coordinate of surface point as a Distance
lonSigma Longitude sigma of body-fixed coordinate of surface point as a Distance
radiusSigma Radius sigma of body-fixed coordinate of surface point in meters
References _FILEINFO_, and Isis::Distance::meters().
Referenced by Isis::ControlPointV0001::ControlPointV0001(), and Isis::AbstractPointItem::setData().
stringToCoordinateType()
SurfacePoint::CoordinateType Isis::SurfacePoint::stringToCoordinateType (QString type) static
This method converts the given string value to a SurfacePoint::CoordinateType enumeration.
Currently (March 31, 2017) accepted inputs are listed below.
This method is case insensitive.
Parameters
type The coordinate type name to be converted
Returns
CoordinateType The enumeration corresponding to the input name
References _FILEINFO_.
ToNaifArray()
void Isis::SurfacePoint::ToNaifArray (double naifOutput[3]) const
A naif array is a c-style array of size 3.
The element types are double... keep in mind a SpiceDouble is a double. The values' units are kilometers because that is the unit naif works in. The first element is X, the second Y, and the third Z.
Parameters
naifOutput The naif array to populate with the surface point's XYZ position.
References _FILEINFO_.
Referenced by Isis::DemShape::calculateLocalNormal(), Isis::BulletShapeModel::ellipsoidNormal(), Isis::EmbreeShapeModel::ellipsoidNormal(), Isis::NaifDskShape::ellipsoidNormal(), Isis::TriangularPlate::hasPoint(), Isis::EmbreeShapeModel::intersectSurface(), Isis::EmbreeShapeModel::isVisibleFrom(), Isis::TriangularPlate::point(), and Isis::RadarGroundMap::SetGround().
Valid()
bool Isis::SurfacePoint::Valid () const
Referenced by Isis::ControlPoint::ComputeApriori(), Isis::QnetPointDistanceFilter::filter(), Isis::ControlPoint::GetBestSurfacePoint(), GetDistanceToPoint(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::RadarGroundMap::SetGround(), Isis::Camera::SetGround(), Isis::CSMCamera::SetGround(), Isis::ControlNetVersioner::toPvl(), and Isis::LidarData::write().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/SurfacePoint/SurfacePoint.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/SurfacePoint/SurfacePoint.cpp