Isis Developer Reference: Isis::MatrixSceneWidget Class Reference
Isis::MatrixSceneWidget Class Reference
This widget encompasses the entire matrixDisplay scene.
#include <MatrixSceneWidget.h>
Public Slots
void redrawElements ()
Redraw matrix when the focus is changed.
Signals
void mouseEnter ()
Emitted when mouse enters widget focus.
void mouseMove (QPointF)
Emitted when mouse moves in widget.
void mouseLeave ()
Emitted when mouse leaves widget focus.
void mouseDoubleClick (QPointF)
Emitted when handling a mouse double-click.
void mouseButtonPress (QPointF, Qt::MouseButton s)
Emitted when mouse is pressed.
void mouseButtonRelease (QPointF, Qt::MouseButton s)
Emitted when mouse button released.
void mouseWheel (QPointF, int delta)
Emitted when mouse wheel is activated Emitted when rubber band selection is complete.
void rubberBandComplete (QRectF r, Qt::MouseButton s)
void visibleRectChanged (QRectF)
Emitted when the visible rectangle is changed.
void elementsChanged ()
Emitted when an element of the widget is changed.
void queueSelectionChanged ()
Emitted when selection is changed.
void elementClicked (QString)
Emitted when an element of the widget is clicked.
Public Member Functions
MatrixSceneWidget (QStatusBar *status, bool showTools, bool internalizeToolBarsAndProgress, Directory *directory, QWidget *parent=0)
Constructor, creates a matrix scene widget.
virtual ~MatrixSceneWidget ()
Default Destructor.
MatrixGraphicsView * getView () const
Accessor for the QGraphicsView.
QGraphicsScene * getScene () const
Accessor for the QGraphicsScene.
bool contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
This is called by MatrixGraphicsScene::contextMenuEvent.
void drawGrid (CorrelationMatrix corrMatrix)
Draw the lines that will show the columns and blocks for each image.
void drawElements (CorrelationMatrix corrMatrix)
Draw elements.
QProgressBar * getProgress ()
Accessor for the widget's progress bar.
PvlObject toPvl () const
void fromPvl (const PvlObject &)
QRectF elementsBoundingRect () const
Returns the bounding rectangle for the images.
Directory * directory () const
Accessor for the directory.
QList< QAction * > getViewActions ()
Accessor for the view actions.
QList< QAction * > supportedActions (CorrelationMatrix *matrix)
Get a list of applicable actions for the elements in this scene.
void redrawItems ()
Redraws all the items in the view.
void setUpOptions (CorrelationMatrix corrMat)
Change item colors when options are changed.
template<typename DataType >
QList< QAction * > supportedActions (DataType)
Return an empty list of actions for unknown data types.
Protected Member Functions
virtual bool eventFilter (QObject *obj, QEvent *ev)
Pick the relevant actions given the type of event that occured in the scene.
Detailed Description
This widget encompasses the entire matrixDisplay scene.
This widget is a self-contained view of the correlation matrix resulting from a bundle adjust. It uses Qt's graphics scene/view framework. This widget holds the graphics scene, view, and items. It will also hold the options dialog for the matrix.
Author
2014-05-10 Kimberly Oyama
Constructor & Destructor Documentation
MatrixSceneWidget()
Isis::MatrixSceneWidget::MatrixSceneWidget (QStatusBar * status, bool showTools, bool internalizeToolBarsAndProgress, Directory * directory, QWidget * parent = 0)
Constructor, creates a matrix scene widget.
Parameters
status Pointer to an existing status bar
showTools Whether or not create a matrix scene or matrix world view
internalizeToolBarsAndProgress Whether or not to show progress and status
directory The directory of the current project
parent QPointer to the parent widget
References directory(), Isis::MatrixGraphicsView::enableResizeZooming(), and getView().
~MatrixSceneWidget()
Isis::MatrixSceneWidget::~MatrixSceneWidget () virtual
Default Destructor.
Member Function Documentation
contextMenuEvent()
bool Isis::MatrixSceneWidget::contextMenuEvent (QGraphicsSceneContextMenuEvent * event)
This is called by MatrixGraphicsScene::contextMenuEvent.
Parameters
event The context menu event
Returns
bool false if not handled, true if handled.
References getScene().
directory()
Directory * Isis::MatrixSceneWidget::directory () const
Accessor for the directory.
Returns
Directory* The directory
Referenced by MatrixSceneWidget().
drawElements()
void Isis::MatrixSceneWidget::drawElements (CorrelationMatrix corrMatrix)
Draw elements.
If element is drawn in black, something is wrong. The correlation value is out of range.
Need separate redraw method because we will already have the list of MatrixSceneItems.
Parameters
corrMatrix The matrix that belongs to the project.
References Isis::MatrixOptions::badCorrelationColor(), Isis::MatrixOptions::colorScheme(), Isis::MatrixOptions::colorTolerance(), Isis::MatrixOptions::goodCorrelationColor(), Isis::CorrelationMatrix::imagesAndParameters(), and Isis::CorrelationMatrix::visibleBlocks().
Referenced by Isis::MatrixViewWorkOrder::execute(), redrawElements(), and Isis::MatrixViewWorkOrder::setupExecution().
drawGrid()
void Isis::MatrixSceneWidget::drawGrid (CorrelationMatrix corrMatrix)
Draw the lines that will show the columns and blocks for each image.
Parameters
corrMatrix The matrix that belongs to the project
References Isis::CorrelationMatrix::imagesAndParameters().
Referenced by Isis::MatrixViewWorkOrder::execute(), and Isis::MatrixViewWorkOrder::setupExecution().
elementClicked
void Isis::MatrixSceneWidget::elementClicked (QString) signal
Emitted when an element of the widget is clicked.
Referenced by eventFilter().
elementsBoundingRect()
QRectF Isis::MatrixSceneWidget::elementsBoundingRect () const
Returns the bounding rectangle for the images.
Returns
QRectF Bounding rectangle for image elements
elementsChanged
void Isis::MatrixSceneWidget::elementsChanged () signal
Emitted when an element of the widget is changed.
eventFilter()
bool Isis::MatrixSceneWidget::eventFilter (QObject * obj, QEvent * event) protected virtual
Pick the relevant actions given the type of event that occured in the scene.
Mouse Events:
Press - Emit elementClicked signal to update the options dialog Release - nolowerColorValue? Double-Click - same as press Move - nolowerColorValue Enter - change label to match current item. Leave - clear label
Parameters
obj Pointer to the target QObject to watch events on
event The event to inspect
Returns
bool True if the event is filter (stopping all future processing of the event)
References elementClicked(), and mouseDoubleClick().
fromPvl()
void Isis::MatrixSceneWidget::fromPvl (const PvlObject &)
getProgress()
QProgressBar * Isis::MatrixSceneWidget::getProgress ()
Accessor for the widget's progress bar.
Returns
QProgressBar* The progress bar
getScene()
QGraphicsScene * Isis::MatrixSceneWidget::getScene () const
Accessor for the QGraphicsScene.
Returns
MatrixGraphicsScene* The matrix scene.
Referenced by contextMenuEvent().
getView()
MatrixGraphicsView * Isis::MatrixSceneWidget::getView () const
Accessor for the QGraphicsView.
Returns
MatrixGraphicsView* The matrix view.
Referenced by MatrixSceneWidget().
getViewActions()
QList< QAction * > Isis::MatrixSceneWidget::getViewActions ()
Accessor for the view actions.
Returns
QList<QAction*> List of view actions
mouseButtonPress
void Isis::MatrixSceneWidget::mouseButtonPress (QPointF , Qt::MouseButton s) signal
Emitted when mouse is pressed.
mouseButtonRelease
void Isis::MatrixSceneWidget::mouseButtonRelease (QPointF , Qt::MouseButton s) signal
Emitted when mouse button released.
mouseDoubleClick
void Isis::MatrixSceneWidget::mouseDoubleClick (QPointF) signal
Emitted when handling a mouse double-click.
Referenced by eventFilter().
mouseEnter
void Isis::MatrixSceneWidget::mouseEnter () signal
Emitted when mouse enters widget focus.
mouseLeave
void Isis::MatrixSceneWidget::mouseLeave () signal
Emitted when mouse leaves widget focus.
mouseMove
void Isis::MatrixSceneWidget::mouseMove (QPointF) signal
Emitted when mouse moves in widget.
mouseWheel
void Isis::MatrixSceneWidget::mouseWheel (QPointF , int delta) signal
Emitted when mouse wheel is activated Emitted when rubber band selection is complete.
queueSelectionChanged
void Isis::MatrixSceneWidget::queueSelectionChanged () signal
Emitted when selection is changed.
redrawElements
void Isis::MatrixSceneWidget::redrawElements () slot
Redraw matrix when the focus is changed.
References drawElements(), and Isis::MatrixOptions::parentMatrix().
Referenced by setUpOptions().
redrawItems()
void Isis::MatrixSceneWidget::redrawItems ()
Redraws all the items in the view.
Also makes sure to resize the view rectangle to fit the newly drawn items.
rubberBandComplete
void Isis::MatrixSceneWidget::rubberBandComplete (QRectF r, Qt::MouseButton s) signal
setUpOptions()
void Isis::MatrixSceneWidget::setUpOptions (CorrelationMatrix corrMat)
Change item colors when options are changed.
Parameters
colorScheme True if using tolerance. False if using gradient. Allows for changing the options on a CorrelationMatrix
corrMat The matrix to set up options for
References redrawElements().
Referenced by Isis::MatrixViewWorkOrder::execute(), and Isis::MatrixViewWorkOrder::setupExecution().
supportedActions() [1/2]
QList< QAction * > Isis::MatrixSceneWidget::supportedActions (CorrelationMatrix * matrix)
Get a list of applicable actions for the elements in this scene.
Parameters
matrix Pointer to the CorrelationMatrix that belongs to the project
Returns
QList<QAction*> List of supported actions for the CorrelationMatrix elements
supportedActions() [2/2]
template<typename DataType > QList<QAction *> Isis::MatrixSceneWidget::supportedActions (DataType) inline
Return an empty list of actions for unknown data types.
Parameters
DataType The type of data we want to get actions for
Returns
QList<QAction*> Empty list of actions (currently)
toPvl()
PvlObject Isis::MatrixSceneWidget::toPvl () const
visibleRectChanged
void Isis::MatrixSceneWidget::visibleRectChanged (QRectF) signal
Emitted when the visible rectangle is changed.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MatrixSceneWidget/MatrixSceneWidget.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MatrixSceneWidget/MatrixSceneWidget.cpp