Isis Developer Reference: Isis::PushFrameCameraCcdLayout Class Reference
Isis::PushFrameCameraCcdLayout Class Reference
Provide image coordinates that map to the push frame detector.
#include <PushFrameCameraCcdLayout.h>
Classes
struct FrameletInfo
Container for the layout of a specific framelet on the detector.
Public Member Functions
PushFrameCameraCcdLayout ()
Push frame full CCD layout class.
PushFrameCameraCcdLayout (const int ccdId)
Push frame full CCD layout class for specific Id.
virtual ~PushFrameCameraCcdLayout ()
Destructor.
bool addKernel (const QString &kernel)
Add a NAIF kernel to the set of kernels that values will be pulled from.
int ccdSamples () const
Return the number of samples in the CCD.
int ccdLines () const
Return the number of lines in the CCD.
FrameletInfo getFrameInfo (const int &frameId, const QString &name="") const
Get the layout information for a framelet.
Detailed Description
Provide image coordinates that map to the push frame detector.
See also
Camera
Author
2017-08-11 Kris Becker
Constructor & Destructor Documentation
PushFrameCameraCcdLayout() [1/2]
Isis::PushFrameCameraCcdLayout::PushFrameCameraCcdLayout ()
Push frame full CCD layout class.
PushFrameCameraCcdLayout() [2/2]
Isis::PushFrameCameraCcdLayout::PushFrameCameraCcdLayout (const int ccdId)
Push frame full CCD layout class for specific Id.
Parameters
ccId The NAIF ID of the CCD
~PushFrameCameraCcdLayout()
Isis::PushFrameCameraCcdLayout::~PushFrameCameraCcdLayout () virtual
Destructor.
Member Function Documentation
addKernel()
bool Isis::PushFrameCameraCcdLayout::addKernel (const QString & kernel)
Add a NAIF kernel to the set of kernels that values will be pulled from.
Parameters
kernel The path to the kernel file to load. The kernel name can contain a series of ?? characters to indicate version numbers. In this case the highest version numbered file will be added.
Returns
bool If the kernel was successfully loaded.
References Isis::Kernels::Add(), Isis::FileName::expanded(), Isis::FileName::highestVersion(), Isis::FileName::isVersioned(), and Isis::Kernels::Load().
ccdLines()
int Isis::PushFrameCameraCcdLayout::ccdLines () const
Return the number of lines in the CCD.
Queries the NAIF keyword INS(CCD NAIF ID)_FILTER_LINES from the loaded kernels.
Returns
int The number of lines in the CCD.
References Isis::toString().
ccdSamples()
int Isis::PushFrameCameraCcdLayout::ccdSamples () const
Return the number of samples in the CCD.
Queries the NAIF keyword INS(CCD NAIF ID)_FILTER_SAMPLES from the loaded kernels.
Returns
int The number of samples in the CCD.
References Isis::toString().
getFrameInfo()
PushFrameCameraCcdLayout::FrameletInfo Isis::PushFrameCameraCcdLayout::getFrameInfo (const int & frameId, const QString & name = "") const
Get the layout information for a framelet.
Parameters
frameId The NAIF ID of the framelet.
name The name of the framelet. If empty, the loaded kernels will be queried for the name associated with the NAIF ID.
Returns
FrameletInfo The location and size of the framelet on the CCD.
References _FILEINFO_, Isis::IException::Io, Isis::PushFrameCameraCcdLayout::FrameletInfo::m_filterName, Isis::PushFrameCameraCcdLayout::FrameletInfo::m_lines, Isis::PushFrameCameraCcdLayout::FrameletInfo::m_samples, Isis::PushFrameCameraCcdLayout::FrameletInfo::m_startLine, Isis::PushFrameCameraCcdLayout::FrameletInfo::m_startSample, and Isis::toString().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/PushFrameCameraCcdLayout/PushFrameCameraCcdLayout.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/PushFrameCameraCcdLayout/PushFrameCameraCcdLayout.cpp