Isis Developer Reference: Isis::VimsSkyMap Class Reference
Isis::VimsSkyMap Class Reference
Spice, Instruments, and Cameras
Convert between undistorted focal plane and ground coordinates.
#include <VimsSkyMap.h>
Public Member Functions
VimsSkyMap (Camera *parent, Pvl &lab)
Constructs the VimsSkyMap object.
virtual ~VimsSkyMap ()
Destroys the VimsSkyMap object.
virtual bool SetFocalPlane (const double ux, const double uy, const double uz)
Compute ground position from focal plane coordinate.
virtual bool SetSky (const double ra, const double dec)
Sets the sky position to the given ra and dec.
void Init (Pvl &lab)
Initialize vims sky model.
double FocalPlaneX () const
double FocalPlaneY () const
Protected Attributes
Camera * p_camera
The main camera to calculate distortions on.
double p_focalPlaneX
Undistorted x value for the focal plane.
double p_focalPlaneY
Undistorted y value for the focal plane.
Detailed Description
Convert between undistorted focal plane and ground coordinates.
This base class is used to convert between undistorted focal plane coordinates (x/y) in millimeters and ground coordinates lat/lon. This class handles the case of framing cameras.
See also
Camera
VimsCamera
Author
2006-04-05 Tracie Sucharski
Constructor & Destructor Documentation
VimsSkyMap()
Isis::VimsSkyMap::VimsSkyMap (Camera * parent, Pvl & lab)
Constructs the VimsSkyMap object.
Parameters
parent A pointer to the parent Camera object
lab Pvl labels for the image
~VimsSkyMap()
virtual Isis::VimsSkyMap::~VimsSkyMap () inline virtual
Destroys the VimsSkyMap object.
Member Function Documentation
FocalPlaneX()
double Isis::CameraSkyMap::FocalPlaneX () const inline inherited
Returns
The undistorted focal plane x
References Isis::CameraSkyMap::p_focalPlaneX.
Referenced by Isis::Camera::SetRightAscensionDeclination().
FocalPlaneY()
double Isis::CameraSkyMap::FocalPlaneY () const inline inherited
Returns
The undistorted focal plane y
References Isis::CameraSkyMap::p_focalPlaneY.
Referenced by Isis::Camera::SetRightAscensionDeclination().
Init()
void Isis::VimsSkyMap::Init (Pvl & lab)
Initialize vims sky model.
Parameters
[in] lab (Pvl &) Cube Pvl label
Exceptions
iException::Io - "Cannot process NYQUIST(undersampled) mode "
iException::Io - "Can't open unit vector file"
References _FILEINFO_, Isis::Sensor::Declination(), Isis::iTime::Et(), Isis::PvlObject::findGroup(), Isis::Spice::getClockTime(), Isis::Camera::IgnoreProjection(), Isis::NULL8, Isis::CameraSkyMap::p_camera, Isis::Camera::ParentLines(), Isis::Camera::ParentSamples(), Isis::IException::Programmer, Isis::Sensor::RightAscension(), Isis::Camera::SetImage(), Isis::Sensor::setTime(), Isis::toDouble(), and Isis::PvlObject::Traverse.
SetFocalPlane()
bool Isis::VimsSkyMap::SetFocalPlane (const double ux, const double uy, const double uz) virtual
Compute ground position from focal plane coordinate.
This method will compute the ground position given an undistorted focal plane coordinate. Note that the latitude/longitude value can be obtained from the camera class passed into the constructor.
Parameters
ux distorted focal plane x in millimeters
uy distorted focal plane y in millimeters
uz distorted focal plane z in millimeters
Returns
conversion was successful
Reimplemented from Isis::CameraSkyMap.
References Isis::CameraSkyMap::p_camera, Isis::Camera::ParentLines(), Isis::Camera::ParentSamples(), Isis::Sensor::SetLookDirection(), and Isis::Sensor::setTime().
SetSky()
bool Isis::VimsSkyMap::SetSky (const double ra, const double dec) virtual
Sets the sky position to the given ra and dec.
Parameters
ra the right ascension
dec the declination
Returns
set sky was successful
Reimplemented from Isis::CameraSkyMap.
References Isis::LeastSquares::AddKnown(), Isis::LeastSquares::Evaluate(), Isis::Camera::IgnoreProjection(), Isis::LeastSquares::Knowns(), Isis::NULL8, Isis::CameraSkyMap::p_camera, Isis::CameraSkyMap::p_focalPlaneX, Isis::CameraSkyMap::p_focalPlaneY, Isis::Camera::ParentLines(), Isis::Camera::ParentSamples(), Isis::Camera::SetImage(), and Isis::LeastSquares::Solve().
Member Data Documentation
p_camera
Camera* Isis::CameraSkyMap::p_camera protected inherited
The main camera to calculate distortions on.
Referenced by Isis::CameraSkyMap::CameraSkyMap(), Isis::CSMSkyMap::CSMSkyMap(), Init(), Isis::CameraSkyMap::SetFocalPlane(), SetFocalPlane(), Isis::CameraSkyMap::SetSky(), Isis::CSMSkyMap::SetSky(), Isis::LineScanCameraSkyMap::SetSky(), and SetSky().
p_focalPlaneX
double Isis::CameraSkyMap::p_focalPlaneX protected inherited
Undistorted x value for the focal plane.
Referenced by Isis::CameraSkyMap::FocalPlaneX(), Isis::CameraSkyMap::SetSky(), Isis::CSMSkyMap::SetSky(), Isis::LineScanCameraSkyMap::SetSky(), and SetSky().
p_focalPlaneY
double Isis::CameraSkyMap::p_focalPlaneY protected inherited
Undistorted y value for the focal plane.
Referenced by Isis::CameraSkyMap::FocalPlaneY(), Isis::CameraSkyMap::SetSky(), Isis::CSMSkyMap::SetSky(), Isis::LineScanCameraSkyMap::SetSky(), and SetSky().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/cassini/objs/VimsCamera/VimsSkyMap.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/cassini/objs/VimsCamera/VimsSkyMap.cpp