Isis Developer Reference: Isis::ShapeList Class Reference
Isis::ShapeList Class Reference
Internalizes a list of shapes and allows for operations on the entire list.
#include <ShapeList.h>
Signals
void countChanged (int newCount)
Public Member Functions
ShapeList (QString name, QString path, QObject *parent=NULL)
Creates an shape list from an shape list name and path (does not read Shapes).
ShapeList (QObject *parent=NULL)
Creates a blank shape list.
ShapeList (QList< Shape * >, QObject *parent=NULL)
Creates an shape list from a list of shapes.
ShapeList (QStringList &)
Creates an shape list from a list of cube file names.
ShapeList (const ShapeList &)
Copy constructor.
~ShapeList ()
Destructor.
SerialNumberList serialNumberList ()
Creates a SerialNumberList from the shape list.
void append (Shape *const &value)
Appends an shape to the shape list.
void append (const QList< Shape * > &value)
Appends a list of shapes to the shape list.
void clear ()
Clears the shape list.
iterator erase (iterator pos)
Erases a single shape from the shape list.
iterator erase (iterator begin, iterator end)
Erases a range of shapes from the shape list.
void insert (int i, Shape *const &value)
Inserts an shape into the shape list at an index.
iterator insert (iterator before, Shape *const &value)
Inserts an shape into the shape list after an iterator.
void prepend (Shape *const &value)
Inserts an shape at the beginning of the shape list.
void push_back (Shape *const &value)
Appends an shape to the end of the shape list.
void push_front (Shape *const &value)
Prepends an shape to the beginning of the shape list.
int removeAll (Shape *const &value)
Removes all occurances of an shape.
void removeAt (int i)
Removes the shape at an index.
void removeFirst ()
Removes the shape at the front of the shape list.
void removeLast ()
Removes the shape at the end of the shape list.
bool removeOne (Shape *const &value)
Removes the first occurance of an shape.
void swap (QList< Shape * > &other)
Swaps the shape list with another list of shapes.
Shape * takeAt (int i)
Removes the shape at an index and returns it.
Shape * takeFirst ()
Removes and returns the first shape.
Shape * takeLast ()
Removes and returns the last shape.
ShapeList & operator+= (const QList< Shape * > &other)
Appends a list of shapes to the end of the shape list.
ShapeList & operator+= (Shape *const &other)
Appends a single shape to the end of the shape list.
ShapeList & operator<< (const QList< Shape * > &other)
Appends a list of shapes to the end of the shape list.
ShapeList & operator<< (Shape *const &other)
Appends a single shape to the end of the shape list.
ShapeList & operator= (const QList< Shape * > &rhs)
Assigns another list of shapes to the shape list.
ShapeList & operator= (const ShapeList &rhs)
Assignment operator.
void setName (QString newName)
Set the human-readable name of this shape list.
void setPath (QString newPath)
Set the relative path (from the project root) to this shape list's folder.
QString name () const
Get the human-readable name of this shape list.
QString path () const
Get the path to the shapes in the shape list (relative to project root).
void deleteFromDisk (Project *project)
Delete all of the contained Shapes from disk.
void save (QXmlStreamWriter &stream, const Project *project, FileName newProjectRoot) const
Convert this shape list into XML format for saving/restoring capabilities.
Detailed Description
Internalizes a list of shapes and allows for operations on the entire list.
This class reads a list of shapes from an shapes.xml file and internalizes them as aQList of shapes. It also allows for modifications to the entire list of shapes and storing the shape list as an shapes.xml file.
Author
2016-07-25 Tracie Sucharski
Constructor & Destructor Documentation
ShapeList() [1/5]
Isis::ShapeList::ShapeList (QString name, QString path, QObject * parent = NULL)
Creates an shape list from an shape list name and path (does not read Shapes).
Parameters
name The ShapeList's name (i.e. import1, import2, ...).
path The ShapeList's folder name (i.e. import1, import2, ...).
parent The Qt-relationship parent.
References name(), and path().
ShapeList() [2/5]
Isis::ShapeList::ShapeList (QObject * parent = NULL) explicit
Creates a blank shape list.
Parameters
parent The Qt-relationship parent.
ShapeList() [3/5]
Isis::ShapeList::ShapeList (QList< Shape * > shapes, QObject * parent = NULL) explicit
Creates an shape list from a list of shapes.
Parameters
shapes The list of shapes.
parent The Qt-relationship parent.
References append().
ShapeList() [4/5]
Isis::ShapeList::ShapeList (QStringList & fileNames) explicit
Creates an shape list from a list of cube file names.
This is slow (serial) and not recommended.
Parameters
fileNames The list of cube fileNames.
References append().
ShapeList() [5/5]
Isis::ShapeList::ShapeList (const ShapeList & other)
Copy constructor.
Parameters
other The shape list to copy.
~ShapeList()
Isis::ShapeList::~ShapeList ()
Destructor.
This does not free the Shapes from memory.
Member Function Documentation
append() [1/2]
void Isis::ShapeList::append (const QList< Shape * > & value)
Appends a list of shapes to the shape list.
Parameters
value the list of shapes to be appened.
See also
QList<Shape *>::append().
References countChanged().
append() [2/2]
void Isis::ShapeList::append (Shape *const & value)
Appends an shape to the shape list.
Parameters
value The shape to be appended.
See also
QList<Shape *>::append().
References countChanged().
Referenced by Isis::WorkOrder::isExecutable(), Isis::WorkOrder::setData(), and ShapeList().
clear()
void Isis::ShapeList::clear ()
Clears the shape list.
See also
QList<Shape *>::clear().
References countChanged().
countChanged
void Isis::ShapeList::countChanged (int newCount) signal
Referenced by append(), clear(), erase(), insert(), operator+=(), operator<<(), operator=(), prepend(), push_back(), push_front(), removeAll(), removeAt(), removeFirst(), removeLast(), removeOne(), swap(), takeAt(), takeFirst(), and takeLast().
deleteFromDisk()
void Isis::ShapeList::deleteFromDisk (Project * project)
Delete all of the contained Shapes from disk.
Parameters
project The project the shapes in the shape list belong to.
See also
Shape::deleteFromDisk()
References Isis::Shape::deleteFromDisk(), and Isis::Project::shapeDataRoot().
Referenced by Isis::Project::deleteAllProjectFiles(), and Isis::ImportShapesWorkOrder::undoExecution().
erase() [1/2]
QList< Shape * >::iterator Isis::ShapeList::erase (iterator begin, iterator end)
Erases a range of shapes from the shape list.
Erases all shapes from begin up to (but not including) end.
Parameters
begin An iterator pointing to the first shape to be erased.
end An iterator pointing to the shape just after the last shape to be erased. Will be invalid after the call.
Returns
QList::iterator An iterator pointing to the shape end refered to before the call.
See also
QList<Shape *>::erase()
References countChanged().
erase() [2/2]
QList< Shape * >::iterator Isis::ShapeList::erase (iterator pos)
Erases a single shape from the shape list.
Parameters
pos An iterator pointing to the shape to be erased.
Returns
QList::iterator An iterator pointing to the shape after the shape that was removed.
See also
QList<Shape *>::erase()
References countChanged().
insert() [1/2]
void Isis::ShapeList::insert (int i, Shape *const & value)
Inserts an shape into the shape list at an index.
Parameters
i The index at which to insert the shape.
value the shape to be inserted.
See also
QList<Shape *>::insert()
References countChanged().
insert() [2/2]
QList< Shape * >::iterator Isis::ShapeList::insert (iterator before, Shape *const & value)
Inserts an shape into the shape list after an iterator.
Parameters
before An iterator pointing to the shape that value will be inserted after
value The shape to be inserted.
Returns
QList::iterator An iterator pointing to the inserted shape.
See also
QList<Shape *>::insert()
References countChanged().
name()
QString Isis::ShapeList::name () const
Get the human-readable name of this shape list.
Returns
Qstring The name of the shape list (or an empty string if anonymous).
Referenced by Isis::ProjectItem::setShapeList(), Isis::Project::shapeList(), and ShapeList().
operator+=() [1/2]
ShapeList & Isis::ShapeList::operator+= (const QList< Shape * > & other)
Appends a list of shapes to the end of the shape list.
Parameters
other The list of shapes to be appended.
Returns
ShapeList & A reference to the shapeList.
See also
append()
QList<Shape *>::operator+=()
References countChanged().
operator+=() [2/2]
ShapeList & Isis::ShapeList::operator+= (Shape *const & other)
Appends a single shape to the end of the shape list.
Parameters
other The shape to be appended.
Returns
ShapeList & A reference to the shapeList.
See also
append()
QList<Shape *>::operator+=()
References countChanged().
operator<<() [1/2]
ShapeList & Isis::ShapeList::operator<< (const QList< Shape * > & other)
Appends a list of shapes to the end of the shape list.
Parameters
other The list of shapes to be appended.
Returns
ShapeList & A reference to the shapeList.
See also
append()
QList<Shape *>::operator<<()
References countChanged(), and operator<<().
operator<<() [2/2]
ShapeList & Isis::ShapeList::operator<< (Shape *const & other)
Appends a single shape to the end of the shape list.
Parameters
other The shape to be appended.
Returns
ShapeList & A reference to the shapeList.
See also
append()
QList<Shape *>::operator<<()
References countChanged(), and operator<<().
operator=() [1/2]
ShapeList & Isis::ShapeList::operator= (const QList< Shape * > & rhs)
Assigns another list of shapes to the shape list.
Parameters
rhs The list of shapes that shapeList will become a copy of.
Returns
ShapeList & A reference to the shapeList.
See also
QList<Shape *>::operator=()
References countChanged().
operator=() [2/2]
ShapeList & Isis::ShapeList::operator= (const ShapeList & rhs)
Assignment operator.
Parameters
rhs The right hand side of the '=' operator
Returns
ShapeList & This shape list.
References countChanged().
path()
QString Isis::ShapeList::path () const
Get the path to the shapes in the shape list (relative to project root).
This only applies to an shape list from the project.
Returns
QString The path to the shapes in the shape list (or an empty string if unknown).
Referenced by Isis::ProjectItem::setShapeList(), and ShapeList().
prepend()
void Isis::ShapeList::prepend (Shape *const & value)
Inserts an shape at the beginning of the shape list.
Parameters
value The shape to be inserted.
See also
QList<Shape *>::prepend()
References countChanged().
push_back()
void Isis::ShapeList::push_back (Shape *const & value)
Appends an shape to the end of the shape list.
Equivalent to append().
Parameters
value The shape to be appended.
See also
QList<Shape *>::push_back()
References countChanged().
push_front()
void Isis::ShapeList::push_front (Shape *const & value)
Prepends an shape to the beginning of the shape list.
Equivalent to prepend().
Parameters
value The shape to be appended.
See also
QList<Shape *>::push_front()
References countChanged().
removeAll()
int Isis::ShapeList::removeAll (Shape *const & value)
Removes all occurances of an shape.
Parameters
value The shape to be removed.
Returns
int The number of occurances of the shape.
See also
QList<Shape *>::removeAll()
References countChanged().
removeAt()
void Isis::ShapeList::removeAt (int i)
Removes the shape at an index.
Parameters
i The index of the shape to be removed.
See also
QList<Shape *>::removeAt()
References countChanged().
removeFirst()
void Isis::ShapeList::removeFirst ()
Removes the shape at the front of the shape list.
See also
QList<Shape *>::removeFirst()
References countChanged().
removeLast()
void Isis::ShapeList::removeLast ()
Removes the shape at the end of the shape list.
See also
QList<Shape *>::removeLast()
References countChanged().
removeOne()
bool Isis::ShapeList::removeOne (Shape *const & value)
Removes the first occurance of an shape.
Parameters
value The shape to be removed.
Returns
bool True if successful, otherwise false.
See also
QList<Shape *>::removeOne()
References countChanged().
save()
void Isis::ShapeList::save (QXmlStreamWriter & stream, const Project * project, FileName newProjectRoot) const
Convert this shape list into XML format for saving/restoring capabilities.
This writes:
  <shapeList name="..." path="...">
to the given xml stream, and creates an 'shapes.xml' inside the folder with the shapes. Inside the shapes.xml, this writes:
  <shapes>
    ...
  </shapes>
Parameters
stream XmlStream to write out the document.
project The project the shape list will be saved to.
newProjectRoot The path to the root directory for the new project.
Exceptions
iException::Io "Failed to create directory"
iException::Io "Unable to save shape information because new file could not be opened for writing"
References _FILEINFO_, Isis::FileName::dir(), Isis::IException::Io, Isis::FileName::original(), Isis::FileName::path(), Isis::ReadWrite, Isis::Shape::save(), Isis::Project::shapeDataRoot(), and Isis::FileName::toString().
serialNumberList()
SerialNumberList Isis::ShapeList::serialNumberList ()
Creates a SerialNumberList from the shape list.
Returns
SerialNumberList The list of serial numbers for the cubes in the ShapeList.
References Isis::SerialNumberList::add().
setName()
void Isis::ShapeList::setName (QString newName)
Set the human-readable name of this shape list.
This is really only useful for project shape lists (not anonymous temporary ones).
Parameters
newName The name to give this shape list
Referenced by Isis::ProjectItemModel::setData().
setPath()
void Isis::ShapeList::setPath (QString newPath)
Set the relative path (from the project root) to this shape list's folder.
This is really only useful for project shape lists (not anonymous temporary ones).
Parameters
newPath The path to the shapes in this shape list
swap()
void Isis::ShapeList::swap (QList< Shape * > & other)
Swaps the shape list with another list of shapes.
Parameters
other The list of shapes to swapped with.
See also
QList<Shape *>::swap()
References countChanged().
takeAt()
Shape * Isis::ShapeList::takeAt (int i)
Removes the shape at an index and returns it.
Parameters
i The index of the shape to be removed and returned.
Returns
Shape * The removed shape.
See also
QList<Shape *>::takeAt()
References countChanged().
takeFirst()
Shape * Isis::ShapeList::takeFirst ()
Removes and returns the first shape.
Returns
Shape * The first shape.
See also
QList<Shape *>::takeFirst()
References countChanged().
takeLast()
Shape * Isis::ShapeList::takeLast ()
Removes and returns the last shape.
Returns
Shape * The last shape.
See also
QList<Shape *>::takeLast()
References countChanged().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ShapeList/ShapeList.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ShapeList/ShapeList.cpp