Isis Developer Reference: Isis::Average Class Reference
Isis::Average Class Reference
Functor for reduce using average functionality.
#include <Reduce.h>
Public Member Functions
Average (Isis::Cube *pInCube, double pdSampleScale, double pdLineScale, double pdValidPer, QString psReplaceMode)
Constructor.
void operator() (Isis::Buffer &out) const
Operator () overload.
Isis::PvlGroup UpdateOutputLabel (Isis::Cube *pOutCube)
Create label for the reduced output image.
void setInputBoundary (int startSample, int endSample, int startLine, int endLine)
Parameters to input image sub area.
Protected Attributes
Isis::Cube * mInCube
Input image.
double mdSampleScale
Sample scale.
double mdLineScale
Line scale.
int miStartSample
Input start sample.
int miEndSample
Input end sample.
int miStartLine
Input start line.
int miEndLine
Input end line.
double mdLine
Line index.
int miOutputSamples
Output Samples.
int miOutputLines
Output Lines.
int miInputSamples
Input Samples.
int miInputLines
Input Lines.
int miInputBands
Input Bands.
int miBandIndex
Band Index.
Isis::Portal * m_iPortal
Input portal.
Detailed Description
Functor for reduce using average functionality.
Author
2011-04-15 Sharmila Prasad
Constructor & Destructor Documentation
Average()
Isis::Average::Average (Isis::Cube * pInCube, double pdSampleScale, double pdLineScale, double pdValidPer, QString psReplaceMode) inline
Constructor.
Member Function Documentation
operator()()
void Isis::Average::operator() (Isis::Buffer & out) const
Operator () overload.
Average Operator () overload, parameter for StartProcessInPlace refer ProcessByLine, ProcessByBrick.
Parameters
out - output buffer
References Isis::Buffer::Band(), Isis::IsSpecial(), Isis::IsValidPixel(), Isis::Buffer::Line(), Isis::Null, Isis::PixelToString(), Isis::Buffer::size(), and Isis::StringToPixel().
setInputBoundary()
void Isis::Reduce::setInputBoundary (int startSample, int endSample, int startLine, int endLine) inherited
Parameters to input image sub area.
Parameters to input image sub area to be reduced.
Author
Sharmila Prasad (5/11/2011)
Parameters
startSample - input image start sample
endSample - input image end sample
startLine - input image start line
endLine - input image end line
UpdateOutputLabel()
Isis::PvlGroup Isis::Reduce::UpdateOutputLabel (Isis::Cube * pOutCube) inherited
Create label for the reduced output image.
Update the Mapping, Instrument, and AlphaCube groups in the output cube label.
Parameters
pOutCube - Resulting reduced output cube
pResultsGrp - This is the Results group that will go into the application log file. This group must be created by the calling application. Information will be added to it if the Mapping or Instrument groups are deleted from the output image label
References Isis::SubArea::SetSubArea(), Isis::toString(), and Isis::SubArea::UpdateLabel().
Member Data Documentation
m_iPortal
Isis::Portal* Isis::Reduce::m_iPortal protected inherited
Input portal.
mdLine
double Isis::Reduce::mdLine mutable protected inherited
Line index.
mdLineScale
double Isis::Reduce::mdLineScale protected inherited
Line scale.
mdSampleScale
double Isis::Reduce::mdSampleScale protected inherited
Sample scale.
miBandIndex
int Isis::Reduce::miBandIndex mutable protected inherited
Band Index.
miEndLine
int Isis::Reduce::miEndLine protected inherited
Input end line.
miEndSample
int Isis::Reduce::miEndSample protected inherited
Input end sample.
miInputBands
int Isis::Reduce::miInputBands protected inherited
Input Bands.
miInputLines
int Isis::Reduce::miInputLines protected inherited
Input Lines.
miInputSamples
int Isis::Reduce::miInputSamples protected inherited
Input Samples.
mInCube
Isis::Cube* Isis::Reduce::mInCube protected inherited
Input image.
miOutputLines
int Isis::Reduce::miOutputLines protected inherited
Output Lines.
miOutputSamples
int Isis::Reduce::miOutputSamples protected inherited
Output Samples.
miStartLine
int Isis::Reduce::miStartLine protected inherited
Input start line.
miStartSample
int Isis::Reduce::miStartSample protected inherited
Input start sample.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Reduce/Reduce.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Reduce/Reduce.cpp