Isis Developer Reference: Isis::ControlMeasureLogData Class Reference
Isis::ControlMeasureLogData Class Reference
Statistical and similar ControlMeasure associated information.
#include <ControlMeasureLogData.h>
Public Types
enum NumericLogDataType {
InvalidNumericLogDataType = 0 , Obsolete_Eccentricity = 1 , GoodnessOfFit = 2 , MinimumPixelZScore = 3 ,
MaximumPixelZScore = 4 , PixelShift = 5 , WholePixelCorrelation = 6 , SubPixelCorrelation = 7 ,
Obsolete_AverageResidual = 8
}
Please do not change existing values in this list except the size - it will break backwards compadibility.
Public Member Functions
ControlMeasureLogData ()
This creates an empty, invalid (IsValid() will return false), instance.
ControlMeasureLogData (NumericLogDataType dataType)
This creates an instance with the given type but no value yet.
ControlMeasureLogData (PvlKeyword keywordRep)
This creates an instance while attempting to interpret keywordRep.
ControlMeasureLogData (NumericLogDataType dataType, double value)
This creates an instance with the given type and value for that type.
ControlMeasureLogData (const ControlMeasureLogData &other)
Copy constructor.
~ControlMeasureLogData ()
Destructor.
void SetNumericalValue (double value)
This updates the value associated with a NumericLogDataType.
void SetDataType (NumericLogDataType newDataType)
This changes the type of this log data.
double GetNumericalValue () const
Get the value associated with this log data.
NumericLogDataType GetDataType () const
Get the data type associated with this log data.
QVariant GetValue () const
Get the data type associated with this log data.
bool IsValid () const
This tests if the log data is complete and valid.
PvlKeyword ToKeyword () const
This converts the log data to a PvlKeyword.
NumericLogDataType NameToDataType (QString name) const
This converts a string to a log data type and is useful for converting Pvl keywords to Numeric Log Data Type.
QString DataTypeToName (NumericLogDataType type) const
This converts the log data type to a string and is used internally for convertions to and from Pvl.
Static Public Attributes
static const int MaximumNumericLogDataType = 9
This value must be > the largest enumerated value in this type or convertions to and from Pvl will not work.
Detailed Description
Statistical and similar ControlMeasure associated information.
This class represents information that is related to, or associated with, a control measure but is not part of the measure itself.
Author
2010-12-22 Steven Lambright
See also
ControlMeasure
Member Enumeration Documentation
NumericLogDataType
enum Isis::ControlMeasureLogData::NumericLogDataType
Please do not change existing values in this list except the size - it will break backwards compadibility.
This is the list of log data for control measures. To add a new element, put it in the list (anywhere), assign it a value one greater than the current maximum, and increase the maximum's value. Then add a case to ControlMeasureLogData::DataTypeToName. Once you've done that, you're done! :)
Enumerator
InvalidNumericLogDataType
This is a placeholder for unset values.
Obsolete_Eccentricity
Deprecated keyword kept for backwards compatability with older Control Networks.
DO NOT USE!!
GoodnessOfFit
GoodnessOfFit is pointreg information for reference measures.
This measures how well the computed fit area matches the pattern area.
MinimumPixelZScore
Control measures store z-scores in pairs.
A pair contains the z-scores of the minimum and maximum pixels in the pattern chip generated for the given measure during point registration. Each z-score indicates how many standard deviations the given pixel value is above or below the mean DN.
MaximumPixelZScore
See also
MinimumPixelZScore
PixelShift
Deprecated keyword kept for backwards compatability with older Control Networks.
DO NOT USE!!
WholePixelCorrelation
Deprecated keyword kept for backwards compatability with older Control Networks.
DO NOT USE!!
SubPixelCorrelation
Deprecated keyword kept for backwards compatability with older Control Networks.
DO NOT USE!!
Obsolete_AverageResidual
Deprecated keyword kept for backwards compatability with older Control Networks.
DO NOT USE!!
Constructor & Destructor Documentation
ControlMeasureLogData() [1/5]
Isis::ControlMeasureLogData::ControlMeasureLogData ()
This creates an empty, invalid (IsValid() will return false), instance.
ControlMeasureLogData() [2/5]
Isis::ControlMeasureLogData::ControlMeasureLogData (NumericLogDataType dataType)
This creates an instance with the given type but no value yet.
IsValid() will return false until a value is set.
Parameters
dataType What the instance is describing (the field)
ControlMeasureLogData() [3/5]
Isis::ControlMeasureLogData::ControlMeasureLogData (PvlKeyword keywordRep)
This creates an instance while attempting to interpret keywordRep.
On failure, the IsValid() test will return false.
Parameters
keywordRep The PvlKeyword representing log data
References InvalidNumericLogDataType, Isis::PvlKeyword::name(), NameToDataType(), and Isis::toDouble().
ControlMeasureLogData() [4/5]
Isis::ControlMeasureLogData::ControlMeasureLogData (NumericLogDataType dataType, double value)
This creates an instance with the given type and value for that type.
Parameters
dataType What the value is describing (the field)
value The numerical value of this field
ControlMeasureLogData() [5/5]
Isis::ControlMeasureLogData::ControlMeasureLogData (const ControlMeasureLogData & other)
Copy constructor.
Parameters
other The instance to copy into this one.
~ControlMeasureLogData()
Isis::ControlMeasureLogData::~ControlMeasureLogData ()
Destructor.
This frees allocated memory by the instance of this class.
Member Function Documentation
DataTypeToName()
QString Isis::ControlMeasureLogData::DataTypeToName (NumericLogDataType type) const
This converts the log data type to a string and is used internally for convertions to and from Pvl.
This is also useful for GUI programs that need to display log information.
Parameters
type The data type to convert to a string
References _FILEINFO_, GoodnessOfFit, InvalidNumericLogDataType, MaximumPixelZScore, MinimumPixelZScore, Obsolete_AverageResidual, Obsolete_Eccentricity, PixelShift, Isis::IException::Programmer, SubPixelCorrelation, Isis::toString(), and WholePixelCorrelation.
Referenced by NameToDataType(), ToKeyword(), and Isis::ControlMeasure::UpdateLogData().
GetDataType()
ControlMeasureLogData::NumericLogDataType Isis::ControlMeasureLogData::GetDataType () const
Get the data type associated with this log data.
The return value is InvalidNumericLogDataType is no value has been set..
Returns
A numerical representation of the current DataType
Referenced by Isis::ControlPointV0003::ControlPointV0003(), Isis::ControlMeasure::DeleteLogData(), Isis::ControlMeasure::GetLogData(), Isis::ControlMeasure::GetLogValue(), Isis::ControlMeasure::HasLogData(), Isis::ControlMeasure::SetLogData(), and Isis::ControlMeasure::UpdateLogData().
GetNumericalValue()
double Isis::ControlMeasureLogData::GetNumericalValue () const
Get the value associated with this log data.
Returns Null is IsValid() if false.
Returns
A numerical representation of the current DataType
Referenced by Isis::ControlPointV0003::ControlPointV0003(), Isis::GoodnessOfFitFilter::evaluate(), Isis::AbstractMeasureItem::getData(), Isis::ControlPoint::GetStatistic(), and Isis::ControlNetFilter::PointGoodnessOfFitFilter().
GetValue()
QVariant Isis::ControlMeasureLogData::GetValue () const
Get the data type associated with this log data.
The return value is an invalid variant type if the value is not set.
Referenced by Isis::ControlMeasure::GetLogValue().
IsValid()
bool Isis::ControlMeasureLogData::IsValid () const
This tests if the log data is complete and valid.
Returns
True if type and value are known, false otherwise
References InvalidNumericLogDataType, and Isis::Null.
Referenced by Isis::ControlPointV0003::ControlPointV0003(), Isis::ControlMeasure::SetLogData(), and ToKeyword().
NameToDataType()
ControlMeasureLogData::NumericLogDataType Isis::ControlMeasureLogData::NameToDataType (QString name) const
This converts a string to a log data type and is useful for converting Pvl keywords to Numeric Log Data Type.
Parameters
name The string to convert to data type
Returns
The data type converted from a string
References DataTypeToName(), InvalidNumericLogDataType, and MaximumNumericLogDataType.
Referenced by ControlMeasureLogData().
SetDataType()
void Isis::ControlMeasureLogData::SetDataType (NumericLogDataType newDataType)
This changes the type of this log data.
This will reset the value of the log data also.
Parameters
newDataType The data type this log data should represent
SetNumericalValue()
void Isis::ControlMeasureLogData::SetNumericalValue (double value)
This updates the value associated with a NumericLogDataType.
Parameters
value The new value for this log data
ToKeyword()
PvlKeyword Isis::ControlMeasureLogData::ToKeyword () const
This converts the log data to a PvlKeyword.
These should be understandable by the constructor.
Returns
A PVL representation of this log data
References DataTypeToName(), IsValid(), and Isis::toString().
Referenced by Isis::ControlNetVersioner::toPvl().
Member Data Documentation
MaximumNumericLogDataType
const int Isis::ControlMeasureLogData::MaximumNumericLogDataType = 9 static
This value must be > the largest enumerated value in this type or convertions to and from Pvl will not work.
Referenced by NameToDataType().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/ControlMeasureLogData/ControlMeasureLogData.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/ControlMeasureLogData/ControlMeasureLogData.cpp