Isis Developer Reference: Isis::ImagePointFilterSelector Class Reference
Isis::ImagePointFilterSelector Class Reference
Allows users to choose filters for filtering images and points.
#include <ImagePointFilterSelector.h>
Public Slots
void sendClose ()
Signals
void close (AbstractFilterSelector *)
void filterChanged ()
void sizeChanged ()
Public Member Functions
ImagePointFilterSelector ()
ImagePointFilterSelector (const ImagePointFilterSelector &other)
virtual ~ImagePointFilterSelector ()
ImagePointFilterSelector & operator= (const ImagePointFilterSelector &other)
template<typename Evaluatable >
bool evaluate (const Evaluatable *evaluatable) const
bool hasFilter () const
bool hasFilter (bool(AbstractFilter::*)() const) const
QString getDescription (QString(AbstractFilter::*)() const) const
Protected Slots
virtual void deleteFilter ()
Protected Member Functions
void createSelector ()
void changeFilter (int)
void nullify ()
QComboBox * getSelector () const
QHBoxLayout * getMainLayout () const
AbstractFilter * getFilter () const
void setFilter (AbstractFilter *)
Detailed Description
Allows users to choose filters for filtering images and points.
This class is responsible for creating a list of filters that can be selected for filtering images and points.
Author
????-??-?? Eric Hyer
Constructor & Destructor Documentation
ImagePointFilterSelector() [1/2]
Isis::ImagePointFilterSelector::ImagePointFilterSelector ()
References createSelector(), and Isis::AbstractFilterSelector::nullify().
ImagePointFilterSelector() [2/2]
Isis::ImagePointFilterSelector::ImagePointFilterSelector (const ImagePointFilterSelector & other)
References Isis::AbstractFilter::clone(), createSelector(), Isis::AbstractFilterSelector::getFilter(), Isis::AbstractFilterSelector::getSelector(), and Isis::AbstractFilterSelector::setFilter().
~ImagePointFilterSelector()
Isis::ImagePointFilterSelector::~ImagePointFilterSelector () virtual
Member Function Documentation
changeFilter()
void Isis::ImagePointFilterSelector::changeFilter (int index) protected virtual
Implements Isis::AbstractFilterSelector.
References Isis::AbstractFilterSelector::deleteFilter(), Isis::AbstractFilterSelector::filterChanged(), Isis::AbstractFilter::Images, Isis::AbstractFilter::Points, Isis::AbstractFilterSelector::setFilter(), and Isis::AbstractFilterSelector::sizeChanged().
close
void Isis::AbstractFilterSelector::close (AbstractFilterSelector *) signal inherited
Referenced by Isis::AbstractFilterSelector::sendClose().
createSelector()
void Isis::ImagePointFilterSelector::createSelector () protected virtual
Reimplemented from Isis::AbstractFilterSelector.
References Isis::AbstractFilterSelector::createSelector(), Isis::CnetDisplayProperties::getInstance(), Isis::AbstractFilterSelector::getSelector(), and Isis::CnetDisplayProperties::XYZ.
Referenced by ImagePointFilterSelector().
deleteFilter
void Isis::AbstractFilterSelector::deleteFilter () protected virtual slot inherited
Referenced by Isis::ImageImageFilterSelector::changeFilter(), changeFilter(), Isis::PointMeasureFilterSelector::changeFilter(), and Isis::AbstractFilterSelector::~AbstractFilterSelector().
evaluate()
template<typename Evaluatable > bool Isis::AbstractFilterSelector::evaluate (const Evaluatable * evaluatable) const inline inherited
References Isis::AbstractFilter::evaluate().
filterChanged
void Isis::AbstractFilterSelector::filterChanged () signal inherited
Referenced by changeFilter(), Isis::PointMeasureFilterSelector::changeFilter(), and Isis::AbstractFilterSelector::setFilter().
getDescription()
QString Isis::AbstractFilterSelector::getDescription (QString(AbstractFilter::*)() const meth) const inherited
getFilter()
AbstractFilter * Isis::AbstractFilterSelector::getFilter () const protected inherited
Referenced by Isis::ImageImageFilterSelector::ImageImageFilterSelector(), ImagePointFilterSelector(), Isis::PointMeasureFilterSelector::PointMeasureFilterSelector(), and Isis::AbstractFilterSelector::setFilter().
getMainLayout()
QHBoxLayout * Isis::AbstractFilterSelector::getMainLayout () const protected inherited
Referenced by Isis::AbstractFilterSelector::setFilter().
getSelector()
QComboBox * Isis::AbstractFilterSelector::getSelector () const protected inherited
Referenced by createSelector(), Isis::PointMeasureFilterSelector::createSelector(), Isis::ImageImageFilterSelector::ImageImageFilterSelector(), ImagePointFilterSelector(), Isis::AbstractFilterSelector::operator=(), and Isis::PointMeasureFilterSelector::PointMeasureFilterSelector().
hasFilter() [1/2]
bool Isis::AbstractFilterSelector::hasFilter () const inherited
hasFilter() [2/2]
bool Isis::AbstractFilterSelector::hasFilter (bool(AbstractFilter::*)() const meth) const inherited
nullify()
void Isis::AbstractFilterSelector::nullify () protected inherited
Referenced by Isis::AbstractFilterSelector::AbstractFilterSelector(), Isis::ImageImageFilterSelector::ImageImageFilterSelector(), and ImagePointFilterSelector().
operator=()
ImagePointFilterSelector & Isis::ImagePointFilterSelector::operator= (const ImagePointFilterSelector & other)
sendClose
void Isis::AbstractFilterSelector::sendClose () slot inherited
References Isis::AbstractFilterSelector::close().
Referenced by Isis::AbstractFilterSelector::createSelector().
setFilter()
void Isis::AbstractFilterSelector::setFilter (AbstractFilter * someFilter) protected inherited
References Isis::AbstractFilterSelector::filterChanged(), Isis::AbstractFilterSelector::getFilter(), and Isis::AbstractFilterSelector::getMainLayout().
Referenced by changeFilter(), Isis::PointMeasureFilterSelector::changeFilter(), Isis::ImageImageFilterSelector::ImageImageFilterSelector(), ImagePointFilterSelector(), Isis::AbstractFilterSelector::operator=(), and Isis::PointMeasureFilterSelector::PointMeasureFilterSelector().
sizeChanged
void Isis::AbstractFilterSelector::sizeChanged () signal inherited
Referenced by changeFilter(), and Isis::PointMeasureFilterSelector::changeFilter().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/ImagePointFilterSelector.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/ImagePointFilterSelector.cpp