Isis Developer Reference: Isis::CnetEditorWidget Class Reference
Isis::CnetEditorWidget Class Reference
This widget provides full editing, filtering and viewing capabilities for the raw data in a control network.
#include <CnetEditorWidget.h>
Public Types
enum View { PointView , ImageView , ConnectionView }
Public Slots
void configSorting ()
Configures the sorting dialog.
void setLatLonRadiusCoordinateDisplay ()
Set control point coordinate display type to latitude, longitude, radius.
void setXYZCoordinateDisplay ()
Set control point coordinate display type to X,Y,Z.
void setTablesFrozen (bool)
Sets if the tables are frozen.
void rebuildModels ()
Rebuilds the models.
Signals
void cnetModified ()
void editControlPoint (ControlPoint *controlPoint, QString serialNumber)
void coordinateDisplayTypeChanged ()
Public Member Functions
CnetEditorWidget (Control *control, QString pathForSettings)
virtual ~CnetEditorWidget ()
Destructor.
void readSettings ()
Reads the working version settings stored at the settings path.
void writeSettings ()
Writes the configuration settings used.
QWidget * pointTreeView ()
Returns the point tree view.
QWidget * serialTreeView ()
Returns the serial tree view.
QWidget * connectionTreeView ()
Returns the connection tree view.
QWidget * pointFilterWidget ()
Returns the point filter widget.
QWidget * serialFilterWidget ()
Returns the serial filter widget.
QWidget * connectionFilterWidget ()
Returns the connection filter widget.
TableView * pointTableView ()
Returns the point table view.
TableView * measureTableView ()
Returns the measure table view.
ControlNet * control ()
Returns the control network.
AbstractTableModel * measureTableModel ()
Returns the measure table model.
AbstractTableModel * pointTableModel ()
Returns the point table model.
QMap< QAction *, QList< QString > > menuActions ()
Returns the menu actions.
QMap< QString, QList< QAction * > > toolBarActions ()
Returns the tool bar actions.
ControlNet * filteredNetwork () const
Returns the filtered control net.
bool measureTableSortingEnabled () const
Returns true if the measure table can be sorted.
int measureTableSortLimit () const
Returns the sorting limit for the measure table.
bool pointTableSortingEnabled () const
Returns true if the point table can be sorted.
int pointTableSortLimit () const
Returns the sorting limit for the point table.
void setMeasureTableSortingEnabled (bool enabled)
Sets if the measure table can be sorted.
void setMeasureTableSortLimit (int limit)
Sets the measure table sorting limit.
void setPointTableSortingEnabled (bool enabled)
Sets if the point table can be sorted.
void setPointTableSortLimit (int limit)
Sets the point table sorting limit.
Detailed Description
This widget provides full editing, filtering and viewing capabilities for the raw data in a control network.
The raw data is, for example, chooser name or cube serial number. The display is all textual. Please use the widget accessors to appropriately place the various ancillary sections of the editor.
Author
????-??-?? Eric Hyer
Member Enumeration Documentation
View
enum Isis::CnetEditorWidget::View
Enumerator
PointView
ImageView
ConnectionView
Constructor & Destructor Documentation
CnetEditorWidget()
Isis::CnetEditorWidget::CnetEditorWidget (Control * control, QString pathForSettings)
References cnetModified(), control(), Isis::CnetDisplayProperties::getInstance(), readSettings(), and rebuildModels().
~CnetEditorWidget()
Isis::CnetEditorWidget::~CnetEditorWidget () virtual
Destructor.
References writeSettings().
Member Function Documentation
cnetModified
void Isis::CnetEditorWidget::cnetModified () signal
Referenced by CnetEditorWidget().
configSorting
void Isis::CnetEditorWidget::configSorting () slot
Configures the sorting dialog.
If one does not already exist, create it, then show the dialog
connectionFilterWidget()
QWidget * Isis::CnetEditorWidget::connectionFilterWidget ()
Returns the connection filter widget.
Returns
QWidget The connection filter widget
connectionTreeView()
QWidget * Isis::CnetEditorWidget::connectionTreeView ()
Returns the connection tree view.
Returns
QWidget The connection tree view
control()
ControlNet * Isis::CnetEditorWidget::control ()
Returns the control network.
Returns
ControlNet The control network
References Isis::Control::controlNet().
Referenced by CnetEditorWidget().
coordinateDisplayTypeChanged
void Isis::CnetEditorWidget::coordinateDisplayTypeChanged () signal
Referenced by setLatLonRadiusCoordinateDisplay(), and setXYZCoordinateDisplay().
editControlPoint
void Isis::CnetEditorWidget::editControlPoint (ControlPoint * controlPoint, QString serialNumber) signal
filteredNetwork()
ControlNet * Isis::CnetEditorWidget::filteredNetwork () const
Returns the filtered control net.
Returns
ControlNet Filtered control network
References Isis::Control::controlNet(), Isis::ControlPoint::Delete(), Isis::ControlNet::DeletePoint(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::ControlPoint::GetId(), Isis::AbstractTreeModel::getItems(), Isis::ControlPoint::GetMeasure(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlNet::GetNumPoints(), Isis::ControlNet::GetPoint(), Isis::AbstractTreeItem::Measure, Isis::AbstractTreeModel::MeasureItems, Isis::ControlMeasure::Parent(), Isis::AbstractTreeItem::Point, Isis::AbstractTreeModel::PointItems, Isis::ControlMeasure::SetEditLock(), and Isis::ControlPoint::SetEditLock().
measureTableModel()
AbstractTableModel * Isis::CnetEditorWidget::measureTableModel ()
Returns the measure table model.
Returns
AbstractTableModel The measure table model
measureTableSortingEnabled()
bool Isis::CnetEditorWidget::measureTableSortingEnabled () const
Returns true if the measure table can be sorted.
Returns
bool True if sorting is enabled on the measure table
References Isis::AbstractTableModel::sortingIsEnabled().
Referenced by writeSettings().
measureTableSortLimit()
int Isis::CnetEditorWidget::measureTableSortLimit () const
Returns the sorting limit for the measure table.
Returns
int The sorting limit for the measure table
References Isis::AbstractTableModel::sortLimit().
Referenced by writeSettings().
measureTableView()
TableView * Isis::CnetEditorWidget::measureTableView ()
Returns the measure table view.
Returns
TableView The measure table view
Referenced by Isis::Directory::addCnetEditorView().
menuActions()
QMap< QAction *, QList< QString > > Isis::CnetEditorWidget::menuActions ()
Returns the menu actions.
Returns
QMap< QAction *, QList< QString > > QMap of menu actions
pointFilterWidget()
QWidget * Isis::CnetEditorWidget::pointFilterWidget ()
Returns the point filter widget.
Returns
QWidget The point filter widget
pointTableModel()
AbstractTableModel * Isis::CnetEditorWidget::pointTableModel ()
Returns the point table model.
Returns
AbstractTableModel The point table model
pointTableSortingEnabled()
bool Isis::CnetEditorWidget::pointTableSortingEnabled () const
Returns true if the point table can be sorted.
Returns
bool True if sorting is enabled on the point table
References Isis::AbstractTableModel::sortingIsEnabled().
Referenced by writeSettings().
pointTableSortLimit()
int Isis::CnetEditorWidget::pointTableSortLimit () const
Returns the sorting limit for the point table.
Returns
int The sorting limit for the point table
References Isis::AbstractTableModel::sortLimit().
Referenced by writeSettings().
pointTableView()
TableView * Isis::CnetEditorWidget::pointTableView ()
Returns the point table view.
Returns
TableView The point table view
Referenced by Isis::Directory::addCnetEditorView().
pointTreeView()
QWidget * Isis::CnetEditorWidget::pointTreeView ()
Returns the point tree view.
Returns
QWidget The point tree view
readSettings()
void Isis::CnetEditorWidget::readSettings ()
Reads the working version settings stored at the settings path.
References Isis::AbstractMeasureItem::getColumnName(), Isis::AbstractPointItem::getColumnName(), Isis::TableView::getHorizontalHeader(), setMeasureTableSortingEnabled(), setMeasureTableSortLimit(), setPointTableSortingEnabled(), and setPointTableSortLimit().
Referenced by CnetEditorWidget().
rebuildModels
void Isis::CnetEditorWidget::rebuildModels () slot
Rebuilds the models.
Referenced by CnetEditorWidget().
serialFilterWidget()
QWidget * Isis::CnetEditorWidget::serialFilterWidget ()
Returns the serial filter widget.
Returns
QWidget The serial filter widget
serialTreeView()
QWidget * Isis::CnetEditorWidget::serialTreeView ()
Returns the serial tree view.
Returns
QWidget The serial tree view
setLatLonRadiusCoordinateDisplay
void Isis::CnetEditorWidget::setLatLonRadiusCoordinateDisplay () slot
Set control point coordinate display type to latitude, longitude, radius.
TODO: can we selectively rebuild only the columns that need to be re-displayed?
References coordinateDisplayTypeChanged(), Isis::CnetDisplayProperties::getInstance(), Isis::CnetDisplayProperties::LatLonRadius, Isis::PointMeasureTreeModel::rebuildItems(), and Isis::CnetDisplayProperties::setCoordinateDisplayType().
setMeasureTableSortingEnabled()
void Isis::CnetEditorWidget::setMeasureTableSortingEnabled (bool enabled)
Sets if the measure table can be sorted.
Parameters
bool Bool if the table can be sorted or not
References Isis::AbstractTableModel::setSortingEnabled().
Referenced by readSettings().
setMeasureTableSortLimit()
void Isis::CnetEditorWidget::setMeasureTableSortLimit (int limit)
Sets the measure table sorting limit.
Parameters
int Sorting limit
References Isis::AbstractTableModel::setSortLimit().
Referenced by readSettings().
setPointTableSortingEnabled()
void Isis::CnetEditorWidget::setPointTableSortingEnabled (bool enabled)
Sets if the point table can be sorted.
Parameters
bool Bool if the table can be sorted or not
References Isis::AbstractTableModel::setSortingEnabled().
Referenced by readSettings().
setPointTableSortLimit()
void Isis::CnetEditorWidget::setPointTableSortLimit (int limit)
Sets the point table sorting limit.
Parameters
int Sorting limit
References Isis::AbstractTableModel::setSortLimit().
Referenced by readSettings().
setTablesFrozen
void Isis::CnetEditorWidget::setTablesFrozen (bool freezeTables) slot
Sets if the tables are frozen.
Parameters
bool Bool that freezes the tables or not
References Isis::AbstractTreeModel::setFrozen().
setXYZCoordinateDisplay
void Isis::CnetEditorWidget::setXYZCoordinateDisplay () slot
Set control point coordinate display type to X,Y,Z.
TODO: can we selectively rebuild only the columns that need to be re-displayed?
References coordinateDisplayTypeChanged(), Isis::CnetDisplayProperties::getInstance(), Isis::PointMeasureTreeModel::rebuildItems(), Isis::CnetDisplayProperties::setCoordinateDisplayType(), and Isis::CnetDisplayProperties::XYZ.
toolBarActions()
QMap< QString, QList< QAction * > > Isis::CnetEditorWidget::toolBarActions ()
Returns the tool bar actions.
Returns
QMap< QAction *, QList< QString > > QMap of tool bar actions
writeSettings()
void Isis::CnetEditorWidget::writeSettings ()
Writes the configuration settings used.
References Isis::AbstractMeasureItem::getColumnName(), Isis::AbstractPointItem::getColumnName(), Isis::TableView::getHorizontalHeader(), measureTableSortingEnabled(), measureTableSortLimit(), pointTableSortingEnabled(), and pointTableSortLimit().
Referenced by ~CnetEditorWidget().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/CnetEditorWidget.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/CnetEditorWidget.cpp