Isis Developer Reference: Isis::BoxcarManager Class Reference
Isis::BoxcarManager Class Reference
Low Level Cube I/O
Buffer manager, for moving through a cube by boxcar.
#include <BoxcarManager.h>
Public Member Functions
BoxcarManager (const Isis::Cube &cube, const int &boxSamples, const int &boxLines)
Constructs a BoxcarManager object.
~BoxcarManager ()
Destroys the BoxcarManager object.
bool operator++ (int)
Moves the shape buffer to the next position.
BufferManager & operator+= (int i)
Moves the shape buffer by a certain amount.
bool begin ()
Moves the shape buffer to the first position.
bool next ()
Moves the shape buffer to the next position.
bool end () const
Returns true if the shape buffer has accessed the end of the cube.
bool setpos (BigInt map)
Sets the position of the shape in the cube.
void swap (BufferManager &other)
Swaps the values of this BufferManager with that of another.
int SampleDimension () const
Returns the number of samples in the shape buffer.
int LineDimension () const
Returns the number of lines in the shape buffer.
int BandDimension () const
Returns the number of bands in the shape buffer.
int size () const
Returns the total number of pixels in the shape buffer.
int Sample (const int index=0) const
Returns the sample position associated with a shape buffer index.
int Line (const int index=0) const
Returns the line position associated with a shape buffer index.
int Band (const int index=0) const
Returns the band position associated with a shape buffer index.
void Position (const int index, int &i_samp, int &i_line, int &i_band) const
Returns the sample, line, and band position associated with a shape buffer index.
int Index (const int i_samp, const int i_line, const int i_band) const
Given a sample, line, and band position, this returns the appropriate index in the shape buffer.
double at (const int index) const
Returns the value in the shape buffer at the given index.
double & operator[] (const int index)
Returns the value in the shape buffer at given index.
const double & operator[] (const int index) const
Returns the value in the shape buffer at given index.
double * DoubleBuffer () const
Returns the value of the shape buffer.
void Copy (const Buffer &in, bool includeRawBuf=true)
Allows copying of the buffer contents to another Buffer.
bool CopyOverlapFrom (const Buffer &in)
Allows copying of the buffer contents of a larger buffer to another same size or smaller Buffer, using their base positions to relate data.
void * RawBuffer () const
Returns a void pointer to the raw buffer.
Isis::PixelType PixelType () const
Returns the raw buffer pixel type.
Protected Member Functions
int MaxSamples () const
Returns the number of samples in the cube.
int MaxLines () const
Returns the number of lines in the cube.
int MaxBands () const
Returns the number of bands in the cube.
BigInt MaxMaps () const
Returns the maximum number of positions the shape buffer needs to cover the entire image (see setpos method for more info).
void SetIncrements (const int sinc, const int linc, const int binc)
Sets how the shape is incremented through the cube.
void SetOffsets (const int soff, const int loff, const int boff)
Sets the offset of the buffer.
void SetBasePosition (const int start_sample, const int start_line, const int start_band)
This method is used to set the base position of the shape buffer.
void SetBaseSample (const int start_samp)
This method is used to set the base sample position of the shape buffer.
void SetBaseLine (const int start_line)
This method is used to set the base line position of the shape buffer.
void SetBaseBand (const int start_band)
This method is used to set the base band position of the shape buffer.
void Allocate ()
Size or resize the memory buffer.
Protected Attributes
int p_sample
Starting sample to read/write.
int p_nsamps
Number of samples to read/write.
int p_line
Starting line to read/write.
int p_nlines
Number of lines to read/write.
int p_band
Starting band to read/write.
int p_nbands
Number of bands to read/write.
int p_npixels
Number of pixels (nsamps * nlines * nbands)
double * p_buf
Shape buffer allocated to the size of npixels for handling reads/writes.
const Isis::PixelType p_pixelType
The pixel type of the raw buffer.
void * p_rawbuf
The raw dm read from the disk.
Detailed Description
Buffer manager, for moving through a cube by boxcar.
This class is used as a manager for moving through a cube one boxcar at a time. A boxcar is defined as two-dimensional (n samples by m lines) sub area of a cube. The band direction is always one deep.
The sequence of boxcars starts with the boxcar containing sample one, line one and band one. It then moves across the cube in the sample direction one pixel at a time, then the line direction and finally to the next boxcar in the band direction.
The pixel being processed will be indexed into the boxcar buffer as follows: index = (int((boxLines-1)/2) * boxSamples) + int((boxSamples-1)/2), for example, if the boxcar is 5x5, the pixel being processed would be at sample 3, line 3 of the boxcar. If the boxcar is a 4x4, the pixel being processed would be at sample 2, line 2.
If you would like to see BoxcarManager being used in implementation, see the ProcessByBoxcar class.
Author
2003-01-02 Tracie Sucharski
Constructor & Destructor Documentation
BoxcarManager()
Isis::BoxcarManager::BoxcarManager (const Isis::Cube & cube, const int & boxSamples, const int & boxLines)
Constructs a BoxcarManager object.
Parameters
cube The cube this buffer will be associated with.
boxSamples The number of samples in each boxcar buffer.
boxLines The number of lines in each boxcar buffer.
References Isis::BufferManager::SetIncrements(), and Isis::BufferManager::SetOffsets().
~BoxcarManager()
Isis::BoxcarManager::~BoxcarManager () inline
Destroys the BoxcarManager object.
Member Function Documentation
Allocate()
void Isis::Buffer::Allocate () protected inherited
Size or resize the memory buffer.
Exceptions
Isis::iException::System - Memory allocation failed
References _FILEINFO_, Isis::Message::MemoryAllocationFailed(), Isis::Buffer::p_buf, Isis::Buffer::p_npixels, Isis::Buffer::p_pixelType, Isis::Buffer::p_rawbuf, Isis::SizeOf(), and Isis::IException::Unknown.
Referenced by Isis::Buffer::Buffer(), and Isis::Brick::Resize().
at()
double Isis::Buffer::at (const int index) const inherited
Returns the value in the shape buffer at the given index.
Parameters
index Index position in buffer. Out of bounds index is trapped.
Returns
double Buffer value at index
Exceptions
Isis::iException::Programmer - Array Subscript not in range
References _FILEINFO_, Isis::Message::ArraySubscriptNotInRange(), Isis::Buffer::p_buf, Isis::Buffer::p_npixels, and Isis::IException::Programmer.
Referenced by Isis::CubeDataThreadTester::BrickChanged(), Isis::ViewportBuffer::DataReady(), Isis::ViewportBuffer::fillBuffer(), Isis::CubeDataThreadTester::ReadBrick(), and Isis::CubeDataThreadTester::ReadWriteBrick().
Band()
int Isis::Buffer::Band (const int index = 0) const inherited
Returns the band position associated with a shape buffer index.
The shape buffer is one dimensional. Let us assume a nsamps=2, nlines=3, and nbands=2. Therefore the total size of the shape buffer is 12 and valid index values are 0-11. Indexes 0-5 will return band 1 and 6-11 will return band 2.
Parameters
index Shape buffer index to map to a band position. Defaults to 0.
Returns
int The absolute band number based on the buffer index.
References Isis::Buffer::p_band, Isis::Buffer::p_nlines, and Isis::Buffer::p_nsamps.
Referenced by Isis::Buffer::CopyOverlapFrom(), Isis::IndependentCubeViewport::cubeDataChanged(), main(), Isis::SpectralDefinition2D::operator()(), Isis::Equalization::ApplyFunctor::operator()(), Isis::ImageImporter::operator()(), Isis::Average::operator()(), Isis::Buffer::Position(), Isis::CubeIoHandler::read(), and Isis::ProcessRubberSheet::StartProcess().
BandDimension()
int Isis::Buffer::BandDimension () const inline inherited
Returns the number of bands in the shape buffer.
Returns
int
References Isis::Buffer::p_nbands.
Referenced by Isis::IndependentCubeViewport::cubeDataChanged(), Isis::CubeIoHandler::read(), Isis::RegionalCachingAlgorithm::recommendChunksToFree(), and Isis::Hillshade::shadedValue().
begin()
bool Isis::BufferManager::begin () inline inherited
Moves the shape buffer to the first position.
Returns
bool
References Isis::BufferManager::setpos().
Referenced by Isis::Cube::copy(), Isis::ProcessExport::GetBuffersBIL(), Isis::ProcessExport::GetBuffersBIP(), Isis::ProcessExport::GetBuffersBSQ(), main(), Isis::ProcessRubberSheet::StartProcess(), Isis::ProcessByBrick::StartProcess(), Isis::ProcessExport::StartProcess(), and Isis::ProcessByBoxcar::StartProcess().
Copy()
void Isis::Buffer::Copy (const Buffer & in, bool includeRawBuf = true) inherited
Allows copying of the buffer contents to another Buffer.
Parameters
in The Buffer to be copied.
includeRawBuf Whether to include raw dm read from disk
Exceptions
Isis::iException::Programmer - Input and Output buffers are not the same size
Isis::iException::Programmer - Input and Output buffers do not use the same pixel type
References _FILEINFO_, Isis::Buffer::p_buf, Isis::Buffer::p_npixels, Isis::Buffer::p_pixelType, Isis::Buffer::p_rawbuf, Isis::Buffer::PixelType(), Isis::IException::Programmer, Isis::Buffer::size(), and Isis::SizeOf().
Referenced by Isis::Buffer::Buffer(), and Isis::Cube::copy().
CopyOverlapFrom()
bool Isis::Buffer::CopyOverlapFrom (const Buffer & in) inherited
Allows copying of the buffer contents of a larger buffer to another same size or smaller Buffer, using their base positions to relate data.
This does not copy the raw buffer.
Parameters
in The Buffer to be copied.
Returns
The operation was successful (the buffers overlapped)
References Isis::Buffer::Band(), Isis::Buffer::Index(), Isis::Buffer::Line(), Isis::Buffer::p_band, Isis::Buffer::p_line, Isis::Buffer::p_nbands, Isis::Buffer::p_nlines, Isis::Buffer::p_npixels, Isis::Buffer::p_nsamps, Isis::Buffer::p_sample, Isis::Buffer::Sample(), and Isis::Buffer::size().
DoubleBuffer()
double* Isis::Buffer::DoubleBuffer () const inline inherited
Returns the value of the shape buffer.
Returns
double* The shape buffer
References Isis::Buffer::p_buf.
Referenced by Isis::Process::CalculateStatistics(), Isis::IndependentCubeViewport::cubeDataChanged(), Isis::Chip::Extract(), Isis::StretchTool::histFromCube(), Isis::Cube::histogram(), Isis::ImageHistogram::ImageHistogram(), Isis::DemShape::localRadius(), Isis::OverlapStatistics::OverlapStatistics(), Isis::HistogramTool::refreshPlot(), Isis::ProcessByQuickFilter::StartProcess(), Isis::Cube::statistics(), and Isis::StretchTool::statsFromCube().
end()
bool Isis::BufferManager::end () const inline inherited
Returns true if the shape buffer has accessed the end of the cube.
Returns
bool
Referenced by Isis::Cube::copy(), main(), Isis::BufferManager::setpos(), Isis::ProcessRubberSheet::StartProcess(), Isis::ProcessByBrick::StartProcess(), Isis::ProcessExport::StartProcess(), and Isis::ProcessByBoxcar::StartProcess().
Index()
int Isis::Buffer::Index (const int i_samp, const int i_line, const int i_band) const inherited
Given a sample, line, and band position, this returns the appropriate index in the shape buffer.
Parameters
i_samp Sample position.
i_line Line position.
i_band Band position.
Returns
int Index at the specified sample, line and band.
Exceptions
Isis::iException::Programmer - Array Subscript not in range
References _FILEINFO_, Isis::Message::ArraySubscriptNotInRange(), Isis::Buffer::p_band, Isis::Buffer::p_line, Isis::Buffer::p_nbands, Isis::Buffer::p_nlines, Isis::Buffer::p_nsamps, Isis::Buffer::p_sample, and Isis::IException::Programmer.
Referenced by Isis::Buffer::CopyOverlapFrom(), and Isis::ViewportBuffer::fillBuffer().
Line()
int Isis::Buffer::Line (const int index = 0) const inherited
Returns the line position associated with a shape buffer index.
The shape buffer is one dimensional. Let us assume a nsamps=2, nlines=3, and nbands=2. Therefore the total size of the shape buffer is 12 and valid index values are 0-11. Line(0), Line(1), Line(6) and Line(7), will return a 1, Line(2), Line(3), Line(8) and Line(9) will return a 2, and Line(4), Line(5), Line(10), and Line(11) will return a 3.
Parameters
index Shape buffer index to map to a line position. Defaults to 0
Returns
int The absolute line number based on the buffer index
References Isis::Buffer::p_line, Isis::Buffer::p_nlines, and Isis::Buffer::p_nsamps.
Referenced by Isis::Buffer::CopyOverlapFrom(), Isis::IndependentCubeViewport::cubeDataChanged(), Isis::CubeViewport::cubeDataChanged(), Isis::ViewportBuffer::DataReady(), Isis::Chip::Extract(), Isis::ViewportBuffer::fillBuffer(), main(), Isis::Equalization::CalculateFunctor::operator()(), Isis::ImageImporter::operator()(), Isis::Nearest::operator()(), Isis::Average::operator()(), Isis::Buffer::Position(), Isis::CubeIoHandler::read(), Isis::QtExporter::writeGrayscale(), Isis::StreamExporter::writeGrayscale(), Isis::QtExporter::writeRgb(), Isis::StreamExporter::writeRgb(), Isis::QtExporter::writeRgba(), and Isis::StreamExporter::writeRgba().
LineDimension()
int Isis::Buffer::LineDimension () const inline inherited
Returns the number of lines in the shape buffer.
Returns
int
References Isis::Buffer::p_nlines.
Referenced by Isis::IndependentCubeViewport::cubeDataChanged(), Isis::CubeViewport::cubeDataChanged(), Isis::ViewportBuffer::fillBuffer(), Isis::Equalization::CalculateFunctor::operator()(), Isis::CubeIoHandler::read(), Isis::RegionalCachingAlgorithm::recommendChunksToFree(), and Isis::Hillshade::shadedValue().
MaxBands()
int Isis::BufferManager::MaxBands () const inline protected inherited
Returns the number of bands in the cube.
Returns
int
Referenced by Isis::BandManager::SetBand().
MaxLines()
int Isis::BufferManager::MaxLines () const inline protected inherited
Returns the number of lines in the cube.
Returns
int
Referenced by Isis::LineManager::SetLine().
MaxMaps()
BigInt Isis::BufferManager::MaxMaps () const inline protected inherited
Returns the maximum number of positions the shape buffer needs to cover the entire image (see setpos method for more info).
Returns
int
Referenced by Isis::Brick::Bricks(), and Isis::TileManager::Tiles().
MaxSamples()
int Isis::BufferManager::MaxSamples () const inline protected inherited
Returns the number of samples in the cube.
Returns
int
Referenced by Isis::SampleManager::SetSample().
next()
bool Isis::BufferManager::next () inline inherited
Moves the shape buffer to the next position.
Returns true if the next position is valid.
Returns
bool
References Isis::BufferManager::setpos().
Referenced by Isis::Cube::copy(), Isis::BufferManager::operator++(), Isis::ProcessExport::StartProcess(), and Isis::ProcessByBoxcar::StartProcess().
operator++()
bool Isis::BufferManager::operator++ (int) inline inherited
Moves the shape buffer to the next position.
Returns true if the next position is valid.
Returns
bool
References Isis::BufferManager::next().
operator+=()
BufferManager& Isis::BufferManager::operator+= (int i) inline inherited
Moves the shape buffer by a certain amount.
Returns a pointer to the BufferManager it was called on.
Parameters
i How far to shift the shape buffer
Returns
BufferManager
References Isis::BufferManager::setpos().
operator[]() [1/2]
double& Isis::Buffer::operator[] (const int index) inline inherited
Returns the value in the shape buffer at given index.
Parameters
index Index position in buffer. No out of bounds index is checked
Returns
double&
References Isis::Buffer::p_buf.
operator[]() [2/2]
const double& Isis::Buffer::operator[] (const int index) const inline inherited
Returns the value in the shape buffer at given index.
Parameters
index Index position in buffer. No out of bounds index is checked
Returns
double
References Isis::Buffer::p_buf.
PixelType()
Isis::PixelType Isis::Buffer::PixelType () const inline inherited
Returns the raw buffer pixel type.
Returns
Isis::PixelType
References Isis::Buffer::p_pixelType.
Referenced by Isis::Buffer::Copy().
Position()
void Isis::Buffer::Position (const int index, int & i_samp, int & i_line, int & i_band) const inherited
Returns the sample, line, and band position associated with a shape buffer index.
Performs the same function as the Sample, Line, and Band methods.
Parameters
index Shape buffer index to map to a band position.
i_samp Sample position in shape buffer at index.
i_line Line position in shape buffer at index
i_band Band position in shape buffer at index.
References Isis::Buffer::Band(), Isis::Buffer::Line(), and Isis::Buffer::Sample().
RawBuffer()
void* Isis::Buffer::RawBuffer () const inline inherited
Returns a void pointer to the raw buffer.
Cast this void pointer using information from the PixelType() method
Returns
void* Pointer to the raw buffer
References Isis::Buffer::p_rawbuf.
Sample()
int Isis::Buffer::Sample (const int index = 0) const inherited
Returns the sample position associated with a shape buffer index.
The shape buffer is one dimensional. Let us assume a nsamps=2, nlines=3, and nbands=2. Therefore the total size of the shape buffer is 12 and valid index values are 0-11. Sample(0), Sample(2), Sample(4), etc will return a 1 while Sample(1), Sample(3), Sample(5), etc will return a 2.
Parameters
index Shape buffer index to map to a sample position. Defaults to 0.
Returns
int The absolute sample number based on the buffer index.
References Isis::Buffer::p_nsamps, and Isis::Buffer::p_sample.
Referenced by Isis::Buffer::CopyOverlapFrom(), Isis::IndependentCubeViewport::cubeDataChanged(), Isis::CubeViewport::cubeDataChanged(), Isis::ViewportBuffer::DataReady(), Isis::Chip::Extract(), Isis::ViewportBuffer::fillBuffer(), Isis::SpectralDefinition2D::operator()(), Isis::Buffer::Position(), and Isis::CubeIoHandler::read().
SampleDimension()
int Isis::Buffer::SampleDimension () const inline inherited
Returns the number of samples in the shape buffer.
Returns
int
References Isis::Buffer::p_nsamps.
Referenced by Isis::IndependentCubeViewport::cubeDataChanged(), Isis::CubeViewport::cubeDataChanged(), Isis::ViewportBuffer::fillBuffer(), Isis::ImageImporter::operator()(), Isis::CubeIoHandler::read(), Isis::RegionalCachingAlgorithm::recommendChunksToFree(), Isis::Hillshade::shadedValue(), Isis::QtExporter::writeGrayscale(), Isis::StreamExporter::writeGrayscale(), Isis::QtExporter::writeRgb(), Isis::StreamExporter::writeRgb(), Isis::QtExporter::writeRgba(), and Isis::StreamExporter::writeRgba().
SetBaseBand()
void Isis::Buffer::SetBaseBand (const int start_band) inline protected inherited
This method is used to set the base band position of the shape buffer.
Parameters
start_band Starting band to set
References Isis::Buffer::p_band.
Referenced by Isis::Brick::SetBaseBand(), and Isis::Buffer::SetBasePosition().
SetBaseLine()
void Isis::Buffer::SetBaseLine (const int start_line) inline protected inherited
This method is used to set the base line position of the shape buffer.
Parameters
start_line Starting line to set
References Isis::Buffer::p_line.
Referenced by Isis::Brick::SetBaseLine(), and Isis::Buffer::SetBasePosition().
SetBasePosition()
void Isis::Buffer::SetBasePosition (const int start_sample, const int start_line, const int start_band) protected inherited
This method is used to set the base position of the shape buffer.
In general it is used by BufferManager objects to progress sequentially through a cube by line, tile, boxcar, etc.
Parameters
start_sample Starting sample to set.
start_line Starting line to set.
start_band Starting band to set.
References Isis::Buffer::SetBaseBand(), Isis::Buffer::SetBaseLine(), and Isis::Buffer::SetBaseSample().
Referenced by Isis::Brick::SetBasePosition(), Isis::BufferManager::setpos(), and Isis::Portal::SetPosition().
SetBaseSample()
void Isis::Buffer::SetBaseSample (const int start_samp) inline protected inherited
This method is used to set the base sample position of the shape buffer.
Parameters
start_samp Starting sample to set
References Isis::Buffer::p_sample.
Referenced by Isis::Buffer::SetBasePosition(), and Isis::Brick::SetBaseSample().
SetIncrements()
void Isis::BufferManager::SetIncrements (const int sinc, const int linc, const int binc) protected inherited
Sets how the shape is incremented through the cube.
By default (if this method is not invoked) shapes are moved sequentially through the cube with no overlap. For example, assume a 3 sample by 3 line tile buffer. It would first move across the image from left-to-right starting at sample 1, line 1, and band 1. Upon an increment it would be positioned at sample 4, line 1, and band 1. Each successive increment would cause the sample position to increase by 3 until it exceeds the number of samples in the cube. At that point the shape buffer would be positioned at sample 1, line 4, and band 1 (effectively moving to the next row of tiles). The shape would then continue moving across the cube until it reaches the edge again. Then the next row of tiles would be accessed until the shape reached the bottom of the cube. This default management can be overridden using this method. For example, by setting the increments to (6,3,1) we effectively skip every other tile. By setting them to (6,6,1) we skip every other tile and every other row of tiles. By setting them to (1,1,1) we essentially have NSxNLxNB positions in the cube and the 3x3 tile is managed such that the top left corner of the tile is moved over by 1 sample until it reaches the end of the line then down 1 line and so on until the end of the cube is reached.
Parameters
sinc Sample increment
linc Line increment
binc Band increment
Referenced by BoxcarManager(), and Isis::BufferManager::BufferManager().
SetOffsets()
void Isis::BufferManager::SetOffsets (const int soff, const int loff, const int boff) protected inherited
Sets the offset of the buffer.
By default (if this method is not invoked) the offsets are (0,0,0). Offsets are applied when computing the top-left corner of the shape buffer. When used in conjunction with the SetIncrements method, this allows for centering shape buffers around a pixel when passing in negative offsets. For example,with a 3x3x1 shape and offsets of (-1,-1,0) and increments of (1,1,1) would cause the manager to walk a 3x3 buffer through the entire image. Setting the manager position the beginning causes the 3x3 window to be positioned such that sample 1, line 1 of the cube would be at the center of the window and increment would cause sample 2, line 1 to be at the center of the window. Successive increments will move the window in the sample direction until the end of line is reached at which time the buffer would be centered on sample 1, line 2.
Parameters
soff Sample offset
loff Line offset
boff Band offset
Referenced by BoxcarManager().
setpos()
bool Isis::BufferManager::setpos (BigInt map) inherited
Sets the position of the shape in the cube.
This shape fits into the cube a specific number of times.
When p_reverse is left false: (default) For example, a line shape on a 100 sample, 200 line, and 2 band cube would have 200*2 or 400 different positions as there are 400 total lines in the cube. Performing setpos(0) would position the shape at sample 1, line 1, and band 1. While setpos(200) would position the shape at sample 1, line 1, and band 2. Finally, setpos(399) would position the shape at sample 1, line 400, and band 2. Setpos returns true if it was sucessfully in setting the position, and false if the shape is at the end of the cube (beyond index 399 in the case of our example).
When p_reverse is set to true: Following the above cube with 100 samples, 200 lines, and 2 bands, performing the setpos(0) would still position the shape at sample 1, line 1, and band 1. However, setpos(1) would position the shape at sample 1, line 1, band 2, while setpos(200) would position the spame at sample 1, line 100, band 1. Setpos returns true of it was sucessfully in setting the position, and false if the shape is at the end of the cube(beyond final index).
Parameters
map Shape buffer position value
Returns
bool True or False depending on whether the shape is at the end of the cube or not.
Exceptions
Isis::iException::Programmer - Invalid value for map argument
References _FILEINFO_, Isis::BufferManager::end(), Isis::IException::Programmer, and Isis::Buffer::SetBasePosition().
Referenced by Isis::BufferManager::begin(), Isis::BufferManager::next(), Isis::BufferManager::operator+=(), Isis::BandManager::SetBand(), Isis::Brick::SetBrick(), Isis::LineManager::SetLine(), Isis::SampleManager::SetSample(), and Isis::TileManager::SetTile().
size()
int Isis::Buffer::size () const inline inherited
Returns the total number of pixels in the shape buffer.
Returns
int
References Isis::Buffer::p_npixels.
Referenced by Isis::Equalization::CalculateFunctor::addStats(), Isis::HiEqualization::HiCalculateFunctor::addStats(), Isis::CubeDataThreadTester::BrickChanged(), Isis::Process::CalculateStatistics(), Isis::Buffer::Copy(), Isis::Buffer::CopyOverlapFrom(), Isis::IndependentCubeViewport::cubeDataChanged(), Isis::ViewportBuffer::DataReady(), Isis::Chip::Extract(), Isis::ViewportBuffer::fillBuffer(), Isis::Cube::histogram(), Isis::ImageHistogram::ImageHistogram(), main(), Isis::Equalization::ApplyFunctor::operator()(), Isis::Average::operator()(), Isis::Calculator::Push(), Isis::CubeIoHandler::read(), Isis::CubeDataThreadTester::ReadBrick(), Isis::CubeDataThreadTester::ReadWriteBrick(), Isis::ScatterPlotData::ScatterPlotData(), Isis::Hillshade::shadedValue(), Isis::ProcessMosaic::StartProcess(), Isis::ProcessExport::StartProcess(), Isis::ProcessByBoxcar::StartProcess(), and Isis::Cube::statistics().
swap()
void Isis::BufferManager::swap (BufferManager & other) inherited
Swaps the values of this BufferManager with that of another.
Parameters
&other Reference to a BufferManager to swap with
Referenced by Isis::BufferManager::operator=().
Member Data Documentation
p_band
int Isis::Buffer::p_band protected inherited
Starting band to read/write.
Referenced by Isis::Buffer::Band(), Isis::Buffer::Buffer(), Isis::Buffer::CopyOverlapFrom(), Isis::Buffer::Index(), and Isis::Buffer::SetBaseBand().
p_buf
double* Isis::Buffer::p_buf protected inherited
Shape buffer allocated to the size of npixels for handling reads/writes.
Referenced by Isis::Buffer::Allocate(), Isis::Buffer::at(), Isis::Buffer::Copy(), Isis::Buffer::DoubleBuffer(), Isis::Buffer::operator=(), Isis::Buffer::operator[](), Isis::Brick::Resize(), and Isis::Buffer::~Buffer().
p_line
int Isis::Buffer::p_line protected inherited
Starting line to read/write.
Referenced by Isis::Buffer::Buffer(), Isis::Buffer::CopyOverlapFrom(), Isis::Buffer::Index(), Isis::Buffer::Line(), and Isis::Buffer::SetBaseLine().
p_nbands
int Isis::Buffer::p_nbands protected inherited
Number of bands to read/write.
Referenced by Isis::Buffer::BandDimension(), Isis::Buffer::Buffer(), Isis::Buffer::CopyOverlapFrom(), Isis::Buffer::Index(), and Isis::Brick::Resize().
p_nlines
int Isis::Buffer::p_nlines protected inherited
Number of lines to read/write.
Referenced by Isis::Buffer::Band(), Isis::Buffer::Buffer(), Isis::Buffer::CopyOverlapFrom(), Isis::Buffer::Index(), Isis::Buffer::Line(), Isis::Buffer::LineDimension(), and Isis::Brick::Resize().
p_npixels
int Isis::Buffer::p_npixels protected inherited
Number of pixels (nsamps * nlines * nbands)
Referenced by Isis::Buffer::Allocate(), Isis::Buffer::at(), Isis::Buffer::Buffer(), Isis::Buffer::Copy(), Isis::Buffer::CopyOverlapFrom(), Isis::Buffer::operator=(), Isis::Brick::Resize(), and Isis::Buffer::size().
p_nsamps
int Isis::Buffer::p_nsamps protected inherited
Number of samples to read/write.
Referenced by Isis::Buffer::Band(), Isis::Buffer::Buffer(), Isis::Buffer::CopyOverlapFrom(), Isis::Buffer::Index(), Isis::Buffer::Line(), Isis::Brick::Resize(), Isis::Buffer::Sample(), and Isis::Buffer::SampleDimension().
p_pixelType
const Isis::PixelType Isis::Buffer::p_pixelType protected inherited
The pixel type of the raw buffer.
Referenced by Isis::Buffer::Allocate(), Isis::Buffer::Copy(), and Isis::Buffer::PixelType().
p_rawbuf
void* Isis::Buffer::p_rawbuf protected inherited
The raw dm read from the disk.
Referenced by Isis::Buffer::Allocate(), Isis::Buffer::Copy(), Isis::Buffer::RawBuffer(), Isis::Brick::Resize(), and Isis::Buffer::~Buffer().
p_sample
int Isis::Buffer::p_sample protected inherited
Starting sample to read/write.
Referenced by Isis::Buffer::Buffer(), Isis::Buffer::CopyOverlapFrom(), Isis::Buffer::Index(), Isis::Buffer::Sample(), and Isis::Buffer::SetBaseSample().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/BoxcarManager/BoxcarManager.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/BoxcarManager/BoxcarManager.cpp