Isis Developer Reference: Isis::QnetNavTool Class Reference
Isis::QnetNavTool Class Reference
Qnet Navigation Tool.
#include <QnetNavTool.h>
Public Types
enum FilterIndex { Points , Cubes }
enum PointFilterIndex {
JigsawErrors , RegistrationErrors , Id , NumberImages ,
Type , LatLonRange , Distance , MeasureType ,
GoodnessOfFit , CubeName
}
enum CubeFilterIndex { Name , NumberPoints , PointDistance }
Public Slots
void resetList ()
Resets the list box with whatever is in the global lists.
void refreshList ()
Slot to refresh the listBox.
void updateEditPoint (QString pointId)
Update the list showing the new point highlighted.
void disconnectAprioriDialog ()
Apriori dialog has been closed and needs to be disconnected and deleted so a new dialog can be brought up next time.
void showNavTool ()
This method sets the Navigation Dialog window to shown=true.
void activate (bool)
Activates the tool.
virtual void updateTool ()
Updates the tool.
void setCubeViewport (MdiCubeViewport *cvp)
Sets the current viewport to the given cvp.
Signals
void activityUpdate (QString)
void loadPointImages (ControlPoint *)
void loadImage (const QString &)
void modifyPoint (ControlPoint *)
void ignoredPoints ()
void deletedPoints ()
void pointChanged (QString pointId)
void netChanged ()
void serialListModified ()
void clearWarningSignal ()
void toolActivated ()
void viewportChanged ()
Public Member Functions
QnetNavTool (QnetTool *qnetTool, QWidget *parent)
Constructs the Navigation Tool window.
~QnetNavTool ()
QList< int > & filteredImages ()
const QList< int > & filteredImages () const
QList< int > & filteredPoints ()
const QList< int > & filteredPoints () const
ControlNet * controlNet ()
const ControlNet * controlNet () const
SerialNumberList * serialNumberList ()
const SerialNumberList * serialNumberList () const
void addTo (ViewportMainWindow *mw)
Adds the tool to the application.
void addTo (ToolPad *toolpad)
Adds the tool to the toolpad.
virtual void addTo (QMenu *menu)
virtual void addTo (Workspace *ws)
Adds the given workspace to the cubeviewport list.
virtual QString menuName () const
Anytime a tool is created, you must give it a name for the menu.
virtual void addToPermanent (QToolBar *toolbar)
void addToActive (QToolBar *toolbar)
QString toolIconDir () const
returns the path to the icon directory.
virtual void paintViewport (MdiCubeViewport *vp, QPainter *painter)
RubberBandTool * rubberBandTool ()
void setList (ToolList *currentList)
Protected Types
typedef QVector< MdiCubeViewport * > CubeViewportList
A list of cubeviewports.
Protected Slots
virtual void rubberBandComplete ()
virtual void screenPixelsChanged ()
This is called when actions change which pixels from the cube are displayed.
virtual void mouseEnter ()
virtual void mouseMove (QPoint p)
virtual void mouseMove (QPoint p, Qt::MouseButton)
virtual void mouseLeave ()
Protected Member Functions
virtual void mouseDoubleClick (QPoint p)
virtual void mouseButtonPress (QPoint p, Qt::MouseButton s)
virtual void mouseButtonRelease (QPoint p, Qt::MouseButton s)
Resets the Warning to Nowarning when a different activity occurs on the application.
virtual void updateMeasure ()
virtual void scaleChanged ()
virtual void stretchRequested (MdiCubeViewport *, int)
void registerTool (MdiCubeViewport *viewport)
Registers the tool to the viewport.
MdiCubeViewport * cubeViewport () const
Return the current cubeviewport.
CubeViewportList * cubeViewportList () const
Return the list of cubeviewports.
virtual QAction * toolPadAction (ToolPad *toolpad)
Anytime a tool is created, you must setup a tool pad action with it.
virtual QWidget * createToolBarWidget (QStackedWidget *parent)
Anytime a tool is created, you must add it to the tool bar.
virtual void addConnections (MdiCubeViewport *cvp)
Anytime a tool is created, you must add the connections for it.
virtual void removeConnections (MdiCubeViewport *cvp)
Anytime a tool is created, you must be able to remove it's connections.
virtual void enableRubberBandTool ()
Anytime a tool is created, you may use the rubber band tool.
Workspace * workspace ()
Detailed Description
Qnet Navigation Tool.
Author
2006-11-07 Elizabeth Ribelin
Member Typedef Documentation
CubeViewportList
typedef QVector< MdiCubeViewport * > Isis::Tool::CubeViewportList protected inherited
A list of cubeviewports.
Member Enumeration Documentation
CubeFilterIndex
enum Isis::QnetNavTool::CubeFilterIndex
Enumerator
Name
NumberPoints
PointDistance
FilterIndex
enum Isis::QnetNavTool::FilterIndex
Enumerator
Points
Cubes
PointFilterIndex
enum Isis::QnetNavTool::PointFilterIndex
Enumerator
JigsawErrors
RegistrationErrors
Id
NumberImages
Type
LatLonRange
Distance
MeasureType
GoodnessOfFit
CubeName
Constructor & Destructor Documentation
QnetNavTool()
Isis::QnetNavTool::QnetNavTool (QnetTool * qnetTool, QWidget * parent)
Constructs the Navigation Tool window.
Parameters
parent The parent widget for the navigation tool
References activityUpdate(), deletedPoints(), and refreshList().
~QnetNavTool()
Isis::QnetNavTool::~QnetNavTool ()
References Isis::FileName::expanded().
Member Function Documentation
activate
void Isis::Tool::activate (bool on) slot inherited
Activates the tool.
Parameters
on
References Isis::Tool::clearWarningSignal(), and Isis::Tool::toolActivated().
Referenced by Isis::Tool::addTo(), Isis::AdvancedTrackTool::AdvancedTrackTool(), Isis::RubberBandTool::disable(), Isis::RubberBandTool::enable(), Isis::AdvancedTrackTool::eventFilter(), Isis::FileTool::FileTool(), Isis::RubberBandTool::RubberBandTool(), Isis::TrackTool::TrackTool(), Isis::WindowTool::WindowTool(), and Isis::Workspace::Workspace().
activityUpdate
void Isis::QnetNavTool::activityUpdate (QString) signal
Referenced by QnetNavTool(), and updateEditPoint().
addConnections()
virtual void Isis::Tool::addConnections (MdiCubeViewport * cvp) inline protected virtual inherited
Anytime a tool is created, you must add the connections for it.
Parameters
cvp
Reimplemented in Isis::WindowTool, and Isis::TrackTool.
addTo() [1/4]
virtual void Isis::Tool::addTo (QMenu * menu) inline virtual inherited
Parameters
menu
Reimplemented in Isis::ZoomTool, Isis::WindowTool, Isis::SunShadowTool, Isis::StretchTool, Isis::SpectralPlotTool, Isis::SpecialPixelTool, Isis::QnetFileTool, Isis::MeasureTool, Isis::HelpTool, Isis::FindTool, Isis::FileTool, Isis::FeatureNomenclatureTool, Isis::BlinkTool, Isis::AdvancedTrackTool, and Isis::PanTool.
addTo() [2/4]
void Isis::Tool::addTo (ToolPad * toolpad) inherited
Adds the tool to the toolpad.
Parameters
toolpad
References Isis::Tool::activate(), Isis::ToolPad::addAction(), and Isis::Tool::toolPadAction().
addTo() [3/4]
void Isis::Tool::addTo (ViewportMainWindow * pViewPortMnWin) inherited
Adds the tool to the application.
Parameters
pViewPortMnWin
References Isis::ViewportMainWindow::activeToolBar(), Isis::Tool::addToActive(), Isis::Tool::addToPermanent(), Isis::ViewportMainWindow::getMenu(), Isis::Tool::menuName(), Isis::ViewportMainWindow::permanentToolBar(), Isis::ViewportMainWindow::toolPad(), and Isis::ViewportMainWindow::workspace().
Referenced by Isis::EditTool::addTo(), Isis::FileTool::addTo(), Isis::SpecialPixelTool::addTo(), Isis::WindowTool::addTo(), Isis::ViewportMainWindow::ViewportMainWindow(), and Isis::Workspace::Workspace().
addTo() [4/4]
void Isis::Tool::addTo (Workspace * ws) virtual inherited
Adds the given workspace to the cubeviewport list.
Parameters
ws
Reimplemented in Isis::WindowTool, Isis::SpecialPixelTool, Isis::FileTool, and Isis::EditTool.
References Isis::Tool::registerTool(), and Isis::Tool::setCubeViewport().
addToActive()
void Isis::Tool::addToActive (QToolBar * toolbar) inherited
Parameters
toolbar
References Isis::Tool::createToolBarWidget(), and Isis::ToolList::toolBarStack().
Referenced by Isis::Tool::addTo(), and Isis::Workspace::Workspace().
addToPermanent()
virtual void Isis::Tool::addToPermanent (QToolBar * toolbar) inline virtual inherited
Parameters
toolbar
Reimplemented in Isis::WindowTool, Isis::SpecialPixelTool, Isis::HelpTool, Isis::FileTool, Isis::BlinkTool, and Isis::AdvancedTrackTool.
Referenced by Isis::Tool::addTo(), and Isis::Workspace::Workspace().
clearWarningSignal
void Isis::Tool::clearWarningSignal () signal inherited
Referenced by Isis::Tool::activate(), Isis::Tool::mouseButtonPress(), Isis::Tool::mouseButtonRelease(), and Isis::Tool::mouseDoubleClick().
controlNet() [1/2]
ControlNet * Isis::QnetNavTool::controlNet ()
References Isis::QnetTool::controlNet().
Referenced by Isis::QnetFilter::controlNet(), and resetList().
controlNet() [2/2]
const ControlNet * Isis::QnetNavTool::controlNet () const
References Isis::QnetTool::controlNet().
createToolBarWidget()
virtual QWidget* Isis::Tool::createToolBarWidget (QStackedWidget * parent) inline protected virtual inherited
Anytime a tool is created, you must add it to the tool bar.
Parameters
parent
Returns
QWidget*
Reimplemented in Isis::ZoomTool, Isis::SunShadowTool, Isis::StretchTool, Isis::StereoTool, Isis::StatisticsTool, Isis::SpectralPlotTool, Isis::SpatialPlotTool, Isis::ScatterPlotTool, Isis::PanTool, Isis::MeasureTool, Isis::HistogramTool, Isis::FindTool, Isis::FeatureNomenclatureTool, Isis::AbstractPlotTool, Isis::LatLonGridTool, Isis::EditTool, and Isis::BandTool.
Referenced by Isis::Tool::addToActive().
cubeViewport()
MdiCubeViewport* Isis::Tool::cubeViewport () const inline protected inherited
Return the current cubeviewport.
Returns
CubeViewport*
Referenced by Isis::TrackTool::addConnections(), Isis::WindowTool::addConnections(), Isis::StretchTool::deleteFromCube(), Isis::FileTool::discard(), Isis::FileTool::exportToList(), Isis::FileTool::exportView(), Isis::StretchTool::loadStretchFromCube(), Isis::SunShadowTool::mouseButtonPress(), Isis::EditTool::mouseButtonRelease(), Isis::ControlNetTool::mouseButtonRelease(), Isis::FeatureNomenclatureTool::mouseButtonRelease(), Isis::FindTool::mouseButtonRelease(), Isis::MatchTool::mouseButtonRelease(), Isis::PanTool::mouseButtonRelease(), Isis::QnetTool::mouseButtonRelease(), Isis::RubberBandTool::mouseButtonRelease(), Isis::StretchTool::mouseButtonRelease(), Isis::AdvancedTrackTool::mouseLeave(), Isis::SunShadowTool::mouseMove(), Isis::TrackTool::mouseMove(), Isis::RubberBandTool::mouseMove(), Isis::ScatterPlotTool::mouseMove(), Isis::LatLonGridTool::paintViewport(), Isis::FindTool::paintViewport(), Isis::RubberBandTool::paintViewport(), Isis::SunShadowTool::paintViewport(), Isis::FileTool::print(), Isis::HistogramTool::refreshPlot(), Isis::SpatialPlotTool::refreshPlot(), Isis::SpectralPlotTool::refreshPlot(), Isis::TrackTool::removeConnections(), Isis::WindowTool::removeConnections(), Isis::EditTool::rubberBandComplete(), Isis::HistogramTool::rubberBandComplete(), Isis::MeasureTool::rubberBandComplete(), Isis::StereoTool::rubberBandComplete(), Isis::StretchTool::rubberBandComplete(), Isis::ZoomTool::rubberBandComplete(), Isis::FileTool::save(), Isis::FileTool::saveAs(), Isis::FileTool::saveAsCubeByOption(), Isis::FileTool::saveInfo(), Isis::StretchTool::saveStretchToCube(), Isis::ScatterPlotTool::showNewScatterPlotConfig(), Isis::StretchTool::stretchGlobal(), Isis::StretchTool::stretchGlobalAllBands(), Isis::StretchTool::stretchRegional(), Isis::StretchTool::updateAdvStretchDialogforAll(), Isis::StretchTool::updateHistograms(), Isis::MeasureTool::updateMeasure(), Isis::AbstractPlotTool::updateTool(), Isis::BandTool::updateTool(), Isis::BlinkTool::updateTool(), Isis::EditTool::updateTool(), Isis::FileTool::updateTool(), Isis::FindTool::updateTool(), Isis::LatLonGridTool::updateTool(), Isis::SpecialPixelTool::updateTool(), Isis::StretchTool::updateTool(), Isis::SunShadowTool::updateTool(), Isis::WindowTool::updateTool(), Isis::ZoomTool::updateTool(), and Isis::AbstractPlotTool::viewportsToPlot().
cubeViewportList()
Tool::CubeViewportList * Isis::Tool::cubeViewportList () const protected inherited
Return the list of cubeviewports.
Returns
CubeViewportList*
References Isis::Workspace::cubeViewportList().
Referenced by Isis::FileTool::closeAll(), Isis::MatchTool::createPoint(), Isis::BlinkTool::eventFilter(), Isis::PanTool::mouseButtonRelease(), Isis::RubberBandTool::mouseButtonRelease(), Isis::RubberBandTool::mouseMove(), Isis::ScatterPlotTool::repaintViewports(), Isis::AbstractPlotTool::repaintViewports(), Isis::ZoomTool::rubberBandComplete(), Isis::ControlNetTool::setControlNet(), Isis::FeatureNomenclatureTool::setFontColor(), Isis::FeatureNomenclatureTool::setFontSize(), Isis::FeatureNomenclatureTool::setShowApprovedOnly(), Isis::FeatureNomenclatureTool::setVectorType(), Isis::StretchTool::stretchGlobalAllViewports(), Isis::MeasureTool::updateMeasure(), Isis::BlinkTool::updateTool(), Isis::FindTool::updateTool(), Isis::WindowTool::updateTool(), and Isis::AbstractPlotTool::viewportsToPlot().
deletedPoints
void Isis::QnetNavTool::deletedPoints () signal
Referenced by QnetNavTool().
disconnectAprioriDialog
void Isis::QnetNavTool::disconnectAprioriDialog () slot
Apriori dialog has been closed and needs to be disconnected and deleted so a new dialog can be brought up next time.
Author
2016-11-14 Makayla Shepherd
enableRubberBandTool()
void Isis::Tool::enableRubberBandTool () protected virtual inherited
Anytime a tool is created, you may use the rubber band tool.
Enable the use of the rubberband tool.
Reimplemented in Isis::ZoomTool, Isis::StereoTool, Isis::SpectralPlotTool, Isis::SpatialPlotTool, Isis::RubberBandTool, Isis::MeasureTool, and Isis::HistogramTool.
References Isis::RubberBandTool::disable(), and Isis::Tool::rubberBandTool().
filteredImages() [1/2]
QList< int > & Isis::QnetNavTool::filteredImages ()
Referenced by Isis::QnetFilter::filteredImages().
filteredImages() [2/2]
const QList< int > & Isis::QnetNavTool::filteredImages () const
filteredPoints() [1/2]
QList< int > & Isis::QnetNavTool::filteredPoints ()
Referenced by Isis::QnetFilter::filteredPoints().
filteredPoints() [2/2]
const QList< int > & Isis::QnetNavTool::filteredPoints () const
ignoredPoints
void Isis::QnetNavTool::ignoredPoints () signal
loadImage
void Isis::QnetNavTool::loadImage (const QString &) signal
loadPointImages
void Isis::QnetNavTool::loadPointImages (ControlPoint *) signal
menuName()
virtual QString Isis::Tool::menuName () const inline virtual inherited
Anytime a tool is created, you must give it a name for the menu.
Returns
QString
Reimplemented in Isis::ZoomTool, Isis::WindowTool, Isis::StretchTool, Isis::SpecialPixelTool, Isis::PanTool, Isis::MeasureTool, Isis::HelpTool, Isis::FindTool, Isis::FileTool, Isis::FeatureNomenclatureTool, Isis::BlinkTool, Isis::BandTool, and Isis::AdvancedTrackTool.
Referenced by Isis::Tool::addTo(), and Isis::Workspace::Workspace().
modifyPoint
void Isis::QnetNavTool::modifyPoint (ControlPoint *) signal
mouseButtonPress()
void Isis::Tool::mouseButtonPress (QPoint p, Qt::MouseButton s) protected virtual inherited
Parameters
p
s
References Isis::Tool::clearWarningSignal().
mouseButtonRelease()
void Isis::Tool::mouseButtonRelease (QPoint p, Qt::MouseButton s) protected virtual inherited
Resets the Warning to Nowarning when a different activity occurs on the application.
This is called by all the mouseButtonRelease events in all the tools.
Parameters
p
s
Reimplemented in Isis::FeatureNomenclatureTool.
References Isis::Tool::clearWarningSignal().
Referenced by Isis::StretchTool::mouseButtonRelease().
mouseDoubleClick()
void Isis::Tool::mouseDoubleClick (QPoint p) protected virtual inherited
Parameters
p
References Isis::Tool::clearWarningSignal().
mouseEnter
virtual void Isis::Tool::mouseEnter () inline protected virtual slot inherited
mouseLeave
virtual void Isis::Tool::mouseLeave () inline protected virtual slot inherited
mouseMove [1/2]
void Isis::Tool::mouseMove (QPoint p) protected virtual slot inherited
Parameters
p
mouseMove [2/2]
virtual void Isis::Tool::mouseMove (QPoint p, Qt::MouseButton) inline protected virtual slot inherited
netChanged
void Isis::QnetNavTool::netChanged () signal
paintViewport()
virtual void Isis::Tool::paintViewport (MdiCubeViewport * vp, QPainter * painter) inline virtual inherited
Parameters
vp
painter
Reimplemented in Isis::SunShadowTool, Isis::ScatterPlotTool, Isis::RubberBandTool, Isis::FindTool, Isis::FeatureNomenclatureTool, Isis::AbstractPlotTool, Isis::MatchTool, Isis::LatLonGridTool, Isis::StereoTool, Isis::QnetTool, and Isis::ControlNetTool.
pointChanged
void Isis::QnetNavTool::pointChanged (QString pointId) signal
refreshList
void Isis::QnetNavTool::refreshList () slot
Slot to refresh the listBox.
References resetList().
Referenced by QnetNavTool().
registerTool()
void Isis::Tool::registerTool (MdiCubeViewport * viewport) protected inherited
Registers the tool to the viewport.
Parameters
viewport
References Isis::MdiCubeViewport::registerTool(), and Isis::Tool::stretchRequested().
Referenced by Isis::Tool::addTo().
removeConnections()
virtual void Isis::Tool::removeConnections (MdiCubeViewport * cvp) inline protected virtual inherited
Anytime a tool is created, you must be able to remove it's connections.
Parameters
cvp
Reimplemented in Isis::WindowTool, Isis::TrackTool, and Isis::MeasureTool.
resetList
void Isis::QnetNavTool::resetList () slot
Resets the list box with whatever is in the global lists.
References controlNet(), Cubes, Isis::ControlNet::GetNumPoints(), Isis::FileName::name(), Points, serialNumberList(), Isis::QnetTool::serialNumberList(), Isis::SerialNumberList::size(), and updateEditPoint().
Referenced by refreshList().
rubberBandComplete
virtual void Isis::Tool::rubberBandComplete () inline protected virtual slot inherited
rubberBandTool()
RubberBandTool * Isis::Tool::rubberBandTool () inherited
References Isis::ToolList::rubberBandTool().
Referenced by Isis::MeasureTool::createToolBarWidget(), Isis::EditTool::enableRubberBandTool(), Isis::HistogramTool::enableRubberBandTool(), Isis::MeasureTool::enableRubberBandTool(), Isis::SpatialPlotTool::enableRubberBandTool(), Isis::SpectralPlotTool::enableRubberBandTool(), Isis::StereoTool::enableRubberBandTool(), Isis::StretchTool::enableRubberBandTool(), Isis::Tool::enableRubberBandTool(), Isis::ZoomTool::enableRubberBandTool(), Isis::HistogramTool::refreshPlot(), Isis::SpatialPlotTool::refreshPlot(), Isis::SpectralPlotTool::refreshPlot(), Isis::RubberBandComboBox::RubberBandComboBox(), Isis::EditTool::rubberBandComplete(), Isis::HistogramTool::rubberBandComplete(), Isis::MeasureTool::rubberBandComplete(), Isis::SpatialPlotTool::rubberBandComplete(), Isis::SpectralPlotTool::rubberBandComplete(), Isis::StereoTool::rubberBandComplete(), Isis::StretchTool::rubberBandComplete(), Isis::ZoomTool::rubberBandComplete(), and Isis::RubberBandComboBox::selectionChanged().
scaleChanged()
virtual void Isis::Tool::scaleChanged () inline protected virtual inherited
Reimplemented in Isis::RubberBandTool.
screenPixelsChanged
virtual void Isis::Tool::screenPixelsChanged () inline protected virtual slot inherited
This is called when actions change which pixels from the cube are displayed.
serialListModified
void Isis::QnetNavTool::serialListModified () signal
serialNumberList() [1/2]
SerialNumberList * Isis::QnetNavTool::serialNumberList ()
References Isis::QnetTool::serialNumberList().
Referenced by resetList(), and Isis::QnetFilter::serialNumberList().
serialNumberList() [2/2]
const SerialNumberList * Isis::QnetNavTool::serialNumberList () const
References Isis::QnetTool::serialNumberList().
setCubeViewport
void Isis::Tool::setCubeViewport (MdiCubeViewport * cvp) slot inherited
Sets the current viewport to the given cvp.
Parameters
cvp
References Isis::Tool::updateTool(), and Isis::Tool::viewportChanged().
Referenced by Isis::Tool::addTo(), and Isis::FileTool::closeAll().
setList()
void Isis::Tool::setList (ToolList * currentList) inherited
Referenced by Isis::ToolList::append().
showNavTool
void Isis::QnetNavTool::showNavTool () slot
This method sets the Navigation Dialog window to shown=true.
Author
Jeannie Walldren
stretchRequested()
virtual void Isis::Tool::stretchRequested (MdiCubeViewport * , int) inline protected virtual inherited
Reimplemented in Isis::StretchTool.
Referenced by Isis::Tool::registerTool().
toolActivated
void Isis::Tool::toolActivated () signal inherited
Referenced by Isis::Tool::activate(), Isis::FeatureNomenclatureTool::FeatureNomenclatureTool(), Isis::MatchTool::MatchTool(), and Isis::StereoTool::StereoTool().
toolIconDir()
QString Isis::Tool::toolIconDir () const inline inherited
returns the path to the icon directory.
Returns
QString
Referenced by Isis::AdvancedTrackTool::AdvancedTrackTool(), Isis::BlinkTool::BlinkTool(), Isis::BandTool::createToolBarWidget(), Isis::EditTool::createToolBarWidget(), Isis::FindTool::createToolBarWidget(), Isis::MatchTool::createToolBarWidget(), Isis::PanTool::createToolBarWidget(), Isis::StereoTool::createToolBarWidget(), Isis::StretchTool::createToolBarWidget(), Isis::ZoomTool::createToolBarWidget(), Isis::FileTool::FileTool(), Isis::FindTool::FindTool(), Isis::HelpTool::HelpTool(), Isis::HistogramTool::HistogramTool(), Isis::PanTool::PanTool(), Isis::SpecialPixelTool::SpecialPixelTool(), Isis::RubberBandComboBox::toolIconDir(), Isis::BandTool::toolPadAction(), Isis::ControlNetTool::toolPadAction(), Isis::EditTool::toolPadAction(), Isis::FeatureNomenclatureTool::toolPadAction(), Isis::HistogramTool::toolPadAction(), Isis::LatLonGridTool::toolPadAction(), Isis::MatchTool::toolPadAction(), Isis::MeasureTool::toolPadAction(), Isis::PanTool::toolPadAction(), Isis::QnetTool::toolPadAction(), Isis::ScatterPlotTool::toolPadAction(), Isis::SpatialPlotTool::toolPadAction(), Isis::SpectralPlotTool::toolPadAction(), Isis::StereoTool::toolPadAction(), Isis::StretchTool::toolPadAction(), Isis::SunShadowTool::toolPadAction(), Isis::FindTool::toolPadAction(), Isis::StatisticsTool::toolPadAction(), Isis::ZoomTool::toolPadAction(), Isis::WindowTool::WindowTool(), and Isis::ZoomTool::ZoomTool().
toolPadAction()
virtual QAction* Isis::Tool::toolPadAction (ToolPad * toolpad) inline protected virtual inherited
Anytime a tool is created, you must setup a tool pad action with it.
Parameters
toolpad
Returns
QAction*
Reimplemented in Isis::ZoomTool, Isis::StatisticsTool, Isis::FindTool, Isis::SunShadowTool, Isis::StretchTool, Isis::StereoTool, Isis::SpectralPlotTool, Isis::SpatialPlotTool, Isis::ScatterPlotTool, Isis::QnetTool, Isis::PanTool, Isis::MeasureTool, Isis::MatchTool, Isis::LatLonGridTool, Isis::HistogramTool, Isis::FeatureNomenclatureTool, Isis::EditTool, Isis::ControlNetTool, and Isis::BandTool.
Referenced by Isis::Tool::addTo().
updateEditPoint
void Isis::QnetNavTool::updateEditPoint (QString pointId) slot
Update the list showing the new point highlighted.
Parameters
pointId Value of the PointId keyword for the new point.
References activityUpdate().
Referenced by resetList().
updateMeasure()
virtual void Isis::Tool::updateMeasure () inline protected virtual inherited
updateTool
void Isis::Tool::updateTool () virtual slot inherited
Updates the tool.
Reimplemented in Isis::ZoomTool, Isis::WindowTool, Isis::SunShadowTool, Isis::StretchTool, Isis::SpectralPlotTool, Isis::SpecialPixelTool, Isis::SpatialPlotTool, Isis::MeasureTool, Isis::LatLonGridTool, Isis::HistogramTool, Isis::FindTool, Isis::FileTool, Isis::FeatureNomenclatureTool, Isis::EditTool, Isis::BlinkTool, Isis::BandTool, and Isis::AbstractPlotTool.
Referenced by Isis::Tool::setCubeViewport().
viewportChanged
void Isis::Tool::viewportChanged () signal inherited
Referenced by Isis::Tool::setCubeViewport(), Isis::SpatialPlotTool::SpatialPlotTool(), Isis::SpectralPlotTool::SpectralPlotTool(), and Isis::SunShadowTool::SunShadowTool().
workspace()
Workspace * Isis::Tool::workspace () protected inherited
Referenced by Isis::EditTool::addTo(), Isis::ControlNetTool::setControlNet(), and Isis::ScatterPlotTool::showNewScatterPlotConfig().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/QnetTools/QnetNavTool.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/QnetTools/QnetNavTool.cpp