Isis Developer Reference: IsisAml Class Reference
IsisAml Class Reference
Application Interface
Application program XML file parameter manager.
#include <IsisAml.h>
Public Member Functions
IsisAml (const QString &xmlfile)
Constructs an IsisAml object and internalizes the XML data in the given file name.
~IsisAml ()
Destructs an IsisAml object.
void PutAsString (const QString &paramName, const QString &value)
Allows the insertion of a value for any parameter.
void PutAsString (const QString &paramName, const std::vector< QString > &value)
void PutFileName (const QString &paramName, const QString &value)
Allows the insertion of a value for a parameter of type "filename".
void PutFileName (const QString &paramName, const std::vector< QString > &value)
void PutCubeName (const QString &paramName, const QString &value)
Allows the insertion of a value for a parameter of type "cubename".
void PutDouble (const QString &paramName, const double &value)
Allows the insertion of a value for a parameter of type "double".
void PutDouble (const QString &paramName, const std::vector< double > &value)
void PutInteger (const QString &paramName, const int &value)
Allows the insertion of a value for a parameter of type "integer".
void PutInteger (const QString &paramName, const std::vector< int > &value)
void PutBoolean (const QString &paramName, const bool &value)
Allows the insertion of a value for a parameter of type "boolean".
void PutBoolean (const QString &paramName, const std::vector< bool > &value)
void PutString (const QString &paramName, const QString &value)
Allows the insertion of a value for any parameter.
void PutString (const QString &paramName, const std::vector< QString > &value)
QString GetAsString (const QString &paramName) const
Allows the retrieval of a value for a parameter of any type.
void GetAsString (const QString &paramName, std::vector< QString > &values) const
QString GetFileName (const QString &paramName, QString extension="") const
Allows the retrieval of a value for a parameter of type "filename".
void GetFileName (const QString &paramName, std::vector< QString > &values) const
QString GetCubeName (const QString &paramName, QString extension="") const
Retrieves of a value for a parameter of type "cubename".
QString GetString (const QString &paramName) const
Allows the retrieval of a value for a parameter of type "string".
void GetString (const QString &paramName, std::vector< QString > &values) const
int GetInteger (const QString &paramName) const
Allows the retrieval of a value for a parameter of type "integer".
void GetInteger (const QString &paramName, std::vector< int > &values) const
bool GetBoolean (const QString &paramName) const
Allows the retrieval of a value for a parameter of type "boolean".
void GetBoolean (const QString &paramName, std::vector< bool > &values) const
double GetDouble (const QString &paramName) const
Allows the retrieval of a value for a parameter of type "double".
void GetDouble (const QString &paramName, std::vector< double > &values) const
bool WasEntered (const QString &paramName) const
Returns a true if the parameter has a value, and false if it does not.
void Clear (const QString &paramName)
Clears the value(s) in the named parameter.
Isis::CubeAttributeInput & GetInputAttribute (const QString &paramName)
Gets the attributes for an input cube.
Isis::CubeAttributeOutput & GetOutputAttribute (const QString &paramName)
Gets the attributes for an output cube.
QString ProgramName () const
Returns the Program name.
QString Brief () const
Returns the brief description of the program.
QString Description () const
Returns the full description of the program.
int NumGroups () const
Returns the number of groups found in the XML.
QString GroupName (const int &group) const
Returns the group name of group[index].
int GroupIndex (const QString &grpName) const
Given the group name get its index in group array.
nlohmann::json GetParams ()
Creates a json object which could be used as a command line.
int NumParams (const int &) const
Returns the number of parameters in a group.
QString ParamName (const int &group, const int &param) const
Returns the parameter name.
QString ParamType (const int &group, const int &param) const
Returns the parameter type of a parameter in a specified group.
QString ParamBrief (const int &group, const int &param) const
Returns the brief description of a parameter in a specified group.
QString ParamDescription (const int &group, const int &param) const
Returns the long description of a parameter in a specified group.
QString ParamMinimum (const int &group, const int &param) const
Returns the minimum value of a parameter in a specified group.
QString ParamMinimumInclusive (const int &group, const int &param) const
Returns whether the minimum value is inclusive or not.
QString ParamMaximum (const int &group, const int &param) const
Returns the maximum value of a parameter in a specified group.
QString ParamMaximumInclusive (const int &group, const int &param) const
Returns whether the maximum value is inclusive or not.
QString ParamOdd (const int &group, const int &param) const
Returns whether the selected parameter has a restriction on odd values or not.
int ParamGreaterThanSize (const int &group, const int &param) const
Returns the number of values in the parameters greater than list.
int ParamGreaterThanOrEqualSize (const int &group, const int &param) const
Returns the number of values in the parameters greater than or equal list.
int ParamLessThanSize (const int &group, const int &param) const
Returns the number of values in the parameters less than list.
int ParamLessThanOrEqualSize (const int &group, const int &param) const
Returns the number of values in the parameters less than or equal list.
int ParamNotEqualSize (const int &group, const int &param) const
Returns the number of values in the not equal list.
QString ParamGreaterThan (const int &group, const int &param, const int &great) const
Returns the name of the specified greaterThan parameter.
QString ParamGreaterThanOrEqual (const int &group, const int &param, const int &great) const
Returns the name of the specified greaterThanOrEqual parameter.
QString ParamLessThan (const int &group, const int &param, const int &great) const
Returns the name of the specified lessThan parameter.
QString ParamLessThanOrEqual (const int &group, const int &param, const int &les) const
Returns the name of the specified lessThanOrEqual parameter.
QString ParamNotEqual (const int &group, const int &param, const int &notEq) const
Returns the name of the specified notEqual parameter.
int ParamListSize (const int &group, const int &param) const
Returns the number of options in the specified parameter's list.
QString ParamListValue (const int &group, const int &param, const int &option) const
Returns the option value for a specific option to a parameter.
QString ParamListBrief (const int &group, const int &param, const int &option) const
Returns the brief description for a specific option to a parameter.
QString ParamListDescription (const int &group, const int &param, const int &option) const
Returns the full description for a specific option to a parameter.
int ParamListExcludeSize (const int &group, const int &param, const int &option) const
Returns the number of items in a parameters list exclude section.
QString ParamListExclude (const int &group, const int &param, const int &option, const int &exclude) const
Returns the parameter name to be excluded if this option is selected.
int ParamListIncludeSize (const int &group, const int &param, const int &option) const
Returns the number of items in a parameters list include section.
QString ParamListInclude (const int &group, const int &param, const int &option, const int &include) const
Returns the parameter name to be included if this option is selected.
QString ParamDefault (const int &group, const int &param) const
Returns the default for a parameter in a specified group.
QString ParamInternalDefault (const int &group, const int &param) const
Returns the internal default for a parameter in a specified group.
QString ParamFilter (const int &group, const int &param) const
Returns the parameter filter for a parameter in a specified group.
QString ParamPath (const int &group, const int &param) const
Returns the default path for a filename/cube parameter.
QString ParamFileMode (const int &group, const int &param) const
Returns the file mode for a parameter in a specified group.
int ParamExcludeSize (const int &group, const int &param) const
Returns the number of parameters excluded in this parameter's exclusions.
QString ParamExclude (const int &group, const int &param, const int &exclude) const
Returns the name of the specified excluded parameter.
int ParamIncludeSize (const int &group, const int &param) const
Returns the number of parameters included in this parameter's inclusions.
QString ParamInclude (const int &group, const int &param, const int &include) const
Returns the name of the specified included parameter.
QString PixelType (const int &group, const int &param) const
Returns the default pixel type from the XML.
int HelpersSize (const int &group, const int &param) const
Returns the number of helpers the parameter has.
QString HelperButtonName (const int &group, const int &param, const int &helper) const
Returns the name of the helper button.
QString HelperFunction (const int &group, const int &param, const int &helper) const
Returns the name of the helper function.
QString HelperBrief (const int &group, const int &param, const int &helper) const
Returns the brief description of the helper button.
QString HelperDescription (const int &group, const int &param, const int &helper) const
Returns the long description of the helper button.
QString HelperIcon (const int &group, const int &param, const int &helper) const
Returns the name of the icon for the helper button.
bool IsParamInPvlInclude (QString &paramName, std::vector< QString > &exclude)
Verify whether Parameter name is in the Include list Used in creation of DefFile.
void CreatePVL (Isis::Pvl &pvlDef, QString guiGrpName, QString pvlObjName, QString pvlGrpName, std::vector< QString > &exclude)
Create Pvl with the parameters in a user defined group given the Pvl object and group name.
void VerifyAll ()
Verify all parameters.
bool StringToBool (QString value) const
Returns a boolean value based on the QString contents.
void CommandLine (Isis::Pvl &lab) const
Creates a QString which could be used as a command line.
QString Version () const
Returns the application version date.
Protected Member Functions
const IsisParameterData * ReturnParam (const QString &paramName) const
Returns a pointer to a parameter whose name starts with paramName.
Protected Attributes
QString name
QString brief
QString description
std::vector< IsisGroupData > groups
std::vector< QString > categorys
std::vector< IsisChangeData > changes
Detailed Description
Application program XML file parameter manager.
This class is used to manage the data in an application XML file pertaining to the program parameters. The data is stored, accessed, and modified through this class and its helper classes.
Author
2002-05-30 Stuart Sides
Constructor & Destructor Documentation
IsisAml()
IsisAml::IsisAml (const QString & xmlfile)
Constructs an IsisAml object and internalizes the XML data in the given file name.
Parameters
xmlfile Indicates the pull path of the XML file to be parsed.
~IsisAml()
IsisAml::~IsisAml ()
Destructs an IsisAml object.
Member Function Documentation
Brief()
QString IsisAml::Brief () const
Returns the brief description of the program.
Returns
The brief description.
Clear()
void IsisAml::Clear (const QString & paramName)
Clears the value(s) in the named parameter.
Parameters
paramName The name of the parameter to clear
References IsisParameterData::inCubeAtt, IsisParameterData::outCubeAtt, IsisParameterData::pixelType, Isis::CubeAttribute< ChildClass >::setAttributes(), and IsisParameterData::values.
Referenced by Isis::UserInterface::SetBatchList(), and Isis::ProcessExport::SetInputRange().
CommandLine()
void IsisAml::CommandLine (Isis::Pvl & cont) const
Creates a QString which could be used as a command line.
Parameters
cont Pvl to put command line information in
References Isis::PvlObject::addGroup(), Isis::PvlKeyword::addValue(), Isis::PvlObject::clear(), IsisParameterData::defaultValues, Isis::PvlContainer::deleteKeyword(), Isis::PvlContainer::hasKeyword(), IsisParameterData::listOptions, IsisParameterData::name, Isis::IString::Trim(), IsisParameterData::type, Isis::IString::UpCase(), and IsisParameterData::values.
Referenced by Isis::UserInterface::SaveHistory().
CreatePVL()
void IsisAml::CreatePVL (Isis::Pvl & pvlDef, QString guiGrpName, QString pvlObjName, QString pvlGrpName, std::vector< QString > & exclude)
Create Pvl with the parameters in a user defined group given the Pvl object and group name.
Create a PVL file from the parameters in a Group given the Gui group name, Pvl Object and Group names and the list of parameters to be included in the Pvl.
Author
Sharmila Prasad (8/11/2011)
Parameters
pvlDef - output PVL
guiGrpName - Gui Group name
pvlObjName - output PVL Object name
pvlGrpName - output PVL Group name
include - vector of parameter names to be part of the output PVL
References _FILEINFO_, Isis::IString::DownCase(), Isis::toString(), and Isis::IException::User.
Description()
QString IsisAml::Description () const
Returns the full description of the program.
Returns
The full description.
GetAsString() [1/2]
QString IsisAml::GetAsString (const QString & paramName) const
Allows the retrieval of a value for a parameter of any type.
The value will be returned as a QString no matter what the parameter type is.
Parameters
paramName The partial or full name of the parameter to be retrieved.
Returns
A QString representation of the value for the specified parameter.
Exceptions
iException (IsisProgrammerError) The parameter has no value.
References _FILEINFO_, IsisParameterData::defaultValues, Isis::IException::Programmer, and IsisParameterData::values.
Referenced by Isis::PipelineApplication::AddParameter(), Isis::Pipeline::SetInputFile(), Isis::Pipeline::SetOutputFile(), Isis::GuiParameter::SetToCurrent(), and Isis::GuiParameter::Update().
GetAsString() [2/2]
void IsisAml::GetAsString (const QString & paramName, std::vector< QString > & values) const
GetBoolean() [1/2]
bool IsisAml::GetBoolean (const QString & paramName) const
Allows the retrieval of a value for a parameter of type "boolean".
Parameters
paramName The partial or full name of the parameter to be retrieved.
Returns
The value of the parameter.
Exceptions
iException::Programmer (IsisErrorUser) The parameter has no value.
References _FILEINFO_, IsisParameterData::defaultValues, Isis::IException::Programmer, Isis::toBool(), IsisParameterData::type, Isis::IException::User, and IsisParameterData::values.
GetBoolean() [2/2]
void IsisAml::GetBoolean (const QString & paramName, std::vector< bool > & values) const
GetCubeName()
QString IsisAml::GetCubeName (const QString & paramName, QString extension = "") const
Retrieves of a value for a parameter of type "cubename".
Parameters
paramName The partial or full name of the parameter to be retrieved.
extension A default extension to add if it does not already exist on the file name. For example, "txt" will make /mydir/myfile into /mydir/myfile.txt
Returns
The value of the parameter.
References _FILEINFO_, Isis::FileName::addExtension(), Isis::FileName::attributes(), IsisParameterData::defaultValues, Isis::FileName::expanded(), Isis::IException::Programmer, IsisParameterData::type, Isis::IException::User, and IsisParameterData::values.
Referenced by Isis::Pipeline::SetInputFile(), Isis::ProcessImport::SetOutputCube(), Isis::ProcessMosaic::SetOutputCube(), and Isis::Process::SetOutputCubeStretch().
GetDouble() [1/2]
double IsisAml::GetDouble (const QString & paramName) const
Allows the retrieval of a value for a parameter of type "double".
Parameters
paramName The partial or full name of the parameter to be retrieved.
Returns
The value of the parameter.
Exceptions
iException::Programmer (IsisErrorUser) The parameter has no value.
References _FILEINFO_, IsisParameterData::defaultValues, Isis::IException::Programmer, Isis::IString::ToDouble(), IsisParameterData::type, Isis::IException::User, and IsisParameterData::values.
Referenced by Isis::ProcessExport::SetInputRange().
GetDouble() [2/2]
void IsisAml::GetDouble (const QString & paramName, std::vector< double > & values) const
GetFileName() [1/2]
QString IsisAml::GetFileName (const QString & paramName, QString extension = "") const
Allows the retrieval of a value for a parameter of type "filename".
Parameters
paramName The partial or full name of the parameter to be retrieved.
extension A default extension to add if it does not already exist on the file name. For example, "txt" will make /mydir/myfile into /mydir/myfile.txt
Returns
The value of the parameter.
References _FILEINFO_, Isis::FileName::addExtension(), IsisParameterData::defaultValues, Isis::FileName::expanded(), Isis::IException::Programmer, IsisParameterData::type, Isis::IException::User, and IsisParameterData::values.
Referenced by Isis::Pipeline::SetInputListFile(), and Isis::Pipeline::SetOutputListFile().
GetFileName() [2/2]
void IsisAml::GetFileName (const QString & paramName, std::vector< QString > & values) const
GetInputAttribute()
Isis::CubeAttributeInput & IsisAml::GetInputAttribute (const QString & paramName)
Gets the attributes for an input cube.
Parameters
paramName The name of the parameter to get the attributes for
Returns
CubeAttributeInput
Exceptions
iException::Programmer "Parameter is not a cube."
iException::Programmer "Parameter in not an input cube"
References _FILEINFO_, IsisParameterData::defaultValues, IsisParameterData::fileMode, IsisParameterData::inCubeAtt, Isis::IException::Programmer, Isis::CubeAttribute< ChildClass >::setAttributes(), IsisParameterData::type, and IsisParameterData::values.
Referenced by Isis::Pipeline::SetInputFile().
GetInteger() [1/2]
int IsisAml::GetInteger (const QString & paramName) const
Allows the retrieval of a value for a parameter of type "integer".
Parameters
paramName The partial or full name of the parameter to be retrieved.
Returns
The value of the parameter.
Exceptions
iException::Programmer (IsisErrorUser) The parameter has no value.
References _FILEINFO_, IsisParameterData::defaultValues, Isis::IException::Programmer, Isis::IString::ToInteger(), IsisParameterData::type, Isis::IException::User, and IsisParameterData::values.
GetInteger() [2/2]
void IsisAml::GetInteger (const QString & paramName, std::vector< int > & values) const
GetOutputAttribute()
Isis::CubeAttributeOutput & IsisAml::GetOutputAttribute (const QString & paramName)
Gets the attributes for an output cube.
Parameters
paramName The name of the parameter to get the attributes for
Returns
CubeAttributeOutput
Exceptions
iException::Programmer "Parameter is not a cube"
iException::Programmer "Parameter in not an output"
References _FILEINFO_, Isis::CubeAttribute< ChildClass >::addAttributes(), IsisParameterData::defaultValues, IsisParameterData::fileMode, IsisParameterData::outCubeAtt, IsisParameterData::pixelType, Isis::IException::Programmer, Isis::CubeAttribute< ChildClass >::setAttributes(), IsisParameterData::type, and IsisParameterData::values.
Referenced by Isis::ProcessImport::SetOutputCube(), and Isis::Process::SetOutputCubeStretch().
GetParams()
json IsisAml::GetParams ()
Creates a json object which could be used as a command line.
References IsisParameterData::defaultValues, IsisParameterData::name, and IsisParameterData::values.
GetString() [1/2]
QString IsisAml::GetString (const QString & paramName) const
Allows the retrieval of a value for a parameter of type "string".
Parameters
paramName The partial or full name of the parameter to be retrieved.
Returns
The value of the parameter.
Exceptions
iException::Programmer (IsisErrorUser) The parameter has no value.
References _FILEINFO_, IsisParameterData::defaultValues, IsisParameterData::listOptions, Isis::IException::Programmer, IsisParameterData::type, Isis::IException::User, and IsisParameterData::values.
Referenced by Isis::ProcessExport::SetInputRange().
GetString() [2/2]
void IsisAml::GetString (const QString & paramName, std::vector< QString > & values) const
GroupIndex()
int IsisAml::GroupIndex (const QString & grpName) const
Given the group name get its index in group array.
Given group name return its index in the Gui.
Author
Sharmila Prasad (8/11/2011)
Parameters
grpName
Returns
int
References Isis::IString::DownCase().
GroupName()
QString IsisAml::GroupName (const int & index) const
Returns the group name of group[index].
Parameters
index The array index of the group.
Returns
The group name.
HelperBrief()
QString IsisAml::HelperBrief (const int & group, const int & param, const int & helper) const
Returns the brief description of the helper button.
Parameters
group The group index
param The parameter index
helper The helper index
Returns
QString The brief description of the helper button
Referenced by Isis::GuiParameter::AddHelpers().
HelperButtonName()
QString IsisAml::HelperButtonName (const int & group, const int & param, const int & helper) const
Returns the name of the helper button.
Parameters
group The group index
param The parameter index
helper The helper index
Returns
QString The name of the helper
Referenced by Isis::GuiParameter::AddHelpers().
HelperDescription()
QString IsisAml::HelperDescription (const int & group, const int & param, const int & helper) const
Returns the long description of the helper button.
Parameters
group The group index
param The parameter index
helper The helper index
Returns
QString The long description of the helper button
Referenced by Isis::GuiParameter::AddHelpers().
HelperFunction()
QString IsisAml::HelperFunction (const int & group, const int & param, const int & helper) const
Returns the name of the helper function.
Parameters
group The group index
param The parameter index
helper The helper index
Returns
QString The name of the helper function
Referenced by Isis::GuiParameter::AddHelpers().
HelperIcon()
QString IsisAml::HelperIcon (const int & group, const int & param, const int & helper) const
Returns the name of the icon for the helper button.
Parameters
group The group index
param The parameter index
helper The helper index
Returns
QString The name of the helper icon
Referenced by Isis::GuiParameter::AddHelpers().
HelpersSize()
int IsisAml::HelpersSize (const int & group, const int & param) const
Returns the number of helpers the parameter has.
Parameters
group The group index
param The parameter index
Returns
int The number of helpers the parameter has
Referenced by Isis::GuiParameter::AddHelpers(), Isis::GuiBooleanParameter::GuiBooleanParameter(), Isis::GuiDoubleParameter::GuiDoubleParameter(), Isis::GuiFileNameParameter::GuiFileNameParameter(), Isis::GuiIntegerParameter::GuiIntegerParameter(), Isis::GuiListParameter::GuiListParameter(), and Isis::GuiStringParameter::GuiStringParameter().
IsParamInPvlInclude()
bool IsisAml::IsParamInPvlInclude (QString & paramName, std::vector< QString > & exclude)
Verify whether Parameter name is in the Include list Used in creation of DefFile.
Verify if the Parameter is in the Included list.
Author
Sharmila Prasad (8/11/2011)
Parameters
paramName - parameter name
include - include list
Returns
bool
References Isis::IString::DownCase().
NumGroups()
int IsisAml::NumGroups () const
Returns the number of groups found in the XML.
Returns
The number of groups.
Referenced by Isis::Gui::Gui(), and Isis::UserInterface::SetBatchList().
NumParams()
int IsisAml::NumParams (const int & group) const
Returns the number of parameters in a group.
Parameters
group The group to measure.
Returns
The number of parameters.
Referenced by Isis::Gui::Gui(), and Isis::UserInterface::SetBatchList().
ParamBrief()
QString IsisAml::ParamBrief (const int & group, const int & param) const
Returns the brief description of a parameter in a specified group.
Parameters
group The group index
param The parameter index
Returns
The brief description.
Referenced by Isis::GuiBooleanParameter::GuiBooleanParameter(), and Isis::GuiParameter::GuiParameter().
ParamDefault()
QString IsisAml::ParamDefault (const int & group, const int & param) const
Returns the default for a parameter in a specified group.
Parameters
group The group index
param The parameter index
Returns
The default for the specified parameter.
Referenced by Isis::GuiParameter::GuiParameter(), Isis::GuiBooleanParameter::IsModified(), Isis::GuiParameter::IsModified(), Isis::GuiParameter::SetToDefault(), and Isis::GuiParameter::Update().
ParamDescription()
QString IsisAml::ParamDescription (const int & group, const int & param) const
Returns the long description of a parameter in a specified group.
Parameters
group The group index
param The parameter index
Returns
The long description
ParamExclude()
QString IsisAml::ParamExclude (const int & group, const int & param, const int & exclude) const
Returns the name of the specified excluded parameter.
Parameters
group The group index
param The parameter index
exclude The exclude index
Returns
The name of the excluded parameter
Referenced by Isis::GuiBooleanParameter::Exclusions(), and Isis::GuiParameter::GuiParameter().
ParamExcludeSize()
int IsisAml::ParamExcludeSize (const int & group, const int & param) const
Returns the number of parameters excluded in this parameter's exclusions.
Parameters
group The group index
param The parameter index
Returns
The number of items in the parameters exclude list
Referenced by Isis::GuiBooleanParameter::Exclusions(), and Isis::GuiParameter::GuiParameter().
ParamFileMode()
QString IsisAml::ParamFileMode (const int & group, const int & param) const
Returns the file mode for a parameter in a specified group.
Parameters
group The group index
param The parameter index
Returns
The file mode for the parameter.
Referenced by Isis::GuiFileNameParameter::SelectFile().
ParamFilter()
QString IsisAml::ParamFilter (const int & group, const int & param) const
Returns the parameter filter for a parameter in a specified group.
Parameters
group The group index
param The parameter index
Returns
The paramter filter.
Referenced by Isis::GuiFileNameParameter::SelectFile().
ParamGreaterThan()
QString IsisAml::ParamGreaterThan (const int & group, const int & param, const int & great) const
Returns the name of the specified greaterThan parameter.
Parameters
group The group index
param The parameter index
great The greaterThan index
Returns
The name of the greaterThan parameter
Referenced by Isis::GuiParameter::GuiParameter().
ParamGreaterThanOrEqual()
QString IsisAml::ParamGreaterThanOrEqual (const int & group, const int & param, const int & great) const
Returns the name of the specified greaterThanOrEqual parameter.
Parameters
group The group index
param The parameter index
great The greaterThanOrEqual index
Returns
The name of the greaterThanOrEqual parameter
Referenced by Isis::GuiParameter::GuiParameter().
ParamGreaterThanOrEqualSize()
int IsisAml::ParamGreaterThanOrEqualSize (const int & group, const int & param) const
Returns the number of values in the parameters greater than or equal list.
Parameters
group The group index
param The parameter index
Returns
Number of values in the parameters greater than or equal list
Referenced by Isis::GuiParameter::GuiParameter().
ParamGreaterThanSize()
int IsisAml::ParamGreaterThanSize (const int & group, const int & param) const
Returns the number of values in the parameters greater than list.
Parameters
group The group index
param The parameter index
Returns
Number of values in the parameters greater than list
Referenced by Isis::GuiParameter::GuiParameter().
ParamInclude()
QString IsisAml::ParamInclude (const int & group, const int & param, const int & include) const
Returns the name of the specified included parameter.
Parameters
group The group index
param The parameter index
include The include index
Returns
The name of the included parameter
Referenced by Isis::GuiBooleanParameter::Exclusions(), and Isis::GuiParameter::GuiParameter().
ParamIncludeSize()
int IsisAml::ParamIncludeSize (const int & group, const int & param) const
Returns the number of parameters included in this parameter's inclusions.
Parameters
group The group index
param The parameter index
Returns
The number of items in the parameters include list
Referenced by Isis::GuiBooleanParameter::Exclusions(), and Isis::GuiParameter::GuiParameter().
ParamInternalDefault()
QString IsisAml::ParamInternalDefault (const int & group, const int & param) const
Returns the internal default for a parameter in a specified group.
.
Parameters
group The group index
param The parameter index
Returns
The internal default for the specified parameter.
Referenced by Isis::GuiParameter::GuiParameter(), Isis::GuiParameter::IsModified(), Isis::GuiFileNameParameter::SelectFile(), Isis::GuiParameter::SetToDefault(), and Isis::GuiParameter::Update().
ParamLessThan()
QString IsisAml::ParamLessThan (const int & group, const int & param, const int & les) const
Returns the name of the specified lessThan parameter.
Parameters
group The group index
param The parameter index
les The lessThan index
Returns
The name of the lessThan parameter
Referenced by Isis::GuiParameter::GuiParameter().
ParamLessThanOrEqual()
QString IsisAml::ParamLessThanOrEqual (const int & group, const int & param, const int & les) const
Returns the name of the specified lessThanOrEqual parameter.
Parameters
group The group index
param The parameter index
les The lessThanOrEqual index
Returns
The name of the lessThanOrEqual parameter
Referenced by Isis::GuiParameter::GuiParameter().
ParamLessThanOrEqualSize()
int IsisAml::ParamLessThanOrEqualSize (const int & group, const int & param) const
Returns the number of values in the parameters less than or equal list.
Parameters
group The group index
param The parameter index
Returns
Number of values in the parameters less than or equal list
Referenced by Isis::GuiParameter::GuiParameter().
ParamLessThanSize()
int IsisAml::ParamLessThanSize (const int & group, const int & param) const
Returns the number of values in the parameters less than list.
Parameters
group The group index
param The parameter index
Returns
Number of values in the parameters less than list
Referenced by Isis::GuiParameter::GuiParameter().
ParamListBrief()
QString IsisAml::ParamListBrief (const int & group, const int & param, const int & option) const
Returns the brief description for a specific option to a parameter.
Parameters
group The group index
param The parameter index
option The option number within the parameters list.
Returns
The brief description of the option.
Referenced by Isis::GuiComboBoxParameter::GuiComboBoxParameter(), and Isis::GuiListParameter::GuiListParameter().
ParamListDescription()
QString IsisAml::ParamListDescription (const int & group, const int & param, const int & option) const
Returns the full description for a specific option to a parameter.
Parameters
group The group index
param The parameter index
option The option number within the parameters list.
Returns
The full description of the option.
ParamListExclude()
QString IsisAml::ParamListExclude (const int & group, const int & param, const int & option, const int & exclude) const
Returns the parameter name to be excluded if this option is selected.
Parameters
group The group index
param The parameter index
option The option number within the parameters list.
exclude The exclusion number within the parameters list.
Returns
The parameter name to be excluded if this option is selected.
Referenced by Isis::GuiComboBoxParameter::Exclusions(), and Isis::GuiListParameter::Exclusions().
ParamListExcludeSize()
int IsisAml::ParamListExcludeSize (const int & group, const int & param, const int & option) const
Returns the number of items in a parameters list exclude section.
Parameters
group The group index
param The parameter index
option The option number within the parameters list.
Returns
The number of items in the parameters list exclude section.
Referenced by Isis::GuiComboBoxParameter::Exclusions(), and Isis::GuiListParameter::Exclusions().
ParamListInclude()
QString IsisAml::ParamListInclude (const int & group, const int & param, const int & option, const int & include) const
Returns the parameter name to be included if this option is selected.
Parameters
group The group index
param The parameter index
option The option number within the parameters list.
include The inclusion number within the parameters list.
Returns
The parameter name to be included if this option is selected.
ParamListIncludeSize()
int IsisAml::ParamListIncludeSize (const int & group, const int & param, const int & option) const
Returns the number of items in a parameters list include section.
Parameters
group The group index
param The parameter index
option The option number within the parameters list.
Returns
The number of items in the parameters list include section.
ParamListSize()
int IsisAml::ParamListSize (const int & group, const int & param) const
Returns the number of options in the specified parameter's list.
Parameters
group The group index
param The parameter index
Returns
The number of options contained in the parameter's list. If the parameter does not contain a list, zero will be returned.
Referenced by Isis::GuiParameterFactory::Create(), Isis::GuiComboBoxParameter::GuiComboBoxParameter(), Isis::GuiListParameter::GuiListParameter(), Isis::GuiComboBoxParameter::Set(), and Isis::GuiListParameter::Set().
ParamListValue()
QString IsisAml::ParamListValue (const int & group, const int & param, const int & option) const
Returns the option value for a specific option to a parameter.
Parameters
group The group index
param The parameter index
option The option number within the parameters list.
Returns
The value of the option.
Referenced by Isis::GuiComboBoxParameter::GuiComboBoxParameter(), Isis::GuiListParameter::GuiListParameter(), Isis::GuiComboBoxParameter::Set(), Isis::GuiListParameter::Set(), Isis::GuiComboBoxParameter::Value(), and Isis::GuiListParameter::Value().
ParamMaximum()
QString IsisAml::ParamMaximum (const int & group, const int & param) const
Returns the maximum value of a parameter in a specified group.
Parameters
group The group index
param The parameter index
Returns
The maximum
Referenced by Isis::GuiParameter::GuiParameter().
ParamMaximumInclusive()
QString IsisAml::ParamMaximumInclusive (const int & group, const int & param) const
Returns whether the maximum value is inclusive or not.
Parameters
group The group index
param The parameter index
Returns
Whether maximum is inclusive or not
Referenced by Isis::GuiParameter::GuiParameter().
ParamMinimum()
QString IsisAml::ParamMinimum (const int & group, const int & param) const
Returns the minimum value of a parameter in a specified group.
Parameters
group The group index
param The parameter index
Returns
The minimum
Referenced by Isis::GuiParameter::GuiParameter().
ParamMinimumInclusive()
QString IsisAml::ParamMinimumInclusive (const int & group, const int & param) const
Returns whether the minimum value is inclusive or not.
Parameters
group The group index
param The parameter index
Returns
Whether minimum is inclusive or not
Referenced by Isis::GuiParameter::GuiParameter().
ParamName()
QString IsisAml::ParamName (const int & group, const int & param) const
Returns the parameter name.
Parameters
group The group index where the parameter can be found.
param The index of the parameter to name.
Returns
The name of the parameter.
Referenced by Isis::GuiParameter::GuiParameter(), and Isis::UserInterface::SetBatchList().
ParamNotEqual()
QString IsisAml::ParamNotEqual (const int & group, const int & param, const int & notEq) const
Returns the name of the specified notEqual parameter.
Parameters
group The group index
param The parameter index
notEq The notEqual index
Returns
The name of the notEqual parameter
Referenced by Isis::GuiParameter::GuiParameter().
ParamNotEqualSize()
int IsisAml::ParamNotEqualSize (const int & group, const int & param) const
Returns the number of values in the not equal list.
Parameters
group The group index
param The parameter index
Returns
Number of values in the parameters not equal list
Referenced by Isis::GuiParameter::GuiParameter().
ParamOdd()
QString IsisAml::ParamOdd (const int & group, const int & param) const
Returns whether the selected parameter has a restriction on odd values or not.
Parameters
group The group index
param The parameter index
Returns
Whether the parameter restricts odd values or not
Referenced by Isis::GuiParameter::GuiParameter().
ParamPath()
QString IsisAml::ParamPath (const int & group, const int & param) const
Returns the default path for a filename/cube parameter.
Parameters
group The group index
param The parameter index
Returns
The default path.
Referenced by Isis::GuiFileNameParameter::SelectFile().
ParamType()
QString IsisAml::ParamType (const int & group, const int & param) const
Returns the parameter type of a parameter in a specified group.
Parameters
group The group index
param The parameter index
Returns
The type of parameter.
Referenced by Isis::GuiParameterFactory::Create(), and Isis::GuiParameter::GuiParameter().
PixelType()
QString IsisAml::PixelType (const int & group, const int & param) const
Returns the default pixel type from the XML.
Parameters
group The group index
param The parameter index
Returns
The default pixel type
Referenced by Isis::GuiParameter::GuiParameter().
ProgramName()
QString IsisAml::ProgramName () const
Returns the Program name.
Returns
The name of the program.
Referenced by Isis::UserInterface::SaveHistory(), and Isis::Gui::ShowWarning().
PutAsString() [1/2]
void IsisAml::PutAsString (const QString & paramName, const QString & value)
Allows the insertion of a value for any parameter.
No validity check is performed on the value passed in.
Parameters
paramName The partial or full name of the parameter to be modified.
value The QString representation of the value to be placed in the parameters value data member. For parameters of type integer, the QString must be convertable to an integer. For parameters of type double, the QString must be convertable to a double. For parameters of type boolean, the QString must be one of: (TRUE, FALSE, YES, NO, or a partial match of any of these beginning with the first character).
Exceptions
IException The parameter already has a value in its "value" data member.Overwriting an existing value is not allowed. Use "Clear" to erase all values in the value data member instead of overwriting an existing value.
References _FILEINFO_, Isis::IException::User, and IsisParameterData::values.
Referenced by Isis::UserInterface::SetBatchList().
PutAsString() [2/2]
void IsisAml::PutAsString (const QString & paramName, const std::vector< QString > & value)
PutBoolean() [1/2]
void IsisAml::PutBoolean (const QString & paramName, const bool & value)
Allows the insertion of a value for a parameter of type "boolean".
A validity check is performed on the value passed in.
Parameters
paramName The partial or full name of the parameter to be modified.
value The boolean value to be placed in the boolean's value data member.
Exceptions
iException (IsisProgrammerError) The parameter already has a value in its "value" data member.Overwriting an existing value is not allowed. Use "Clear" to erase all values in the value data member instead of overwriting an existing value.
iException (IsisProgrammerError) The parameter is not of type "boolean".
References _FILEINFO_, Isis::IException::Programmer, IsisParameterData::type, and IsisParameterData::values.
PutBoolean() [2/2]
void IsisAml::PutBoolean (const QString & paramName, const std::vector< bool > & value)
PutCubeName()
void IsisAml::PutCubeName (const QString & paramName, const QString & value)
Allows the insertion of a value for a parameter of type "cubename".
A validity check is performed on the value passed in.
Parameters
paramName The partial or full name of the parameter to be modified.
value The QString representation of the value to be placed in the cubename's value data member.
References _FILEINFO_, Isis::IException::Programmer, IsisParameterData::type, and IsisParameterData::values.
PutDouble() [1/2]
void IsisAml::PutDouble (const QString & paramName, const double & value)
Allows the insertion of a value for a parameter of type "double".
A validity check is performed on the value passed in.
Parameters
paramName The partial or full name of the parameter to be modified.
value The double value to be placed in the double's value data member.
Exceptions
iException (IsisProgrammerError) The parameter already has a value in its "value" data member.Overwriting an existing value is not allowed. Use "Clear" to erase all values in the value data member instead of overwriting an existing value.
iException (IsisProgrammerError) The parameter is not of type "double".
References _FILEINFO_, Isis::IException::Programmer, Isis::toString(), IsisParameterData::type, and IsisParameterData::values.
Referenced by Isis::ProcessExport::SetInputRange().
PutDouble() [2/2]
void IsisAml::PutDouble (const QString & paramName, const std::vector< double > & value)
PutFileName() [1/2]
void IsisAml::PutFileName (const QString & paramName, const QString & value)
Allows the insertion of a value for a parameter of type "filename".
A validity check is performed on the value passed in.
Parameters
paramName The partial or full name of the parameter to be modified.
value The QString representation of the value to be placed in the filename's value data member.
References _FILEINFO_, Isis::IException::Programmer, IsisParameterData::type, and IsisParameterData::values.
PutFileName() [2/2]
void IsisAml::PutFileName (const QString & paramName, const std::vector< QString > & value)
PutInteger() [1/2]
void IsisAml::PutInteger (const QString & paramName, const int & value)
Allows the insertion of a value for a parameter of type "integer".
A validity check is performed on the value passed in.
Parameters
paramName The partial or full name of the parameter to be modified.
value The integer value to be placed in the integer's value data member.
Exceptions
iException (IsisProgrammerError) The parameter is not of type "int".
References _FILEINFO_, Isis::IException::Programmer, Isis::toString(), IsisParameterData::type, and IsisParameterData::values.
PutInteger() [2/2]
void IsisAml::PutInteger (const QString & paramName, const std::vector< int > & value)
PutString() [1/2]
void IsisAml::PutString (const QString & paramName, const QString & value)
Allows the insertion of a value for any parameter.
No validity check is performed on the value passed in.
Parameters
paramName The partial or full name of the parameter to be modified.
value The QString representation of the value to be placed in the parameters value data member. For parameters of type integer, the QString must be convertable to an integer. For parameters of type double, the QString must be convertable to a double. For parameters of type boolean, the QString must be one of: (TRUE, FALSE, YES, NO, or a partial match of any of these beginning with the first character).
References _FILEINFO_, Isis::IException::Programmer, IsisParameterData::type, and IsisParameterData::values.
PutString() [2/2]
void IsisAml::PutString (const QString & paramName, const std::vector< QString > & value)
ReturnParam()
const IsisParameterData * IsisAml::ReturnParam (const QString & paramName) const protected
Returns a pointer to a parameter whose name starts with paramName.
Parameters
paramName The name of the parameter to return
Returns
IsisParameterData
Exceptions
iException::User (Parameter is not unique)
iException::User (Unknown Parameter)
References _FILEINFO_, Isis::IString::UpCase(), and Isis::IException::User.
StringToBool()
bool IsisAml::StringToBool (QString value) const
Returns a boolean value based on the QString contents.
Parameters
value The value to convert to a boolean
Returns
boolean value based on QString contents
Exceptions
iException::Programmer (Invalid boolean value)
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by Isis::GuiBooleanParameter::Set().
VerifyAll()
void IsisAml::VerifyAll ()
Verify all parameters.
References _FILEINFO_, IsisParameterData::defaultValues, IsisParameterData::exclude, IsisParameterData::greaterThan, IsisParameterData::greaterThanOrEqual, IsisParameterData::include, IsisParameterData::internalDefault, IsisParameterData::lessThan, IsisParameterData::lessThanOrEqual, IsisParameterData::listOptions, IsisParameterData::name, IsisParameterData::notEqual, Isis::IException::Programmer, IsisParameterData::type, Isis::IException::User, and IsisParameterData::values.
Referenced by Isis::UserInterface::SetBatchList().
Version()
QString IsisAml::Version () const
Returns the application version date.
Returns
The application version date
WasEntered()
bool IsisAml::WasEntered (const QString & paramName) const
Returns a true if the parameter has a value, and false if it does not.
Parameters
paramName The name of the parameter to check if it was entered
Returns
True if the parameter was entered, and false if it was not
References IsisParameterData::values.
Referenced by Isis::PipelineApplication::AddParameter(), Isis::Pipeline::SetInputFile(), Isis::Pipeline::SetOutputFile(), Isis::Pipeline::SetOutputListFile(), Isis::GuiParameter::SetToCurrent(), and Isis::GuiParameter::Update().
Member Data Documentation
brief
QString IsisAmlData::brief inherited
categorys
std::vector<QString> IsisAmlData::categorys inherited
changes
std::vector<IsisChangeData> IsisAmlData::changes inherited
description
QString IsisAmlData::description inherited
groups
std::vector<IsisGroupData> IsisAmlData::groups inherited
name
QString IsisAmlData::name inherited
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/IsisAml/IsisAml.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/IsisAml/IsisAml.cpp