Isis Developer Reference: Isis::HistoryTreeWidget Class Reference
Isis::HistoryTreeWidget Class Reference
History Widget for ipce.
#include <HistoryTreeWidget.h>
Public Member Functions
HistoryTreeWidget (Project *project, QWidget *parent=0)
Construct a history tree widget.
virtual ~HistoryTreeWidget ()
Clean up allocated memory.
void addToHistory (QString historyEntry)
Add a non-workorder history to the display.
Protected Member Functions
int sizeHintForColumn (int column) const
Get the preferred size of a given column.
Detailed Description
History Widget for ipce.
This widget shows the history of work orders performed on the project.
Author
2012-07-23 Steven Lambright
Constructor & Destructor Documentation
HistoryTreeWidget()
Isis::HistoryTreeWidget::HistoryTreeWidget (Project * project, QWidget * parent = 0)
Construct a history tree widget.
Parameters
project The project to show history for
parent The Qt-relationship parent
References addToHistory(), and Isis::Project::undoStack().
~HistoryTreeWidget()
Isis::HistoryTreeWidget::~HistoryTreeWidget () virtual
Clean up allocated memory.
Member Function Documentation
addToHistory()
void Isis::HistoryTreeWidget::addToHistory (QString historyEntry)
Add a non-workorder history to the display.
Parameters
(QString) historyEntry The string displayed in the history tree
Referenced by HistoryTreeWidget().
sizeHintForColumn()
int Isis::HistoryTreeWidget::sizeHintForColumn (int column) const protected
Get the preferred size of a given column.
This is used by resizeColumnToContents().
The work order name column prefers space not taken by other columns. The progress column prefers 200. The date column prefers a little more than the text size of a date.
Returns
The preferred width of the given column
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/HistoryTreeWidget/HistoryTreeWidget.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/HistoryTreeWidget/HistoryTreeWidget.cpp