Isis Developer Reference: Isis::ShapeModelFactory Class Reference
Isis::ShapeModelFactory Class Reference
This class is used to create ShapeModel objects.
#include <ShapeModelFactory.h>
Static Public Member Functions
static ShapeModel * create (Target *target, Pvl &pvl)
Construct a valid shape model from the given target and contents of kernels group.
Detailed Description
This class is used to create ShapeModel objects.
It determines the type of shape model in the input Pvl object and creates the appropriate type of shape model.
Author
2010-07-29 Debbie A. Cook
Member Function Documentation
create()
ShapeModel * Isis::ShapeModelFactory::create (Target * target, Pvl & pvl) static
Construct a valid shape model from the given target and contents of kernels group.
If the Kernels group does not have a ShapeModel or ElevationModel specified, then the default model is an ellipsoidal shape.
Parameters
target Pointer to target body model.
pvl Pvl containing a Kernels group.
Returns
ShapeModel* Pointer to the created ShapeModel object.
Author
2017-03-17 Kris Becker
References _FILEINFO_, Isis::PvlContainer::addKeyword(), Isis::IException::append(), Isis::FileName::extension(), Isis::PvlObject::findGroup(), Isis::PvlFlatMap::get(), Isis::PvlContainer::hasKeyword(), Isis::Projection::IsEquatorialCylindrical(), Isis::Target::isSky(), Isis::PvlFlatMap::merge(), Isis::Cube::open(), Isis::Cube::projection(), Isis::BulletShapeModel::setTolerance(), Isis::EmbreeShapeModel::setTolerance(), Isis::toDouble(), and Isis::toString().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ShapeModelFactory/ShapeModelFactory.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ShapeModelFactory/ShapeModelFactory.cpp