Isis Developer Reference: Isis::BundleImage Class Reference
Isis::BundleImage Class Reference
This class hold image information that BundleAdjust needs to run correctly.Definition for a BundleImageQsp, a shared pointer to a BundleImage.
#include <BundleImage.h>
Public Member Functions
BundleImage (Camera *camera, QString serialNumber, QString fileName)
Constructs a BundleImage with the given camera pointer, serial number, and filename.
BundleImage (const BundleImage &other)
Constructs a BundleImage from another BundleImage object.
~BundleImage ()
Destroys a BundleImage object.
BundleImage & operator= (const BundleImage &other)
An assignment operator to set this BundleImage to another BundleImage object.
void setParentObservation (QSharedPointer< BundleObservation > parentObservation)
Sets the parent BundleObservation object.
Camera * camera ()
Returns the camera model used for the BundleImage.
QSharedPointer< BundleObservation > parentObservation ()
Returns the parent BundleObservation object.
QString serialNumber ()
Returns the serial number for the BundleImage.
QString fileName ()
Returns the file name for the BundleImage.
Detailed Description
This class hold image information that BundleAdjust needs to run correctly.Definition for a BundleImageQsp, a shared pointer to a BundleImage.
Author
2014-05-22 Ken Edmundson
Constructor & Destructor Documentation
BundleImage() [1/2]
Isis::BundleImage::BundleImage (Camera * camera, QString serialNumber, QString fileName)
Constructs a BundleImage with the given camera pointer, serial number, and filename.
Parent observation defaults to NULL.
Parameters
camera The camera model for the BundleImage
serialNumber The serial number for the BundleImage
fileName The file name for the BundleImage
References camera(), fileName(), and serialNumber().
BundleImage() [2/2]
Isis::BundleImage::BundleImage (const BundleImage & other)
Constructs a BundleImage from another BundleImage object.
Parameters
other The BundleImage to copy from.
~BundleImage()
Isis::BundleImage::~BundleImage ()
Destroys a BundleImage object.
Member Function Documentation
camera()
Camera * Isis::BundleImage::camera ()
Returns the camera model used for the BundleImage.
Returns
Camera* A pointer to the camera model.
Referenced by BundleImage().
fileName()
QString Isis::BundleImage::fileName ()
Returns the file name for the BundleImage.
Returns
QString The image's file name.
Referenced by BundleImage().
operator=()
BundleImage & Isis::BundleImage::operator= (const BundleImage & other)
An assignment operator to set this BundleImage to another BundleImage object.
Parameters
other The BundleImage to copy from.
Returns
BundleImage& A reference to this BundleImage after being assigned to.
parentObservation()
QSharedPointer< BundleObservation > Isis::BundleImage::parentObservation ()
Returns the parent BundleObservation object.
Returns
QSharedPointer<BundleObservation> A pointer to the parent BundleObservation.
Referenced by setParentObservation().
serialNumber()
QString Isis::BundleImage::serialNumber ()
Returns the serial number for the BundleImage.
Returns
QString The image's serial number.
Referenced by BundleImage().
setParentObservation()
void Isis::BundleImage::setParentObservation (QSharedPointer< BundleObservation > parentObservation)
Sets the parent BundleObservation object.
Parameters
parentObservation The parent BundleObservation.
References parentObservation().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/BundleUtilities/BundleImage.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/BundleUtilities/BundleImage.cpp