Isis Developer Reference: Isis::MosaicAreaTool Class Reference
Isis::MosaicAreaTool Class Reference
This displays a box with a given distance from a point.
#include <MosaicAreaTool.h>
Public Slots
void userChangedBox ()
void clearBox ()
void activate (bool)
Activates the tool.
Signals
void activated (bool)
Public Member Functions
MosaicAreaTool (MosaicSceneWidget *)
MosaicAreaTool constructor.
void addToMenu (QMenu *menu)
Adds the pan action to the given menu.
PvlObject toPvl () const
void fromPvl (const PvlObject &obj)
QString projectPvlObjectName () const
bool isActive () const
Returns the activeness of this toool.
QPixmap getIcon (QString iconName) const
returns the path to the icon directory.
virtual void addTo (QMenu *menu)
virtual void addTo (ToolPad *toolPad)
virtual void addTo (QToolBar *toolBar)
virtual QList< QAction * > getViewActions ()
Protected Slots
virtual void updateTool ()
Protected Member Functions
QAction * getPrimaryAction ()
Adds the action to the toolpad.
QWidget * getToolBarWidget ()
This method returns a widget that will be put in a tool bar when the tool is activated.
QWidget * createToolBarWidget ()
Creates the widget to add to the tool bar.
void mouseButtonRelease (QPointF, Qt::MouseButton)
virtual void mouseEnter ()
virtual void mouseMove (QPointF)
virtual void mouseLeave ()
virtual void mouseDoubleClick (QPointF)
virtual void mouseButtonPress (QPointF, Qt::MouseButton s)
virtual void mouseWheel (QPointF, int delta)
virtual void rubberBandComplete (QRectF r, Qt::MouseButton s)
void toolBarDestroyed (QObject *obj)
MosaicSceneWidget * getWidget ()
Detailed Description
This displays a box with a given distance from a point.
Author
????-??-?? Steven Lambright
Constructor & Destructor Documentation
MosaicAreaTool()
Isis::MosaicAreaTool::MosaicAreaTool (MosaicSceneWidget * scene)
MosaicAreaTool constructor.
Parameters
parent
References userChangedBox().
Member Function Documentation
activate
void Isis::MosaicTool::activate (bool on) slot inherited
Activates the tool.
Parameters
on
References Isis::MosaicTool::activated().
Referenced by Isis::MosaicTool::addTo().
activated
void Isis::MosaicTool::activated (bool) signal inherited
Referenced by Isis::MosaicTool::activate(), Isis::MosaicGridTool::getToolBarWidget(), and Isis::MosaicTool::MosaicTool().
addTo() [1/3]
virtual void Isis::MosaicTool::addTo (QMenu * menu) inline virtual inherited
Referenced by Isis::MosaicSceneWidget::addTo(), Isis::MosaicSceneWidget::getControlNetHelp(), and Isis::MosaicSceneWidget::getGridHelp().
addTo() [2/3]
void Isis::MosaicTool::addTo (QToolBar * toolBar) virtual inherited
References Isis::MosaicTool::getToolBarWidget(), and Isis::MosaicTool::toolBarDestroyed().
addTo() [3/3]
void Isis::MosaicTool::addTo (ToolPad * toolPad) virtual inherited
References Isis::MosaicTool::activate(), Isis::ToolPad::addAction(), and Isis::MosaicTool::getPrimaryAction().
addToMenu()
void Isis::MosaicAreaTool::addToMenu (QMenu * menu)
Adds the pan action to the given menu.
Parameters
menu
clearBox
void Isis::MosaicAreaTool::clearBox () slot
References Isis::MosaicSceneWidget::getScene(), and Isis::MosaicTool::getWidget().
Referenced by getToolBarWidget(), mouseButtonRelease(), and userChangedBox().
createToolBarWidget()
QWidget * Isis::MosaicAreaTool::createToolBarWidget () protected
Creates the widget to add to the tool bar.
Parameters
parent
Returns
QWidget*
fromPvl()
void Isis::MosaicAreaTool::fromPvl (const PvlObject & obj) virtual
Reimplemented from Isis::MosaicTool.
References Isis::PvlObject::hasKeyword(), Isis::toBool(), and userChangedBox().
getIcon()
QPixmap Isis::MosaicTool::getIcon (QString iconName) const inherited
returns the path to the icon directory.
Returns
QString
References Isis::FileName::expanded().
Referenced by getPrimaryAction(), Isis::MosaicControlNetTool::getPrimaryAction(), Isis::MosaicFindTool::getPrimaryAction(), Isis::MosaicGridTool::getPrimaryAction(), Isis::MosaicPanTool::getPrimaryAction(), Isis::MosaicSelectTool::getPrimaryAction(), Isis::MosaicZoomTool::getPrimaryAction(), and Isis::MosaicZoomTool::MosaicZoomTool().
getPrimaryAction()
QAction * Isis::MosaicAreaTool::getPrimaryAction () protected virtual
Adds the action to the toolpad.
Parameters
toolpad
Returns
QAction*
Implements Isis::MosaicTool.
References Isis::MosaicTool::getIcon().
getToolBarWidget()
QWidget * Isis::MosaicAreaTool::getToolBarWidget () protected virtual
This method returns a widget that will be put in a tool bar when the tool is activated.
This method will only be called once so it can new the widget without a problem.
Reimplemented from Isis::MosaicTool.
References clearBox(), and userChangedBox().
getViewActions()
QList< QAction * > Isis::MosaicTool::getViewActions () virtual inherited
Reimplemented in Isis::MosaicZoomTool.
Referenced by Isis::MosaicSceneWidget::getViewActions().
getWidget()
MosaicSceneWidget* Isis::MosaicTool::getWidget () inline protected inherited
Referenced by Isis::MosaicGridTool::autoGrid(), clearBox(), Isis::MosaicGridTool::clearGrid(), Isis::MosaicFindTool::clearPoint(), Isis::MosaicGridTool::domainMaxLon(), Isis::MosaicGridTool::domainMinLon(), Isis::MosaicGridTool::drawGrid(), Isis::MosaicGridTool::fromPvl(), Isis::MosaicGridTool::getToolBarWidget(), Isis::MosaicFindTool::getUserGroundPoint(), Isis::MosaicGridTool::latType(), Isis::MosaicControlNetTool::loadNetwork(), Isis::MosaicGridTool::lonDomain(), Isis::MosaicControlNetTool::MosaicControlNetTool(), Isis::MosaicGridTool::MosaicGridTool(), Isis::MosaicTrackTool::MosaicTrackTool(), Isis::MosaicControlNetTool::mouseButtonRelease(), mouseButtonRelease(), Isis::MosaicFindTool::mouseButtonRelease(), Isis::MosaicZoomTool::mouseWheel(), Isis::MosaicGridTool::onCubesChanged(), Isis::MosaicGridTool::onProjectionChanged(), Isis::MosaicZoomTool::rubberBandComplete(), Isis::MosaicGridTool::sceneWidget(), Isis::MosaicGridTool::setLatExtents(), Isis::MosaicGridTool::setLonExtents(), Isis::MosaicTrackTool::updateLabels(), Isis::MosaicZoomTool::updateResolutionBox(), Isis::MosaicPanTool::updateTool(), Isis::MosaicSelectTool::updateTool(), Isis::MosaicZoomTool::updateTool(), userChangedBox(), and Isis::MosaicZoomTool::zoomFit().
isActive()
bool Isis::MosaicTool::isActive () const inline inherited
Returns the activeness of this toool.
Returns
bool
Referenced by Isis::MosaicSceneWidget::isControlNetToolActive(), Isis::MosaicControlNetTool::mouseButtonRelease(), Isis::MosaicZoomTool::mouseButtonRelease(), mouseButtonRelease(), Isis::MosaicFindTool::mouseButtonRelease(), Isis::MosaicZoomTool::rubberBandComplete(), Isis::MosaicFindTool::updateTool(), Isis::MosaicPanTool::updateTool(), Isis::MosaicSelectTool::updateTool(), and Isis::MosaicZoomTool::updateTool().
mouseButtonPress()
void Isis::MosaicTool::mouseButtonPress (QPointF , Qt::MouseButton s) protected virtual inherited
Referenced by Isis::MosaicTool::MosaicTool().
mouseButtonRelease()
void Isis::MosaicAreaTool::mouseButtonRelease (QPointF mouseLoc, Qt::MouseButton s) protected virtual
Reimplemented from Isis::MosaicTool.
References clearBox(), Isis::MosaicSceneWidget::getProjection(), Isis::MosaicSceneWidget::getView(), Isis::MosaicTool::getWidget(), Isis::MosaicTool::isActive(), Isis::TProjection::Latitude(), Isis::TProjection::Longitude(), Isis::TProjection::SetCoordinate(), and userChangedBox().
mouseDoubleClick()
void Isis::MosaicTool::mouseDoubleClick (QPointF) protected virtual inherited
Referenced by Isis::MosaicTool::MosaicTool().
mouseEnter()
virtual void Isis::MosaicTool::mouseEnter () inline protected virtual inherited
Referenced by Isis::MosaicTool::MosaicTool().
mouseLeave()
virtual void Isis::MosaicTool::mouseLeave () inline protected virtual inherited
Referenced by Isis::MosaicTool::MosaicTool().
mouseMove()
void Isis::MosaicTool::mouseMove (QPointF) protected virtual inherited
Referenced by Isis::MosaicTool::MosaicTool().
mouseWheel()
void Isis::MosaicTool::mouseWheel (QPointF , int delta) protected virtual inherited
Reimplemented in Isis::MosaicZoomTool.
Referenced by Isis::MosaicTool::MosaicTool().
projectPvlObjectName()
QString Isis::MosaicAreaTool::projectPvlObjectName () const virtual
Reimplemented from Isis::MosaicTool.
Referenced by toPvl().
rubberBandComplete()
virtual void Isis::MosaicTool::rubberBandComplete (QRectF r, Qt::MouseButton s) inline protected virtual inherited
Reimplemented in Isis::MosaicZoomTool.
Referenced by Isis::MosaicTool::MosaicTool().
toolBarDestroyed()
void Isis::MosaicTool::toolBarDestroyed (QObject * obj) protected inherited
Referenced by Isis::MosaicTool::addTo().
toPvl()
PvlObject Isis::MosaicAreaTool::toPvl () const virtual
Reimplemented from Isis::MosaicTool.
References projectPvlObjectName(), and Isis::toString().
updateTool
virtual void Isis::MosaicTool::updateTool () inline protected virtual slot inherited
Referenced by Isis::MosaicTool::MosaicTool().
userChangedBox
void Isis::MosaicAreaTool::userChangedBox () slot
References clearBox(), Isis::MosaicSceneWidget::getProjection(), Isis::MosaicSceneWidget::getScene(), Isis::MosaicSceneWidget::getView(), Isis::MosaicTool::getWidget(), Isis::Distance::Meters, Isis::Projection::projectionType(), Isis::TProjection::SetGround(), Isis::IString::ToDouble(), Isis::Projection::Triaxial, Isis::Projection::XCoord(), and Isis::Projection::YCoord().
Referenced by fromPvl(), getToolBarWidget(), MosaicAreaTool(), and mouseButtonRelease().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/MosaicAreaTool.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/MosaicAreaTool.cpp