Isis Developer Reference: Isis::ControlDisplayProperties Class Reference
Isis::ControlDisplayProperties Class Reference
This is the GUI communication mechanism for cubes.
#include <ControlDisplayProperties.h>
Public Types
enum Property { None = 0 , Color = 1 , Selected = 2 , ShowLabel = 16 }
This is a list of properties and actions that are possible.
Public Slots
void setColor (QColor newColor)
Change the color associated with this cube.
void setShowLabel (bool)
Change the visibility of the display name associated with this cube.
void setSelected (bool)
Change the selected state associated with this cube.
Signals
void propertyChanged (ControlDisplayProperties *)
void supportAdded (Property)
void propertyChanged (DisplayProperties *)
void supportAdded (int)
Public Member Functions
ControlDisplayProperties (QString displayName, QObject *parent=NULL)
ControlDisplayProperties constructor.
virtual ~ControlDisplayProperties ()
destructor
void addSupport (Property prop)
Call this with every property you support, otherwise they will not communicate properly between widgets.
bool supports (Property prop)
Support may come later, please make sure you are connected to the supportAdded signal.
QVariant getValue (Property prop) const
Get a property's associated data.
void save (QXmlStreamWriter &stream, const Project *project, FileName newProjectRoot) const
void fromPvl (const PvlObject &pvl)
PvlObject toPvl () const
Convert to Pvl for project files.
void addSupport (int property)
Call this with every property you support, otherwise they will not communicate properly between widgets.
bool supports (int property)
Support may come later, please make sure you are connected to the supportAdded signal.
QVariant getValue (int property) const
Get a property's associated data.
void setDisplayName (QString displayName)
Sets display name.
QString displayName () const
Returns the display name.
Static Public Member Functions
static QColor randomColor ()
Creates and returns a random color for the intial color of the footprint polygon.
Protected Member Functions
void setValue (int prop, QVariant value)
This is the generic mutator for properties.
Detailed Description
This is the GUI communication mechanism for cubes.
This class is the connector between various GUI interfaces for cubes. We use this to communicate shared properties that various widgets need to know/should react to in a generic way.
This is how this class is supposed to "connect" widgets:
widgetA widgetB widgetC | | | ---—DisplayProperties ----—
When a user selects a cube in widgetA, widgetB and widgetC now have a chance to also select the same cube. This applies to all shared properties. Some of the properties are actions - such as zoomFit. This also allows a widget with no zooming (such as a list) to have an option to zoom (if any of the widgets support it*) and have that option work. There is no state associated with zoomFit - it's an action connected to a signal.
The proper way to detect a cube going away is to connect to the destroyed signal (from the parent QObject). Once that is emitted you cannot call any methods on this object.
Author
2012-06-12 Ken Edmundson
Member Enumeration Documentation
Property
enum Isis::ControlDisplayProperties::Property
This is a list of properties and actions that are possible.
Enumerator
None
Null display property for bit-flag purposes.
Color
The color of the control net, default randomized (QColor)
Selected
The selection state of this control net (bool)
ShowLabel
True if the control net should show its display name (bool)
Constructor & Destructor Documentation
ControlDisplayProperties()
Isis::ControlDisplayProperties::ControlDisplayProperties (QString displayName, QObject * parent = NULL)
ControlDisplayProperties constructor.
This sets default values and constructs the object *.
Parameters
displayName The filename (fully expanded) of the object.
parent Qt parent object (this is destroyed when parent is destroyed)
References None, randomColor(), setSelected(), and setShowLabel().
~ControlDisplayProperties()
Isis::ControlDisplayProperties::~ControlDisplayProperties () virtual
destructor
Member Function Documentation
addSupport() [1/2]
void Isis::DisplayProperties::addSupport (int property) inherited
Call this with every property you support, otherwise they will not communicate properly between widgets.
Parameters
prop The property you are adding support for
References Isis::DisplayProperties::supportAdded(), and Isis::DisplayProperties::supports().
Referenced by Isis::ImageTreeWidgetItem::ImageTreeWidgetItem(), and Isis::MosaicSceneItem::MosaicSceneItem().
addSupport() [2/2]
void Isis::ControlDisplayProperties::addSupport (Property prop)
Call this with every property you support, otherwise they will not communicate properly between widgets.
Parameters
prop The property you are adding support for
References supportAdded(), and supports().
displayName()
QString Isis::DisplayProperties::displayName () const inherited
Returns the display name.
Referenced by Isis::Directory::addCnetEditorView(), Isis::MosaicSceneItem::contextMenuEvent(), Isis::DisplayProperties::DisplayProperties(), Isis::ImageTreeWidgetItem::ImageTreeWidgetItem(), Isis::Image::initFootprint(), Isis::Shape::initFootprint(), Isis::JigsawSetupDialog::JigsawSetupDialog(), Isis::MosaicSceneItem::MosaicSceneItem(), Isis::GuiCamera::operator==(), Isis::MosaicSceneItem::reproject(), save(), Isis::DisplayProperties::save(), Isis::GuiCameraDisplayProperties::save(), Isis::ShapeDisplayProperties::save(), Isis::TargetBodyDisplayProperties::save(), Isis::SensorInfoWidget::SensorInfoWidget(), Isis::DisplayProperties::setDisplayName(), Isis::ExportControlNetWorkOrder::setupExecution(), Isis::TargetInfoWidget::TargetInfoWidget(), and Isis::DisplayProperties::toPvl().
fromPvl()
void Isis::DisplayProperties::fromPvl (const PvlObject & pvl) inherited
References Isis::DisplayProperties::setDisplayName().
Referenced by Isis::Image::fromPvl(), and Isis::Shape::fromPvl().
getValue() [1/2]
QVariant Isis::DisplayProperties::getValue (int property) const inherited
Get a property's associated data.
Parameters
prop The property
Referenced by Isis::MosaicSceneItem::color(), Isis::MosaicSceneItem::cubeDisplayChanged(), Isis::MosaicSceneItem::paint(), Isis::ImageListActionWorkOrder::qualifyString(), Isis::MosaicSceneItem::reproject(), Isis::ImageTreeWidgetItem::update(), and Isis::MosaicSceneItem::updateSelection().
getValue() [2/2]
QVariant Isis::ControlDisplayProperties::getValue (Property prop) const
Get a property's associated data.
Parameters
prop The property
propertyChanged [1/2]
void Isis::ControlDisplayProperties::propertyChanged (ControlDisplayProperties *) signal
propertyChanged [2/2]
void Isis::DisplayProperties::propertyChanged (DisplayProperties *) signal inherited
Referenced by Isis::DisplayProperties::setValue().
randomColor()
QColor Isis::ControlDisplayProperties::randomColor () static
Creates and returns a random color for the intial color of the footprint polygon.
Referenced by ControlDisplayProperties().
save()
void Isis::ControlDisplayProperties::save (QXmlStreamWriter & stream, const Project * project, FileName newProjectRoot) const
References Isis::DisplayProperties::displayName(), and Isis::ReadWrite.
Referenced by Isis::Control::save().
setColor
void Isis::ControlDisplayProperties::setColor (QColor newColor) slot
Change the color associated with this cube.
setDisplayName()
void Isis::DisplayProperties::setDisplayName (QString displayName) inherited
Sets display name.
Parameters
displayName Display name of the object.
References Isis::DisplayProperties::displayName().
Referenced by Isis::DisplayProperties::fromPvl().
setSelected
void Isis::ControlDisplayProperties::setSelected (bool newValue) slot
Change the selected state associated with this cube.
References Selected.
Referenced by ControlDisplayProperties().
setShowLabel
void Isis::ControlDisplayProperties::setShowLabel (bool newValue) slot
Change the visibility of the display name associated with this cube.
References ShowLabel.
Referenced by ControlDisplayProperties().
setValue()
void Isis::DisplayProperties::setValue (int property, QVariant value) protected inherited
This is the generic mutator for properties.
Given a value, this will change it and emit propertyChanged if its different and supported.
References Isis::DisplayProperties::propertyChanged(), and Isis::DisplayProperties::supports().
Referenced by Isis::ImageDisplayProperties::ImageDisplayProperties(), Isis::ImageDisplayProperties::setColor(), Isis::ImageDisplayProperties::setSelected(), Isis::ImageDisplayProperties::setShowDNs(), Isis::ImageDisplayProperties::setShowFill(), Isis::ImageDisplayProperties::setShowLabel(), and Isis::ImageDisplayProperties::setShowOutline().
supportAdded [1/2]
void Isis::DisplayProperties::supportAdded (int) signal inherited
Referenced by Isis::DisplayProperties::addSupport().
supportAdded [2/2]
void Isis::ControlDisplayProperties::supportAdded (Property) signal
Referenced by addSupport().
supports() [1/2]
bool Isis::DisplayProperties::supports (int property) inherited
Support may come later, please make sure you are connected to the supportAdded signal.
Returns
True if the property has support, false otherwise
Referenced by Isis::DisplayProperties::addSupport(), Isis::ImageList::allSupport(), Isis::DisplayProperties::setValue(), and Isis::ImageTreeWidgetItem::update().
supports() [2/2]
bool Isis::ControlDisplayProperties::supports (Property prop)
Support may come later, please make sure you are connected to the supportAdded signal.
Returns
True if the property has support, false otherwise
Referenced by addSupport().
toPvl()
PvlObject Isis::DisplayProperties::toPvl () const inherited
Convert to Pvl for project files.
This stores all of the data associated with all of the properties (but not what is supported). This also stores the cube filename.
References Isis::DisplayProperties::displayName(), and Isis::ReadWrite.
Referenced by Isis::Image::toPvl(), and Isis::Shape::toPvl().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ControlDisplayProperties/ControlDisplayProperties.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ControlDisplayProperties/ControlDisplayProperties.cpp