Isis Developer Reference: Isis::InterestOperator Class Reference
Isis::InterestOperator Class Reference abstract
Interest Operator class.
#include <InterestOperator.h>
Public Member Functions
InterestOperator (Pvl &pPvl)
Create InterestOperator object.
virtual ~InterestOperator ()
Destroy InterestOperator object.
void InitInterestOptions ()
Initialise Interest Options to defaults.
void SetPatternValidPercent (const double percent)
void SetPatternSampling (const double percent)
void SetSearchSampling (const double percent)
void SetTolerance (double tolerance)
void SetPatternReduction (std::vector< int > samples, std::vector< int > lines)
QString operatorName () const
Return name of the matching operator.
bool Operate (Cube &pCube, UniversalGroundMap &pUnivGrndMap, int piSample, int piLine)
Operate used by the app interestcube- to calculate interest by sample,line.
void Operate (ControlNet &pNewNet, QString psSerialNumFile, QString psOverlapListFile="")
Operate - to calculate interest for entire control net to get better reference.
double InterestAmount () const
Return the Interest Amount.
double WorstInterest () const
Return the Worst(least value) Interest.
double CubeSample () const
Return the search chip cube sample that best matched.
double CubeLine () const
Return the search chip cube line that best matched.
virtual bool CompareInterests (double int1, double int2)
Compare for int1 greater than / equal to int2.
void addGroup (Isis::PvlObject &obj)
void SetClipPolygon (const geos::geom::MultiPolygon &clipPolygon)
Set the Clip Polygon for points to be contained in the overlaps.
Isis::PvlGroup Operator ()
Return the Operator name.
void InitStdOptions (void)
Initialize the Standard Options.
void InitStdOptionsGroup (void)
Initialize the Standard Options Pvl Group with no DefFile.
virtual Pvl & GetLogPvl (void)
Get the Pvl Log file.
bool ValidEmissionAngle (double pdEmissionAngle)
Validate whether the Emission Angle is in the set Range.
bool ValidIncidenceAngle (double pdIncidenceAngle)
Validate whether the Incidence Angle is in the set Range.
bool ValidDnValue (double pdDnValue)
Validate whether the DN Value is in the set Range.
bool ValidResolution (double pdResolution)
Validate whether the Resolution is in the set Range.
bool ValidResidualTolerances (double pdSampleResidual, double pdLineResidual, double pdResidualMagnitude, MeasureValidationResults &pResults)
Validate whether the Residuals are within the set Tolerance.
bool ValidShiftTolerances (double sampleShift, double lineShift, double pixelShift, MeasureValidationResults &results)
Validate whether the Sample and Line Shifts and Pixel Shift are within the set Tolerances.
bool ValidLatLon (Isis::Camera *pCamera, int piSample, int piLine)
Validate the Lat/Lon.
PvlGroup & GetStdOptions (void)
Get the Standard Options Pvl Group.
PvlGroup & GetStatistics (void)
Get the Statistics Pvl Grp.
double GetMinDN (void)
Get the option MinDN.
double GetMaxDN (void)
Get the option MaxDN.
double GetMinEmissionAngle (void)
Get the option MinEmissionAngle.
double GetMaxEmissionAngle (void)
Get the option MaxEmissionAngle.
double GetMinIncidenceAngle (void)
Get the option MinIncidenceAngle.
double GetMaxIncidenceAngle (void)
Get the option MaxIncidenceAngle.
double GetPixelsFromEdge (void)
Get the option PixelsFromEdge.
double GetMetersFromEdge (void)
Get the option MetersFromEdge.
QString LocationString (double pdSample, double pdLine) const
API to display location in the form "Sample,Line".
bool PixelsFromEdge (int piSample, int piLine, Cube *pCube)
Test for a point to be user defined number of pixels from the edge.
bool MetersFromEdge (int piSample, int piLine, Cube *pCube)
Test for a point to be user defined number of meters from the edge.
MeasureValidationResults ValidStandardOptions (const ControlMeasure *pMeasure, Cube *pCube, PvlGroup *pMeasureGrp=NULL)
Validate Standard options to pick a reference based on a particular criteria.
MeasureValidationResults ValidStandardOptions (const ControlMeasure *pMeasure, Cube *pCube, Camera *camera, PvlGroup *pMeasureGrp=NULL)
Validate Standard options to pick a reference based on a particular criteria.
MeasureValidationResults ValidStandardOptions (double pSample, double pLine, const ControlMeasure *pMeasure, Cube *pCube, PvlGroup *pMeasureGrp=NULL)
Validate Standard options to pick a reference based on a particular criteria.
MeasureValidationResults ValidStandardOptions (double pSample, double pLine, const ControlMeasure *pMeasure, Cube *pCube, Camera *measureCamera, PvlGroup *pMeasureGrp=NULL)
MeasureValidationResults ValidStandardOptions (double pSample, double pLine, Cube *pCube, PvlGroup *pMeasureGrp=NULL)
Validate Standard options to pick a reference based on a particular criteria.
bool IsCubeRequired ()
bool IsCameraRequired ()
API to get status of CameraRequired flag.
Protected Member Functions
void Parse (Pvl &pPvl)
Parse the Interest specific keywords.
virtual double Interest (Chip &subCube)=0
Calculate the interest.
const geos::geom::MultiPolygon * FindOverlap (Isis::ControlPoint &pCnetPoint)
Find if a point is in the overlap.
const geos::geom::MultiPolygon * FindOverlapByImageFootPrint (Isis::ControlPoint &pCnetPoint)
Find imageoverlaps by finding the intersection of image footprints.
void FindCnetRef (ControlNet &pNewNet)
Find best ref for an entire control net by calculating the interest and moving point to a better interest area.
void ProcessLocked_Point_Reference (ControlPoint &pCPoint, PvlObject &pPvlObj, int &piMeasuresModified)
Process (Validate and Log) Point with Lock or with Referemce Measure Locked.
int InterestByPoint (ControlPoint &pCnetPoint)
Calculate interest for a Control Point.
bool InterestByMeasure (int piMeasure, Isis::ControlMeasure &pCnetMeasure, Isis::Cube &pCube)
Calculate interest for a measure by index.
void InitInterestResults (int piIndex)
Init Interest Results structure.
virtual int Padding ()
Sets an offset to pass in larger chips if operator requires it This is used to offset the subchip size passed into Interest.
void ValidatePvlDN (void)
Validate PVL Min & Max DN Standard Options.
void ValidatePvlEmissionAngle (void)
Validate PVL Min & Max EmissionAngle Standard Options.
void ValidatePvlIncidenceAngle (void)
Validate PVL Min & Max IncidenceAngle Standard Options.
void ValidatePvlResolution (void)
Validate PVL Min & Max Resolution Standard Options.
void ValidatePvlFromEdge (void)
Validate and read Pixels and Meters from Edge Standard Options.
void ValidatePvlResidualTolerances (void)
Validate Pvl Sample, Line, Residual Magnitude Tolerances.
void ValidatePvlShiftTolerances ()
Validate Pvl Sample, Line, Pixel (Sample and Line) Magnitude Shift Tolerances.
void ReadSerialNumbers (QString psSerialNumfile)
Read the Serial Numbers from the file and open assocaited cubes.
void SetCameraRequiredFlag (bool pbFlag)
Set the CameraRequired Flag.
Protected Attributes
double p_worstInterest
double p_interestAmount
geos::geom::MultiPolygon * p_clipPolygon
Clipping polygon set by SetClipPolygon (line,samp)
Isis::PvlGroup mOperatorGrp
Operator group that created this projection.
double mdMinDN
Standard Option MinDN.
double mdMaxDN
Standard Option MaxDN.
double mdMinResolution
Standard Option MinResolution.
double mdMaxResolution
Standard Option MaxResolution.
double mdMinEmissionAngle
Standard Option MinEmissionAngle.
double mdMaxEmissionAngle
Standard Option MaxEmissionAngle.
double mdMinIncidenceAngle
Standard Option MinIncidenceAngle.
double mdMaxIncidenceAngle
Standard Option MaxIncidenceAngle.
double mdMetersFromEdge
Standard Option MeteresFromEdge.
int miPixelsFromEdge
Standard Option PixelsFromEdge.
double mdSampleResTolerance
Standard Option Sample Residual.
double mdLineResTolerance
Standard Option Line Residual.
double mdResidualTolerance
Standard Option Residual Magnitude.
double m_sampleShiftTolerance
Standard Option Sample Shift.
double m_lineShiftTolerance
Standard Option Line Shift.
double m_pixelShiftTolerance
Standard Option Pixel Shift.
double mdEmissionAngle
Store current Measure's Emission Angle.
double mdIncidenceAngle
Store current Measure's Incidence Angle.
double mdResolution
Store current Measure's Resolution.
double mdDnValue
Store current Measure's DN Value.
double mdSampleResidual
Store current Measure's Sample Residual.
double mdLineResidual
Store current Measure's Line Residual.
double mdResidualMagnitude
Store current Measure's Residual Magnitude.
double m_sampleShift
Store current Measure's Sample Shift.
double m_lineShift
Store current Measure's Line Shift.
double m_pixelShift
Store current Measure's Pixel Shift.
PvlGroup mPvlOpGrp
Pvl Operator Group.
PvlGroup mStdOptionsGrp
Pvl Standard Options Group.
PvlGroup mStatisticsGrp
Pvl output Statistics Group.
Pvl mPvlLog
Pvl Log of all the processing.
Progress mStatus
Monitor the status of the app.
CubeManager mCubeMgr
CubeManager to open and read cubes.
SerialNumberList mSerialNumbers
Serial numbers list.
bool mbCameraRequired
To improve speed, flag to indicate if Camera needs to be opened.
bool mbValidateDN
Check if DN needs to be Validated.
bool mbValidateFromEdge
Check if Pixels/Meters from edge needs to be Validated.
Detailed Description
Interest Operator class.
Create InterestOperator object. Because this is a pure virtual class you can not create an InterestOperator class directly. Instead, see the InterestOperatorFactory class.
See also
StandardDeviationOperator GradientOperator
Author
2006-02-11 Jacob Danton
Constructor & Destructor Documentation
InterestOperator()
Isis::InterestOperator::InterestOperator (Pvl & pPvl)
Create InterestOperator object.
Because this is a pure virtual class you can not create an InterestOperator class directly. Instead, see the InterestOperatorFactory class.
Parameters
pvl A pvl object containing a valid InterestOperator specification
References InitInterestOptions(), mOperatorGrp, and Parse().
~InterestOperator()
Isis::InterestOperator::~InterestOperator () virtual
Destroy InterestOperator object.
References p_clipPolygon.
Member Function Documentation
addGroup()
void Isis::InterestOperator::addGroup (Isis::PvlObject & obj)
References Isis::PvlObject::addGroup().
CompareInterests()
bool Isis::InterestOperator::CompareInterests (double int1, double int2) virtual
Compare for int1 greater than / equal to int2.
This virtual method must return if the 1st fit is equal to or better than the second fit.
Parameters
int1 1st interestAmount
int2 2nd interestAmount
Referenced by InterestByMeasure(), InterestByPoint(), and Operate().
CubeLine()
double Isis::InterestOperator::CubeLine () const inline
Return the search chip cube line that best matched.
CubeSample()
double Isis::InterestOperator::CubeSample () const inline
Return the search chip cube sample that best matched.
FindCnetRef()
void Isis::InterestOperator::FindCnetRef (ControlNet & pNewNet) protected virtual
Find best ref for an entire control net by calculating the interest and moving point to a better interest area.
This traverses all the control points and measures in the network and checks for valid Measure which passes the Emission Incidence Angle, DN value tests and picks the Measure with the best Interest as the Reference.
Author
Sharmila Prasad (5/14/2010)
Parameters
pNewNet - Input Control Net
History:
2010-07-13 Tracie Sucharski, Changes for binary control networks, Measure type of Estimated is now Candidate and instead of a separate keyword indicating whether a meausre is the reference, the MeasureType is set to Reference.
2010-10-04 Sharmila Prasad - Modified for binary Control Net ex Edit Lock
2010-10-15 Sharmila Prasad - Use only a single copy of Control Net
Returns
none
Reimplemented from Isis::ControlNetValidMeasure.
References _FILEINFO_, Isis::Cube::camera(), Isis::ControlMeasure::Candidate, Isis::Progress::CheckStatus(), Isis::ControlPoint::Constrained, Isis::SerialNumberList::fileName(), Isis::ControlPoint::Fixed, Isis::ControlPoint::Free, Isis::ControlPoint::GetAprioriSurfacePointSource(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::ControlPoint::GetId(), Isis::ControlMeasure::GetLine(), Isis::ControlPoint::GetMeasure(), Isis::ControlPoint::GetNumLockedMeasures(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlNet::GetNumPoints(), Isis::ControlNet::GetPoint(), Isis::ControlPoint::GetRefMeasure(), Isis::ControlMeasure::GetSample(), Isis::ControlPoint::GetType(), Isis::Camera::InCube(), Isis::ControlPoint::IndexOfRefMeasure(), InterestByPoint(), Isis::ControlMeasure::IsEditLocked(), Isis::ControlPoint::IsEditLocked(), Isis::ControlMeasure::IsIgnored(), Isis::ControlPoint::IsIgnored(), Isis::MeasureValidationResults::isValid(), Isis::Camera::Line(), Isis::ControlNetValidMeasure::LocationString(), Isis::ControlNetValidMeasure::mCubeMgr, Isis::ControlNetValidMeasure::mdResolution, Isis::ControlNetValidMeasure::mPvlLog, Isis::ControlNetValidMeasure::mSerialNumbers, Isis::ControlNetValidMeasure::mStatisticsGrp, Isis::ControlNetValidMeasure::mStatus, Isis::CubeManager::OpenCube(), ProcessLocked_Point_Reference(), Isis::ControlPoint::SurfacePointSource::Reference, Isis::Camera::Sample(), Isis::ControlMeasure::SetChooserName(), Isis::ControlMeasure::SetCoordinate(), Isis::ControlMeasure::SetDateTime(), Isis::ControlMeasure::SetIgnored(), Isis::ControlPoint::SetIgnored(), Isis::Camera::SetImage(), Isis::Progress::SetMaximumSteps(), Isis::ControlPoint::SetRefMeasure(), Isis::Progress::SetText(), Isis::ControlMeasure::SetType(), Isis::Camera::SetUniversalGround(), Isis::MeasureValidationResults::toString(), Isis::toString(), Isis::Sensor::UniversalLatitude(), Isis::Sensor::UniversalLongitude(), Isis::IException::User, Isis::ControlNetValidMeasure::ValidStandardOptions(), and WorstInterest().
Referenced by Operate().
FindOverlap()
const geos::geom::MultiPolygon * Isis::InterestOperator::FindOverlap (Isis::ControlPoint & pCnetPoint) protected
Find if a point is in the overlap.
This method searches for an overlap in the ImageOverlapSet that belongs to the given control point.
Only exact SN matches are accepted.
References FindOverlapByImageFootPrint(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::ControlPoint::GetNumMeasures(), Isis::ImageOverlap::HasSerialNumber(), Isis::ImageOverlapSet::Size(), and Isis::ImageOverlap::Size().
Referenced by InterestByPoint().
FindOverlapByImageFootPrint()
const geos::geom::MultiPolygon * Isis::InterestOperator::FindOverlapByImageFootPrint (Isis::ControlPoint & pCnetPoint) protected
Find imageoverlaps by finding the intersection of image footprints.
Find image overlaps by getting intersection of the individual image footprints when an exact match in the overlaplist fails.
Author
Sharmila Prasad (7/1/2010)
Parameters
pCnetPoint - Overlaps for the Control Point
Returns
const geos::geom::MultiPolygon*
References Isis::SerialNumberList::fileName(), Isis::ControlPoint::GetNumMeasures(), Isis::PolygonTools::Intersect(), Isis::PolygonTools::MakeMultiPolygon(), Isis::ControlNetValidMeasure::mCubeMgr, Isis::ControlNetValidMeasure::mSerialNumbers, Isis::CubeManager::OpenCube(), Isis::ImagePolygon::Polys(), and Isis::Cube::read().
Referenced by FindOverlap().
GetLogPvl()
virtual Pvl& Isis::ControlNetValidMeasure::GetLogPvl (void) inline virtual inherited
Get the Pvl Log file.
References Isis::ControlNetValidMeasure::mPvlLog.
GetMaxDN()
double Isis::ControlNetValidMeasure::GetMaxDN (void) inline inherited
Get the option MaxDN.
References Isis::ControlNetValidMeasure::mdMaxDN.
GetMaxEmissionAngle()
double Isis::ControlNetValidMeasure::GetMaxEmissionAngle (void) inline inherited
Get the option MaxEmissionAngle.
References Isis::ControlNetValidMeasure::mdMaxEmissionAngle.
GetMaxIncidenceAngle()
double Isis::ControlNetValidMeasure::GetMaxIncidenceAngle (void) inline inherited
Get the option MaxIncidenceAngle.
References Isis::ControlNetValidMeasure::mdMaxIncidenceAngle.
GetMetersFromEdge()
double Isis::ControlNetValidMeasure::GetMetersFromEdge (void) inline inherited
Get the option MetersFromEdge.
References Isis::ControlNetValidMeasure::mdMetersFromEdge.
GetMinDN()
double Isis::ControlNetValidMeasure::GetMinDN (void) inline inherited
Get the option MinDN.
References Isis::ControlNetValidMeasure::mdMinDN.
GetMinEmissionAngle()
double Isis::ControlNetValidMeasure::GetMinEmissionAngle (void) inline inherited
Get the option MinEmissionAngle.
References Isis::ControlNetValidMeasure::mdMinEmissionAngle.
GetMinIncidenceAngle()
double Isis::ControlNetValidMeasure::GetMinIncidenceAngle (void) inline inherited
Get the option MinIncidenceAngle.
References Isis::ControlNetValidMeasure::mdMinIncidenceAngle.
GetPixelsFromEdge()
double Isis::ControlNetValidMeasure::GetPixelsFromEdge (void) inline inherited
Get the option PixelsFromEdge.
References Isis::ControlNetValidMeasure::miPixelsFromEdge.
GetStatistics()
PvlGroup& Isis::ControlNetValidMeasure::GetStatistics (void) inline inherited
Get the Statistics Pvl Grp.
References Isis::ControlNetValidMeasure::mStatisticsGrp.
GetStdOptions()
PvlGroup& Isis::ControlNetValidMeasure::GetStdOptions (void) inline inherited
Get the Standard Options Pvl Group.
References Isis::ControlNetValidMeasure::mStdOptionsGrp.
InitInterestOptions()
void Isis::InterestOperator::InitInterestOptions ()
Initialise Interest Options to defaults.
Author
Sharmila Prasad (11/21/2011)
References p_clipPolygon, p_interestAmount, and p_worstInterest.
Referenced by InterestOperator().
InitInterestResults()
void Isis::InterestOperator::InitInterestResults (int piIndex) protected
Init Interest Results structure.
Initialise the InterestResults structure given the index.
Author
Sharmila Prasad (6/8/2010)
Parameters
piIndex - Index for the Interest Results structure
References Isis::Null, and Isis::ValidMinimum.
Referenced by InterestByPoint().
InitStdOptions()
void Isis::ControlNetValidMeasure::InitStdOptions (void) inherited
Initialize the Standard Options.
Init all the standard options to default.
Author
Sharmila Prasad (6/8/2010)
References Isis::ControlNetValidMeasure::m_lineShiftTolerance, Isis::ControlNetValidMeasure::m_pixelShiftTolerance, Isis::ControlNetValidMeasure::m_sampleShiftTolerance, Isis::ControlNetValidMeasure::mbCameraRequired, Isis::ControlNetValidMeasure::mbValidateDN, Isis::ControlNetValidMeasure::mbValidateFromEdge, Isis::ControlNetValidMeasure::mdLineResTolerance, Isis::ControlNetValidMeasure::mdMaxDN, Isis::ControlNetValidMeasure::mdMaxEmissionAngle, Isis::ControlNetValidMeasure::mdMaxIncidenceAngle, Isis::ControlNetValidMeasure::mdMaxResolution, Isis::ControlNetValidMeasure::mdMetersFromEdge, Isis::ControlNetValidMeasure::mdMinDN, Isis::ControlNetValidMeasure::mdMinEmissionAngle, Isis::ControlNetValidMeasure::mdMinIncidenceAngle, Isis::ControlNetValidMeasure::mdMinResolution, Isis::ControlNetValidMeasure::mdResidualTolerance, Isis::ControlNetValidMeasure::mdSampleResTolerance, Isis::ControlNetValidMeasure::miPixelsFromEdge, Isis::ValidMaximum, and Isis::ValidMinimum.
Referenced by Isis::ControlNetValidMeasure::ControlNetValidMeasure().
InitStdOptionsGroup()
void Isis::ControlNetValidMeasure::InitStdOptionsGroup (void) inherited
Initialize the Standard Options Pvl Group with no DefFile.
Set the Standard Options group for logging.
Author
Sharmila Prasad (6/8/2010)
References Isis::ControlNetValidMeasure::m_lineShiftTolerance, Isis::ControlNetValidMeasure::m_pixelShiftTolerance, Isis::ControlNetValidMeasure::m_sampleShiftTolerance, Isis::ControlNetValidMeasure::mdLineResTolerance, Isis::ControlNetValidMeasure::mdMaxDN, Isis::ControlNetValidMeasure::mdMaxEmissionAngle, Isis::ControlNetValidMeasure::mdMaxIncidenceAngle, Isis::ControlNetValidMeasure::mdMaxResolution, Isis::ControlNetValidMeasure::mdMetersFromEdge, Isis::ControlNetValidMeasure::mdMinDN, Isis::ControlNetValidMeasure::mdMinEmissionAngle, Isis::ControlNetValidMeasure::mdMinIncidenceAngle, Isis::ControlNetValidMeasure::mdMinResolution, Isis::ControlNetValidMeasure::mdResidualTolerance, Isis::ControlNetValidMeasure::mdSampleResTolerance, Isis::ControlNetValidMeasure::miPixelsFromEdge, Isis::ControlNetValidMeasure::mStdOptionsGrp, Isis::toString(), Isis::ValidMaximum, and Isis::ValidMinimum.
Referenced by Isis::ControlNetValidMeasure::ControlNetValidMeasure().
Interest()
virtual double Isis::InterestOperator::Interest (Chip & subCube) protected pure virtual
Calculate the interest.
Implemented in Isis::StandardDeviationOperator, Isis::NoOperator, Isis::MoravecOperator, Isis::GradientOperator, and Isis::ForstnerOperator.
Referenced by InterestByMeasure(), and Operate().
InterestAmount()
double Isis::InterestOperator::InterestAmount () const inline
Return the Interest Amount.
References p_interestAmount.
InterestByMeasure()
bool Isis::InterestOperator::InterestByMeasure (int piMeasure, Isis::ControlMeasure & pCnetMeasure, Isis::Cube & pCube) protected
Calculate interest for a measure by index.
Find the interest by Measure given the index to store the results in the InterestResults structure.
Author
Sharmila Prasad (6/10/2010)
Parameters
piMeasure - Index for Interest Results structure
pCnetMeasure - Control Measure for which the best interest is calculated
pCube - Measure Cube
Returns
bool
References _FILEINFO_, Isis::Cube::camera(), CompareInterests(), Isis::Chip::CubeLine(), Isis::Chip::CubeSample(), Isis::Sensor::EmissionAngle(), Isis::Chip::Extract(), Isis::SerialNumberList::fileName(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::ControlMeasure::GetLine(), Isis::ControlMeasure::GetSample(), Isis::Sensor::IncidenceAngle(), Interest(), Isis::MeasureValidationResults::isValid(), Isis::Chip::Load(), Isis::ControlNetValidMeasure::mdDnValue, Isis::ControlNetValidMeasure::mdEmissionAngle, Isis::ControlNetValidMeasure::mdIncidenceAngle, Isis::ControlNetValidMeasure::mdResolution, Isis::ControlNetValidMeasure::mSerialNumbers, Isis::Null, p_clipPolygon, Padding(), Isis::Camera::PixelResolution(), Isis::Cube::pixelType(), Isis::Cube::read(), Isis::Chip::SetChipPosition(), Isis::Chip::SetClipPolygon(), Isis::Camera::SetImage(), Isis::Portal::SetPosition(), Isis::Chip::TackCube(), Isis::IException::User, and Isis::ControlNetValidMeasure::ValidStandardOptions().
Referenced by InterestByPoint().
InterestByPoint()
int Isis::InterestOperator::InterestByPoint (ControlPoint & pCnetPoint) protected
Calculate interest for a Control Point.
InterestByPoint - Find the interest of all measures in a Point and store all the results in Interest Results structure.
Author
Sharmila Prasad (6/8/2010)
Parameters
pCnetPoint - Control Point for which the best interest is calculated
References _FILEINFO_, CompareInterests(), Isis::SerialNumberList::fileName(), FindOverlap(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::ControlPoint::GetId(), Isis::ControlPoint::GetNumMeasures(), InitInterestResults(), InterestByMeasure(), Isis::ControlMeasure::IsIgnored(), Isis::PolygonTools::LatLonToSampleLine(), Isis::ControlNetValidMeasure::mCubeMgr, Isis::ControlNetValidMeasure::mSerialNumbers, Isis::Null, Isis::CubeManager::OpenCube(), SetClipPolygon(), and Isis::IException::User.
Referenced by FindCnetRef().
IsCameraRequired()
bool Isis::ControlNetValidMeasure::IsCameraRequired () inline inherited
API to get status of CameraRequired flag.
Author
Sharmila Prasad (5/19/2011)
Returns
bool
References Isis::ControlNetValidMeasure::mbCameraRequired.
Referenced by Isis::ControlNetValidMeasure::IsCubeRequired().
IsCubeRequired()
bool Isis::ControlNetValidMeasure::IsCubeRequired () inline inherited
References Isis::ControlNetValidMeasure::IsCameraRequired(), Isis::ControlNetValidMeasure::mbValidateDN, and Isis::ControlNetValidMeasure::mbValidateFromEdge.
LocationString()
QString Isis::ControlNetValidMeasure::LocationString (double pdSample, double pdLine) const inline inherited
API to display location in the form "Sample,Line".
References Isis::toString().
Referenced by FindCnetRef(), and ProcessLocked_Point_Reference().
MetersFromEdge()
bool Isis::ControlNetValidMeasure::MetersFromEdge (int piSample, int piLine, Cube * pCube) inherited
Test for a point to be user defined number of meters from the edge.
Validate if a point in Measure is user defined number of meters from the edge.
Author
Sharmila Prasad (6/21/2010)
Parameters
piSample - Point Sample Location
piLine - Point Line Location
pCube - Control Measure Cube
Returns
bool
References _FILEINFO_, Isis::Cube::camera(), Isis::Cube::fileName(), Isis::Cube::lineCount(), Isis::ControlNetValidMeasure::mdMetersFromEdge, Isis::Camera::PixelResolution(), Isis::Cube::sampleCount(), Isis::Camera::SetImage(), and Isis::IException::User.
Referenced by Isis::ControlNetValidMeasure::ValidStandardOptions().
Operate() [1/2]
void Isis::InterestOperator::Operate (ControlNet & pNewNet, QString psSerialNumFile, QString psOverlapListFile = "")
Operate - to calculate interest for entire control net to get better reference.
Read the Serial#'s and overlaplist if any and call API to find the reference for all the points in the network.
Author
Sharmila Prasad (6/9/2010)
Parameters
pNewNet - Input Control Net
psSerialNumFile - Serial Number File
psOverlapListFile - Overlaplist File containing overlap data
History:
10/15/2010 Sharmila Prasad - Use a single copy of Control Net
References FindCnetRef(), Isis::ImageOverlapSet::ReadImageOverlaps(), and Isis::ControlNetValidMeasure::ReadSerialNumbers().
Operate() [2/2]
bool Isis::InterestOperator::Operate (Cube & pCube, UniversalGroundMap & pUnivGrndMap, int piSample, int piLine)
Operate used by the app interestcube- to calculate interest by sample,line.
Walk the pattern chip through the search chip to find the best interest.
Parameters
cube [in] The Isis::Cube to look for an interesting area in
piSample [in] The sample postion in the cube where the chip is located
piLine [in] The line postion in the cube where the chip is located
pUnivGrndMap Reference to the Universal Ground map of this image
Returns
Returns the status of the operation. The following conditions can occur true=Success, false=Failed
History:
2010-03-30 Sharmila Prasad - Check for valid DN Value and Emission Angle in the user defined ValidMin-ValidMax range when selecting point of interest in a Control Measure
2010-06-23 Sharmila Prasad - Validate for Resolution Range and Pixels/Meters from edge options
2016-08-24 Kelvin Rodriguez - Changed calls to abs to qAbs to squash implicit conversion warnings in clang. Part of porting to OS X 10.11.
References _FILEINFO_, CompareInterests(), Isis::Chip::CubeLine(), Isis::Chip::CubeSample(), Isis::Chip::Extract(), Isis::Cube::fileName(), Isis::UniversalGroundMap::HasCamera(), Interest(), Isis::MeasureValidationResults::isValid(), Isis::Chip::Load(), Isis::Null, p_clipPolygon, p_interestAmount, Padding(), Isis::IException::Programmer, Isis::Chip::SetChipPosition(), Isis::Chip::SetClipPolygon(), Isis::UniversalGroundMap::SetImage(), Isis::Chip::TackCube(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
Operator()
PvlGroup Isis::InterestOperator::Operator ()
Return the Operator name.
This function returns the keywords that this object was created from.
Returns
PvlGroup The keywords this object used in initialization
References mOperatorGrp.
operatorName()
QString Isis::InterestOperator::operatorName () const inline
Return name of the matching operator.
References mOperatorGrp.
Padding()
int Isis::InterestOperator::Padding () protected virtual
Sets an offset to pass in larger chips if operator requires it This is used to offset the subchip size passed into Interest.
Returns
int Amount to add to both x & y total sizes
Reimplemented in Isis::MoravecOperator.
Referenced by InterestByMeasure(), and Operate().
Parse()
void Isis::InterestOperator::Parse (Pvl & pPvl) protected
Parse the Interest specific keywords.
Create an InterestOperator object using a PVL specification.
An example of the PVL required for this is:
Group = Operator
  Name      = StandardDeviation
  Samples   = 21
  Lines     = 21
  DeltaLine = 50
  DeltaSamp = 25
EndGroup
There are many other options that can be set via the pvl and are described in other documentation (see below).
Parameters
pvl The pvl object containing the specification
History:
2010-04-09 Sharmila Prasad Check for validity of new keyword "MaxEmissionAngle"
2010-06-10 Sharmila Prasad Parse only Interest specific keywords and store in Operator group
References _FILEINFO_, Isis::PvlContainer::fileName(), Isis::PvlObject::findGroup(), mOperatorGrp, Isis::toString(), Isis::PvlObject::Traverse, and Isis::IException::User.
Referenced by InterestOperator().
PixelsFromEdge()
bool Isis::ControlNetValidMeasure::PixelsFromEdge (int piSample, int piLine, Cube * pCube) inherited
Test for a point to be user defined number of pixels from the edge.
Validate if a point in Measure is user defined number of pixels from the edge.
Author
Sharmila Prasad (6/21/2010)
Parameters
piSample - Point Sample Location
piLine - Point Line Location
pCube - Control Measure Cube
Returns
bool
References Isis::Cube::lineCount(), Isis::ControlNetValidMeasure::miPixelsFromEdge, and Isis::Cube::sampleCount().
Referenced by Isis::ControlNetValidMeasure::ValidStandardOptions().
ProcessLocked_Point_Reference()
void Isis::InterestOperator::ProcessLocked_Point_Reference (ControlPoint & pCPoint, PvlObject & pPvlObj, int & piMeasuresModified) protected
Process (Validate and Log) Point with Lock or with Referemce Measure Locked.
Process a Control Point which is Locked or has the Reference Measure locked.
Author
Sharmila Prasad (10/5/2010)
Parameters
pCPoint - Control Point wtih the Locks(s)
pPvlObj - Output log Pvl
References Isis::SerialNumberList::fileName(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::ControlMeasure::GetLine(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlMeasure::GetSample(), Isis::ControlMeasure::IsEditLocked(), Isis::ControlPoint::IsEditLocked(), Isis::ControlMeasure::IsIgnored(), Isis::MeasureValidationResults::isValid(), Isis::ControlNetValidMeasure::LocationString(), Isis::ControlNetValidMeasure::mCubeMgr, Isis::ControlNetValidMeasure::mSerialNumbers, Isis::CubeManager::OpenCube(), Isis::ControlMeasure::SetChooserName(), Isis::ControlMeasure::SetDateTime(), Isis::ControlMeasure::SetIgnored(), Isis::ControlPoint::SetIgnored(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
Referenced by FindCnetRef().
ReadSerialNumbers()
void Isis::ControlNetValidMeasure::ReadSerialNumbers (QString psSerialNumfile) protected inherited
Read the Serial Numbers from the file and open assocaited cubes.
Read Serial Numbers from specified file and populate the Cube and UniversalGround Maps using the serial numbers.
Author
Sharmila Prasad (6/3/2010)
Parameters
psSerialNumfile - File with list of Serial Numbers
References Isis::ControlNetValidMeasure::mCubeMgr, Isis::ControlNetValidMeasure::mSerialNumbers, Isis::ControlNetValidMeasure::mStatus, and Isis::CubeManager::SetNumOpenCubes().
Referenced by Operate().
SetCameraRequiredFlag()
void Isis::ControlNetValidMeasure::SetCameraRequiredFlag (bool pbFlag) inline protected inherited
Set the CameraRequired Flag.
This flag indicates whether a camera is required to Validate a Control Measure. Camera is required to get Emission, Incidence angles and Resolution
Author
Sharmila Prasad (5/19/2011)
Parameters
pbFlag
References Isis::ControlNetValidMeasure::mbCameraRequired.
SetClipPolygon()
void Isis::InterestOperator::SetClipPolygon (const geos::geom::MultiPolygon & clipPolygon)
Set the Clip Polygon for points to be contained in the overlaps.
Sets the clipping polygon for the chip.
The coordinates must be in (sample,line) order.
Parameters
clipPolygon The polygons used to clip the chip
References Isis::PolygonTools::CopyMultiPolygon(), and p_clipPolygon.
Referenced by InterestByPoint().
SetPatternReduction()
void Isis::InterestOperator::SetPatternReduction (std::vector< int > samples, std::vector< int > lines)
SetPatternSampling()
void Isis::InterestOperator::SetPatternSampling (const double percent)
SetPatternValidPercent()
void Isis::InterestOperator::SetPatternValidPercent (const double percent)
SetSearchSampling()
void Isis::InterestOperator::SetSearchSampling (const double percent)
SetTolerance()
void Isis::InterestOperator::SetTolerance (double tolerance)
ValidatePvlDN()
void Isis::ControlNetValidMeasure::ValidatePvlDN (void) protected inherited
Validate PVL Min & Max DN Standard Options.
Validate the Min and Max Dn Values set by the user in the Operator pvl file.
If not set then set the options to default and enter their names in the Unused Group. If the user set values are invalid then exception is thrown.
Author
Sharmila Prasad (5/10/2010)
References _FILEINFO_, Isis::PvlContainer::hasKeyword(), Isis::ControlNetValidMeasure::mbValidateDN, Isis::ControlNetValidMeasure::mdMaxDN, Isis::ControlNetValidMeasure::mdMinDN, Isis::ControlNetValidMeasure::mPvlOpGrp, Isis::ControlNetValidMeasure::mStdOptionsGrp, Isis::toString(), Isis::IException::User, Isis::ValidMaximum, and Isis::ValidMinimum.
Referenced by Isis::ControlNetValidMeasure::Parse().
ValidatePvlEmissionAngle()
void Isis::ControlNetValidMeasure::ValidatePvlEmissionAngle (void) protected inherited
Validate PVL Min & Max EmissionAngle Standard Options.
ValidateEmissionAngle: Validate the Min and Max Emission Values set by the user in the Operator pvl file.
If not set then set the options to default and enter their names in the Unused Group. If the user set values are invalid then exception is thrown, the valid range being [0-135]
Author
Sharmila Prasad (5/10/2010)
References _FILEINFO_, Isis::PvlContainer::hasKeyword(), Isis::ControlNetValidMeasure::mbCameraRequired, Isis::ControlNetValidMeasure::mdMaxEmissionAngle, Isis::ControlNetValidMeasure::mdMinEmissionAngle, Isis::ControlNetValidMeasure::mPvlOpGrp, Isis::ControlNetValidMeasure::mStdOptionsGrp, Isis::toString(), and Isis::IException::User.
Referenced by Isis::ControlNetValidMeasure::Parse().
ValidatePvlFromEdge()
void Isis::ControlNetValidMeasure::ValidatePvlFromEdge (void) protected inherited
Validate and read Pixels and Meters from Edge Standard Options.
Validate and Read the Pixels and Meters from Edge Standard Options.
Author
Sharmila Prasad (6/22/2010)
References Isis::PvlContainer::hasKeyword(), Isis::ControlNetValidMeasure::mbValidateFromEdge, Isis::ControlNetValidMeasure::mdMetersFromEdge, Isis::ControlNetValidMeasure::miPixelsFromEdge, Isis::ControlNetValidMeasure::mPvlOpGrp, Isis::ControlNetValidMeasure::mStdOptionsGrp, and Isis::toString().
Referenced by Isis::ControlNetValidMeasure::Parse().
ValidatePvlIncidenceAngle()
void Isis::ControlNetValidMeasure::ValidatePvlIncidenceAngle (void) protected inherited
Validate PVL Min & Max IncidenceAngle Standard Options.
ValidateIncidenceAngle: Validate the Min and Max Incidence Values set by the user in the Operator pvl file.
If not set then set the options to default and enter their names in the Unused Group. If the user set values are invalid then exception is thrown, the valid range being [0-135]
Author
Sharmila Prasad (5/10/2010)
References _FILEINFO_, Isis::PvlContainer::hasKeyword(), Isis::ControlNetValidMeasure::mbCameraRequired, Isis::ControlNetValidMeasure::mdMaxIncidenceAngle, Isis::ControlNetValidMeasure::mdMinIncidenceAngle, Isis::ControlNetValidMeasure::mPvlOpGrp, Isis::ControlNetValidMeasure::mStdOptionsGrp, Isis::toString(), and Isis::IException::User.
Referenced by Isis::ControlNetValidMeasure::Parse().
ValidatePvlResidualTolerances()
void Isis::ControlNetValidMeasure::ValidatePvlResidualTolerances (void) protected inherited
Validate Pvl Sample, Line, Residual Magnitude Tolerances.
Author
Sharmila Prasad (5/16/2011)
References _FILEINFO_, Isis::PvlContainer::hasKeyword(), Isis::ControlNetValidMeasure::mdLineResTolerance, Isis::ControlNetValidMeasure::mdResidualTolerance, Isis::ControlNetValidMeasure::mdSampleResTolerance, Isis::ControlNetValidMeasure::mPvlOpGrp, Isis::ControlNetValidMeasure::mStdOptionsGrp, Isis::toString(), and Isis::IException::User.
Referenced by Isis::ControlNetValidMeasure::Parse().
ValidatePvlResolution()
void Isis::ControlNetValidMeasure::ValidatePvlResolution (void) protected inherited
Validate PVL Min & Max Resolution Standard Options.
Validate the Min and Max Resolution Values set by the user in the Operator pvl file.
If not set then set the options to default and enter their names in the Unused Group. If the user set values are invalid then exception is thrown.
Author
Sharmila Prasad (6/4/2010)
References _FILEINFO_, Isis::PvlContainer::hasKeyword(), Isis::ControlNetValidMeasure::mbCameraRequired, Isis::ControlNetValidMeasure::mdMaxResolution, Isis::ControlNetValidMeasure::mdMinResolution, Isis::ControlNetValidMeasure::mPvlOpGrp, Isis::ControlNetValidMeasure::mStdOptionsGrp, Isis::toString(), and Isis::IException::User.
Referenced by Isis::ControlNetValidMeasure::Parse().
ValidatePvlShiftTolerances()
void Isis::ControlNetValidMeasure::ValidatePvlShiftTolerances () protected inherited
Validate Pvl Sample, Line, Pixel (Sample and Line) Magnitude Shift Tolerances.
References _FILEINFO_, Isis::PvlContainer::hasKeyword(), Isis::ControlNetValidMeasure::m_lineShiftTolerance, Isis::ControlNetValidMeasure::m_pixelShiftTolerance, Isis::ControlNetValidMeasure::m_sampleShiftTolerance, Isis::ControlNetValidMeasure::mPvlOpGrp, Isis::ControlNetValidMeasure::mStdOptionsGrp, Isis::toString(), and Isis::IException::User.
Referenced by Isis::ControlNetValidMeasure::Parse().
ValidDnValue()
bool Isis::ControlNetValidMeasure::ValidDnValue (double pdDnValue) inherited
Validate whether the DN Value is in the set Range.
Validates Dn Value by comparing against the Min and Max DN Values set in the def file or the defaults.
Author
Sharmila Prasad (3/30/2010)
Parameters
pdDnValue - DN Value to Valdiate
Returns
bool
References Isis::IsSpecial(), and Isis::ControlNetValidMeasure::mdMaxDN.
Referenced by Isis::GradientOperator::Interest(), Isis::MoravecOperator::Interest(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
ValidEmissionAngle()
bool Isis::ControlNetValidMeasure::ValidEmissionAngle (double pdEmissionAngle) inherited
Validate whether the Emission Angle is in the set Range.
Validates an Emission angle by comparing with the min and max values in the def file.
If Emission Angle is greater or lesser than the max/min values in the def file or the defaults it returns false else true.
Author
Sharmila Prasad (3/30/2010)
Parameters
pdEmissionAngle - Emission Angle to Valdiate
Returns
bool
References Isis::ControlNetValidMeasure::mdMaxEmissionAngle.
Referenced by Isis::ControlNetValidMeasure::ValidStandardOptions().
ValidIncidenceAngle()
bool Isis::ControlNetValidMeasure::ValidIncidenceAngle (double pdIncidenceAngle) inherited
Validate whether the Incidence Angle is in the set Range.
Validates an Incidence angle by comparing with the min and max values in the def file.
If Incidence Angle is greater or lesser than the max/min values in the def file or the defaults it returns false else true.
Author
Sharmila Prasad (5/10/2010)
Parameters
pdIncidenceAngle - Incidence Angle to Valdiate
Returns
bool
References Isis::ControlNetValidMeasure::mdMaxIncidenceAngle.
Referenced by Isis::ControlNetValidMeasure::ValidStandardOptions().
ValidLatLon()
bool Isis::ControlNetValidMeasure::ValidLatLon (Isis::Camera * pCamera, int piSample, int piLine) inherited
Validate the Lat/Lon.
Validate if a point has a valid lat, lon for that camera.
Author
Sharmila Prasad (6/4/2010)
Parameters
pCamera
piSample
piLine
Returns
bool
ValidResidualTolerances()
bool Isis::ControlNetValidMeasure::ValidResidualTolerances (double pdSampleResidual, double pdLineResidual, double pdResidualMagnitude, MeasureValidationResults & pResults) inherited
Validate whether the Residuals are within the set Tolerance.
Validate whether the Sample and Line Residuals and Residual Magnitudes are within the set Tolerances'.
Author
Sharmila Prasad (5/16/2011)
Parameters
pdSampleResidual - Measure's Sample residual
pdLineResidual - Measure's Line residual
pdResidualMagnitude - Measure's Residual Magnitude
pResults - MeasureValidationResults
Returns
bool - Valid (true/false)
References Isis::MeasureValidationResults::addFailure(), Isis::MeasureValidationResults::LineResidual, Isis::ControlNetValidMeasure::mdLineResTolerance, Isis::ControlNetValidMeasure::mdResidualTolerance, Isis::ControlNetValidMeasure::mdSampleResTolerance, Isis::MeasureValidationResults::ResidualMagnitude, and Isis::MeasureValidationResults::SampleResidual.
Referenced by Isis::ControlNetValidMeasure::ValidStandardOptions().
ValidResolution()
bool Isis::ControlNetValidMeasure::ValidResolution (double pdResolution) inherited
Validate whether the Resolution is in the set Range.
Validates Dn Value by comparing against the Min and Max DN Values set in the def file or the defaults.
Author
Sharmila Prasad (6/4/2010)
Parameters
pdResolution - Resolution to Validate
Returns
bool
References Isis::ControlNetValidMeasure::mdMaxResolution.
Referenced by Isis::ControlNetValidMeasure::ValidStandardOptions().
ValidShiftTolerances()
bool Isis::ControlNetValidMeasure::ValidShiftTolerances (double sampleShift, double lineShift, double pixelShift, MeasureValidationResults & results) inherited
Validate whether the Sample and Line Shifts and Pixel Shift are within the set Tolerances.
Parameters
sampleShift Measure's sample shift (current - apriori)
lineShift Measure's line shift (current - apriori)
pixelShift Measure's pixel shift (Euclidean distance shifted)
results Validation results populated with any new failures
Returns
Whether every test was valid or not
References Isis::MeasureValidationResults::addFailure(), Isis::MeasureValidationResults::LineShift, Isis::ControlNetValidMeasure::m_lineShiftTolerance, Isis::ControlNetValidMeasure::m_pixelShiftTolerance, Isis::ControlNetValidMeasure::m_sampleShiftTolerance, Isis::MeasureValidationResults::PixelShift, and Isis::MeasureValidationResults::SampleShift.
Referenced by Isis::ControlNetValidMeasure::ValidStandardOptions().
ValidStandardOptions() [1/5]
MeasureValidationResults Isis::ControlNetValidMeasure::ValidStandardOptions (const ControlMeasure * pMeasure, Cube * pCube, Camera * camera, PvlGroup * pMeasureGrp = NULL) inherited
Validate Standard options to pick a reference based on a particular criteria.
References Isis::ControlMeasure::GetLine(), Isis::ControlMeasure::GetSample(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
ValidStandardOptions() [2/5]
MeasureValidationResults Isis::ControlNetValidMeasure::ValidStandardOptions (const ControlMeasure * pMeasure, Cube * pCube, PvlGroup * pMeasureGrp = NULL) inherited
Validate Standard options to pick a reference based on a particular criteria.
Validate a measure for all the Standard Options.
Author
Sharmila Prasad (6/22/2010)
Parameters
piSample - Point Sample location
piLine - Point Line location
pCube - Control Measure Cube
pMeasureGrp - Log PvlGroup
Returns
bool
References Isis::ControlMeasure::GetLine(), and Isis::ControlMeasure::GetSample().
Referenced by FindCnetRef(), InterestByMeasure(), Operate(), ProcessLocked_Point_Reference(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
ValidStandardOptions() [3/5]
MeasureValidationResults Isis::ControlNetValidMeasure::ValidStandardOptions (double pSample, double pLine, const ControlMeasure * pMeasure, Cube * pCube, Camera * measureCamera, PvlGroup * pMeasureGrp = NULL) inherited
References Isis::MeasureValidationResults::addFailure(), Isis::MeasureValidationResults::DNValue, Isis::Sensor::EmissionAngle(), Isis::MeasureValidationResults::EmissionAngle, Isis::ControlMeasure::GetLineResidual(), Isis::ControlMeasure::GetLineShift(), Isis::ControlMeasure::GetPixelShift(), Isis::ControlMeasure::GetResidualMagnitude(), Isis::ControlMeasure::GetSampleResidual(), Isis::ControlMeasure::GetSampleShift(), Isis::Sensor::IncidenceAngle(), Isis::MeasureValidationResults::IncidenceAngle, Isis::ControlNetValidMeasure::m_lineShift, Isis::ControlNetValidMeasure::m_pixelShift, Isis::ControlNetValidMeasure::m_sampleShift, Isis::ControlNetValidMeasure::mbCameraRequired, Isis::ControlNetValidMeasure::mbValidateDN, Isis::ControlNetValidMeasure::mbValidateFromEdge, Isis::ControlNetValidMeasure::mdDnValue, Isis::ControlNetValidMeasure::mdEmissionAngle, Isis::ControlNetValidMeasure::mdIncidenceAngle, Isis::ControlNetValidMeasure::mdLineResidual, Isis::ControlNetValidMeasure::mdMaxDN, Isis::ControlNetValidMeasure::mdMaxEmissionAngle, Isis::ControlNetValidMeasure::mdMaxIncidenceAngle, Isis::ControlNetValidMeasure::mdMaxResolution, Isis::ControlNetValidMeasure::mdMetersFromEdge, Isis::ControlNetValidMeasure::mdMinDN, Isis::ControlNetValidMeasure::mdMinEmissionAngle, Isis::ControlNetValidMeasure::mdMinIncidenceAngle, Isis::ControlNetValidMeasure::mdMinResolution, Isis::ControlNetValidMeasure::mdResidualMagnitude, Isis::ControlNetValidMeasure::mdResolution, Isis::ControlNetValidMeasure::mdSampleResidual, Isis::ControlNetValidMeasure::MetersFromEdge(), Isis::MeasureValidationResults::MetersFromEdge, Isis::ControlNetValidMeasure::miPixelsFromEdge, Isis::Null, Isis::Camera::PixelResolution(), Isis::ControlNetValidMeasure::PixelsFromEdge(), Isis::MeasureValidationResults::PixelsFromEdge, Isis::Cube::pixelType(), Isis::Cube::read(), Isis::MeasureValidationResults::Resolution, Isis::Camera::SetImage(), Isis::Portal::SetPosition(), Isis::toString(), Isis::ControlNetValidMeasure::ValidDnValue(), Isis::ControlNetValidMeasure::ValidEmissionAngle(), Isis::ControlNetValidMeasure::ValidIncidenceAngle(), Isis::ControlNetValidMeasure::ValidResidualTolerances(), Isis::ControlNetValidMeasure::ValidResolution(), and Isis::ControlNetValidMeasure::ValidShiftTolerances().
ValidStandardOptions() [4/5]
MeasureValidationResults Isis::ControlNetValidMeasure::ValidStandardOptions (double pSample, double pLine, const ControlMeasure * pMeasure, Cube * pCube, PvlGroup * pMeasureGrp = NULL) inherited
Validate Standard options to pick a reference based on a particular criteria.
Validate a point on an image and the Control Measure if not Null.
Author
Sharmila Prasad (5/17/2011)
Parameters
pSample - Image Sample
pLine - Image Line
pMeasure - Control Measure
pCube - Control Measure's image
pMeasureGrp - Result PvlGroup
Returns
MeasureValidationResults
References _FILEINFO_, Isis::Cube::camera(), Isis::Cube::fileName(), Isis::ControlNetValidMeasure::mbCameraRequired, Isis::IException::User, and Isis::ControlNetValidMeasure::ValidStandardOptions().
ValidStandardOptions() [5/5]
MeasureValidationResults Isis::ControlNetValidMeasure::ValidStandardOptions (double pSample, double pLine, Cube * pCube, PvlGroup * pMeasureGrp = NULL) inherited
Validate Standard options to pick a reference based on a particular criteria.
Validate a point on an image for Standard Options.
Author
Sharmila Prasad (5/17/2011)
Parameters
pSample - Image Sample
pLine - Image Line
pCube - Image
pMeasureGrp - Optional Result Group
Returns
MeasureValidationResults
References Isis::ControlNetValidMeasure::ValidStandardOptions().
WorstInterest()
double Isis::InterestOperator::WorstInterest () const inline
Return the Worst(least value) Interest.
References p_worstInterest.
Referenced by FindCnetRef().
Member Data Documentation
m_lineShift
double Isis::ControlNetValidMeasure::m_lineShift protected inherited
Store current Measure's Line Shift.
Referenced by Isis::ControlNetValidMeasure::ValidStandardOptions().
m_lineShiftTolerance
double Isis::ControlNetValidMeasure::m_lineShiftTolerance protected inherited
Standard Option Line Shift.
Referenced by Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::ControlNetValidMeasure::ValidatePvlShiftTolerances(), and Isis::ControlNetValidMeasure::ValidShiftTolerances().
m_pixelShift
double Isis::ControlNetValidMeasure::m_pixelShift protected inherited
Store current Measure's Pixel Shift.
Referenced by Isis::ControlNetValidMeasure::ValidStandardOptions().
m_pixelShiftTolerance
double Isis::ControlNetValidMeasure::m_pixelShiftTolerance protected inherited
Standard Option Pixel Shift.
Referenced by Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::ControlNetValidMeasure::ValidatePvlShiftTolerances(), and Isis::ControlNetValidMeasure::ValidShiftTolerances().
m_sampleShift
double Isis::ControlNetValidMeasure::m_sampleShift protected inherited
Store current Measure's Sample Shift.
Referenced by Isis::ControlNetValidMeasure::ValidStandardOptions().
m_sampleShiftTolerance
double Isis::ControlNetValidMeasure::m_sampleShiftTolerance protected inherited
Standard Option Sample Shift.
Referenced by Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::ControlNetValidMeasure::ValidatePvlShiftTolerances(), and Isis::ControlNetValidMeasure::ValidShiftTolerances().
mbCameraRequired
bool Isis::ControlNetValidMeasure::mbCameraRequired protected inherited
To improve speed, flag to indicate if Camera needs to be opened.
Referenced by Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::IsCameraRequired(), Isis::ControlNetValidMeasure::SetCameraRequiredFlag(), Isis::ControlNetValidMeasure::ValidatePvlEmissionAngle(), Isis::ControlNetValidMeasure::ValidatePvlIncidenceAngle(), Isis::ControlNetValidMeasure::ValidatePvlResolution(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mbValidateDN
bool Isis::ControlNetValidMeasure::mbValidateDN protected inherited
Check if DN needs to be Validated.
Referenced by Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::IsCubeRequired(), Isis::ControlNetValidMeasure::ValidatePvlDN(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mbValidateFromEdge
bool Isis::ControlNetValidMeasure::mbValidateFromEdge protected inherited
Check if Pixels/Meters from edge needs to be Validated.
Referenced by Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::IsCubeRequired(), Isis::ControlNetValidMeasure::ValidatePvlFromEdge(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mCubeMgr
CubeManager Isis::ControlNetValidMeasure::mCubeMgr protected inherited
CubeManager to open and read cubes.
Referenced by FindCnetRef(), FindOverlapByImageFootPrint(), InterestByPoint(), ProcessLocked_Point_Reference(), Isis::ControlNetValidMeasure::ReadSerialNumbers(), and Isis::ControlNetValidMeasure::~ControlNetValidMeasure().
mdDnValue
double Isis::ControlNetValidMeasure::mdDnValue protected inherited
Store current Measure's DN Value.
Referenced by InterestByMeasure(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mdEmissionAngle
double Isis::ControlNetValidMeasure::mdEmissionAngle protected inherited
Store current Measure's Emission Angle.
Referenced by InterestByMeasure(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mdIncidenceAngle
double Isis::ControlNetValidMeasure::mdIncidenceAngle protected inherited
Store current Measure's Incidence Angle.
Referenced by InterestByMeasure(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mdLineResidual
double Isis::ControlNetValidMeasure::mdLineResidual protected inherited
Store current Measure's Line Residual.
Referenced by Isis::ControlNetValidMeasure::ValidStandardOptions().
mdLineResTolerance
double Isis::ControlNetValidMeasure::mdLineResTolerance protected inherited
Standard Option Line Residual.
Referenced by Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::ControlNetValidMeasure::ValidatePvlResidualTolerances(), and Isis::ControlNetValidMeasure::ValidResidualTolerances().
mdMaxDN
double Isis::ControlNetValidMeasure::mdMaxDN protected inherited
Standard Option MaxDN.
Referenced by Isis::ControlNetValidMeasure::GetMaxDN(), Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::StandardDeviationOperator::Interest(), Isis::ControlNetValidMeasure::ValidatePvlDN(), Isis::ControlNetValidMeasure::ValidDnValue(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mdMaxEmissionAngle
double Isis::ControlNetValidMeasure::mdMaxEmissionAngle protected inherited
Standard Option MaxEmissionAngle.
Referenced by Isis::ControlNetValidMeasure::GetMaxEmissionAngle(), Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::ControlNetValidMeasure::ValidatePvlEmissionAngle(), Isis::ControlNetValidMeasure::ValidEmissionAngle(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mdMaxIncidenceAngle
double Isis::ControlNetValidMeasure::mdMaxIncidenceAngle protected inherited
Standard Option MaxIncidenceAngle.
Referenced by Isis::ControlNetValidMeasure::GetMaxIncidenceAngle(), Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::ControlNetValidMeasure::ValidatePvlIncidenceAngle(), Isis::ControlNetValidMeasure::ValidIncidenceAngle(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mdMaxResolution
double Isis::ControlNetValidMeasure::mdMaxResolution protected inherited
Standard Option MaxResolution.
Referenced by Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::ControlNetValidMeasure::ValidatePvlResolution(), Isis::ControlNetValidMeasure::ValidResolution(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mdMetersFromEdge
double Isis::ControlNetValidMeasure::mdMetersFromEdge protected inherited
Standard Option MeteresFromEdge.
Referenced by Isis::ControlNetValidMeasure::GetMetersFromEdge(), Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::ControlNetValidMeasure::MetersFromEdge(), Isis::ControlNetValidMeasure::ValidatePvlFromEdge(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mdMinDN
double Isis::ControlNetValidMeasure::mdMinDN protected inherited
Standard Option MinDN.
Referenced by Isis::ControlNetValidMeasure::GetMinDN(), Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::StandardDeviationOperator::Interest(), Isis::ControlNetValidMeasure::ValidatePvlDN(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mdMinEmissionAngle
double Isis::ControlNetValidMeasure::mdMinEmissionAngle protected inherited
Standard Option MinEmissionAngle.
Referenced by Isis::ControlNetValidMeasure::GetMinEmissionAngle(), Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::ControlNetValidMeasure::ValidatePvlEmissionAngle(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mdMinIncidenceAngle
double Isis::ControlNetValidMeasure::mdMinIncidenceAngle protected inherited
Standard Option MinIncidenceAngle.
Referenced by Isis::ControlNetValidMeasure::GetMinIncidenceAngle(), Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::ControlNetValidMeasure::ValidatePvlIncidenceAngle(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mdMinResolution
double Isis::ControlNetValidMeasure::mdMinResolution protected inherited
Standard Option MinResolution.
Referenced by Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::ControlNetValidMeasure::ValidatePvlResolution(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mdResidualMagnitude
double Isis::ControlNetValidMeasure::mdResidualMagnitude protected inherited
Store current Measure's Residual Magnitude.
Referenced by Isis::ControlNetValidMeasure::ValidStandardOptions().
mdResidualTolerance
double Isis::ControlNetValidMeasure::mdResidualTolerance protected inherited
Standard Option Residual Magnitude.
Referenced by Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::ControlNetValidMeasure::ValidatePvlResidualTolerances(), and Isis::ControlNetValidMeasure::ValidResidualTolerances().
mdResolution
double Isis::ControlNetValidMeasure::mdResolution protected inherited
Store current Measure's Resolution.
Referenced by FindCnetRef(), InterestByMeasure(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mdSampleResidual
double Isis::ControlNetValidMeasure::mdSampleResidual protected inherited
Store current Measure's Sample Residual.
Referenced by Isis::ControlNetValidMeasure::ValidStandardOptions().
mdSampleResTolerance
double Isis::ControlNetValidMeasure::mdSampleResTolerance protected inherited
Standard Option Sample Residual.
Referenced by Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::ControlNetValidMeasure::ValidatePvlResidualTolerances(), and Isis::ControlNetValidMeasure::ValidResidualTolerances().
miPixelsFromEdge
int Isis::ControlNetValidMeasure::miPixelsFromEdge protected inherited
Standard Option PixelsFromEdge.
Referenced by Isis::ControlNetValidMeasure::GetPixelsFromEdge(), Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::ControlNetValidMeasure::PixelsFromEdge(), Isis::ControlNetValidMeasure::ValidatePvlFromEdge(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
mOperatorGrp
Isis::PvlGroup Isis::InterestOperator::mOperatorGrp protected
Operator group that created this projection.
Referenced by InterestOperator(), Operator(), operatorName(), and Parse().
mPvlLog
Pvl Isis::ControlNetValidMeasure::mPvlLog protected inherited
Pvl Log of all the processing.
Referenced by FindCnetRef(), Isis::ControlNetValidMeasure::GetLogPvl(), and Isis::ControlNetValidMeasure::Parse().
mPvlOpGrp
PvlGroup Isis::ControlNetValidMeasure::mPvlOpGrp protected inherited
Pvl Operator Group.
Referenced by Isis::ControlNetValidMeasure::Parse(), Isis::ControlNetValidMeasure::ValidatePvlDN(), Isis::ControlNetValidMeasure::ValidatePvlEmissionAngle(), Isis::ControlNetValidMeasure::ValidatePvlFromEdge(), Isis::ControlNetValidMeasure::ValidatePvlIncidenceAngle(), Isis::ControlNetValidMeasure::ValidatePvlResidualTolerances(), Isis::ControlNetValidMeasure::ValidatePvlResolution(), and Isis::ControlNetValidMeasure::ValidatePvlShiftTolerances().
mSerialNumbers
SerialNumberList Isis::ControlNetValidMeasure::mSerialNumbers protected inherited
Serial numbers list.
Referenced by FindCnetRef(), FindOverlapByImageFootPrint(), InterestByMeasure(), InterestByPoint(), ProcessLocked_Point_Reference(), and Isis::ControlNetValidMeasure::ReadSerialNumbers().
mStatisticsGrp
PvlGroup Isis::ControlNetValidMeasure::mStatisticsGrp protected inherited
Pvl output Statistics Group.
Referenced by Isis::ControlNetValidMeasure::ControlNetValidMeasure(), FindCnetRef(), and Isis::ControlNetValidMeasure::GetStatistics().
mStatus
Progress Isis::ControlNetValidMeasure::mStatus protected inherited
Monitor the status of the app.
Referenced by FindCnetRef(), and Isis::ControlNetValidMeasure::ReadSerialNumbers().
mStdOptionsGrp
PvlGroup Isis::ControlNetValidMeasure::mStdOptionsGrp protected inherited
Pvl Standard Options Group.
Referenced by Isis::ControlNetValidMeasure::GetStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::ControlNetValidMeasure::Parse(), Isis::ControlNetValidMeasure::ValidatePvlDN(), Isis::ControlNetValidMeasure::ValidatePvlEmissionAngle(), Isis::ControlNetValidMeasure::ValidatePvlFromEdge(), Isis::ControlNetValidMeasure::ValidatePvlIncidenceAngle(), Isis::ControlNetValidMeasure::ValidatePvlResidualTolerances(), Isis::ControlNetValidMeasure::ValidatePvlResolution(), and Isis::ControlNetValidMeasure::ValidatePvlShiftTolerances().
p_clipPolygon
geos::geom::MultiPolygon* Isis::InterestOperator::p_clipPolygon protected
Clipping polygon set by SetClipPolygon (line,samp)
Referenced by InitInterestOptions(), InterestByMeasure(), Operate(), SetClipPolygon(), and ~InterestOperator().
p_interestAmount
double Isis::InterestOperator::p_interestAmount protected
Referenced by InitInterestOptions(), InterestAmount(), and Operate().
p_worstInterest
double Isis::InterestOperator::p_worstInterest protected
Referenced by InitInterestOptions(), Isis::NoOperator::NoOperator(), Isis::StandardDeviationOperator::StandardDeviationOperator(), and WorstInterest().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/InterestOperator/InterestOperator.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/InterestOperator/InterestOperator.cpp