Isis Developer Reference: Isis::BundleAdjust Class Reference
Isis::BundleAdjust Class Reference
An image bundle adjustment object.
#include <BundleAdjust.h>
Public Slots
bool solveCholesky ()
Compute the least squares bundle adjustment solution using Cholesky decomposition.
void abortBundle ()
Flag to abort when bundle is threaded.
void outputBundleStatus (QString status)
Slot for deltack and jigsaw to output the bundle status.
ControlNetQsp controlNet ()
Returns a pointer to the output control network.
LidarDataQsp lidarData ()
Returns a pointer to the output lidar data file.
SerialNumberList * serialNumberList ()
Returns a pointer to the serial number list.
QString fileName (int index)
Return the ith filename in the cube list file given to constructor.
QString iterationSummaryGroup () const
Returns the iteration summary string.
bool isConverged ()
Returns if the BundleAdjust converged.
Table cMatrix (int index)
Return the updated instrument pointing table for the ith cube in the cube list given to the constructor.
Table spVector (int index)
Return the updated instrument position table for the ith cube in the cube list given to the constructor.
QString modelState (int index)
Return the updated model state for the ith cube in the cube list given to the constructor.
int numberOfImages () const
Returns the number of images.
double iteration () const
Returns what iteration the BundleAdjust is currently on.
Signals
void statusUpdate (QString)
void error (QString)
void iterationUpdate (int)
void pointUpdate (int)
void statusBarUpdate (QString)
void resultsReady (BundleSolutionInfo *bundleSolveInformation)
void finished ()
Public Member Functions
BundleAdjust (BundleSettingsQsp bundleSettings, const QString &cnetFile, const QString &cubeList, bool printSummary=true)
Construct a BundleAdjust object from the given settings, control network file, and cube list.
BundleAdjust (BundleSettingsQsp bundleSettings, const QString &cnetFile, const QString &cubeList, const QString &lidarDataFile, bool printSummary=true)
Construct a BundleAdjust object from the given settings, control network file, cube list, and lidar point data.
BundleAdjust (BundleSettingsQsp bundleSettings, QString &cnet, SerialNumberList &snlist, bool printSummary=true)
Construct a BundleAdjust object with held cubes.
BundleAdjust (BundleSettingsQsp bundleSettings, Control &cnet, SerialNumberList &snlist, bool bPrintSummary)
Constructs a BundleAdjust object using a Control object.
BundleAdjust (BundleSettingsQsp bundleSettings, ControlNet &cnet, SerialNumberList &snlist, bool printSummary=true)
Constructs a BundleAdjust object using a ControlNet object.
BundleAdjust (BundleSettingsQsp bundleSettings, ControlNetQsp cnet, const QString &cubeList, bool printSummary=true)
Constructs a BundleAdjust from an already created ControlNet within a shared pointer.
BundleAdjust (BundleSettingsQsp bundleSettings, Control &control, QList< ImageList * > imgList, bool printSummary)
Thread safe constructor.
~BundleAdjust ()
Destroys BundleAdjust object, deallocates pointers (if we have ownership), and frees variables from cholmod library.
BundleSolutionInfo * solveCholeskyBR ()
Compute the least squares bundle adjustment solution using Cholesky decomposition.
QList< ImageList * > imageLists ()
This method returns the image list used in the bundle adjust.
bool isAborted ()
Returns if the BundleAdjust has been aborted.
Detailed Description
An image bundle adjustment object.
BundleAdjust is used to perform a bundle adjustment on overlapping ISIS cubes. Using the collineariy condition, BundleAdjust can construct a system of normal equations and then using the CHOLMOD library, solve that system.
Author
2006-05-30 Jeff Anderson, Debbie A. Cook, and Tracie Sucharski
Constructor & Destructor Documentation
BundleAdjust() [1/7]
Isis::BundleAdjust::BundleAdjust (BundleSettingsQsp bundleSettings, const QString & cnetFile, const QString & cubeList, bool printSummary = true)
Construct a BundleAdjust object from the given settings, control network file, and cube list.
Parameters
bundleSettings A shared pointer to the BundleSettings to be used.
cnetFile The filename of the control network to be used.
cubeList The list of filenames of the cubes to be adjusted.
printSummary If summaries should be printed each iteration.
BundleAdjust() [2/7]
Isis::BundleAdjust::BundleAdjust (BundleSettingsQsp bundleSettings, const QString & cnetFile, const QString & cubeList, const QString & lidarDataFile, bool printSummary = true)
Construct a BundleAdjust object from the given settings, control network file, cube list, and lidar point data.
Parameters
bundleSettings A shared pointer to the BundleSettings to be used.
cnetFile The filename of the control network to be used.
cubeList The list of filenames of the cubes to be adjusted.
lidarDataFile Lidar point dataset filename.
printSummary If summaries should be printed each iteration.
BundleAdjust() [3/7]
Isis::BundleAdjust::BundleAdjust (BundleSettingsQsp bundleSettings, QString & cnetFile, SerialNumberList & snlist, bool printSummary = true)
Construct a BundleAdjust object with held cubes.
Parameters
bundleSettings A shared pointer to the BundleSettings to be used.
cnetFile The filename of the control network to be used.
cubeList The list of filenames of the cubes to be adjusted.
heldList The list of filenames of the held cubes. Held cubes must be in both heldList and cubeList.
printSummary If summaries should be printed each iteration.
BundleAdjust() [4/7]
Isis::BundleAdjust::BundleAdjust (BundleSettingsQsp bundleSettings, Control & cnet, SerialNumberList & snlist, bool printSummary)
Constructs a BundleAdjust object using a Control object.
A new control network object will be created as a copy of the Control's control network.
Parameters
bundleSettings A shared pointer to the BundleSettings to be used.
cnet The Control object whose control network will be copied. The Control will not be modified by the BundleAdjust.
snlist A serial number list containing the cubes to be adjusted.
printSummary If summaries should be printed each iteration.
References Isis::Control::fileName().
BundleAdjust() [5/7]
Isis::BundleAdjust::BundleAdjust (BundleSettingsQsp bundleSettings, ControlNet & cnet, SerialNumberList & snlist, bool printSummary = true)
Constructs a BundleAdjust object using a ControlNet object.
A copy of the ControlNet will be used.
Parameters
bundleSettings A shared pointer to the BundleSettings to be used.
cnet The ControlNet that will be copied. The original ControlNet will not be modified.
snlist A serial number list containing the cubes to be adjusted.
printSummary If summaries should be printed each iteration.
BundleAdjust() [6/7]
Isis::BundleAdjust::BundleAdjust (BundleSettingsQsp bundleSettings, ControlNetQsp cnet, const QString & cubeList, bool printSummary = true)
Constructs a BundleAdjust from an already created ControlNet within a shared pointer.
Parameters
bundleSettings QSharedPointer to the bundle settings to use.
cnet QSharedPointer to the control net to adjust.
cubeList QString name of list of cubes to create serial numbers for.
printSummary Boolean indicating whether to print application output summary.
BundleAdjust() [7/7]
Isis::BundleAdjust::BundleAdjust (BundleSettingsQsp bundleSettings, Control & control, QList< ImageList * > imgLists, bool printSummary)
Thread safe constructor.
Parameters
bundleSettings A shared pointer to the BundleSettings to be used.
control The Control object whose control network will be copied. The Control will not be modified by the BundleAdjust.
snlist A serial number list containing the cubes to be adjusted.
printSummary If summaries should be printed each iteration.
References Isis::SerialNumberList::add(), Isis::Control::fileName(), and Isis::Image::fileName().
~BundleAdjust()
Isis::BundleAdjust::~BundleAdjust ()
Destroys BundleAdjust object, deallocates pointers (if we have ownership), and frees variables from cholmod library.
Member Function Documentation
abortBundle
void Isis::BundleAdjust::abortBundle () slot
Flag to abort when bundle is threaded.
Flag is set outside the bundle thread, typically by the gui thread.
Referenced by Isis::JigsawRunWidget::closeEvent().
cMatrix
Table Isis::BundleAdjust::cMatrix (int i) slot
Return the updated instrument pointing table for the ith cube in the cube list given to the constructor.
This is only valid for ISIS camera model cubes
Parameters
i The index of the cube
Returns
Table The InstrumentPointing table for the cube.
controlNet
ControlNetQsp Isis::BundleAdjust::controlNet () slot
Returns a pointer to the output control network.
Returns
ControlNetQsp A shared pointer to the output control network.
error
void Isis::BundleAdjust::error (QString) signal
fileName
QString Isis::BundleAdjust::fileName (int i) slot
Return the ith filename in the cube list file given to constructor.
Parameters
i The index of the cube.
Returns
QString The filename of the cube.
finished
void Isis::BundleAdjust::finished () signal
imageLists()
QList< ImageList * > Isis::BundleAdjust::imageLists ()
This method returns the image list used in the bundle adjust.
If a QList<ImageList *> was passed into the constructor then it uses that list, otherwise it constructs the QList using the m_serialNumberList
Returns
QList<ImageList *> The ImageLists used for the bundle adjust
References _FILEINFO_, Isis::ImageList::append(), and Isis::Image::closeCube().
isAborted()
bool Isis::BundleAdjust::isAborted ()
Returns if the BundleAdjust has been aborted.
Returns
bool If the BundleAdjust was aborted.
Referenced by Isis::JigsawRunWidget::notifyThreadFinished().
isConverged
bool Isis::BundleAdjust::isConverged () slot
Returns if the BundleAdjust converged.
Returns
bool If the BundleAdjust converged.
iteration
double Isis::BundleAdjust::iteration () const slot
Returns what iteration the BundleAdjust is currently on.
Returns
double The current iteration number.
iterationSummaryGroup
QString Isis::BundleAdjust::iterationSummaryGroup () const slot
Returns the iteration summary string.
Returns
QString the iteration summary string.
See also
iterationSummary()
iterationUpdate
void Isis::BundleAdjust::iterationUpdate (int) signal
lidarData
LidarDataQsp Isis::BundleAdjust::lidarData () slot
Returns a pointer to the output lidar data file.
Returns
LidarDataQsp A shared pointer to the output lidar data file.
modelState
QString Isis::BundleAdjust::modelState (int i) slot
Return the updated model state for the ith cube in the cube list given to the constructor.
This is only valid for CSM cubes.
Parameters
i The index of the cube to get the model state for
Returns
QString The updated CSM model state string
References _FILEINFO_, Isis::Camera::Camera(), Isis::Camera::GetCameraType(), Isis::CSMCamera::getModelState(), and Isis::toString().
numberOfImages
int Isis::BundleAdjust::numberOfImages () const slot
Returns the number of images.
Returns
int The number of images.
References Isis::SerialNumberList::size().
outputBundleStatus
void Isis::BundleAdjust::outputBundleStatus (QString status) slot
Slot for deltack and jigsaw to output the bundle status.
Parameters
status The bundle status string to output.
References Isis::iApp.
pointUpdate
void Isis::BundleAdjust::pointUpdate (int) signal
resultsReady
void Isis::BundleAdjust::resultsReady (BundleSolutionInfo * bundleSolveInformation) signal
serialNumberList
SerialNumberList * Isis::BundleAdjust::serialNumberList () slot
Returns a pointer to the serial number list.
Returns
SerialNumberList* A pointer to the serial number list.
solveCholesky
bool Isis::BundleAdjust::solveCholesky () slot
Compute the least squares bundle adjustment solution using Cholesky decomposition.
Returns
bool If the solution was successfully computed.
References _FILEINFO_, Isis::IException::errorType(), Isis::SurfacePoint::GetLatitude(), Isis::SurfacePoint::GetLongitude(), and Isis::SurfacePoint::ResetLocalRadius().
solveCholeskyBR()
BundleSolutionInfo * Isis::BundleAdjust::solveCholeskyBR ()
Compute the least squares bundle adjustment solution using Cholesky decomposition.
Returns
BundleSolutionInfo A container with settings and results from the adjustment.
See also
BundleAdjust::solveCholesky
spVector
Table Isis::BundleAdjust::spVector (int i) slot
Return the updated instrument position table for the ith cube in the cube list given to the constructor.
This is only valid for ISIS camera model cubes
Parameters
i The index of the cube
Returns
Table The InstrumentPosition table for the cube.
statusBarUpdate
void Isis::BundleAdjust::statusBarUpdate (QString) signal
statusUpdate
void Isis::BundleAdjust::statusUpdate (QString) signal
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/BundleAdjust/BundleAdjust.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/BundleAdjust/BundleAdjust.cpp