Isis Developer Reference: Isis::PvlToXmlTranslationManager Class Reference
Isis::PvlToXmlTranslationManager Class Reference
Parsing
Allows applications to translate simple text files.
#include <PvlToXmlTranslationManager.h>
Public Member Functions
PvlToXmlTranslationManager (const QString &transFile)
Constructs and initializes a TranslationManager object from given the Pvl translation file.
PvlToXmlTranslationManager (Pvl &inputLabel, const QString &transFile)
Constructs and initializes a TranslationManager object.
virtual ~PvlToXmlTranslationManager ()
Destroys the TranslationManager object.
virtual QString Translate (QString translationGroupName, int inputIndex=0)
Returns a translated value.
void Auto (QDomDocument &outputLabel)
Automatically translate all the output names found in the translation table.
void Auto (Pvl &inputLabel, QDomDocument &outputLabel)
Set the inputLabel and automatically translate all the output names found in the translation table.
virtual const PvlKeyword & InputKeyword (const QString translationGroupName) const
Uses the translation file group name to find the input label's PvlKeyword that corresponds to the InputKey value of the translation table and returns it, if found.
virtual bool InputHasKeyword (const QString translationGroupName)
Indicates if the input keyword corresponding to the output name exists in the label.
void SetLabel (Pvl &inputLabel)
Internalizes a Pvl formatted label for translation.
QString Translate (const QString translationGroupName, const QString inputKeyValue="") const
Translates a single output value from the given translation group name and input value.
virtual void Auto (Pvl &outputLabel)
Automatically translate all the output names tagged as Auto in the translation table If a output name does not translate an error will be thrown by one of the support members.
virtual QStringList parseSpecification (QString specification) const
Parses and validates a dependency specification.
virtual PvlKeyword InputGroup (const QString translationGroupName, const int inst=0) const
Returns the input group name from the translation table corresponding to the output name argument.
virtual QString InputKeywordName (const QString translationGroupName) const
Returns the input keyword name from the translation table corresponding to the output name argument.
QString InputDefault (const QString translationGroupName) const
Returns the input default value from the translation table corresponding to the output name argument.
void AddTable (std::istream &transStm)
Adds the contents of a translation table to the searchable groups/keys Also performs a verification, to ensure that the translation table is valid.
void AddTable (const QString &transFile)
Adds the contents of a translation table to the searchable groups/keys.
Static Public Member Functions
static void addElement (QDomElement &parent, QString name, QString value, QString units="")
Add a QDomElement to the given parent with the indicated value and units.
static void setElementValue (QDomElement &element, QString value, QString units="")
Set the QDomElement's value, and units, if units != "".
static void resetElementValue (QDomElement &element, QString value, QString units="")
Reset the QDomElement's value, and units, if units != "".
Protected Member Functions
void doTranslation (PvlGroup transGroup, QDomElement &parent)
Translate the requested output name to output values using the input name and values or default value.
virtual const PvlContainer * GetContainer (const PvlKeyword &inputGroup) const
Return a container from the input label with the path given by the "InputPosition" keyword of the translation table.
virtual std::vector< std::pair< QString, int > > validKeywords () const
Returns a vector of valid keyword names and their sizes.
bool checkDependencies (QDomElement element, PvlKeyword dependencies, bool isDebug) const
QDomElement * createParentElements (const QString translationGroupName, QDomElement &xml)
Read the OutputPosition for the translation group name passed and create any parent elements specified by OutputPosition to prepare for translation.
void addSiblings (PvlKeyword outputSiblings, QDomElement &parent)
Take in outputSiblings PvlKeyword and turn each sibling into its corresponding QDomElement.
void addAttributes (PvlKeyword something, QDomElement &parent)
Take in the outputAttributes PvlKeyword and add each attribute to the appropriate element given as an argument.
virtual PvlKeyword DoTranslation (const QString translationGroupName)
Translate the requested output name to output values using the input name and values or default value.
virtual PvlContainer * CreateContainer (const QString translationGroupName, Pvl &pvl)
Creates all parent PVL containers for an output keyword.
Pvl & TranslationTable ()
Protected accessor for pvl translation table passed into class.
const Pvl & TranslationTable () const
Protected accessor for const pvl translation table passed into class.
bool hasInputDefault (const QString translationGroupName)
Determines whether the given group has a default input value.
bool IsAuto (const QString translationGroupName)
Determines whether the given group should be automatically translated.
bool IsOptional (const QString translationGroupName)
Determines whether the translation group is optional.
PvlKeyword OutputPosition (const QString translationGroupName)
Retrieves the OutputPosition PvlKeyword for the translation group with the given name.
QString OutputName (const QString translationGroupName)
Retrieves a string containing the value of the OutputName keyword for the translation group with the given name.
const PvlGroup & findTranslationGroup (const QString translationGroupName) const
Searches for translation group with the given name.
Detailed Description
Allows applications to translate simple text files.
This class allows the translation of text files which can be parsed by the Pvl class into Xml files.
Author
2017-05-24 Jeannie Backer and Ian Humphrey
Constructor & Destructor Documentation
PvlToXmlTranslationManager() [1/2]
Isis::PvlToXmlTranslationManager::PvlToXmlTranslationManager (const QString & transFile)
Constructs and initializes a TranslationManager object from given the Pvl translation file.
If this constructor is used, the user will need to set the input label before translating. This may be done by using SetLabel(Pvl inputLabel) or Auto(Pvl inputLabel, Pvl outputLabel).
Parameters
transFile The translation file to be used to tranlate keywords in the input label.
PvlToXmlTranslationManager() [2/2]
Isis::PvlToXmlTranslationManager::PvlToXmlTranslationManager (Pvl & inputLabel, const QString & transFile)
Constructs and initializes a TranslationManager object.
Parameters
inputLabel The Pvl holding the input label.
transFile The translation file to be used to tranlate keywords in the input label.
~PvlToXmlTranslationManager()
Isis::PvlToXmlTranslationManager::~PvlToXmlTranslationManager () virtual
Destroys the TranslationManager object.
Member Function Documentation
addAttributes()
void Isis::PvlToXmlTranslationManager::addAttributes (PvlKeyword outputAttributes, QDomElement & element) protected
Take in the outputAttributes PvlKeyword and add each attribute to the appropriate element given as an argument.
Parameters
outputAttributes The PvlKeyword that holds the list of siblings
element QDomElement to be modified
Exceptions
IException::Programmer "Malformed output attribute [" + outputAttributes[i] + ]."
References _FILEINFO_, Isis::LabelTranslationManager::parseSpecification(), Isis::IException::Programmer, and Isis::PvlKeyword::size().
Referenced by doTranslation().
addElement()
void Isis::PvlToXmlTranslationManager::addElement (QDomElement & parent, QString name, QString value, QString units = "") static
Add a QDomElement to the given parent with the indicated value and units.
Parameters
parent The parent QDomElement of the new element.
name The name of the new element.
value The value of the new element.
units A string containing the unit specification for the new element.
References setElementValue().
addSiblings()
void Isis::PvlToXmlTranslationManager::addSiblings (PvlKeyword outputSiblings, QDomElement & parent) protected
Take in outputSiblings PvlKeyword and turn each sibling into its corresponding QDomElement.
Then add the QDomElement to the parent as a child.
Parameters
outputSiblings The PvlKeyword that holds the list of siblings
parent The parent QDomElement
Exceptions
IException::Programmer "Malformed OutputSibling [" + outputSiblings[i] + "]"
References _FILEINFO_, Isis::LabelTranslationManager::parseSpecification(), Isis::IException::Programmer, setElementValue(), and Isis::PvlKeyword::size().
Referenced by doTranslation().
AddTable() [1/2]
void Isis::PvlTranslationTable::AddTable (const QString & transFile) inherited
Adds the contents of a translation table to the searchable groups/keys.
Parameters
transFile The name of the translation file to be added.
References Isis::Pvl::read().
AddTable() [2/2]
void Isis::PvlTranslationTable::AddTable (std::istream & transStm) inherited
Adds the contents of a translation table to the searchable groups/keys Also performs a verification, to ensure that the translation table is valid.
Parameters
transStm The stream to be added.
Exceptions
IException::User - "Unable to find InputKey for group in translation file."
IException::User - "Keyword is not valid. Error in file."
IException::User - "Keyword does not have correct number of elements. Error in file."
References _FILEINFO_, Isis::PvlContainer::hasKeyword(), Isis::PvlContainer::keywords(), Isis::PvlContainer::name(), Isis::PvlKeyword::name(), and Isis::PvlKeyword::size().
Referenced by Isis::LabelTranslationManager::LabelTranslationManager(), and Isis::XmlToPvlTranslationManager::XmlToPvlTranslationManager().
Auto() [1/3]
void Isis::PvlToXmlTranslationManager::Auto (Pvl & inputLabel, QDomDocument & outputLabel)
Set the inputLabel and automatically translate all the output names found in the translation table.
If a output name does not translate an error will be thrown by one of the support members. If the output name is translated, store the translated key, value pairs in the QDomDocument.
Parameters
inputLabel The input Pvl label
outputLabel The output QDomDocument label
See also
Auto(QDomDocument &outputLabel)
References Auto().
Auto() [2/3]
void Isis::LabelTranslationManager::Auto (Pvl & outputLabel) virtual inherited
Automatically translate all the output names tagged as Auto in the translation table If a output name does not translate an error will be thrown by one of the support members.
The results of the translations will be stored in the outputLabel PVL based on the OutputPosition keywords in the translation table.
Parameters
outputLabel The PVL to add the translated keywords to.
Reimplemented in Isis::PvlToPvlTranslationManager.
References Isis::LabelTranslationManager::CreateContainer(), Isis::LabelTranslationManager::DoTranslation(), Isis::PvlObject::group(), Isis::PvlObject::groups(), Isis::PvlTranslationTable::IsAuto(), Isis::PvlTranslationTable::IsOptional(), Isis::PvlContainer::name(), and Isis::PvlTranslationTable::TranslationTable().
Auto() [3/3]
void Isis::PvlToXmlTranslationManager::Auto (QDomDocument & outputLabel)
Automatically translate all the output names found in the translation table.
If a output name does not translate an error will be thrown by one of the support members. If the output name is translated, store the translated key, value pairs in the QDomDocument.
Parameters
outputLabel A reference to the output QDomDocument label
References createParentElements(), doTranslation(), Isis::PvlObject::group(), Isis::PvlObject::groups(), Isis::PvlTranslationTable::IsAuto(), Isis::PvlTranslationTable::IsOptional(), Isis::PvlContainer::name(), and Isis::PvlTranslationTable::TranslationTable().
Referenced by Auto(), Isis::ProcessExportPds4::displaySettings(), Isis::ProcessExportPds4::fileAreaObservational(), Isis::ProcessExportPds4::identificationArea(), Isis::ProcessExportPds4::StandardAllMapping(), Isis::ProcessExportPds4::standardInstrument(), Isis::ProcessExportPds4::translateBandBinImage(), Isis::ProcessExportPds4::translateBandBinSpectrumBinSet(), and Isis::ProcessExportPds4::translateBandBinSpectrumUniform().
checkDependencies()
bool Isis::PvlToXmlTranslationManager::checkDependencies (QDomElement element, PvlKeyword dependencies, bool isDebug) const protected
CreateContainer()
PvlContainer * Isis::LabelTranslationManager::CreateContainer (const QString translationGroupName, Pvl & pvl) protected virtual inherited
Creates all parent PVL containers for an output keyword.
If any parent containers already exist then they will not be recreated.
Parameters
translationGroupName The name of the output keyword. The OutputPosition keyword in the translation group for translationGroupName will be used to determine which containers are made.
pvl The PVL file to create the containers in.
Returns
PvlContainer The immediate parent container for translationGroupName.
Reimplemented in Isis::PvlToPvlTranslationManager.
References Isis::PvlObject::addGroup(), Isis::PvlObject::addObject(), Isis::PvlObject::findGroup(), Isis::PvlObject::findObject(), Isis::PvlObject::hasGroup(), Isis::PvlObject::hasObject(), Isis::PvlTranslationTable::OutputPosition(), and Isis::PvlKeyword::size().
Referenced by Isis::LabelTranslationManager::Auto(), and Isis::PvlToPvlTranslationManager::CreateContainer().
createParentElements()
QDomElement * Isis::PvlToXmlTranslationManager::createParentElements (const QString translationGroupName, QDomElement & xmlRootElement) protected
Read the OutputPosition for the translation group name passed and create any parent elements specified by OutputPosition to prepare for translation.
Parameters
const QString translationGroupName Name of the translation group we will grab OutputPosition from.
QDomElement &xmlRootElement The XML document root element to add to.
Returns
QDomElement * Returns a pointer to the parent element right above the element we are going to create when the caller starts the translation.
References Isis::PvlTranslationTable::OutputPosition(), Isis::LabelTranslationManager::parseSpecification(), and Isis::PvlKeyword::size().
Referenced by Auto().
DoTranslation()
PvlKeyword Isis::LabelTranslationManager::DoTranslation (const QString outputName) protected virtual inherited
Translate the requested output name to output values using the input name and values or default value.
Parameters
outputName The output name used to identify the input keyword to be translated.
Returns
PvlKeyword A keyword containing the output name and output value.
@TODO output units
Reimplemented in Isis::PvlToPvlTranslationManager.
References Isis::LabelTranslationManager::Translate().
Referenced by Isis::LabelTranslationManager::Auto().
doTranslation()
void Isis::PvlToXmlTranslationManager::doTranslation (PvlGroup transGroup, QDomElement & parentElement) protected
Translate the requested output name to output values using the input name and values or default value.
Parameters
transGroupName The output name used to identify the input keyword to be translated.
parentElement The element that is the parent of the new QDomElement, if a new element is created. If a new element is not created, then parentElement will have an attribute added to it.
References addAttributes(), addSiblings(), Isis::PvlContainer::findKeyword(), GetContainer(), Isis::PvlContainer::hasKeyword(), Isis::PvlTranslationTable::InputGroup(), Isis::PvlTranslationTable::InputKeywordName(), Isis::PvlContainer::name(), Isis::PvlKeyword::name(), Isis::PvlTranslationTable::OutputName(), Isis::LabelTranslationManager::parseSpecification(), setElementValue(), Isis::PvlTranslationTable::Translate(), and Isis::PvlKeyword::unit().
Referenced by Auto().
findTranslationGroup()
const PvlGroup & Isis::PvlTranslationTable::findTranslationGroup (const QString translationGroupName) const protected inherited
Searches for translation group with the given name.
See also
PvlObject::findGroup()
Parameters
translationGroupName The name of the PVL translation group used to identify the input/output keywords to be translated. Often, this is the same as the output keyword name.
Returns
const PvlGroup& The first PVL group with the given name.
Exceptions
IException::Programmer - "Unable to find translation group in file."
References _FILEINFO_, and Isis::PvlContainer::fileName().
GetContainer()
const PvlContainer * Isis::PvlToXmlTranslationManager::GetContainer (const PvlKeyword & inputGroup) const protected virtual
Return a container from the input label with the path given by the "InputPosition" keyword of the translation table.
Parameters
inputGroup The InputPosition keyword
Returns
PvlContainer* Pointer to the PvlContainer found
References Isis::PvlObject::findGroup(), Isis::PvlObject::findObject(), Isis::PvlObject::hasGroup(), Isis::PvlObject::hasObject(), Isis::PvlKeyword::size(), and Isis::PvlKeyword::stringEqual().
Referenced by doTranslation(), InputHasKeyword(), InputKeyword(), and Translate().
hasInputDefault()
bool Isis::PvlTranslationTable::hasInputDefault (const QString translationGroupName) protected inherited
Determines whether the given group has a default input value.
This method returns true if the translation group contains a PvlKeyword with the name "InputDefault". Note: no value needs to be assigned to this keyword.
Parameters
translationGroupName The name of the PVL translation group used to identify the input/output keywords to be translated. Often, this is the same as the output keyword name.
Returns
bool Indicates whether the given group has an InputDefault keyword.
References Isis::PvlContainer::hasKeyword().
Referenced by Isis::XmlToPvlTranslationManager::Translate().
InputDefault()
QString Isis::PvlTranslationTable::InputDefault (const QString translationGroupName) const inherited
Returns the input default value from the translation table corresponding to the output name argument.
Parameters
translationGroupName The name of the PVL translation group used to identify the input/output keywords to be translated. Often, this is the same as the output keyword name.
Returns
QString The input default value.
References Isis::PvlContainer::hasKeyword().
Referenced by Isis::XmlToPvlTranslationManager::Translate().
InputGroup()
PvlKeyword Isis::PvlTranslationTable::InputGroup (const QString translationGroupName, const int inst = 0) const virtual inherited
Returns the input group name from the translation table corresponding to the output name argument.
Parameters
translationGroupName The name of the PVL translation group used to identify the input/output keywords to be translated. Often, this is the same as the output keyword name.
inst The occurence number of the "InputGroup" keyword (first one is zero)
Returns
QString The input group name
Exceptions
IException::Programmer - "Keyword [InputPosition] cannot have a comma [,] in the value."
References _FILEINFO_, Isis::PvlContainer::begin(), Isis::PvlContainer::end(), Isis::PvlContainer::findKeyword(), and Isis::PvlKeyword::size().
Referenced by Isis::PvlToPvlTranslationManager::DoTranslation(), doTranslation(), Isis::PvlToPvlTranslationManager::InputHasKeyword(), InputHasKeyword(), Isis::PvlToPvlTranslationManager::InputKeyword(), InputKeyword(), Isis::PvlToPvlTranslationManager::Translate(), and Translate().
InputHasKeyword()
bool Isis::PvlToXmlTranslationManager::InputHasKeyword (const QString transGroupName) virtual
Indicates if the input keyword corresponding to the output name exists in the label.
Parameters
transGroupName The output name used to identify the input keyword.
Returns
bool If the input keyword exists in the input label.
References GetContainer(), Isis::PvlContainer::hasKeyword(), Isis::PvlTranslationTable::InputGroup(), and Isis::PvlTranslationTable::InputKeywordName().
InputKeyword()
const PvlKeyword & Isis::PvlToXmlTranslationManager::InputKeyword (const QString transGroupName) const virtual
Uses the translation file group name to find the input label's PvlKeyword that corresponds to the InputKey value of the translation table and returns it, if found.
Parameters
transGroupName The name of the translation group for this InputKey.
Returns
PvlKeyword The input PvlKeyword for the translation group.
Exceptions
IException::Programmer
References _FILEINFO_, Isis::PvlContainer::fileName(), Isis::PvlContainer::findKeyword(), GetContainer(), Isis::PvlContainer::hasKeyword(), Isis::PvlTranslationTable::InputGroup(), Isis::PvlTranslationTable::InputKeywordName(), Isis::PvlKeyword::name(), Isis::IException::Programmer, Isis::PvlKeyword::size(), and Isis::PvlTranslationTable::TranslationTable().
InputKeywordName()
QString Isis::PvlTranslationTable::InputKeywordName (const QString translationGroupName) const virtual inherited
Returns the input keyword name from the translation table corresponding to the output name argument.
Parameters
translationGroupName The name of the PVL translation group used to identify the input/output keywords to be translated. Often, this is the same as the output keyword name.
Returns
QString The input keyword name
Exceptions
IException::Programmer
References Isis::PvlContainer::hasKeyword().
Referenced by doTranslation(), Isis::PvlToPvlTranslationManager::InputHasKeyword(), InputHasKeyword(), Isis::PvlToPvlTranslationManager::InputKeyword(), InputKeyword(), Isis::PvlToPvlTranslationManager::Translate(), and Translate().
IsAuto()
bool Isis::PvlTranslationTable::IsAuto (const QString translationGroupName) protected inherited
Determines whether the given group should be automatically translated.
This method returns true if the translation group contains a PvlKeyword with the name "Auto". Note: no value is assigned to this keyword.
Parameters
translationGroupName The name of the PVL translation group used to identify the input/output keywords to be translated. Often, this is the same as the output keyword name.
Returns
bool Indicates whether the given group has an Auto keyword.
References Isis::PvlContainer::hasKeyword().
Referenced by Isis::LabelTranslationManager::Auto(), Isis::PvlToPvlTranslationManager::Auto(), and Auto().
IsOptional()
bool Isis::PvlTranslationTable::IsOptional (const QString translationGroupName) protected inherited
Determines whether the translation group is optional.
This method returns true if the translation group contains a PvlKeyword with the name "Optional". Note: no value is assigned to this keyword.
Parameters
translationGroupName The name of the PVL translation group used to identify the input/output keywords to be translated. Often, this is the same as the output keyword name.
Returns
bool Indicates whether the given group has an Optional keyword.
References Isis::PvlContainer::hasKeyword().
Referenced by Isis::LabelTranslationManager::Auto(), Isis::PvlToPvlTranslationManager::Auto(), and Auto().
OutputName()
QString Isis::PvlTranslationTable::OutputName (const QString translationGroupName) protected inherited
Retrieves a string containing the value of the OutputName keyword for the translation group with the given name.
Parameters
translationGroupName The name of the PVL translation group used to identify the input/output keywords to be translated. Often, this is the same as the output keyword name.
Returns
QString The value of the OutputName keyword from the given translation group.
References Isis::PvlContainer::hasKeyword().
Referenced by Isis::PvlToPvlTranslationManager::DoTranslation(), and doTranslation().
OutputPosition()
PvlKeyword Isis::PvlTranslationTable::OutputPosition (const QString translationGroupName) protected inherited
Retrieves the OutputPosition PvlKeyword for the translation group with the given name.
Parameters
translationGroupName The name of the PVL translation group used to identify the input/output keywords to be translated. Often, this is the same as the output keyword name.
Returns
PvlKeyword The OutputPosition keyword from the given translation group.
Exceptions
IException::Programmer - "Unable to find translation keyword [OutputPostion] in translation group in file."
References _FILEINFO_, and Isis::PvlContainer::hasKeyword().
Referenced by Isis::LabelTranslationManager::CreateContainer(), and createParentElements().
parseSpecification()
QStringList Isis::LabelTranslationManager::parseSpecification (QString specification) const virtual inherited
Parses and validates a dependency specification.
Parameters
specification The dependency specification string.
Returns
QStringList The dependency split into 3 components
the type (att or tag)
the name of what to check
the value to check for
Exceptions
IException::Programmer "Malformed dependency specification."
IException::Programmer "Specification does not have two components separated by [@], the type of dependency and the name-value pair.
IException::Programmer "Dependency type specification is invalid. Valid types are [att] and [tag]"
IException::Programmer "Name-value specification does not have two components separated by [|]."
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by addAttributes(), addSiblings(), Isis::XmlToPvlTranslationManager::checkDependencies(), createParentElements(), and doTranslation().
resetElementValue()
void Isis::PvlToXmlTranslationManager::resetElementValue (QDomElement & element, QString value, QString units = "") static
Reset the QDomElement's value, and units, if units != "".
Parameters
element The QDomElement whose value needs to be reset.
value The value to set.
units A string containing the unit specification.
setElementValue()
void Isis::PvlToXmlTranslationManager::setElementValue (QDomElement & element, QString value, QString units = "") static
Set the QDomElement's value, and units, if units != "".
Parameters
element The QDomElement whose value needs to be set.
value The value to set.
units A string containing the unit specification.
Referenced by addElement(), addSiblings(), and doTranslation().
SetLabel()
void Isis::PvlToXmlTranslationManager::SetLabel (Pvl & inputLabel)
Internalizes a Pvl formatted label for translation.
Parameters
inputLabel The Pvl formatted label to be translated.
Translate() [1/2]
QString Isis::PvlTranslationTable::Translate (const QString translationGroupName, const QString inputKeyValue = "") const inherited
Translates a single output value from the given translation group name and input value.
Parameters
translationGroupName The name of the PVL translation group used to identify the input/output keywords to be translated. Often, this is the same as the output keyword name.
inputKeyValue The value to be translated, from the input keyword.
Returns
QString The translated value, for the output keyword.
Exceptions
IException::Programmer - "No value or default value to translate for translation group."
IException::Programmer - "Unable to find translation value in file."
References _FILEINFO_, Isis::PvlContainer::begin(), Isis::PvlContainer::end(), Isis::PvlContainer::fileName(), Isis::PvlContainer::findKeyword(), and Isis::PvlContainer::hasKeyword().
Referenced by Isis::PvlToPvlTranslationManager::DoTranslation(), doTranslation(), Isis::PvlToPvlTranslationManager::Translate(), Isis::XmlToPvlTranslationManager::Translate(), and Translate().
Translate() [2/2]
QString Isis::PvlToXmlTranslationManager::Translate (QString transGroupName, int inputIndex = 0) virtual
Returns a translated value.
The output name is used to find the input group, keyword, default and tranlations in the translation table. If the keyword does not exist in the input label, the input default if available will be used as the input value. This input value is then used to search all of the translations. If a match is found the translated value is returned.
Parameters
transGroupName The output name used to identify the input keyword to be translated.
findex The index into the input keyword array. Defaults to 0
Returns
QString The translated value.
Implements Isis::LabelTranslationManager.
References GetContainer(), Isis::PvlContainer::hasKeyword(), Isis::PvlTranslationTable::InputGroup(), Isis::PvlTranslationTable::InputKeywordName(), and Isis::PvlTranslationTable::Translate().
TranslationTable() [1/2]
Pvl & Isis::PvlTranslationTable::TranslationTable () protected inherited
Protected accessor for pvl translation table passed into class.
This method returns a reference to the translation table member.
Returns
Pvl The translation table as a PVL object.
Referenced by Isis::LabelTranslationManager::Auto(), Isis::PvlToPvlTranslationManager::Auto(), Auto(), Isis::PvlToPvlTranslationManager::DoTranslation(), Isis::PvlToPvlTranslationManager::InputKeyword(), InputKeyword(), and Isis::XmlToPvlTranslationManager::Translate().
TranslationTable() [2/2]
const Pvl & Isis::PvlTranslationTable::TranslationTable () const protected inherited
Protected accessor for const pvl translation table passed into class.
This method returns a const reference to the translation table member.
Returns
Pvl The translation table as a PVL object.
validKeywords()
vector< pair< QString, int > > Isis::PvlToXmlTranslationManager::validKeywords () const protected virtual
Returns a vector of valid keyword names and their sizes.
A size of -1 indicates that the keyword can be any size.
Returns
vector<pair<QString,int>> A vector of valid keyword names and their sizes.
See also
PvlTranslationTable::validKeywords()
Reimplemented from Isis::PvlTranslationTable.
References validKeywords(), and Isis::PvlTranslationTable::validKeywords().
Referenced by validKeywords().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/PvlToXmlTranslationManager/PvlToXmlTranslationManager.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/PvlToXmlTranslationManager/PvlToXmlTranslationManager.cpp