Isis Developer Reference: Isis::MatchPoint Class Reference
Isis::MatchPoint Class Reference
Structure containing comprehensive registration info/results.
#include <GruenTypes.h>
Public Member Functions
MatchPoint ()
MatchPoint (const AffineRadio &radio)
MatchPoint (const PointPair &point)
~MatchPoint ()
int getStatus () const
const MatchPoint & setStatus (int status)
bool isValid () const
double getEigen () const
Coordinate getAffinePoint (const Coordinate &coord=Coordinate(0.0, 0.0)) const
Return registration offset of a given chip coordinate from center
Public Attributes
PointPair m_point
AffineRadio m_affine
Analysis m_analysis
int m_nIters
int m_status
Detailed Description
Structure containing comprehensive registration info/results.
This structure is used to contain all the parameters from a Gruen registration process. It contains status of the match as well as point analysis, error analysis and affine/radiometric paramters. The offset of the registration can be obtained through a call to getAffinePoint() using the default point coordinate of (0,0).
Author
2011-05-18 Kris Becker
Constructor & Destructor Documentation
MatchPoint() [1/3]
Isis::MatchPoint::MatchPoint () inline
MatchPoint() [2/3]
Isis::MatchPoint::MatchPoint (const AffineRadio & radio) inline
MatchPoint() [3/3]
Isis::MatchPoint::MatchPoint (const PointPair & point) inline
~MatchPoint()
Isis::MatchPoint::~MatchPoint () inline
Member Function Documentation
getAffinePoint()
Coordinate Isis::MatchPoint::getAffinePoint (const Coordinate & coord = Coordinate(0.0, 0.0)) const inline
Return registration offset of a given chip coordinate from center
References Isis::AffineRadio::getPoint(), and m_affine.
getEigen()
double Isis::MatchPoint::getEigen () const inline
References Isis::Analysis::getEigen(), and m_analysis.
Referenced by Isis::SmtkPoint::GoodnessOfFit(), and Isis::Gruen::Registration().
getStatus()
int Isis::MatchPoint::getStatus () const inline
References m_status.
isValid()
bool Isis::MatchPoint::isValid () const inline
References m_status.
Referenced by Isis::Gruen::Registration().
setStatus()
const MatchPoint& Isis::MatchPoint::setStatus (int status) inline
References m_status.
Referenced by Isis::Gruen::Registration().
Member Data Documentation
m_affine
AffineRadio Isis::MatchPoint::m_affine
Referenced by Isis::SmtkPoint::getAffine(), getAffinePoint(), and Isis::Gruen::Registration().
m_analysis
Analysis Isis::MatchPoint::m_analysis
Referenced by Isis::SmtkMatcher::Create(), getEigen(), and Isis::Gruen::Registration().
m_nIters
int Isis::MatchPoint::m_nIters
Referenced by Isis::Gruen::Registration().
m_point
PointPair Isis::MatchPoint::m_point
Referenced by Isis::SmtkMatcher::Clone(), and Isis::SmtkPoint::getPoints().
m_status
int Isis::MatchPoint::m_status
Referenced by getStatus(), isValid(), and setStatus().
The documentation for this class was generated from the following file:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Gruen/GruenTypes.h