Isis Developer Reference: Isis::CameraFocalPlaneMap Class Reference
Isis::CameraFocalPlaneMap Class Reference
Convert between distorted focal plane and detector coordinates.
#include <CameraFocalPlaneMap.h>
Public Types
enum FocalPlaneXDependencyType { Sample = 1 , Line = 2 }
Focal plane x dependency indicates whether the x value of the focal plane coordinate maps to a sample or a line.
Public Member Functions
CameraFocalPlaneMap (Camera *parent, const int naifIkCode)
Construct mapping between detectors and focal plane x/y.
CameraFocalPlaneMap (const int naifIkCode)
Construct mapping between detectors and focal plane x/y.
CameraFocalPlaneMap (Camera *parent, Affine &affine)
Added new method to allow programmer to pass in affine coefficients.
virtual ~CameraFocalPlaneMap ()
Destructor.
virtual bool SetDetector (const double sample, const double line)
Compute distorted focal plane coordinate from detector position (sampel,line)
virtual bool SetFocalPlane (const double dx, const double dy)
Compute detector position (sample,line) from focal plane coordinates.
double FocalPlaneX () const
double FocalPlaneY () const
double DetectorSample () const
double DetectorLine () const
double CenteredDetectorSample () const
double CenteredDetectorLine () const
void SetDetectorOrigin (const double sample, const double line)
Set the detector origin.
double DetectorLineOrigin () const
double DetectorSampleOrigin () const
void SetDetectorOffset (const double sampleOffset, const double lineOffset)
Set the detector offset.
double DetectorLineOffset () const
double DetectorSampleOffset () const
void SetTransL (const QVector< double > transL)
Set the affine coefficients for converting destorted (x,y) to a detector Line.
void SetTransS (const QVector< double > transS)
Set the affine coefficients for converting destorted (x,y) to a detector Sample.
void SetTransX (const QVector< double > transX)
Set the affine coefficients for converting detector (sample,line) to a distorted X.
void SetTransY (const QVector< double > transY)
Set the affine coefficients for converting detector (sample,line) to a distorted Y.
const double * TransL () const
const double * TransS () const
const double * TransX () const
const double * TransY () const
int FocalPlaneXDependency ()
Return the focal plane x dependency variable.
double SignMostSigX ()
Return the sign of the p_transx coefficient with the greatest magnitude.
double SignMostSigY ()
Return the sign of the p_transy coefficient with the greatest magnitude.
Protected Member Functions
void ComputeCentered ()
Convenience method to center detector origin (use when inheriting)
void ComputeUncentered ()
Convenience method to center detector origin (use when inheriting)
Protected Attributes
Camera * p_camera
Camera of the image.
double p_detectorLineOrigin
The origin line of the detector.
double p_detectorSampleOrigin
The origin sample of the detector.
double p_focalPlaneX
x value of focal plane coordinate
double p_focalPlaneY
y value of focal plane coordinate
double p_detectorLine
line value of the detector
double p_detectorSample
sample value of the detector
double p_centeredDetectorSample
Detector sample position.
double p_centeredDetectorLine
Detector line position.
double p_detectorLineOffset
Offset of the detector origin line from the average.
double p_detectorSampleOffset
offset of the detector origin sample from the average
double p_transx [3]
The x transition from detector to distorted.
double p_transy [3]
The y transition from detector to distorted.
double p_itranss [3]
The x transition from distorted to detector.
double p_itransl [3]
The y transition from distorted to detector.
Detailed Description
Convert between distorted focal plane and detector coordinates.
This base class is used to convert between distorted focal plane coordinates (x/y) in millimeters and detector coordinates in pixels. The class expects to find a set of coefficients in the naif instrument (or instrument addendum) kernel that describe the transform from detector to focal plane and vice versa. The transform from detector to focal plane is:
x = transx[0] + sample * transx[1] + line * transx[2];
y = transy[0] + sample * transy[1] + line * transy[2];
where, transx and transy are the coefficients from the naif kernel.
The should be in the form of:
INSxxxxxx_TRANSX = (a, b, c)
INSxxxxxx_TRANSY = (d, e, f)
where, xxxxxx is the NAIF instrument id code.
Likewise, the inverse transform is:
samp = itranss[0] + x * itranss[1] + y * itranss[2];
line = itransl[0] + x * itransl[1] + y * itransl[2];
where, itranss and itranss are the coefficients from the naif kernel.
The should be in the form of:
INSxxxxxx_ITRANSS = (a, b, c)
INSxxxxxx_ITRANSL = (d, e, f)
where, xxxxxx is the NAIF instrument id code.
Author
2005-02-05 Jeff Anderson
See also
Camera
Member Enumeration Documentation
FocalPlaneXDependencyType
enum Isis::CameraFocalPlaneMap::FocalPlaneXDependencyType
Focal plane x dependency indicates whether the x value of the focal plane coordinate maps to a sample or a line.
Enumerator
Sample
The x value of the focal plane maps to a sample.
Line
The x value of the focal plane maps to a line.
Constructor & Destructor Documentation
CameraFocalPlaneMap() [1/3]
Isis::CameraFocalPlaneMap::CameraFocalPlaneMap (Camera * parent, const int naifIkCode)
Construct mapping between detectors and focal plane x/y.
Parameters
parent parent camera that will use this map
naifIkCode code of the naif instrument for reading coefficients
CameraFocalPlaneMap() [2/3]
Isis::CameraFocalPlaneMap::CameraFocalPlaneMap (const int naifIkCode)
Construct mapping between detectors and focal plane x/y.
Parameters
naifIkCode code of the naif instrument for reading coefficients
CameraFocalPlaneMap() [3/3]
Isis::CameraFocalPlaneMap::CameraFocalPlaneMap (Camera * parent, Affine & affine)
Added new method to allow programmer to pass in affine coefficients.
Author
janderson (3/25/2014)
Parameters
parent Parent camera
affine Affine transform containing the coefficients for both transforms to (samp,line) to (x,y) and reverse
References Isis::Affine::Coefficients(), Isis::Affine::InverseCoefficients(), p_camera, p_detectorLineOffset, p_detectorLineOrigin, p_detectorSampleOffset, p_detectorSampleOrigin, p_itransl, p_itranss, p_transx, p_transy, and Isis::Camera::SetFocalPlaneMap().
~CameraFocalPlaneMap()
Isis::CameraFocalPlaneMap::~CameraFocalPlaneMap () virtual
Destructor.
Member Function Documentation
CenteredDetectorLine()
double Isis::CameraFocalPlaneMap::CenteredDetectorLine () const
Returns
The centered detector line
References p_centeredDetectorLine.
CenteredDetectorSample()
double Isis::CameraFocalPlaneMap::CenteredDetectorSample () const
Returns
The centered detector sample
References p_centeredDetectorSample.
ComputeCentered()
void Isis::CameraFocalPlaneMap::ComputeCentered () protected
Convenience method to center detector origin (use when inheriting)
References p_centeredDetectorLine, p_centeredDetectorSample, p_detectorLine, p_detectorLineOrigin, p_detectorSample, and p_detectorSampleOrigin.
Referenced by SetDetector().
ComputeUncentered()
void Isis::CameraFocalPlaneMap::ComputeUncentered () protected
Convenience method to center detector origin (use when inheriting)
References p_centeredDetectorLine, p_centeredDetectorSample, p_detectorLine, p_detectorLineOrigin, p_detectorSample, and p_detectorSampleOrigin.
Referenced by SetFocalPlane().
DetectorLine()
double Isis::CameraFocalPlaneMap::DetectorLine () const
Returns
The detector line
References p_detectorLine.
Referenced by Isis::ControlPoint::ComputeResiduals(), Isis::LoMediumDistortionMap::SetDistortion(), Isis::LoMediumDistortionMap::SetFocalPlane(), Isis::OsirisRexOcamsDistortionMap::SetFocalPlane(), Isis::Camera::SetRightAscensionDeclination(), Isis::LineScanCameraSkyMap::SetSky(), Isis::LoMediumDistortionMap::SetUndistortedFocalPlane(), and Isis::OsirisRexOcamsDistortionMap::SetUndistortedFocalPlane().
DetectorLineOffset()
double Isis::CameraFocalPlaneMap::DetectorLineOffset () const
Returns
The detector line offset
References p_detectorLineOffset.
Referenced by Isis::LineScanCameraDetectorMap::SetParent(), Isis::VariableLineScanCameraDetectorMap::SetParent(), and Isis::LineScanCameraSkyMap::SetSky().
DetectorLineOrigin()
double Isis::CameraFocalPlaneMap::DetectorLineOrigin () const
Returns
The detector line origin
References p_detectorLineOrigin.
Referenced by Isis::OsirisRexDistortionMap::OsirisRexDistortionMap(), Isis::OsirisRexOcamsDistortionMap::OsirisRexOcamsDistortionMap(), Isis::ReseauDistortionMap::SetFocalPlane(), and Isis::ReseauDistortionMap::SetUndistortedFocalPlane().
DetectorSample()
double Isis::CameraFocalPlaneMap::DetectorSample () const
Returns
The detector sample
References p_detectorSample.
Referenced by Isis::ControlPoint::ComputeResiduals(), Isis::LoMediumDistortionMap::SetDistortion(), Isis::LoMediumDistortionMap::SetFocalPlane(), Isis::OsirisRexOcamsDistortionMap::SetFocalPlane(), Isis::Camera::SetRightAscensionDeclination(), Isis::LoMediumDistortionMap::SetUndistortedFocalPlane(), and Isis::OsirisRexOcamsDistortionMap::SetUndistortedFocalPlane().
DetectorSampleOffset()
double Isis::CameraFocalPlaneMap::DetectorSampleOffset () const
Returns
The detector sample offset
References p_detectorSampleOffset.
DetectorSampleOrigin()
double Isis::CameraFocalPlaneMap::DetectorSampleOrigin () const
Returns
The detector sample origin
References p_detectorSampleOrigin.
Referenced by Isis::OsirisRexDistortionMap::OsirisRexDistortionMap(), Isis::OsirisRexOcamsDistortionMap::OsirisRexOcamsDistortionMap(), Isis::ReseauDistortionMap::SetFocalPlane(), and Isis::ReseauDistortionMap::SetUndistortedFocalPlane().
FocalPlaneX()
double Isis::CameraFocalPlaneMap::FocalPlaneX () const
Returns
The distorted focal plane x
References p_focalPlaneX.
Referenced by Isis::LoMediumDistortionMap::SetFocalPlane(), Isis::Camera::SetImage(), and Isis::LoMediumDistortionMap::SetUndistortedFocalPlane().
FocalPlaneXDependency()
int Isis::CameraFocalPlaneMap::FocalPlaneXDependency ()
Return the focal plane x dependency variable.
This method returns the image variable (sample or line) on which the focal plane x depends.
Returns
dependency variable
References Line, p_transx, and Sample.
FocalPlaneY()
double Isis::CameraFocalPlaneMap::FocalPlaneY () const
Returns
The distorted focal plane y
References p_focalPlaneY.
Referenced by Isis::LoMediumDistortionMap::SetFocalPlane(), Isis::Camera::SetImage(), and Isis::LoMediumDistortionMap::SetUndistortedFocalPlane().
SetDetector()
bool Isis::CameraFocalPlaneMap::SetDetector (const double sample, const double line) virtual
Compute distorted focal plane coordinate from detector position (sampel,line)
This method will compute both the distorted focal plane x/y and centered detector position given a detector position
Parameters
sample undistorted focal plane x in millimeters
line undistorted focal plane y in millimeters
Returns
conversion was successful
References ComputeCentered(), p_centeredDetectorLine, p_centeredDetectorSample, p_detectorLine, p_detectorSample, p_focalPlaneX, p_focalPlaneY, p_transx, and p_transy.
Referenced by Isis::LoMediumDistortionMap::SetFocalPlane(), Isis::Camera::SetImage(), and Isis::LoMediumDistortionMap::SetUndistortedFocalPlane().
SetDetectorOffset()
void Isis::CameraFocalPlaneMap::SetDetectorOffset (const double sampleOffset, const double lineOffset)
Set the detector offset.
This is used to set the offset between the detector origin and the average location in detector pixels where the image is being viewed. If not set the offset are both 0.0
Parameters
sampleOffset sample offset in pixels
lineOffset sample offset in lines
References p_detectorLineOffset, and p_detectorSampleOffset.
Referenced by Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::ThemisIrCamera::SetBand(), and Isis::ThemisIrCamera::ThemisIrCamera().
SetDetectorOrigin()
void Isis::CameraFocalPlaneMap::SetDetectorOrigin (const double sample, const double line)
Set the detector origin.
This is used to set the origin of the detector. Typically the middle of the detector. For example, a 512x512 dectector would have the origin at (256.5,256.5). If not set both are 0.
Parameters
sample detector sample at the origin
line detector line at the origin
References p_detectorLineOrigin, and p_detectorSampleOrigin.
Referenced by Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ClipperWacFcCamera::ClipperWacFcCamera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HiresCamera::HiresCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::IdealCamera::IdealCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LwirCamera::LwirCamera(), Isis::MarciCamera::MarciCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::NirCamera::NirCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::LroWideAngleCamera::SetBand(), Isis::ThemisIrCamera::SetBand(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::ThemisVisCamera::ThemisVisCamera(), Isis::UvvisCamera::UvvisCamera(), Isis::VikingCamera::VikingCamera(), and Isis::VoyagerCamera::VoyagerCamera().
SetFocalPlane()
bool Isis::CameraFocalPlaneMap::SetFocalPlane (const double dx, const double dy) virtual
Compute detector position (sample,line) from focal plane coordinates.
NOTE: This is detector (sample, line) not necessarily image (sample, line). If the image was reformatted from what was collected the two differ. See the New Horizons LEISA camera for an example (LEISA is a frame camera being treated as a line scan camera).
This method will compute both the centered and normal detector position given a distorted focal plane coordinate.
Parameters
dx distorted focal plane x in millimeters
dy distorted focal plane y in millimeters
Returns
conversion was successful
References ComputeUncentered(), p_centeredDetectorLine, p_centeredDetectorSample, p_focalPlaneX, p_focalPlaneY, p_itransl, and p_itranss.
Referenced by Isis::ControlPoint::ComputeResiduals(), Isis::LoMediumDistortionMap::SetDistortion(), Isis::LoMediumDistortionMap::SetFocalPlane(), Isis::Camera::SetRightAscensionDeclination(), Isis::LineScanCameraSkyMap::SetSky(), and Isis::LoMediumDistortionMap::SetUndistortedFocalPlane().
SetTransL()
void Isis::CameraFocalPlaneMap::SetTransL (const QVector< double > transL)
Set the affine coefficients for converting destorted (x,y) to a detector Line.
Parameters
transL Vector of the affine coefficients
References p_itransl.
Referenced by Isis::NewHorizonsLeisaCamera::SetBand().
SetTransS()
void Isis::CameraFocalPlaneMap::SetTransS (const QVector< double > transS)
Set the affine coefficients for converting destorted (x,y) to a detector Sample.
Parameters
transS Vector of the affine coefficients
References p_itranss.
Referenced by Isis::NewHorizonsLeisaCamera::SetBand().
SetTransX()
void Isis::CameraFocalPlaneMap::SetTransX (const QVector< double > transX)
Set the affine coefficients for converting detector (sample,line) to a distorted X.
Parameters
transX Vector of the affine coefficients
References p_transx.
Referenced by Isis::NewHorizonsLeisaCamera::SetBand().
SetTransY()
void Isis::CameraFocalPlaneMap::SetTransY (const QVector< double > transY)
Set the affine coefficients for converting detector (sample,line) to a distorted Y.
Parameters
transY Vector of the affine coefficients
References p_transy.
Referenced by Isis::NewHorizonsLeisaCamera::SetBand().
SignMostSigX()
double Isis::CameraFocalPlaneMap::SignMostSigX ()
Return the sign of the p_transx coefficient with the greatest magnitude.
This method returns a +1. or -1. based on the sign of the p_transx coefficient with the greatest magnitude. Only p_transx[1] and p_transx[2] are compared since p_transx[0] is used as a constant in the affine transformation.
Returns
sign of most significant coefficient
References p_transx.
SignMostSigY()
double Isis::CameraFocalPlaneMap::SignMostSigY ()
Return the sign of the p_transy coefficient with the greatest magnitude.
This method returns a +1 or -1 based on the sign of the p_transy coefficient with the greatest magnitude. Only p_transy[1] and p_transy[2] are compared since p_transy[0] is used as a constant in the affine transformation.
Returns
sign of most significant coefficient
References p_transy.
TransL()
const double * Isis::CameraFocalPlaneMap::TransL () const
Returns
The affine coefficients for converting distorted (x,y) to a detector Line
References p_itransl.
Referenced by Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera().
TransS()
const double * Isis::CameraFocalPlaneMap::TransS () const
Returns
The affine coefficients for converting distorted (x,y) to a detector Sample
References p_itranss.
Referenced by Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera().
TransX()
const double * Isis::CameraFocalPlaneMap::TransX () const
Returns
The affine coefficients for converting detector (sample,line) to a distorted X
References p_transx.
Referenced by Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera().
TransY()
const double * Isis::CameraFocalPlaneMap::TransY () const
Returns
The affine coefficients for converting detector (sample,line) to distorted Y
References p_transy.
Referenced by Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera().
Member Data Documentation
p_camera
Camera* Isis::CameraFocalPlaneMap::p_camera protected
Camera of the image.
Referenced by Isis::LroWideAngleCameraFocalPlaneMap::addFilter(), and CameraFocalPlaneMap().
p_centeredDetectorLine
double Isis::CameraFocalPlaneMap::p_centeredDetectorLine protected
Detector line position.
Referenced by CenteredDetectorLine(), ComputeCentered(), ComputeUncentered(), SetDetector(), and SetFocalPlane().
p_centeredDetectorSample
double Isis::CameraFocalPlaneMap::p_centeredDetectorSample protected
Detector sample position.
Referenced by CenteredDetectorSample(), ComputeCentered(), ComputeUncentered(), SetDetector(), and SetFocalPlane().
p_detectorLine
double Isis::CameraFocalPlaneMap::p_detectorLine protected
line value of the detector
Referenced by ComputeCentered(), ComputeUncentered(), DetectorLine(), and SetDetector().
p_detectorLineOffset
double Isis::CameraFocalPlaneMap::p_detectorLineOffset protected
Offset of the detector origin line from the average.
Referenced by CameraFocalPlaneMap(), DetectorLineOffset(), and SetDetectorOffset().
p_detectorLineOrigin
double Isis::CameraFocalPlaneMap::p_detectorLineOrigin protected
The origin line of the detector.
Referenced by CameraFocalPlaneMap(), ComputeCentered(), ComputeUncentered(), DetectorLineOrigin(), and SetDetectorOrigin().
p_detectorSample
double Isis::CameraFocalPlaneMap::p_detectorSample protected
sample value of the detector
Referenced by ComputeCentered(), ComputeUncentered(), DetectorSample(), and SetDetector().
p_detectorSampleOffset
double Isis::CameraFocalPlaneMap::p_detectorSampleOffset protected
offset of the detector origin sample from the average
Referenced by CameraFocalPlaneMap(), DetectorSampleOffset(), and SetDetectorOffset().
p_detectorSampleOrigin
double Isis::CameraFocalPlaneMap::p_detectorSampleOrigin protected
The origin sample of the detector.
Referenced by CameraFocalPlaneMap(), ComputeCentered(), ComputeUncentered(), DetectorSampleOrigin(), and SetDetectorOrigin().
p_focalPlaneX
double Isis::CameraFocalPlaneMap::p_focalPlaneX protected
x value of focal plane coordinate
Referenced by FocalPlaneX(), SetDetector(), and SetFocalPlane().
p_focalPlaneY
double Isis::CameraFocalPlaneMap::p_focalPlaneY protected
y value of focal plane coordinate
Referenced by FocalPlaneY(), SetDetector(), and SetFocalPlane().
p_itransl
double Isis::CameraFocalPlaneMap::p_itransl[3] protected
The y transition from distorted to detector.
Referenced by CameraFocalPlaneMap(), Isis::LroWideAngleCameraFocalPlaneMap::setBand(), SetFocalPlane(), SetTransL(), and TransL().
p_itranss
double Isis::CameraFocalPlaneMap::p_itranss[3] protected
The x transition from distorted to detector.
Referenced by CameraFocalPlaneMap(), Isis::LroWideAngleCameraFocalPlaneMap::setBand(), SetFocalPlane(), SetTransS(), and TransS().
p_transx
double Isis::CameraFocalPlaneMap::p_transx[3] protected
The x transition from detector to distorted.
Referenced by CameraFocalPlaneMap(), FocalPlaneXDependency(), Isis::LroWideAngleCameraFocalPlaneMap::setBand(), SetDetector(), SetTransX(), SignMostSigX(), and TransX().
p_transy
double Isis::CameraFocalPlaneMap::p_transy[3] protected
The y transition from detector to distorted.
Referenced by CameraFocalPlaneMap(), Isis::LroWideAngleCameraFocalPlaneMap::setBand(), SetDetector(), SetTransY(), SignMostSigY(), and TransY().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/CameraFocalPlaneMap/CameraFocalPlaneMap.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/CameraFocalPlaneMap/CameraFocalPlaneMap.cpp