Isis Developer Reference: Isis::EllipsoidShape Class Reference
Isis::EllipsoidShape Class Reference
Define shapes and provide utilities for ISIS targets.
#include <EllipsoidShape.h>
Public Member Functions
EllipsoidShape (Target *target)
Constructors.
EllipsoidShape ()
Initialize the EllipsoidShape.
~EllipsoidShape ()
Destructor.
bool intersectSurface (std::vector< double > observerPos, std::vector< double > lookDirection)
Intersect the shape model.
virtual void calculateDefaultNormal ()
Calculate the default normal of the current intersection point.
bool isDEM () const
Indicates that this shape model is not from a DEM.
void calculateLocalNormal (QVector< double * > cornerNeighborPoints)
Calculate the local surface normal of the current intersection point.
void calculateSurfaceNormal ()
Calculate the surface normal of the current intersection point.
Distance localRadius (const Latitude &lat, const Longitude &lon)
Get the local radius for a point on the surface.
void Initialize ()
Initializes the ShapeModel private variables.
virtual bool intersectSurface (const Latitude &lat, const Longitude &lon, const std::vector< double > &observerPos, const bool &backCheck=true)
Compute surface intersection with optional occlusion check.
virtual bool intersectSurface (const SurfacePoint &surfpt, const std::vector< double > &observerPos, const bool &backCheck=true)
Compute surface intersection with optional occlusion check.
virtual SurfacePoint * surfaceIntersection () const
Returns the surface intersection for this ShapeModel.
bool hasIntersection ()
Returns intersection status.
bool hasNormal () const
Returns surface point normal status.
bool hasLocalNormal () const
Returns surface point local normal status.
virtual void clearSurfacePoint ()
Clears or resets the current surface point.
virtual double emissionAngle (const std::vector< double > &sB)
Computes and returns emission angle, in degrees, given the observer position.
virtual double incidenceAngle (const std::vector< double > &uB)
Computes and returns incidence angle, in degrees, given the illuminator position.
virtual double phaseAngle (const std::vector< double > &sB, const std::vector< double > &uB)
Computes and returns phase angle, in degrees, given the positions of the observer and illuminator.
QString name () const
Gets the shape name.
void setHasIntersection (bool b)
Sets the flag to indicate whether this ShapeModel has an intersection.
virtual void setSurfacePoint (const SurfacePoint &surfacePoint)
Set surface intersection point.
virtual std::vector< double > normal ()
Returns the surface normal at the current intersection point.
virtual std::vector< double > localNormal ()
Returns the local surface normal at the current intersection point.
virtual bool isVisibleFrom (const std::vector< double > observerPos, const std::vector< double > lookDirection)
Default occulsion implementation.
Protected Member Functions
void setNormal (const std::vector< double >)
Sets the surface normal for the currect intersection point.
void setNormal (const double a, const double b, const double c)
Sets the surface normal for the currect intersection point.
void setLocalNormal (const std::vector< double >)
Sets the local normal for the currect intersection point.
void setLocalNormal (const double a, const double b, const double c)
Sets the local normal for the currect intersection point.
void setName (QString name)
Sets the shape name.
void calculateEllipsoidalSurfaceNormal ()
Calculates the ellipsoidal surface normal.
bool hasEllipsoidIntersection ()
Returns the status of the ellipsoid model intersection.
bool intersectEllipsoid (const std::vector< double > observerPosRelativeToTarget, const std::vector< double > &observerLookVectorToTarget)
Finds the intersection point on the ellipsoid model using the given position of the observer (spacecraft) and direction vector from the observer to the target (body).
bool hasValidTarget () const
Returns the status of the target.
std::vector< Distance > targetRadii () const
Returns the radii of the body in km.
void setHasNormal (bool status)
Sets the flag to indicate whether this ShapeModel has a surface normal.
void setHasLocalNormal (bool status)
Sets the flag to indicate whether this ShapeModel has a local normal.
double resolution ()
Convenience method to get pixel resolution (m/pix) at current intersection point.
Detailed Description
Define shapes and provide utilities for ISIS targets.
This class will define shapes of ISIS target bodies as well as provide utilities to retrieve radii and photometric information.
Author
2010-08-02 Debbie A. Cook
Constructor & Destructor Documentation
EllipsoidShape() [1/2]
Isis::EllipsoidShape::EllipsoidShape (Target * target)
Constructors.
Initialize the EllipsoidShape.
Parameters
pvl Valid ISIS cube label.
References Isis::ShapeModel::setName().
EllipsoidShape() [2/2]
Isis::EllipsoidShape::EllipsoidShape ()
Initialize the EllipsoidShape.
Parameters
pvl Valid ISIS cube label.
References Isis::ShapeModel::setName().
~EllipsoidShape()
Isis::EllipsoidShape::~EllipsoidShape () inline
Destructor.
Member Function Documentation
calculateDefaultNormal()
void Isis::EllipsoidShape::calculateDefaultNormal () virtual
Calculate the default normal of the current intersection point.
Calculate default normal.
Implements Isis::ShapeModel.
References calculateSurfaceNormal().
calculateEllipsoidalSurfaceNormal()
void Isis::ShapeModel::calculateEllipsoidalSurfaceNormal () protected inherited
Calculates the ellipsoidal surface normal.
References _FILEINFO_.
calculateLocalNormal()
void Isis::EllipsoidShape::calculateLocalNormal (QVector< double * > cornerNeighborPoints) virtual
Calculate the local surface normal of the current intersection point.
Calculates the unit normal to an ellipsoid at the point of intersection.
In the event that the three axial radii of the body are equal, this method returns the normal vector for a sphere.
The implicit equation for an ellipsoid is: U(x,y,z) = x^2/a^2 + y^2/b^2 + z^2/c^2 -1 =0
The normal to U(x,y,z) is given by:
n = grad(U)/norm(U)
i.e. as:
n = <ux,uy,uz>/sqrt(ux^2,+uy^2+uz^2)
Parameters
cornerNeighborPoints
Implements Isis::ShapeModel.
References _FILEINFO_, Isis::NaifStatus::CheckErrors(), Isis::SurfacePoint::GetX(), Isis::SurfacePoint::GetY(), Isis::SurfacePoint::GetZ(), Isis::ShapeModel::hasIntersection(), Isis::Displacement::kilometers(), Isis::ShapeModel::normal(), Isis::IException::Programmer, Isis::ShapeModel::setHasLocalNormal(), Isis::ShapeModel::setLocalNormal(), Isis::ShapeModel::surfaceIntersection(), and Isis::ShapeModel::targetRadii().
Referenced by calculateSurfaceNormal().
calculateSurfaceNormal()
void Isis::EllipsoidShape::calculateSurfaceNormal () virtual
Calculate the surface normal of the current intersection point.
Calculate surface normal.
Implements Isis::ShapeModel.
References calculateLocalNormal(), Isis::ShapeModel::localNormal(), and Isis::ShapeModel::setNormal().
Referenced by calculateDefaultNormal().
clearSurfacePoint()
void Isis::ShapeModel::clearSurfacePoint () virtual inherited
Clears or resets the current surface point.
Reimplemented in Isis::EmbreeShapeModel, and Isis::BulletShapeModel.
Referenced by Isis::EmbreeShapeModel::clearSurfacePoint(), Isis::Sensor::SetGround(), Isis::Camera::SetGround(), Isis::CSMCamera::SetGround(), Isis::Camera::SetImage(), Isis::Sensor::setTime(), Isis::Camera::SetUniversalGround(), and Isis::Sensor::SetUniversalGround().
emissionAngle()
double Isis::ShapeModel::emissionAngle (const std::vector< double > & observerBodyFixedPosition) virtual inherited
Computes and returns emission angle, in degrees, given the observer position.
Emission Angle: The angle between the surface normal vector at the intersection point and the vector from the intersection point to the observer (usually the spacecraft). The emission angle varies from 0 degrees when the observer is viewing the sub-spacecraft point (nadir viewing) to 90 degrees when the intercept is tangent to the surface of the target body. Thus, higher values of emission angle indicate more oblique viewing of the target.
Parameters
observerBodyFixedPosition Three dimensional position of the observer, in the coordinate system of the target body.
Returns
The emission angle, in decimal degrees.
Reimplemented in Isis::PlaneShape.
References Isis::RAD2DEG.
Referenced by Isis::CSMCamera::EmissionAngle(), and Isis::Sensor::EmissionAngle().
hasEllipsoidIntersection()
bool Isis::ShapeModel::hasEllipsoidIntersection () protected inherited
Returns the status of the ellipsoid model intersection.
Returns
bool Indicates whether this shape model has a valid ellipsoid intersection.
hasIntersection()
bool Isis::ShapeModel::hasIntersection () inherited
Returns intersection status.
Returns
bool Indicates whether this ShapeModel has an intersection.
Referenced by Isis::DemShape::calculateDefaultNormal(), Isis::BulletShapeModel::calculateLocalNormal(), calculateLocalNormal(), Isis::EmbreeShapeModel::calculateLocalNormal(), Isis::NaifDskShape::calculateLocalNormal(), Isis::BulletShapeModel::ellipsoidNormal(), Isis::EmbreeShapeModel::ellipsoidNormal(), Isis::NaifDskShape::ellipsoidNormal(), Isis::Camera::GetLocalNormal(), Isis::Sensor::HasSurfaceIntersection(), Isis::BulletShapeModel::intersectSurface(), Isis::DemShape::intersectSurface(), Isis::EmbreeShapeModel::intersectSurface(), Isis::EquatorialCylindricalShape::intersectSurface(), Isis::CSMCamera::SetGround(), Isis::BulletShapeModel::setLocalNormalFromIntercept(), Isis::NaifDskShape::setLocalNormalFromIntercept(), and Isis::Camera::Slope().
hasLocalNormal()
bool Isis::ShapeModel::hasLocalNormal () const inherited
Returns surface point local normal status.
Returns
Indicates whether this ShapeModel has a surface normal.
Referenced by Isis::Camera::GetLocalNormal().
hasNormal()
bool Isis::ShapeModel::hasNormal () const inherited
Returns surface point normal status.
Returns
Indicates whether this ShapeModel has a surface normal.
Referenced by Isis::EmbreeShapeModel::incidenceAngle(), and Isis::Camera::Slope().
hasValidTarget()
bool Isis::ShapeModel::hasValidTarget () const protected inherited
Returns the status of the target.
If it is NULL, this method returns false.
Returns
Indicates whether the target is valid.
Referenced by Isis::BulletShapeModel::ellipsoidNormal(), Isis::EmbreeShapeModel::ellipsoidNormal(), and Isis::NaifDskShape::ellipsoidNormal().
incidenceAngle()
double Isis::ShapeModel::incidenceAngle (const std::vector< double > & illuminatorBodyFixedPosition) virtual inherited
Computes and returns incidence angle, in degrees, given the illuminator position.
Incidence Angle: The angle between the surface normal vector at the intersection point and the vector from the intersection point to the illuminator (usually the sun).
Note: this method does not use the surface model.
Parameters
illuminatorBodyFixedPosition Three dimensional position for the illuminator, in the body-fixed coordinate system.
Returns
double Incidence angle, in degrees.
Reimplemented in Isis::PlaneShape, and Isis::EmbreeShapeModel.
References Isis::RAD2DEG.
Referenced by Isis::CSMCamera::IncidenceAngle(), Isis::Sensor::IncidenceAngle(), and Isis::EmbreeShapeModel::incidenceAngle().
Initialize()
void Isis::ShapeModel::Initialize () inherited
Initializes the ShapeModel private variables.
intersectEllipsoid()
bool Isis::ShapeModel::intersectEllipsoid (const std::vector< double > observerBodyFixedPosition, const std::vector< double > & observerLookVectorToTarget) protected inherited
Finds the intersection point on the ellipsoid model using the given position of the observer (spacecraft) and direction vector from the observer to the target (body).
Parameters
observerBodyFixedPosition Three dimensional position of the observer, in the coordinate system of the target body.
observerLookVectorToTarget Three dimensional direction vector from the observer to the target.
Returns
bool Indicates whether this shape model found a valid ellipsoid intersection.
Referenced by Isis::DemShape::intersectSurface(), and intersectSurface().
intersectSurface() [1/3]
bool Isis::ShapeModel::intersectSurface (const Latitude & lat, const Longitude & lon, const std::vector< double > & observerPos, const bool & backCheck = true) virtual inherited
Compute surface intersection with optional occlusion check.
This method sets the surface point at the given latitude, longitude. The derived model is called to get the radius at that location to complete the accuracy of the surface point, them the derived method is called to complete the intersection.
Author
2017-03-23 Kris Becker
Parameters
lat Latitude of the surface point
lon Longitude of the surface point
observerPos Position of the observer
backCheck Flag to indicate occlusion check
Returns
bool True if the intersection point is valid (visable)
Reimplemented in Isis::BulletShapeModel, and Isis::EmbreeShapeModel.
intersectSurface() [2/3]
bool Isis::ShapeModel::intersectSurface (const SurfacePoint & surfpt, const std::vector< double > & observerPos, const bool & backCheck = true) virtual inherited
Compute surface intersection with optional occlusion check.
This method sets the surface point at the given latitude, longitude. The derived model is called to get the radius at that location to complete the accuracy of the surface point, them the derived method is called to complete the intersection.
Author
2017-03-23 Kris Becker
Parameters
surfpt Absolute point on the surface to check
observerPos Position of the observer
backCheck Flag to indicate occlusion check
Returns
bool True if the intersection point is valid (visable)
Reimplemented in Isis::BulletShapeModel, Isis::NaifDskShape, and Isis::EmbreeShapeModel.
intersectSurface() [3/3]
bool Isis::EllipsoidShape::intersectSurface (std::vector< double > observerPos, std::vector< double > lookDirection) virtual
Intersect the shape model.
Find the intersection point.
Implements Isis::ShapeModel.
References Isis::ShapeModel::intersectEllipsoid().
isDEM()
bool Isis::EllipsoidShape::isDEM () const virtual
Indicates that this shape model is not from a DEM.
Since this method returns false for this class, the Camera class will not calculate the local normal using neighbor points.
Returns
bool Indicates that this is not a DEM shape model.
Implements Isis::ShapeModel.
isVisibleFrom()
bool Isis::ShapeModel::isVisibleFrom (const std::vector< double > observerPos, const std::vector< double > lookDirection) virtual inherited
Default occulsion implementation.
This method is originally copied from Sensor::SetLocalGround(bool backCheck). This version checks for the emission angle from the observer to be less than or equal to 90 degrees.
It is recommended that models derived from this base class reimplement this method if a more robust, efficent test can be made.
Note this implementation does not handle occlusion!
Author
2017-03-17 Kris Becker
Parameters
observerPos Position of the observer in body fixed coordinates
lookDirection Look direction from the observer
Returns
bool True if the point is not visable, false if it can be seen
Reimplemented in Isis::EmbreeShapeModel, and Isis::BulletShapeModel.
localNormal()
std::vector< double > Isis::ShapeModel::localNormal () virtual inherited
Returns the local surface normal at the current intersection point.
Note: This method will throw an error if the normal doesn't exist. Use the hasLocalNormal() method to verify before calling this method.
See also
hasLocalNormal()
Returns
A local surface normal vector, if it exists.
References _FILEINFO_.
Referenced by calculateSurfaceNormal(), Isis::Camera::GetLocalNormal(), and Isis::EmbreeShapeModel::incidenceAngle().
localRadius()
Distance Isis::EllipsoidShape::localRadius (const Latitude & lat, const Longitude & lon) virtual
Get the local radius for a point on the surface.
Gets the local radius for the given latitude/longitude coordinate.
Returns
Distance The distance from the center of the ellipsoid to its surface at the given lat/lon location.
Implements Isis::ShapeModel.
References Isis::Distance::Kilometers, Isis::Angle::radians(), and Isis::ShapeModel::targetRadii().
name()
QString Isis::ShapeModel::name () const inherited
Gets the shape name.
Returns
QString The name of the ShapeModel.
Referenced by Isis::UniversalGroundMap::GroundRange(), Isis::VimsGroundMap::SetGround(), Isis::Camera::SetGround(), and Isis::CSMCamera::SetGround().
normal()
std::vector< double > Isis::ShapeModel::normal () virtual inherited
Returns the surface normal at the current intersection point.
Note: This method will throw an error if the normal doesn't exist. Use the hasNormal() method to verify before calling this method.
See also
hasNormal()
Returns
A surface normal vector, if it exists.
References _FILEINFO_.
Referenced by Isis::DemShape::calculateDefaultNormal(), Isis::DemShape::calculateLocalNormal(), calculateLocalNormal(), Isis::EmbreeShapeModel::incidenceAngle(), Isis::BulletShapeModel::setLocalNormalFromIntercept(), and Isis::Camera::Slope().
phaseAngle()
double Isis::ShapeModel::phaseAngle (const std::vector< double > & observerBodyFixedPosition, const std::vector< double > & illuminatorBodyFixedPosition) virtual inherited
Computes and returns phase angle, in degrees, given the positions of the observer and illuminator.
Phase Angle: The angle between the vector from the intersection point to the observer (usually the spacecraft) and the vector from the intersection point to the illuminator (usually the sun).
Parameters
observerBodyFixedPosition Three dimensional position of the observer, in the coordinate system of the target body.
illuminatorBodyFixedPosition Three dimensional position for the illuminator, in the body-fixed coordinate system.
Returns
double Phase angle, in degrees.
References Isis::RAD2DEG.
Referenced by Isis::CSMCamera::PhaseAngle().
resolution()
double Isis::ShapeModel::resolution () protected inherited
Convenience method to get pixel resolution (m/pix) at current intersection point.
Returns
@double The pixel resolution at the surface intersection.
References _FILEINFO_.
Referenced by Isis::DemShape::intersectSurface().
setHasIntersection()
void Isis::ShapeModel::setHasIntersection (bool b) inherited
Sets the flag to indicate whether this ShapeModel has an intersection.
Parameters
b Indicates whether there is an intersection.
Referenced by Isis::DemShape::intersectSurface(), Isis::EmbreeShapeModel::intersectSurface(), Isis::EquatorialCylindricalShape::intersectSurface(), Isis::PlaneShape::intersectSurface(), Isis::CSMCamera::SetGround(), Isis::CSMCamera::SetImage(), Isis::Sensor::SetLookDirection(), and Isis::CSMCamera::SetLookDirection().
setHasLocalNormal()
void Isis::ShapeModel::setHasLocalNormal (bool status) protected inherited
Sets the flag to indicate whether this ShapeModel has a local normal.
Parameters
status Indicates whether there is a normal.
Referenced by Isis::DemShape::calculateLocalNormal(), calculateLocalNormal(), and Isis::EmbreeShapeModel::clearSurfacePoint().
setHasNormal()
void Isis::ShapeModel::setHasNormal (bool status) protected inherited
Sets the flag to indicate whether this ShapeModel has a surface normal.
Parameters
status Indicates whether there is a normal.
Referenced by Isis::DemShape::calculateDefaultNormal(), and Isis::EmbreeShapeModel::clearSurfacePoint().
setLocalNormal() [1/2]
void Isis::ShapeModel::setLocalNormal (const double a, const double b, const double c) protected inherited
Sets the local normal for the currect intersection point.
Note: This method will throw an error if this ShapeModel doesn't have and intersection. Use the hasIntersection() method to verify before calling this method.
See also
hasIntersection()
Parameters
a First coordinate value for the three dimensional local normal.
b Second coordinate value for the three dimensional local normal.
c Third coordinate value for the three dimensional local normal.
References _FILEINFO_.
setLocalNormal() [2/2]
void Isis::ShapeModel::setLocalNormal (const std::vector< double > normal) protected inherited
Sets the local normal for the currect intersection point.
Note: This method will throw an error if this ShapeModel doesn't have an intersection. Use the hasIntersection() method to verify before calling this method.
See also
hasIntersection()
Parameters
normal Three dimensional local normal vector.
References _FILEINFO_.
Referenced by Isis::DemShape::calculateLocalNormal(), calculateLocalNormal(), Isis::BulletShapeModel::setLocalNormalFromIntercept(), and Isis::NaifDskShape::setLocalNormalFromIntercept().
setName()
void Isis::ShapeModel::setName (QString name) protected inherited
Sets the shape name.
Parameters
name The name of the ShapeModel.
Referenced by Isis::BulletShapeModel::BulletShapeModel(), Isis::DemShape::DemShape(), EllipsoidShape(), Isis::EmbreeShapeModel::EmbreeShapeModel(), Isis::EquatorialCylindricalShape::EquatorialCylindricalShape(), Isis::NaifDskShape::NaifDskShape(), and Isis::PlaneShape::PlaneShape().
setNormal() [1/2]
void Isis::ShapeModel::setNormal (const double a, const double b, const double c) protected inherited
Sets the surface normal for the currect intersection point.
Note: This method will throw an error if this ShapeModel doesn't have and intersection. Use the hasIntersection() method to verify before calling this method.
See also
hasIntersection()
Parameters
a First coordinate value for the three dimensional surface normal.
b Second coordinate value for the three dimensional surface normal.
c Third coordinate value for the three dimensional surface normal.
References _FILEINFO_.
setNormal() [2/2]
void Isis::ShapeModel::setNormal (const std::vector< double > normal) protected inherited
Sets the surface normal for the currect intersection point.
Note: This method will throw an error if this ShapeModel doesn't have an intersection. Use the hasIntersection() method to verify before calling this method.
See also
hasIntersection()
Parameters
normal Three dimensional surface normal vector.
References _FILEINFO_.
Referenced by Isis::DemShape::calculateDefaultNormal(), Isis::BulletShapeModel::calculateSurfaceNormal(), calculateSurfaceNormal(), Isis::EmbreeShapeModel::calculateSurfaceNormal(), Isis::NaifDskShape::calculateSurfaceNormal(), Isis::EmbreeShapeModel::incidenceAngle(), and Isis::PlaneShape::intersectSurface().
setSurfacePoint()
void Isis::ShapeModel::setSurfacePoint (const SurfacePoint & surfacePoint) virtual inherited
Set surface intersection point.
Parameters
surfacePoint Position coordinate for the surface point.
Reimplemented in Isis::BulletShapeModel.
Referenced by Isis::NaifDskShape::intersectSurface(), and Isis::RadarGroundMap::SetGround().
surfaceIntersection()
SurfacePoint * Isis::ShapeModel::surfaceIntersection () const virtual inherited
Returns the surface intersection for this ShapeModel.
Returns
SurfacePoint Three dimensional position for the surface intersection, in body-fixed coordinate system.
Referenced by Isis::DemShape::calculateDefaultNormal(), Isis::DemShape::calculateLocalNormal(), calculateLocalNormal(), Isis::Sensor::Coordinate(), Isis::BulletShapeModel::ellipsoidNormal(), Isis::EmbreeShapeModel::ellipsoidNormal(), Isis::NaifDskShape::ellipsoidNormal(), Isis::PlaneShape::emissionAngle(), Isis::Sensor::GetLatitude(), Isis::Sensor::GetLongitude(), Isis::Sensor::GetSurfacePoint(), Isis::PlaneShape::incidenceAngle(), Isis::DemShape::intersectSurface(), Isis::EquatorialCylindricalShape::intersectSurface(), Isis::PlaneShape::intersectSurface(), Isis::EmbreeShapeModel::isVisibleFrom(), Isis::Sensor::LocalRadius(), Isis::PlaneShape::localRadius(), Isis::Sensor::SlantDistance(), and Isis::Sensor::SolarDistance().
targetRadii()
std::vector< Distance > Isis::ShapeModel::targetRadii () const protected inherited
Returns the radii of the body in km.
The radii are obtained from the target. Note: This method will throw an error if the ShapeModel does not have a valid target. Use the hasValidTarget() method to verify before calling this method.
See also
hasValidTarget()
Returns
Three dimensional vector containing the ellipsoid radii values.
References _FILEINFO_.
Referenced by Isis::DemShape::calculateDefaultNormal(), calculateLocalNormal(), Isis::BulletShapeModel::ellipsoidNormal(), Isis::EmbreeShapeModel::ellipsoidNormal(), Isis::NaifDskShape::ellipsoidNormal(), Isis::EquatorialCylindricalShape::intersectSurface(), and localRadius().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/EllipsoidShape/EllipsoidShape.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/EllipsoidShape/EllipsoidShape.cpp