Isis Developer Reference: Isis::ProjectionConfigDialog Class Reference
Isis::ProjectionConfigDialog Class Reference
This is the configuration dialog for the MosaicSceneWidget's projection parameters (map file).
#include <ProjectionConfigDialog.h>
Public Slots
void applySettings ()
Take the settings that have been configured and apply them to the mosaic scene.
void readSettings ()
Update the current widgets' states with the current settings in the mosaic scene.
Signals
void shown ()
Public Member Functions
ProjectionConfigDialog (MosaicSceneWidget *scene, QWidget *parent=NULL)
Create a projection configuration dialog.
virtual ~ProjectionConfigDialog ()
void setQuickConfig (bool quick)
Enable/disable minimal interaction mode.
Protected Member Functions
void showEvent (QShowEvent *)
Detailed Description
This is the configuration dialog for the MosaicSceneWidget's projection parameters (map file).
Author
2012-08-06 Steven Lambright
Constructor & Destructor Documentation
ProjectionConfigDialog()
Isis::ProjectionConfigDialog::ProjectionConfigDialog (MosaicSceneWidget * scene, QWidget * parent = NULL)
Create a projection configuration dialog.
Parameters
scene The mosaic scene for which we're going to set the projection, this must not be NULL.
parent The Qt-parent for this dialog.
References applySettings(), readSettings(), and shown().
~ProjectionConfigDialog()
Isis::ProjectionConfigDialog::~ProjectionConfigDialog () virtual
Member Function Documentation
applySettings
void Isis::ProjectionConfigDialog::applySettings () slot
Take the settings that have been configured and apply them to the mosaic scene.
References readSettings().
Referenced by ProjectionConfigDialog().
readSettings
void Isis::ProjectionConfigDialog::readSettings () slot
Update the current widgets' states with the current settings in the mosaic scene.
Referenced by applySettings(), and ProjectionConfigDialog().
setQuickConfig()
void Isis::ProjectionConfigDialog::setQuickConfig (bool quick)
Enable/disable minimal interaction mode.
This is defaulted to false. Setting this option will remove most mouse clicks from the interface and try to immediately use a projection that the user is expected to select from a file.
Parameters
quick True to minimize clicks/interaction, false (default) to use standard behavior.
showEvent()
void Isis::ProjectionConfigDialog::showEvent (QShowEvent * event) protected
References shown().
shown
void Isis::ProjectionConfigDialog::shown () signal
Referenced by ProjectionConfigDialog(), and showEvent().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/ProjectionConfigDialog.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/ProjectionConfigDialog.cpp