Isis Developer Reference: Isis::Projection Class Reference
Isis::Projection Class Reference abstract
Map Projection
Base class for Map Projections.
#include <Projection.h>
Public Types
enum ProjectionType { Triaxial , RingPlane }
This enum defines the subclasses of Projection supported in Isis.
Public Member Functions
Projection (Pvl &label)
Constructs an empty Projection object.
virtual ~Projection ()
Destroys the Projection object.
virtual bool operator== (const Projection &proj)
This method determines whether two map projection objects are equal by comparing the resolution, and projection name.
bool operator!= (const Projection &proj)
This method determines whether two map projection objects are not equal.
void setProjectionType (const ProjectionType ptype)
Sets the projection subclass type.
ProjectionType projectionType () const
Returns an enum value for the projection type.
bool IsSky () const
Returns true if projection is sky and false if it is land.
virtual QString Name () const =0
This method returns the name of the map projection.
virtual double LocalRadius () const =0
virtual QString Version () const =0
This method returns the Version of the map projection.
virtual bool IsEquatorialCylindrical ()
This method returns true if the projection is equatorial cylindrical.
virtual bool HasGroundRange () const
This indicates if the longitude direction type is positive west (as opposed to postive east).
double Rotation () const
Returns the value of the Rotation keyword from the mapping group.
void SetWorldMapper (WorldMapper *mapper)
If desired the programmer can use this method to set a world mapper to be used in the SetWorld, WorldX, and WorldY methods.
virtual bool SetGround (const double lat, const double lon)=0
virtual bool SetCoordinate (const double x, const double y)=0
bool IsGood () const
This indicates if the last invocation of SetGround, SetCoordinate, SetUniversalGround, or SetWorld was with successful or not.
double XCoord () const
This returns the projection X provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
double YCoord () const
This returns the projection Y provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
virtual bool SetUniversalGround (const double coord1, const double coord2)
This method is used to set the lat/lon or radius/azimuth (i.e.
virtual bool SetUnboundUniversalGround (const double coord1, const double coord2)
This method is used to set the lat/lon or radius/azimuth (i.e.
virtual bool SetWorld (const double x, const double y)
This method is used to set a world coordinate.
virtual double WorldX () const
This returns the world X coordinate provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
virtual double WorldY () const
This returns the world Y coordinate provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
double ToWorldX (const double projectionX) const
This method converts a projection x value to a world x value.
double ToWorldY (const double projectionY) const
This method converts a projection y value to a world y value.
double ToProjectionX (const double worldX) const
This method converts a world x value to a projection x value.
double ToProjectionY (const double worldY) const
This method converts a world y value to a projection y value.
double Resolution () const
This method returns the resolution for mapping world coordinates into projection coordinates.
virtual double Scale () const =0
virtual bool XYRange (double &minX, double &maxX, double &minY, double &maxY)=0
void SetUpperLeftCorner (const Displacement &x, const Displacement &y)
This method searches for extreme (min/max/discontinuity) coordinate values along the constBorder line between minBorder and maxBorder (that is, across latitudes/longitudes).
virtual PvlGroup Mapping ()=0
Static Public Member Functions
static double ToHours (double angle)
Converts the given angle (in degrees) to hours by using the ratio 15 degrees per hour.
static QString ToDMS (double angle)
Converts the given angle (in degrees) to degrees, minutes, seconds.
static QString ToHMS (double angle)
Converts the given angle (in degrees) to hours, minutes, seconds.
Protected Member Functions
virtual void XYRangeCheck (const double latitude, const double longitude)=0
void SetXY (double x, double y)
This protected method is a helper for derived classes.
void SetComputedXY (double x, double y)
This protected method is a helper for derived classes.
double GetX () const
Calculates the unrotated form of current x value.
double GetY () const
Calculates the unrotated form of the current y value.
double PixelResolution () const
Returns the pixel resolution value from the PVL mapping group in meters/pixel.
Protected Attributes
WorldMapper * m_mapper
This points to a mapper passed into the SetWorldMapper method.
bool m_good
Indicates if the contents of m_x, m_y, m_latitude, and m_longitude are valid.
bool m_sky
Indicates whether projection is sky or land.
bool m_groundRangeGood
Indicates if the ground range (min/max lat/lons) were read from the labels.
double m_minimumX
The data elements m_minimumX, m_minimumY, m_maximumX, and m_maximumY are convience data elements when you write the XYRange virtual function.
double m_maximumX
See minimumX description.
double m_minimumY
See minimumX description.
double m_maximumY
See minimumX description.
PvlGroup m_mappingGrp
Mapping group that created this projection.
Detailed Description
Base class for Map Projections.
This is a virtual base class for map projections. It must be used to create specific map projection classes such as Sinusoidal, Mercator, etc. The foundation of this class is the ability to convert ground coordinates (latitude and longitude) into projection coordinates (x and y) and vice versa. Options exist to allow conversion to and from programmer specified world coordinates. The world coordinates can be cube pixels, paper units in millimeters, or any other unit the program may need. Generally, you should never directly instantiate this class.
Here is an example of how to use Projection
Pvl lab;
lab.Read("projection.map");
Projection *p = ProjectionFactory::Create(lab);
If you would like to see Projection being used in implementation, see mappos.cpp
Author
2003-01-29 Jeff Anderson
Member Enumeration Documentation
ProjectionType
enum Isis::Projection::ProjectionType
This enum defines the subclasses of Projection supported in Isis.
Enumerator
Triaxial
These projections are used to map triaxial and irregular-shaped bodies.
RingPlane
These projections are used to map ring planes.
Constructor & Destructor Documentation
Projection()
Isis::Projection::Projection (Pvl & label)
Constructs an empty Projection object.
Parameters
label A PVL object containing map projection labels. These labels are fully described in the Isis Map Projection Users Guide. A brief example follows:
  Group = Mapping
    EquatorialRadius = 3396190.0
    PolarRadius = 3376200.0
    LongitudeDirection = PositiveEast
    LongitudeDomain = 360
    LatitudeType = Planetographic
    MinimumLatitude = 10.8920539924144
    MaximumLatitude = 34.7603960060206
    MinimumLongitude = 219.72432466275
    MaximumLongitude = 236.186050244411
    PixelResolution = 1387.31209461362
    ProjectionName = SimpleCylindrical
    CenterLongitude = 220.0
  EndGroup
End
Exceptions
IException::Unknown - "Projection failed. No target radii available through keywords [EquatorialRadius and PolarRadius] or [TargetName]." @throw IException::Unknown - "Projection failed. Invalid value for keyword [EquatorialRadius]. It must be greater than zero." @throw IException::Unknown - "Projection failed. Invalid value for keyword [PolarRadius]. It must be greater than zero." @throw IException::Unknown - "Projection failed. Invalid value for keyword [LatitudeType] must be [Planetographic or Planetocentric]" @throw IException::Unknown - "Projection failed. Invalid value for keyword [LongitudeDirection] must be [PositiveWest or PositiveEast]" @throw IException::Unknown - "Projection failed. Invalid value for keyword [LongitudeDomain] must be [180 or 360]" @throw IException::Unknown - "Projection failed. [MinimumLatitude] is outside the range of [-90:90]" @throw IException::Unknown - "Projection failed. [MaximumLatitude] is outside the range of [-90:90]" @throw IException::Unknown - "Projection failed. [MinimumLatitude,MaximumLatitude] are not properly ordered" @throw IException::Unknown - "Projection failed. [MinimumLongitude,MaximumLongitude] are not properly ordered" @throw IException::Unknown - "Projection failed. Invalid keyword value(s). [EquatorialRadius] must be greater than or equal to [PolarRadius]" @throw IException::Unknown - "Projection failed. Invalid label group [Mapping]"
References _FILEINFO_, Isis::PvlObject::findGroup(), Isis::PvlContainer::hasKeyword(), m_good, m_mapper, m_mappingGrp, m_maximumX, m_maximumY, m_minimumX, m_minimumY, m_sky, Isis::Null, Isis::PvlObject::Traverse, and Isis::IException::Unknown.
~Projection()
Isis::Projection::~Projection () virtual
Destroys the Projection object.
References m_mapper.
Member Function Documentation
GetX()
double Isis::Projection::GetX () const protected
Calculates the unrotated form of current x value.
Returns
double The unrotated x-value.
References Isis::PI.
Referenced by Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Mollweide::SetCoordinate(), Isis::ObliqueCylindrical::SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::RingCylindrical::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), and Isis::TransverseMercator::SetCoordinate().
GetY()
double Isis::Projection::GetY () const protected
Calculates the unrotated form of the current y value.
Returns
double The unrotated y-value.
References Isis::PI.
Referenced by Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::ObliqueCylindrical::SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::RingCylindrical::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), and Isis::TransverseMercator::SetCoordinate().
HasGroundRange()
bool Isis::Projection::HasGroundRange () const virtual
This indicates if the longitude direction type is positive west (as opposed to postive east).
The longitude type was obtained from the label during object construction.
Returns
bool This indicates if the longitude direction type is positive east (as opposed to postive west). The longitude type was obtained from the label during object construction.
bool This method returns the longitude direction as a string. It will return either PositiveEast or PositiveWest.
string The longitude direction, "PositiveEast" or "PositiveWest". This indicates if the longitude domain is -180 to 180 (as opposed to 0 to 360). The longitude domain was obtained from the label during object construction.
bool This indicates if the longitude domain is 0 to 360 (as opposed to -180 to 180). The longitude domain was obtained from the label during object construction.
bool This method converts a longitude into the -180 to 180 domain. It will leave the longitude unchanged if it is already in the domain.
Parameters
lon Longitude to convert into the -180 to 180 domain.
Exceptions
IException::Unknown - "The given longitude is invalid."
Returns
double The longitude, converted to 180 domain. This method converts a longitude into the 0 to 360 domain. It will leave the longitude unchanged if it is already in the domain.
Parameters
lon Longitude to convert into the 0 to 360 domain.
Returns
double The longitude, converted to 360 domain. This method returns the longitude domain as a string. It will return either 180 or 360.
string The longitude domain, "180" or "360". This indicates that the labels contained minimum and maximum ground coordinatess (e.g., a ground range coverage). If the projection has ground range coverage then the MinimumLatitude, MaximumLatitude, MinimumLongitude, and MaximumLongitude methods or comparable methods for other projection types can be used. The ground range coverage essentially defines the area of user interest.
bool
References m_groundRangeGood.
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::RingPlaneProjection::Mapping(), Isis::TProjection::MappingLatitudes(), Isis::TProjection::MappingLongitudes(), Isis::Planar::MappingRingLongitudes(), Isis::RingCylindrical::MappingRingLongitudes(), Isis::RingPlaneProjection::MappingRingLongitudes(), Isis::Planar::MappingRingRadii(), Isis::RingCylindrical::MappingRingRadii(), Isis::RingPlaneProjection::MappingRingRadii(), Isis::ProjectionFactory::RingsCreateForCube(), and Isis::TProjection::xyRangeOblique().
IsEquatorialCylindrical()
bool Isis::Projection::IsEquatorialCylindrical () virtual
This method returns true if the projection is equatorial cylindrical.
In other words, if the projection is cylindrical and an image projected at 0 is the same as an image projected at 360.
Returns
bool true if the projection is equatorial cylindrical
Reimplemented in Isis::TProjection, Isis::SimpleCylindrical, Isis::RingCylindrical, Isis::Mercator, and Isis::Equirectangular.
Referenced by Isis::ShapeModelFactory::create(), and Isis::ProcessMapMosaic::StartProcess().
IsGood()
bool Isis::Projection::IsGood () const
This indicates if the last invocation of SetGround, SetCoordinate, SetUniversalGround, or SetWorld was with successful or not.
If there was success then the Latitude, Longitude, XCoord, YCoord, UniversalLatitude, UniversalLongitude, WorldX, and WorldY methods can be utilized.
Returns
bool True if the last call to SetGround, SetCoordinate, SetUniversalGround, or SetWorld was successful.
References m_good.
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::Chip::Load(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::SubArea::UpdateLabel(), Isis::TProjection::XYRangeCheck(), and Isis::RingPlaneProjection::XYRangeCheck().
IsSky()
bool Isis::Projection::IsSky () const
Returns true if projection is sky and false if it is land.
Returns
bool
References m_sky.
Referenced by Isis::Camera::SetImage(), and Isis::Camera::SetRightAscensionDeclination().
LocalRadius()
virtual double Isis::Projection::LocalRadius () const pure virtual
Implemented in Isis::TProjection, and Isis::RingPlaneProjection.
Mapping()
virtual PvlGroup Isis::Projection::Mapping () pure virtual
Implemented in Isis::UpturnedEllipsoidTransverseAzimuthal, Isis::TransverseMercator, Isis::TProjection, Isis::Sinusoidal, Isis::SimpleCylindrical, Isis::Robinson, Isis::RingPlaneProjection, Isis::RingCylindrical, Isis::PolarStereographic, Isis::PointPerspective, Isis::Planar, Isis::Orthographic, Isis::ObliqueCylindrical, Isis::Mollweide, Isis::Mercator, Isis::LunarAzimuthalEqualArea, Isis::LambertConformal, Isis::LambertAzimuthalEqualArea, and Isis::Equirectangular.
Referenced by Isis::MosaicSceneWidget::addToPermanent(), Isis::MosaicGridToolConfigDialog::applySettings(), Isis::UniversalGroundMap::GroundRange(), Isis::MosaicGridToolConfigDialog::readSettings(), Isis::MosaicSceneWidget::save(), Isis::ProcessMapMosaic::SetOutputCube(), Isis::MosaicSceneWidget::setProjection(), and Isis::MosaicSceneWidget::toPvl().
Name()
virtual QString Isis::Projection::Name () const pure virtual
This method returns the name of the map projection.
It is a pure virtual method (requires all subclasses to override).
Returns
string The name of the map projection.
Implemented in Isis::TProjection, Isis::RingPlaneProjection, Isis::UpturnedEllipsoidTransverseAzimuthal, Isis::TransverseMercator, Isis::Sinusoidal, Isis::SimpleCylindrical, Isis::Robinson, Isis::RingCylindrical, Isis::PolarStereographic, Isis::PointPerspective, Isis::Planar, Isis::Orthographic, Isis::ObliqueCylindrical, Isis::Mollweide, Isis::Mercator, Isis::LunarAzimuthalEqualArea, Isis::LambertConformal, Isis::LambertAzimuthalEqualArea, and Isis::Equirectangular.
Referenced by operator==(), Isis::ProcessExportPds::ProjectionName(), and Isis::ProcessExportPds4::StandardAllMapping().
operator!=()
bool Isis::Projection::operator!= (const Projection & proj)
This method determines whether two map projection objects are not equal.
True is returned if they have at least some differences in the radii, latitude type, longitude direction, resolution, or projection name.
Parameters
proj A reference to a Projection object to which this Projection will be compared.
Returns
bool Indicates whether the Projection objects are not equivalent.
operator==()
bool Isis::Projection::operator== (const Projection & proj) virtual
This method determines whether two map projection objects are equal by comparing the resolution, and projection name.
Parameters
proj A reference to a Projection object to which this Projection will be compared.
Returns
bool Indicates whether the Projection objects are equivalent.
Reimplemented in Isis::UpturnedEllipsoidTransverseAzimuthal, Isis::TransverseMercator, Isis::TProjection, Isis::Sinusoidal, Isis::SimpleCylindrical, Isis::Robinson, Isis::RingPlaneProjection, Isis::RingCylindrical, Isis::PolarStereographic, Isis::PointPerspective, Isis::Planar, Isis::Orthographic, Isis::Mollweide, Isis::Mercator, Isis::LambertConformal, Isis::LambertAzimuthalEqualArea, Isis::Equirectangular, and Isis::ObliqueCylindrical.
References Name(), and Resolution().
PixelResolution()
double Isis::Projection::PixelResolution () const protected
Returns the pixel resolution value from the PVL mapping group in meters/pixel.
Returns
double pixel resolution in meters/pixel
Referenced by Isis::Planar::XYRange(), and Isis::RingCylindrical::XYRange().
projectionType()
Projection::ProjectionType Isis::Projection::projectionType () const
Returns an enum value for the projection type.
Returns
projection subclass type
Referenced by Isis::MosaicGridTool::autoGrid(), Isis::MosaicGridTool::fromPvl(), Isis::MosaicFindTool::getUserGroundPoint(), Isis::GridGraphicsItem::GridGraphicsItem(), Isis::UniversalGroundMap::GroundRange(), Isis::MosaicControlNetTool::mouseButtonRelease(), Isis::MosaicFindTool::mouseButtonRelease(), Isis::MosaicGridTool::setLatExtents(), Isis::MosaicGridTool::setLonExtents(), SetUnboundUniversalGround(), SetUniversalGround(), Isis::UniversalGroundMap::UniversalLatitude(), Isis::UniversalGroundMap::UniversalLongitude(), Isis::MosaicTrackTool::updateLabels(), and Isis::MosaicAreaTool::userChangedBox().
Resolution()
double Isis::Projection::Resolution () const
This method returns the resolution for mapping world coordinates into projection coordinates.
For example, if the world coordinate system is an image then this routine returns the number of meters per pixel. Likewise, if the world coordinate system is a piece of paper, it might return the number of meters per inch of paper. If the SetWorldMapper method is not invoked then this method returns 1.0
Returns
double The resolution, in appropriate units.
References m_mapper, and Isis::WorldMapper::Resolution().
Referenced by Isis::ProcessExport::CreateWorldFile(), operator==(), and Isis::UniversalGroundMap::Resolution().
Rotation()
double Isis::Projection::Rotation () const
Returns the value of the Rotation keyword from the mapping group.
Returns
double The rotation of the map.
Scale()
virtual double Isis::Projection::Scale () const pure virtual
Implemented in Isis::TProjection, and Isis::RingPlaneProjection.
SetComputedXY()
void Isis::Projection::SetComputedXY (double x, double y) protected
This protected method is a helper for derived classes.
It takes unrotated x and y values, rotates them using the rotation angle data member, and stores the results in the current x and y data members.
Parameters
x The unrotated x coordinate.
y The unrotated y coordinate.
References m_good, Isis::Null, and Isis::PI.
Referenced by Isis::Equirectangular::SetGround(), Isis::LambertConformal::SetGround(), Isis::LunarAzimuthalEqualArea::SetGround(), Isis::Mercator::SetGround(), Isis::Mollweide::SetGround(), Isis::ObliqueCylindrical::SetGround(), Isis::Orthographic::SetGround(), Isis::PointPerspective::SetGround(), Isis::PolarStereographic::SetGround(), Isis::Robinson::SetGround(), Isis::SimpleCylindrical::SetGround(), Isis::Sinusoidal::SetGround(), Isis::TProjection::SetGround(), Isis::TransverseMercator::SetGround(), Isis::Planar::SetGround(), Isis::RingCylindrical::SetGround(), and Isis::RingPlaneProjection::SetGround().
SetCoordinate()
virtual bool Isis::Projection::SetCoordinate (const double x, const double y) pure virtual
Implemented in Isis::UpturnedEllipsoidTransverseAzimuthal, Isis::TransverseMercator, Isis::TProjection, Isis::Sinusoidal, Isis::SimpleCylindrical, Isis::Robinson, Isis::RingPlaneProjection, Isis::RingCylindrical, Isis::PolarStereographic, Isis::PointPerspective, Isis::Planar, Isis::Orthographic, Isis::ObliqueCylindrical, Isis::Mollweide, Isis::Mercator, Isis::LunarAzimuthalEqualArea, Isis::LambertConformal, Isis::LambertAzimuthalEqualArea, and Isis::Equirectangular.
Referenced by SetWorld(), and Isis::MosaicTrackTool::updateLabels().
SetGround()
virtual bool Isis::Projection::SetGround (const double lat, const double lon) pure virtual
Implemented in Isis::RingPlaneProjection, Isis::RingCylindrical, Isis::Planar, Isis::UpturnedEllipsoidTransverseAzimuthal, Isis::TransverseMercator, Isis::TProjection, Isis::Sinusoidal, Isis::SimpleCylindrical, Isis::Robinson, Isis::PolarStereographic, Isis::PointPerspective, Isis::Orthographic, Isis::ObliqueCylindrical, Isis::Mollweide, Isis::Mercator, Isis::LunarAzimuthalEqualArea, Isis::LambertConformal, Isis::LambertAzimuthalEqualArea, and Isis::Equirectangular.
Referenced by Isis::Camera::SetRightAscensionDeclination().
setProjectionType()
void Isis::Projection::setProjectionType (const ProjectionType ptype)
Sets the projection subclass type.
Parameters
ptype The projection subclass type
Referenced by Isis::RingPlaneProjection::RingPlaneProjection(), and Isis::TProjection::TProjection().
SetUnboundUniversalGround()
bool Isis::Projection::SetUnboundUniversalGround (const double coord1, const double coord2) virtual
This method is used to set the lat/lon or radius/azimuth (i.e.
ring longitude) coordinate, depending on the projection type. The Set forces an attempted calculation of the projection X/Y values. This may or may not be successful and a status is returned as such. This method will not adjust the longitude coordinate based on the longitude domain.
Parameters
coord1 Latitude (planetocentric) or ring radius to project
coord2 Longitude or ring longitude to project. The value passed in should be PositiveEast, Domain360.
Returns
bool Indicates whether the method was successful.
Reimplemented in Isis::TProjection.
References m_good, Isis::Null, projectionType(), Isis::TProjection::SetUnboundUniversalGround(), Isis::RingPlaneProjection::SetUniversalGround(), and Triaxial.
Referenced by Isis::UniversalGroundMap::SetUnboundGround().
SetUniversalGround()
bool Isis::Projection::SetUniversalGround (const double coord1, const double coord2) virtual
This method is used to set the lat/lon or radius/azimuth (i.e.
ring longitude) coordinate, depending on the projection type. The Set forces an attempted calculation of the projection X/Y values. This may or may not be successful and a status is returned as such.
Parameters
coord1 Latitude (planetocentric) or ring radius to project
coord2 Longitude or ring longitude to project. The value passed in should be PositiveEast, Domain360.
Returns
bool Indicates whether the method was successful.
Reimplemented in Isis::RingPlaneProjection, and Isis::TProjection.
References m_good, Isis::Null, projectionType(), Isis::TProjection::SetUniversalGround(), Isis::RingPlaneProjection::SetUniversalGround(), and Triaxial.
Referenced by Isis::Chip::Load(), Isis::DemShape::localRadius(), Isis::UniversalGroundMap::SetGround(), Isis::Camera::SetRightAscensionDeclination(), Isis::UniversalGroundMap::SetUniversalGround(), and Isis::ProcessMapMosaic::StartProcess().
SetUpperLeftCorner()
void Isis::Projection::SetUpperLeftCorner (const Displacement & x, const Displacement & y)
This method searches for extreme (min/max/discontinuity) coordinate values along the constBorder line between minBorder and maxBorder (that is, across latitudes/longitudes).
This method locates the extrema by utilizing the findExtreme() method until the coordinate values converge. Then, extremeVal parameter is updated with this value before returning.
Discontinuities are stored in m_specialLatCases and m_specialLonCases so they may be checked again later, which creates significantly more accuracy in some cases.
Parameters
minBorder Minimum latitude or longitude to search between.
maxBorder Maximum latitude or longitude to search between.
extremeVal The resulting global coordinate value (min or max value for x or y, depending on findMin and searchX) on the constBorder.
constBorder The latitude or longitude that remains constant. The method will step along this border.
searchX Indicates whether the method is searching for a min or max x-coordinate. If false the method searches for min or max y-coordinate.
searchLongitude Indicates whether the method will search along a longitude. If true, constBorder is longitude and all other borders are latitudes. If false, the method searches a latitude (constBorder is a lat, other borders lons).
findMin Indicates whether the method is looking for a minimum coordinate value. If false, the method is looking for a maximum value.
Author
Steven Lambright Searches for extreme (min/max/discontinuity) coordinate values across latitudes/longitudes.
This method looks for these extrema along the constBorder between minBorder and maxBorder by stepping along constBorder (10 times) from the minBorder and maxBorder. Then, the range of this extreme value is recorded in minBorder and maxBorder and the coordinate values corresponding to these new borders are stored in minBorderX, minBorderY, maxBorderX and maxBorderY.
This function should be used by calling it repeatedly until minBorderX and minBorderY do not equal maxBorderX and maxBorderY, respectively. Discontinuities will cause the minBorderX, minBorderY, maxBorderX and maxBorderY to never converge. If minBorderX never comes close to maxBorderX or minBorderY never comes close to maxBorderY, then between minBorder and maxBorder is the value of the most extreme value. In this case, either the smaller or larger of the x or y values found will be correct, depending on the values of findMin and searchX.
Parameters
minBorder Minimum latitude or longitude to search between. This value gets updated to a more precise range.
maxBorder Maximum latitude or longitude to search between. This value gets updated to a more precise range.
minBorderX The x-value corresponding to the lower resultant minBorder and the constBorder, which is more accurate when nearly equal to maxBorderX.
minBorderY The y-value corresponding to the lower resultant minBorder and the constBorder, which is more accurate when nearly equal to maxBorderY.
maxBorderX The x-value corresponding to the higher resultant maxBorder and the constBorder, which is more accurate when nearly equal to minBorderX.
maxBorderY The y-value corresponding to the higher resultant maxBorder and the constBorder, which is more accurate when nearly equal to minBorderY.
constBorder The latitude or longitude that remains constant. The method will step along this border.
searchX Indicates whether the method is searching for a min or max x-coordinate. If false the method searches for min or max y-coordinate.
searchLongitude Indicates whether the method will search along a longitude. If true, constBorder is longitude and all other borders are latitudes. If false, the method searches a latitude (constBorder is a lat, other borders lons).
findMin Indicates whether the method is looking for a minimum coordinate value. If false, the method is looking for a maximum value.
Author
Stephen Lambright This function sets the ground for the given border values. It calls the SetGround(lat, lon) method with the appropriate lat/lon values, depending on whether variableIsLat is true.
This method is used by doSearch and findExtreme in order to set the ground correctly each time.
Parameters
variableBorder The latitude or longitude that is variable in the search methods.
constBorder The latitude or longitude that is constant in the search methods.
variableIsLat Indicates whether variableBorder is the latittude value and constBorder is the longitude value. If false, variableBorder is the longitude value and constBorder is the latitude value.
Author
Stephen Lambright This method sets the UpperLeftCornerX and UpperLeftCornerY keywords in the projection mapping group, in meters.
Parameters
x the upper left corner x value
y the upper left corner y value
References Isis::PvlContainer::addKeyword(), m_mappingGrp, Isis::Displacement::meters(), Isis::PvlContainer::Replace, and Isis::toString().
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::ProjectionFactory::CreateFromCube(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::ProjectionFactory::RingsCreateFromCube(), and Isis::ProcessMapMosaic::SetOutputCube().
SetWorld()
bool Isis::Projection::SetWorld (const double worldX, const double worldY) virtual
This method is used to set a world coordinate.
A world coordinate is a different coordinate type that has a one-to-one mapping to the projection coordinate system. For example, mapping pixel samples and lines to projection x's and y's. The Set forces an attempted calculation of the corresponding latitude/longitude position. This may or may not be successful and a status is returned as such. Note that is only applies if the Projection object was given an WorldMapper object during construction. If an WorldMapper was not supplied then SetWorld operates exactly the same as SetCoordinate (impling that world coordinate and projection coordinate are identical).
Parameters
worldX World X coordinate in units that are specified by the WorldMapper object (e.g., pixels, millimeters, etc)
worldY World Y coordinate in units that are specified by the WorldMapper object (e.g., pixels, millimeters, etc)
Returns
bool Indicates whether the method was successful.
References m_mapper, Isis::WorldMapper::ProjectionX(), Isis::WorldMapper::ProjectionY(), and SetCoordinate().
Referenced by Isis::ProcessExport::CreateWorldFile(), Isis::UniversalGroundMap::GroundRange(), Isis::Cube::latLonRange(), Isis::Chip::Load(), Isis::UniversalGroundMap::SetImage(), Isis::SubArea::UpdateLabel(), and Isis::PolygonTools::XYToLatLon().
SetWorldMapper()
void Isis::Projection::SetWorldMapper (WorldMapper * mapper)
If desired the programmer can use this method to set a world mapper to be used in the SetWorld, WorldX, and WorldY methods.
Mappers typically transform a projection coordinate (x/y) into the desired working coordinate system, for example, cube pixels or inches on a piece of paper. They transform in both directions (world to projection and projection to world). This allows for conversions from line/sample to latitude/longitude and vice versa. This projection will take ownership of the WorldMapper pointer.
Parameters
mapper Pointer to the mapper
References m_mapper.
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::ProjectionFactory::CreateFromCube(), Isis::ProjectionFactory::RingsCreateForCube(), and Isis::ProjectionFactory::RingsCreateFromCube().
SetXY()
void Isis::Projection::SetXY (double x, double y) protected
This protected method is a helper for derived classes.
It takes a rotated x,y and stores them in the current x and y data members.
Parameters
x The rotated x coordinate.
y The rotated y coordinate.
References m_good, and Isis::Null.
Referenced by Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::LunarAzimuthalEqualArea::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Mollweide::SetCoordinate(), Isis::ObliqueCylindrical::SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::Planar::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::RingCylindrical::SetCoordinate(), Isis::RingPlaneProjection::SetCoordinate(), Isis::Robinson::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), Isis::TProjection::SetCoordinate(), and Isis::TransverseMercator::SetCoordinate().
ToDMS()
QString Isis::Projection::ToDMS (double angle) static
Converts the given angle (in degrees) to degrees, minutes, seconds.
Outputs in the form xxx yym zz.zzzs, for example, 206.291 degrees is 206 17m 27.6s
Parameters
angle Angle in degrees to be converted to degrees, minutes, seconds
Returns
string The angle in Degrees, minutes, seconds
ToHMS()
QString Isis::Projection::ToHMS (double angle) static
Converts the given angle (in degrees) to hours, minutes, seconds.
Outputs in the form xxh yym zz.zzzs For example, 206.291 will be 13h 45m 09.84s
Parameters
angle Angle in degrees to be converted to hours, minutes, seconds
Returns
string The angle in Hours, minutes, seconds
References ToHours().
ToHours()
double Isis::Projection::ToHours (double angle) static
Converts the given angle (in degrees) to hours by using the ratio 15 degrees per hour.
Parameters
angle Angle in degrees to be converted to hours
Returns
double The number of hours for the given angle.
Referenced by ToHMS().
ToProjectionX()
double Isis::Projection::ToProjectionX (const double worldX) const
This method converts a world x value to a projection x value.
For example, if the world coordinate system is an image then this method converts a sample position to a projection x value. Note that if SetWorldMapper is not used then this routine simply returns the value of the argument. That is, no mapping occurs.
Parameters
worldX World x coordinate
Exceptions
IException::Unknown - "The given x-value is invalid."
Returns
double The projection X coordinate value.
References _FILEINFO_, m_mapper, Isis::Null, Isis::WorldMapper::ProjectionX(), and Isis::IException::Unknown.
Referenced by Isis::OverlapStatistics::OverlapStatistics(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::ProcessMapMosaic::StartProcess().
ToProjectionY()
double Isis::Projection::ToProjectionY (const double worldY) const
This method converts a world y value to a projection y value.
For example, if the world coordinate system is an image then this method converts a line position to a projection y value. Note that if SetWorldMapper is not used then this routine simply returns the value of the argument. That is, no mapping occurs.
Parameters
worldY World y coordinate
Exceptions
IException::Unknown - "The given y-value is invalid."
Returns
double The projection Y coordinate value.
References _FILEINFO_, m_mapper, Isis::Null, Isis::WorldMapper::ProjectionY(), and Isis::IException::Unknown.
Referenced by Isis::OverlapStatistics::OverlapStatistics(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::ProcessMapMosaic::StartProcess().
ToWorldX()
double Isis::Projection::ToWorldX (const double projectionX) const
This method converts a projection x value to a world x value.
For example, if the world coordinate system is an image then this method converts a projection x to a sample position. Note that if SetWorldMapper is not used then this routine simply returns the value of the argument. That is, no mapping occurs.
Parameters
projectionX Projection x value in meters
Exceptions
IException::Unknown - "The given x-value is invalid."
Returns
double The world X coordinate value.
References _FILEINFO_, m_mapper, Isis::Null, Isis::IException::Unknown, and Isis::WorldMapper::WorldX().
Referenced by Isis::OverlapStatistics::OverlapStatistics(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::ProcessMapMosaic::StartProcess().
ToWorldY()
double Isis::Projection::ToWorldY (const double projectionY) const
This method converts a projection y value to a world y value.
For example, if the world coordinate system is an image then this method converts a projection y to a line position. Note that if SetWorldMapper is not used then this routine simply returns the value of the argument. That is, no mapping occurs.
Parameters
projectionY Projection y value in meters
Exceptions
IException::Unknown - "The given y-value is invalid."
Returns
double The world Y coordinate value.
References _FILEINFO_, m_mapper, Isis::Null, Isis::IException::Unknown, and Isis::WorldMapper::WorldY().
Referenced by Isis::OverlapStatistics::OverlapStatistics(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::ProcessMapMosaic::StartProcess().
Version()
virtual QString Isis::Projection::Version () const pure virtual
This method returns the Version of the map projection.
It is a pure virtual method (requires all subclasses to override).
Returns
string The Version number of the map projection.
Implemented in Isis::TProjection, Isis::RingPlaneProjection, Isis::UpturnedEllipsoidTransverseAzimuthal, Isis::TransverseMercator, Isis::Sinusoidal, Isis::SimpleCylindrical, Isis::Robinson, Isis::RingCylindrical, Isis::PolarStereographic, Isis::PointPerspective, Isis::Planar, Isis::Orthographic, Isis::ObliqueCylindrical, Isis::Mollweide, Isis::Mercator, Isis::LunarAzimuthalEqualArea, Isis::LambertConformal, Isis::LambertAzimuthalEqualArea, and Isis::Equirectangular.
WorldX()
double Isis::Projection::WorldX () const virtual
This returns the world X coordinate provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
Success can also be checked using the IsGood method. The units of X will be in the units as specified by the WorldMapper object which was given to the SetWorldMapper method. If a mapper object was not given then world coordinates are the same as the projection coordinates (i.e., WorldX and XCoord will return the same value).
Returns
double The world X coordinate.
References m_mapper, and Isis::WorldMapper::WorldX().
Referenced by Isis::Chip::Load(), Isis::DemShape::localRadius(), Isis::UniversalGroundMap::Sample(), Isis::Camera::SetRightAscensionDeclination(), and Isis::ProcessMapMosaic::StartProcess().
WorldY()
double Isis::Projection::WorldY () const virtual
This returns the world Y coordinate provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
Success can also be checked using the IsGood method. The units of Y will be in the units as specified by the WorldMapper object which was given to the SetWorldMapper. If a mapper object was not given then world coordinates are the same as the projection coordinates (i.e., WorldY and YCoord will return the same value).
Returns
double The world Y coordinate.
References m_mapper, and Isis::WorldMapper::WorldY().
Referenced by Isis::UniversalGroundMap::Line(), Isis::Chip::Load(), Isis::DemShape::localRadius(), and Isis::Camera::SetRightAscensionDeclination().
XCoord()
double Isis::Projection::XCoord () const
This returns the projection X provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
Success can also be checked using the IsGood method. The units of X will be in the same . units as the radii obtained from the label.
Returns
double
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::ProcessExport::CreateWorldFile(), Isis::MosaicFindTool::getUserGroundPoint(), Isis::GridGraphicsItem::GridGraphicsItem(), Isis::PolygonTools::LatLonToXY(), Isis::MosaicSceneItem::reproject(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::RingPlaneProjection::SetCoordinate(), Isis::TProjection::SetCoordinate(), Isis::MosaicGridTool::setLatExtents(), Isis::SubArea::UpdateLabel(), Isis::MosaicAreaTool::userChangedBox(), Isis::LambertConformal::XYRange(), Isis::PointPerspective::XYRange(), Isis::TProjection::XYRangeCheck(), and Isis::RingPlaneProjection::XYRangeCheck().
XYRange()
virtual bool Isis::Projection::XYRange (double & minX, double & maxX, double & minY, double & maxY) pure virtual
Implemented in Isis::UpturnedEllipsoidTransverseAzimuthal, Isis::TransverseMercator, Isis::TProjection, Isis::Sinusoidal, Isis::SimpleCylindrical, Isis::Robinson, Isis::RingPlaneProjection, Isis::RingCylindrical, Isis::PolarStereographic, Isis::PointPerspective, Isis::Planar, Isis::Orthographic, Isis::ObliqueCylindrical, Isis::Mollweide, Isis::Mercator, Isis::LunarAzimuthalEqualArea, Isis::LambertConformal, Isis::LambertAzimuthalEqualArea, and Isis::Equirectangular.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
XYRangeCheck()
virtual void Isis::Projection::XYRangeCheck (const double latitude, const double longitude) protected pure virtual
Implemented in Isis::RingPlaneProjection, and Isis::TProjection.
YCoord()
double Isis::Projection::YCoord () const
This returns the projection Y provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
Success can also be checked using the IsGood method. The units of Y will be in the same units as the radii obtained from the label.
Returns
double
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::ProcessExport::CreateWorldFile(), Isis::MosaicFindTool::getUserGroundPoint(), Isis::GridGraphicsItem::GridGraphicsItem(), Isis::PolygonTools::LatLonToXY(), Isis::MosaicSceneItem::reproject(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::RingPlaneProjection::SetCoordinate(), Isis::TProjection::SetCoordinate(), Isis::MosaicGridTool::setLatExtents(), Isis::SubArea::UpdateLabel(), Isis::MosaicAreaTool::userChangedBox(), Isis::LambertConformal::XYRange(), Isis::PointPerspective::XYRange(), Isis::TProjection::XYRangeCheck(), and Isis::RingPlaneProjection::XYRangeCheck().
Member Data Documentation
m_good
bool Isis::Projection::m_good protected
Indicates if the contents of m_x, m_y, m_latitude, and m_longitude are valid.
Referenced by IsGood(), Projection(), SetComputedXY(), Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::LunarAzimuthalEqualArea::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Mollweide::SetCoordinate(), Isis::ObliqueCylindrical::SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::Planar::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::RingCylindrical::SetCoordinate(), Isis::RingPlaneProjection::SetCoordinate(), Isis::Robinson::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), Isis::TProjection::SetCoordinate(), Isis::TransverseMercator::SetCoordinate(), Isis::Equirectangular::SetGround(), Isis::LambertConformal::SetGround(), Isis::LunarAzimuthalEqualArea::SetGround(), Isis::Mercator::SetGround(), Isis::Mollweide::SetGround(), Isis::ObliqueCylindrical::SetGround(), Isis::Orthographic::SetGround(), Isis::PointPerspective::SetGround(), Isis::PolarStereographic::SetGround(), Isis::Robinson::SetGround(), Isis::SimpleCylindrical::SetGround(), Isis::Sinusoidal::SetGround(), Isis::TProjection::SetGround(), Isis::TransverseMercator::SetGround(), Isis::Planar::SetGround(), Isis::RingCylindrical::SetGround(), Isis::RingPlaneProjection::SetGround(), SetUnboundUniversalGround(), Isis::TProjection::SetUnboundUniversalGround(), SetUniversalGround(), Isis::TProjection::SetUniversalGround(), Isis::RingPlaneProjection::SetUniversalGround(), SetXY(), Isis::LambertConformal::XYRange(), Isis::TProjection::XYRangeCheck(), and Isis::RingPlaneProjection::XYRangeCheck().
m_groundRangeGood
bool Isis::Projection::m_groundRangeGood protected
Indicates if the ground range (min/max lat/lons) were read from the labels.
Referenced by HasGroundRange(), Isis::RingPlaneProjection::RingPlaneProjection(), Isis::TProjection::TProjection(), Isis::RingPlaneProjection::XYRange(), and Isis::TProjection::XYRange().
m_mapper
WorldMapper* Isis::Projection::m_mapper protected
This points to a mapper passed into the SetWorldMapper method.
This mapper allows the programmer to specify a different world coordinate system. Thus the programmer could pass in line/sample positions in order to obtain a latitude/longitude or set a lat/lon and get a line/sample.
Referenced by Projection(), Resolution(), Isis::RingPlaneProjection::Scale(), Isis::TProjection::Scale(), SetWorld(), SetWorldMapper(), ToProjectionX(), ToProjectionY(), ToWorldX(), ToWorldY(), WorldX(), WorldY(), and ~Projection().
m_mappingGrp
PvlGroup Isis::Projection::m_mappingGrp protected
Mapping group that created this projection.
Referenced by Isis::Equirectangular::Mapping(), Isis::LambertConformal::Mapping(), Isis::LunarAzimuthalEqualArea::Mapping(), Isis::Mercator::Mapping(), Isis::Mollweide::Mapping(), Isis::ObliqueCylindrical::Mapping(), Isis::Orthographic::Mapping(), Isis::PointPerspective::Mapping(), Isis::PolarStereographic::Mapping(), Isis::RingPlaneProjection::Mapping(), Isis::Robinson::Mapping(), Isis::SimpleCylindrical::Mapping(), Isis::Sinusoidal::Mapping(), Isis::TProjection::Mapping(), Isis::TransverseMercator::Mapping(), Isis::Equirectangular::MappingLatitudes(), Isis::LambertConformal::MappingLatitudes(), Isis::Mercator::MappingLatitudes(), Isis::Orthographic::MappingLatitudes(), Isis::PointPerspective::MappingLatitudes(), Isis::PolarStereographic::MappingLatitudes(), Isis::TProjection::MappingLatitudes(), Isis::TransverseMercator::MappingLatitudes(), Isis::Equirectangular::MappingLongitudes(), Isis::LambertConformal::MappingLongitudes(), Isis::Mercator::MappingLongitudes(), Isis::Mollweide::MappingLongitudes(), Isis::Orthographic::MappingLongitudes(), Isis::PointPerspective::MappingLongitudes(), Isis::PolarStereographic::MappingLongitudes(), Isis::Robinson::MappingLongitudes(), Isis::SimpleCylindrical::MappingLongitudes(), Isis::Sinusoidal::MappingLongitudes(), Isis::TProjection::MappingLongitudes(), Isis::TransverseMercator::MappingLongitudes(), Isis::Planar::MappingRingLongitudes(), Isis::RingCylindrical::MappingRingLongitudes(), Isis::RingPlaneProjection::MappingRingLongitudes(), Isis::Planar::MappingRingRadii(), Isis::RingCylindrical::MappingRingRadii(), Isis::RingPlaneProjection::MappingRingRadii(), Projection(), Isis::RingPlaneProjection::RingPlaneProjection(), SetUpperLeftCorner(), and Isis::TProjection::TProjection().
m_maximumX
double Isis::Projection::m_maximumX protected
See minimumX description.
Referenced by Projection(), Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::Planar::XYRange(), Isis::PolarStereographic::XYRange(), Isis::RingCylindrical::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), Isis::TransverseMercator::XYRange(), Isis::TProjection::XYRangeCheck(), Isis::RingPlaneProjection::XYRangeCheck(), and Isis::TProjection::xyRangeOblique().
m_maximumY
double Isis::Projection::m_maximumY protected
See minimumX description.
Referenced by Projection(), Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::Planar::XYRange(), Isis::PolarStereographic::XYRange(), Isis::RingCylindrical::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), Isis::TransverseMercator::XYRange(), Isis::TProjection::XYRangeCheck(), Isis::RingPlaneProjection::XYRangeCheck(), and Isis::TProjection::xyRangeOblique().
m_minimumX
double Isis::Projection::m_minimumX protected
The data elements m_minimumX, m_minimumY, m_maximumX, and m_maximumY are convience data elements when you write the XYRange virtual function.
They are used in conjuction with the XYRangeCheck convience method. After utilizing XYRangeCheck to test boundary conditions in the XYRange method these values will contain the projection x/y coverage for the ground range specified by min/max lat/lon.
Referenced by Projection(), Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::Planar::XYRange(), Isis::PolarStereographic::XYRange(), Isis::RingCylindrical::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), Isis::TransverseMercator::XYRange(), Isis::TProjection::XYRangeCheck(), Isis::RingPlaneProjection::XYRangeCheck(), and Isis::TProjection::xyRangeOblique().
m_minimumY
double Isis::Projection::m_minimumY protected
See minimumX description.
Referenced by Projection(), Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::Planar::XYRange(), Isis::PolarStereographic::XYRange(), Isis::RingCylindrical::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), Isis::TransverseMercator::XYRange(), Isis::TProjection::XYRangeCheck(), Isis::RingPlaneProjection::XYRangeCheck(), and Isis::TProjection::xyRangeOblique().
m_sky
bool Isis::Projection::m_sky protected
Indicates whether projection is sky or land.
Referenced by IsSky(), and Projection().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Projection/Projection.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Projection/Projection.cpp