Isis Developer Reference: Isis::ControlPointList Class Reference
Isis::ControlPointList Class Reference
Control Networks
Control Point List generator.
#include <ControlPointList.h>
Public Member Functions
ControlPointList (const FileName &psFileName)
Creates a ControlPointList from a list of control point ids'.
virtual ~ControlPointList ()
Destructor.
QString ControlPointId (int piIndex)
Return a control point id given an index.
int ControlPointIndex (const QString &psCpId)
return a list index given a control point id
bool HasControlPoint (const QString &psCpId)
Determines whether or not the requested control point id exists in the list.
int Size () const
How many control points in the list.
void RegisterStatistics (Pvl &pcPvlLog)
Register invalid control point and calculate the valid & invalid point count.
Detailed Description
Control Point List generator.
Create a list of Control Points from a file with control points ids
Author
2009-08-11 Sharmila Prasad
Constructor & Destructor Documentation
ControlPointList()
Isis::ControlPointList::ControlPointList (const FileName & psListFile)
Creates a ControlPointList from a list of control point ids'.
Parameters
psListFile The file withe list of control point ids'
References _FILEINFO_, Isis::FileName::expanded(), Isis::toString(), and Isis::IException::User.
~ControlPointList()
Isis::ControlPointList::~ControlPointList () virtual
Destructor.
Member Function Documentation
ControlPointId()
QString Isis::ControlPointList::ControlPointId (int piIndex)
Return a control point id given an index.
Parameters
piIndex The index of the desired control point id
Returns
QString The control point id returned
References _FILEINFO_, Isis::IException::Programmer, Size(), and Isis::toString().
ControlPointIndex()
int Isis::ControlPointList::ControlPointIndex (const QString & psCpId)
return a list index given a control point id
Parameters
ps_cpId The control point id to be searched for
Returns
int The index of the control point id
References _FILEINFO_, HasControlPoint(), and Isis::IException::Programmer.
HasControlPoint()
bool Isis::ControlPointList::HasControlPoint (const QString & psCpId)
Determines whether or not the requested control point id exists in the list.
Parameters
psCpId The control point id to be checked for
Returns
bool
References Size().
Referenced by ControlPointIndex().
RegisterStatistics()
void Isis::ControlPointList::RegisterStatistics (Pvl & pcPvlLog)
Register invalid control point and calculate the valid & invalid point count.
Parameters
Pvl Will contain stats in pvl keywords
References Size(), and Isis::toString().
Size()
int Isis::ControlPointList::Size () const
How many control points in the list.
Returns
int Returns number of control point in the list
Referenced by ControlPointId(), HasControlPoint(), and RegisterStatistics().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/ControlPointList/ControlPointList.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/ControlPointList/ControlPointList.cpp