Isis Developer Reference: Isis::ImageFileListWidget Class Reference
Isis::ImageFileListWidget Class Reference
A colored, grouped cube list.
#include <ImageFileListWidget.h>
Public Slots
void addImages (ImageList *images)
This method adds the new images to the tree.
void removeImages (ImageList *images)
Removes an imagelist from the FileListWidget.
void clear ()
void filterFileList ()
Public Member Functions
ImageFileListWidget (Directory *directory=0, QWidget *parent=0)
Constructor.
virtual ~ImageFileListWidget ()
Destructor.
QProgressBar * getProgress ()
This method returns the progress bar.
void fromPvl (PvlObject &pvl)
This method loads the state of this class from the pvl.
PvlObject toPvl () const
This method writes the state of this class to a pvl.
void save (QXmlStreamWriter &stream, Project *project, FileName newProjectRoot) const
This method saves the FootprintColumns in the project and the settings associated with every column.
QList< QAction * > actions ()
This method calls ImageTreeWidget::actions() which sets up a QAction that sets a default for the file list columns and returns a QList of QPointers that point to the QAction.
QList< QAction * > getViewActions ()
This method calls ImageTreeWidget::getViewActions() which returns a list of FootprintColumns.
QList< QAction * > getExportActions ()
This method creates a new QAction which is connected and when triggered will save the cube list.
Static Public Member Functions
static QWidget * getLongHelp (QWidget *fileListContainer=NULL)
This method creates a QWidget that displays a long help message explaining the tool.
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *event)
This method takes an event and gets all of the FootprintColumns, adds them to the menu, then it pops up the menu at the location of event.
Detailed Description
A colored, grouped cube list.
Author
2011-07-29 Steven Lambright
Constructor & Destructor Documentation
ImageFileListWidget()
Isis::ImageFileListWidget::ImageFileListWidget (Directory * directory = 0, QWidget * parent = 0)
Constructor.
This method sets up the QWidget to show the ImageTreeWidget that is created using directory.
Parameters
directory The directory where you want the ImageTreeWidget to be made
parent The QWidget parent
References clear(), and filterFileList().
Referenced by getLongHelp().
~ImageFileListWidget()
Isis::ImageFileListWidget::~ImageFileListWidget () virtual
Destructor.
Member Function Documentation
actions()
QList< QAction * > Isis::ImageFileListWidget::actions ()
This method calls ImageTreeWidget::actions() which sets up a QAction that sets a default for the file list columns and returns a QList of QPointers that point to the QAction.
Returns
QList<QAction *> The QList of QPointers that point to the QAction set up by ImageTreeWidget::actions().
References Isis::ImageTreeWidget::actions().
Referenced by contextMenuEvent().
addImages
void Isis::ImageFileListWidget::addImages (ImageList * images) slot
This method adds the new images to the tree.
Parameters
images ImageList containing all of the images that need to be added to the tree.
References Isis::ImageTreeWidget::createGroup(), Isis::ImageTreeWidget::createImageListNameItem(), Isis::ImageTreeWidget::ImagePosition::group(), Isis::ImageTreeWidget::groupInList(), Isis::ImageTreeWidget::ImageGroupType, Isis::ImageTreeWidget::ImageListNameType, Isis::ImageTreeWidget::imagesInView(), Isis::ImageTreeWidget::ImagePosition::index(), Isis::ImageTreeWidget::ImagePosition::isValid(), Isis::ImageList::name(), Isis::ImageTreeWidget::prepCube(), and Isis::ImageTreeWidget::refit().
Referenced by Isis::ImageFileListViewWorkOrder::execute().
clear
void Isis::ImageFileListWidget::clear () slot
Referenced by ImageFileListWidget().
contextMenuEvent()
void Isis::ImageFileListWidget::contextMenuEvent (QContextMenuEvent * event) protected
This method takes an event and gets all of the FootprintColumns, adds them to the menu, then it pops up the menu at the location of event.
Parameters
event A QContextMenuEvent that is used to find the position of the mouse.
References actions(), and Isis::ImageTreeWidget::getViewActions().
filterFileList
void Isis::ImageFileListWidget::filterFileList () slot
References Isis::Image::fileName(), and Isis::ImageTreeWidgetItem::image().
Referenced by ImageFileListWidget().
fromPvl()
void Isis::ImageFileListWidget::fromPvl (PvlObject & pvl)
This method loads the state of this class from the pvl.
Parameters
pvl The pvl that we are reading the state from.
Exceptions
IException::Io "Unable to read image file's list widget settings from Pvl"
References _FILEINFO_, Isis::ImageTreeWidget::addGroup(), Isis::ImageTreeWidgetItem::BlankColumn, Isis::IString::Convert(), Isis::ImageTreeWidgetItem::FootprintColumn, Isis::PvlObject::hasKeyword(), Isis::IException::Io, Isis::PvlContainer::name(), Isis::PvlObject::object(), Isis::PvlObject::objects(), Isis::toBool(), Isis::IString::ToQt(), Isis::ImageTreeWidgetItem::treeColumnToString(), and Isis::ImageTreeWidget::updateViewActs().
getExportActions()
QList< QAction * > Isis::ImageFileListWidget::getExportActions ()
This method creates a new QAction which is connected and when triggered will save the cube list.
Returns
QList<QAction *> The QList of the new QAction.
getLongHelp()
QWidget * Isis::ImageFileListWidget::getLongHelp (QWidget * fileListContainer = NULL) static
This method creates a QWidget that displays a long help message explaining the tool.
Returns
QWidget Returns the message QWidget that was made.
References ImageFileListWidget().
getProgress()
QProgressBar * Isis::ImageFileListWidget::getProgress ()
This method returns the progress bar.
Returns
QProgressBar * Returns the ProgressBar
getViewActions()
QList< QAction * > Isis::ImageFileListWidget::getViewActions ()
This method calls ImageTreeWidget::getViewActions() which returns a list of FootprintColumns.
Returns
QList<QAction *> The QList of FootprintColumns.
References Isis::ImageTreeWidget::getViewActions().
removeImages
void Isis::ImageFileListWidget::removeImages (ImageList * images) slot
Removes an imagelist from the FileListWidget.
This would normally be handled elsewhere but for IPCE it needs a method to hide images and update the tree.
Parameters
ImageList containing the images to remove from the tree
References Isis::ImageTreeWidgetItem::image().
save()
void Isis::ImageFileListWidget::save (QXmlStreamWriter & stream, Project * project, FileName newProjectRoot) const
This method saves the FootprintColumns in the project and the settings associated with every column.
Parameters
stream The QXmlStreamWriter that saves the FootprintColumns.
project The current project being saved.
newProjectRoot This is not used.
References Isis::ImageTreeWidgetItem::BlankColumn, Isis::ImageTreeWidgetItem::FootprintColumn, and Isis::ImageTreeWidgetItem::treeColumnToString().
Referenced by Isis::Directory::save(), and Isis::Footprint2DView::save().
toPvl()
PvlObject Isis::ImageFileListWidget::toPvl () const
This method writes the state of this class to a pvl.
Returns
PvlObject The pvl that we are writing too.
References Isis::ImageTreeWidgetItem::BlankColumn, Isis::IString::Convert(), Isis::ImageTreeWidgetItem::FootprintColumn, Isis::Image::id(), Isis::ImageTreeWidgetItem::image(), Isis::ImageTreeWidgetItem::NameColumn, Isis::IString::ToQt(), Isis::toString(), and Isis::ImageTreeWidgetItem::treeColumnToString().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ImageFileListWidget/ImageFileListWidget.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ImageFileListWidget/ImageFileListWidget.cpp