Isis Developer Reference: Isis::NaifStatus Class Reference
Isis::NaifStatus Class Reference
Class for checking for errors in the NAIF library.
#include <NaifStatus.h>
Static Public Member Functions
static void CheckErrors (bool resetNaif=true)
This method looks for any naif errors that might have occurred.
Detailed Description
Class for checking for errors in the NAIF library.
The Naif Status class looks for errors that have occurred in NAIF calls. If an error has occurred, it will be converted to an iException.
Author
2008-06-13 Steven Lambright
Member Function Documentation
CheckErrors()
void Isis::NaifStatus::CheckErrors (bool resetNaif = true) static
This method looks for any naif errors that might have occurred.
It then compares the error to a list of known naif errors and converts the error into an iException.
Parameters
resetNaif True if the NAIF error status should be reset (naif calls valid)
References _FILEINFO_, Isis::PvlObject::addGroup(), Isis::PvlContainer::addKeyword(), Isis::PvlToPvlTranslationManager::Translate(), and Isis::IException::Unknown.
Referenced by Isis::SpiceRotation::Angles(), Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::SpiceRotation::CacheLabel(), Isis::DemShape::calculateDefaultNormal(), Isis::EllipsoidShape::calculateLocalNormal(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::LightTimeCorrectionState::checkSpkKernelsForAberrationCorrection(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ClipperWacFcCamera::ClipperWacFcCamera(), Isis::SpiceRotation::ComputeAv(), Isis::SpicePosition::computeStateVector(), Isis::SpiceRotation::ConstantRotation(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::SpiceRotation::DCJdt(), Isis::BulletShapeModel::ellipsoidNormal(), Isis::EmbreeShapeModel::ellipsoidNormal(), Isis::NaifDskShape::ellipsoidNormal(), Isis::SpiceRotation::Extrapolate(), Isis::SpiceRotation::FrameTrace(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IdealCamera::IdealCamera(), Isis::DemShape::intersectSurface(), Isis::EquatorialCylindricalShape::intersectSurface(), Isis::PlaneShape::intersectSurface(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::SpiceRotation::J2000Vector(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::SpiceRotation::loadPCFromSpice(), Isis::SpiceRotation::loadPCFromTable(), Isis::SpiceRotation::LoadTimeCache(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::LwirCamera::LwirCamera(), Isis::MarciCamera::MarciCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::SpiceRotation::Matrix(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::NirCamera::NirCamera(), Isis::ObliqueCylindrical::ObliqueCylindrical(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::NaifDskPlateModel::plate(), Isis::NaifDskPlateModel::plateIdOfIntercept(), Isis::NaifDskPlateModel::point(), Isis::EmbreeTargetShape::readDSK(), Isis::SpiceRotation::ReferenceVector(), Isis::SpicePosition::ReloadCache(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::Quaternion::Set(), Isis::SpicePosition::SetEphemerisTime(), Isis::SpiceRotation::setEphemerisTimeMemcache(), Isis::SpiceRotation::setEphemerisTimeNadir(), Isis::SpiceRotation::setEphemerisTimePolyFunction(), Isis::SpiceRotation::setEphemerisTimePolyFunctionOverSpice(), Isis::SpiceRotation::setEphemerisTimeSpice(), Isis::CameraSkyMap::SetFocalPlane(), Isis::SpiceRotation::SetPolynomial(), Isis::SpiceRotation::SpiceRotation(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::ThemisVisCamera::ThemisVisCamera(), Isis::SpiceRotation::TimeBasedRotation(), Isis::Quaternion::ToAngles(), Isis::SpiceRotation::toJ2000Partial(), Isis::SpiceRotation::ToReferencePartial(), Isis::UvvisCamera::UvvisCamera(), Isis::VikingCamera::VikingCamera(), Isis::VimsCamera::VimsCamera(), Isis::VoyagerCamera::VoyagerCamera(), and Isis::SpiceRotation::WrapAngle().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/NaifStatus/NaifStatus.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/NaifStatus/NaifStatus.cpp