Isis Developer Reference: Isis::SocketThread Class Reference
Isis::SocketThread Class Reference
#include <SocketThread.h>
Signals
void newImage (const QString &image)
New image signal.
void focusApp ()
Application has focus signal.
Public Member Functions
SocketThread (QObject *parent=0)
Constructor for the SocketThread.
~SocketThread ()
Destroys the SocketThread object.
void run ()
Starts the socket thread.
void stop ()
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
SocketThread()
Isis::SocketThread::SocketThread (QObject * parent = 0)
Constructor for the SocketThread.
Parameters
parent
~SocketThread()
Isis::SocketThread::~SocketThread ()
Destroys the SocketThread object.
Member Function Documentation
focusApp
void Isis::SocketThread::focusApp () signal
Application has focus signal.
Referenced by run().
newImage
void Isis::SocketThread::newImage (const QString & image) signal
New image signal.
Parameters
image
Referenced by run().
run()
void Isis::SocketThread::run ()
Starts the socket thread.
References errno, focusApp(), newImage(), Isis::IString::Token(), and Isis::Application::UserName().
stop()
void Isis::SocketThread::stop () inline
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/SocketThread/SocketThread.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/SocketThread/SocketThread.cpp