Isis Developer Reference: Isis::FileName Class Reference
Isis::FileName Class Reference
Parsing
File name manipulation and expansion.
#include <FileName.h>
Public Member Functions
FileName ()
Constructs an empty FileName object.
FileName (const char *fileName)
Constructs a FileName object using a char pointer as a file name.
FileName (const QString &fileName)
Constructs a FileName object using a QString as a file name.
FileName (const FileName &other)
Constructs a copy of a FileName object using another FileName object.
~FileName ()
Destroys the FileName object.
QString originalPath () const
Returns the path of the original file name.
QString path () const
Returns the path of the file name.
QString attributes () const
Returns a QString of the attributes in a filename, attributes are expected to be of type CubeAttributeInput or CubeAttributeOutput.
QString baseName () const
Returns the name of the file without the path and without extensions.
QString name () const
Returns the name of the file excluding the path and the attributes in the file name.
QString extension () const
Returns the last extension of the file name.
QString expanded () const
Returns a QString of the full file name including the file path, excluding the attributes.
QString original () const
Returns the full file name including the file path.
FileName addExtension (const QString &extension) const
Adds a new extension to the file name.
FileName removeExtension () const
Removes all extensions in the file name.
FileName setExtension (const QString &extension) const
Sets all current file extensions to a new extension in the file name.
bool isVersioned () const
Checks to see if a file name is versioned by date or numerically.
bool isNumericallyVersioned () const
Checks if the file name is versioned numerically.
bool isDateVersioned () const
Checks if the file name is versioned by date.
FileName highestVersion () const
Searches the directory specified in the file name for the highest version of the file name.
FileName newVersion () const
Updates the file name to be the latest version.
bool fileExists () const
Returns true if the file exists; false otherwise.
QDir dir () const
Returns the path of the file's parent directory as a QDir object.
QString toString () const
Returns a QString of the full file name including the file path, excluding the attributes with any Isis Preferences or environment variables indicated by $, changed to what they represent.
FileName & operator= (const FileName &rhs)
Clears the current contents of the FileName object and reinitializes it with the argument.
bool operator== (const FileName &rhs)
Compares equality of two FileName objects.
bool operator!= (const FileName &rhs)
Compares equality of two FileName objects.
Static Public Member Functions
static FileName createTempFile (FileName templateFileName="$TEMPORARY/temp")
Creates a temporary file and returns a FileName object created using the temporary file.
Detailed Description
File name manipulation and expansion.
This class is used for manipulating filenames. It allows access to the path, extension, base name and Isis attributes. A standard Isis filename takes the form of
/path/base.extension+attribute
For example:
/work1/mars.cub+5
Author
2002-06-11 Jeff Anderson
Constructor & Destructor Documentation
FileName() [1/4]
Isis::FileName::FileName ()
Constructs an empty FileName object.
Referenced by addExtension(), createTempFile(), isDateVersioned(), isNumericallyVersioned(), and removeExtension().
FileName() [2/4]
Isis::FileName::FileName (const char * file)
Constructs a FileName object using a char pointer as a file name.
Parameters
file char pointer representing new filename
FileName() [3/4]
Isis::FileName::FileName (const QString & file)
Constructs a FileName object using a QString as a file name.
Parameters
file Qstring representing new filename
FileName() [4/4]
Isis::FileName::FileName (const FileName & other)
Constructs a copy of a FileName object using another FileName object.
Parameters
&other FileName object to copy.
~FileName()
Isis::FileName::~FileName ()
Destroys the FileName object.
Member Function Documentation
addExtension()
FileName Isis::FileName::addExtension (const QString & newExtension) const
Adds a new extension to the file name.
If the current extension is the same as the new extension it will return an unchanged FileName object.
Parameters
newExtension The new file extension to be added at the end of the file name after all exisiting extensions.
Returns
FileName object with added extension
References attributes(), extension(), FileName(), name(), and originalPath().
Referenced by Isis::Cube::create(), IsisAml::GetCubeName(), IsisAml::GetFileName(), Isis::TextFile::Open(), setExtension(), Isis::Cube::write(), Isis::ImageExporter::write(), Isis::JP2Exporter::write(), Isis::QtExporter::write(), and Isis::TiffExporter::write().
attributes()
QString Isis::FileName::attributes () const
Returns a QString of the attributes in a filename, attributes are expected to be of type CubeAttributeInput or CubeAttributeOutput.
Filenames without any attributes return an empty QString.
  for a full file specification of:
   "/tmp/Peaks.cub+Bsq"
  attributes() gives:
   "Bsq"
Returns
QString of the attributes specified in the filename.
Referenced by Isis::CubeAttribute< ChildClass >::addAttributes(), addExtension(), IsisAml::GetCubeName(), removeExtension(), and Isis::CubeAttribute< ChildClass >::setAttributes().
baseName()
QString Isis::FileName::baseName () const
Returns the name of the file without the path and without extensions.
  for a full file specification of:
   "/tmp/Peaks.cub.gz"
  baseName() gives:
   "Peaks"
Returns
QString containing every character excluding the path and all extensions.
Referenced by Isis::ProcessPolygons::AppendOutputCube(), Isis::PipelineApplication::BuildParamString(), createTempFile(), Isis::EmbreeTargetShape::EmbreeTargetShape(), Isis::Pipeline::FinalOutput(), Isis::BundleLidarRangeConstraint::formatBundleOutputString(), Isis::Cube::fromIsd(), Isis::Equalization::generateOutputs(), Isis::ProcessExportPds4::identificationArea(), Isis::JigsawSetupDialog::JigsawSetupDialog(), Isis::ImportPdsTable::load(), removeExtension(), Isis::ProcessPolygons::SetStatCubes(), Isis::ProcessGroundPolygons::SetStatCubes(), and Isis::ProcessExportPds4::WritePds4().
createTempFile()
FileName Isis::FileName::createTempFile (FileName templateFileName = "$TEMPORARY/temp") static
Creates a temporary file and returns a FileName object created using the temporary file.
Parameters
templateFileName the file name used to create the temporary file.
Returns
FileName object created using the temporary file
Exceptions
Isis::IException::Io
References _FILEINFO_, baseName(), extension(), FileName(), Isis::IException::Io, original(), originalPath(), and path().
dir()
QDir Isis::FileName::dir () const
Returns the path of the file's parent directory as a QDir object.
  for a full file specification of:
   "/tmp/Peaks.cub+Bsq"
  dir() gives:
   "/tmp/"
Returns
QDir
References expanded().
Referenced by Isis::Project::addControl(), Isis::Control::copyToNewProjectRoot(), Isis::ControlList::save(), Isis::ImageList::save(), Isis::ShapeList::save(), Isis::TemplateList::save(), Isis::GuiFileNameParameter::SelectFile(), Isis::BundleSolutionInfo::updateFileName(), Isis::Control::updateFileName(), Isis::Image::updateFileName(), Isis::Shape::updateFileName(), and Isis::UserInterface::UserInterface().
expanded()
QString Isis::FileName::expanded () const
Returns a QString of the full file name including the file path, excluding the attributes.
Any Isis Preferences or environment variables indicated by $, are changed to what they represent.
Returns
QString
  for a full file specification of:
   QString(ISISROOT) + "/tmp/Peaks.cub+Bsq"
  expanded() gives:
   "/usgs/pkgs/isis3/isis/tmp/Peaks.cub"
Any Isis Preferences or environment variables indicated by $, are changed to what they represent.
  for a full file specification of:
   "$ISISROOT/tmp/Peaks.cub+Bsq"
  expanded() gives:
   "/usgs/pkgs/isis3/isis/tmp/Peaks.cub"
Returns
QString
Referenced by Isis::SerialNumberList::add(), Isis::CubeDataThread::AddCube(), Isis::GuiParameter::AddHelpers(), Isis::PushFrameCameraCcdLayout::addKernel(), Isis::Pvl::append(), Isis::Application::Application(), Isis::Blob::Blob(), Isis::CnetEditorView::CnetEditorView(), Isis::CorrelationMatrix::computeCorrelationMatrix(), Isis::ControlPointList::ControlPointList(), Isis::TiffImporter::convertProjection(), Isis::Cube::copy(), Isis::Cube::create(), Isis::ProjectionFactory::Create(), Isis::Spice::createCache(), Isis::ControlPointEditWidget::createControlPoint(), Isis::ImageImporter::createOutput(), Isis::Image::deleteFromDisk(), Isis::Shape::deleteFromDisk(), dir(), Isis::ProcessExportPds4::displaySettings(), Isis::Module::Dump(), Isis::EmbreeTargetShape::EmbreeTargetShape(), Isis::ImportMapTemplateWorkOrder::execute(), Isis::ImportRegistrationTemplateWorkOrder::execute(), Isis::ProcessImportFits::extraFitsLabel(), Isis::ProcessExportPds4::fileAreaObservational(), fileExists(), Isis::SerialNumberList::fileNameIndex(), Isis::ProcessImportFits::fitsImageLabel(), Isis::fitsToJson(), Isis::ImageImporter::fromFileName(), Isis::Cube::fromIsd(), Isis::Cube::fromLabel(), Isis::ControlNetStatistics::GeneratePointStats(), IsisAml::GetCubeName(), IsisAml::GetFileName(), Isis::MosaicTool::getIcon(), Isis::Plugin::GetPlugin(), Isis::GuiFileNameParameter::GuiFileNameParameter(), Isis::ProcessExportPds4::identificationArea(), Isis::CameraFactory::initPlugin(), Isis::BundleSolutionInfo::inputControlNetFileName(), Isis::BundleSolutionInfo::inputLidarDataFileName(), isDateVersioned(), isNumericallyVersioned(), Isis::JP2Importer::JP2Importer(), Isis::LoadCSV::load(), Isis::ImportPdsTable::load(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MdiCubeViewport::MdiCubeViewport(), Isis::Process::MissionData(), Isis::ObservationNumberList::observationNumber(), Isis::TextFile::Open(), Isis::CubeManager::OpenCube(), Isis::operator<<(), operator==(), Isis::BundleSolutionInfo::outputHeader(), Isis::XmlToPvlTranslationManager::parseFile(), path(), Isis::Preference::Preferences(), Isis::ControlNetStatistics::PrintImageStats(), Isis::ProcessImport::ProcessBil(), Isis::ProcessImport::ProcessBip(), Isis::ProcessImport::ProcessBsq(), Isis::ProcessImportPds::ProcessLabel(), Isis::Project::Project(), Isis::CorrelationMatrix::pvlObject(), Isis::PvlTranslationTable::PvlTranslationTable(), Isis::QIsisApplication::QIsisApplication(), Isis::QtImporter::QtImporter(), Isis::Pvl::read(), Isis::LidarData::read(), Isis::EmbreeTargetShape::readDSK(), Isis::OriginalXmlLabel::readFromXmlFile(), Isis::ImageOverlapSet::ReadImageOverlaps(), Isis::EmbreeTargetShape::readPC(), Isis::FileDialog::readSettings(), Isis::PaletteWindow::readSettings(), Isis::SpecialPixelTool::readSettings(), Isis::Cube::reopen(), Isis::ProjectionFactory::RingsCreate(), Isis::ProgramLauncher::RunIsisProgram(), Isis::BundleSolutionInfo::save(), Isis::UserInterface::SaveHistory(), Isis::ScatterPlotWindow::ScatterPlotWindow(), Isis::GuiFileNameParameter::SelectFile(), Isis::SerialNumberList::serialNumber(), Isis::CorrelationMatrix::setCovarianceFileName(), Isis::ProcessImportFits::setFitsFile(), Isis::Pipeline::SetInputListFile(), Isis::MdiCubeViewport::setLinked(), Isis::Pipeline::SetOutputFile(), Isis::ControlNetFilter::SetOutputFile(), Isis::Pipeline::SetOutputListFile(), Isis::ImportImagesWorkOrder::setupExecution(), Isis::ImportShapesWorkOrder::setupExecution(), Isis::SpectralDefinition2D::SpectralDefinition2D(), Isis::ProcessExportPds::StandardImageImage(), Isis::ProcessExportPds4::standardInstrument(), Isis::ProcessExportPds::StandardJP2Image(), Isis::ProcessMosaic::StartProcess(), Isis::TiffImporter::TiffImporter(), Isis::Tool::Tool(), toString(), Isis::ProcessExportPds4::translateBandBinImage(), Isis::ProcessExportPds4::translateBandBinSpectrumBinSet(), Isis::ProcessExportPds4::translateBandBinSpectrumUniform(), Isis::ProcessImportPds::TranslatePdsProjection(), Isis::BundleSolutionInfo::updateFileName(), Isis::Control::updateFileName(), Isis::Image::updateFileName(), Isis::Shape::updateFileName(), Isis::BlinkTool::updateTool(), Isis::VikingCamera::VikingCamera(), Isis::VoyagerCamera::VoyagerCamera(), Isis::WarningWidget::WarningWidget(), Isis::Cube::write(), Isis::Pvl::write(), Isis::ControlNetVersioner::write(), Isis::JP2Exporter::write(), Isis::QtExporter::write(), Isis::TiffExporter::write(), Isis::LidarData::write(), Isis::ImageOverlapSet::WriteImageOverlaps(), Isis::ProcessExportPds4::WritePds4(), Isis::FileDialog::writeSettings(), Isis::PaletteWindow::writeSettings(), Isis::SpecialPixelTool::writeSettings(), Isis::QnetNavTool::~QnetNavTool(), Isis::ScatterPlotWindow::~ScatterPlotWindow(), and Isis::Spice::~Spice().
extension()
QString Isis::FileName::extension () const
Returns the last extension of the file name.
  for a full file specification of:
   "/tmp/Peaks.cub.gz"
  extension() gives:
   "gz"
Returns
QString containing every character in the file name after the last "." character.
Referenced by addExtension(), Isis::ProcessPolygons::AppendOutputCube(), Isis::ShapeModelFactory::create(), createTempFile(), Isis::EmbreeTargetShape::EmbreeTargetShape(), Isis::Equalization::generateOutputs(), Isis::BulletTargetShape::load(), Isis::SpectralDefinitionFactory::NewSpectralDefinition(), setExtension(), Isis::ImportImagesWorkOrder::setupExecution(), Isis::ImportShapesWorkOrder::setupExecution(), and Isis::ProcessExportPds4::WritePds4().
fileExists()
bool Isis::FileName::fileExists () const
Returns true if the file exists; false otherwise.
If the file is a symlink that points to a nonexistent file, false is returned.
Returns
Boolean
References expanded().
Referenced by Isis::DatabaseFactory::addAccessProfile(), Isis::Application::Application(), Isis::TiffImporter::convertProjection(), Isis::ProjectionFactory::Create(), Isis::InterestOperatorFactory::Create(), Isis::AutoRegFactory::Create(), Isis::PhotoModelFactory::Create(), Isis::PolygonSeederFactory::Create(), Isis::AtmosModelFactory::Create(), Isis::NormModelFactory::Create(), Isis::CameraFactory::initPlugin(), Isis::OpenProjectWorkOrder::isExecutable(), Isis::ImportPdsTable::load(), Isis::KernelDb::loadSystemDb(), Isis::Process::MissionData(), newVersion(), Isis::TextFile::Open(), Isis::operator<<(), Isis::Preference::Preferences(), Isis::ProcessImportPds::ProcessLabel(), Isis::EmbreeTargetShape::readDSK(), Isis::ProjectionFactory::RingsCreate(), Isis::ProgramLauncher::RunIsisProgram(), Isis::UserInterface::SaveHistory(), Isis::ImportImagesWorkOrder::setupExecution(), Isis::Directory::updateRecentProjects(), and Isis::UserInterface::UserInterface().
highestVersion()
FileName Isis::FileName::highestVersion () const
Searches the directory specified in the file name for the highest version of the file name.
Returns a FileName object with the file name changed to reflect the highest version.
Returns
FileName object
References _FILEINFO_, isDateVersioned(), isNumericallyVersioned(), isVersioned(), name(), originalPath(), and Isis::IException::Unknown.
Referenced by Isis::PushFrameCameraCcdLayout::addKernel(), and Isis::Process::MissionData().
isDateVersioned()
bool Isis::FileName::isDateVersioned () const
Checks if the file name is versioned by date.
Returns true if the file is versioned by date; returns false otherwise.
Returns
Boolean
References expanded(), and FileName().
Referenced by highestVersion(), isVersioned(), and newVersion().
isNumericallyVersioned()
bool Isis::FileName::isNumericallyVersioned () const
Checks if the file name is versioned numerically.
Returns true if the file is versioned numerically; returns false otherwise.
Returns
Boolean
References expanded(), and FileName().
Referenced by highestVersion(), isVersioned(), and newVersion().
isVersioned()
bool Isis::FileName::isVersioned () const
Checks to see if a file name is versioned by date or numerically.
Returns true if file is versioned by date or numerically; returns false otherwise.
Returns
Boolean
References isDateVersioned(), and isNumericallyVersioned().
Referenced by Isis::PushFrameCameraCcdLayout::addKernel(), highestVersion(), and newVersion().
name()
QString Isis::FileName::name () const
Returns the name of the file excluding the path and the attributes in the file name.
  for a full file specification of:
   "/tmp/Peaks.cub+Bsq"
  name() gives:
   "Peaks.cub"
Returns
QString containing every character in the file name exluding the path and attributes of the file.
Referenced by addExtension(), Isis::Directory::addTemplateEditorView(), Isis::ControlPointEditWidget::addTemplates(), Isis::Application::Application(), Isis::ControlNetDiff::compare(), Isis::ObservationNumber::Compose(), Isis::SerialNumber::Compose(), Isis::Control::copyToNewProjectRoot(), Isis::Image::copyToNewProjectRoot(), Isis::Shape::copyToNewProjectRoot(), Isis::Cube::create(), Isis::QnetPointCubeNameFilter::createCubeList(), Isis::MatchTool::createPoint(), Isis::ImportMapTemplateWorkOrder::execute(), Isis::ImportRegistrationTemplateWorkOrder::execute(), Isis::TrackingTable::fileNameToPixel(), Isis::ProcessExportPds::FixedImageRoot(), Isis::ProcessExportPds::FixedJP2ImageRoot(), Isis::ControlMeasure::GetChooserName(), Isis::ControlPoint::GetChooserName(), Isis::CorrelationMatrix::hasCovMat(), highestVersion(), Isis::CorrelationMatrix::isValid(), Isis::JigsawRunWidget::JigsawRunWidget(), Isis::ImportPdsTable::load(), newVersion(), Isis::Cube::open(), Isis::QnetNavTool::resetList(), Isis::ProgramLauncher::RunIsisProgram(), Isis::Project::save(), Isis::BundleSolutionInfo::save(), Isis::TemplateList::save(), Isis::JigsawSetupDialog::selectControl(), Isis::GuiFileNameParameter::SelectFile(), Isis::Pipeline::SetInputListFile(), Isis::ExportControlNetWorkOrder::setupExecution(), Isis::ProcessMapMosaic::StartProcess(), Isis::ProcessExportPds::StreamImageRoot(), Isis::ProcessExportPds::StreamJP2ImageRoot(), Isis::BundleSolutionInfo::updateFileName(), Isis::Control::updateFileName(), Isis::Image::updateFileName(), Isis::Shape::updateFileName(), Isis::Template::updateFileName(), Isis::Cube::write(), and Isis::ProcessExportPds4::WritePds4().
newVersion()
FileName Isis::FileName::newVersion () const
Updates the file name to be the latest version.
If the file is versioned by date the newest version will be the current date. If the file is versioned numerically, the newest version will be the current version plus one.
Returns
FileName object with the new version file name.
Exceptions
Isis::IException::Unknown
References _FILEINFO_, fileExists(), isDateVersioned(), isNumericallyVersioned(), isVersioned(), name(), originalPath(), and Isis::IException::Unknown.
operator!=()
bool Isis::FileName::operator!= (const FileName & rhs)
Compares equality of two FileName objects.
Returns false if the two objects are equal and true otherwise.
Parameters
rhs FileName to compare the current FileName object to.
Returns
Boolean
operator=()
FileName & Isis::FileName::operator= (const FileName & rhs)
Clears the current contents of the FileName object and reinitializes it with the argument.
Parameters
rhs FileName to replace the current contents of the object.
Returns
void
operator==()
bool Isis::FileName::operator== (const FileName & rhs)
Compares equality of two FileName objects.
Returns true if the two objects are equal and false otherwise.
Parameters
rhs FileName to compare the current FileName object to.
Returns
Boolean
References expanded().
original()
QString Isis::FileName::original () const
Returns the full file name including the file path.
Returns
QString containing every character in the file name and the path
  for a full file specification of:
   QString(ISISROOT) + "/tmp/Peaks.cub+Bsq"
  original() gives:
   QString(ISISROOT) + "/tmp/Peaks.cub+Bsq"
  for a full file specification of:
   "$ISISROOT/tmp/Peaks.cub+Bsq"
  original() gives:
   "$ISISROOT/tmp/Peaks.cub+Bsq"
Returns
QString containing every character in the file name and the path
Referenced by Isis::Cube::copy(), createTempFile(), Isis::Process::MissionData(), Isis::Cube::open(), Isis::Cube::relocateDnData(), Isis::Project::save(), Isis::ControlList::save(), Isis::ImageList::save(), Isis::ShapeList::save(), Isis::TemplateList::save(), Isis::Pipeline::SetInputFile(), Isis::ImportImagesWorkOrder::setupExecution(), and Isis::ImportShapesWorkOrder::setupExecution().
originalPath()
QString Isis::FileName::originalPath () const
Returns the path of the original file name.
For *nix operating systems this includes everything up to but not including the last slash "/". For filenames created without any slashes the current working directory will be returned.
  for a full file specification of:
   "/home/me/img/picture.jpg"
  originalPath() gives:
   "/home/me/img"
Returns
QString of the path portion of the original filename.
Referenced by Isis::Directory::addBundleObservationView(), addExtension(), createTempFile(), highestVersion(), newVersion(), Isis::Cube::open(), removeExtension(), and Isis::ProcessExportPds4::WritePds4().
path()
QString Isis::FileName::path () const
Returns the path of the file name.
For *nix operating systems this includes everything up to but not including the last slash "/". For filenames created without any slashes the current working directory will be returned.
  for a full file specification of:
   "/home/me/img/picture.jpg"
  path() gives:
   "/home/me/img"
Returns
QString of the path portion of the filename.
References expanded().
Referenced by Isis::ProcessPolygons::AppendOutputCube(), Isis::Image::copyToNewProjectRoot(), Isis::Shape::copyToNewProjectRoot(), createTempFile(), Isis::Image::deleteFromDisk(), Isis::Shape::deleteFromDisk(), Isis::ProcessExportPds::ExportTable(), Isis::Pipeline::FinalOutput(), Isis::Blob::Find(), Isis::Equalization::generateOutputs(), Isis::ImportPdsTable::load(), Isis::QnetFileTool::open(), Isis::ProcessImportPds::ProcessLabel(), Isis::BundleSolutionInfo::save(), Isis::ControlList::save(), Isis::ImageList::save(), Isis::ShapeList::save(), Isis::TemplateList::save(), Isis::ProcessPolygons::SetStatCubes(), Isis::ProcessGroundPolygons::SetStatCubes(), Isis::CubeViewport::setTrackingCube(), Isis::ImportImagesWorkOrder::setupExecution(), Isis::ImportShapesWorkOrder::setupExecution(), and Isis::ProcessMosaic::StartProcess().
removeExtension()
FileName Isis::FileName::removeExtension () const
Removes all extensions in the file name.
Returns
FileName object with all extensions removed
References attributes(), baseName(), FileName(), and originalPath().
Referenced by setExtension(), Isis::ProcessMosaic::StartProcess(), and Isis::Cube::write().
setExtension()
FileName Isis::FileName::setExtension (const QString & newExtension) const
Sets all current file extensions to a new extension in the file name.
Parameters
newExtension The new file extension to replace any current file extensions with
Returns
FileName object with all existing extensions replaced by the new extension
References addExtension(), extension(), and removeExtension().
Referenced by Isis::Image::copyToNewProjectRoot(), Isis::Shape::copyToNewProjectRoot(), Isis::Cube::create(), Isis::Image::deleteFromDisk(), Isis::Shape::deleteFromDisk(), and Isis::LidarData::write().
toString()
QString Isis::FileName::toString () const
Returns a QString of the full file name including the file path, excluding the attributes with any Isis Preferences or environment variables indicated by $, changed to what they represent.
Returns
QString
  for a full file specification of:
   QString(ISISROOT) + "/tmp/Peaks.cub+Bsq"
  toString() gives:
   "/usgs/pkgs/isis3/isis/tmp/Peaks.cub"
  for a full file specification of:
   "$ISISROOT/tmp/Peaks.cub+Bsq"
  toString() gives:
   "/usgs/pkgs/isis3/isis/tmp/Peaks.cub"
Returns
QString
References expanded().
Referenced by Isis::Control::copyToNewProjectRoot(), Isis::Image::copyToNewProjectRoot(), Isis::Shape::copyToNewProjectRoot(), Isis::Cube::Cube(), Isis::ProcessImportFits::extraFitsLabel(), Isis::ProcessImportFits::fitsImageLabel(), Isis::fitsToJson(), Isis::Cube::fromIsd(), Isis::Cube::fromLabel(), Isis::TextFile::Open(), Isis::Cube::read(), Isis::FileList::read(), Isis::Project::save(), Isis::BundleSolutionInfo::save(), Isis::ControlList::save(), Isis::ImageList::save(), Isis::ShapeList::save(), Isis::TemplateList::save(), Isis::ProcessImportFits::setFitsFile(), Isis::SpectralDefinition1D::SpectralDefinition1D(), Isis::SpectralDefinition2D::SpectralDefinition2D(), and Isis::FileList::write().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/FileName/FileName.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/FileName/FileName.cpp