Isis Developer Reference: Isis::VisualDisplay Class Reference
Isis::VisualDisplay Class Reference
Tool to visualize statistics in an n * m box.
#include <StatisticsTool.h>
Signals
void setDn (const QString st)
Signal to set the DN label to st.
void setSample (const QString st)
Signal to set the Sample label to st.
void setLine (const QString st)
Signal to set the Line label to st.
Public Member Functions
VisualDisplay (QWidget *parent=0)
Constructor for visual display.
QSize sizeHint () const
Size hint for this widget.
void setSamples (int samps)
Set box sample size.
void setLines (int lines)
Set box line size.
void updateSize ()
Update the size of the box.
void setPixelData (QVector< QVector< double > > data, int samp, int line)
Set pixel data and upper left sample/line.
Protected Slots
void setBoxSize (int size)
Set box size in pixels.
void showText (bool b)
Show/Hide text.
void showPixels (bool b)
Show/Hide pixels.
void showDeviation (bool b)
Show/Hide deviation.
Protected Member Functions
void paintPixmap ()
Paint the pixmap.
void paintEvent (QPaintEvent *event)
Paint pixmap to the widget.
void mouseMoveEvent (QMouseEvent *event)
Called when the mouse moves over this widget.
void leaveEvent (QEvent *event)
Mouse left widget, update labels.
Detailed Description
Tool to visualize statistics in an n * m box.
This tool is used to visualize statistics in an n * m box specified by the user. It allows for textual and visual representation of the DN values in the region as well as the standard deviation over the box.
Author
2009-10-07 Noah Hilt
Constructor & Destructor Documentation
VisualDisplay()
Isis::VisualDisplay::VisualDisplay (QWidget * parent = 0)
Constructor for visual display.
Parameters
parent
References Isis::Null, paintPixmap(), Isis::Stretch::SetHis(), Isis::Stretch::SetHrs(), Isis::Stretch::SetLis(), Isis::Stretch::SetLrs(), Isis::Stretch::SetMaximum(), Isis::Stretch::SetMinimum(), and Isis::Stretch::SetNull().
Member Function Documentation
leaveEvent()
void Isis::VisualDisplay::leaveEvent (QEvent * event) protected
Mouse left widget, update labels.
Parameters
event
References setDn(), setLine(), and setSample().
mouseMoveEvent()
void Isis::VisualDisplay::mouseMoveEvent (QMouseEvent * event) protected
Called when the mouse moves over this widget.
Parameters
event
References Isis::IsSpecial(), Isis::PixelToString(), setDn(), setLine(), and setSample().
paintEvent()
void Isis::VisualDisplay::paintEvent (QPaintEvent * event) protected
Paint pixmap to the widget.
Parameters
event
paintPixmap()
void Isis::VisualDisplay::paintPixmap () protected
Paint the pixmap.
References Isis::Statistics::Average(), Isis::IsSpecial(), Isis::Stretch::Map(), Isis::Statistics::Maximum(), Isis::Statistics::Minimum(), Isis::PixelToString(), Isis::Statistics::StandardDeviation(), and Isis::Statistics::TotalPixels().
Referenced by setPixelData(), updateSize(), and VisualDisplay().
setBoxSize
void Isis::VisualDisplay::setBoxSize (int size) protected slot
Set box size in pixels.
Parameters
size
References updateSize().
setDn
void Isis::VisualDisplay::setDn (const QString st) signal
Signal to set the DN label to st.
Parameters
st
Referenced by leaveEvent(), and mouseMoveEvent().
setLine
void Isis::VisualDisplay::setLine (const QString st) signal
Signal to set the Line label to st.
Parameters
st
Referenced by leaveEvent(), and mouseMoveEvent().
setLines()
void Isis::VisualDisplay::setLines (int lines)
Set box line size.
Parameters
lines
References Isis::Statistics::Reset(), and updateSize().
setPixelData()
void Isis::VisualDisplay::setPixelData (QVector< QVector< double > > data, int samp, int line)
Set pixel data and upper left sample/line.
Parameters
data
samp
line
References Isis::Histogram::AddData(), Isis::Statistics::AddData(), Isis::Stretch::AddPair(), Isis::Statistics::BestMaximum(), Isis::Statistics::BestMinimum(), Isis::Stretch::ClearPairs(), paintPixmap(), Isis::Histogram::Percent(), and Isis::Statistics::Reset().
setSample
void Isis::VisualDisplay::setSample (const QString st) signal
Signal to set the Sample label to st.
Parameters
st
Referenced by leaveEvent(), and mouseMoveEvent().
setSamples()
void Isis::VisualDisplay::setSamples (int samps)
Set box sample size.
Parameters
samps
References Isis::Statistics::Reset(), and updateSize().
showDeviation
void Isis::VisualDisplay::showDeviation (bool b) protected slot
Show/Hide deviation.
Parameters
b
References updateSize().
showPixels
void Isis::VisualDisplay::showPixels (bool b) protected slot
Show/Hide pixels.
Parameters
b
References updateSize().
showText
void Isis::VisualDisplay::showText (bool b) protected slot
Show/Hide text.
Parameters
b
References updateSize().
sizeHint()
QSize Isis::VisualDisplay::sizeHint () const
Size hint for this widget.
Returns
QSize
Referenced by updateSize().
updateSize()
void Isis::VisualDisplay::updateSize ()
Update the size of the box.
References paintPixmap(), and sizeHint().
Referenced by setBoxSize(), setLines(), setSamples(), showDeviation(), showPixels(), and showText().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/StatisticsTool/StatisticsTool.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/StatisticsTool/StatisticsTool.cpp