Isis Developer Reference: Isis::AbstractTableModel Class Reference
Isis::AbstractTableModel Class Reference abstract
Translates the tree model into a table model.
#include <AbstractTableModel.h>
Public Types
enum Warning { None = 0 , SortingDisabled , SortingTableSizeLimitReached }
Public Slots
virtual void setGlobalSelection (bool selected)=0
virtual void applyFilter ()
virtual void sort ()
virtual void reverseOrder (TableColumn *)
virtual void updateSort ()
virtual void rebuildSort ()
Signals
void modelModified ()
void filterProgressChanged (int)
void rebuildProgressChanged (int)
void sortProgressChanged (int)
void filterProgressRangeChanged (int, int)
void rebuildProgressRangeChanged (int, int)
void sortProgressRangeChanged (int, int)
void filterCountsChanged (int visibleRows, int totalRows)
void treeSelectionChanged (QList< AbstractTreeItem * >)
void tableSelectionChanged (QList< AbstractTreeItem * >)
void userWarning (AbstractTableModel::Warning)
Public Member Functions
AbstractTableModel (AbstractTreeModel *, AbstractTableDelegate *)
virtual ~AbstractTableModel ()
virtual QList< AbstractTreeItem * > getItems (int, int)=0
virtual QList< AbstractTreeItem * > getItems (AbstractTreeItem *, AbstractTreeItem *)=0
virtual QList< AbstractTreeItem * > getSelectedItems ()=0
virtual int getVisibleRowCount () const =0
virtual QString getWarningMessage (AbstractTreeItem const *, TableColumn const *, QString valueToSave) const =0
virtual int indexOfVisibleItem (AbstractTreeItem const *item) const =0
virtual bool isSorting () const
virtual bool isFiltering () const
virtual bool sortingIsEnabled () const
virtual void setSortingEnabled (bool)
virtual int sortLimit () const
virtual void setSortLimit (int)
virtual bool sortingOn () const
virtual TableColumnList * getColumns ()
virtual const AbstractTableDelegate * getDelegate () const
Protected Member Functions
virtual TableColumnList * createColumns ()=0
AbstractTreeModel * getDataModel ()
const AbstractTreeModel * getDataModel () const
virtual QList< AbstractTreeItem * > getSortedItems (int, int, AbstractTreeModel::InterestingItems)
virtual QList< AbstractTreeItem * > getSortedItems (AbstractTreeItem *, AbstractTreeItem *, AbstractTreeModel::InterestingItems)
void handleTreeSelectionChanged (QList< AbstractTreeItem * > newlySelectedItems, AbstractTreeItem::InternalPointerType)
Detailed Description
Translates the tree model into a table model.
This class acts as a proxy model for the abstract tree model by allowing the user to access data in a table-like fashion (by sorted row).
Author
????-??-?? Eric Hyer
Member Enumeration Documentation
Warning
enum Isis::AbstractTableModel::Warning
Enumerator
None
SortingDisabled
SortingTableSizeLimitReached
Constructor & Destructor Documentation
AbstractTableModel()
Isis::AbstractTableModel::AbstractTableModel (AbstractTreeModel * model, AbstractTableDelegate * someDelegate)
References filterCountsChanged(), filterProgressChanged(), filterProgressRangeChanged(), modelModified(), rebuildProgressChanged(), rebuildProgressRangeChanged(), rebuildSort(), and tableSelectionChanged().
~AbstractTableModel()
Isis::AbstractTableModel::~AbstractTableModel () virtual
References Isis::TableColumnList::size().
Member Function Documentation
applyFilter
void Isis::AbstractTableModel::applyFilter () virtual slot
References Isis::AbstractTreeModel::applyFilter(), and getDataModel().
createColumns()
virtual TableColumnList* Isis::AbstractTableModel::createColumns () protected pure virtual
Implemented in Isis::PointTableModel, and Isis::MeasureTableModel.
Referenced by getColumns().
filterCountsChanged
void Isis::AbstractTableModel::filterCountsChanged (int visibleRows, int totalRows) signal
Referenced by AbstractTableModel(), Isis::MeasureTableModel::MeasureTableModel(), and Isis::PointTableModel::PointTableModel().
filterProgressChanged
void Isis::AbstractTableModel::filterProgressChanged (int) signal
Referenced by AbstractTableModel().
filterProgressRangeChanged
void Isis::AbstractTableModel::filterProgressRangeChanged (int , int) signal
Referenced by AbstractTableModel().
getColumns()
TableColumnList * Isis::AbstractTableModel::getColumns () virtual
References createColumns(), and sort().
Referenced by Isis::PointTableModel::resetColumnHeaders(), Isis::TableViewHeader::setModel(), Isis::TableView::TableView(), and Isis::TableViewContent::TableViewContent().
getDataModel() [1/2]
AbstractTreeModel * Isis::AbstractTableModel::getDataModel () protected
Referenced by applyFilter(), Isis::MeasureTableModel::getSelectedItems(), Isis::PointTableModel::getSelectedItems(), getSortedItems(), Isis::MeasureTableModel::getVisibleRowCount(), Isis::PointTableModel::getVisibleRowCount(), Isis::MeasureTableModel::indexOfVisibleItem(), Isis::PointTableModel::indexOfVisibleItem(), Isis::MeasureTableModel::setGlobalSelection(), and Isis::PointTableModel::setGlobalSelection().
getDataModel() [2/2]
const AbstractTreeModel * Isis::AbstractTableModel::getDataModel () const protected
getDelegate()
const AbstractTableDelegate * Isis::AbstractTableModel::getDelegate () const virtual
Referenced by Isis::TableViewContent::keyPressEvent(), and Isis::TableViewContent::mouseDoubleClickEvent().
getItems() [1/2]
virtual QList< AbstractTreeItem * > Isis::AbstractTableModel::getItems (AbstractTreeItem * , AbstractTreeItem *) pure virtual
Implemented in Isis::PointTableModel, and Isis::MeasureTableModel.
getItems() [2/2]
virtual QList< AbstractTreeItem * > Isis::AbstractTableModel::getItems (int , int) pure virtual
Implemented in Isis::PointTableModel, and Isis::MeasureTableModel.
Referenced by Isis::TableViewContent::keyPressEvent(), and rebuildSort().
getSelectedItems()
virtual QList< AbstractTreeItem * > Isis::AbstractTableModel::getSelectedItems () pure virtual
Implemented in Isis::PointTableModel, and Isis::MeasureTableModel.
Referenced by Isis::TableViewContent::mousePressEvent(), and Isis::TableViewContent::refresh().
getSortedItems() [1/2]
QList< AbstractTreeItem * > Isis::AbstractTableModel::getSortedItems (AbstractTreeItem * item1, AbstractTreeItem * item2, AbstractTreeModel::InterestingItems flags) protected virtual
References _FILEINFO_, getDataModel(), Isis::AbstractTreeModel::getItems(), Isis::IException::Programmer, and sortingOn().
getSortedItems() [2/2]
QList< AbstractTreeItem * > Isis::AbstractTableModel::getSortedItems (int start, int end, AbstractTreeModel::InterestingItems flags) protected virtual
References getDataModel(), Isis::AbstractTreeModel::getItems(), isFiltering(), and sortingOn().
Referenced by Isis::MeasureTableModel::getItems(), and Isis::PointTableModel::getItems().
getVisibleRowCount()
virtual int Isis::AbstractTableModel::getVisibleRowCount () const pure virtual
Implemented in Isis::PointTableModel, and Isis::MeasureTableModel.
Referenced by Isis::TableView::displayWarning(), Isis::TableViewContent::keyPressEvent(), Isis::CnetEditorSortConfigDialog::readSettings(), Isis::TableViewContent::refresh(), and sortingOn().
getWarningMessage()
virtual QString Isis::AbstractTableModel::getWarningMessage (AbstractTreeItem const * , TableColumn const * , QString valueToSave) const pure virtual
Implemented in Isis::PointTableModel, and Isis::MeasureTableModel.
handleTreeSelectionChanged()
void Isis::AbstractTableModel::handleTreeSelectionChanged (QList< AbstractTreeItem * > newlySelectedItems, AbstractTreeItem::InternalPointerType pointerType) protected
References Isis::AbstractTreeItem::getPointerType(), and treeSelectionChanged().
Referenced by Isis::MeasureTableModel::handleTreeSelectionChanged(), and Isis::PointTableModel::handleTreeSelectionChanged().
indexOfVisibleItem()
virtual int Isis::AbstractTableModel::indexOfVisibleItem (AbstractTreeItem const * item) const pure virtual
Implemented in Isis::PointTableModel, and Isis::MeasureTableModel.
Referenced by Isis::TableViewContent::keyPressEvent(), and Isis::TableViewContent::scrollTo().
isFiltering()
bool Isis::AbstractTableModel::isFiltering () const virtual
References Isis::AbstractTreeModel::isFiltering().
Referenced by getSortedItems(), and Isis::TableViewContent::refresh().
isSorting()
bool Isis::AbstractTableModel::isSorting () const virtual
Referenced by sort().
modelModified
void Isis::AbstractTableModel::modelModified () signal
Referenced by AbstractTableModel(), rebuildSort(), and sort().
rebuildProgressChanged
void Isis::AbstractTableModel::rebuildProgressChanged (int) signal
Referenced by AbstractTableModel().
rebuildProgressRangeChanged
void Isis::AbstractTableModel::rebuildProgressRangeChanged (int , int) signal
Referenced by AbstractTableModel().
rebuildSort
void Isis::AbstractTableModel::rebuildSort () virtual slot
References getItems(), modelModified(), None, sort(), SortingDisabled, sortingOn(), SortingTableSizeLimitReached, and userWarning().
Referenced by AbstractTableModel(), setSortingEnabled(), and setSortLimit().
reverseOrder
void Isis::AbstractTableModel::reverseOrder (TableColumn * column) virtual slot
setGlobalSelection
virtual void Isis::AbstractTableModel::setGlobalSelection (bool selected) pure virtual slot
Implemented in Isis::PointTableModel, and Isis::MeasureTableModel.
Referenced by Isis::TableViewContent::keyPressEvent(), and Isis::TableViewContent::mousePressEvent().
setSortingEnabled()
void Isis::AbstractTableModel::setSortingEnabled (bool enabled) virtual
References rebuildSort().
Referenced by Isis::CnetEditorWidget::setMeasureTableSortingEnabled(), and Isis::CnetEditorWidget::setPointTableSortingEnabled().
setSortLimit()
void Isis::AbstractTableModel::setSortLimit (int limit) virtual
References rebuildSort().
Referenced by Isis::CnetEditorWidget::setMeasureTableSortLimit(), and Isis::CnetEditorWidget::setPointTableSortLimit().
sort
void Isis::AbstractTableModel::sort () virtual slot
References Isis::TableColumnList::getSortingOrder(), Isis::AbstractTreeModel::isFiltering(), Isis::AbstractTreeModel::isRebuilding(), isSorting(), modelModified(), and sortingOn().
Referenced by getColumns(), and rebuildSort().
sortingIsEnabled()
bool Isis::AbstractTableModel::sortingIsEnabled () const virtual
Referenced by Isis::CnetEditorWidget::measureTableSortingEnabled(), Isis::CnetEditorWidget::pointTableSortingEnabled(), and sortingOn().
sortingOn()
bool Isis::AbstractTableModel::sortingOn () const virtual
References getVisibleRowCount(), sortingIsEnabled(), and sortLimit().
Referenced by getSortedItems(), Isis::TableViewHeader::mouseReleaseEvent(), rebuildSort(), and sort().
sortLimit()
int Isis::AbstractTableModel::sortLimit () const virtual
Referenced by Isis::TableView::displayWarning(), Isis::CnetEditorWidget::measureTableSortLimit(), Isis::CnetEditorWidget::pointTableSortLimit(), Isis::CnetEditorSortConfigDialog::readSettings(), and sortingOn().
sortProgressChanged
void Isis::AbstractTableModel::sortProgressChanged (int) signal
sortProgressRangeChanged
void Isis::AbstractTableModel::sortProgressRangeChanged (int , int) signal
tableSelectionChanged
void Isis::AbstractTableModel::tableSelectionChanged (QList< AbstractTreeItem * >) signal
Referenced by AbstractTableModel().
treeSelectionChanged
void Isis::AbstractTableModel::treeSelectionChanged (QList< AbstractTreeItem * >) signal
Referenced by handleTreeSelectionChanged(), Isis::MeasureTableModel::MeasureTableModel(), and Isis::PointTableModel::PointTableModel().
updateSort
void Isis::AbstractTableModel::updateSort () virtual slot
userWarning
void Isis::AbstractTableModel::userWarning (AbstractTableModel::Warning) signal
Referenced by rebuildSort().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/AbstractTableModel.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/AbstractTableModel.cpp