Isis Developer Reference: Isis::ProcessBySample Class Reference
Isis::ProcessBySample Class Reference
High Level Cube I/O
Process cubes by sample.
#include <ProcessBySample.h>
Public Types
enum IOCubes { InPlace , InputOutput , InputOutputList }
enum ProcessingDirection { LinesFirst , BandsFirst }
Public Member Functions
ProcessBySample ()
Isis::Cube * SetInputCube (const QString &parameter, int requirements=0)
Opens an input cube specified by the user and verifies requirements are met.
Isis::Cube * SetInputCube (const QString &file, Isis::CubeAttributeInput &att, int requirements=0)
Opens an input cube specified by the user with cube attributes and requirements.
void StartProcess (void funct(Isis::Buffer &inout))
This method invokes the process by sample operation over a single input or output cube.
void StartProcess (void funct(Isis::Buffer &in, Isis::Buffer &out))
This method invokes the process by sample operation over exactly one input and one output cube.
void StartProcess (void funct(std::vector< Isis::Buffer * > &in, std::vector< Isis::Buffer * > &out))
This method invokes the process by sample operation over multiple input and output cubes.
template<typename Functor >
void ProcessCubeInPlace (const Functor &funct, bool threaded=true)
template<typename Functor >
void ProcessCube (const Functor &funct, bool threaded=true)
template<typename Functor >
void ProcessCubes (const Functor &funct, bool threaded=true)
Cube * SetInputCube (const QString &fname, const CubeAttributeInput &att, int requirements=0)
Opens an input cube specified by the user, sets the attributes, and verifies requirements are met.
virtual Isis::Cube * SetInputCube (const QString &parameter, const int requirements=0)
Opens an input cube specified by the user and verifies requirements are met.
virtual void SetInputCube (Isis::Cube *inCube, int requirements=0)
Set the InputCube vector to an opened Cube which was dynamically allocated.
void VerifyCubes (IOCubes cn)
Verifies the dimensions of the input/output cubes.
void SetBrickSize (int ns, int nl, int nb)
Sets the input and output bricks sizes to the given number of samples, lines, and bands.
void SetInputBrickSize (int ns, int nl, int nb)
Sets the size of all input bricks.
void SetInputBrickSize (int ns, int nl, int nb, int cube)
Sets the brick size of the specified cube.
void SetOutputBrickSize (int ns, int nl, int nb)
Sets the size of all output bricks.
void SetOutputBrickSize (int ns, int nl, int nb, int cube)
Sets the brick size of the specified output cube.
virtual Cube * SetOutputCube (const QString &fname, const CubeAttributeOutput &att)
Create the output file.
virtual Isis::Cube * SetOutputCube (const QString &parameter)
Allocates a user-specified output cube whose size matches the first input cube.
virtual Isis::Cube * SetOutputCube (const QString &parameter, const int nsamps, const int nlines, const int nbands=1)
Allocates a user specified output cube whose size is specified by the programmer.
virtual Isis::Cube * SetOutputCube (const QString &fname, const Isis::CubeAttributeOutput &att, const int nsamps, const int nlines, const int nbands=1)
Allocates a output cube whose name and size is specified by the programmer.
void SetProcessingDirection (ProcessingDirection direction)
Set the direction the data will be read, either all lines in a single band proceeding to the next band (LinesFirst), or every band for every line proceeding to the next line (BandsFirst).
ProcessingDirection GetProcessingDirection ()
Returns the direction the data will be read, either all lines in a single band proceeding to the next band (LinesFirst), or every band for every line proceeding to the next line (BandsFirst).
void SetOutputRequirements (int outputRequirements)
void SetWrap (bool wrap)
This wrapping option only applys when there are two or more input cubes.
bool Wraps ()
Returns true if the wrapping option is enabled.
virtual void StartProcess (void funct(Buffer &in))
Starts the systematic processing of the input cube by moving an arbitrarily-shaped brick through the cube.
virtual void StartProcess (std::function< void(Buffer &in)> funct)
Starts the systematic processing of the input cube by moving an arbitrarily-shaped brick through the cube.
virtual void StartProcess (void funct(Buffer &in, Buffer &out))
Starts the systematic processing of the input cube by moving an arbitrarily-shaped brick through the cube.
virtual void StartProcess (std::function< void(Buffer &in, Buffer &out)> funct)
Starts the systematic processing of the input cube by moving an arbitrarily-shaped brick through the cube.
virtual void StartProcess (void funct(std::vector< Buffer * > &in, std::vector< Buffer * > &out))
Starts the systematic processing of the input cube by moving an arbitrarily-shaped brick through the cube.
virtual void StartProcess (std::function< void(std::vector< Buffer * > &in, std::vector< Buffer * > &out)> funct)
Starts the systematic processing of the input cube by moving an arbitrarily-shaped brick through the cube.
virtual void StartProcess (void funct())
In the base class, this method will invoked a user-specified function exactly one time.
void EndProcess ()
End the processing sequence and cleans up by closing cubes, freeing memory, etc.
void Finalize ()
Cleans up by closing cubes and freeing memory.
virtual Isis::Cube * SetOutputCubeStretch (const QString &parameter, UserInterface *ui=nullptr)
Allocates a user-specified output cube whose size matches the first input cube.
virtual Isis::Cube * SetOutputCubeStretch (const QString &parameter, const int nsamps, const int nlines, const int nbands=1, UserInterface *ui=nullptr)
Allocates a user specified output cube whose size is specified by the programmer.
void AddInputCube (Cube *cube, bool owned=true)
void AddOutputCube (Cube *cube, bool owned=true)
void CheckRequirements (const Cube *cube, const int requirements)
Checks to make sure the input cube meets the inputted requirements.
void ClearCubes ()
Close owned cubes from the list and clear the list.
void ClearInputCubes ()
Close owned input cubes from the list and clear the list.
void ClearOutputCubes ()
Close owned output cubes from the list and clear the list.
void PropagateLabels (const bool prop)
This method allows the programmer to turn on/off the propagation of labels from the 1st input cube to any of the output cubes.
void PropagateLabels (const QString &cube)
This method allows the programmer to propagate labels from a specific secondary cube.
void PropagateTables (const bool prop)
This method allows the programmer to propagate input tables to the output cube (default is true)
void PropagateTables (const QString &fromName, const QList< QString > &tableNames=QList< QString >())
Propagate the tables from the cube with the given filename to the output cube.
void PropagatePolygons (const bool prop)
This method allows the programmer to propagate input blobs to the output cube (default is true)
void PropagateHistory (const bool prop)
This method allows the programmer to propagate history to the output cube (default is true)
void PropagateOriginalLabel (const bool prop)
This method allows the programmer to propagate original labels to the output cube (default is true)
Isis::Progress * Progress ()
This method returns a pointer to a Progress object.
QString MissionData (const QString &mission, const QString &file, bool highestVersion=false)
This method reads the mission specific data directory from the user preference file, makes sure that mission is available in the Isis installation, and the attaches the provided input file to the directory in order to create a full file specification.
void WriteHistory (Cube &cube)
Writes out the History blob to the cube.
void CalculateStatistics ()
Calculates and stores off statistics on every band of every cube added to this process via the SetInputCube method.
std::vector< Isis::Statistics * > BandStatistics (const unsigned index)
Get the vector of Statistics objects for each band separately of a specified input cube.
Isis::Statistics * CubeStatistics (const unsigned index)
Get the Statistics object for all bands of a specified input cube.
Protected Attributes
Isis::Progress * p_progress
Pointer to a Progress object.
bool p_propagateLabels
Flag indicating if labels are be propagated to output cubes.
bool p_propagateTables
Flag indicating if tables are be propagated to output cubes.
bool p_propagatePolygons
Flag indicating if blobs are be propagated to output cubes.
bool p_propagateHistory
Flag indicating if history is to be propagated to output cubes.
bool p_propagateOriginalLabel
Flag indicating if original lable is to be propagated to output cubes.
std::vector< std::vector< Isis::Statistics * > > p_bandStats
Holds the calculated statistics for each band separately of every input cubei after the CalculateStatistics method is called.
std::vector< Isis::Statistics * > p_cubeStats
Holds the calculated statistics for every band together of every input cubei after the CalculateStatistics method is called.
std::vector< Isis::Cube * > InputCubes
A vector of pointers to opened Cube objects.
std::vector< Isis::Cube * > OutputCubes
A vector of pointers to allocated Cube objects.
QSet< Isis::Cube * > * m_ownedCubes
A list of cubes owned by this instant.
Detailed Description
Process cubes by sample.
This class allows a programmer to develop a program which process input and output cubes sequentially by sample. That is, receive the input data for sample one, manipulate the data, and pass back the data for output sample one. Then proceed to the sample two and so one. This class is derived from the Process class which give many functions for setting up input and output cubes.
Author
2006-03-27 Jacob Danton
Member Enumeration Documentation
IOCubes
enum Isis::ProcessByBrick::IOCubes inherited
Enumerator
InPlace
InputOutput
InputOutputList
ProcessingDirection
enum Isis::ProcessByBrick::ProcessingDirection inherited
Enumerator
LinesFirst
BandsFirst
Constructor & Destructor Documentation
ProcessBySample()
Isis::ProcessBySample::ProcessBySample () inline
References Isis::ProcessByBrick::SetWrap().
Member Function Documentation
AddInputCube()
void Isis::Process::AddInputCube (Cube * cube, bool owned = true) inherited
AddOutputCube()
void Isis::Process::AddOutputCube (Cube * cube, bool owned = true) inherited
BandStatistics()
std::vector<Isis::Statistics *> Isis::Process::BandStatistics (const unsigned index) inline inherited
Get the vector of Statistics objects for each band separately of a specified input cube.
Parameters
index The index of the input cube in InputCubes
Returns
vector<Statistics*> A list of statistics ordered by band
References Isis::Process::p_bandStats.
CalculateStatistics()
void Isis::Process::CalculateStatistics () inherited
Calculates and stores off statistics on every band of every cube added to this process via the SetInputCube method.
The newly calculated statistics are stored in two ways: as a vector where each entry is a single Statistics object for every band of a particular input cube, and as a vector where each entry is a vector of Statistics objects, for each band separately, of a particular input cube.
References Isis::Statistics::AddData(), Isis::Cube::bandCount(), Isis::Progress::CheckStatus(), Isis::Buffer::DoubleBuffer(), Isis::Cube::lineCount(), Isis::Cube::read(), Isis::LineManager::SetLine(), Isis::Progress::SetMaximumSteps(), Isis::Progress::SetText(), Isis::Buffer::size(), and Isis::toString().
CheckRequirements()
void Isis::Process::CheckRequirements (const Cube * cube, const int requirements) inherited
Checks to make sure the input cube meets the inputted requirements.
Parameters
cube Cube to check
requirements Use to specify requirements for the input file. The following requirments are checked against 1) ic_base::SizeMatch checks to make sure the input cube has the same bands, samples, and lines as the first input cube open using this method, 2) ic_base::SpatialMatch checks to make sure the input cube has the same samples and lines as the first input cube, 3) ic_base::Georeferenced checks to make sure latitude/longitudes can be obtained from the input cube, 4) ic_base::FullyGeoreferenced checks to make sure latitude/longitude, phase/incidence/emission, and other geometric parameters can be obtained from the input cube, 5) ic_base::OneBand checks to make sure the input cube has exactly one band. Note, that these requirements can be logically or'ed. For example, ic_base::SpatialMatch | ic_base::georeferenced. Defaults to 0
Exceptions
Isis::iException::Message
References _FILEINFO_, Isis::AllMatchOrOne, Isis::Cube::bandCount(), Isis::BandMatchOrOne, Isis::Cube::fileName(), Isis::Cube::lineCount(), Isis::OneBand, Isis::Cube::sampleCount(), Isis::SizeMatch, and Isis::SpatialMatch.
ClearCubes()
void Isis::Process::ClearCubes () inherited
Close owned cubes from the list and clear the list.
ClearInputCubes()
void Isis::Process::ClearInputCubes () inherited
Close owned input cubes from the list and clear the list.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
ClearOutputCubes()
void Isis::Process::ClearOutputCubes () inherited
Close owned output cubes from the list and clear the list.
CubeStatistics()
Isis::Statistics* Isis::Process::CubeStatistics (const unsigned index) inline inherited
Get the Statistics object for all bands of a specified input cube.
Parameters
index The index of the input cube in InputCubes
Returns
Statistics* Collections of statistics gathered on all bands
References Isis::Process::p_cubeStats.
EndProcess()
void Isis::ProcessByBrick::EndProcess () virtual inherited
End the processing sequence and cleans up by closing cubes, freeing memory, etc.
Deprecated:
Please use Finalize()
Reimplemented from Isis::Process.
Reimplemented in Isis::ProcessByTile.
Referenced by Isis::Equalization::applyCorrection(), Isis::Equalization::calculateBandStatistics(), Isis::ImageImporter::import(), Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
Finalize()
void Isis::ProcessByBrick::Finalize () virtual inherited
Cleans up by closing cubes and freeing memory.
Reimplemented from Isis::Process.
Reimplemented in Isis::ProcessByTile.
Referenced by Isis::SpectralDefinition2D::SpectralDefinition2D().
GetProcessingDirection()
ProcessByBrick::ProcessingDirection Isis::ProcessByBrick::GetProcessingDirection () inherited
Returns the direction the data will be read, either all lines in a single band proceeding to the next band (LinesFirst), or every band for every line proceeding to the next line (BandsFirst).
The default is to process all lines of a band first.
Returns
The selected enumerated processing direction
MissionData()
QString Isis::Process::MissionData (const QString & mission, const QString & file, bool highestVersion = false) inherited
This method reads the mission specific data directory from the user preference file, makes sure that mission is available in the Isis installation, and the attaches the provided input file to the directory in order to create a full file specification.
Parameters
mission Name of the mission data directory
file Name of the file to attach to the end of the directory
highestVersion If set to true the method will return the highest version number of the given file. Therefore, file must contain question marks such as "file???.dat". See the FileName class for more information on versioned files. Defaults to false.
References _FILEINFO_, Isis::FileName::expanded(), Isis::FileName::fileExists(), Isis::PvlObject::findGroup(), Isis::FileName::highestVersion(), Isis::FileName::original(), and Isis::Preference::Preferences().
ProcessCube()
template<typename Functor > void Isis::ProcessBySample::ProcessCube (const Functor & funct, bool threaded = true) inline
See also
ProcessByBrick::ProcessCube()
Parameters
funct The processing function or functor which does your desired calculations.
threaded True if multi-threading is supported, false otherwise.
References Isis::ProcessByBrick::InputOutput, Isis::ProcessByBrick::ProcessCube(), and Isis::ProcessByBrick::VerifyCubes().
ProcessCubeInPlace()
template<typename Functor > void Isis::ProcessBySample::ProcessCubeInPlace (const Functor & funct, bool threaded = true) inline
See also
ProcessByBrick::ProcessCubeInPlace()
Parameters
funct The processing function or functor which does your desired calculations.
threaded True if multi-threading is supported, false otherwise.
References Isis::ProcessByBrick::InPlace, Isis::ProcessByBrick::ProcessCubeInPlace(), and Isis::ProcessByBrick::VerifyCubes().
Referenced by Isis::SpectralDefinition2D::SpectralDefinition2D().
ProcessCubes()
template<typename Functor > void Isis::ProcessBySample::ProcessCubes (const Functor & funct, bool threaded = true) inline
See also
ProcessByBrick::ProcessCubes()
Parameters
funct The processing function or functor which does your desired calculations.
threaded True if multi-threading is supported, false otherwise.
References Isis::ProcessByBrick::InputOutputList, Isis::ProcessByBrick::ProcessCubes(), and Isis::ProcessByBrick::VerifyCubes().
Progress()
Isis::Progress* Isis::Process::Progress () inline inherited
This method returns a pointer to a Progress object.
Returns
Progress*
References Isis::Process::p_progress.
Referenced by Isis::Equalization::applyCorrection(), Isis::Equalization::calculateBandStatistics(), Isis::HiEqualization::calculateStatistics(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::SpectralDefinition2D::SpectralDefinition2D().
PropagateHistory()
void Isis::Process::PropagateHistory (const bool prop) inherited
This method allows the programmer to propagate history to the output cube (default is true)
Parameters
prop Flag indicating if history is to be propagated to output cubes.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
PropagateLabels() [1/2]
void Isis::Process::PropagateLabels (const bool prop) inherited
This method allows the programmer to turn on/off the propagation of labels from the 1st input cube to any of the output cubes.
By default, propagation occurs automatically in the Process class when a call to either of the SetOutputCube methods is invoked. If the program * requires no propagation then utilize this method. This method can be invoked between successive calls of SetOutputCube so that some cube will have labels propagated while others will not.
Parameters
prop Flag indicating if labels are be propagated to output cubes.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
PropagateLabels() [2/2]
void Isis::Process::PropagateLabels (const QString & cube) inherited
This method allows the programmer to propagate labels from a specific secondary cube.
Parameters
cube IString containing the name of the cube containing the labels to propagate.
References Isis::PvlObject::addGroup(), Isis::PvlObject::addObject(), Isis::PvlObject::findObject(), Isis::PvlObject::group(), Isis::PvlObject::groups(), and Isis::PvlObject::hasObject().
PropagateOriginalLabel()
void Isis::Process::PropagateOriginalLabel (const bool prop) inherited
This method allows the programmer to propagate original labels to the output cube (default is true)
Parameters
prop Flag indicating if original labels is to be propagated to output cubes.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
PropagatePolygons()
void Isis::Process::PropagatePolygons (const bool prop) inherited
This method allows the programmer to propagate input blobs to the output cube (default is true)
Parameters
prop Flag indicating if input blobs are to be propagated to output cubes.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
PropagateTables() [1/2]
void Isis::Process::PropagateTables (const bool prop) inherited
This method allows the programmer to propagate input tables to the output cube (default is true)
Parameters
prop Flag indicating if input tables are to be propagated to output cubes.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
PropagateTables() [2/2]
void Isis::Process::PropagateTables (const QString & fromName, const QList< QString > & tableNames = QList<QString>()) inherited
Propagate the tables from the cube with the given filename to the output cube.
This is done at the time this method is called, not during normal processing. The names of the tables to propagate can be provided through the second paramter, by specifing a list of table names. Not providing any list (or providing an empty list) will propagate all tables.
Parameters
fromName QString of the name of the cube containing the tables to propagate.
tableNames List of QStrings of the names of the tables to propagate; default is empty, which indicates that all tables will be propagated.
References Isis::Cube::close(), Isis::Cube::label(), Isis::PvlObject::object(), Isis::PvlObject::objects(), Isis::Cube::open(), and Isis::Cube::read().
SetBrickSize()
void Isis::ProcessByBrick::SetBrickSize (int ns, int nl, int nb) inherited
Sets the input and output bricks sizes to the given number of samples, lines, and bands.
Parameters
ns Number of samples
nl Number of lines
nb Number of bands
SetInputBrickSize() [1/2]
void Isis::ProcessByBrick::SetInputBrickSize (int ns, int nl, int nb) inherited
Sets the size of all input bricks.
Parameters
ns Number of samples
nl Number of lines
nb Number of bands
SetInputBrickSize() [2/2]
void Isis::ProcessByBrick::SetInputBrickSize (int ns, int nl, int nb, int cube) inherited
Sets the brick size of the specified cube.
Parameters
ns Number of samples
nl Number of lines
nb Number of bands
cube The index of the cube
References _FILEINFO_.
SetInputCube() [1/5]
Isis::Cube * Isis::ProcessBySample::SetInputCube (const QString & file, Isis::CubeAttributeInput & att, int requirements = 0)
Opens an input cube specified by the user with cube attributes and requirements.
For more information see Process::SetInputCube
Returns
Cube*
Parameters
file Name of cube file
att Cube attributes
requirements See Process::SetInputCube for more information. Defaults to 0
References Isis::BandMatchOrOne, and Isis::SpatialMatch.
SetInputCube() [2/5]
Cube * Isis::ProcessByBrick::SetInputCube (const QString & file, const CubeAttributeInput & att, int requirements = 0) virtual inherited
Opens an input cube specified by the user, sets the attributes, and verifies requirements are met.
This method is overloaded and adds the requirements of ISIS::SpatialMatch which requires all input cubes to have the same dimensions or be exactly be exactly one. For more information see Process::SetInputCube
Returns
Cube*
Parameters
file User parameter to obtain file to open. Typically, the value is "FROM". For example, the user can specify on the command line FROM=myfile.cub and this method will attempt to open the cube "myfile.cub" if the parameter was set to "FROM".
att See Process::SetInputCube for more information.
requirements See Process::SetInputCube for more information. Defaults to 0
Exceptions
iException::Message
Reimplemented from Isis::Process.
References Isis::AllMatchOrOne.
SetInputCube() [3/5]
Isis::Cube * Isis::Process::SetInputCube inherited
Opens an input cube specified by the user and verifies requirements are met.
Returns
Cube*
Parameters
parameter User parameter to obtain file to open. Typically, the value is "FROM". For example, the user can specify on the command line FROM=myfile.cub and this method will attempt to open the cube "myfile.cub" if the parameter was set to "FROM".
requirements Requirements to check that the input cube meets. See CheckRequirements().
Exceptions
Isis::iException::Message
SetInputCube() [4/5]
Isis::Cube * Isis::ProcessBySample::SetInputCube (const QString & parameter, int requirements = 0) virtual
Opens an input cube specified by the user and verifies requirements are met.
This method is overloaded and adds the requirements of ic_base::SpatialMatch which requires all input cubes to have the same number of samples and lines. It also added the requirement ic_base::BandMatchOrOne which forces 2nd, 3rd, 4th, etc input cubes to match the number of bands in the 1st input cube or to have exactly one band. For more information see Process::SetInputCube
Returns
Cube*
Parameters
parameter User parameter to obtain file to open. Typically, the value is "FROM". For example, the user can specify on the command line FROM=myfile.cub and this method will attempt to open the cube "myfile.cub" if the parameter was set to "FROM".
requirements See Process::SetInputCube for more information. Defaults to 0
Reimplemented from Isis::ProcessByBrick.
References Isis::BandMatchOrOne, and Isis::SpatialMatch.
Referenced by Isis::SpectralDefinition2D::SpectralDefinition2D().
SetInputCube() [5/5]
void Isis::Process::SetInputCube (Isis::Cube * inCube, int requirements = 0) virtual inherited
Set the InputCube vector to an opened Cube which was dynamically allocated.
This is used if there already exists a valid opened cube
Author
Sharmila Prasad (5/7/2011)
Parameters
inCube - Pointer to input Cube
requirements Requirements to check that the input cube meets. See CheckRequirements().
References _FILEINFO_, and Isis::Cube::isOpen().
SetOutputBrickSize() [1/2]
void Isis::ProcessByBrick::SetOutputBrickSize (int ns, int nl, int nb) inherited
Sets the size of all output bricks.
Parameters
ns Number of samples
nl Number of lines
nb Number of bands
SetOutputBrickSize() [2/2]
void Isis::ProcessByBrick::SetOutputBrickSize (int ns, int nl, int nb, int cube) inherited
Sets the brick size of the specified output cube.
Parameters
ns Number of samples
nl Number of lines
nb Number of bands
cube The index of the cube
References _FILEINFO_.
SetOutputCube() [1/4]
Isis::Cube * Isis::ProcessByBrick::SetOutputCube (const QString & fname, const CubeAttributeOutput & att) virtual inherited
Create the output file.
This method assumes that the output cube size matches the input cube size. Therefore, SetInputCube() must be called before this method.
Parameters
parameter The output file name.
att An output cube attribute to define the characteristics of the output cube.
Returns
Isis::Cube Output cube.
Exceptions
Isis::iException::Message "File is not in a supported organization."
References Isis::Cube::lineCount().
Referenced by Isis::Equalization::applyCorrection(), Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
SetOutputCube() [2/4]
Isis::Cube * Isis::Process::SetOutputCube (const QString & fname, const Isis::CubeAttributeOutput & att, const int ns, const int nl, const int nb = 1) virtual inherited
Allocates a output cube whose name and size is specified by the programmer.
Returns
Cube*
Parameters
fname Name of the output cube to allocate
att The cube attributes to use when creating the output cube.
ns Number of samples to allocate
nl Number of lines to allocate
nb Number of bands to allocate
Exceptions
Isis::iException::Message
References _FILEINFO_, Isis::PvlObject::addGroup(), Isis::PvlObject::addObject(), Isis::AttachedLabel, Isis::CubeAttributeOutput::byteOrder(), Isis::Cube::create(), Isis::CubeAttributeOutput::fileFormat(), Isis::PvlObject::findObject(), Isis::PvlObject::group(), Isis::PvlObject::groups(), Isis::PvlContainer::isNamed(), Isis::Cube::label(), Isis::CubeAttributeOutput::labelAttachment(), Isis::Cube::labelSize(), Isis::CubeAttributeOutput::maximum(), Isis::CubeAttributeOutput::minimum(), Isis::PvlContainer::name(), Isis::PvlObject::object(), Isis::PvlObject::objects(), Isis::Cube::pixelType(), Isis::CubeAttributeOutput::pixelType(), Isis::CubeAttributeOutput::propagateMinimumMaximum(), Isis::CubeAttributeOutput::propagatePixelType(), Isis::Real, Isis::Cube::setBaseMultiplier(), Isis::Cube::setByteOrder(), Isis::Cube::setDimensions(), Isis::Cube::setFormat(), Isis::Cube::setLabelsAttached(), Isis::Cube::setLabelSize(), Isis::Cube::setMinMax(), Isis::Cube::setPixelType(), Isis::SignedInteger, Isis::SignedWord, Isis::UnsignedByte, Isis::UnsignedInteger, Isis::UnsignedWord, and Isis::Cube::write().
SetOutputCube() [3/4]
Isis::Cube * Isis::Process::SetOutputCube (const QString & parameter) virtual inherited
Allocates a user-specified output cube whose size matches the first input cube.
Returns
Cube*
Parameters
parameter User specified output file. For example, "TO" is a popular user parameter. If the user specified TO=output.cub, then this routine would allocate the file output.cub with size specified by the first opened input cube. The output pixel type will be propagated from the first loaded input cube or will use the value in the application XML file for pixelType.
Exceptions
Isis::iException::Message
Reimplemented in Isis::ProcessMosaic, Isis::ProcessImport, and Isis::ProcessMapMosaic.
References _FILEINFO_.
Referenced by Isis::ProcessImport::SetOutputCube().
SetOutputCube() [4/4]
Isis::Cube * Isis::Process::SetOutputCube (const QString & parameter, const int ns, const int nl, const int nb = 1) virtual inherited
Allocates a user specified output cube whose size is specified by the programmer.
Returns
Cube*
Parameters
parameter User specified output file. For example, "TO" is a popular user parameter. If the user specified TO=output.cub, then this routine would allocate the file output.cub with size specified by the first opened input cube. The output pixel type will be propagated from the first loaded input cube or will use the value in the application XML file for pixelType.
ns Number of samples to allocate
nl Number of lines to allocate
nb Number of bands to allocate
Exceptions
Isis::iException::Message
References _FILEINFO_.
SetOutputCubeStretch() [1/2]
Isis::Cube * Isis::Process::SetOutputCubeStretch (const QString & parameter, const int ns, const int nl, const int nb = 1, UserInterface * ui = nullptr) virtual inherited
Allocates a user specified output cube whose size is specified by the programmer.
Returns
Cube*
Parameters
parameter User specified output file. For example, "TO" is a popular user parameter. If the user specified TO=output.cub, then this routine would allocate the file output.cub with size specified by the first opened input cube. The output pixel type will be propagated from the first loaded input cube or will use the value in the application XML file for pixelType.
ns Number of samples to allocate
nl Number of lines to allocate
nb Number of bands to allocate
ui A user interface used to get the attributes needed. If null, the user interface will be obtained from the application.
Exceptions
Isis::iException::Message
References _FILEINFO_, IsisAml::GetCubeName(), and IsisAml::GetOutputAttribute().
SetOutputCubeStretch() [2/2]
Isis::Cube * Isis::Process::SetOutputCubeStretch (const QString & parameter, UserInterface * ui = nullptr) virtual inherited
Allocates a user-specified output cube whose size matches the first input cube.
Returns
Cube*
Parameters
parameter User specified output file. For example, "TO" is a popular user parameter. If the user specified TO=output.cub, then this routine would allocate the file output.cub with size specified by the first opened input cube. The output pixel type will be propagated from the first loaded input cube or will use the value in the application XML file for pixelType.
ui A user interface used to get the attributes needed for SetOutputCube.
Exceptions
Isis::iException::Message
References _FILEINFO_.
SetOutputRequirements()
void Isis::ProcessByBrick::SetOutputRequirements (int outputRequirements) inherited
SetProcessingDirection()
void Isis::ProcessByBrick::SetProcessingDirection (ProcessingDirection direction) inherited
Set the direction the data will be read, either all lines in a single band proceeding to the next band (LinesFirst), or every band for every line proceeding to the next line (BandsFirst).
The default is to process all lines of a band first.
Parameters
direction The new enumerated processing direction
Referenced by Isis::ImageImporter::import(), and Isis::SpectralDefinition2D::SpectralDefinition2D().
SetWrap()
void Isis::ProcessByBrick::SetWrap (bool wrap) inherited
This wrapping option only applys when there are two or more input cubes.
If wrapping is enabled and the second cube is smaller than the first The brick will be wrapped back to the beginning of the second cube once brick movement reaches the end of the cube. For example, if the brick shape was a single line and the second cube only had one line then function passed into StartProcess will receive the same contents in the 2nd input buffer every time.
Parameters
wrap Specifies whether or not to wrap
Referenced by Isis::ProcessByLine::ProcessByLine(), and ProcessBySample().
StartProcess() [1/10]
void Isis::ProcessByBrick::StartProcess (std::function< void(Buffer &in)> funct) virtual inherited
Starts the systematic processing of the input cube by moving an arbitrarily-shaped brick through the cube.
This method requires that exactly one input cube be loaded. No output cubes are produced.
Parameters
funct (Buffer &in) Receive an nxm brick in the input buffer. If n=1 and m=lines this will process by columns. Likewise if n=samples and m=1 this will process by lines.
Exceptions
iException::Programmer
Reimplemented in Isis::ProcessByLine.
References Isis::BufferManager::begin(), Isis::Brick::Bricks(), Isis::BufferManager::end(), Isis::Cube::isReadWrite(), Isis::Cube::read(), and Isis::Cube::write().
StartProcess() [2/10]
void Isis::ProcessByBrick::StartProcess (std::function< void(Buffer &in, Buffer &out)> funct) virtual inherited
Starts the systematic processing of the input cube by moving an arbitrarily-shaped brick through the cube.
This method requires that exactly one input cube and one output cube be loaded using the SetInputCube and SetOutputCube methods.
Parameters
funct (Buffer &in, Buffer &out) Receive an nxm brick in the input buffer and output the an nxm brick. If n=1 and m=lines this will process by columns. Likewise if n=samples and m=1 this will process by lines.
Exceptions
iException::Programmer
Reimplemented in Isis::ProcessByLine.
References Isis::BufferManager::begin().
StartProcess() [3/10]
void Isis::ProcessByBrick::StartProcess (std::function< void(std::vector< Buffer * > &in, std::vector< Buffer * > &out)> funct) virtual inherited
Starts the systematic processing of the input cube by moving an arbitrarily-shaped brick through the cube.
This method allows multiple input and output cubes.
Parameters
funct (vector<Buffer *> &in, vector<Buffer *> &out) Receive an nxm brick in the input buffer. If n=1 and m=lines this will process by columns. Likewise if n=samples and m=1 this will process by lines.
Exceptions
iException::Programmer
StartProcess() [4/10]
virtual void Isis::Process::StartProcess (void funct()) inline virtual inherited
In the base class, this method will invoked a user-specified function exactly one time.
In derived classes such as ProcessByLine, the StartProcess will invoke a user-specified function for every line in a cube.
Parameters
funct() Name of your processing function
StartProcess() [5/10]
void Isis::ProcessByBrick::StartProcess (void functBuffer &in) virtual inherited
Starts the systematic processing of the input cube by moving an arbitrarily-shaped brick through the cube.
This method requires that exactly one input cube be loaded. No output cubes are produced.
Parameters
funct (Buffer &in) Receive an nxm brick in the input buffer. If n=1 and m=lines this will process by columns. Likewise if n=samples and m=1 this will process by lines.
Exceptions
iException::Programmer
Reimplemented in Isis::ProcessByTile.
References Isis::BufferManager::begin(), Isis::Brick::Bricks(), Isis::BufferManager::end(), Isis::Cube::isReadWrite(), Isis::Cube::read(), and Isis::Cube::write().
StartProcess() [6/10]
void Isis::ProcessByBrick::StartProcess (void functBuffer &in, Buffer &out) virtual inherited
Starts the systematic processing of the input cube by moving an arbitrarily-shaped brick through the cube.
This method requires that exactly one input cube and one output cube be loaded using the SetInputCube and SetOutputCube methods.
Parameters
funct (Buffer &in, Buffer &out) Receive an nxm brick in the input buffer and output the an nxm brick. If n=1 and m=lines this will process by columns. Likewise if n=samples and m=1 this will process by lines.
Exceptions
iException::Programmer
Reimplemented in Isis::ProcessByTile.
References Isis::BufferManager::begin().
StartProcess() [7/10]
void Isis::ProcessBySample::StartProcess (void functIsis::Buffer &in, Isis::Buffer &out)
This method invokes the process by sample operation over exactly one input and one output cube.
Typically, this method is used for simple operations such as stretching a cube or applying various operators to a cube (add constant, multiply by constant, etc).
Deprecated:
Please use ProcessCube()
Parameters
funct (Isis::Buffer &in, Isis::Buffer &out) Name of your processing function
StartProcess() [8/10]
void Isis::ProcessBySample::StartProcess (void functIsis::Buffer &inout)
This method invokes the process by sample operation over a single input or output cube.
It will be an input cube if the method SetInputCube was invoked exactly one time before calling StartProcess. It will be an output cube if the SetOutputCube method was invoked exactly one time. Typically this method can be used to obtain statistics, histograms, or other information from an input cube.
Deprecated:
Please use ProcessCubeInPlace()
Parameters
funct (Isis::Buffer &b) Name of your processing function
StartProcess() [9/10]
void Isis::ProcessByBrick::StartProcess (void functstd::vector< Buffer * > &in, std::vector< Buffer * > &out) virtual inherited
Starts the systematic processing of the input cube by moving an arbitrarily-shaped brick through the cube.
This method allows multiple input and output cubes.
Parameters
funct (vector<Buffer *> &in, vector<Buffer *> &out) Receive an nxm brick in the input buffer. If n=1 and m=lines this will process by columns. Likewise if n=samples and m=1 this will process by lines.
Exceptions
iException::Programmer
Reimplemented in Isis::ProcessByTile.
StartProcess() [10/10]
void Isis::ProcessBySample::StartProcess (void functstd::vector< Isis::Buffer * > &in, std::vector< Isis::Buffer * > &out)
This method invokes the process by sample operation over multiple input and output cubes.
Typically, this method is used when two input cubes are required for operations like ratios, differences, masking, etc.
Deprecated:
Please use ProcessCubes()
Parameters
funct (vector<Isis::Buffer *> &in, vector<Isis::Buffer *> &out) Name of your processing function
VerifyCubes()
void Isis::ProcessByBrick::VerifyCubes (IOCubes cn) inherited
Verifies the dimensions of the input/output cubes.
Parameters
cn An IOCubes enumeration for one of three possible Input/Output situations: InPlace: The input cube is the output cube InputOutput: One input cube and one output cube InputOutputList: A vector of input and output cubes. The input vector is not necessarily the same length as the output vector
Exceptions
iException::Message
References _FILEINFO_, and Isis::SpatialMatch.
Referenced by Isis::ProcessByLine::ProcessCube(), ProcessCube(), Isis::ProcessBySpectra::ProcessCube(), Isis::ProcessByTile::ProcessCube(), Isis::ProcessByLine::ProcessCubeInPlace(), ProcessCubeInPlace(), Isis::ProcessBySpectra::ProcessCubeInPlace(), Isis::ProcessByTile::ProcessCubeInPlace(), Isis::ProcessByLine::ProcessCubes(), ProcessCubes(), Isis::ProcessBySpectra::ProcessCubes(), and Isis::ProcessByTile::ProcessCubes().
Wraps()
bool Isis::ProcessByBrick::Wraps () inherited
Returns true if the wrapping option is enabled.
See also
SetWrap()
Returns
The value of the wrapping option
Referenced by Isis::ProcessByBrick::ProcessCubes().
WriteHistory()
void Isis::Process::WriteHistory (Cube & cube) inherited
Writes out the History blob to the cube.
References Isis::History::AddEntry(), Isis::iApp, Isis::PvlContainer::isNamed(), Isis::PvlObject::object(), Isis::PvlObject::objects(), Isis::Cube::readHistory(), and Isis::Cube::write().
Referenced by Isis::ImageImporter::import().
Member Data Documentation
InputCubes
std::vector<Isis::Cube *> Isis::Process::InputCubes protected inherited
A vector of pointers to opened Cube objects.
The pointers are established in the SetInputCube/SetInputWorkCube methods.
Referenced by Isis::ProcessExport::CreateWorldFile(), Isis::ProcessExport::GetBuffersBIL(), Isis::ProcessExport::GetBuffersBIP(), Isis::ProcessExport::GetBuffersBSQ(), Isis::ProcessByBrick::ProcessCube(), Isis::ProcessExport::ProcessCubes(), Isis::ProcessByBrick::ProcessCubes(), Isis::ProcessExport::SetInputRange(), Isis::ProcessExport::StartProcess(), and Isis::ProcessByQuickFilter::StartProcess().
m_ownedCubes
QSet<Isis::Cube *>* Isis::Process::m_ownedCubes protected inherited
A list of cubes owned by this instant.
These cubes will be deleted on finalization. Process will not take ownership of cubes allocated outside of Process. It is the caller's responsibility to delete such cubes.
OutputCubes
std::vector<Isis::Cube *> Isis::Process::OutputCubes protected inherited
A vector of pointers to allocated Cube objects.
The pointers are established in the SetOutputCube method.
Referenced by Isis::ProcessImport::ProcessBil(), Isis::ProcessImport::ProcessBip(), Isis::ProcessImport::ProcessBsq(), Isis::ProcessByBrick::ProcessCube(), Isis::ProcessByBrick::ProcessCubes(), Isis::ProcessImport::ProcessJp2(), and Isis::ProcessByQuickFilter::StartProcess().
p_bandStats
std::vector< std::vector< Isis::Statistics * > > Isis::Process::p_bandStats protected inherited
Holds the calculated statistics for each band separately of every input cubei after the CalculateStatistics method is called.
Referenced by Isis::Process::BandStatistics().
p_cubeStats
std::vector< Isis::Statistics * > Isis::Process::p_cubeStats protected inherited
Holds the calculated statistics for every band together of every input cubei after the CalculateStatistics method is called.
Referenced by Isis::Process::CubeStatistics().
p_progress
Isis::Progress* Isis::Process::p_progress protected inherited
Pointer to a Progress object.
Referenced by Isis::ProcessImport::ProcessBil(), Isis::ProcessImport::ProcessBip(), Isis::ProcessImport::ProcessBsq(), Isis::ProcessExport::ProcessCubes(), Isis::ProcessExport::ProcessExport(), Isis::ProcessImport::ProcessImport(), Isis::ProcessImport::ProcessJp2(), Isis::Process::Progress(), Isis::ProcessExport::StartProcess(), and Isis::ProcessByQuickFilter::StartProcess().
p_propagateHistory
bool Isis::Process::p_propagateHistory protected inherited
Flag indicating if history is to be propagated to output cubes.
p_propagateLabels
bool Isis::Process::p_propagateLabels protected inherited
Flag indicating if labels are be propagated to output cubes.
p_propagateOriginalLabel
bool Isis::Process::p_propagateOriginalLabel protected inherited
Flag indicating if original lable is to be propagated to output cubes.
p_propagatePolygons
bool Isis::Process::p_propagatePolygons protected inherited
Flag indicating if blobs are be propagated to output cubes.
p_propagateTables
bool Isis::Process::p_propagateTables protected inherited
Flag indicating if tables are be propagated to output cubes.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ProcessBySample/ProcessBySample.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ProcessBySample/ProcessBySample.cpp