Isis Developer Reference: Isis::QnetFixedPointDialog Class Reference
Isis::QnetFixedPointDialog Class Reference
#include <QnetFixedPointDialog.h>
Public Member Functions
QnetFixedPointDialog (QnetTool *qnetTool, QString defaultPointId, QWidget *parent=0)
QnetNewPointDialog constructor.
~QnetFixedPointDialog ()
bool isFixed () const
bool isConstrained () const
QString pointId () const
QStringList selectedFiles () const
void setFiles (QStringList pointFiles)
Set files found containing selected point.
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
QnetFixedPointDialog()
Isis::QnetFixedPointDialog::QnetFixedPointDialog (QnetTool * qnetTool, QString defaultPointId, QWidget * parent = 0)
QnetNewPointDialog constructor.
Parameters
parent The parent widget for the cube points filter
~QnetFixedPointDialog()
Isis::QnetFixedPointDialog::~QnetFixedPointDialog ()
Member Function Documentation
isConstrained()
bool Isis::QnetFixedPointDialog::isConstrained () const
isFixed()
bool Isis::QnetFixedPointDialog::isFixed () const
Referenced by Isis::QnetTool::createFixedPoint().
pointId()
QString Isis::QnetFixedPointDialog::pointId () const
Referenced by Isis::QnetTool::createFixedPoint().
selectedFiles()
QStringList Isis::QnetFixedPointDialog::selectedFiles () const
Referenced by Isis::QnetTool::createFixedPoint().
setFiles()
void Isis::QnetFixedPointDialog::setFiles (QStringList pointFiles)
Set files found containing selected point.
Author
2010-11-10 Tracie Sucharski
References Isis::SerialNumberList::fileName(), Isis::QnetTool::serialNumberList(), and Isis::SerialNumberList::size().
Referenced by Isis::QnetTool::createFixedPoint().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/QnetTools/QnetFixedPointDialog.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/QnetTools/QnetFixedPointDialog.cpp