Isis Developer Reference: Isis::IsisBundleObservation Class Reference
Isis::IsisBundleObservation Class Reference
Control Networks
Class for observations that use ISIS camera models in bundle adjustment.
#include <IsisBundleObservation.h>
Public Member Functions
IsisBundleObservation ()
Constructs a IsisBundleObservation initialized to a default state.
IsisBundleObservation (BundleImageQsp image, QString observationNumber, QString instrumentId, BundleTargetBodyQsp bundleTargetBody)
Constructs a IsisBundleObservation from an BundleImage, an instrument id, an observation number to assign to this IsisBundleObservation, and a target body.
IsisBundleObservation (const IsisBundleObservation &src)
Creates a copy of another IsisBundleObservation.
~IsisBundleObservation ()
Destructor.
IsisBundleObservation & operator= (const IsisBundleObservation &src)
Assignment operator.
void copy (const IsisBundleObservation &src)
virtual bool setSolveSettings (BundleObservationSolveSettings solveSettings)
Set solve parameters.
int numberPositionParameters ()
Returns the number of position parameters there are.
int numberPointingParameters ()
Returns the number of pointing parameters being solved for.
int numberParameters ()
Returns the number of total parameters there are for solving.
SpiceRotation * spiceRotation ()
Accesses the instrument's spice rotation.
SpicePosition * spicePosition ()
Accesses the instrument's spice position.
const BundleObservationSolveSettingsQsp solveSettings ()
Accesses the solve settings.
bool applyParameterCorrections (LinearAlgebra::Vector corrections)
Applies the parameter corrections.
bool initializeExteriorOrientation ()
Initializes the exterior orientation.
void initializeBodyRotation ()
Intializes the body rotation.
void updateBodyRotation ()
Updates the body rotation.
void bundleOutputFetchData (QVector< double > &finalParameterValues, int &nPositionCoefficients, int &nPointingCoefficients, bool &useDefaultPosition, bool &useDefaultPointing, bool &useDefaultTwist)
Fetches data for the log file output methods.
void bundleOutputString (std::ostream &fpOut, bool errorPropagation)
Takes in an open std::ofstream and writes out information which goes into the bundleout.txt file.
QString bundleOutputCSV (bool errorPropagation)
Creates and returns a formatted QString representing the bundle coefficients and parameters in csv format.
virtual QStringList parameterList ()
Returns the list of observation parameter names.
bool computeTargetPartials (LinearAlgebra::Matrix &coeffTarget, BundleMeasure &measure, BundleSettingsQsp &bundleSettings, BundleTargetBodyQsp &bundleTargetBody)
Computes any needed partials for the target body parameters.
bool computeImagePartials (LinearAlgebra::Matrix &coeffImage, BundleMeasure &measure)
Calculates the sensor partials with respect to the selected solve parameters and populates the coeffImage matrix.
bool computePoint3DPartials (LinearAlgebra::Matrix &coeffPoint3D, BundleMeasure &measure, SurfacePoint::CoordinateType coordType)
Calculates the ground partials for the ground point currently set in the sensor model.
bool computeRHSPartials (LinearAlgebra::Vector &coeffRHS, BundleMeasure &measure)
Calculates the sample, line residuals between the measured focal plane values and the focal plane coordinates calculated for the ground point by the sensor model.
double computeObservationValue (BundleMeasure &measure, double deltaVal)
Converts the observed value from a focal plane coordinate to an image sample or line.
void copy (const BundleObservation &src)
virtual void append (const BundleImageQsp &value)
Appends a BundleImage shared pointer to the BundleObservation.
BundleImageQsp imageByCubeSerialNumber (QString cubeSerialNumber)
Returns the BundleImage shared pointer associated with the given serial number.
void setIndex (int n)
Sets the index for the observation.
int index ()
Accesses the observation's index.
QString instrumentId ()
Accesses the instrument id.
double vtpv ()
Compute vtpv, the weighted sum of squares of constrained image parameter residuals.
virtual LinearAlgebra::Vector & parameterWeights ()
Accesses the solve parameter weights.
virtual LinearAlgebra::Vector & parameterCorrections ()
Accesses the parameter corrections.
virtual LinearAlgebra::Vector & aprioriSigmas ()
Accesses the a priori sigmas.
virtual LinearAlgebra::Vector & adjustedSigmas ()
Accesses the adjusted sigmas.
virtual QStringList imageNames ()
Access to image names for CorrelationMatrix to use.
Protected Attributes
QString m_observationNumber
The shared portion of the serial numbers of all images in the observation.
int m_index
Index of this observation in the set of observations. Map between cube serial number and BundleImage pointers.
QMap< QString, BundleImageQsp > m_cubeSerialNumberToBundleImageMap
QStringList m_serialNumbers
List of all cube serial numbers in observation.
QStringList m_imageNames
List of all cube names.
QString m_instrumentId
Spacecraft instrument id.
LinearAlgebra::Vector m_weights
Parameter weights. Cumulative parameter correction vector.
LinearAlgebra::Vector m_corrections
LinearAlgebra::Vector m_aprioriSigmas
A posteriori (adjusted) parameter sigmas.
LinearAlgebra::Vector m_adjustedSigmas
A posteriori (adjusted) parameter sigmas.
Detailed Description
Class for observations that use ISIS camera models in bundle adjustment.
Constructor & Destructor Documentation
IsisBundleObservation() [1/3]
Isis::IsisBundleObservation::IsisBundleObservation ()
Constructs a IsisBundleObservation initialized to a default state.
IsisBundleObservation() [2/3]
Isis::IsisBundleObservation::IsisBundleObservation (BundleImageQsp image, QString observationNumber, QString instrumentId, BundleTargetBodyQsp bundleTargetBody)
Constructs a IsisBundleObservation from an BundleImage, an instrument id, an observation number to assign to this IsisBundleObservation, and a target body.
Parameters
image QSharedPointer to the primary image in the observation
observationNumber Observation number of the observation
instrumentId Id of the instrument for the observation
bundleTargetBody QSharedPointer to the target body of the observation
IsisBundleObservation() [3/3]
Isis::IsisBundleObservation::IsisBundleObservation (const IsisBundleObservation & src)
Creates a copy of another IsisBundleObservation.
Parameters
src Reference to the IsisBundleObservation to copy
~IsisBundleObservation()
Isis::IsisBundleObservation::~IsisBundleObservation ()
Destructor.
Contained BundleImages will remain until all shared pointers are deleted.
Member Function Documentation
adjustedSigmas()
LinearAlgebra::Vector & Isis::BundleObservation::adjustedSigmas () virtual inherited
Accesses the adjusted sigmas.
Returns
LinearAlgebra::Vector Returns the adjusted sigmas
append()
void Isis::BundleObservation::append (const BundleImageQsp & value) virtual inherited
Appends a BundleImage shared pointer to the BundleObservation.
If the pointer is valid, then the BundleImage and its serial number will be inserted into the serial number to BundleImage map.
Parameters
value The BundleImage to be appended.
See also
QVector::append()
applyParameterCorrections()
bool Isis::IsisBundleObservation::applyParameterCorrections (LinearAlgebra::Vector corrections) virtual
Applies the parameter corrections.
Parameters
corrections Vector of corrections to apply
Exceptions
IException::Unknown "Instrument position is NULL, but position solve option is [not NoPositionFactors]"
IException::Unknown "Instrument position is NULL, but pointing solve option is [not NoPointingFactors]"
IException::Unknown "Unable to apply parameter corrections to IsisBundleObservation."
Returns
bool Returns true upon successful application of corrections
Implements Isis::BundleObservation.
References _FILEINFO_, Isis::SpiceRotation::GetPolynomial(), Isis::SpicePosition::GetPolynomial(), Isis::BundleObservation::index(), Isis::BundleObservationSolveSettings::instrumentPointingSolveOptionToString(), Isis::BundleObservationSolveSettings::instrumentPositionSolveOptionToString(), Isis::BundleObservation::m_corrections, Isis::BundleObservationSolveSettings::NoPointingFactors, Isis::BundleObservationSolveSettings::NoPositionFactors, Isis::SpicePosition::SetPolynomial(), Isis::SpiceRotation::SetPolynomial(), spiceRotation(), and Isis::IException::Unknown.
aprioriSigmas()
LinearAlgebra::Vector & Isis::BundleObservation::aprioriSigmas () virtual inherited
Accesses the a priori sigmas.
Returns
LinearAlgebra::Vector Returns the a priori sigmas
bundleOutputCSV()
QString Isis::IsisBundleObservation::bundleOutputCSV (bool errorPropagation) virtual
Creates and returns a formatted QString representing the bundle coefficients and parameters in csv format.
Parameters
errorPropagation Boolean indicating whether or not to attach more information (corrections, sigmas, adjusted sigmas...) to the output QString
Returns
QString Returns a formatted QString representing the IsisBundleObservation in csv format
Implements Isis::BundleObservation.
References bundleOutputFetchData(), Isis::IsSpecial(), Isis::BundleObservation::m_adjustedSigmas, Isis::BundleObservation::m_aprioriSigmas, Isis::BundleObservation::m_corrections, Isis::RAD2DEG, and Isis::toString().
bundleOutputFetchData()
void Isis::IsisBundleObservation::bundleOutputFetchData (QVector< double > & finalParameterValues, int & nPositionCoefficients, int & nPointingCoefficients, bool & useDefaultPosition, bool & useDefaultPointing, bool & useDefaultTwist)
Fetches data for the log file output methods.
Parameters
finalParameterValues Reference to QVector<double> of calculated position and pointing
nPositionCoefficients Reference to int of the number of position coefficients
nPointingCoefficients Reference to int of the number of pointing coefficients
useDefaultPosition Reference to boolean of whether to use default position
useDefaultPointing Reference to boolean of whether to use default pointing
useDefaultTwist Reference to bollean of whether to use defualt twist
References Isis::SpiceRotation::GetCenterAngles(), Isis::SpicePosition::GetCenterCoordinate(), Isis::SpiceRotation::GetPolynomial(), and Isis::SpicePosition::GetPolynomial().
Referenced by bundleOutputCSV(), and bundleOutputString().
bundleOutputString()
void Isis::IsisBundleObservation::bundleOutputString (std::ostream & fpOut, bool errorPropagation) virtual
Takes in an open std::ofstream and writes out information which goes into the bundleout.txt file.
Parameters
fpOut The open std::ofstream object which is passed in from BundleSolutionInfo::outputText()
errorPropagation Boolean indicating whether or not to attach more information (corrections, sigmas, adjusted sigmas...) to the output.
Implements Isis::BundleObservation.
References bundleOutputFetchData(), Isis::IsSpecial(), Isis::BundleObservation::m_adjustedSigmas, Isis::BundleObservation::m_aprioriSigmas, Isis::BundleObservation::m_corrections, Isis::RAD2DEG, and Isis::toString().
computeImagePartials()
bool Isis::IsisBundleObservation::computeImagePartials (LinearAlgebra::Matrix & coeffImage, BundleMeasure & measure) virtual
Calculates the sensor partials with respect to the selected solve parameters and populates the coeffImage matrix.
Parameters
coeffImage A matrix that will be populated with the sensor partials with respect to the specified solve parameters.
measure The measure that the partials are being computed for.
Returns
bool
Implements Isis::BundleObservation.
References Isis::BundleMeasure::camera(), Isis::CameraGroundMap::GetdXYdOrientation(), Isis::CameraGroundMap::GetdXYdPosition(), Isis::Camera::GroundMap(), Isis::BundleObservation::index(), Isis::BundleObservationSolveSettings::NoPointingFactors, Isis::BundleObservationSolveSettings::NoPositionFactors, Isis::Camera::PixelPitch(), solveSettings(), Isis::SpiceRotation::WRT_Declination, Isis::SpiceRotation::WRT_RightAscension, Isis::SpiceRotation::WRT_Twist, Isis::SpicePosition::WRT_X, Isis::SpicePosition::WRT_Y, and Isis::SpicePosition::WRT_Z.
computeObservationValue()
double Isis::IsisBundleObservation::computeObservationValue (BundleMeasure & measure, double deltaVal) virtual
Converts the observed value from a focal plane coordinate to an image sample or line.
Parameters
measure The measure that the partials are being computed for.
deltaVal The difference between the measured and calculated focal plane coordinate
Returns
double The The difference between the measured and calculated (line, sample) coordinate
Implements Isis::BundleObservation.
computePoint3DPartials()
bool Isis::IsisBundleObservation::computePoint3DPartials (LinearAlgebra::Matrix & coeffPoint3D, BundleMeasure & measure, SurfacePoint::CoordinateType coordType) virtual
Calculates the ground partials for the ground point currently set in the sensor model.
Parameters
coeffPoint3D A matrix that will be populated with the (line, sample) partials with respect to the ground point.
measure The measure that the partials are being computed for.
coordType Specifies whether latitudinal or (x, y, z) coordinates are used.
Returns
bool
Implements Isis::BundleObservation.
References Isis::BundleControlPoint::adjustedSurfacePoint(), Isis::BundleMeasure::camera(), Isis::CameraGroundMap::GetdXYdPoint(), Isis::Camera::GroundMap(), Isis::SurfacePoint::One, Isis::BundleMeasure::parentControlPoint(), Isis::SurfacePoint::Partial(), Isis::Camera::PixelPitch(), Isis::SurfacePoint::Three, and Isis::SurfacePoint::Two.
computeRHSPartials()
bool Isis::IsisBundleObservation::computeRHSPartials (LinearAlgebra::Vector & coeffRHS, BundleMeasure & measure) virtual
Calculates the sample, line residuals between the measured focal plane values and the focal plane coordinates calculated for the ground point by the sensor model.
Parameters
coeffRHS A vector that will contain the focal plane x, y residuals.
measure The measure that the partials are being computed for.
Returns
bool
Implements Isis::BundleObservation.
References _FILEINFO_, Isis::BundleControlPoint::adjustedSurfacePoint(), Isis::BundleMeasure::camera(), Isis::BundleMeasure::cubeSerialNumber(), Isis::BundleMeasure::focalPlaneMeasuredX(), Isis::BundleMeasure::focalPlaneMeasuredY(), Isis::CameraGroundMap::GetXY(), Isis::Camera::GroundMap(), Isis::BundleControlPoint::id(), Isis::BundleMeasure::parentControlPoint(), Isis::Camera::PixelPitch(), and Isis::IException::User.
computeTargetPartials()
bool Isis::IsisBundleObservation::computeTargetPartials (LinearAlgebra::Matrix & coeffTarget, BundleMeasure & measure, BundleSettingsQsp & bundleSettings, BundleTargetBodyQsp & bundleTargetBody) virtual
Computes any needed partials for the target body parameters.
Parameters
coeffTarget Matrix for target body partial derivatives
measure The measure that the partials are being computed for.
bundleSettings The settings for the bundle adjustment
bundleTargetBody QSharedPointer to the target body of the observation
Returns
bool
Implements Isis::BundleObservation.
References Isis::BundleControlPoint::adjustedSurfacePoint(), Isis::BundleMeasure::camera(), Isis::CameraGroundMap::EllipsoidPartial(), Isis::CameraGroundMap::GetdXYdPoint(), Isis::CameraGroundMap::GetdXYdTOrientation(), Isis::Camera::GroundMap(), Isis::BundleObservation::index(), Isis::CameraGroundMap::MeanRadiusPartial(), Isis::BundleMeasure::parentControlPoint(), Isis::Camera::PixelPitch(), Isis::SpiceRotation::WRT_Declination, Isis::CameraGroundMap::WRT_MajorAxis, Isis::CameraGroundMap::WRT_MinorAxis, Isis::CameraGroundMap::WRT_PolarAxis, Isis::SpiceRotation::WRT_RightAscension, and Isis::SpiceRotation::WRT_Twist.
copy() [1/2]
void Isis::BundleObservation::copy (const BundleObservation & src) inherited
copy() [2/2]
void Isis::IsisBundleObservation::copy (const IsisBundleObservation & src)
imageByCubeSerialNumber()
BundleImageQsp Isis::BundleObservation::imageByCubeSerialNumber (QString cubeSerialNumber) inherited
Returns the BundleImage shared pointer associated with the given serial number.
If no BundleImage with that serial number is contained a NULL pointer is returned.
Parameters
cubeSerialNumber The serial number of the cube to be returned.
Returns
BundleImageQsp A shared pointer to the BundleImage (NULL if not found).
imageNames()
QStringList Isis::BundleObservation::imageNames () virtual inherited
Access to image names for CorrelationMatrix to use.
Returns
QStringList Returns a QStringList of the image names
index()
int Isis::BundleObservation::index () inherited
Accesses the observation's index.
Returns
int Returns the observation's index
Referenced by applyParameterCorrections(), computeImagePartials(), and computeTargetPartials().
initializeBodyRotation()
void Isis::IsisBundleObservation::initializeBodyRotation ()
Intializes the body rotation.
initializeExteriorOrientation()
bool Isis::IsisBundleObservation::initializeExteriorOrientation ()
Initializes the exterior orientation.
Returns
bool Returns true upon successful intialization
References Isis::SpicePosition::GetBaseTime(), Isis::SpiceRotation::GetBaseTime(), Isis::SpiceRotation::GetPolynomial(), Isis::SpicePosition::GetPolynomial(), Isis::SpicePosition::GetTimeScale(), Isis::SpiceRotation::GetTimeScale(), Isis::BundleObservationSolveSettings::NoPointingFactors, Isis::BundleObservationSolveSettings::NoPositionFactors, Isis::SpicePosition::SetOverrideBaseTime(), Isis::SpiceRotation::SetOverrideBaseTime(), Isis::SpicePosition::SetPolynomial(), Isis::SpiceRotation::SetPolynomial(), Isis::SpicePosition::SetPolynomialDegree(), Isis::SpiceRotation::SetPolynomialDegree(), and spicePosition().
instrumentId()
QString Isis::BundleObservation::instrumentId () inherited
Accesses the instrument id.
Returns
QString Returns the instrument id of the observation
numberParameters()
int Isis::IsisBundleObservation::numberParameters () virtual
Returns the number of total parameters there are for solving.
The total number of parameters is equal to the number of position parameters and number of pointing parameters
Returns
int Returns the number of parameters there are
Implements Isis::BundleObservation.
References numberPointingParameters(), and numberPositionParameters().
numberPointingParameters()
int Isis::IsisBundleObservation::numberPointingParameters ()
Returns the number of pointing parameters being solved for.
Returns
int Returns the number of pointing parameters
Referenced by numberParameters().
numberPositionParameters()
int Isis::IsisBundleObservation::numberPositionParameters ()
Returns the number of position parameters there are.
Returns
int Returns the number of position parameters
Referenced by numberParameters().
operator=()
IsisBundleObservation & Isis::IsisBundleObservation::operator= (const IsisBundleObservation & src)
Assignment operator.
Assigns the state of the source IsisBundleObservation to this IsisBundleObservation
Parameters
IsisBundleObservation Reference to the source IsisBundleObservation to assign from
Returns
IsisBundleObservation& Reference to this IsisBundleObservation
References Isis::BundleObservation::operator=().
parameterCorrections()
LinearAlgebra::Vector & Isis::BundleObservation::parameterCorrections () virtual inherited
Accesses the parameter corrections.
Returns
LinearAlgebra::Vector Returns the parameter corrections
parameterList()
QStringList Isis::IsisBundleObservation::parameterList () virtual
Returns the list of observation parameter names.
This will always return at least one set of positions and pointings because we always output at least the center values even when not solving for them.
Returns
QStringList List of observation parameter names
Implements Isis::BundleObservation.
References solveSettings(), and Isis::toString().
parameterWeights()
LinearAlgebra::Vector & Isis::BundleObservation::parameterWeights () virtual inherited
Accesses the solve parameter weights.
Returns
LinearAlgebra::Vector Returns the parameter weights for solving
setIndex()
void Isis::BundleObservation::setIndex (int n) inherited
Sets the index for the observation.
Parameters
n Value to set the index of the observation to
setSolveSettings()
bool Isis::IsisBundleObservation::setSolveSettings (BundleObservationSolveSettings solveSettings) virtual
Set solve parameters.
Parameters
solveSettings The solve settings to use
Returns
bool Returns true if settings were successfully set
Implements Isis::BundleObservation.
References Isis::BundleObservation::m_adjustedSigmas, Isis::BundleObservation::m_aprioriSigmas, Isis::BundleObservation::m_corrections, Isis::BundleObservation::m_weights, Isis::Null, and solveSettings().
solveSettings()
const BundleObservationSolveSettingsQsp Isis::IsisBundleObservation::solveSettings () virtual
Accesses the solve settings.
Returns
const IsisBundleObservationSolveSettingsQsp Returns a pointer to the solve settings for this IsisBundleObservation
Implements Isis::BundleObservation.
Referenced by computeImagePartials(), parameterList(), and setSolveSettings().
spicePosition()
SpicePosition * Isis::IsisBundleObservation::spicePosition ()
Accesses the instrument's spice position.
Returns
SpicePosition* Returns the SpicePosition for this observation
Referenced by initializeExteriorOrientation().
spiceRotation()
SpiceRotation * Isis::IsisBundleObservation::spiceRotation ()
Accesses the instrument's spice rotation.
Returns
SpiceRotation* Returns the SpiceRotation for this observation
Referenced by applyParameterCorrections().
updateBodyRotation()
void Isis::IsisBundleObservation::updateBodyRotation ()
Updates the body rotation.
vtpv()
double Isis::BundleObservation::vtpv () inherited
Compute vtpv, the weighted sum of squares of constrained image parameter residuals.
Returns
double Weighted sum of squares of constrained image parameter residuals.
Member Data Documentation
m_adjustedSigmas
LinearAlgebra::Vector Isis::BundleObservation::m_adjustedSigmas protected inherited
A posteriori (adjusted) parameter sigmas.
Referenced by bundleOutputCSV(), Isis::CsmBundleObservation::bundleOutputCSV(), bundleOutputString(), Isis::CsmBundleObservation::bundleOutputString(), setSolveSettings(), and Isis::CsmBundleObservation::setSolveSettings().
m_aprioriSigmas
LinearAlgebra::Vector Isis::BundleObservation::m_aprioriSigmas protected inherited
A posteriori (adjusted) parameter sigmas.
Referenced by bundleOutputCSV(), Isis::CsmBundleObservation::bundleOutputCSV(), bundleOutputString(), Isis::CsmBundleObservation::bundleOutputString(), setSolveSettings(), and Isis::CsmBundleObservation::setSolveSettings().
m_corrections
LinearAlgebra::Vector Isis::BundleObservation::m_corrections protected inherited
Referenced by applyParameterCorrections(), Isis::CsmBundleObservation::applyParameterCorrections(), bundleOutputCSV(), Isis::CsmBundleObservation::bundleOutputCSV(), bundleOutputString(), Isis::CsmBundleObservation::bundleOutputString(), setSolveSettings(), and Isis::CsmBundleObservation::setSolveSettings().
m_cubeSerialNumberToBundleImageMap
QMap<QString, BundleImageQsp> Isis::BundleObservation::m_cubeSerialNumberToBundleImageMap protected inherited
Referenced by Isis::BundleObservation::BundleObservation(), and Isis::BundleObservation::operator=().
m_imageNames
QStringList Isis::BundleObservation::m_imageNames protected inherited
List of all cube names.
m_index
int Isis::BundleObservation::m_index protected inherited
Index of this observation in the set of observations. Map between cube serial number and BundleImage pointers.
Referenced by Isis::BundleObservation::BundleObservation().
m_instrumentId
QString Isis::BundleObservation::m_instrumentId protected inherited
Spacecraft instrument id.
Referenced by Isis::BundleObservation::BundleObservation(), and Isis::BundleObservation::operator=().
m_observationNumber
QString Isis::BundleObservation::m_observationNumber protected inherited
The shared portion of the serial numbers of all images in the observation.
Referenced by Isis::BundleObservation::BundleObservation(), and Isis::BundleObservation::operator=().
m_serialNumbers
QStringList Isis::BundleObservation::m_serialNumbers protected inherited
List of all cube serial numbers in observation.
Referenced by Isis::BundleObservation::BundleObservation(), and Isis::BundleObservation::operator=().
m_weights
LinearAlgebra::Vector Isis::BundleObservation::m_weights protected inherited
Parameter weights. Cumulative parameter correction vector.
Referenced by setSolveSettings(), and Isis::CsmBundleObservation::setSolveSettings().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/BundleUtilities/IsisBundleObservation.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/BundleUtilities/IsisBundleObservation.cpp