Isis Developer Reference: Isis::SerialNumber Class Reference
Isis::SerialNumber Class Reference
Control Networks
Serial Number composer.
#include <SerialNumber.h>
Public Member Functions
SerialNumber ()
Create an empty SerialNumber object.
virtual ~SerialNumber ()
Destroy a SerialNumber object.
Static Public Member Functions
static QString Compose (Pvl &label, bool def2filename=false)
Compose a SerialNumber from a PVL.
static QString Compose (Cube &cube, bool def2filename=false)
Compose a SerialNumber from a Cube.
static QString Compose (const QString &filename, bool def2filename=false)
Compose a SerialNumber from a file.
static QString ComposeObservation (const QString &sn, SerialNumberList &list, bool def2filename=false)
Creates the ObservationNumber from a string representing the SerialNumber and a SerialList.
Static Protected Member Functions
static QString CreateSerialNumber (PvlGroup &snGroup, int key)
Create the SerialNumber string by concatenating the keywords in the label with '/' in between serialNumber groups and the number of observationKeys.
Detailed Description
Serial Number composer.
A Serial Number is a unique identification for some object such as an Isis cube. A Serial Number for a specific object must be repeatable. This class is intended to be used to create all Serial Numbers for Isis.
Author
2005-07-28 Stuart Sides
Constructor & Destructor Documentation
SerialNumber()
Isis::SerialNumber::SerialNumber ()
Create an empty SerialNumber object.
~SerialNumber()
Isis::SerialNumber::~SerialNumber () virtual
Destroy a SerialNumber object.
Member Function Documentation
Compose() [1/3]
QString Isis::SerialNumber::Compose (const QString & filename, bool def2filename = false) static
Compose a SerialNumber from a file.
Parameters
filename a filename to open
def2filename If a serial number could not be found, try to return the filename
Returns
Calculated SerialNumber or FileName
References Compose().
Compose() [2/3]
QString Isis::SerialNumber::Compose (Cube & cube, bool def2filename = false) static
Compose a SerialNumber from a Cube.
Parameters
cube An opened Isis cub
def2filename If a serial number could not be found, try to return the filename
Returns
Calculated SerialNumber or FileName
References Compose(), and Isis::Cube::label().
Compose() [3/3]
QString Isis::SerialNumber::Compose (Pvl & label, bool def2filename = false) static
Compose a SerialNumber from a PVL.
Parameters
label A pvl formatted label to be used to generate the serial number
def2filename If a serial number could not be found, try to return the filename
Returns
Calculated SerialNumber or FileName
References CreateSerialNumber(), Isis::PvlContainer::fileName(), and Isis::FileName::name().
Referenced by Isis::SerialNumberList::add(), Compose(), Isis::QnetFileTool::loadImage(), Isis::ControlNetTool::mouseButtonRelease(), Isis::ChipViewport::paintEvent(), Isis::StereoTool::paintViewport(), and Isis::Image::serialNumber().
ComposeObservation()
QString Isis::SerialNumber::ComposeObservation (const QString & sn, SerialNumberList & list, bool def2filename = false) static
Creates the ObservationNumber from a string representing the SerialNumber and a SerialList.
Parameters
sn the string representing the SerialNumber
list the SerialNumberList
def2filename If a serial number could not be found, try to return the filename
Returns
Calculated SerialNumber or FileName
References Isis::ObservationNumber::Compose(), and Isis::SerialNumberList::fileName().
CreateSerialNumber()
QString Isis::SerialNumber::CreateSerialNumber (PvlGroup & snGroup, int keys) static protected
Create the SerialNumber string by concatenating the keywords in the label with '/' in between serialNumber groups and the number of observationKeys.
Parameters
snGroup A PvlGroup containing the keywords to concatenate
keys the number of strings to contatenate
Referenced by Isis::ObservationNumber::Compose(), and Compose().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/SerialNumber/SerialNumber.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/SerialNumber/SerialNumber.cpp