Isis Developer Reference: Isis::ImageHistogram Class Reference
Isis::ImageHistogram Class Reference
Statistics
Container of a cube histogram.
#include <ImageHistogram.h>
Public Member Functions
ImageHistogram (double minimum, double maximum, int bins=1024)
Constructs a histogram object.
ImageHistogram (Cube &cube, int statsBand, Progress *progress=NULL, double startSample=1.0, double startLine=1.0, double endSample=Null, double endLine=Null, int bins=0, bool addCubeData=false)
Constructs a histogram object using a cube.
~ImageHistogram ()
Destructs a histogram object.
virtual void AddData (const double *data, const unsigned int count)
Add an array of doubles to the histogram counters.
virtual void AddData (const double data)
Add a single double data to the histogram.
virtual void RemoveData (const double *data, const unsigned int count)
Remove an array of doubles from the histogram counters.
virtual void BinRange (const int index, double &low, double &high) const
Returns the left edge and right edge values of a bin.
void SetBins (const int bins)
Change the number of bins in the histogram and reset counters.
void Reset ()
Resets histogram counters to zero.
void RemoveData (const double data)
double Median () const
Returns the median.
double Mode () const
Returns the mode.
double Percent (const double percent) const
Computes and returns the value at X percent of the histogram.
double Skew () const
Computes and returns the skew.
BigInt BinCount (const int index) const
Returns the count at a bin position in the histogram.
double BinMiddle (const int index) const
Returns the value represented by a bin.
double BinSize () const
Returns the size of an individual bin.
int Bins () const
Returns the number of bins in the histogram.
BigInt MaxBinCount () const
Returns the highest bin count.
double BinRangeStart () const
double BinRangeEnd () const
void SetValidRange (const double minimum=Isis::ValidMinimum, const double maximum=Isis::ValidMaximum)
Changes the range of the bins.
void readStatistics (QXmlStreamReader *xmlReader)
double ValidMinimum () const
double ValidMaximum () const
bool InRange (const double value)
bool AboveRange (const double value)
bool BelowRange (const double value)
double Average () const
Computes and returns the average.
double StandardDeviation () const
Computes and returns the standard deviation.
double Variance () const
Computes and returns the variance.
double Sum () const
Returns the sum of all the data.
double SumSquare () const
Returns the sum of all the squared data.
double Rms () const
Computes and returns the rms.
double Minimum () const
Returns the absolute minimum double found in all data passed through the AddData method.
double Maximum () const
Returns the absolute maximum double found in all data passed through the AddData method.
double ChebyshevMinimum (const double percent=99.5) const
This method returns a minimum such that X percent of the data will fall with K standard deviations of the average (Chebyshev's Theorem).
double ChebyshevMaximum (const double percent=99.5) const
This method returns a maximum such that X percent of the data will fall with K standard deviations of the average (Chebyshev's Theorem).
double BestMinimum (const double percent=99.5) const
This method returns the better of the absolute minimum or the Chebyshev minimum.
double BestMaximum (const double percent=99.5) const
This method returns the better of the absolute maximum or the Chebyshev maximum.
double ZScore (const double value) const
This method returns the better of the z-score of the given value.
BigInt TotalPixels () const
Returns the total number of pixels processed (valid and invalid).
BigInt ValidPixels () const
Returns the total number of valid pixels processed.
BigInt OverRangePixels () const
Returns the total number of pixels over the valid range encountered.
BigInt UnderRangePixels () const
Returns the total number of pixels under the valid range encountered.
BigInt NullPixels () const
Returns the total number of NULL pixels encountered.
BigInt LisPixels () const
Returns the total number of low instrument saturation (LIS) pixels encountered.
BigInt LrsPixels () const
Returns the total number of low representation saturation (LRS) pixels encountered.
BigInt HisPixels () const
Returns the total number of high instrument saturation (HIS) pixels encountered.
BigInt HrsPixels () const
Returns the total number of high representation saturation (HRS) pixels encountered.
BigInt OutOfRangePixels () const
Returns the total number of pixels outside of the valid range encountered.
bool RemovedData () const
PvlGroup toPvl (QString name="Statistics") const
Serialize statistics as a pvl group.
void save (QXmlStreamWriter &stream, const Project *project) const
QDataStream & write (QDataStream &stream) const
Order saved must match the offsets in the static compoundH5DataType() method.
QDataStream & read (QDataStream &stream)
Protected Attributes
std::vector< BigInt > p_bins
The array of counts.
Detailed Description
Container of a cube histogram.
This class is used to accumulate an image histogram on double arrays. In particular, it is highly useful for obtaining a histogram on cube data. Parameters which can be computed are the 1) median, 2) mode, and 3) skew. The histogram consists of a fixed set of distinct bins. When an object is created the programmer must provide a minimum and maximum which defines how data is further placed in the bins. The minimum is mapped to the middle of the first bin [0] and the maximum is mapped to the middle of the last bin [Bins()-1]. There are a set of methods which return bin information such as 1) count, 2) size, 3) middle value, 4) range, and 5) maximum bin count.
Author
2020-09-22 Adam Paquette
Constructor & Destructor Documentation
ImageHistogram() [1/2]
Isis::ImageHistogram::ImageHistogram (double minimum, double maximum, int nbins = 1024)
Constructs a histogram object.
Only data between the minimum and maximum will be binned, and the bin range will be from the minimum to the maximum.
Parameters
minimum Minimum value for binning the data into the histogram.
maximum Maximum value for binning the data into the histogram.
nbins The number of bins to use
ImageHistogram() [2/2]
Isis::ImageHistogram::ImageHistogram (Cube & cube, int statsBand, Progress * progress = NULL, double startSample = 1.0, double startLine = 1.0, double endSample = Null, double endLine = Null, int bins = 0, bool addCubeData = false)
Constructs a histogram object using a cube.
This constructor computes the minimum, maximum for the binning range and number of bins automatically. All statistics will still be collected, though data at either end of the histogram will be put into one bin in order to attempt to achieve better histogram statistics.
TODO: progress needs to be a bool.
Parameters
cube The cube to used to determine min/max and bins
statsBand The band number the histogram will be collected from
progress The Progress object to be used to output the percent processed information
startSample The sample to start reading cube data from
startLine The line to start reading cube data from
endSample The sample to stop reading cube data at (Null for nsamps)
endLine The line to stop reading cube data at (Null for nlines)
bins The number of histogram bins to create (0 for automatic)
addCubeData True to fill the histogram with data in addition to initializing the binning ranges.
References AddData(), Isis::Cube::bandCount(), Isis::Progress::CheckStatus(), Isis::Buffer::DoubleBuffer(), Isis::Cube::pixelType(), Isis::Cube::read(), Isis::Brick::SetBasePosition(), Isis::Progress::SetMaximumSteps(), Isis::Progress::SetText(), and Isis::Buffer::size().
~ImageHistogram()
Isis::ImageHistogram::~ImageHistogram ()
Destructs a histogram object.
Member Function Documentation
AboveRange()
bool Isis::Statistics::AboveRange (const double value) inherited
Referenced by Isis::Statistics::AddData(), Isis::Statistics::InRange(), and Isis::Statistics::RemoveData().
AddData() [1/2]
void Isis::ImageHistogram::AddData (const double * data, const unsigned int count) virtual
Add an array of doubles to the histogram counters.
This method can be invoked multiple times. For example, once for each line in a cube, before obtaining statistics and histogram information.
Parameters
data Pointer to array of double to add.
count Number of doubles to process.
Reimplemented from Isis::Histogram.
References Isis::Statistics::AddData(), Isis::Histogram::BinRangeEnd(), Isis::Histogram::BinRangeStart(), Isis::Statistics::InRange(), Isis::IsValidPixel(), and Isis::Histogram::p_bins.
Referenced by ImageHistogram().
AddData() [2/2]
void Isis::ImageHistogram::AddData (const double data) virtual
Add a single double data to the histogram.
Of course this can be invoke multiple times. e.g. once for each residual in a network for instance.
Parameters
data a single observation to be added to the histogram
Reimplemented from Isis::Histogram.
References Isis::Statistics::AddData(), Isis::Histogram::BinRangeEnd(), Isis::Histogram::BinRangeStart(), Isis::Statistics::InRange(), Isis::IsValidPixel(), and Isis::Histogram::p_bins.
Average()
double Isis::Statistics::Average () const inherited
Computes and returns the average.
If there are no valid pixels, then NULL8 is returned.
Returns
The Average
References Isis::NULL8.
Referenced by Isis::OverlapNormalization::AddOverlap(), Isis::averageLines(), Isis::ControlNet::AverageResidual(), Isis::averageSamples(), Isis::Statistics::ChebyshevMaximum(), Isis::Statistics::ChebyshevMinimum(), Isis::MultivariateStatistics::Covariance(), Isis::ControlNetStatistics::GenerateControlNetStats(), Isis::ZeroBufferFit::guess(), main(), Isis::ControlPointGraphicsItem::paint(), Isis::VisualDisplay::paintPixmap(), Isis::AutoReg::Reduce(), Isis::CameraStatistics::toPvl(), Isis::Statistics::toPvl(), and Isis::Statistics::ZScore().
BelowRange()
bool Isis::Statistics::BelowRange (const double value) inherited
Referenced by Isis::Statistics::AddData(), Isis::Statistics::InRange(), and Isis::Statistics::RemoveData().
BestMaximum()
double Isis::Statistics::BestMaximum (const double percent = 99.5) const inherited
This method returns the better of the absolute maximum or the Chebyshev maximum.
The better value is considered the value closest to the mean.
Parameters
percent The probability that the maximum is within K standard deviations of the mean (Used to compute the Chebyshev maximum). Default value = 99.5.
Returns
Best of absolute and Chebyshev maximums
See also
Statistics::Maximum Statistics::ChebyshevMaximum
References Isis::Statistics::ChebyshevMaximum(), Isis::Statistics::Maximum(), Isis::Statistics::Minimum(), and Isis::NULL8.
Referenced by Isis::IndependentCubeViewport::cubeDataChanged(), Isis::StretchTool::histFromBuffer(), Isis::VisualDisplay::setPixelData(), Isis::LinearStretchType::setStretch(), Isis::StretchTool::stretchBand(), and Isis::StretchTool::stretchBuffer().
BestMinimum()
double Isis::Statistics::BestMinimum (const double percent = 99.5) const inherited
This method returns the better of the absolute minimum or the Chebyshev minimum.
The better value is considered the value closest to the mean.
Parameters
percent The probability that the minimum is within K standard deviations of the mean (Used to compute the Chebyshev minimum). Default value = 99.5.
Returns
Best of absolute and Chebyshev minimums
See also
Statistics::Minimum Statistics::ChebyshevMinimum
References Isis::Statistics::ChebyshevMinimum(), Isis::Statistics::Maximum(), Isis::Statistics::Minimum(), and Isis::NULL8.
Referenced by Isis::IndependentCubeViewport::cubeDataChanged(), Isis::StretchTool::histFromBuffer(), Isis::VisualDisplay::setPixelData(), Isis::LinearStretchType::setStretch(), Isis::StretchTool::stretchBand(), and Isis::StretchTool::stretchBuffer().
BinCount()
BigInt Isis::Histogram::BinCount (const int index) const inherited
Returns the count at a bin position in the histogram.
Parameters
index Index of the desired bin 0 to Bins()-1.
Returns
The count at a bin position in the histogram.
References _FILEINFO_, and Isis::Message::ArraySubscriptNotInRange().
Referenced by Isis::QHistogram::Load(), and Isis::HistogramWidget::setHistogram().
BinMiddle()
double Isis::Histogram::BinMiddle (const int index) const inherited
Returns the value represented by a bin.
This is not the count, but the actual data value at the middle of the bin.
Parameters
index Index of the desired bin 0 to Bins()-1.
Returns
The middle value of the bin.
References _FILEINFO_, and Isis::Message::ArraySubscriptNotInRange().
Referenced by Isis::QHistogram::Load(), and Isis::HistogramWidget::setHistogram().
BinRange()
void Isis::ImageHistogram::BinRange (const int index, double & low, double & high) const virtual
Returns the left edge and right edge values of a bin.
That is the range of data the bin covers.
Exceptions
iException The programmer has passed in an index outside of 0 to Bins()-1.
Parameters
index Index of the desired bin 0 to Bins()-1.
low The value at the left edge of the requested bin.
high The value at the right edge of the requested bin.
Reimplemented from Isis::Histogram.
References _FILEINFO_, Isis::Message::ArraySubscriptNotInRange(), Isis::Histogram::BinRangeEnd(), Isis::Histogram::BinRangeStart(), Isis::Histogram::p_bins, and Isis::IException::Programmer.
BinRangeEnd()
double Isis::Histogram::BinRangeEnd () const inline inherited
Referenced by AddData(), BinRange(), Isis::Cube::histogram(), and RemoveData().
BinRangeStart()
double Isis::Histogram::BinRangeStart () const inline inherited
Referenced by AddData(), BinRange(), Isis::Cube::histogram(), and RemoveData().
Bins()
int Isis::Histogram::Bins () const inherited
Returns the number of bins in the histogram.
Returns
The number of bins in the histogram.
Referenced by Isis::GaussianStretch::GaussianStretch(), Isis::QHistogram::Load(), and Isis::HistogramWidget::setHistogram().
BinSize()
double Isis::Histogram::BinSize () const inherited
Returns the size of an individual bin.
Essentially, the difference of the high and low edge values (BinRange) of a bin. This value is constant for all bins.
Returns
The size of the individual bin.
Referenced by Isis::HistogramWidget::setHistogram(), Isis::BinaryStretchType::setStretch(), Isis::LinearStretchType::setStretch(), and Isis::SawtoothStretchType::setStretch().
ChebyshevMaximum()
double Isis::Statistics::ChebyshevMaximum (const double percent = 99.5) const inherited
This method returns a maximum such that X percent of the data will fall with K standard deviations of the average (Chebyshev's Theorem).
It can be used to obtain a minimum that does not include statistical outliers.
Parameters
percent The probability that the maximum is within K standard deviations of the mean. Default value = 99.5.
Returns
maximum value excluding statistical outliers
Exceptions
Isis::IException::Message
References _FILEINFO_, Isis::Statistics::Average(), Isis::NULL8, Isis::IException::Programmer, and Isis::Statistics::StandardDeviation().
Referenced by Isis::Statistics::BestMaximum().
ChebyshevMinimum()
double Isis::Statistics::ChebyshevMinimum (const double percent = 99.5) const inherited
This method returns a minimum such that X percent of the data will fall with K standard deviations of the average (Chebyshev's Theorem).
It can be used to obtain a minimum that does not include statistical outliers.
Parameters
percent The probability that the minimum is within K standard deviations of the mean. Default value = 99.5.
Returns
Minimum value (excluding statistical outliers)
Exceptions
Isis::IException::Message
References _FILEINFO_, Isis::Statistics::Average(), Isis::NULL8, Isis::IException::Programmer, and Isis::Statistics::StandardDeviation().
Referenced by Isis::Statistics::BestMinimum().
HisPixels()
BigInt Isis::Statistics::HisPixels () const inherited
Returns the total number of high instrument saturation (HIS) pixels encountered.
Returns
The number of HIS pixels (data) processed
Referenced by Isis::Statistics::toPvl().
HrsPixels()
BigInt Isis::Statistics::HrsPixels () const inherited
Returns the total number of high representation saturation (HRS) pixels encountered.
Returns
The number of HRS pixels (data) processed
Referenced by Isis::Statistics::toPvl().
InRange()
bool Isis::Statistics::InRange (const double value) inherited
References Isis::Statistics::AboveRange(), and Isis::Statistics::BelowRange().
Referenced by AddData().
LisPixels()
BigInt Isis::Statistics::LisPixels () const inherited
Returns the total number of low instrument saturation (LIS) pixels encountered.
Returns
The number of LIS pixels (data) processed
Referenced by Isis::Statistics::toPvl().
LrsPixels()
BigInt Isis::Statistics::LrsPixels () const inherited
Returns the total number of low representation saturation (LRS) pixels encountered.
Returns
The number of LRS pixels (data) processed
Referenced by Isis::Statistics::toPvl().
MaxBinCount()
BigInt Isis::Histogram::MaxBinCount () const inherited
Returns the highest bin count.
Returns
The highest bin count.
Referenced by Isis::HistogramWidget::setHistogram().
Maximum()
double Isis::Statistics::Maximum () const inherited
Returns the absolute maximum double found in all data passed through the AddData method.
If there are no valid pixels, then NULL8 is returned.
Returns
Current maximum value in data set
Exceptions
Isis::IException::Message The data set is blank, so the maximum is invalid.
References _FILEINFO_, Isis::NULL8, and Isis::IException::Programmer.
Referenced by Isis::Statistics::BestMaximum(), Isis::Statistics::BestMinimum(), Isis::IndependentCubeViewport::cubeDataChanged(), Isis::QnetPointJigsawErrorFilter::filter(), Isis::QnetPointRegistrationErrorFilter::filter(), Isis::GaussianStretch::GaussianStretch(), Isis::ControlNetStatistics::GenerateControlNetStats(), Isis::ControlNet::GetMaximumResidual(), Isis::ControlPointGraphicsItem::paint(), Isis::VisualDisplay::paintPixmap(), Isis::SawtoothStretchType::SawtoothStretchType(), Isis::ScatterPlotData::ScatterPlotData(), Isis::HistogramWidget::setHistogram(), Isis::BinaryStretchType::setStretch(), Isis::StretchTool::stretchBuffer(), Isis::CameraStatistics::toPvl(), Isis::Statistics::toPvl(), and Isis::Statistics::ZScore().
Median()
double Isis::Histogram::Median () const inherited
Returns the median.
Returns
The median
Referenced by Isis::SawtoothStretchType::SawtoothStretchType(), and Isis::ProcessExport::SetInputRange().
Minimum()
double Isis::Statistics::Minimum () const inherited
Returns the absolute minimum double found in all data passed through the AddData method.
If there are no valid pixels, then NULL8 is returned.
Returns
Current minimum value in data set.
Exceptions
Isis::IException::Message The data set is blank, so the minimum is invalid.
References _FILEINFO_, Isis::NULL8, and Isis::IException::Programmer.
Referenced by Isis::Statistics::BestMaximum(), Isis::Statistics::BestMinimum(), Isis::IndependentCubeViewport::cubeDataChanged(), Isis::GaussianStretch::GaussianStretch(), Isis::ControlNetStatistics::GenerateControlNetStats(), Isis::VisualDisplay::paintPixmap(), Isis::SawtoothStretchType::SawtoothStretchType(), Isis::ScatterPlotData::ScatterPlotData(), Isis::HistogramWidget::setHistogram(), Isis::BinaryStretchType::setStretch(), Isis::StretchTool::stretchBuffer(), Isis::CameraStatistics::toPvl(), and Isis::Statistics::toPvl().
Mode()
double Isis::Histogram::Mode () const inherited
Returns the mode.
Returns
The mode
References Isis::NULL8.
Referenced by main().
NullPixels()
BigInt Isis::Statistics::NullPixels () const inherited
Returns the total number of NULL pixels encountered.
Returns
The number of NULL pixels (data) processed
Referenced by main(), and Isis::Statistics::toPvl().
OutOfRangePixels()
BigInt Isis::Statistics::OutOfRangePixels () const inherited
Returns the total number of pixels outside of the valid range encountered.
Returns
The number of Out of Range pixels (data) processed
OverRangePixels()
BigInt Isis::Statistics::OverRangePixels () const inherited
Returns the total number of pixels over the valid range encountered.
Returns
The number of pixels less than the ValidMaximum() processed
Referenced by Isis::Statistics::toPvl().
Percent()
double Isis::Histogram::Percent (const double percent) const inherited
Computes and returns the value at X percent of the histogram.
For example, Percent(50.0) is equivalent to the computing the median. While Percent(0.5) and Percent(99.5) would obtain a minimum and maximum for the data that could be used for a good contrast stretch.
Parameters
percent X percent of the histogram to compute.
Returns
The value at X percent of the histogram.
References _FILEINFO_, and Isis::NULL8.
Referenced by Isis::BinaryStretchType::BinaryStretchType(), Isis::IndependentCubeViewport::cubeDataChanged(), Isis::GaussianStretch::GaussianStretch(), Isis::Stretch::Parse(), Isis::ProcessExport::SetInputRange(), Isis::VisualDisplay::setPixelData(), Isis::StretchTool::stretchBand(), and Isis::StretchTool::stretchBuffer().
read()
QDataStream & Isis::Statistics::read (QDataStream & stream) inherited
Referenced by Isis::operator>>().
readStatistics()
void Isis::Statistics::readStatistics (QXmlStreamReader * xmlReader) inherited
References Isis::toBigInt(), Isis::toBool(), Isis::toDouble(), Isis::ValidMaximum, and Isis::ValidMinimum.
Referenced by Isis::Statistics::Statistics().
RemoveData() [1/2]
void Isis::ImageHistogram::RemoveData (const double * data, const unsigned int count) virtual
Remove an array of doubles from the histogram counters.
Note that this invalidates the absolute minimum and maximum. They will no longer be useable.
See also
Stats
Parameters
data Pointer to array of doubles to remove.
count number of doubles to process.
Reimplemented from Isis::Histogram.
References Isis::Histogram::BinRangeEnd(), Isis::Histogram::BinRangeStart(), Isis::IsValidPixel(), Isis::Histogram::p_bins, and Isis::Statistics::RemoveData().
RemoveData() [2/2]
void Isis::Statistics::RemoveData (const double data) inherited
References _FILEINFO_, Isis::Statistics::AboveRange(), Isis::Statistics::BelowRange(), Isis::IsHisPixel(), Isis::IsHrsPixel(), Isis::IsLisPixel(), Isis::IsLrsPixel(), Isis::IsNullPixel(), and Isis::IException::Programmer.
RemovedData()
bool Isis::Statistics::RemovedData () const inherited
Reset()
void Isis::Histogram::Reset () inherited
Resets histogram counters to zero.
Rms()
double Isis::Statistics::Rms () const inherited
Computes and returns the rms.
If there are no valid pixels, then NULL8 is returned.
Returns
The rms (root mean square)
References Isis::NULL8.
Referenced by Isis::ControlPoint::GetLineResidualRms(), Isis::ControlPoint::GetResidualRms(), Isis::ControlPoint::GetSampleResidualRms(), and Isis::BundleSolutionInfo::outputHeader().
save()
void Isis::Statistics::save (QXmlStreamWriter & stream, const Project * project) const inherited
References Isis::toString().
SetBins()
void Isis::Histogram::SetBins (const int bins) inherited
Change the number of bins in the histogram and reset counters.
SetValidRange()
void Isis::Histogram::SetValidRange (const double minimum = Isis::ValidMinimum, const double maximum = Isis::ValidMaximum) inherited
Changes the range of the bins.
This function also sets the range of the parent statistics class and resets the stats/histogram counters. So binRange = setValidRange. Should only be called once, prior to Adding data to the histogram.
Parameters
binStart The start of the bin range
binEnd The end of the bin range
References _FILEINFO_, and Isis::Statistics::SetValidRange().
Referenced by Isis::Cube::histogram().
Skew()
double Isis::Histogram::Skew () const inherited
Computes and returns the skew.
If there are no valid pixels then NULL8 is returned. Recognize that because of the binning which occurs, in order to generate the histogram, the skew may not be precise but will be very close.
Returns
The skew.
References Isis::NULL8.
StandardDeviation()
double Isis::Statistics::StandardDeviation () const inherited
Computes and returns the standard deviation.
If there are no valid pixels, then NULL8 is returned.
Returns
The standard deviation
References Isis::NULL8, and Isis::Statistics::Variance().
Referenced by Isis::Statistics::ChebyshevMaximum(), Isis::Statistics::ChebyshevMinimum(), Isis::MultivariateStatistics::Correlation(), Isis::StandardDeviationOperator::Interest(), main(), Isis::VisualDisplay::paintPixmap(), Isis::ReseauDistortionMap::SetFocalPlane(), Isis::ReseauDistortionMap::SetUndistortedFocalPlane(), Isis::CameraStatistics::toPvl(), Isis::Statistics::toPvl(), and Isis::Statistics::ZScore().
Sum()
double Isis::Statistics::Sum () const inherited
Returns the sum of all the data.
Returns
The sum of the data
Referenced by Isis::MultivariateStatistics::Covariance(), Isis::MultivariateStatistics::LinearRegression(), and Isis::Statistics::toPvl().
SumSquare()
double Isis::Statistics::SumSquare () const inherited
Returns the sum of all the squared data.
Returns
The sum of the squared data
Referenced by Isis::MultivariateStatistics::LinearRegression(), and Isis::Statistics::toPvl().
toPvl()
PvlGroup Isis::Statistics::toPvl (QString name = "Statistics") const inherited
Serialize statistics as a pvl group.
Parameters
QString name (Default value is "Statistics") - Name of the statistics group
Returns
PvlGroup Statistics information as a pvl group
References Isis::Statistics::Average(), Isis::Statistics::HisPixels(), Isis::Statistics::HrsPixels(), Isis::Statistics::LisPixels(), Isis::Statistics::LrsPixels(), Isis::Statistics::Maximum(), Isis::Statistics::Minimum(), Isis::Statistics::NullPixels(), Isis::Statistics::OverRangePixels(), Isis::Statistics::StandardDeviation(), Isis::Statistics::Sum(), Isis::Statistics::SumSquare(), Isis::toString(), Isis::Statistics::TotalPixels(), Isis::Statistics::UnderRangePixels(), Isis::Statistics::ValidMaximum(), Isis::Statistics::ValidMinimum(), Isis::Statistics::ValidPixels(), and Isis::Statistics::Variance().
Referenced by Isis::MultivariateStatistics::toPvl().
TotalPixels()
BigInt Isis::Statistics::TotalPixels () const inherited
Returns the total number of pixels processed (valid and invalid).
Returns
The number of pixels (data) processed
Referenced by main(), Isis::VisualDisplay::paintPixmap(), and Isis::Statistics::toPvl().
UnderRangePixels()
BigInt Isis::Statistics::UnderRangePixels () const inherited
Returns the total number of pixels under the valid range encountered.
Returns
The number of pixels less than the ValidMinimum() processed
Referenced by Isis::Statistics::toPvl().
ValidMaximum()
double Isis::Statistics::ValidMaximum () const inherited
Referenced by Isis::Statistics::toPvl().
ValidMinimum()
double Isis::Statistics::ValidMinimum () const inherited
Referenced by Isis::Statistics::toPvl().
ValidPixels()
BigInt Isis::Statistics::ValidPixels () const inherited
Returns the total number of valid pixels processed.
Only valid pixels are utilized when computing the average, standard deviation, variance, minimum and maximum.
Returns
The number of valid pixels (data) processed
Referenced by Isis::OverlapNormalization::AddOverlap(), Isis::IndependentCubeViewport::cubeDataChanged(), Isis::QHistogram::Load(), Isis::StretchTool::stretchBuffer(), Isis::Statistics::toPvl(), and Isis::StretchTool::updateHistograms().
Variance()
double Isis::Statistics::Variance () const inherited
Computes and returns the variance.
If there are no valid pixels, then NULL8 is returned.
Returns
The variance
References Isis::NULL8.
Referenced by Isis::Statistics::StandardDeviation(), and Isis::Statistics::toPvl().
write()
QDataStream & Isis::Statistics::write (QDataStream & stream) const inherited
Order saved must match the offsets in the static compoundH5DataType() method.
Referenced by Isis::operator<<().
ZScore()
double Isis::Statistics::ZScore (const double value) const inherited
This method returns the better of the z-score of the given value.
The z-score is the number of standard deviations the value lies above or below the average.
Parameters
value The value to calculate the z-score of.
Returns
z-score
References _FILEINFO_, Isis::Statistics::Average(), Isis::Statistics::Maximum(), Isis::IException::Programmer, Isis::Statistics::StandardDeviation(), and Isis::toString().
Member Data Documentation
p_bins
std::vector<BigInt> Isis::Histogram::p_bins protected inherited
The array of counts.
Referenced by AddData(), BinRange(), and RemoveData().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ImageHistogram/ImageHistogram.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ImageHistogram/ImageHistogram.cpp