Isis Developer Reference: Isis::TextFile Class Reference
Isis::TextFile Class Reference
Utility
Provides access to sequential ASCII stream I/O.
#include <TextFile.h>
Public Member Functions
TextFile ()
Constructs an empty TextFile object.
TextFile (const QString &filename, const char *openmode="input", const char *extension="")
Constructs a TextFile object and opens the specified file (including path).
TextFile (const char *filename, const char *openmode, std::vector< QString > &lines, const int &maxLinesToReadWrite=0, const bool skipComments=true)
Constructs a TextFile object and opens the specified file (including path), reads or writes file, leaves file open for further use of the rest of the methods.
TextFile (const QString &filename, const char *openmode, std::vector< QString > &lines, const int &maxLinesToReadWrite=0, const bool skipComments=true)
Constructs a TextFile object and opens the specified file (including path), reads or writes file, leaves file open for further use of the rest of the methods.
TextFile (const char *filename, const char *openmode, QString *lines, const int &maxLinesToReadWrite, const bool skipComments=true)
Constructs a TextFile object and opens the specified file (including path), reads or writes file, leaves file open for further use of the rest of the methods.
TextFile (const QString &filename, const char *openmode, QString *lines, const int &maxLinesToReadWrite, const bool skipComments=true)
Constructs a TextFile object and opens the specified file (including path), reads or writes file, leaves file open for further use of the rest of the methods.
~TextFile ()
Closes file (if still open). Destroys the TextFile object.
void Open (const QString &filename, const char *openmode="input", const char *extension="")
Opens a text file.
void Open (const char *filename, const char *openmode="input", const char *extension="")
bool OpenChk (bool bailIfNotOpen=false)
void Rewind ()
Sets Read / Write pointer to begining of opened file.
void Close ()
Closes file. Called automatically by TextFile destructor.
void GetFile (std::vector< QString > &lines, const int &maxLinesToRead=0, const bool skipComments=true)
void GetFile (QString *lines, const int &maxLinesToRead, const bool skipComments=true)
void PutFile (std::vector< QString > &lines, const int &maxLinesToWrite=0)
void PutFile (const QString *lines, const int &maxLinesToWrite)
bool GetLine (QString &line, const bool skipComments=true)
Gets next line from file.
bool GetLineNoFilter (QString &line)
Gets next NON-COMMENT line from file.
bool GetLine (const bool skipComments=true)
Gets next line from file.
bool GetLineNoFilter ()
Gets next NON-COMMENT line from file.
void PutLine (const QString &line)
Writes string to file and appends a 'newline' string.
void PutLine (const char *line="")
Writes char string to file and appends a 'newline' string.
void PutLineComment (const QString &line)
Writes string to file, prepends a 'comment' string and appends a 'newline' string.
void PutLineComment (const char *line="")
Writes char string to file, prepends a 'comment' string and appends a 'newline' string.
QString GetComment ()
QString GetNewLine ()
void SetComment (const char *commentString="#")
Sets the 'comment' string.
void SetNewLine (const char *newLineString="\n")
Sets the 'newline' string.
int LineCount (const int &maxLinesToRead=0)
Counts number of lines in file.
std::streamsize Size ()
Counts number of bytes in file.
Protected Member Functions
bool p_GetLine (QString &line, bool chkComment)
Gets next line from file.
Protected Attributes
std::fstream p_stream
File stream handle.
int p_openmode
openmode of file: Input, Output, Overwrite, Append
QString p_filename
FileName of the opened file.
QString p_commentString
'comment' string used by GetLine and PutLineComment
QString p_newLineString
'newline' string used by PutLine and PutLineComment
Detailed Description
Provides access to sequential ASCII stream I/O.
Provides access to sequential ASCII stream I/O. Checks for errors in opening, reading, and writing ASCII files. Can check for 'comment lines' while reading a text file.
Author
2003-08-29 Glenn Bennett
Constructor & Destructor Documentation
TextFile() [1/6]
Isis::TextFile::TextFile ()
Constructs an empty TextFile object.
TextFile() [2/6]
Isis::TextFile::TextFile (const QString & filename, const char * openmode = "input", const char * extension = "")
Constructs a TextFile object and opens the specified file (including path).
Parameters
filename FileName (including path) to be opened by TextFile object.
openmode Open Mode of file opened by TextFile object. InputOpens file for Input: Read Only, Fails if file does not exist OutputOpens file for Output: Read / Write - Creates file, Fails if file exists. OverwriteOpens file for Output: Read / Write - Creates file, Truncates if file exists. AppendOpens file for Append: Read / Write- Creates file, Appends if file exists. Defaults to "input"
extension Extension to be added to filename (added only if not already on filename). Defaults to ""
TextFile() [3/6]
Isis::TextFile::TextFile (const char * filename, const char * openmode, std::vector< QString > & lines, const int & maxLinesToReadWrite = 0, const bool skipComments = true)
Constructs a TextFile object and opens the specified file (including path), reads or writes file, leaves file open for further use of the rest of the methods.
Parameters
filename FileName (including path) to be opened by TextFile object.
openmode Open Mode of file opened by TextFile object. InputOpens file for Input: Read Only, Fails if file does not exist OutputOpens file for Output: Read / Write - Creates file, Fails if file exists. OverwriteOpens file for Output: Read / Write - Creates file, Truncates if file exists. AppendOpens file for Append: Read / Write - Creates file, Appends if file exists. Defaults to "input"
lines
maxLinesToReadWrite Limits the maximum lines read or written; 0=read entire file or write entire vectorDefaults to 0
skipComments Controls whether comments lines are filtered; true=filter, false=return any line read from fileDefaults to true
TextFile() [4/6]
Isis::TextFile::TextFile (const QString & filename, const char * openmode, std::vector< QString > & lines, const int & maxLinesToReadWrite = 0, const bool skipComments = true)
Constructs a TextFile object and opens the specified file (including path), reads or writes file, leaves file open for further use of the rest of the methods.
Parameters
filename FileName (including path) to be opened by TextFile object.
openmode Open Mode of file opened by TextFile object. InputOpens file for Input: Read Only, Fails if file does not exist OutputOpens file for Output: Read / Write - Creates file, Fails if file exists. OverwriteOpens file for Output: Read / Write - Creates file, Truncates if file exists. AppendOpens file for Append: Read / Write - Creates file, Appends if file exists. Defaults to "input"
lines IString Vector to fill if reading or put to file if writing
maxLinesToReadWrite Limits the maximum lines read or written; 0=read entire file or write entire vectorDefaults to 0
skipComments Controls whether comments lines are filtered; true=filter, false=return any line read from fileDefaults to true
TextFile() [5/6]
Isis::TextFile::TextFile (const char * filename, const char * openmode, QString * lines, const int & maxLinesToReadWrite, const bool skipComments = true)
Constructs a TextFile object and opens the specified file (including path), reads or writes file, leaves file open for further use of the rest of the methods.
Parameters
filename FileName (including path) to be opened by TextFile object.
openmode Open Mode of file opened by TextFile object. InputOpens file for Input: Read Only, Fails if file does not exist OutputOpens file for Output: Read / Write - Creates file, Fails if file exists. OverwriteOpens file for Output: Read / Write - Creates file, Truncates if file exists. AppendOpens file for Append: Read / Write - Creates file, Appends if file exists. Defaults to "input"
lines
maxLinesToReadWrite Limits the maximum lines read or written; 0=read entire file or write entire vectorDefaults to 0
skipComments Controls whether comments lines are filtered; true=filter, false=return any line read from fileDefaults to true
TextFile() [6/6]
Isis::TextFile::TextFile (const QString & filename, const char * openmode, QString * lines, const int & maxLinesToReadWrite, const bool skipComments = true)
Constructs a TextFile object and opens the specified file (including path), reads or writes file, leaves file open for further use of the rest of the methods.
Parameters
filename FileName (including path) to be opened by TextFile object.
openmode Open Mode of file opened by TextFile object. InputOpens file for Input: Read Only, Fails if file does not exist OutputOpens file for Output: Read / Write - Creates file, Fails if file exists. OverwriteOpens file for Output: Read / Write - Creates file, Truncates if file exists. AppendOpens file for Append: Read / Write - Creates file, Appends if file exists. Defaults to "input"
lines
maxLinesToReadWrite Limits the maximum lines read or written; 0=read entire file or write entire vectorDefaults to 0
skipComments Controls whether comments lines are filtered; true=filter, false=return any line read from fileDefaults to true
~TextFile()
Isis::TextFile::~TextFile ()
Closes file (if still open). Destroys the TextFile object.
Member Function Documentation
Close()
void Isis::TextFile::Close ()
Closes file. Called automatically by TextFile destructor.
Referenced by Isis::CisscalFile::~CisscalFile().
GetComment()
QString Isis::TextFile::GetComment ()
GetFile() [1/2]
void Isis::TextFile::GetFile (QString * lines, const int & maxLinesToRead, const bool skipComments = true)
GetFile() [2/2]
void Isis::TextFile::GetFile (std::vector< QString > & lines, const int & maxLinesToRead = 0, const bool skipComments = true)
GetLine() [1/2]
bool Isis::TextFile::GetLine (const bool skipComments = true)
Gets next line from file.
Returns True if read a line, False if End Of File.
Parameters
skipComments Controls whether comments lines are filtered; true=filter, false=return any line read from fileDefaults to true
Returns
bool
GetLine() [2/2]
bool Isis::TextFile::GetLine (QString & line, const bool skipComments = true)
Gets next line from file.
Returns True if read a line, False if End Of File.
Parameters
line Line read from file, with newline removed.
skipComments Controls whether comments lines are filtered; true=filter, false=return any line read from fileDefaults to true
Returns
bool
Referenced by Isis::Environment::isisVersion(), Isis::MosaicMainWindow::MosaicMainWindow(), Isis::MosaicMainWindow::openList(), Isis::ImportImagesWorkOrder::setupExecution(), and Isis::ImportShapesWorkOrder::setupExecution().
GetLineNoFilter() [1/2]
bool Isis::TextFile::GetLineNoFilter ()
Gets next NON-COMMENT line from file.
Returns True if read a line, False if End Of File. See SetComment method.
Returns
bool
GetLineNoFilter() [2/2]
bool Isis::TextFile::GetLineNoFilter (QString & line)
Gets next NON-COMMENT line from file.
Returns True if read a line, False if End Of File. See SetComment method.
Parameters
line Line read from file, with newline removed.
Returns
bool
GetNewLine()
QString Isis::TextFile::GetNewLine ()
LineCount()
int Isis::TextFile::LineCount (const int & maxLinesToRead = 0)
Counts number of lines in file.
Parameters
maxLinesToRead Limits lines counted - intended for large files. 0=count all lines. n=count up to and including n lines; if file longer than n lines, returns n+1. Defaults to 0
Returns
streamsize
Open() [1/2]
void Isis::TextFile::Open (const char * filename, const char * openmode = "input", const char * extension = "")
Open() [2/2]
void Isis::TextFile::Open (const QString & filename, const char * openmode = "input", const char * extension = "")
Opens a text file.
Parameters
filename FileName (including path) to be opened.
openmode Open Mode of file to be opened. There are four options, "input", "output", "overwrite", and "append". "input" opens with in fstream option, "output" opens with in, out, and trunc fstream options and verifies the file does not exist, "overwrite" opens with in, out, and trunc fstream options, and "append" opens with in, out, and ate(at end) fstream options, "append" will open with in and out options if the file does not exist.
extension Extension to be added to filename (added only if not already on filename). Defaults to ""
Exceptions
Isis::IException::Programmer
Isis::IException::Io - output file already exists
Isis::IException::Io - unable to open file
References _FILEINFO_, Isis::FileName::addExtension(), Isis::IString::DownCase(), Isis::FileName::expanded(), Isis::FileName::fileExists(), and Isis::FileName::toString().
OpenChk()
bool Isis::TextFile::OpenChk (bool bailIfNotOpen = false)
References _FILEINFO_.
Referenced by Isis::CisscalFile::p_GetLine().
p_GetLine()
bool Isis::TextFile::p_GetLine (QString & line, bool chkComment) protected
Gets next line from file.
Returns True if read a line, False if End Of File.
Parameters
line Line read from file, with newline removed.
chkComment True=Skip Comment Lines, False=Return All Lines.
Returns
bool
Exceptions
Isis::IException::Io - error reading text file
References _FILEINFO_.
PutFile() [1/2]
void Isis::TextFile::PutFile (const QString * lines, const int & maxLinesToWrite)
PutFile() [2/2]
void Isis::TextFile::PutFile (std::vector< QString > & lines, const int & maxLinesToWrite = 0)
PutLine() [1/2]
void Isis::TextFile::PutLine (const char * line = "")
Writes char string to file and appends a 'newline' string.
See SetNewLine method.
Parameters
line Char string to be written to file.Defaults to ""
Exceptions
Isis::IException::Io - error writing text to file
Isis::IException::Programmer - input is read only text file, cannot write to file
References _FILEINFO_.
PutLine() [2/2]
void Isis::TextFile::PutLine (const QString & line)
Writes string to file and appends a 'newline' string.
See SetNewLine method.
Parameters
line IString to be written to file. Defaults to ""
PutLineComment() [1/2]
void Isis::TextFile::PutLineComment (const char * line = "")
Writes char string to file, prepends a 'comment' string and appends a 'newline' string.
See SetComment method and SetNewLine method.
Parameters
line Char string to be written to file.Defaults to ""
PutLineComment() [2/2]
void Isis::TextFile::PutLineComment (const QString & line)
Writes string to file, prepends a 'comment' string and appends a 'newline' string.
See SetComment method and SetNewLine method.
Parameters
line IString to be written to file.Defaults to ""
Rewind()
void Isis::TextFile::Rewind ()
Sets Read / Write pointer to begining of opened file.
SetComment()
void Isis::TextFile::SetComment (const char * commentString = "#")
Sets the 'comment' string.
Default = '#' See ReadFilter method. Skips lines that begin with this string. See PutLineComment method. Prepends 'comment' string to output line.
Parameters
commentString The string of characters to be used for 'comment' lines. Defaults to "#"
SetNewLine()
void Isis::TextFile::SetNewLine (const char * newLineString = "\n")
Sets the 'newline' string.
Default = '
'. See PutLine and PutLineComment methods. Appends 'newline' string to output line.
Parameters
newLineString The string of characters to be used for 'comment' lines. Defaults to "\n"
Size()
streamsize Isis::TextFile::Size ()
Counts number of bytes in file.
Returns
streamsize
Member Data Documentation
p_commentString
QString Isis::TextFile::p_commentString protected
'comment' string used by GetLine and PutLineComment
p_filename
QString Isis::TextFile::p_filename protected
FileName of the opened file.
Referenced by Isis::CisscalFile::p_GetLine().
p_newLineString
QString Isis::TextFile::p_newLineString protected
'newline' string used by PutLine and PutLineComment
p_openmode
int Isis::TextFile::p_openmode protected
openmode of file: Input, Output, Overwrite, Append
p_stream
std::fstream Isis::TextFile::p_stream protected
File stream handle.
Referenced by Isis::CisscalFile::p_GetLine().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/TextFile/TextFile.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/TextFile/TextFile.cpp