Isis Developer Reference: Isis::Application Class Reference
Isis::Application Class Reference
#include <Application.h>
Public Member Functions
Application (int &argc, char *argv[])
Constuctor for the Application object.
~Application ()
Destroys the Application object.
int Run (void(*funct)())
Runs the program defined in the function funct.
PvlGroup Accounting ()
Creates accounting PvlGroup.
PvlObject History ()
Creates an application history PvlObject.
void RegisterGuiHelpers (std::map< QString, void * > helpers)
void * GetGuiHelper (QString helper)
void GuiReportError (IException &e)
Loads the error message into the gui, but does not write it to the session log.
Static Public Member Functions
static UserInterface & GetUserInterface ()
Returns the UserInterface object.
static void Log (PvlGroup &results)
Writes Pvl results to sessionlog and printfile.
static void AppendAndLog (PvlGroup &results, Pvl *log)
Writes the pvl group results to both a passed in Pvl log and the applications log (either GUI or command line)
static void GuiLog (const Pvl &results)
Writes the Pvl results to the sessionlog, but not to the printfile.
static void GuiLog (const PvlGroup &results)
Writes the PvlGroup results to the sessionlog, but not to the printfile.
static void GuiLog (const QString &results)
Writes the results to the sessionlog, but not to the printfile.
static QString Name ()
Returns the name of the application.
static QString formatError (IException &e)
static QString UserName ()
Returns the user name.
static QString HostName ()
Returns the host name.
static QString DateTime (time_t *curtime=0)
Returns the date and time as a QString.
static QString Version ()
The Isis Version for this application.
static bool HasParent ()
Returns whether the application has a parent or not.
static QString userName ()
@Returns the user name.
static QString hostName ()
static QString isisVersion ()
static QString getEnvironmentValue (QString, QString)
Static Public Attributes
static bool p_applicationForceGuiApp = false
Friends
class Gui
class Progress
class ProgramLauncher
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
Application()
Isis::Application::Application (int & argc, char * argv[])
Constuctor for the Application object.
Parameters
argc Number of arguments in argv[]. This must be passed by reference!!
*argv[] An array containing the command line arguments
Exceptions
Isis::iException::Io - FileOpen error
References _FILEINFO_, Isis::IException::errorType(), Isis::FileName::expanded(), Isis::FileName::fileExists(), Isis::Message::FileOpen(), GetUserInterface(), Isis::iApp, Isis::FileName::name(), Isis::UserInterface::ParentId(), Isis::IException::print(), and Isis::toString().
~Application()
Isis::Application::~Application ()
Destroys the Application object.
Member Function Documentation
Accounting()
PvlGroup Isis::Application::Accounting ()
Creates accounting PvlGroup.
Returns
PvlGroup Accounting Group
AppendAndLog()
void Isis::Application::AppendAndLog (PvlGroup & results, Pvl * log) static
Writes the pvl group results to both a passed in Pvl log and the applications log (either GUI or command line)
Parameters
results Pvl containing the results to add to the session log
log App log for running in code
References Isis::PvlObject::addGroup().
DateTime()
QString Isis::Application::DateTime (time_t * curtime = 0) static
Returns the date and time as a QString.
Parameters
*curtime
Returns
QString The date and time
Referenced by Isis::ControlPoint::GetDateTime().
formatError()
QString Isis::Application::formatError (IException & e) static
References Isis::PvlObject::group(), Isis::PvlObject::groups(), Isis::PvlContainer::isNamed(), and Isis::IException::toString().
getEnvironmentValue()
QString Isis::Environment::getEnvironmentValue (QString variable, QString defaultValue) static inherited
Parameters
variable The environment variable to get
defaultValue The returned value for variable if variable doesn't exist.
Returns
The value for the environment variable requested.
Referenced by Isis::Environment::Environment(), Isis::Environment::hostName(), QStartup(), and Isis::Environment::userName().
GetGuiHelper()
void* Isis::Application::GetGuiHelper (QString helper) inline
Parameters
helper
GetUserInterface()
Isis::UserInterface & Isis::Application::GetUserInterface () static
Returns the UserInterface object.
Returns
A pointer to the UserInterface object
References Isis::iApp.
Referenced by Isis::PipelineApplication::AddParameter(), Application(), GuiLog(), Log(), Isis::Pipeline::SetInputFile(), Isis::Pipeline::SetInputListFile(), Isis::ProcessExport::SetInputRange(), Isis::ProcessImport::SetOutputCube(), Isis::Pipeline::SetOutputFile(), Isis::Pipeline::SetOutputListFile(), and Isis::Gui::ShowWarning().
GuiLog() [1/3]
void Isis::Application::GuiLog (const Pvl & results) static
Writes the Pvl results to the sessionlog, but not to the printfile.
Parameters
results Pvl containing the results to add to the session log
References GetUserInterface(), Isis::iApp, Isis::UserInterface::IsInteractive(), Isis::Gui::Log(), Isis::Gui::ShowLog(), and Isis::UserInterface::TheGui().
GuiLog() [2/3]
void Isis::Application::GuiLog (const PvlGroup & results) static
Writes the PvlGroup results to the sessionlog, but not to the printfile.
Parameters
results PvlGroup containing the results to add to the session log
References GetUserInterface(), Isis::iApp, Isis::UserInterface::IsInteractive(), Isis::Gui::Log(), Isis::Gui::ShowLog(), and Isis::UserInterface::TheGui().
GuiLog() [3/3]
void Isis::Application::GuiLog (const QString & results) static
Writes the results to the sessionlog, but not to the printfile.
Parameters
results QString containing the results to add to the session log
References GetUserInterface(), Isis::iApp, Isis::UserInterface::IsInteractive(), Isis::Gui::Log(), Isis::Gui::ShowLog(), and Isis::UserInterface::TheGui().
GuiReportError()
void Isis::Application::GuiReportError (IException & e)
Loads the error message into the gui, but does not write it to the session log.
Parameters
e The Isis::iException
HasParent()
bool Isis::Application::HasParent () static
Returns whether the application has a parent or not.
Returns
bool Returns true if it has a parent, and false if it does not
References Isis::iApp, and Isis::UserInterface::ParentId().
History()
PvlObject Isis::Application::History ()
Creates an application history PvlObject.
Returns
PvlObject
References Isis::PvlObject::addGroup(), and Isis::PvlObject::findGroup().
Referenced by Isis::History::AddEntry().
HostName()
QString Isis::Application::HostName () static
Returns the host name.
Returns 'Unknown' if it cannot find the host name.
Returns
QString Host Name
hostName()
QString Isis::Environment::hostName () static inherited
Returns
the host name. Returns 'Unknown' if it cannot find the host name.
References Isis::Environment::getEnvironmentValue().
isisVersion()
QString Isis::Environment::isisVersion () static inherited
Returns
the Isis version in the format isis?.?.?.?qualifier | date
References _FILEINFO_, Isis::TextFile::GetLine(), and Isis::IException::Programmer.
Log()
void Isis::Application::Log (PvlGroup & results) static
Writes Pvl results to sessionlog and printfile.
Parameters
results PvlGroup of results to add to the session log
References GetUserInterface(), Isis::iApp, Isis::UserInterface::IsInteractive(), Isis::Gui::Log(), Isis::Gui::ShowLog(), and Isis::UserInterface::TheGui().
Name()
QString Isis::Application::Name () static
Returns the name of the application.
Returns 'Unknown' if the application or gui equal NULL
Returns
QString The application name
Referenced by Isis::ControlPoint::GetChooserName(), Isis::Pipeline::Run(), and Isis::IException::toPvl().
RegisterGuiHelpers()
void Isis::Application::RegisterGuiHelpers (std::map< QString, void * > helpers) inline
Parameters
helpers
Referenced by main().
Run()
int Isis::Application::Run (void(*)() funct)
Runs the program defined in the function funct.
Parameters
*funct
Returns
int Status of the function execution
References _FILEINFO_, and Isis::IException::what().
Referenced by main().
UserName()
QString Isis::Application::UserName () static
Returns the user name.
Returns 'Unknown' if it cannot find the user name.
Returns
QString User Name
Referenced by Isis::ControlPointEditWidget::createControlPoint(), Isis::QnetTool::createFixedPoint(), Isis::QnetTool::createPoint(), Isis::StereoTool::createPoint(), Isis::MatchTool::createPoint(), Isis::QnetFileTool::open(), and Isis::SocketThread::run().
userName()
QString Isis::Environment::userName () static inherited
@Returns the user name.
Returns 'Unknown' if it cannot find the user name.
References Isis::Environment::getEnvironmentValue().
Referenced by Isis::Project::clear(), and Isis::Project::Project().
Version()
QString Isis::Application::Version () static
The Isis Version for this application.
Returns
QString
Friends And Related Function Documentation
Gui
friend class Gui friend
ProgramLauncher
friend class ProgramLauncher friend
Progress
friend class Progress friend
Member Data Documentation
p_applicationForceGuiApp
bool Isis::Application::p_applicationForceGuiApp = false static
Referenced by main().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Application/Application.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Application/Application.cpp