Isis Developer Reference: Isis::Statistics Class Reference
Isis::Statistics Class Reference
Math | Statistics
This class is used to accumulate statistics on double arrays.
#include <Statistics.h>
Public Member Functions
Statistics (QObject *parent=0)
Constructs an IsisStats object with accumulators and counters set to zero.
Statistics (QXmlStreamReader *xmlReader, QObject *parent=0)
void readStatistics (QXmlStreamReader *xmlReader)
Statistics (const PvlGroup &inStats, QObject *parent=0)
Constructs a Statistics object from an input Pvl.
Statistics (const Statistics &other)
virtual ~Statistics ()
Destroys the IsisStats object.
Statistics & operator= (const Statistics &other)
void Reset ()
Reset all accumulators and counters to zero.
void AddData (const double *data, const unsigned int count)
Add an array of doubles to the accumulators and counters.
void AddData (const double data)
Add a double to the accumulators and counters.
void RemoveData (const double *data, const unsigned int count)
Remove an array of doubles from the accumulators and counters.
void RemoveData (const double data)
void SetValidRange (const double minimum=Isis::ValidMinimum, const double maximum=Isis::ValidMaximum)
double ValidMinimum () const
double ValidMaximum () const
bool InRange (const double value)
bool AboveRange (const double value)
bool BelowRange (const double value)
double Average () const
Computes and returns the average.
double StandardDeviation () const
Computes and returns the standard deviation.
double Variance () const
Computes and returns the variance.
double Sum () const
Returns the sum of all the data.
double SumSquare () const
Returns the sum of all the squared data.
double Rms () const
Computes and returns the rms.
double Minimum () const
Returns the absolute minimum double found in all data passed through the AddData method.
double Maximum () const
Returns the absolute maximum double found in all data passed through the AddData method.
double ChebyshevMinimum (const double percent=99.5) const
This method returns a minimum such that X percent of the data will fall with K standard deviations of the average (Chebyshev's Theorem).
double ChebyshevMaximum (const double percent=99.5) const
This method returns a maximum such that X percent of the data will fall with K standard deviations of the average (Chebyshev's Theorem).
double BestMinimum (const double percent=99.5) const
This method returns the better of the absolute minimum or the Chebyshev minimum.
double BestMaximum (const double percent=99.5) const
This method returns the better of the absolute maximum or the Chebyshev maximum.
double ZScore (const double value) const
This method returns the better of the z-score of the given value.
BigInt TotalPixels () const
Returns the total number of pixels processed (valid and invalid).
BigInt ValidPixels () const
Returns the total number of valid pixels processed.
BigInt OverRangePixels () const
Returns the total number of pixels over the valid range encountered.
BigInt UnderRangePixels () const
Returns the total number of pixels under the valid range encountered.
BigInt NullPixels () const
Returns the total number of NULL pixels encountered.
BigInt LisPixels () const
Returns the total number of low instrument saturation (LIS) pixels encountered.
BigInt LrsPixels () const
Returns the total number of low representation saturation (LRS) pixels encountered.
BigInt HisPixels () const
Returns the total number of high instrument saturation (HIS) pixels encountered.
BigInt HrsPixels () const
Returns the total number of high representation saturation (HRS) pixels encountered.
BigInt OutOfRangePixels () const
Returns the total number of pixels outside of the valid range encountered.
bool RemovedData () const
PvlGroup toPvl (QString name="Statistics") const
Serialize statistics as a pvl group.
void save (QXmlStreamWriter &stream, const Project *project) const
QDataStream & write (QDataStream &stream) const
Order saved must match the offsets in the static compoundH5DataType() method.
QDataStream & read (QDataStream &stream)
Detailed Description
This class is used to accumulate statistics on double arrays.
This class is used to accumulate statistics on double arrays. In particular, it is highly useful for obtaining statistics on cube data. Parameters which can be computed are 1) average, 2) standard deviation, 3) variance, 4) minimum, 5) maximum and 6) various counts of valid and/or special pixels.
The following example shows a simple set up and usage of the Statistics class to calculate the average of a set of values:
Statistics myStats ;
double myData [] = { 1.0, 3.0, 2.4, 7.5 } ;
myStats.AddData (myData, 4) ;
double myAverage = myStats.Average () ;
cout << "The average of the data is " << myAverage << endl ;
For an example of how the Statistics object is used in Isis, see the Histogram object (inherits from Statistics) and the stats application, stats.cpp (uses the Statistics child class Histogram).
Author
2002-05-06 Jeff Anderson
Constructor & Destructor Documentation
Statistics() [1/4]
Isis::Statistics::Statistics (QObject * parent = 0)
Constructs an IsisStats object with accumulators and counters set to zero.
References Reset(), and SetValidRange().
Statistics() [2/4]
Isis::Statistics::Statistics (QXmlStreamReader * xmlReader, QObject * parent = 0)
References readStatistics(), Reset(), and SetValidRange().
Statistics() [3/4]
Isis::Statistics::Statistics (const PvlGroup & inStats, QObject * parent = 0)
Constructs a Statistics object from an input Pvl.
Parameters
const PvlGroup & - The input statistics
References Reset(), and SetValidRange().
Statistics() [4/4]
Isis::Statistics::Statistics (const Statistics & other)
~Statistics()
Isis::Statistics::~Statistics () virtual
Destroys the IsisStats object.
Member Function Documentation
AboveRange()
bool Isis::Statistics::AboveRange (const double value)
Referenced by AddData(), InRange(), and RemoveData().
AddData() [1/2]
void Isis::Statistics::AddData (const double * data, const unsigned int count)
Add an array of doubles to the accumulators and counters.
This method can be invoked multiple times (for example: once for each line in a cube) before obtaining statistics.
Parameters
data The data to be added to the data set used for statistical calculations.
count The number of elements in the incoming data to be added.
Referenced by Isis::ImageHistogram::AddData(), Isis::MultivariateStatistics::AddData(), Isis::HiEqualization::HiCalculateFunctor::addStats(), Isis::CameraStatistics::addStats(), Isis::averageLines(), Isis::averageSamples(), Isis::Process::CalculateStatistics(), Isis::IndependentCubeViewport::cubeDataChanged(), Isis::GainLineStat(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlPoint::GetLineResidualRms(), Isis::ControlPoint::GetResidualRms(), Isis::ControlPoint::GetSampleResidualRms(), Isis::ControlPoint::GetStatistic(), Isis::ZeroBufferFit::guess(), Isis::StandardDeviationOperator::Interest(), Isis::BundleSolutionInfo::outputHeader(), Isis::ControlPointGraphicsItem::paint(), Isis::AutoReg::Reduce(), Isis::ReseauDistortionMap::SetFocalPlane(), Isis::VisualDisplay::setPixelData(), Isis::ReseauDistortionMap::SetUndistortedFocalPlane(), Isis::Chip::Statistics(), Isis::Cube::statistics(), Isis::StretchTool::statsFromBuffer(), and Isis::StretchTool::statsFromCube().
AddData() [2/2]
void Isis::Statistics::AddData (const double data)
Add a double to the accumulators and counters.
This method can be invoked multiple times (for example: once for each pixel in a cube) before obtaining statistics.
Parameters
data The data to be added to the data set used for statistical calculations.
References AboveRange(), BelowRange(), Isis::IsHisPixel(), Isis::IsHrsPixel(), Isis::IsLisPixel(), Isis::IsLrsPixel(), and Isis::IsNullPixel().
Average()
double Isis::Statistics::Average () const
Computes and returns the average.
If there are no valid pixels, then NULL8 is returned.
Returns
The Average
References Isis::NULL8.
Referenced by Isis::OverlapNormalization::AddOverlap(), Isis::averageLines(), Isis::ControlNet::AverageResidual(), Isis::averageSamples(), ChebyshevMaximum(), ChebyshevMinimum(), Isis::MultivariateStatistics::Covariance(), Isis::ControlNetStatistics::GenerateControlNetStats(), Isis::ZeroBufferFit::guess(), main(), Isis::ControlPointGraphicsItem::paint(), Isis::VisualDisplay::paintPixmap(), Isis::AutoReg::Reduce(), Isis::CameraStatistics::toPvl(), toPvl(), and ZScore().
BelowRange()
bool Isis::Statistics::BelowRange (const double value)
Referenced by AddData(), InRange(), and RemoveData().
BestMaximum()
double Isis::Statistics::BestMaximum (const double percent = 99.5) const
This method returns the better of the absolute maximum or the Chebyshev maximum.
The better value is considered the value closest to the mean.
Parameters
percent The probability that the maximum is within K standard deviations of the mean (Used to compute the Chebyshev maximum). Default value = 99.5.
Returns
Best of absolute and Chebyshev maximums
See also
Statistics::Maximum Statistics::ChebyshevMaximum
References ChebyshevMaximum(), Maximum(), Minimum(), and Isis::NULL8.
Referenced by Isis::IndependentCubeViewport::cubeDataChanged(), Isis::StretchTool::histFromBuffer(), Isis::VisualDisplay::setPixelData(), Isis::LinearStretchType::setStretch(), Isis::StretchTool::stretchBand(), and Isis::StretchTool::stretchBuffer().
BestMinimum()
double Isis::Statistics::BestMinimum (const double percent = 99.5) const
This method returns the better of the absolute minimum or the Chebyshev minimum.
The better value is considered the value closest to the mean.
Parameters
percent The probability that the minimum is within K standard deviations of the mean (Used to compute the Chebyshev minimum). Default value = 99.5.
Returns
Best of absolute and Chebyshev minimums
See also
Statistics::Minimum Statistics::ChebyshevMinimum
References ChebyshevMinimum(), Maximum(), Minimum(), and Isis::NULL8.
Referenced by Isis::IndependentCubeViewport::cubeDataChanged(), Isis::StretchTool::histFromBuffer(), Isis::VisualDisplay::setPixelData(), Isis::LinearStretchType::setStretch(), Isis::StretchTool::stretchBand(), and Isis::StretchTool::stretchBuffer().
ChebyshevMaximum()
double Isis::Statistics::ChebyshevMaximum (const double percent = 99.5) const
This method returns a maximum such that X percent of the data will fall with K standard deviations of the average (Chebyshev's Theorem).
It can be used to obtain a minimum that does not include statistical outliers.
Parameters
percent The probability that the maximum is within K standard deviations of the mean. Default value = 99.5.
Returns
maximum value excluding statistical outliers
Exceptions
Isis::IException::Message
References _FILEINFO_, Average(), Isis::NULL8, Isis::IException::Programmer, and StandardDeviation().
Referenced by BestMaximum().
ChebyshevMinimum()
double Isis::Statistics::ChebyshevMinimum (const double percent = 99.5) const
This method returns a minimum such that X percent of the data will fall with K standard deviations of the average (Chebyshev's Theorem).
It can be used to obtain a minimum that does not include statistical outliers.
Parameters
percent The probability that the minimum is within K standard deviations of the mean. Default value = 99.5.
Returns
Minimum value (excluding statistical outliers)
Exceptions
Isis::IException::Message
References _FILEINFO_, Average(), Isis::NULL8, Isis::IException::Programmer, and StandardDeviation().
Referenced by BestMinimum().
HisPixels()
BigInt Isis::Statistics::HisPixels () const
Returns the total number of high instrument saturation (HIS) pixels encountered.
Returns
The number of HIS pixels (data) processed
Referenced by toPvl().
HrsPixels()
BigInt Isis::Statistics::HrsPixels () const
Returns the total number of high representation saturation (HRS) pixels encountered.
Returns
The number of HRS pixels (data) processed
Referenced by toPvl().
InRange()
bool Isis::Statistics::InRange (const double value)
References AboveRange(), and BelowRange().
Referenced by Isis::ImageHistogram::AddData().
LisPixels()
BigInt Isis::Statistics::LisPixels () const
Returns the total number of low instrument saturation (LIS) pixels encountered.
Returns
The number of LIS pixels (data) processed
Referenced by toPvl().
LrsPixels()
BigInt Isis::Statistics::LrsPixels () const
Returns the total number of low representation saturation (LRS) pixels encountered.
Returns
The number of LRS pixels (data) processed
Referenced by toPvl().
Maximum()
double Isis::Statistics::Maximum () const
Returns the absolute maximum double found in all data passed through the AddData method.
If there are no valid pixels, then NULL8 is returned.
Returns
Current maximum value in data set
Exceptions
Isis::IException::Message The data set is blank, so the maximum is invalid.
References _FILEINFO_, Isis::NULL8, and Isis::IException::Programmer.
Referenced by BestMaximum(), BestMinimum(), Isis::IndependentCubeViewport::cubeDataChanged(), Isis::QnetPointJigsawErrorFilter::filter(), Isis::QnetPointRegistrationErrorFilter::filter(), Isis::GaussianStretch::GaussianStretch(), Isis::ControlNetStatistics::GenerateControlNetStats(), Isis::ControlNet::GetMaximumResidual(), Isis::ControlPointGraphicsItem::paint(), Isis::VisualDisplay::paintPixmap(), Isis::SawtoothStretchType::SawtoothStretchType(), Isis::ScatterPlotData::ScatterPlotData(), Isis::HistogramWidget::setHistogram(), Isis::BinaryStretchType::setStretch(), Isis::StretchTool::stretchBuffer(), Isis::CameraStatistics::toPvl(), toPvl(), and ZScore().
Minimum()
double Isis::Statistics::Minimum () const
Returns the absolute minimum double found in all data passed through the AddData method.
If there are no valid pixels, then NULL8 is returned.
Returns
Current minimum value in data set.
Exceptions
Isis::IException::Message The data set is blank, so the minimum is invalid.
References _FILEINFO_, Isis::NULL8, and Isis::IException::Programmer.
Referenced by BestMaximum(), BestMinimum(), Isis::IndependentCubeViewport::cubeDataChanged(), Isis::GaussianStretch::GaussianStretch(), Isis::ControlNetStatistics::GenerateControlNetStats(), Isis::VisualDisplay::paintPixmap(), Isis::SawtoothStretchType::SawtoothStretchType(), Isis::ScatterPlotData::ScatterPlotData(), Isis::HistogramWidget::setHistogram(), Isis::BinaryStretchType::setStretch(), Isis::StretchTool::stretchBuffer(), Isis::CameraStatistics::toPvl(), and toPvl().
NullPixels()
BigInt Isis::Statistics::NullPixels () const
Returns the total number of NULL pixels encountered.
Returns
The number of NULL pixels (data) processed
Referenced by main(), and toPvl().
operator=()
Statistics & Isis::Statistics::operator= (const Statistics & other)
OutOfRangePixels()
BigInt Isis::Statistics::OutOfRangePixels () const
Returns the total number of pixels outside of the valid range encountered.
Returns
The number of Out of Range pixels (data) processed
OverRangePixels()
BigInt Isis::Statistics::OverRangePixels () const
Returns the total number of pixels over the valid range encountered.
Returns
The number of pixels less than the ValidMaximum() processed
Referenced by toPvl().
read()
QDataStream & Isis::Statistics::read (QDataStream & stream)
Referenced by Isis::operator>>().
readStatistics()
void Isis::Statistics::readStatistics (QXmlStreamReader * xmlReader)
References Isis::toBigInt(), Isis::toBool(), Isis::toDouble(), Isis::ValidMaximum, and Isis::ValidMinimum.
Referenced by Statistics().
RemoveData() [1/2]
void Isis::Statistics::RemoveData (const double * data, const unsigned int count)
Remove an array of doubles from the accumulators and counters.
Note that is invalidates the absolute minimum and maximum. They will no longer be usable.
Parameters
data The data to be removed from data set used for statistical calculations.
count The number of elements in the data to be removed.
Exceptions
IException::Message RemoveData is trying to remove data that doesn't exist.
Referenced by Isis::ImageHistogram::RemoveData(), and Isis::MultivariateStatistics::RemoveData().
RemoveData() [2/2]
void Isis::Statistics::RemoveData (const double data)
References _FILEINFO_, AboveRange(), BelowRange(), Isis::IsHisPixel(), Isis::IsHrsPixel(), Isis::IsLisPixel(), Isis::IsLrsPixel(), Isis::IsNullPixel(), and Isis::IException::Programmer.
RemovedData()
bool Isis::Statistics::RemovedData () const
Reset()
void Isis::Statistics::Reset ()
Reset all accumulators and counters to zero.
Referenced by Isis::ZeroBufferFit::guess(), Isis::AutoReg::Reduce(), Isis::MultivariateStatistics::Reset(), Isis::VisualDisplay::setLines(), Isis::VisualDisplay::setPixelData(), Isis::VisualDisplay::setSamples(), and Statistics().
Rms()
double Isis::Statistics::Rms () const
Computes and returns the rms.
If there are no valid pixels, then NULL8 is returned.
Returns
The rms (root mean square)
References Isis::NULL8.
Referenced by Isis::ControlPoint::GetLineResidualRms(), Isis::ControlPoint::GetResidualRms(), Isis::ControlPoint::GetSampleResidualRms(), and Isis::BundleSolutionInfo::outputHeader().
save()
void Isis::Statistics::save (QXmlStreamWriter & stream, const Project * project) const
References Isis::toString().
SetValidRange()
void Isis::Statistics::SetValidRange (const double minimum = Isis::ValidMinimum, const double maximum = Isis::ValidMaximum)
References _FILEINFO_, Isis::IException::Programmer, and Isis::toString().
Referenced by Isis::StandardDeviationOperator::Interest(), Isis::Histogram::SetValidRange(), Isis::Chip::Statistics(), Isis::Cube::statistics(), and Statistics().
StandardDeviation()
double Isis::Statistics::StandardDeviation () const
Computes and returns the standard deviation.
If there are no valid pixels, then NULL8 is returned.
Returns
The standard deviation
References Isis::NULL8, and Variance().
Referenced by ChebyshevMaximum(), ChebyshevMinimum(), Isis::MultivariateStatistics::Correlation(), Isis::StandardDeviationOperator::Interest(), main(), Isis::VisualDisplay::paintPixmap(), Isis::ReseauDistortionMap::SetFocalPlane(), Isis::ReseauDistortionMap::SetUndistortedFocalPlane(), Isis::CameraStatistics::toPvl(), toPvl(), and ZScore().
Sum()
double Isis::Statistics::Sum () const
Returns the sum of all the data.
Returns
The sum of the data
Referenced by Isis::MultivariateStatistics::Covariance(), Isis::MultivariateStatistics::LinearRegression(), and toPvl().
SumSquare()
double Isis::Statistics::SumSquare () const
Returns the sum of all the squared data.
Returns
The sum of the squared data
Referenced by Isis::MultivariateStatistics::LinearRegression(), and toPvl().
toPvl()
PvlGroup Isis::Statistics::toPvl (QString name = "Statistics") const
Serialize statistics as a pvl group.
Parameters
QString name (Default value is "Statistics") - Name of the statistics group
Returns
PvlGroup Statistics information as a pvl group
References Average(), HisPixels(), HrsPixels(), LisPixels(), LrsPixels(), Maximum(), Minimum(), NullPixels(), OverRangePixels(), StandardDeviation(), Sum(), SumSquare(), Isis::toString(), TotalPixels(), UnderRangePixels(), ValidMaximum(), ValidMinimum(), ValidPixels(), and Variance().
Referenced by Isis::MultivariateStatistics::toPvl().
TotalPixels()
BigInt Isis::Statistics::TotalPixels () const
Returns the total number of pixels processed (valid and invalid).
Returns
The number of pixels (data) processed
Referenced by main(), Isis::VisualDisplay::paintPixmap(), and toPvl().
UnderRangePixels()
BigInt Isis::Statistics::UnderRangePixels () const
Returns the total number of pixels under the valid range encountered.
Returns
The number of pixels less than the ValidMinimum() processed
Referenced by toPvl().
ValidMaximum()
double Isis::Statistics::ValidMaximum () const
Referenced by toPvl().
ValidMinimum()
double Isis::Statistics::ValidMinimum () const
Referenced by toPvl().
ValidPixels()
BigInt Isis::Statistics::ValidPixels () const
Returns the total number of valid pixels processed.
Only valid pixels are utilized when computing the average, standard deviation, variance, minimum and maximum.
Returns
The number of valid pixels (data) processed
Referenced by Isis::OverlapNormalization::AddOverlap(), Isis::IndependentCubeViewport::cubeDataChanged(), Isis::QHistogram::Load(), Isis::StretchTool::stretchBuffer(), toPvl(), and Isis::StretchTool::updateHistograms().
Variance()
double Isis::Statistics::Variance () const
Computes and returns the variance.
If there are no valid pixels, then NULL8 is returned.
Returns
The variance
References Isis::NULL8.
Referenced by StandardDeviation(), and toPvl().
write()
QDataStream & Isis::Statistics::write (QDataStream & stream) const
Order saved must match the offsets in the static compoundH5DataType() method.
Referenced by Isis::operator<<().
ZScore()
double Isis::Statistics::ZScore (const double value) const
This method returns the better of the z-score of the given value.
The z-score is the number of standard deviations the value lies above or below the average.
Parameters
value The value to calculate the z-score of.
Returns
z-score
References _FILEINFO_, Average(), Maximum(), Isis::IException::Programmer, StandardDeviation(), and Isis::toString().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Statistics/Statistics.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Statistics/Statistics.cpp