Isis Developer Reference: Isis::PanTool Class Reference
Isis::PanTool Class Reference
#include <PanTool.h>
Public Slots
void activate (bool)
Activates the tool.
virtual void updateTool ()
Updates the tool.
void setCubeViewport (MdiCubeViewport *cvp)
Sets the current viewport to the given cvp.
Signals
void clearWarningSignal ()
void toolActivated ()
void viewportChanged ()
Public Member Functions
PanTool (QWidget *parent)
void addTo (QMenu *)
QString menuName () const
Anytime a tool is created, you must give it a name for the menu.
void addTo (ViewportMainWindow *mw)
Adds the tool to the application.
void addTo (ToolPad *toolpad)
Adds the tool to the toolpad.
virtual void addTo (Workspace *ws)
Adds the given workspace to the cubeviewport list.
virtual void addToPermanent (QToolBar *toolbar)
void addToActive (QToolBar *toolbar)
QString toolIconDir () const
returns the path to the icon directory.
virtual void paintViewport (MdiCubeViewport *vp, QPainter *painter)
RubberBandTool * rubberBandTool ()
void setList (ToolList *currentList)
Protected Types
typedef QVector< MdiCubeViewport * > CubeViewportList
A list of cubeviewports.
Protected Slots
void mouseButtonPress (QPoint p, Qt::MouseButton s)
void mouseMove (QPoint p)
void mouseButtonRelease (QPoint p, Qt::MouseButton s)
virtual void rubberBandComplete ()
virtual void screenPixelsChanged ()
This is called when actions change which pixels from the cube are displayed.
virtual void mouseEnter ()
virtual void mouseMove (QPoint p, Qt::MouseButton)
virtual void mouseLeave ()
Protected Member Functions
QAction * toolPadAction (ToolPad *pad)
Anytime a tool is created, you must setup a tool pad action with it.
QWidget * createToolBarWidget (QStackedWidget *parent)
Anytime a tool is created, you must add it to the tool bar.
virtual void mouseDoubleClick (QPoint p)
virtual void updateMeasure ()
virtual void scaleChanged ()
virtual void stretchRequested (MdiCubeViewport *, int)
void registerTool (MdiCubeViewport *viewport)
Registers the tool to the viewport.
MdiCubeViewport * cubeViewport () const
Return the current cubeviewport.
CubeViewportList * cubeViewportList () const
Return the list of cubeviewports.
virtual void addConnections (MdiCubeViewport *cvp)
Anytime a tool is created, you must add the connections for it.
virtual void removeConnections (MdiCubeViewport *cvp)
Anytime a tool is created, you must be able to remove it's connections.
virtual void enableRubberBandTool ()
Anytime a tool is created, you may use the rubber band tool.
Workspace * workspace ()
Detailed Description
Author
????-??-?? Unknown
Member Typedef Documentation
CubeViewportList
typedef QVector< MdiCubeViewport * > Isis::Tool::CubeViewportList protected inherited
A list of cubeviewports.
Constructor & Destructor Documentation
PanTool()
Isis::PanTool::PanTool (QWidget * parent)
References Isis::Tool::toolIconDir().
Member Function Documentation
activate
void Isis::Tool::activate (bool on) slot inherited
Activates the tool.
Parameters
on
References Isis::Tool::clearWarningSignal(), and Isis::Tool::toolActivated().
Referenced by Isis::Tool::addTo(), Isis::AdvancedTrackTool::AdvancedTrackTool(), Isis::RubberBandTool::disable(), Isis::RubberBandTool::enable(), Isis::AdvancedTrackTool::eventFilter(), Isis::FileTool::FileTool(), Isis::RubberBandTool::RubberBandTool(), Isis::TrackTool::TrackTool(), Isis::WindowTool::WindowTool(), and Isis::Workspace::Workspace().
addConnections()
virtual void Isis::Tool::addConnections (MdiCubeViewport * cvp) inline protected virtual inherited
Anytime a tool is created, you must add the connections for it.
Parameters
cvp
Reimplemented in Isis::WindowTool, and Isis::TrackTool.
addTo() [1/4]
void Isis::PanTool::addTo (QMenu * menu) virtual
Parameters
menu
Reimplemented from Isis::Tool.
addTo() [2/4]
void Isis::Tool::addTo (ToolPad * toolpad) inherited
Adds the tool to the toolpad.
Parameters
toolpad
References Isis::Tool::activate(), Isis::ToolPad::addAction(), and Isis::Tool::toolPadAction().
addTo() [3/4]
void Isis::Tool::addTo (ViewportMainWindow * pViewPortMnWin) inherited
Adds the tool to the application.
Parameters
pViewPortMnWin
References Isis::ViewportMainWindow::activeToolBar(), Isis::Tool::addToActive(), Isis::Tool::addToPermanent(), Isis::ViewportMainWindow::getMenu(), Isis::Tool::menuName(), Isis::ViewportMainWindow::permanentToolBar(), Isis::ViewportMainWindow::toolPad(), and Isis::ViewportMainWindow::workspace().
Referenced by Isis::EditTool::addTo(), Isis::FileTool::addTo(), Isis::SpecialPixelTool::addTo(), Isis::WindowTool::addTo(), Isis::ViewportMainWindow::ViewportMainWindow(), and Isis::Workspace::Workspace().
addTo() [4/4]
void Isis::Tool::addTo (Workspace * ws) virtual inherited
Adds the given workspace to the cubeviewport list.
Parameters
ws
Reimplemented in Isis::WindowTool, Isis::SpecialPixelTool, Isis::FileTool, and Isis::EditTool.
References Isis::Tool::registerTool(), and Isis::Tool::setCubeViewport().
addToActive()
void Isis::Tool::addToActive (QToolBar * toolbar) inherited
Parameters
toolbar
References Isis::Tool::createToolBarWidget(), and Isis::ToolList::toolBarStack().
Referenced by Isis::Tool::addTo(), and Isis::Workspace::Workspace().
addToPermanent()
virtual void Isis::Tool::addToPermanent (QToolBar * toolbar) inline virtual inherited
Parameters
toolbar
Reimplemented in Isis::WindowTool, Isis::SpecialPixelTool, Isis::HelpTool, Isis::FileTool, Isis::BlinkTool, and Isis::AdvancedTrackTool.
Referenced by Isis::Tool::addTo(), and Isis::Workspace::Workspace().
clearWarningSignal
void Isis::Tool::clearWarningSignal () signal inherited
Referenced by Isis::Tool::activate(), Isis::Tool::mouseButtonPress(), Isis::Tool::mouseButtonRelease(), and Isis::Tool::mouseDoubleClick().
createToolBarWidget()
QWidget * Isis::PanTool::createToolBarWidget (QStackedWidget * parent) protected virtual
Anytime a tool is created, you must add it to the tool bar.
Parameters
parent
Returns
QWidget*
Reimplemented from Isis::Tool.
References Isis::Tool::toolIconDir().
cubeViewport()
MdiCubeViewport* Isis::Tool::cubeViewport () const inline protected inherited
Return the current cubeviewport.
Returns
CubeViewport*
Referenced by Isis::TrackTool::addConnections(), Isis::WindowTool::addConnections(), Isis::StretchTool::deleteFromCube(), Isis::FileTool::discard(), Isis::FileTool::exportToList(), Isis::FileTool::exportView(), Isis::StretchTool::loadStretchFromCube(), Isis::SunShadowTool::mouseButtonPress(), Isis::EditTool::mouseButtonRelease(), Isis::ControlNetTool::mouseButtonRelease(), Isis::FeatureNomenclatureTool::mouseButtonRelease(), Isis::FindTool::mouseButtonRelease(), Isis::MatchTool::mouseButtonRelease(), mouseButtonRelease(), Isis::QnetTool::mouseButtonRelease(), Isis::RubberBandTool::mouseButtonRelease(), Isis::StretchTool::mouseButtonRelease(), Isis::AdvancedTrackTool::mouseLeave(), Isis::SunShadowTool::mouseMove(), Isis::TrackTool::mouseMove(), Isis::RubberBandTool::mouseMove(), Isis::ScatterPlotTool::mouseMove(), Isis::LatLonGridTool::paintViewport(), Isis::FindTool::paintViewport(), Isis::RubberBandTool::paintViewport(), Isis::SunShadowTool::paintViewport(), Isis::FileTool::print(), Isis::HistogramTool::refreshPlot(), Isis::SpatialPlotTool::refreshPlot(), Isis::SpectralPlotTool::refreshPlot(), Isis::TrackTool::removeConnections(), Isis::WindowTool::removeConnections(), Isis::EditTool::rubberBandComplete(), Isis::HistogramTool::rubberBandComplete(), Isis::MeasureTool::rubberBandComplete(), Isis::StereoTool::rubberBandComplete(), Isis::StretchTool::rubberBandComplete(), Isis::ZoomTool::rubberBandComplete(), Isis::FileTool::save(), Isis::FileTool::saveAs(), Isis::FileTool::saveAsCubeByOption(), Isis::FileTool::saveInfo(), Isis::StretchTool::saveStretchToCube(), Isis::ScatterPlotTool::showNewScatterPlotConfig(), Isis::StretchTool::stretchGlobal(), Isis::StretchTool::stretchGlobalAllBands(), Isis::StretchTool::stretchRegional(), Isis::StretchTool::updateAdvStretchDialogforAll(), Isis::StretchTool::updateHistograms(), Isis::MeasureTool::updateMeasure(), Isis::AbstractPlotTool::updateTool(), Isis::BandTool::updateTool(), Isis::BlinkTool::updateTool(), Isis::EditTool::updateTool(), Isis::FileTool::updateTool(), Isis::FindTool::updateTool(), Isis::LatLonGridTool::updateTool(), Isis::SpecialPixelTool::updateTool(), Isis::StretchTool::updateTool(), Isis::SunShadowTool::updateTool(), Isis::WindowTool::updateTool(), Isis::ZoomTool::updateTool(), and Isis::AbstractPlotTool::viewportsToPlot().
cubeViewportList()
Tool::CubeViewportList * Isis::Tool::cubeViewportList () const protected inherited
Return the list of cubeviewports.
Returns
CubeViewportList*
References Isis::Workspace::cubeViewportList().
Referenced by Isis::FileTool::closeAll(), Isis::MatchTool::createPoint(), Isis::BlinkTool::eventFilter(), mouseButtonRelease(), Isis::RubberBandTool::mouseButtonRelease(), Isis::RubberBandTool::mouseMove(), Isis::ScatterPlotTool::repaintViewports(), Isis::AbstractPlotTool::repaintViewports(), Isis::ZoomTool::rubberBandComplete(), Isis::ControlNetTool::setControlNet(), Isis::FeatureNomenclatureTool::setFontColor(), Isis::FeatureNomenclatureTool::setFontSize(), Isis::FeatureNomenclatureTool::setShowApprovedOnly(), Isis::FeatureNomenclatureTool::setVectorType(), Isis::StretchTool::stretchGlobalAllViewports(), Isis::MeasureTool::updateMeasure(), Isis::BlinkTool::updateTool(), Isis::FindTool::updateTool(), Isis::WindowTool::updateTool(), and Isis::AbstractPlotTool::viewportsToPlot().
enableRubberBandTool()
void Isis::Tool::enableRubberBandTool () protected virtual inherited
Anytime a tool is created, you may use the rubber band tool.
Enable the use of the rubberband tool.
Reimplemented in Isis::ZoomTool, Isis::StereoTool, Isis::SpectralPlotTool, Isis::SpatialPlotTool, Isis::RubberBandTool, Isis::MeasureTool, and Isis::HistogramTool.
References Isis::RubberBandTool::disable(), and Isis::Tool::rubberBandTool().
menuName()
QString Isis::PanTool::menuName () const inline virtual
Anytime a tool is created, you must give it a name for the menu.
Returns
QString
Reimplemented from Isis::Tool.
mouseButtonPress
void Isis::PanTool::mouseButtonPress (QPoint p, Qt::MouseButton s) protected slot
mouseButtonRelease
void Isis::PanTool::mouseButtonRelease (QPoint p, Qt::MouseButton s) protected slot
References Isis::CubeViewport::center(), Isis::Tool::cubeViewport(), Isis::Tool::cubeViewportList(), Isis::MdiCubeViewport::isLinked(), and Isis::CubeViewport::viewportToCube().
mouseDoubleClick()
void Isis::Tool::mouseDoubleClick (QPoint p) protected virtual inherited
Parameters
p
References Isis::Tool::clearWarningSignal().
mouseEnter
virtual void Isis::Tool::mouseEnter () inline protected virtual slot inherited
mouseLeave
virtual void Isis::Tool::mouseLeave () inline protected virtual slot inherited
mouseMove [1/2]
void Isis::PanTool::mouseMove (QPoint p) protected slot
mouseMove [2/2]
virtual void Isis::Tool::mouseMove (QPoint p, Qt::MouseButton) inline protected virtual slot inherited
paintViewport()
virtual void Isis::Tool::paintViewport (MdiCubeViewport * vp, QPainter * painter) inline virtual inherited
Parameters
vp
painter
Reimplemented in Isis::SunShadowTool, Isis::ScatterPlotTool, Isis::RubberBandTool, Isis::FindTool, Isis::FeatureNomenclatureTool, Isis::AbstractPlotTool, Isis::MatchTool, Isis::LatLonGridTool, Isis::StereoTool, Isis::QnetTool, and Isis::ControlNetTool.
registerTool()
void Isis::Tool::registerTool (MdiCubeViewport * viewport) protected inherited
Registers the tool to the viewport.
Parameters
viewport
References Isis::MdiCubeViewport::registerTool(), and Isis::Tool::stretchRequested().
Referenced by Isis::Tool::addTo().
removeConnections()
virtual void Isis::Tool::removeConnections (MdiCubeViewport * cvp) inline protected virtual inherited
Anytime a tool is created, you must be able to remove it's connections.
Parameters
cvp
Reimplemented in Isis::WindowTool, Isis::TrackTool, and Isis::MeasureTool.
rubberBandComplete
virtual void Isis::Tool::rubberBandComplete () inline protected virtual slot inherited
rubberBandTool()
RubberBandTool * Isis::Tool::rubberBandTool () inherited
References Isis::ToolList::rubberBandTool().
Referenced by Isis::MeasureTool::createToolBarWidget(), Isis::EditTool::enableRubberBandTool(), Isis::HistogramTool::enableRubberBandTool(), Isis::MeasureTool::enableRubberBandTool(), Isis::SpatialPlotTool::enableRubberBandTool(), Isis::SpectralPlotTool::enableRubberBandTool(), Isis::StereoTool::enableRubberBandTool(), Isis::StretchTool::enableRubberBandTool(), Isis::Tool::enableRubberBandTool(), Isis::ZoomTool::enableRubberBandTool(), Isis::HistogramTool::refreshPlot(), Isis::SpatialPlotTool::refreshPlot(), Isis::SpectralPlotTool::refreshPlot(), Isis::RubberBandComboBox::RubberBandComboBox(), Isis::EditTool::rubberBandComplete(), Isis::HistogramTool::rubberBandComplete(), Isis::MeasureTool::rubberBandComplete(), Isis::SpatialPlotTool::rubberBandComplete(), Isis::SpectralPlotTool::rubberBandComplete(), Isis::StereoTool::rubberBandComplete(), Isis::StretchTool::rubberBandComplete(), Isis::ZoomTool::rubberBandComplete(), and Isis::RubberBandComboBox::selectionChanged().
scaleChanged()
virtual void Isis::Tool::scaleChanged () inline protected virtual inherited
Reimplemented in Isis::RubberBandTool.
screenPixelsChanged
virtual void Isis::Tool::screenPixelsChanged () inline protected virtual slot inherited
This is called when actions change which pixels from the cube are displayed.
setCubeViewport
void Isis::Tool::setCubeViewport (MdiCubeViewport * cvp) slot inherited
Sets the current viewport to the given cvp.
Parameters
cvp
References Isis::Tool::updateTool(), and Isis::Tool::viewportChanged().
Referenced by Isis::Tool::addTo(), and Isis::FileTool::closeAll().
setList()
void Isis::Tool::setList (ToolList * currentList) inherited
Referenced by Isis::ToolList::append().
stretchRequested()
virtual void Isis::Tool::stretchRequested (MdiCubeViewport * , int) inline protected virtual inherited
Reimplemented in Isis::StretchTool.
Referenced by Isis::Tool::registerTool().
toolActivated
void Isis::Tool::toolActivated () signal inherited
Referenced by Isis::Tool::activate(), Isis::FeatureNomenclatureTool::FeatureNomenclatureTool(), Isis::MatchTool::MatchTool(), and Isis::StereoTool::StereoTool().
toolIconDir()
QString Isis::Tool::toolIconDir () const inline inherited
returns the path to the icon directory.
Returns
QString
Referenced by Isis::AdvancedTrackTool::AdvancedTrackTool(), Isis::BlinkTool::BlinkTool(), Isis::BandTool::createToolBarWidget(), Isis::EditTool::createToolBarWidget(), Isis::FindTool::createToolBarWidget(), Isis::MatchTool::createToolBarWidget(), createToolBarWidget(), Isis::StereoTool::createToolBarWidget(), Isis::StretchTool::createToolBarWidget(), Isis::ZoomTool::createToolBarWidget(), Isis::FileTool::FileTool(), Isis::FindTool::FindTool(), Isis::HelpTool::HelpTool(), Isis::HistogramTool::HistogramTool(), PanTool(), Isis::SpecialPixelTool::SpecialPixelTool(), Isis::RubberBandComboBox::toolIconDir(), Isis::BandTool::toolPadAction(), Isis::ControlNetTool::toolPadAction(), Isis::EditTool::toolPadAction(), Isis::FeatureNomenclatureTool::toolPadAction(), Isis::HistogramTool::toolPadAction(), Isis::LatLonGridTool::toolPadAction(), Isis::MatchTool::toolPadAction(), Isis::MeasureTool::toolPadAction(), toolPadAction(), Isis::QnetTool::toolPadAction(), Isis::ScatterPlotTool::toolPadAction(), Isis::SpatialPlotTool::toolPadAction(), Isis::SpectralPlotTool::toolPadAction(), Isis::StereoTool::toolPadAction(), Isis::StretchTool::toolPadAction(), Isis::SunShadowTool::toolPadAction(), Isis::FindTool::toolPadAction(), Isis::StatisticsTool::toolPadAction(), Isis::ZoomTool::toolPadAction(), Isis::WindowTool::WindowTool(), and Isis::ZoomTool::ZoomTool().
toolPadAction()
QAction * Isis::PanTool::toolPadAction (ToolPad * toolpad) protected virtual
Anytime a tool is created, you must setup a tool pad action with it.
Parameters
toolpad
Returns
QAction*
Reimplemented from Isis::Tool.
References Isis::Tool::toolIconDir().
updateMeasure()
virtual void Isis::Tool::updateMeasure () inline protected virtual inherited
updateTool
void Isis::Tool::updateTool () virtual slot inherited
Updates the tool.
Reimplemented in Isis::ZoomTool, Isis::WindowTool, Isis::SunShadowTool, Isis::StretchTool, Isis::SpectralPlotTool, Isis::SpecialPixelTool, Isis::SpatialPlotTool, Isis::MeasureTool, Isis::LatLonGridTool, Isis::HistogramTool, Isis::FindTool, Isis::FileTool, Isis::FeatureNomenclatureTool, Isis::EditTool, Isis::BlinkTool, Isis::BandTool, and Isis::AbstractPlotTool.
Referenced by Isis::Tool::setCubeViewport().
viewportChanged
void Isis::Tool::viewportChanged () signal inherited
Referenced by Isis::Tool::setCubeViewport(), Isis::SpatialPlotTool::SpatialPlotTool(), Isis::SpectralPlotTool::SpectralPlotTool(), and Isis::SunShadowTool::SunShadowTool().
workspace()
Workspace * Isis::Tool::workspace () protected inherited
Referenced by Isis::EditTool::addTo(), Isis::ControlNetTool::setControlNet(), and Isis::ScatterPlotTool::showNewScatterPlotConfig().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/PanTool/PanTool.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/PanTool/PanTool.cpp