Isis Developer Reference: Isis::TableViewContent Class Reference
Isis::TableViewContent Class Reference
#include <TableViewContent.h>
Public Slots
void scrollTo (QList< AbstractTreeItem * >)
Scrolls to the selected items.
void scrollTo (AbstractTreeItem *)
Scrolls to the selected item.
void refresh ()
Refreshes the table and viewport.
void updateHorizontalScrollBar (bool scrollRight=false)
Updates the horizontal scroll bar.
Signals
void rebuildModels (QList< AbstractTreeItem * >)
void modelDataChanged ()
void tableSelectionChanged ()
void tableSelectionChanged (QList< AbstractTreeItem * >)
void horizontalScrollBarValueChanged (int)
void editControlPoint (ControlPoint *controlPoint, QString serialNumber)
Public Member Functions
TableViewContent (AbstractTableModel *someModel)
Constructor.
virtual ~TableViewContent ()
Destructor.
QSize minimumSizeHint () const
Returns the minimum size hint.
QSize sizeHint () const
Returns the minimum size hint.
AbstractTableModel * getModel ()
Returns the model.
void setActiveControlNet (bool activeNet)
Sets if there is an active control net.
Protected Member Functions
bool eventFilter (QObject *target, QEvent *event)
Overrides QObject::eventFilter.
void keyPressEvent (QKeyEvent *event)
Overrides QWidget::keyPressEvent.
void leaveEvent (QEvent *event)
Overrides QWidget::leaveEvent.
void mouseDoubleClickEvent (QMouseEvent *event)
Overrides QWidget::mouseDoubleClickEvent.
void mouseMoveEvent (QMouseEvent *event)
Overrides QWidget::mouseMoveEvent.
void mousePressEvent (QMouseEvent *event)
Overrides QWidget::mousePressEvent.
void mouseReleaseEvent (QMouseEvent *event)
Overrides QWidget::mouseReleaseEvent.
void paintEvent (QPaintEvent *event)
Paints the table when there is a paint event.
void resizeEvent (QResizeEvent *event)
Updates the table when it is resized.
void scrollContentsBy (int dx, int dy)
Updates the item list when the user scrolls.
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
TableViewContent()
Isis::TableViewContent::TableViewContent (AbstractTableModel * someModel)
Constructor.
Parameters
someModel The abstract table model
References Isis::AbstractTableModel::getColumns(), getModel(), horizontalScrollBarValueChanged(), modelDataChanged(), refresh(), scrollTo(), Isis::TableColumnList::size(), tableSelectionChanged(), and updateHorizontalScrollBar().
~TableViewContent()
Isis::TableViewContent::~TableViewContent () virtual
Destructor.
Member Function Documentation
editControlPoint
void Isis::TableViewContent::editControlPoint (ControlPoint * controlPoint, QString serialNumber) signal
eventFilter()
bool Isis::TableViewContent::eventFilter (QObject * target, QEvent * event) protected
Overrides QObject::eventFilter.
Parameters
target The object that was changed
event The event that was triggered
Returns
bool True if the event is filtered out
getModel()
AbstractTableModel * Isis::TableViewContent::getModel ()
Returns the model.
Returns
AbstractTableModel The model of the table
Referenced by Isis::TableView::displayWarning(), Isis::TableView::getModel(), keyPressEvent(), scrollTo(), and TableViewContent().
horizontalScrollBarValueChanged
void Isis::TableViewContent::horizontalScrollBarValueChanged (int) signal
Referenced by TableViewContent().
keyPressEvent()
void Isis::TableViewContent::keyPressEvent (QKeyEvent * event) protected
Overrides QWidget::keyPressEvent.
Parameters
event QMouseEvent
References Isis::AbstractTableModel::getDelegate(), Isis::AbstractTableModel::getItems(), getModel(), Isis::TableColumnList::getVisibleColumns(), Isis::AbstractTableModel::getVisibleRowCount(), Isis::AbstractTableDelegate::getWidget(), Isis::AbstractTableModel::indexOfVisibleItem(), Isis::AbstractTableDelegate::readData(), scrollTo(), Isis::AbstractTableModel::setGlobalSelection(), and tableSelectionChanged().
leaveEvent()
void Isis::TableViewContent::leaveEvent (QEvent * event) protected
Overrides QWidget::leaveEvent.
Parameters
event QMouseEvent
minimumSizeHint()
QSize Isis::TableViewContent::minimumSizeHint () const
Returns the minimum size hint.
Returns
QSize Minimum size hint
Referenced by sizeHint().
modelDataChanged
void Isis::TableViewContent::modelDataChanged () signal
Referenced by TableViewContent().
mouseDoubleClickEvent()
void Isis::TableViewContent::mouseDoubleClickEvent (QMouseEvent * event) protected
Overrides QWidget::mouseDoubleClickEvent.
Parameters
event QMouseEvent
References Isis::AbstractTableModel::getDelegate(), Isis::TableColumnList::getVisibleColumns(), Isis::AbstractTableDelegate::getWidget(), and Isis::AbstractTableDelegate::readData().
mouseMoveEvent()
void Isis::TableViewContent::mouseMoveEvent (QMouseEvent * event) protected
Overrides QWidget::mouseMoveEvent.
Parameters
event QMouseEvent
References Isis::AbstractTreeItem::getChildren(), Isis::AbstractTreeItem::getPointerType(), Isis::AbstractTreeItem::Point, Isis::AbstractTreeItem::setSelected(), and tableSelectionChanged().
mousePressEvent()
void Isis::TableViewContent::mousePressEvent (QMouseEvent * event) protected
Overrides QWidget::mousePressEvent.
Parameters
event QMouseEvent
References Isis::AbstractTreeItem::getChildren(), Isis::AbstractTreeItem::getPointerType(), Isis::AbstractTableModel::getSelectedItems(), Isis::TableColumn::getTitle(), Isis::TableColumnList::getVisibleColumns(), Isis::AbstractTreeItem::isSelected(), Isis::AbstractTreeItem::Measure, Isis::AbstractTreeItem::parent(), Isis::AbstractTreeItem::Point, Isis::AbstractTableModel::setGlobalSelection(), Isis::AbstractTreeItem::setSelected(), and tableSelectionChanged().
mouseReleaseEvent()
void Isis::TableViewContent::mouseReleaseEvent (QMouseEvent * event) protected
Overrides QWidget::mouseReleaseEvent.
Empty function
Parameters
event QMouseEvent
paintEvent()
void Isis::TableViewContent::paintEvent (QPaintEvent * event) protected
Paints the table when there is a paint event.
Overrides QWidget::paintEvent
Parameters
event The paint event
References Isis::TableColumnList::getVisibleWidth(), and Isis::TableColumnList::getVisibleXRange().
rebuildModels
void Isis::TableViewContent::rebuildModels (QList< AbstractTreeItem * >) signal
refresh
void Isis::TableViewContent::refresh () slot
Refreshes the table and viewport.
References Isis::AbstractTableModel::getSelectedItems(), Isis::AbstractTableModel::getVisibleRowCount(), and Isis::AbstractTableModel::isFiltering().
Referenced by Isis::TableView::handleModelSelectionChanged(), and TableViewContent().
resizeEvent()
void Isis::TableViewContent::resizeEvent (QResizeEvent * event) protected
Updates the table when it is resized.
Parameters
event Resize event
References updateHorizontalScrollBar().
scrollContentsBy()
void Isis::TableViewContent::scrollContentsBy (int dx, int dy) protected
Updates the item list when the user scrolls.
Parameters
dx X scroll
dy Y scroll
scrollTo [1/2]
void Isis::TableViewContent::scrollTo (AbstractTreeItem * newlySelectedItem) slot
Scrolls to the selected item.
Parameters
newlySelectedItem Newly selected item to scroll to
References getModel(), and Isis::AbstractTableModel::indexOfVisibleItem().
scrollTo [2/2]
void Isis::TableViewContent::scrollTo (QList< AbstractTreeItem * > newlySelectedItems) slot
Scrolls to the selected items.
Parameters
newlySelectedItems Newly selected items to scroll to
Referenced by Isis::TableView::handleModelSelectionChanged(), keyPressEvent(), and TableViewContent().
setActiveControlNet()
void Isis::TableViewContent::setActiveControlNet (bool activeNet)
Sets if there is an active control net.
Parameters
bool The bool if there is an active control net
Referenced by Isis::Directory::addCnetEditorView().
sizeHint()
QSize Isis::TableViewContent::sizeHint () const
Returns the minimum size hint.
See also
TableViewContent::minimumSizeHint()
Returns
QSize Minimum size hint
References minimumSizeHint().
tableSelectionChanged [1/2]
void Isis::TableViewContent::tableSelectionChanged () signal
Referenced by keyPressEvent(), mouseMoveEvent(), mousePressEvent(), and TableViewContent().
tableSelectionChanged [2/2]
void Isis::TableViewContent::tableSelectionChanged (QList< AbstractTreeItem * >) signal
updateHorizontalScrollBar
void Isis::TableViewContent::updateHorizontalScrollBar (bool scrollRight = false) slot
Updates the horizontal scroll bar.
Parameters
scrollRight True if the horizontal scroll bar has scrolled right
References Isis::TableColumnList::getVisibleColumns(), and Isis::TableColumnList::size().
Referenced by resizeEvent(), and TableViewContent().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/TableViewContent.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/TableViewContent.cpp