Isis Developer Reference: Isis::NonLinearLSQ Class Reference
Isis::NonLinearLSQ Class Reference abstract
Utility
NonLinearLSQ Computes a fit using a Levenberg-Marquardt algorithm.
#include <NonLinearLSQ.h>
Public Types
typedef TNT::Array1D< double > NLVector
typedef TNT::Array2D< double > NLMatrix
Public Member Functions
NonLinearLSQ ()
virtual ~NonLinearLSQ ()
Destructor.
virtual int nSize () const =0
virtual int nParms () const =0
void setMaxIters (int m)
Sets the maximum number of iterations.
int maxIters () const
Maximum number iterations for valid solution.
virtual NLVector guess ()=0
virtual NLVector f_x (const NLVector &x)=0
virtual NLMatrix df_x (const NLVector &x)=0
virtual double absErr () const
virtual double relErr () const
int curvefit ()
int status () const
Return status of last fit processing.
bool success () const
Determine success from last fit processing.
bool success (int status) const
Check status for success of the given condition
std::string statusstr () const
Return error message pertaining to last fit procesing.
std::string statusstr (int status) const
Return error message given status condition.
virtual int checkIteration (const int Iter, const NLVector &fitcoefs, const NLVector &uncerts, double cplxconj, int Istatus)
Default interation test simply returns input status.
NLVector coefs () const
Return coefficients from last fit processing.
NLVector uncert () const
Return uncertainties from last fit processing.
int nIterations () const
Return number of iterations from last fit processing.
Protected Member Functions
void Terminate (const std::string &message="")
void Abort (const std::string &reason="")
bool doContinue () const
Detailed Description
NonLinearLSQ Computes a fit using a Levenberg-Marquardt algorithm.
This virtual base class uses the GSL toolkit to apply the Levenberg-Marquardt algorithm to fit data to a non-linear equation using least squares.
Author
2007-11-15 Kris Becker
Member Typedef Documentation
NLMatrix
typedef TNT::Array2D<double> Isis::NonLinearLSQ::NLMatrix
NLVector
typedef TNT::Array1D<double> Isis::NonLinearLSQ::NLVector
Constructor & Destructor Documentation
NonLinearLSQ()
Isis::NonLinearLSQ::NonLinearLSQ () inline
~NonLinearLSQ()
virtual Isis::NonLinearLSQ::~NonLinearLSQ () inline virtual
Destructor.
Member Function Documentation
Abort()
void Isis::NonLinearLSQ::Abort (const std::string & reason = "") protected
absErr()
virtual double Isis::NonLinearLSQ::absErr () const inline virtual
Reimplemented in Isis::ZeroBufferFit.
checkIteration()
virtual int Isis::NonLinearLSQ::checkIteration (const int Iter, const NLVector & fitcoefs, const NLVector & uncerts, double cplxconj, int Istatus) inline virtual
Default interation test simply returns input status.
Reimplemented in Isis::ZeroBufferFit.
coefs()
NLVector Isis::NonLinearLSQ::coefs () const inline
Return coefficients from last fit processing.
Referenced by Isis::ZeroBufferFit::Solve().
curvefit()
int Isis::NonLinearLSQ::curvefit ()
Referenced by Isis::ZeroBufferFit::Solve().
df_x()
virtual NLMatrix Isis::NonLinearLSQ::df_x (const NLVector & x) pure virtual
Implemented in Isis::ZeroBufferFit.
doContinue()
bool Isis::NonLinearLSQ::doContinue () const inline protected
f_x()
virtual NLVector Isis::NonLinearLSQ::f_x (const NLVector & x) pure virtual
Implemented in Isis::ZeroBufferFit.
guess()
virtual NLVector Isis::NonLinearLSQ::guess () pure virtual
Implemented in Isis::ZeroBufferFit.
maxIters()
int Isis::NonLinearLSQ::maxIters () const inline
Maximum number iterations for valid solution.
Returns
int Maximum resolutions
Referenced by Isis::ZeroBufferFit::ZeroBufferFit().
nIterations()
int Isis::NonLinearLSQ::nIterations () const inline
Return number of iterations from last fit processing.
Referenced by Isis::ZeroBufferFit::Solve().
nParms()
virtual int Isis::NonLinearLSQ::nParms () const pure virtual
Implemented in Isis::ZeroBufferFit.
nSize()
virtual int Isis::NonLinearLSQ::nSize () const pure virtual
Implemented in Isis::ZeroBufferFit.
relErr()
virtual double Isis::NonLinearLSQ::relErr () const inline virtual
Reimplemented in Isis::ZeroBufferFit.
setMaxIters()
void Isis::NonLinearLSQ::setMaxIters (int m) inline
Sets the maximum number of iterations.
Parameters
m User provides the maximum number iterations
Referenced by Isis::ZeroBufferFit::ZeroBufferFit().
status()
int Isis::NonLinearLSQ::status () const inline
Return status of last fit processing.
Referenced by statusstr(), and success().
statusstr() [1/2]
std::string Isis::NonLinearLSQ::statusstr () const inline
Return error message pertaining to last fit procesing.
Referenced by Isis::ZeroBufferFit::Solve().
statusstr() [2/2]
std::string Isis::NonLinearLSQ::statusstr (int status) const inline
Return error message given status condition.
References status().
success() [1/2]
bool Isis::NonLinearLSQ::success () const inline
Determine success from last fit processing.
Referenced by Isis::ZeroBufferFit::Solve().
success() [2/2]
bool Isis::NonLinearLSQ::success (int status) const inline
Check status for success of the given condition
References status().
Terminate()
void Isis::NonLinearLSQ::Terminate (const std::string & message = "") protected
uncert()
NLVector Isis::NonLinearLSQ::uncert () const inline
Return uncertainties from last fit processing.
Referenced by Isis::ZeroBufferFit::Solve().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/mro/objs/HiCal/NonLinearLSQ.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/mro/objs/HiCal/NonLinearLSQ.cpp