Isis Developer Reference: Isis::PlotWindowBestFitDialog Class Reference
Isis::PlotWindowBestFitDialog Class Reference
#include <PlotWindowBestFitDialog.h>
Public Slots
void createBestFitLine ()
This is called when the user wants the best fit line.
void readCurvesFromWindow ()
This populates the curve selection combo with all of the available information inside of the PlotWindow for which we're adding a best fit line to.
Public Member Functions
PlotWindowBestFitDialog (PlotWindow *windowWithCurves, QWidget *parent)
Create a PlotWindowBestFitDialog.
virtual ~PlotWindowBestFitDialog ()
Detailed Description
Author
2012-01-18 Steven Lambright
Constructor & Destructor Documentation
PlotWindowBestFitDialog()
Isis::PlotWindowBestFitDialog::PlotWindowBestFitDialog (PlotWindow * windowWithCurves, QWidget * parent)
Create a PlotWindowBestFitDialog.
If a best fit line is accepted by the user, then the curve will be added directly to the plot window with no extra code in the plot window. This fully initializes the state of the dialog and no extra initialization should be required.
Parameters
windowWithCurves This must not be NULL. This is the plot window for which a best fit line should be calculated.
parent The Qt-parent of this dialog.
References createBestFitLine(), and readCurvesFromWindow().
~PlotWindowBestFitDialog()
Isis::PlotWindowBestFitDialog::~PlotWindowBestFitDialog () virtual
Member Function Documentation
createBestFitLine
void Isis::PlotWindowBestFitDialog::createBestFitLine () slot
This is called when the user wants the best fit line.
The already populated m_curveMultivariateStats is used to give us the current best-fit coefficients. We create y-data points based on the best fit for every x value inside of the curve we're fitting. The curve is then added directly to the plot window.
References Isis::PlotCurve::color(), Isis::CubePlotCurve::copySource(), Isis::ScatterPlotData::discreteXValues(), Isis::IsSpecial(), Isis::Null, Isis::PlotCurve::setColor(), Isis::PlotCurve::setData(), Isis::PlotCurve::setMarkerSymbol(), Isis::PlotCurve::setPen(), Isis::PlotCurve::xUnits(), and Isis::PlotCurve::yUnits().
Referenced by PlotWindowBestFitDialog().
readCurvesFromWindow
void Isis::PlotWindowBestFitDialog::readCurvesFromWindow () slot
This populates the curve selection combo with all of the available information inside of the PlotWindow for which we're adding a best fit line to.
Referenced by PlotWindowBestFitDialog().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/PlotWindow/PlotWindowBestFitDialog.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/PlotWindow/PlotWindowBestFitDialog.cpp