Isis Developer Reference: Isis::SubArea Class Reference
Isis::SubArea Class Reference
High Level Cube I/O
Apply corrections to a cube label for subarea extraction.
#include <SubArea.h>
Public Member Functions
SubArea ()
~SubArea ()
void SetSubArea (const int orignl, const int origns, const int sl, const int ss, const int el, const int es, const double linc, const double sinc)
Defines the subarea.
void UpdateLabel (Cube *icube, Cube *ocube, PvlGroup &results)
Modifies a label for a file containing a subarea.
Detailed Description
Apply corrections to a cube label for subarea extraction.
This class is used to apply corrections to a cube label when a subarea has been extracted. It is a base class which will take the cube label from the original cube file along with subarea information and generate a corrected cube label for the output cube file.
If you would like to see SubArea being used in implementation, see crop, reduce, enlarge, cropspecial, or pad.
Author
2009-10-02 Janet Barrett
Constructor & Destructor Documentation
SubArea()
Isis::SubArea::SubArea () inline
~SubArea()
Isis::SubArea::~SubArea () inline
Member Function Documentation
SetSubArea()
void Isis::SubArea::SetSubArea (const int orignl, const int origns, const int sl, const int ss, const int el, const int es, const double linc, const double sinc)
Defines the subarea.
Parameters
orignl This is the number of lines in the original image.
origns This is the number of samples in the original image.
sl This is the line in the original image where the subarea will start at. This value must be greater than or equal to 1 and less than or equal to the number of lines in the original image.
ss This is the sample in the original image where the subarea will start at. This value must be greater than or equal to 1 and less than or equal to the number of samples in the original image.
el This is the ending line of the subarea to extract from the original image. This value must be greater than or equal to sl and less than or equal to the number of lines in the original image. The actual number of lines that will be in the subarea will be (el-sl+1)/linc.
es This is the ending sample of the subarea to extract from the original image. This value must be greater than or equal to ss and less than or equal to the number of samples in the original image. The actual number of samples that will be in the subarea will be (es-ss+1)/sinc.
linc This is the line increment that will be used to extract the subarea from the original image. It must be greater than 0.
sinc This is the sample increment that will be used to extract the subarea from the original image. It must be greater than 0.
References _FILEINFO_.
Referenced by Isis::Enlarge::UpdateOutputLabel(), and Isis::Reduce::UpdateOutputLabel().
UpdateLabel()
void Isis::SubArea::UpdateLabel (Cube * icube, Cube * ocube, PvlGroup & results)
Modifies a label for a file containing a subarea.
The AlphaCube, Mapping, and Instrument groups are all affected when a subarea is extracted from another file. If the linc is not equal to the sinc, then the Instrument and Mapping groups will be removed from the label because they will no longer be valid. If the linc is equal to the sinc and they are not equal to 1, then the map scale and resolution in the Mapping group needs to be updated. The latitude and longitude ranges become invalid when the subarea does not cover the entire sample and line range of the original cube. Update the upper left corner x,y values if the projection is still valid and the starting line and/or starting sample have been changed from their location in the original file.
Parameters
icube This is the input cube that will have the subarea extracted from it. The label of this cube will be used to create updated Mapping, Instrument, and AlphaCube groups for the label of the output cube containing the subarea.
ocube This is the output cube file containing the subarea. The label of this cube will be modified by extracting the Mapping, Instrument, and AlphaCube groups from the input label and putting them in this label.
results This is the Results group that will go into the application log file. This group must be created by the calling application. Information will be added to it if the Mapping or Instrument groups are deleted from the output image label.
References Isis::PvlContainer::addKeyword(), Isis::Cube::deleteGroup(), Isis::PvlContainer::deleteKeyword(), Isis::PvlObject::findObject(), Isis::TProjection::Has180Domain(), Isis::TProjection::Has360Domain(), Isis::Cube::hasGroup(), Isis::PvlContainer::hasKeyword(), Isis::TProjection::IsEquatorialCylindrical(), Isis::Projection::IsGood(), Isis::TProjection::IsPlanetographic(), Isis::TProjection::IsPositiveEast(), Isis::Cube::label(), Isis::Cube::lineCount(), Isis::TProjection::Longitude(), Isis::Cube::projection(), Isis::Cube::putGroup(), Isis::Cube::sampleCount(), Isis::Projection::SetWorld(), Isis::TProjection::To180Domain(), Isis::toDouble(), Isis::TProjection::ToPlanetographic(), Isis::TProjection::ToPositiveWest(), Isis::toString(), Isis::TProjection::UniversalLatitude(), Isis::TProjection::UniversalLongitude(), Isis::AlphaCube::UpdateGroup(), Isis::Projection::XCoord(), and Isis::Projection::YCoord().
Referenced by Isis::Enlarge::UpdateOutputLabel(), and Isis::Reduce::UpdateOutputLabel().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/SubArea/SubArea.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/SubArea/SubArea.cpp