Isis Developer Reference: Isis::ProcessImportFits Class Reference
Isis::ProcessImportFits Class Reference
High Level Cube I/O
Import a FITS file.
#include <ProcessImportFits.h>
Public Types
enum VAXDataType { VAX_REAL , VAX_INT }
enum VAXSpecialPixel {
VAX_MIN4 , VAX_NULL4 , VAX_LRS4 , VAX_LIS4 ,
VAX_HIS4 , VAX_HRS4
}
enum Interleave {
InterleaveUndefined , JP2 , BSQ , BIL ,
BIP
}
This enum includes how the document should be read: by BSQ, BIL, BIP, JP2, or InterleaveUndefined.
Public Member Functions
ProcessImportFits ()
Constructor for ProcessImportFits.
virtual ~ProcessImportFits ()
Destructor for ProcessImportFits.
PvlGroup standardInstrumentGroup (PvlGroup fitsLabel) const
Return a PVL instrument group populated with expected default values.
PvlGroup extraFitsLabel (int labelNumber) const
Supplies the extra FITS label corresponding to the given index.
PvlGroup fitsImageLabel (int labelNumber) const
Supplies the FITS image label corresponding to the given index.
void setFitsFile (FileName fitsFile)
Opens a FITS image file with header and reads the FITS labels.
void setProcessFileStructure (int labelNumber)
Sets the Process file structure parameters based on the given image label index.
virtual void StartProcess ()
Process the input file and write it to the output.
virtual void StartProcess (void funct(Isis::Buffer &out))
Process the input file and send data to method.
virtual void StartProcess (void funct())
In the base class, this method will invoked a user-specified function exactly one time.
void SetInputFile (const QString &file)
Sets the name of the input file to be read in the import StartProcess method and verifies its existance.
QString InputFile ()
Sets the name of the input file to be read in the import StartProcess method and verifies its existance.
Isis::Cube * SetOutputCube (const QString &parameter)
Create the output file.
Isis::Cube * SetOutputCube (const QString &parameter, UserInterface &ui)
Create the output file.
virtual Isis::Cube * SetOutputCube (const QString &fname, Isis::CubeAttributeOutput &att)
Create the output file.
virtual Isis::Cube * SetOutputCube (const QString &parameter, const int nsamps, const int nlines, const int nbands=1)
Allocates a user specified output cube whose size is specified by the programmer.
virtual Isis::Cube * SetOutputCube (const QString &fname, const Isis::CubeAttributeOutput &att, const int nsamps, const int nlines, const int nbands=1)
Allocates a output cube whose name and size is specified by the programmer.
void SetAttributes (CubeAttributeOutput &att)
Given a CubeAttributeOutput object, set min/max to propagate if propagating min/max attributes was requested and set the pixel type to propagate if pixel type propagation was requested.
void SetPixelType (const Isis::PixelType type)
Sets the pixel type of the input file.
Isis::PixelType PixelType ()
Returns the pixel type.
void SetDimensions (const int ns, const int nl, const int nb)
Sets the physical size of the input cube.
int Samples ()
Returns the number of samples.
int Lines ()
Returns the number of lines.
int Bands ()
Returns the number of bands.
void SetByteOrder (const Isis::ByteOrder order)
Sets the byte order of the input file.
Isis::ByteOrder ByteOrder ()
Returns the byte order.
bool IsVAXSpecial (unsigned int *vax, VAXSpecialPixel pix)
Determines if the VAX encoded pixel value is special or not.
double VAXConversion (void *ibuf)
Conversion routine which translates VAX_REAL to IEEE_REAL.
void SetSuffixOffset (int samples, int lines, int coreBands, int itemBytes)
void SetSuffixPixelType (const Isis::PixelType type)
void SetVAXConvert (const bool vax_convert)
Sets the VAX flag of the input cube.
void SetFileHeaderBytes (const int bytes)
This method sets the number of bytes in the header of a file.
void SetFileTrailerBytes (const int bytes)
This method sets the number of bytes in the trailer of a file.
void SetDataHeaderBytes (const int bytes)
This method sets the number of bytes in the header of each datablock of a file.
void SetDataTrailerBytes (const int bytes)
This method sets the number of bytes in the trailer of each datablock of a file.
void SetDataPrefixBytes (const int bytes)
This method sets the number of bytes at the beginning of each data record of a file.
void SetDataSuffixBytes (const int bytes)
This method sets the number of bytes at the end of each data record of a file.
void SaveFileHeader ()
This method marks the file header to be saved.
void SaveFileTrailer ()
This method marks the file trailer to be saved.
void SaveDataHeader ()
This method marks the data block headers to be saved.
void SaveDataTrailer ()
This method marks the data block trailers to be saved.
void SaveDataPrefix ()
This method marks the data prefix to be saved.
void SaveDataSuffix ()
This method marks the data suffix to be saved.
int FileHeaderBytes () const
This method returns the number of file header bytes.
int FileTrailerBytes () const
This method returns the number of file trailer bytes.
int DataHeaderBytes () const
This method returns the number of data header bytes.
int DataTrailerBytes () const
This method returns the number of data trailer bytes.
int DataPrefixBytes () const
This method returns the number of data prefix bytes.
int DataSuffixBytes () const
This method returns the number of data duffix bytes.
char * FileHeader ()
This method returns a pointer to the file header.
char * FileTrailer ()
This method returns a pointer to the file trailer.
std::vector< char * > DataHeader ()
This method returns a pointer to the data header.
std::vector< char * > DataTrailer ()
This method returns a pointer to the data trailer.
std::vector< std::vector< char * > > DataPrefix ()
This method returns a pointer to the data prefix.
std::vector< std::vector< char * > > DataSuffix ()
This method returns a pointer to the data suffix.
void SetOrganization (const ProcessImport::Interleave org)
Sets the organization of the input cube.
Interleave Organization () const
Gets the organization of the input cube.
void SetBase (const double base)
Sets the core base of the input cube.
void SetBase (const std::vector< double > base)
Sets band dependent core base.
void SetMultiplier (const double mult)
Sets the core multiplier of the input cube.
void SetMultiplier (const std::vector< double > mult)
Sets band dependent core multiplier.
void SetSpecialValues (const double null, const double lrs, const double lis, const double hrs, const double his)
Sets a mapping of input pixel values to output special pixel values.
void SetNull (const double null_min, const double null_max)
Sets the range that will be considered Isis::Null.
void SetLRS (const double lrs_min, const double lrs_max)
Sets the range that will be considered Isis::Null.
void SetLIS (const double lis_min, const double lis_max)
Sets the range that will be considered Isis::Null.
void SetHRS (const double hrs_min, const double hrs_max)
Sets the range that will be considered Isis::Null.
void SetHIS (const double his_min, const double his_max)
Sets the range that will be considered Isis::Null.
double TestPixel (const double pixel)
Tests the pixel.
void ProcessBsq (void funct(Isis::Buffer &out)=NULL)
Process the import data as a band sequential file.
void ProcessBil (void funct(Isis::Buffer &out)=NULL)
Function to process files stored as Band Interleaved by Line.
void ProcessBip (void funct(Isis::Buffer &out)=NULL)
Function to process files stored as Band Interleaved by Pixel.
void ProcessJp2 (void funct(Isis::Buffer &out)=NULL)
Function to process files containing compressed JPEG2000 data (which is always BSQ but is processed as BIL with one or more lines stored sequentially for each band).
void CheckPixelRange (QString pixelName, double min, double max)
Checks the special pixel range of the given against all other special pixel value ranges, making sure none overlap.
virtual void EndProcess ()
End the processing sequence and cleans up by closing cubes, freeing memory, etc.
virtual void Finalize ()
Cleans up by closing cubes and freeing memory for owned cubes.
virtual Isis::Cube * SetInputCube (const QString &parameter, const int requirements=0)
Opens an input cube specified by the user and verifies requirements are met.
virtual Isis::Cube * SetInputCube (const QString &fname, const Isis::CubeAttributeInput &att, int requirements=0)
Opens an input cube specified by the programmer and verifies requirements are met.
virtual void SetInputCube (Isis::Cube *inCube, int requirements=0)
Set the InputCube vector to an opened Cube which was dynamically allocated.
virtual Isis::Cube * SetOutputCubeStretch (const QString &parameter, UserInterface *ui=nullptr)
Allocates a user-specified output cube whose size matches the first input cube.
virtual Isis::Cube * SetOutputCubeStretch (const QString &parameter, const int nsamps, const int nlines, const int nbands=1, UserInterface *ui=nullptr)
Allocates a user specified output cube whose size is specified by the programmer.
void AddInputCube (Cube *cube, bool owned=true)
void AddOutputCube (Cube *cube, bool owned=true)
void CheckRequirements (const Cube *cube, const int requirements)
Checks to make sure the input cube meets the inputted requirements.
void ClearCubes ()
Close owned cubes from the list and clear the list.
void ClearInputCubes ()
Close owned input cubes from the list and clear the list.
void ClearOutputCubes ()
Close owned output cubes from the list and clear the list.
void PropagateLabels (const bool prop)
This method allows the programmer to turn on/off the propagation of labels from the 1st input cube to any of the output cubes.
void PropagateLabels (const QString &cube)
This method allows the programmer to propagate labels from a specific secondary cube.
void PropagateTables (const bool prop)
This method allows the programmer to propagate input tables to the output cube (default is true)
void PropagateTables (const QString &fromName, const QList< QString > &tableNames=QList< QString >())
Propagate the tables from the cube with the given filename to the output cube.
void PropagatePolygons (const bool prop)
This method allows the programmer to propagate input blobs to the output cube (default is true)
void PropagateHistory (const bool prop)
This method allows the programmer to propagate history to the output cube (default is true)
void PropagateOriginalLabel (const bool prop)
This method allows the programmer to propagate original labels to the output cube (default is true)
Isis::Progress * Progress ()
This method returns a pointer to a Progress object.
QString MissionData (const QString &mission, const QString &file, bool highestVersion=false)
This method reads the mission specific data directory from the user preference file, makes sure that mission is available in the Isis installation, and the attaches the provided input file to the directory in order to create a full file specification.
void WriteHistory (Cube &cube)
Writes out the History blob to the cube.
void CalculateStatistics ()
Calculates and stores off statistics on every band of every cube added to this process via the SetInputCube method.
std::vector< Isis::Statistics * > BandStatistics (const unsigned index)
Get the vector of Statistics objects for each band separately of a specified input cube.
Isis::Statistics * CubeStatistics (const unsigned index)
Get the Statistics object for all bands of a specified input cube.
Protected Attributes
Isis::Progress * p_progress
Pointer to a Progress object.
bool p_propagateLabels
Flag indicating if labels are be propagated to output cubes.
bool p_propagateTables
Flag indicating if tables are be propagated to output cubes.
bool p_propagatePolygons
Flag indicating if blobs are be propagated to output cubes.
bool p_propagateHistory
Flag indicating if history is to be propagated to output cubes.
bool p_propagateOriginalLabel
Flag indicating if original lable is to be propagated to output cubes.
std::vector< std::vector< Isis::Statistics * > > p_bandStats
Holds the calculated statistics for each band separately of every input cubei after the CalculateStatistics method is called.
std::vector< Isis::Statistics * > p_cubeStats
Holds the calculated statistics for every band together of every input cubei after the CalculateStatistics method is called.
std::vector< Isis::Cube * > InputCubes
A vector of pointers to opened Cube objects.
std::vector< Isis::Cube * > OutputCubes
A vector of pointers to allocated Cube objects.
QSet< Isis::Cube * > * m_ownedCubes
A list of cubes owned by this instant.
Detailed Description
Import a FITS file.
This class allows a programmer to develop application programs which import FITS cubes and mangles the FITS label into appropriate ISIS labels. The entire FITS label is converted to an ISIS PVL, allowing the programmer to interrogate it with existing ISIS tools.
Author
2013-10-08 Stuart Sides
Member Enumeration Documentation
Interleave
enum Isis::ProcessImport::Interleave inherited
This enum includes how the document should be read: by BSQ, BIL, BIP, JP2, or InterleaveUndefined.
Enumerator
InterleaveUndefined
Undefined.
JP2
Jpeg 2000 Format (always band sequential).
BSQ
Band Sequential Format (i.e.
Band Interleaved). The first line of data is followed immediately by the next line in the same spectral band.
BIL
Band Interleaved By Line Format (i.e.
Row Interleaved). The first line of data is followed immediately by the first line of data in the next band.
BIP
Band Interleaved By Pixel Format (i.e.
Pixel Interleaved). The first pixel for all bands is followed by the second pixel for all bands.
VAXDataType
enum Isis::ProcessImport::VAXDataType inherited
Enumerator
VAX_REAL
VAX_INT
VAXSpecialPixel
enum Isis::ProcessImport::VAXSpecialPixel inherited
Enumerator
VAX_MIN4
VAX_NULL4
VAX_LRS4
VAX_LIS4
VAX_HIS4
VAX_HRS4
Constructor & Destructor Documentation
ProcessImportFits()
Isis::ProcessImportFits::ProcessImportFits ()
Constructor for ProcessImportFits.
~ProcessImportFits()
Isis::ProcessImportFits::~ProcessImportFits () virtual
Destructor for ProcessImportFits.
Member Function Documentation
AddInputCube()
void Isis::Process::AddInputCube (Cube * cube, bool owned = true) inherited
AddOutputCube()
void Isis::Process::AddOutputCube (Cube * cube, bool owned = true) inherited
Bands()
int Isis::ProcessImport::Bands () inline inherited
Returns the number of bands.
Returns
The number of bands
BandStatistics()
std::vector<Isis::Statistics *> Isis::Process::BandStatistics (const unsigned index) inline inherited
Get the vector of Statistics objects for each band separately of a specified input cube.
Parameters
index The index of the input cube in InputCubes
Returns
vector<Statistics*> A list of statistics ordered by band
References Isis::Process::p_bandStats.
ByteOrder()
Isis::ByteOrder Isis::ProcessImport::ByteOrder () inline inherited
Returns the byte order.
Returns
Byte order of the data
CalculateStatistics()
void Isis::Process::CalculateStatistics () inherited
Calculates and stores off statistics on every band of every cube added to this process via the SetInputCube method.
The newly calculated statistics are stored in two ways: as a vector where each entry is a single Statistics object for every band of a particular input cube, and as a vector where each entry is a vector of Statistics objects, for each band separately, of a particular input cube.
References Isis::Statistics::AddData(), Isis::Cube::bandCount(), Isis::Progress::CheckStatus(), Isis::Buffer::DoubleBuffer(), Isis::Cube::lineCount(), Isis::Cube::read(), Isis::LineManager::SetLine(), Isis::Progress::SetMaximumSteps(), Isis::Progress::SetText(), Isis::Buffer::size(), and Isis::toString().
CheckPixelRange()
void Isis::ProcessImport::CheckPixelRange (QString pixelName, double pixelMin, double pixelMax) inherited
Checks the special pixel range of the given against all other special pixel value ranges, making sure none overlap.
Parameters
pixelName Name of the special pixel type to be displayed in the error message.
pixelMin The minimum value of the special pixel range
pixelMax The maximum value of the special pixel range
References _FILEINFO_, Isis::toString(), and Isis::IException::User.
Referenced by Isis::ProcessImport::SetHIS(), Isis::ProcessImport::SetHRS(), Isis::ProcessImport::SetLIS(), Isis::ProcessImport::SetLRS(), and Isis::ProcessImport::SetNull().
CheckRequirements()
void Isis::Process::CheckRequirements (const Cube * cube, const int requirements) inherited
Checks to make sure the input cube meets the inputted requirements.
Parameters
cube Cube to check
requirements Use to specify requirements for the input file. The following requirments are checked against 1) ic_base::SizeMatch checks to make sure the input cube has the same bands, samples, and lines as the first input cube open using this method, 2) ic_base::SpatialMatch checks to make sure the input cube has the same samples and lines as the first input cube, 3) ic_base::Georeferenced checks to make sure latitude/longitudes can be obtained from the input cube, 4) ic_base::FullyGeoreferenced checks to make sure latitude/longitude, phase/incidence/emission, and other geometric parameters can be obtained from the input cube, 5) ic_base::OneBand checks to make sure the input cube has exactly one band. Note, that these requirements can be logically or'ed. For example, ic_base::SpatialMatch | ic_base::georeferenced. Defaults to 0
Exceptions
Isis::iException::Message
References _FILEINFO_, Isis::AllMatchOrOne, Isis::Cube::bandCount(), Isis::BandMatchOrOne, Isis::Cube::fileName(), Isis::Cube::lineCount(), Isis::OneBand, Isis::Cube::sampleCount(), Isis::SizeMatch, and Isis::SpatialMatch.
ClearCubes()
void Isis::Process::ClearCubes () inherited
Close owned cubes from the list and clear the list.
ClearInputCubes()
void Isis::Process::ClearInputCubes () inherited
Close owned input cubes from the list and clear the list.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
ClearOutputCubes()
void Isis::Process::ClearOutputCubes () inherited
Close owned output cubes from the list and clear the list.
CubeStatistics()
Isis::Statistics* Isis::Process::CubeStatistics (const unsigned index) inline inherited
Get the Statistics object for all bands of a specified input cube.
Parameters
index The index of the input cube in InputCubes
Returns
Statistics* Collections of statistics gathered on all bands
References Isis::Process::p_cubeStats.
DataHeader()
std::vector< char * > Isis::ProcessImport::DataHeader () inherited
This method returns a pointer to the data header.
A data header is a block of non-image data at the beginning of each data block (for BSQ data blocks are bands). This is not included in the file header and does not include any record headers, such as line prefixes. In order to retrieve this data, the data header bytes must be set and the data header must be saved via SetDataHeaderBytes() and SaveDataHeader(), respectively. This method must be called only after StartProcess() has returned and before EndProcess() is called.
Returns
vector <char*> Vector of pointers to data headers for each block, if saved.
Exceptions
Isis::iException::Message "Data header was not saved. Use SaveDataHeader()."
See also
SetDataHeaderBytes()
SaveDataHeader()
References _FILEINFO_, and Isis::IException::Programmer.
DataHeaderBytes()
int Isis::ProcessImport::DataHeaderBytes () const inherited
This method returns the number of data header bytes.
DataPrefix()
std::vector< std::vector< char * > > Isis::ProcessImport::DataPrefix () inherited
This method returns a pointer to the data prefix.
A data prefix is a block of non-image data at the beginning of each data record (for BSQ data records are lines). This is not included in the file header or the data header. In order to retrieve this data, the data prefix bytes must be set and the data prefix must be saved via SetDataPrefixBytes() and SaveDataPrefix(), respectively. This method must be called only after StartProcess() has returned and before EndProcess() is called.
Returns
vector <vector <char*> > Two-dimensional vector of pointers to data prefixes for each record, if saved.
Exceptions
Isis::iException::Message "Data prefix was not saved. Use SaveDataPrefix()."
See also
SetDataPrefixBytes()
SaveDataPrefix()
References _FILEINFO_, and Isis::IException::Programmer.
DataPrefixBytes()
int Isis::ProcessImport::DataPrefixBytes () const inherited
This method returns the number of data prefix bytes.
Referenced by setProcessFileStructure().
DataSuffix()
std::vector< std::vector< char * > > Isis::ProcessImport::DataSuffix () inherited
This method returns a pointer to the data suffix.
A data suffix is a block of non-image data at the end of each data record (for BSQ data records are lines). This is not included in the file trailer or the data trailer. In order to retrieve this data, the data suffix bytes must be set and the data suffix must be saved via SetDataSuffixBytes() and SaveDataSuffix(), respectively. This method must be called only after StartProcess() has returned and before EndProcess() is called.
Returns
vector <vector <char*> > Two-dimensional vector of pointers to data suffixes for each record, if saved.
Exceptions
Isis::iException::Message "Data suffix was not saved. Use SaveDataSuffix()."
See also
SetDataSuffixBytes()
SaveDataSuffix()
References _FILEINFO_, and Isis::IException::Programmer.
DataSuffixBytes()
int Isis::ProcessImport::DataSuffixBytes () const inherited
This method returns the number of data duffix bytes.
Referenced by setProcessFileStructure().
DataTrailer()
std::vector< char * > Isis::ProcessImport::DataTrailer () inherited
This method returns a pointer to the data trailer.
A data trailer is a block of non-image data at the end each data block (for BSQ data blocks are bands). This is not included in the file trailer and does not include any record trailers, such as line suffixes. In order to retrieve this data, the data trailer bytes must be set and the data trailer must be saved via SetDataTrailerBytes() and SaveDataTrailer(), respectively. This method must be called only after StartProcess() has returned and before EndProcess() is called.
Returns
vector <char*> Vector of pointers to data trailers for each block, if saved.
Exceptions
Isis::iException::Message "Data trailer was not saved. Use SaveDataTrailer()."
See also
SetDataTrailerBytes()
SaveDataTrailer()
References _FILEINFO_, and Isis::IException::Programmer.
DataTrailerBytes()
int Isis::ProcessImport::DataTrailerBytes () const inherited
This method returns the number of data trailer bytes.
EndProcess()
void Isis::Process::EndProcess () virtual inherited
End the processing sequence and cleans up by closing cubes, freeing memory, etc.
Deprecated:
Please use Finalize()
Reimplemented in Isis::ProcessPolygons, Isis::ProcessMosaic, Isis::ProcessImportPds, Isis::ProcessGroundPolygons, Isis::ProcessByTile, Isis::ProcessByBrick, and Isis::ProcessByBoxcar.
Referenced by Isis::ProcessByBoxcar::EndProcess().
extraFitsLabel()
PvlGroup Isis::ProcessImportFits::extraFitsLabel (int labelNumber) const
Supplies the extra FITS label corresponding to the given index.
Zero returns the first label in the FITS header that has no data. To access image labels, call fitsImageLabel().
See also
fitsImageLabel()
Parameters
labelNumber The index to the extra FITS header label.
Returns
PvlGroup version of a FITS label corresponding to requested label number.
References _FILEINFO_, Isis::FileName::expanded(), Isis::IException::Programmer, Isis::FileName::toString(), and Isis::IException::User.
FileHeader()
char * Isis::ProcessImport::FileHeader () inherited
This method returns a pointer to the file header.
A file header is a block of non-image data at the beginning of the entire file. This does not include any section headers, such as band headers or line prefixes. In order to retrieve this data, the file header bytes must be set and the file header must be saved via SetFileHeaderBytes() and SaveFileHeader(), respectively. This method must be called only after StartProcess() has returned and before EndProcess() is called.
Returns
char* Pointer to file header, if saved.
Exceptions
Isis::iException::Message "File header was not saved. Use SaveFileHeader()."
See also
SetFileHeaderBytes()
SaveFileHeader()
References _FILEINFO_, and Isis::IException::Programmer.
FileHeaderBytes()
int Isis::ProcessImport::FileHeaderBytes () const inherited
This method returns the number of file header bytes.
FileTrailer()
char * Isis::ProcessImport::FileTrailer () inherited
This method returns a pointer to the file trailer.
A file trailer is a block of non-image data at the end of the entire file. This does not include any section trailers, such as band trailers or line suffixes. In order to retrieve this data, the file trailer bytes must be set and the file trailer must be saved via SetFileTrailerBytes() and SaveFileTrailer(), respectively. This method must be called only after StartProcess() has returned and before EndProcess() is called.
Returns
char* Pointer to file trailer, if saved.
Exceptions
Isis::iException::Message "File trailer was not saved. Use SaveFileTrailer()."
See also
SetFileTrailerBytes()
SaveFileTrailer()
References _FILEINFO_, and Isis::IException::Programmer.
FileTrailerBytes()
int Isis::ProcessImport::FileTrailerBytes () const inherited
This method returns the number of file trailer bytes.
Finalize()
void Isis::Process::Finalize () virtual inherited
Cleans up by closing cubes and freeing memory for owned cubes.
Clears the lists for all cubes.
Reimplemented in Isis::ProcessPolygons, Isis::ProcessImportPds, Isis::ProcessGroundPolygons, Isis::ProcessByTile, Isis::ProcessByBrick, and Isis::ProcessByBoxcar.
Referenced by Isis::ProcessByBoxcar::Finalize().
fitsImageLabel()
PvlGroup Isis::ProcessImportFits::fitsImageLabel (int labelNumber) const
Supplies the FITS image label corresponding to the given index.
Zero returns the first label that precedes actual image data. Extra labels that have no data can be accessed by calling extraFitsLabel().
See also
extraFitsLabel()
Parameters
labelNumber The index to the FITS header image label.
Returns
PvlGroup version of a FITS label corresponding to requested label number.
References _FILEINFO_, Isis::FileName::expanded(), Isis::IException::Programmer, Isis::FileName::toString(), and Isis::IException::User.
Referenced by setFitsFile().
InputFile()
QString Isis::ProcessImport::InputFile () inherited
Sets the name of the input file to be read in the import StartProcess method and verifies its existance.
Parameters
file The name of the input file to import.
Exceptions
Isis::iException::Message "File does not exist."
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by setProcessFileStructure().
IsVAXSpecial()
bool Isis::ProcessImport::IsVAXSpecial (unsigned int * vax, VAXSpecialPixel pix) inherited
Determines if the VAX encoded pixel value is special or not.
Parameters
vax A pointer to a VAX pixel
pix An enumerated value indicating the VAX pixel type
Returns
bool Returns true if the bit pattern for the enumerated type matches that pointed to by vax. Returns false otherwise.
References Isis::ProcessImport::VAX_HIS4, Isis::ProcessImport::VAX_HRS4, Isis::ProcessImport::VAX_LIS4, Isis::ProcessImport::VAX_LRS4, Isis::ProcessImport::VAX_MIN4, and Isis::ProcessImport::VAX_NULL4.
Lines()
int Isis::ProcessImport::Lines () inline inherited
Returns the number of lines.
Returns
The number of lines
MissionData()
QString Isis::Process::MissionData (const QString & mission, const QString & file, bool highestVersion = false) inherited
This method reads the mission specific data directory from the user preference file, makes sure that mission is available in the Isis installation, and the attaches the provided input file to the directory in order to create a full file specification.
Parameters
mission Name of the mission data directory
file Name of the file to attach to the end of the directory
highestVersion If set to true the method will return the highest version number of the given file. Therefore, file must contain question marks such as "file???.dat". See the FileName class for more information on versioned files. Defaults to false.
References _FILEINFO_, Isis::FileName::expanded(), Isis::FileName::fileExists(), Isis::PvlObject::findGroup(), Isis::FileName::highestVersion(), Isis::FileName::original(), and Isis::Preference::Preferences().
Organization()
ProcessImport::Interleave Isis::ProcessImport::Organization () const inherited
Gets the organization of the input cube.
Referenced by setProcessFileStructure().
PixelType()
Isis::PixelType Isis::ProcessImport::PixelType () inline inherited
Returns the pixel type.
Returns
The pixel type of input data
ProcessBil()
void Isis::ProcessImport::ProcessBil (void functIsis::Buffer &out = NULL) inherited
Function to process files stored as Band Interleaved by Line.
Parameters
funct Method that accepts Isis::Buffer as an input parameter, processes the image, and has no return value.
Exceptions
Isis::iException::Message "Cannot open input file."
Isis::iException::Message "Cannot read file. Position[]. Byte count[]"
References _FILEINFO_, Isis::ByteOrderName(), Isis::Progress::CheckStatus(), Isis::EndianSwapper::Double(), Isis::Double, Isis::FileName::expanded(), Isis::EndianSwapper::Float(), Isis::EndianSwapper::Int(), Isis::IException::Io, Isis::IsValidPixel(), Isis::Process::OutputCubes, Isis::Process::p_progress, Isis::Real, Isis::Progress::SetMaximumSteps(), Isis::EndianSwapper::ShortInt(), Isis::SignedInteger, Isis::SignedWord, Isis::SizeOf(), Isis::ProcessImport::TestPixel(), Isis::toString(), Isis::EndianSwapper::Uint32_t(), Isis::UnsignedByte, Isis::UnsignedInteger, Isis::EndianSwapper::UnsignedShortInt(), Isis::UnsignedWord, and Isis::ProcessImport::VAXConversion().
Referenced by Isis::ProcessImport::StartProcess().
ProcessBip()
void Isis::ProcessImport::ProcessBip (void functIsis::Buffer &out = NULL) inherited
Function to process files stored as Band Interleaved by Pixel.
Parameters
funct Method that accepts Isis::Buffer as an input parameter, processes the image, and has no return value.
Exceptions
Isis::iException::Message "Cannot open input file."
Isis::iException::Message "Cannot read file. Position[]. Byte count[]"
References _FILEINFO_, Isis::ByteOrderName(), Isis::Progress::CheckStatus(), Isis::EndianSwapper::Double(), Isis::Double, Isis::FileName::expanded(), Isis::EndianSwapper::Float(), Isis::EndianSwapper::Int(), Isis::IException::Io, Isis::IsValidPixel(), Isis::Process::OutputCubes, Isis::Process::p_progress, Isis::Real, Isis::Progress::SetMaximumSteps(), Isis::EndianSwapper::ShortInt(), Isis::SignedInteger, Isis::SignedWord, Isis::SizeOf(), Isis::ProcessImport::TestPixel(), Isis::toString(), Isis::EndianSwapper::Uint32_t(), Isis::UnsignedByte, Isis::UnsignedInteger, Isis::EndianSwapper::UnsignedShortInt(), Isis::UnsignedWord, and Isis::ProcessImport::VAXConversion().
Referenced by Isis::ProcessImport::StartProcess().
ProcessBsq()
void Isis::ProcessImport::ProcessBsq (void functIsis::Buffer &out = NULL) inherited
Process the import data as a band sequential file.
Parameters
funct Method that accepts Isis::Buffer as an input parameter, processes the image, and has no return value.
Exceptions
Isis::iException::Message "Cannot open input file."
Isis::iException::Message "Cannot read file. Position[]. Byte count[]"
References _FILEINFO_, Isis::ByteOrderName(), Isis::Progress::CheckStatus(), Isis::EndianSwapper::Double(), Isis::Double, Isis::FileName::expanded(), Isis::EndianSwapper::Float(), Isis::EndianSwapper::Int(), Isis::IException::Io, Isis::IsValidPixel(), Isis::Process::OutputCubes, Isis::Process::p_progress, Isis::Real, Isis::Progress::SetMaximumSteps(), Isis::EndianSwapper::ShortInt(), Isis::SignedInteger, Isis::SignedWord, Isis::SizeOf(), Isis::ProcessImport::TestPixel(), Isis::toString(), Isis::EndianSwapper::Uint32_t(), Isis::UnsignedByte, Isis::UnsignedInteger, Isis::EndianSwapper::UnsignedShortInt(), Isis::UnsignedWord, and Isis::ProcessImport::VAXConversion().
Referenced by Isis::ProcessImport::StartProcess().
ProcessJp2()
void Isis::ProcessImport::ProcessJp2 (void functIsis::Buffer &out = NULL) inherited
Function to process files containing compressed JPEG2000 data (which is always BSQ but is processed as BIL with one or more lines stored sequentially for each band).
There is no need to set up an Isis::EndianSwapper because JP2 data is always assumed to be in MSB format. The Kakadu library does an automatic byte swap for the current architecture.
Parameters
funct Method that accepts Isis::Buffer as an input parameter, processes the image, and has no return value.
Exceptions
Isis::iException::Message "Cannot open input file."
Isis::iException::Message "Cannot read file. Position[]. Byte count[]"
References Isis::Progress::CheckStatus(), Isis::JP2Decoder::GetBandDimension(), Isis::JP2Decoder::GetLineDimension(), Isis::JP2Decoder::GetSampleDimension(), Isis::IsValidPixel(), Isis::JP2Decoder::OpenFile(), Isis::Process::OutputCubes, Isis::Process::p_progress, Isis::JP2Decoder::Read(), Isis::Progress::SetMaximumSteps(), Isis::SignedWord, Isis::SizeOf(), Isis::ProcessImport::TestPixel(), Isis::UnsignedByte, and Isis::UnsignedWord.
Referenced by Isis::ProcessImport::StartProcess().
Progress()
Isis::Progress* Isis::Process::Progress () inline inherited
This method returns a pointer to a Progress object.
Returns
Progress*
References Isis::Process::p_progress.
Referenced by Isis::Equalization::applyCorrection(), Isis::Equalization::calculateBandStatistics(), Isis::HiEqualization::calculateStatistics(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::SpectralDefinition2D::SpectralDefinition2D().
PropagateHistory()
void Isis::Process::PropagateHistory (const bool prop) inherited
This method allows the programmer to propagate history to the output cube (default is true)
Parameters
prop Flag indicating if history is to be propagated to output cubes.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
PropagateLabels() [1/2]
void Isis::Process::PropagateLabels (const bool prop) inherited
This method allows the programmer to turn on/off the propagation of labels from the 1st input cube to any of the output cubes.
By default, propagation occurs automatically in the Process class when a call to either of the SetOutputCube methods is invoked. If the program * requires no propagation then utilize this method. This method can be invoked between successive calls of SetOutputCube so that some cube will have labels propagated while others will not.
Parameters
prop Flag indicating if labels are be propagated to output cubes.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
PropagateLabels() [2/2]
void Isis::Process::PropagateLabels (const QString & cube) inherited
This method allows the programmer to propagate labels from a specific secondary cube.
Parameters
cube IString containing the name of the cube containing the labels to propagate.
References Isis::PvlObject::addGroup(), Isis::PvlObject::addObject(), Isis::PvlObject::findObject(), Isis::PvlObject::group(), Isis::PvlObject::groups(), and Isis::PvlObject::hasObject().
PropagateOriginalLabel()
void Isis::Process::PropagateOriginalLabel (const bool prop) inherited
This method allows the programmer to propagate original labels to the output cube (default is true)
Parameters
prop Flag indicating if original labels is to be propagated to output cubes.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
PropagatePolygons()
void Isis::Process::PropagatePolygons (const bool prop) inherited
This method allows the programmer to propagate input blobs to the output cube (default is true)
Parameters
prop Flag indicating if input blobs are to be propagated to output cubes.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
PropagateTables() [1/2]
void Isis::Process::PropagateTables (const bool prop) inherited
This method allows the programmer to propagate input tables to the output cube (default is true)
Parameters
prop Flag indicating if input tables are to be propagated to output cubes.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
PropagateTables() [2/2]
void Isis::Process::PropagateTables (const QString & fromName, const QList< QString > & tableNames = QList<QString>()) inherited
Propagate the tables from the cube with the given filename to the output cube.
This is done at the time this method is called, not during normal processing. The names of the tables to propagate can be provided through the second paramter, by specifing a list of table names. Not providing any list (or providing an empty list) will propagate all tables.
Parameters
fromName QString of the name of the cube containing the tables to propagate.
tableNames List of QStrings of the names of the tables to propagate; default is empty, which indicates that all tables will be propagated.
References Isis::Cube::close(), Isis::Cube::label(), Isis::PvlObject::object(), Isis::PvlObject::objects(), Isis::Cube::open(), and Isis::Cube::read().
Samples()
int Isis::ProcessImport::Samples () inline inherited
Returns the number of samples.
Returns
The number of samples
SaveDataHeader()
void Isis::ProcessImport::SaveDataHeader () inherited
This method marks the data block headers to be saved.
A data header is a block of non-image data at the beginning of each data block (for BSQ data blocks are bands). This is not included in the file header and does not include any record headers, such as line prefixes. Each of the header blocks will be saved inside StartProcess(). It must be called after setting the size with SetDataHeaderBytes() and before StartProcess() is called. This data will only be available via DataHeader() after StartProcess() has returned and before EndProcess() is called.
Exceptions
Isis::iException::Message "Data header bytes equals 0. There is nothing to save. Use SetDataHeaderBytes() first."
See also
SetDataHeaderBytes()
DataHeader()
References _FILEINFO_, and Isis::IException::Programmer.
SaveDataPrefix()
void Isis::ProcessImport::SaveDataPrefix () inherited
This method marks the data prefix to be saved.
A data prefix is a block of non-image data at the beginning of each data record (for BSQ data records are lines). This is not included in the file header or the data header. Each of the data prefixes will be saved inside StartProcess(). It must be called after setting the size with SetDataPrefixBytes() and before StartProcess() is called. This data will only be available via DataPrefix() after StartProcess() has returned and before EndProcess() is called.
Exceptions
Isis::iException::Message "Data prefix bytes equals 0. There is nothing to save. Use SetDataPrefixBytes() first."
See also
SetDataPrefixBytes()
DataPrefix()
References _FILEINFO_, and Isis::IException::Programmer.
SaveDataSuffix()
void Isis::ProcessImport::SaveDataSuffix () inherited
This method marks the data suffix to be saved.
A data suffix is a block of non-image data at the end of each data record (for BSQ data records are lines). This is not included in the file trailer or the data trailer. Each of the data suffixes will be saved inside StartProcess(). It must be called after setting the size with SetDataPrefixBytes() and before StartProcess() is called. This data will only be available via DataPrefix() after StartProcess() has returned and before EndProcess() is called.
Exceptions
Isis::iException::Message "Data suffix bytes equals 0. There is nothing to save. Use SetDataSuffixBytes() first."
See also
SetDataSuffixBytes()
DataSuffix()
References _FILEINFO_, and Isis::IException::Programmer.
SaveDataTrailer()
void Isis::ProcessImport::SaveDataTrailer () inherited
This method marks the data block trailers to be saved.
A data trailer is a block of non-image data at the end of each data block (for BSQ data blocks are bands). This is not included in the file trailer and does not include any record trailers, such as line suffixes. Each of the trailer blocks will be saved inside StartProcess(). It must be called after setting the size with SetDataTrailerBytes() and before StartProcess() is called. This data will only be available via DataTrailer() after StartProcess() has returned and before EndProcess() is called.
Exceptions
Isis::iException::Message "Data trailer bytes equals 0. There is nothing to save. Use SetDataTrailerBytes() first."
See also
SetDataTrailerBytes()
DataTrailer()
References _FILEINFO_, and Isis::IException::Programmer.
SaveFileHeader()
void Isis::ProcessImport::SaveFileHeader () inherited
This method marks the file header to be saved.
A file header is a block of non-image data at the beginning of the entire file. This does not include any section headers, such as band headers or line prefixes. The file header will be saved inside StartProcess(). It must be called after setting the size with SetFileHeaderBytes() and before StartProcess() is called. This data will only be available via FileHeader() after StartProcess() has returned and before EndProcess() is called.
Exceptions
Isis::iException::Message "File header bytes equals 0. There is nothing to save. Use SetFileHeaderBytes() first."
See also
SetFileHeaderBytes()
FileHeader()
References _FILEINFO_, and Isis::IException::Programmer.
SaveFileTrailer()
void Isis::ProcessImport::SaveFileTrailer () inherited
This method marks the file trailer to be saved.
A file trailer is a block of non-image data at the end of the entire file. This does not include any section trailers, such as band trailers or line suffixes. The file trailer will be saved inside StartProcess(). It must be called after setting the size with SetFileTrailerBytes() and before StartProcess() is called. This data will only be available via FileTrailer() after StartProcess() has returned and before EndProcess() is called.
Exceptions
Isis::iException::Message "File trailer bytes equals 0. There is nothing to save. Use SetFileTrailerBytes() first."
See also
SetFileTrailerBytes()
FileTrailer()
References _FILEINFO_, and Isis::IException::Programmer.
SetAttributes()
void Isis::ProcessImport::SetAttributes (CubeAttributeOutput & att) inherited
Given a CubeAttributeOutput object, set min/max to propagate if propagating min/max attributes was requested and set the pixel type to propagate if pixel type propagation was requested.
Parameters
parameter The parameter name that holds the output file name.
Exceptions
Isis::iException::Message "Unsupported pixel type."
References _FILEINFO_, Isis::Double, Isis::IVALID_MAX4, Isis::IVALID_MIN4, Isis::PixelTypeName(), Isis::IException::Programmer, Isis::CubeAttributeOutput::propagateMinimumMaximum(), Isis::CubeAttributeOutput::propagatePixelType(), Isis::Real, Isis::CubeAttributeOutput::setMaximum(), Isis::CubeAttributeOutput::setMinimum(), Isis::CubeAttributeOutput::setPixelType(), Isis::SignedInteger, Isis::SignedWord, Isis::UnsignedByte, Isis::UnsignedInteger, Isis::UnsignedWord, Isis::VALID_MAX1, Isis::VALID_MAX2, Isis::VALID_MAX4, Isis::VALID_MAXU2, Isis::VALID_MAXUI4, Isis::VALID_MIN1, Isis::VALID_MIN2, Isis::VALID_MIN4, Isis::VALID_MINU2, and Isis::VALID_MINUI4.
Referenced by Isis::ProcessImport::SetOutputCube().
SetBase() [1/2]
void Isis::ProcessImport::SetBase (const double base) inherited
Sets the core base of the input cube.
Defaults to zero if not invoked.
Parameters
base Core base
Referenced by setProcessFileStructure().
SetBase() [2/2]
void Isis::ProcessImport::SetBase (const std::vector< double > base) inherited
Sets band dependent core base.
Parameters
base A vector containing the base for each band.
SetByteOrder()
void Isis::ProcessImport::SetByteOrder (const Isis::ByteOrder order) inherited
Sets the byte order of the input file.
This must be invoked prior to SetOutputCube.
Parameters
order The enumerated byte order Isis::Lsb or Isis::Msb
Referenced by setProcessFileStructure().
SetDataHeaderBytes()
void Isis::ProcessImport::SetDataHeaderBytes (const int bytes) inherited
This method sets the number of bytes in the header of each datablock of a file.
A data header is a block of non-image data at the beginning of each data block (for BSQ data blocks are bands). This is not included in the file header and does not include any record headers, such as line prefixes. It must be called before StartProcess(). This data will only be available if saved via SaveDataHeader() and may be accessed via DataHeader() after StartProcess() has returned and before EndProcess() is called. If not invoked the default is 0.
Parameters
bytes Number of bytes
Exceptions
Isis::iException::Message "Illegal data header size." (when bytes < 0)
See also
SaveDataHeader()
DataHeader()
References _FILEINFO_, Isis::IException::Programmer, and Isis::toString().
SetDataPrefixBytes()
void Isis::ProcessImport::SetDataPrefixBytes (const int bytes) inherited
This method sets the number of bytes at the beginning of each data record of a file.
A data prefix is a block of non-image data at the beginning of each data record (for BSQ data records are lines). This is not included in the file header or the data header. It must be called before StartProcess(). This data will only be available if saved via SaveDataPrefix() and may be accessed via DataPrefix() after StartProcess() has returned and before EndProcess() is called. If not invoked the default is 0.
Parameters
bytes Number of bytes
Exceptions
Isis::iException::Message "Illegal data prefix size." (when bytes < 0)
See also
SaveDataPrefix()
DataPrefix()
References _FILEINFO_, Isis::IException::Programmer, and Isis::toString().
SetDataSuffixBytes()
void Isis::ProcessImport::SetDataSuffixBytes (const int bytes) inherited
This method sets the number of bytes at the end of each data record of a file.
A data suffix is a block of non-image data at the end of each data record (for BSQ data records are lines). This is not included in the file trailer or the data trailer. It must be called before StartProcess(). This data will only be available if saved via SaveDataSuffix() and may be accessed via DataSuffix() after StartProcess() has returned and before EndProcess() is called. If not invoked the default is 0.
Parameters
bytes Number of bytes
Exceptions
Isis::iException::Message "Illegal data suffix size." (when bytes < 0)
See also
SaveDataSuffix()
DataSuffix()
References _FILEINFO_, Isis::IException::Programmer, and Isis::toString().
SetDataTrailerBytes()
void Isis::ProcessImport::SetDataTrailerBytes (const int bytes) inherited
This method sets the number of bytes in the trailer of each datablock of a file.
A data trailer is a block of non-image data at the end of each data block (for BSQ data blocks are bands). This is not included in the file trailer and does not include any record trailers, such as line suffixes. It must be called before StartProcess(). This data will only be available if saved via SaveDataTrailer() and may be accessed via DataTrailer() after StartProcess() has returned and before EndProcess() is called. If not invoked the default is 0.
Parameters
bytes Number of bytes
Exceptions
Isis::iException::Message "Illegal data trailer size." (when bytes < 0)
See also
SaveDataTrailer()
DataTrailer()
References _FILEINFO_, Isis::IException::Programmer, and Isis::toString().
SetDimensions()
void Isis::ProcessImport::SetDimensions (const int ns, const int nl, const int nb) inherited
Sets the physical size of the input cube.
This must be invoked prior to setOutputCube.
Parameters
ns Number of samples
nl Number of lines
nb Number of bands
Exceptions
Isis::iException::Message "Illegal dimension."
References _FILEINFO_, Isis::IException::Programmer, and Isis::toString().
Referenced by setProcessFileStructure().
SetFileHeaderBytes()
void Isis::ProcessImport::SetFileHeaderBytes (const int bytes) inherited
This method sets the number of bytes in the header of a file.
The file header is a block of non-image data at the beginning of the entire file. This does not include any section headers, such as band headers or line prefixes. Typically it is used to delineate the boundary of the binary or ascii labels. It must be called before StartProcess(). This data will only be available if saved via SaveFileHeader() and may be accessed via FileHeader() after StartProcess() has returned and before EndProcess() is called. If not invoked the default is 0.
Parameters
bytes Number of bytes
Exceptions
Isis::iException::Message "Illegal file header size." (when bytes < 0)
See also
SaveFileHeader()
FileHeader()
References _FILEINFO_, Isis::IException::Programmer, and Isis::toString().
Referenced by setProcessFileStructure().
SetFileTrailerBytes()
void Isis::ProcessImport::SetFileTrailerBytes (const int bytes) inherited
This method sets the number of bytes in the trailer of a file.
The trailer is a block of non-image data at the end of the entire file. This does not include any section trailers, such as band trailers or line suffixes. It must be called before StartProcess(). This data will only be available if saved via SaveFileTrailer() and may be accessed via FileTrailer() after StartProcess() has returned and before EndProcess() is called. If not invoked the default is 0.
Parameters
bytes Number of bytes
Exceptions
Isis::iException::Message "Illegal file trailer size." (when bytes < 0)
See also
SaveFileTrailer()
FileTrailer()
History:
2008-08-12 Jeannie Walldren, Method created
References _FILEINFO_, Isis::IException::Programmer, and Isis::toString().
setFitsFile()
void Isis::ProcessImportFits::setFitsFile (FileName fitsFile)
Opens a FITS image file with header and reads the FITS labels.
Note: This method does not handle detached label files.
Parameters
fitsFile Name of the FITS file to open.
References _FILEINFO_, Isis::FileName::expanded(), fitsImageLabel(), Isis::PvlContainer::hasKeyword(), Isis::ProcessImport::SetInputFile(), Isis::FileName::toString(), and Isis::IException::User.
SetHIS()
void Isis::ProcessImport::SetHIS (const double his_min, const double his_max) inherited
Sets the range that will be considered Isis::Null.
Parameters
his_min The double precision value used to identify the min range of his pixels in the image being imported.
his_max The double precision value used to identify the max range of his pixels in the image being imported.
References Isis::ProcessImport::CheckPixelRange().
Referenced by Isis::ProcessImport::ProcessImport(), and Isis::ProcessImport::SetSpecialValues().
SetHRS()
void Isis::ProcessImport::SetHRS (const double hrs_min, const double hrs_max) inherited
Sets the range that will be considered Isis::Null.
Parameters
hrs_min The double precision value used to identify the min range of hrs pixels in the image being imported.
hrs_max The double precision value used to identify the max range of hrs pixels in the image being imported.
References Isis::ProcessImport::CheckPixelRange().
Referenced by Isis::ProcessImport::ProcessImport(), and Isis::ProcessImport::SetSpecialValues().
SetInputCube() [1/3]
Isis::Cube * Isis::Process::SetInputCube (const QString & fname, const Isis::CubeAttributeInput & att, int requirements = 0) virtual inherited
Opens an input cube specified by the programmer and verifies requirements are met.
Parameters
fname Programmer specified work file. For example, "myfile.cub".
att The cube attributes to use when opening the input cube.
requirements Requirements to check that the input cube meets. See CheckRequirements().
Returns
Cube*
Exceptions
Isis::iException::Message
Reimplemented in Isis::ProcessByBrick.
References Isis::CubeAttributeInput::bands(), Isis::Cube::open(), Isis::ReadWrite, and Isis::Cube::setVirtualBands().
SetInputCube() [2/3]
Isis::Cube * Isis::Process::SetInputCube (const QString & parameter, const int requirements = 0) virtual inherited
Opens an input cube specified by the user and verifies requirements are met.
Returns
Cube*
Parameters
parameter User parameter to obtain file to open. Typically, the value is "FROM". For example, the user can specify on the command line FROM=myfile.cub and this method will attempt to open the cube "myfile.cub" if the parameter was set to "FROM".
requirements Requirements to check that the input cube meets. See CheckRequirements().
Exceptions
Isis::iException::Message
Reimplemented in Isis::ProcessBySample, Isis::ProcessByBrick, Isis::ProcessBySpectra, and Isis::ProcessByLine.
Referenced by Isis::ProcessGroundPolygons::SetStatCubes().
SetInputCube() [3/3]
void Isis::Process::SetInputCube (Isis::Cube * inCube, int requirements = 0) virtual inherited
Set the InputCube vector to an opened Cube which was dynamically allocated.
This is used if there already exists a valid opened cube
Author
Sharmila Prasad (5/7/2011)
Parameters
inCube - Pointer to input Cube
requirements Requirements to check that the input cube meets. See CheckRequirements().
References _FILEINFO_, and Isis::Cube::isOpen().
SetInputFile()
void Isis::ProcessImport::SetInputFile (const QString & file) inherited
Sets the name of the input file to be read in the import StartProcess method and verifies its existance.
Parameters
file The name of the input file to import.
Exceptions
Isis::iException::Message "File does not exist."
References _FILEINFO_, and Isis::IException::User.
Referenced by setFitsFile().
SetLIS()
void Isis::ProcessImport::SetLIS (const double lis_min, const double lis_max) inherited
Sets the range that will be considered Isis::Null.
Parameters
lis_min The double precision value used to identify the min range of lis pixels in the image being imported.
lis_max The double precision value used to identify the max range of lis pixels in the image being imported.
References Isis::ProcessImport::CheckPixelRange().
Referenced by Isis::ProcessImport::ProcessImport(), and Isis::ProcessImport::SetSpecialValues().
SetLRS()
void Isis::ProcessImport::SetLRS (const double lrs_min, const double lrs_max) inherited
Sets the range that will be considered Isis::Null.
Parameters
lrs_min The double precision value used to identify the min range of lrs pixels in the image being imported.
lrs_max The double precision value used to identify the max range of lrs pixels in the image being imported.
References Isis::ProcessImport::CheckPixelRange().
Referenced by Isis::ProcessImport::ProcessImport(), and Isis::ProcessImport::SetSpecialValues().
SetMultiplier() [1/2]
void Isis::ProcessImport::SetMultiplier (const double mult) inherited
Sets the core multiplier of the input cube.
Defaults to one if not invoked.
Parameters
mult Core base
Referenced by setProcessFileStructure().
SetMultiplier() [2/2]
void Isis::ProcessImport::SetMultiplier (const std::vector< double > mult) inherited
Sets band dependent core multiplier.
Parameters
mult A vector containing the multiplier for each band.
SetNull()
void Isis::ProcessImport::SetNull (const double null_min, const double null_max) inherited
Sets the range that will be considered Isis::Null.
Parameters
null_min The double precision value used to identify the min range of null pixels in the image being imported.
null_max The double precision value used to identify the max range of null pixels in the image being imported.
References Isis::ProcessImport::CheckPixelRange().
Referenced by Isis::ProcessImport::ProcessImport(), and Isis::ProcessImport::SetSpecialValues().
SetOrganization()
void Isis::ProcessImport::SetOrganization (const ProcessImport::Interleave org) inherited
Sets the organization of the input cube.
If not invoked it is assumed Isis::Import::Bsq.
Parameters
org The enumerated organizations either Isis::Import::Bsq Isis::Import::Bil or Isis::Import::Bip
SetOutputCube() [1/5]
Isis::Cube * Isis::Process::SetOutputCube (const QString & fname, const Isis::CubeAttributeOutput & att, const int ns, const int nl, const int nb = 1) virtual inherited
Allocates a output cube whose name and size is specified by the programmer.
Returns
Cube*
Parameters
fname Name of the output cube to allocate
att The cube attributes to use when creating the output cube.
ns Number of samples to allocate
nl Number of lines to allocate
nb Number of bands to allocate
Exceptions
Isis::iException::Message
References _FILEINFO_, Isis::PvlObject::addGroup(), Isis::PvlObject::addObject(), Isis::AttachedLabel, Isis::CubeAttributeOutput::byteOrder(), Isis::Cube::create(), Isis::CubeAttributeOutput::fileFormat(), Isis::PvlObject::findObject(), Isis::PvlObject::group(), Isis::PvlObject::groups(), Isis::PvlContainer::isNamed(), Isis::Cube::label(), Isis::CubeAttributeOutput::labelAttachment(), Isis::Cube::labelSize(), Isis::CubeAttributeOutput::maximum(), Isis::CubeAttributeOutput::minimum(), Isis::PvlContainer::name(), Isis::PvlObject::object(), Isis::PvlObject::objects(), Isis::Cube::pixelType(), Isis::CubeAttributeOutput::pixelType(), Isis::CubeAttributeOutput::propagateMinimumMaximum(), Isis::CubeAttributeOutput::propagatePixelType(), Isis::Real, Isis::Cube::setBaseMultiplier(), Isis::Cube::setByteOrder(), Isis::Cube::setDimensions(), Isis::Cube::setFormat(), Isis::Cube::setLabelsAttached(), Isis::Cube::setLabelSize(), Isis::Cube::setMinMax(), Isis::Cube::setPixelType(), Isis::SignedInteger, Isis::SignedWord, Isis::UnsignedByte, Isis::UnsignedInteger, Isis::UnsignedWord, and Isis::Cube::write().
SetOutputCube() [2/5]
Isis::Cube * Isis::ProcessImport::SetOutputCube (const QString & fname, Isis::CubeAttributeOutput & att) virtual inherited
Create the output file.
Note that all the appropiate calls to at least SetDimensions should be invoked prior to calling this method.
Parameters
fname The output file name.
att An output cube attribute to define the characteristics of the output cube.
Returns
Isis::Cube Output cube.
Exceptions
Isis::iException::Message "File is not in a supported organization."
References Isis::ProcessImport::SetAttributes(), and Isis::Process::SetOutputCube().
SetOutputCube() [3/5]
Isis::Cube * Isis::ProcessImport::SetOutputCube (const QString & parameter) virtual inherited
Create the output file.
Note that all the appropriate calls to at least SetDimensions and SetPixelType should be made prior to calling this method.
Parameters
parameter The parameter name that holds the output file name.
Returns
Isis::Cube Output cube.
Exceptions
Isis::iException::Message "Unsupported pixel type."
Reimplemented from Isis::Process.
References IsisAml::GetOutputAttribute(), Isis::Application::GetUserInterface(), Isis::ProcessImport::SetAttributes(), and Isis::Process::SetOutputCube().
SetOutputCube() [4/5]
Isis::Cube * Isis::Process::SetOutputCube (const QString & parameter, const int ns, const int nl, const int nb = 1) virtual inherited
Allocates a user specified output cube whose size is specified by the programmer.
Returns
Cube*
Parameters
parameter User specified output file. For example, "TO" is a popular user parameter. If the user specified TO=output.cub, then this routine would allocate the file output.cub with size specified by the first opened input cube. The output pixel type will be propagated from the first loaded input cube or will use the value in the application XML file for pixelType.
ns Number of samples to allocate
nl Number of lines to allocate
nb Number of bands to allocate
Exceptions
Isis::iException::Message
References _FILEINFO_.
SetOutputCube() [5/5]
Isis::Cube * Isis::ProcessImport::SetOutputCube (const QString & parameter, UserInterface & ui) inherited
Create the output file.
References IsisAml::GetCubeName(), IsisAml::GetOutputAttribute(), Isis::ProcessImport::SetAttributes(), and Isis::Process::SetOutputCube().
SetOutputCubeStretch() [1/2]
Isis::Cube * Isis::Process::SetOutputCubeStretch (const QString & parameter, const int ns, const int nl, const int nb = 1, UserInterface * ui = nullptr) virtual inherited
Allocates a user specified output cube whose size is specified by the programmer.
Returns
Cube*
Parameters
parameter User specified output file. For example, "TO" is a popular user parameter. If the user specified TO=output.cub, then this routine would allocate the file output.cub with size specified by the first opened input cube. The output pixel type will be propagated from the first loaded input cube or will use the value in the application XML file for pixelType.
ns Number of samples to allocate
nl Number of lines to allocate
nb Number of bands to allocate
ui A user interface used to get the attributes needed. If null, the user interface will be obtained from the application.
Exceptions
Isis::iException::Message
References _FILEINFO_, IsisAml::GetCubeName(), and IsisAml::GetOutputAttribute().
SetOutputCubeStretch() [2/2]
Isis::Cube * Isis::Process::SetOutputCubeStretch (const QString & parameter, UserInterface * ui = nullptr) virtual inherited
Allocates a user-specified output cube whose size matches the first input cube.
Returns
Cube*
Parameters
parameter User specified output file. For example, "TO" is a popular user parameter. If the user specified TO=output.cub, then this routine would allocate the file output.cub with size specified by the first opened input cube. The output pixel type will be propagated from the first loaded input cube or will use the value in the application XML file for pixelType.
ui A user interface used to get the attributes needed for SetOutputCube.
Exceptions
Isis::iException::Message
References _FILEINFO_.
SetPixelType()
void Isis::ProcessImport::SetPixelType (const Isis::PixelType type) inherited
Sets the pixel type of the input file.
Parameters
type The enumerated pixel type Isis::Real, Isis::SignedWord, or Isis::UnsignedByte. This must be invoked prior to setOutputCube
Exceptions
Isis::iException::Message "Unsupported pixel type."
References _FILEINFO_, Isis::Double, Isis::PixelTypeName(), Isis::IException::Programmer, Isis::Real, Isis::SignedInteger, Isis::SignedWord, Isis::UnsignedByte, Isis::UnsignedInteger, and Isis::UnsignedWord.
Referenced by setProcessFileStructure().
setProcessFileStructure()
void Isis::ProcessImportFits::setProcessFileStructure (int labelNumber)
Sets the Process file structure parameters based on the given image label index.
NOTE: The (DataPrefixBytes + DataSuffixByte) / PixelSize is subtracted from the number of samples before the output file is created.
Parameters
labelNumber FITS image index. Zero indicates the first image label, one indicates the first image extension, etc...
References _FILEINFO_, Isis::ProcessImport::BIL, Isis::ProcessImport::BIP, Isis::ProcessImport::BSQ, Isis::ProcessImport::DataPrefixBytes(), Isis::ProcessImport::DataSuffixBytes(), Isis::Double, Isis::PvlContainer::hasKeyword(), Isis::ProcessImport::InputFile(), Isis::Msb, Isis::ProcessImport::Organization(), Isis::Real, Isis::ProcessImport::SetBase(), Isis::ProcessImport::SetByteOrder(), Isis::ProcessImport::SetDimensions(), Isis::ProcessImport::SetFileHeaderBytes(), Isis::ProcessImport::SetMultiplier(), Isis::ProcessImport::SetPixelType(), Isis::SignedInteger, Isis::SignedWord, Isis::SizeOf(), Isis::toDouble(), Isis::toInt(), Isis::UnsignedByte, and Isis::IException::User.
SetSpecialValues()
void Isis::ProcessImport::SetSpecialValues (const double null, const double lrs, const double lis, const double hrs, const double his) inherited
Sets a mapping of input pixel values to output special pixel values.
Parameters
null The double precision value used to identify null pixels in the image being imported.
lrs The double precisiion value used to identify low representation saturation LRS pixels in the image being imported.
lis The double precision value used to identify low instrument saturation LIS pixels in the image being imported.
hrs The double precision value used to identify high representation saturation HRS pixels in the image being imported.
his The double precision value used to identify high instrument saturation HIS pixels in the image being imported.
References Isis::ProcessImport::SetHIS(), Isis::ProcessImport::SetHRS(), Isis::ProcessImport::SetLIS(), Isis::ProcessImport::SetLRS(), and Isis::ProcessImport::SetNull().
SetSuffixOffset()
void Isis::ProcessImport::SetSuffixOffset (int samples, int lines, int coreBands, int itemBytes) inherited
SetSuffixPixelType()
void Isis::ProcessImport::SetSuffixPixelType (const Isis::PixelType type) inherited
References _FILEINFO_, Isis::Double, Isis::PixelTypeName(), Isis::IException::Programmer, Isis::Real, Isis::SignedWord, Isis::UnsignedByte, and Isis::UnsignedWord.
SetVAXConvert()
void Isis::ProcessImport::SetVAXConvert (const bool vax_convert) inherited
Sets the VAX flag of the input cube.
If true, then the core pixel type of the input cube is VAX, and VAX conversion routines need to be run to convert the pixels to IEEE format.
Parameters
vax_convert Flag indicating whether or not to run VAX conersion methods
standardInstrumentGroup()
PvlGroup Isis::ProcessImportFits::standardInstrumentGroup (PvlGroup fitsLabel) const
Return a PVL instrument group populated with expected default values.
NOTE: These values are not appropriate for all missions. See specific mission documentation to verify that these are the keywords needed.
Parameters
fitsLabel A PVL group containing keywords from the FITS label.
Returns
PvlGroup An ISIS cube instrument group filled with keywords from the given FITS label.
References Isis::PvlContainer::hasKeyword().
StartProcess() [1/3]
void Isis::ProcessImport::StartProcess () virtual inherited
Process the input file and write it to the output.
Reimplemented in Isis::ProcessImportPds, Isis::ProcessImportPds, and Isis::ProcessImportPds.
References _FILEINFO_, Isis::ProcessImport::BIL, Isis::ProcessImport::BIP, Isis::ProcessImport::BSQ, Isis::ProcessImport::JP2, Isis::ProcessImport::ProcessBil(), Isis::ProcessImport::ProcessBip(), Isis::ProcessImport::ProcessBsq(), Isis::ProcessImport::ProcessJp2(), and Isis::IException::Programmer.
StartProcess() [2/3]
virtual void Isis::Process::StartProcess (void funct()) inline virtual inherited
In the base class, this method will invoked a user-specified function exactly one time.
In derived classes such as ProcessByLine, the StartProcess will invoke a user-specified function for every line in a cube.
Parameters
funct() Name of your processing function
StartProcess() [3/3]
void Isis::ProcessImport::StartProcess (void functIsis::Buffer &out) virtual inherited
Process the input file and send data to method.
Parameters
funct Method that accepts Isis::Buffer as an input parameter, processes the image, and has no return value.
Exceptions
Isis::iException::Message "File is not a supported organization."
Reimplemented in Isis::ProcessImportPds.
References _FILEINFO_, Isis::ProcessImport::BIL, Isis::ProcessImport::BIP, Isis::ProcessImport::BSQ, Isis::ProcessImport::JP2, Isis::ProcessImport::ProcessBil(), Isis::ProcessImport::ProcessBip(), Isis::ProcessImport::ProcessBsq(), Isis::ProcessImport::ProcessJp2(), and Isis::IException::Programmer.
TestPixel()
double Isis::ProcessImport::TestPixel (const double pixel) inherited
Tests the pixel.
If it is valid it will return the dn value, otherwise it will return the Isis special pixel value that corresponds to it
Parameters
pixel The double precision value that represents a pixel.
Returns
double The double precision value representing the pixel will return as a valid dn or changed to an isis special pixel.
References Isis::HIGH_INSTR_SAT8, Isis::HIGH_REPR_SAT8, Isis::LOW_INSTR_SAT8, Isis::LOW_REPR_SAT8, and Isis::NULL8.
Referenced by Isis::ProcessImport::ProcessBil(), Isis::ProcessImport::ProcessBip(), Isis::ProcessImport::ProcessBsq(), and Isis::ProcessImport::ProcessJp2().
VAXConversion()
double Isis::ProcessImport::VAXConversion (void * ibuf) inherited
Conversion routine which translates VAX_REAL to IEEE_REAL.
Parameters
ibuf Memory buffer of input data to be converted
Returns
double the converted value
Referenced by Isis::ProcessImport::ProcessBil(), Isis::ProcessImport::ProcessBip(), and Isis::ProcessImport::ProcessBsq().
WriteHistory()
void Isis::Process::WriteHistory (Cube & cube) inherited
Writes out the History blob to the cube.
References Isis::History::AddEntry(), Isis::iApp, Isis::PvlContainer::isNamed(), Isis::PvlObject::object(), Isis::PvlObject::objects(), Isis::Cube::readHistory(), and Isis::Cube::write().
Referenced by Isis::ImageImporter::import().
Member Data Documentation
InputCubes
std::vector<Isis::Cube *> Isis::Process::InputCubes protected inherited
A vector of pointers to opened Cube objects.
The pointers are established in the SetInputCube/SetInputWorkCube methods.
Referenced by Isis::ProcessExport::CreateWorldFile(), Isis::ProcessExport::GetBuffersBIL(), Isis::ProcessExport::GetBuffersBIP(), Isis::ProcessExport::GetBuffersBSQ(), Isis::ProcessByBrick::ProcessCube(), Isis::ProcessExport::ProcessCubes(), Isis::ProcessByBrick::ProcessCubes(), Isis::ProcessExport::SetInputRange(), Isis::ProcessExport::StartProcess(), and Isis::ProcessByQuickFilter::StartProcess().
m_ownedCubes
QSet<Isis::Cube *>* Isis::Process::m_ownedCubes protected inherited
A list of cubes owned by this instant.
These cubes will be deleted on finalization. Process will not take ownership of cubes allocated outside of Process. It is the caller's responsibility to delete such cubes.
OutputCubes
std::vector<Isis::Cube *> Isis::Process::OutputCubes protected inherited
A vector of pointers to allocated Cube objects.
The pointers are established in the SetOutputCube method.
Referenced by Isis::ProcessImport::ProcessBil(), Isis::ProcessImport::ProcessBip(), Isis::ProcessImport::ProcessBsq(), Isis::ProcessByBrick::ProcessCube(), Isis::ProcessByBrick::ProcessCubes(), Isis::ProcessImport::ProcessJp2(), and Isis::ProcessByQuickFilter::StartProcess().
p_bandStats
std::vector< std::vector< Isis::Statistics * > > Isis::Process::p_bandStats protected inherited
Holds the calculated statistics for each band separately of every input cubei after the CalculateStatistics method is called.
Referenced by Isis::Process::BandStatistics().
p_cubeStats
std::vector< Isis::Statistics * > Isis::Process::p_cubeStats protected inherited
Holds the calculated statistics for every band together of every input cubei after the CalculateStatistics method is called.
Referenced by Isis::Process::CubeStatistics().
p_progress
Isis::Progress* Isis::Process::p_progress protected inherited
Pointer to a Progress object.
Referenced by Isis::ProcessImport::ProcessBil(), Isis::ProcessImport::ProcessBip(), Isis::ProcessImport::ProcessBsq(), Isis::ProcessExport::ProcessCubes(), Isis::ProcessExport::ProcessExport(), Isis::ProcessImport::ProcessImport(), Isis::ProcessImport::ProcessJp2(), Isis::Process::Progress(), Isis::ProcessExport::StartProcess(), and Isis::ProcessByQuickFilter::StartProcess().
p_propagateHistory
bool Isis::Process::p_propagateHistory protected inherited
Flag indicating if history is to be propagated to output cubes.
p_propagateLabels
bool Isis::Process::p_propagateLabels protected inherited
Flag indicating if labels are be propagated to output cubes.
p_propagateOriginalLabel
bool Isis::Process::p_propagateOriginalLabel protected inherited
Flag indicating if original lable is to be propagated to output cubes.
p_propagatePolygons
bool Isis::Process::p_propagatePolygons protected inherited
Flag indicating if blobs are be propagated to output cubes.
p_propagateTables
bool Isis::Process::p_propagateTables protected inherited
Flag indicating if tables are be propagated to output cubes.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ProcessImportFits/ProcessImportFits.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ProcessImportFits/ProcessImportFits.cpp