Isis Developer Reference: Isis::MatrixOptions Class Reference
Isis::MatrixOptions Class Reference
This class holds the matrix color and focus information.
#include <MatrixOptions.h>
Public Types
enum FocusOption { Best , Worst , Specific , Tolerance }
Signals
void optionsUpdated ()
Public Member Functions
MatrixOptions (CorrelationMatrix parent, MatrixSceneWidget *scene)
Default Constructor.
~MatrixOptions ()
Constructor that sets up all the variables.
QColor goodCorrelationColor ()
The color selected for the correlation values that are below the given threshold.
QColor badCorrelationColor ()
The color selected for the correlation values that are above the given threshold.
double colorTolerance ()
Threshold for what is considered a bad correlation.
bool colorScheme ()
Use the green-red gradient if false.
void setColorScheme (bool tolerance)
void setColorTolerance (double tolerance)
void setGoodCorrelationColor (QColor color)
void setBadCorrelationColor (QColor color)
FocusOption focusOption ()
double focusValue ()
The value of the spot on the matrix that we need to focus on.
QString focusImage1 ()
QString focusParameter1 ()
QString focusImage2 ()
QString focusParameter2 ()
QList< double > goodElements ()
QList< double > badElements ()
void setFocusOption (FocusOption option)
void setFocusValue (double value)
void setGoodElements (QList< double > goodElements)
void setBadElements (QList< double > badElements)
double currentCorrelation ()
QString currentImage1 ()
QString currentParameter1 ()
QString currentImage2 ()
QString currentParameter2 ()
void setCurrentCorrelation (double value)
void setCurrentImage1 (QString current)
void setCurrentParameter1 (QString current)
void setCurrentImage2 (QString current)
void setCurrentParameter2 (QString current)
QMap< QString, QStringList > matrixImgsAndParams ()
This slot will be called when a matrix element is clicked on.
CorrelationMatrix * parentMatrix ()
Detailed Description
This class holds the matrix color and focus information.
This class is the go-between for the MatrixOptionsDialog and the MatrixSceneWidget.
Author
2014-07-14 Kimberly Oyama
Member Enumeration Documentation
FocusOption
enum Isis::MatrixOptions::FocusOption
Enumerator
Best
Worst
Specific
Tolerance
Constructor & Destructor Documentation
MatrixOptions()
Isis::MatrixOptions::MatrixOptions (CorrelationMatrix parent, MatrixSceneWidget * scene)
Default Constructor.
References optionsUpdated(), and Tolerance.
~MatrixOptions()
Isis::MatrixOptions::~MatrixOptions ()
Constructor that sets up all the variables.
Default Destructor
Member Function Documentation
badCorrelationColor()
QColor Isis::MatrixOptions::badCorrelationColor ()
The color selected for the correlation values that are above the given threshold.
Returns
Referenced by Isis::MatrixSceneWidget::drawElements(), and Isis::MatrixOptionsDialog::readOptions().
badElements()
QList< double > Isis::MatrixOptions::badElements ()
Returns
Referenced by setBadElements().
colorScheme()
bool Isis::MatrixOptions::colorScheme ()
Use the green-red gradient if false.
Use the 50/50 color split if true. You need the good/bad correlation color methods if true.
Returns
Referenced by Isis::MatrixSceneWidget::drawElements(), and Isis::MatrixOptionsDialog::readOptions().
colorTolerance()
double Isis::MatrixOptions::colorTolerance ()
Threshold for what is considered a bad correlation.
Returns
Referenced by Isis::MatrixSceneWidget::drawElements(), and Isis::MatrixOptionsDialog::readOptions().
currentCorrelation()
double Isis::MatrixOptions::currentCorrelation ()
Returns
currentImage1()
QString Isis::MatrixOptions::currentImage1 ()
Returns
currentImage2()
QString Isis::MatrixOptions::currentImage2 ()
Returns
currentParameter1()
QString Isis::MatrixOptions::currentParameter1 ()
Returns
currentParameter2()
QString Isis::MatrixOptions::currentParameter2 ()
Returns
focusImage1()
QString Isis::MatrixOptions::focusImage1 ()
Returns
focusImage2()
QString Isis::MatrixOptions::focusImage2 ()
Returns
focusOption()
MatrixOptions::FocusOption Isis::MatrixOptions::focusOption ()
Returns
Referenced by Isis::MatrixOptionsDialog::readOptions().
focusParameter1()
QString Isis::MatrixOptions::focusParameter1 ()
Returns
focusParameter2()
QString Isis::MatrixOptions::focusParameter2 ()
Returns
focusValue()
double Isis::MatrixOptions::focusValue ()
The value of the spot on the matrix that we need to focus on.
This can come from the best or worst option as well as the good/bad lists when a tolerance is entered.
Returns
Referenced by Isis::MatrixOptionsDialog::readOptions().
goodCorrelationColor()
QColor Isis::MatrixOptions::goodCorrelationColor ()
The color selected for the correlation values that are below the given threshold.
Returns
Referenced by Isis::MatrixSceneWidget::drawElements(), and Isis::MatrixOptionsDialog::readOptions().
goodElements()
QList< double > Isis::MatrixOptions::goodElements ()
Returns
Referenced by setGoodElements().
matrixImgsAndParams()
QMap< QString, QStringList > Isis::MatrixOptions::matrixImgsAndParams ()
This slot will be called when a matrix element is clicked on.
Returns
References Isis::CorrelationMatrix::imagesAndParameters().
Referenced by Isis::MatrixOptionsDialog::readOptions().
optionsUpdated
void Isis::MatrixOptions::optionsUpdated () signal
Referenced by MatrixOptions().
parentMatrix()
CorrelationMatrix * Isis::MatrixOptions::parentMatrix ()
Referenced by Isis::MatrixSceneWidget::redrawElements().
setBadCorrelationColor()
void Isis::MatrixOptions::setBadCorrelationColor (QColor color)
Parameters
Referenced by Isis::MatrixOptionsDialog::applyOptions().
setBadElements()
void Isis::MatrixOptions::setBadElements (QList< double > badElements)
Parameters
References badElements().
setColorScheme()
void Isis::MatrixOptions::setColorScheme (bool tolerance)
Parameters
Referenced by Isis::MatrixOptionsDialog::applyOptions().
setColorTolerance()
void Isis::MatrixOptions::setColorTolerance (double tolerance)
Parameters
Referenced by Isis::MatrixOptionsDialog::applyOptions().
setCurrentCorrelation()
void Isis::MatrixOptions::setCurrentCorrelation (double value)
Parameters
setCurrentImage1()
void Isis::MatrixOptions::setCurrentImage1 (QString current)
Parameters
setCurrentImage2()
void Isis::MatrixOptions::setCurrentImage2 (QString current)
Parameters
setCurrentParameter1()
void Isis::MatrixOptions::setCurrentParameter1 (QString current)
Parameters
setCurrentParameter2()
void Isis::MatrixOptions::setCurrentParameter2 (QString current)
Parameters
setFocusOption()
void Isis::MatrixOptions::setFocusOption (FocusOption option)
Parameters
setFocusValue()
void Isis::MatrixOptions::setFocusValue (double value)
Parameters
setGoodCorrelationColor()
void Isis::MatrixOptions::setGoodCorrelationColor (QColor color)
Parameters
Referenced by Isis::MatrixOptionsDialog::applyOptions().
setGoodElements()
void Isis::MatrixOptions::setGoodElements (QList< double > goodElements)
Parameters
References goodElements().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MatrixSceneWidget/MatrixOptions.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MatrixSceneWidget/MatrixOptions.cpp