Isis Developer Reference: Isis::ControlNetStatistics Class Reference
Isis::ControlNetStatistics Class Reference
Control Network Stats.
#include <ControlNetStatistics.h>
Public Types
enum ePointDetails {
total , ignore , locked , fixed ,
constrained , freed
}
Enumeration for Point Statistics.
enum ePointIntStats {
totalPoints , validPoints , ignoredPoints , fixedPoints ,
constrainedPoints , freePoints , editLockedPoints , totalMeasures ,
validMeasures , ignoredMeasures , editLockedMeasures
}
Enumeration for Point int stats for counts such as valid points, measures etc.
enum ePointDoubleStats {
avgResidual , minResidual , maxResidual , minLineResidual ,
maxLineResidual , minSampleResidual , maxSampleResidual , avgPixelShift ,
minPixelShift , maxPixelShift , minLineShift , maxLineShift ,
minSampleShift , maxSampleShift , minGFit , maxGFit ,
minEccentricity , maxEccentricity , minPixelZScore , maxPixelZScore
}
Enumeration for Point stats like Tolerances, PixelShifts which have double data.
enum ImageStats {
imgSamples , imgLines , imgTotalPoints , imgIgnoredPoints ,
imgFixedPoints , imgLockedPoints , imgLocked , imgConstrainedPoints ,
imgFreePoints , imgConvexHullArea , imgConvexHullRatio
}
Enumeration for image stats.
Public Member Functions
ControlNetStatistics (ControlNet *pCNet, const QString &psSerialNumFile, Progress *pProgress=0)
Constructor.
ControlNetStatistics (ControlNet *pCNet, Progress *pProgress=0)
Constructor.
~ControlNetStatistics ()
Destructor.
void GenerateImageStats ()
Generate stats like Total, Ignored, Fixed Points in an Image.
void PrintImageStats (const QString &psImageFile)
Print the Image Stats into specified output file.
QVector< double > GetImageStatsBySerialNum (QString psSerialNum) const
Returns the Image Stats by Serial Number.
void GeneratePointStats (const QString &psPointFile)
Generate stats like Ignored, Fixed, Total Measures, Ignored by Control Point.
void GenerateControlNetStats (PvlGroup &pStatsGrp)
Generate the Control Net Stats into the PvlGroup.
int NumValidPoints () const
Returns the Number of Valid (Not Ignored) Points in the Control Net.
int NumFixedPoints () const
Returns the Number of Fixed Points in the Control Net.
int NumConstrainedPoints () const
Returns the number of Constrained Points in Control Net.
int NumFreePoints () const
Returns the number of Constrained Points in Control Net.
int NumIgnoredPoints () const
Returns the number of ignored points.
int NumEditLockedPoints () const
Returns total number of edit locked points.
int NumMeasures () const
Returns the total Number of Measures in the Control Net.
int NumValidMeasures () const
Returns the total Number of valid Measures in the Control Net.
int NumIgnoredMeasures () const
Returns the total Number of Ignored Measures in the Control Net.
int NumEditLockedMeasures () const
Returns total number of edit locked measures in the network.
double GetAverageResidual () const
Determine the average error of all points in the network.
double GetMinimumResidual () const
Determine the minimum error of all points in the network.
double GetMaximumResidual () const
Determine the maximum error of all points in the network.
double GetMinLineResidual () const
Determine the minimum line error of all points in the network.
double GetMinSampleResidual () const
Determine the minimum sample error of all points in the network.
double GetMaxLineResidual () const
Determine the maximum line error of all points in the network.
double GetMaxSampleResidual () const
Determine the maximum sample error of all points in the network.
double GetMinLineShift () const
Get Min and Max LineShift.
double GetMaxLineShift () const
Get network Max LineShift.
double GetMinSampleShift () const
Get network Min SampleShift.
double GetMaxSampleShift () const
Get network Max SampleShift.
double GetMinPixelShift () const
Get network Min PixelShift.
double GetMaxPixelShift () const
Get network Max PixelShift.
double GetAvgPixelShift () const
Get network Avg PixelShift.
Static Public Attributes
static const int numPointDetails = 6
static const int numPointIntStats = 11
static const int numPointDblStats = 20
static const int numImageStats = 11
Protected Attributes
SerialNumberList mSerialNumList
Serial Number List.
ControlNet * mCNet
Control Network.
Progress * mProgress
Progress state.
Detailed Description
Control Network Stats.
This class is used to get statistics of Control Network by Image or by Point
Author
2010-08-24 Sharmila Prasad
See also
ControlNetwork ControlPoint ControlMeasure
Member Enumeration Documentation
ePointDetails
enum Isis::ControlNetStatistics::ePointDetails
Enumeration for Point Statistics.
Enumerator
total
ignore
locked
fixed
constrained
freed
ePointDoubleStats
enum Isis::ControlNetStatistics::ePointDoubleStats
Enumeration for Point stats like Tolerances, PixelShifts which have double data.
Enumerator
avgResidual
minResidual
maxResidual
minLineResidual
maxLineResidual
minSampleResidual
maxSampleResidual
avgPixelShift
minPixelShift
maxPixelShift
minLineShift
maxLineShift
minSampleShift
maxSampleShift
minGFit
maxGFit
minEccentricity
maxEccentricity
minPixelZScore
maxPixelZScore
ePointIntStats
enum Isis::ControlNetStatistics::ePointIntStats
Enumeration for Point int stats for counts such as valid points, measures etc.
Enumerator
totalPoints
validPoints
ignoredPoints
fixedPoints
constrainedPoints
freePoints
editLockedPoints
totalMeasures
validMeasures
ignoredMeasures
editLockedMeasures
ImageStats
enum Isis::ControlNetStatistics::ImageStats
Enumeration for image stats.
Enumerator
imgSamples
imgLines
imgTotalPoints
imgIgnoredPoints
imgFixedPoints
imgLockedPoints
imgLocked
imgConstrainedPoints
imgFreePoints
imgConvexHullArea
imgConvexHullRatio
Constructor & Destructor Documentation
ControlNetStatistics() [1/2]
Isis::ControlNetStatistics::ControlNetStatistics (ControlNet * pCNet, const QString & psSerialNumFile, Progress * pProgress = 0)
Constructor.
ControlNetStatistics Constructor has ctor to it's base Control Network.
Author
Sharmila Prasad (8/24/2010)
Parameters
pCNet - Input Control network
psSerialNumFile - Serial Number List file
pProgress - Check Progress if not Null
References GenerateImageStats(), mCNet, mProgress, and mSerialNumList.
ControlNetStatistics() [2/2]
Isis::ControlNetStatistics::ControlNetStatistics (ControlNet * pCNet, Progress * pProgress = 0)
Constructor.
Constructor with ControlNet.
Author
Sharmila Prasad (11/5/2010)
Parameters
pCNet
pProgress
References mCNet, and mProgress.
~ControlNetStatistics()
Isis::ControlNetStatistics::~ControlNetStatistics ()
Destructor.
Author
Sharmila Prasad (9/17/2010)
References mCNet.
Member Function Documentation
GenerateControlNetStats()
void Isis::ControlNetStatistics::GenerateControlNetStats (PvlGroup & pStatsGrp)
Generate the Control Net Stats into the PvlGroup.
Generates the summary stats for the entire control network.
Stats include Total images, Total, Valid, Ignored, Fixed Points, Total, Valid, Ignored Measures and also Average, Min, Max Error, Min, Max Line and Sample Errors
Author
Sharmila Prasad (8/25/2010)
Parameters
pStatsGrp - Output Control Net Stats in Pvl format
References Isis::Statistics::Average(), GetAverageResidual(), GetAvgPixelShift(), GetMaximumResidual(), GetMaxLineResidual(), GetMaxLineShift(), GetMaxPixelShift(), GetMaxSampleResidual(), GetMaxSampleShift(), GetMinimumResidual(), GetMinLineResidual(), GetMinLineShift(), GetMinPixelShift(), GetMinSampleResidual(), GetMinSampleShift(), Isis::ControlNet::GetNumEditLockMeasures(), Isis::ControlNet::GetNumEditLockPoints(), Isis::ControlNet::GetNumPoints(), maxEccentricity, maxGFit, Isis::Statistics::Maximum(), maxPixelZScore, mCNet, minEccentricity, minGFit, Isis::Statistics::Minimum(), minPixelZScore, mSerialNumList, Isis::Null, NumConstrainedPoints(), NumFixedPoints(), NumFreePoints(), NumIgnoredMeasures(), NumMeasures(), NumValidMeasures(), NumValidPoints(), Isis::SerialNumberList::size(), and Isis::toString().
GenerateImageStats()
void Isis::ControlNetStatistics::GenerateImageStats ()
Generate stats like Total, Ignored, Fixed Points in an Image.
Generate the Image stats - imgSamples, imgLines, imgTotalPoints, imgIgnoredPoints, imgFixedPoints, imgLockedPoints, imgLocked, imgConstrainedPoints, imgFreePoints, imgConvexHullArea, imgConvexHullRatio.
Author
Sharmila Prasad (11/1/2011)
References Isis::Statistics::AddData(), Isis::Progress::CheckStatus(), Isis::ControlPoint::Constrained, Isis::SerialNumberList::fileName(), Isis::ControlPoint::Fixed, Isis::ControlPoint::Free, Isis::ControlNet::GetCubeSerials(), Isis::ControlMeasure::GetLine(), Isis::ControlNet::GetMeasuresInCube(), Isis::ControlMeasure::GetSample(), Isis::ControlPoint::GetType(), imgConstrainedPoints, imgConvexHullArea, imgConvexHullRatio, imgFixedPoints, imgFreePoints, imgIgnoredPoints, imgLines, imgLocked, imgLockedPoints, imgSamples, imgTotalPoints, Isis::ControlMeasure::IsEditLocked(), Isis::ControlPoint::IsEditLocked(), Isis::ControlPoint::IsIgnored(), Isis::Cube::lineCount(), mCNet, mProgress, mSerialNumList, numImageStats, Isis::CubeManager::OpenCube(), Isis::ControlMeasure::Parent(), Isis::Cube::sampleCount(), Isis::Progress::SetMaximumSteps(), Isis::CubeManager::SetNumOpenCubes(), and Isis::Progress::SetText().
Referenced by ControlNetStatistics(), Isis::ControlNetFilter::CubeConvexHullFilter(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::ControlNetFilter::CubeNameExpressionFilter(), Isis::ControlNetFilter::CubeNumPointsFilter(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointEditLockFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointIDFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::ControlNetFilter::PointMeasurePropertiesFilter(), Isis::ControlNetFilter::PointMeasuresFilter(), Isis::ControlNetFilter::PointNumMeasuresEditLockFilter(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::ControlNetFilter::PointPropertiesFilter(), and Isis::ControlNetFilter::PointResMagnitudeFilter().
GeneratePointStats()
void Isis::ControlNetStatistics::GeneratePointStats (const QString & psPointFile)
Generate stats like Ignored, Fixed, Total Measures, Ignored by Control Point.
Generate the statistics of a Control Network by Point Stats include ID, Type of each Control Point and Total, Ignored measures in each Control Point.
Author
Sharmila Prasad (8/24/2010)
Parameters
psPointFile - Output Point Statisitics File
References _FILEINFO_, Isis::Progress::CheckStatus(), Isis::FileName::expanded(), Isis::ControlPoint::GetId(), Isis::ControlPoint::GetNumLockedMeasures(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlNet::GetNumPoints(), Isis::ControlPoint::GetNumValidMeasures(), Isis::ControlNet::GetPoint(), Isis::ControlPoint::GetType(), Isis::IException::Io, Isis::ControlPoint::IsEditLocked(), Isis::ControlPoint::IsIgnored(), mCNet, mProgress, Isis::sBoolean, Isis::Progress::SetMaximumSteps(), Isis::Progress::SetText(), and Isis::sPointType.
GetAverageResidual()
double Isis::ControlNetStatistics::GetAverageResidual () const inline
Determine the average error of all points in the network.
References avgResidual.
Referenced by GenerateControlNetStats().
GetAvgPixelShift()
double Isis::ControlNetStatistics::GetAvgPixelShift () const inline
Get network Avg PixelShift.
References avgPixelShift.
Referenced by GenerateControlNetStats().
GetImageStatsBySerialNum()
QVector< double > Isis::ControlNetStatistics::GetImageStatsBySerialNum (QString psSerialNum) const
Returns the Image Stats by Serial Number.
Author
Sharmila Prasad (11/3/2011)
Parameters
psSerialNum - Image serialNum
Returns
const QVector<double>
Referenced by Isis::ControlNetFilter::CubeConvexHullFilter(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::ControlNetFilter::CubeNameExpressionFilter(), Isis::ControlNetFilter::CubeNumPointsFilter(), and Isis::ControlNetFilter::PointCubeNamesFilter().
GetMaximumResidual()
double Isis::ControlNetStatistics::GetMaximumResidual () const inline
Determine the maximum error of all points in the network.
References maxResidual.
Referenced by GenerateControlNetStats().
GetMaxLineResidual()
double Isis::ControlNetStatistics::GetMaxLineResidual () const inline
Determine the maximum line error of all points in the network.
References maxLineResidual.
Referenced by GenerateControlNetStats().
GetMaxLineShift()
double Isis::ControlNetStatistics::GetMaxLineShift () const inline
Get network Max LineShift.
References maxLineShift.
Referenced by GenerateControlNetStats().
GetMaxPixelShift()
double Isis::ControlNetStatistics::GetMaxPixelShift () const inline
Get network Max PixelShift.
References maxPixelShift.
Referenced by GenerateControlNetStats().
GetMaxSampleResidual()
double Isis::ControlNetStatistics::GetMaxSampleResidual () const inline
Determine the maximum sample error of all points in the network.
References maxSampleResidual.
Referenced by GenerateControlNetStats().
GetMaxSampleShift()
double Isis::ControlNetStatistics::GetMaxSampleShift () const inline
Get network Max SampleShift.
References maxSampleShift.
Referenced by GenerateControlNetStats().
GetMinimumResidual()
double Isis::ControlNetStatistics::GetMinimumResidual () const inline
Determine the minimum error of all points in the network.
References minResidual.
Referenced by GenerateControlNetStats().
GetMinLineResidual()
double Isis::ControlNetStatistics::GetMinLineResidual () const inline
Determine the minimum line error of all points in the network.
References minLineResidual.
Referenced by GenerateControlNetStats().
GetMinLineShift()
double Isis::ControlNetStatistics::GetMinLineShift () const inline
Get Min and Max LineShift.
References minLineShift.
Referenced by GenerateControlNetStats().
GetMinPixelShift()
double Isis::ControlNetStatistics::GetMinPixelShift () const inline
Get network Min PixelShift.
References minPixelShift.
Referenced by GenerateControlNetStats().
GetMinSampleResidual()
double Isis::ControlNetStatistics::GetMinSampleResidual () const inline
Determine the minimum sample error of all points in the network.
References minSampleResidual.
Referenced by GenerateControlNetStats().
GetMinSampleShift()
double Isis::ControlNetStatistics::GetMinSampleShift () const inline
Get network Min SampleShift.
References minSampleShift.
Referenced by GenerateControlNetStats().
NumConstrainedPoints()
int Isis::ControlNetStatistics::NumConstrainedPoints () const inline
Returns the number of Constrained Points in Control Net.
References constrainedPoints.
Referenced by GenerateControlNetStats().
NumEditLockedMeasures()
int Isis::ControlNetStatistics::NumEditLockedMeasures () const inline
Returns total number of edit locked measures in the network.
References editLockedMeasures.
NumEditLockedPoints()
int Isis::ControlNetStatistics::NumEditLockedPoints () const inline
Returns total number of edit locked points.
References editLockedPoints.
NumFixedPoints()
int Isis::ControlNetStatistics::NumFixedPoints () const inline
Returns the Number of Fixed Points in the Control Net.
References fixedPoints.
Referenced by GenerateControlNetStats().
NumFreePoints()
int Isis::ControlNetStatistics::NumFreePoints () const inline
Returns the number of Constrained Points in Control Net.
References freePoints.
Referenced by GenerateControlNetStats().
NumIgnoredMeasures()
int Isis::ControlNetStatistics::NumIgnoredMeasures () const inline
Returns the total Number of Ignored Measures in the Control Net.
References ignoredMeasures.
Referenced by GenerateControlNetStats().
NumIgnoredPoints()
int Isis::ControlNetStatistics::NumIgnoredPoints () const inline
Returns the number of ignored points.
References ignoredPoints.
NumMeasures()
int Isis::ControlNetStatistics::NumMeasures () const inline
Returns the total Number of Measures in the Control Net.
References totalMeasures.
Referenced by GenerateControlNetStats().
NumValidMeasures()
int Isis::ControlNetStatistics::NumValidMeasures () const inline
Returns the total Number of valid Measures in the Control Net.
References validMeasures.
Referenced by GenerateControlNetStats().
NumValidPoints()
int Isis::ControlNetStatistics::NumValidPoints () const inline
Returns the Number of Valid (Not Ignored) Points in the Control Net.
References validPoints.
Referenced by GenerateControlNetStats().
PrintImageStats()
void Isis::ControlNetStatistics::PrintImageStats (const QString & psImageFile)
Print the Image Stats into specified output file.
Author
Sharmila Prasad (9/1/2010)
Header: FileName, SerialNumber, TotalPoints, PointsIgnored, PointsLocked, Fixed, Constrained, Free
Parameters
psImageFile - Output Image Stats File
References _FILEINFO_, Isis::FileName::expanded(), Isis::SerialNumberList::fileName(), imgConstrainedPoints, imgConvexHullRatio, imgFixedPoints, imgFreePoints, imgIgnoredPoints, imgLockedPoints, imgTotalPoints, Isis::IException::Io, mSerialNumList, Isis::SerialNumberList::size(), and Isis::IException::User.
Member Data Documentation
mCNet
ControlNet* Isis::ControlNetStatistics::mCNet protected
Control Network.
Referenced by ControlNetStatistics(), Isis::ControlNetFilter::CubeDistanceFilter(), GenerateControlNetStats(), GenerateImageStats(), GeneratePointStats(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointEditLockFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointIDFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::ControlNetFilter::PointMeasurePropertiesFilter(), Isis::ControlNetFilter::PointMeasuresFilter(), Isis::ControlNetFilter::PointNumMeasuresEditLockFilter(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::ControlNetFilter::PointPropertiesFilter(), Isis::ControlNetFilter::PointResMagnitudeFilter(), and ~ControlNetStatistics().
mProgress
Progress* Isis::ControlNetStatistics::mProgress protected
Progress state.
Referenced by ControlNetStatistics(), GenerateImageStats(), and GeneratePointStats().
mSerialNumList
SerialNumberList Isis::ControlNetStatistics::mSerialNumList protected
Serial Number List.
Referenced by ControlNetStatistics(), Isis::ControlNetFilter::CubeDistanceFilter(), GenerateControlNetStats(), GenerateImageStats(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::ControlNetFilter::PointMeasurePropertiesFilter(), Isis::ControlNetFilter::PrintCubeFileSerialNum(), and PrintImageStats().
numImageStats
const int Isis::ControlNetStatistics::numImageStats = 11 static
Referenced by GenerateImageStats().
numPointDblStats
const int Isis::ControlNetStatistics::numPointDblStats = 20 static
numPointDetails
const int Isis::ControlNetStatistics::numPointDetails = 6 static
numPointIntStats
const int Isis::ControlNetStatistics::numPointIntStats = 11 static
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/ControlNetStatistics/ControlNetStatistics.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/ControlNetStatistics/ControlNetStatistics.cpp