Isis Developer Reference: Isis::PointPair Class Reference
Isis::PointPair Class Reference
Define a point set of left, right and geometry at that location.
#include <GruenTypes.h>
Public Member Functions
PointPair ()
PointPair (const double &line, const double &sample)
PointPair (const Coordinate &left, const Coordinate &right=Coordinate())
bool isValid () const
Left, right and geometry coordinates must all be good data.
const Coordinate & getLeft () const
const Coordinate & getRight () const
double getLine () const
double getSample () const
double getLeftLine () const
double getLeftSample () const
double getRightLine () const
double getRightSample () const
Public Attributes
Coordinate m_left
Coordinate m_right
Detailed Description
Define a point set of left, right and geometry at that location.
The structure defines a Gruen point set that may or may not contain a valid geometry. This supports the (efficient) growing feature of SMTK in that a grown point will have valid left and right points, but not neccesarily geomertry. Valid geometry requires using camera models and that is costly.
Default initialize sets all points to an invalid state.
Author
????-??-?? Unknown
Constructor & Destructor Documentation
PointPair() [1/3]
Isis::PointPair::PointPair () inline
PointPair() [2/3]
Isis::PointPair::PointPair (const double & line, const double & sample) inline
PointPair() [3/3]
Isis::PointPair::PointPair (const Coordinate & left, const Coordinate & right = Coordinate()) inline
Member Function Documentation
getLeft()
const Coordinate& Isis::PointPair::getLeft () const inline
References m_left.
Referenced by Isis::SmtkMatcher::Register().
getLeftLine()
double Isis::PointPair::getLeftLine () const inline
References Isis::Coordinate::getLine(), and m_left.
Referenced by getLine().
getLeftSample()
double Isis::PointPair::getLeftSample () const inline
References Isis::Coordinate::getSample(), and m_left.
Referenced by getSample().
getLine()
double Isis::PointPair::getLine () const inline
References getLeftLine().
getRight()
const Coordinate& Isis::PointPair::getRight () const inline
References m_right.
Referenced by Isis::SmtkMatcher::Register().
getRightLine()
double Isis::PointPair::getRightLine () const inline
References Isis::Coordinate::getLine(), and m_right.
getRightSample()
double Isis::PointPair::getRightSample () const inline
References Isis::Coordinate::getSample(), and m_right.
getSample()
double Isis::PointPair::getSample () const inline
References getLeftSample().
isValid()
bool Isis::PointPair::isValid () const inline
Left, right and geometry coordinates must all be good data.
References Isis::Coordinate::isValid(), m_left, and m_right.
Member Data Documentation
m_left
Coordinate Isis::PointPair::m_left
Referenced by getLeft(), getLeftLine(), getLeftSample(), and isValid().
m_right
Coordinate Isis::PointPair::m_right
Referenced by getRight(), getRightLine(), getRightSample(), and isValid().
The documentation for this class was generated from the following file:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Gruen/GruenTypes.h