Isis Developer Reference: Isis::OriginalLabel Class Reference
Isis::OriginalLabel Class Reference
Low Level Cube I/O
Read and store original labels.
#include <OriginalLabel.h>
Public Member Functions
OriginalLabel ()
Constructor for creating an original blob with a given name.
OriginalLabel (const QString &file)
Constructor for creating an original blob with a given name and file to read labels from.
OriginalLabel (Isis::Blob &blob)
Constructor for creating an original label from a blob object.
OriginalLabel (Pvl pvl)
Constructor for creating an original blob with a given name and Pvl container.
~OriginalLabel ()
Pvl ReturnLabels () const
Returns the labels in a Pvl object.
Isis::Blob toBlob ()
Serialize the OriginalLabel data to a Blob.
Protected Member Functions
void WriteInit ()
Detailed Description
Read and store original labels.
This class provides a means to read and store the labels from the original source. The labels can be retreived in a Pvl object.
Author
2006-02-23 Robert Wallace and Brian Lipkowitz
Constructor & Destructor Documentation
OriginalLabel() [1/4]
Isis::OriginalLabel::OriginalLabel ()
Constructor for creating an original blob with a given name.
OriginalLabel() [2/4]
Isis::OriginalLabel::OriginalLabel (const QString & file)
Constructor for creating an original blob with a given name and file to read labels from.
Parameters
file File to read labels from
References Isis::Blob::Read().
OriginalLabel() [3/4]
Isis::OriginalLabel::OriginalLabel (Isis::Blob & blob)
Constructor for creating an original label from a blob object.
OriginalLabel() [4/4]
Isis::OriginalLabel::OriginalLabel (Pvl pvl)
Constructor for creating an original blob with a given name and Pvl container.
Parameters
pvl Pvl containing labels of the source
~OriginalLabel()
Isis::OriginalLabel::~OriginalLabel ()
Member Function Documentation
ReturnLabels()
Pvl Isis::OriginalLabel::ReturnLabels () const
Returns the labels in a Pvl object.
Returns
(Isis::Pvl) original labels
toBlob()
Isis::Blob Isis::OriginalLabel::toBlob ()
Serialize the OriginalLabel data to a Blob.
Returns
Blob
References Isis::Blob::setData().
Referenced by Isis::Cube::write().
WriteInit()
void Isis::OriginalLabel::WriteInit () protected
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/OriginalLabel/OriginalLabel.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/OriginalLabel/OriginalLabel.cpp