Isis Developer Reference: Isis::NewControlPointDialog Class Reference
Isis::NewControlPointDialog Class Reference
#include <NewControlPointDialog.h>
Public Member Functions
NewControlPointDialog (ControlNet *controlNet, SerialNumberList *serialNumberList, QString defaultPointId, QWidget *parent=0, bool pointType=false, bool groundSource=false, bool subpixelRegisterMeasures=false)
@description Create dialog for creating a new Control Point
QString pointId () const
int pointType () const
void setGroundSource (QStringList groundFiles, int numberShapesWithPoint)
void setRadiusSource (QStringList radiusFiles)
QString groundSource () const
QString radiusSource () const
QStringList selectedFiles () const
void setFiles (QStringList pointFiles)
bool subpixelRegisterPoint ()
Detailed Description
Author
????-??-?? Tracie Sucharski
Constructor & Destructor Documentation
NewControlPointDialog()
Isis::NewControlPointDialog::NewControlPointDialog (ControlNet * controlNet, SerialNumberList * serialNumberList, QString defaultPointId, QWidget * parent = 0, bool pointType = false, bool groundSource = false, bool subpixelRegisterMeasures = false)
@description Create dialog for creating a new Control Point
Parameters
controlNet The control net the new control point will be contained in
serialNumberList The serial number list corresponding to the controlNet
defaultPointId The default pointID, usually empty string
parent Parent widget
pointType Show the Point Type combo box, default = false
groundSource Show the Ground Source list, default = false
subpixelRegisterMeasures Show the check box for sub-pixel registration option, default = false
References groundSource(), pointType(), Isis::ControlPoint::PointTypeCount, and Isis::ControlPoint::PointTypeToString().
Member Function Documentation
groundSource()
QString Isis::NewControlPointDialog::groundSource () const
Referenced by Isis::ControlPointEditWidget::createControlPoint(), and NewControlPointDialog().
pointId()
QString Isis::NewControlPointDialog::pointId () const
Referenced by Isis::ControlPointEditWidget::createControlPoint(), and Isis::QnetTool::createPoint().
pointType()
int Isis::NewControlPointDialog::pointType () const
References Isis::ControlPoint::Constrained, Isis::ControlPoint::Fixed, and Isis::ControlPoint::Free.
Referenced by Isis::ControlPointEditWidget::createControlPoint(), and NewControlPointDialog().
radiusSource()
QString Isis::NewControlPointDialog::radiusSource () const
selectedFiles()
QStringList Isis::NewControlPointDialog::selectedFiles () const
Referenced by Isis::ControlPointEditWidget::createControlPoint(), and Isis::QnetTool::createPoint().
setFiles()
void Isis::NewControlPointDialog::setFiles (QStringList pointFiles)
References Isis::SerialNumberList::fileName(), and Isis::SerialNumberList::size().
Referenced by Isis::ControlPointEditWidget::createControlPoint(), and Isis::QnetTool::createPoint().
setGroundSource()
void Isis::NewControlPointDialog::setGroundSource (QStringList groundFiles, int numberShapesWithPoint)
Referenced by Isis::ControlPointEditWidget::createControlPoint().
setRadiusSource()
void Isis::NewControlPointDialog::setRadiusSource (QStringList radiusFiles)
Referenced by Isis::ControlPointEditWidget::createControlPoint().
subpixelRegisterPoint()
bool Isis::NewControlPointDialog::subpixelRegisterPoint ()
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/NewControlPointDialog/NewControlPointDialog.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/NewControlPointDialog/NewControlPointDialog.cpp