Isis Developer Reference: Isis::QStretch Class Reference
Isis::QStretch Class Reference abstract
Abstract class for complex stretch objects.
#include <QStretch.h>
Signals
void update ()
Signal to emit when this QStretch has been updated.
Public Member Functions
QStretch (const StretchTool *stretchTool, QString name)
QStretch Constructor.
virtual QStretch * clone ()=0
Abstract method to clone a QStretch in order to retain its parameters and stretch pairs.
virtual void connectTable (QTableWidget *widget)
Abstract method to connect the AdvancedStretchTool's table of stretch pairs in order to modify it if necessary.
virtual void disconnectTable (QTableWidget *widget)
Abstract method to disconnect the AdvancedStretchTool's table of stretch pairs.
virtual QGroupBox * getParameters ()=0
Abstract method to return a QGroupBox of this QStretch's parameters.
QString name ()
This method returns the name of this QStretch.
Stretch stretch ()
This method returns the stretch.
virtual void setMinMax (double min, double max)
Abstract method to set the minimum and maximum values that stretch input pairs can be set to.
Protected Attributes
const StretchTool * p_stretchTool
The StretchTool that created this QStretch.
QString p_name
The name of this QStretch.
double p_min
The minimum value a stretch input pair can be set to.
double p_max
The maximum value a stretch input pair can be set to.
QGroupBox * p_parametersBox
The QGroupBox that holds this QStretch's parameters.
Stretch p_stretch
The stretch that this QStretch modifies.
Detailed Description
Abstract class for complex stretch objects.
This class serves as the parent class to complex stretch objects that are used by the AdvancedStretchTool. It must define parameters to manipulate its stretch pairs that will be used by the AdvancedStretchTool's 'Advanced' dialog.
Author
2009-05-01 Noah hilt
Constructor & Destructor Documentation
QStretch()
Isis::QStretch::QStretch (const StretchTool * stretchTool, QString name) inline
QStretch Constructor.
StretchTool can not be null.
Initializes the stretch and sets its special pixel values to their defaults.
Parameters
stretchTool
name
References p_stretch, Isis::Stretch::SetHis(), Isis::Stretch::SetHrs(), Isis::Stretch::SetLis(), Isis::Stretch::SetLrs(), Isis::Stretch::SetMaximum(), Isis::Stretch::SetMinimum(), and Isis::Stretch::SetNull().
Member Function Documentation
clone()
virtual QStretch* Isis::QStretch::clone () pure virtual
Abstract method to clone a QStretch in order to retain its parameters and stretch pairs.
This method must be overridden.
Returns
QStretch*
connectTable()
virtual void Isis::QStretch::connectTable (QTableWidget * widget) inline virtual
Abstract method to connect the AdvancedStretchTool's table of stretch pairs in order to modify it if necessary.
The default implementation is to do nothing.
Parameters
widget
disconnectTable()
virtual void Isis::QStretch::disconnectTable (QTableWidget * widget) inline virtual
Abstract method to disconnect the AdvancedStretchTool's table of stretch pairs.
The default implementation is to do nothing.
Parameters
widget
getParameters()
virtual QGroupBox* Isis::QStretch::getParameters () pure virtual
Abstract method to return a QGroupBox of this QStretch's parameters.
This method must be overridden.
Returns
QGroupBox*
name()
QString Isis::QStretch::name () inline
This method returns the name of this QStretch.
Returns
QString
References p_name.
setMinMax()
virtual void Isis::QStretch::setMinMax (double min, double max) inline virtual
Abstract method to set the minimum and maximum values that stretch input pairs can be set to.
Parameters
min
max
References p_max, and p_min.
stretch()
Stretch Isis::QStretch::stretch () inline
This method returns the stretch.
Returns
Stretch
References p_stretch.
update
void Isis::QStretch::update () signal
Signal to emit when this QStretch has been updated.
Member Data Documentation
p_max
double Isis::QStretch::p_max protected
The maximum value a stretch input pair can be set to.
Referenced by setMinMax().
p_min
double Isis::QStretch::p_min protected
The minimum value a stretch input pair can be set to.
Referenced by setMinMax().
p_name
QString Isis::QStretch::p_name protected
The name of this QStretch.
Referenced by name().
p_parametersBox
QGroupBox* Isis::QStretch::p_parametersBox protected
The QGroupBox that holds this QStretch's parameters.
p_stretch
Stretch Isis::QStretch::p_stretch protected
The stretch that this QStretch modifies.
Referenced by QStretch(), and stretch().
p_stretchTool
const StretchTool* Isis::QStretch::p_stretchTool protected
The StretchTool that created this QStretch.
The documentation for this class was generated from the following file:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/StretchTool/QStretch.h