Isis Developer Reference: Isis::FileTool Class Reference
Isis::FileTool Class Reference
#include <FileTool.h>
Public Slots
virtual void open ()
This method allows the user to navigate and open a cube with a file dialog.
virtual void browse ()
This method allows the user to navigate and browse cubes with a file dialog .
void print ()
This method allows the user to print the current viewport.
virtual void save ()
This method saves any changes made to the current cube, these changes are finalized! There is no undoing once a save has been made.
virtual void saveAs ()
SaveAs Action - Displays the FileDialog with the filterlist (*.cub) to select the output cube.
virtual void saveInfo ()
Saves the whatsthis info of the cubeviewport.
virtual void exportView ()
This method allows the user to export the current view as an image file.
virtual void exportToList ()
FileTool::exportToList.
virtual bool closeAll ()
Try to close all open cubes and save/discard if necessary.
virtual void exit ()
Exit the program, this slot called when the exit is chosen from the File menu.
void enableSave (bool enable)
This slot enables or disables save and save as.
void discard ()
This slot emits a signal to discard all changes to the current viewport.
void saveAsCubeByOption (QString)
Save as Isis Cube (FullImage, AsIs, FullRes)
void activate (bool)
Activates the tool.
void setCubeViewport (MdiCubeViewport *cvp)
Sets the current viewport to the given cvp.
Signals
void fileSelected (QString)
This signal is called when a file is selected.
void saveChanges (CubeViewport *vp)
This signal is called when changes should be saved.
void discardChanges (CubeViewport *vp)
This signal is called when changes should be discarded.
void clearWarningSignal ()
void toolActivated ()
void viewportChanged ()
Public Member Functions
FileTool (QWidget *parent)
Constructs a FileTool object.
void addTo (QMenu *menu)
Adds the file tool's actions to the menu.
void addTo (Workspace *ws)
Connects the fileSelected signal to the workspace's addCubeViewport slot.
void addToPermanent (QToolBar *perm)
Adds the file tool's actions to the permanent toolbar.
QPointer< QAction > openAction ()
QPointer< QAction > saveAction ()
QString menuName () const
void addTo (ViewportMainWindow *mw)
Adds the tool to the application.
void addTo (ToolPad *toolpad)
Adds the tool to the toolpad.
void addToActive (QToolBar *toolbar)
QString toolIconDir () const
returns the path to the icon directory.
virtual void paintViewport (MdiCubeViewport *vp, QPainter *painter)
RubberBandTool * rubberBandTool ()
void setList (ToolList *currentList)
Public Attributes
QStringList p_filterList
Filter List.
QDir p_dir
Directory.
QStringList p_fileList
File list.
Protected Types
typedef QVector< MdiCubeViewport * > CubeViewportList
A list of cubeviewports.
Protected Slots
virtual void rubberBandComplete ()
virtual void screenPixelsChanged ()
This is called when actions change which pixels from the cube are displayed.
virtual void mouseEnter ()
virtual void mouseMove (QPoint p)
virtual void mouseMove (QPoint p, Qt::MouseButton)
virtual void mouseLeave ()
Protected Member Functions
void updateTool ()
Updates the tool.
virtual void mouseDoubleClick (QPoint p)
virtual void mouseButtonPress (QPoint p, Qt::MouseButton s)
virtual void mouseButtonRelease (QPoint p, Qt::MouseButton s)
Resets the Warning to Nowarning when a different activity occurs on the application.
virtual void updateMeasure ()
virtual void scaleChanged ()
virtual void stretchRequested (MdiCubeViewport *, int)
void registerTool (MdiCubeViewport *viewport)
Registers the tool to the viewport.
MdiCubeViewport * cubeViewport () const
Return the current cubeviewport.
CubeViewportList * cubeViewportList () const
Return the list of cubeviewports.
virtual QAction * toolPadAction (ToolPad *toolpad)
Anytime a tool is created, you must setup a tool pad action with it.
virtual QWidget * createToolBarWidget (QStackedWidget *parent)
Anytime a tool is created, you must add it to the tool bar.
virtual void addConnections (MdiCubeViewport *cvp)
Anytime a tool is created, you must add the connections for it.
virtual void removeConnections (MdiCubeViewport *cvp)
Anytime a tool is created, you must be able to remove it's connections.
virtual void enableRubberBandTool ()
Anytime a tool is created, you may use the rubber band tool.
Workspace * workspace ()
Detailed Description
Author
????-??-?? Unknown
Member Typedef Documentation
CubeViewportList
typedef QVector< MdiCubeViewport * > Isis::Tool::CubeViewportList protected inherited
A list of cubeviewports.
Constructor & Destructor Documentation
FileTool()
Isis::FileTool::FileTool (QWidget * parent)
Constructs a FileTool object.
Parameters
parent
References Isis::Tool::activate(), browse(), exit(), exportToList(), exportView(), open(), p_dir, print(), save(), saveAs(), saveInfo(), and Isis::Tool::toolIconDir().
Member Function Documentation
activate
void Isis::Tool::activate (bool on) slot inherited
Activates the tool.
Parameters
on
References Isis::Tool::clearWarningSignal(), and Isis::Tool::toolActivated().
Referenced by Isis::Tool::addTo(), Isis::AdvancedTrackTool::AdvancedTrackTool(), Isis::RubberBandTool::disable(), Isis::RubberBandTool::enable(), Isis::AdvancedTrackTool::eventFilter(), FileTool(), Isis::RubberBandTool::RubberBandTool(), Isis::TrackTool::TrackTool(), Isis::WindowTool::WindowTool(), and Isis::Workspace::Workspace().
addConnections()
virtual void Isis::Tool::addConnections (MdiCubeViewport * cvp) inline protected virtual inherited
Anytime a tool is created, you must add the connections for it.
Parameters
cvp
Reimplemented in Isis::WindowTool, and Isis::TrackTool.
addTo() [1/4]
void Isis::FileTool::addTo (QMenu * menu) virtual
Adds the file tool's actions to the menu.
Parameters
menu
Reimplemented from Isis::Tool.
Reimplemented in Isis::QnetFileTool.
Referenced by Isis::QnetFileTool::addTo().
addTo() [2/4]
void Isis::Tool::addTo (ToolPad * toolpad) inherited
Adds the tool to the toolpad.
Parameters
toolpad
References Isis::Tool::activate(), Isis::ToolPad::addAction(), and Isis::Tool::toolPadAction().
addTo() [3/4]
void Isis::Tool::addTo (ViewportMainWindow * pViewPortMnWin) inherited
Adds the tool to the application.
Parameters
pViewPortMnWin
References Isis::ViewportMainWindow::activeToolBar(), Isis::Tool::addToActive(), Isis::Tool::addToPermanent(), Isis::ViewportMainWindow::getMenu(), Isis::Tool::menuName(), Isis::ViewportMainWindow::permanentToolBar(), Isis::ViewportMainWindow::toolPad(), and Isis::ViewportMainWindow::workspace().
Referenced by Isis::EditTool::addTo(), addTo(), Isis::SpecialPixelTool::addTo(), Isis::WindowTool::addTo(), Isis::ViewportMainWindow::ViewportMainWindow(), and Isis::Workspace::Workspace().
addTo() [4/4]
void Isis::FileTool::addTo (Workspace * ws) virtual
Connects the fileSelected signal to the workspace's addCubeViewport slot.
Parameters
ws
Reimplemented from Isis::Tool.
References Isis::Tool::addTo(), fileSelected(), and Isis::Workspace::mdiArea().
addToActive()
void Isis::Tool::addToActive (QToolBar * toolbar) inherited
Parameters
toolbar
References Isis::Tool::createToolBarWidget(), and Isis::ToolList::toolBarStack().
Referenced by Isis::Tool::addTo(), and Isis::Workspace::Workspace().
addToPermanent()
void Isis::FileTool::addToPermanent (QToolBar * perm) virtual
Adds the file tool's actions to the permanent toolbar.
Parameters
perm
Reimplemented from Isis::Tool.
browse
void Isis::FileTool::browse () virtual slot
This method allows the user to navigate and browse cubes with a file dialog .
References fileSelected(), p_dir, and p_filterList.
Referenced by FileTool().
clearWarningSignal
void Isis::Tool::clearWarningSignal () signal inherited
Referenced by Isis::Tool::activate(), Isis::Tool::mouseButtonPress(), Isis::Tool::mouseButtonRelease(), and Isis::Tool::mouseDoubleClick().
closeAll
bool Isis::FileTool::closeAll () virtual slot
Try to close all open cubes and save/discard if necessary.
References Isis::Tool::cubeViewportList(), and Isis::Tool::setCubeViewport().
createToolBarWidget()
virtual QWidget* Isis::Tool::createToolBarWidget (QStackedWidget * parent) inline protected virtual inherited
Anytime a tool is created, you must add it to the tool bar.
Parameters
parent
Returns
QWidget*
Reimplemented in Isis::ZoomTool, Isis::SunShadowTool, Isis::StretchTool, Isis::StereoTool, Isis::StatisticsTool, Isis::SpectralPlotTool, Isis::SpatialPlotTool, Isis::ScatterPlotTool, Isis::PanTool, Isis::MeasureTool, Isis::HistogramTool, Isis::FindTool, Isis::FeatureNomenclatureTool, Isis::AbstractPlotTool, Isis::LatLonGridTool, Isis::EditTool, and Isis::BandTool.
Referenced by Isis::Tool::addToActive().
cubeViewport()
MdiCubeViewport* Isis::Tool::cubeViewport () const inline protected inherited
Return the current cubeviewport.
Returns
CubeViewport*
Referenced by Isis::TrackTool::addConnections(), Isis::WindowTool::addConnections(), Isis::StretchTool::deleteFromCube(), discard(), exportToList(), exportView(), Isis::StretchTool::loadStretchFromCube(), Isis::SunShadowTool::mouseButtonPress(), Isis::EditTool::mouseButtonRelease(), Isis::ControlNetTool::mouseButtonRelease(), Isis::FeatureNomenclatureTool::mouseButtonRelease(), Isis::FindTool::mouseButtonRelease(), Isis::MatchTool::mouseButtonRelease(), Isis::PanTool::mouseButtonRelease(), Isis::QnetTool::mouseButtonRelease(), Isis::RubberBandTool::mouseButtonRelease(), Isis::StretchTool::mouseButtonRelease(), Isis::AdvancedTrackTool::mouseLeave(), Isis::SunShadowTool::mouseMove(), Isis::TrackTool::mouseMove(), Isis::RubberBandTool::mouseMove(), Isis::ScatterPlotTool::mouseMove(), Isis::LatLonGridTool::paintViewport(), Isis::FindTool::paintViewport(), Isis::RubberBandTool::paintViewport(), Isis::SunShadowTool::paintViewport(), print(), Isis::HistogramTool::refreshPlot(), Isis::SpatialPlotTool::refreshPlot(), Isis::SpectralPlotTool::refreshPlot(), Isis::TrackTool::removeConnections(), Isis::WindowTool::removeConnections(), Isis::EditTool::rubberBandComplete(), Isis::HistogramTool::rubberBandComplete(), Isis::MeasureTool::rubberBandComplete(), Isis::StereoTool::rubberBandComplete(), Isis::StretchTool::rubberBandComplete(), Isis::ZoomTool::rubberBandComplete(), save(), saveAs(), saveAsCubeByOption(), saveInfo(), Isis::StretchTool::saveStretchToCube(), Isis::ScatterPlotTool::showNewScatterPlotConfig(), Isis::StretchTool::stretchGlobal(), Isis::StretchTool::stretchGlobalAllBands(), Isis::StretchTool::stretchRegional(), Isis::StretchTool::updateAdvStretchDialogforAll(), Isis::StretchTool::updateHistograms(), Isis::MeasureTool::updateMeasure(), Isis::AbstractPlotTool::updateTool(), Isis::BandTool::updateTool(), Isis::BlinkTool::updateTool(), Isis::EditTool::updateTool(), updateTool(), Isis::FindTool::updateTool(), Isis::LatLonGridTool::updateTool(), Isis::SpecialPixelTool::updateTool(), Isis::StretchTool::updateTool(), Isis::SunShadowTool::updateTool(), Isis::WindowTool::updateTool(), Isis::ZoomTool::updateTool(), and Isis::AbstractPlotTool::viewportsToPlot().
cubeViewportList()
Tool::CubeViewportList * Isis::Tool::cubeViewportList () const protected inherited
Return the list of cubeviewports.
Returns
CubeViewportList*
References Isis::Workspace::cubeViewportList().
Referenced by closeAll(), Isis::MatchTool::createPoint(), Isis::BlinkTool::eventFilter(), Isis::PanTool::mouseButtonRelease(), Isis::RubberBandTool::mouseButtonRelease(), Isis::RubberBandTool::mouseMove(), Isis::ScatterPlotTool::repaintViewports(), Isis::AbstractPlotTool::repaintViewports(), Isis::ZoomTool::rubberBandComplete(), Isis::ControlNetTool::setControlNet(), Isis::FeatureNomenclatureTool::setFontColor(), Isis::FeatureNomenclatureTool::setFontSize(), Isis::FeatureNomenclatureTool::setShowApprovedOnly(), Isis::FeatureNomenclatureTool::setVectorType(), Isis::StretchTool::stretchGlobalAllViewports(), Isis::MeasureTool::updateMeasure(), Isis::BlinkTool::updateTool(), Isis::FindTool::updateTool(), Isis::WindowTool::updateTool(), and Isis::AbstractPlotTool::viewportsToPlot().
discard
void Isis::FileTool::discard () slot
This slot emits a signal to discard all changes to the current viewport.
References Isis::Tool::cubeViewport(), and discardChanges().
Referenced by updateTool().
discardChanges
void Isis::FileTool::discardChanges (CubeViewport * vp) signal
This signal is called when changes should be discarded.
Parameters
vp
Referenced by discard(), and updateTool().
enableRubberBandTool()
void Isis::Tool::enableRubberBandTool () protected virtual inherited
Anytime a tool is created, you may use the rubber band tool.
Enable the use of the rubberband tool.
Reimplemented in Isis::ZoomTool, Isis::StereoTool, Isis::SpectralPlotTool, Isis::SpatialPlotTool, Isis::RubberBandTool, Isis::MeasureTool, and Isis::HistogramTool.
References Isis::RubberBandTool::disable(), and Isis::Tool::rubberBandTool().
enableSave
void Isis::FileTool::enableSave (bool enable) slot
This slot enables or disables save and save as.
Parameters
enable
exit
void Isis::FileTool::exit () virtual slot
Exit the program, this slot called when the exit is chosen from the File menu.
Referenced by FileTool().
exportToList
void Isis::FileTool::exportToList () virtual slot
FileTool::exportToList.
This method exports the file names of all active cubes into a .lis file by looping through The ViewportMainWindow and grabbing the file names from the active child CubeViewports.
Author
Adam Goins
References Isis::CubeViewport::cube(), Isis::Tool::cubeViewport(), and Isis::Cube::fileName().
Referenced by FileTool().
exportView
void Isis::FileTool::exportView () virtual slot
This method allows the user to export the current view as an image file.
References Isis::Tool::cubeViewport().
Referenced by FileTool().
fileSelected
void Isis::FileTool::fileSelected (QString) signal
This signal is called when a file is selected.
Referenced by addTo(), browse(), Isis::QnetFileTool::loadImage(), open(), saveAs(), and saveAsCubeByOption().
menuName()
QString Isis::FileTool::menuName () const inline virtual
Returns
the menu name for the file tool
Reimplemented from Isis::Tool.
mouseButtonPress()
void Isis::Tool::mouseButtonPress (QPoint p, Qt::MouseButton s) protected virtual inherited
Parameters
p
s
References Isis::Tool::clearWarningSignal().
mouseButtonRelease()
void Isis::Tool::mouseButtonRelease (QPoint p, Qt::MouseButton s) protected virtual inherited
Resets the Warning to Nowarning when a different activity occurs on the application.
This is called by all the mouseButtonRelease events in all the tools.
Parameters
p
s
Reimplemented in Isis::FeatureNomenclatureTool.
References Isis::Tool::clearWarningSignal().
Referenced by Isis::StretchTool::mouseButtonRelease().
mouseDoubleClick()
void Isis::Tool::mouseDoubleClick (QPoint p) protected virtual inherited
Parameters
p
References Isis::Tool::clearWarningSignal().
mouseEnter
virtual void Isis::Tool::mouseEnter () inline protected virtual slot inherited
mouseLeave
virtual void Isis::Tool::mouseLeave () inline protected virtual slot inherited
mouseMove [1/2]
void Isis::Tool::mouseMove (QPoint p) protected virtual slot inherited
Parameters
p
mouseMove [2/2]
virtual void Isis::Tool::mouseMove (QPoint p, Qt::MouseButton) inline protected virtual slot inherited
open
void Isis::FileTool::open () virtual slot
This method allows the user to navigate and open a cube with a file dialog.
References fileSelected(), p_dir, and p_filterList.
Referenced by FileTool().
openAction()
QPointer<QAction> Isis::FileTool::openAction () inline
Returns
the open action
Referenced by Isis::QnetFileTool::QnetFileTool().
paintViewport()
virtual void Isis::Tool::paintViewport (MdiCubeViewport * vp, QPainter * painter) inline virtual inherited
Parameters
vp
painter
Reimplemented in Isis::SunShadowTool, Isis::ScatterPlotTool, Isis::RubberBandTool, Isis::FindTool, Isis::FeatureNomenclatureTool, Isis::AbstractPlotTool, Isis::MatchTool, Isis::LatLonGridTool, Isis::StereoTool, Isis::QnetTool, and Isis::ControlNetTool.
print
void Isis::FileTool::print () slot
This method allows the user to print the current viewport.
References Isis::Tool::cubeViewport().
Referenced by FileTool().
registerTool()
void Isis::Tool::registerTool (MdiCubeViewport * viewport) protected inherited
Registers the tool to the viewport.
Parameters
viewport
References Isis::MdiCubeViewport::registerTool(), and Isis::Tool::stretchRequested().
Referenced by Isis::Tool::addTo().
removeConnections()
virtual void Isis::Tool::removeConnections (MdiCubeViewport * cvp) inline protected virtual inherited
Anytime a tool is created, you must be able to remove it's connections.
Parameters
cvp
Reimplemented in Isis::WindowTool, Isis::TrackTool, and Isis::MeasureTool.
rubberBandComplete
virtual void Isis::Tool::rubberBandComplete () inline protected virtual slot inherited
rubberBandTool()
RubberBandTool * Isis::Tool::rubberBandTool () inherited
References Isis::ToolList::rubberBandTool().
Referenced by Isis::MeasureTool::createToolBarWidget(), Isis::EditTool::enableRubberBandTool(), Isis::HistogramTool::enableRubberBandTool(), Isis::MeasureTool::enableRubberBandTool(), Isis::SpatialPlotTool::enableRubberBandTool(), Isis::SpectralPlotTool::enableRubberBandTool(), Isis::StereoTool::enableRubberBandTool(), Isis::StretchTool::enableRubberBandTool(), Isis::Tool::enableRubberBandTool(), Isis::ZoomTool::enableRubberBandTool(), Isis::HistogramTool::refreshPlot(), Isis::SpatialPlotTool::refreshPlot(), Isis::SpectralPlotTool::refreshPlot(), Isis::RubberBandComboBox::RubberBandComboBox(), Isis::EditTool::rubberBandComplete(), Isis::HistogramTool::rubberBandComplete(), Isis::MeasureTool::rubberBandComplete(), Isis::SpatialPlotTool::rubberBandComplete(), Isis::SpectralPlotTool::rubberBandComplete(), Isis::StereoTool::rubberBandComplete(), Isis::StretchTool::rubberBandComplete(), Isis::ZoomTool::rubberBandComplete(), and Isis::RubberBandComboBox::selectionChanged().
save
void Isis::FileTool::save () virtual slot
This method saves any changes made to the current cube, these changes are finalized! There is no undoing once a save has been made.
References Isis::CubeViewport::cube(), Isis::Tool::cubeViewport(), Isis::Cube::reopen(), and saveChanges().
Referenced by FileTool(), saveAsCubeByOption(), and updateTool().
saveAction()
QPointer<QAction> Isis::FileTool::saveAction () inline
Returns
the save as action
Referenced by Isis::QnetFileTool::QnetFileTool().
saveAs
void Isis::FileTool::saveAs () virtual slot
SaveAs Action - Displays the FileDialog with the filterlist (*.cub) to select the output cube.
This dialog additionally displays radio buttons for choices FullImage, ExportAsIs, ExportFullRes. These choices are located at the bottom of the dialog. FullImage - copies the entire image into the user specified output file ExportAsIs - copies the image as displayed in the qview app window ExportFullRes - copies the image as displayed in the qview app window but with full resolution
Author
Sharmila Prasad (4/8/2011)
References Isis::Tool::cubeViewport(), fileSelected(), p_dir, p_filterList, and saveAsCubeByOption().
Referenced by FileTool().
saveAsCubeByOption
void Isis::FileTool::saveAsCubeByOption (QString psOutFile) slot
Save as Isis Cube (FullImage, AsIs, FullRes)
Save input image as a cube into specified output file as FullImage or ExportAsIs or ExportFullRes option.
Author
Sharmila Prasad (4/8/2011)
Parameters
psOutFile - user specified output file
References Isis::Cube::bandCount(), Isis::Cube::close(), Isis::Tool::cubeViewport(), Isis::SaveAsDialog::ExportAsIs, Isis::SaveAsDialog::ExportFullRes, fileSelected(), Isis::SaveAsDialog::FullImage, Isis::Cube::lineCount(), Isis::Cube::open(), Isis::Cube::sampleCount(), and save().
Referenced by saveAs().
saveChanges
void Isis::FileTool::saveChanges (CubeViewport * vp) signal
This signal is called when changes should be saved.
Parameters
vp
Referenced by save(), and updateTool().
saveInfo
void Isis::FileTool::saveInfo (void) virtual slot
Saves the whatsthis info of the cubeviewport.
Saves the whatsthis info of the cubeviewport to user specified output file.
Author
Sharmila Prasad (4/6/2011)
References Isis::Tool::cubeViewport(), Isis::CubeViewport::getAllWhatsThisInfo(), and Isis::Pvl::write().
Referenced by FileTool().
scaleChanged()
virtual void Isis::Tool::scaleChanged () inline protected virtual inherited
Reimplemented in Isis::RubberBandTool.
screenPixelsChanged
virtual void Isis::Tool::screenPixelsChanged () inline protected virtual slot inherited
This is called when actions change which pixels from the cube are displayed.
setCubeViewport
void Isis::Tool::setCubeViewport (MdiCubeViewport * cvp) slot inherited
Sets the current viewport to the given cvp.
Parameters
cvp
References Isis::Tool::updateTool(), and Isis::Tool::viewportChanged().
Referenced by Isis::Tool::addTo(), and closeAll().
setList()
void Isis::Tool::setList (ToolList * currentList) inherited
Referenced by Isis::ToolList::append().
stretchRequested()
virtual void Isis::Tool::stretchRequested (MdiCubeViewport * , int) inline protected virtual inherited
Reimplemented in Isis::StretchTool.
Referenced by Isis::Tool::registerTool().
toolActivated
void Isis::Tool::toolActivated () signal inherited
Referenced by Isis::Tool::activate(), Isis::FeatureNomenclatureTool::FeatureNomenclatureTool(), Isis::MatchTool::MatchTool(), and Isis::StereoTool::StereoTool().
toolIconDir()
QString Isis::Tool::toolIconDir () const inline inherited
returns the path to the icon directory.
Returns
QString
Referenced by Isis::AdvancedTrackTool::AdvancedTrackTool(), Isis::BlinkTool::BlinkTool(), Isis::BandTool::createToolBarWidget(), Isis::EditTool::createToolBarWidget(), Isis::FindTool::createToolBarWidget(), Isis::MatchTool::createToolBarWidget(), Isis::PanTool::createToolBarWidget(), Isis::StereoTool::createToolBarWidget(), Isis::StretchTool::createToolBarWidget(), Isis::ZoomTool::createToolBarWidget(), FileTool(), Isis::FindTool::FindTool(), Isis::HelpTool::HelpTool(), Isis::HistogramTool::HistogramTool(), Isis::PanTool::PanTool(), Isis::SpecialPixelTool::SpecialPixelTool(), Isis::RubberBandComboBox::toolIconDir(), Isis::BandTool::toolPadAction(), Isis::ControlNetTool::toolPadAction(), Isis::EditTool::toolPadAction(), Isis::FeatureNomenclatureTool::toolPadAction(), Isis::HistogramTool::toolPadAction(), Isis::LatLonGridTool::toolPadAction(), Isis::MatchTool::toolPadAction(), Isis::MeasureTool::toolPadAction(), Isis::PanTool::toolPadAction(), Isis::QnetTool::toolPadAction(), Isis::ScatterPlotTool::toolPadAction(), Isis::SpatialPlotTool::toolPadAction(), Isis::SpectralPlotTool::toolPadAction(), Isis::StereoTool::toolPadAction(), Isis::StretchTool::toolPadAction(), Isis::SunShadowTool::toolPadAction(), Isis::FindTool::toolPadAction(), Isis::StatisticsTool::toolPadAction(), Isis::ZoomTool::toolPadAction(), Isis::WindowTool::WindowTool(), and Isis::ZoomTool::ZoomTool().
toolPadAction()
virtual QAction* Isis::Tool::toolPadAction (ToolPad * toolpad) inline protected virtual inherited
Anytime a tool is created, you must setup a tool pad action with it.
Parameters
toolpad
Returns
QAction*
Reimplemented in Isis::ZoomTool, Isis::StatisticsTool, Isis::FindTool, Isis::SunShadowTool, Isis::StretchTool, Isis::StereoTool, Isis::SpectralPlotTool, Isis::SpatialPlotTool, Isis::ScatterPlotTool, Isis::QnetTool, Isis::PanTool, Isis::MeasureTool, Isis::MatchTool, Isis::LatLonGridTool, Isis::HistogramTool, Isis::FeatureNomenclatureTool, Isis::EditTool, Isis::ControlNetTool, and Isis::BandTool.
Referenced by Isis::Tool::addTo().
updateMeasure()
virtual void Isis::Tool::updateMeasure () inline protected virtual inherited
updateTool()
void Isis::FileTool::updateTool () protected virtual
Updates the tool.
This method is called when the tool is updated.
Reimplemented from Isis::Tool.
References Isis::Tool::cubeViewport(), discard(), discardChanges(), save(), and saveChanges().
viewportChanged
void Isis::Tool::viewportChanged () signal inherited
Referenced by Isis::Tool::setCubeViewport(), Isis::SpatialPlotTool::SpatialPlotTool(), Isis::SpectralPlotTool::SpectralPlotTool(), and Isis::SunShadowTool::SunShadowTool().
workspace()
Workspace * Isis::Tool::workspace () protected inherited
Referenced by Isis::EditTool::addTo(), Isis::ControlNetTool::setControlNet(), and Isis::ScatterPlotTool::showNewScatterPlotConfig().
Member Data Documentation
p_dir
QDir Isis::FileTool::p_dir
Directory.
Referenced by browse(), FileTool(), open(), and saveAs().
p_fileList
QStringList Isis::FileTool::p_fileList
File list.
p_filterList
QStringList Isis::FileTool::p_filterList
Filter List.
Referenced by browse(), open(), and saveAs().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/FileTool/FileTool.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/FileTool/FileTool.cpp