Isis Developer Reference: Isis::ViewportBufferFill Class Reference
Isis::ViewportBufferFill Class Reference
#include <ViewportBufferFill.h>
Public Types
enum ActionType { none , transform , fill , stretch }
This uniquely identifies which child is instantiated.
Public Member Functions
ViewportBufferFill (const QRect &rect, const int &xCoef, const double &xScale, const int &yCoef, const double &yScale, const QPoint &topLeftPixel)
Constructor.
~ViewportBufferFill ()
Destructor.
virtual ViewportBufferAction::ActionType getActionType ()
Returns the type of this class.
double viewportToSample (int x)
Converts screen x position to cube sample position.
double viewportToLine (int y)
Converts screen y position to cube line position.
int getRequestPosition () const
Returns the current request position (>= read position)
int getReadPosition () const
Returns the current read position.
void incReadPosition ()
Increment read position.
void incRequestPosition ()
Increment request position.
QRect * getRect ()
Returns the rect that this action is filling in screen pixels.
int getTopmostPixelPosition ()
Returns the top of the X/Y bounding rect for this fill.
int getLeftmostPixelPosition ()
Returns the left of the X/Y bounding rect for this fill.
bool doneReading ()
Returns true if read position is past the end of the fill.
bool shouldRequestMore ()
Returns true if request position is past the end of the fill.
bool shouldPaint (int &linesToPaint)
Returns true if it is recommended to paint the fill area so far.
void stop ()
Cancels the current operation.
bool started ()
Returns true if this is an action that takes time and has begun.
void started (bool started)
Sets started.
Detailed Description
Author
????-??-?? Unknown
Member Enumeration Documentation
ActionType
enum Isis::ViewportBufferAction::ActionType inherited
This uniquely identifies which child is instantiated.
Enumerator
none
Parent was instantiated.
transform
ViewportBufferTransform.
fill
ViewportBufferFill.
stretch
ViewportBufferStretch.
Constructor & Destructor Documentation
ViewportBufferFill()
Isis::ViewportBufferFill::ViewportBufferFill (const QRect & rect, const int & xCoef, const double & xScale, const int & yCoef, const double & yScale, const QPoint & topLeftPixel)
Constructor.
Parameters
rect
xCoef
xScale
yCoef
yScale
topLeftPixel
~ViewportBufferFill()
Isis::ViewportBufferFill::~ViewportBufferFill ()
Destructor.
Member Function Documentation
doneReading()
bool Isis::ViewportBufferFill::doneReading ()
Returns true if read position is past the end of the fill.
Returns
bool
Referenced by Isis::ViewportBuffer::DataReady(), and shouldPaint().
getActionType()
virtual ViewportBufferAction::ActionType Isis::ViewportBufferFill::getActionType () inline virtual
Returns the type of this class.
Returns
ViewportBufferAction::ActionType
Reimplemented from Isis::ViewportBufferAction.
References Isis::ViewportBufferAction::fill.
getLeftmostPixelPosition()
int Isis::ViewportBufferFill::getLeftmostPixelPosition ()
Returns the left of the X/Y bounding rect for this fill.
Returns
int
Referenced by Isis::ViewportBuffer::DataReady(), and Isis::ViewportBuffer::fillBuffer().
getReadPosition()
int Isis::ViewportBufferFill::getReadPosition () const inline
Returns the current read position.
Returns
int
Referenced by Isis::ViewportBuffer::DataReady(), and Isis::ViewportBuffer::totalUnfilledArea().
getRect()
QRect* Isis::ViewportBufferFill::getRect () inline
Returns the rect that this action is filling in screen pixels.
Returns
QRect*
Referenced by Isis::ViewportBuffer::DataReady(), and Isis::ViewportBuffer::totalUnfilledArea().
getRequestPosition()
int Isis::ViewportBufferFill::getRequestPosition () const inline
Returns the current request position (>= read position)
Returns
int
Referenced by Isis::ViewportBuffer::fillBuffer().
getTopmostPixelPosition()
int Isis::ViewportBufferFill::getTopmostPixelPosition ()
Returns the top of the X/Y bounding rect for this fill.
Returns
int
Referenced by Isis::ViewportBuffer::DataReady(), and Isis::ViewportBuffer::fillBuffer().
incReadPosition()
void Isis::ViewportBufferFill::incReadPosition () inline
Increment read position.
Referenced by Isis::ViewportBuffer::DataReady(), and Isis::ViewportBuffer::fillBuffer().
incRequestPosition()
void Isis::ViewportBufferFill::incRequestPosition () inline
Increment request position.
Referenced by Isis::ViewportBuffer::fillBuffer().
shouldPaint()
bool Isis::ViewportBufferFill::shouldPaint (int & linesToPaint)
Returns true if it is recommended to paint the fill area so far.
Parameters
linesToPaint
Returns
bool
References doneReading().
shouldRequestMore()
bool Isis::ViewportBufferFill::shouldRequestMore ()
Returns true if request position is past the end of the fill.
Returns
bool
Referenced by Isis::ViewportBuffer::DataReady(), and Isis::ViewportBuffer::fillBuffer().
started() [1/2]
bool Isis::ViewportBufferAction::started () inline inherited
Returns true if this is an action that takes time and has begun.
Referenced by Isis::ViewportBuffer::DataReady(), and Isis::ViewportBufferAction::started().
started() [2/2]
void Isis::ViewportBufferAction::started (bool started) inline inherited
Sets started.
Parameters
started True if starting
References Isis::ViewportBufferAction::started().
stop()
void Isis::ViewportBufferFill::stop () virtual
Cancels the current operation.
Stops filling ASAP.
Reimplemented from Isis::ViewportBufferAction.
viewportToLine()
double Isis::ViewportBufferFill::viewportToLine (int y) inline
Converts screen y position to cube line position.
Parameters
y
Returns
double
Referenced by Isis::ViewportBuffer::DataReady(), and Isis::ViewportBuffer::fillBuffer().
viewportToSample()
double Isis::ViewportBufferFill::viewportToSample (int x) inline
Converts screen x position to cube sample position.
Parameters
x
Returns
double
Referenced by Isis::ViewportBuffer::DataReady(), and Isis::ViewportBuffer::fillBuffer().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CubeViewport/ViewportBufferFill.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CubeViewport/ViewportBufferFill.cpp