Isis Developer Reference: Isis::ControlHealthMonitorView Class Reference
Isis::ControlHealthMonitorView Class Reference
View for the Control Net Health Monitor.
#include <ControlHealthMonitorView.h>
Public Slots
virtual void addItem (ProjectItem *item)
Adds an item to the view.
virtual void addItems (QList< ProjectItem * > items)
Adds several items to the view.
virtual void removeItem (ProjectItem *item)
Removes an item to the view.
virtual void removeItems (QList< ProjectItem * > items)
Removes several items from the view.
virtual void disableActions ()
Disables toolbars and toolpad actions.
Signals
void windowChangeEvent (bool event)
Public Member Functions
ControlHealthMonitorView (Directory *directory, QWidget *parent=0)
Constructor.
~ControlHealthMonitorView ()
Destructor.
virtual QSize sizeHint () const
Return a reasonable size.
virtual QList< QAction * > permToolBarActions ()
Returns a list of actions for the permanent tool bar.
virtual QList< QAction * > activeToolBarActions ()
Returns a list of actions for the active tool bar.
virtual QList< QAction * > toolPadActions ()
Returns a list of actions for the tool pad.
ControlHealthMonitorWidget * controlHealthMonitorWidget ()
Returns the ControlHealthMonitorWidget.
virtual void setModel (ProjectItemModel *model)
Sets the model used by the view.
virtual ProjectItemModel * model ()
Returns the model used by the view.
virtual void dragEnterEvent (QDragEnterEvent *event)
Accepts the drag enter event if the internal model can accept the mime data.
virtual void dragMoveEvent (QDragMoveEvent *event)
Accepts the drag event if the internal model can accept the mime data.
virtual void dropEvent (QDropEvent *event)
Drops the data into the internal model if it can accept the data.
virtual void moveEvent (QMoveEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void enterEvent (QEvent *event)
Enables actions when cursor enters the view.
virtual void leaveEvent (QEvent *event)
Disables actions when cursor leaves the view.
virtual void enableActions ()
Enables toolbars and toolpad actions.
virtual QList< QAction * > contextMenuActions ()
Returns a list of actions appropriate for a context menu.
virtual ProjectItem * currentItem ()
Returns the current item of the model.
virtual QList< ProjectItem * > selectedItems ()
Return the selected items of the model.
virtual ProjectItemModel * internalModel ()
Returns the internal model of the view.
virtual void setInternalModel (ProjectItemModel *model)
Sets the internal model of the view.
Detailed Description
View for the Control Net Health Monitor.
Author
2018-06-07 Adam Goins
Constructor & Destructor Documentation
ControlHealthMonitorView()
Isis::ControlHealthMonitorView::ControlHealthMonitorView (Directory * directory, QWidget * parent = 0)
Constructor.
References Isis::Project::activeControl(), Isis::Control::controlNet(), and Isis::Directory::project().
~ControlHealthMonitorView()
Isis::ControlHealthMonitorView::~ControlHealthMonitorView ()
Destructor.
Member Function Documentation
activeToolBarActions()
QList< QAction * > Isis::ControlHealthMonitorView::activeToolBarActions () virtual
Returns a list of actions for the active tool bar.
Returns
(QList<QAction *>) The actions
addItem
void Isis::AbstractProjectItemView::addItem (ProjectItem * item) virtual slot inherited
Adds an item to the view.
The item must be part of the view's model. This method can be overridden in a subclass to filter out unneeded items.
Parameters
[in] item (ProjectItem *) The item to add.
References Isis::AbstractProjectItemView::internalModel().
Referenced by Isis::CubeDnView::addItem().
addItems
void Isis::AbstractProjectItemView::addItems (QList< ProjectItem * > items) virtual slot inherited
Adds several items to the view.
The items must be a part of the view's model. This method can be overridden in a subclass to filter out unneeded items.
Parameters
[in] items (QList<ProjectItem *>) The items to add.
References Isis::AbstractProjectItemView::internalModel().
Referenced by Isis::CubeDnViewWorkOrder::execute(), and Isis::Footprint2DViewWorkOrder::execute().
contextMenuActions()
QList< QAction * > Isis::AbstractProjectItemView::contextMenuActions () virtual inherited
Returns a list of actions appropriate for a context menu.
Returns
QList<QAction *> The actions
controlHealthMonitorWidget()
ControlHealthMonitorWidget * Isis::ControlHealthMonitorView::controlHealthMonitorWidget ()
Returns the ControlHealthMonitorWidget.
Returns
(ControlHealthMonitorWidget *) The currently active ControlHealthMonitorWidget.
currentItem()
ProjectItem * Isis::AbstractProjectItemView::currentItem () virtual inherited
Returns the current item of the model.
Returns
ProjectItem * The item
References Isis::ProjectItemModel::currentItem(), and Isis::AbstractProjectItemView::model().
disableActions
void Isis::AbstractProjectItemView::disableActions () virtual slot inherited
Disables toolbars and toolpad actions.
Referenced by Isis::CnetEditorView::CnetEditorView(), Isis::Footprint2DView::Footprint2DView(), and Isis::AbstractProjectItemView::leaveEvent().
dragEnterEvent()
void Isis::AbstractProjectItemView::dragEnterEvent (QDragEnterEvent * event) virtual inherited
Accepts the drag enter event if the internal model can accept the mime data.
Parameters
[in] event (QDragEnterEvent *) The drag event
References Isis::AbstractProjectItemView::internalModel().
Referenced by Isis::Footprint2DView::eventFilter().
dragMoveEvent()
void Isis::AbstractProjectItemView::dragMoveEvent (QDragMoveEvent * event) virtual inherited
Accepts the drag event if the internal model can accept the mime data.
Parameters
[in] event (QDragMoveEvent *) The drag event
References Isis::AbstractProjectItemView::internalModel().
Referenced by Isis::Footprint2DView::eventFilter().
dropEvent()
void Isis::AbstractProjectItemView::dropEvent (QDropEvent * event) virtual inherited
Drops the data into the internal model if it can accept the data.
Parameters
[in] event (QDropEvent *) The drop event
References Isis::AbstractProjectItemView::internalModel().
Referenced by Isis::Footprint2DView::eventFilter().
enableActions()
void Isis::AbstractProjectItemView::enableActions () virtual inherited
Enables toolbars and toolpad actions.
Referenced by Isis::AbstractProjectItemView::enterEvent().
enterEvent()
void Isis::AbstractProjectItemView::enterEvent (QEvent * event) virtual inherited
Enables actions when cursor enters the view.
Parameters
event The enter event
References Isis::AbstractProjectItemView::enableActions().
internalModel()
ProjectItemModel * Isis::AbstractProjectItemView::internalModel () virtual inherited
Returns the internal model of the view.
By default it is a proxy model.
Returns
ProjectItemModel * The internal model
Referenced by Isis::AbstractProjectItemView::addItem(), Isis::AbstractProjectItemView::addItems(), Isis::CubeDnView::CubeDnView(), Isis::AbstractProjectItemView::dragEnterEvent(), Isis::AbstractProjectItemView::dragMoveEvent(), Isis::AbstractProjectItemView::dropEvent(), Isis::Footprint2DView::Footprint2DView(), Isis::AbstractProjectItemView::model(), Isis::ProjectItemTreeView::ProjectItemTreeView(), Isis::AbstractProjectItemView::removeItem(), Isis::ProjectItemTreeView::setInternalModel(), and Isis::AbstractProjectItemView::setModel().
leaveEvent()
void Isis::AbstractProjectItemView::leaveEvent (QEvent * event) virtual inherited
Disables actions when cursor leaves the view.
Parameters
event The leave event
References Isis::AbstractProjectItemView::disableActions().
model()
ProjectItemModel * Isis::AbstractProjectItemView::model () virtual inherited
Returns the model used by the view.
If the internal model is a proxy model, it returns the source model.
Returns
ProjectItemModel * The model.
References Isis::AbstractProjectItemView::internalModel().
Referenced by Isis::AbstractProjectItemView::currentItem(), Isis::AbstractProjectItemView::selectedItems(), Isis::AbstractProjectItemView::setInternalModel(), Isis::ProjectItemTreeView::setInternalModel(), and Isis::AbstractProjectItemView::setModel().
moveEvent()
void Isis::AbstractProjectItemView::moveEvent (QMoveEvent * event) virtual inherited
References Isis::AbstractProjectItemView::windowChangeEvent().
permToolBarActions()
QList< QAction * > Isis::ControlHealthMonitorView::permToolBarActions () virtual
Returns a list of actions for the permanent tool bar.
Returns
(QList<QAction *>) The actions
removeItem
void Isis::AbstractProjectItemView::removeItem (ProjectItem * item) virtual slot inherited
Removes an item to the view.
The item must be part of the view's model. This method can be overriden in a subclass to filter out unneeded items.
Parameters
[in] item (ProjectItem *) The item to remove.
References Isis::AbstractProjectItemView::internalModel().
Referenced by Isis::AbstractProjectItemView::removeItems().
removeItems
void Isis::AbstractProjectItemView::removeItems (QList< ProjectItem * > items) virtual slot inherited
Removes several items from the view.
The items must be a part of the view's model.
Parameters
[in] items (QList<ProjectItem *>) The items to remove.
References Isis::AbstractProjectItemView::removeItem().
resizeEvent()
void Isis::AbstractProjectItemView::resizeEvent (QResizeEvent * event) virtual inherited
References Isis::AbstractProjectItemView::windowChangeEvent().
selectedItems()
QList< ProjectItem * > Isis::AbstractProjectItemView::selectedItems () virtual inherited
Return the selected items of the model.
Returns
QList<ProjectItem *> The items
References Isis::AbstractProjectItemView::model(), and Isis::ProjectItemModel::selectedItems().
setInternalModel()
void Isis::AbstractProjectItemView::setInternalModel (ProjectItemModel * model) virtual inherited
Sets the internal model of the view.
Parameters
[in] model (ProjectItemModel *) The new internal model
Reimplemented in Isis::ProjectItemTreeView.
References Isis::AbstractProjectItemView::model().
Referenced by Isis::ProjectItemTreeView::setInternalModel().
setModel()
void Isis::AbstractProjectItemView::setModel (ProjectItemModel * model) virtual inherited
Sets the model used by the view.
If the internal model is a proxy model, it sets the source model.
Parameters
[in] model (ProjectItemModel *) The new model
References Isis::AbstractProjectItemView::internalModel(), and Isis::AbstractProjectItemView::model().
Referenced by Isis::Directory::addCubeDnView(), Isis::Directory::addFootprint2DView(), and Isis::Directory::addProjectItemTreeView().
sizeHint()
QSize Isis::ControlHealthMonitorView::sizeHint () const virtual
Return a reasonable size.
Reimplemented from Isis::AbstractProjectItemView.
toolPadActions()
QList< QAction * > Isis::ControlHealthMonitorView::toolPadActions () virtual
Returns a list of actions for the tool pad.
Returns
(QList<QAction *>) The actions
windowChangeEvent
void Isis::AbstractProjectItemView::windowChangeEvent (bool event) signal inherited
Referenced by Isis::AbstractProjectItemView::moveEvent(), and Isis::AbstractProjectItemView::resizeEvent().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ControlHealthMonitorView/ControlHealthMonitorView.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ControlHealthMonitorView/ControlHealthMonitorView.cpp