Isis Developer Reference: Isis::BandSpinBox Class Reference
Isis::BandSpinBox Class Reference
#include <BandSpinBox.h>
Public Slots
void setKey (QString key)
Sets the key to the provided key.
void setKey (int key)
Sets the key to the provided key.
Public Member Functions
BandSpinBox (QWidget *parent=0)
BandSpinBox constructor.
void setBandBin (Pvl &pvl, const QString &key="BandNumber")
Sets the band bin.
QStringList BandBinKeys ()
returns the list of keys.
QSize sizeHint () const
returns a size hint for the spin box
QValidator::State validate (QString &input, int &pos) const
returns how valid the value from the spin box is.
Protected Member Functions
QString textFromValue (int val) const
Gets the text using p_map.
int valueFromText (const QString &text) const
gets the value (int) using p_map.
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
BandSpinBox()
Isis::BandSpinBox::BandSpinBox (QWidget * parent = 0)
BandSpinBox constructor.
Parameters
parent
Member Function Documentation
BandBinKeys()
QStringList Isis::BandSpinBox::BandBinKeys ()
returns the list of keys.
Returns
QStringList
setBandBin()
void Isis::BandSpinBox::setBandBin (Pvl & pvl, const QString & key = "BandNumber")
Sets the band bin.
Parameters
pvl
key
References Isis::PvlObject::findObject(), Isis::PvlContainer::keywords(), Isis::PvlContainer::name(), and setKey().
setKey [1/2]
void Isis::BandSpinBox::setKey (int key) slot
Sets the key to the provided key.
Parameters
key
References _FILEINFO_, Isis::IException::Programmer, and setKey().
setKey [2/2]
void Isis::BandSpinBox::setKey (QString key) slot
Sets the key to the provided key.
Parameters
key
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by setBandBin(), and setKey().
sizeHint()
QSize Isis::BandSpinBox::sizeHint () const
returns a size hint for the spin box
Returns
QSize
References textFromValue().
textFromValue()
QString Isis::BandSpinBox::textFromValue (int val) const protected
Gets the text using p_map.
Parameters
val
Returns
QString
Referenced by sizeHint().
validate()
QValidator::State Isis::BandSpinBox::validate (QString & input, int & pos) const
returns how valid the value from the spin box is.
Parameters
input
pos
Returns
QValidator::State
valueFromText()
int Isis::BandSpinBox::valueFromText (const QString & text) const protected
gets the value (int) using p_map.
Parameters
text
Returns
int
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/BandSpinBox/BandSpinBox.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/BandSpinBox/BandSpinBox.cpp