Isis Developer Reference: Isis::CubeViewport::BandInfo Class Reference
Isis::CubeViewport::BandInfo Class Reference
#include <CubeViewport.h>
Public Member Functions
BandInfo ()
BandInfo (const BandInfo &other)
~BandInfo ()
Deconstructor.
const BandInfo & operator= (BandInfo other)
The BandInfo for the Cube.
CubeStretch getStretch () const
void setStretch (const Stretch &newStretch)
Public Attributes
int band
The band.
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
BandInfo() [1/2]
Isis::CubeViewport::BandInfo::BandInfo ()
References Isis::Stretch::SetHis(), Isis::Stretch::SetHrs(), Isis::Stretch::SetLis(), Isis::Stretch::SetLrs(), Isis::Stretch::SetMaximum(), Isis::Stretch::SetMinimum(), and Isis::Stretch::SetNull().
BandInfo() [2/2]
Isis::CubeViewport::BandInfo::BandInfo (const BandInfo & other)
Parameters
other The other BandInfo
~BandInfo()
Isis::CubeViewport::BandInfo::~BandInfo ()
Deconstructor.
Member Function Documentation
getStretch()
CubeStretch Isis::CubeViewport::BandInfo::getStretch () const
Returns
The Stretch
Referenced by Isis::CubeViewport::blueStretch(), Isis::CubeViewport::grayStretch(), Isis::CubeViewport::greenStretch(), Isis::CubeViewport::redStretch(), Isis::CubeViewport::stretchBlue(), Isis::CubeViewport::stretchGray(), Isis::CubeViewport::stretchGreen(), Isis::CubeViewport::stretchRed(), Isis::CubeViewport::viewGray(), and Isis::CubeViewport::viewRGB().
operator=()
const CubeViewport::BandInfo & Isis::CubeViewport::BandInfo::operator= (CubeViewport::BandInfo other)
The BandInfo for the Cube.
Parameters
other The other BandInfo
Returns
The BandInfo
References band.
setStretch()
void Isis::CubeViewport::BandInfo::setStretch (const Stretch & newStretch)
Parameters
newStretch The new Stretch value
Referenced by Isis::CubeViewport::stretchBlue(), Isis::CubeViewport::stretchGray(), Isis::CubeViewport::stretchGreen(), Isis::CubeViewport::stretchRed(), and Isis::CubeViewport::viewRGB().
Member Data Documentation
band
int Isis::CubeViewport::BandInfo::band
The band.
Referenced by Isis::CubeViewport::blueBand(), Isis::CubeViewport::bluePixel(), Isis::CubeViewport::grayBand(), Isis::CubeViewport::grayPixel(), Isis::CubeViewport::greenBand(), Isis::CubeViewport::greenPixel(), operator=(), Isis::CubeViewport::redBand(), Isis::CubeViewport::redPixel(), Isis::CubeViewport::setCaption(), Isis::CubeViewport::viewGray(), and Isis::CubeViewport::viewRGB().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CubeViewport/CubeViewport.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CubeViewport/CubeViewport.cpp