Isis Developer Reference: Isis::TiffExporter Class Reference
Isis::TiffExporter Class Reference
High Level Cube I/O
Exports cubes into TIFF images.
#include <TiffExporter.h>
Public Member Functions
TiffExporter ()
Construct the TIFF exporter.
virtual ~TiffExporter ()
Destruct the exporter.
virtual void write (FileName outputName, int quality=100, QString compression="none", UserInterface *ui=nullptr)
Open the output file for writing, initialize its fields, then let the base ImageExporter handle the generic black-box writing routine.
virtual void setGrayscale (ExportDescription &desc)
Generic initialization with the export description.
virtual void setRgb (ExportDescription &desc)
Generic initialization with the export description.
virtual void setRgba (ExportDescription &desc)
Generic initialization with the export description.
void operator() (vector< Buffer * > &in) const
The method for writing a line of input image data (with potentially several bands representing color channels) to the output image.
int samples () const
Number of samples (columns) in the output image.
int lines () const
Number of lines (rows) in the output image.
int bands () const
Number of bands (channels) in the output image.
double inputMinimum (int channel) const
Returns the input minimum for the given channel.
double inputMaximum (int channel) const
Returns the input maximum for the given channel.
void setOutputPixelRange (double outputPixelMinimum, double outputPixelMaximum)
Set the DN floor and ceiling for the exported image.
Static Public Member Functions
static bool canWriteFormat (QString format)
Returns true if the format is "tiff".
static ImageExporter * fromFormat (QString format)
A static (factory) method for constructing an ImageExporter instance from an output format.
Protected Types
typedef void(ImageExporter::* WriteChannels) (vector< Buffer * > &in) const
Friendly alias for a method used to write a particular color channel.
Protected Member Functions
virtual void createBuffer ()
Creates the buffer to store a chunk of streamed line data with one or more bands.
virtual void setBuffer (int s, int b, int dn) const
Set the DN value at the given sample and band, resolved to a single index, of the line buffer.
virtual void writeLine (int l) const
Writes a line of buffered data to the output image on disk.
virtual void initialize (ExportDescription &desc)
Generic initialization with the export description.
virtual void writeGrayscale (vector< Buffer * > &in) const
Write a line of grayscale data to the output image.
virtual void writeRgb (vector< Buffer * > &in) const
Write a line of RGB data to the output image.
virtual void writeRgba (vector< Buffer * > &in) const
Write a line of RGBA data to the output image.
void setExtension (QString extension)
Sets the extension for the output image and generates the extension for the world file from it.
void setExportDescription (ExportDescription &desc)
Sets the description for the output image.
Cube * initializeProcess ()
Sets up the export process with the parameters described within the given description.
QString extension () const
Gets the extension for the output image.
ExportDescription & exportDescription () const
Gets the description for the output image.
ProcessExport & process () const
Get a reference to the process object, useful for subclasses to access and manipulate the process.
PixelType pixelType () const
Returns the pixel type.
virtual int outputPixelValue (double dn) const
Return the output clamped integer pixel value from the input double-precision DN.
Detailed Description
Exports cubes into TIFF images.
A streamed exporter for TIFF images. Can write an arbitrarily large set of single-band Isis cubes to an arbitrarily large TIFF image with the given pixel type.
Author
2012-04-03 Travis Addair
Member Typedef Documentation
WriteChannels
typedef void(ImageExporter::* Isis::ImageExporter::WriteChannels) (vector< Buffer * > &in) const protected inherited
Friendly alias for a method used to write a particular color channel.
Constructor & Destructor Documentation
TiffExporter()
Isis::TiffExporter::TiffExporter ()
Construct the TIFF exporter.
References Isis::ImageExporter::setExtension().
~TiffExporter()
Isis::TiffExporter::~TiffExporter () virtual
Destruct the exporter.
Member Function Documentation
bands()
int Isis::ImageExporter::bands () const inherited
Number of bands (channels) in the output image.
Returns
The depth of the output
Referenced by Isis::QtExporter::checkDataSize(), Isis::JP2Exporter::createBuffer(), createBuffer(), setBuffer(), Isis::JP2Exporter::write(), and write().
canWriteFormat()
bool Isis::TiffExporter::canWriteFormat (QString format) static
Returns true if the format is "tiff".
Parameters
format Lowercase format abbreviation
Returns
True if "tiff", false otherwise
Referenced by Isis::ImageExporter::fromFormat().
createBuffer()
void Isis::TiffExporter::createBuffer () protected virtual
Creates the buffer to store a chunk of streamed line data with one or more bands.
Implements Isis::StreamExporter.
References _FILEINFO_, Isis::ImageExporter::bands(), Isis::ImageExporter::pixelType(), Isis::ImageExporter::samples(), Isis::IException::Unknown, and Isis::UnsignedByte.
exportDescription()
ExportDescription & Isis::ImageExporter::exportDescription () const protected inherited
Gets the description for the output image.
Returns
The export description
extension()
QString Isis::ImageExporter::extension () const protected inherited
Gets the extension for the output image.
Returns
The extension for the output image
Referenced by Isis::JP2Exporter::write(), Isis::QtExporter::write(), and write().
fromFormat()
ImageExporter * Isis::ImageExporter::fromFormat (QString format) static inherited
A static (factory) method for constructing an ImageExporter instance from an output format.
The specific subclass of the returned instance is determined from the desired output image format provided. Each subclass has knowledge of whether or not it can write a particular format. Because the ability to export an image format is not mutually exclusive amongst exporters, the order of condieration here matters. For example, using a TIFF exporter takes precedence over a Qt exporter for TIFF images, because the former can process cubes greater than 2GB while the latter cannot. It is the caller's responsibility to delete the exporter instance when they are finished with it.
Parameters
format The format for the output image to be created
Returns
A pointer to the instantiated exporter owned by the caller
References _FILEINFO_, Isis::JP2Exporter::canWriteFormat(), Isis::QtExporter::canWriteFormat(), canWriteFormat(), and Isis::IException::Programmer.
initialize()
void Isis::StreamExporter::initialize (ExportDescription & desc) protected virtual inherited
Generic initialization with the export description.
Set the input, set the pixel type, and create the buffer.
Parameters
desc Export description containing necessary channel information
Implements Isis::ImageExporter.
References Isis::StreamExporter::createBuffer(), and Isis::ImageExporter::initialize().
Referenced by Isis::StreamExporter::setGrayscale(), Isis::StreamExporter::setRgb(), and Isis::StreamExporter::setRgba().
initializeProcess()
Cube * Isis::ImageExporter::initializeProcess () protected inherited
Sets up the export process with the parameters described within the given description.
This method determines determines whether to write the data as grayscale, RGB, or RGBA. It then opens a cube for retrieving the input data and establishing the dimensions of the output image. Next, the ProcessExport format is set to BIL and the ProcessExport output pixel type, output valid data range, and output null are set based on the given export description. Last, the absolute output pixel range is set based on the given description (this is the smallest and largest allowed pixel values in the output, including "special" pixel values).
Returns
A cube pointer to the first channel created, owned by the process
References _FILEINFO_, Isis::ProcessExport::BIL, Isis::Cube::lineCount(), Isis::IException::Programmer, Isis::Cube::sampleCount(), Isis::ProcessExport::setFormat(), Isis::ProcessExport::SetOutputNull(), Isis::ProcessExport::SetOutputRange(), Isis::ProcessExport::SetOutputType(), Isis::ImageExporter::writeGrayscale(), Isis::ImageExporter::writeRgb(), and Isis::ImageExporter::writeRgba().
inputMaximum()
double Isis::ImageExporter::inputMaximum (int channel) const inherited
Returns the input maximum for the given channel.
Any value of max in the input cube will be mapped to the output max of the output channel.
Parameters
channel Index of the channel within the process
Returns
The maximum DN in the input mapped to the maximum of the output
inputMinimum()
double Isis::ImageExporter::inputMinimum (int channel) const inherited
Returns the input minimum for the given channel.
Any value of min in the input cube will be mapped to the output min of the output channel.
Parameters
channel Index of the channel within the process
Returns
The minimum DN in the input mapped to the minimum of the output
lines()
int Isis::ImageExporter::lines () const inherited
Number of lines (rows) in the output image.
Returns
The height of the output
Referenced by Isis::QtExporter::checkDataSize(), Isis::QtExporter::setGrayscale(), Isis::QtExporter::setRgb(), Isis::QtExporter::setRgba(), Isis::JP2Exporter::write(), and write().
operator()()
void Isis::ImageExporter::operator() (vector< Buffer * > & in) const inherited
The method for writing a line of input image data (with potentially several bands representing color channels) to the output image.
It is called for each line of data in the input images (provides a vector containing the same line from each single-band input image). Enables the exporter to be used as a functor in a custom ProcessExport routine, bypassing the black-box write() method entirely.
Parameters
in Vector containing a line of input data from each input channel
outputPixelValue()
int Isis::ImageExporter::outputPixelValue (double dn) const protected virtual inherited
Return the output clamped integer pixel value from the input double-precision DN.
Parameters
dn The input DN
Returns
The pixel value for the output
Referenced by Isis::QtExporter::writeGrayscale(), Isis::StreamExporter::writeGrayscale(), Isis::QtExporter::writeRgb(), Isis::StreamExporter::writeRgb(), Isis::QtExporter::writeRgba(), and Isis::StreamExporter::writeRgba().
pixelType()
PixelType Isis::ImageExporter::pixelType () const protected inherited
Returns the pixel type.
Defaults to None if not set by the user.
Returns
The pixel type: {None, UnsignedByte, SignedWord, UnsignedWord}
References Isis::None.
Referenced by Isis::JP2Exporter::createBuffer(), createBuffer(), Isis::JP2Exporter::setBuffer(), setBuffer(), Isis::JP2Exporter::write(), write(), and Isis::JP2Exporter::writeLine().
process()
ProcessExport & Isis::ImageExporter::process () const protected inherited
Get a reference to the process object, useful for subclasses to access and manipulate the process.
Returns
A reference to the process object
samples()
int Isis::ImageExporter::samples () const inherited
Number of samples (columns) in the output image.
Returns
The width of the output
Referenced by Isis::QtExporter::checkDataSize(), Isis::JP2Exporter::createBuffer(), createBuffer(), Isis::QtExporter::setGrayscale(), Isis::QtExporter::setRgb(), Isis::QtExporter::setRgba(), Isis::JP2Exporter::write(), and write().
setBuffer()
void Isis::TiffExporter::setBuffer (int s, int b, int dn) const protected virtual
Set the DN value at the given sample and band, resolved to a single index, of the line buffer.
Parameters
s The sample component of the index into the buffer
b The band component of the index into the buffer
dn The value to set at the given index
Implements Isis::StreamExporter.
References _FILEINFO_, Isis::ImageExporter::bands(), Isis::ImageExporter::pixelType(), Isis::IException::Programmer, Isis::SignedWord, Isis::toString(), Isis::UnsignedByte, and Isis::UnsignedWord.
setExportDescription()
void Isis::ImageExporter::setExportDescription (ExportDescription & desc) protected inherited
Sets the description for the output image.
Parameters
desc The export description
setExtension()
void Isis::ImageExporter::setExtension (QString extension) protected inherited
Sets the extension for the output image and generates the extension for the world file from it.
Parameters
extension The extension for the output image
Referenced by Isis::JP2Exporter::JP2Exporter(), Isis::QtExporter::QtExporter(), and TiffExporter().
setGrayscale()
void Isis::StreamExporter::setGrayscale (ExportDescription & desc) virtual inherited
Generic initialization with the export description.
Stream exporters do not do anything special to export a grayscale image beyond setting up the appropriate number of color channels.
Parameters
desc Export description containing necessary channel information
Implements Isis::ImageExporter.
References Isis::StreamExporter::initialize().
setOutputPixelRange()
void Isis::ImageExporter::setOutputPixelRange (double outputPixelMinimum, double outputPixelMaximum) inherited
Set the DN floor and ceiling for the exported image.
All DNs less than the min will be set to the min in the exported image. Similarly, all DNs greater than the max will be set to the max in the exported image.
Note: These values may be "special". For example, if Null pixels are exported to 0.0 and the minimum valid pixels are exported to 2.0, then 0.0 should be passed in for the value of the min parameter.
Parameters
min The absolute minimum output DN value.
max The absolute maximum output DN value.
setRgb()
void Isis::StreamExporter::setRgb (ExportDescription & desc) virtual inherited
Generic initialization with the export description.
Stream exporters do not do anything special to export an RGB image beyond setting up the appropriate number of color channels.
Parameters
desc Export description containing necessary channel information
Implements Isis::ImageExporter.
References Isis::StreamExporter::initialize().
setRgba()
void Isis::StreamExporter::setRgba (ExportDescription & desc) virtual inherited
Generic initialization with the export description.
Stream exporters do not do anything special to export an RGBA image beyond setting up the appropriate number of color channels.
Parameters
desc Export description containing necessary channel information
Implements Isis::ImageExporter.
References Isis::StreamExporter::initialize().
write()
void Isis::TiffExporter::write (FileName outputName, int quality = 100, QString compression = "none", UserInterface * ui = nullptr) virtual
Open the output file for writing, initialize its fields, then let the base ImageExporter handle the generic black-box writing routine.
Parameters
outputName The filename of the output cube
quality The quality of the output, not used for TIFF
compression The compression algorithm used. Currenly supports "packbits", "lzw", "deflate", and "none".
Reimplemented from Isis::ImageExporter.
References _FILEINFO_, Isis::FileName::addExtension(), Isis::ImageExporter::bands(), Isis::FileName::expanded(), Isis::ImageExporter::extension(), Isis::ImageExporter::lines(), Isis::ImageExporter::pixelType(), Isis::IException::Programmer, Isis::ImageExporter::samples(), Isis::SignedWord, Isis::UnsignedByte, and Isis::ImageExporter::write().
writeGrayscale()
void Isis::StreamExporter::writeGrayscale (vector< Buffer * > & in) const protected virtual inherited
Write a line of grayscale data to the output image.
Parameters
in Vector containing a single grayscale input line
Implements Isis::ImageExporter.
References Isis::Buffer::Line(), Isis::ImageExporter::outputPixelValue(), Isis::Buffer::SampleDimension(), Isis::StreamExporter::setBuffer(), and Isis::StreamExporter::writeLine().
writeLine()
void Isis::TiffExporter::writeLine (int l) const protected virtual
Writes a line of buffered data to the output image on disk.
Parameters
l The line of the output image
Implements Isis::StreamExporter.
References _FILEINFO_, and Isis::IException::Programmer.
writeRgb()
void Isis::StreamExporter::writeRgb (vector< Buffer * > & in) const protected virtual inherited
Write a line of RGB data to the output image.
Parameters
in Vector containing three input lines (red, green, blue)
Implements Isis::ImageExporter.
References Isis::Buffer::Line(), Isis::ImageExporter::outputPixelValue(), Isis::Buffer::SampleDimension(), Isis::StreamExporter::setBuffer(), and Isis::StreamExporter::writeLine().
writeRgba()
void Isis::StreamExporter::writeRgba (vector< Buffer * > & in) const protected virtual inherited
Write a line of RGBA data to the output image.
Parameters
in Vector containing four input lines (red, green, blue, alpha)
Implements Isis::ImageExporter.
References Isis::Buffer::Line(), Isis::ImageExporter::outputPixelValue(), Isis::Buffer::SampleDimension(), Isis::StreamExporter::setBuffer(), and Isis::StreamExporter::writeLine().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/TiffExporter/TiffExporter.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/TiffExporter/TiffExporter.cpp