Isis Developer Reference: Isis::ScatterPlotConfigDialog Class Reference
Isis::ScatterPlotConfigDialog Class Reference
This configuration dialog is for users to determine the scatter plot parameters required to create a scatter plot.
#include <ScatterPlotConfigDialog.h>
Public Member Functions
ScatterPlotConfigDialog (MdiCubeViewport *activeViewport, Workspace *workspace, QWidget *parent=NULL)
This method creates all the dialog boxes required for the scatter plot window.
virtual QSize sizeHint () const
This is overridden to give a better default size than what Qt calculates by default.
Cube * xAxisCube () const
The current user selection for a cube for the x-axis data for a scatter plot.
Cube * yAxisCube () const
The current user selection for a cube for the x-axis data for a scatter plot.
int xAxisCubeBand () const
The current user selection for the band in the x-axis cube to get data from.
int yAxisCubeBand () const
The current user selection for the band in the y-axis cube to get data from.
int xAxisBinCount () const
The current user selection for the resolution of the scatter plot's x data.
int yAxisBinCount () const
The current user selection for the resolution of the scatter plot's y data.
QwtInterval sampleRange () const
This is the sample range from which the scatter plot should be created.
QwtInterval lineRange () const
This is the line range from which the scatter plot should be created.
MdiCubeViewport * xAxisCubeViewport () const
This returns a viewport which contains the x-axis cube.
MdiCubeViewport * yAxisCubeViewport () const
This returns a viewport which contains the y-axis cube.
Detailed Description
This configuration dialog is for users to determine the scatter plot parameters required to create a scatter plot.
Author
2012-01-18 Steven Lambright
Constructor & Destructor Documentation
ScatterPlotConfigDialog()
Isis::ScatterPlotConfigDialog::ScatterPlotConfigDialog (MdiCubeViewport * activeViewport, Workspace * workspace, QWidget * parent = NULL)
This method creates all the dialog boxes required for the scatter plot window.
Parameters
activeViewport The current user-selected viewport
workspace The workspace containing all of the viewports
parent The Qt-parent for this dialog
References Isis::CubeViewport::cube().
Member Function Documentation
lineRange()
QwtInterval Isis::ScatterPlotConfigDialog::lineRange () const
This is the line range from which the scatter plot should be created.
The return value is 1-based (lines start at 1) and inclusive. The range 1 and nlines is the entire line range.
Returns
The line range for the scatter plot data
sampleRange()
QwtInterval Isis::ScatterPlotConfigDialog::sampleRange () const
This is the sample range from which the scatter plot should be created.
The return value is 1-based (samples start at 1) and inclusive. The range 1 and nsamples is the entire sample range.
Returns
The sample range for the scatter plot data
sizeHint()
QSize Isis::ScatterPlotConfigDialog::sizeHint () const virtual
This is overridden to give a better default size than what Qt calculates by default.
Returns
The recommended size for this dialog
xAxisBinCount()
int Isis::ScatterPlotConfigDialog::xAxisBinCount () const
The current user selection for the resolution of the scatter plot's x data.
Returns
The x-axis data's bin count for a histogram/spectrogram
xAxisCube()
Cube * Isis::ScatterPlotConfigDialog::xAxisCube () const
The current user selection for a cube for the x-axis data for a scatter plot.
This never returns null if the dialog was accepted().
Returns
The x-axis cube or NULL if there isn't one selected.
Referenced by xAxisCubeViewport().
xAxisCubeBand()
int Isis::ScatterPlotConfigDialog::xAxisCubeBand () const
The current user selection for the band in the x-axis cube to get data from.
This isn't valid unless there is an xAxisCube().
Returns
The x-axis cube's band to get data from.
xAxisCubeViewport()
MdiCubeViewport * Isis::ScatterPlotConfigDialog::xAxisCubeViewport () const
This returns a viewport which contains the x-axis cube.
Returns
a viewport which contains the x-axis cube
References Isis::CubeViewport::cube(), Isis::Workspace::cubeViewportList(), and xAxisCube().
yAxisBinCount()
int Isis::ScatterPlotConfigDialog::yAxisBinCount () const
The current user selection for the resolution of the scatter plot's y data.
Returns
The y-axis data's bin count for a histogram/spectrogram
yAxisCube()
Cube * Isis::ScatterPlotConfigDialog::yAxisCube () const
The current user selection for a cube for the x-axis data for a scatter plot.
This never returns null if the dialog was accepted().
Returns
The y-axis cube or NULL if there isn't one selected.
Referenced by yAxisCubeViewport().
yAxisCubeBand()
int Isis::ScatterPlotConfigDialog::yAxisCubeBand () const
The current user selection for the band in the y-axis cube to get data from.
This isn't valid unless there is an yAxisCube().
Returns
The y-axis cube's band to get data from.
yAxisCubeViewport()
MdiCubeViewport * Isis::ScatterPlotConfigDialog::yAxisCubeViewport () const
This returns a viewport which contains the y-axis cube.
Returns
a viewport which contains the y-axis cube
References Isis::CubeViewport::cube(), Isis::Workspace::cubeViewportList(), and yAxisCube().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ScatterPlotTool/ScatterPlotConfigDialog.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ScatterPlotTool/ScatterPlotConfigDialog.cpp