Isis Developer Reference: Isis::ControlNetValidMeasure Class Reference
Isis::ControlNetValidMeasure Class Reference
ControlNetValidMeasure class.
#include <ControlNetValidMeasure.h>
Public Member Functions
ControlNetValidMeasure (Pvl *pvl=0)
Constructor - Initializes the data members and parses the input Pvl .
ControlNetValidMeasure (Pvl &pvl)
Constructor with a reference to Pvl Def file.
void InitStdOptions (void)
Initialize the Standard Options.
void InitStdOptionsGroup (void)
Initialize the Standard Options Pvl Group with no DefFile.
virtual ~ControlNetValidMeasure ()
Destructor: clean up stuff relevant for this class.
void Parse (Pvl &pvlDef)
Parse the DefFile for Standard Options.
virtual Pvl & GetLogPvl (void)
Get the Pvl Log file.
virtual void FindCnetRef (ControlNet &pNewNet)
Virtual Function to get better references for a Control Network based on Criteria.
bool ValidEmissionAngle (double pdEmissionAngle)
Validate whether the Emission Angle is in the set Range.
bool ValidIncidenceAngle (double pdIncidenceAngle)
Validate whether the Incidence Angle is in the set Range.
bool ValidDnValue (double pdDnValue)
Validate whether the DN Value is in the set Range.
bool ValidResolution (double pdResolution)
Validate whether the Resolution is in the set Range.
bool ValidResidualTolerances (double pdSampleResidual, double pdLineResidual, double pdResidualMagnitude, MeasureValidationResults &pResults)
Validate whether the Residuals are within the set Tolerance.
bool ValidShiftTolerances (double sampleShift, double lineShift, double pixelShift, MeasureValidationResults &results)
Validate whether the Sample and Line Shifts and Pixel Shift are within the set Tolerances.
bool ValidLatLon (Isis::Camera *pCamera, int piSample, int piLine)
Validate the Lat/Lon.
PvlGroup & GetStdOptions (void)
Get the Standard Options Pvl Group.
PvlGroup & GetStatistics (void)
Get the Statistics Pvl Grp.
double GetMinDN (void)
Get the option MinDN.
double GetMaxDN (void)
Get the option MaxDN.
double GetMinEmissionAngle (void)
Get the option MinEmissionAngle.
double GetMaxEmissionAngle (void)
Get the option MaxEmissionAngle.
double GetMinIncidenceAngle (void)
Get the option MinIncidenceAngle.
double GetMaxIncidenceAngle (void)
Get the option MaxIncidenceAngle.
double GetPixelsFromEdge (void)
Get the option PixelsFromEdge.
double GetMetersFromEdge (void)
Get the option MetersFromEdge.
QString LocationString (double pdSample, double pdLine) const
API to display location in the form "Sample,Line".
bool PixelsFromEdge (int piSample, int piLine, Cube *pCube)
Test for a point to be user defined number of pixels from the edge.
bool MetersFromEdge (int piSample, int piLine, Cube *pCube)
Test for a point to be user defined number of meters from the edge.
MeasureValidationResults ValidStandardOptions (const ControlMeasure *pMeasure, Cube *pCube, PvlGroup *pMeasureGrp=NULL)
Validate Standard options to pick a reference based on a particular criteria.
MeasureValidationResults ValidStandardOptions (const ControlMeasure *pMeasure, Cube *pCube, Camera *camera, PvlGroup *pMeasureGrp=NULL)
Validate Standard options to pick a reference based on a particular criteria.
MeasureValidationResults ValidStandardOptions (double pSample, double pLine, const ControlMeasure *pMeasure, Cube *pCube, PvlGroup *pMeasureGrp=NULL)
Validate Standard options to pick a reference based on a particular criteria.
MeasureValidationResults ValidStandardOptions (double pSample, double pLine, const ControlMeasure *pMeasure, Cube *pCube, Camera *measureCamera, PvlGroup *pMeasureGrp=NULL)
MeasureValidationResults ValidStandardOptions (double pSample, double pLine, Cube *pCube, PvlGroup *pMeasureGrp=NULL)
Validate Standard options to pick a reference based on a particular criteria.
bool IsCubeRequired ()
bool IsCameraRequired ()
API to get status of CameraRequired flag.
Protected Member Functions
void ValidatePvlDN (void)
Validate PVL Min & Max DN Standard Options.
void ValidatePvlEmissionAngle (void)
Validate PVL Min & Max EmissionAngle Standard Options.
void ValidatePvlIncidenceAngle (void)
Validate PVL Min & Max IncidenceAngle Standard Options.
void ValidatePvlResolution (void)
Validate PVL Min & Max Resolution Standard Options.
void ValidatePvlFromEdge (void)
Validate and read Pixels and Meters from Edge Standard Options.
void ValidatePvlResidualTolerances (void)
Validate Pvl Sample, Line, Residual Magnitude Tolerances.
void ValidatePvlShiftTolerances ()
Validate Pvl Sample, Line, Pixel (Sample and Line) Magnitude Shift Tolerances.
void ReadSerialNumbers (QString psSerialNumfile)
Read the Serial Numbers from the file and open assocaited cubes.
void SetCameraRequiredFlag (bool pbFlag)
Set the CameraRequired Flag.
Protected Attributes
double mdMinDN
Standard Option MinDN.
double mdMaxDN
Standard Option MaxDN.
double mdMinResolution
Standard Option MinResolution.
double mdMaxResolution
Standard Option MaxResolution.
double mdMinEmissionAngle
Standard Option MinEmissionAngle.
double mdMaxEmissionAngle
Standard Option MaxEmissionAngle.
double mdMinIncidenceAngle
Standard Option MinIncidenceAngle.
double mdMaxIncidenceAngle
Standard Option MaxIncidenceAngle.
double mdMetersFromEdge
Standard Option MeteresFromEdge.
int miPixelsFromEdge
Standard Option PixelsFromEdge.
double mdSampleResTolerance
Standard Option Sample Residual.
double mdLineResTolerance
Standard Option Line Residual.
double mdResidualTolerance
Standard Option Residual Magnitude.
double m_sampleShiftTolerance
Standard Option Sample Shift.
double m_lineShiftTolerance
Standard Option Line Shift.
double m_pixelShiftTolerance
Standard Option Pixel Shift.
double mdEmissionAngle
Store current Measure's Emission Angle.
double mdIncidenceAngle
Store current Measure's Incidence Angle.
double mdResolution
Store current Measure's Resolution.
double mdDnValue
Store current Measure's DN Value.
double mdSampleResidual
Store current Measure's Sample Residual.
double mdLineResidual
Store current Measure's Line Residual.
double mdResidualMagnitude
Store current Measure's Residual Magnitude.
double m_sampleShift
Store current Measure's Sample Shift.
double m_lineShift
Store current Measure's Line Shift.
double m_pixelShift
Store current Measure's Pixel Shift.
PvlGroup mPvlOpGrp
Pvl Operator Group.
PvlGroup mStdOptionsGrp
Pvl Standard Options Group.
PvlGroup mStatisticsGrp
Pvl output Statistics Group.
Pvl mPvlLog
Pvl Log of all the processing.
Progress mStatus
Monitor the status of the app.
CubeManager mCubeMgr
CubeManager to open and read cubes.
SerialNumberList mSerialNumbers
Serial numbers list.
bool mbCameraRequired
To improve speed, flag to indicate if Camera needs to be opened.
bool mbValidateDN
Check if DN needs to be Validated.
bool mbValidateFromEdge
Check if Pixels/Meters from edge needs to be Validated.
Detailed Description
ControlNetValidMeasure class.
Base class to validate all the common Control Network options specific to Control Network applications.
See also
cnetref autoseed etc.
Author
2010-05-11 Sharmila Prasad
Constructor & Destructor Documentation
ControlNetValidMeasure() [1/2]
Isis::ControlNetValidMeasure::ControlNetValidMeasure (Pvl * pPvl = 0)
Constructor - Initializes the data members and parses the input Pvl .
The Pvl Def File is optional.
Author
Sharmila Prasad (5/13/2010)
Parameters
pPvl - Pvl DefFile
References Isis::PvlObject::hasGroup(), InitStdOptions(), InitStdOptionsGroup(), mStatisticsGrp, and Parse().
ControlNetValidMeasure() [2/2]
Isis::ControlNetValidMeasure::ControlNetValidMeasure (Pvl & pPvl)
Constructor with a reference to Pvl Def file.
Used for Interest Operator where Def File is a requirement
Author
Sharmila Prasad (6/8/2010)
Parameters
pPvl - Pvl DefFile
References Isis::PvlObject::hasGroup(), InitStdOptions(), InitStdOptionsGroup(), mStatisticsGrp, and Parse().
~ControlNetValidMeasure()
Isis::ControlNetValidMeasure::~ControlNetValidMeasure () virtual
Destructor: clean up stuff relevant for this class.
Author
Sharmila Prasad (6/3/2010)
References Isis::CubeManager::CleanCubes(), and mCubeMgr.
Member Function Documentation
FindCnetRef()
virtual void Isis::ControlNetValidMeasure::FindCnetRef (ControlNet & pNewNet) inline virtual
Virtual Function to get better references for a Control Network based on Criteria.
Reimplemented in Isis::InterestOperator.
GetLogPvl()
virtual Pvl& Isis::ControlNetValidMeasure::GetLogPvl (void) inline virtual
Get the Pvl Log file.
References mPvlLog.
GetMaxDN()
double Isis::ControlNetValidMeasure::GetMaxDN (void) inline
Get the option MaxDN.
References mdMaxDN.
GetMaxEmissionAngle()
double Isis::ControlNetValidMeasure::GetMaxEmissionAngle (void) inline
Get the option MaxEmissionAngle.
References mdMaxEmissionAngle.
GetMaxIncidenceAngle()
double Isis::ControlNetValidMeasure::GetMaxIncidenceAngle (void) inline
Get the option MaxIncidenceAngle.
References mdMaxIncidenceAngle.
GetMetersFromEdge()
double Isis::ControlNetValidMeasure::GetMetersFromEdge (void) inline
Get the option MetersFromEdge.
References mdMetersFromEdge.
GetMinDN()
double Isis::ControlNetValidMeasure::GetMinDN (void) inline
Get the option MinDN.
References mdMinDN.
GetMinEmissionAngle()
double Isis::ControlNetValidMeasure::GetMinEmissionAngle (void) inline
Get the option MinEmissionAngle.
References mdMinEmissionAngle.
GetMinIncidenceAngle()
double Isis::ControlNetValidMeasure::GetMinIncidenceAngle (void) inline
Get the option MinIncidenceAngle.
References mdMinIncidenceAngle.
GetPixelsFromEdge()
double Isis::ControlNetValidMeasure::GetPixelsFromEdge (void) inline
Get the option PixelsFromEdge.
References miPixelsFromEdge.
GetStatistics()
PvlGroup& Isis::ControlNetValidMeasure::GetStatistics (void) inline
Get the Statistics Pvl Grp.
References mStatisticsGrp.
GetStdOptions()
PvlGroup& Isis::ControlNetValidMeasure::GetStdOptions (void) inline
Get the Standard Options Pvl Group.
References mStdOptionsGrp.
InitStdOptions()
void Isis::ControlNetValidMeasure::InitStdOptions (void)
Initialize the Standard Options.
Init all the standard options to default.
Author
Sharmila Prasad (6/8/2010)
References m_lineShiftTolerance, m_pixelShiftTolerance, m_sampleShiftTolerance, mbCameraRequired, mbValidateDN, mbValidateFromEdge, mdLineResTolerance, mdMaxDN, mdMaxEmissionAngle, mdMaxIncidenceAngle, mdMaxResolution, mdMetersFromEdge, mdMinDN, mdMinEmissionAngle, mdMinIncidenceAngle, mdMinResolution, mdResidualTolerance, mdSampleResTolerance, miPixelsFromEdge, Isis::ValidMaximum, and Isis::ValidMinimum.
Referenced by ControlNetValidMeasure().
InitStdOptionsGroup()
void Isis::ControlNetValidMeasure::InitStdOptionsGroup (void)
Initialize the Standard Options Pvl Group with no DefFile.
Set the Standard Options group for logging.
Author
Sharmila Prasad (6/8/2010)
References m_lineShiftTolerance, m_pixelShiftTolerance, m_sampleShiftTolerance, mdLineResTolerance, mdMaxDN, mdMaxEmissionAngle, mdMaxIncidenceAngle, mdMaxResolution, mdMetersFromEdge, mdMinDN, mdMinEmissionAngle, mdMinIncidenceAngle, mdMinResolution, mdResidualTolerance, mdSampleResTolerance, miPixelsFromEdge, mStdOptionsGrp, Isis::toString(), Isis::ValidMaximum, and Isis::ValidMinimum.
Referenced by ControlNetValidMeasure().
IsCameraRequired()
bool Isis::ControlNetValidMeasure::IsCameraRequired () inline
API to get status of CameraRequired flag.
Author
Sharmila Prasad (5/19/2011)
Returns
bool
References mbCameraRequired.
Referenced by IsCubeRequired().
IsCubeRequired()
bool Isis::ControlNetValidMeasure::IsCubeRequired () inline
References IsCameraRequired(), mbValidateDN, and mbValidateFromEdge.
LocationString()
QString Isis::ControlNetValidMeasure::LocationString (double pdSample, double pdLine) const inline
API to display location in the form "Sample,Line".
References Isis::toString().
Referenced by Isis::InterestOperator::FindCnetRef(), and Isis::InterestOperator::ProcessLocked_Point_Reference().
MetersFromEdge()
bool Isis::ControlNetValidMeasure::MetersFromEdge (int piSample, int piLine, Cube * pCube)
Test for a point to be user defined number of meters from the edge.
Validate if a point in Measure is user defined number of meters from the edge.
Author
Sharmila Prasad (6/21/2010)
Parameters
piSample - Point Sample Location
piLine - Point Line Location
pCube - Control Measure Cube
Returns
bool
References _FILEINFO_, Isis::Cube::camera(), Isis::Cube::fileName(), Isis::Cube::lineCount(), mdMetersFromEdge, Isis::Camera::PixelResolution(), Isis::Cube::sampleCount(), Isis::Camera::SetImage(), and Isis::IException::User.
Referenced by ValidStandardOptions().
Parse()
void Isis::ControlNetValidMeasure::Parse (Pvl & pvlDef)
Parse the DefFile for Standard Options.
Virtual member that parses the common Cnet Options and checks for their validity.
Author
Sharmila Prasad (5/13/2010)
Parameters
pvlDef - Pvl DefFile
References Isis::PvlObject::findGroup(), mPvlLog, mPvlOpGrp, mStdOptionsGrp, Isis::PvlObject::Traverse, ValidatePvlDN(), ValidatePvlEmissionAngle(), ValidatePvlFromEdge(), ValidatePvlIncidenceAngle(), ValidatePvlResidualTolerances(), ValidatePvlResolution(), and ValidatePvlShiftTolerances().
Referenced by ControlNetValidMeasure().
PixelsFromEdge()
bool Isis::ControlNetValidMeasure::PixelsFromEdge (int piSample, int piLine, Cube * pCube)
Test for a point to be user defined number of pixels from the edge.
Validate if a point in Measure is user defined number of pixels from the edge.
Author
Sharmila Prasad (6/21/2010)
Parameters
piSample - Point Sample Location
piLine - Point Line Location
pCube - Control Measure Cube
Returns
bool
References Isis::Cube::lineCount(), miPixelsFromEdge, and Isis::Cube::sampleCount().
Referenced by ValidStandardOptions().
ReadSerialNumbers()
void Isis::ControlNetValidMeasure::ReadSerialNumbers (QString psSerialNumfile) protected
Read the Serial Numbers from the file and open assocaited cubes.
Read Serial Numbers from specified file and populate the Cube and UniversalGround Maps using the serial numbers.
Author
Sharmila Prasad (6/3/2010)
Parameters
psSerialNumfile - File with list of Serial Numbers
References mCubeMgr, mSerialNumbers, mStatus, and Isis::CubeManager::SetNumOpenCubes().
Referenced by Isis::InterestOperator::Operate().
SetCameraRequiredFlag()
void Isis::ControlNetValidMeasure::SetCameraRequiredFlag (bool pbFlag) inline protected
Set the CameraRequired Flag.
This flag indicates whether a camera is required to Validate a Control Measure. Camera is required to get Emission, Incidence angles and Resolution
Author
Sharmila Prasad (5/19/2011)
Parameters
pbFlag
References mbCameraRequired.
ValidatePvlDN()
void Isis::ControlNetValidMeasure::ValidatePvlDN (void) protected
Validate PVL Min & Max DN Standard Options.
Validate the Min and Max Dn Values set by the user in the Operator pvl file.
If not set then set the options to default and enter their names in the Unused Group. If the user set values are invalid then exception is thrown.
Author
Sharmila Prasad (5/10/2010)
References _FILEINFO_, Isis::PvlContainer::hasKeyword(), mbValidateDN, mdMaxDN, mdMinDN, mPvlOpGrp, mStdOptionsGrp, Isis::toString(), Isis::IException::User, Isis::ValidMaximum, and Isis::ValidMinimum.
Referenced by Parse().
ValidatePvlEmissionAngle()
void Isis::ControlNetValidMeasure::ValidatePvlEmissionAngle (void) protected
Validate PVL Min & Max EmissionAngle Standard Options.
ValidateEmissionAngle: Validate the Min and Max Emission Values set by the user in the Operator pvl file.
If not set then set the options to default and enter their names in the Unused Group. If the user set values are invalid then exception is thrown, the valid range being [0-135]
Author
Sharmila Prasad (5/10/2010)
References _FILEINFO_, Isis::PvlContainer::hasKeyword(), mbCameraRequired, mdMaxEmissionAngle, mdMinEmissionAngle, mPvlOpGrp, mStdOptionsGrp, Isis::toString(), and Isis::IException::User.
Referenced by Parse().
ValidatePvlFromEdge()
void Isis::ControlNetValidMeasure::ValidatePvlFromEdge (void) protected
Validate and read Pixels and Meters from Edge Standard Options.
Validate and Read the Pixels and Meters from Edge Standard Options.
Author
Sharmila Prasad (6/22/2010)
References Isis::PvlContainer::hasKeyword(), mbValidateFromEdge, mdMetersFromEdge, miPixelsFromEdge, mPvlOpGrp, mStdOptionsGrp, and Isis::toString().
Referenced by Parse().
ValidatePvlIncidenceAngle()
void Isis::ControlNetValidMeasure::ValidatePvlIncidenceAngle (void) protected
Validate PVL Min & Max IncidenceAngle Standard Options.
ValidateIncidenceAngle: Validate the Min and Max Incidence Values set by the user in the Operator pvl file.
If not set then set the options to default and enter their names in the Unused Group. If the user set values are invalid then exception is thrown, the valid range being [0-135]
Author
Sharmila Prasad (5/10/2010)
References _FILEINFO_, Isis::PvlContainer::hasKeyword(), mbCameraRequired, mdMaxIncidenceAngle, mdMinIncidenceAngle, mPvlOpGrp, mStdOptionsGrp, Isis::toString(), and Isis::IException::User.
Referenced by Parse().
ValidatePvlResidualTolerances()
void Isis::ControlNetValidMeasure::ValidatePvlResidualTolerances (void) protected
Validate Pvl Sample, Line, Residual Magnitude Tolerances.
Author
Sharmila Prasad (5/16/2011)
References _FILEINFO_, Isis::PvlContainer::hasKeyword(), mdLineResTolerance, mdResidualTolerance, mdSampleResTolerance, mPvlOpGrp, mStdOptionsGrp, Isis::toString(), and Isis::IException::User.
Referenced by Parse().
ValidatePvlResolution()
void Isis::ControlNetValidMeasure::ValidatePvlResolution (void) protected
Validate PVL Min & Max Resolution Standard Options.
Validate the Min and Max Resolution Values set by the user in the Operator pvl file.
If not set then set the options to default and enter their names in the Unused Group. If the user set values are invalid then exception is thrown.
Author
Sharmila Prasad (6/4/2010)
References _FILEINFO_, Isis::PvlContainer::hasKeyword(), mbCameraRequired, mdMaxResolution, mdMinResolution, mPvlOpGrp, mStdOptionsGrp, Isis::toString(), and Isis::IException::User.
Referenced by Parse().
ValidatePvlShiftTolerances()
void Isis::ControlNetValidMeasure::ValidatePvlShiftTolerances () protected
Validate Pvl Sample, Line, Pixel (Sample and Line) Magnitude Shift Tolerances.
References _FILEINFO_, Isis::PvlContainer::hasKeyword(), m_lineShiftTolerance, m_pixelShiftTolerance, m_sampleShiftTolerance, mPvlOpGrp, mStdOptionsGrp, Isis::toString(), and Isis::IException::User.
Referenced by Parse().
ValidDnValue()
bool Isis::ControlNetValidMeasure::ValidDnValue (double pdDnValue)
Validate whether the DN Value is in the set Range.
Validates Dn Value by comparing against the Min and Max DN Values set in the def file or the defaults.
Author
Sharmila Prasad (3/30/2010)
Parameters
pdDnValue - DN Value to Valdiate
Returns
bool
References Isis::IsSpecial(), and mdMaxDN.
Referenced by Isis::GradientOperator::Interest(), Isis::MoravecOperator::Interest(), and ValidStandardOptions().
ValidEmissionAngle()
bool Isis::ControlNetValidMeasure::ValidEmissionAngle (double pdEmissionAngle)
Validate whether the Emission Angle is in the set Range.
Validates an Emission angle by comparing with the min and max values in the def file.
If Emission Angle is greater or lesser than the max/min values in the def file or the defaults it returns false else true.
Author
Sharmila Prasad (3/30/2010)
Parameters
pdEmissionAngle - Emission Angle to Valdiate
Returns
bool
References mdMaxEmissionAngle.
Referenced by ValidStandardOptions().
ValidIncidenceAngle()
bool Isis::ControlNetValidMeasure::ValidIncidenceAngle (double pdIncidenceAngle)
Validate whether the Incidence Angle is in the set Range.
Validates an Incidence angle by comparing with the min and max values in the def file.
If Incidence Angle is greater or lesser than the max/min values in the def file or the defaults it returns false else true.
Author
Sharmila Prasad (5/10/2010)
Parameters
pdIncidenceAngle - Incidence Angle to Valdiate
Returns
bool
References mdMaxIncidenceAngle.
Referenced by ValidStandardOptions().
ValidLatLon()
bool Isis::ControlNetValidMeasure::ValidLatLon (Isis::Camera * pCamera, int piSample, int piLine)
Validate the Lat/Lon.
Validate if a point has a valid lat, lon for that camera.
Author
Sharmila Prasad (6/4/2010)
Parameters
pCamera
piSample
piLine
Returns
bool
ValidResidualTolerances()
bool Isis::ControlNetValidMeasure::ValidResidualTolerances (double pdSampleResidual, double pdLineResidual, double pdResidualMagnitude, MeasureValidationResults & pResults)
Validate whether the Residuals are within the set Tolerance.
Validate whether the Sample and Line Residuals and Residual Magnitudes are within the set Tolerances'.
Author
Sharmila Prasad (5/16/2011)
Parameters
pdSampleResidual - Measure's Sample residual
pdLineResidual - Measure's Line residual
pdResidualMagnitude - Measure's Residual Magnitude
pResults - MeasureValidationResults
Returns
bool - Valid (true/false)
References Isis::MeasureValidationResults::addFailure(), Isis::MeasureValidationResults::LineResidual, mdLineResTolerance, mdResidualTolerance, mdSampleResTolerance, Isis::MeasureValidationResults::ResidualMagnitude, and Isis::MeasureValidationResults::SampleResidual.
Referenced by ValidStandardOptions().
ValidResolution()
bool Isis::ControlNetValidMeasure::ValidResolution (double pdResolution)
Validate whether the Resolution is in the set Range.
Validates Dn Value by comparing against the Min and Max DN Values set in the def file or the defaults.
Author
Sharmila Prasad (6/4/2010)
Parameters
pdResolution - Resolution to Validate
Returns
bool
References mdMaxResolution.
Referenced by ValidStandardOptions().
ValidShiftTolerances()
bool Isis::ControlNetValidMeasure::ValidShiftTolerances (double sampleShift, double lineShift, double pixelShift, MeasureValidationResults & results)
Validate whether the Sample and Line Shifts and Pixel Shift are within the set Tolerances.
Parameters
sampleShift Measure's sample shift (current - apriori)
lineShift Measure's line shift (current - apriori)
pixelShift Measure's pixel shift (Euclidean distance shifted)
results Validation results populated with any new failures
Returns
Whether every test was valid or not
References Isis::MeasureValidationResults::addFailure(), Isis::MeasureValidationResults::LineShift, m_lineShiftTolerance, m_pixelShiftTolerance, m_sampleShiftTolerance, Isis::MeasureValidationResults::PixelShift, and Isis::MeasureValidationResults::SampleShift.
Referenced by ValidStandardOptions().
ValidStandardOptions() [1/5]
MeasureValidationResults Isis::ControlNetValidMeasure::ValidStandardOptions (const ControlMeasure * pMeasure, Cube * pCube, Camera * camera, PvlGroup * pMeasureGrp = NULL)
Validate Standard options to pick a reference based on a particular criteria.
References Isis::ControlMeasure::GetLine(), Isis::ControlMeasure::GetSample(), and ValidStandardOptions().
ValidStandardOptions() [2/5]
MeasureValidationResults Isis::ControlNetValidMeasure::ValidStandardOptions (const ControlMeasure * pMeasure, Cube * pCube, PvlGroup * pMeasureGrp = NULL)
Validate Standard options to pick a reference based on a particular criteria.
Validate a measure for all the Standard Options.
Author
Sharmila Prasad (6/22/2010)
Parameters
piSample - Point Sample location
piLine - Point Line location
pCube - Control Measure Cube
pMeasureGrp - Log PvlGroup
Returns
bool
References Isis::ControlMeasure::GetLine(), and Isis::ControlMeasure::GetSample().
Referenced by Isis::InterestOperator::FindCnetRef(), Isis::InterestOperator::InterestByMeasure(), Isis::InterestOperator::Operate(), Isis::InterestOperator::ProcessLocked_Point_Reference(), and ValidStandardOptions().
ValidStandardOptions() [3/5]
MeasureValidationResults Isis::ControlNetValidMeasure::ValidStandardOptions (double pSample, double pLine, const ControlMeasure * pMeasure, Cube * pCube, Camera * measureCamera, PvlGroup * pMeasureGrp = NULL)
References Isis::MeasureValidationResults::addFailure(), Isis::MeasureValidationResults::DNValue, Isis::Sensor::EmissionAngle(), Isis::MeasureValidationResults::EmissionAngle, Isis::ControlMeasure::GetLineResidual(), Isis::ControlMeasure::GetLineShift(), Isis::ControlMeasure::GetPixelShift(), Isis::ControlMeasure::GetResidualMagnitude(), Isis::ControlMeasure::GetSampleResidual(), Isis::ControlMeasure::GetSampleShift(), Isis::Sensor::IncidenceAngle(), Isis::MeasureValidationResults::IncidenceAngle, m_lineShift, m_pixelShift, m_sampleShift, mbCameraRequired, mbValidateDN, mbValidateFromEdge, mdDnValue, mdEmissionAngle, mdIncidenceAngle, mdLineResidual, mdMaxDN, mdMaxEmissionAngle, mdMaxIncidenceAngle, mdMaxResolution, mdMetersFromEdge, mdMinDN, mdMinEmissionAngle, mdMinIncidenceAngle, mdMinResolution, mdResidualMagnitude, mdResolution, mdSampleResidual, MetersFromEdge(), Isis::MeasureValidationResults::MetersFromEdge, miPixelsFromEdge, Isis::Null, Isis::Camera::PixelResolution(), PixelsFromEdge(), Isis::MeasureValidationResults::PixelsFromEdge, Isis::Cube::pixelType(), Isis::Cube::read(), Isis::MeasureValidationResults::Resolution, Isis::Camera::SetImage(), Isis::Portal::SetPosition(), Isis::toString(), ValidDnValue(), ValidEmissionAngle(), ValidIncidenceAngle(), ValidResidualTolerances(), ValidResolution(), and ValidShiftTolerances().
ValidStandardOptions() [4/5]
MeasureValidationResults Isis::ControlNetValidMeasure::ValidStandardOptions (double pSample, double pLine, const ControlMeasure * pMeasure, Cube * pCube, PvlGroup * pMeasureGrp = NULL)
Validate Standard options to pick a reference based on a particular criteria.
Validate a point on an image and the Control Measure if not Null.
Author
Sharmila Prasad (5/17/2011)
Parameters
pSample - Image Sample
pLine - Image Line
pMeasure - Control Measure
pCube - Control Measure's image
pMeasureGrp - Result PvlGroup
Returns
MeasureValidationResults
References _FILEINFO_, Isis::Cube::camera(), Isis::Cube::fileName(), mbCameraRequired, Isis::IException::User, and ValidStandardOptions().
ValidStandardOptions() [5/5]
MeasureValidationResults Isis::ControlNetValidMeasure::ValidStandardOptions (double pSample, double pLine, Cube * pCube, PvlGroup * pMeasureGrp = NULL)
Validate Standard options to pick a reference based on a particular criteria.
Validate a point on an image for Standard Options.
Author
Sharmila Prasad (5/17/2011)
Parameters
pSample - Image Sample
pLine - Image Line
pCube - Image
pMeasureGrp - Optional Result Group
Returns
MeasureValidationResults
References ValidStandardOptions().
Member Data Documentation
m_lineShift
double Isis::ControlNetValidMeasure::m_lineShift protected
Store current Measure's Line Shift.
Referenced by ValidStandardOptions().
m_lineShiftTolerance
double Isis::ControlNetValidMeasure::m_lineShiftTolerance protected
Standard Option Line Shift.
Referenced by InitStdOptions(), InitStdOptionsGroup(), ValidatePvlShiftTolerances(), and ValidShiftTolerances().
m_pixelShift
double Isis::ControlNetValidMeasure::m_pixelShift protected
Store current Measure's Pixel Shift.
Referenced by ValidStandardOptions().
m_pixelShiftTolerance
double Isis::ControlNetValidMeasure::m_pixelShiftTolerance protected
Standard Option Pixel Shift.
Referenced by InitStdOptions(), InitStdOptionsGroup(), ValidatePvlShiftTolerances(), and ValidShiftTolerances().
m_sampleShift
double Isis::ControlNetValidMeasure::m_sampleShift protected
Store current Measure's Sample Shift.
Referenced by ValidStandardOptions().
m_sampleShiftTolerance
double Isis::ControlNetValidMeasure::m_sampleShiftTolerance protected
Standard Option Sample Shift.
Referenced by InitStdOptions(), InitStdOptionsGroup(), ValidatePvlShiftTolerances(), and ValidShiftTolerances().
mbCameraRequired
bool Isis::ControlNetValidMeasure::mbCameraRequired protected
To improve speed, flag to indicate if Camera needs to be opened.
Referenced by InitStdOptions(), IsCameraRequired(), SetCameraRequiredFlag(), ValidatePvlEmissionAngle(), ValidatePvlIncidenceAngle(), ValidatePvlResolution(), and ValidStandardOptions().
mbValidateDN
bool Isis::ControlNetValidMeasure::mbValidateDN protected
Check if DN needs to be Validated.
Referenced by InitStdOptions(), IsCubeRequired(), ValidatePvlDN(), and ValidStandardOptions().
mbValidateFromEdge
bool Isis::ControlNetValidMeasure::mbValidateFromEdge protected
Check if Pixels/Meters from edge needs to be Validated.
Referenced by InitStdOptions(), IsCubeRequired(), ValidatePvlFromEdge(), and ValidStandardOptions().
mCubeMgr
CubeManager Isis::ControlNetValidMeasure::mCubeMgr protected
CubeManager to open and read cubes.
Referenced by Isis::InterestOperator::FindCnetRef(), Isis::InterestOperator::FindOverlapByImageFootPrint(), Isis::InterestOperator::InterestByPoint(), Isis::InterestOperator::ProcessLocked_Point_Reference(), ReadSerialNumbers(), and ~ControlNetValidMeasure().
mdDnValue
double Isis::ControlNetValidMeasure::mdDnValue protected
Store current Measure's DN Value.
Referenced by Isis::InterestOperator::InterestByMeasure(), and ValidStandardOptions().
mdEmissionAngle
double Isis::ControlNetValidMeasure::mdEmissionAngle protected
Store current Measure's Emission Angle.
Referenced by Isis::InterestOperator::InterestByMeasure(), and ValidStandardOptions().
mdIncidenceAngle
double Isis::ControlNetValidMeasure::mdIncidenceAngle protected
Store current Measure's Incidence Angle.
Referenced by Isis::InterestOperator::InterestByMeasure(), and ValidStandardOptions().
mdLineResidual
double Isis::ControlNetValidMeasure::mdLineResidual protected
Store current Measure's Line Residual.
Referenced by ValidStandardOptions().
mdLineResTolerance
double Isis::ControlNetValidMeasure::mdLineResTolerance protected
Standard Option Line Residual.
Referenced by InitStdOptions(), InitStdOptionsGroup(), ValidatePvlResidualTolerances(), and ValidResidualTolerances().
mdMaxDN
double Isis::ControlNetValidMeasure::mdMaxDN protected
Standard Option MaxDN.
Referenced by GetMaxDN(), InitStdOptions(), InitStdOptionsGroup(), Isis::StandardDeviationOperator::Interest(), ValidatePvlDN(), ValidDnValue(), and ValidStandardOptions().
mdMaxEmissionAngle
double Isis::ControlNetValidMeasure::mdMaxEmissionAngle protected
Standard Option MaxEmissionAngle.
Referenced by GetMaxEmissionAngle(), InitStdOptions(), InitStdOptionsGroup(), ValidatePvlEmissionAngle(), ValidEmissionAngle(), and ValidStandardOptions().
mdMaxIncidenceAngle
double Isis::ControlNetValidMeasure::mdMaxIncidenceAngle protected
Standard Option MaxIncidenceAngle.
Referenced by GetMaxIncidenceAngle(), InitStdOptions(), InitStdOptionsGroup(), ValidatePvlIncidenceAngle(), ValidIncidenceAngle(), and ValidStandardOptions().
mdMaxResolution
double Isis::ControlNetValidMeasure::mdMaxResolution protected
Standard Option MaxResolution.
Referenced by InitStdOptions(), InitStdOptionsGroup(), ValidatePvlResolution(), ValidResolution(), and ValidStandardOptions().
mdMetersFromEdge
double Isis::ControlNetValidMeasure::mdMetersFromEdge protected
Standard Option MeteresFromEdge.
Referenced by GetMetersFromEdge(), InitStdOptions(), InitStdOptionsGroup(), MetersFromEdge(), ValidatePvlFromEdge(), and ValidStandardOptions().
mdMinDN
double Isis::ControlNetValidMeasure::mdMinDN protected
Standard Option MinDN.
Referenced by GetMinDN(), InitStdOptions(), InitStdOptionsGroup(), Isis::StandardDeviationOperator::Interest(), ValidatePvlDN(), and ValidStandardOptions().
mdMinEmissionAngle
double Isis::ControlNetValidMeasure::mdMinEmissionAngle protected
Standard Option MinEmissionAngle.
Referenced by GetMinEmissionAngle(), InitStdOptions(), InitStdOptionsGroup(), ValidatePvlEmissionAngle(), and ValidStandardOptions().
mdMinIncidenceAngle
double Isis::ControlNetValidMeasure::mdMinIncidenceAngle protected
Standard Option MinIncidenceAngle.
Referenced by GetMinIncidenceAngle(), InitStdOptions(), InitStdOptionsGroup(), ValidatePvlIncidenceAngle(), and ValidStandardOptions().
mdMinResolution
double Isis::ControlNetValidMeasure::mdMinResolution protected
Standard Option MinResolution.
Referenced by InitStdOptions(), InitStdOptionsGroup(), ValidatePvlResolution(), and ValidStandardOptions().
mdResidualMagnitude
double Isis::ControlNetValidMeasure::mdResidualMagnitude protected
Store current Measure's Residual Magnitude.
Referenced by ValidStandardOptions().
mdResidualTolerance
double Isis::ControlNetValidMeasure::mdResidualTolerance protected
Standard Option Residual Magnitude.
Referenced by InitStdOptions(), InitStdOptionsGroup(), ValidatePvlResidualTolerances(), and ValidResidualTolerances().
mdResolution
double Isis::ControlNetValidMeasure::mdResolution protected
Store current Measure's Resolution.
Referenced by Isis::InterestOperator::FindCnetRef(), Isis::InterestOperator::InterestByMeasure(), and ValidStandardOptions().
mdSampleResidual
double Isis::ControlNetValidMeasure::mdSampleResidual protected
Store current Measure's Sample Residual.
Referenced by ValidStandardOptions().
mdSampleResTolerance
double Isis::ControlNetValidMeasure::mdSampleResTolerance protected
Standard Option Sample Residual.
Referenced by InitStdOptions(), InitStdOptionsGroup(), ValidatePvlResidualTolerances(), and ValidResidualTolerances().
miPixelsFromEdge
int Isis::ControlNetValidMeasure::miPixelsFromEdge protected
Standard Option PixelsFromEdge.
Referenced by GetPixelsFromEdge(), InitStdOptions(), InitStdOptionsGroup(), PixelsFromEdge(), ValidatePvlFromEdge(), and ValidStandardOptions().
mPvlLog
Pvl Isis::ControlNetValidMeasure::mPvlLog protected
Pvl Log of all the processing.
Referenced by Isis::InterestOperator::FindCnetRef(), GetLogPvl(), and Parse().
mPvlOpGrp
PvlGroup Isis::ControlNetValidMeasure::mPvlOpGrp protected
Pvl Operator Group.
Referenced by Parse(), ValidatePvlDN(), ValidatePvlEmissionAngle(), ValidatePvlFromEdge(), ValidatePvlIncidenceAngle(), ValidatePvlResidualTolerances(), ValidatePvlResolution(), and ValidatePvlShiftTolerances().
mSerialNumbers
SerialNumberList Isis::ControlNetValidMeasure::mSerialNumbers protected
Serial numbers list.
Referenced by Isis::InterestOperator::FindCnetRef(), Isis::InterestOperator::FindOverlapByImageFootPrint(), Isis::InterestOperator::InterestByMeasure(), Isis::InterestOperator::InterestByPoint(), Isis::InterestOperator::ProcessLocked_Point_Reference(), and ReadSerialNumbers().
mStatisticsGrp
PvlGroup Isis::ControlNetValidMeasure::mStatisticsGrp protected
Pvl output Statistics Group.
Referenced by ControlNetValidMeasure(), Isis::InterestOperator::FindCnetRef(), and GetStatistics().
mStatus
Progress Isis::ControlNetValidMeasure::mStatus protected
Monitor the status of the app.
Referenced by Isis::InterestOperator::FindCnetRef(), and ReadSerialNumbers().
mStdOptionsGrp
PvlGroup Isis::ControlNetValidMeasure::mStdOptionsGrp protected
Pvl Standard Options Group.
Referenced by GetStdOptions(), InitStdOptionsGroup(), Parse(), ValidatePvlDN(), ValidatePvlEmissionAngle(), ValidatePvlFromEdge(), ValidatePvlIncidenceAngle(), ValidatePvlResidualTolerances(), ValidatePvlResolution(), and ValidatePvlShiftTolerances().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/ControlNetValidMeasure/ControlNetValidMeasure.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/ControlNetValidMeasure/ControlNetValidMeasure.cpp