Isis Developer Reference: Isis::FileList Class Reference
Isis::FileList Class Reference
Parsing
Internalizes a list of files.
#include <FileList.h>
Public Member Functions
FileList (FileName listFile)
Creates a FileList based on a FileName.
FileList (std::istream &in)
Constructs a FileList from an istream.
FileList ()
Creates an empty FileList obj.
~FileList ()
Destroys the FileList object.
void read (FileName listFile)
reads in a FileName obj
void read (std::istream &in)
reads in an istream
void write (FileName outputFileList)
writes to a FileName obj
void write (std::ostream &out)
writes to an ostream
Detailed Description
Internalizes a list of files.
This class reads a list of filenames from a file an internalizes them in a standard template vector of strings. Thus, a file like:
m0035431.imq
m0030402.imq
m0033231.imq
   .
   .
   .
m0203331.imq
Will be internalized as and accessable as an vector.
Author
2003-05-01 Jeff Anderson
Constructor & Destructor Documentation
FileList() [1/3]
Isis::FileList::FileList (FileName listFile)
Creates a FileList based on a FileName.
Constructs a FileList from a FileName.
Parameters
listFile A FileName obj
FileList() [2/3]
Isis::FileList::FileList (std::istream & in)
Constructs a FileList from an istream.
Parameters
in the istream to read from
FileList() [3/3]
Isis::FileList::FileList ()
Creates an empty FileList obj.
Constructs an empty FileList.
~FileList()
Isis::FileList::~FileList () inline
Destroys the FileList object.
Member Function Documentation
read() [1/2]
void Isis::FileList::read (FileName listFile)
reads in a FileName obj
Opens and loads the list of files from a file.
Parameters
listFile Name of the file to open that contains the list of files.
Exceptions
Isis::iException::Io - Cannot open file
References _FILEINFO_, Isis::Message::FileOpen(), and Isis::FileName::toString().
Referenced by Isis::Equalization::addHolds(), and Isis::Equalization::loadOutputs().
read() [2/2]
void Isis::FileList::read (std::istream & in)
reads in an istream
Loads list of files from a stream.
This takes in a stream and loads a file list from it. The lines in the stream are considered separate entries, and comments are ignored. comments are considered to be any line starting with a '#' or '//', and anything after any whitespace following the first text on the line.
Parameters
in An input stream containing a list of files.
References _FILEINFO_, Isis::IString::Token(), Isis::IString::ToQt(), Isis::IString::TrimHead(), and Isis::IString::TrimTail().
write() [1/2]
void Isis::FileList::write (FileName outputFileList)
writes to a FileName obj
Writes a list of files to a file.
Parameters
outputFileList The name of the file to create. The method will overwrite any existing files.
Exceptions
Isis::iException::Io File could not be created.
References _FILEINFO_, Isis::Message::FileOpen(), and Isis::FileName::toString().
Referenced by Isis::Pipeline::Run().
write() [2/2]
void Isis::FileList::write (std::ostream & out)
writes to an ostream
Writes a list of files to a stream.
Parameters
out The list will be written to this output stream.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/FileList/FileList.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/FileList/FileList.cpp