Isis Developer Reference: Isis::MocLabels Class Reference
Isis::MocLabels Class Reference
Spice, Instruments, and Cameras | Mission Specific Objects » Mars Global Surveyor
Read values from MOC labels.
#include <MocLabels.h>
Public Member Functions
MocLabels (Cube &cube)
Construct MocLabels object using a Pvl object.
MocLabels (const QString &file)
Construct MocLabels object using the file name.
~MocLabels ()
Empty destructor.
bool NarrowAngle () const
Indicates whether the camera was narrow angle.
bool WideAngle () const
Indicates whether the camera was wide angle.
bool WideAngleRed () const
Indicates whether the camera was red wide angle.
bool WideAngleBlue () const
Indicates whether the camera was blue wide angle.
int CrosstrackSumming () const
Returns value for CrosstrackSumming from the instrument group.
int DowntrackSumming () const
Returns value for DowntrackSumming from the instrument group.
int FirstLineSample () const
Returns value for FirstLineSample from the instrument group.
double FocalPlaneTemperature () const
Returns value for FocalPlaneTemperature from the instrument group.
double LineRate () const
Returns the value for the true line rate.
double ExposureDuration () const
Returns the value for LineExposureDuration from the instrument group.
QString StartTime () const
Returns the value for StartTime from the instrument group.
int Detectors () const
Returns 2048 if narrow angle and 3456 if wide angle.
int StartDetector (int sample) const
Converts from sample to starting detector.
int EndDetector (int sample) const
Converts from sample to ending detector.
double Sample (int detector) const
Converts from detector to sample.
double EphemerisTime (double line) const
Returns the ephemeris time at the given line.
double Gain (int line=1)
Returns the true gain at a given line.
double Offset (int line=1)
Returns the offset at the given line.
Detailed Description
Read values from MOC labels.
Author
2007-01-30 Author Unknown
Constructor & Destructor Documentation
MocLabels() [1/2]
Isis::MocLabels::MocLabels (Cube & cube)
Construct MocLabels object using a Pvl object.
MocLabels() [2/2]
Isis::MocLabels::MocLabels (const QString & file)
Construct MocLabels object using the file name.
~MocLabels()
Isis::MocLabels::~MocLabels () inline
Empty destructor.
Member Function Documentation
CrosstrackSumming()
int Isis::MocLabels::CrosstrackSumming () const inline
Returns value for CrosstrackSumming from the instrument group.
Returns
int Crosstrack summing
Referenced by Isis::MocWideAngleCamera::MocWideAngleCamera().
Detectors()
int Isis::MocLabels::Detectors () const inline
Returns 2048 if narrow angle and 3456 if wide angle.
Returns
int Value of detectors.
DowntrackSumming()
int Isis::MocLabels::DowntrackSumming () const inline
Returns value for DowntrackSumming from the instrument group.
Returns
int Downtrack summing
Referenced by Isis::MocWideAngleCamera::MocWideAngleCamera().
EndDetector()
int Isis::MocLabels::EndDetector (int sample) const
Converts from sample to ending detector.
Parameters
sample Sample to be converted
Returns
int Converted ending detector
References _FILEINFO_.
EphemerisTime()
double Isis::MocLabels::EphemerisTime (double line) const
Returns the ephemeris time at the given line.
Parameters
line Line to evaluate
Returns
double Ephemeris time
ExposureDuration()
double Isis::MocLabels::ExposureDuration () const inline
Returns the value for LineExposureDuration from the instrument group.
Returns
double Line exposure duration
FirstLineSample()
int Isis::MocLabels::FirstLineSample () const inline
Returns value for FirstLineSample from the instrument group.
Returns
int First line sample
Referenced by Isis::MocWideAngleCamera::MocWideAngleCamera().
FocalPlaneTemperature()
double Isis::MocLabels::FocalPlaneTemperature () const inline
Returns value for FocalPlaneTemperature from the instrument group.
Returns
double Focal plane temperature
Gain()
double Isis::MocLabels::Gain (int line = 1)
Returns the true gain at a given line.
Parameters
line Line to evaluate
Returns
double True gain
LineRate()
double Isis::MocLabels::LineRate () const inline
Returns the value for the true line rate.
This is calculated by dividing the product of LineExposureDuration and the DowntrackSumming by 1000.
Returns
double Value for the true line rate
Referenced by Isis::MocWideAngleCamera::MocWideAngleCamera().
NarrowAngle()
bool Isis::MocLabels::NarrowAngle () const inline
Indicates whether the camera was narrow angle.
Returns
bool True if the instrument ID is MOC-NA.
Offset()
double Isis::MocLabels::Offset (int line = 1)
Returns the offset at the given line.
Parameters
line Line to evaluate
Returns
double Offset
Sample()
double Isis::MocLabels::Sample (int detector) const
Converts from detector to sample.
Parameters
detector Detector to be converted
Returns
double Converted sample
References _FILEINFO_.
StartDetector()
int Isis::MocLabels::StartDetector (int sample) const
Converts from sample to starting detector.
Parameters
sample Sample to be converted
Returns
int Converted start detector
References _FILEINFO_.
StartTime()
QString Isis::MocLabels::StartTime () const inline
Returns the value for StartTime from the instrument group.
Returns
QString Start time
WideAngle()
bool Isis::MocLabels::WideAngle () const inline
Indicates whether the camera was wide angle.
Returns
bool True if the instrument ID is MOC-WA.
WideAngleBlue()
bool Isis::MocLabels::WideAngleBlue () const inline
Indicates whether the camera was blue wide angle.
Returns
bool True if the instrument ID is MOC-WA and filter name is BLUE.
WideAngleRed()
bool Isis::MocLabels::WideAngleRed () const inline
Indicates whether the camera was red wide angle.
Returns
bool True if the instrument ID is MOC-WA and filter name is RED.
Referenced by Isis::MocWideAngleCamera::MocWideAngleCamera().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/mgs/objs/MocLabels/MocLabels.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/mgs/objs/MocLabels/MocLabels.cpp