Isis Developer Reference: Isis::SensorInfoWidget Class Reference
Isis::SensorInfoWidget Class Reference
Control Networks
Widget for displaying information about a sensor.
#include <SensorInfoWidget.h>
Public Member Functions
SensorInfoWidget (GuiCamera *camera, Directory *directory, QWidget *parent=0)
Constructor.
~SensorInfoWidget ()
Destructor.
Detailed Description
Widget for displaying information about a sensor.
Author
2015-07-10 Ken Edmundson
Constructor & Destructor Documentation
SensorInfoWidget()
Isis::SensorInfoWidget::SensorInfoWidget (GuiCamera * camera, Directory * directory, QWidget * parent = 0) explicit
Constructor.
Parameters
camera The camera whose information is being displayed
directory unused
parent The parent widget
References Isis::DisplayProperties::displayName(), Isis::GuiCamera::displayProperties(), and Isis::GuiCamera::spacecraftNameLong().
~SensorInfoWidget()
Isis::SensorInfoWidget::~SensorInfoWidget ()
Destructor.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/SensorInfoWidget/SensorInfoWidget.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/SensorInfoWidget/SensorInfoWidget.cpp