Isis Developer Reference: Isis::QnetPointMeasureFilter Class Reference
Isis::QnetPointMeasureFilter Class Reference
Defines the Measure Properties filter for the QnetNavTool's Points section.
#include <QnetPointMeasureFilter.h>
Signals
void filteredListModified ()
Public Member Functions
QnetPointMeasureFilter (QnetNavTool *navTool, QWidget *parent=0)
Contructor for the Point Measure filter.
virtual void filter ()
Filters a list of points for points that have at least one measure of the selected type(s).
Protected Member Functions
QList< int > & filteredImages ()
const QList< int > & filteredImages () const
QList< int > & filteredPoints ()
const QList< int > & filteredPoints () const
ControlNet * controlNet ()
const ControlNet * controlNet () const
SerialNumberList * serialNumberList ()
const SerialNumberList * serialNumberList () const
Detailed Description
Defines the Measure Properties filter for the QnetNavTool's Points section.
This class filters points whose measures have at least one measure with the selected properties. If the user chooses more than one measure type, the list will contain points with at least one measure with either of these types. If the user chooses to filter by measure type and ignore status, the list will contain points with at least one measure that contains both of these properties. This class is designed to remove points from the current filtered list that do not contain any measures of the selected type.
Author
????-??-?? Unknown
Constructor & Destructor Documentation
QnetPointMeasureFilter()
Isis::QnetPointMeasureFilter::QnetPointMeasureFilter (QnetNavTool * navTool, QWidget * parent = 0)
Contructor for the Point Measure filter.
It creates the Measure filter window found in the navtool
Parameters
parent The parent widget for the point measure filter
Member Function Documentation
controlNet() [1/2]
ControlNet * Isis::QnetFilter::controlNet () protected inherited
References Isis::QnetNavTool::controlNet().
Referenced by Isis::QnetCubeDistanceFilter::filter(), Isis::QnetCubePointsFilter::filter(), Isis::QnetPointCubeNameFilter::filter(), Isis::QnetPointDistanceFilter::filter(), Isis::QnetPointGoodnessFilter::filter(), Isis::QnetPointIdFilter::filter(), Isis::QnetPointImagesFilter::filter(), Isis::QnetPointJigsawErrorFilter::filter(), filter(), Isis::QnetPointRangeFilter::filter(), Isis::QnetPointRegistrationErrorFilter::filter(), and Isis::QnetPointTypeFilter::filter().
controlNet() [2/2]
const ControlNet * Isis::QnetFilter::controlNet () const protected inherited
References Isis::QnetNavTool::controlNet().
filter()
void Isis::QnetPointMeasureFilter::filter () virtual
Filters a list of points for points that have at least one measure of the selected type(s).
The filtered list will appear in the navtools point list display.
Reimplemented from Isis::QnetFilter.
References Isis::QnetFilter::controlNet(), Isis::QnetFilter::filteredListModified(), Isis::QnetFilter::filteredPoints(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlPoint::IsEditLocked(), and Isis::ControlPoint::IsIgnored().
filteredImages() [1/2]
QList< int > & Isis::QnetFilter::filteredImages () protected inherited
References Isis::QnetNavTool::filteredImages().
Referenced by Isis::QnetCubeDistanceFilter::filter(), Isis::QnetCubeNameFilter::filter(), and Isis::QnetCubePointsFilter::filter().
filteredImages() [2/2]
const QList< int > & Isis::QnetFilter::filteredImages () const protected inherited
References Isis::QnetNavTool::filteredImages().
filteredListModified
void Isis::QnetFilter::filteredListModified () signal inherited
Referenced by Isis::QnetCubeDistanceFilter::filter(), Isis::QnetCubeNameFilter::filter(), Isis::QnetCubePointsFilter::filter(), Isis::QnetPointCubeNameFilter::filter(), Isis::QnetPointDistanceFilter::filter(), Isis::QnetPointGoodnessFilter::filter(), Isis::QnetPointIdFilter::filter(), Isis::QnetPointImagesFilter::filter(), Isis::QnetPointJigsawErrorFilter::filter(), filter(), Isis::QnetPointRangeFilter::filter(), Isis::QnetPointRegistrationErrorFilter::filter(), and Isis::QnetPointTypeFilter::filter().
filteredPoints() [1/2]
QList< int > & Isis::QnetFilter::filteredPoints () protected inherited
References Isis::QnetNavTool::filteredPoints().
Referenced by Isis::QnetPointCubeNameFilter::filter(), Isis::QnetPointDistanceFilter::filter(), Isis::QnetPointGoodnessFilter::filter(), Isis::QnetPointIdFilter::filter(), Isis::QnetPointImagesFilter::filter(), Isis::QnetPointJigsawErrorFilter::filter(), filter(), Isis::QnetPointRangeFilter::filter(), Isis::QnetPointRegistrationErrorFilter::filter(), and Isis::QnetPointTypeFilter::filter().
filteredPoints() [2/2]
const QList< int > & Isis::QnetFilter::filteredPoints () const protected inherited
References Isis::QnetNavTool::filteredPoints().
serialNumberList() [1/2]
SerialNumberList * Isis::QnetFilter::serialNumberList () protected inherited
References Isis::QnetNavTool::serialNumberList().
Referenced by Isis::QnetPointCubeNameFilter::createCubeList(), Isis::QnetCubeDistanceFilter::filter(), Isis::QnetCubeNameFilter::filter(), Isis::QnetCubePointsFilter::filter(), Isis::QnetPointCubeNameFilter::filter(), and Isis::QnetPointDistanceFilter::filter().
serialNumberList() [2/2]
const SerialNumberList * Isis::QnetFilter::serialNumberList () const protected inherited
References Isis::QnetNavTool::serialNumberList().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/QnetTools/QnetPointMeasureFilter.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/QnetTools/QnetPointMeasureFilter.cpp