Isis Developer Reference: Isis::AbstractMultipleChoiceFilter Class Reference
Isis::AbstractMultipleChoiceFilter Class Reference abstract
Base class for combo box type filters.
#include <AbstractMultipleChoiceFilter.h>
Public Types
enum FilterEffectiveness { Images = 1 , Points = 2 , Measures = 4 }
Signals
void filterChanged ()
Public Member Functions
AbstractMultipleChoiceFilter (AbstractFilter::FilterEffectivenessFlag, int minimumForSuccess=-1)
AbstractMultipleChoiceFilter (const AbstractMultipleChoiceFilter &other)
virtual ~AbstractMultipleChoiceFilter ()
virtual bool canFilterImages () const
virtual bool canFilterPoints () const
virtual bool canFilterMeasures () const
virtual bool evaluate (const QPair< QString, ControlNet * > *) const =0
virtual bool evaluate (const ControlPoint *) const =0
virtual bool evaluate (const ControlMeasure *) const =0
virtual AbstractFilter * clone () const =0
virtual QString getImageDescription () const
virtual QString getPointDescription () const
virtual QString getMeasureDescription () const
Protected Member Functions
void createWidget (QStringList options)
QString const & getCurrentChoice () const
virtual bool evaluate (const ControlPoint *, bool(ControlPoint::*)() const) const
virtual bool evaluate (const ControlMeasure *, bool(ControlMeasure::*)() const) const
bool inclusive () const
int getMinForSuccess () const
AbstractFilter::FilterEffectivenessFlag * getEffectivenessFlags () const
QBoxLayout * getMainLayout () const
QBoxLayout * getInclusiveExclusiveLayout () const
bool evaluateImageFromPointFilter (const QPair< QString, ControlNet * > *) const
bool evaluateImageFromMeasureFilter (const QPair< QString, ControlNet * > *) const
bool evaluatePointFromMeasureFilter (const ControlPoint *) const
Detailed Description
Base class for combo box type filters.
This class is the base class that all filters that use combo boxes.
Author
????-??-?? Eric Hyer
Member Enumeration Documentation
FilterEffectiveness
enum Isis::AbstractFilter::FilterEffectiveness inherited
Enumerator
Images
Points
Measures
Constructor & Destructor Documentation
AbstractMultipleChoiceFilter() [1/2]
Isis::AbstractMultipleChoiceFilter::AbstractMultipleChoiceFilter (AbstractFilter::FilterEffectivenessFlag flag, int minimumForSuccess = -1)
AbstractMultipleChoiceFilter() [2/2]
Isis::AbstractMultipleChoiceFilter::AbstractMultipleChoiceFilter (const AbstractMultipleChoiceFilter & other)
References createWidget().
~AbstractMultipleChoiceFilter()
Isis::AbstractMultipleChoiceFilter::~AbstractMultipleChoiceFilter () virtual
Member Function Documentation
canFilterImages()
bool Isis::AbstractFilter::canFilterImages () const virtual inherited
References Isis::AbstractFilter::Images.
Referenced by Isis::FilterWidget::evaluate(), Isis::AbstractFilter::evaluateImageFromMeasureFilter(), and Isis::AbstractFilter::evaluateImageFromPointFilter().
canFilterMeasures()
bool Isis::AbstractFilter::canFilterMeasures () const virtual inherited
References Isis::AbstractFilter::Measures.
Referenced by Isis::FilterWidget::evaluate().
canFilterPoints()
bool Isis::AbstractFilter::canFilterPoints () const virtual inherited
References Isis::AbstractFilter::Points.
Referenced by Isis::FilterWidget::evaluate(), and Isis::AbstractFilter::evaluatePointFromMeasureFilter().
clone()
virtual AbstractFilter* Isis::AbstractFilter::clone () const pure virtual inherited
Implemented in Isis::SampleShiftFilter, Isis::SampleResidualFilter, Isis::SampleFilter, Isis::ResidualMagnitudeFilter, Isis::PointTypeFilter, Isis::PointJigsawRejectedFilter, Isis::PointIgnoredFilter, Isis::PointIdFilter, Isis::PointEditLockedFilter, Isis::MeasureTypeFilter, Isis::MeasureJigsawRejectedFilter, Isis::MeasureIgnoredFilter, Isis::MeasureCountFilter, Isis::LineShiftFilter, Isis::LineResidualFilter, Isis::LineFilter, Isis::ImageIdFilter, Isis::GoodnessOfFitFilter, Isis::ChooserNameFilter, Isis::APrioriZSigmaFilter, Isis::APrioriZFilter, Isis::APrioriYSigmaFilter, Isis::APrioriYFilter, Isis::APrioriXSigmaFilter, Isis::APrioriXFilter, Isis::APrioriRadiusSigmaFilter, Isis::APrioriRadiusFilter, Isis::APrioriLongitudeSigmaFilter, Isis::APrioriLongitudeFilter, Isis::APrioriLatitudeSigmaFilter, Isis::APrioriLatitudeFilter, Isis::AdjustedZSigmaFilter, Isis::AdjustedZFilter, Isis::AdjustedYSigmaFilter, Isis::AdjustedYFilter, Isis::AdjustedXSigmaFilter, Isis::AdjustedXFilter, Isis::AdjustedRadiusSigmaFilter, Isis::AdjustedRadiusFilter, Isis::AdjustedLongitudeSigmaFilter, Isis::AdjustedLongitudeFilter, Isis::AdjustedLatitudeSigmaFilter, and Isis::AdjustedLatitudeFilter.
Referenced by Isis::ImageImageFilterSelector::ImageImageFilterSelector(), Isis::ImagePointFilterSelector::ImagePointFilterSelector(), Isis::AbstractFilterSelector::operator=(), and Isis::PointMeasureFilterSelector::PointMeasureFilterSelector().
createWidget()
void Isis::AbstractMultipleChoiceFilter::createWidget (QStringList options) protected
References Isis::AbstractFilter::getMainLayout().
Referenced by AbstractMultipleChoiceFilter(), Isis::MeasureTypeFilter::MeasureTypeFilter(), and Isis::PointTypeFilter::PointTypeFilter().
evaluate() [1/5]
virtual bool Isis::AbstractFilter::evaluate (const ControlMeasure *) const pure virtual inherited
Implemented in Isis::SampleShiftFilter, Isis::SampleResidualFilter, Isis::SampleFilter, Isis::ResidualMagnitudeFilter, Isis::PointTypeFilter, Isis::PointJigsawRejectedFilter, Isis::PointIgnoredFilter, Isis::PointIdFilter, Isis::PointEditLockedFilter, Isis::MeasureTypeFilter, Isis::MeasureJigsawRejectedFilter, Isis::MeasureIgnoredFilter, Isis::MeasureCountFilter, Isis::LineShiftFilter, Isis::LineResidualFilter, Isis::LineFilter, Isis::ImageIdFilter, Isis::GoodnessOfFitFilter, Isis::ChooserNameFilter, Isis::APrioriZSigmaFilter, Isis::APrioriZFilter, Isis::APrioriYSigmaFilter, Isis::APrioriYFilter, Isis::APrioriXSigmaFilter, Isis::APrioriXFilter, Isis::APrioriRadiusSigmaFilter, Isis::APrioriRadiusFilter, Isis::APrioriLongitudeSigmaFilter, Isis::APrioriLongitudeFilter, Isis::APrioriLatitudeSigmaFilter, Isis::APrioriLatitudeFilter, Isis::AdjustedZSigmaFilter, Isis::AdjustedZFilter, Isis::AdjustedYSigmaFilter, Isis::AdjustedYFilter, Isis::AdjustedXSigmaFilter, Isis::AdjustedXFilter, Isis::AdjustedRadiusSigmaFilter, Isis::AdjustedRadiusFilter, Isis::AdjustedLongitudeSigmaFilter, Isis::AdjustedLongitudeFilter, Isis::AdjustedLatitudeSigmaFilter, and Isis::AdjustedLatitudeFilter.
evaluate() [2/5]
bool Isis::AbstractFilter::evaluate (const ControlMeasure * measure, bool(ControlMeasure::*)() const meth) const protected virtual inherited
References Isis::AbstractFilter::inclusive().
evaluate() [3/5]
virtual bool Isis::AbstractFilter::evaluate (const ControlPoint *) const pure virtual inherited
Implemented in Isis::SampleShiftFilter, Isis::SampleResidualFilter, Isis::SampleFilter, Isis::ResidualMagnitudeFilter, Isis::PointTypeFilter, Isis::PointJigsawRejectedFilter, Isis::PointIgnoredFilter, Isis::PointIdFilter, Isis::PointEditLockedFilter, Isis::MeasureTypeFilter, Isis::MeasureJigsawRejectedFilter, Isis::MeasureIgnoredFilter, Isis::MeasureCountFilter, Isis::LineShiftFilter, Isis::LineResidualFilter, Isis::LineFilter, Isis::ImageIdFilter, Isis::GoodnessOfFitFilter, Isis::ChooserNameFilter, Isis::APrioriZSigmaFilter, Isis::APrioriZFilter, Isis::APrioriYSigmaFilter, Isis::APrioriYFilter, Isis::APrioriXSigmaFilter, Isis::APrioriXFilter, Isis::APrioriRadiusSigmaFilter, Isis::APrioriRadiusFilter, Isis::APrioriLongitudeSigmaFilter, Isis::APrioriLongitudeFilter, Isis::APrioriLatitudeSigmaFilter, Isis::APrioriLatitudeFilter, Isis::AdjustedZSigmaFilter, Isis::AdjustedZFilter, Isis::AdjustedYSigmaFilter, Isis::AdjustedYFilter, Isis::AdjustedXSigmaFilter, Isis::AdjustedXFilter, Isis::AdjustedRadiusSigmaFilter, Isis::AdjustedRadiusFilter, Isis::AdjustedLongitudeSigmaFilter, Isis::AdjustedLongitudeFilter, Isis::AdjustedLatitudeSigmaFilter, and Isis::AdjustedLatitudeFilter.
evaluate() [4/5]
bool Isis::AbstractFilter::evaluate (const ControlPoint * point, bool(ControlPoint::*)() const meth) const protected virtual inherited
References Isis::AbstractFilter::inclusive().
evaluate() [5/5]
virtual bool Isis::AbstractFilter::evaluate (const QPair< QString, ControlNet * > *) const pure virtual inherited
Implemented in Isis::SampleShiftFilter, Isis::SampleResidualFilter, Isis::SampleFilter, Isis::ResidualMagnitudeFilter, Isis::PointTypeFilter, Isis::PointJigsawRejectedFilter, Isis::PointIgnoredFilter, Isis::PointIdFilter, Isis::PointEditLockedFilter, Isis::MeasureTypeFilter, Isis::MeasureJigsawRejectedFilter, Isis::MeasureIgnoredFilter, Isis::MeasureCountFilter, Isis::LineShiftFilter, Isis::LineResidualFilter, Isis::LineFilter, Isis::ImageIdFilter, Isis::GoodnessOfFitFilter, Isis::ChooserNameFilter, Isis::APrioriZSigmaFilter, Isis::APrioriZFilter, Isis::APrioriYSigmaFilter, Isis::APrioriYFilter, Isis::APrioriXSigmaFilter, Isis::APrioriXFilter, Isis::APrioriRadiusSigmaFilter, Isis::APrioriRadiusFilter, Isis::APrioriLongitudeSigmaFilter, Isis::APrioriLongitudeFilter, Isis::APrioriLatitudeSigmaFilter, Isis::APrioriLatitudeFilter, Isis::AdjustedZSigmaFilter, Isis::AdjustedZFilter, Isis::AdjustedYSigmaFilter, Isis::AdjustedYFilter, Isis::AdjustedXSigmaFilter, Isis::AdjustedXFilter, Isis::AdjustedRadiusSigmaFilter, Isis::AdjustedRadiusFilter, Isis::AdjustedLongitudeSigmaFilter, Isis::AdjustedLongitudeFilter, Isis::AdjustedLatitudeSigmaFilter, and Isis::AdjustedLatitudeFilter.
Referenced by Isis::MeasureIgnoredFilter::evaluate(), Isis::MeasureJigsawRejectedFilter::evaluate(), Isis::PointEditLockedFilter::evaluate(), Isis::PointIgnoredFilter::evaluate(), Isis::PointJigsawRejectedFilter::evaluate(), and Isis::AbstractFilterSelector::evaluate().
evaluateImageFromMeasureFilter()
bool Isis::AbstractFilter::evaluateImageFromMeasureFilter (const QPair< QString, ControlNet * > * imageAndNet) const protected inherited
References Isis::AbstractFilter::canFilterImages().
Referenced by Isis::GoodnessOfFitFilter::evaluate(), Isis::LineFilter::evaluate(), Isis::LineResidualFilter::evaluate(), Isis::LineShiftFilter::evaluate(), Isis::MeasureIgnoredFilter::evaluate(), Isis::MeasureJigsawRejectedFilter::evaluate(), Isis::MeasureTypeFilter::evaluate(), Isis::ResidualMagnitudeFilter::evaluate(), Isis::SampleFilter::evaluate(), Isis::SampleResidualFilter::evaluate(), and Isis::SampleShiftFilter::evaluate().
evaluateImageFromPointFilter()
bool Isis::AbstractFilter::evaluateImageFromPointFilter (const QPair< QString, ControlNet * > * imageAndNet) const protected inherited
References Isis::AbstractFilter::canFilterImages().
Referenced by Isis::AdjustedLatitudeFilter::evaluate(), Isis::AdjustedLatitudeSigmaFilter::evaluate(), Isis::AdjustedLongitudeFilter::evaluate(), Isis::AdjustedLongitudeSigmaFilter::evaluate(), Isis::AdjustedRadiusFilter::evaluate(), Isis::AdjustedRadiusSigmaFilter::evaluate(), Isis::AdjustedXFilter::evaluate(), Isis::AdjustedXSigmaFilter::evaluate(), Isis::AdjustedYFilter::evaluate(), Isis::AdjustedYSigmaFilter::evaluate(), Isis::AdjustedZFilter::evaluate(), Isis::AdjustedZSigmaFilter::evaluate(), Isis::APrioriLatitudeFilter::evaluate(), Isis::APrioriLatitudeSigmaFilter::evaluate(), Isis::APrioriLongitudeFilter::evaluate(), Isis::APrioriLongitudeSigmaFilter::evaluate(), Isis::APrioriRadiusFilter::evaluate(), Isis::APrioriRadiusSigmaFilter::evaluate(), Isis::APrioriXFilter::evaluate(), Isis::APrioriXSigmaFilter::evaluate(), Isis::APrioriYFilter::evaluate(), Isis::APrioriYSigmaFilter::evaluate(), Isis::APrioriZFilter::evaluate(), Isis::APrioriZSigmaFilter::evaluate(), Isis::ChooserNameFilter::evaluate(), Isis::MeasureCountFilter::evaluate(), Isis::PointEditLockedFilter::evaluate(), Isis::PointIdFilter::evaluate(), Isis::PointIgnoredFilter::evaluate(), Isis::PointJigsawRejectedFilter::evaluate(), and Isis::PointTypeFilter::evaluate().
evaluatePointFromMeasureFilter()
bool Isis::AbstractFilter::evaluatePointFromMeasureFilter (const ControlPoint * point) const protected inherited
References Isis::AbstractFilter::canFilterPoints(), and Isis::ControlPoint::getMeasures().
Referenced by Isis::GoodnessOfFitFilter::evaluate(), Isis::ImageIdFilter::evaluate(), Isis::LineFilter::evaluate(), Isis::LineResidualFilter::evaluate(), Isis::LineShiftFilter::evaluate(), Isis::MeasureIgnoredFilter::evaluate(), Isis::MeasureJigsawRejectedFilter::evaluate(), Isis::MeasureTypeFilter::evaluate(), Isis::ResidualMagnitudeFilter::evaluate(), Isis::SampleFilter::evaluate(), Isis::SampleResidualFilter::evaluate(), and Isis::SampleShiftFilter::evaluate().
filterChanged
void Isis::AbstractFilter::filterChanged () signal inherited
getCurrentChoice()
QString const & Isis::AbstractMultipleChoiceFilter::getCurrentChoice () const protected
Referenced by Isis::MeasureTypeFilter::evaluate(), Isis::PointTypeFilter::evaluate(), Isis::MeasureTypeFilter::getImageDescription(), Isis::PointTypeFilter::getImageDescription(), Isis::MeasureTypeFilter::getMeasureDescription(), and Isis::PointTypeFilter::getPointDescription().
getEffectivenessFlags()
AbstractFilter::FilterEffectivenessFlag * Isis::AbstractFilter::getEffectivenessFlags () const protected inherited
getImageDescription()
QString Isis::AbstractFilter::getImageDescription () const virtual inherited
Reimplemented in Isis::SampleShiftFilter, Isis::SampleResidualFilter, Isis::SampleFilter, Isis::ResidualMagnitudeFilter, Isis::PointTypeFilter, Isis::PointJigsawRejectedFilter, Isis::PointIgnoredFilter, Isis::PointIdFilter, Isis::PointEditLockedFilter, Isis::MeasureTypeFilter, Isis::MeasureJigsawRejectedFilter, Isis::MeasureIgnoredFilter, Isis::MeasureCountFilter, Isis::LineShiftFilter, Isis::LineResidualFilter, Isis::LineFilter, Isis::ImageIdFilter, Isis::GoodnessOfFitFilter, Isis::ChooserNameFilter, Isis::APrioriZSigmaFilter, Isis::APrioriZFilter, Isis::APrioriYSigmaFilter, Isis::APrioriYFilter, Isis::APrioriXSigmaFilter, Isis::APrioriXFilter, Isis::APrioriRadiusSigmaFilter, Isis::APrioriRadiusFilter, Isis::APrioriLongitudeSigmaFilter, Isis::APrioriLongitudeFilter, Isis::APrioriLatitudeSigmaFilter, Isis::APrioriLatitudeFilter, Isis::AdjustedZSigmaFilter, Isis::AdjustedZFilter, Isis::AdjustedYSigmaFilter, Isis::AdjustedYFilter, Isis::AdjustedXSigmaFilter, Isis::AdjustedXFilter, Isis::AdjustedRadiusSigmaFilter, Isis::AdjustedRadiusFilter, Isis::AdjustedLongitudeSigmaFilter, Isis::AdjustedLongitudeFilter, Isis::AdjustedLatitudeSigmaFilter, and Isis::AdjustedLatitudeFilter.
References Isis::AbstractFilter::getMinForSuccess().
Referenced by Isis::AdjustedLatitudeFilter::getImageDescription(), Isis::AdjustedLatitudeSigmaFilter::getImageDescription(), Isis::AdjustedLongitudeFilter::getImageDescription(), Isis::AdjustedLongitudeSigmaFilter::getImageDescription(), Isis::AdjustedRadiusFilter::getImageDescription(), Isis::AdjustedRadiusSigmaFilter::getImageDescription(), Isis::AdjustedXFilter::getImageDescription(), Isis::AdjustedXSigmaFilter::getImageDescription(), Isis::AdjustedYFilter::getImageDescription(), Isis::AdjustedYSigmaFilter::getImageDescription(), Isis::AdjustedZFilter::getImageDescription(), Isis::AdjustedZSigmaFilter::getImageDescription(), Isis::APrioriLatitudeFilter::getImageDescription(), Isis::APrioriLatitudeSigmaFilter::getImageDescription(), Isis::APrioriLongitudeFilter::getImageDescription(), Isis::APrioriLongitudeSigmaFilter::getImageDescription(), Isis::APrioriRadiusFilter::getImageDescription(), Isis::APrioriRadiusSigmaFilter::getImageDescription(), Isis::APrioriXFilter::getImageDescription(), Isis::APrioriXSigmaFilter::getImageDescription(), Isis::APrioriYFilter::getImageDescription(), Isis::APrioriYSigmaFilter::getImageDescription(), Isis::APrioriZFilter::getImageDescription(), Isis::APrioriZSigmaFilter::getImageDescription(), Isis::ChooserNameFilter::getImageDescription(), Isis::GoodnessOfFitFilter::getImageDescription(), Isis::LineFilter::getImageDescription(), Isis::LineResidualFilter::getImageDescription(), Isis::LineShiftFilter::getImageDescription(), Isis::MeasureCountFilter::getImageDescription(), Isis::MeasureIgnoredFilter::getImageDescription(), Isis::MeasureJigsawRejectedFilter::getImageDescription(), Isis::MeasureTypeFilter::getImageDescription(), Isis::PointEditLockedFilter::getImageDescription(), Isis::PointIdFilter::getImageDescription(), Isis::PointIgnoredFilter::getImageDescription(), Isis::PointJigsawRejectedFilter::getImageDescription(), Isis::PointTypeFilter::getImageDescription(), Isis::ResidualMagnitudeFilter::getImageDescription(), Isis::SampleFilter::getImageDescription(), Isis::SampleResidualFilter::getImageDescription(), Isis::SampleShiftFilter::getImageDescription(), and Isis::ImageIdFilter::getPointDescription().
getInclusiveExclusiveLayout()
QBoxLayout * Isis::AbstractFilter::getInclusiveExclusiveLayout () const protected inherited
getMainLayout()
QBoxLayout * Isis::AbstractFilter::getMainLayout () const protected inherited
Referenced by createWidget().
getMeasureDescription()
QString Isis::AbstractFilter::getMeasureDescription () const virtual inherited
Reimplemented in Isis::SampleShiftFilter, Isis::SampleResidualFilter, Isis::SampleFilter, Isis::ResidualMagnitudeFilter, Isis::MeasureTypeFilter, Isis::MeasureJigsawRejectedFilter, Isis::MeasureIgnoredFilter, Isis::LineShiftFilter, Isis::LineResidualFilter, Isis::LineFilter, Isis::ImageIdFilter, and Isis::GoodnessOfFitFilter.
getMinForSuccess()
int Isis::AbstractFilter::getMinForSuccess () const inline protected inherited
Referenced by Isis::AbstractFilter::getImageDescription(), Isis::AdjustedLatitudeFilter::getImageDescription(), Isis::AdjustedLatitudeSigmaFilter::getImageDescription(), Isis::AdjustedLongitudeFilter::getImageDescription(), Isis::AdjustedLongitudeSigmaFilter::getImageDescription(), Isis::AdjustedRadiusFilter::getImageDescription(), Isis::AdjustedRadiusSigmaFilter::getImageDescription(), Isis::AdjustedXFilter::getImageDescription(), Isis::AdjustedXSigmaFilter::getImageDescription(), Isis::AdjustedYFilter::getImageDescription(), Isis::AdjustedYSigmaFilter::getImageDescription(), Isis::AdjustedZFilter::getImageDescription(), Isis::AdjustedZSigmaFilter::getImageDescription(), Isis::APrioriLatitudeFilter::getImageDescription(), Isis::APrioriLatitudeSigmaFilter::getImageDescription(), Isis::APrioriLongitudeFilter::getImageDescription(), Isis::APrioriLongitudeSigmaFilter::getImageDescription(), Isis::APrioriRadiusFilter::getImageDescription(), Isis::APrioriRadiusSigmaFilter::getImageDescription(), Isis::APrioriXFilter::getImageDescription(), Isis::APrioriXSigmaFilter::getImageDescription(), Isis::APrioriYFilter::getImageDescription(), Isis::APrioriYSigmaFilter::getImageDescription(), Isis::APrioriZFilter::getImageDescription(), Isis::APrioriZSigmaFilter::getImageDescription(), Isis::ChooserNameFilter::getImageDescription(), Isis::GoodnessOfFitFilter::getImageDescription(), Isis::LineFilter::getImageDescription(), Isis::LineResidualFilter::getImageDescription(), Isis::LineShiftFilter::getImageDescription(), Isis::MeasureCountFilter::getImageDescription(), Isis::MeasureIgnoredFilter::getImageDescription(), Isis::MeasureJigsawRejectedFilter::getImageDescription(), Isis::MeasureTypeFilter::getImageDescription(), Isis::PointEditLockedFilter::getImageDescription(), Isis::PointIdFilter::getImageDescription(), Isis::PointIgnoredFilter::getImageDescription(), Isis::PointJigsawRejectedFilter::getImageDescription(), Isis::PointTypeFilter::getImageDescription(), Isis::ResidualMagnitudeFilter::getImageDescription(), Isis::SampleFilter::getImageDescription(), Isis::SampleResidualFilter::getImageDescription(), Isis::SampleShiftFilter::getImageDescription(), and Isis::ImageIdFilter::getPointDescription().
getPointDescription()
QString Isis::AbstractFilter::getPointDescription () const virtual inherited
Reimplemented in Isis::SampleShiftFilter, Isis::SampleResidualFilter, Isis::SampleFilter, Isis::ResidualMagnitudeFilter, Isis::PointTypeFilter, Isis::PointJigsawRejectedFilter, Isis::PointIgnoredFilter, Isis::PointIdFilter, Isis::PointEditLockedFilter, Isis::MeasureTypeFilter, Isis::MeasureJigsawRejectedFilter, Isis::MeasureIgnoredFilter, Isis::MeasureCountFilter, Isis::LineShiftFilter, Isis::LineResidualFilter, Isis::LineFilter, Isis::ImageIdFilter, Isis::GoodnessOfFitFilter, Isis::ChooserNameFilter, Isis::APrioriZSigmaFilter, Isis::APrioriZFilter, Isis::APrioriYSigmaFilter, Isis::APrioriYFilter, Isis::APrioriXSigmaFilter, Isis::APrioriXFilter, Isis::APrioriRadiusSigmaFilter, Isis::APrioriRadiusFilter, Isis::APrioriLongitudeSigmaFilter, Isis::APrioriLongitudeFilter, Isis::APrioriLatitudeSigmaFilter, Isis::APrioriLatitudeFilter, Isis::AdjustedZSigmaFilter, Isis::AdjustedZFilter, Isis::AdjustedYSigmaFilter, Isis::AdjustedYFilter, Isis::AdjustedXSigmaFilter, Isis::AdjustedXFilter, Isis::AdjustedRadiusSigmaFilter, Isis::AdjustedRadiusFilter, Isis::AdjustedLongitudeSigmaFilter, Isis::AdjustedLongitudeFilter, Isis::AdjustedLatitudeSigmaFilter, and Isis::AdjustedLatitudeFilter.
inclusive()
bool Isis::AbstractFilter::inclusive () const protected inherited
Referenced by Isis::AbstractNumberFilter::descriptionSuffix(), Isis::AbstractStringFilter::descriptionSuffix(), Isis::MeasureTypeFilter::evaluate(), Isis::PointTypeFilter::evaluate(), Isis::AbstractFilter::evaluate(), Isis::AbstractNumberFilter::evaluate(), Isis::AbstractStringFilter::evaluate(), Isis::MeasureCountFilter::getImageDescription(), Isis::MeasureIgnoredFilter::getImageDescription(), Isis::MeasureJigsawRejectedFilter::getImageDescription(), Isis::MeasureTypeFilter::getImageDescription(), Isis::PointEditLockedFilter::getImageDescription(), Isis::PointIgnoredFilter::getImageDescription(), Isis::PointJigsawRejectedFilter::getImageDescription(), Isis::PointTypeFilter::getImageDescription(), Isis::MeasureIgnoredFilter::getMeasureDescription(), Isis::MeasureJigsawRejectedFilter::getMeasureDescription(), Isis::MeasureTypeFilter::getMeasureDescription(), Isis::MeasureCountFilter::getPointDescription(), Isis::PointEditLockedFilter::getPointDescription(), Isis::PointIgnoredFilter::getPointDescription(), Isis::PointJigsawRejectedFilter::getPointDescription(), and Isis::PointTypeFilter::getPointDescription().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/AbstractMultipleChoiceFilter.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/AbstractMultipleChoiceFilter.cpp