Isis Developer Reference: Isis::FramingCamera Class Reference
Isis::FramingCamera Class Reference abstract
Spice, Instruments, and Cameras
Generic class for Framing Cameras.
#include <FramingCamera.h>
Public Types
enum CameraType {
Framing , PushFrame , LineScan , Radar ,
Point , RollingShutter , Csm
}
This enum defines the types of cameras supported in this class.
Public Member Functions
FramingCamera (Cube &cube)
Constructs the FramingCamera object.
~FramingCamera ()
Destroys the FramingCamera Object.
virtual CameraType GetCameraType () const
This method returns Framing camera type.
virtual std::pair< iTime, iTime > ShutterOpenCloseTimes (double time, double exposureDuration)=0
Returns the shutter open and close times.
virtual bool SetImage (const double sample, const double line)
Sets the sample/line values of the image to get the lat/lon values.
virtual bool SetImage (const double sample, const double line, const double deltaT)
Sets the sample/line values of the image to get the lat/lon values with a time offset of deltaT.
virtual bool SetUniversalGround (const double latitude, const double longitude)
Sets the lat/lon values to get the sample/line values.
virtual bool SetUniversalGround (const double latitude, const double longitude, const double radius)
Sets the lat/lon/radius values to get the sample/line values.
bool SetUniversalGround (const double latitude, const double longitude, bool backCheck=true)
This is the opposite routine for SetLookDirection.
bool SetUniversalGround (const double latitude, const double longitude, const double radius, bool backCheck=true)
This overloaded method has the opposite function as SetLookDirection.
virtual bool SetGround (Latitude latitude, Longitude longitude)
Sets the lat/lon values to get the sample/line values.
virtual bool SetGround (const SurfacePoint &surfacePt)
Sets the lat/lon/radius values to get the sample/line values.
bool SetGround (const SurfacePoint &surfacePt, bool backCheck=true)
This overloaded method has the opposite function as SetLookDirection.
virtual bool SetRightAscensionDeclination (const double ra, const double dec)
Sets the right ascension declination.
void LocalPhotometricAngles (Angle &phase, Angle &incidence, Angle &emission, bool &success)
Calculates LOCAL photometric angles using the DEM (not ellipsoid).
void Slope (double &slope, bool &success)
Calculates the slope at the current point by computing the angle between the local surface normal and the ellipsoid surface normal.
void GetLocalNormal (double normal[3])
This method will find the local normal at the current (sample, line) and set it to the passed in array.
bool HasProjection ()
Checks to see if the camera object has a projection.
virtual bool IsBandIndependent ()
Virtual method that checks if the band is independent.
int ReferenceBand () const
Returns the reference band.
bool HasReferenceBand () const
Checks to see if the Camera object has a reference band.
virtual void SetBand (const int band)
Virtual method that sets the band number.
virtual double Sample () const
Returns the current sample number.
virtual int Band () const
Returns the current band.
virtual double Line () const
Returns the current line number.
bool GroundRange (double &minlat, double &maxlat, double &minlon, double &maxlon, Pvl &pvl)
Computes the Ground Range.
bool ringRange (double &minRingRadius, double &maxRingRadius, double &minRingLongitude, double &maxRingLongitude, Pvl &pvl)
Analogous to the above Ground Range method.
bool IntersectsLongitudeDomain (Pvl &pvl)
Checks whether the ground range intersects the longitude domain or not.
virtual double PixelResolution ()
Returns the pixel resolution at the current position in meters/pixel.
virtual double LineResolution ()
Returns the line resolution at the current position in meters.
virtual double SampleResolution ()
Returns the sample resolution at the current position in meters.
virtual double DetectorResolution ()
Returns the detector resolution at the current position in meters.
virtual double ObliqueDetectorResolution (bool useLocal=true)
This method returns the Oblique Detector Resolution if the Look Vector intersects the target and if the emission angle is greater than or equal to 0, and less than 90 degrees.
virtual double ObliqueSampleResolution (bool useLocal=true)
Returns the oblique sample resolution at the current position in m.
virtual double ObliqueLineResolution (bool useLocal=true)
Returns the oblique line resolution at the current position in meters.
virtual double ObliquePixelResolution (bool useLocal=true)
Returns the oblique pixel resolution at the current position in meters/pixel.
virtual double resolution ()
Returns the resolution of the camera.
double LowestImageResolution ()
Returns the lowest/worst resolution in the entire image.
double HighestImageResolution ()
Returns the highest/best resolution in the entire image.
double LowestObliqueImageResolution ()
Returns the lowest/worst oblique resolution in the entire image.
double HighestObliqueImageResolution ()
Returns the highest/best oblique resolution in the entire image.
void BasicMapping (Pvl &map)
Writes the basic mapping group to the specified Pvl.
void basicRingMapping (Pvl &map)
Writes the basic mapping group for ring plane to the specified Pvl.
double FocalLength () const
Returns the focal length.
double PixelPitch () const
Returns the pixel pitch.
virtual double exposureDuration () const
Return the exposure duration for the pixel that the camera is set to.
virtual double exposureDuration (const double sample, const double line, const int band=-1) const
Return the exposure duration for the pixel at the given line, sample and band.
virtual QList< QPointF > PixelIfovOffsets ()
Returns the pixel ifov offsets from center of pixel, which defaults to the (pixel pitch * summing mode) / 2.
int Samples () const
Returns the number of samples in the image.
int Lines () const
Returns the number of lines in the image.
int Bands () const
Returns the number of bands in the image.
int ParentLines () const
Returns the number of lines in the parent alphacube.
int ParentSamples () const
Returns the number of samples in the parent alphacube.
double CelestialNorthClockAngle ()
Computes the celestial north clock angle at the current line/sample or ra/dec.
bool RaDecRange (double &minra, double &maxra, double &mindec, double &maxdec)
Computes the RaDec range.
double RaDecResolution ()
Returns the RaDec resolution.
CameraDistortionMap * DistortionMap ()
Returns a pointer to the CameraDistortionMap object.
CameraFocalPlaneMap * FocalPlaneMap ()
Returns a pointer to the CameraFocalPlaneMap object.
CameraDetectorMap * DetectorMap ()
Returns a pointer to the CameraDetectorMap object.
CameraGroundMap * GroundMap ()
Returns a pointer to the CameraGroundMap object.
CameraSkyMap * SkyMap ()
Returns a pointer to the CameraSkyMap object.
QString instrumentId ()
This method returns the InstrumentId as it appears in the cube.
QString instrumentNameLong () const
This method returns the full instrument name.
QString instrumentNameShort () const
This method returns the shortened instrument name.
QString spacecraftNameLong () const
This method returns the full spacecraft name.
QString spacecraftNameShort () const
This method returns the shortened spacecraft name.
void SetDistortionMap (CameraDistortionMap *map, bool deleteExisting=true)
Sets the Distortion Map.
void SetFocalPlaneMap (CameraFocalPlaneMap *map)
Sets the Focal Plane Map.
void SetDetectorMap (CameraDetectorMap *map)
Sets the Detector Map.
void SetGroundMap (CameraGroundMap *map)
Sets the Ground Map.
void SetSkyMap (CameraSkyMap *map)
Sets the Sky Map.
double NorthAzimuth ()
Returns the North Azimuth.
double SunAzimuth ()
Returns the Sun Azimuth.
double SpacecraftAzimuth ()
Return the Spacecraft Azimuth.
double OffNadirAngle ()
Return the off nadir angle in degrees.
void IgnoreProjection (bool ignore)
Set whether or not the camera should ignore the Projection.
void LoadCache ()
This loads the spice cache big enough for this image.
std::pair< double, double > StartEndEphemerisTimes ()
Calculates the start and end ephemeris times.
int CacheSize (double startTime, double endTime)
This method calculates the spice cache size.
void GetGeometricTilingHint (int &startSize, int &endSize)
This will get the geometric tiling hint; these values are typically used for ProcessRubberSheet::SetTiling(...).
bool InCube ()
This returns true if the current Sample() or Line() value is outside of the cube (meaning the point must have been extrapolated).
virtual int CkFrameId () const =0
Provides the NAIF frame code for an instruments CK kernel.
virtual int CkReferenceId () const =0
Provides the NAIF reference code for an instruments CK kernel.
virtual int SpkReferenceId () const =0
Provides reference frame for instruments SPK NAIF kernel.
virtual int SpkTargetId () const
Provides target code for instruments SPK NAIF kernel.
virtual int SpkCenterId () const
Provides the center of motion body for SPK NAIF kernel.
void setTime (const iTime &time)
By setting the time you essential set the position of the spacecraft and body as indicated in the class Spice.
bool SetLookDirection (const double v[3])
Sets the look direction of the spacecraft.
bool HasSurfaceIntersection () const
Returns if the last call to either SetLookDirection or SetUniversalGround had a valid intersection with the target.
void Coordinate (double p[3]) const
Returns the x,y,z of the surface intersection in BodyFixed km.
virtual double UniversalLatitude () const
Returns the planetocentric latitude, in degrees, at the surface intersection point in the body fixed coordinate system.
Latitude GetLatitude () const
Returns a planetocentric latitude object at the surface intersection point in body fixed.
virtual double UniversalLongitude () const
Returns the positive east, 0-360 domain longitude, in degrees, at the surface intersection point in the body fixed coordinate system.
Longitude GetLongitude () const
Returns a positive east, 0-360 domain longitude object at the surface intersection point in the body fixed coordinate system.
virtual SurfacePoint GetSurfacePoint () const
Returns the surface point (most efficient accessor).
Distance LocalRadius () const
Returns the local radius at the intersection point.
Distance LocalRadius (Latitude lat, Longitude lon)
Returns the local radius at the intersection point.
Distance LocalRadius (double lat, double lon)
Returns the local radius at the intersection point.
virtual double PhaseAngle () const
Returns the phase angle in degrees.
virtual double EmissionAngle () const
Returns the emission angle in degrees.
virtual double IncidenceAngle () const
Returns the incidence angle in degrees.
void LookDirection (double v[3]) const
Returns the look direction in the camera coordinate system.
virtual std::vector< double > lookDirectionJ2000 () const
Returns the look direction in the camera coordinate system.
virtual std::vector< double > lookDirectionBodyFixed () const
Returns the look direction in the body fixed coordinate system.
virtual double RightAscension ()
Returns the right ascension angle (sky longitude).
virtual double Declination ()
Returns the declination angle (sky latitude).
void SpacecraftSurfaceVector (double scSurfaceVector[3]) const
Sets the vector between the spacecraft and surface point in body-fixed.
virtual double SlantDistance () const
Return the distance between the spacecraft and surface point in kmv.
double LocalSolarTime ()
Return the local solar time in hours.
virtual double SolarDistance () const
Returns the distance between the sun and surface point in AU.
double SpacecraftAltitude ()
Returns the distance from the spacecraft to the subspacecraft point in km.
void IgnoreElevationModel (bool ignore)
This allows you to ignore the cube elevation model and use the ellipse.
void instrumentPosition (double p[3]) const
Returns the spacecraft position in body-fixed frame km units.
virtual SpicePosition * instrumentPosition () const
Accessor method for the instrument position.
virtual void instrumentBodyFixedPosition (double p[3]) const
Returns the spacecraft position in body-fixed frame km units.
virtual void sunPosition (double p[3]) const
Fills the input vector with sun position information, in either body-fixed or J2000 reference frame and km units.
virtual SpicePosition * sunPosition () const
Accessor method for the sun position.
virtual double targetCenterDistance () const
Calculates and returns the distance from the spacecraft to the target center.
virtual double sunToBodyDist () const
virtual Longitude solarLongitude ()
Returns the solar longitude.
virtual void instrumentBodyFixedVelocity (double v[3]) const
Returns the spacecraft velocity in body-fixed frame km/sec units.
virtual iTime time () const
Returns the ephemeris time in seconds which was used to obtain the spacecraft and sun positions.
void radii (Distance r[3]) const
Returns the radii of the body in km.
virtual void createCache (iTime startTime, iTime endTime, const int size, double tol)
This method creates an internal cache of spacecraft and sun positions over a specified time range.
virtual iTime cacheStartTime () const
Accessor method for the cache start time.
virtual iTime cacheEndTime () const
Accessor method for the cache end time.
virtual void subSpacecraftPoint (double &lat, double &lon)
Returns the sub-spacecraft latitude/longitude in universal coordinates (0-360 positive east, ocentric)
virtual void subSolarPoint (double &lat, double &lon)
Returns the sub-solar latitude/longitude in universal coordinates (0-360 positive east, ocentric)
virtual Target * target () const
Returns a pointer to the target object.
QString targetName () const
Returns the QString name of the target.
virtual iTime getClockTime (QString clockValue, int sclkCode=-1, bool clockTicks=false)
This converts the spacecraft clock ticks value (clockValue) to an iTime.
SpiceDouble getDouble (const QString &key, int index=0)
This returns a value from the NAIF text pool.
SpiceInt getInteger (const QString &key, int index=0)
This returns a value from the NAIF text pool.
QString getString (const QString &key, int index=0)
This returns a value from the NAIF text pool.
virtual SpiceRotation * bodyRotation () const
Accessor method for the body rotation.
virtual SpiceRotation * instrumentRotation () const
Accessor method for the instrument rotation.
bool isUsingAle ()
bool hasKernels (Pvl &lab)
Returns true if the kernel group has kernel files.
bool isTimeSet ()
Returns true if time has been initialized.
SpiceInt naifBodyCode () const
This returns the NAIF body code of the target indicated in the labels.
SpiceInt naifSpkCode () const
This returns the NAIF SPK code to use when reading from SPK kernels.
SpiceInt naifCkCode () const
This returns the NAIF CK code to use when reading from CK kernels.
SpiceInt naifIkCode () const
This returns the NAIF IK code to use when reading from instrument kernels.
SpiceInt naifSclkCode () const
This returns the NAIF SCLK code to use when reading from instrument kernels.
SpiceInt naifBodyFrameCode () const
This returns the NAIF body frame code.
PvlObject getStoredNaifKeywords () const
This returns the PvlObject that stores all of the requested Naif data and can be a replacement for furnishing text kernels.
Static Public Member Functions
static double GroundAzimuth (double glat, double glon, double slat, double slon)
Computes and returns the ground azimuth between the ground point and another point of interest, such as the subspacecraft point or the subsolar point.
Protected Types
enum SpiceValueType { SpiceDoubleType , SpiceStringType , SpiceIntType , SpiceByteCodeType }
NAIF value primitive type.
Protected Member Functions
void SetFocalLength (double v)
Sets the focal length.
void SetFocalLength ()
Reads the focal length from the instrument kernel.
void SetPixelPitch (double v)
Sets the pixel pitch.
void SetPixelPitch ()
Reads the Pixel Pitch from the instrument kernel.
void SetGeometricTilingHint (int startSize=128, int endSize=8)
This method sets the best geometric tiling size for projecting from this camera model.
QVariant readValue (QString key, SpiceValueType type, int index=0)
This should be used for reading ALL text naif kernel values.
void storeResult (QString name, SpiceValueType type, QVariant value)
QVariant getStoredResult (QString name, SpiceValueType type)
void storeValue (QString key, int index, SpiceValueType type, QVariant value)
QVariant readStoredValue (QString key, SpiceValueType type, int index)
virtual void computeSolarLongitude (iTime et)
Computes the solar longitude for the given ephemeris time.
Protected Attributes
QString m_instrumentId
The InstrumentId as it appears on the cube.
QString m_instrumentNameLong
Full instrument name.
QString m_instrumentNameShort
Shortened instrument name.
QString m_spacecraftNameLong
Full spacecraft name.
QString m_spacecraftNameShort
Shortened spacecraft name.
double p_childSample
Sample value for child.
double p_childLine
Line value for child.
AlphaCube * p_alphaCube
A pointer to the AlphaCube.
bool p_pointComputed
Flag showing if Sample/Line has been computed.
SpiceDouble m_lookB [3]
Look direction in body fixed.
bool m_newLookB
flag to indicate we need to recompute ra/dec
SpiceDouble m_uB [3]
This contains the sun position (u) in the bodyfixed reference frame (B).
SpiceDouble m_BJ [3][3]
This contains the transformation matrix from J2000 (J) to Body fixed (B).
Target * m_target
Target of the observation.
iTime * m_et
Ephemeris time (read NAIF documentation for a detailed description)
Longitude * m_solarLongitude
Body rotation solar longitude value.
Detailed Description
Generic class for Framing Cameras.
This class is used to abstract out framing camera functionality from children classes. The ShutterOpenCloseTimes() method is pure virtual and must be overridden by all framing camera models that extend this class.
Author
2009-08-26 Steven Lambright
Member Enumeration Documentation
CameraType
enum Isis::Camera::CameraType inherited
This enum defines the types of cameras supported in this class.
Enumerator
Framing
Framing Camera.
PushFrame
Push Frame Camera.
LineScan
Line Scan Camera.
Radar
Radar Camera.
Point
Point Camera.
RollingShutter
RollingShutter.
Csm
Community Sensor Model Camera.
SpiceValueType
enum Isis::Spice::SpiceValueType protected inherited
NAIF value primitive type.
Enumerator
SpiceDoubleType
SpiceDouble type.
SpiceStringType
SpiceString type.
SpiceIntType
SpiceInt type.
SpiceByteCodeType
SpiceByteCode type.
Constructor & Destructor Documentation
FramingCamera()
Isis::FramingCamera::FramingCamera (Cube & cube)
Constructs the FramingCamera object.
Parameters
lab Pvl label used to create the parent Camera object
~FramingCamera()
Isis::FramingCamera::~FramingCamera () inline
Destroys the FramingCamera Object.
Member Function Documentation
Band()
int Isis::Camera::Band () const virtual inherited
Returns the current band.
Returns
int Band
Referenced by Isis::Camera::RaDecRange(), and Isis::Camera::RaDecResolution().
Bands()
int Isis::Camera::Bands () const inherited
Returns the number of bands in the image.
Returns
int Number of Bands
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::LroWideAngleCamera::SetBand(), Isis::MarciCamera::SetBand(), and Isis::Camera::StartEndEphemerisTimes().
BasicMapping()
void Isis::Camera::BasicMapping (Pvl & pvl) inherited
Writes the basic mapping group to the specified Pvl.
Parameters
pvl Pvl to write mapping group to
References Isis::PvlObject::addGroup(), Isis::Target::radii(), Isis::Spice::radii(), Isis::Spice::target(), and Isis::toString().
Referenced by Isis::ImagePolygon::Create().
basicRingMapping()
void Isis::Camera::basicRingMapping (Pvl & pvl) inherited
Writes the basic mapping group for ring plane to the specified Pvl.
Parameters
pvl Pvl to write mapping group to
References _FILEINFO_, Isis::PvlObject::addGroup(), Isis::Spice::target(), Isis::toString(), and Isis::IException::User.
bodyRotation()
SpiceRotation * Isis::Spice::bodyRotation () const virtual inherited
Accessor method for the body rotation.
Returns
iTime Body rotation for the image.
Author
Steven Lambright
Reimplemented in Isis::CSMCamera.
Referenced by Isis::Cube::attachSpiceFromIsd(), Isis::Sensor::EmissionAngle(), Isis::RadarGroundMap::GetdXYdPosition(), Isis::RadarGroundMap::GetXY(), Isis::Sensor::lookDirectionJ2000(), Isis::MiniRF::MiniRF(), Isis::RadarGroundMap::SetFocalPlane(), Isis::RadarGroundMap::SetGround(), Isis::Sensor::SetGround(), Isis::Sensor::SetLookDirection(), and Isis::Sensor::SetUniversalGround().
cacheEndTime()
iTime Isis::Spice::cacheEndTime () const virtual inherited
Accessor method for the cache end time.
Returns
iTime End time for the image.
Author
Steven Lambright
CacheSize()
int Isis::Camera::CacheSize (double startTime, double endTime) inherited
This method calculates the spice cache size.
This method finds the number of lines in the beta cube and adds 1, since we need at least 2 points for interpolation. This method must be called before a call to the Spice::createCache() method. It is called in the LoadCache() method.
Parameters
startTime Starting ephemeris time to cache
endTime Ending ephemeris time to cache
Returns
int The calculated spice cache size
Exceptions
iException::Programmer - "A cache has already been created."
See also
createCache()
LoadCache()
Author
2011-02-02 Jeannie Walldren
References Isis::AlphaCube::BetaLines(), and Isis::Camera::p_alphaCube.
Referenced by Isis::Camera::LoadCache().
cacheStartTime()
iTime Isis::Spice::cacheStartTime () const virtual inherited
Accessor method for the cache start time.
Returns
iTime Start time for the image.
Author
Steven Lambright
CelestialNorthClockAngle()
double Isis::Camera::CelestialNorthClockAngle () inherited
Computes the celestial north clock angle at the current line/sample or ra/dec.
The reference vector is a vecor from the current pixel pointed directly "upward". Celetial North is a vector from the current pixel poiting towards celetial north. The Celestial North Clock Angle is the angle between these two vectors on the image.
Returns
double The resultant Celestial North Clock Angle
References Isis::Sensor::Declination(), Isis::Camera::Line(), Isis::PI, Isis::Camera::RaDecResolution(), Isis::Sensor::RightAscension(), Isis::Camera::Sample(), Isis::Camera::SetImage(), and Isis::Camera::SetRightAscensionDeclination().
CkFrameId()
virtual int Isis::Camera::CkFrameId () const pure virtual inherited
Provides the NAIF frame code for an instruments CK kernel.
This pure virtual method must be implemented in each camera model providing the reference frame NAIF ID code found in the mission CK kernel.
This value can be easily determined by using the NAIF spacit application that sumarizes binary CK kernels a particular instrument on a spacecraft. spacit will additionally require a spacecraft clock kernel (SCLK) and a leap seconds kernel (LSK). For example, the output of the MESSENGER camera CK supporting the MDIS camera below indicates it is the MESSENGER spacecraft.
Segment ID     : MSGR_SPACECRAFT
Instrument Code: -236000
Spacecraft     : Body -236, MESSENGER
Reference Frame: Frame 1, J2000
CK Data Type   : Type 3
Description : Continuous Pointing: Linear Interpolation
Available Data : Pointing and Angular Velocity
UTC Start Time : 2004 AUG 12 17:17:42.558
UTC Stop Time  : 2010 JUL 23 12:35:22.814
SCLK Start Time: 1/000818300:000000
SCLK Stop Time : 1/188375996:000000
The CkFrameId value is found in the "Instrument Code" entry (-236000).
Returns
int NAIF code for CK frame for an instrument
Implemented in Isis::VoyagerCamera, Isis::VikingCamera, Isis::TgoCassisCamera, Isis::RosettaVirtisCamera, Isis::RosettaOsirisCamera, Isis::OsirisRexTagcamsCamera, Isis::OsirisRexOcamsCamera, Isis::ThemisVisCamera, Isis::ThemisIrCamera, Isis::NewHorizonsMvicTdiCamera, Isis::NewHorizonsMvicFrameCamera, Isis::NewHorizonsLorriCamera, Isis::NewHorizonsLeisaCamera, Isis::MsiCamera, Isis::MarciCamera, Isis::HiriseCamera, Isis::CTXCamera, Isis::CrismCamera, Isis::MocWideAngleCamera, Isis::MocNarrowAngleCamera, Isis::MexHrscSrcCamera, Isis::HrscCamera, Isis::MdisCamera, Isis::Mariner10Camera, Isis::MiniRF, Isis::LroWideAngleCamera, Isis::LroNarrowAngleCamera, Isis::LoMediumCamera, Isis::LoHighCamera, Isis::KaguyaTcCamera, Isis::KaguyaMiCamera, Isis::JunoCamera, Isis::Hyb2OncCamera, Isis::HayabusaNirsCamera, Isis::HayabusaAmicaCamera, Isis::SsiCamera, Isis::DawnVirCamera, Isis::DawnFcCamera, Isis::ClipperWacFcCamera, Isis::ClipperPushBroomCamera, Isis::ClipperNacRollingShutterCamera, Isis::UvvisCamera, Isis::NirCamera, Isis::LwirCamera, Isis::HiresCamera, Isis::Chandrayaan1M3Camera, Isis::VimsCamera, Isis::IssWACamera, Isis::IssNACamera, Isis::IdealCamera, Isis::CSMCamera, Isis::ApolloPanoramicCamera, and Isis::ApolloMetricCamera.
CkReferenceId()
virtual int Isis::Camera::CkReferenceId () const pure virtual inherited
Provides the NAIF reference code for an instruments CK kernel.
This virtual method must be implemented in each camera model providing the reference frame NAIF ID code found in the mission CK kernel.
This value can be easily determined by using the NAIF spacit application that sumarizes binary CK kernels a particular instrument on a spacecraft. spacit will additionally require a spacecraft clock kernel (SCLK) and a leap seconds kernel (LSK).For example, the output of the MESSENGER camera CK supporting the MDIS camera below indicates it is the MESSENGER spacecraft.
Segment ID     : MSGR_SPACECRAFT
Instrument Code: -236000
Spacecraft     : Body -236, MESSENGER
Reference Frame: Frame 1, J2000
CK Data Type   : Type 3
Description : Continuous Pointing: Linear Interpolation
Available Data : Pointing and Angular Velocity
UTC Start Time : 2004 AUG 12 17:17:42.558
UTC Stop Time  : 2010 JUL 23 12:35:22.814
SCLK Start Time: 1/000818300:000000
SCLK Stop Time : 1/188375996:000000
The CkReferenced value is found in the "Reference Frame" entry (1).
Returns
int NAIF code for CK reference for an instrument
Implemented in Isis::VoyagerCamera, Isis::VikingCamera, Isis::TgoCassisCamera, Isis::RosettaVirtisCamera, Isis::RosettaOsirisCamera, Isis::OsirisRexTagcamsCamera, Isis::OsirisRexOcamsCamera, Isis::ThemisVisCamera, Isis::ThemisIrCamera, Isis::NewHorizonsMvicTdiCamera, Isis::NewHorizonsMvicFrameCamera, Isis::NewHorizonsLorriCamera, Isis::NewHorizonsLeisaCamera, Isis::MsiCamera, Isis::MarciCamera, Isis::HiriseCamera, Isis::CTXCamera, Isis::CrismCamera, Isis::MocWideAngleCamera, Isis::MocNarrowAngleCamera, Isis::MexHrscSrcCamera, Isis::HrscCamera, Isis::MdisCamera, Isis::Mariner10Camera, Isis::MiniRF, Isis::LroWideAngleCamera, Isis::LroNarrowAngleCamera, Isis::LoMediumCamera, Isis::LoHighCamera, Isis::KaguyaTcCamera, Isis::KaguyaMiCamera, Isis::JunoCamera, Isis::Hyb2OncCamera, Isis::HayabusaNirsCamera, Isis::HayabusaAmicaCamera, Isis::SsiCamera, Isis::DawnVirCamera, Isis::DawnFcCamera, Isis::ClipperWacFcCamera, Isis::ClipperPushBroomCamera, Isis::ClipperNacRollingShutterCamera, Isis::UvvisCamera, Isis::NirCamera, Isis::LwirCamera, Isis::HiresCamera, Isis::Chandrayaan1M3Camera, Isis::VimsCamera, Isis::IssWACamera, Isis::IssNACamera, Isis::IdealCamera, Isis::CSMCamera, Isis::ApolloPanoramicCamera, and Isis::ApolloMetricCamera.
computeSolarLongitude()
void Isis::Spice::computeSolarLongitude (iTime et) protected virtual inherited
Computes the solar longitude for the given ephemeris time.
If the target is sky, the longitude is set to -999.0.
Parameters
et Ephemeris time
Reimplemented in Isis::CSMCamera.
References Isis::iTime::Et(), and Isis::Longitude::force360Domain().
Coordinate()
void Isis::Sensor::Coordinate (double p[3]) const inherited
Returns the x,y,z of the surface intersection in BodyFixed km.
Parameters
p[] The coordinate of the surface intersection.
References Isis::SurfacePoint::GetX(), Isis::SurfacePoint::GetY(), Isis::SurfacePoint::GetZ(), Isis::Displacement::kilometers(), Isis::Target::shape(), Isis::ShapeModel::surfaceIntersection(), and Isis::Spice::target().
Referenced by Isis::ControlPoint::ComputeApriori(), Isis::Camera::DetectorResolution(), Isis::Sensor::EmissionAngle(), Isis::VimsGroundMap::Init(), Isis::Camera::OffNadirAngle(), Isis::Sensor::PhaseAngle(), Isis::Sensor::SetGround(), Isis::Sensor::SetLookDirection(), and Isis::Sensor::SetUniversalGround().
createCache()
void Isis::Spice::createCache (iTime startTime, iTime endTime, const int size, double tol) virtual inherited
This method creates an internal cache of spacecraft and sun positions over a specified time range.
The SPICE kernels are then immediately unloaded. This allows multiple instances of the Spice object to be created as the NAIF toolkit can clash if multiple sets of SPICE kernels are loaded. Note that the cache size is specified as an argument. Therefore, times requested via setTime() which are not directly loaded in the cache will be interpolated. If the instrument position is not cached and cacheSize is greater than 3, the tolerance is passed to the SpicePosition Memcache2HermiteCache() method.
Note: Before this method is called, the private variables m_cacheSize, m_startTime and m_endTime must be set. This is done in the Camera classes using the methods SetCacheSize() and SetStartEndEphemerisTime().
Parameters
startTime Starting ephemeris time to cache
endTime Ending ephemeris time to cache
size Size of the cache.
tol Tolerance.
Exceptions
Isis::IException::Programmer - "Argument cacheSize must be greater than zero"
Isis::IException::Programmer - "Argument startTime must be less than or equal to endTime"
Isis::IException::User - "This instrument does not support time padding"
References _FILEINFO_, Isis::iTime::Et(), and Isis::FileName::expanded().
Referenced by Isis::CrismCamera::CrismCamera(), Isis::Camera::LoadCache(), and Isis::MiniRF::MiniRF().
Declination()
double Isis::Sensor::Declination () virtual inherited
Returns the declination angle (sky latitude).
Returns
double Declination angle, in degrees.
Reimplemented in Isis::CSMCamera.
References Isis::Sensor::m_newLookB.
Referenced by Isis::Camera::CelestialNorthClockAngle(), Isis::VimsSkyMap::Init(), Isis::FindTool::mouseButtonRelease(), Isis::Camera::RaDecRange(), and Isis::Camera::RaDecResolution().
DetectorMap()
CameraDetectorMap * Isis::Camera::DetectorMap () inherited
Returns a pointer to the CameraDetectorMap object.
Returns
CameraDetectorMap*
Referenced by Isis::LineScanCamera::DetectorMap(), Isis::PushFrameCamera::DetectorMap(), Isis::RollingShutterCamera::DetectorMap(), Isis::LineScanCameraGroundMap::FindFocalPlane(), Isis::LineScanCameraGroundMap::FindSpacecraftDistance(), Isis::Camera::PixelIfovOffsets(), Isis::PushFrameCameraGroundMap::SetGround(), and Isis::LineScanCameraSkyMap::SetSky().
DetectorResolution()
double Isis::Camera::DetectorResolution () virtual inherited
Returns the detector resolution at the current position in meters.
Returns
double The detector resolution
Reimplemented in Isis::CSMCamera.
References Isis::Sensor::Coordinate(), Isis::Sensor::HasSurfaceIntersection(), Isis::Spice::instrumentPosition(), and Isis::Null.
Referenced by Isis::Camera::LineResolution(), Isis::Camera::ObliqueDetectorResolution(), and Isis::Camera::SampleResolution().
DistortionMap()
CameraDistortionMap * Isis::Camera::DistortionMap () inherited
Returns a pointer to the CameraDistortionMap object.
Returns
CameraDistortionMap*
Referenced by Isis::ControlPoint::ComputeApriori(), Isis::ControlPoint::ComputeResiduals(), Isis::LidarControlPoint::ComputeResiduals(), Isis::LroWideAngleCamera::SetBand(), Isis::MarciCamera::SetBand(), Isis::ThemisIrCamera::SetBand(), and Isis::LineScanCameraSkyMap::SetSky().
EmissionAngle()
double Isis::Sensor::EmissionAngle () const virtual inherited
Returns the emission angle in degrees.
Returns
double Emission angle, in degrees.
Reimplemented in Isis::CSMCamera.
References Isis::Spice::bodyRotation(), Isis::Sensor::Coordinate(), Isis::ShapeModel::emissionAngle(), Isis::Spice::instrumentPosition(), Isis::Target::shape(), and Isis::Spice::target().
Referenced by Isis::CameraStatistics::addStats(), Isis::InterestOperator::InterestByMeasure(), Isis::Camera::ObliqueDetectorResolution(), Isis::Camera::OffNadirAngle(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
exposureDuration() [1/2]
double Isis::Camera::exposureDuration () const virtual inherited
Return the exposure duration for the pixel that the camera is set to.
Returns
double The exposure duration in seconds for the pixel that the camera is set to.
References Isis::CameraDetectorMap::exposureDuration(), Isis::Camera::p_childLine, and Isis::Camera::p_childSample.
Referenced by Isis::DawnFcCamera::DawnFcCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IdealCamera::IdealCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::PixelFOV::latLonVertices(), Isis::LwirCamera::LwirCamera(), Isis::MdisCamera::MdisCamera(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NirCamera::NirCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::ApolloMetricCamera::ShutterOpenCloseTimes(), Isis::IssNACamera::ShutterOpenCloseTimes(), Isis::IssWACamera::ShutterOpenCloseTimes(), Isis::HiresCamera::ShutterOpenCloseTimes(), Isis::LwirCamera::ShutterOpenCloseTimes(), Isis::NirCamera::ShutterOpenCloseTimes(), Isis::UvvisCamera::ShutterOpenCloseTimes(), Isis::ClipperWacFcCamera::ShutterOpenCloseTimes(), Isis::DawnFcCamera::ShutterOpenCloseTimes(), Isis::SsiCamera::ShutterOpenCloseTimes(), Isis::HayabusaAmicaCamera::ShutterOpenCloseTimes(), Isis::HayabusaNirsCamera::ShutterOpenCloseTimes(), Isis::Hyb2OncCamera::ShutterOpenCloseTimes(), Isis::JunoCamera::ShutterOpenCloseTimes(), Isis::LoHighCamera::ShutterOpenCloseTimes(), Isis::LoMediumCamera::ShutterOpenCloseTimes(), Isis::Mariner10Camera::ShutterOpenCloseTimes(), Isis::MdisCamera::ShutterOpenCloseTimes(), Isis::MexHrscSrcCamera::ShutterOpenCloseTimes(), Isis::MsiCamera::ShutterOpenCloseTimes(), Isis::NewHorizonsLorriCamera::ShutterOpenCloseTimes(), Isis::NewHorizonsMvicFrameCamera::ShutterOpenCloseTimes(), Isis::OsirisRexOcamsCamera::ShutterOpenCloseTimes(), Isis::OsirisRexTagcamsCamera::ShutterOpenCloseTimes(), Isis::RosettaOsirisCamera::ShutterOpenCloseTimes(), Isis::TgoCassisCamera::ShutterOpenCloseTimes(), Isis::VikingCamera::ShutterOpenCloseTimes(), Isis::VoyagerCamera::ShutterOpenCloseTimes(), ShutterOpenCloseTimes(), Isis::SsiCamera::SsiCamera(), Isis::UvvisCamera::UvvisCamera(), Isis::VikingCamera::VikingCamera(), and Isis::VoyagerCamera::VoyagerCamera().
exposureDuration() [2/2]
double Isis::Camera::exposureDuration (const double sample, const double line, const int band = -1) const virtual inherited
Return the exposure duration for the pixel at the given line, sample and band.
Parameters
sample The sample of the desired pixel.
line The line of the desired pixel.
band The band of the desired pixel. Defaults to 1.
Returns
double The exposure duration for the desired pixel in seconds.
References Isis::CameraDetectorMap::exposureDuration().
FocalLength()
double Isis::Camera::FocalLength () const inherited
Returns the focal length.
Returns
double Focal Length
Referenced by Isis::CrismCamera::CrismCamera(), Isis::OsirisRexTagcamsDistortionMap::distortion_to_pointing_frame(), Isis::LineScanCameraGroundMap::FindFocalPlane(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::Camera::LoadCache(), Isis::MiniRF::MiniRF(), Isis::OsirisRexTagcamsDistortionMap::pointing_to_distortion_frame(), Isis::MocWideAngleDistortionMap::SetFocalPlane(), Isis::CameraSkyMap::SetSky(), Isis::CSMSkyMap::SetSky(), Isis::LineScanCameraSkyMap::SetSky(), Isis::MocWideAngleDistortionMap::SetUndistortedFocalPlane(), and Isis::CameraDistortionMap::UndistortedFocalPlaneZ().
FocalPlaneMap()
CameraFocalPlaneMap * Isis::Camera::FocalPlaneMap () inherited
Returns a pointer to the CameraFocalPlaneMap object.
Returns
CameraFocalPlaneMap*
Referenced by Isis::ControlPoint::ComputeResiduals(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HrscCamera::HrscCamera(), Isis::MarciCamera::MarciCamera(), Isis::OsirisRexDistortionMap::OsirisRexDistortionMap(), Isis::OsirisRexOcamsDistortionMap::OsirisRexOcamsDistortionMap(), Isis::OsirisRexTagcamsDistortionMap::OsirisRexTagcamsDistortionMap(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::LroWideAngleCamera::SetBand(), Isis::ThemisIrCamera::SetBand(), Isis::NewHorizonsLeisaCamera::SetBand(), Isis::LoMediumDistortionMap::SetDistortion(), Isis::ReseauDistortionMap::SetFocalPlane(), Isis::LoMediumDistortionMap::SetFocalPlane(), Isis::OsirisRexOcamsDistortionMap::SetFocalPlane(), Isis::LineScanCameraDetectorMap::SetParent(), Isis::VariableLineScanCameraDetectorMap::SetParent(), Isis::LineScanCameraSkyMap::SetSky(), Isis::ReseauDistortionMap::SetUndistortedFocalPlane(), Isis::LoMediumDistortionMap::SetUndistortedFocalPlane(), and Isis::OsirisRexOcamsDistortionMap::SetUndistortedFocalPlane().
GetCameraType()
virtual CameraType Isis::FramingCamera::GetCameraType () const inline virtual
This method returns Framing camera type.
Returns
CameraType Type of camera, Framing.
Implements Isis::Camera.
References Isis::Camera::Framing.
getClockTime()
iTime Isis::Spice::getClockTime (QString clockValue, int sclkCode = -1, bool clockTicks = false) virtual inherited
This converts the spacecraft clock ticks value (clockValue) to an iTime.
If the clock ticks value is provided directly, rather than the spacecraft clock string, set clockTicks=true.
Use this when possible because naif calls (such as scs2e_c) cannot be called when not using naif.
References Isis::toString().
Referenced by Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::VimsGroundMap::Init(), Isis::VimsSkyMap::Init(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::MarciCamera::MarciCamera(), Isis::MdisCamera::MdisCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::ThemisVisCamera::ThemisVisCamera(), and Isis::VikingCamera::VikingCamera().
getDouble()
SpiceDouble Isis::Spice::getDouble (const QString & key, int index = 0) inherited
This returns a value from the NAIF text pool.
It is a static convience method
Parameters
key Name of NAIF keyword to obtain from the pool
index If the keyword is an array, the element to obtain. Defaults to 0
Returns
SpiceDouble Spice double from NAIF text pool
Exceptions
Isis::iException::Io - "Can not find key in instrument kernels."
Referenced by Isis::LroWideAngleCameraDistortionMap::addFilter(), Isis::LroWideAngleCameraFocalPlaneMap::addFilter(), Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::RosettaOsirisCamera::initDistortion(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::KaguyaTcCameraDistortionMap::KaguyaTcCameraDistortionMap(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::LwirCamera::LwirCamera(), Isis::MarciCamera::MarciCamera(), Isis::MarciDistortionMap::MarciDistortionMap(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::NirCamera::NirCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::OsirisRexTagcamsDistortionMap::OsirisRexTagcamsDistortionMap(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::KaguyaMiCameraDistortionMap::SetDistortion(), Isis::LroNarrowAngleDistortionMap::SetDistortion(), Isis::TaylorCameraDistortionMap::SetDistortion(), Isis::OsirisRexOcamsDistortionMap::SetDistortion(), Isis::Camera::SetFocalLength(), Isis::Camera::SetPixelPitch(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::TgoCassisDistortionMap::TgoCassisDistortionMap(), and Isis::UvvisCamera::UvvisCamera().
GetGeometricTilingHint()
void Isis::Camera::GetGeometricTilingHint (int & startSize, int & endSize) inherited
This will get the geometric tiling hint; these values are typically used for ProcessRubberSheet::SetTiling(...).
Parameters
startSize Tiling start size
endSize Tiling end size
getInteger()
SpiceInt Isis::Spice::getInteger (const QString & key, int index = 0) inherited
This returns a value from the NAIF text pool.
It is a static convience
Parameters
key Name of NAIF keyword to obtain from the pool
index If the keyword is an array, the element to obtain. Defaults to 0
Returns
SpiceInt Spice integer from NAIF text pool
Exceptions
Isis::iException::Io - "Can not find key in instrument kernels
Referenced by Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), and Isis::LroWideAngleCamera::LroWideAngleCamera().
GetLatitude()
Latitude Isis::Sensor::GetLatitude () const inherited
Returns a planetocentric latitude object at the surface intersection point in body fixed.
Returns
Latidude Universal latitude object.
References Isis::SurfacePoint::GetLatitude(), Isis::Target::shape(), Isis::ShapeModel::surfaceIntersection(), and Isis::Spice::target().
Referenced by Isis::Sensor::UniversalLatitude().
GetLocalNormal()
void Isis::Camera::GetLocalNormal (double normal[3]) inherited
This method will find the local normal at the current (sample, line) and set it to the passed in array.
Parameters
[out] normal The local normal vector to be calculated.
References Isis::ShapeModel::calculateLocalNormal(), Isis::SurfacePoint::GetLatitude(), Isis::SurfacePoint::GetLongitude(), Isis::Sensor::GetSurfacePoint(), Isis::ShapeModel::hasIntersection(), Isis::ShapeModel::hasLocalNormal(), Isis::ShapeModel::isDEM(), Isis::Distance::kilometers(), Isis::Camera::Line(), Isis::ShapeModel::localNormal(), Isis::Sensor::LocalRadius(), Isis::Camera::p_pointComputed, Isis::Angle::radians(), Isis::Camera::Sample(), Isis::Camera::SetImage(), Isis::Target::shape(), and Isis::Spice::target().
Referenced by Isis::Camera::LocalPhotometricAngles(), and Isis::Camera::Slope().
GetLongitude()
Longitude Isis::Sensor::GetLongitude () const inherited
Returns a positive east, 0-360 domain longitude object at the surface intersection point in the body fixed coordinate system.
Returns
Longitude Universal longitude object.
References Isis::SurfacePoint::GetLongitude(), Isis::Target::shape(), Isis::ShapeModel::surfaceIntersection(), and Isis::Spice::target().
Referenced by Isis::Sensor::UniversalLongitude().
getStoredNaifKeywords()
PvlObject Isis::Spice::getStoredNaifKeywords () const inherited
This returns the PvlObject that stores all of the requested Naif data and can be a replacement for furnishing text kernels.
Referenced by Isis::Cube::attachSpiceFromIsd().
getStoredResult()
QVariant Isis::Spice::getStoredResult (QString name, SpiceValueType type) protected inherited
References Isis::EndianSwapper::Double().
getString()
QString Isis::Spice::getString (const QString & key, int index = 0) inherited
This returns a value from the NAIF text pool.
It is a static convience method
Parameters
key Name of NAIF keyword to obtain from the pool
index If the keyword is an array, the element to obtain. Defaults to 0
Returns
QString Value from the NAIF text pool
Exceptions
Isis::IException::Io - "Can not find key in instrument kernels."
Referenced by Isis::LightTimeCorrectionState::checkAberrationCorrection(), Isis::LightTimeCorrectionState::checkLightTimeToSurfaceCorrect(), Isis::LightTimeCorrectionState::checkObserverTargetSwap(), Isis::MdisCamera::MdisCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::OsirisRexTagcamsDistortionMap::OsirisRexTagcamsDistortionMap(), and Isis::OsirisRexOcamsDistortionMap::SetDistortion().
GetSurfacePoint()
SurfacePoint Isis::Sensor::GetSurfacePoint () const virtual inherited
Returns the surface point (most efficient accessor).
Returns
SurfacePoint Coordinate for the surface intersection.
References Isis::Target::shape(), Isis::ShapeModel::surfaceIntersection(), and Isis::Spice::target().
Referenced by Isis::ControlPoint::ComputeResiduals(), Isis::QnetPointDistanceFilter::filter(), Isis::Camera::GetLocalNormal(), Isis::CSMCamera::GroundPartials(), Isis::CSMCamera::IncidenceAngle(), Isis::Camera::LocalPhotometricAngles(), Isis::CSMCamera::PhaseAngle(), and Isis::CSMCamera::SlantDistance().
GroundAzimuth()
double Isis::Camera::GroundAzimuth (double glat, double glon, double slat, double slon) static inherited
Computes and returns the ground azimuth between the ground point and another point of interest, such as the subspacecraft point or the subsolar point.
The ground azimuth is the clockwise angle on the ground between a line drawn from the ground point to the North pole of the body and a line drawn from the selected point on the surface to some point of interest on the surface (such as the subsolar point or the subspacecraft point).
Note: This is different from the image azimuth algorithm used in ComputeAzimuth(). For ground azimuths, the initial ray of the angle is the vector from the selected ground point to the north pole. For image azimuths, the initial ray is the vector from the selected image location to the right, horizontally.
Parameters
glat The latitude of the ground point
glon The longitude of the ground point
slat The latitude of the subspacecraft or subsolar point
slon The longitude of the subspacecraft or subsolar point
Returns
double The azimuth in degrees
References Isis::PI.
GroundMap()
CameraGroundMap * Isis::Camera::GroundMap () inherited
Returns a pointer to the CameraGroundMap object.
Returns
CameraCGroundMap*
Referenced by Isis::IsisBundleObservation::computeImagePartials(), Isis::IsisBundleObservation::computePoint3DPartials(), Isis::ControlPoint::ComputeResiduals(), Isis::ControlPoint::ComputeResiduals_Millimeters(), Isis::IsisBundleObservation::computeRHSPartials(), Isis::IsisBundleObservation::computeTargetPartials(), Isis::LineScanCamera::GroundMap(), Isis::PushFrameCamera::GroundMap(), and Isis::VimsCamera::VimsCamera().
GroundRange()
bool Isis::Camera::GroundRange (double & minlat, double & maxlat, double & minlon, double & maxlon, Pvl & pvl) inherited
Computes the Ground Range.
Parameters
minlat The minimum latitude
maxlat The maximum latitude
minlon The minimum longitude
maxlon The maximum longitude
pvl The pvl file used for ground range calculations
Returns
bool Returns true if it crosses the longitude domain boundary and false if it does not
References Isis::PvlObject::findGroup(), Isis::PvlContainer::hasKeyword(), Isis::Distance::Meters, Isis::PI, Isis::Spice::radii(), Isis::toDouble(), and Isis::PvlObject::Traverse.
Referenced by Isis::UniversalGroundMap::GroundRange(), and Isis::Camera::IntersectsLongitudeDomain().
hasKernels()
bool Isis::Spice::hasKernels (Pvl & lab) inherited
Returns true if the kernel group has kernel files.
Parameters
lab Label containing Instrument and Kernels groups.
Returns
bool status of kernel files in the kernel group
References Isis::PvlObject::findGroup(), Isis::PvlContainer::hasKeyword(), and Isis::PvlKeyword::size().
HasProjection()
bool Isis::Camera::HasProjection () inherited
Checks to see if the camera object has a projection.
Returns
bool Returns true if it has a projection and false if it does not
Referenced by Isis::CubeViewport::CubeViewport(), and Isis::ImagePolygon::initCube().
HasReferenceBand()
bool Isis::Camera::HasReferenceBand () const inherited
Checks to see if the Camera object has a reference band.
Returns
bool Returns true if it has a reference band, and false if it does not
Referenced by Isis::ThemisVisCamera::BandEphemerisTimeOffset(), and Isis::ThemisIrCamera::SetBand().
HasSurfaceIntersection()
bool Isis::Sensor::HasSurfaceIntersection () const inherited
Returns if the last call to either SetLookDirection or SetUniversalGround had a valid intersection with the target.
If so then other methods such as Coordinate, UniversalLatitude, UniversalLongitude, etc can be used with confidence.
Returns
bool True if the look direction intersects with the target.
References Isis::ShapeModel::hasIntersection(), Isis::Target::shape(), and Isis::Spice::target().
Referenced by Isis::CameraStatistics::addStats(), Isis::Camera::DetectorResolution(), Isis::CSMCamera::DetectorResolution(), Isis::Stereo::elevation(), Isis::CSMCamera::LineResolution(), Isis::Chip::Load(), Isis::Camera::ObliqueDetectorResolution(), Isis::CSMCamera::SampleResolution(), and Isis::VimsGroundMap::SetGround().
HighestImageResolution()
double Isis::Camera::HighestImageResolution () inherited
Returns the highest/best resolution in the entire image.
Returns
double The highest/best resolution in the entire image
HighestObliqueImageResolution()
double Isis::Camera::HighestObliqueImageResolution () inherited
Returns the highest/best oblique resolution in the entire image.
Returns
double The highest/best oblique resolution in the entire image
IgnoreElevationModel()
void Isis::Sensor::IgnoreElevationModel (bool ignore) inherited
This allows you to ignore the cube elevation model and use the ellipse.
Parameters
ignore Indicates whether the elevation model is ignored.
References Isis::Target::restoreShape(), Isis::Target::setShapeEllipsoid(), and Isis::Spice::target().
Referenced by Isis::ImagePolygon::Create(), and Isis::ImagePolygon::initCube().
IgnoreProjection()
void Isis::Camera::IgnoreProjection (bool ignore) inherited
Set whether or not the camera should ignore the Projection.
Parameters
ignore
Referenced by Isis::VimsGroundMap::Init(), Isis::VimsSkyMap::Init(), Isis::VimsGroundMap::SetGround(), Isis::VimsSkyMap::SetSky(), and Isis::VimsCamera::VimsCamera().
IncidenceAngle()
double Isis::Sensor::IncidenceAngle () const virtual inherited
Returns the incidence angle in degrees.
This does not use the surface model.
Returns
double Incidence angle, in degrees.
Reimplemented in Isis::CSMCamera.
References Isis::ShapeModel::incidenceAngle(), Isis::Spice::m_uB, Isis::Target::shape(), and Isis::Spice::target().
Referenced by Isis::CameraStatistics::addStats(), Isis::InterestOperator::InterestByMeasure(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
InCube()
bool Isis::Camera::InCube () inherited
This returns true if the current Sample() or Line() value is outside of the cube (meaning the point must have been extrapolated).
Returns
bool Point was extrapolated
References Isis::Camera::Line(), Isis::Camera::Lines(), Isis::Camera::Sample(), and Isis::Camera::Samples().
Referenced by Isis::InterestOperator::FindCnetRef(), Isis::UniversalGroundMap::SetGround(), Isis::UniversalGroundMap::SetUnboundGround(), and Isis::UniversalGroundMap::SetUniversalGround().
instrumentBodyFixedPosition()
void Isis::Spice::instrumentBodyFixedPosition (double p[3]) const virtual inherited
Returns the spacecraft position in body-fixed frame km units.
Parameters
p[] Spacecraft position
See also
setTime()
Exceptions
Isis::iException::Programmer - "You must call SetTime first"
Reimplemented in Isis::CSMCamera.
References _FILEINFO_.
Referenced by Isis::Camera::LocalPhotometricAngles(), Isis::Sensor::PhaseAngle(), and Isis::Sensor::SlantDistance().
instrumentBodyFixedVelocity()
void Isis::Spice::instrumentBodyFixedVelocity (double v[3]) const virtual inherited
Returns the spacecraft velocity in body-fixed frame km/sec units.
Parameters
v[] Spacecraft velocity
References _FILEINFO_.
instrumentId()
QString Isis::Camera::instrumentId () inherited
This method returns the InstrumentId as it appears in the cube.
Returns
QString Returns m_instrumentId
References Isis::Camera::m_instrumentId.
Referenced by Isis::GuiCamera::GuiCamera(), and Isis::RosettaVirtisCamera::RosettaVirtisCamera().
instrumentNameLong()
QString Isis::Camera::instrumentNameLong () const virtual inherited
This method returns the full instrument name.
Returns
QString
Implements Isis::Sensor.
Reimplemented in Isis::IdealCamera.
References Isis::Camera::m_instrumentNameLong.
Referenced by Isis::GuiCamera::GuiCamera().
instrumentNameShort()
QString Isis::Camera::instrumentNameShort () const virtual inherited
This method returns the shortened instrument name.
Returns
QString
Implements Isis::Sensor.
Reimplemented in Isis::IdealCamera.
References Isis::Camera::m_instrumentNameShort.
Referenced by Isis::GuiCamera::GuiCamera().
instrumentPosition() [1/2]
SpicePosition * Isis::Spice::instrumentPosition () const virtual inherited
Accessor method for the instrument position.
Returns
iTime Instrument position for the image.
Author
Steven Lambright
Reimplemented in Isis::CSMCamera.
Referenced by Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::Camera::DetectorResolution(), Isis::Sensor::EmissionAngle(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MiniRF::MiniRF(), Isis::Camera::OffNadirAngle(), Isis::Sensor::SetGround(), Isis::Sensor::SetLookDirection(), Isis::Sensor::SetUniversalGround(), and Isis::Sensor::SpacecraftAltitude().
instrumentPosition() [2/2]
void Isis::Spice::instrumentPosition (double p[3]) const inherited
Returns the spacecraft position in body-fixed frame km units.
Parameters
p[] Spacecraft position
See also
setTime()
Exceptions
Isis::iException::Programmer - "You must call SetTime first"
Referenced by Isis::Cube::attachSpiceFromIsd(), Isis::RadarGroundMap::GetdXYdPosition(), Isis::RadarGroundMap::GetXY(), Isis::RadarGroundMap::SetFocalPlane(), and Isis::RadarGroundMap::SetGround().
instrumentRotation()
SpiceRotation * Isis::Spice::instrumentRotation () const virtual inherited
Accessor method for the instrument rotation.
Returns
iTime Instrument rotation for the image.
Author
Steven Lambright
Reimplemented in Isis::CSMCamera.
Referenced by Isis::Cube::attachSpiceFromIsd(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::Sensor::LookDirection(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::RadarGroundMap::SetFocalPlane(), Isis::RadarGroundMap::SetGround(), Isis::Sensor::SetLookDirection(), Isis::Sensor::SetRightAscensionDeclination(), and Isis::TgoCassisCamera::TgoCassisCamera().
IntersectsLongitudeDomain()
bool Isis::Camera::IntersectsLongitudeDomain (Pvl & pvl) inherited
Checks whether the ground range intersects the longitude domain or not.
Parameters
pvl The pvl file used to set the ground range
Returns
bool Returns true if the range intersects the longitude domain, and false if it does not
References Isis::Camera::GroundRange().
IsBandIndependent()
bool Isis::Camera::IsBandIndependent () virtual inherited
Virtual method that checks if the band is independent.
Returns
bool Returns true if the band is independent, and false if it is not
Reimplemented in Isis::ThemisVisCamera, Isis::ThemisIrCamera, Isis::NewHorizonsLeisaCamera, Isis::MarciCamera, Isis::CrismCamera, and Isis::LroWideAngleCamera.
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::Camera::RaDecRange(), and Isis::ProjectionFactory::RingsCreateForCube().
isTimeSet()
bool Isis::Spice::isTimeSet () inherited
Returns true if time has been initialized.
Author
2016-10-19 Kristin Berry
Returns
bool true if time has been set
Referenced by Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
isUsingAle()
bool Isis::Spice::isUsingAle () inherited
Line()
double Isis::Camera::Line () const virtual inherited
Returns the current line number.
Returns
double Line Number
References Isis::Camera::p_childLine.
Referenced by Isis::Camera::CelestialNorthClockAngle(), Isis::CSMCamera::CelestialNorthClockAngle(), Isis::LidarControlPoint::ComputeResiduals(), Isis::ControlPoint::ComputeResiduals_Millimeters(), Isis::CsmBundleObservation::computeRHSPartials(), Isis::ControlPointEditWidget::createControlPoint(), Isis::QnetTool::createFixedPoint(), Isis::ProjectionFactory::CreateForCube(), Isis::QnetTool::createPoint(), Isis::InterestOperator::FindCnetRef(), Isis::Camera::GetLocalNormal(), Isis::IsisSensor::getState(), Isis::Camera::InCube(), Isis::UniversalGroundMap::Line(), Isis::Chip::Load(), Isis::CSMCamera::parentLine(), Isis::Camera::RaDecRange(), and Isis::Camera::RaDecResolution().
LineResolution()
double Isis::Camera::LineResolution () virtual inherited
Returns the line resolution at the current position in meters.
Returns
double The line resolution
Reimplemented in Isis::CSMCamera.
References Isis::Camera::DetectorResolution(), and Isis::CameraDetectorMap::LineScaleFactor().
Referenced by Isis::CameraStatistics::addStats(), and Isis::Camera::PixelResolution().
Lines()
int Isis::Camera::Lines () const inherited
Returns the number of lines in the image.
Returns
int Number of Lines
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::Camera::InCube(), Isis::NewHorizonsMvicFrameCameraDistortionMap::NewHorizonsMvicFrameCameraDistortionMap(), Isis::RadarGroundMap::RadarGroundMap(), and Isis::ProjectionFactory::RingsCreateForCube().
LoadCache()
void Isis::Camera::LoadCache () inherited
This loads the spice cache big enough for this image.
The default cache size is the number of lines in the cube if the ephemeris time changes in the image, one otherwise.
References Isis::AlphaCube::BetaLines(), Isis::AlphaCube::BetaSamples(), Isis::Camera::CacheSize(), Isis::Spice::createCache(), Isis::Camera::FocalLength(), Isis::Camera::p_alphaCube, Isis::Camera::PixelPitch(), Isis::Camera::PixelResolution(), Isis::Camera::SetBand(), Isis::Camera::SetImage(), Isis::Sensor::setTime(), Isis::Sensor::SpacecraftAltitude(), Isis::Camera::StartEndEphemerisTimes(), and Isis::Spice::target().
Referenced by Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ClipperWacFcCamera::ClipperWacFcCamera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IdealCamera::IdealCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::LwirCamera::LwirCamera(), Isis::MarciCamera::MarciCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::NirCamera::NirCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::ThemisVisCamera::ThemisVisCamera(), Isis::UvvisCamera::UvvisCamera(), Isis::VikingCamera::VikingCamera(), Isis::VimsCamera::VimsCamera(), and Isis::VoyagerCamera::VoyagerCamera().
LocalPhotometricAngles()
void Isis::Camera::LocalPhotometricAngles (Angle & phase, Angle & incidence, Angle & emission, bool & success) inherited
Calculates LOCAL photometric angles using the DEM (not ellipsoid).
These calculations are more expensive computationally than Sensor's angle getter methods. Furthermore, this cost is mostly in calculating the local normal vector, which can be done only once for all angles using this method.
Parameters
phase The local phase angle to be calculated
incidence The local incidence angle to be calculated
emission The local emission angle to be calculated
success A boolean to keep track of whether normal is valid
References Isis::Camera::GetLocalNormal(), Isis::Sensor::GetSurfacePoint(), Isis::SurfacePoint::GetX(), Isis::SurfacePoint::GetY(), Isis::SurfacePoint::GetZ(), Isis::Spice::instrumentBodyFixedPosition(), Isis::Displacement::kilometers(), Isis::Spice::m_uB, and Isis::Angle::Radians.
Referenced by Isis::Camera::ObliqueDetectorResolution().
LocalRadius() [1/3]
Distance Isis::Sensor::LocalRadius () const inherited
Returns the local radius at the intersection point.
This is either the radius on the ellipsoid, the radius from the surface model passed into the constructor, or the radius set with SetUniversalGround.
Returns
Distance The local radius at the surface intersection.
References Isis::SurfacePoint::GetLocalRadius(), Isis::Target::shape(), Isis::ShapeModel::surfaceIntersection(), and Isis::Spice::target().
Referenced by Isis::CameraStatistics::addStats(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::QnetCubeDistanceFilter::filter(), Isis::Camera::GetLocalNormal(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::LineScanCameraGroundMap::SetGround(), Isis::PushFrameCameraGroundMap::SetGround(), Isis::RadarGroundMap::SetGround(), Isis::VimsGroundMap::SetGround(), Isis::Camera::SetGround(), Isis::CSMCamera::SetGround(), and Isis::Sensor::SpacecraftAltitude().
LocalRadius() [2/3]
Distance Isis::Sensor::LocalRadius (double lat, double lon) inherited
Returns the local radius at the intersection point.
This is either the radius on the ellipsoid, the radius from the surface model passed into the constructor, or the radius set with SetUniversalGround.
Parameters
lat
lon
Returns
Distance The distance from the center of the planet to this lat,lon in meters.
References Isis::Angle::Degrees, Isis::ShapeModel::localRadius(), Isis::Target::shape(), and Isis::Spice::target().
LocalRadius() [3/3]
Distance Isis::Sensor::LocalRadius (Latitude lat, Longitude lon) inherited
Returns the local radius at the intersection point.
This is either the radius on the ellipsoid, the radius from the surface model passed into the constructor, or the radius set with SetUniversalGround.
Parameters
lat
lon
Returns
Distance The distance from the center of the planet to this lat,lon in meters.
References Isis::ShapeModel::localRadius(), Isis::Target::shape(), and Isis::Spice::target().
LocalSolarTime()
double Isis::Sensor::LocalSolarTime () inherited
Return the local solar time in hours.
Returns
double Local solar time, in hours.
References Isis::Spice::subSolarPoint(), and Isis::Sensor::UniversalLongitude().
Referenced by Isis::CameraStatistics::addStats().
LookDirection()
void Isis::Sensor::LookDirection (double v[3]) const inherited
Returns the look direction in the camera coordinate system.
Parameters
v[] The look vector.
References Isis::Spice::instrumentRotation(), Isis::Sensor::lookDirectionJ2000(), and Isis::SpiceRotation::ReferenceVector().
lookDirectionBodyFixed()
vector< double > Isis::Sensor::lookDirectionBodyFixed () const virtual inherited
Returns the look direction in the body fixed coordinate system.
Returns
vector<double> Look direction in body fixed coordinate system.
References Isis::Sensor::m_lookB.
Referenced by Isis::Sensor::lookDirectionJ2000().
lookDirectionJ2000()
vector< double > Isis::Sensor::lookDirectionJ2000 () const virtual inherited
Returns the look direction in the camera coordinate system.
Returns
vector<double> Look direction in J2000 cooridinate system.
References Isis::Spice::bodyRotation(), Isis::SpiceRotation::J2000Vector(), and Isis::Sensor::lookDirectionBodyFixed().
Referenced by Isis::Sensor::LookDirection().
LowestImageResolution()
double Isis::Camera::LowestImageResolution () inherited
Returns the lowest/worst resolution in the entire image.
Returns
double The lowest/worst resolution in the image
LowestObliqueImageResolution()
double Isis::Camera::LowestObliqueImageResolution () inherited
Returns the lowest/worst oblique resolution in the entire image.
Returns
double The lowest/worst oblique resolution in the image
naifBodyCode()
SpiceInt Isis::Spice::naifBodyCode () const inherited
This returns the NAIF body code of the target indicated in the labels.
Returns
SpiceInt NAIF body code
Referenced by Isis::Camera::SpkCenterId().
naifBodyFrameCode()
SpiceInt Isis::Spice::naifBodyFrameCode () const inherited
This returns the NAIF body frame code.
It is read from the labels, if it exists. Otherwise, it's calculated by the init() method.
Returns
SpiceInt NAIF body frame code
naifCkCode()
SpiceInt Isis::Spice::naifCkCode () const inherited
This returns the NAIF CK code to use when reading from CK kernels.
Returns
SpiceInt NAIF CK code
naifIkCode()
SpiceInt Isis::Spice::naifIkCode () const inherited
This returns the NAIF IK code to use when reading from instrument kernels.
Returns
SpiceInt NAIF IK code
Referenced by Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ClipperWacFcCamera::ClipperWacFcCamera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::LwirCamera::LwirCamera(), Isis::MarciCamera::MarciCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MiniRF::MiniRF(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::NirCamera::NirCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::Camera::SetFocalLength(), Isis::Camera::SetPixelPitch(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::ThemisVisCamera::ThemisVisCamera(), Isis::UvvisCamera::UvvisCamera(), Isis::VikingCamera::VikingCamera(), Isis::VimsCamera::VimsCamera(), and Isis::VoyagerCamera::VoyagerCamera().
naifSclkCode()
SpiceInt Isis::Spice::naifSclkCode () const inherited
This returns the NAIF SCLK code to use when reading from instrument kernels.
Returns
SpiceInt NAIF SCLK code
Referenced by Isis::CrismCamera::CrismCamera().
naifSpkCode()
SpiceInt Isis::Spice::naifSpkCode () const inherited
This returns the NAIF SPK code to use when reading from SPK kernels.
Returns
SpiceInt NAIF SPK code
Referenced by Isis::Camera::SpkTargetId().
NorthAzimuth()
double Isis::Camera::NorthAzimuth () inherited
Returns the North Azimuth.
Returns
double North Azimuth
References _FILEINFO_, Isis::IException::Programmer, Isis::Spice::target(), and Isis::Sensor::UniversalLatitude().
Referenced by Isis::CameraStatistics::addStats().
ObliqueDetectorResolution()
double Isis::Camera::ObliqueDetectorResolution (bool useLocal = true) virtual inherited
This method returns the Oblique Detector Resolution if the Look Vector intersects the target and if the emission angle is greater than or equal to 0, and less than 90 degrees.
Otherwise, it returns Isis::Null. This formula provides an improved estimate to the detector resolution for images near the limb:
\[ \text{Oblique\;\;Detector\;\; Resolution} = \frac{n}{cos(\theta)} \]
The equation is derived two separate ways. A geometric argument is presented in Reference 2, while a matrix algebra based argument is presented in Theorem 2.1 of Reference 1.
Reference 1: J-M Morel and G. Yu, "Asift: A new framework for fully affine invariant image comparison," SIAM Journal on Imaging Sciences 2(2), pp. 438-469, 2009
Reference 2: Handwritten notes by Orrin Thomas which can be found in the Glossary under the entry for Oblique Detector Resolution.
Parameters
useLocal If true, emission is fetched from LocalPhotometricAngles. Otherwise, emission is fetched from EmissionAngle(). This is an optional parameter that defaults to true, because local emission will give more accurate results.
Returns
double
Reimplemented in Isis::CSMCamera.
References Isis::DEG2RAD, Isis::Angle::degrees(), Isis::Camera::DetectorResolution(), Isis::Sensor::EmissionAngle(), Isis::HALFPI, Isis::Sensor::HasSurfaceIntersection(), Isis::Camera::LocalPhotometricAngles(), and Isis::Null.
Referenced by Isis::Camera::ObliqueLineResolution(), and Isis::Camera::ObliqueSampleResolution().
ObliqueLineResolution()
double Isis::Camera::ObliqueLineResolution (bool useLocal = true) virtual inherited
Returns the oblique line resolution at the current position in meters.
This provides a more accurate estimate of the line resolution at oblique angles.
Returns
double The line resolution
Reimplemented in Isis::CSMCamera.
References Isis::CameraDetectorMap::LineScaleFactor(), and Isis::Camera::ObliqueDetectorResolution().
Referenced by Isis::CameraStatistics::addStats(), and Isis::Camera::ObliquePixelResolution().
ObliquePixelResolution()
double Isis::Camera::ObliquePixelResolution (bool useLocal = true) virtual inherited
Returns the oblique pixel resolution at the current position in meters/pixel.
This provides a more accurate estimate of the pixel resolution at oblique angles.
Returns
double The pixel resolution
References Isis::Null, Isis::Camera::ObliqueLineResolution(), and Isis::Camera::ObliqueSampleResolution().
Referenced by Isis::CameraStatistics::addStats().
ObliqueSampleResolution()
double Isis::Camera::ObliqueSampleResolution (bool useLocal = true) virtual inherited
Returns the oblique sample resolution at the current position in m.
This gives a more accurate estimate of the sample resolution at oblique angles.
Returns
double The sample resolution
Reimplemented in Isis::CSMCamera.
References Isis::Camera::ObliqueDetectorResolution(), and Isis::CameraDetectorMap::SampleScaleFactor().
Referenced by Isis::CameraStatistics::addStats(), and Isis::Camera::ObliquePixelResolution().
OffNadirAngle()
double Isis::Camera::OffNadirAngle () inherited
Return the off nadir angle in degrees.
Returns
double Off Nadir Angle
References Isis::Sensor::Coordinate(), Isis::Sensor::EmissionAngle(), Isis::Spice::instrumentPosition(), and Isis::RAD2DEG.
ParentLines()
int Isis::Camera::ParentLines () const inherited
Returns the number of lines in the parent alphacube.
Returns
int Number of Lines in parent alphacube
References Isis::AlphaCube::AlphaLines(), and Isis::Camera::p_alphaCube.
Referenced by Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::CrismCamera::CrismCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::VimsGroundMap::Init(), Isis::VimsSkyMap::Init(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::MarciCamera::MarciCamera(), Isis::MiniRF::MiniRF(), Isis::VimsGroundMap::SetFocalPlane(), Isis::VimsSkyMap::SetFocalPlane(), Isis::VimsGroundMap::SetGround(), Isis::VimsSkyMap::SetSky(), Isis::ThemisVisCamera::ThemisVisCamera(), Isis::PushFrameCameraDetectorMap::TotalFramelets(), and Isis::VimsGroundMap::VimsGroundMap().
ParentSamples()
int Isis::Camera::ParentSamples () const inherited
Returns the number of samples in the parent alphacube.
Returns
int Number of Samples in the parent alphacube
References Isis::AlphaCube::AlphaSamples(), and Isis::Camera::p_alphaCube.
Referenced by Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::LineScanCameraGroundMap::FindFocalPlane(), Isis::LineScanCameraGroundMap::FindSpacecraftDistance(), Isis::VimsGroundMap::Init(), Isis::VimsSkyMap::Init(), Isis::VimsGroundMap::SetFocalPlane(), Isis::VimsSkyMap::SetFocalPlane(), Isis::VimsGroundMap::SetGround(), Isis::VimsSkyMap::SetSky(), and Isis::VimsGroundMap::VimsGroundMap().
PhaseAngle()
double Isis::Sensor::PhaseAngle () const virtual inherited
Returns the phase angle in degrees.
This does not use the surface model.
Returns
double Phase angle, in degrees.
Reimplemented in Isis::CSMCamera.
References Isis::Sensor::Coordinate(), Isis::Spice::instrumentBodyFixedPosition(), Isis::Spice::m_uB, and Isis::RAD2DEG.
Referenced by Isis::CameraStatistics::addStats().
PixelIfovOffsets()
QList< QPointF > Isis::Camera::PixelIfovOffsets () virtual inherited
Returns the pixel ifov offsets from center of pixel, which defaults to the (pixel pitch * summing mode) / 2.
If an instrument has a non-square ifov, it must implement this method to return the offsets from the center of the pixel.
Returns
QList<QPointF> A list of offsets
Reimplemented from Isis::Sensor.
Reimplemented in Isis::HayabusaNirsCamera, Isis::VimsCamera, and Isis::CSMCamera.
References Isis::Camera::DetectorMap(), and Isis::Camera::PixelPitch().
PixelPitch()
double Isis::Camera::PixelPitch () const inherited
Returns the pixel pitch.
Returns
double Pixel Pitch
Referenced by Isis::IsisBundleObservation::computeImagePartials(), Isis::IsisBundleObservation::computePoint3DPartials(), Isis::IsisBundleObservation::computeRHSPartials(), Isis::IsisBundleObservation::computeTargetPartials(), Isis::CrismCamera::CrismCamera(), Isis::OsirisRexTagcamsDistortionMap::distortion_to_pointing_frame(), Isis::IdealCamera::IdealCamera(), Isis::Camera::LoadCache(), Isis::MiniRF::MiniRF(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::NewHorizonsMvicFrameCameraDistortionMap::NewHorizonsMvicFrameCameraDistortionMap(), Isis::NewHorizonsMvicTdiCameraDistortionMap::NewHorizonsMvicTdiCameraDistortionMap(), Isis::OsirisRexDistortionMap::OsirisRexDistortionMap(), Isis::OsirisRexOcamsDistortionMap::OsirisRexOcamsDistortionMap(), Isis::Camera::PixelIfovOffsets(), Isis::HayabusaNirsCamera::PixelIfovOffsets(), Isis::OsirisRexTagcamsDistortionMap::pointing_to_distortion_frame(), Isis::ReseauDistortionMap::ReseauDistortionMap(), Isis::KaguyaMiCameraDistortionMap::SetDistortion(), Isis::JunoDistortionMap::SetDistortion(), Isis::MarciDistortionMap::SetFocalPlane(), Isis::JunoDistortionMap::SetFocalPlane(), Isis::BundleMeasure::setSigma(), Isis::MarciDistortionMap::SetUndistortedFocalPlane(), Isis::CameraDistortionMap::SetUndistortedFocalPlane(), and Isis::Hyb2OncDistortionMap::SetUndistortedFocalPlane().
PixelResolution()
double Isis::Camera::PixelResolution () virtual inherited
Returns the pixel resolution at the current position in meters/pixel.
Returns
double The pixel resolution
References Isis::Camera::LineResolution(), Isis::Null, and Isis::Camera::SampleResolution().
Referenced by Isis::CameraStatistics::addStats(), Isis::InterestOperator::InterestByMeasure(), Isis::Camera::LoadCache(), Isis::ControlNetValidMeasure::MetersFromEdge(), Isis::MiniRF::MiniRF(), Isis::Camera::resolution(), Isis::UniversalGroundMap::Resolution(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
RaDecRange()
bool Isis::Camera::RaDecRange (double & minra, double & maxra, double & mindec, double & maxdec) inherited
Computes the RaDec range.
Parameters
minra Minimum right ascension value
maxra Maximum right ascension value
mindec Minimum declination value
maxdec Maximum declination value
Returns
bool Returns true if the range computation was successful and false if it was not
References Isis::Camera::Band(), Isis::Sensor::Declination(), Isis::Camera::IsBandIndependent(), Isis::Camera::Line(), Isis::Camera::p_pointComputed, Isis::Sensor::RightAscension(), Isis::Camera::Sample(), Isis::Camera::SetBand(), Isis::Camera::SetImage(), and Isis::Camera::SetRightAscensionDeclination().
RaDecResolution()
double Isis::Camera::RaDecResolution () inherited
Returns the RaDec resolution.
Returns
double The resutant RaDec resolution
References Isis::Camera::Band(), Isis::Sensor::Declination(), Isis::Camera::Line(), Isis::Camera::p_pointComputed, Isis::Sensor::RightAscension(), Isis::Camera::Sample(), Isis::Camera::SetBand(), and Isis::Camera::SetImage().
Referenced by Isis::Camera::CelestialNorthClockAngle(), and Isis::CSMCamera::CelestialNorthClockAngle().
radii()
void Isis::Spice::radii (Distance r[3]) const inherited
Returns the radii of the body in km.
The radii are obtained from the appropriate SPICE kernel for the body specified by TargetName in the Instrument group of the labels.
Parameters
r[] Radii of the target in kilometers
Referenced by Isis::Camera::BasicMapping(), Isis::Camera::GroundRange(), Isis::VimsGroundMap::Init(), Isis::MiniRF::MiniRF(), Isis::RadarGroundMap::SetFocalPlane(), and Isis::CSMCamera::setTarget().
readStoredValue()
QVariant Isis::Spice::readStoredValue (QString key, SpiceValueType type, int index) protected inherited
References Isis::IException::print(), Isis::toDouble(), and Isis::toInt().
readValue()
QVariant Isis::Spice::readValue (QString key, SpiceValueType type, int index = 0) protected inherited
This should be used for reading ALL text naif kernel values.
This will read it from Naif if we're using naif/not attached kernels. If we have attached kernels and a NaifKeywords label object we will grab it from there instead. This allows us to not furnish kernels after spiceinit.
Parameters
key The naif keyword,value name
type The naif value's primitive type
index The index into the naif keyword array to read
References _FILEINFO_.
Referenced by Isis::IdealCamera::IdealCamera().
ReferenceBand()
int Isis::Camera::ReferenceBand () const inherited
Returns the reference band.
Returns
int Reference Band
Referenced by Isis::ThemisVisCamera::BandEphemerisTimeOffset(), and Isis::ThemisIrCamera::SetBand().
resolution()
double Isis::Camera::resolution () virtual inherited
Returns the resolution of the camera.
Returns
double pixel resolution
Reimplemented from Isis::Sensor.
References Isis::Camera::PixelResolution().
RightAscension()
double Isis::Sensor::RightAscension () virtual inherited
Returns the right ascension angle (sky longitude).
Returns
double The angle of right ascension, in degrees.
Reimplemented in Isis::CSMCamera.
References Isis::Sensor::m_newLookB.
Referenced by Isis::Camera::CelestialNorthClockAngle(), Isis::VimsSkyMap::Init(), Isis::FindTool::mouseButtonRelease(), Isis::Camera::RaDecRange(), and Isis::Camera::RaDecResolution().
ringRange()
bool Isis::Camera::ringRange (double & minRingRadius, double & maxRingRadius, double & minRingLongitude, double & maxRingLongitude, Pvl & pvl) inherited
Analogous to the above Ground Range method.
Computes Range on the ring plane
Parameters
minRingRadius The minimum ring radius
maxRingRadius The maximum ring radius
minRingLongitude The minimum ring longitude
maxRingLongitude The maximum ring longitude
pvl The pvl file used for ring range calculations
Returns
bool Returns true if it crosses the longitude domain boundary and false if it does not
References Isis::PvlObject::findGroup(), Isis::PvlContainer::hasKeyword(), and Isis::PvlObject::Traverse.
Sample()
double Isis::Camera::Sample () const virtual inherited
Returns the current sample number.
Returns
double Sample Number
References Isis::Camera::p_childSample.
Referenced by Isis::Camera::CelestialNorthClockAngle(), Isis::CSMCamera::CelestialNorthClockAngle(), Isis::LidarControlPoint::ComputeResiduals(), Isis::ControlPoint::ComputeResiduals_Millimeters(), Isis::CsmBundleObservation::computeRHSPartials(), Isis::ControlPointEditWidget::createControlPoint(), Isis::QnetTool::createFixedPoint(), Isis::ProjectionFactory::CreateForCube(), Isis::QnetTool::createPoint(), Isis::InterestOperator::FindCnetRef(), Isis::Camera::GetLocalNormal(), Isis::Camera::InCube(), Isis::Chip::Load(), Isis::CSMCamera::parentSample(), Isis::Camera::RaDecRange(), Isis::Camera::RaDecResolution(), and Isis::UniversalGroundMap::Sample().
SampleResolution()
double Isis::Camera::SampleResolution () virtual inherited
Returns the sample resolution at the current position in meters.
Returns
double The sample resolution
Reimplemented in Isis::CSMCamera.
References Isis::Camera::DetectorResolution(), and Isis::CameraDetectorMap::SampleScaleFactor().
Referenced by Isis::CameraStatistics::addStats(), and Isis::Camera::PixelResolution().
Samples()
int Isis::Camera::Samples () const inherited
Returns the number of samples in the image.
Returns
int Number of Samples
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::Camera::InCube(), Isis::MiniRF::MiniRF(), Isis::NewHorizonsMvicFrameCameraDistortionMap::NewHorizonsMvicFrameCameraDistortionMap(), Isis::NewHorizonsMvicTdiCameraDistortionMap::NewHorizonsMvicTdiCameraDistortionMap(), and Isis::ProjectionFactory::RingsCreateForCube().
SetBand()
void Isis::Camera::SetBand (const int band) virtual inherited
Virtual method that sets the band number.
Parameters
band Band Number
Reimplemented in Isis::NewHorizonsMvicFrameCamera, Isis::NewHorizonsLeisaCamera, Isis::CrismCamera, Isis::ThemisVisCamera, Isis::ThemisIrCamera, Isis::MarciCamera, and Isis::LroWideAngleCamera.
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::Camera::LoadCache(), Isis::Camera::RaDecRange(), Isis::Camera::RaDecResolution(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::UniversalGroundMap::SetBand(), Isis::LroWideAngleCamera::SetBand(), Isis::MarciCamera::SetBand(), Isis::ThemisVisCamera::SetBand(), Isis::NewHorizonsLeisaCamera::SetBand(), Isis::NewHorizonsMvicFrameCamera::SetBand(), Isis::Camera::StartEndEphemerisTimes(), Isis::CubeViewport::viewGray(), and Isis::CubeViewport::viewRGB().
SetDetectorMap()
void Isis::Camera::SetDetectorMap (CameraDetectorMap * map) inherited
Sets the Detector Map.
This object will take ownership of the detector map pointer.
Parameters
*map Pointer to a CameraDetectorMap object
Referenced by Isis::CameraDetectorMap::CameraDetectorMap().
SetDistortionMap()
void Isis::Camera::SetDistortionMap (CameraDistortionMap * map, bool deleteExisting = true) inherited
Sets the Distortion Map.
This object will take ownership of the distortion map pointer.
Parameters
*map Pointer to a CameraDistortionMap object
Referenced by Isis::CameraDistortionMap::CameraDistortionMap(), and Isis::TgoCassisCamera::TgoCassisCamera().
SetFocalLength() [1/2]
void Isis::Camera::SetFocalLength () protected inherited
Reads the focal length from the instrument kernel.
References Isis::Spice::getDouble(), Isis::Spice::naifIkCode(), and Isis::toString().
Referenced by Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ClipperWacFcCamera::ClipperWacFcCamera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IdealCamera::IdealCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::LwirCamera::LwirCamera(), Isis::MarciCamera::MarciCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MiniRF::MiniRF(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::NirCamera::NirCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::LroWideAngleCamera::SetBand(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::ThemisVisCamera::ThemisVisCamera(), Isis::UvvisCamera::UvvisCamera(), Isis::VikingCamera::VikingCamera(), Isis::VimsCamera::VimsCamera(), and Isis::VoyagerCamera::VoyagerCamera().
SetFocalLength() [2/2]
void Isis::Camera::SetFocalLength (double v) protected inherited
Sets the focal length.
Parameters
v Focal Length
Referenced by Isis::RadarSlantRangeMap::SetFocalPlane(), and Isis::RadarGroundMap::SetGround().
SetFocalPlaneMap()
void Isis::Camera::SetFocalPlaneMap (CameraFocalPlaneMap * map) inherited
Sets the Focal Plane Map.
This object will take ownership of the focal plane map pointer.
Parameters
*map Pointer to a CameraFocalPlaneMap object
Referenced by Isis::CameraFocalPlaneMap::CameraFocalPlaneMap().
SetGeometricTilingHint()
void Isis::Camera::SetGeometricTilingHint (int startSize = 128, int endSize = 8) protected inherited
This method sets the best geometric tiling size for projecting from this camera model.
This is used by cam2map/ProcessRubberSheet. When cubes are projected, an attempt is made to use linear equations to take large, square chunks of data at a time to cull the amount of SetUniversalGround(...) calls necessary to project a cube. If the chunk of data fails to be linear, then it will be split up into 4 corners and each of the new chunks (corners) are reconsidered up until endSize is reached - the endsize size will be considered, it is inclusive. The startSize must be a power of 2 greater than 2, and the endSize must be a power of 2 equal to or less than the start size but greater than 2. If both the startSize and endSize are set to 2 then no geometric tiling will be enabled.
Parameters
startSize The tile size to start with; default 128
endSize The tile size to give up at; default 8
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by Isis::Camera::Camera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), and Isis::MarciCamera::MarciCamera().
SetGround() [1/3]
bool Isis::Camera::SetGround (const SurfacePoint & surfacePt) virtual inherited
Sets the lat/lon/radius values to get the sample/line values.
Parameters
surfacePt The point used for calculation
Returns
bool Returns true if the Universal Ground was set successfully and false if it was not
Reimplemented in Isis::CSMCamera.
References Isis::ShapeModel::clearSurfacePoint(), Isis::CameraGroundMap::SetGround(), Isis::Target::shape(), Isis::Spice::target(), and Isis::SurfacePoint::Valid().
SetGround() [2/3]
bool Isis::Sensor::SetGround (const SurfacePoint & surfacePt, bool backCheck = true) inherited
This overloaded method has the opposite function as SetLookDirection.
Instead of computing a point on the target, a point is set and the look direction is computed. Other methods such as lat/lon, phase, incidence, etc. can be used if this method returns a true.
Parameters
backCheck If true this method will check the lat/lon point to see if it falls on the backside of the target (or beyond the horizon). If false this test will not occur. Defaults to true.
Returns
bool
References Isis::Spice::bodyRotation(), Isis::ShapeModel::clearSurfacePoint(), Isis::Sensor::Coordinate(), Isis::Spice::instrumentPosition(), Isis::ShapeModel::intersectSurface(), Isis::Target::shape(), and Isis::Spice::target().
SetGround() [3/3]
bool Isis::Camera::SetGround (Latitude latitude, Longitude longitude) virtual inherited
Sets the lat/lon values to get the sample/line values.
Parameters
latitude Latitude coordinate of the point
longitude Longitude coordinate of the point
Returns
bool Returns true if the Universal Ground was set successfully and false if it was not
Reimplemented in Isis::CSMCamera.
References Isis::ShapeModel::clearSurfacePoint(), Isis::Angle::Degrees, Isis::Angle::degrees(), Isis::Distance::isValid(), Isis::Distance::Kilometers, Isis::Sensor::LocalRadius(), Isis::ShapeModel::name(), Isis::Target::shape(), and Isis::Spice::target().
Referenced by Isis::LidarControlPoint::ComputeResiduals(), Isis::ControlPoint::ComputeResiduals_Millimeters(), Isis::CsmBundleObservation::computeRHSPartials(), Isis::UniversalGroundMap::SetGround(), and Isis::UniversalGroundMap::SetUnboundGround().
SetGroundMap()
void Isis::Camera::SetGroundMap (CameraGroundMap * map) inherited
Sets the Ground Map.
This object will take ownership of the ground map pointer.
Parameters
*map Pointer to a CameraGroundMap object
Referenced by Isis::CameraGroundMap::CameraGroundMap().
SetImage() [1/2]
bool Isis::Camera::SetImage (const double sample, const double line) virtual inherited
Sets the sample/line values of the image to get the lat/lon values.
Parameters
sample Sample coordinate of the cube.
line Line coordinate of the cube.
Returns
bool Returns True if the image was set successfully and False if it was not.
Reimplemented in Isis::CSMCamera.
References Isis::AlphaCube::AlphaLine(), Isis::AlphaCube::AlphaSample(), Isis::ShapeModel::clearSurfacePoint(), Isis::CameraDetectorMap::DetectorLine(), Isis::CameraDetectorMap::DetectorSample(), Isis::CameraFocalPlaneMap::FocalPlaneX(), Isis::CameraFocalPlaneMap::FocalPlaneY(), Isis::Projection::IsSky(), Isis::Camera::p_alphaCube, Isis::Camera::p_childLine, Isis::Camera::p_childSample, Isis::Camera::p_pointComputed, Isis::CameraFocalPlaneMap::SetDetector(), Isis::CameraGroundMap::SetFocalPlane(), Isis::CameraDistortionMap::SetFocalPlane(), Isis::CameraDetectorMap::SetParent(), Isis::Target::shape(), Isis::Spice::target(), Isis::CameraDistortionMap::UndistortedFocalPlaneX(), Isis::CameraDistortionMap::UndistortedFocalPlaneY(), and Isis::CameraDistortionMap::UndistortedFocalPlaneZ().
Referenced by Isis::CameraStatistics::addStats(), Isis::Camera::CelestialNorthClockAngle(), Isis::ControlPoint::ComputeApriori(), Isis::ControlPoint::ComputeResiduals(), Isis::ControlPoint::ComputeResiduals_Millimeters(), Isis::ProjectionFactory::CreateForCube(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::QnetCubeDistanceFilter::filter(), Isis::QnetPointDistanceFilter::filter(), Isis::InterestOperator::FindCnetRef(), Isis::Camera::GetLocalNormal(), Isis::VimsGroundMap::Init(), Isis::VimsSkyMap::Init(), Isis::InterestOperator::InterestByMeasure(), Isis::Cube::latLonRange(), Isis::PixelFOV::latLonVertices(), Isis::Chip::Load(), Isis::Camera::LoadCache(), Isis::ControlNetValidMeasure::MetersFromEdge(), Isis::SunShadowTool::mouseButtonPress(), Isis::LatLonGridTool::paintViewport(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::Camera::RaDecRange(), Isis::Camera::RaDecResolution(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::VimsGroundMap::SetGround(), Isis::BundleMeasure::setImage(), Isis::UniversalGroundMap::SetImage(), Isis::VimsSkyMap::SetSky(), Isis::Camera::StartEndEphemerisTimes(), Isis::ControlNetValidMeasure::ValidStandardOptions(), and Isis::VimsCamera::VimsCamera().
SetImage() [2/2]
bool Isis::Camera::SetImage (const double sample, const double line, const double deltaT) virtual inherited
Sets the sample/line values of the image to get the lat/lon values with a time offset of deltaT.
Warning: The deltaT parameter was added specifically for pixel2map to use for the Dawn VIR camera. It is used to adjust the pointing to its location at specific times like the times at the beginning, middle, and end of exposure for a specific pixel, when the correct deltaT can be determined to achieve these results.
Do not use this verstion of SetImage with a deltaT unless you understand exactly what this does.
Parameters
sample Sample coordinate of the cube.
line Line coordinate of the cube.
deltaT seconds from the center exposure time
Returns
bool Returns True if the image was set successfully and False if it was not.
References Isis::AlphaCube::AlphaLine(), Isis::AlphaCube::AlphaSample(), Isis::ShapeModel::clearSurfacePoint(), Isis::CameraDetectorMap::DetectorLine(), Isis::CameraDetectorMap::DetectorSample(), Isis::CameraFocalPlaneMap::FocalPlaneX(), Isis::CameraFocalPlaneMap::FocalPlaneY(), Isis::Projection::IsSky(), Isis::Camera::p_alphaCube, Isis::Camera::p_childLine, Isis::Camera::p_childSample, Isis::Camera::p_pointComputed, Isis::CameraFocalPlaneMap::SetDetector(), Isis::CameraGroundMap::SetFocalPlane(), Isis::CameraDistortionMap::SetFocalPlane(), Isis::CameraDetectorMap::SetParent(), Isis::Target::shape(), Isis::Spice::target(), Isis::CameraDistortionMap::UndistortedFocalPlaneX(), Isis::CameraDistortionMap::UndistortedFocalPlaneY(), and Isis::CameraDistortionMap::UndistortedFocalPlaneZ().
SetLookDirection()
bool Isis::Sensor::SetLookDirection (const double v[3]) inherited
Sets the look direction of the spacecraft.
This routine will then attempt to intersect the look direction with the target. If successful you can utilize the methods which return the lat/lon, phase, incidence, etc. This routine returns false if the look direction does not intersect the target.
Parameters
v[] A look vector in camera coordinates. For example, (0,0,1) is usually the look direction out of the boresight of a camera.
Returns
bool Indicates whether the given look direction intersects the target.
References Isis::Spice::bodyRotation(), Isis::Sensor::Coordinate(), Isis::Spice::instrumentPosition(), Isis::Spice::instrumentRotation(), Isis::ShapeModel::intersectSurface(), Isis::SpiceRotation::J2000Vector(), Isis::Sensor::m_lookB, Isis::Sensor::m_newLookB, Isis::SpiceRotation::ReferenceVector(), Isis::ShapeModel::setHasIntersection(), Isis::Target::shape(), and Isis::Spice::target().
Referenced by Isis::CameraSkyMap::SetFocalPlane(), Isis::VimsGroundMap::SetFocalPlane(), Isis::VimsSkyMap::SetFocalPlane(), and Isis::Sensor::SetRightAscensionDeclination().
SetPixelPitch() [1/2]
void Isis::Camera::SetPixelPitch () protected inherited
Reads the Pixel Pitch from the instrument kernel.
References Isis::Spice::getDouble(), Isis::Spice::naifIkCode(), and Isis::toString().
Referenced by Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ClipperWacFcCamera::ClipperWacFcCamera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IdealCamera::IdealCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::LwirCamera::LwirCamera(), Isis::MarciCamera::MarciCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MiniRF::MiniRF(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::NirCamera::NirCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::ThemisVisCamera::ThemisVisCamera(), Isis::UvvisCamera::UvvisCamera(), Isis::VikingCamera::VikingCamera(), Isis::VimsCamera::VimsCamera(), and Isis::VoyagerCamera::VoyagerCamera().
SetPixelPitch() [2/2]
void Isis::Camera::SetPixelPitch (double v) protected inherited
Sets the pixel pitch.
Parameters
v Pixel Pitch
SetRightAscensionDeclination()
bool Isis::Camera::SetRightAscensionDeclination (const double ra, const double dec) virtual inherited
Sets the right ascension declination.
Parameters
ra Right ascension value
dec Declination value
Returns
bool Returns true if the declination was set successfully and false if it was not
Reimplemented in Isis::CSMCamera.
References Isis::AlphaCube::BetaLine(), Isis::AlphaCube::BetaSample(), Isis::CameraFocalPlaneMap::DetectorLine(), Isis::CameraFocalPlaneMap::DetectorSample(), Isis::CameraDistortionMap::FocalPlaneX(), Isis::CameraSkyMap::FocalPlaneX(), Isis::CameraDistortionMap::FocalPlaneY(), Isis::CameraSkyMap::FocalPlaneY(), Isis::Projection::IsSky(), Isis::Camera::p_alphaCube, Isis::Camera::p_childLine, Isis::Camera::p_childSample, Isis::Camera::p_pointComputed, Isis::CameraDetectorMap::ParentLine(), Isis::CameraDetectorMap::ParentSample(), Isis::CameraDetectorMap::SetDetector(), Isis::CameraFocalPlaneMap::SetFocalPlane(), Isis::Projection::SetGround(), Isis::CameraSkyMap::SetSky(), Isis::CameraDistortionMap::SetUndistortedFocalPlane(), Isis::Projection::SetUniversalGround(), Isis::Spice::target(), Isis::Sensor::UniversalLatitude(), Isis::Sensor::UniversalLongitude(), Isis::Projection::WorldX(), and Isis::Projection::WorldY().
Referenced by Isis::Camera::CelestialNorthClockAngle(), and Isis::Camera::RaDecRange().
SetSkyMap()
void Isis::Camera::SetSkyMap (CameraSkyMap * map) inherited
Sets the Sky Map.
This object will take ownership of the sky map pointer.
Parameters
*map Pointer to a CameraSkyMap object
Referenced by Isis::CameraSkyMap::CameraSkyMap(), and Isis::CSMSkyMap::CSMSkyMap().
setTime()
void Isis::Sensor::setTime (const iTime & time) virtual inherited
By setting the time you essential set the position of the spacecraft and body as indicated in the class Spice.
However, after this is invoked there will be no intersection point until SetLookDirection or SetUniversalGround is invoked. (Read NAIF documentation for a detailed description of ephemeris time.)
Parameters
time Ephemeris time.
Reimplemented from Isis::Spice.
References Isis::ShapeModel::clearSurfacePoint(), Isis::Spice::setTime(), Isis::Target::shape(), Isis::Spice::target(), and Isis::Spice::time().
Referenced by Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ClipperWacFcCamera::ClipperWacFcCamera(), Isis::CrismCamera::CrismCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IdealCamera::IdealCamera(), Isis::VimsGroundMap::Init(), Isis::VimsSkyMap::Init(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::Camera::LoadCache(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LwirCamera::LwirCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MiniRF::MiniRF(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NirCamera::NirCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::ThemisVisCamera::SetBand(), Isis::NewHorizonsMvicFrameCamera::SetBand(), Isis::VimsGroundMap::SetFocalPlane(), Isis::VimsSkyMap::SetFocalPlane(), Isis::PushFrameCameraDetectorMap::SetFramelet(), Isis::RadarPulseMap::SetParent(), Isis::CameraDetectorMap::SetParent(), Isis::LineScanCameraDetectorMap::SetParent(), Isis::RollingShutterCameraDetectorMap::SetParent(), Isis::VariableLineScanCameraDetectorMap::SetParent(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::UvvisCamera::UvvisCamera(), Isis::VikingCamera::VikingCamera(), and Isis::VoyagerCamera::VoyagerCamera().
SetUniversalGround() [1/4]
bool Isis::Camera::SetUniversalGround (const double latitude, const double longitude) virtual inherited
Sets the lat/lon values to get the sample/line values.
Parameters
latitude Latitude coordinate of the point
longitude Longitude coordinate of the point
Returns
bool Returns true if the Universal Ground was set successfully and false if it was not
Reimplemented in Isis::CSMCamera.
References Isis::ShapeModel::clearSurfacePoint(), Isis::Angle::Degrees, Isis::CameraGroundMap::SetGround(), Isis::Target::shape(), and Isis::Spice::target().
Referenced by Isis::ControlPointEditWidget::createControlPoint(), Isis::QnetTool::createFixedPoint(), Isis::ProjectionFactory::CreateForCube(), Isis::QnetTool::createPoint(), Isis::InterestOperator::FindCnetRef(), Isis::Chip::Load(), and Isis::UniversalGroundMap::SetUniversalGround().
SetUniversalGround() [2/4]
bool Isis::Sensor::SetUniversalGround (const double latitude, const double longitude, bool backCheck = true) inherited
This is the opposite routine for SetLookDirection.
Instead of computing a point on the target, a point is set and the look direction is computed. Other methods such as lat/lon, phase, incidence, etc. can be used if this method returns a true.
Parameters
latitude Planetocentric latitude.
longitude Positive east longitude.
backCheck If true this method will check the lat/lon point to see if it falls on the backside of the target (or beyond the horizon). If false this test will not occur. Defaults to true.
Returns
bool True if the look direction intersects the target.
References Isis::Spice::bodyRotation(), Isis::ShapeModel::clearSurfacePoint(), Isis::Sensor::Coordinate(), Isis::Angle::Degrees, Isis::Spice::instrumentPosition(), Isis::ShapeModel::intersectSurface(), Isis::Target::shape(), and Isis::Spice::target().
SetUniversalGround() [3/4]
bool Isis::Camera::SetUniversalGround (const double latitude, const double longitude, const double radius) virtual inherited
Sets the lat/lon/radius values to get the sample/line values.
Parameters
latitude Latitude coordinate of the cube
longitude Longitude coordinate of the cube
radius Radius coordinate of the cube
Returns
bool Returns True if the Universal Ground was set successfully and False if it was not
Reimplemented in Isis::CSMCamera.
References Isis::ShapeModel::clearSurfacePoint(), Isis::Angle::Degrees, Isis::Distance::Meters, Isis::CameraGroundMap::SetGround(), Isis::Target::shape(), and Isis::Spice::target().
SetUniversalGround() [4/4]
bool Isis::Sensor::SetUniversalGround (const double latitude, const double longitude, const double radius, bool backCheck = true) inherited
This overloaded method has the opposite function as SetLookDirection.
Instead of computing a point on the target, a point is set and the look direction is computed. Other methods such as lat/lon, phase, incidence, etc. can be used if this method returns a true.
Parameters
latitude Planetocentric latitude in degrees.
longitude Positive east longitude in degrees.
radius Radius in meters.
backCheck If true this method will check the lat/lon point to see if it falls on the backside of the target (or beyond the horizon). If false this test will not occur. Defaults to true.
Returns
bool True if the look direction intersects the target.
References Isis::Spice::bodyRotation(), Isis::ShapeModel::clearSurfacePoint(), Isis::Sensor::Coordinate(), Isis::Angle::Degrees, Isis::Spice::instrumentPosition(), Isis::ShapeModel::intersectSurface(), Isis::Distance::Meters, Isis::Target::shape(), and Isis::Spice::target().
ShutterOpenCloseTimes()
pair< iTime, iTime > Isis::FramingCamera::ShutterOpenCloseTimes (double time, double exposureDuration) pure virtual
Returns the shutter open and close times.
This is a pure virtual method and so must be overridden by all child classes. Child classes may call this implementation if the shutter open and close times are found the same way. Namely, the time value is the shutter open time and the exposure duration is added to get the shutter close time.
Parameters
exposureDuration Exposure duration value in seconds. Usually, this parameter is found in the image labels.
time An ephemeris time value. Usually this parameter is the StartTime or SpacecraftClockCount value from the image labels.
Returns
pair < iTime, iTime > The first value is the shutter open time and the second is the shutter close time.
Author
2011-05-03 Jeannie Walldren
Implemented in Isis::VoyagerCamera, Isis::VikingCamera, Isis::TgoCassisCamera, Isis::RosettaOsirisCamera, Isis::OsirisRexTagcamsCamera, Isis::OsirisRexOcamsCamera, Isis::NewHorizonsMvicFrameCamera, Isis::NewHorizonsLorriCamera, Isis::MsiCamera, Isis::MexHrscSrcCamera, Isis::MdisCamera, Isis::Mariner10Camera, Isis::LoMediumCamera, Isis::LoHighCamera, Isis::JunoCamera, Isis::Hyb2OncCamera, Isis::HayabusaNirsCamera, Isis::HayabusaAmicaCamera, Isis::SsiCamera, Isis::DawnFcCamera, Isis::ClipperWacFcCamera, Isis::UvvisCamera, Isis::NirCamera, Isis::LwirCamera, Isis::HiresCamera, Isis::IssWACamera, Isis::IssNACamera, and Isis::ApolloMetricCamera.
References Isis::Camera::exposureDuration(), and Isis::Spice::time().
Referenced by Isis::IssNACamera::ShutterOpenCloseTimes(), Isis::IssWACamera::ShutterOpenCloseTimes(), Isis::HiresCamera::ShutterOpenCloseTimes(), Isis::LwirCamera::ShutterOpenCloseTimes(), Isis::NirCamera::ShutterOpenCloseTimes(), Isis::UvvisCamera::ShutterOpenCloseTimes(), Isis::ClipperWacFcCamera::ShutterOpenCloseTimes(), Isis::DawnFcCamera::ShutterOpenCloseTimes(), Isis::HayabusaAmicaCamera::ShutterOpenCloseTimes(), Isis::HayabusaNirsCamera::ShutterOpenCloseTimes(), Isis::Hyb2OncCamera::ShutterOpenCloseTimes(), Isis::JunoCamera::ShutterOpenCloseTimes(), Isis::MdisCamera::ShutterOpenCloseTimes(), Isis::MexHrscSrcCamera::ShutterOpenCloseTimes(), Isis::MsiCamera::ShutterOpenCloseTimes(), Isis::NewHorizonsLorriCamera::ShutterOpenCloseTimes(), Isis::NewHorizonsMvicFrameCamera::ShutterOpenCloseTimes(), Isis::OsirisRexOcamsCamera::ShutterOpenCloseTimes(), Isis::OsirisRexTagcamsCamera::ShutterOpenCloseTimes(), Isis::RosettaOsirisCamera::ShutterOpenCloseTimes(), and Isis::TgoCassisCamera::ShutterOpenCloseTimes().
SkyMap()
CameraSkyMap * Isis::Camera::SkyMap () inherited
Returns a pointer to the CameraSkyMap object.
Returns
CameraSkyMap*
Referenced by Isis::LineScanCamera::SkyMap(), and Isis::VimsCamera::VimsCamera().
SlantDistance()
double Isis::Sensor::SlantDistance () const virtual inherited
Return the distance between the spacecraft and surface point in kmv.
Returns
double Slant distance.
Reimplemented in Isis::CSMCamera.
References Isis::SurfacePoint::GetX(), Isis::SurfacePoint::GetY(), Isis::SurfacePoint::GetZ(), Isis::Spice::instrumentBodyFixedPosition(), Isis::Displacement::kilometers(), Isis::Target::shape(), Isis::ShapeModel::surfaceIntersection(), and Isis::Spice::target().
Referenced by Isis::LineScanCameraGroundMap::FindSpacecraftDistance().
Slope()
void Isis::Camera::Slope (double & slope, bool & success) inherited
Calculates the slope at the current point by computing the angle between the local surface normal and the ellipsoid surface normal.
If there is a failure during the process, such as there not being an intersection, then success will be false and slope will not be modified.
Parameters
[out] slope The slope angle in degrees
[out] success If the slope was successfully calculated
References Isis::ShapeModel::calculateSurfaceNormal(), Isis::Camera::GetLocalNormal(), Isis::ShapeModel::hasIntersection(), Isis::ShapeModel::hasNormal(), Isis::ShapeModel::normal(), Isis::RAD2DEG, Isis::Target::shape(), and Isis::Spice::target().
SolarDistance()
double Isis::Sensor::SolarDistance () const virtual inherited
Returns the distance between the sun and surface point in AU.
Returns
double Solar distance.
Reimplemented in Isis::CSMCamera.
References Isis::SurfacePoint::GetX(), Isis::SurfacePoint::GetY(), Isis::SurfacePoint::GetZ(), Isis::Displacement::kilometers(), Isis::Target::shape(), Isis::Spice::sunPosition(), Isis::ShapeModel::surfaceIntersection(), and Isis::Spice::target().
solarLongitude()
Longitude Isis::Spice::solarLongitude () virtual inherited
Returns the solar longitude.
Returns
double The Solar Longitude
Referenced by Isis::Cube::attachSpiceFromIsd().
SpacecraftAltitude()
double Isis::Sensor::SpacecraftAltitude () inherited
Returns the distance from the spacecraft to the subspacecraft point in km.
It uses the ellipsoid, not the shape model.
Returns
double Spacecraft altitude.
References Isis::Spice::instrumentPosition(), Isis::Distance::kilometers(), Isis::Sensor::LocalRadius(), and Isis::Spice::subSpacecraftPoint().
Referenced by Isis::CrismCamera::CrismCamera(), Isis::Camera::LoadCache(), and Isis::MiniRF::MiniRF().
SpacecraftAzimuth()
double Isis::Camera::SpacecraftAzimuth () inherited
Return the Spacecraft Azimuth.
Returns
double Spacecraft Azimuth
References Isis::Spice::subSpacecraftPoint().
spacecraftNameLong()
QString Isis::Camera::spacecraftNameLong () const virtual inherited
This method returns the full spacecraft name.
Returns
QString
Implements Isis::Sensor.
Reimplemented in Isis::IdealCamera.
References Isis::Camera::m_spacecraftNameLong.
Referenced by Isis::GuiCamera::GuiCamera().
spacecraftNameShort()
QString Isis::Camera::spacecraftNameShort () const virtual inherited
This method returns the shortened spacecraft name.
Returns
QString
Implements Isis::Sensor.
Reimplemented in Isis::IdealCamera.
References Isis::Camera::m_spacecraftNameShort.
Referenced by Isis::GuiCamera::GuiCamera().
SpacecraftSurfaceVector()
void Isis::Sensor::SpacecraftSurfaceVector (double scSurfaceVector[3]) const inherited
Sets the vector between the spacecraft and surface point in body-fixed.
Parameters
scSurfaceVector The direction vector from the observer to the surface intersection.
Author
2011-12-20 Tracie Sucharski
References Isis::Sensor::m_lookB.
SpkCenterId()
int Isis::Camera::SpkCenterId () const virtual inherited
Provides the center of motion body for SPK NAIF kernel.
This virtual method may need to be implemented in each camera model providing the NAIF integer code for the center of motion of the object identified by the SpkTargetId() code. This is typically the targeted body for a particular image observation, but may be unique depending upon the design of the SPK mission kernels.
This value can be easily determined by using the NAIF spacit application that sumarizes binary kernels on the SPK kernel used for a particular instrument on a spacecraft. spacit will additionally require a leap seconds kernel (LSK). For example, the output of the MESSENGER SPK camera supporting the MDIS camera below indicates it is Venus.
Segment ID     : msgr_20050903_20061125_recon002.nio
Target Body    : Body -236, MESSENGER
Center Body    : Body 2, VENUS BARYCENTER
Reference frame: Frame 1, J2000
SPK Data Type  : Type 1
Description : Modified Difference Array
UTC Start Time : 2006 OCT 16 19:25:41.111
UTC Stop Time  : 2006 OCT 31 22:14:24.040
ET Start Time  : 2006 OCT 16 19:26:46.293
ET Stop time   : 2006 OCT 31 22:15:29.222
The SpkCenterId value is found in the "Center Body" entry (2). The center of motion is most likely the targeted body for the image and this is provided by the naifBodyCode() method (in the Spice class). If this is not consistently the case for a particular mission, then camera models will need to reimplement this method.
Returns
int NAIF code for SPK center of motion body for an instrument
Reimplemented in Isis::IdealCamera, and Isis::CSMCamera.
References Isis::Spice::naifBodyCode().
SpkReferenceId()
virtual int Isis::Camera::SpkReferenceId () const pure virtual inherited
Provides reference frame for instruments SPK NAIF kernel.
This pure virtual method must be implemented in each camera model providing the reference frame NAIF ID code found in the mission SPK kernel. This is typically J2000, but may be relative to other frames.
This value can be easily determined by using the NAIF spacit application that sumarizes binary kernels on the SPK kernel used for a particular instrument on a spacecraft. spacit will additionally require a leap seconds kernel (LSK). For example, the output of the MESSENGER SPK camera supporting the MDIS camera below indicates it is indeed the J2000 reference frame:
Segment ID     : msgr_20050903_20061125_recon002.nio
Target Body    : Body -236, MESSENGER
Center Body    : Body 2, VENUS BARYCENTER
Reference frame: Frame 1, J2000
SPK Data Type  : Type 1
Description : Modified Difference Array
UTC Start Time : 2006 OCT 16 19:25:41.111
UTC Stop Time  : 2006 OCT 31 22:14:24.040
ET Start Time  : 2006 OCT 16 19:26:46.293
ET Stop time   : 2006 OCT 31 22:15:29.222
The SpkReferenceId value is found in the "Reference frame" entry (1).
Returns
int NAIF code for SPK reference frame for an instrument
Implemented in Isis::VoyagerCamera, Isis::VikingCamera, Isis::TgoCassisCamera, Isis::RosettaVirtisCamera, Isis::RosettaOsirisCamera, Isis::OsirisRexTagcamsCamera, Isis::OsirisRexOcamsCamera, Isis::ThemisVisCamera, Isis::ThemisIrCamera, Isis::NewHorizonsMvicTdiCamera, Isis::NewHorizonsMvicFrameCamera, Isis::NewHorizonsLorriCamera, Isis::NewHorizonsLeisaCamera, Isis::MsiCamera, Isis::MarciCamera, Isis::HiriseCamera, Isis::CTXCamera, Isis::CrismCamera, Isis::MocWideAngleCamera, Isis::MocNarrowAngleCamera, Isis::MexHrscSrcCamera, Isis::HrscCamera, Isis::MdisCamera, Isis::Mariner10Camera, Isis::MiniRF, Isis::LroWideAngleCamera, Isis::LroNarrowAngleCamera, Isis::LoMediumCamera, Isis::LoHighCamera, Isis::KaguyaTcCamera, Isis::KaguyaMiCamera, Isis::JunoCamera, Isis::Hyb2OncCamera, Isis::HayabusaNirsCamera, Isis::HayabusaAmicaCamera, Isis::SsiCamera, Isis::DawnVirCamera, Isis::DawnFcCamera, Isis::ClipperWacFcCamera, Isis::ClipperPushBroomCamera, Isis::ClipperNacRollingShutterCamera, Isis::UvvisCamera, Isis::NirCamera, Isis::LwirCamera, Isis::HiresCamera, Isis::Chandrayaan1M3Camera, Isis::VimsCamera, Isis::IssWACamera, Isis::IssNACamera, Isis::IdealCamera, Isis::CSMCamera, Isis::ApolloPanoramicCamera, and Isis::ApolloMetricCamera.
SpkTargetId()
int Isis::Camera::SpkTargetId () const virtual inherited
Provides target code for instruments SPK NAIF kernel.
This virtual method may need to be implemented in each camera model providing the target NAIF ID code found in the mission SPK kernel. This is typically the spacecraft ID code.
This value can be easily determined by using the NAIF spacit application that sumarizes binary kernels on the SPK kernel used for a particular instrument on a spacecraft. spacit will additionally require a leap seconds kernel (LSK). For example, the output of the MESSENGER SPK camera supporting the MDIS camera below indicates it is indeed the MESSENGER spacecraft:
Segment ID     : msgr_20050903_20061125_recon002.nio
Target Body    : Body -236, MESSENGER
Center Body    : Body 2, VENUS BARYCENTER
Reference frame: Frame 1, J2000
SPK Data Type  : Type 1
Description : Modified Difference Array
UTC Start Time : 2006 OCT 16 19:25:41.111
UTC Stop Time  : 2006 OCT 31 22:14:24.040
ET Start Time  : 2006 OCT 16 19:26:46.293
ET Stop time   : 2006 OCT 31 22:15:29.222
The SpkTargetId value is found in the "Target Body" entry (-236).
For most cases, this is the NAIF SPK code returned by the naifSpkCode() method (in the Spice class). Some instrument camera models may need to override this method if this is not case.
Returns
int NAIF code for the SPK target for an instrument
Reimplemented in Isis::VoyagerCamera, Isis::VikingCamera, Isis::TgoCassisCamera, Isis::MdisCamera, Isis::MiniRF, Isis::JunoCamera, Isis::IdealCamera, and Isis::ApolloMetricCamera.
References Isis::Spice::naifSpkCode().
StartEndEphemerisTimes()
pair< double, double > Isis::Camera::StartEndEphemerisTimes () inherited
Calculates the start and end ephemeris times.
These times are found by looping through the bands and finding the ephemeris times for the upper left and bottom right pixels in the image. The start time (shutter open time) is the minimum value of those ephemeris times. The end time (shutter close time) is the maximum value of those ephemeris times. This method must be called before a call to the Spice::createCache() method. It is called in the LoadCache() method.
Returns
pair<double, double> A pair containing the start and end ephemeris times
Exceptions
iException::Programmer - "Unable to find time range for the spice kernels."
See also
createCache()
LoadCache()
Author
2011-02-02 Jeannie Walldren
References _FILEINFO_, Isis::Camera::Bands(), Isis::AlphaCube::BetaLines(), Isis::AlphaCube::BetaSamples(), Isis::iTime::Et(), Isis::Camera::p_alphaCube, Isis::IException::Programmer, Isis::Camera::SetBand(), Isis::Camera::SetImage(), and Isis::Spice::time().
Referenced by Isis::Camera::LoadCache().
storeResult()
void Isis::Spice::storeResult (QString name, SpiceValueType type, QVariant value) protected inherited
References Isis::EndianSwapper::Double().
storeValue()
void Isis::Spice::storeValue (QString key, int index, SpiceValueType type, QVariant value) protected inherited
References _FILEINFO_, Isis::PvlKeyword::addValue(), Isis::PvlKeyword::size(), and Isis::toString().
Referenced by Isis::IdealCamera::IdealCamera().
subSolarPoint()
void Isis::Spice::subSolarPoint (double & lat, double & lon) virtual inherited
Returns the sub-solar latitude/longitude in universal coordinates (0-360 positive east, ocentric)
Parameters
lat Sub-solar latitude
lon Sub-solar longitude
See also
setTime()
Exceptions
Isis::IException::Programmer - "You must call SetTime first."
Reimplemented in Isis::CSMCamera.
References _FILEINFO_, and Isis::PI.
Referenced by Isis::Sensor::LocalSolarTime(), and Isis::Camera::SunAzimuth().
subSpacecraftPoint()
void Isis::Spice::subSpacecraftPoint (double & lat, double & lon) virtual inherited
Returns the sub-spacecraft latitude/longitude in universal coordinates (0-360 positive east, ocentric)
Parameters
lat Sub-spacecraft latitude
lon Sub-spacecraft longitude
See also
setTime()
Exceptions
Isis::IException::Programmer - "You must call SetTime first."
Reimplemented in Isis::CSMCamera.
References _FILEINFO_, and Isis::PI.
Referenced by Isis::Sensor::SpacecraftAltitude(), and Isis::Camera::SpacecraftAzimuth().
SunAzimuth()
double Isis::Camera::SunAzimuth () inherited
Returns the Sun Azimuth.
Returns
double Sun Azimuth
References Isis::Spice::subSolarPoint().
Referenced by Isis::SunShadowTool::mouseButtonPress().
sunPosition() [1/2]
SpicePosition * Isis::Spice::sunPosition () const virtual inherited
Accessor method for the sun position.
Returns
iTime Sun position for the image.
Author
Steven Lambright
Reimplemented in Isis::CSMCamera.
Referenced by Isis::Sensor::SolarDistance().
sunPosition() [2/2]
void Isis::Spice::sunPosition (double p[3]) const virtual inherited
Fills the input vector with sun position information, in either body-fixed or J2000 reference frame and km units.
Parameters
p[] Sun position
See also
setTime()
Reimplemented in Isis::CSMCamera.
References _FILEINFO_.
Referenced by Isis::Cube::attachSpiceFromIsd().
sunToBodyDist()
double Isis::Spice::sunToBodyDist () const virtual inherited
target()
Target * Isis::Spice::target () const virtual inherited
Returns a pointer to the target object.
Returns
string
Referenced by Isis::Camera::BasicMapping(), Isis::Camera::basicRingMapping(), Isis::Sensor::Coordinate(), Isis::CSMCamera::EmissionAngle(), Isis::Sensor::EmissionAngle(), Isis::Sensor::GetLatitude(), Isis::Camera::GetLocalNormal(), Isis::Sensor::GetLongitude(), Isis::Sensor::GetSurfacePoint(), Isis::UniversalGroundMap::GroundRange(), Isis::Sensor::HasSurfaceIntersection(), Isis::Sensor::IgnoreElevationModel(), Isis::CSMCamera::IncidenceAngle(), Isis::Sensor::IncidenceAngle(), Isis::Camera::LoadCache(), Isis::Sensor::LocalRadius(), Isis::FindTool::mouseButtonRelease(), Isis::Camera::NorthAzimuth(), Isis::CSMCamera::PhaseAngle(), Isis::VimsGroundMap::SetGround(), Isis::RadarGroundMap::SetGround(), Isis::Sensor::SetGround(), Isis::Camera::SetGround(), Isis::CSMCamera::SetGround(), Isis::Camera::SetImage(), Isis::CSMCamera::SetImage(), Isis::Sensor::SetLookDirection(), Isis::CSMCamera::SetLookDirection(), Isis::Camera::SetRightAscensionDeclination(), Isis::CSMCamera::setTarget(), Isis::Sensor::setTime(), Isis::Camera::SetUniversalGround(), Isis::Sensor::SetUniversalGround(), Isis::Sensor::SlantDistance(), Isis::Camera::Slope(), and Isis::Sensor::SolarDistance().
targetCenterDistance()
double Isis::Spice::targetCenterDistance () const virtual inherited
Calculates and returns the distance from the spacecraft to the target center.
Returns
double Distance to the center of the target from the spacecraft
Reimplemented in Isis::CSMCamera.
targetName()
QString Isis::Spice::targetName () const inherited
Returns the QString name of the target.
Returns
QString
References Isis::Target::name().
time()
iTime Isis::Spice::time () const virtual inherited
Returns the ephemeris time in seconds which was used to obtain the spacecraft and sun positions.
Returns
iTime the currently set ephemeris time
Exceptions
IException::Programmer "Unable to retrieve the time Spice::setTime must be called first."
References _FILEINFO_.
Referenced by Isis::LineScanCameraGroundMap::FindFocalPlane(), Isis::HiresCamera::HiresCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LwirCamera::LwirCamera(), Isis::NewHorizonsMvicFrameCamera::SetBand(), Isis::LineScanCameraDetectorMap::SetDetector(), Isis::RadarPulseMap::SetDetector(), Isis::VariableLineScanCameraDetectorMap::SetDetector(), Isis::RadarSlantRangeMap::SetFocalPlane(), Isis::CameraDetectorMap::SetParent(), Isis::RollingShutterCameraDetectorMap::SetParent(), Isis::Sensor::setTime(), Isis::RadarSlantRangeMap::SetUndistortedFocalPlane(), Isis::ApolloMetricCamera::ShutterOpenCloseTimes(), Isis::IssNACamera::ShutterOpenCloseTimes(), Isis::IssWACamera::ShutterOpenCloseTimes(), Isis::HiresCamera::ShutterOpenCloseTimes(), Isis::LwirCamera::ShutterOpenCloseTimes(), Isis::NirCamera::ShutterOpenCloseTimes(), Isis::UvvisCamera::ShutterOpenCloseTimes(), Isis::ClipperWacFcCamera::ShutterOpenCloseTimes(), Isis::DawnFcCamera::ShutterOpenCloseTimes(), Isis::SsiCamera::ShutterOpenCloseTimes(), Isis::HayabusaAmicaCamera::ShutterOpenCloseTimes(), Isis::HayabusaNirsCamera::ShutterOpenCloseTimes(), Isis::Hyb2OncCamera::ShutterOpenCloseTimes(), Isis::JunoCamera::ShutterOpenCloseTimes(), Isis::LoHighCamera::ShutterOpenCloseTimes(), Isis::LoMediumCamera::ShutterOpenCloseTimes(), Isis::Mariner10Camera::ShutterOpenCloseTimes(), Isis::MdisCamera::ShutterOpenCloseTimes(), Isis::MexHrscSrcCamera::ShutterOpenCloseTimes(), Isis::MsiCamera::ShutterOpenCloseTimes(), Isis::NewHorizonsLorriCamera::ShutterOpenCloseTimes(), Isis::NewHorizonsMvicFrameCamera::ShutterOpenCloseTimes(), Isis::OsirisRexOcamsCamera::ShutterOpenCloseTimes(), Isis::OsirisRexTagcamsCamera::ShutterOpenCloseTimes(), Isis::RosettaOsirisCamera::ShutterOpenCloseTimes(), Isis::TgoCassisCamera::ShutterOpenCloseTimes(), Isis::VikingCamera::ShutterOpenCloseTimes(), Isis::VoyagerCamera::ShutterOpenCloseTimes(), ShutterOpenCloseTimes(), Isis::Camera::StartEndEphemerisTimes(), and Isis::UvvisCamera::UvvisCamera().
UniversalLatitude()
double Isis::Sensor::UniversalLatitude () const virtual inherited
Returns the planetocentric latitude, in degrees, at the surface intersection point in the body fixed coordinate system.
Returns
double Universal latitude, in degrees.
References Isis::Angle::degrees(), and Isis::Sensor::GetLatitude().
Referenced by Isis::CameraStatistics::addStats(), Isis::ProjectionFactory::CreateForCube(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::QnetCubeDistanceFilter::filter(), Isis::InterestOperator::FindCnetRef(), Isis::Cube::latLonRange(), Isis::Chip::Load(), Isis::Camera::NorthAzimuth(), Isis::LatLonGridTool::paintViewport(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::Camera::SetRightAscensionDeclination(), and Isis::UniversalGroundMap::UniversalLatitude().
UniversalLongitude()
double Isis::Sensor::UniversalLongitude () const virtual inherited
Returns the positive east, 0-360 domain longitude, in degrees, at the surface intersection point in the body fixed coordinate system.
Returns
double Universal longitude, in degrees.
References Isis::Angle::degrees(), and Isis::Sensor::GetLongitude().
Referenced by Isis::CameraStatistics::addStats(), Isis::ProjectionFactory::CreateForCube(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::QnetCubeDistanceFilter::filter(), Isis::InterestOperator::FindCnetRef(), Isis::Cube::latLonRange(), Isis::Chip::Load(), Isis::Sensor::LocalSolarTime(), Isis::LatLonGridTool::paintViewport(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::Camera::SetRightAscensionDeclination(), and Isis::UniversalGroundMap::UniversalLongitude().
Member Data Documentation
m_BJ
SpiceDouble Isis::Spice::m_BJ[3][3] protected inherited
This contains the transformation matrix from J2000 (J) to Body fixed (B).
Recall that the transpose of this matrix JB will convert from body-fixed to J2000. It is left in protected space so that conversions between double and SpiceDouble do not have to occur in inheriting classes.
m_et
iTime* Isis::Spice::m_et protected inherited
Ephemeris time (read NAIF documentation for a detailed description)
Referenced by Isis::CSMCamera::SetGround(), and Isis::CSMCamera::SetImage().
m_instrumentId
QString Isis::Camera::m_instrumentId protected inherited
The InstrumentId as it appears on the cube.
Referenced by Isis::Camera::Camera(), and Isis::Camera::instrumentId().
m_instrumentNameLong
QString Isis::Camera::m_instrumentNameLong protected inherited
Full instrument name.
Referenced by Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Camera::Camera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ClipperWacFcCamera::ClipperWacFcCamera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::Camera::instrumentNameLong(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::LwirCamera::LwirCamera(), Isis::MarciCamera::MarciCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MiniRF::MiniRF(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::NirCamera::NirCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::ThemisVisCamera::ThemisVisCamera(), Isis::UvvisCamera::UvvisCamera(), Isis::VikingCamera::VikingCamera(), Isis::VimsCamera::VimsCamera(), and Isis::VoyagerCamera::VoyagerCamera().
m_instrumentNameShort
QString Isis::Camera::m_instrumentNameShort protected inherited
Shortened instrument name.
Referenced by Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Camera::Camera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ClipperWacFcCamera::ClipperWacFcCamera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::Camera::instrumentNameShort(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::LwirCamera::LwirCamera(), Isis::MarciCamera::MarciCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MiniRF::MiniRF(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::NirCamera::NirCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::ThemisVisCamera::ThemisVisCamera(), Isis::UvvisCamera::UvvisCamera(), Isis::VikingCamera::VikingCamera(), Isis::VimsCamera::VimsCamera(), and Isis::VoyagerCamera::VoyagerCamera().
m_lookB
SpiceDouble Isis::Sensor::m_lookB[3] protected inherited
Look direction in body fixed.
Referenced by Isis::Sensor::lookDirectionBodyFixed(), Isis::CSMCamera::SetGround(), Isis::Sensor::SetLookDirection(), Isis::CSMCamera::SetLookDirection(), and Isis::Sensor::SpacecraftSurfaceVector().
m_newLookB
bool Isis::Sensor::m_newLookB protected inherited
flag to indicate we need to recompute ra/dec
Referenced by Isis::Sensor::Declination(), Isis::Sensor::RightAscension(), Isis::Sensor::Sensor(), Isis::CSMCamera::SetGround(), Isis::Sensor::SetLookDirection(), and Isis::CSMCamera::SetLookDirection().
m_solarLongitude
Longitude* Isis::Spice::m_solarLongitude protected inherited
Body rotation solar longitude value.
m_spacecraftNameLong
QString Isis::Camera::m_spacecraftNameLong protected inherited
Full spacecraft name.
Referenced by Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Camera::Camera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ClipperWacFcCamera::ClipperWacFcCamera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::LwirCamera::LwirCamera(), Isis::MarciCamera::MarciCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MiniRF::MiniRF(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::NirCamera::NirCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::Camera::spacecraftNameLong(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::ThemisVisCamera::ThemisVisCamera(), Isis::UvvisCamera::UvvisCamera(), Isis::VikingCamera::VikingCamera(), Isis::VimsCamera::VimsCamera(), and Isis::VoyagerCamera::VoyagerCamera().
m_spacecraftNameShort
QString Isis::Camera::m_spacecraftNameShort protected inherited
Shortened spacecraft name.
Referenced by Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Camera::Camera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ClipperWacFcCamera::ClipperWacFcCamera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::LwirCamera::LwirCamera(), Isis::MarciCamera::MarciCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MiniRF::MiniRF(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::NirCamera::NirCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::Camera::spacecraftNameShort(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::ThemisVisCamera::ThemisVisCamera(), Isis::UvvisCamera::UvvisCamera(), Isis::VikingCamera::VikingCamera(), Isis::VimsCamera::VimsCamera(), and Isis::VoyagerCamera::VoyagerCamera().
m_target
Target* Isis::Spice::m_target protected inherited
Target of the observation.
Referenced by Isis::CSMCamera::setTarget().
m_uB
SpiceDouble Isis::Spice::m_uB[3] protected inherited
This contains the sun position (u) in the bodyfixed reference frame (B).
It is left protected so that conversions between double and SpiceDouble do not have to occur in inheriting classes. Units are km
Referenced by Isis::Sensor::IncidenceAngle(), Isis::Camera::LocalPhotometricAngles(), and Isis::Sensor::PhaseAngle().
p_alphaCube
AlphaCube* Isis::Camera::p_alphaCube protected inherited
A pointer to the AlphaCube.
Referenced by Isis::Camera::CacheSize(), Isis::Camera::Camera(), Isis::Camera::LoadCache(), Isis::CSMCamera::parentLine(), Isis::Camera::ParentLines(), Isis::CSMCamera::parentSample(), Isis::Camera::ParentSamples(), Isis::CSMCamera::SetGround(), Isis::Camera::SetImage(), Isis::CSMCamera::SetImage(), Isis::Camera::SetRightAscensionDeclination(), Isis::Camera::StartEndEphemerisTimes(), and Isis::Camera::~Camera().
p_childLine
double Isis::Camera::p_childLine protected inherited
Line value for child.
Referenced by Isis::CSMCamera::Declination(), Isis::Camera::exposureDuration(), Isis::Camera::Line(), Isis::CSMCamera::RightAscension(), Isis::CSMCamera::SetGround(), Isis::Camera::SetImage(), Isis::CSMCamera::SetImage(), and Isis::Camera::SetRightAscensionDeclination().
p_childSample
double Isis::Camera::p_childSample protected inherited
Sample value for child.
Referenced by Isis::CSMCamera::Declination(), Isis::Camera::exposureDuration(), Isis::CSMCamera::RightAscension(), Isis::Camera::Sample(), Isis::CSMCamera::SetGround(), Isis::Camera::SetImage(), Isis::CSMCamera::SetImage(), and Isis::Camera::SetRightAscensionDeclination().
p_pointComputed
bool Isis::Camera::p_pointComputed protected inherited
Flag showing if Sample/Line has been computed.
Referenced by Isis::Camera::Camera(), Isis::Camera::GetLocalNormal(), Isis::Camera::RaDecRange(), Isis::Camera::RaDecResolution(), Isis::CSMCamera::SetGround(), Isis::Camera::SetImage(), Isis::CSMCamera::SetImage(), and Isis::Camera::SetRightAscensionDeclination().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/FramingCamera/FramingCamera.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/FramingCamera/FramingCamera.cpp