Isis Developer Reference: Isis::PlotCurve Class Reference
Isis::PlotCurve Class Reference
#include <PlotCurve.h>
Public Types
enum Units {
Unknown , Band , CubeDN , Elevation ,
Percentage , PixelNumber , Meters , Kilometers ,
Wavelength
}
These are all the possible units for the x or y data in a plot curve.
Public Member Functions
PlotCurve (Units xUnits, Units yUnits)
Constructs and instance of a PlotCurve with some default properties.
~PlotCurve ()
void attachMarkers ()
After attaching this curve to a plot, due to an inheritance/implementation complication with qwt the markers will remain detached until they are recreated.
QColor color () const
This method returns the color of the curve.
QwtSymbol * markerSymbol () const
This method returns the shape of the markers.
Units xUnits () const
Get the units of the x-axis double data.
Units yUnits () const
Get the units of the y-axis double data.
void setColor (const QColor &color)
Set the color of this curve and it's markers.
void setData (QwtSeriesData< QPointF > *data)
This method sets the data for the curve, then sets the value for the markers associated with the curve.
void setPen (const QPen &pen)
Sets the plot pen to the passed-in pen.
void setMarkerSymbol (QwtSymbol::Style style)
This method sets the shape of the markers.
void setMarkerVisible (bool visible)
This method sets the visibility states of the markers at each value point.
Protected Member Functions
QByteArray fromByteArray (const QByteArray &classData)
Construct the plot curve given the past results of toByteArray(...).
QByteArray toByteArray () const
Detailed Description
Author
????-??-?? Unknown
Member Enumeration Documentation
Units
enum Isis::PlotCurve::Units
These are all the possible units for the x or y data in a plot curve.
We want these in order to have type checking when moving curves around - it's theoretically possible to even utilize the right y axis automatically when you put mismatched plot curve y data into the same plot. All of this and more requires knowing your data's units.
Enumerator
Unknown
The data units are not yet known.
Please avoid using this if at all possible.
Band
The data is a band number.
CubeDN
The data is a Cube DN value.
Elevation
The data is an elevation (in meters).
Percentage
The data is a percentage (0-100).
PixelNumber
The data is a pixel #.
For example, it's the nth pixel along a line.
Meters
The data is in meters.
For example, it's the nth meter along a line.
Kilometers
The data is in kilometers.
For example, it's the nth kilometer along a line.
Wavelength
The data is a wavelength.
This is usually associated with a band and comes from the band bin group.
Constructor & Destructor Documentation
PlotCurve()
Isis::PlotCurve::PlotCurve (Units xUnits, Units yUnits)
Constructs and instance of a PlotCurve with some default properties.
References xUnits(), and yUnits().
~PlotCurve()
Isis::PlotCurve::~PlotCurve ()
Member Function Documentation
attachMarkers()
void Isis::PlotCurve::attachMarkers ()
After attaching this curve to a plot, due to an inheritance/implementation complication with qwt the markers will remain detached until they are recreated.
This forces the markers to be updated immediately.
Please always call this method after attaching this curve to a plot.
Referenced by Isis::PlotWindow::add().
color()
QColor Isis::PlotCurve::color () const
This method returns the color of the curve.
Returns
QColor
Referenced by Isis::PlotWindowBestFitDialog::createBestFitLine(), Isis::CubePlotCurve::paint(), Isis::PlotWindow::plotCurves(), and setColor().
fromByteArray()
QByteArray Isis::PlotCurve::fromByteArray (const QByteArray & classData) protected
Construct the plot curve given the past results of toByteArray(...).
This is used for copy/paste and drag/drop.
Returns
The unconsumed part of the byte array.
References _FILEINFO_, Isis::IException::Programmer, Isis::ReadWrite, setColor(), setData(), and setPen().
Referenced by Isis::CubePlotCurve::CubePlotCurve().
markerSymbol()
QwtSymbol * Isis::PlotCurve::markerSymbol () const
This method returns the shape of the markers.
Returns
QwtSymbol *
setColor()
void Isis::PlotCurve::setColor (const QColor & color)
Set the color of this curve and it's markers.
This color will override the pen's color always.
Parameters
color The color of this curve.
References color(), and setPen().
Referenced by Isis::PlotWindowBestFitDialog::createBestFitLine(), Isis::AbstractPlotTool::createCurve(), and fromByteArray().
setData()
void Isis::PlotCurve::setData (QwtSeriesData< QPointF > * data)
This method sets the data for the curve, then sets the value for the markers associated with the curve.
Parameters
data
Referenced by Isis::PlotWindowBestFitDialog::createBestFitLine(), and fromByteArray().
setMarkerSymbol()
void Isis::PlotCurve::setMarkerSymbol (QwtSymbol::Style style)
This method sets the shape of the markers.
Parameters
style
Referenced by Isis::PlotWindowBestFitDialog::createBestFitLine().
setMarkerVisible()
void Isis::PlotCurve::setMarkerVisible (bool visible)
This method sets the visibility states of the markers at each value point.
Parameters
visible True to show markers, false to hide
setPen()
void Isis::PlotCurve::setPen (const QPen & pen)
Sets the plot pen to the passed-in pen.
Parameters
pen
Referenced by Isis::PlotWindowBestFitDialog::createBestFitLine(), Isis::AbstractPlotTool::createCurve(), fromByteArray(), and setColor().
toByteArray()
QByteArray Isis::PlotCurve::toByteArray () const protected
References Isis::ReadWrite.
xUnits()
PlotCurve::Units Isis::PlotCurve::xUnits () const
Get the units of the x-axis double data.
Returns
The units of the x-axis data
Referenced by Isis::PlotWindow::canAdd(), Isis::PlotWindowBestFitDialog::createBestFitLine(), and PlotCurve().
yUnits()
PlotCurve::Units Isis::PlotCurve::yUnits () const
Get the units of the y-axis double data.
Returns
The units of the y-axis data
Referenced by Isis::PlotWindow::canAdd(), Isis::PlotWindowBestFitDialog::createBestFitLine(), and PlotCurve().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/PlotCurve/PlotCurve.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/PlotCurve/PlotCurve.cpp