Isis Developer Reference: Isis::MosaicGridTool Class Reference
Isis::MosaicGridTool Class Reference
This controls the 'Grid' abilities in the MosaicSceneWidget.
#include <MosaicGridTool.h>
Public Types
enum GridExtentSource { Map , Cubes , Manual }
Public Slots
void autoGrid (bool draw)
Calculates the lat/lon increments from the bounding rectangle of the open cubes.
void clearGrid ()
Clears the grid from the scene.
void configure ()
Give a configuration dialog for the options available in this tool.
void drawGrid ()
Creates the GridGraphicsItem that will draw the grid.
void drawGrid (bool draw)
Determines whether the grid should be drawn or not.
void onCubesChanged ()
Determines whether or not the bounding rectangle was changed by the addition or removal of cubes.
void onToolOpen (bool check)
Checks both checkboxes when the tool is first opened.
void onProjectionChanged ()
void activate (bool)
Activates the tool.
Signals
void boundingRectChanged ()
void activated (bool)
Public Member Functions
MosaicGridTool (MosaicSceneWidget *)
MosaicGridTool constructor.
void addToMenu (QMenu *menu)
Adds the pan action to the given menu.
bool autoGridCheckBox ()
True if checked.
Latitude baseLat ()
The base latitude.
Longitude baseLon ()
The base longitude.
int density ()
The density or resolution of the grid.
Angle latInc ()
The angle of the latitude increment.
GridExtentSource latExtents ()
The extent type (Map, Cubes, Manual) for the latitude.
QString latType ()
The latitude type (planetocentric/planetographic) of the projection of the scene.
QString lonDomain ()
The longitude domain of the projection of the scene.
GridExtentSource lonExtents ()
The extent type (Map, Cubes, Manual) for the longitude.
Angle lonInc ()
The angle of the longitude increment.
Latitude maxLat ()
The maximum latitude used to determine the grid's extents and increments.
Longitude maxLon ()
The maximum longitude used to determine the grid's extents and increments.
Latitude minLat ()
The minimum latitude used to determine the grid's extents and increments.
Longitude minLon ()
The minimum longitude used to determine the grid's extents and increments.
MosaicSceneWidget * sceneWidget ()
bool showGrid ()
True if grid is displayed.
void setAutoGridCheckBox (bool checked)
Modify the check state of the checkbox.
void setBaseLat (Latitude baseLat)
Modify the base latitude.
void setBaseLon (Longitude baseLon)
Modify the base longitude.
void setDensity (int density)
Modify the density.
void setLatExtents (GridExtentSource source, Latitude minLat, Latitude maxLat)
Set the maximum and minimum latitude of the grid.
void setLatInc (Angle latInc)
Modify the latitude increment.
void setLonExtents (GridExtentSource source, Longitude minLon, Longitude maxLon)
Set the maximum and minimum longitude of the grid.
void setLonInc (Angle lonInc)
Modify the longitude increment.
void setShowGrid (bool show)
Modify the check state of the checkbox.
void fromPvl (const PvlObject &obj)
Read the tool information form a pvl object.
QString projectPvlObjectName () const
An accessor for the name of the Pvl object that the tool's information is stored in.
PvlObject toPvl () const
Store the tool information in a pvl object.
Longitude domainMinLon ()
Longitude domainMaxLon ()
bool isActive () const
Returns the activeness of this toool.
QPixmap getIcon (QString iconName) const
returns the path to the icon directory.
virtual void addTo (QMenu *menu)
virtual void addTo (ToolPad *toolPad)
virtual void addTo (QToolBar *toolBar)
virtual QList< QAction * > getViewActions ()
Protected Slots
virtual void updateTool ()
Protected Member Functions
QWidget * createToolBarWidget ()
Creates the widget to add to the tool bar.
QAction * getPrimaryAction ()
Adds the action to the toolpad.
QWidget * getToolBarWidget ()
Creates the Grid Toolbar Widget.
virtual void mouseEnter ()
virtual void mouseMove (QPointF)
virtual void mouseLeave ()
virtual void mouseDoubleClick (QPointF)
virtual void mouseButtonPress (QPointF, Qt::MouseButton s)
virtual void mouseButtonRelease (QPointF, Qt::MouseButton s)
virtual void mouseWheel (QPointF, int delta)
virtual void rubberBandComplete (QRectF r, Qt::MouseButton s)
void toolBarDestroyed (QObject *obj)
MosaicSceneWidget * getWidget ()
Detailed Description
This controls the 'Grid' abilities in the MosaicSceneWidget.
Author
????-??-?? Stacy Alley
Member Enumeration Documentation
GridExtentSource
enum Isis::MosaicGridTool::GridExtentSource
Enumerator
Map
The grid will be drawn using the extents from the map projection.
Cubes
The grid will be drawn using the extents from the bounding rectangle of the open cubes.
Manual
The grid will be drawn using the extents that the user specifies.
Constructor & Destructor Documentation
MosaicGridTool()
Isis::MosaicGridTool::MosaicGridTool (MosaicSceneWidget * scene)
MosaicGridTool constructor.
Parameters
parent
References Cubes, Isis::MosaicSceneWidget::cubesBoundingRect(), Isis::Angle::Degrees, domainMaxLon(), domainMinLon(), Isis::MosaicTool::getWidget(), and onProjectionChanged().
Member Function Documentation
activate
void Isis::MosaicTool::activate (bool on) slot inherited
Activates the tool.
Parameters
on
References Isis::MosaicTool::activated().
Referenced by Isis::MosaicTool::addTo().
activated
void Isis::MosaicTool::activated (bool) signal inherited
Referenced by Isis::MosaicTool::activate(), getToolBarWidget(), and Isis::MosaicTool::MosaicTool().
addTo() [1/3]
virtual void Isis::MosaicTool::addTo (QMenu * menu) inline virtual inherited
Referenced by Isis::MosaicSceneWidget::addTo(), Isis::MosaicSceneWidget::getControlNetHelp(), and Isis::MosaicSceneWidget::getGridHelp().
addTo() [2/3]
void Isis::MosaicTool::addTo (QToolBar * toolBar) virtual inherited
References Isis::MosaicTool::getToolBarWidget(), and Isis::MosaicTool::toolBarDestroyed().
addTo() [3/3]
void Isis::MosaicTool::addTo (ToolPad * toolPad) virtual inherited
References Isis::MosaicTool::activate(), Isis::ToolPad::addAction(), and Isis::MosaicTool::getPrimaryAction().
addToMenu()
void Isis::MosaicGridTool::addToMenu (QMenu * menu)
Adds the pan action to the given menu.
Parameters
menu
autoGrid
void Isis::MosaicGridTool::autoGrid (bool draw) slot
Calculates the lat/lon increments from the bounding rectangle of the open cubes.
Parameters
draw True if lat/lon increments need to be calculated.
References Isis::MosaicSceneWidget::cubesBoundingRect(), Isis::Angle::Degrees, Isis::Angle::degrees(), drawGrid(), Isis::MosaicSceneWidget::getProjection(), Isis::MosaicTool::getWidget(), Isis::TProjection::Mapping(), Isis::Latitude::planetographic(), Isis::Projection::projectionType(), setLatExtents(), setLonExtents(), and Isis::Projection::Triaxial.
Referenced by Isis::MosaicGridToolConfigDialog::applySettings(), getToolBarWidget(), onCubesChanged(), and onToolOpen().
autoGridCheckBox()
bool Isis::MosaicGridTool::autoGridCheckBox ()
True if checked.
Returns
The state of the checkbox.
Referenced by Isis::MosaicGridToolConfigDialog::readSettings().
baseLat()
Latitude Isis::MosaicGridTool::baseLat ()
The base latitude.
Returns
The base latitude
Referenced by onProjectionChanged(), Isis::MosaicGridToolConfigDialog::readSettings(), and setBaseLat().
baseLon()
Longitude Isis::MosaicGridTool::baseLon ()
The base longitude.
Returns
The base longitude
Referenced by onProjectionChanged(), Isis::MosaicGridToolConfigDialog::readSettings(), and setBaseLon().
boundingRectChanged
void Isis::MosaicGridTool::boundingRectChanged () signal
Referenced by onCubesChanged().
clearGrid
void Isis::MosaicGridTool::clearGrid () slot
Clears the grid from the scene.
Does not erase any grid information.
References drawGrid(), Isis::MosaicSceneWidget::getScene(), and Isis::MosaicTool::getWidget().
Referenced by Isis::MosaicGridToolConfigDialog::applySettings(), and drawGrid().
configure
void Isis::MosaicGridTool::configure () slot
Give a configuration dialog for the options available in this tool.
Referenced by getToolBarWidget().
createToolBarWidget()
QWidget * Isis::MosaicGridTool::createToolBarWidget () protected
Creates the widget to add to the tool bar.
Parameters
parent
Returns
QWidget*
density()
int Isis::MosaicGridTool::density ()
The density or resolution of the grid.
The number of straight lines used to draw the grid.
Returns
The density
Referenced by Isis::MosaicGridToolConfigDialog::readSettings(), and setDensity().
domainMaxLon()
Longitude Isis::MosaicGridTool::domainMaxLon ()
References Isis::Angle::Degrees, Isis::MosaicSceneWidget::getProjection(), Isis::MosaicTool::getWidget(), Isis::TProjection::Has360Domain(), and Isis::Projection::Triaxial.
Referenced by MosaicGridTool(), and setLonExtents().
domainMinLon()
Longitude Isis::MosaicGridTool::domainMinLon ()
References Isis::Angle::Degrees, Isis::MosaicSceneWidget::getProjection(), Isis::MosaicTool::getWidget(), Isis::TProjection::Has360Domain(), and Isis::Projection::Triaxial.
Referenced by MosaicGridTool(), and setLonExtents().
drawGrid [1/2]
void Isis::MosaicGridTool::drawGrid () slot
Creates the GridGraphicsItem that will draw the grid.
If there is no grid item the grid is cleared and redrawn with a new item.
References Isis::Angle::degrees(), Isis::MosaicSceneWidget::getScene(), Isis::MosaicTool::getWidget(), and onCubesChanged().
Referenced by Isis::MosaicGridToolConfigDialog::applySettings(), autoGrid(), clearGrid(), drawGrid(), fromPvl(), and getToolBarWidget().
drawGrid [2/2]
void Isis::MosaicGridTool::drawGrid (bool draw) slot
Determines whether the grid should be drawn or not.
Parameters
draw True if grid should be drawn. Otherwise, it will be cleared.
References clearGrid(), and drawGrid().
fromPvl()
void Isis::MosaicGridTool::fromPvl (const PvlObject & obj) virtual
Read the tool information form a pvl object.
Parameters
obj the object from which we are extracting the information
Reimplemented from Isis::MosaicTool.
References Isis::Angle::Degrees, drawGrid(), Isis::TProjection::EquatorialRadius(), Isis::MosaicSceneWidget::getProjection(), Isis::MosaicTool::getWidget(), Isis::PvlObject::hasKeyword(), Isis::Distance::Meters, Isis::Latitude::Planetocentric, Isis::TProjection::PolarRadius(), Isis::Projection::projectionType(), Isis::toBool(), Isis::toDouble(), Isis::toInt(), and Isis::Projection::Triaxial.
getIcon()
QPixmap Isis::MosaicTool::getIcon (QString iconName) const inherited
returns the path to the icon directory.
Returns
QString
References Isis::FileName::expanded().
Referenced by Isis::MosaicAreaTool::getPrimaryAction(), Isis::MosaicControlNetTool::getPrimaryAction(), Isis::MosaicFindTool::getPrimaryAction(), getPrimaryAction(), Isis::MosaicPanTool::getPrimaryAction(), Isis::MosaicSelectTool::getPrimaryAction(), Isis::MosaicZoomTool::getPrimaryAction(), and Isis::MosaicZoomTool::MosaicZoomTool().
getPrimaryAction()
QAction * Isis::MosaicGridTool::getPrimaryAction () protected virtual
Adds the action to the toolpad.
Parameters
toolpad
Returns
QAction*
Implements Isis::MosaicTool.
References Isis::MosaicTool::getIcon().
getToolBarWidget()
QWidget * Isis::MosaicGridTool::getToolBarWidget () protected virtual
Creates the Grid Toolbar Widget.
Returns
The toolbar widget
Reimplemented from Isis::MosaicTool.
References Isis::MosaicTool::activated(), autoGrid(), configure(), Isis::MosaicSceneWidget::cubesBoundingRect(), drawGrid(), Isis::MosaicTool::getWidget(), and onToolOpen().
getViewActions()
QList< QAction * > Isis::MosaicTool::getViewActions () virtual inherited
Reimplemented in Isis::MosaicZoomTool.
Referenced by Isis::MosaicSceneWidget::getViewActions().
getWidget()
MosaicSceneWidget* Isis::MosaicTool::getWidget () inline protected inherited
Referenced by autoGrid(), Isis::MosaicAreaTool::clearBox(), clearGrid(), Isis::MosaicFindTool::clearPoint(), domainMaxLon(), domainMinLon(), drawGrid(), fromPvl(), getToolBarWidget(), Isis::MosaicFindTool::getUserGroundPoint(), latType(), Isis::MosaicControlNetTool::loadNetwork(), lonDomain(), Isis::MosaicControlNetTool::MosaicControlNetTool(), MosaicGridTool(), Isis::MosaicTrackTool::MosaicTrackTool(), Isis::MosaicControlNetTool::mouseButtonRelease(), Isis::MosaicAreaTool::mouseButtonRelease(), Isis::MosaicFindTool::mouseButtonRelease(), Isis::MosaicZoomTool::mouseWheel(), onCubesChanged(), onProjectionChanged(), Isis::MosaicZoomTool::rubberBandComplete(), sceneWidget(), setLatExtents(), setLonExtents(), Isis::MosaicTrackTool::updateLabels(), Isis::MosaicZoomTool::updateResolutionBox(), Isis::MosaicPanTool::updateTool(), Isis::MosaicSelectTool::updateTool(), Isis::MosaicZoomTool::updateTool(), Isis::MosaicAreaTool::userChangedBox(), and Isis::MosaicZoomTool::zoomFit().
isActive()
bool Isis::MosaicTool::isActive () const inline inherited
Returns the activeness of this toool.
Returns
bool
Referenced by Isis::MosaicSceneWidget::isControlNetToolActive(), Isis::MosaicControlNetTool::mouseButtonRelease(), Isis::MosaicZoomTool::mouseButtonRelease(), Isis::MosaicAreaTool::mouseButtonRelease(), Isis::MosaicFindTool::mouseButtonRelease(), Isis::MosaicZoomTool::rubberBandComplete(), Isis::MosaicFindTool::updateTool(), Isis::MosaicPanTool::updateTool(), Isis::MosaicSelectTool::updateTool(), and Isis::MosaicZoomTool::updateTool().
latExtents()
MosaicGridTool::GridExtentSource Isis::MosaicGridTool::latExtents ()
The extent type (Map, Cubes, Manual) for the latitude.
Returns
The extent type of the latitude
Referenced by Isis::MosaicGridToolConfigDialog::MosaicGridToolConfigDialog(), and Isis::MosaicGridToolConfigDialog::readSettings().
latInc()
Angle Isis::MosaicGridTool::latInc ()
The angle of the latitude increment.
Returns
The latitude increment angle.
Referenced by Isis::MosaicGridToolConfigDialog::readSettings(), and setLatInc().
latType()
QString Isis::MosaicGridTool::latType ()
The latitude type (planetocentric/planetographic) of the projection of the scene.
Returns
the latitude type as a string
References Isis::MosaicSceneWidget::getProjection(), Isis::MosaicTool::getWidget(), Isis::TProjection::LatitudeTypeString(), and Isis::Projection::Triaxial.
Referenced by Isis::MosaicGridToolConfigDialog::MosaicGridToolConfigDialog().
lonDomain()
QString Isis::MosaicGridTool::lonDomain ()
The longitude domain of the projection of the scene.
Returns
the domain as a string
References Isis::MosaicSceneWidget::getProjection(), Isis::MosaicTool::getWidget(), Isis::TProjection::LongitudeDomainString(), and Isis::Projection::Triaxial.
Referenced by Isis::MosaicGridToolConfigDialog::MosaicGridToolConfigDialog().
lonExtents()
MosaicGridTool::GridExtentSource Isis::MosaicGridTool::lonExtents ()
The extent type (Map, Cubes, Manual) for the longitude.
Returns
The extent type of the longitude
Referenced by Isis::MosaicGridToolConfigDialog::MosaicGridToolConfigDialog(), and Isis::MosaicGridToolConfigDialog::readSettings().
lonInc()
Angle Isis::MosaicGridTool::lonInc ()
The angle of the longitude increment.
Returns
The longitude increment angle.
Referenced by Isis::MosaicGridToolConfigDialog::readSettings(), and setLonInc().
maxLat()
Latitude Isis::MosaicGridTool::maxLat ()
The maximum latitude used to determine the grid's extents and increments.
Returns
The maximum latitude of the grid range.
Referenced by onProjectionChanged(), Isis::MosaicGridToolConfigDialog::readSettings(), and setLatExtents().
maxLon()
Longitude Isis::MosaicGridTool::maxLon ()
The maximum longitude used to determine the grid's extents and increments.
Returns
The maximum longitude of the grid range.
Referenced by onProjectionChanged(), Isis::MosaicGridToolConfigDialog::readSettings(), and setLonExtents().
minLat()
Latitude Isis::MosaicGridTool::minLat ()
The minimum latitude used to determine the grid's extents and increments.
Returns
The minimum latitude of the grid range.
Referenced by onProjectionChanged(), Isis::MosaicGridToolConfigDialog::readSettings(), and setLatExtents().
minLon()
Longitude Isis::MosaicGridTool::minLon ()
The minimum longitude used to determine the grid's extents and increments.
Returns
The minimum longitude of the grid range.
Referenced by onProjectionChanged(), Isis::MosaicGridToolConfigDialog::readSettings(), and setLonExtents().
mouseButtonPress()
void Isis::MosaicTool::mouseButtonPress (QPointF , Qt::MouseButton s) protected virtual inherited
Referenced by Isis::MosaicTool::MosaicTool().
mouseButtonRelease()
void Isis::MosaicTool::mouseButtonRelease (QPointF , Qt::MouseButton s) protected virtual inherited
Reimplemented in Isis::MosaicFindTool, Isis::MosaicAreaTool, Isis::MosaicZoomTool, and Isis::MosaicControlNetTool.
Referenced by Isis::MosaicTool::MosaicTool().
mouseDoubleClick()
void Isis::MosaicTool::mouseDoubleClick (QPointF) protected virtual inherited
Referenced by Isis::MosaicTool::MosaicTool().
mouseEnter()
virtual void Isis::MosaicTool::mouseEnter () inline protected virtual inherited
Referenced by Isis::MosaicTool::MosaicTool().
mouseLeave()
virtual void Isis::MosaicTool::mouseLeave () inline protected virtual inherited
Referenced by Isis::MosaicTool::MosaicTool().
mouseMove()
void Isis::MosaicTool::mouseMove (QPointF) protected virtual inherited
Referenced by Isis::MosaicTool::MosaicTool().
mouseWheel()
void Isis::MosaicTool::mouseWheel (QPointF , int delta) protected virtual inherited
Reimplemented in Isis::MosaicZoomTool.
Referenced by Isis::MosaicTool::MosaicTool().
onCubesChanged
void Isis::MosaicGridTool::onCubesChanged () slot
Determines whether or not the bounding rectangle was changed by the addition or removal of cubes.
If it wasn't changed, the grid is not redrawn. If it was (and autogrid is checked), the grid is redrawn with new lat/lon increments.
References autoGrid(), boundingRectChanged(), Isis::MosaicSceneWidget::getView(), and Isis::MosaicTool::getWidget().
Referenced by drawGrid().
onProjectionChanged
void Isis::MosaicGridTool::onProjectionChanged () slot
References baseLat(), baseLon(), Isis::Angle::Degrees, Isis::MosaicSceneWidget::getProjection(), Isis::MosaicTool::getWidget(), Map, Isis::TProjection::Mapping(), Isis::TProjection::MaximumLatitude(), Isis::TProjection::MaximumLongitude(), maxLat(), maxLon(), Isis::TProjection::MinimumLatitude(), Isis::TProjection::MinimumLongitude(), minLat(), minLon(), setBaseLat(), setBaseLon(), setLatExtents(), and setLonExtents().
Referenced by MosaicGridTool().
onToolOpen
void Isis::MosaicGridTool::onToolOpen (bool check) slot
Checks both checkboxes when the tool is first opened.
Allows the grid to remain when the tool is not active.
Parameters
check True when the tool is activated
References autoGrid().
Referenced by getToolBarWidget().
projectPvlObjectName()
QString Isis::MosaicGridTool::projectPvlObjectName () const virtual
An accessor for the name of the Pvl object that the tool's information is stored in.
Returns
The name in string form.
Reimplemented from Isis::MosaicTool.
Referenced by toPvl().
rubberBandComplete()
virtual void Isis::MosaicTool::rubberBandComplete (QRectF r, Qt::MouseButton s) inline protected virtual inherited
Reimplemented in Isis::MosaicZoomTool.
Referenced by Isis::MosaicTool::MosaicTool().
sceneWidget()
MosaicSceneWidget * Isis::MosaicGridTool::sceneWidget ()
Returns
a pointer to the scene
References Isis::MosaicTool::getWidget().
Referenced by Isis::MosaicGridToolConfigDialog::applySettings(), and Isis::MosaicGridToolConfigDialog::readSettings().
setAutoGridCheckBox()
void Isis::MosaicGridTool::setAutoGridCheckBox (bool checked)
Modify the check state of the checkbox.
Parameters
checked the new state of the checkbox
Referenced by Isis::MosaicGridToolConfigDialog::applySettings().
setBaseLat()
void Isis::MosaicGridTool::setBaseLat (Latitude baseLat)
Modify the base latitude.
Parameters
baseLat the new base latitude.
References baseLat().
Referenced by Isis::MosaicGridToolConfigDialog::applySettings(), and onProjectionChanged().
setBaseLon()
void Isis::MosaicGridTool::setBaseLon (Longitude baseLon)
Modify the base longitude.
Parameters
baseLon the new base longitude.
References baseLon().
Referenced by Isis::MosaicGridToolConfigDialog::applySettings(), and onProjectionChanged().
setDensity()
void Isis::MosaicGridTool::setDensity (int density)
Modify the density.
Parameters
density the new density value.
References density().
Referenced by Isis::MosaicGridToolConfigDialog::applySettings().
setLatExtents()
void Isis::MosaicGridTool::setLatExtents (GridExtentSource source, Latitude minLat = Latitude(), Latitude maxLat = Latitude())
Set the maximum and minimum latitude of the grid.
Parameters
source Where the grid extents come from (Map, Cubes, Manual).
minLat The minimum latitude of the grid.
maxLat The maximum latitude of the grid.
References Cubes, Isis::MosaicSceneWidget::cubesBoundingRect(), Isis::Angle::Degrees, Isis::TProjection::EquatorialRadius(), Isis::MosaicSceneWidget::getProjection(), Isis::MosaicTool::getWidget(), Isis::TProjection::Latitude(), Manual, Map, Isis::TProjection::Mapping(), Isis::TProjection::MaximumLatitude(), maxLat(), Isis::Distance::Meters, Isis::TProjection::MinimumLatitude(), minLat(), Isis::TProjection::PolarRadius(), Isis::Projection::projectionType(), Isis::TProjection::SetCoordinate(), Isis::TProjection::SetUniversalGround(), Isis::Projection::Triaxial, Isis::Projection::XCoord(), and Isis::Projection::YCoord().
Referenced by Isis::MosaicGridToolConfigDialog::applySettings(), autoGrid(), and onProjectionChanged().
setLatInc()
void Isis::MosaicGridTool::setLatInc (Angle latInc)
Modify the latitude increment.
Parameters
latInc the new increment angle.
References Isis::Angle::Degrees, and latInc().
Referenced by Isis::MosaicGridToolConfigDialog::applySettings().
setLonExtents()
void Isis::MosaicGridTool::setLonExtents (GridExtentSource source, Longitude minLon = Longitude(), Longitude maxLon = Longitude())
Set the maximum and minimum longitude of the grid.
Parameters
source Where the grid extents come from (Map, Cubes, Manual).
minLon The minimum longitude of the grid.
maxLon The maximum longitude of the grid.
References Cubes, Isis::MosaicSceneWidget::cubesBoundingRect(), Isis::Angle::Degrees, domainMaxLon(), domainMinLon(), Isis::MosaicSceneWidget::getProjection(), Isis::MosaicTool::getWidget(), Isis::TProjection::Longitude(), Manual, Map, Isis::TProjection::MaximumLongitude(), maxLon(), Isis::TProjection::MinimumLongitude(), minLon(), Isis::Projection::projectionType(), Isis::TProjection::SetCoordinate(), and Isis::Projection::Triaxial.
Referenced by Isis::MosaicGridToolConfigDialog::applySettings(), autoGrid(), and onProjectionChanged().
setLonInc()
void Isis::MosaicGridTool::setLonInc (Angle lonInc)
Modify the longitude increment.
Parameters
lonInc the new lonitude increment.
References Isis::Angle::Degrees, and lonInc().
Referenced by Isis::MosaicGridToolConfigDialog::applySettings().
setShowGrid()
void Isis::MosaicGridTool::setShowGrid (bool show)
Modify the check state of the checkbox.
Parameters
checked the new state of the checkbox
Referenced by Isis::MosaicGridToolConfigDialog::applySettings().
showGrid()
bool Isis::MosaicGridTool::showGrid ()
True if grid is displayed.
Returns
Whether or not the grid is displayed.
Referenced by Isis::MosaicGridToolConfigDialog::readSettings().
toolBarDestroyed()
void Isis::MosaicTool::toolBarDestroyed (QObject * obj) protected inherited
Referenced by Isis::MosaicTool::addTo().
toPvl()
PvlObject Isis::MosaicGridTool::toPvl () const virtual
Store the tool information in a pvl object.
Returns
the pvl object
Reimplemented from Isis::MosaicTool.
References Isis::Angle::degrees(), projectPvlObjectName(), and Isis::toString().
updateTool
virtual void Isis::MosaicTool::updateTool () inline protected virtual slot inherited
Referenced by Isis::MosaicTool::MosaicTool().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/MosaicGridTool.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/MosaicGridTool.cpp