Isis Developer Reference: Isis::Coordinate Class Reference
Isis::Coordinate Class Reference
Define a generic Y/X container.
#include <GruenTypes.h>
Public Member Functions
Coordinate ()
Coordinate (double y, double x)
Coordinate (const Chip &chip)
~Coordinate ()
void setLatLon (const double &latitude, const double &longitude)
Use Latitude/Longitude interface.
void setLineSamp (const double &line, const double &sample)
Use the Line/Sample interface.
Coordinate & operator+= (const Coordinate &other)
Add a point to this point.
Coordinate & operator-= (const Coordinate &other)
Subtract a point from this point.
double getDistance (const Coordinate &pntA=Coordinate(0.0, 0.0)) const
Computes the distance from this point and the point provided.
bool isValid () const
Check for goodness.
double getLatitude () const
double getLongitude () const
double getLine () const
double getSample () const
Public Attributes
double m_y
double m_x
Detailed Description
Define a generic Y/X container.
This generic container is designed to be used as a line/sample or a latitude/longitude container. It can be used to contain other cartesian coordinates if desired.
The default initialization sets the points the ISIS Null pixel value indicating it has not been initialized or can signal an invalid point if either one of the values is not initialized to something other than an ISIS special pixel.
Operators are defined to ease performing simple add/subtract operations.
Author
????-??-?? Unknown
Constructor & Destructor Documentation
Coordinate() [1/3]
Isis::Coordinate::Coordinate () inline
Coordinate() [2/3]
Isis::Coordinate::Coordinate (double y, double x) inline
Coordinate() [3/3]
Isis::Coordinate::Coordinate (const Chip & chip) inline
~Coordinate()
Isis::Coordinate::~Coordinate () inline
Member Function Documentation
getDistance()
double Isis::Coordinate::getDistance (const Coordinate & pntA = Coordinate(0.0, 0.0)) const inline
Computes the distance from this point and the point provided.
References m_x, and m_y.
getLatitude()
double Isis::Coordinate::getLatitude () const inline
References m_y.
getLine()
double Isis::Coordinate::getLine () const inline
References m_y.
Referenced by Isis::PointPair::getLeftLine(), Isis::AffineRadio::getPoint(), Isis::PointPair::getRightLine(), Isis::SmtkMatcher::isValid(), Isis::SmtkMatcher::Register(), Isis::Gruen::Registration(), and Isis::AffineRadio::Translate().
getLongitude()
double Isis::Coordinate::getLongitude () const inline
References m_x.
getSample()
double Isis::Coordinate::getSample () const inline
References m_x.
Referenced by Isis::PointPair::getLeftSample(), Isis::AffineRadio::getPoint(), Isis::PointPair::getRightSample(), Isis::SmtkMatcher::isValid(), Isis::SmtkMatcher::Register(), Isis::Gruen::Registration(), and Isis::AffineRadio::Translate().
isValid()
bool Isis::Coordinate::isValid () const inline
Check for goodness.
References Isis::IsSpecial(), m_x, and m_y.
Referenced by Isis::SmtkMatcher::Create(), Isis::PointPair::isValid(), Isis::PointGeometry::isValid(), Isis::SmtkMatcher::isValid(), Isis::operator+(), operator+=(), Isis::operator-(), operator-=(), and Isis::SmtkMatcher::Register().
operator+=()
Coordinate& Isis::Coordinate::operator+= (const Coordinate & other) inline
Add a point to this point.
References isValid(), m_x, m_y, and Isis::Null.
operator-=()
Coordinate& Isis::Coordinate::operator-= (const Coordinate & other) inline
Subtract a point from this point.
References isValid(), m_x, m_y, and Isis::Null.
setLatLon()
void Isis::Coordinate::setLatLon (const double & latitude, const double & longitude) inline
Use Latitude/Longitude interface.
References m_x, and m_y.
setLineSamp()
void Isis::Coordinate::setLineSamp (const double & line, const double & sample) inline
Use the Line/Sample interface.
References m_x, and m_y.
Member Data Documentation
m_x
double Isis::Coordinate::m_x
Referenced by getDistance(), getLongitude(), getSample(), isValid(), Isis::operator+(), operator+=(), Isis::operator-(), operator-=(), setLatLon(), and setLineSamp().
m_y
double Isis::Coordinate::m_y
Referenced by getDistance(), getLatitude(), getLine(), isValid(), Isis::operator+(), operator+=(), Isis::operator-(), operator-=(), setLatLon(), and setLineSamp().
The documentation for this class was generated from the following file:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Gruen/GruenTypes.h