Isis Developer Reference: Isis::PvlSequence Class Reference
Isis::PvlSequence Class Reference
Parsing
Parse and return elements of a Pvl sequence.
#include <PvlSequence.h>
Public Member Functions
PvlSequence ()
Construct an empty sequence.
~PvlSequence ()
Destruct sequence.
PvlSequence & operator= (PvlKeyword &key)
Load a sequence using a Pvl keyword.
PvlSequence & operator+= (const QString &array)
Add a string array to the sequence.
PvlSequence & operator+= (std::vector< QString > &array)
Add a vector of strings to the sequence.
PvlSequence & operator+= (std::vector< int > &array)
Add a vector of ints to the sequence.
PvlSequence & operator+= (std::vector< double > &array)
Add a vector of ints to the sequence.
std::vector< QString > & operator[] (int i)
Return the ith Array of the sequence.
int Size () const
Number of arrays in the sequence.
void Clear ()
Clear the sequence.
Detailed Description
Parse and return elements of a Pvl sequence.
A Pvl sequence is essentially an array of arrays. For example,
Keyword = ((a,b,c), (d,e))
To extract the invidual arrays from a PvlKeyword you must use a PvlSequence.
Here is an example of how to use PvlSequence
PvlKeyword k;
k += "(a,b,c)";
k += "(d,e)";
PvlSequence s = k;
cout << s.Size() << endl; // should be 2
cout << s[0][0] << endl;  // should be a
cout << s[1][1] << endl;  // should be e
Author
2005-02-16 Jeff Anderson
Constructor & Destructor Documentation
PvlSequence()
Isis::PvlSequence::PvlSequence () inline
Construct an empty sequence.
~PvlSequence()
Isis::PvlSequence::~PvlSequence () inline
Destruct sequence.
Member Function Documentation
Clear()
void Isis::PvlSequence::Clear () inline
Clear the sequence.
operator+=() [1/4]
PvlSequence & Isis::PvlSequence::operator+= (const QString & array)
Add a string array to the sequence.
The values in the string must be enclosed in parens and comma separated. For example, (1,2,3).
Parameters
array A string representing an array.
References Isis::PvlKeyword::size().
Referenced by operator=().
operator+=() [2/4]
PvlSequence & Isis::PvlSequence::operator+= (std::vector< double > & array)
Add a vector of ints to the sequence.
This adds another array to the sequence whose values are all doubles.
Parameters
array vector of doubles
References Isis::toString().
operator+=() [3/4]
PvlSequence & Isis::PvlSequence::operator+= (std::vector< int > & array)
Add a vector of ints to the sequence.
This adds another array to the sequence whose values are all integers.
Parameters
array vector of integers
References Isis::toString().
operator+=() [4/4]
PvlSequence & Isis::PvlSequence::operator+= (std::vector< QString > & array)
Add a vector of strings to the sequence.
This adds another array to the sequence whose values are all strings
Parameters
array vector of strings
operator=()
PvlSequence & Isis::PvlSequence::operator= (PvlKeyword & key)
Load a sequence using a Pvl keyword.
Each value of the PvlKeyword will be treated as an array for a sequence. Typically, the values in the PvlKeyword should be enclosed in parens and comma separated. For example, (a,b,c).
Parameters
key keyword containing sequence
References operator+=(), and Isis::PvlKeyword::size().
operator[]()
std::vector<QString>& Isis::PvlSequence::operator[] (int i) inline
Return the ith Array of the sequence.
Size()
int Isis::PvlSequence::Size () const inline
Number of arrays in the sequence.
Referenced by Isis::PvlKeyword::operator=(), and Isis::RadarSlantRangeMap::SetCoefficients().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/PvlSequence/PvlSequence.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/PvlSequence/PvlSequence.cpp