Isis Developer Reference: Isis::AdvancedStretch Class Reference
Isis::AdvancedStretch Class Reference
Advanced Stretch Dialog.
#include <AdvancedStretch.h>
Signals
void stretchChanged ()
Emitted when a new stretch is available.
void saveToCube ()
void deleteFromCube ()
void loadStretch ()
Public Member Functions
AdvancedStretch (Histogram &, const Stretch &, const QString &, const QColor &)
This constructs an advanced stretch.
~AdvancedStretch ()
Destructor.
CubeStretch getStretch ()
This returns the current stretch type's stretch.
void setStretch (Stretch newStretch)
This is called when the user creates a stretch outside of the advanced stretch.
void restoreSavedStretch (CubeStretch newStretch)
Used to restore a saved Stretch from a cube.
void setHistogram (const Histogram &newHist)
This is called when the visible area changes, so that the histogram can be updated.
Detailed Description
Advanced Stretch Dialog.
This class is one of the panes on the advanced stretch dialog (gray, red, green or blue). This contains advanced stretch types of each kind and a selection between them.
Author
2010-05-20 Steven Lambright
Constructor & Destructor Documentation
AdvancedStretch()
Isis::AdvancedStretch::AdvancedStretch (Histogram & hist, const Stretch & curStretch, const QString & name, const QColor & color)
This constructs an advanced stretch.
Parameters
hist Current histogram of visible area
curStretch Current stretch
name Graph name
color Graph color
References deleteFromCube(), loadStretch(), saveToCube(), and stretchChanged().
~AdvancedStretch()
Isis::AdvancedStretch::~AdvancedStretch ()
Destructor.
Member Function Documentation
deleteFromCube
void Isis::AdvancedStretch::deleteFromCube () signal
Referenced by AdvancedStretch().
getStretch()
CubeStretch Isis::AdvancedStretch::getStretch ()
This returns the current stretch type's stretch.
Returns
Stretch
Referenced by Isis::AdvancedStretchDialog::getBluStretch(), Isis::AdvancedStretchDialog::getGrayStretch(), Isis::AdvancedStretchDialog::getGrnStretch(), and Isis::AdvancedStretchDialog::getRedStretch().
loadStretch
void Isis::AdvancedStretch::loadStretch () signal
Referenced by AdvancedStretch().
restoreSavedStretch()
void Isis::AdvancedStretch::restoreSavedStretch (CubeStretch newStretch)
Used to restore a saved Stretch from a cube.
This function is distinct from setStretch in that setStretch deliberately does not change the stretch type, and this function does change the stretch type.
Parameters
newStretch saved stretch to restore
References Isis::CubeStretch::getType().
Referenced by Isis::AdvancedStretchDialog::restoreGrayStretch(), and Isis::AdvancedStretchDialog::restoreRgbStretch().
saveToCube
void Isis::AdvancedStretch::saveToCube () signal
Referenced by AdvancedStretch().
setHistogram()
void Isis::AdvancedStretch::setHistogram (const Histogram & newHist)
This is called when the visible area changes, so that the histogram can be updated.
It is essential that the stretch doesn't really change in this, or zooming will affect the stretch.
Parameters
newHist
References Isis::StretchType::setHistogram().
Referenced by Isis::AdvancedStretchDialog::updateForRGBMode(), Isis::AdvancedStretchDialog::updateHistogram(), and Isis::AdvancedStretchDialog::updateHistograms().
setStretch()
void Isis::AdvancedStretch::setStretch (Stretch newStretch)
This is called when the user creates a stretch outside of the advanced stretch.
For example, they do a global stretch. The advanced stretch will be given this stretch and a chance to re-interpret it.
Parameters
newStretch
References Isis::StretchType::setStretch().
Referenced by Isis::AdvancedStretchDialog::updateForRGBMode(), and Isis::AdvancedStretchDialog::updateStretch().
stretchChanged
void Isis::AdvancedStretch::stretchChanged () signal
Emitted when a new stretch is available.
Referenced by AdvancedStretch().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/StretchTool/AdvancedStretch.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/StretchTool/AdvancedStretch.cpp