Isis Developer Reference: Isis::RegionalCachingAlgorithm Class Reference
Isis::RegionalCachingAlgorithm Class Reference
This algorithm recommends chunks to be freed that are not within the last IO.
#include <RegionalCachingAlgorithm.h>
Public Member Functions
virtual CacheResult recommendChunksToFree (QList< RawCubeChunk * > allocated, QList< RawCubeChunk * > justUsed, const Buffer &justRequested)
Detailed Description
This algorithm recommends chunks to be freed that are not within the last IO.
Once the 10MB limit is reached, it recommends more chunks to free in order to stay below this limit, as long as the chunks weren't in the last IO.
Author
????-??-?? Jai Rideout and Steven Lambright
Member Function Documentation
recommendChunksToFree()
CubeCachingAlgorithm::CacheResult Isis::RegionalCachingAlgorithm::recommendChunksToFree (QList< RawCubeChunk * > allocated, QList< RawCubeChunk * > justUsed, const Buffer & justRequested) virtual
See also
CubeCachingAlgorithm::recommendChunksToFree()
Parameters
allocated
justUsed
justRequested
Returns
Implements Isis::CubeCachingAlgorithm.
References Isis::Buffer::BandDimension(), Isis::Buffer::LineDimension(), and Isis::Buffer::SampleDimension().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Cube/RegionalCachingAlgorithm.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Cube/RegionalCachingAlgorithm.cpp