Isis Developer Reference: Isis::Gui Class Reference
Isis::Gui Class Reference
Gui for Isis Applications.
#include <Gui.h>
Public Member Functions
void ProgressText (const QString &text)
Change progress text.
void Progress (int percent)
Update the progress bar.
int Exec (void(*funct)())
Start the Gui and enter the main loop This routine only returns when the program is ready to exit.
bool ProcessEvents ()
Let the event loop have some time to see if we need to cancel.
void LoadMessage (const QString &message)
Add more information to the error message.
int ShowWarning ()
Show an error message and return if the user wants to continue/abort.
void ShowLog ()
void Log (const QString &text)
Write text to the gui log.
Gui (Isis::UserInterface &ui)
Constructor.
~Gui ()
Destructor.
bool eventFilter (QObject *o, QEvent *e)
Reset the Progress bar when the user moves the mouse onto the toolbar.
Static Public Member Functions
static void checkX11 ()
check to see if X is available
static Gui * Create (Isis::UserInterface &ui, int &argc, char *argv[])
Detailed Description
Gui for Isis Applications.
This is the main GUI for all Isis Applications.
Author
2003-01-01 Stuart Sides
Constructor & Destructor Documentation
Gui()
Isis::Gui::Gui (Isis::UserInterface & ui)
Constructor.
References IsisAml::NumGroups(), IsisAml::NumParams(), and Isis::GuiParameter::Update().
Referenced by Create().
~Gui()
Isis::Gui::~Gui ()
Destructor.
Member Function Documentation
checkX11()
void Isis::Gui::checkX11 () static
check to see if X is available
Referenced by Isis::UserInterface::UserInterface().
Create()
Gui * Isis::Gui::Create (Isis::UserInterface & ui, int & argc, char * argv[]) static
References Isis::PvlObject::findGroup(), Gui(), Isis::PvlContainer::hasKeyword(), and Isis::Preference::Preferences().
Referenced by Isis::UserInterface::UserInterface().
eventFilter()
bool Isis::Gui::eventFilter (QObject * o, QEvent * e)
Reset the Progress bar when the user moves the mouse onto the toolbar.
References Progress(), and ProgressText().
Exec()
int Isis::Gui::Exec (void(*)() funct)
Start the Gui and enter the main loop This routine only returns when the program is ready to exit.
LoadMessage()
void Isis::Gui::LoadMessage (const QString & message)
Add more information to the error message.
Log()
void Isis::Gui::Log (const QString & text)
Write text to the gui log.
References Isis::GuiLog::Write().
Referenced by Isis::Application::GuiLog(), and Isis::Application::Log().
ProcessEvents()
bool Isis::Gui::ProcessEvents ()
Let the event loop have some time to see if we need to cancel.
This is normally called by the Isis::Progress class.
Progress()
void Isis::Gui::Progress (int percent)
Update the progress bar.
Referenced by eventFilter().
ProgressText()
void Isis::Gui::ProgressText (const QString & text)
Change progress text.
Referenced by eventFilter().
ShowLog()
void Isis::Gui::ShowLog () inline
Referenced by Isis::Application::GuiLog(), and Isis::Application::Log().
ShowWarning()
int Isis::Gui::ShowWarning ()
Show an error message and return if the user wants to continue/abort.
References Isis::Application::GetUserInterface(), Isis::iApp, and IsisAml::ProgramName().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Gui/Gui.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Gui/Gui.cpp