Isis Developer Reference: Isis::QHistogram Class Reference
Isis::QHistogram Class Reference
Utility
Plot Histograms.
#include <QHistogram.h>
Public Slots
void trackerEnabled ()
Enables mouse tracking on the plot.
void cdfCurveVisible ()
Hide/show the cdf curve.
void printPlot ()
Provide printing capabilities.
void savePlot ()
Allows user to save the plot to an image file.
void switchBackground ()
Switches the plot background color between black and white.
void showHelp ()
Provides help text in a dialog box.
Public Member Functions
QHistogram (QWidget *parent=NULL)
Constructs a QHistogram object with default titles.
~QHistogram ()
Destroys the QHistogram object.
void Load (Histogram &hist)
Plots the given Isis Histogram in the plot window.
Detailed Description
Plot Histograms.
This class is used to plot histograms. It is a utility class for the hist application.
Author
2006-12-21 Elizabeth Miller
Constructor & Destructor Documentation
QHistogram()
Isis::QHistogram::QHistogram (QWidget * parent = NULL)
Constructs a QHistogram object with default titles.
Parameters
parent
~QHistogram()
Isis::QHistogram::~QHistogram () inline
Destroys the QHistogram object.
Member Function Documentation
cdfCurveVisible
void Isis::QHistogram::cdfCurveVisible () slot
Hide/show the cdf curve.
Load()
void Isis::QHistogram::Load (Histogram & hist)
Plots the given Isis Histogram in the plot window.
Parameters
hist The Isis Histogram to plot
References Isis::Histogram::BinCount(), Isis::Histogram::BinMiddle(), Isis::Histogram::Bins(), and Isis::Statistics::ValidPixels().
printPlot
void Isis::QHistogram::printPlot () slot
Provide printing capabilities.
savePlot
void Isis::QHistogram::savePlot () slot
Allows user to save the plot to an image file.
showHelp
void Isis::QHistogram::showHelp () slot
Provides help text in a dialog box.
switchBackground
void Isis::QHistogram::switchBackground () slot
Switches the plot background color between black and white.
trackerEnabled
void Isis::QHistogram::trackerEnabled () slot
Enables mouse tracking on the plot.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/QHistogram/QHistogram.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/QHistogram/QHistogram.cpp