Isis Developer Reference: Isis::ImageTreeWidget::ImagePosition Class Reference
Isis::ImageTreeWidget::ImagePosition Class Reference
#include <ImageTreeWidget.h>
Public Member Functions
ImagePosition ()
ImagePosition (int outerIndex, int innerIndex)
ImagePosition (const ImagePosition &other)
virtual ~ImagePosition ()
void setPosition (int outerIndex, int innerIndex)
int group () const
int index () const
bool isValid () const
void swap (ImagePosition &other)
bool operator< (const ImagePosition &rhs)
ImagePosition & operator= (const ImagePosition &rhs)
Detailed Description
Author
2012-??-?? ???
Constructor & Destructor Documentation
ImagePosition() [1/3]
Isis::ImageTreeWidget::ImagePosition::ImagePosition ()
ImagePosition() [2/3]
Isis::ImageTreeWidget::ImagePosition::ImagePosition (int outerIndex, int innerIndex)
ImagePosition() [3/3]
Isis::ImageTreeWidget::ImagePosition::ImagePosition (const ImagePosition & other)
~ImagePosition()
Isis::ImageTreeWidget::ImagePosition::~ImagePosition () virtual
Member Function Documentation
group()
int Isis::ImageTreeWidget::ImagePosition::group () const
Referenced by Isis::ImageFileListWidget::addImages(), and operator<().
index()
int Isis::ImageTreeWidget::ImagePosition::index () const
Referenced by Isis::ImageFileListWidget::addImages(), and operator<().
isValid()
bool Isis::ImageTreeWidget::ImagePosition::isValid () const
Referenced by Isis::ImageFileListWidget::addImages().
operator<()
bool Isis::ImageTreeWidget::ImagePosition::operator< (const ImagePosition & rhs)
References group(), and index().
operator=()
ImageTreeWidget::ImagePosition & Isis::ImageTreeWidget::ImagePosition::operator= (const ImagePosition & rhs)
setPosition()
void Isis::ImageTreeWidget::ImagePosition::setPosition (int outerIndex, int innerIndex)
swap()
void Isis::ImageTreeWidget::ImagePosition::swap (ImagePosition & other)
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ImageFileListWidget/ImageTreeWidget.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ImageFileListWidget/ImageTreeWidget.cpp