Isis Developer Reference: Isis::NomenclatureToolConfigDialog Class Reference
Isis::NomenclatureToolConfigDialog Class Reference
Configure user's settings for the nomenclature tool.
#include <NomenclatureToolConfigDialog.h>
Public Slots
void applySettings ()
Apply the user's current settings to the tool.
void readSettings ()
Read the tool's current settings and set the widget states to match.
Public Member Functions
NomenclatureToolConfigDialog (FeatureNomenclatureTool *tool, QWidget *parent)
Create a config dialog that configures the given FeatureNomenclatureTool.
~NomenclatureToolConfigDialog ()
Clean up allocated memory.
Detailed Description
Configure user's settings for the nomenclature tool.
This dialog enables the user to configure the given nomenclature tool.
Author
2012-03-22 Steven Lambright and Jai Rideout
Constructor & Destructor Documentation
NomenclatureToolConfigDialog()
Isis::NomenclatureToolConfigDialog::NomenclatureToolConfigDialog (FeatureNomenclatureTool * tool, QWidget * parent)
Create a config dialog that configures the given FeatureNomenclatureTool.
Parameters
tool The tool to read settings from and write settings to.
parent The qt-parent relationship parent.
References applySettings(), Isis::FeatureNomenclatureTool::Arrows4, Isis::FeatureNomenclatureTool::Arrows8, Isis::FeatureNomenclatureTool::Box, Isis::FeatureNomenclatureTool::None, and readSettings().
~NomenclatureToolConfigDialog()
Isis::NomenclatureToolConfigDialog::~NomenclatureToolConfigDialog ()
Clean up allocated memory.
Member Function Documentation
applySettings
void Isis::NomenclatureToolConfigDialog::applySettings () slot
Apply the user's current settings to the tool.
References readSettings(), Isis::FeatureNomenclatureTool::setDefaultEnabled(), Isis::FeatureNomenclatureTool::setFontColor(), Isis::FeatureNomenclatureTool::setFontSize(), Isis::FeatureNomenclatureTool::setShowApprovedOnly(), and Isis::FeatureNomenclatureTool::setVectorType().
Referenced by NomenclatureToolConfigDialog().
readSettings
void Isis::NomenclatureToolConfigDialog::readSettings () slot
Read the tool's current settings and set the widget states to match.
References Isis::FeatureNomenclatureTool::defaultEnabled(), Isis::FeatureNomenclatureTool::fontColor(), Isis::FeatureNomenclatureTool::fontSize(), Isis::FeatureNomenclatureTool::showApprovedOnly(), and Isis::FeatureNomenclatureTool::vectorType().
Referenced by applySettings(), and NomenclatureToolConfigDialog().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/FeatureNomenclatureTool/NomenclatureToolConfigDialog.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/FeatureNomenclatureTool/NomenclatureToolConfigDialog.cpp