Isis Developer Reference: Isis::HiBlob Class Reference
Isis::HiBlob Class Reference
Mission Specific Objects » Mars Reconnaissance Orbiter
BLOB extraction class.
#include <HiBlob.h>
Public Member Functions
HiBlob ()
Default, mostly useless constructor.
HiBlob (Cube &cube, const QString &tblname, const QString &field, const QString &name="HiBlob")
Constructor providing interface to an ISIS Cube object.
virtual ~HiBlob ()
Destructor.
const HiMatrix & buffer () const
Return a reference to the data.
Blobber deepcopy () const
Create a unique copy of this blob.
void setName (const QString &name)
Specifies the name of this class instantiation.
void setBlobName (const QString &bname)
Sets the name of the ISIS BLOB object that contains the data.
void setFieldName (const QString &fname)
Sets field name in the ISIS BLOB object that contains data.
int size () const
Returns the total number of elements (rows * columns) in blob.
int Lines () const
Number of rows or lines in the BLOB.
int Samples () const
Number of columns or samples in the BLOB.
QString getName () const
Returns the name of the BLOB given to refer to this instantiation.
QString getBlobName () const
Retrieves the name of the Table object.
QString getFieldName () const
Retreive the name of the field in the Tabel object BLOB.
double * operator[] (int i)
Returns the ith row/line in the BLOB that can be further referenced into samples.
double const * operator[] (int i) const
Returns the ith row/line in the BLOB that can be further referenced into samples.
void load (const QString &filename)
Loads the contents of a BLOB from a cube file.
void load (Cube &cube)
Loads the contents of a BLOB from a Cube object.
Protected Types
typedef TNT::Array2D< double > BlobBuf
Internal buffer uses TNT.
Protected Member Functions
const BlobBuf & ref () const
Returns a const reference to the internal buffer for ease of use to derived objects.
Detailed Description
BLOB extraction class.
This class provides access and processing of HiRISE data as stored in an ISIS BLOB (Table).
Note that the file provided must be a HiRISE ISIS cube file that is freshly converted from a PDS compatable EDR (hi2isis). It must contain an ISIS Table named "HiRISE Calibration Image". From that table, data is extracted from the "Calibration" field.
Author
2007-10-09 Kris Becker
See also
Blobber
Member Typedef Documentation
BlobBuf
typedef TNT::Array2D<double> Isis::Blobber::BlobBuf protected inherited
Internal buffer uses TNT.
Constructor & Destructor Documentation
HiBlob() [1/2]
Isis::HiBlob::HiBlob () inline
Default, mostly useless constructor.
HiBlob() [2/2]
Isis::HiBlob::HiBlob (Cube & cube, const QString & tblname, const QString & field, const QString & name = "HiBlob") inline
Constructor providing interface to an ISIS Cube object.
~HiBlob()
virtual Isis::HiBlob::~HiBlob () inline virtual
Destructor.
Member Function Documentation
buffer()
const HiMatrix& Isis::HiBlob::buffer () const inline
Return a reference to the data.
References Isis::Blobber::ref().
Referenced by Isis::HiCalData::load().
deepcopy()
Blobber Isis::Blobber::deepcopy () const inherited
Create a unique copy of this blob.
This method creates a fully new copy of this object. The default copy constructors/methods create a reference to the data read from the Table object. For example, the following code fragment will result in two Blobbers that refer to the same memory location that stores the BLOB data:
Blobber myblob = yourblob;
To ensure you have two unique storage areas of the BLOB data so they can change independantly, use:
Blobber myblob = yourblob.deepcopy();
Returns
(Blobber) Returns a completely new copy, including data, to caller.
getBlobName()
QString Isis::Blobber::getBlobName () const inline inherited
Retrieves the name of the Table object.
Returns
(string) Name of the Table
Referenced by Isis::Blobber::load().
getFieldName()
QString Isis::Blobber::getFieldName () const inline inherited
Retreive the name of the field in the Tabel object BLOB.
Returns
(string) Name of the BLOB field
Referenced by Isis::Blobber::load().
getName()
QString Isis::Blobber::getName () const inline inherited
Returns the name of the BLOB given to refer to this instantiation.
Returns
Name of BLOB instance
Lines()
int Isis::Blobber::Lines () const inline inherited
Number of rows or lines in the BLOB.
Returns
The lines or rows
Referenced by Isis::Blobber::size().
load() [1/2]
void Isis::Blobber::load (const QString & filename) inherited
Loads the contents of a BLOB from a cube file.
Provides the I/O interface for ISIS cube files.
Parameters
[in] filename (string&) Name of ISIS cube file to read
References Isis::Cube::open().
Referenced by Isis::Blobber::Blobber().
load() [2/2]
void Isis::Blobber::load (Cube & cube) inherited
Loads the contents of a BLOB from a Cube object.
Provides the I/O interface for the Cube object. One thing to note here is that it creates a CubeInfo object from the Cube object and then calls the CubeInfo load method. Hence, this method is required as an intermediary method that cascades to the actual method that does the real work.
Parameters
[in] cube (Cube&) Reference to an ISIS cube file that has been opened or created in the Cube object.
References _FILEINFO_, Isis::Blobber::getBlobName(), Isis::Blobber::getFieldName(), Isis::TableField::isDouble(), Isis::TableField::isInteger(), Isis::IException::Programmer, and Isis::Cube::readTable().
operator[]() [1/2]
double* Isis::Blobber::operator[] (int i) inline inherited
Returns the ith row/line in the BLOB that can be further referenced into samples.
To access the 2nd sample in the 10th line use:
double sample = blobber[9][1];
Parameters
i Index
Returns
Pointer to the ith row in the BLOB
operator[]() [2/2]
double const* Isis::Blobber::operator[] (int i) const inline inherited
Returns the ith row/line in the BLOB that can be further referenced into samples.
This method provides const access to the data in row matrix form. To access the 2nd sample in the 10th line use:
double sample = blobber[9][1];
Parameters
i Index
Returns
Const pointer to the ith row in the BLOB
ref()
const BlobBuf& Isis::Blobber::ref () const inline protected inherited
Returns a const reference to the internal buffer for ease of use to derived objects.
Returns
Const reference to BLOB buffer
Referenced by buffer().
Samples()
int Isis::Blobber::Samples () const inline inherited
Number of columns or samples in the BLOB.
Returns
The number of samples or columns
Referenced by Isis::Blobber::size().
setBlobName()
void Isis::Blobber::setBlobName (const QString & bname) inline inherited
Sets the name of the ISIS BLOB object that contains the data.
This is name of a ISIS Table object that contains one or more fields that make up the BLOB. This is the value of the [i]Name[/i] keyword in the Table object.
Parameters
bname Blobber name
setFieldName()
void Isis::Blobber::setFieldName (const QString & fname) inline inherited
Sets field name in the ISIS BLOB object that contains data.
This method sets the name of the field contained within the Table object BLOB from which the data is extracted.
Parameters
fname Field name
setName()
void Isis::Blobber::setName (const QString & name) inline inherited
Specifies the name of this class instantiation.
This is just an additional name that can be used to identify instantiations of this class. It provides a way to uniquely identify each object.
Parameters
name Unique name
size()
int Isis::Blobber::size () const inline inherited
Returns the total number of elements (rows * columns) in blob.
Returns
The product of rows and columns
References Isis::Blobber::Lines(), and Isis::Blobber::Samples().
The documentation for this class was generated from the following file:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/mro/objs/HiCal/HiBlob.h