Isis Developer Reference: Isis::PvlGroup Class Reference
Isis::PvlGroup Class Reference
Parsing
Contains multiple PvlContainers.
#include <PvlGroup.h>
Public Types
enum InsertMode { Append , Replace }
Contains both modes: Append or Replace.
typedef QList< PvlKeyword >::iterator PvlKeywordIterator
The keyword iterator.
typedef QList< PvlKeyword >::const_iterator ConstPvlKeywordIterator
The const keyword iterator.
Public Member Functions
PvlGroup ()
Creates a blank PvlGroup object.
PvlGroup (const QString &name)
Creates a PvlGroup object with a name.
PvlGroup (const PvlGroup &other)
Copy constructor.
void validateGroup (PvlGroup &pPvlGrp)
Validate a Group comparing with the Template Group.
bool operator== (const PvlGroup &group) const
Whenever the '==' operator is used on a PvlGroup object, it will call the stringEqual() method.
const PvlGroup & operator= (const PvlGroup &other)
This is an assignment operator.
void setName (const QString &name)
Set the name of the container.
QString name () const
Returns the container name.
bool isNamed (const QString &match) const
Returns whether the given string is equal to the container name or not.
QString type () const
Returns the container type.
int keywords () const
Returns the number of keywords contained in the PvlContainer.
void clear ()
Clears PvlKeywords.
void addKeyword (const PvlKeyword &keyword, const InsertMode mode=Append)
Add a keyword to the container.
PvlKeywordIterator addKeyword (const PvlKeyword &keyword, PvlKeywordIterator pos)
Insert a keyword at the specified iterator position.
void operator+= (const PvlKeyword &keyword)
When you use the += operator with a PvlKeyword, it will call the addKeyword() method.
PvlKeyword & findKeyword (const QString &name)
Find a keyword with a specified name.
const PvlKeyword & findKeyword (const QString &name) const
Find a keyword with a specified name.
PvlKeywordIterator findKeyword (const QString &name, PvlKeywordIterator beg, PvlKeywordIterator end)
Find the index of a keyword, using iterators.
ConstPvlKeywordIterator findKeyword (const QString &name, ConstPvlKeywordIterator beg, ConstPvlKeywordIterator end) const
Find the index of a keyword, using iterators.
PvlKeyword & operator[] (const QString &name)
When you use the [] operator with a (string) name, it will call the findKeyword() method.
PvlKeyword & operator[] (const int index)
Return the PvlKeyword object at the specified index.
PvlKeyword & operator[] (const char *name)
When you use the [] operator with a (char) name, it will call the findKeyword() method.
const PvlKeyword & operator[] (const QString &name) const
When you use the [] operator with a (string) name, it will call the findKeyword() method.
const PvlKeyword & operator[] (const int index) const
Return the PvlKeyword object at the specified index.
PvlKeyword operator[] (const char *name) const
When you use the [] operator with a (char) name, it will call the findKeyword() method.
bool hasKeyword (const QString &name) const
Check to see if a keyword exists.
PvlKeywordIterator begin ()
Return the beginning iterator.
ConstPvlKeywordIterator begin () const
Return the const beginning iterator.
PvlKeywordIterator end ()
Return the ending iterator.
ConstPvlKeywordIterator end () const
Return the const ending iterator.
void deleteKeyword (const QString &name)
Remove a specified keyword.
void deleteKeyword (const int index)
Remove the specified keyword.
bool cleanDuplicateKeywords ()
Removes keywords from the container that have BOTH the same name and value.
void operator-= (const QString &name)
When you use the -= operator with a (string) name, it will call the deleteKeyword() method.
void operator-= (const PvlKeyword &key)
When you use the -= operator with a PvlKeyword object, it will call the deleteKeyword() method.
QString fileName () const
Returns the filename used to initialise the Pvl object.
void setFormatTemplate (PvlContainer &ref)
bool hasFormatTemplate ()
PvlContainer * formatTemplate ()
PvlFormat * format ()
void setFormat (PvlFormat *format)
int indent ()
void setIndent (int indent)
int comments () const
QString comment (const int index) const
void addComment (const QString &comment)
PvlKeyword & nameKeyword ()
const PvlKeyword & nameKeyword () const
Protected Member Functions
void init ()
Sets the filename to blank.
void setFileName (const QString &filename)
Sets the filename to the specified string.
void validateAllKeywords (PvlContainer &pPvlCont)
Validate All the Keywords in a Container comparing with the Template.
void validateRepeatOption (PvlKeyword &pPvlTmplKwrd, PvlContainer &pPvlCont)
Validate the Repeat Option for a Keyword.
Protected Attributes
QString m_filename
This contains the filename used to initialize the pvl object.
PvlKeyword m_name
This is the name keyword.
QList< PvlKeyword > m_keywords
This is the vector of PvlKeywords the container is holding.
PvlContainer * m_formatTemplate
Friends
std::istream & operator>> (std::istream &is, PvlGroup &result)
Read in a group.
std::ostream & operator<< (std::ostream &os, PvlGroup &group)
Outputs the PvlGroup data to a specified output stream.
Detailed Description
Contains multiple PvlContainers.
Contains multiple PvlContainers so that keyword-value pairs can be organized in specific groups. For example, a PvlGroup would be used to group all data from a particular mission together. A PvlGroup object will also organize (indent) objects on output.
Author
2002-10-11 Jeff Anderson
Member Typedef Documentation
ConstPvlKeywordIterator
typedef QList<PvlKeyword>::const_iterator Isis::PvlContainer::ConstPvlKeywordIterator inherited
The const keyword iterator.
PvlKeywordIterator
typedef QList<PvlKeyword>::iterator Isis::PvlContainer::PvlKeywordIterator inherited
The keyword iterator.
Member Enumeration Documentation
InsertMode
enum Isis::PvlContainer::InsertMode inherited
Contains both modes: Append or Replace.
Enumerator
Append
Replace
Constructor & Destructor Documentation
PvlGroup() [1/3]
Isis::PvlGroup::PvlGroup ()
Creates a blank PvlGroup object.
PvlGroup() [2/3]
Isis::PvlGroup::PvlGroup (const QString & name)
Creates a PvlGroup object with a name.
Parameters
name The group name.
PvlGroup() [3/3]
Isis::PvlGroup::PvlGroup (const PvlGroup & other)
Copy constructor.
Member Function Documentation
addComment()
void Isis::PvlContainer::addComment (const QString & comment) inline inherited
References Isis::PvlKeyword::addComment(), Isis::PvlContainer::comment(), and Isis::PvlContainer::m_name.
Referenced by Isis::Equalization::setResults(), Isis::Table::toBlob(), and Isis::ControlNetVersioner::write().
addKeyword() [1/2]
void Isis::PvlContainer::addKeyword (const PvlKeyword & keyword, const InsertMode mode = Append) inherited
Add a keyword to the container.
Add a keyword to the PvlContainer object.
Parameters
keyword The PvlKeyword object to append.
mode Using the InsertMode value of Append.
key The PvlKeyword object to add.
mode The enum InsertMode has two possible values, Append or Replace. Use Append if you just want to add it to the end, Replace if you want to replace it.
References Isis::PvlKeyword::name().
Referenced by Isis::ControlNetDiff::addUniqueMeasure(), Isis::ControlNetDiff::addUniquePoint(), Isis::NaifStatus::CheckErrors(), Isis::ControlNetDiff::compare(), Isis::ControlNetDiff::compareGroups(), Isis::CameraFactory::Create(), Isis::ShapeModelFactory::create(), Isis::ProjectionFactory::CreateForCube(), Isis::ControlNetDiff::diff(), Isis::fitsToJson(), Isis::PvlContainer::operator+=(), Isis::operator<<(), Isis::GridPolygonSeeder::PluginParameters(), Isis::LimitPolygonSeeder::PluginParameters(), Isis::PolygonSeeder::PluginParameters(), Isis::StripPolygonSeeder::PluginParameters(), Isis::PvlObject::PvlObject(), Isis::Target::radiiGroup(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::Stretch::Save(), Isis::ProcessMapMosaic::SetOutputCube(), Isis::Projection::SetUpperLeftCorner(), Isis::ProcessMosaic::StartProcess(), Isis::SubArea::UpdateLabel(), Isis::CubeTileHandler::updateLabels(), Isis::CubeBsqHandler::updateLabels(), and Isis::ControlNetVersioner::write().
addKeyword() [2/2]
PvlContainer::PvlKeywordIterator Isis::PvlContainer::addKeyword (const PvlKeyword & keyword, PvlKeywordIterator pos) inherited
Insert a keyword at the specified iterator position.
This method provides the capability to insert a keyword at the specified iterator position. The process follows the description of the STL vector definition along with all the caveats (e.g., invalidation of iterators upon insert operations).
This method will not perform any checks for the existance of the keyword. This could lead to multiple instances of the same keyword in the same container. It is up to the caller to manage this issue.
Parameters
key Keyword to insert
pos Iterator position where to insert the new keyword
Returns
PvlContainer::PvlKeywordIterator Returns the position of the inserted keyword per the STL vector documentation.
begin() [1/2]
PvlKeywordIterator Isis::PvlContainer::begin () inline inherited
Return the beginning iterator.
Returns
The beginning iterator.
References Isis::PvlContainer::m_keywords.
Referenced by Isis::PvlToPvlTranslationManager::DoTranslation(), Isis::PvlObject::findKeyword(), Isis::PvlObject::hasKeyword(), Isis::PvlTranslationTable::InputGroup(), Isis::DbProfile::loadkeys(), Isis::pvlContainerToJSON(), Isis::PvlTranslationTable::Translate(), and Isis::XmlToPvlTranslationManager::Translate().
begin() [2/2]
ConstPvlKeywordIterator Isis::PvlContainer::begin () const inline inherited
Return the const beginning iterator.
Returns
The const beginning iterator.
References Isis::PvlContainer::m_keywords.
cleanDuplicateKeywords()
bool Isis::PvlContainer::cleanDuplicateKeywords () inherited
Removes keywords from the container that have BOTH the same name and value.
Returns
bool True if one or more keywords were deleted; False if no keywords were deleted.
clear()
void Isis::PvlContainer::clear () inline inherited
Clears PvlKeywords.
References Isis::PvlContainer::m_keywords.
Referenced by Isis::PvlObject::clear().
comment()
QString Isis::PvlContainer::comment (const int index) const inline inherited
References Isis::PvlKeyword::comment(), and Isis::PvlContainer::m_name.
Referenced by Isis::PvlContainer::addComment(), Isis::operator<<(), and Isis::pvlContainerToJSON().
comments()
int Isis::PvlContainer::comments () const inline inherited
References Isis::PvlKeyword::comments(), and Isis::PvlContainer::m_name.
Referenced by Isis::operator<<(), and Isis::pvlContainerToJSON().
deleteKeyword() [1/2]
void Isis::PvlContainer::deleteKeyword (const int index) inherited
Remove the specified keyword.
Parameters
index The index of the keyword to remove.
Exceptions
iException::Pvl Keyword doesn't exist.
References _FILEINFO_.
deleteKeyword() [2/2]
void Isis::PvlContainer::deleteKeyword (const QString & name) inherited
Remove a specified keyword.
Parameters
name The name of the keyword to remove.
Exceptions
iException::Pvl Keyword doesn't exist.
References _FILEINFO_.
Referenced by IsisAml::CommandLine(), Isis::ControlPointV0001::ControlPointV0001(), Isis::ControlPointV0002::ControlPointV0002(), Isis::ControlPointV0003::ControlPointV0003(), Isis::Preference::Load(), Isis::ObliqueCylindrical::ObliqueCylindrical(), Isis::PvlContainer::operator-=(), Isis::GridPolygonSeeder::Parse(), Isis::LimitPolygonSeeder::Parse(), Isis::PolygonSeeder::Parse(), Isis::StripPolygonSeeder::Parse(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), Isis::ProcessExportPds::StandardImageImage(), Isis::ProcessExportPds::StandardJP2Image(), Isis::SubArea::UpdateLabel(), Isis::PvlContainer::validateAllKeywords(), and Isis::PvlContainer::validateRepeatOption().
end() [1/2]
PvlKeywordIterator Isis::PvlContainer::end () inline inherited
Return the ending iterator.
Returns
The ending iterator.
References Isis::PvlContainer::m_keywords.
Referenced by Isis::PvlToPvlTranslationManager::DoTranslation(), Isis::PvlObject::findGroup(), Isis::PvlObject::findKeyword(), Isis::PvlObject::findObject(), Isis::PvlObject::hasKeyword(), Isis::PvlTranslationTable::InputGroup(), Isis::DbProfile::loadkeys(), Isis::pvlContainerToJSON(), Isis::PvlTranslationTable::Translate(), and Isis::XmlToPvlTranslationManager::Translate().
end() [2/2]
ConstPvlKeywordIterator Isis::PvlContainer::end () const inline inherited
Return the const ending iterator.
Returns
The const ending iterator.
References Isis::PvlContainer::m_keywords.
fileName()
QString Isis::PvlContainer::fileName () const inline inherited
Returns the filename used to initialise the Pvl object.
If the object was not initialized using a file, this string is empty.
Returns
The filename.
References Isis::PvlContainer::m_filename.
Referenced by Isis::PvlObject::addObject(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ObservationNumber::Compose(), Isis::SerialNumber::Compose(), Isis::ProjectionFactory::CreateForCube(), Isis::ProjectionFactory::CreateFromCube(), Isis::DawnVirCamera::DawnVirCamera(), Isis::PvlTranslationTable::findTranslationGroup(), Isis::PvlToPvlTranslationManager::InputKeyword(), Isis::PvlToXmlTranslationManager::InputKeyword(), Isis::InterestOperator::Parse(), Isis::AutoReg::Parse(), Isis::GridPolygonSeeder::Parse(), Isis::LimitPolygonSeeder::Parse(), Isis::PolygonSeeder::Parse(), Isis::StripPolygonSeeder::Parse(), Isis::PvlEditDialog::PvlEditDialog(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::ProjectionFactory::RingsCreateFromCube(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), and Isis::PvlTranslationTable::Translate().
findKeyword() [1/4]
Isis::PvlKeyword & Isis::PvlContainer::findKeyword (const QString & name) inherited
Find a keyword with a specified name.
Parameters
name The name of the keyword to look for.
Returns
The PvlKeyword object.
Exceptions
iException::Pvl The keyword doesn't exist.
References _FILEINFO_.
Referenced by Isis::MosaicSceneWidget::addToPermanent(), Isis::BundleObservationSolveSettings::BundleObservationSolveSettings(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ControlNetDiff::compare(), Isis::ControlNetDiff::compareGroups(), Isis::CubeIoHandler::CubeIoHandler(), Isis::PvlToPvlTranslationManager::DoTranslation(), Isis::PvlToXmlTranslationManager::doTranslation(), Isis::fitsToJson(), Isis::CubeViewport::getBandFilterName(), Isis::PvlTranslationTable::InputGroup(), Isis::PvlToPvlTranslationManager::InputKeyword(), Isis::PvlToXmlTranslationManager::InputKeyword(), Isis::JunoCamera::JunoCamera(), Isis::Stretch::Load(), Isis::KernelDb::matches(), Isis::PvlContainer::operator[](), Isis::Target::radiiGroup(), Isis::ReseauDistortionMap::ReseauDistortionMap(), Isis::MosaicSceneWidget::setProjection(), Isis::CubeViewport::setTrackingCube(), Isis::ProcessExportPds4::StandardAllMapping(), Isis::ProcessExportPds::StandardAllMapping(), Isis::PvlTranslationTable::Translate(), Isis::XmlToPvlTranslationManager::Translate(), Isis::PvlContainer::validateAllKeywords(), Isis::PvlObject::validateObject(), and Isis::Pvl::validatePvl().
findKeyword() [2/4]
const Isis::PvlKeyword & Isis::PvlContainer::findKeyword (const QString & name) const inherited
Find a keyword with a specified name.
Parameters
name The name of the keyword to look for.
Returns
The PvlKeyword object.
Exceptions
IException The keyword doesn't exist.
References _FILEINFO_.
findKeyword() [3/4]
PvlContainer::ConstPvlKeywordIterator Isis::PvlContainer::findKeyword (const QString & name, PvlContainer::ConstPvlKeywordIterator beg, PvlContainer::ConstPvlKeywordIterator end) const inherited
Find the index of a keyword, using iterators.
Parameters
name The name of the keyword.
beg The beginning iterator.
end The ending iterator.
Returns
The keyword index.
findKeyword() [4/4]
PvlContainer::PvlKeywordIterator Isis::PvlContainer::findKeyword (const QString & name, PvlContainer::PvlKeywordIterator beg, PvlContainer::PvlKeywordIterator end) inherited
Find the index of a keyword, using iterators.
Parameters
name The name of the keyword.
beg The beginning iterator.
end The ending iterator.
Returns
The keyword index.
format()
PvlFormat* Isis::PvlContainer::format () inline inherited
References Isis::PvlKeyword::format(), and Isis::PvlContainer::m_name.
Referenced by Isis::Pvl::append(), Isis::ProcessExportPds::CreateImageLabel(), Isis::ProcessExportPds::FixedJP2ImageRoot(), Isis::operator<<(), Isis::PvlContainer::setFormat(), Isis::ProcessExportPds::StandardImageImage(), Isis::ProcessExportPds::StandardJP2Image(), Isis::ProcessExportPds::StreamJP2ImageRoot(), and Isis::Pvl::write().
formatTemplate()
PvlContainer* Isis::PvlContainer::formatTemplate () inline inherited
References Isis::PvlContainer::m_formatTemplate.
Referenced by Isis::operator<<().
hasFormatTemplate()
bool Isis::PvlContainer::hasFormatTemplate () inline inherited
References Isis::PvlContainer::m_formatTemplate.
Referenced by Isis::operator<<().
hasKeyword()
bool Isis::PvlContainer::hasKeyword (const QString & name) const inherited
Check to see if a keyword exists.
Parameters
name The name of the keyword to check for.
Returns
True if the keyword exists, false if it doesn't.
Referenced by Isis::Latitude::add(), Isis::SerialNumberList::add(), Isis::PvlTranslationTable::AddTable(), Isis::Albedo::Albedo(), Isis::AlbedoAtm::AlbedoAtm(), Isis::AtmosModel::AtmosModel(), Isis::BulletShapeModel::BulletShapeModel(), Isis::BundleObservationSolveSettings::BundleObservationSolveSettings(), Isis::Camera::Camera(), Isis::CameraFactory::CameraVersion(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), IsisAml::CommandLine(), Isis::ControlNetDiff::compareGroups(), Isis::ControlPointV0001::ControlPointV0001(), Isis::ControlPointV0002::ControlPointV0002(), Isis::ControlPointV0003::ControlPointV0003(), Isis::CameraFactory::Create(), Isis::Gui::Create(), Isis::PhotoModelFactory::Create(), Isis::AtmosModelFactory::Create(), Isis::NormModelFactory::Create(), Isis::ShapeModelFactory::create(), Isis::ProcessExportPds4::createUnitMap(), Isis::ControlNetFilter::CubeConvexHullFilter(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::ControlNetFilter::CubeNameExpressionFilter(), Isis::ControlNetFilter::CubeNumPointsFilter(), Isis::DemShape::DemShape(), Isis::PvlToPvlTranslationManager::DoTranslation(), Isis::PvlToXmlTranslationManager::doTranslation(), Isis::EmbreeShapeModel::EmbreeShapeModel(), Isis::Equirectangular::Equirectangular(), Isis::KernelDb::findAll(), Isis::fitsToJson(), Isis::CubeViewport::getBandFilterName(), Isis::UniversalGroundMap::GroundRange(), Isis::Camera::GroundRange(), Isis::Hapke::Hapke(), Isis::PvlTranslationTable::hasInputDefault(), Isis::Spice::hasKernels(), Isis::HiLab::HiLab(), Isis::IdealCamera::IdealCamera(), Isis::Equalization::importStatistics(), Isis::PvlTranslationTable::InputDefault(), Isis::PvlToPvlTranslationManager::InputHasKeyword(), Isis::PvlToXmlTranslationManager::InputHasKeyword(), Isis::PvlToPvlTranslationManager::InputKeyword(), Isis::PvlToXmlTranslationManager::InputKeyword(), Isis::PvlTranslationTable::InputKeywordName(), Isis::PvlTranslationTable::IsAuto(), Isis::PvlTranslationTable::IsOptional(), Isis::LambertConformal::LambertConformal(), Isis::Latitude::Latitude(), Isis::Preference::Load(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LunarLambert::LunarLambert(), Isis::LunarLambertEmpirical::LunarLambertEmpirical(), Isis::RingPlaneProjection::Mapping(), Isis::TProjection::Mapping(), Isis::KernelDb::matches(), Isis::Mercator::Mercator(), Isis::Minnaert::Minnaert(), Isis::MinnaertEmpirical::MinnaertEmpirical(), Isis::Mixed::Mixed(), Isis::Mollweide::Mollweide(), Isis::MoonAlbedo::MoonAlbedo(), Isis::NaifDskShape::NaifDskShape(), Isis::ObliqueCylindrical::ObliqueCylindrical(), Isis::operator<<(), Isis::Orthographic::Orthographic(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::Preference::outputErrorAsPvl(), Isis::PvlTranslationTable::OutputName(), Isis::PvlTranslationTable::OutputPosition(), Isis::AutoReg::Parse(), Isis::GridPolygonSeeder::Parse(), Isis::LimitPolygonSeeder::Parse(), Isis::PolygonSeeder::Parse(), Isis::StripPolygonSeeder::Parse(), Isis::PhotoModel::PhotoModel(), Isis::Planar::Planar(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointEditLockFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::ControlNetFilter::PointMeasurePropertiesFilter(), Isis::ControlNetFilter::PointMeasuresFilter(), Isis::ControlNetFilter::PointNumMeasuresEditLockFilter(), Isis::PointPerspective::PointPerspective(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::ControlNetFilter::PointPropertiesFilter(), Isis::ControlNetFilter::PointResMagnitudeFilter(), Isis::PolarStereographic::PolarStereographic(), Isis::Projection::Projection(), Isis::Target::radiiGroup(), Isis::AutoReg::RegTemplate(), Isis::Preference::reportFileLine(), Isis::RingCylindrical::RingCylindrical(), Isis::RingPlaneProjection::RingPlaneProjection(), Isis::Camera::ringRange(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::Robinson::Robinson(), Isis::ProcessImportFits::setFitsFile(), Isis::ProcessMapMosaic::SetOutputCube(), Isis::ProcessImportFits::setProcessFileStructure(), Isis::ControlNet::SetTarget(), Isis::Shade::Shade(), Isis::ShadeAtm::ShadeAtm(), Isis::SimpleCylindrical::SimpleCylindrical(), Isis::Sinusoidal::Sinusoidal(), Isis::ProcessExportPds::StandardAllMapping(), Isis::ProcessImportFits::standardInstrumentGroup(), Isis::Target::Target(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::Topo::Topo(), Isis::TopoAtm::TopoAtm(), Isis::TProjection::TProjection(), Isis::PvlTranslationTable::Translate(), Isis::PvlToPvlTranslationManager::Translate(), Isis::XmlToPvlTranslationManager::Translate(), Isis::PvlToXmlTranslationManager::Translate(), Isis::ProcessExportPds4::translateBandBinSpectrumBinSet(), Isis::ProcessExportPds4::translateBandBinSpectrumUniform(), Isis::TransverseMercator::TransverseMercator(), Isis::SubArea::UpdateLabel(), Isis::SpectralPlotTool::updateTool(), Isis::PvlContainer::validateAllKeywords(), Isis::PvlObject::validateObject(), Isis::Pvl::validatePvl(), Isis::ControlNetValidMeasure::ValidatePvlDN(), Isis::ControlNetValidMeasure::ValidatePvlEmissionAngle(), Isis::ControlNetValidMeasure::ValidatePvlFromEdge(), Isis::ControlNetValidMeasure::ValidatePvlIncidenceAngle(), Isis::ControlNetValidMeasure::ValidatePvlResidualTolerances(), Isis::ControlNetValidMeasure::ValidatePvlResolution(), and Isis::ControlNetValidMeasure::ValidatePvlShiftTolerances().
indent()
int Isis::PvlContainer::indent () inline inherited
References Isis::PvlKeyword::indent(), and Isis::PvlContainer::m_name.
Referenced by Isis::operator<<(), and Isis::PvlContainer::setIndent().
init()
void Isis::PvlContainer::init () protected inherited
Sets the filename to blank.
isNamed()
bool Isis::PvlContainer::isNamed (const QString & match) const inline inherited
Returns whether the given string is equal to the container name or not.
Parameters
match The string to compare to the name.
Returns
True if the name and string are the same, false if they are not.
References Isis::PvlContainer::m_name, and Isis::PvlKeyword::stringEqual().
Referenced by Isis::SessionLog::AddError(), Isis::Cube::attachSpiceFromIsd(), Isis::Cube::copy(), Isis::Blob::Find(), Isis::KernelDb::findAll(), Isis::Application::formatError(), Isis::Cube::hasBlob(), Isis::IsBlob(), Isis::Image::isFootprintable(), Isis::Shape::isFootprintable(), Isis::RemoveHiBlobs(), Isis::Process::SetOutputCube(), and Isis::Process::WriteHistory().
keywords()
int Isis::PvlContainer::keywords () const inline inherited
Returns the number of keywords contained in the PvlContainer.
Returns
The number of keywords.
References Isis::PvlContainer::m_keywords.
Referenced by Isis::PvlFormat::add(), Isis::PvlTranslationTable::AddTable(), Isis::ControlNetDiff::addTolerances(), Isis::UserInterface::BuildNewCommandLineFromPvl(), Isis::ControlNetDiff::compare(), Isis::ControlNetDiff::compareGroups(), Isis::ControlPointV0001::ControlPointV0001(), Isis::ControlPointV0002::ControlPointV0002(), Isis::ControlPointV0003::ControlPointV0003(), Isis::KernelDb::findAll(), Isis::MosaicSceneWidget::fromPvl(), Isis::ImageImporter::import(), Isis::Equalization::importStatistics(), Isis::Preference::Load(), Isis::KernelDb::matches(), Isis::operator<<(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::BandSpinBox::setBandBin(), Isis::ProcessImportVicar::SetVicarFile(), validateGroup(), Isis::PvlObject::validateObject(), Isis::Pvl::validatePvl(), and Isis::PvlContainer::validateRepeatOption().
name()
QString Isis::PvlContainer::name () const inline inherited
Returns the container name.
Returns
The container name.
References Isis::PvlContainer::m_name.
Referenced by Isis::PvlTranslationTable::AddTable(), Isis::ControlNetDiff::addTolerances(), Isis::LabelTranslationManager::Auto(), Isis::PvlToPvlTranslationManager::Auto(), Isis::PvlToXmlTranslationManager::Auto(), Isis::ControlPointV0003::ControlPointV0003(), Isis::Cube::copy(), Isis::CorrelationMatrix::CorrelationMatrix(), Isis::ProcessExportPds4::createUnitMap(), Isis::Cube::deleteBlob(), Isis::PvlObject::deleteGroup(), Isis::PvlObject::deleteObject(), Isis::PvlToXmlTranslationManager::doTranslation(), Isis::PvlObject::findGroup(), Isis::PvlObject::findObject(), Isis::ImageFileListWidget::fromPvl(), Isis::PvlObject::hasGroup(), Isis::PvlObject::hasObject(), Isis::Preference::Load(), Isis::PvlContainer::operator-=(), Isis::operator<<(), operator==(), Isis::PvlObject::operator==(), Isis::PvlContainer::operator[](), Isis::Cube::putGroup(), Isis::PvlObject::PvlObject(), Isis::BandSpinBox::setBandBin(), Isis::PvlContainer::setName(), Isis::Process::SetOutputCube(), Isis::OverlapStatistics::toPvl(), validateGroup(), Isis::PvlObject::validateObject(), Isis::Pvl::validatePvl(), and Isis::Blob::Write().
nameKeyword() [1/2]
PvlKeyword& Isis::PvlContainer::nameKeyword () inline inherited
References Isis::PvlContainer::m_name.
Referenced by Isis::BundleObservationSolveSettings::BundleObservationSolveSettings().
nameKeyword() [2/2]
const PvlKeyword& Isis::PvlContainer::nameKeyword () const inline inherited
References Isis::PvlContainer::m_name.
operator+=()
void Isis::PvlContainer::operator+= (const PvlKeyword & keyword) inline inherited
When you use the += operator with a PvlKeyword, it will call the addKeyword() method.
Parameters
keyword The PvlKeyword to be added.
References Isis::PvlContainer::addKeyword().
operator-=() [1/2]
void Isis::PvlContainer::operator-= (const PvlKeyword & key) inline inherited
When you use the -= operator with a PvlKeyword object, it will call the deleteKeyword() method.
Parameters
key The PvlKeyword object to remove.
References Isis::PvlContainer::deleteKeyword(), and Isis::PvlKeyword::name().
operator-=() [2/2]
void Isis::PvlContainer::operator-= (const QString & name) inline inherited
When you use the -= operator with a (string) name, it will call the deleteKeyword() method.
Parameters
name The name of the keyword to remove.
References Isis::PvlContainer::deleteKeyword(), and Isis::PvlContainer::name().
operator=()
const PvlGroup & Isis::PvlGroup::operator= (const PvlGroup & other)
This is an assignment operator.
References Isis::PvlContainer::operator=().
operator==()
bool Isis::PvlGroup::operator== (const PvlGroup & group) const inline
Whenever the '==' operator is used on a PvlGroup object, it will call the stringEqual() method.
This returns a boolean value.
Parameters
group The PvlGroup object to compare.
Returns
True if the other PvlGroup has the same name as this one, false if not.
References Isis::PvlContainer::name(), and Isis::PvlKeyword::stringEqual().
operator[]() [1/6]
PvlKeyword& Isis::PvlContainer::operator[] (const char * name) inline inherited
When you use the [] operator with a (char) name, it will call the findKeyword() method.
Parameters
name The name of the keyword to find.
References Isis::PvlContainer::name(), and Isis::PvlContainer::operator[]().
operator[]() [2/6]
PvlKeyword Isis::PvlContainer::operator[] (const char * name) const inline inherited
When you use the [] operator with a (char) name, it will call the findKeyword() method.
Parameters
name The name of the keyword to find.
References Isis::PvlContainer::name(), and Isis::PvlContainer::operator[]().
operator[]() [3/6]
PvlKeyword & Isis::PvlContainer::operator[] (const int index) inherited
Return the PvlKeyword object at the specified index.
Parameters
index The index to use.
Returns
The PvlKeyword at the specified index.
Exceptions
iException::Message The index is out of bounds.
References _FILEINFO_, and Isis::Message::ArraySubscriptNotInRange().
operator[]() [4/6]
const Isis::PvlKeyword & Isis::PvlContainer::operator[] (const int index) const inherited
Return the PvlKeyword object at the specified index.
Parameters
index The index to use.
Returns
The PvlKeyword at the specified index.
Exceptions
iException::Message The index is out of bounds.
References _FILEINFO_, and Isis::Message::ArraySubscriptNotInRange().
operator[]() [5/6]
PvlKeyword& Isis::PvlContainer::operator[] (const QString & name) inline inherited
When you use the [] operator with a (string) name, it will call the findKeyword() method.
Parameters
name The name of the keyword to find.
References Isis::PvlContainer::findKeyword(), and Isis::PvlContainer::name().
Referenced by Isis::PvlContainer::operator[]().
operator[]() [6/6]
const PvlKeyword& Isis::PvlContainer::operator[] (const QString & name) const inline inherited
When you use the [] operator with a (string) name, it will call the findKeyword() method.
Parameters
name The name of the keyword to find.
References Isis::PvlContainer::findKeyword(), and Isis::PvlContainer::name().
setFileName()
void Isis::PvlContainer::setFileName (const QString & filename) inline protected inherited
Sets the filename to the specified string.
Parameters
filename The new filename to use.
References Isis::PvlContainer::m_filename.
setFormat()
void Isis::PvlContainer::setFormat (PvlFormat * format) inline inherited
References Isis::PvlContainer::format(), Isis::PvlContainer::m_name, and Isis::PvlKeyword::setFormat().
Referenced by Isis::Pvl::append(), Isis::operator<<(), and Isis::Pvl::write().
setFormatTemplate()
void Isis::PvlContainer::setFormatTemplate (PvlContainer & ref) inline inherited
References Isis::PvlContainer::m_formatTemplate.
Referenced by Isis::Pvl::setFormatTemplate().
setIndent()
void Isis::PvlContainer::setIndent (int indent) inline inherited
References Isis::PvlContainer::indent(), Isis::PvlContainer::m_name, and Isis::PvlKeyword::setIndent().
Referenced by Isis::operator<<().
setName()
void Isis::PvlContainer::setName (const QString & name) inline inherited
Set the name of the container.
References Isis::PvlContainer::m_name, Isis::PvlContainer::name(), and Isis::PvlKeyword::setValue().
Referenced by Isis::fitsToJson(), Isis::MosaicSceneWidget::save(), and Isis::MosaicSceneWidget::toPvl().
type()
QString Isis::PvlContainer::type () const inline inherited
Returns the container type.
Returns
The container type.
References Isis::PvlContainer::m_name, and Isis::PvlKeyword::name().
Referenced by Isis::PvlObject::deleteGroup(), Isis::PvlObject::deleteObject(), and Isis::operator<<().
validateAllKeywords()
void Isis::PvlContainer::validateAllKeywords (PvlContainer & pPvlCont) protected inherited
Validate All the Keywords in a Container comparing with the Template.
Validate all the PvlKeywords in this container.
Author
Sharmila Prasad (9/24/2010)
Parameters
pPvlCont - Container to be Validated
History:
2010-10-18 Sharmila Prasad - Added options "Type", "Range", "Value" for the keyword validation
References _FILEINFO_, Isis::PvlContainer::deleteKeyword(), Isis::PvlContainer::findKeyword(), Isis::PvlContainer::hasKeyword(), Isis::PvlKeyword::name(), and Isis::PvlKeyword::validateKeyword().
Referenced by validateGroup(), Isis::PvlObject::validateObject(), and Isis::Pvl::validatePvl().
validateGroup()
void Isis::PvlGroup::validateGroup (PvlGroup & pPvlGrp)
Validate a Group comparing with the Template Group.
Validate a PvlGroup, comparing against the corresponding PvlGroup in the Template file.
Template PvlGroup has the format: Group = (groupName, optional/required)
Author
Sharmila Prasad (9/22/2010)
Parameters
pPvlGrp - PvlGroup to be validated
References _FILEINFO_, Isis::PvlContainer::keywords(), Isis::PvlContainer::name(), Isis::IException::User, and Isis::PvlContainer::validateAllKeywords().
Referenced by Isis::PvlObject::validateObject(), and Isis::Pvl::validatePvl().
validateRepeatOption()
void Isis::PvlContainer::validateRepeatOption (PvlKeyword & pPvlTmplKwrd, PvlContainer & pPvlCont) protected inherited
Validate the Repeat Option for a Keyword.
Validate Repeat Option in the Template Group.
This option indicates that a particular keyname can be repeated several times
Author
Sharmila Prasad (9/24/2010)
Parameters
pPvlTmplKwrd - Template Keyword wit
pPvlCont - Container with all the Keywords
History:
2010-10-18 Sharmila Prasad - Added option "Type" for the keyword validation
References Isis::PvlContainer::deleteKeyword(), Isis::PvlContainer::keywords(), Isis::PvlKeyword::name(), and Isis::PvlKeyword::validateKeyword().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, PvlGroup & group) friend
Outputs the PvlGroup data to a specified output stream.
Parameters
os The output stream to output to.
group The PvlGroup object to output.
operator>>
std::istream& operator>> (std::istream & is, PvlGroup & result) friend
Read in a group.
Parameters
is The input stream
result The PvlGroup to read into (OUTPUT)
Member Data Documentation
m_filename
QString Isis::PvlContainer::m_filename protected inherited
This contains the filename used to initialize the pvl object.
If the object was not initialized using a filename the string is empty.
Referenced by Isis::PvlObject::deleteGroup(), Isis::PvlObject::deleteObject(), Isis::PvlContainer::fileName(), Isis::PvlObject::findGroup(), Isis::PvlObject::findKeyword(), Isis::PvlObject::findObject(), Isis::PvlContainer::operator=(), Isis::Pvl::read(), and Isis::PvlContainer::setFileName().
m_formatTemplate
PvlContainer* Isis::PvlContainer::m_formatTemplate protected inherited
Referenced by Isis::PvlContainer::formatTemplate(), Isis::PvlContainer::hasFormatTemplate(), Isis::PvlContainer::operator=(), Isis::Pvl::setFormatTemplate(), Isis::PvlContainer::setFormatTemplate(), and Isis::Pvl::~Pvl().
m_keywords
QList<PvlKeyword> Isis::PvlContainer::m_keywords protected inherited
This is the vector of PvlKeywords the container is holding.
Referenced by Isis::PvlContainer::begin(), Isis::PvlContainer::clear(), Isis::PvlContainer::end(), Isis::PvlContainer::keywords(), and Isis::PvlContainer::operator=().
m_name
PvlKeyword Isis::PvlContainer::m_name protected inherited
This is the name keyword.
Referenced by Isis::PvlContainer::addComment(), Isis::PvlContainer::comment(), Isis::PvlContainer::comments(), Isis::PvlContainer::format(), Isis::PvlContainer::indent(), Isis::PvlContainer::isNamed(), Isis::PvlContainer::name(), Isis::PvlContainer::nameKeyword(), Isis::PvlContainer::operator=(), Isis::PvlContainer::setFormat(), Isis::PvlContainer::setIndent(), Isis::PvlContainer::setName(), and Isis::PvlContainer::type().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/PvlGroup/PvlGroup.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/PvlGroup/PvlGroup.cpp