Isis Developer Reference: Isis::MosaicControlNetToolMovementConfigDialog Class Reference
Isis::MosaicControlNetToolMovementConfigDialog Class Reference
Configure qmos Control Net Tool's movement arrows.
#include <MosaicControlNetToolMovementConfigDialog.h>
Public Slots
void applySettings ()
Apply the user's current settings to the tool.
void readSettings ()
Read the tool's current settings and set the widget states to match.
void refreshWidgetStates ()
Enables or disables widgets depending on the state of the tool.
Public Member Functions
MosaicControlNetToolMovementConfigDialog (MosaicControlNetTool *tool, QWidget *parent)
Create a config dialog that configures the given MosaicControlNetTool.
~MosaicControlNetToolMovementConfigDialog ()
Clean up allocated memory.
Detailed Description
Configure qmos Control Net Tool's movement arrows.
This allows a user to configure the qmos Control Net Tool's movement arrows. These are the arrows that go from the A Priori surface point to the Adjusted surface point.
Author
2012-12-31 Steven Lambright
Constructor & Destructor Documentation
MosaicControlNetToolMovementConfigDialog()
Isis::MosaicControlNetToolMovementConfigDialog::MosaicControlNetToolMovementConfigDialog (MosaicControlNetTool * tool, QWidget * parent)
Create a config dialog that configures the given MosaicControlNetTool.
Parameters
tool The tool to read settings from and write settings to.
parent The qt-parent relationship parent.
References applySettings(), Isis::MosaicControlNetTool::MeasureCount, Isis::MosaicControlNetTool::NoColor, readSettings(), refreshWidgetStates(), and Isis::MosaicControlNetTool::ResidualMagnitude.
~MosaicControlNetToolMovementConfigDialog()
Isis::MosaicControlNetToolMovementConfigDialog::~MosaicControlNetToolMovementConfigDialog ()
Clean up allocated memory.
Member Function Documentation
applySettings
void Isis::MosaicControlNetToolMovementConfigDialog::applySettings () slot
Apply the user's current settings to the tool.
References Isis::MosaicControlNetTool::NoMovement, Isis::Null, readSettings(), Isis::toDouble(), and Isis::toInt().
Referenced by MosaicControlNetToolMovementConfigDialog().
readSettings
void Isis::MosaicControlNetToolMovementConfigDialog::readSettings () slot
Read the tool's current settings and set the widget states to match.
References Isis::MosaicControlNetTool::NoMovement, Isis::Null, refreshWidgetStates(), and Isis::toString().
Referenced by applySettings(), and MosaicControlNetToolMovementConfigDialog().
refreshWidgetStates
void Isis::MosaicControlNetToolMovementConfigDialog::refreshWidgetStates () slot
Enables or disables widgets depending on the state of the tool.
References Isis::MosaicControlNetTool::MeasureCount, Isis::MosaicControlNetTool::NoColor, Isis::MosaicControlNetTool::ResidualMagnitude, and Isis::toInt().
Referenced by MosaicControlNetToolMovementConfigDialog(), and readSettings().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/MosaicControlNetToolMovementConfigDialog.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/MosaicControlNetToolMovementConfigDialog.cpp