Isis Developer Reference: Isis::ExportDescription::ChannelDescription Class Reference
Isis::ExportDescription::ChannelDescription Class Reference
High Level Cube I/O
Describes how a cube as a single color channel to be exported.
#include <ExportDescription.h>
Public Member Functions
ChannelDescription (FileName &filename, CubeAttributeInput &att)
Construct the channel description with the given input name and attributes.
virtual ~ChannelDescription ()
Destruct the export description.
FileName filename () const
Returns a copy of the filename associated with this channel.
CubeAttributeInput attributes () const
Returns a copy of the input attributes associated with this channel.
void setInputRange (double min, double max)
Sets the input range for this channel.
double inputMinimum () const
Returns the input minimum for this channel.
double inputMaximum () const
Returns the input maximum for this channel.
bool hasCustomRange () const
Returns true if the user of this instance has set a custom input range for this channel.
Detailed Description
Describes how a cube as a single color channel to be exported.
Specifies the filename, attributes, and input DN range of a cube to be exported as a color channel in a standard image.
Author
2012-04-03 Travis Addair
Constructor & Destructor Documentation
ChannelDescription()
Isis::ExportDescription::ChannelDescription::ChannelDescription (FileName & filename, CubeAttributeInput & att)
Construct the channel description with the given input name and attributes.
Parameters
filename The name of the cube
att The cube attributes such as band number
References filename().
~ChannelDescription()
virtual Isis::ExportDescription::ChannelDescription::~ChannelDescription () inline virtual
Destruct the export description.
Member Function Documentation
attributes()
CubeAttributeInput Isis::ExportDescription::ChannelDescription::attributes () const
Returns a copy of the input attributes associated with this channel.
Returns
The cube attributes such as band number
Referenced by Isis::ExportDescription::ExportDescription(), and Isis::ExportDescription::operator=().
filename()
FileName Isis::ExportDescription::ChannelDescription::filename () const
Returns a copy of the filename associated with this channel.
Returns
The name of the cube
Referenced by ChannelDescription(), Isis::ExportDescription::ExportDescription(), and Isis::ExportDescription::operator=().
hasCustomRange()
bool Isis::ExportDescription::ChannelDescription::hasCustomRange () const
Returns true if the user of this instance has set a custom input range for this channel.
Returns
True if a custom range has been set, false otherwise
Referenced by Isis::ExportDescription::ExportDescription(), and Isis::ExportDescription::operator=().
inputMaximum()
double Isis::ExportDescription::ChannelDescription::inputMaximum () const
Returns the input maximum for this channel.
Any value of max in the input cube will be mapped to the output max of the output channel.
Returns
The maximum DN in the input mapped to the maximum of the output
Referenced by Isis::ExportDescription::ExportDescription(), and Isis::ExportDescription::operator=().
inputMinimum()
double Isis::ExportDescription::ChannelDescription::inputMinimum () const
Returns the input minimum for this channel.
Any value of min in the input cube will be mapped to the output min of the output channel.
Returns
The minimum DN in the input mapped to the minimum of the output
Referenced by Isis::ExportDescription::ExportDescription(), and Isis::ExportDescription::operator=().
setInputRange()
void Isis::ExportDescription::ChannelDescription::setInputRange (double min, double max)
Sets the input range for this channel.
Any value of min in the input cube will be mapped to the output min of the output channel. Similar for the max.
Parameters
min The minimum DN in the input mapped to the minimum of the output
max The maximum DN in the input mapped to the maximum of the output
Referenced by Isis::ExportDescription::addChannel().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ExportDescription/ExportDescription.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ExportDescription/ExportDescription.cpp