Isis Developer Reference: Isis::MaximumLikelihoodWFunctions Class Reference
Isis::MaximumLikelihoodWFunctions Class Reference
Math
Class provides maximum likelihood estimation functions for robust parameter estimation, e.g.
#include <MaximumLikelihoodWFunctions.h>
Public Types
enum Model { Huber , HuberModified , Welsch , Chen }
The supported maximum likelihood estimation models.
Public Member Functions
MaximumLikelihoodWFunctions ()
Sets up a maximumlikelihood estimation function with Huber model and default tweaking constant.
MaximumLikelihoodWFunctions (Model modelSelection)
Sets up a maximumlikelihood estimation function with specified model and default tweaking constant.
MaximumLikelihoodWFunctions (Model modelSelection, double tweakingConstant)
Sets up a maximumlikelihood estimation function with specified model and tweaking constant.
MaximumLikelihoodWFunctions (const MaximumLikelihoodWFunctions &other)
~MaximumLikelihoodWFunctions ()
MaximumLikelihoodWFunctions & operator= (const MaximumLikelihoodWFunctions &other)
void setModel (Model modelSelection)
Allows the maximum likelihood model to be changed together and the default tweaking constant to be set.
void setTweakingConstantDefault ()
Sets default tweaking constants based on the maximum likelihood estimation model being used.
void setModel (Model modelSelection, double tweakingConstant)
Allows the maximum likelihood model to be changed together with the tweaking constant.
void setTweakingConstant (double tweakingConstant)
Allows the tweaking constant to be changed without changing the maximum likelihood function.
Model model () const
Accessor method to return the MaximumLikelihoodWFunctions::Model enumeration.
double tweakingConstant () const
Returns the current tweaking constant.
double sqrtWeightScaler (double residualZScore)
This provides the scaler to the sqrt of the weight, which is very useful for building normal equations.
double tweakingConstantQuantile ()
Suggest a quantile of the probility distribution of the residuals to use as the tweaking constants based on the maximum likelihood estimation model being used.
QString weightedResidualCutoff ()
Method to return a string represtentation of the weighted residual cutoff (if it exists) for the MaximumLikelihoodWFunctions::Model.
QDataStream & write (QDataStream &stream) const
QDataStream & read (QDataStream &stream)
Static Public Member Functions
static QString modelToString (Model model)
Static method to return a string represtentation for a given MaximumLikelihoodWFunctions::Model enum.
static MaximumLikelihoodWFunctions::Model stringToModel (QString modelName)
Detailed Description
Class provides maximum likelihood estimation functions for robust parameter estimation, e.g.
in bundle adjustment.
A maximum likelihood estimation W function provides a scheme for 're-weighting' observations so that measures with large residuals have reduced or negligible effect on the solution. There are many such functions available, a few have been programmed into this class. See enum Model documentation for specifics of the estimation models.
References: Zhangs, "Parameter Estimation: A Tutorial with Application to Conic Fitting" Koch, "Parameter Estimation and Hypothesis Testing in Linear Systems" 2nd edition, chapter 3.8 Manual of Photogrammetry, 5th edition, chapter 2.2 (particularly 2.2.6) Chen, "Robust Regression with Projection Based M-estimators"
Author
2012-03-23 Orrin Thomas
Member Enumeration Documentation
Model
enum Isis::MaximumLikelihoodWFunctions::Model
The supported maximum likelihood estimation models.
Enumerator
Huber
According to Zhang (Parameter Estimation: A Tutorial with application to conic fitting) "[Huber's] estimator is so satisfactory this is has been recommended for almost all situations; very rarely has it been found to be inferior to some other function.
" Its one deficiency is the discontinuous second derivative which cause rare diffeculites. No measures are totally disregarded. http://research.microsoft.com/en-us/um/people/zhang/Papers/ZhangIVC-97-01.pdf
HuberModified
A modification to Huber's method propsed by William J.J.
Rey in Introduction to Robust and Quasi-Robust Statistical Methods. Springer, Berlin, Heidelberg, 1983. It has similiar properties to the Huber, but with a continuous second derivative. This comes at the cost of being somewhat more computationally expernsive. No measures are totally disregarded. http://research.microsoft.com/en-us/um/people/zhang/Papers/ZhangIVC-97-01.pdf
Welsch
The Welsch method aggresively discounts measures with large resiudals.
Residuals two times greater than the tweaking constant are all but ignored. This method can be risky to use (at least at first) because it does not gaurantee a unique solution. And if sufficient measures are effectively 'removed' by the weighting, the system can become singular. The manual of photogrammetry recommended using it for clean up after convergeance or near convergence had been optained with a more stable method (such as Huber's). http://research.microsoft.com/en-us/um/people/zhang/Papers/ZhangIVC-97-01.pdf
Chen
The Chen method was found in "Robust Regression with Projection Based M-estimators" Chen, et.
al., though Chen does not take credit as the author. It was of interest because he seemed to present its use as expected in systems with large numbers of outliers, and because of it's unique properties. It is exceptionally aggresive. Residuals less than the tweaking constant generally have MORE influence than in standard least squares (or any other estimation function I've studied), and residuals larger than the tweaking function are totaly discounted.
Constructor & Destructor Documentation
MaximumLikelihoodWFunctions() [1/4]
Isis::MaximumLikelihoodWFunctions::MaximumLikelihoodWFunctions ()
Sets up a maximumlikelihood estimation function with Huber model and default tweaking constant.
References Huber, and setModel().
MaximumLikelihoodWFunctions() [2/4]
Isis::MaximumLikelihoodWFunctions::MaximumLikelihoodWFunctions (Model modelSelection)
Sets up a maximumlikelihood estimation function with specified model and default tweaking constant.
Parameters
[in] enum Model modelSelection, the model to be used (see documentation for enum Model)
References setModel().
MaximumLikelihoodWFunctions() [3/4]
Isis::MaximumLikelihoodWFunctions::MaximumLikelihoodWFunctions (Model modelSelection, double tweakingConstant)
Sets up a maximumlikelihood estimation function with specified model and tweaking constant.
Parameters
[in] enum Model modelSelection, the model to be used (see documentation for enum Model)
[in] double tweaking constant, exact meaning varies by model, but generally the larger the value the more influence larger resiudals have on the solution. As well as possibly the more measures are included in the solution.
Exceptions
IsisProgrammerError if tweakingConstant <= 0.0
References setModel(), and tweakingConstant().
MaximumLikelihoodWFunctions() [4/4]
Isis::MaximumLikelihoodWFunctions::MaximumLikelihoodWFunctions (const MaximumLikelihoodWFunctions & other)
~MaximumLikelihoodWFunctions()
Isis::MaximumLikelihoodWFunctions::~MaximumLikelihoodWFunctions ()
Member Function Documentation
model()
MaximumLikelihoodWFunctions::Model Isis::MaximumLikelihoodWFunctions::model () const
Accessor method to return the MaximumLikelihoodWFunctions::Model enumeration.
Returns
enum for the maximum likelihood estimation model.
Referenced by modelToString(), and read().
modelToString()
QString Isis::MaximumLikelihoodWFunctions::modelToString (MaximumLikelihoodWFunctions::Model model) static
Static method to return a string represtentation for a given MaximumLikelihoodWFunctions::Model enum.
Parameters
model Enumerated value for a MaximumLikelihoodWFunctions model.
Returns
QString label for the enumeration.
References _FILEINFO_, Chen, Huber, HuberModified, model(), Isis::IException::Programmer, Isis::toString(), and Welsch.
Referenced by Isis::BundleSolutionInfo::outputHeader(), Isis::BundleResults::save(), and Isis::BundleSettings::save().
operator=()
MaximumLikelihoodWFunctions & Isis::MaximumLikelihoodWFunctions::operator= (const MaximumLikelihoodWFunctions & other)
read()
QDataStream & Isis::MaximumLikelihoodWFunctions::read (QDataStream & stream)
References model().
Referenced by Isis::operator>>().
setModel() [1/2]
void Isis::MaximumLikelihoodWFunctions::setModel (Model modelSelection)
Allows the maximum likelihood model to be changed together and the default tweaking constant to be set.
@Param[in] enum Model modelSelection, the model to be used (see documentation for enum Model)
References setTweakingConstantDefault().
Referenced by MaximumLikelihoodWFunctions().
setModel() [2/2]
void Isis::MaximumLikelihoodWFunctions::setModel (Model modelSelection, double tweakingConstant)
Allows the maximum likelihood model to be changed together with the tweaking constant.
Parameters
[in] enum Model modelSelection, the model to be used (see documentation for enum Model)
[in] tweakingConstant,exact meaning varies by model, but generally the larger the value the more influence larger resiudals have on the solution. As well as possibly the more measures are included in the solution.
Exceptions
IsisProgrammerError if tweakingConstant <= 0.0
References setTweakingConstant(), and tweakingConstant().
setTweakingConstant()
void Isis::MaximumLikelihoodWFunctions::setTweakingConstant (double tweakingConstant)
Allows the tweaking constant to be changed without changing the maximum likelihood function.
Parameters
[in] tweakingConstant,exact meaning varies by model, but generally the larger the value the more influence larger resiudals have on the solution. As well as possiblly the more measures are included in the solution.
Exceptions
IsisProgrammerError if tweakingConstant <= 0.0
References _FILEINFO_, Isis::IException::Programmer, and tweakingConstant().
Referenced by setModel().
setTweakingConstantDefault()
void Isis::MaximumLikelihoodWFunctions::setTweakingConstantDefault ()
Sets default tweaking constants based on the maximum likelihood estimation model being used.
References Chen, Huber, HuberModified, and Welsch.
Referenced by setModel().
sqrtWeightScaler()
double Isis::MaximumLikelihoodWFunctions::sqrtWeightScaler (double residualZScore)
This provides the scaler to the sqrt of the weight, which is very useful for building normal equations.
Parameters
[in] double residualZScore, this the residual of a particulare measure in a particular iteration divided by the standard deviation (sigma) of that measure
Returns
double the scaler adjustment to the sqrt of the weight for the measure nominal sqrt(weight) = 1 /sigma and sqrt(weight') = scaler/sigma
stringToModel()
MaximumLikelihoodWFunctions::Model Isis::MaximumLikelihoodWFunctions::stringToModel (QString modelName) static
References _FILEINFO_, Chen, Huber, HuberModified, Isis::IException::Programmer, and Welsch.
Referenced by Isis::JigsawSetupDialog::bundleSettings(), Isis::BundleSettings::readBundleSettings(), and Isis::BundleResults::readMaxLikelihoodEstimation().
tweakingConstant()
double Isis::MaximumLikelihoodWFunctions::tweakingConstant () const
Returns the current tweaking constant.
Referenced by MaximumLikelihoodWFunctions(), Isis::BundleSolutionInfo::outputHeader(), setModel(), and setTweakingConstant().
tweakingConstantQuantile()
double Isis::MaximumLikelihoodWFunctions::tweakingConstantQuantile ()
Suggest a quantile of the probility distribution of the residuals to use as the tweaking constants based on the maximum likelihood estimation model being used.
Returns
double quantile [0,1] the value pretaining to this quantile (in the probility distribution of the residuals) should be used as the tweaking constant.
References Chen, Huber, HuberModified, and Welsch.
weightedResidualCutoff()
QString Isis::MaximumLikelihoodWFunctions::weightedResidualCutoff ()
Method to return a string represtentation of the weighted residual cutoff (if it exists) for the MaximumLikelihoodWFunctions::Model.
If no cutoff exists, the string "N/A" is returned.
Returns
QString label for the weighted residual cut off of the maximum likelihood estimation model.
Exceptions
Estimation model has not been set.
References _FILEINFO_, Chen, Huber, HuberModified, Isis::IException::Programmer, Isis::toString(), and Welsch.
Referenced by Isis::BundleSolutionInfo::outputHeader().
write()
QDataStream & Isis::MaximumLikelihoodWFunctions::write (QDataStream & stream) const
Referenced by Isis::operator<<().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/MaximumLikelihoodWFunctions/MaximumLikelihoodWFunctions.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/MaximumLikelihoodWFunctions/MaximumLikelihoodWFunctions.cpp