Isis Developer Reference: Isis::Directory Class Reference
Isis::Directory Class Reference
#include <Directory.h>
Public Slots
void cleanupBundleObservationViews (QObject *)
Removes pointers to deleted BundleObservationView objects.
void cleanupCnetEditorViewWidgets (QObject *)
Removes pointers to deleted CnetEditorWidget objects.
void cleanupCubeDnViewWidgets (QObject *)
Removes pointers to deleted CubeDnView objects.
void cleanupFileListWidgets (QObject *)
Removes pointers to deleted ImageFileListWidget objects.
void cleanupFootprint2DViewWidgets (QObject *)
Removes pointers to deleted Footprint2DView objects.
void cleanupControlPointEditViewWidget (QObject *)
Delete the ControlPointEditWidget and set it's pointer to NULL.
void cleanupMatrixViewWidgets (QObject *)
Removes pointers to deleted MatrixSceneWidget objects.
void cleanupSensorInfoWidgets (QObject *)
Removes pointers to deleted SensorInfoWidget objects.
void cleanupTargetInfoWidgets (QObject *)
Removes pointers to deleted TargetInfoWidget objects.
void cleanupTemplateEditorWidgets (QObject *)
Removes pointers to deleted TemplateEditorWidget objects.
void cleanupJigsawRunWidget (QObject *)
void updateControlNetEditConnections ()
Updates the SIGNAL/SLOT connections for the cotrol net editor.
void modifyControlPoint (ControlPoint *controlPoint, QString serialNumber="")
Slot that is connected from a left mouse button operation on views.
void deleteControlPoint (ControlPoint *controlPoint)
Slot that is connected from a middle mouse button operation on views.
void createControlPoint (double latitude, double longitude, Cube *cube=0, bool isGroundSource=false)
Slot that is connected from a right mouse button operation on views.
void updateRecentProjects (Project *project)
Adds a new Project object to the list of recent projects if it has not already been added.
void updateRecentProjects ()
Loads and displays a list of recently opened projects in the file menu.
Signals
void directoryCleaned ()
void newWarning ()
void newDockAvailable (QMainWindow *newWidget)
void newWidgetAvailable (QWidget *newWidget)
void closeView (QWidget *widget)
void cnetModified ()
void activeControlModified ()
void redrawMeasures ()
void cleanProject (bool)
Public Member Functions
Directory (QObject *parent=0)
The Constructor.
~Directory ()
The Destructor.
void clean ()
Cleans directory of everything to do with the current project.
void setHistoryContainer (QDockWidget *historyContainer)
Set up the history info in the history dockable widget.
void setWarningContainer (QDockWidget *warningContainer)
Set up the warning info in the warning dockable widget.
void setRecentProjectsList (QStringList recentProjects)
Add recent projects to the recent projects list.
QStringList recentProjectsList ()
Public accessor for the list of recent projects.
BundleObservationView * addBundleObservationView (FileItemQsp fileItem)
Add the BundleObservationView to the window.
ControlHealthMonitorView * addControlHealthMonitorView ()
CnetEditorView * addCnetEditorView (Control *control, QString objectName="")
Add the widget for the cnet editor view to the window.
CubeDnView * addCubeDnView (QString objectName="")
Add the qview workspace to the window.
Footprint2DView * addFootprint2DView (QString objectName="")
Add the qmos view widget to the window.
JigsawRunWidget * addJigsawRunWidget ()
MatrixSceneWidget * addMatrixView ()
Add the matrix view widget to the window.
TargetInfoWidget * addTargetInfoView (TargetBodyQsp target)
Add target body data view widget to the window.
TemplateEditorWidget * addTemplateEditorView (Template *currentTemplate)
Add template editor view widget to the window.
SensorInfoWidget * addSensorInfoView (GuiCameraQsp camera)
Add sensor data view widget to the window.
ImageFileListWidget * addImageFileListView (QString objectName="")
Add an imageFileList widget to the window.
ControlPointEditView * addControlPointEditView ()
ProjectItemTreeView * addProjectItemTreeView ()
Adds a ProjectItemTreeView to the window.
ProjectItemModel * model ()
Gets the ProjectItemModel for this directory.
Project * project () const
Gets the Project for this directory.
QList< QAction * > fileMenuActions ()
Get the list of actions that the Directory can provide for the file menu.
QList< QAction * > projectMenuActions ()
Get the list of actions that the Directory can provide for the project menu.
QList< QAction * > editMenuActions ()
Get the list of actions that the Directory can provide for the edit menu.
QList< QAction * > viewMenuActions ()
Get the list of actions that the Directory can provide for the view menu.
QList< QAction * > settingsMenuActions ()
Get the list of actions that the Directory can provide for the settings menu.
QList< QAction * > helpMenuActions ()
Get the list of actions that the Directory can provide for the help menu.
QList< QAction * > permToolBarActions ()
Get the list of actions that the Directory can provide for the permanent Tool Bar.
QList< QAction * > activeToolBarActions ()
Get the list of actions that the Directory can provide for the active Tool Bar.
QList< QAction * > toolPadActions ()
Get the list of actions that the Directory can provide for the Tool Pad.
QList< BundleObservationView * > bundleObservationViews ()
QList< CnetEditorView * > cnetEditorViews ()
Returns a list of all the control network views for this directory.
QList< CubeDnView * > cubeDnViews ()
Accessor for the list of CubeDnViews currently available.
QList< Footprint2DView * > footprint2DViews ()
Accessor for the list of Footprint2DViews currently available.
QList< MatrixSceneWidget * > matrixViews ()
Accessor for the list of MatrixSceneWidgets currently available.
QList< SensorInfoWidget * > sensorInfoViews ()
Accessor for the list of SensorInfoWidgets currently available.
QList< TargetInfoWidget * > targetInfoViews ()
Accessor for the list of TargetInfoWidgets currently available.
QList< TemplateEditorWidget * > templateEditorViews ()
Accessor for the list of TemplateEditorWidgets currently available.
QList< ImageFileListWidget * > imageFileListViews ()
Accessor for the list of ImageFileListWidgets currently available.
QList< QProgressBar * > progressBars ()
Gets the ControlNetEditor associated with this the Directory.
ControlHealthMonitorView * controlHealthMonitorView ()
ControlPointEditView * controlPointEditView ()
Gets the ControlPointEditWidget associated with the Directory.
JigsawRunWidget * jigsawRunWidget ()
bool controlUsedInCnetEditorWidget (Control *control)
@description Return true if control is not currently being viewed in a CnetEditorWidget
QString editPointId ()
Return the current control point id loaded in the ControlPointEditWidget.
template<typename DataType >
QList< QAction * > supportedActions (DataType data)
Returns a list of supported actions for a WorkOrder.
void showWarning (QString text)
Displays a Warning.
template<typename Data >
void showWarning (QString text, Data data)
Shows warning text for a Widget.
QWidget * warningWidget ()
Returns a pointer to the warning widget.
QAction * redoAction ()
Creates an Action to redo the last action.
QAction * undoAction ()
Creates an Action to undo the last action.
void save (QXmlStreamWriter &stream, FileName newProjectRoot) const
Save the directory to an XML file.
Detailed Description
Author
2012-??-?? ???
Constructor & Destructor Documentation
Directory()
Isis::Directory::Directory (QObject * parent = 0) explicit
The Constructor.
Exceptions
IException::Programmer To handle the event that a Project cannot be created.
IException::Programmer To handle the event that a Directory cannot be created because the WorkOrders we are attempting to add to the Directory are corrupt.
References _FILEINFO_, activeControlModified(), cleanProject(), cnetModified(), Isis::IException::Programmer, project(), and updateRecentProjects().
~Directory()
Isis::Directory::~Directory ()
The Destructor.
Member Function Documentation
activeControlModified
void Isis::Directory::activeControlModified () signal
Referenced by addCubeDnView(), addFootprint2DView(), and Directory().
activeToolBarActions()
QList< QAction * > Isis::Directory::activeToolBarActions ()
Get the list of actions that the Directory can provide for the active Tool Bar.
Returns
QList<QAction *> Returns a list of active Tool Bar actions.
addBundleObservationView()
BundleObservationView * Isis::Directory::addBundleObservationView (FileItemQsp fileItem)
Add the BundleObservationView to the window.
Returns
(BundleObservationView *) The BundleObservationView displayed.
References cleanupBundleObservationViews(), newWidgetAvailable(), and Isis::FileName::originalPath().
Referenced by Isis::BundleObservationViewWorkOrder::execute().
addCnetEditorView()
CnetEditorView * Isis::Directory::addCnetEditorView (Control * control, QString objectName = "")
Add the widget for the cnet editor view to the window.
Parameters
Control to edit.
Returns
(CnetEditorView *) The view to add to the window.
References cleanupCnetEditorViewWidgets(), Isis::CnetEditorView::cnetEditorWidget(), cnetModified(), Isis::TableView::content(), Isis::DisplayProperties::displayName(), Isis::Control::displayProperties(), Isis::CnetEditorWidget::measureTableView(), modifyControlPoint(), newWidgetAvailable(), Isis::CnetEditorWidget::pointTableView(), project(), and Isis::TableViewContent::setActiveControlNet().
Referenced by Isis::CnetEditorViewWorkOrder::execute().
addControlHealthMonitorView()
ControlHealthMonitorView * Isis::Directory::addControlHealthMonitorView ()
References Isis::Project::activeControl(), controlHealthMonitorView(), newWidgetAvailable(), and project().
Referenced by Isis::ControlHealthMonitorWorkOrder::execute().
addControlPointEditView()
ControlPointEditView * Isis::Directory::addControlPointEditView ()
References Isis::Project::activeControl(), cleanupControlPointEditViewWidget(), cnetModified(), controlPointEditView(), Isis::ControlPointEditView::controlPointEditWidget(), newWidgetAvailable(), project(), Isis::ControlPointEditWidget::setControl(), and Isis::ControlPointEditWidget::setSerialNumberList().
Referenced by createControlPoint(), deleteControlPoint(), and modifyControlPoint().
addCubeDnView()
CubeDnView * Isis::Directory::addCubeDnView (QString objectName = "")
Add the qview workspace to the window.
Returns
(CubeDnView*) The work space to display.
References activeControlModified(), cleanupCubeDnViewWidgets(), createControlPoint(), deleteControlPoint(), modifyControlPoint(), newWidgetAvailable(), project(), redrawMeasures(), and Isis::AbstractProjectItemView::setModel().
Referenced by Isis::CubeDnViewWorkOrder::execute().
addFootprint2DView()
Footprint2DView * Isis::Directory::addFootprint2DView (QString objectName = "")
Add the qmos view widget to the window.
Returns
(Footprint2DView*) A pointer to the Footprint2DView to display.
References activeControlModified(), cleanupFootprint2DViewWidgets(), cnetModified(), createControlPoint(), deleteControlPoint(), modifyControlPoint(), Isis::Footprint2DView::mosaicSceneWidget(), newWidgetAvailable(), project(), redrawMeasures(), and Isis::AbstractProjectItemView::setModel().
Referenced by Isis::Footprint2DViewWorkOrder::execute().
addImageFileListView()
ImageFileListWidget * Isis::Directory::addImageFileListView (QString objectName = "")
Add an imageFileList widget to the window.
Returns
(ImageFileListWidget *) A pointer to the widget to add to the window.
References cleanupFileListWidgets().
Referenced by Isis::ImageFileListViewWorkOrder::execute().
addJigsawRunWidget()
JigsawRunWidget * Isis::Directory::addJigsawRunWidget ()
References cleanupJigsawRunWidget(), jigsawRunWidget(), and newWidgetAvailable().
Referenced by Isis::JigsawWorkOrder::execute().
addMatrixView()
MatrixSceneWidget * Isis::Directory::addMatrixView ()
Add the matrix view widget to the window.
Returns
(MatrixSceneWidget*) The widget to view.
References cleanupMatrixViewWidgets(), and newWidgetAvailable().
Referenced by Isis::MatrixViewWorkOrder::execute().
addProjectItemTreeView()
ProjectItemTreeView * Isis::Directory::addProjectItemTreeView ()
Adds a ProjectItemTreeView to the window.
Returns
(ProjectItemTreeView *) The added view.
References Isis::AbstractProjectItemView::setModel().
addSensorInfoView()
SensorInfoWidget * Isis::Directory::addSensorInfoView (GuiCameraQsp camera)
Add sensor data view widget to the window.
Returns
(SensorInfoWidget*) The widget to view.
References cleanupSensorInfoWidgets(), and newWidgetAvailable().
Referenced by Isis::SensorGetInfoWorkOrder::execute().
addTargetInfoView()
TargetInfoWidget * Isis::Directory::addTargetInfoView (TargetBodyQsp target)
Add target body data view widget to the window.
Returns
(TargetInfoWidget*) The widget to view.
References cleanupTargetInfoWidgets(), and newWidgetAvailable().
Referenced by Isis::TargetGetInfoWorkOrder::execute().
addTemplateEditorView()
TemplateEditorWidget * Isis::Directory::addTemplateEditorView (Template * currentTemplate)
Add template editor view widget to the window.
Returns
(TemplateEditorWidget*) The widget to view.
References cleanupTemplateEditorWidgets(), Isis::Template::fileName(), Isis::FileName::name(), and newWidgetAvailable().
Referenced by Isis::TemplateEditViewWorkOrder::execute().
bundleObservationViews()
QList<BundleObservationView *> Isis::Directory::bundleObservationViews ()
clean()
void Isis::Directory::clean ()
Cleans directory of everything to do with the current project.
This function was implemented to be called from the Project::clear function to allow for a new project to be opened in IPCE.
References directoryCleaned().
Referenced by Isis::Project::clear().
cleanProject
void Isis::Directory::cleanProject (bool) signal
Referenced by Directory().
cleanupBundleObservationViews
void Isis::Directory::cleanupBundleObservationViews (QObject * obj) slot
Removes pointers to deleted BundleObservationView objects.
Referenced by addBundleObservationView().
cleanupCnetEditorViewWidgets
void Isis::Directory::cleanupCnetEditorViewWidgets (QObject * obj) slot
Removes pointers to deleted CnetEditorWidget objects.
References Isis::Project::activeControl(), Isis::Control::closeControlNet(), and project().
Referenced by addCnetEditorView().
cleanupControlPointEditViewWidget
void Isis::Directory::cleanupControlPointEditViewWidget (QObject * obj) slot
Delete the ControlPointEditWidget and set it's pointer to NULL.
References controlPointEditView().
Referenced by addControlPointEditView().
cleanupCubeDnViewWidgets
void Isis::Directory::cleanupCubeDnViewWidgets (QObject * obj) slot
Removes pointers to deleted CubeDnView objects.
Referenced by addCubeDnView().
cleanupFileListWidgets
void Isis::Directory::cleanupFileListWidgets (QObject * obj) slot
Removes pointers to deleted ImageFileListWidget objects.
Referenced by addImageFileListView().
cleanupFootprint2DViewWidgets
void Isis::Directory::cleanupFootprint2DViewWidgets (QObject * obj) slot
Removes pointers to deleted Footprint2DView objects.
Referenced by addFootprint2DView().
cleanupJigsawRunWidget
void Isis::Directory::cleanupJigsawRunWidget (QObject * obj) slot
References jigsawRunWidget().
Referenced by addJigsawRunWidget().
cleanupMatrixViewWidgets
void Isis::Directory::cleanupMatrixViewWidgets (QObject * obj) slot
Removes pointers to deleted MatrixSceneWidget objects.
Referenced by addMatrixView().
cleanupSensorInfoWidgets
void Isis::Directory::cleanupSensorInfoWidgets (QObject * obj) slot
Removes pointers to deleted SensorInfoWidget objects.
Referenced by addSensorInfoView().
cleanupTargetInfoWidgets
void Isis::Directory::cleanupTargetInfoWidgets (QObject * obj) slot
Removes pointers to deleted TargetInfoWidget objects.
Referenced by addTargetInfoView().
cleanupTemplateEditorWidgets
void Isis::Directory::cleanupTemplateEditorWidgets (QObject * obj) slot
Removes pointers to deleted TemplateEditorWidget objects.
Referenced by addTemplateEditorView().
closeView
void Isis::Directory::closeView (QWidget * widget) signal
cnetEditorViews()
QList< CnetEditorView * > Isis::Directory::cnetEditorViews ()
Returns a list of all the control network views for this directory.
Returns
QList<CnetEditorView *> A pointer list of all the CnetEditorWidget objects.
Referenced by Isis::CnetEditorViewWorkOrder::undoExecution().
cnetModified
void Isis::Directory::cnetModified () signal
Referenced by addCnetEditorView(), addControlPointEditView(), addFootprint2DView(), and Directory().
controlHealthMonitorView()
ControlHealthMonitorView * Isis::Directory::controlHealthMonitorView ()
Referenced by addControlHealthMonitorView().
controlPointEditView()
ControlPointEditView * Isis::Directory::controlPointEditView ()
Gets the ControlPointEditWidget associated with the Directory.
Returns
(ControlPointEditWidget *) Returns a pointer to the ControlPointEditWidget.
Referenced by addControlPointEditView(), cleanupControlPointEditViewWidget(), createControlPoint(), deleteControlPoint(), and modifyControlPoint().
controlUsedInCnetEditorWidget()
bool Isis::Directory::controlUsedInCnetEditorWidget (Control * control)
@description Return true if control is not currently being viewed in a CnetEditorWidget
Parameters
Control * Control used to search current CnetEditorWidgets
Returns
(bool) Returns true if control is currently being viewed in CnetEditorWidget
createControlPoint
void Isis::Directory::createControlPoint (double latitude, double longitude, Cube * cube = 0, bool isGroundSource = false) slot
Slot that is connected from a right mouse button operation on views.
Parameters
latitude (double) Latitude location where the control point was created
longitude (double) Longitude location where the control point was created
cube (Cube *) The Cube in the CubeDnView that was used to select location for new control point. This parameter will be empty if control point was selected from Footprint2DView.
isGroundSource (bool) Indicates whether the Cube in the CubeDnView that was used to select location for new control point is a ground source. This parameter will be empty if control point was selected from Footprint2DView.
References addControlPointEditView(), controlPointEditView(), Isis::ControlPointEditView::controlPointEditWidget(), Isis::ControlPointEditWidget::createControlPoint(), and Isis::ControlPointEditWidget::editPointId().
Referenced by addCubeDnView(), and addFootprint2DView().
cubeDnViews()
QList< CubeDnView * > Isis::Directory::cubeDnViews ()
Accessor for the list of CubeDnViews currently available.
Returns
QList<CubeDnView *> The list CubeDnView objects.
Referenced by Isis::CubeDnViewWorkOrder::execute(), and Isis::CubeDnViewWorkOrder::setupExecution().
deleteControlPoint
void Isis::Directory::deleteControlPoint (ControlPoint * controlPoint) slot
Slot that is connected from a middle mouse button operation on views.
Parameters
controlPoint (ControlPoint *) The control point selected from view for editing
References addControlPointEditView(), controlPointEditView(), Isis::ControlPointEditView::controlPointEditWidget(), Isis::ControlPointEditWidget::deletePoint(), Isis::ControlPoint::GetId(), and redrawMeasures().
Referenced by addCubeDnView(), addFootprint2DView(), and updateControlNetEditConnections().
directoryCleaned
void Isis::Directory::directoryCleaned () signal
Referenced by clean().
editMenuActions()
QList< QAction * > Isis::Directory::editMenuActions ()
Get the list of actions that the Directory can provide for the edit menu.
Returns
QList<QAction *> Returns a list of edit menu actions.
editPointId()
QString Isis::Directory::editPointId ()
Return the current control point id loaded in the ControlPointEditWidget.
Returns
QString Id of the control point loaded in the ControlPointEditWidget
Referenced by Isis::ControlPointGraphicsItem::paint().
fileMenuActions()
QList< QAction * > Isis::Directory::fileMenuActions ()
Get the list of actions that the Directory can provide for the file menu.
Returns
QList<QAction *> Returns a list of file menu actions.
footprint2DViews()
QList< Footprint2DView * > Isis::Directory::footprint2DViews ()
Accessor for the list of Footprint2DViews currently available.
Returns
QList<Footprint2DView *> The list of MosaicSceneWidget objects.
Referenced by Isis::Footprint2DViewWorkOrder::execute(), and Isis::Footprint2DViewWorkOrder::setupExecution().
helpMenuActions()
QList< QAction * > Isis::Directory::helpMenuActions ()
Get the list of actions that the Directory can provide for the help menu.
Returns
QList<QAction *> Returns a list of help menu actions.
imageFileListViews()
QList< ImageFileListWidget * > Isis::Directory::imageFileListViews ()
Accessor for the list of ImageFileListWidgets currently available.
Returns
QList<ImageFileListWidget *> The list of ImageFileListWidgets.
Referenced by Isis::ImageFileListViewWorkOrder::execute(), and Isis::ImageFileListViewWorkOrder::setupExecution().
jigsawRunWidget()
JigsawRunWidget * Isis::Directory::jigsawRunWidget ()
Referenced by addJigsawRunWidget(), and cleanupJigsawRunWidget().
matrixViews()
QList< MatrixSceneWidget * > Isis::Directory::matrixViews ()
Accessor for the list of MatrixSceneWidgets currently available.
Returns
QList<MatrixSceneWidget *> The list of MatrixSceneWidget objects.
Referenced by Isis::MatrixViewWorkOrder::setupExecution(), and Isis::MatrixViewWorkOrder::undoExecution().
model()
ProjectItemModel * Isis::Directory::model ()
Gets the ProjectItemModel for this directory.
Returns
(ProjectItemModel *) Returns a pointer to the ProjectItemModel.
Referenced by Isis::CubeDnViewWorkOrder::execute(), Isis::Footprint2DViewWorkOrder::execute(), Isis::RemoveImagesWorkOrder::execute(), Isis::JigsawSetupDialog::JigsawSetupDialog(), Isis::Project::setActiveControl(), Isis::Project::setActiveImageList(), Isis::RemoveImagesWorkOrder::setupExecution(), Isis::ImportImagesWorkOrder::undoExecution(), Isis::ImportMapTemplateWorkOrder::undoExecution(), Isis::ImportRegistrationTemplateWorkOrder::undoExecution(), and Isis::ImportShapesWorkOrder::undoExecution().
modifyControlPoint
void Isis::Directory::modifyControlPoint (ControlPoint * controlPoint, QString serialNumber = "") slot
Slot that is connected from a left mouse button operation on views.
Parameters
controlPoint (ControlPoint *) The control point selected from view for editing
serialNumber (QString) The serial number of Cube that was used to select control point from the CubeDnView. This parameter will be empty if control point was selected from Footprint2DView.
References addControlPointEditView(), controlPointEditView(), Isis::ControlPointEditView::controlPointEditWidget(), Isis::ControlPoint::GetId(), redrawMeasures(), and Isis::ControlPointEditWidget::setEditPoint().
Referenced by addCnetEditorView(), addCubeDnView(), and addFootprint2DView().
newDockAvailable
void Isis::Directory::newDockAvailable (QMainWindow * newWidget) signal
newWarning
void Isis::Directory::newWarning () signal
Referenced by showWarning().
newWidgetAvailable
void Isis::Directory::newWidgetAvailable (QWidget * newWidget) signal
Referenced by addBundleObservationView(), addCnetEditorView(), addControlHealthMonitorView(), addControlPointEditView(), addCubeDnView(), addFootprint2DView(), addJigsawRunWidget(), addMatrixView(), addSensorInfoView(), addTargetInfoView(), and addTemplateEditorView().
permToolBarActions()
QList< QAction * > Isis::Directory::permToolBarActions ()
Get the list of actions that the Directory can provide for the permanent Tool Bar.
Returns
QList<QAction *> Returns a list of permanent tool bar menu actions.
progressBars()
QList< QProgressBar * > Isis::Directory::progressBars ()
Gets the ControlNetEditor associated with this the Directory.
Returns
(ControlNetEditor *) Returns a pointer to the ControlNetEditor.
Returns a list of progress bars associated with this Directory.
Returns
QList<QProgressBar *>
project()
Project * Isis::Directory::project () const
Gets the Project for this directory.
Returns
(Project *) Returns a pointer to the Project.
Referenced by addCnetEditorView(), addControlHealthMonitorView(), addControlPointEditView(), addCubeDnView(), addFootprint2DView(), cleanupCnetEditorViewWidgets(), Isis::ImageTreeWidget::contextMenuEvent(), Isis::MosaicSceneItem::contextMenuEvent(), Isis::MosaicSceneWidget::contextMenuEvent(), Isis::ControlHealthMonitorView::ControlHealthMonitorView(), Isis::ControlPointEditWidget::ControlPointEditWidget(), Directory(), Isis::ControlNetTool::loadNetwork(), Isis::MosaicControlNetTool::loadNetwork(), redoAction(), save(), Isis::TemplateEditorWidget::saveAsText(), Isis::ControlPointEditWidget::setControlFromActive(), setHistoryContainer(), Isis::MosaicSceneWidget::supportedActions(), Isis::ControlNetTool::toolPadAction(), undoAction(), and updateRecentProjects().
projectMenuActions()
QList< QAction * > Isis::Directory::projectMenuActions ()
Get the list of actions that the Directory can provide for the project menu.
Returns
QList<QAction *> Returns a list of project menu actions.
recentProjectsList()
QStringList Isis::Directory::recentProjectsList ()
Public accessor for the list of recent projects.
Returns
QStringList List of recent projects.
redoAction()
QAction * Isis::Directory::redoAction ()
Creates an Action to redo the last action.
Returns
(QAction *) Returns an action pointer to redo the last action.
References project(), and Isis::Project::undoStack().
redrawMeasures
void Isis::Directory::redrawMeasures () signal
Referenced by addCubeDnView(), addFootprint2DView(), deleteControlPoint(), and modifyControlPoint().
save()
void Isis::Directory::save (QXmlStreamWriter & stream, FileName newProjectRoot) const
Save the directory to an XML file.
Parameters
stream The XML stream writer
newProjectRoot The FileName of the project this Directory is attached to.
References project(), Isis::CnetEditorView::save(), Isis::CubeDnView::save(), Isis::Footprint2DView::save(), and Isis::ImageFileListWidget::save().
sensorInfoViews()
QList< SensorInfoWidget * > Isis::Directory::sensorInfoViews ()
Accessor for the list of SensorInfoWidgets currently available.
Returns
QList<SensorInfoWidget *> The list of SensorInfoWidget objects.
Referenced by Isis::SensorGetInfoWorkOrder::isExecutable().
setHistoryContainer()
void Isis::Directory::setHistoryContainer (QDockWidget * historyContainer)
Set up the history info in the history dockable widget.
Parameters
historyContainer The widget to fill.
References project().
setRecentProjectsList()
void Isis::Directory::setRecentProjectsList (QStringList recentProjects)
Add recent projects to the recent projects list.
Parameters
recentProjects List of projects to add to list.
settingsMenuActions()
QList< QAction * > Isis::Directory::settingsMenuActions ()
Get the list of actions that the Directory can provide for the settings menu.
Returns
QList<QAction *> Returns a list of menu actions for the settings.
setWarningContainer()
void Isis::Directory::setWarningContainer (QDockWidget * warningContainer)
Set up the warning info in the warning dockable widget.
Parameters
warningContainer The widget to fill.
showWarning() [1/2]
void Isis::Directory::showWarning (QString text)
Displays a Warning.
Parameters
text The text to be displayed as a warning.
References newWarning().
Referenced by Isis::Project::open(), and Isis::Project::warn().
showWarning() [2/2]
template<typename Data > void Isis::Directory::showWarning (QString text, Data data) inline
Shows warning text for a Widget.
Parameters
text The warning text.
Data The Widget object we are passing the warning to.
supportedActions()
template<typename DataType > QList<QAction *> Isis::Directory::supportedActions (DataType data) inline
Returns a list of supported actions for a WorkOrder.
Parameters
data The WorkOrder type we are using.
Returns
QList<QAction *> A list of supported actions.
References Isis::WorkOrder::clone(), Isis::WorkOrder::isExecutable(), and Isis::WorkOrder::setData().
Referenced by Isis::ImageTreeWidget::contextMenuEvent(), Isis::MosaicSceneItem::contextMenuEvent(), and Isis::MosaicSceneWidget::contextMenuEvent().
targetInfoViews()
QList< TargetInfoWidget * > Isis::Directory::targetInfoViews ()
Accessor for the list of TargetInfoWidgets currently available.
Returns
QList<TargetInfoWidget *> The list of TargetInfoWidget objects.
Referenced by Isis::TargetGetInfoWorkOrder::isExecutable().
templateEditorViews()
QList< TemplateEditorWidget * > Isis::Directory::templateEditorViews ()
Accessor for the list of TemplateEditorWidgets currently available.
Returns
QList<TemplateEditorWidget *> The list of TemplateEditorWidget objects.
Referenced by Isis::TemplateEditViewWorkOrder::isExecutable().
toolPadActions()
QList< QAction * > Isis::Directory::toolPadActions ()
Get the list of actions that the Directory can provide for the Tool Pad.
Returns
QList<QAction *> Returns a list of Tool Pad actions.
undoAction()
QAction * Isis::Directory::undoAction ()
Creates an Action to undo the last action.
Returns
(QAction *) Returns an action pointer to undo the last action.
References project(), and Isis::Project::undoStack().
updateControlNetEditConnections
void Isis::Directory::updateControlNetEditConnections () slot
Updates the SIGNAL/SLOT connections for the cotrol net editor.
References deleteControlPoint().
updateRecentProjects [1/2]
void Isis::Directory::updateRecentProjects () slot
Loads and displays a list of recently opened projects in the file menu.
References Isis::FileName::fileExists(), and Isis::Project::maxRecentProjects().
Referenced by Directory().
updateRecentProjects [2/2]
void Isis::Directory::updateRecentProjects (Project * project) slot
Adds a new Project object to the list of recent projects if it has not already been added.
Parameters
project A pointer to the Project to add.
References project(), and Isis::Project::projectRoot().
viewMenuActions()
QList< QAction * > Isis::Directory::viewMenuActions ()
Get the list of actions that the Directory can provide for the view menu.
Returns
QList<QAction *> Returns a list of view menu actions.
warningWidget()
QWidget * Isis::Directory::warningWidget ()
Returns a pointer to the warning widget.
Returns
(QWidget *) The WarningTreeWidget pointer.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/Directory/Directory.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/Directory/Directory.cpp