Isis Developer Reference: Isis::ApolloPanoramicDetectorMap Class Reference
Isis::ApolloPanoramicDetectorMap Class Reference
Convert between parent image (aka encoder aka machine) coordinates and detector coordinates.
#include <ApolloPanoramicDetectorMap.h>
Public Member Functions
ApolloPanoramicDetectorMap (Camera *parent, double etMiddle, double lineRate, Pvl *lab)
Construct a detector map for line scan cameras.
virtual ~ApolloPanoramicDetectorMap ()
Destroys ApolloPanoramicDetectorMap object.
virtual bool SetParent (const double sample, const double line)
This method sets dector sample line coordinates from given cube coordinates.
virtual bool SetDetector (const double sample, const double line)
This method sets cube sample line coordinates from given Dector coordinates.
void SetLineRate (const double lineRate)
Reset the line rate.
double LineRate () const
Return the time in seconds between scan lines.
double meanResidual ()
Mean (average) of interior orientation residual vector lengths, accesor.
double maxResidual ()
Max interior orientation residual vector length, accesor.
double stdevResidual ()
Standard deviation of interior orientation residual vector lengths, accesor.
virtual bool SetParent (const double sample, const double line, const double deltaT)
Compute detector position from a parent image coordinate.
double AdjustedStartingSample () const
Return the starting detector sample adjusted for summation.
double AdjustedStartingLine () const
Return the starting detector line adjusted for summation.
double ParentSample () const
Return parent sample.
double ParentLine () const
Return parent line.
double DetectorSample () const
Return detector sample.
double DetectorLine () const
Return detector line.
void SetStartingDetectorSample (const double sample)
Set the starting detector sample.
void SetStartingDetectorLine (const double line)
Set the starting detector line.
void SetDetectorSampleSumming (const double summing)
Set sample summing mode.
void SetDetectorLineSumming (const double summing)
Set line summing mode.
virtual double SampleScaleFactor () const
Return scaling factor for computing sample resolution.
virtual double LineScaleFactor () const
Return scaling factor for computing line resolution.
virtual double exposureDuration (const double sample, const double line, const int band) const
This virtual method is for returning the exposure duration of a given pixel.
Protected Attributes
Camera * p_camera
Pointer to the camera.
double p_parentSample
The parent sample calculated from the detector.
double p_parentLine
The parent line calculated from the detector.
double p_detectorLine
Detector coordinate line value.
double p_detectorSample
Detector coordinate sample value.
double p_detectorSampleSumming
The scaling factor for computing sample resolution.
double p_detectorLineSumming
The scaling factor for computing line resolution.
double p_startingDetectorSample
Detector start coordinate sample value.
double p_startingDetectorLine
Detector start coordinate line value.
double p_ss
Start sample.
double p_sl
Start line.
Detailed Description
Convert between parent image (aka encoder aka machine) coordinates and detector coordinates.
This class is used to convert between parent image (aka encoder aka machine) coordinates (sample/line) and detector coordinates for a the Apollo Panoramic Image.
Author
2011-11-21 Orrin Thomas
Constructor & Destructor Documentation
ApolloPanoramicDetectorMap()
Isis::ApolloPanoramicDetectorMap::ApolloPanoramicDetectorMap (Camera * parent, double etMiddle, double lineRate, Pvl * lab) inline
Construct a detector map for line scan cameras.
Parameters
parent The parent Camera Model
etMiddle Time of the center line, line 0 after interior orientation
lineRate the time in seconds between lines (msec)
lab The labels to use for the camera creation
~ApolloPanoramicDetectorMap()
virtual Isis::ApolloPanoramicDetectorMap::~ApolloPanoramicDetectorMap () inline virtual
Destroys ApolloPanoramicDetectorMap object.
Member Function Documentation
AdjustedStartingLine()
double Isis::CameraDetectorMap::AdjustedStartingLine () const inherited
Return the starting detector line adjusted for summation.
Returns
(double) The starting line
References Isis::CameraDetectorMap::p_sl.
AdjustedStartingSample()
double Isis::CameraDetectorMap::AdjustedStartingSample () const inherited
Return the starting detector sample adjusted for summation.
Returns
(double) The starting sample
References Isis::CameraDetectorMap::p_ss.
DetectorLine()
double Isis::CameraDetectorMap::DetectorLine () const inherited
Return detector line.
Returns
(double) The detector line
References Isis::CameraDetectorMap::p_detectorLine.
Referenced by Isis::Camera::SetImage().
DetectorSample()
double Isis::CameraDetectorMap::DetectorSample () const inherited
Return detector sample.
Returns
(double) The detector sample
References Isis::CameraDetectorMap::p_detectorSample.
Referenced by Isis::Camera::SetImage().
exposureDuration()
double Isis::CameraDetectorMap::exposureDuration (const double sample, const double line, const int band) const virtual inherited
This virtual method is for returning the exposure duration of a given pixel.
For framing cameras, exposure duration is not available so it throws an error.
Parameters
sample The sample of the desired pixel.
line The line of the desired pixel.
band The band of the desired pixel.
Returns
double The exposure duration for the desired pixel in seconds.
Exceptions
IException::Programmer "Exposure duration is only available for LineScan, VariableLineScan, and PushFrame Cameras."
Reimplemented in Isis::NirsDetectorMap, Isis::VariableLineScanCameraDetectorMap, Isis::PushFrameCameraDetectorMap, and Isis::LineScanCameraDetectorMap.
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by Isis::Camera::exposureDuration().
LineRate()
double Isis::ApolloPanoramicDetectorMap::LineRate () const inline virtual
Return the time in seconds between scan lines.
Returns
double Time in seconds between scan lines
Reimplemented from Isis::CameraDetectorMap.
LineScaleFactor()
double Isis::CameraDetectorMap::LineScaleFactor () const virtual inherited
Return scaling factor for computing line resolution.
Returns
(double) The scaling factor for line resolution
References Isis::CameraDetectorMap::p_detectorLineSumming.
Referenced by Isis::Camera::LineResolution(), Isis::Camera::ObliqueLineResolution(), Isis::ThemisIrCamera::SetBand(), Isis::PushFrameCameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetParent(), and Isis::PushFrameCameraDetectorMap::TotalFramelets().
maxResidual()
double Isis::ApolloPanoramicDetectorMap::maxResidual () inline
Max interior orientation residual vector length, accesor.
Returns
double Max interior orientation residual vector length
References Isis::ApolloPanIO::maxResiduals().
Referenced by Isis::ApolloPanoramicCamera::ApolloPanoramicCamera().
meanResidual()
double Isis::ApolloPanoramicDetectorMap::meanResidual () inline
Mean (average) of interior orientation residual vector lengths, accesor.
Returns
double Mean of interior orientation residual vector lengths
References Isis::ApolloPanIO::meanResiduals().
Referenced by Isis::ApolloPanoramicCamera::ApolloPanoramicCamera().
ParentLine()
double Isis::CameraDetectorMap::ParentLine () const inherited
Return parent line.
Returns
(double) The parent line
References Isis::CameraDetectorMap::p_parentLine.
Referenced by Isis::Camera::SetRightAscensionDeclination().
ParentSample()
double Isis::CameraDetectorMap::ParentSample () const inherited
Return parent sample.
Returns
(double) The parent sample
References Isis::CameraDetectorMap::p_parentSample.
Referenced by Isis::Camera::SetRightAscensionDeclination().
SampleScaleFactor()
double Isis::CameraDetectorMap::SampleScaleFactor () const virtual inherited
Return scaling factor for computing sample resolution.
Returns
(double) The scaling factor for sample resolution
References Isis::CameraDetectorMap::p_detectorSampleSumming.
Referenced by Isis::Camera::ObliqueSampleResolution(), and Isis::Camera::SampleResolution().
SetDetector()
bool Isis::ApolloPanoramicDetectorMap::SetDetector (const double sample, const double line) virtual
This method sets cube sample line coordinates from given Dector coordinates.
Parameters
sample dector sample coordinate
line detector line coordinate
Returns
bool Always returns true
Reimplemented from Isis::CameraDetectorMap.
SetDetectorLineSumming()
void Isis::CameraDetectorMap::SetDetectorLineSumming (const double summing) inline inherited
Set line summing mode.
Use this method to specify if detector lines are summed/averaged. That is, one image lines represents the average of N detectors. If not set the default is 1.
Parameters
summing Line summing mode
References Isis::CameraDetectorMap::p_detectorLineSumming.
Referenced by Isis::CrismCamera::CrismCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::MarciCamera::MarciCamera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), and Isis::ThemisVisCamera::ThemisVisCamera().
SetDetectorSampleSumming()
void Isis::CameraDetectorMap::SetDetectorSampleSumming (const double summing) inline inherited
Set sample summing mode.
Use this method to specify if detector samples are summed/averaged. That is, one image sample represents the average of N detectors. If not set the default is 1.
Parameters
summing Sample summing mode
References Isis::CameraDetectorMap::p_detectorSampleSumming.
Referenced by Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::MarciCamera::MarciCamera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), and Isis::ThemisVisCamera::ThemisVisCamera().
SetLineRate()
void Isis::ApolloPanoramicDetectorMap::SetLineRate (const double lineRate) inline
Reset the line rate.
Use this method to reset the time between lines. Usually this will not need to be done unless the rate changes between bands.
Parameters
lineRate the time in seconds between lines
Returns
void
SetParent() [1/2]
bool Isis::ApolloPanoramicDetectorMap::SetParent (const double sample, const double line) virtual
This method sets dector sample line coordinates from given cube coordinates.
Parameters
sample cube sample coordinate
line cube line coordinate
Returns
bool Always returns true
Reimplemented from Isis::CameraDetectorMap.
SetParent() [2/2]
bool Isis::CameraDetectorMap::SetParent (const double sample, const double line, const double deltaT) virtual inherited
Compute detector position from a parent image coordinate.
This method will compute the detector position from the parent line/sample coordinate and an offset from the currently set time in seconds. If the time has not already been set, the input offset is not applied.
Parameters
sample Sample number in the parent image
line Line number in the parent image
deltaT option time offset from center of exposure in seconds
Returns
conversion successful
Reimplemented in Isis::VariableLineScanCameraDetectorMap, Isis::RollingShutterCameraDetectorMap, Isis::PushFrameCameraDetectorMap, and Isis::LineScanCameraDetectorMap.
References Isis::iTime::Et(), Isis::Spice::isTimeSet(), Isis::CameraDetectorMap::p_camera, Isis::CameraDetectorMap::p_detectorLine, Isis::CameraDetectorMap::p_detectorLineSumming, Isis::CameraDetectorMap::p_detectorSample, Isis::CameraDetectorMap::p_detectorSampleSumming, Isis::CameraDetectorMap::p_parentLine, Isis::CameraDetectorMap::p_parentSample, Isis::CameraDetectorMap::p_sl, Isis::CameraDetectorMap::p_ss, Isis::Sensor::setTime(), and Isis::Spice::time().
SetStartingDetectorLine()
void Isis::CameraDetectorMap::SetStartingDetectorLine (const double line) inline inherited
Set the starting detector line.
Use this method to specify the starting detector that represents the first image line in the cube. If not set the default is 1.
Parameters
line Starting detector line
References Isis::CameraDetectorMap::p_startingDetectorLine.
Referenced by Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::JunoCamera::JunoCamera(), Isis::MdisCamera::MdisCamera(), and Isis::RosettaOsirisCamera::RosettaOsirisCamera().
SetStartingDetectorSample()
void Isis::CameraDetectorMap::SetStartingDetectorSample (const double sample) inline inherited
Set the starting detector sample.
Use this method to specify the starting detector that represents the first image sample in the cube. If not set the default is 1.
Parameters
sample Starting detector sample
References Isis::CameraDetectorMap::p_startingDetectorSample.
Referenced by Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::CTXCamera::CTXCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::MdisCamera::MdisCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), and Isis::RosettaOsirisCamera::RosettaOsirisCamera().
stdevResidual()
double Isis::ApolloPanoramicDetectorMap::stdevResidual () inline
Standard deviation of interior orientation residual vector lengths, accesor.
Returns
double Standard deviation of interior orientation residual vector lengths
References Isis::ApolloPanIO::stdevResiduals().
Referenced by Isis::ApolloPanoramicCamera::ApolloPanoramicCamera().
Member Data Documentation
p_camera
Camera* Isis::CameraDetectorMap::p_camera protected inherited
Pointer to the camera.
Referenced by Isis::CameraDetectorMap::CameraDetectorMap(), Isis::LineScanCameraDetectorMap::SetDetector(), Isis::RadarPulseMap::SetDetector(), Isis::VariableLineScanCameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetFramelet(), Isis::RadarPulseMap::SetParent(), Isis::CameraDetectorMap::SetParent(), Isis::LineScanCameraDetectorMap::SetParent(), Isis::RollingShutterCameraDetectorMap::SetParent(), Isis::VariableLineScanCameraDetectorMap::SetParent(), and Isis::PushFrameCameraDetectorMap::TotalFramelets().
p_detectorLine
double Isis::CameraDetectorMap::p_detectorLine protected inherited
Detector coordinate line value.
Referenced by Isis::CameraDetectorMap::DetectorLine(), Isis::CameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::RadarPulseMap::SetParent(), Isis::CameraDetectorMap::SetParent(), Isis::LineScanCameraDetectorMap::SetParent(), Isis::PushFrameCameraDetectorMap::SetParent(), Isis::RollingShutterCameraDetectorMap::SetParent(), and Isis::VariableLineScanCameraDetectorMap::SetParent().
p_detectorLineSumming
double Isis::CameraDetectorMap::p_detectorLineSumming protected inherited
The scaling factor for computing line resolution.
Referenced by Isis::CameraDetectorMap::CameraDetectorMap(), Isis::CameraDetectorMap::LineScaleFactor(), Isis::CameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetDetectorLineSumming(), Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_detectorSample
double Isis::CameraDetectorMap::p_detectorSample protected inherited
Detector coordinate sample value.
Referenced by Isis::CameraDetectorMap::DetectorSample(), Isis::CameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_detectorSampleSumming
double Isis::CameraDetectorMap::p_detectorSampleSumming protected inherited
The scaling factor for computing sample resolution.
Referenced by Isis::CameraDetectorMap::CameraDetectorMap(), Isis::CameraDetectorMap::SampleScaleFactor(), Isis::CameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetDetectorSampleSumming(), Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_parentLine
double Isis::CameraDetectorMap::p_parentLine protected inherited
The parent line calculated from the detector.
Referenced by Isis::CameraDetectorMap::ParentLine(), Isis::CameraDetectorMap::SetDetector(), Isis::LineScanCameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetDetector(), Isis::RadarPulseMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::VariableLineScanCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetParent(), Isis::PushFrameCameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_parentSample
double Isis::CameraDetectorMap::p_parentSample protected inherited
The parent sample calculated from the detector.
Referenced by Isis::CameraDetectorMap::ParentSample(), Isis::CameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetParent(), Isis::PushFrameCameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_sl
double Isis::CameraDetectorMap::p_sl protected inherited
Start line.
Referenced by Isis::CameraDetectorMap::AdjustedStartingLine(), Isis::CameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_ss
double Isis::CameraDetectorMap::p_ss protected inherited
Start sample.
Referenced by Isis::CameraDetectorMap::AdjustedStartingSample(), Isis::CameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_startingDetectorLine
double Isis::CameraDetectorMap::p_startingDetectorLine protected inherited
Detector start coordinate line value.
Referenced by Isis::CameraDetectorMap::CameraDetectorMap(), and Isis::CameraDetectorMap::SetStartingDetectorLine().
p_startingDetectorSample
double Isis::CameraDetectorMap::p_startingDetectorSample protected inherited
Detector start coordinate sample value.
Referenced by Isis::CameraDetectorMap::CameraDetectorMap(), and Isis::CameraDetectorMap::SetStartingDetectorSample().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/apollo/objs/ApolloPanoramicCamera/ApolloPanoramicDetectorMap.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/apollo/objs/ApolloPanoramicCamera/ApolloPanoramicDetectorMap.cpp