Isis Developer Reference: Isis::SpectralDefinition2D Class Reference
Isis::SpectralDefinition2D Class Reference
A Spectral definition that includes wavelength and center values for each (line, sample) coordinate.
#include <SpectralDefinition2D.h>
Public Member Functions
SpectralDefinition2D (FileName smileDefFilename)
Construct a SpectralDefinition2D object using a filename.
~SpectralDefinition2D ()
destructor
Spectel findSpectel (const int sample, const int line, const int band) const
Get the Spectel at some sample, line, band (associated with your input/calibration file)
Spectel findSpectelByWavelength (const double wavelength, const int sectionNumber) const
Spectel findSpectel (const Spectel &inSpectel, const int sectionNumber) const
virtual int sectionCount () const
Returns the number of sections in the calibration image.
int sectionNumber (int s, int l, int b) const
returns section number given (s,l,b)
QString toString ()
Returns QString representation of SpectralDefinition2D.
void operator() (Buffer &in) const
Internal function used to help read-in a calibration cube.
virtual int sampleCount () const
Returns the number of samples in the calibration image.
virtual int lineCount () const
Returns the number of line in the calibration image.
virtual int bandCount () const
Returns the number of bands in the calibration image.
Protected Attributes
int m_ns
Number of samples in input Cube.
int m_nl
Number of lines in input Cube.
int m_nb
Number of bands in input Cube.
Detailed Description
A Spectral definition that includes wavelength and center values for each (line, sample) coordinate.
Author
2015-05-21 Kristin Berry
Constructor & Destructor Documentation
SpectralDefinition2D()
Isis::SpectralDefinition2D::SpectralDefinition2D (FileName smileDefFilename)
Construct a SpectralDefinition2D object using a filename.
Isis Cubes are the only supported format.
Author
2015-05021 Kristin Berry
Parameters
smileDefFilename the filename of the spectral definition
References _FILEINFO_, Isis::Cube::bandCount(), Isis::ProcessByBrick::BandsFirst, Isis::FileName::expanded(), Isis::ProcessByBrick::Finalize(), Isis::Cube::lineCount(), Isis::SpectralDefinition::m_nb, Isis::SpectralDefinition::m_nl, Isis::SpectralDefinition::m_ns, Isis::ProcessBySample::ProcessCubeInPlace(), Isis::Process::Progress(), Isis::Cube::sampleCount(), Isis::ProcessBySample::SetInputCube(), Isis::ProcessByBrick::SetProcessingDirection(), Isis::Progress::SetText(), Isis::FileName::toString(), Isis::IException::Unknown, and Isis::IException::User.
~SpectralDefinition2D()
Isis::SpectralDefinition2D::~SpectralDefinition2D ()
destructor
Member Function Documentation
bandCount()
int Isis::SpectralDefinition::bandCount () const virtual inherited
Returns the number of bands in the calibration image.
References Isis::SpectralDefinition::m_nb.
findSpectel() [1/2]
Spectel Isis::SpectralDefinition2D::findSpectel (const int sample, const int line, const int band) const virtual
Get the Spectel at some sample, line, band (associated with your input/calibration file)
Author
2015-05-21 Kristin Berry
Parameters
sample input sample
line input line. Not used for a 2D definition
band input band
Returns
Spectel
Implements Isis::SpectralDefinition.
findSpectel() [2/2]
Spectel Isis::SpectralDefinition2D::findSpectel (const Spectel & inSpectel, const int sectionNumber) const virtual
Implements Isis::SpectralDefinition.
References Isis::Spectel::centerWavelength(), Isis::Pixel::sample(), and sectionNumber().
findSpectelByWavelength()
Spectel Isis::SpectralDefinition2D::findSpectelByWavelength (const double wavelength, const int sectionNumber) const virtual
Implements Isis::SpectralDefinition.
lineCount()
int Isis::SpectralDefinition::lineCount () const virtual inherited
Returns the number of line in the calibration image.
References Isis::SpectralDefinition::m_nl.
operator()()
void Isis::SpectralDefinition2D::operator() (Buffer & in) const
Internal function used to help read-in a calibration cube.
pull information out of the input cube and store it. Each buffer contains two pixels, one center and one width
References Isis::Buffer::Band(), Isis::NULL8, and Isis::Buffer::Sample().
sampleCount()
int Isis::SpectralDefinition::sampleCount () const virtual inherited
Returns the number of samples in the calibration image.
References Isis::SpectralDefinition::m_ns.
sectionCount()
int Isis::SpectralDefinition2D::sectionCount () const virtual
Returns the number of sections in the calibration image.
Reimplemented from Isis::SpectralDefinition.
sectionNumber()
int Isis::SpectralDefinition2D::sectionNumber (int s, int l, int b) const virtual
returns section number given (s,l,b)
Implements Isis::SpectralDefinition.
Referenced by findSpectel().
toString()
QString Isis::SpectralDefinition2D::toString ()
Returns QString representation of SpectralDefinition2D.
Author
Kristin L Berry
Returns
QString String representation of SpectralDefinition2D
References Isis::Spectel::centerWavelength(), and Isis::Spectel::filterWidth().
Member Data Documentation
m_nb
int Isis::SpectralDefinition::m_nb protected inherited
Number of bands in input Cube.
Referenced by Isis::SpectralDefinition::bandCount(), Isis::SpectralDefinition1D::SpectralDefinition1D(), and SpectralDefinition2D().
m_nl
int Isis::SpectralDefinition::m_nl protected inherited
Number of lines in input Cube.
Referenced by Isis::SpectralDefinition::lineCount(), Isis::SpectralDefinition1D::SpectralDefinition1D(), and SpectralDefinition2D().
m_ns
int Isis::SpectralDefinition::m_ns protected inherited
Number of samples in input Cube.
Referenced by Isis::SpectralDefinition::sampleCount(), Isis::SpectralDefinition1D::SpectralDefinition1D(), and SpectralDefinition2D().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/SpectralDefinition2D/SpectralDefinition2D.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/SpectralDefinition2D/SpectralDefinition2D.cpp