Isis Developer Reference: Isis::HistogramItem Class Reference
Isis::HistogramItem Class Reference
This is the (qwt) plot item for a histogram.
#include <HistogramItem.h>
Public Types
enum HistogramAttribute { Auto = 0 , Xfy = 1 }
Public Member Functions
HistogramItem (const QString &title=QString())
Constructor 2.
HistogramItem (const QwtText &title)
Constructor 1.
virtual ~HistogramItem ()
Destructor.
void setData (const QwtIntervalSeriesData &data)
Overridden method to set the data in the histogram.
const QwtIntervalSeriesData & data () const
Returns this item's data.
QList< QPointF > getVertices () const
This method returns a list of points which are the vertices of the selected area (by the rubberband) on the cvp.
void setVertices (const QList< QPoint > &points)
This method sets the vertices of the selected area on the cvp.
CubeViewport * getViewPort () const
This method returns the cube view port associated with the curve.
void setViewPort (CubeViewport *cvp)
This method sets the view port.
void setColor (const QColor &)
Set the color of the hist.
QColor color () const
Return the color of the item.
virtual QRectF boundingRect () const
Returns the bounding rectangle of the item.
virtual int rtti () const
virtual void draw (QPainter *, const QwtScaleMap &xMap, const QwtScaleMap &yMap, const QRectF &) const
void setBaseline (double reference)
double baseline () const
Returns the baseline.
void setHistogramAttribute (HistogramAttribute, bool on=true)
bool testHistogramAttribute (HistogramAttribute) const
Protected Member Functions
virtual void drawBar (QPainter *, Qt::Orientation o, const QRect &) const
This method draws the bars of the bar graph.
Detailed Description
This is the (qwt) plot item for a histogram.
This draws bars for each of the histogram bins.
Author
????-??-?? Unknown
Member Enumeration Documentation
HistogramAttribute
enum Isis::HistogramItem::HistogramAttribute
Enumerator
Auto
Xfy
Constructor & Destructor Documentation
HistogramItem() [1/2]
Isis::HistogramItem::HistogramItem (const QString & title = QString()) explicit
Constructor 2.
Parameters
title
HistogramItem() [2/2]
Isis::HistogramItem::HistogramItem (const QwtText & title) explicit
Constructor 1.
Parameters
title
~HistogramItem()
Isis::HistogramItem::~HistogramItem () virtual
Destructor.
Member Function Documentation
baseline()
double Isis::HistogramItem::baseline () const
Returns the baseline.
Returns
double
Referenced by draw().
boundingRect()
QRectF Isis::HistogramItem::boundingRect () const virtual
Returns the bounding rectangle of the item.
Returns
QwtDoubleRect
References Xfy.
color()
QColor Isis::HistogramItem::color () const
Return the color of the item.
Returns
QColor
Referenced by drawBar(), and setColor().
data()
const QwtIntervalSeriesData & Isis::HistogramItem::data () const
Returns this item's data.
Returns
Referenced by draw(), and setData().
draw()
void Isis::HistogramItem::draw (QPainter * painter, const QwtScaleMap & xMap, const QwtScaleMap & yMap, const QRectF &) const virtual
Parameters
painter
xMap
yMap
References baseline(), data(), drawBar(), and Xfy.
drawBar()
void Isis::HistogramItem::drawBar (QPainter * painter, Qt::Orientation o, const QRect & rect) const protected virtual
This method draws the bars of the bar graph.
Parameters
painter
rect
References color().
Referenced by draw().
getVertices()
QList< QPointF > Isis::HistogramItem::getVertices () const
This method returns a list of points which are the vertices of the selected area (by the rubberband) on the cvp.
Returns
QList<QPoint>
getViewPort()
CubeViewport * Isis::HistogramItem::getViewPort () const
This method returns the cube view port associated with the curve.
Returns
CubeViewport*
Referenced by setVertices().
rtti()
int Isis::HistogramItem::rtti () const virtual
Returns
int
setBaseline()
void Isis::HistogramItem::setBaseline (double reference)
Parameters
reference
setColor()
void Isis::HistogramItem::setColor (const QColor & color)
Set the color of the hist.
item.
Parameters
color
References color().
Referenced by Isis::HistogramWidget::HistogramWidget().
setData()
void Isis::HistogramItem::setData (const QwtIntervalSeriesData & data)
Overridden method to set the data in the histogram.
Parameters
data
References data().
Referenced by Isis::HistogramWidget::setHistogram().
setHistogramAttribute()
void Isis::HistogramItem::setHistogramAttribute (HistogramAttribute attribute, bool on = true)
Parameters
attribute
on
setVertices()
void Isis::HistogramItem::setVertices (const QList< QPoint > & points)
This method sets the vertices of the selected area on the cvp.
Parameters
points
References getViewPort(), and Isis::CubeViewport::viewportToCube().
setViewPort()
void Isis::HistogramItem::setViewPort (CubeViewport * cvp)
This method sets the view port.
Parameters
cvp
testHistogramAttribute()
bool Isis::HistogramItem::testHistogramAttribute (HistogramAttribute attribute) const
Parameters
attribute
Returns
bool
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/HistogramTool/HistogramItem.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/HistogramTool/HistogramItem.cpp