Isis Developer Reference: Isis::ControlNetFilter Class Reference
Isis::ControlNetFilter Class Reference
Filter Control Network.
#include <ControlNetFilter.h>
Public Types
enum ePointDetails {
total , ignore , locked , fixed ,
constrained , freed
}
Enumeration for Point Statistics.
enum ePointIntStats {
totalPoints , validPoints , ignoredPoints , fixedPoints ,
constrainedPoints , freePoints , editLockedPoints , totalMeasures ,
validMeasures , ignoredMeasures , editLockedMeasures
}
Enumeration for Point int stats for counts such as valid points, measures etc.
enum ePointDoubleStats {
avgResidual , minResidual , maxResidual , minLineResidual ,
maxLineResidual , minSampleResidual , maxSampleResidual , avgPixelShift ,
minPixelShift , maxPixelShift , minLineShift , maxLineShift ,
minSampleShift , maxSampleShift , minGFit , maxGFit ,
minEccentricity , maxEccentricity , minPixelZScore , maxPixelZScore
}
Enumeration for Point stats like Tolerances, PixelShifts which have double data.
enum ImageStats {
imgSamples , imgLines , imgTotalPoints , imgIgnoredPoints ,
imgFixedPoints , imgLockedPoints , imgLocked , imgConstrainedPoints ,
imgFreePoints , imgConvexHullArea , imgConvexHullRatio
}
Enumeration for image stats.
Public Member Functions
ControlNetFilter (ControlNet *pCNet, QString &psSerialNumFile, Progress *pProgress=0)
Constructor.
~ControlNetFilter ()
Destructor.
void PointPixelShiftFilter (const PvlGroup &pvlGrp, bool pbLastFilter)
Filter Points by Pixel Shift.
void PointEditLockFilter (const PvlGroup &pvlGrp, bool pbLastFilter)
Filter Points by Edit Lock.
void PointNumMeasuresEditLockFilter (const PvlGroup &pvlGrp, bool pbLastFilter)
Filter Points by Measure Edit Lock number.
void PointResMagnitudeFilter (const PvlGroup &pvlGrp, bool pbLastFilter)
Filter Points by Residual Magnitude.
void PointGoodnessOfFitFilter (const PvlGroup &pvlGrp, bool pbLastFilter)
Filter Points by GoodnessOfFit.
void PointIDFilter (const PvlGroup &pvlGrp, bool pbLastFilter)
Filter Points by Point ID Expression.
void PointMeasuresFilter (const PvlGroup &pvlGrp, bool pbLastFilter)
Filter Points by Number of measures.
void PointPropertiesFilter (const PvlGroup &pvlGrp, bool pbLastFilter)
Filter Points by properties.
void PointLatLonFilter (const PvlGroup &pvlGrp, bool pbLastFilter)
Filter Points by Lat Lon Range.
void PointDistanceFilter (const PvlGroup &pvlGrp, bool pbLastFilter)
Filter Points by distance between points.
void PointMeasurePropertiesFilter (const PvlGroup &pvlGrp, bool pbLastFilter)
Filter Points by Measure properties.
void PointCubeNamesFilter (const PvlGroup &pvlGrp, bool pbLastFilter)
Filter Points by Cube names.
void PointStatsHeader (void)
Standard Point stats Header.
void PointStats (const ControlPoint &pcPoint)
Standard Point Stats.
void CubeNameExpressionFilter (const PvlGroup &pvlGrp, bool pbLastFilter)
Filter Cubes by Cube name expression.
void CubeNumPointsFilter (const PvlGroup &pvlGrp, bool pbLastFilter)
Filter Cubes by number of points in the cube.
void CubeDistanceFilter (const PvlGroup &pvlGrp, bool pbLastFilter)
Filter Cubes by Distance between points in a Cube.
void CubeConvexHullFilter (const PvlGroup &pvlGrp, bool pbLastFilter)
Filter Cubes by its ConvexHull Ratio.
void CubeStatsHeader (void)
Print the standard cube stats Header.
void SetOutputFile (QString psPrintFile)
Set the output print file.
void PrintCubeFileSerialNum (const ControlMeasure &pcMeasure)
Print Cube's File and Serial Number into the Output File.
void GenerateImageStats ()
Generate stats like Total, Ignored, Fixed Points in an Image.
void PrintImageStats (const QString &psImageFile)
Print the Image Stats into specified output file.
QVector< double > GetImageStatsBySerialNum (QString psSerialNum) const
Returns the Image Stats by Serial Number.
void GeneratePointStats (const QString &psPointFile)
Generate stats like Ignored, Fixed, Total Measures, Ignored by Control Point.
void GenerateControlNetStats (PvlGroup &pStatsGrp)
Generate the Control Net Stats into the PvlGroup.
int NumValidPoints () const
Returns the Number of Valid (Not Ignored) Points in the Control Net.
int NumFixedPoints () const
Returns the Number of Fixed Points in the Control Net.
int NumConstrainedPoints () const
Returns the number of Constrained Points in Control Net.
int NumFreePoints () const
Returns the number of Constrained Points in Control Net.
int NumIgnoredPoints () const
Returns the number of ignored points.
int NumEditLockedPoints () const
Returns total number of edit locked points.
int NumMeasures () const
Returns the total Number of Measures in the Control Net.
int NumValidMeasures () const
Returns the total Number of valid Measures in the Control Net.
int NumIgnoredMeasures () const
Returns the total Number of Ignored Measures in the Control Net.
int NumEditLockedMeasures () const
Returns total number of edit locked measures in the network.
double GetAverageResidual () const
Determine the average error of all points in the network.
double GetMinimumResidual () const
Determine the minimum error of all points in the network.
double GetMaximumResidual () const
Determine the maximum error of all points in the network.
double GetMinLineResidual () const
Determine the minimum line error of all points in the network.
double GetMinSampleResidual () const
Determine the minimum sample error of all points in the network.
double GetMaxLineResidual () const
Determine the maximum line error of all points in the network.
double GetMaxSampleResidual () const
Determine the maximum sample error of all points in the network.
double GetMinLineShift () const
Get Min and Max LineShift.
double GetMaxLineShift () const
Get network Max LineShift.
double GetMinSampleShift () const
Get network Min SampleShift.
double GetMaxSampleShift () const
Get network Max SampleShift.
double GetMinPixelShift () const
Get network Min PixelShift.
double GetMaxPixelShift () const
Get network Max PixelShift.
double GetAvgPixelShift () const
Get network Avg PixelShift.
Static Public Attributes
static const int numPointDetails = 6
static const int numPointIntStats = 11
static const int numPointDblStats = 20
static const int numImageStats = 11
Protected Attributes
SerialNumberList mSerialNumList
Serial Number List.
ControlNet * mCNet
Control Network.
Progress * mProgress
Progress state.
Detailed Description
Filter Control Network.
This class is used to filter Control Network based on different options
Author
2010-08-10 Sharmila Prasad
See also
ControlNetwork ControlPoint ControlMeasure
Member Enumeration Documentation
ePointDetails
enum Isis::ControlNetStatistics::ePointDetails inherited
Enumeration for Point Statistics.
Enumerator
total
ignore
locked
fixed
constrained
freed
ePointDoubleStats
enum Isis::ControlNetStatistics::ePointDoubleStats inherited
Enumeration for Point stats like Tolerances, PixelShifts which have double data.
Enumerator
avgResidual
minResidual
maxResidual
minLineResidual
maxLineResidual
minSampleResidual
maxSampleResidual
avgPixelShift
minPixelShift
maxPixelShift
minLineShift
maxLineShift
minSampleShift
maxSampleShift
minGFit
maxGFit
minEccentricity
maxEccentricity
minPixelZScore
maxPixelZScore
ePointIntStats
enum Isis::ControlNetStatistics::ePointIntStats inherited
Enumeration for Point int stats for counts such as valid points, measures etc.
Enumerator
totalPoints
validPoints
ignoredPoints
fixedPoints
constrainedPoints
freePoints
editLockedPoints
totalMeasures
validMeasures
ignoredMeasures
editLockedMeasures
ImageStats
enum Isis::ControlNetStatistics::ImageStats inherited
Enumeration for image stats.
Enumerator
imgSamples
imgLines
imgTotalPoints
imgIgnoredPoints
imgFixedPoints
imgLockedPoints
imgLocked
imgConstrainedPoints
imgFreePoints
imgConvexHullArea
imgConvexHullRatio
Constructor & Destructor Documentation
ControlNetFilter()
Isis::ControlNetFilter::ControlNetFilter (ControlNet * pCNet, QString & psSerialNumFile, Progress * pProgress = 0)
Constructor.
ControlNetFilter Constructor.
Author
Sharmila Prasad (8/27/2010)
Parameters
pCNet - input Control Net
psSerialNumFile - Corresponding Serial Num List
pProgress - Progress of the processing
~ControlNetFilter()
Isis::ControlNetFilter::~ControlNetFilter ()
Destructor.
ControlNetFilter Destructor.
Author
Sharmila Prasad (8/27/2010)
Member Function Documentation
CubeConvexHullFilter()
void Isis::ControlNetFilter::CubeConvexHullFilter (const PvlGroup & pvlGrp, bool pbLastFilter)
Filter Cubes by its ConvexHull Ratio.
Filter Cubes by its ConvexHull Ratio (Ratio = Convex Hull / Image Area).
ConvexHull is calculated only for valid Control Points
Author
Sharmila Prasad (11/2/2011)
Parameters
pvlGrp - Pvl Group containing the filter info
pbLastFilter - Flag to indicate whether this is the last filter to print the stats
Group = Cube_ConvexHullRatio LessThan = double GreaterThan = double EndGroup
References _FILEINFO_, CubeStatsHeader(), Isis::SerialNumberList::fileName(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlNetStatistics::GetImageStatsBySerialNum(), Isis::PvlContainer::hasKeyword(), Isis::ControlNetStatistics::imgConstrainedPoints, Isis::ControlNetStatistics::imgConvexHullRatio, Isis::ControlNetStatistics::imgFixedPoints, Isis::ControlNetStatistics::imgFreePoints, Isis::ControlNetStatistics::imgIgnoredPoints, Isis::ControlNetStatistics::imgLockedPoints, Isis::ControlNetStatistics::imgTotalPoints, Isis::SerialNumberList::remove(), Isis::SerialNumberList::serialNumber(), Isis::SerialNumberList::size(), Isis::IException::User, and Isis::ValidMaximum.
CubeDistanceFilter()
void Isis::ControlNetFilter::CubeDistanceFilter (const PvlGroup & pvlGrp, bool pbLastFilter)
Filter Cubes by Distance between points in a Cube.
Filter by distance between points in Cube Group by Image.
Author
Sharmila Prasad (8/17/2010)
Parameters
pvlGrp - Pvl Group containing the filter info
pbLastFilter - Flag to indicate whether this is the last filter to print the stats
References _FILEINFO_, Isis::ControlPoint::Constrained, Isis::CameraFactory::Create(), CubeStatsHeader(), Isis::Angle::Degrees, Isis::SerialNumberList::fileName(), Isis::ControlPoint::Fixed, Isis::ControlPoint::Free, Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::SurfacePoint::GetDistanceToPoint(), Isis::ControlNetStatistics::GetImageStatsBySerialNum(), Isis::ControlMeasure::GetLine(), Isis::ControlPoint::GetMeasure(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlNet::GetNumPoints(), Isis::ControlNet::GetPoint(), Isis::ControlMeasure::GetSample(), Isis::ControlPoint::GetType(), Isis::PvlContainer::hasKeyword(), Isis::ControlNetStatistics::imgConvexHullRatio, Isis::ControlPoint::IsEditLocked(), Isis::ControlPoint::IsIgnored(), Isis::Sensor::LocalRadius(), Isis::ControlNetStatistics::mCNet, Isis::Distance::Meters, Isis::Distance::meters(), Isis::ControlNetStatistics::mSerialNumList, Isis::SerialNumberList::remove(), Isis::SerialNumberList::serialNumber(), Isis::Camera::SetImage(), Isis::SerialNumberList::size(), Isis::toString(), Isis::Sensor::UniversalLatitude(), Isis::Sensor::UniversalLongitude(), and Isis::IException::User.
CubeNameExpressionFilter()
void Isis::ControlNetFilter::CubeNameExpressionFilter (const PvlGroup & pvlGrp, bool pbLastFilter)
Filter Cubes by Cube name expression.
Filter Cube names in Control Network by cube name expression Group by Image.
Author
Sharmila Prasad (8/16/2010)
Parameters
pvlGrp - Pvl Group containing the filter info
pbLastFilter - Flag to indicate whether this is the last filter to print the stats
References CubeStatsHeader(), Isis::SerialNumberList::fileName(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlNetStatistics::GetImageStatsBySerialNum(), Isis::PvlContainer::hasKeyword(), Isis::ControlNetStatistics::imgConstrainedPoints, Isis::ControlNetStatistics::imgConvexHullRatio, Isis::ControlNetStatistics::imgFixedPoints, Isis::ControlNetStatistics::imgFreePoints, Isis::ControlNetStatistics::imgIgnoredPoints, Isis::ControlNetStatistics::imgLockedPoints, Isis::ControlNetStatistics::imgTotalPoints, Isis::SerialNumberList::remove(), Isis::SerialNumberList::serialNumber(), and Isis::SerialNumberList::size().
CubeNumPointsFilter()
void Isis::ControlNetFilter::CubeNumPointsFilter (const PvlGroup & pvlGrp, bool pbLastFilter)
Filter Cubes by number of points in the cube.
Filter the cube by the number of points in each cube Group by Image.
Author
Sharmila Prasad (8/16/2010)
Parameters
pvlGrp - Pvl Group containing the filter info
pbLastFilter - Flag to indicate whether this is the last filter to print the stats
References _FILEINFO_, CubeStatsHeader(), Isis::SerialNumberList::fileName(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlNetStatistics::GetImageStatsBySerialNum(), Isis::PvlContainer::hasKeyword(), Isis::ControlNetStatistics::imgConstrainedPoints, Isis::ControlNetStatistics::imgConvexHullRatio, Isis::ControlNetStatistics::imgFixedPoints, Isis::ControlNetStatistics::imgFreePoints, Isis::ControlNetStatistics::imgIgnoredPoints, Isis::ControlNetStatistics::imgLockedPoints, Isis::ControlNetStatistics::imgTotalPoints, Isis::SerialNumberList::remove(), Isis::SerialNumberList::serialNumber(), Isis::SerialNumberList::size(), Isis::toInt(), Isis::IException::User, and Isis::VALID_MAX2.
CubeStatsHeader()
void Isis::ControlNetFilter::CubeStatsHeader (void)
Print the standard cube stats Header.
Print the Standard Cube Stats Header into Output File.
Author
Sharmila Prasad (8/31/2010)
Referenced by CubeConvexHullFilter(), CubeDistanceFilter(), CubeNameExpressionFilter(), CubeNumPointsFilter(), and PointCubeNamesFilter().
GenerateControlNetStats()
void Isis::ControlNetStatistics::GenerateControlNetStats (PvlGroup & pStatsGrp) inherited
Generate the Control Net Stats into the PvlGroup.
Generates the summary stats for the entire control network.
Stats include Total images, Total, Valid, Ignored, Fixed Points, Total, Valid, Ignored Measures and also Average, Min, Max Error, Min, Max Line and Sample Errors
Author
Sharmila Prasad (8/25/2010)
Parameters
pStatsGrp - Output Control Net Stats in Pvl format
References Isis::Statistics::Average(), Isis::ControlNetStatistics::GetAverageResidual(), Isis::ControlNetStatistics::GetAvgPixelShift(), Isis::ControlNetStatistics::GetMaximumResidual(), Isis::ControlNetStatistics::GetMaxLineResidual(), Isis::ControlNetStatistics::GetMaxLineShift(), Isis::ControlNetStatistics::GetMaxPixelShift(), Isis::ControlNetStatistics::GetMaxSampleResidual(), Isis::ControlNetStatistics::GetMaxSampleShift(), Isis::ControlNetStatistics::GetMinimumResidual(), Isis::ControlNetStatistics::GetMinLineResidual(), Isis::ControlNetStatistics::GetMinLineShift(), Isis::ControlNetStatistics::GetMinPixelShift(), Isis::ControlNetStatistics::GetMinSampleResidual(), Isis::ControlNetStatistics::GetMinSampleShift(), Isis::ControlNet::GetNumEditLockMeasures(), Isis::ControlNet::GetNumEditLockPoints(), Isis::ControlNet::GetNumPoints(), Isis::ControlNetStatistics::maxEccentricity, Isis::ControlNetStatistics::maxGFit, Isis::Statistics::Maximum(), Isis::ControlNetStatistics::maxPixelZScore, Isis::ControlNetStatistics::mCNet, Isis::ControlNetStatistics::minEccentricity, Isis::ControlNetStatistics::minGFit, Isis::Statistics::Minimum(), Isis::ControlNetStatistics::minPixelZScore, Isis::ControlNetStatistics::mSerialNumList, Isis::Null, Isis::ControlNetStatistics::NumConstrainedPoints(), Isis::ControlNetStatistics::NumFixedPoints(), Isis::ControlNetStatistics::NumFreePoints(), Isis::ControlNetStatistics::NumIgnoredMeasures(), Isis::ControlNetStatistics::NumMeasures(), Isis::ControlNetStatistics::NumValidMeasures(), Isis::ControlNetStatistics::NumValidPoints(), Isis::SerialNumberList::size(), and Isis::toString().
GenerateImageStats()
void Isis::ControlNetStatistics::GenerateImageStats () inherited
Generate stats like Total, Ignored, Fixed Points in an Image.
Generate the Image stats - imgSamples, imgLines, imgTotalPoints, imgIgnoredPoints, imgFixedPoints, imgLockedPoints, imgLocked, imgConstrainedPoints, imgFreePoints, imgConvexHullArea, imgConvexHullRatio.
Author
Sharmila Prasad (11/1/2011)
References Isis::Statistics::AddData(), Isis::Progress::CheckStatus(), Isis::ControlPoint::Constrained, Isis::SerialNumberList::fileName(), Isis::ControlPoint::Fixed, Isis::ControlPoint::Free, Isis::ControlNet::GetCubeSerials(), Isis::ControlMeasure::GetLine(), Isis::ControlNet::GetMeasuresInCube(), Isis::ControlMeasure::GetSample(), Isis::ControlPoint::GetType(), Isis::ControlNetStatistics::imgConstrainedPoints, Isis::ControlNetStatistics::imgConvexHullArea, Isis::ControlNetStatistics::imgConvexHullRatio, Isis::ControlNetStatistics::imgFixedPoints, Isis::ControlNetStatistics::imgFreePoints, Isis::ControlNetStatistics::imgIgnoredPoints, Isis::ControlNetStatistics::imgLines, Isis::ControlNetStatistics::imgLocked, Isis::ControlNetStatistics::imgLockedPoints, Isis::ControlNetStatistics::imgSamples, Isis::ControlNetStatistics::imgTotalPoints, Isis::ControlMeasure::IsEditLocked(), Isis::ControlPoint::IsEditLocked(), Isis::ControlPoint::IsIgnored(), Isis::Cube::lineCount(), Isis::ControlNetStatistics::mCNet, Isis::ControlNetStatistics::mProgress, Isis::ControlNetStatistics::mSerialNumList, Isis::ControlNetStatistics::numImageStats, Isis::CubeManager::OpenCube(), Isis::ControlMeasure::Parent(), Isis::Cube::sampleCount(), Isis::Progress::SetMaximumSteps(), Isis::CubeManager::SetNumOpenCubes(), and Isis::Progress::SetText().
Referenced by Isis::ControlNetStatistics::ControlNetStatistics(), CubeConvexHullFilter(), CubeDistanceFilter(), CubeNameExpressionFilter(), CubeNumPointsFilter(), PointCubeNamesFilter(), PointDistanceFilter(), PointEditLockFilter(), PointGoodnessOfFitFilter(), PointIDFilter(), PointLatLonFilter(), PointMeasurePropertiesFilter(), PointMeasuresFilter(), PointNumMeasuresEditLockFilter(), PointPixelShiftFilter(), PointPropertiesFilter(), and PointResMagnitudeFilter().
GeneratePointStats()
void Isis::ControlNetStatistics::GeneratePointStats (const QString & psPointFile) inherited
Generate stats like Ignored, Fixed, Total Measures, Ignored by Control Point.
Generate the statistics of a Control Network by Point Stats include ID, Type of each Control Point and Total, Ignored measures in each Control Point.
Author
Sharmila Prasad (8/24/2010)
Parameters
psPointFile - Output Point Statisitics File
References _FILEINFO_, Isis::Progress::CheckStatus(), Isis::FileName::expanded(), Isis::ControlPoint::GetId(), Isis::ControlPoint::GetNumLockedMeasures(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlNet::GetNumPoints(), Isis::ControlPoint::GetNumValidMeasures(), Isis::ControlNet::GetPoint(), Isis::ControlPoint::GetType(), Isis::IException::Io, Isis::ControlPoint::IsEditLocked(), Isis::ControlPoint::IsIgnored(), Isis::ControlNetStatistics::mCNet, Isis::ControlNetStatistics::mProgress, Isis::sBoolean, Isis::Progress::SetMaximumSteps(), Isis::Progress::SetText(), and Isis::sPointType.
GetAverageResidual()
double Isis::ControlNetStatistics::GetAverageResidual () const inline inherited
Determine the average error of all points in the network.
References Isis::ControlNetStatistics::avgResidual.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
GetAvgPixelShift()
double Isis::ControlNetStatistics::GetAvgPixelShift () const inline inherited
Get network Avg PixelShift.
References Isis::ControlNetStatistics::avgPixelShift.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
GetImageStatsBySerialNum()
QVector< double > Isis::ControlNetStatistics::GetImageStatsBySerialNum (QString psSerialNum) const inherited
Returns the Image Stats by Serial Number.
Author
Sharmila Prasad (11/3/2011)
Parameters
psSerialNum - Image serialNum
Returns
const QVector<double>
Referenced by CubeConvexHullFilter(), CubeDistanceFilter(), CubeNameExpressionFilter(), CubeNumPointsFilter(), and PointCubeNamesFilter().
GetMaximumResidual()
double Isis::ControlNetStatistics::GetMaximumResidual () const inline inherited
Determine the maximum error of all points in the network.
References Isis::ControlNetStatistics::maxResidual.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
GetMaxLineResidual()
double Isis::ControlNetStatistics::GetMaxLineResidual () const inline inherited
Determine the maximum line error of all points in the network.
References Isis::ControlNetStatistics::maxLineResidual.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
GetMaxLineShift()
double Isis::ControlNetStatistics::GetMaxLineShift () const inline inherited
Get network Max LineShift.
References Isis::ControlNetStatistics::maxLineShift.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
GetMaxPixelShift()
double Isis::ControlNetStatistics::GetMaxPixelShift () const inline inherited
Get network Max PixelShift.
References Isis::ControlNetStatistics::maxPixelShift.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
GetMaxSampleResidual()
double Isis::ControlNetStatistics::GetMaxSampleResidual () const inline inherited
Determine the maximum sample error of all points in the network.
References Isis::ControlNetStatistics::maxSampleResidual.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
GetMaxSampleShift()
double Isis::ControlNetStatistics::GetMaxSampleShift () const inline inherited
Get network Max SampleShift.
References Isis::ControlNetStatistics::maxSampleShift.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
GetMinimumResidual()
double Isis::ControlNetStatistics::GetMinimumResidual () const inline inherited
Determine the minimum error of all points in the network.
References Isis::ControlNetStatistics::minResidual.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
GetMinLineResidual()
double Isis::ControlNetStatistics::GetMinLineResidual () const inline inherited
Determine the minimum line error of all points in the network.
References Isis::ControlNetStatistics::minLineResidual.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
GetMinLineShift()
double Isis::ControlNetStatistics::GetMinLineShift () const inline inherited
Get Min and Max LineShift.
References Isis::ControlNetStatistics::minLineShift.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
GetMinPixelShift()
double Isis::ControlNetStatistics::GetMinPixelShift () const inline inherited
Get network Min PixelShift.
References Isis::ControlNetStatistics::minPixelShift.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
GetMinSampleResidual()
double Isis::ControlNetStatistics::GetMinSampleResidual () const inline inherited
Determine the minimum sample error of all points in the network.
References Isis::ControlNetStatistics::minSampleResidual.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
GetMinSampleShift()
double Isis::ControlNetStatistics::GetMinSampleShift () const inline inherited
Get network Min SampleShift.
References Isis::ControlNetStatistics::minSampleShift.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
NumConstrainedPoints()
int Isis::ControlNetStatistics::NumConstrainedPoints () const inline inherited
Returns the number of Constrained Points in Control Net.
References Isis::ControlNetStatistics::constrainedPoints.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
NumEditLockedMeasures()
int Isis::ControlNetStatistics::NumEditLockedMeasures () const inline inherited
Returns total number of edit locked measures in the network.
References Isis::ControlNetStatistics::editLockedMeasures.
NumEditLockedPoints()
int Isis::ControlNetStatistics::NumEditLockedPoints () const inline inherited
Returns total number of edit locked points.
References Isis::ControlNetStatistics::editLockedPoints.
NumFixedPoints()
int Isis::ControlNetStatistics::NumFixedPoints () const inline inherited
Returns the Number of Fixed Points in the Control Net.
References Isis::ControlNetStatistics::fixedPoints.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
NumFreePoints()
int Isis::ControlNetStatistics::NumFreePoints () const inline inherited
Returns the number of Constrained Points in Control Net.
References Isis::ControlNetStatistics::freePoints.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
NumIgnoredMeasures()
int Isis::ControlNetStatistics::NumIgnoredMeasures () const inline inherited
Returns the total Number of Ignored Measures in the Control Net.
References Isis::ControlNetStatistics::ignoredMeasures.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
NumIgnoredPoints()
int Isis::ControlNetStatistics::NumIgnoredPoints () const inline inherited
Returns the number of ignored points.
References Isis::ControlNetStatistics::ignoredPoints.
NumMeasures()
int Isis::ControlNetStatistics::NumMeasures () const inline inherited
Returns the total Number of Measures in the Control Net.
References Isis::ControlNetStatistics::totalMeasures.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
NumValidMeasures()
int Isis::ControlNetStatistics::NumValidMeasures () const inline inherited
Returns the total Number of valid Measures in the Control Net.
References Isis::ControlNetStatistics::validMeasures.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
NumValidPoints()
int Isis::ControlNetStatistics::NumValidPoints () const inline inherited
Returns the Number of Valid (Not Ignored) Points in the Control Net.
References Isis::ControlNetStatistics::validPoints.
Referenced by Isis::ControlNetStatistics::GenerateControlNetStats().
PointCubeNamesFilter()
void Isis::ControlNetFilter::PointCubeNamesFilter (const PvlGroup & pvlGrp, bool pbLastFilter)
Filter Points by Cube names.
Filter points based on the image serial # - Group by Point.
Author
Sharmila Prasad (8/16/2010)
Parameters
pvlGrp - Pvl Group containing the filter info
pbLastFilter - Flag to indicate whether this is the last filter to print the stats
References CubeStatsHeader(), Isis::SerialNumberList::fileName(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::ControlPoint::GetId(), Isis::ControlNetStatistics::GetImageStatsBySerialNum(), Isis::ControlPoint::GetMeasure(), Isis::ControlPoint::GetNumLockedMeasures(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlNet::GetNumPoints(), Isis::ControlPoint::GetNumValidMeasures(), Isis::ControlNet::GetPoint(), Isis::ControlPoint::GetType(), Isis::ControlNetStatistics::imgConstrainedPoints, Isis::ControlNetStatistics::imgConvexHullRatio, Isis::ControlNetStatistics::imgFixedPoints, Isis::ControlNetStatistics::imgFreePoints, Isis::ControlNetStatistics::imgIgnoredPoints, Isis::ControlNetStatistics::imgLockedPoints, Isis::ControlNetStatistics::imgTotalPoints, Isis::ControlMeasure::IsEditLocked(), Isis::ControlPoint::IsEditLocked(), Isis::ControlMeasure::IsIgnored(), Isis::ControlPoint::IsIgnored(), Isis::PvlContainer::keywords(), Isis::ControlNetStatistics::mCNet, Isis::ControlNetStatistics::mSerialNumList, PointStatsHeader(), Isis::sBoolean, and Isis::sPointType.
PointDistanceFilter()
void Isis::ControlNetFilter::PointDistanceFilter (const PvlGroup & pvlGrp, bool pbLastFilter)
Filter Points by distance between points.
Filter points that are within given distance of some other point Group by Points.
Author
Sharmila Prasad (8/13/2010)
Parameters
pvlGrp - Pvl Group containing the filter info
pbLastFilter - Flag to indicate whether this is the last filter to print the stats
References Isis::CameraFactory::Create(), Isis::Angle::Degrees, Isis::SerialNumberList::fileName(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlPoint::GetAdjustedSurfacePoint(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::SurfacePoint::GetDistanceToPoint(), Isis::ControlPoint::GetId(), Isis::ControlMeasure::GetLine(), Isis::SurfacePoint::GetLocalRadius(), Isis::ControlNet::GetNumPoints(), Isis::ControlNet::GetPoint(), Isis::ControlPoint::GetRefMeasure(), Isis::ControlMeasure::GetSample(), Isis::PvlContainer::hasKeyword(), Isis::Sensor::LocalRadius(), Isis::ControlNetStatistics::mCNet, Isis::Distance::meters(), Isis::ControlNetStatistics::mSerialNumList, Isis::Null, PointStats(), PointStatsHeader(), Isis::Camera::SetImage(), Isis::SurfacePoint::SetSpherical(), Isis::Sensor::UniversalLatitude(), Isis::Sensor::UniversalLongitude(), and Isis::SurfacePoint::Valid().
PointEditLockFilter()
void Isis::ControlNetFilter::PointEditLockFilter (const PvlGroup & pvlGrp, bool pbLastFilter)
Filter Points by Edit Lock.
Filter points based on the point EditLock.
Author
Sharmila Prasad (7/20/2011)
Header - PointID, Type, Ignore, EditLock, NumMeasures, NumIgnoredMeasures, NumLockedMeasures,
Parameters
pvlGrp - Deffile Input group
pbLastFilter - Is this the last filter - for printing purposes.
References Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlPoint::GetId(), Isis::ControlPoint::GetNumLockedMeasures(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlNet::GetNumPoints(), Isis::ControlPoint::GetNumValidMeasures(), Isis::ControlNet::GetPoint(), Isis::ControlPoint::GetType(), Isis::PvlContainer::hasKeyword(), Isis::ControlPoint::IsEditLocked(), Isis::ControlPoint::IsIgnored(), Isis::ControlNetStatistics::mCNet, PointStatsHeader(), Isis::sBoolean, and Isis::sPointType.
PointGoodnessOfFitFilter()
void Isis::ControlNetFilter::PointGoodnessOfFitFilter (const PvlGroup & pvlGrp, bool pbLastFilter)
Filter Points by GoodnessOfFit.
Filter the Points based on the Measures Goodness ofFit value Group by Points.
Header: PointID, PointType, PointIgnored, PointEditLocked, TotalMeasures, MeasuresIgnored, MeasuresEditLocked, FileName, SerialNumber, GoodnessOfFit, MeasureIgnored, MeasureType, MeasureEditLocked, Reference
Author
Sharmila Prasad (8/16/2010)
Parameters
pvlGrp - Pvl Group containing the filter info
pbLastFilter - Flag to indicate whether this is the last filter to print the stats
References Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlPoint::GetId(), Isis::ControlMeasure::GetLogData(), Isis::ControlPoint::GetMeasure(), Isis::ControlMeasure::GetMeasureTypeString(), Isis::ControlMeasureLogData::GetNumericalValue(), Isis::ControlPoint::GetNumLockedMeasures(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlNet::GetNumPoints(), Isis::ControlPoint::GetNumValidMeasures(), Isis::ControlNet::GetPoint(), Isis::ControlPoint::GetRefMeasure(), Isis::ControlPoint::GetType(), Isis::ControlMeasureLogData::GoodnessOfFit, Isis::PvlContainer::hasKeyword(), Isis::ControlMeasure::IsEditLocked(), Isis::ControlPoint::IsEditLocked(), Isis::ControlMeasure::IsIgnored(), Isis::ControlPoint::IsIgnored(), Isis::ControlNetStatistics::mCNet, Isis::Null, PointStatsHeader(), PrintCubeFileSerialNum(), Isis::sBoolean, Isis::sPointType, and Isis::ValidMaximum.
PointIDFilter()
void Isis::ControlNetFilter::PointIDFilter (const PvlGroup & pvlGrp, bool pbLastFilter)
Filter Points by Point ID Expression.
Filter PointID based on regular expression Group by Points.
Author
Sharmila Prasad (8/11/2010)
Parameters
pvlGrp - Pvl Group containing the filter info
pbLastFilter - Flag to indicate whether this is the last filter to print the stats
References Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlPoint::GetId(), Isis::ControlNet::GetNumPoints(), Isis::ControlNet::GetPoint(), Isis::ControlNetStatistics::mCNet, PointStats(), and PointStatsHeader().
PointLatLonFilter()
void Isis::ControlNetFilter::PointLatLonFilter (const PvlGroup & pvlGrp, bool pbLastFilter)
Filter Points by Lat Lon Range.
Filters the Control Network based on Lat,Lon Range Group by Points.
Author
Sharmila Prasad (8/13/2010)
Parameters
pvlGrp - Pvl Group containing the filter info
pbLastFilter - Flag to indicate whether this is the last filter to print the stats
References _FILEINFO_, Isis::CameraFactory::Create(), Isis::Angle::Degrees, Isis::Angle::degrees(), Isis::SerialNumberList::fileName(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlPoint::GetAdjustedSurfacePoint(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::SurfacePoint::GetLatitude(), Isis::ControlMeasure::GetLine(), Isis::SurfacePoint::GetLocalRadius(), Isis::SurfacePoint::GetLongitude(), Isis::ControlNet::GetNumPoints(), Isis::ControlNet::GetPoint(), Isis::ControlPoint::GetRefMeasure(), Isis::ControlMeasure::GetSample(), Isis::PvlContainer::hasKeyword(), Isis::Sensor::LocalRadius(), Isis::ControlNetStatistics::mCNet, Isis::Distance::meters(), Isis::ControlNetStatistics::mSerialNumList, PointStats(), PointStatsHeader(), Isis::Camera::SetImage(), Isis::SurfacePoint::SetSpherical(), Isis::Sensor::UniversalLatitude(), Isis::Sensor::UniversalLongitude(), Isis::IException::User, Isis::SurfacePoint::Valid(), Isis::ValidMaximum, and Isis::ValidMinimum.
PointMeasurePropertiesFilter()
void Isis::ControlNetFilter::PointMeasurePropertiesFilter (const PvlGroup & pvlGrp, bool pbLastFilter)
Filter Points by Measure properties.
Filter the Points which have measures of specified Measure type and Ignored Flag.
Group by Points
Author
Sharmila Prasad (8/13/2010)
Parameters
pvlGrp - Pvl Group containing the filter info
pbLastFilter - Flag to indicate whether this is the last filter to print the stats
References Isis::ControlMeasure::Candidate, Isis::IString::DownCase(), Isis::SerialNumberList::fileName(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::ControlPoint::GetMeasure(), Isis::ControlMeasure::GetMeasureTypeString(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlNet::GetNumPoints(), Isis::ControlNet::GetPoint(), Isis::ControlPoint::GetRefMeasure(), Isis::ControlMeasure::GetType(), Isis::PvlContainer::hasKeyword(), Isis::ControlMeasure::IsEditLocked(), Isis::ControlMeasure::IsIgnored(), Isis::ControlMeasure::Manual, Isis::ControlNetStatistics::mCNet, Isis::ControlNetStatistics::mSerialNumList, PointStats(), PointStatsHeader(), Isis::ControlMeasure::RegisteredPixel, Isis::ControlMeasure::RegisteredSubPixel, and Isis::sBoolean.
PointMeasuresFilter()
void Isis::ControlNetFilter::PointMeasuresFilter (const PvlGroup & pvlGrp, bool pbLastFilter)
Filter Points by Number of measures.
Filters the Control Network based on the user specified number of measures in a Control Point.
Group by Points
Author
Sharmila Prasad (8/12/2010)
Parameters
pvlGrp - Pvl Group containing the filter info
pbLastFilter - Flag to indicate whether this is the last filter to print the stats
References _FILEINFO_, Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlPoint::GetMeasure(), Isis::ControlMeasure::GetMeasureTypeString(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlNet::GetNumPoints(), Isis::ControlNet::GetPoint(), Isis::ControlPoint::GetRefMeasure(), Isis::PvlContainer::hasKeyword(), Isis::ControlMeasure::IsEditLocked(), Isis::ControlMeasure::IsIgnored(), Isis::ControlNetStatistics::mCNet, PointStats(), PointStatsHeader(), PrintCubeFileSerialNum(), Isis::sBoolean, Isis::toInt(), Isis::IException::User, and Isis::VALID_MAX2.
PointNumMeasuresEditLockFilter()
void Isis::ControlNetFilter::PointNumMeasuresEditLockFilter (const PvlGroup & pvlGrp, bool pbLastFilter)
Filter Points by Measure Edit Lock number.
Filter points based on number of measures EditLocked.
Author
Sharmila Prasad (7/20/2011)
Header - PointID, Type, Ignore, EditLock, NumMeasures, NumIgnoredMeasures, NumLockedMeasures,
Parameters
pvlGrp - Deffile Input group
pbLastFilter - Is this the last filter - for printing purposes.
References _FILEINFO_, Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlPoint::GetMeasure(), Isis::ControlMeasure::GetMeasureTypeString(), Isis::ControlPoint::GetNumLockedMeasures(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlNet::GetNumPoints(), Isis::ControlNet::GetPoint(), Isis::ControlPoint::GetRefMeasure(), Isis::PvlContainer::hasKeyword(), Isis::ControlMeasure::IsEditLocked(), Isis::ControlMeasure::IsIgnored(), Isis::ControlNetStatistics::mCNet, PointStats(), PointStatsHeader(), PrintCubeFileSerialNum(), Isis::sBoolean, Isis::toInt(), Isis::IException::User, and Isis::VALID_MAX2.
PointPixelShiftFilter()
void Isis::ControlNetFilter::PointPixelShiftFilter (const PvlGroup & pvlGrp, bool pbLastFilter)
Filter Points by Pixel Shift.
Filter Points by PixelShift.
Author
Sharmila Prasad (7/20/2011)
Parameters
pvlGrp - Deffile Input group
pbLastFilter - Is this the last filter - for printing purposes.
References _FILEINFO_, Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlPoint::GetId(), Isis::ControlPoint::GetMeasure(), Isis::ControlMeasure::GetMeasureTypeString(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlNet::GetNumPoints(), Isis::ControlMeasure::GetPixelShift(), Isis::ControlNet::GetPoint(), Isis::ControlPoint::GetRefMeasure(), Isis::ControlPoint::GetType(), Isis::PvlContainer::hasKeyword(), Isis::ControlMeasure::IsEditLocked(), Isis::ControlPoint::IsEditLocked(), Isis::ControlMeasure::IsIgnored(), Isis::ControlPoint::IsIgnored(), Isis::ControlNetStatistics::mCNet, Isis::Null, PrintCubeFileSerialNum(), Isis::sBoolean, Isis::sPointType, Isis::toString(), Isis::IException::User, and Isis::ValidMaximum.
PointPropertiesFilter()
void Isis::ControlNetFilter::PointPropertiesFilter (const PvlGroup & pvlGrp, bool pbLastFilter)
Filter Points by properties.
Filter the Control Network based on Ignored, Fixed Point Properties Group by Points.
Author
Sharmila Prasad (8/12/2010)
Parameters
pvlGrp - Pvl Group containing the filter info
pbLastFilter - Flag to indicate whether this is the last filter to print the stats
References Isis::ControlPoint::Constrained, Isis::IString::DownCase(), Isis::ControlPoint::Fixed, Isis::ControlPoint::Free, Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlNet::GetNumPoints(), Isis::ControlNet::GetPoint(), Isis::ControlPoint::GetType(), Isis::PvlContainer::hasKeyword(), Isis::ControlPoint::IsIgnored(), Isis::ControlNetStatistics::mCNet, PointStats(), and PointStatsHeader().
PointResMagnitudeFilter()
void Isis::ControlNetFilter::PointResMagnitudeFilter (const PvlGroup & pvlGrp, bool pbLastFilter)
Filter Points by Residual Magnitude.
Filters out the Control Network based on Residual Magnitude Criteria.
Group by Points
Author
Sharmila Prasad (8/11/2010)
Header: PointID, Type, Ignore, EditLock, FileName, SerialNum, ResidualMagnitude, MeasureIgnore, MeasureLocked, Reference,
Parameters
pvlGrp - Pvl Group containing the filter info
pbLastFilter - Flag to indicate whether this is the last filter to print the stats
References _FILEINFO_, Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlPoint::GetId(), Isis::ControlPoint::GetMeasure(), Isis::ControlMeasure::GetMeasureTypeString(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlNet::GetNumPoints(), Isis::ControlNet::GetPoint(), Isis::ControlPoint::GetRefMeasure(), Isis::ControlMeasure::GetResidualMagnitude(), Isis::ControlPoint::GetType(), Isis::PvlContainer::hasKeyword(), Isis::ControlMeasure::IsEditLocked(), Isis::ControlPoint::IsEditLocked(), Isis::ControlMeasure::IsIgnored(), Isis::ControlPoint::IsIgnored(), Isis::ControlNetStatistics::mCNet, Isis::Null, PrintCubeFileSerialNum(), Isis::sBoolean, Isis::sPointType, Isis::IException::User, and Isis::ValidMaximum.
PointStats()
void Isis::ControlNetFilter::PointStats (const ControlPoint & pcPoint)
Standard Point Stats.
Print the Standard Point Stats into Output file given the Control Point.
Author
Sharmila Prasad (8/31/2010)
Parameters
pcPoint
References Isis::ControlPoint::GetId(), Isis::ControlPoint::GetNumLockedMeasures(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlPoint::GetNumValidMeasures(), Isis::ControlPoint::GetType(), Isis::ControlPoint::IsEditLocked(), Isis::ControlPoint::IsIgnored(), Isis::sBoolean, and Isis::sPointType.
Referenced by PointDistanceFilter(), PointIDFilter(), PointLatLonFilter(), PointMeasurePropertiesFilter(), PointMeasuresFilter(), PointNumMeasuresEditLockFilter(), and PointPropertiesFilter().
PointStatsHeader()
void Isis::ControlNetFilter::PointStatsHeader (void)
Standard Point stats Header.
Print the Standard Point Stats Header into Output File.
Author
Sharmila Prasad (8/31/2010)
Referenced by PointCubeNamesFilter(), PointDistanceFilter(), PointEditLockFilter(), PointGoodnessOfFitFilter(), PointIDFilter(), PointLatLonFilter(), PointMeasurePropertiesFilter(), PointMeasuresFilter(), PointNumMeasuresEditLockFilter(), and PointPropertiesFilter().
PrintCubeFileSerialNum()
void Isis::ControlNetFilter::PrintCubeFileSerialNum (const ControlMeasure & pcMeasure)
Print Cube's File and Serial Number into the Output File.
Author
Sharmila Prasad (8/31/2010)
Parameters
pcMeasure - Measure's Cube and Serial #
References Isis::SerialNumberList::fileName(), Isis::ControlMeasure::GetCubeSerialNumber(), and Isis::ControlNetStatistics::mSerialNumList.
Referenced by PointGoodnessOfFitFilter(), PointMeasuresFilter(), PointNumMeasuresEditLockFilter(), PointPixelShiftFilter(), and PointResMagnitudeFilter().
PrintImageStats()
void Isis::ControlNetStatistics::PrintImageStats (const QString & psImageFile) inherited
Print the Image Stats into specified output file.
Author
Sharmila Prasad (9/1/2010)
Header: FileName, SerialNumber, TotalPoints, PointsIgnored, PointsLocked, Fixed, Constrained, Free
Parameters
psImageFile - Output Image Stats File
References _FILEINFO_, Isis::FileName::expanded(), Isis::SerialNumberList::fileName(), Isis::ControlNetStatistics::imgConstrainedPoints, Isis::ControlNetStatistics::imgConvexHullRatio, Isis::ControlNetStatistics::imgFixedPoints, Isis::ControlNetStatistics::imgFreePoints, Isis::ControlNetStatistics::imgIgnoredPoints, Isis::ControlNetStatistics::imgLockedPoints, Isis::ControlNetStatistics::imgTotalPoints, Isis::IException::Io, Isis::ControlNetStatistics::mSerialNumList, Isis::SerialNumberList::size(), and Isis::IException::User.
SetOutputFile()
void Isis::ControlNetFilter::SetOutputFile (QString psPrintFile)
Set the output print file.
Get the output file and open the output file stream.
Author
Sharmila Prasad (9/7/2010)
Parameters
psPrintFile
pbPvl
References Isis::FileName::expanded().
Member Data Documentation
mCNet
ControlNet* Isis::ControlNetStatistics::mCNet protected inherited
Control Network.
Referenced by Isis::ControlNetStatistics::ControlNetStatistics(), CubeDistanceFilter(), Isis::ControlNetStatistics::GenerateControlNetStats(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlNetStatistics::GeneratePointStats(), PointCubeNamesFilter(), PointDistanceFilter(), PointEditLockFilter(), PointGoodnessOfFitFilter(), PointIDFilter(), PointLatLonFilter(), PointMeasurePropertiesFilter(), PointMeasuresFilter(), PointNumMeasuresEditLockFilter(), PointPixelShiftFilter(), PointPropertiesFilter(), PointResMagnitudeFilter(), and Isis::ControlNetStatistics::~ControlNetStatistics().
mProgress
Progress* Isis::ControlNetStatistics::mProgress protected inherited
Progress state.
Referenced by Isis::ControlNetStatistics::ControlNetStatistics(), Isis::ControlNetStatistics::GenerateImageStats(), and Isis::ControlNetStatistics::GeneratePointStats().
mSerialNumList
SerialNumberList Isis::ControlNetStatistics::mSerialNumList protected inherited
Serial Number List.
Referenced by Isis::ControlNetStatistics::ControlNetStatistics(), CubeDistanceFilter(), Isis::ControlNetStatistics::GenerateControlNetStats(), Isis::ControlNetStatistics::GenerateImageStats(), PointCubeNamesFilter(), PointDistanceFilter(), PointLatLonFilter(), PointMeasurePropertiesFilter(), PrintCubeFileSerialNum(), and Isis::ControlNetStatistics::PrintImageStats().
numImageStats
const int Isis::ControlNetStatistics::numImageStats = 11 static inherited
Referenced by Isis::ControlNetStatistics::GenerateImageStats().
numPointDblStats
const int Isis::ControlNetStatistics::numPointDblStats = 20 static inherited
numPointDetails
const int Isis::ControlNetStatistics::numPointDetails = 6 static inherited
numPointIntStats
const int Isis::ControlNetStatistics::numPointIntStats = 11 static inherited
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/ControlNetFilter/ControlNetFilter.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/ControlNetFilter/ControlNetFilter.cpp