Isis Developer Reference: Isis::SaveAsDialog Class Reference
Isis::SaveAsDialog Class Reference
Widget to save(Save As) Isis cubes(used in qview) to display the FileDialog to select the output cube.
#include <SaveAsDialog.h>
Public Types
enum saveAsType { FullImage , ExportAsIs , ExportFullRes }
Public Slots
void setFullImage (bool)
Check FullImage radio button and if checked set the saveAsType to FullImage.
void setAsIs (bool)
Check ExportAsIs radio button and if checked set the saveAsType to ExportAsIs.
void setFullResolution (bool)
Check ExportFullRes radio button and if checked set the saveAsType to ExportFullRes.
Signals
void fileSelected (QString)
void filterSelected (QString)
Public Member Functions
SaveAsDialog (QString pTitle, QStringList &pFilterList, QDir &pDir, QWidget *pParent=0)
Constructor - Displays FileDialog with different save options.
int getSaveAsType ()
Get user chosen save type.
void closeEvent (QCloseEvent *event)
This method is overridden so that we can be sure to write the current settings of the Main window.
void readSettings ()
This method is called from the constructor so that when the Main window is created, it know's it's size and location.
void writeSettings ()
This method is called when the File Dialog is closed or hidden to write the size and location settings to a config file in the user's home directory.
Protected Slots
void sendSignal ()
This saves the directory that the user selected the file from so it can open to this directory next time.
void done ()
Called when the user presses OK.
void done (int r)
Called when the user presses OK.
void cancel ()
Called when user presses cancel.
void saveFilter ()
This is where we actually set the user editable filters and remember them.
Protected Member Functions
bool eventFilter (QObject *o, QEvent *e)
This event filter is installed on the parent of this window.
Detailed Description
Widget to save(Save As) Isis cubes(used in qview) to display the FileDialog to select the output cube.
This dialog additionally displays radio buttons for choices FullImage, ExportAsIs, ExportFullRes. These choices are located at the bottom of the dialog.
FullImage - copies the entire image into the user specified output file ExportAsIs - copies the image as displayed in the qview app window ExportFullRes - copies the image as displayed in the qview app window but with full resolution
Author
2011-05-11 Sharmila Prasad
Member Enumeration Documentation
saveAsType
enum Isis::SaveAsDialog::saveAsType
Parameters
FullImage,ExportAsIs,ExportFullRes
Enumerator
FullImage
ExportAsIs
ExportFullRes
Constructor & Destructor Documentation
SaveAsDialog()
Isis::SaveAsDialog::SaveAsDialog (QString pTitle, QStringList & pFilterList, QDir & pDir, QWidget * pParent = 0)
Constructor - Displays FileDialog with different save options.
Author
Sharmila Prasad (5/11/2011)
Parameters
pTitle - Dialog Title
pFilterList - Dialog Filter list
pDir - Current Directory
pParent - Parent widget
References FullImage, setAsIs(), setFullImage(), and setFullResolution().
Member Function Documentation
cancel
void Isis::FileDialog::cancel () protected slot inherited
Called when user presses cancel.
Referenced by Isis::FileDialog::FileDialog().
closeEvent()
void Isis::FileDialog::closeEvent (QCloseEvent * event) inherited
This method is overridden so that we can be sure to write the current settings of the Main window.
Parameters
event
References Isis::FileDialog::writeSettings().
done [1/2]
void Isis::FileDialog::done () protected slot inherited
Called when the user presses OK.
References Isis::FileDialog::sendSignal().
Referenced by Isis::FileDialog::FileDialog().
done [2/2]
void Isis::FileDialog::done (int r) protected slot inherited
Called when the user presses OK.
eventFilter()
bool Isis::FileDialog::eventFilter (QObject * o, QEvent * e) protected inherited
This event filter is installed on the parent of this window.
When the user closes the main window of the application, the FileDialog will write their settings even though they did not receive the close event themselves.
Parameters
o
e
Returns
bool
References Isis::FileDialog::writeSettings().
fileSelected
void Isis::FileDialog::fileSelected (QString) signal inherited
Referenced by Isis::BrowseDialog::displayCube(), and Isis::FileDialog::sendSignal().
filterSelected
void Isis::FileDialog::filterSelected (QString) signal inherited
getSaveAsType()
int Isis::SaveAsDialog::getSaveAsType ()
Get user chosen save type.
Author
Sharmila Prasad (5/11/2011)
Returns
int - Return user chosen save type
References ExportAsIs, ExportFullRes, and FullImage.
readSettings()
void Isis::FileDialog::readSettings () inherited
This method is called from the constructor so that when the Main window is created, it know's it's size and location.
References Isis::FileName::expanded().
Referenced by Isis::FileDialog::FileDialog().
saveFilter
void Isis::FileDialog::saveFilter () protected slot inherited
This is where we actually set the user editable filters and remember them.
Referenced by Isis::FileDialog::FileDialog().
sendSignal
void Isis::FileDialog::sendSignal () protected slot inherited
This saves the directory that the user selected the file from so it can open to this directory next time.
Also, emits the signal to open the selected file.
References Isis::FileDialog::fileSelected().
Referenced by Isis::FileDialog::done(), and Isis::FileDialog::FileDialog().
setAsIs
void Isis::SaveAsDialog::setAsIs (bool pbChecked) slot
Check ExportAsIs radio button and if checked set the saveAsType to ExportAsIs.
Author
Sharmila Prasad (5/11/2011)
Parameters
pbChecked - Button Checked(true/false)
References ExportAsIs.
Referenced by SaveAsDialog().
setFullImage
void Isis::SaveAsDialog::setFullImage (bool pbChecked) slot
Check FullImage radio button and if checked set the saveAsType to FullImage.
Author
Sharmila Prasad (5/11/2011)
Parameters
pbChecked - Button Checked(true/false)
References FullImage.
Referenced by SaveAsDialog().
setFullResolution
void Isis::SaveAsDialog::setFullResolution (bool pbChecked) slot
Check ExportFullRes radio button and if checked set the saveAsType to ExportFullRes.
Author
Sharmila Prasad (5/11/2011)
Parameters
pbChecked - Button Checked(true/false)
References ExportFullRes.
Referenced by SaveAsDialog().
writeSettings()
void Isis::FileDialog::writeSettings () inherited
This method is called when the File Dialog is closed or hidden to write the size and location settings to a config file in the user's home directory.
References Isis::FileName::expanded().
Referenced by Isis::FileDialog::closeEvent(), and Isis::FileDialog::eventFilter().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/SaveAsDialog/SaveAsDialog.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/SaveAsDialog/SaveAsDialog.cpp