Isis Developer Reference: Isis::ImageImageTreeModel Class Reference
Isis::ImageImageTreeModel Class Reference
Tree model for images and images.
#include <ImageImageTreeModel.h>
Public Types
enum InterestingItems { PointItems = 1 , MeasureItems = 2 , ImageItems = 4 , AllItems = PointItems | MeasureItems | ImageItems }
Public Slots
void applyFilter ()
Signals
void cancelSort ()
void modelModified ()
void filterProgressChanged (int)
void filterProgressRangeChanged (int, int)
void rebuildProgressChanged (int)
void rebuildProgressRangeChanged (int, int)
void treeSelectionChanged (QList< AbstractTreeItem * >)
void tableSelectionChanged (QList< AbstractTreeItem * >)
void filterCountsChanged (int visibleTopLevelItemCount, int topLevelItemCount)
This signal is emitted after filtering to provide the number of visible top-level items remaining after the filter was applied, as well as the total number of items that were possible.
Public Member Functions
ImageImageTreeModel (ControlNet *cNet, TreeView *v, QObject *parent=0)
virtual ~ImageImageTreeModel ()
void rebuildItems ()
QList< AbstractTreeItem * > getItems (int, int, InterestingItemsFlag=AllItems, bool=false)
QList< AbstractTreeItem * > getItems (AbstractTreeItem *, AbstractTreeItem *, InterestingItemsFlag=AllItems, bool=false)
QList< AbstractTreeItem * > getSelectedItems (InterestingItemsFlag=AllItems, bool=false)
QMutex * getMutex () const
int getItemCount (InterestingItemsFlag) const
int getTopLevelItemCount () const
int getVisibleItemCount (InterestingItemsFlag, bool) const
int getVisibleTopLevelItemCount () const
TreeView * getView () const
void setDrivable (bool drivableStatus)
bool isDrivable () const
bool isFiltering () const
bool isRebuilding () const
void setRebuilding (bool running)
void setFilter (FilterWidget *newFilter)
void setGlobalSelection (bool selected, InterestingItemsFlag=AllItems)
void stopWorking ()
QSize getVisibleSize (int indentation) const
indentation is in pixels
int indexOfVisibleItem (AbstractTreeItem const *item, InterestingItemsFlag=AllItems, bool=false) const
void setFrozen (bool)
bool isFrozen () const
void queueRebuild ()
Protected Member Functions
void clear ()
ControlNet * getControlNetwork () const
FilterWidget * getFilterWidget () const
QFutureWatcher< QAtomicPointer< RootItem > > * getRebuildWatcher () const
RootItem * getRootItem () const
Protected Attributes
RootItem * rootItem
Detailed Description
Tree model for images and images.
This class represents a model that provides access to images that are connected together through a control point. The tree structure is designed such that images are parent nodes with images as children (leaf) nodes.
This class also provides functionality for the multi-threaded rebuilding of the image-image tree model structure, which is necessary when certain types of changes are made to the underlying control network.
Author
????-??-?? Eric Hyer
Member Enumeration Documentation
InterestingItems
enum Isis::AbstractTreeModel::InterestingItems inherited
Enumerator
PointItems
MeasureItems
ImageItems
AllItems
Constructor & Destructor Documentation
ImageImageTreeModel()
Isis::ImageImageTreeModel::ImageImageTreeModel (ControlNet * cNet, TreeView * v, QObject * parent = 0)
References rebuildItems().
~ImageImageTreeModel()
Isis::ImageImageTreeModel::~ImageImageTreeModel () virtual
Member Function Documentation
applyFilter
void Isis::AbstractTreeModel::applyFilter () slot inherited
References Isis::AbstractTreeModel::cancelSort(), Isis::AbstractTreeModel::filterCountsChanged(), Isis::AbstractParentItem::getChildren(), Isis::AbstractTreeModel::getTopLevelItemCount(), Isis::AbstractTreeModel::rootItem, and Isis::RootItem::setLastVisibleFilteredItem().
Referenced by Isis::AbstractTableModel::applyFilter(), Isis::AbstractTreeModel::setFilter(), and Isis::AbstractTreeModel::setFrozen().
cancelSort
void Isis::AbstractTreeModel::cancelSort () signal inherited
Referenced by Isis::AbstractTreeModel::applyFilter(), rebuildItems(), Isis::ImagePointTreeModel::rebuildItems(), and Isis::PointMeasureTreeModel::rebuildItems().
clear()
void Isis::AbstractTreeModel::clear () protected inherited
References Isis::AbstractTreeModel::rootItem.
filterCountsChanged
void Isis::AbstractTreeModel::filterCountsChanged (int visibleTopLevelItemCount, int topLevelItemCount) signal inherited
This signal is emitted after filtering to provide the number of visible top-level items remaining after the filter was applied, as well as the total number of items that were possible.
Referenced by Isis::AbstractTreeModel::applyFilter(), rebuildItems(), Isis::ImagePointTreeModel::rebuildItems(), and Isis::PointMeasureTreeModel::rebuildItems().
filterProgressChanged
void Isis::AbstractTreeModel::filterProgressChanged (int) signal inherited
Referenced by Isis::AbstractTreeModel::AbstractTreeModel().
filterProgressRangeChanged
void Isis::AbstractTreeModel::filterProgressRangeChanged (int , int) signal inherited
Referenced by Isis::AbstractTreeModel::AbstractTreeModel().
getControlNetwork()
ControlNet * Isis::AbstractTreeModel::getControlNetwork () const protected inherited
Referenced by rebuildItems(), Isis::ImagePointTreeModel::rebuildItems(), and Isis::PointMeasureTreeModel::rebuildItems().
getFilterWidget()
FilterWidget* Isis::AbstractTreeModel::getFilterWidget () const protected inherited
getItemCount()
int Isis::AbstractTreeModel::getItemCount (InterestingItemsFlag flags) const inherited
References Isis::AbstractTreeModel::rootItem.
getItems() [1/2]
QList< AbstractTreeItem * > Isis::AbstractTreeModel::getItems (AbstractTreeItem * item1, AbstractTreeItem * item2, InterestingItemsFlag flags = AllItems, bool ignoreExpansion = false) inherited
References _FILEINFO_, Isis::AbstractParentItem::childCount(), Isis::AbstractParentItem::getFirstVisibleChild(), Isis::IException::Programmer, and Isis::AbstractTreeModel::rootItem.
getItems() [2/2]
QList< AbstractTreeItem * > Isis::AbstractTreeModel::getItems (int start, int end, InterestingItemsFlag flags = AllItems, bool ignoreExpansion = false) inherited
References Isis::AbstractParentItem::childCount(), Isis::AbstractParentItem::getFirstVisibleChild(), Isis::AbstractTreeItem::getLastVisibleChild(), Isis::RootItem::getLastVisibleFilteredItem(), Isis::AbstractTreeModel::isFiltering(), Isis::AbstractTreeItem::parent(), and Isis::AbstractTreeModel::rootItem.
Referenced by Isis::CnetEditorWidget::filteredNetwork(), Isis::AbstractTableModel::getSortedItems(), and Isis::TreeViewContent::mousePressEvent().
getMutex()
QMutex * Isis::AbstractTreeModel::getMutex () const inherited
getRebuildWatcher()
QFutureWatcher< QAtomicPointer< RootItem > > * Isis::AbstractTreeModel::getRebuildWatcher () const protected inherited
Referenced by rebuildItems(), Isis::ImagePointTreeModel::rebuildItems(), and Isis::PointMeasureTreeModel::rebuildItems().
getRootItem()
RootItem * Isis::AbstractTreeModel::getRootItem () const protected inherited
References Isis::AbstractTreeModel::rootItem.
getSelectedItems()
QList< AbstractTreeItem * > Isis::AbstractTreeModel::getSelectedItems (InterestingItemsFlag flags = AllItems, bool ignoreExpansion = false) inherited
References Isis::AbstractParentItem::getFirstVisibleChild(), Isis::AbstractTreeModel::isFiltering(), Isis::AbstractTreeItem::isSelected(), and Isis::AbstractTreeModel::rootItem.
Referenced by Isis::MeasureTableModel::getSelectedItems(), and Isis::PointTableModel::getSelectedItems().
getTopLevelItemCount()
int Isis::AbstractTreeModel::getTopLevelItemCount () const inherited
References Isis::AbstractParentItem::childCount(), and Isis::AbstractTreeModel::rootItem.
Referenced by Isis::AbstractTreeModel::applyFilter(), rebuildItems(), Isis::ImagePointTreeModel::rebuildItems(), and Isis::PointMeasureTreeModel::rebuildItems().
getView()
TreeView * Isis::AbstractTreeModel::getView () const inherited
getVisibleItemCount()
int Isis::AbstractTreeModel::getVisibleItemCount (InterestingItemsFlag flags, bool ignoreExpansion) const inherited
References Isis::AbstractParentItem::getFirstVisibleChild(), Isis::AbstractTreeModel::isFiltering(), and Isis::AbstractTreeModel::rootItem.
Referenced by Isis::MeasureTableModel::getVisibleRowCount(), and Isis::PointTableModel::getVisibleRowCount().
getVisibleSize()
QSize Isis::AbstractTreeModel::getVisibleSize (int indentation) const inherited
indentation is in pixels
References Isis::AbstractTreeModel::AllItems, Isis::AbstractTreeItem::getDataWidth(), Isis::AbstractTreeItem::getDepth(), Isis::AbstractParentItem::getFirstVisibleChild(), Isis::AbstractTreeModel::isFiltering(), and Isis::AbstractTreeModel::rootItem.
Referenced by Isis::TreeViewContent::refresh().
getVisibleTopLevelItemCount()
int Isis::AbstractTreeModel::getVisibleTopLevelItemCount () const inherited
References Isis::AbstractParentItem::getFirstVisibleChild(), Isis::AbstractTreeItem::getNextVisiblePeer(), Isis::AbstractTreeModel::isFiltering(), and Isis::AbstractTreeModel::rootItem.
indexOfVisibleItem()
int Isis::AbstractTreeModel::indexOfVisibleItem (AbstractTreeItem const * item, InterestingItemsFlag flags = AllItems, bool ignoreExpansion = false) const inherited
References Isis::AbstractParentItem::getFirstVisibleChild(), Isis::AbstractTreeModel::isFiltering(), and Isis::AbstractTreeModel::rootItem.
Referenced by Isis::MeasureTableModel::indexOfVisibleItem(), and Isis::PointTableModel::indexOfVisibleItem().
isDrivable()
bool Isis::AbstractTreeModel::isDrivable () const inherited
isFiltering()
bool Isis::AbstractTreeModel::isFiltering () const inherited
Referenced by Isis::AbstractTreeModel::getItems(), Isis::AbstractTreeModel::getSelectedItems(), Isis::AbstractTreeModel::getVisibleItemCount(), Isis::AbstractTreeModel::getVisibleSize(), Isis::AbstractTreeModel::getVisibleTopLevelItemCount(), Isis::AbstractTreeModel::indexOfVisibleItem(), Isis::AbstractTableModel::isFiltering(), Isis::TreeViewContent::refresh(), and Isis::AbstractTableModel::sort().
isFrozen()
bool Isis::AbstractTreeModel::isFrozen () const inherited
Referenced by rebuildItems(), Isis::ImagePointTreeModel::rebuildItems(), and Isis::PointMeasureTreeModel::rebuildItems().
isRebuilding()
bool Isis::AbstractTreeModel::isRebuilding () const inherited
Referenced by Isis::AbstractTableModel::sort().
modelModified
void Isis::AbstractTreeModel::modelModified () signal inherited
queueRebuild()
void Isis::AbstractTreeModel::queueRebuild () inherited
Referenced by rebuildItems(), Isis::ImagePointTreeModel::rebuildItems(), and Isis::PointMeasureTreeModel::rebuildItems().
rebuildItems()
void Isis::ImageImageTreeModel::rebuildItems () virtual
Implements Isis::AbstractTreeModel.
References Isis::AbstractTreeModel::cancelSort(), Isis::AbstractTreeModel::filterCountsChanged(), Isis::AbstractTreeModel::getControlNetwork(), Isis::AbstractTreeModel::getRebuildWatcher(), Isis::AbstractTreeModel::getTopLevelItemCount(), Isis::AbstractTreeModel::isFrozen(), Isis::AbstractTreeModel::queueRebuild(), and Isis::AbstractTreeModel::setRebuilding().
Referenced by ImageImageTreeModel().
rebuildProgressChanged
void Isis::AbstractTreeModel::rebuildProgressChanged (int) signal inherited
Referenced by Isis::AbstractTreeModel::AbstractTreeModel().
rebuildProgressRangeChanged
void Isis::AbstractTreeModel::rebuildProgressRangeChanged (int , int) signal inherited
Referenced by Isis::AbstractTreeModel::AbstractTreeModel().
setDrivable()
void Isis::AbstractTreeModel::setDrivable (bool drivableStatus) inherited
setFilter()
void Isis::AbstractTreeModel::setFilter (FilterWidget * newFilter) inherited
References Isis::AbstractTreeModel::applyFilter().
setFrozen()
void Isis::AbstractTreeModel::setFrozen (bool newFrozenState) inherited
References Isis::AbstractTreeModel::applyFilter(), and Isis::AbstractTreeModel::rebuildItems().
Referenced by Isis::CnetEditorWidget::setTablesFrozen().
setGlobalSelection()
void Isis::AbstractTreeModel::setGlobalSelection (bool selected, InterestingItemsFlag flags = AllItems) inherited
References Isis::AbstractTreeModel::rootItem.
Referenced by Isis::TreeViewContent::keyPressEvent(), Isis::TreeViewContent::mousePressEvent(), Isis::MeasureTableModel::setGlobalSelection(), and Isis::PointTableModel::setGlobalSelection().
setRebuilding()
void Isis::AbstractTreeModel::setRebuilding (bool running) inline inherited
Referenced by rebuildItems(), Isis::ImagePointTreeModel::rebuildItems(), and Isis::PointMeasureTreeModel::rebuildItems().
stopWorking()
void Isis::AbstractTreeModel::stopWorking () inherited
tableSelectionChanged
void Isis::AbstractTreeModel::tableSelectionChanged (QList< AbstractTreeItem * >) signal inherited
treeSelectionChanged
void Isis::AbstractTreeModel::treeSelectionChanged (QList< AbstractTreeItem * >) signal inherited
Member Data Documentation
rootItem
RootItem* Isis::AbstractTreeModel::rootItem protected inherited
Referenced by Isis::AbstractTreeModel::AbstractTreeModel(), Isis::AbstractTreeModel::applyFilter(), Isis::AbstractTreeModel::clear(), Isis::AbstractTreeModel::getItemCount(), Isis::AbstractTreeModel::getItems(), Isis::AbstractTreeModel::getRootItem(), Isis::AbstractTreeModel::getSelectedItems(), Isis::AbstractTreeModel::getTopLevelItemCount(), Isis::AbstractTreeModel::getVisibleItemCount(), Isis::AbstractTreeModel::getVisibleSize(), Isis::AbstractTreeModel::getVisibleTopLevelItemCount(), Isis::AbstractTreeModel::indexOfVisibleItem(), Isis::AbstractTreeModel::setGlobalSelection(), and Isis::AbstractTreeModel::~AbstractTreeModel().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/ImageImageTreeModel.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/ImageImageTreeModel.cpp