Isis Developer Reference: Isis::QIsisApplication Class Reference
Isis::QIsisApplication Class Reference
Handles exceptions which the QT event handlers and QApplication do not handle.
#include <QIsisApplication.h>
Public Slots
void openUrl (QUrl url)
Open a URL in the browser specified by Isis.
Public Member Functions
QIsisApplication (int &argc, char *argv[])
Constructor.
virtual bool notify (QObject *rec, QEvent *ev)
notify - this function overrides the QApplication notify as QT event handlers do not handle exceptions.
Detailed Description
Handles exceptions which the QT event handlers and QApplication do not handle.
This class is derived of QApplication and handles the exception on handled by QT event handlers and QApplication. This class overrides QApplication's notify().
Author
2009-11-24 Sharmila Prasad
Constructor & Destructor Documentation
QIsisApplication()
Isis::QIsisApplication::QIsisApplication (int & argc, char * argv[])
Constructor.
Parameters
argc Pass this in from main(argc, argv)
argv Pass this in from main(argc, argv)
References Isis::PvlObject::clear(), Isis::FileName::expanded(), Isis::Preference::Load(), and Isis::Preference::Preferences().
Member Function Documentation
notify()
bool Isis::QIsisApplication::notify (QObject * rec, QEvent * ev) virtual
notify - this function overrides the QApplication notify as QT event handlers do not handle exceptions.
QIsisApplication handles the exception by catching it and displaying the MessageBox Warning.
Author
Sharmila Prasad (11/24/2009)
Parameters
rec - QObject where the exception occured
ev - Event where the exception occured
Returns
bool
References Isis::IException::what().
openUrl
void Isis::QIsisApplication::openUrl (QUrl url) slot
Open a URL in the browser specified by Isis.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/QIsisApplication/QIsisApplication.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/QIsisApplication/QIsisApplication.cpp