Isis Developer Reference: Isis::PointTableDelegate Class Reference
Isis::PointTableDelegate Class Reference
Delegate for creating, reading, and saving data in the point table.
#include <PointTableDelegate.h>
Public Member Functions
PointTableDelegate ()
virtual ~PointTableDelegate ()
QWidget * getWidget (TableColumn const *) const
void readData (QWidget *, AbstractTreeItem *, TableColumn const *) const
void readData (QWidget *, AbstractTreeItem *, TableColumn const *, QString) const
void saveData (QWidget *, AbstractTreeItem *, TableColumn const *) const
Detailed Description
Delegate for creating, reading, and saving data in the point table.
This class is responsible for creating widgets that can be used to edit cells in the point table. It is also responsible for populating the widgets with values and for saving the values.
Author
????-??-?? Eric Hyer
Constructor & Destructor Documentation
PointTableDelegate()
Isis::PointTableDelegate::PointTableDelegate ()
~PointTableDelegate()
Isis::PointTableDelegate::~PointTableDelegate () virtual
Member Function Documentation
getWidget()
QWidget * Isis::PointTableDelegate::getWidget (TableColumn const * col) const virtual
Implements Isis::AbstractTableDelegate.
References _FILEINFO_, Isis::AbstractPointItem::APrioriRadiusSource, Isis::AbstractPointItem::APrioriSPSource, Isis::AbstractPointItem::EditLock, Isis::AbstractPointItem::getColumn(), Isis::TableColumn::getTitle(), Isis::AbstractPointItem::Ignored, Isis::AbstractPointItem::PointType, Isis::ControlPoint::PointTypeCount, Isis::ControlPoint::PointTypeToString(), Isis::IException::Programmer, and Isis::AbstractPointItem::Reference.
readData() [1/2]
void Isis::PointTableDelegate::readData (QWidget * widget, AbstractTreeItem * row, TableColumn const * col) const virtual
Implements Isis::AbstractTableDelegate.
References Isis::AbstractPointItem::APrioriRadiusSource, Isis::AbstractPointItem::APrioriSPSource, Isis::AbstractPointItem::EditLock, Isis::AbstractPointItem::getColumn(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::AbstractTreeItem::getFormattedData(), Isis::ControlPoint::GetMeasure(), Isis::ControlPoint::GetNumMeasures(), Isis::AbstractTreeItem::getPointer(), Isis::TableColumn::getTitle(), Isis::AbstractPointItem::Ignored, Isis::ControlPoint::IndexOfRefMeasure(), Isis::ControlPoint::IsEditLocked(), Isis::ControlPoint::IsIgnored(), Isis::AbstractPointItem::PointType, Isis::AbstractPointItem::Reference, Isis::ControlPoint::StringToPointType(), Isis::ControlPoint::StringToRadiusSource(), and Isis::ControlPoint::StringToSurfacePointSource().
readData() [2/2]
void Isis::PointTableDelegate::readData (QWidget * widget, AbstractTreeItem * row, TableColumn const * col, QString newData) const virtual
Implements Isis::AbstractTableDelegate.
References Isis::AbstractPointItem::APrioriRadiusSource, Isis::AbstractPointItem::APrioriSPSource, Isis::AbstractPointItem::EditLock, Isis::AbstractPointItem::getColumn(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::AbstractTreeItem::getFormattedData(), Isis::ControlPoint::GetMeasure(), Isis::ControlPoint::GetNumMeasures(), Isis::AbstractTreeItem::getPointer(), Isis::TableColumn::getTitle(), Isis::AbstractPointItem::Ignored, Isis::ControlPoint::IndexOfRefMeasure(), Isis::ControlPoint::IsEditLocked(), Isis::ControlPoint::IsIgnored(), Isis::AbstractPointItem::PointType, Isis::AbstractPointItem::Reference, Isis::ControlPoint::StringToPointType(), Isis::ControlPoint::StringToRadiusSource(), and Isis::ControlPoint::StringToSurfacePointSource().
saveData()
void Isis::PointTableDelegate::saveData (QWidget * widget, AbstractTreeItem * row, TableColumn const * col) const virtual
Implements Isis::AbstractTableDelegate.
References Isis::AbstractPointItem::APrioriRadiusSource, Isis::AbstractPointItem::APrioriSPSource, Isis::AbstractPointItem::EditLock, Isis::AbstractPointItem::getColumn(), Isis::PointTableModel::getPointWarningMessage(), Isis::TableColumn::getTitle(), Isis::AbstractPointItem::Ignored, Isis::AbstractPointItem::PointType, Isis::AbstractPointItem::Reference, and Isis::AbstractTreeItem::setData().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/PointTableDelegate.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/PointTableDelegate.cpp