Isis Developer Reference: Isis::MeasureTableDelegate Class Reference
Isis::MeasureTableDelegate Class Reference
Delegate for creating, reading, and saving data in the measure table.
#include <MeasureTableDelegate.h>
Public Member Functions
MeasureTableDelegate ()
virtual ~MeasureTableDelegate ()
QWidget * getWidget (TableColumn const *) const
void readData (QWidget *, AbstractTreeItem *, TableColumn const *) const
void readData (QWidget *, AbstractTreeItem *, TableColumn const *, QString) const
void saveData (QWidget *, AbstractTreeItem *, TableColumn const *) const
Detailed Description
Delegate for creating, reading, and saving data in the measure table.
This class is responsible for creating widgets that can be used to edit cells in the measure table. It is also responsible for populating the widgets with values and for saving the values.
Author
????-??-?? Eric Hyer
Constructor & Destructor Documentation
MeasureTableDelegate()
Isis::MeasureTableDelegate::MeasureTableDelegate ()
~MeasureTableDelegate()
Isis::MeasureTableDelegate::~MeasureTableDelegate () virtual
Member Function Documentation
getWidget()
QWidget * Isis::MeasureTableDelegate::getWidget (TableColumn const * col) const virtual
Implements Isis::AbstractTableDelegate.
References _FILEINFO_, Isis::AbstractMeasureItem::EditLock, Isis::AbstractMeasureItem::getColumn(), Isis::TableColumn::getTitle(), Isis::AbstractMeasureItem::Ignored, Isis::IException::Programmer, and Isis::AbstractMeasureItem::Type.
readData() [1/2]
void Isis::MeasureTableDelegate::readData (QWidget * widget, AbstractTreeItem * row, TableColumn const * col) const virtual
Implements Isis::AbstractTableDelegate.
References Isis::AbstractMeasureItem::EditLock, Isis::AbstractMeasureItem::getColumn(), Isis::AbstractTreeItem::getFormattedData(), Isis::AbstractTreeItem::getPointer(), Isis::TableColumn::getTitle(), Isis::AbstractMeasureItem::Ignored, Isis::ControlMeasure::IsEditLocked(), Isis::ControlMeasure::IsIgnored(), Isis::ControlMeasure::StringToMeasureType(), and Isis::AbstractMeasureItem::Type.
readData() [2/2]
void Isis::MeasureTableDelegate::readData (QWidget * widget, AbstractTreeItem * row, TableColumn const * col, QString newData) const virtual
Implements Isis::AbstractTableDelegate.
References Isis::AbstractMeasureItem::EditLock, Isis::AbstractMeasureItem::getColumn(), Isis::AbstractTreeItem::getFormattedData(), Isis::AbstractTreeItem::getPointer(), Isis::TableColumn::getTitle(), Isis::AbstractMeasureItem::Ignored, Isis::ControlMeasure::IsEditLocked(), Isis::ControlMeasure::IsIgnored(), Isis::ControlMeasure::StringToMeasureType(), and Isis::AbstractMeasureItem::Type.
saveData()
void Isis::MeasureTableDelegate::saveData (QWidget * widget, AbstractTreeItem * row, TableColumn const * col) const virtual
Implements Isis::AbstractTableDelegate.
References Isis::AbstractMeasureItem::EditLock, Isis::AbstractMeasureItem::getColumn(), Isis::MeasureTableModel::getMeasureWarningMessage(), Isis::TableColumn::getTitle(), Isis::AbstractMeasureItem::Ignored, Isis::AbstractTreeItem::setData(), and Isis::AbstractMeasureItem::Type.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/MeasureTableDelegate.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/MeasureTableDelegate.cpp