Isis Developer Reference: Isis::AtmosModel Class Reference
Isis::AtmosModel Class Reference abstract
Radiometric And Photometric Correction
Isotropic atmos scattering model.
#include <AtmosModel.h>
Public Member Functions
AtmosModel (Pvl &pvl, PhotoModel &pmodel)
Create an AtmosModel object.
virtual ~AtmosModel ()
Empty destructor.
void CalcAtmEffect (double pha, double inc, double ema, double *pstd, double *trans, double *trans0, double *sbar, double *transs)
Calculate the atmospheric scattering effect using photometric angle information.
virtual void SetStandardConditions (bool standard)
Used to calculate atmosphere at standard conditions.
void GenerateAhTable ()
This method computes the values of the atmospheric Ah table and sets the properties of the atmospheric Ah spline.
void GenerateHahgTables ()
This method computes the values of the atmospheric Hahg and Hahg0 tables and sets the properties of the atmospheric Hahg and Hahg0 splines.
void GenerateHahgTablesShadow ()
This method is a modified version of the GenerateHahgTables method and is used solely for shadow modeling.
void SetAtmosAtmSwitch (const int atmswitch)
Set the switch that controls the function that will be integrated.
void SetAtmosBha (const double bha)
Set the Anisotropic Atmospheric function parameter.
void SetAtmosHga (const double hga)
Set the Hapke atmospheric function parameter.
void SetAtmosInc (const double inc)
Set the incidence angle.
void SetAtmosNulneg (const string nulneg)
Set the Atmospheric function parameter.
void SetAtmosPhi (const double phi)
Set the azimuth angle.
void SetAtmosTau (const double tau)
Set the Atmospheric function parameter.
void SetAtmosTauref (const double tauref)
Set the Atmospheric function parameter.
void SetAtmosWha (const double wha)
Set the Atmospheric function parameter.
void SetAtmosHnorm (const double hnorm)
Set the Atmospheric function parameter.
void SetAtmosIord (const string offset)
Set additive offset in fit.
void SetAtmosEstTau (const string esttau)
Estimate the optical depth tau using shadows.
string AlgorithmName () const
Return atmospheric algorithm name.
bool AtmosAdditiveOffset () const
Allow additive offset in fit?
double AtmosHnorm () const
Return atmospheric Hnorm value.
double AtmosBha () const
Return atmospheric Bha value.
double AtmosTau () const
Return atmospheric Tau value.
double AtmosWha () const
Return atmospheric Wha value.
double AtmosHga () const
Return atmospheric Hga value.
double AtmosTauref () const
Return atmospheric Tauref value.
bool AtmosNulneg () const
Return atmospheric Nulneg value.
double AtmosAb () const
Return atmospheric Ab value.
double AtmosHahgsb () const
Return atmospheric Hahgsb value.
int AtmosNinc () const
Return atmospheric Ninc value.
double AtmosMunot () const
Return atmospheric Munot value.
vector< double > AtmosIncTable ()
Return atmospheric IncTable value.
vector< double > AtmosAhTable ()
Return atmospheric AhTable value.
vector< double > AtmosHahgtTable ()
Return atmospheric HahgtTable value.
vector< double > AtmosHahgt0Table ()
Return atmospheric Hahgt0Table value.
NumericalApproximation AtmosAhSpline ()
If GenerateAhTable() has been called this returns a clamped cubic spline of the data set (p_atmosIncTable, p_atmosAhTable) with first derivatives of the endpoints equal to 1.0e30.
NumericalApproximation AtmosHahgtSpline ()
If GenerateHahgTables() has been called this returns a clamped cubic spline of the data set (p_atmosIncTable, p_atmosHahgtTable) with first derivatives of the endpoints equal to 1.0e30.
NumericalApproximation AtmosHahgt0Spline ()
If GenerateHahgTables() has been called this returns a clamped cubic spline of the data set (p_atmosIncTable, p_atmosHahgt0Table) with first derivatives of the endpoints equal to 1.0e30.
Static Public Member Functions
static double G11Prime (double tau)
Perform Chandra and Van de Hulst's series approximation for the g'11 function needed in second order scattering theory.
static double Ei (double x)
This routine computes the exponential integral, Ei(x).
static double En (unsigned int n, double x)
This routine evaluates the generalized exponential integral, En(x).
Protected Member Functions
virtual void AtmosModelAlgorithm (double phase, double incidence, double emission)=0
void SetAlgorithmName (string name)
void SetAtmosNulneg (bool nulneg)
void SetAtmosIord (bool offset)
void SetAtmosEstTau (bool esttau)
void SetOldTau (double tau)
void SetOldWha (double wha)
PhotoModel * GetPhotoModel () const
bool StandardConditions () const
bool TauOrWhaChanged () const
Checks whether tau or wha have changed.
double Eulgam () const
Protected Attributes
int p_atmosAtmSwitch
int p_atmosNinc
double p_atmosBha
double p_atmosBhasave
double p_atmosHgasave
double p_atmosTauref
double p_atmosTausave
double p_atmosWhasave
double p_pstd
Pure atmospheric-scattering term.
double p_trans
Transmission of surface reflected light through the atmosphere overall.
double p_trans0
Transmission of surface reflected light through the atmosphere with no scatterings in the atmosphere.
double p_transs
Transmission of light that must be subtracted from the flat surface model to get the shadow model.
double p_sbar
Illumination of the ground by the sky.
double p_atmosHga
double p_atmosTau
double p_atmosWha
double p_atmosAb
double p_atmosHnorm
Atmospheric shell thickness normalized to planet radius.
bool p_atmosAddOffset
Allow additive offset in fit.
bool p_atmosEstTau
Estimate optical depth tau using shadows.
vector< double > p_atmosIncTable
vector< double > p_atmosAhTable
double p_atmosHahgsb
vector< double > p_atmosHahgtTable
vector< double > p_atmosHahgt0Table
double p_atmosInc
double p_atmosPhi
double p_atmosMunot
double p_atmosSini
double p_atmosCosphi
double p_atmosEulgam
NumericalApproximation p_atmosAhSpline
Spline object for the atmospheric Ah Table. Properties are set in GenerateAhTable().
NumericalApproximation p_atmosHahgtSpline
Spline object for the atmospheric Hahg Table. Properties are set in GenerateHahgTables().
NumericalApproximation p_atmosHahgt0Spline
Spline object for the atmospheric Hahg0 Table. Properties are set in GenerateHahgTables().
Friends
class NumericalAtmosApprox
Detailed Description
Isotropic atmos scattering model.
Author
1998-12-21 Randy Kirk
Constructor & Destructor Documentation
AtmosModel()
Isis::AtmosModel::AtmosModel (Pvl & pvl, PhotoModel & pmodel)
Create an AtmosModel object.
Because this is a pure virtual class you can not create an AtmosModel class directly. Instead, see the Isis::AtmosModelFactory class.
Parameters
pvl Isis::Pvl object containing a valid AtmosModel specification
pmodel PhotoModel object containing valud AtmosModel data
See also
atmosphericModels.doc
References Isis::PvlObject::findObject(), and Isis::PvlContainer::hasKeyword().
~AtmosModel()
virtual Isis::AtmosModel::~AtmosModel () inline virtual
Empty destructor.
Member Function Documentation
AlgorithmName()
string Isis::AtmosModel::AlgorithmName () const inline
Return atmospheric algorithm name.
AtmosAb()
double Isis::AtmosModel::AtmosAb () const inline
Return atmospheric Ab value.
Referenced by Isis::AlbedoAtm::NormModelAlgorithm(), Isis::ShadeAtm::NormModelAlgorithm(), Isis::TopoAtm::NormModelAlgorithm(), and Isis::TopoAtm::TopoAtm().
AtmosAdditiveOffset()
bool Isis::AtmosModel::AtmosAdditiveOffset () const inline
Allow additive offset in fit?
AtmosAhSpline()
NumericalApproximation Isis::AtmosModel::AtmosAhSpline () inline
If GenerateAhTable() has been called this returns a clamped cubic spline of the data set (p_atmosIncTable, p_atmosAhTable) with first derivatives of the endpoints equal to 1.0e30.
Otherwise, it is a natural cubic spline with an empty data set.
Returns
NumericalApproximation Cubic spline
Referenced by Isis::AlbedoAtm::AlbedoAtm(), Isis::AlbedoAtm::NormModelAlgorithm(), Isis::ShadeAtm::NormModelAlgorithm(), Isis::TopoAtm::NormModelAlgorithm(), and Isis::TopoAtm::TopoAtm().
AtmosAhTable()
vector<double> Isis::AtmosModel::AtmosAhTable () inline
Return atmospheric AhTable value.
AtmosBha()
double Isis::AtmosModel::AtmosBha () const inline
Return atmospheric Bha value.
AtmosHahgsb()
double Isis::AtmosModel::AtmosHahgsb () const inline
Return atmospheric Hahgsb value.
AtmosHahgt0Spline()
NumericalApproximation Isis::AtmosModel::AtmosHahgt0Spline () inline
If GenerateHahgTables() has been called this returns a clamped cubic spline of the data set (p_atmosIncTable, p_atmosHahgt0Table) with first derivatives of the endpoints equal to 1.0e30.
Otherwise, it is a natural cubic spline with an empty data set.
Returns
NumericalApproximation Cubic spline
AtmosHahgt0Table()
vector<double> Isis::AtmosModel::AtmosHahgt0Table () inline
Return atmospheric Hahgt0Table value.
AtmosHahgtSpline()
NumericalApproximation Isis::AtmosModel::AtmosHahgtSpline () inline
If GenerateHahgTables() has been called this returns a clamped cubic spline of the data set (p_atmosIncTable, p_atmosHahgtTable) with first derivatives of the endpoints equal to 1.0e30.
Otherwise, it is a natural cubic spline with an empty data set.
Returns
NumericalApproximation Cubic spline
AtmosHahgtTable()
vector<double> Isis::AtmosModel::AtmosHahgtTable () inline
Return atmospheric HahgtTable value.
AtmosHga()
double Isis::AtmosModel::AtmosHga () const inline
Return atmospheric Hga value.
Referenced by Isis::NumericalAtmosApprox::InrFunc2Bint().
AtmosHnorm()
double Isis::AtmosModel::AtmosHnorm () const inline
Return atmospheric Hnorm value.
AtmosIncTable()
vector<double> Isis::AtmosModel::AtmosIncTable () inline
Return atmospheric IncTable value.
AtmosModelAlgorithm()
virtual void Isis::AtmosModel::AtmosModelAlgorithm (double phase, double incidence, double emission) protected pure virtual
Implemented in Isis::Isotropic2, Isis::Isotropic1, Isis::HapkeAtm2, Isis::HapkeAtm1, Isis::Anisotropic2, and Isis::Anisotropic1.
AtmosMunot()
double Isis::AtmosModel::AtmosMunot () const inline
Return atmospheric Munot value.
AtmosNinc()
int Isis::AtmosModel::AtmosNinc () const inline
Return atmospheric Ninc value.
AtmosNulneg()
bool Isis::AtmosModel::AtmosNulneg () const inline
Return atmospheric Nulneg value.
AtmosTau()
double Isis::AtmosModel::AtmosTau () const inline
Return atmospheric Tau value.
Referenced by Isis::NumericalAtmosApprox::InrFunc2Bint().
AtmosTauref()
double Isis::AtmosModel::AtmosTauref () const inline
Return atmospheric Tauref value.
AtmosWha()
double Isis::AtmosModel::AtmosWha () const inline
Return atmospheric Wha value.
Referenced by Isis::HapkeAtm1::AtmosModelAlgorithm(), and Isis::HapkeAtm2::AtmosModelAlgorithm().
CalcAtmEffect()
void Isis::AtmosModel::CalcAtmEffect (double pha, double inc, double ema, double * pstd, double * trans, double * trans0, double * sbar, double * transs)
Calculate the atmospheric scattering effect using photometric angle information.
Parameters
pha phase angle
inc incidence angle
ema emission angle
pstd pure atmospheric-scattering term
trans transmission of surface reflected light through the atmosphere overall
trans0 transmission of surface reflected light through the atmosphere with no scatterings in the atmosphere
sbar illumination of the ground by the sky
Exceptions
Isis::IException::User "Invalid photometric angles"
Referenced by Isis::AlbedoAtm::AlbedoAtm(), Isis::AlbedoAtm::NormModelAlgorithm(), Isis::ShadeAtm::NormModelAlgorithm(), Isis::TopoAtm::NormModelAlgorithm(), and Isis::TopoAtm::TopoAtm().
Ei()
double Isis::AtmosModel::Ei (double x) static
This routine computes the exponential integral, Ei(x).
This is defined as
\[ Ei(x) = - \int_{-x}^{\infty} \frac{e^{-t}}{t}\mathrm{d}t = \int_{-\infty}^{x} \frac{e^{t}}{t}\mathrm{d}t \]
for x > 0.
For small x, this method uses the power series,
\[ Ei(x) = \gamma + \ln x + \frac{x}{1*1!} + \frac{x^2}{2*2!} + ... \]
where \(\gamma = 0.5772156649... \) is Euler's constant, and for large x, the asymptotic series is used,
\[ Ei(x) \sim \frac{e^x}{x} (1 + \frac{1!}{x} + \frac{2!}{x^2} + ...) \]
See also
mathworld.wolfram.com/ExponentialIntegral.html
Parameters
x Value at which the exponential integral will be computed, x > 0.0
Returns
double The exponential integral for the given x.
Exceptions
Isis::IException::Programmer "Invalid arguments. Definition requires x > 0.0."
Isis::IException::Math "Power series failed to converge"
References _FILEINFO_.
Referenced by Isis::Anisotropic2::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), and Isis::Isotropic2::AtmosModelAlgorithm().
En()
double Isis::AtmosModel::En (unsigned int n, double x) static
This routine evaluates the generalized exponential integral, En(x).
This is defined as
\[ E_n(x) = \int_{1}^{\infty} \frac{e^{-xt}}{t^n}\mathrm{d}t \mathrm{ for } x \in \mathbb{R }, n \in \mathbb{Z } \mathrm{such that } x \ge 0.0, n \ge 0 \]
Notice that if x = 0, then the equation is not defined for n = 0 or n = 1, as these will result in \(E_n(x) = \infty \).
This method uses the following for cases:
For n > 1 and x = 0.0,
\[ E_n(0) = \frac{1}{n-1} \]
For n = 0 and x > 0.0,
\[ E_0(x) = \frac{e^{-x}}{x} \]
For \(x >\sim 1.0 \), Lentz's continued fraction algorithm is used,
\[ E_n(x) = e^{-x}(\frac{1}{x + n - \frac{1*n}{x + n + 2 - \frac{2(n+1)}{x + n + 4 - ...}}}) \]
For \(0.0 < x <\sim 1.0 \), series representation is used,
\[ E_n(x) = \frac{(-x)^{n-1}}{(n-1)!}[- \ln x + \psi (n)] - \sum_{m=0, m \neq n-1}^{\infty}\frac{(-x)^m}{(m-n+1)m!} \]
where \(\psi (1) = \gamma \) and \(\psi (n) = - \gamma + \sum_{m=1}^{n-1} \frac{1}{m}\) and \(\gamma = 0.5772156649... \) is Euler's constant.
The parameter n is of type unsigned int since n cannot be negative.
The routine allows fast evaluation of En(x) to any accuracy, \(\epsilon\), within the reach of your machine's word length for floating-point numbers. The only modification required for increased accuracy is to supply Euler's constant with enough significant digits.
See also
mathworld.wolfram.com/En-Function.html
Parameters
n Integer value at which the exponential integral will be evaluated (n >= 0)
x The exponential integral En(x) will be evaluated
Returns
double Value of the exponential integral for the give n and x.
Exceptions
Isis::IException::Programmer "Invalid arguments. Definition requires (x > 0.0 and n >=0) or (x >= 0.0 and n > 1)." @throws Isis::IException::Math "Continued fraction failed to converge" @throws Isis::IException::Math "Series representation failed to converge"
References _FILEINFO_.
Referenced by Isis::Anisotropic1::AtmosModelAlgorithm(), Isis::Anisotropic2::AtmosModelAlgorithm(), Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), Isis::Isotropic1::AtmosModelAlgorithm(), and Isis::Isotropic2::AtmosModelAlgorithm().
Eulgam()
double Isis::AtmosModel::Eulgam () const inline protected
Referenced by Isis::Anisotropic2::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), and Isis::Isotropic2::AtmosModelAlgorithm().
G11Prime()
double Isis::AtmosModel::G11Prime (double tau) static
Perform Chandra and Van de Hulst's series approximation for the g'11 function needed in second order scattering theory.
Parameters
tau normal optical depth of atmosphere
Returns
double Value of the g'11 function evaluated at the given tau
References MAX, and Isis::PI.
Referenced by Isis::Anisotropic2::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), and Isis::Isotropic2::AtmosModelAlgorithm().
GenerateAhTable()
void Isis::AtmosModel::GenerateAhTable ()
This method computes the values of the atmospheric Ah table and sets the properties of the atmospheric Ah spline.
It obtains the hemispheric albedo by integrating the photometric function times mu over mu = 0 to 1 and then over phi = 0 to 2*pi to calculate the hemispheric reflectance Ah needed for the photometric model with atmosphere. The Trapezoid rule is applied to the table of Ah to obtain bihemispheric albedo Ab. The parameter p_atmosAtmSwitch is set to 0 to integrate Ah.
References Isis::PI, Isis::NumericalAtmosApprox::RombergsMethod(), and Isis::IString::UpCase().
Referenced by Isis::AlbedoAtm::AlbedoAtm(), Isis::ShadeAtm::NormModelAlgorithm(), and Isis::TopoAtm::TopoAtm().
GenerateHahgTables()
void Isis::AtmosModel::GenerateHahgTables ()
This method computes the values of the atmospheric Hahg and Hahg0 tables and sets the properties of the atmospheric Hahg and Hahg0 splines.
It integrates functions involving the single particle phase function (assumed to be Hapke Henyey-Greenstein) over mu = 0 to 1 and then over phi = 0 to 2*pi to calculate the corrections needed for the anisotropic photometric model with atmosphere. The Trapezoid rule is applied to the table of Ah to obtain bihemispheric albedo Ab. The parameter p_atmosAtmSwitch is set to 1, 2, 3 to evaluate the 3 required integrals.
References Isis::PI, Isis::NumericalApproximation::Reset(), and Isis::NumericalAtmosApprox::RombergsMethod().
Referenced by Isis::HapkeAtm1::AtmosModelAlgorithm(), and Isis::HapkeAtm2::AtmosModelAlgorithm().
GenerateHahgTablesShadow()
void Isis::AtmosModel::GenerateHahgTablesShadow ()
This method is a modified version of the GenerateHahgTables method and is used solely for shadow modeling.
Unlike the GenerateHahgTables method, this method does not tabulate the first or third integrals. It only evaluates the middle integral that corrects the sbar variable (illumination of the ground by the sky).
References Isis::PI, Isis::NumericalApproximation::Reset(), and Isis::NumericalAtmosApprox::RombergsMethod().
Referenced by Isis::HapkeAtm1::AtmosModelAlgorithm(), and Isis::HapkeAtm2::AtmosModelAlgorithm().
GetPhotoModel()
PhotoModel* Isis::AtmosModel::GetPhotoModel () const inline protected
SetAlgorithmName()
void Isis::AtmosModel::SetAlgorithmName (string name) inline protected
SetAtmosAtmSwitch()
void Isis::AtmosModel::SetAtmosAtmSwitch (const int atmswitch)
Set the switch that controls the function that will be integrated.
This method is only used for testing the methods in this class. This parameter is limited to the values 0, 1, 2, and 3.
Parameters
atmswitch Internal atmospheric function parameter, there is no default
Exceptions
Isis::IException::User "Invalid value of atmospheric atmswitch"
References _FILEINFO_.
SetAtmosBha()
void Isis::AtmosModel::SetAtmosBha (const double bha)
Set the Anisotropic Atmospheric function parameter.
This is the coefficient of the single particle Legendre phase function. This parameter is limited to values that are >=-1 and <=1.
Parameters
bha Anisotropic atmospheric function parameter, default is 0.85
Exceptions
Isis::IException::User "Invalid value of atmospheric bha"
References _FILEINFO_.
SetAtmosEstTau() [1/2]
void Isis::AtmosModel::SetAtmosEstTau (bool esttau) inline protected
SetAtmosEstTau() [2/2]
void Isis::AtmosModel::SetAtmosEstTau (const string esttau)
Estimate the optical depth tau using shadows.
Author
Janet Barrett (12/16/2011)
Parameters
esttau true/false
References _FILEINFO_, and Isis::IString::UpCase().
SetAtmosHga()
void Isis::AtmosModel::SetAtmosHga (const double hga)
Set the Hapke atmospheric function parameter.
This is the coefficient of the single particle Henyey-Greenstein phase function. This parameter is limited to values that are >-1 and <1.
Parameters
hga Hapke atmospheric function parameter, default is 0.68
Exceptions
Isis::IException::User "Invalid value of atmospheric hga"
References _FILEINFO_.
SetAtmosHnorm()
void Isis::AtmosModel::SetAtmosHnorm (const double hnorm)
Set the Atmospheric function parameter.
This is the atmospheric shell thickness normalized to the planet radius and is used to modify angles to get more accurate path lengths near the terminator (ratio of scale height to the planetary radius). This parameter is limited to values that are >=0.
Parameters
hnorm Atmospheric function parameter, default is 0.003
References _FILEINFO_, and Isis::toString().
SetAtmosInc()
void Isis::AtmosModel::SetAtmosInc (const double inc)
Set the incidence angle.
This method is only used for testing the methods in this class. This parameter is limited to values >=0 and <=90.
Parameters
inc Internal atmospheric function parameter, there is no default
Exceptions
Isis::IException::User "Invalid value of atmospheric inc"
References _FILEINFO_, and Isis::PI.
SetAtmosIord() [1/2]
void Isis::AtmosModel::SetAtmosIord (bool offset) inline protected
SetAtmosIord() [2/2]
void Isis::AtmosModel::SetAtmosIord (const string offset)
Set additive offset in fit.
Author
Sharmila Prasad (8/18/2011)
Parameters
offset true/false
References _FILEINFO_, and Isis::IString::UpCase().
SetAtmosNulneg() [1/2]
void Isis::AtmosModel::SetAtmosNulneg (bool nulneg) inline protected
SetAtmosNulneg() [2/2]
void Isis::AtmosModel::SetAtmosNulneg (const string nulneg)
Set the Atmospheric function parameter.
This determines if negative values after removal of atmospheric effects will be set to NULL. This parameter is limited to values of YES or NO.
Parameters
nulneg Atmospheric function parameter, default is NO
Exceptions
Isis::IException::User "Invalid value of atmospheric nulneg"
References _FILEINFO_, and Isis::IString::UpCase().
SetAtmosPhi()
void Isis::AtmosModel::SetAtmosPhi (const double phi)
Set the azimuth angle.
This method is only used for testing the methods in this class. This parameter is limited to values >=0 and <=360.
Parameters
phi Internal atmospheric function parameter, there is no default
Exceptions
Isis::IException::User "Invalid value of atmospheric phi"
References _FILEINFO_, and Isis::PI.
SetAtmosTau()
void Isis::AtmosModel::SetAtmosTau (const double tau)
Set the Atmospheric function parameter.
This specifies the normal optical depth of the atmosphere. This parameter is limited to values that are >=0.
Parameters
tau Atmospheric function parameter, default is 0.28
Exceptions
Isis::IException::User "Invalid value of atmospheric tau"
References _FILEINFO_.
SetAtmosTauref()
void Isis::AtmosModel::SetAtmosTauref (const double tauref)
Set the Atmospheric function parameter.
This specifies the reference optical depth of the atmosphere to which the image will be normalized. This parameter is limited to values that are >=0.
Parameters
tauref Atmospheric function parameter, default is 0.0
Exceptions
Isis::IException::User "Invalid value of atmospheric tauref"
References _FILEINFO_.
SetAtmosWha()
void Isis::AtmosModel::SetAtmosWha (const double wha)
Set the Atmospheric function parameter.
This is the single- scattering albedo of atmospheric particles. This parameter is limited to values that are >0 and <=1.
Parameters
wha Atmospheric function parameter, default is 0.95
Exceptions
Isis::IException::User "Invalid value of atmospheric wha"
References _FILEINFO_.
SetOldTau()
void Isis::AtmosModel::SetOldTau (double tau) inline protected
Referenced by Isis::Anisotropic1::AtmosModelAlgorithm(), Isis::Anisotropic2::AtmosModelAlgorithm(), Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), Isis::Isotropic1::AtmosModelAlgorithm(), and Isis::Isotropic2::AtmosModelAlgorithm().
SetOldWha()
void Isis::AtmosModel::SetOldWha (double wha) inline protected
Referenced by Isis::Anisotropic1::AtmosModelAlgorithm(), Isis::Anisotropic2::AtmosModelAlgorithm(), Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), Isis::Isotropic1::AtmosModelAlgorithm(), and Isis::Isotropic2::AtmosModelAlgorithm().
SetStandardConditions()
void Isis::AtmosModel::SetStandardConditions (bool standard) virtual
Used to calculate atmosphere at standard conditions.
Referenced by Isis::AlbedoAtm::AlbedoAtm(), and Isis::TopoAtm::TopoAtm().
StandardConditions()
bool Isis::AtmosModel::StandardConditions () const inline protected
TauOrWhaChanged()
bool Isis::AtmosModel::TauOrWhaChanged () const protected
Checks whether tau or wha have changed.
Returns
bool True if either have changed.
Referenced by Isis::Anisotropic1::AtmosModelAlgorithm(), Isis::Anisotropic2::AtmosModelAlgorithm(), Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), Isis::Isotropic1::AtmosModelAlgorithm(), and Isis::Isotropic2::AtmosModelAlgorithm().
Friends And Related Function Documentation
NumericalAtmosApprox
friend class NumericalAtmosApprox friend
Member Data Documentation
p_atmosAb
double Isis::AtmosModel::p_atmosAb protected
p_atmosAddOffset
bool Isis::AtmosModel::p_atmosAddOffset protected
Allow additive offset in fit.
p_atmosAhSpline
NumericalApproximation Isis::AtmosModel::p_atmosAhSpline protected
Spline object for the atmospheric Ah Table. Properties are set in GenerateAhTable().
p_atmosAhTable
vector<double> Isis::AtmosModel::p_atmosAhTable protected
p_atmosAtmSwitch
int Isis::AtmosModel::p_atmosAtmSwitch protected
Referenced by Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), and Isis::NumericalAtmosApprox::InrFunc2Bint().
p_atmosBha
double Isis::AtmosModel::p_atmosBha protected
Referenced by Isis::Anisotropic1::AtmosModelAlgorithm(), and Isis::Anisotropic2::AtmosModelAlgorithm().
p_atmosBhasave
double Isis::AtmosModel::p_atmosBhasave protected
p_atmosCosphi
double Isis::AtmosModel::p_atmosCosphi protected
Referenced by Isis::NumericalAtmosApprox::InrFunc2Bint(), and Isis::NumericalAtmosApprox::OutrFunc2Bint().
p_atmosEstTau
bool Isis::AtmosModel::p_atmosEstTau protected
Estimate optical depth tau using shadows.
Referenced by Isis::HapkeAtm1::AtmosModelAlgorithm(), and Isis::HapkeAtm2::AtmosModelAlgorithm().
p_atmosEulgam
double Isis::AtmosModel::p_atmosEulgam protected
p_atmosHahgsb
double Isis::AtmosModel::p_atmosHahgsb protected
Referenced by Isis::HapkeAtm1::AtmosModelAlgorithm(), and Isis::HapkeAtm2::AtmosModelAlgorithm().
p_atmosHahgt0Spline
NumericalApproximation Isis::AtmosModel::p_atmosHahgt0Spline protected
Spline object for the atmospheric Hahg0 Table. Properties are set in GenerateHahgTables().
Referenced by Isis::HapkeAtm1::AtmosModelAlgorithm(), and Isis::HapkeAtm2::AtmosModelAlgorithm().
p_atmosHahgt0Table
vector<double> Isis::AtmosModel::p_atmosHahgt0Table protected
p_atmosHahgtSpline
NumericalApproximation Isis::AtmosModel::p_atmosHahgtSpline protected
Spline object for the atmospheric Hahg Table. Properties are set in GenerateHahgTables().
Referenced by Isis::HapkeAtm1::AtmosModelAlgorithm(), and Isis::HapkeAtm2::AtmosModelAlgorithm().
p_atmosHahgtTable
vector<double> Isis::AtmosModel::p_atmosHahgtTable protected
p_atmosHga
double Isis::AtmosModel::p_atmosHga protected
Referenced by Isis::HapkeAtm1::AtmosModelAlgorithm(), and Isis::HapkeAtm2::AtmosModelAlgorithm().
p_atmosHgasave
double Isis::AtmosModel::p_atmosHgasave protected
p_atmosHnorm
double Isis::AtmosModel::p_atmosHnorm protected
Atmospheric shell thickness normalized to planet radius.
Referenced by Isis::Anisotropic1::AtmosModelAlgorithm(), Isis::Anisotropic2::AtmosModelAlgorithm(), Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), Isis::Isotropic1::AtmosModelAlgorithm(), and Isis::Isotropic2::AtmosModelAlgorithm().
p_atmosInc
double Isis::AtmosModel::p_atmosInc protected
Referenced by Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), and Isis::NumericalAtmosApprox::InrFunc2Bint().
p_atmosIncTable
vector<double> Isis::AtmosModel::p_atmosIncTable protected
p_atmosMunot
double Isis::AtmosModel::p_atmosMunot protected
Referenced by Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), and Isis::NumericalAtmosApprox::InrFunc2Bint().
p_atmosNinc
int Isis::AtmosModel::p_atmosNinc protected
p_atmosPhi
double Isis::AtmosModel::p_atmosPhi protected
Referenced by Isis::NumericalAtmosApprox::OutrFunc2Bint().
p_atmosSini
double Isis::AtmosModel::p_atmosSini protected
Referenced by Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), and Isis::NumericalAtmosApprox::InrFunc2Bint().
p_atmosTau
double Isis::AtmosModel::p_atmosTau protected
Referenced by Isis::Anisotropic1::AtmosModelAlgorithm(), Isis::Anisotropic2::AtmosModelAlgorithm(), Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), Isis::Isotropic1::AtmosModelAlgorithm(), and Isis::Isotropic2::AtmosModelAlgorithm().
p_atmosTauref
double Isis::AtmosModel::p_atmosTauref protected
p_atmosTausave
double Isis::AtmosModel::p_atmosTausave protected
p_atmosWha
double Isis::AtmosModel::p_atmosWha protected
Referenced by Isis::Anisotropic1::AtmosModelAlgorithm(), Isis::Anisotropic2::AtmosModelAlgorithm(), Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), Isis::Isotropic1::AtmosModelAlgorithm(), and Isis::Isotropic2::AtmosModelAlgorithm().
p_atmosWhasave
double Isis::AtmosModel::p_atmosWhasave protected
p_pstd
double Isis::AtmosModel::p_pstd protected
Pure atmospheric-scattering term.
Referenced by Isis::Anisotropic1::AtmosModelAlgorithm(), Isis::Anisotropic2::AtmosModelAlgorithm(), Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), Isis::Isotropic1::AtmosModelAlgorithm(), and Isis::Isotropic2::AtmosModelAlgorithm().
p_sbar
double Isis::AtmosModel::p_sbar protected
Illumination of the ground by the sky.
Referenced by Isis::Anisotropic1::AtmosModelAlgorithm(), Isis::Anisotropic2::AtmosModelAlgorithm(), Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), Isis::Isotropic1::AtmosModelAlgorithm(), and Isis::Isotropic2::AtmosModelAlgorithm().
p_trans
double Isis::AtmosModel::p_trans protected
Transmission of surface reflected light through the atmosphere overall.
Referenced by Isis::Anisotropic1::AtmosModelAlgorithm(), Isis::Anisotropic2::AtmosModelAlgorithm(), Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), Isis::Isotropic1::AtmosModelAlgorithm(), and Isis::Isotropic2::AtmosModelAlgorithm().
p_trans0
double Isis::AtmosModel::p_trans0 protected
Transmission of surface reflected light through the atmosphere with no scatterings in the atmosphere.
Referenced by Isis::Anisotropic1::AtmosModelAlgorithm(), Isis::Anisotropic2::AtmosModelAlgorithm(), Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), Isis::Isotropic1::AtmosModelAlgorithm(), and Isis::Isotropic2::AtmosModelAlgorithm().
p_transs
double Isis::AtmosModel::p_transs protected
Transmission of light that must be subtracted from the flat surface model to get the shadow model.
Referenced by Isis::Anisotropic1::AtmosModelAlgorithm(), Isis::Anisotropic2::AtmosModelAlgorithm(), Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), Isis::Isotropic1::AtmosModelAlgorithm(), and Isis::Isotropic2::AtmosModelAlgorithm().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/AtmosModel/AtmosModel.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/AtmosModel/AtmosModel.cpp