Isis Developer Reference: Isis::BundleMeasure Class Reference
Isis::BundleMeasure Class Reference
Control Networks
A container class for a ControlMeasure.
#include <BundleMeasure.h>
Public Member Functions
BundleMeasure (ControlMeasure *controlMeasure, BundleControlPoint *bundleControlPoint)
Constructor.
BundleMeasure (const BundleMeasure &src)
Copy constructor.
~BundleMeasure ()
Destructor.
BundleMeasure & operator= (const BundleMeasure &src)
Assignment operator.
void setParentObservation (QSharedPointer< BundleObservation > observation)
Sets the parent bundle observation.
void setParentImage (QSharedPointer< BundleImage > image)
Sets the parent bundle image.
void setRejected (bool reject)
Sets the BundleMeasure's status to rejected or not rejected.
void setImage ()
Sets the BundleMeasure's status to rejected or not rejected.
void setNormalsPositionBlockIndex (int index)
Sets block index into normal equations for position piecewise polynomial segment.
void setNormalsPointingBlockIndex (int index)
Sets block index into normal equations for pointing piecewise polynomial segment.
void setFocalPlaneResidualsMillimeters ()
Computes and sets measure focal plane residuals in millimeters.
void setSigma (double sigma)
Sets sigma (i.e.
bool isRejected () const
Determines whether or not this BundleMeasure is rejected.
Camera * camera () const
Accesses the associated camera for this bundle measure.
BundleControlPoint * parentControlPoint ()
Accesses the parent BundleControlPoint for this bundle measure.
QSharedPointer< BundleImage > parentBundleImage ()
Access the parent BundleImage for this bundle measure.
QSharedPointer< BundleObservation > parentBundleObservation ()
Accesses the parent BundleObservation for this bundle measure.
const QSharedPointer< BundleObservationSolveSettings > observationSolveSettings ()
Accesses the parent observation's solve settings.
double sample () const
Accesses the current sample measurement for this control measure.
double sampleResidual () const
Accesses the sample residual for this control measure.
double line () const
Accesses the current line measurement for this control measure.
double lineResidual () const
Accesses the line residual for this control measure.
double sigma () const
Accesses the measure sigma.
double weight () const
Accesses measure weight for bundle.
double weightSqrt () const
Accesses sqrt of measure weight for bundle.
double residualMagnitude () const
Accesses the residual magnitude for this control measure.
double xFocalPlaneResidual () const
Accesses the focal plane x-coordinate residual in millimeters.
double yFocalPlaneResidual () const
Accesses the focal plane y-coordinate residual in millimeters.
QString cubeSerialNumber () const
Accesses the serial number of the cube containing this control measure.
double focalPlaneComputedX () const
Accesses the computed focal plane x value for this control measure.
double focalPlaneComputedY () const
Accesses the computed focal plane y value for this control measure.
double focalPlaneMeasuredX () const
Accesses the measured focal plane x value for this control measure //TODO verify?
double focalPlaneMeasuredY () const
Accesses the measured focal plane y value for this control measure //TODO verify?
int observationIndex () const
Accesses the observation index for the parent observation.
int positionNormalsBlockIndex () const
Accesses block index into normal equations matrix of position piecewise polynomial segment.
int pointingNormalsBlockIndex () const
Accesses block index into normal equations matrix of pointing piecewise polynomial segment.
Detailed Description
A container class for a ControlMeasure.
This class is used as a wrapper around a ControlMeasure to provide the necessary information for BundleAdjust. This class can be used to get the parent bundle observation solve settings for observation mode adjustment.
Note that a BundleMeasure should be created from a non-ignored ControlMeasure.
Author
2014-07-09 Ken Edmundson
Constructor & Destructor Documentation
BundleMeasure() [1/2]
Isis::BundleMeasure::BundleMeasure (ControlMeasure * controlMeasure, BundleControlPoint * bundleControlPoint)
Constructor.
Constructs a BundleMeasure from a ControlMeasure with the passed BundleControlPoint as its parent control point
Parameters
controlMeasure Pointer to the ControlMeasure to store
bundleControlPoint Pointer to the BundleControlPoint that contains this BundleMeasure
BundleMeasure() [2/2]
Isis::BundleMeasure::BundleMeasure (const BundleMeasure & src)
Copy constructor.
Constructs a BundleMeasure from another BundleMeasure
Parameters
src The source BundleMeasure to copy
~BundleMeasure()
Isis::BundleMeasure::~BundleMeasure ()
Destructor.
Member Function Documentation
camera()
Camera * Isis::BundleMeasure::camera () const
Accesses the associated camera for this bundle measure.
See also
ControlMeasure::camera()
Returns
Camera* Returns a pointer to the camera associated with this bundle measure
References Isis::ControlMeasure::Camera().
Referenced by Isis::IsisBundleObservation::computeImagePartials(), Isis::CsmBundleObservation::computeImagePartials(), Isis::IsisBundleObservation::computePoint3DPartials(), Isis::CsmBundleObservation::computePoint3DPartials(), Isis::IsisBundleObservation::computeRHSPartials(), Isis::CsmBundleObservation::computeRHSPartials(), and Isis::IsisBundleObservation::computeTargetPartials().
cubeSerialNumber()
QString Isis::BundleMeasure::cubeSerialNumber () const
Accesses the serial number of the cube containing this control measure.
See also
ControlMeasure::GetCubeSerialNumber()
Returns
QString Returns the serial number of the cube that contains this control measure
References Isis::ControlMeasure::GetCubeSerialNumber().
Referenced by Isis::IsisBundleObservation::computeRHSPartials(), and Isis::CsmBundleObservation::computeRHSPartials().
focalPlaneComputedX()
double Isis::BundleMeasure::focalPlaneComputedX () const
Accesses the computed focal plane x value for this control measure.
See also
ControlMeasure::GetFocalPlaneComputedX()
Returns
double Returns the computed focal plane x value
References Isis::ControlMeasure::GetFocalPlaneComputedX().
focalPlaneComputedY()
double Isis::BundleMeasure::focalPlaneComputedY () const
Accesses the computed focal plane y value for this control measure.
See also
ControlMeasure::GetFocalPlaneComputedY()
Returns
double Returns the computed focal plane y value
References Isis::ControlMeasure::GetFocalPlaneComputedY().
focalPlaneMeasuredX()
double Isis::BundleMeasure::focalPlaneMeasuredX () const
Accesses the measured focal plane x value for this control measure //TODO verify?
See also
ControlMeasure::GetFocalPlaneMeasuredX()
Returns
double Returns the measured focal plane x value
References Isis::ControlMeasure::GetFocalPlaneMeasuredX().
Referenced by Isis::IsisBundleObservation::computeRHSPartials().
focalPlaneMeasuredY()
double Isis::BundleMeasure::focalPlaneMeasuredY () const
Accesses the measured focal plane y value for this control measure //TODO verify?
See also
ControlMeasure::GetFocalPlaneMeasuredY()
Returns
double Returns the measured focal plane y value
References Isis::ControlMeasure::GetFocalPlaneMeasuredY().
Referenced by Isis::IsisBundleObservation::computeRHSPartials().
isRejected()
bool Isis::BundleMeasure::isRejected () const
Determines whether or not this BundleMeasure is rejected.
Returns
bool Returns a boolean indicating whether this BundleMeasure is rejected
References Isis::ControlMeasure::IsRejected().
line()
double Isis::BundleMeasure::line () const
Accesses the current line measurement for this control measure.
See also
ControlMeasure::GetLine()
Returns
double Returns the line measurement for this control measure
References Isis::ControlMeasure::GetLine().
Referenced by Isis::CsmBundleObservation::computeRHSPartials().
lineResidual()
double Isis::BundleMeasure::lineResidual () const
Accesses the line residual for this control measure.
See also
ControlMeasure::GetLineResidual()
Returns
double Returns the line residual
References Isis::ControlMeasure::GetLineResidual().
observationIndex()
int Isis::BundleMeasure::observationIndex () const
Accesses the observation index for the parent observation.
See also
BundleObservation::index()
Returns
int Returns the observation index of the parent observation
Exceptions
IException::Programmer "In BundleMeasure::observationIndex: parent observation has not been set."
References _FILEINFO_, and Isis::IException::Programmer.
observationSolveSettings()
const QSharedPointer< BundleObservationSolveSettings > Isis::BundleMeasure::observationSolveSettings ()
Accesses the parent observation's solve settings.
See also
BundleObservation::solveSettings()
Returns
const QSharedPointer<BundleObservationSolveSettings> Returns a const pointer to the BundleObservationSolveSettings for the parent BundleObservation
Exceptions
IException::Programmer "In BundleMeasure::observationSolveSettings: parent observation has not been set."
References _FILEINFO_, and Isis::IException::Programmer.
operator=()
BundleMeasure & Isis::BundleMeasure::operator= (const BundleMeasure & src)
Assignment operator.
Assigns the state of this BundleMeasure from another BundleMeasure
Parameters
src The source BundleMeasure to assign state from
Returns
BundleMeasure& Returns a reference to this BundleMeasure
parentBundleImage()
QSharedPointer< BundleImage > Isis::BundleMeasure::parentBundleImage ()
Access the parent BundleImage for this bundle measure.
Returns
QSharedPointer<BundleImage> Returns a pointer to the parent BundleImage
parentBundleObservation()
QSharedPointer< BundleObservation > Isis::BundleMeasure::parentBundleObservation ()
Accesses the parent BundleObservation for this bundle measure.
Returns
QSharedPointer<BundleObservation> Returns a pointer to the parent BundleObservation
parentControlPoint()
BundleControlPoint * Isis::BundleMeasure::parentControlPoint ()
Accesses the parent BundleControlPoint for this bundle measure.
Returns
BundleControlPoint* Returns a pointer to the parent BundleControlPoint
Referenced by Isis::CsmBundleObservation::computeImagePartials(), Isis::IsisBundleObservation::computePoint3DPartials(), Isis::CsmBundleObservation::computePoint3DPartials(), Isis::IsisBundleObservation::computeRHSPartials(), Isis::CsmBundleObservation::computeRHSPartials(), and Isis::IsisBundleObservation::computeTargetPartials().
pointingNormalsBlockIndex()
int Isis::BundleMeasure::pointingNormalsBlockIndex () const
Accesses block index into normal equations matrix of pointing piecewise polynomial segment.
Returns
int block index into normal equations matrix of pointing piecewise polynomial segment
positionNormalsBlockIndex()
int Isis::BundleMeasure::positionNormalsBlockIndex () const
Accesses block index into normal equations matrix of position piecewise polynomial segment.
Returns
int block index into normal equations matrix of position piecewise polynomial. segment
residualMagnitude()
double Isis::BundleMeasure::residualMagnitude () const
Accesses the residual magnitude for this control measure.
See also
ControlMeasure::GetResidualMagnitude()
Returns
double Returns the residual magnitude
References Isis::ControlMeasure::GetResidualMagnitude().
sample()
double Isis::BundleMeasure::sample () const
Accesses the current sample measurement for this control measure.
See also
ControlMeasure::GetSample()
Returns
double Returns the sample measurement for this control measure
References Isis::ControlMeasure::GetSample().
Referenced by Isis::CsmBundleObservation::computeRHSPartials().
sampleResidual()
double Isis::BundleMeasure::sampleResidual () const
Accesses the sample residual for this control measure.
See also
ControlMeasure::GetSampleResidual()
Returns
double Returns the sample residual
References Isis::ControlMeasure::GetSampleResidual().
setFocalPlaneResidualsMillimeters()
void Isis::BundleMeasure::setFocalPlaneResidualsMillimeters ()
Computes and sets measure focal plane residuals in millimeters.
References Isis::ControlMeasure::GetFocalPlaneComputedX(), Isis::ControlMeasure::GetFocalPlaneComputedY(), Isis::ControlMeasure::GetFocalPlaneMeasuredX(), and Isis::ControlMeasure::GetFocalPlaneMeasuredY().
setImage()
void Isis::BundleMeasure::setImage ()
Sets the BundleMeasure's status to rejected or not rejected.
Parameters
reject True will set the BundleMeasure to rejected.
See also
ControlMeasure::SetRejected(bool reject)
References Isis::ControlMeasure::Camera(), Isis::ControlMeasure::GetLine(), Isis::ControlMeasure::GetSample(), and Isis::Camera::SetImage().
setNormalsPointingBlockIndex()
void Isis::BundleMeasure::setNormalsPointingBlockIndex (int index)
Sets block index into normal equations for pointing piecewise polynomial segment.
Parameters
index normal equations matrix block index.
setNormalsPositionBlockIndex()
void Isis::BundleMeasure::setNormalsPositionBlockIndex (int index)
Sets block index into normal equations for position piecewise polynomial segment.
Parameters
index normal equations matrix block index.
setParentImage()
void Isis::BundleMeasure::setParentImage (QSharedPointer< BundleImage > image)
Sets the parent bundle image.
Parameters
image Pointer to the parent BundleImage
setParentObservation()
void Isis::BundleMeasure::setParentObservation (QSharedPointer< BundleObservation > observation)
Sets the parent bundle observation.
Parameters
observation Pointer to the parent BundleObservation
setRejected()
void Isis::BundleMeasure::setRejected (bool reject)
Sets the BundleMeasure's status to rejected or not rejected.
Parameters
reject True will set the BundleMeasure to rejected.
See also
ControlMeasure::SetRejected(bool reject)
References Isis::ControlMeasure::SetRejected().
setSigma()
void Isis::BundleMeasure::setSigma (double sigmaMultiplier)
Sets sigma (i.e.
standard deviation or uncertainty) of raw measure in mm and sqrt of weight for bundle
Parameters
double sigma
TODO: what if camera has been subsampled, is pixel pitch computation still valid?
References _FILEINFO_, Isis::ControlMeasure::Camera(), Isis::Camera::PixelPitch(), and Isis::IException::Programmer.
sigma()
double Isis::BundleMeasure::sigma () const
Accesses the measure sigma.
Returns
double measure sigma
weight()
double Isis::BundleMeasure::weight () const
Accesses measure weight for bundle.
Returns
double measure weight
weightSqrt()
double Isis::BundleMeasure::weightSqrt () const
Accesses sqrt of measure weight for bundle.
Returns
double sqrt of measure weight
xFocalPlaneResidual()
double Isis::BundleMeasure::xFocalPlaneResidual () const
Accesses the focal plane x-coordinate residual in millimeters.
Returns
double Returns the focal plane x-coordinate residual in millimeters
yFocalPlaneResidual()
double Isis::BundleMeasure::yFocalPlaneResidual () const
Accesses the focal plane y-coordinate residual in millimeters.
Returns
double Returns the focal plane y-coordinate residual in millimeters
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/BundleUtilities/BundleMeasure.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/BundleUtilities/BundleMeasure.cpp