Isis Developer Reference: Isis::CsmBundleObservation Class Reference
Isis::CsmBundleObservation Class Reference
Control Networks
Class for observations that use CSM camera models in bundle adjustment.
#include <CsmBundleObservation.h>
Public Member Functions
CsmBundleObservation ()
Constructs a CsmBundleObservation initialized to a default state.
CsmBundleObservation (BundleImageQsp image, QString observationNumber, QString instrumentId, BundleTargetBodyQsp bundleTargetBody)
Constructs a CsmBundleObservation from a BundleImage, an instrument id, an observation number to assign to this CsmBundleObservation, and a target body.
CsmBundleObservation (const CsmBundleObservation &src)
Creates a copy of another CsmBundleObservation.
~CsmBundleObservation ()
Destructor.
CsmBundleObservation & operator= (const CsmBundleObservation &src)
Assignment operator.
void copy (const CsmBundleObservation &src)
virtual bool setSolveSettings (BundleObservationSolveSettings solveSettings)
Set solve parameters.
int numberParameters ()
Returns the number of total parameters there are for solving.
const BundleObservationSolveSettingsQsp solveSettings ()
Accesses the solve settings.
bool applyParameterCorrections (LinearAlgebra::Vector corrections)
Applies the parameter corrections.
void bundleOutputString (std::ostream &fpOut, bool errorPropagation)
Takes in an open std::ofstream and writes out information which goes into the bundleout.txt file.
QString bundleOutputCSV (bool errorPropagation)
Creates and returns a formatted QString representing the bundle coefficients and parameters in csv format.
virtual QStringList parameterList ()
Returns the list of observation parameter names.
bool computeTargetPartials (LinearAlgebra::Matrix &coeffTarget, BundleMeasure &measure, BundleSettingsQsp &bundleSettings, BundleTargetBodyQsp &bundleTargetBody)
Cannot compute target body parameters for a CSM observation, so always throws an exception.
bool computeImagePartials (LinearAlgebra::Matrix &coeffImage, BundleMeasure &measure)
Calculates the sensor partials with respect to the solve parameters and populates the coeffImage matrix.
bool computePoint3DPartials (LinearAlgebra::Matrix &coeffPoint3D, BundleMeasure &measure, SurfacePoint::CoordinateType coordType)
Calculates the ground partials for the line, sample currently set in the sensor model.
bool computeRHSPartials (LinearAlgebra::Vector &coeffRHS, BundleMeasure &measure)
Calculates the sample, line residuals between the values measured in the image and the ground-to-image sample, line calculated by the sensor model.
double computeObservationValue (BundleMeasure &measure, double deltaVal)
Returns the observed value in (sample, line) coordinates.
void copy (const BundleObservation &src)
virtual void append (const BundleImageQsp &value)
Appends a BundleImage shared pointer to the BundleObservation.
BundleImageQsp imageByCubeSerialNumber (QString cubeSerialNumber)
Returns the BundleImage shared pointer associated with the given serial number.
void setIndex (int n)
Sets the index for the observation.
int index ()
Accesses the observation's index.
QString instrumentId ()
Accesses the instrument id.
double vtpv ()
Compute vtpv, the weighted sum of squares of constrained image parameter residuals.
virtual LinearAlgebra::Vector & parameterWeights ()
Accesses the solve parameter weights.
virtual LinearAlgebra::Vector & parameterCorrections ()
Accesses the parameter corrections.
virtual LinearAlgebra::Vector & aprioriSigmas ()
Accesses the a priori sigmas.
virtual LinearAlgebra::Vector & adjustedSigmas ()
Accesses the adjusted sigmas.
virtual QStringList imageNames ()
Access to image names for CorrelationMatrix to use.
Protected Attributes
QString m_observationNumber
The shared portion of the serial numbers of all images in the observation.
int m_index
Index of this observation in the set of observations. Map between cube serial number and BundleImage pointers.
QMap< QString, BundleImageQsp > m_cubeSerialNumberToBundleImageMap
QStringList m_serialNumbers
List of all cube serial numbers in observation.
QStringList m_imageNames
List of all cube names.
QString m_instrumentId
Spacecraft instrument id.
LinearAlgebra::Vector m_weights
Parameter weights. Cumulative parameter correction vector.
LinearAlgebra::Vector m_corrections
LinearAlgebra::Vector m_aprioriSigmas
A posteriori (adjusted) parameter sigmas.
LinearAlgebra::Vector m_adjustedSigmas
A posteriori (adjusted) parameter sigmas.
Detailed Description
Class for observations that use CSM camera models in bundle adjustment.
Constructor & Destructor Documentation
CsmBundleObservation() [1/3]
Isis::CsmBundleObservation::CsmBundleObservation ()
Constructs a CsmBundleObservation initialized to a default state.
CsmBundleObservation() [2/3]
Isis::CsmBundleObservation::CsmBundleObservation (BundleImageQsp image, QString observationNumber, QString instrumentId, BundleTargetBodyQsp bundleTargetBody)
Constructs a CsmBundleObservation from a BundleImage, an instrument id, an observation number to assign to this CsmBundleObservation, and a target body.
Parameters
image QSharedPointer to the primary image in the observation
observationNumber Observation number of the observation
instrumentId Id of the instrument for the observation
bundleTargetBody QSharedPointer to the target body of the observation
References _FILEINFO_, and Isis::IException::User.
CsmBundleObservation() [3/3]
Isis::CsmBundleObservation::CsmBundleObservation (const CsmBundleObservation & src)
Creates a copy of another CsmBundleObservation.
Parameters
src Reference to the CsmBundleObservation to copy
~CsmBundleObservation()
Isis::CsmBundleObservation::~CsmBundleObservation ()
Destructor.
Contained BundleImages will remain until all shared pointers are deleted.
Member Function Documentation
adjustedSigmas()
LinearAlgebra::Vector & Isis::BundleObservation::adjustedSigmas () virtual inherited
Accesses the adjusted sigmas.
Returns
LinearAlgebra::Vector Returns the adjusted sigmas
append()
void Isis::BundleObservation::append (const BundleImageQsp & value) virtual inherited
Appends a BundleImage shared pointer to the BundleObservation.
If the pointer is valid, then the BundleImage and its serial number will be inserted into the serial number to BundleImage map.
Parameters
value The BundleImage to be appended.
See also
QVector::append()
applyParameterCorrections()
bool Isis::CsmBundleObservation::applyParameterCorrections (LinearAlgebra::Vector corrections) virtual
Applies the parameter corrections.
Parameters
corrections Vector of corrections to apply
Exceptions
IException::Unknown "Instrument position is NULL, but position solve option is [not NoPositionFactors]"
IException::Unknown "Instrument position is NULL, but pointing solve option is [not NoPointingFactors]"
IException::Unknown "Unable to apply parameter corrections to CsmBundleObservation."
Returns
bool Returns true upon successful application of corrections
Implements Isis::BundleObservation.
References _FILEINFO_, Isis::CSMCamera::applyParameterCorrection(), Isis::BundleObservation::m_corrections, and Isis::IException::Programmer.
aprioriSigmas()
LinearAlgebra::Vector & Isis::BundleObservation::aprioriSigmas () virtual inherited
Accesses the a priori sigmas.
Returns
LinearAlgebra::Vector Returns the a priori sigmas
bundleOutputCSV()
QString Isis::CsmBundleObservation::bundleOutputCSV (bool errorPropagation) virtual
Creates and returns a formatted QString representing the bundle coefficients and parameters in csv format.
Parameters
errorPropagation Boolean indicating whether or not to attach more information (corrections, sigmas, adjusted sigmas...) to the output QString
Returns
QString Returns a formatted QString representing the CsmBundleObservation in csv format
Implements Isis::BundleObservation.
References Isis::CSMCamera::getParameterValue(), Isis::BundleObservation::m_adjustedSigmas, Isis::BundleObservation::m_aprioriSigmas, Isis::BundleObservation::m_corrections, and Isis::toString().
bundleOutputString()
void Isis::CsmBundleObservation::bundleOutputString (std::ostream & fpOut, bool errorPropagation) virtual
Takes in an open std::ofstream and writes out information which goes into the bundleout.txt file.
Parameters
fpOut The open std::ofstream object which is passed in from BundleSolutionInfo::outputText()
errorPropagation Boolean indicating whether or not to attach more information (corrections, sigmas, adjusted sigmas...) to the output.
Implements Isis::BundleObservation.
References Isis::CSMCamera::getParameterName(), Isis::CSMCamera::getParameterUnits(), Isis::CSMCamera::getParameterValue(), Isis::IsSpecial(), Isis::BundleObservation::m_adjustedSigmas, Isis::BundleObservation::m_aprioriSigmas, Isis::BundleObservation::m_corrections, numberParameters(), and Isis::toString().
computeImagePartials()
bool Isis::CsmBundleObservation::computeImagePartials (LinearAlgebra::Matrix & coeffImage, BundleMeasure & measure) virtual
Calculates the sensor partials with respect to the solve parameters and populates the coeffImage matrix.
Parameters
coeffImage A matrix that will be populated with the sensor partials with respect to the solve parameters.
measure The measure that the partials are being computed for.
Returns
bool
Implements Isis::BundleObservation.
References Isis::BundleControlPoint::adjustedSurfacePoint(), Isis::BundleMeasure::camera(), Isis::CSMCamera::getSensorPartials(), and Isis::BundleMeasure::parentControlPoint().
computeObservationValue()
double Isis::CsmBundleObservation::computeObservationValue (BundleMeasure & measure, double deltaVal) virtual
Returns the observed value in (sample, line) coordinates.
This requires no modification for Csm.
Parameters
measure measure The measure that the partials are being computed for.
deltaVal The difference between the measured and calculate sample, line coordinates
Returns
double The The difference between the measured and calculated (line, sample) coordinate
Implements Isis::BundleObservation.
computePoint3DPartials()
bool Isis::CsmBundleObservation::computePoint3DPartials (LinearAlgebra::Matrix & coeffPoint3D, BundleMeasure & measure, SurfacePoint::CoordinateType coordType) virtual
Calculates the ground partials for the line, sample currently set in the sensor model.
Parameters
coeffPoint3D A matrix that will be populated with the (line, sample) partials with respect to the ground point.
measure The measure that the partials are being computed for.
coordType Not used in this class. Coordinates are x,y,z
Returns
bool
Implements Isis::BundleObservation.
References _FILEINFO_, Isis::BundleControlPoint::adjustedSurfacePoint(), Isis::BundleMeasure::camera(), Isis::CSMCamera::GroundPartials(), Isis::SurfacePoint::Latitudinal, Isis::SurfacePoint::LatitudinalDerivative(), Isis::SurfacePoint::One, Isis::BundleMeasure::parentControlPoint(), Isis::IException::Programmer, Isis::SurfacePoint::Rectangular, Isis::SurfacePoint::Three, Isis::toString(), and Isis::SurfacePoint::Two.
computeRHSPartials()
bool Isis::CsmBundleObservation::computeRHSPartials (LinearAlgebra::Vector & coeffRHS, BundleMeasure & measure) virtual
Calculates the sample, line residuals between the values measured in the image and the ground-to-image sample, line calculated by the sensor model.
Parameters
coeffRHS A vector that will contain the sample, line residuals.
measure The measure that the partials are being computed for.
Returns
bool
Implements Isis::BundleObservation.
References _FILEINFO_, Isis::BundleControlPoint::adjustedSurfacePoint(), Isis::BundleMeasure::camera(), Isis::BundleMeasure::cubeSerialNumber(), Isis::BundleControlPoint::id(), Isis::Camera::Line(), Isis::BundleMeasure::line(), Isis::BundleMeasure::parentControlPoint(), Isis::Camera::Sample(), Isis::BundleMeasure::sample(), Isis::Camera::SetGround(), and Isis::IException::User.
computeTargetPartials()
bool Isis::CsmBundleObservation::computeTargetPartials (LinearAlgebra::Matrix & coeffTarget, BundleMeasure & measure, BundleSettingsQsp & bundleSettings, BundleTargetBodyQsp & bundleTargetBody) virtual
Cannot compute target body parameters for a CSM observation, so always throws an exception.
Parameters
coeffTarget Matrix for target body partial derivatives
measure The measure that the partials are being computed for.
bundleSettings The settings for the bundle adjustment
bundleTargetBody QSharedPointer to the target body of the observation
Returns
bool Always false
Implements Isis::BundleObservation.
References _FILEINFO_, and Isis::IException::User.
copy() [1/2]
void Isis::BundleObservation::copy (const BundleObservation & src) inherited
copy() [2/2]
void Isis::CsmBundleObservation::copy (const CsmBundleObservation & src)
imageByCubeSerialNumber()
BundleImageQsp Isis::BundleObservation::imageByCubeSerialNumber (QString cubeSerialNumber) inherited
Returns the BundleImage shared pointer associated with the given serial number.
If no BundleImage with that serial number is contained a NULL pointer is returned.
Parameters
cubeSerialNumber The serial number of the cube to be returned.
Returns
BundleImageQsp A shared pointer to the BundleImage (NULL if not found).
imageNames()
QStringList Isis::BundleObservation::imageNames () virtual inherited
Access to image names for CorrelationMatrix to use.
Returns
QStringList Returns a QStringList of the image names
index()
int Isis::BundleObservation::index () inherited
Accesses the observation's index.
Returns
int Returns the observation's index
Referenced by Isis::IsisBundleObservation::applyParameterCorrections(), Isis::IsisBundleObservation::computeImagePartials(), and Isis::IsisBundleObservation::computeTargetPartials().
instrumentId()
QString Isis::BundleObservation::instrumentId () inherited
Accesses the instrument id.
Returns
QString Returns the instrument id of the observation
numberParameters()
int Isis::CsmBundleObservation::numberParameters () virtual
Returns the number of total parameters there are for solving.
The total number of parameters is equal to the number of position parameters and number of pointing parameters
Returns
int Returns the number of parameters there are
Implements Isis::BundleObservation.
Referenced by bundleOutputString().
operator=()
CsmBundleObservation & Isis::CsmBundleObservation::operator= (const CsmBundleObservation & src)
Assignment operator.
Assigns the state of the source CsmBundleObservation to this CsmBundleObservation
Parameters
CsmBundleObservation Reference to the source CsmBundleObservation to assign from
Returns
CsmBundleObservation& Reference to this CsmBundleObservation
parameterCorrections()
LinearAlgebra::Vector & Isis::BundleObservation::parameterCorrections () virtual inherited
Accesses the parameter corrections.
Returns
LinearAlgebra::Vector Returns the parameter corrections
parameterList()
QStringList Isis::CsmBundleObservation::parameterList () virtual
Returns the list of observation parameter names.
This will always return at least one set of positions and pointings because we always output at least the center values even when not solving for them.
Returns
QStringList List of observation parameter names
Implements Isis::BundleObservation.
References Isis::CSMCamera::getParameterName().
parameterWeights()
LinearAlgebra::Vector & Isis::BundleObservation::parameterWeights () virtual inherited
Accesses the solve parameter weights.
Returns
LinearAlgebra::Vector Returns the parameter weights for solving
setIndex()
void Isis::BundleObservation::setIndex (int n) inherited
Sets the index for the observation.
Parameters
n Value to set the index of the observation to
setSolveSettings()
bool Isis::CsmBundleObservation::setSolveSettings (BundleObservationSolveSettings solveSettings) virtual
Set solve parameters.
Parameters
solveSettings The solve settings to use
Returns
bool Returns true if settings were successfully set
Implements Isis::BundleObservation.
References Isis::CSMCamera::getParameterCovariance(), Isis::CSMCamera::getParameterIndices(), Isis::BundleObservationSolveSettings::List, Isis::BundleObservation::m_adjustedSigmas, Isis::BundleObservation::m_aprioriSigmas, Isis::BundleObservation::m_corrections, Isis::BundleObservation::m_weights, Isis::BundleObservationSolveSettings::Set, solveSettings(), and Isis::BundleObservationSolveSettings::Type.
solveSettings()
const BundleObservationSolveSettingsQsp Isis::CsmBundleObservation::solveSettings () virtual
Accesses the solve settings.
Returns
const BundleObservationSolveSettingsQsp Returns a pointer to the solve settings for this CsmBundleObservation
Implements Isis::BundleObservation.
Referenced by setSolveSettings().
vtpv()
double Isis::BundleObservation::vtpv () inherited
Compute vtpv, the weighted sum of squares of constrained image parameter residuals.
Returns
double Weighted sum of squares of constrained image parameter residuals.
Member Data Documentation
m_adjustedSigmas
LinearAlgebra::Vector Isis::BundleObservation::m_adjustedSigmas protected inherited
A posteriori (adjusted) parameter sigmas.
Referenced by Isis::IsisBundleObservation::bundleOutputCSV(), bundleOutputCSV(), Isis::IsisBundleObservation::bundleOutputString(), bundleOutputString(), Isis::IsisBundleObservation::setSolveSettings(), and setSolveSettings().
m_aprioriSigmas
LinearAlgebra::Vector Isis::BundleObservation::m_aprioriSigmas protected inherited
A posteriori (adjusted) parameter sigmas.
Referenced by Isis::IsisBundleObservation::bundleOutputCSV(), bundleOutputCSV(), Isis::IsisBundleObservation::bundleOutputString(), bundleOutputString(), Isis::IsisBundleObservation::setSolveSettings(), and setSolveSettings().
m_corrections
LinearAlgebra::Vector Isis::BundleObservation::m_corrections protected inherited
Referenced by Isis::IsisBundleObservation::applyParameterCorrections(), applyParameterCorrections(), Isis::IsisBundleObservation::bundleOutputCSV(), bundleOutputCSV(), Isis::IsisBundleObservation::bundleOutputString(), bundleOutputString(), Isis::IsisBundleObservation::setSolveSettings(), and setSolveSettings().
m_cubeSerialNumberToBundleImageMap
QMap<QString, BundleImageQsp> Isis::BundleObservation::m_cubeSerialNumberToBundleImageMap protected inherited
Referenced by Isis::BundleObservation::BundleObservation(), and Isis::BundleObservation::operator=().
m_imageNames
QStringList Isis::BundleObservation::m_imageNames protected inherited
List of all cube names.
m_index
int Isis::BundleObservation::m_index protected inherited
Index of this observation in the set of observations. Map between cube serial number and BundleImage pointers.
Referenced by Isis::BundleObservation::BundleObservation().
m_instrumentId
QString Isis::BundleObservation::m_instrumentId protected inherited
Spacecraft instrument id.
Referenced by Isis::BundleObservation::BundleObservation(), and Isis::BundleObservation::operator=().
m_observationNumber
QString Isis::BundleObservation::m_observationNumber protected inherited
The shared portion of the serial numbers of all images in the observation.
Referenced by Isis::BundleObservation::BundleObservation(), and Isis::BundleObservation::operator=().
m_serialNumbers
QStringList Isis::BundleObservation::m_serialNumbers protected inherited
List of all cube serial numbers in observation.
Referenced by Isis::BundleObservation::BundleObservation(), and Isis::BundleObservation::operator=().
m_weights
LinearAlgebra::Vector Isis::BundleObservation::m_weights protected inherited
Parameter weights. Cumulative parameter correction vector.
Referenced by Isis::IsisBundleObservation::setSolveSettings(), and setSolveSettings().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/CsmBundleObservation/CsmBundleObservation.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/CsmBundleObservation/CsmBundleObservation.cpp