Isis Developer Reference: Isis::VariableLineScanCameraDetectorMap Class Reference
Isis::VariableLineScanCameraDetectorMap Class Reference
Convert between parent image coordinates and detector coordinates.
#include <VariableLineScanCameraDetectorMap.h>
Public Member Functions
VariableLineScanCameraDetectorMap (Camera *parent, std::vector< LineRateChange > &lineRates)
Constructs a VariableLineScanCameraDetectorMap.
virtual ~VariableLineScanCameraDetectorMap ()
Destructor.
virtual bool SetParent (const double sample, const double line)
Compute detector position from a parent image coordinate.
virtual bool SetParent (const double sample, const double line, const double deltaT)
Compute detector position from a parent image coordinate.
virtual bool SetDetector (const double sample, const double line)
Compute parent position from a detector coordinate.
virtual double exposureDuration (const double sample, const double line, const int band) const
This virtual method is for returning the exposure duration of a given pixel.
LineRateChange & lineRate (const double line) const
Get the line rate information for a given line.
void SetStartTime (const double etStart)
Reset the starting ephemeris time.
void SetLineRate (const double lineRate)
Reset the line rate.
double LineRate () const
Access the time, in seconds, between scan lines.
double StartTime () const
Access the starting time at the top edge of the first line in the parent image.
double AdjustedStartingSample () const
Return the starting detector sample adjusted for summation.
double AdjustedStartingLine () const
Return the starting detector line adjusted for summation.
double ParentSample () const
Return parent sample.
double ParentLine () const
Return parent line.
double DetectorSample () const
Return detector sample.
double DetectorLine () const
Return detector line.
void SetStartingDetectorSample (const double sample)
Set the starting detector sample.
void SetStartingDetectorLine (const double line)
Set the starting detector line.
void SetDetectorSampleSumming (const double summing)
Set sample summing mode.
void SetDetectorLineSumming (const double summing)
Set line summing mode.
virtual double SampleScaleFactor () const
Return scaling factor for computing sample resolution.
virtual double LineScaleFactor () const
Return scaling factor for computing line resolution.
Protected Attributes
Camera * p_camera
Pointer to the camera.
double p_parentSample
The parent sample calculated from the detector.
double p_parentLine
The parent line calculated from the detector.
double p_detectorLine
Detector coordinate line value.
double p_detectorSample
Detector coordinate sample value.
double p_detectorSampleSumming
The scaling factor for computing sample resolution.
double p_detectorLineSumming
The scaling factor for computing line resolution.
double p_startingDetectorSample
Detector start coordinate sample value.
double p_startingDetectorLine
Detector start coordinate line value.
double p_ss
Start sample.
double p_sl
Start line.
Detailed Description
Convert between parent image coordinates and detector coordinates.
This class is used to convert between parent dector coordinates (sample/line) and detector coordinates for a line scan camera.
Author
2008-08-08 Steven Lambright
See also
Camera
Constructor & Destructor Documentation
VariableLineScanCameraDetectorMap()
Isis::VariableLineScanCameraDetectorMap::VariableLineScanCameraDetectorMap (Camera * parent, std::vector< LineRateChange > & lineRates)
Constructs a VariableLineScanCameraDetectorMap.
Parameters
parent The camera
p_lineRates This should be a vector with an entry for every scan rate change in it. The pair consists of the line number and ET of the changed time; the first entry should be line 1 and the last entry should be one line past the end of the image. See HrscCamera for an example.
~VariableLineScanCameraDetectorMap()
Isis::VariableLineScanCameraDetectorMap::~VariableLineScanCameraDetectorMap () virtual
Destructor.
Member Function Documentation
AdjustedStartingLine()
double Isis::CameraDetectorMap::AdjustedStartingLine () const inherited
Return the starting detector line adjusted for summation.
Returns
(double) The starting line
References Isis::CameraDetectorMap::p_sl.
AdjustedStartingSample()
double Isis::CameraDetectorMap::AdjustedStartingSample () const inherited
Return the starting detector sample adjusted for summation.
Returns
(double) The starting sample
References Isis::CameraDetectorMap::p_ss.
DetectorLine()
double Isis::CameraDetectorMap::DetectorLine () const inherited
Return detector line.
Returns
(double) The detector line
References Isis::CameraDetectorMap::p_detectorLine.
Referenced by Isis::Camera::SetImage().
DetectorSample()
double Isis::CameraDetectorMap::DetectorSample () const inherited
Return detector sample.
Returns
(double) The detector sample
References Isis::CameraDetectorMap::p_detectorSample.
Referenced by Isis::Camera::SetImage().
exposureDuration()
double Isis::VariableLineScanCameraDetectorMap::exposureDuration (const double sample, const double line, const int band) const virtual
This virtual method is for returning the exposure duration of a given pixel.
For a variable line scan camera, the exposure duration is assumed to be the line scan rate for the given line. Note, this may not be the actual exposure duration. The line scan rate is the time from the beginning of one line to the beginning of the next. The exposure duration is the time from the beginning of a line to the end of that line. So, if the end of a line is not the beginning of the next line, these two values will not be the same.
Parameters
sample The sample of the desired pixel.
line The line of the desired pixel.
band The band of the desired pixel.
Returns
double The exposure duration for the desired pixel in seconds.
Exceptions
IException::Programmer "line was not found in the line scan rate table."
@TODO How do we get the actual exposure duration?
Reimplemented from Isis::LineScanCameraDetectorMap.
References Isis::LineRateChange::GetLineScanRate(), and lineRate().
LineRate()
double Isis::LineScanCameraDetectorMap::LineRate () const virtual inherited
Access the time, in seconds, between scan lines.
Returns
Line rate.
Reimplemented from Isis::CameraDetectorMap.
Referenced by Isis::LineScanCameraDetectorMap::exposureDuration(), and Isis::LineScanCameraSkyMap::SetSky().
lineRate()
LineRateChange & Isis::VariableLineScanCameraDetectorMap::lineRate (const double line) const
Get the line rate information for a given line.
Parameters
line The line to find the line rate information for.
Returns
LineRateChange& The LineRateChange object that is used for time calculations with the input line.
@TODO How to handle if rateIndex < 0?
Referenced by exposureDuration().
LineScaleFactor()
double Isis::CameraDetectorMap::LineScaleFactor () const virtual inherited
Return scaling factor for computing line resolution.
Returns
(double) The scaling factor for line resolution
References Isis::CameraDetectorMap::p_detectorLineSumming.
Referenced by Isis::Camera::LineResolution(), Isis::Camera::ObliqueLineResolution(), Isis::ThemisIrCamera::SetBand(), Isis::PushFrameCameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetParent(), and Isis::PushFrameCameraDetectorMap::TotalFramelets().
ParentLine()
double Isis::CameraDetectorMap::ParentLine () const inherited
Return parent line.
Returns
(double) The parent line
References Isis::CameraDetectorMap::p_parentLine.
Referenced by Isis::Camera::SetRightAscensionDeclination().
ParentSample()
double Isis::CameraDetectorMap::ParentSample () const inherited
Return parent sample.
Returns
(double) The parent sample
References Isis::CameraDetectorMap::p_parentSample.
Referenced by Isis::Camera::SetRightAscensionDeclination().
SampleScaleFactor()
double Isis::CameraDetectorMap::SampleScaleFactor () const virtual inherited
Return scaling factor for computing sample resolution.
Returns
(double) The scaling factor for sample resolution
References Isis::CameraDetectorMap::p_detectorSampleSumming.
Referenced by Isis::Camera::ObliqueSampleResolution(), and Isis::Camera::SampleResolution().
SetDetector()
bool Isis::VariableLineScanCameraDetectorMap::SetDetector (const double sample, const double line) virtual
Compute parent position from a detector coordinate.
This method will compute a parent sample given a detector coordinate. The parent line will be computed using the the time in the parent camera
Parameters
sample Sample number in the detector
line Line number in the detector
Returns
conversion successful
Reimplemented from Isis::LineScanCameraDetectorMap.
References Isis::iTime::Et(), Isis::CameraDetectorMap::p_camera, Isis::CameraDetectorMap::p_parentLine, Isis::CameraDetectorMap::SetDetector(), Isis::LineScanCameraDetectorMap::SetLineRate(), and Isis::Spice::time().
SetDetectorLineSumming()
void Isis::CameraDetectorMap::SetDetectorLineSumming (const double summing) inline inherited
Set line summing mode.
Use this method to specify if detector lines are summed/averaged. That is, one image lines represents the average of N detectors. If not set the default is 1.
Parameters
summing Line summing mode
References Isis::CameraDetectorMap::p_detectorLineSumming.
Referenced by Isis::CrismCamera::CrismCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::MarciCamera::MarciCamera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), and Isis::ThemisVisCamera::ThemisVisCamera().
SetDetectorSampleSumming()
void Isis::CameraDetectorMap::SetDetectorSampleSumming (const double summing) inline inherited
Set sample summing mode.
Use this method to specify if detector samples are summed/averaged. That is, one image sample represents the average of N detectors. If not set the default is 1.
Parameters
summing Sample summing mode
References Isis::CameraDetectorMap::p_detectorSampleSumming.
Referenced by Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::MarciCamera::MarciCamera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), and Isis::ThemisVisCamera::ThemisVisCamera().
SetLineRate()
void Isis::LineScanCameraDetectorMap::SetLineRate (const double lineRate) inherited
Reset the line rate.
Use this method to reset the time between lines. Usually this will not need to be done unless the rate changes between bands.
Parameters
lineRate the time in seconds between lines
Referenced by SetDetector(), and SetParent().
SetParent() [1/2]
bool Isis::VariableLineScanCameraDetectorMap::SetParent (const double sample, const double line) virtual
Compute detector position from a parent image coordinate.
This method will compute the detector position from the parent line/sample coordinate. The parent line will be used to set the appropriate time in the parent camera.
Parameters
sample Sample number in the parent image
line Line number in the parent image
Returns
conversion successful
Reimplemented from Isis::LineScanCameraDetectorMap.
SetParent() [2/2]
bool Isis::VariableLineScanCameraDetectorMap::SetParent (const double sample, const double line, const double deltaT) virtual
Compute detector position from a parent image coordinate.
This method will compute the detector position from the parent line/sample coordinate. The parent line will be used to set the appropriate time in the parent camera.
Parameters
sample Sample number in the parent image
line Line number in the parent image
deltaT offset in seconds from center exposure time
Returns
bool conversion successful
Reimplemented from Isis::LineScanCameraDetectorMap.
References Isis::CameraFocalPlaneMap::DetectorLineOffset(), Isis::Camera::FocalPlaneMap(), Isis::CameraDetectorMap::p_camera, Isis::CameraDetectorMap::p_detectorLine, Isis::LineScanCameraDetectorMap::SetLineRate(), Isis::CameraDetectorMap::SetParent(), and Isis::Sensor::setTime().
SetStartingDetectorLine()
void Isis::CameraDetectorMap::SetStartingDetectorLine (const double line) inline inherited
Set the starting detector line.
Use this method to specify the starting detector that represents the first image line in the cube. If not set the default is 1.
Parameters
line Starting detector line
References Isis::CameraDetectorMap::p_startingDetectorLine.
Referenced by Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::JunoCamera::JunoCamera(), Isis::MdisCamera::MdisCamera(), and Isis::RosettaOsirisCamera::RosettaOsirisCamera().
SetStartingDetectorSample()
void Isis::CameraDetectorMap::SetStartingDetectorSample (const double sample) inline inherited
Set the starting detector sample.
Use this method to specify the starting detector that represents the first image sample in the cube. If not set the default is 1.
Parameters
sample Starting detector sample
References Isis::CameraDetectorMap::p_startingDetectorSample.
Referenced by Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::CTXCamera::CTXCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::MdisCamera::MdisCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), and Isis::RosettaOsirisCamera::RosettaOsirisCamera().
SetStartTime()
void Isis::LineScanCameraDetectorMap::SetStartTime (const double etStart) inherited
Reset the starting ephemeris time.
Use this method to reset the starting time of the top edge of the first line in the parent image. That is the time, prior to cropping, scaling, or padding. Usually this will not need to be done unless the time changes between bands.
Parameters
etStart starting ephemeris time in seconds
Referenced by Isis::ThemisIrCamera::SetBand().
StartTime()
double Isis::LineScanCameraDetectorMap::StartTime () const inherited
Access the starting time at the top edge of the first line in the parent image.
Returns
The start ephemeris time for the image.
Member Data Documentation
p_camera
Camera* Isis::CameraDetectorMap::p_camera protected inherited
Pointer to the camera.
Referenced by Isis::CameraDetectorMap::CameraDetectorMap(), Isis::LineScanCameraDetectorMap::SetDetector(), Isis::RadarPulseMap::SetDetector(), SetDetector(), Isis::PushFrameCameraDetectorMap::SetFramelet(), Isis::RadarPulseMap::SetParent(), Isis::CameraDetectorMap::SetParent(), Isis::LineScanCameraDetectorMap::SetParent(), Isis::RollingShutterCameraDetectorMap::SetParent(), SetParent(), and Isis::PushFrameCameraDetectorMap::TotalFramelets().
p_detectorLine
double Isis::CameraDetectorMap::p_detectorLine protected inherited
Detector coordinate line value.
Referenced by Isis::CameraDetectorMap::DetectorLine(), Isis::CameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::RadarPulseMap::SetParent(), Isis::CameraDetectorMap::SetParent(), Isis::LineScanCameraDetectorMap::SetParent(), Isis::PushFrameCameraDetectorMap::SetParent(), Isis::RollingShutterCameraDetectorMap::SetParent(), and SetParent().
p_detectorLineSumming
double Isis::CameraDetectorMap::p_detectorLineSumming protected inherited
The scaling factor for computing line resolution.
Referenced by Isis::CameraDetectorMap::CameraDetectorMap(), Isis::CameraDetectorMap::LineScaleFactor(), Isis::CameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetDetectorLineSumming(), Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_detectorSample
double Isis::CameraDetectorMap::p_detectorSample protected inherited
Detector coordinate sample value.
Referenced by Isis::CameraDetectorMap::DetectorSample(), Isis::CameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_detectorSampleSumming
double Isis::CameraDetectorMap::p_detectorSampleSumming protected inherited
The scaling factor for computing sample resolution.
Referenced by Isis::CameraDetectorMap::CameraDetectorMap(), Isis::CameraDetectorMap::SampleScaleFactor(), Isis::CameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetDetectorSampleSumming(), Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_parentLine
double Isis::CameraDetectorMap::p_parentLine protected inherited
The parent line calculated from the detector.
Referenced by Isis::CameraDetectorMap::ParentLine(), Isis::CameraDetectorMap::SetDetector(), Isis::LineScanCameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetDetector(), Isis::RadarPulseMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), SetDetector(), Isis::CameraDetectorMap::SetParent(), Isis::PushFrameCameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_parentSample
double Isis::CameraDetectorMap::p_parentSample protected inherited
The parent sample calculated from the detector.
Referenced by Isis::CameraDetectorMap::ParentSample(), Isis::CameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetParent(), Isis::PushFrameCameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_sl
double Isis::CameraDetectorMap::p_sl protected inherited
Start line.
Referenced by Isis::CameraDetectorMap::AdjustedStartingLine(), Isis::CameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_ss
double Isis::CameraDetectorMap::p_ss protected inherited
Start sample.
Referenced by Isis::CameraDetectorMap::AdjustedStartingSample(), Isis::CameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_startingDetectorLine
double Isis::CameraDetectorMap::p_startingDetectorLine protected inherited
Detector start coordinate line value.
Referenced by Isis::CameraDetectorMap::CameraDetectorMap(), and Isis::CameraDetectorMap::SetStartingDetectorLine().
p_startingDetectorSample
double Isis::CameraDetectorMap::p_startingDetectorSample protected inherited
Detector start coordinate sample value.
Referenced by Isis::CameraDetectorMap::CameraDetectorMap(), and Isis::CameraDetectorMap::SetStartingDetectorSample().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/VariableLineScanCameraDetectorMap/VariableLineScanCameraDetectorMap.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/VariableLineScanCameraDetectorMap/VariableLineScanCameraDetectorMap.cpp