Isis Developer Reference: Isis::Plugin Class Reference
Isis::Plugin Class Reference
System
Loads plugins from a shared library.
#include <Plugin.h>
Public Types
enum FindOptions { None , Traverse }
A collection of options to use when finding.
typedef QList< Isis::PvlGroup >::iterator PvlGroupIterator
The counter for groups.
typedef QList< Isis::PvlGroup >::const_iterator ConstPvlGroupIterator
typedef QList< PvlObject >::iterator PvlObjectIterator
The counter for objects.
typedef QList< PvlObject >::const_iterator ConstPvlObjectIterator
enum InsertMode { Append , Replace }
Contains both modes: Append or Replace.
typedef QList< PvlKeyword >::iterator PvlKeywordIterator
The keyword iterator.
typedef QList< PvlKeyword >::const_iterator ConstPvlKeywordIterator
The const keyword iterator.
Public Member Functions
Plugin ()
Constructs a Plugin object.
virtual ~Plugin ()
Destroys the Plugin object.
QFunctionPointer GetPlugin (const QString &group)
This method returns a void pointer to a C function (i.e., the plugin) It does this by looking in itself (Pvl) for the keyword LIBRARY and the keyword ROUTINE.
void fromString (const std::string &str)
Load PVL information from a string.
void read (const QString &file)
Loads PVL information from a stream.
void write (const QString &file)
Opens and writes PVL information to a file and handles the end of line sequence.
void append (const QString &file)
Appends PVL information to a file and handles the end of line sequence.
void setTerminator (const QString &term)
Sets the terminator used to signify the end of the PVL informationDefaults to "END".
QString terminator () const
Returns the terminator used to signify the end of the PVL informationDefaults to "END".
void setFormatTemplate (Isis::Pvl &temp)
void setFormatTemplate (const QString &filename)
void setFormatTemplate (PvlContainer &ref)
void validatePvl (const Pvl &pPvl, Pvl &pPvlResults)
Validate a Pvl with the Template Pvl.
int groups () const
Returns the number of groups contained.
PvlGroup & group (const int index)
Return the group at the specified index.
const PvlGroup & group (const int index) const
Return the group at the specified index.
PvlGroupIterator beginGroup ()
Returns the beginning group index.
ConstPvlGroupIterator beginGroup () const
Returns the beginning group index.
PvlGroupIterator endGroup ()
Returns the ending group index.
ConstPvlGroupIterator endGroup () const
Returns the const ending group index.
PvlGroupIterator findGroup (const QString &name, PvlGroupIterator beg, PvlGroupIterator end)
Find a group with the specified name, within these indexes.
ConstPvlGroupIterator findGroup (const QString &name, ConstPvlGroupIterator beg, ConstPvlGroupIterator end) const
Find a group with the specified name, within these indexes.
Isis::PvlGroup & findGroup (const QString &name, FindOptions opts=None)
Finds a group within the current PvlObject.
const Isis::PvlGroup & findGroup (const QString &name, FindOptions opts=None) const
Finds a group within the current PvlObject.
PvlKeyword & findKeyword (const QString &kname, FindOptions opts)
Finds a keyword in the current PvlObject, or deeper inside other PvlObjects and Pvlgroups within this one.
PvlKeyword & findKeyword (const QString &name)
Find a keyword with a specified name.
const PvlKeyword & findKeyword (const QString &name) const
Find a keyword with a specified name.
PvlKeywordIterator findKeyword (const QString &name, PvlKeywordIterator beg, PvlKeywordIterator end)
Find the index of a keyword, using iterators.
ConstPvlKeywordIterator findKeyword (const QString &name, ConstPvlKeywordIterator beg, ConstPvlKeywordIterator end) const
Find the index of a keyword, using iterators.
PvlKeyword & findKeyword (const QString &name)
Find a keyword with a specified name.
const PvlKeyword & findKeyword (const QString &name) const
Find a keyword with a specified name.
PvlKeywordIterator findKeyword (const QString &name, PvlKeywordIterator beg, PvlKeywordIterator end)
Find the index of a keyword, using iterators.
ConstPvlKeywordIterator findKeyword (const QString &name, ConstPvlKeywordIterator beg, ConstPvlKeywordIterator end) const
Find the index of a keyword, using iterators.
bool hasKeyword (const QString &kname, FindOptions opts) const
See if a keyword is in the current PvlObject, or deeper inside other PvlObjects and Pvlgroups within this one.
bool hasKeyword (const QString &name) const
Check to see if a keyword exists.
bool hasKeyword (const QString &name) const
Check to see if a keyword exists.
void addGroup (const Isis::PvlGroup &group)
Add a group to the object.
void operator+= (const Isis::PvlGroup &group)
void operator+= (const Isis::PvlObject &obj)
void operator+= (const PvlKeyword &keyword)
When you use the += operator with a PvlKeyword, it will call the addKeyword() method.
void operator+= (const PvlKeyword &keyword)
When you use the += operator with a PvlKeyword, it will call the addKeyword() method.
void deleteGroup (const QString &name)
Remove a group from the current PvlObject.
void deleteGroup (const int index)
Remove a group from the current PvlObject.
bool hasGroup (const QString &name) const
Returns a boolean value based on whether the object has the specified group or not.
int objects () const
Returns the number of objects.
PvlObject & object (const int index)
Return the object at the specified index.
const PvlObject & object (const int index) const
Return the object at the specified index.
PvlObjectIterator beginObject ()
Returns the index of the beginning object.
ConstPvlObjectIterator beginObject () const
Returns the const index of the beginning object.
PvlObjectIterator endObject ()
Returns the index of the ending object.
ConstPvlObjectIterator endObject () const
Returns the const index of the ending object.
PvlObjectIterator findObject (const QString &name, PvlObjectIterator beg, PvlObjectIterator end)
Find the index of object with a specified name, between two indexes.
ConstPvlObjectIterator findObject (const QString &name, ConstPvlObjectIterator beg, ConstPvlObjectIterator end) const
Find the index of object with a specified name, between two indexes.
PvlObject & findObject (const QString &name, FindOptions opts=None)
Find an object within the current PvlObject.
const PvlObject & findObject (const QString &name, FindOptions opts=None) const
Find an object within the current PvlObject.
void addObject (const PvlObject &object)
Add a PvlObject.
void deleteObject (const QString &name)
Remove an object from the current PvlObject.
void deleteObject (const int index)
Remove an object from the current PvlObject.
bool hasObject (const QString &name) const
Returns a boolean value based on whether the object exists in the current PvlObject or not.
bool operator== (const PvlObject &object) const
Compares two PvlObjects.
void clear ()
Remove everything from the current PvlObject.
void validateObject (PvlObject &pPvlObj)
Validate Object.
void setName (const QString &name)
Set the name of the container.
QString name () const
Returns the container name.
bool isNamed (const QString &match) const
Returns whether the given string is equal to the container name or not.
QString type () const
Returns the container type.
int keywords () const
Returns the number of keywords contained in the PvlContainer.
void addKeyword (const PvlKeyword &keyword, const InsertMode mode=Append)
Add a keyword to the container.
PvlKeywordIterator addKeyword (const PvlKeyword &keyword, PvlKeywordIterator pos)
Insert a keyword at the specified iterator position.
PvlKeyword & operator[] (const QString &name)
When you use the [] operator with a (string) name, it will call the findKeyword() method.
PvlKeyword & operator[] (const int index)
Return the PvlKeyword object at the specified index.
PvlKeyword & operator[] (const char *name)
When you use the [] operator with a (char) name, it will call the findKeyword() method.
const PvlKeyword & operator[] (const QString &name) const
When you use the [] operator with a (string) name, it will call the findKeyword() method.
const PvlKeyword & operator[] (const int index) const
Return the PvlKeyword object at the specified index.
PvlKeyword operator[] (const char *name) const
When you use the [] operator with a (char) name, it will call the findKeyword() method.
PvlKeywordIterator begin ()
Return the beginning iterator.
ConstPvlKeywordIterator begin () const
Return the const beginning iterator.
PvlKeywordIterator end ()
Return the ending iterator.
ConstPvlKeywordIterator end () const
Return the const ending iterator.
void deleteKeyword (const QString &name)
Remove a specified keyword.
void deleteKeyword (const int index)
Remove the specified keyword.
bool cleanDuplicateKeywords ()
Removes keywords from the container that have BOTH the same name and value.
void operator-= (const QString &name)
When you use the -= operator with a (string) name, it will call the deleteKeyword() method.
void operator-= (const PvlKeyword &key)
When you use the -= operator with a PvlKeyword object, it will call the deleteKeyword() method.
QString fileName () const
Returns the filename used to initialise the Pvl object.
bool hasFormatTemplate ()
PvlContainer * formatTemplate ()
PvlFormat * format ()
void setFormat (PvlFormat *format)
int indent ()
void setIndent (int indent)
int comments () const
QString comment (const int index) const
void addComment (const QString &comment)
PvlKeyword & nameKeyword ()
const PvlKeyword & nameKeyword () const
Protected Member Functions
void setFileName (const QString &filename)
Sets the filename to the specified string.
void validateAllKeywords (PvlContainer &pPvlCont)
Validate All the Keywords in a Container comparing with the Template.
void validateRepeatOption (PvlKeyword &pPvlTmplKwrd, PvlContainer &pPvlCont)
Validate the Repeat Option for a Keyword.
Protected Attributes
QString m_filename
This contains the filename used to initialize the pvl object.
PvlKeyword m_name
This is the name keyword.
QList< PvlKeyword > m_keywords
This is the vector of PvlKeywords the container is holding.
PvlContainer * m_formatTemplate
Detailed Description
Loads plugins from a shared library.
This class is used to handle dynamic loading of module/classes. It is rarely used directly but instead is inherited for a particular purpose such as managing class specific map projections or camera models. The class is derived from a PVL which aides in the selection of the shared library and plugin routine to load. For example, assume the file my.plugin contained:
OBJECT=SINUSOIDAL
  LIBRARY=libisis3.so
  ROUTINE=SinusoidalPlugin
END_OBJECT
OBJECT=SIMPLECYLINDRICAL
  LIBRARY=libisis3.so
  ROUTINE=SimpleCylindricalPlugin
END_OBJECT
The desired routine can be selected in code as follows:
Plugin p;
p.Read("my.plugin");
string proj;
cin >> proj;  // Enter either SINUSOIDAL or SIMPLECYLINDRICAL
p.Find(proj);
void *ptr = p.GetPlugin();
Obtaining plugins can be difficult to understand. It is suggested you look at ProjectionFactory to get a better understanding of how they are used.
See also
ProjectionFactory
CameraFactory
Author
2004-02-07 Jeff Anderson
Member Typedef Documentation
ConstPvlGroupIterator
typedef QList<Isis::PvlGroup>::const_iterator Isis::PvlObject::ConstPvlGroupIterator inherited
ConstPvlKeywordIterator
typedef QList<PvlKeyword>::const_iterator Isis::PvlContainer::ConstPvlKeywordIterator inherited
The const keyword iterator.
ConstPvlObjectIterator
typedef QList<PvlObject>::const_iterator Isis::PvlObject::ConstPvlObjectIterator inherited
PvlGroupIterator
typedef QList<Isis::PvlGroup>::iterator Isis::PvlObject::PvlGroupIterator inherited
The counter for groups.
PvlKeywordIterator
typedef QList<PvlKeyword>::iterator Isis::PvlContainer::PvlKeywordIterator inherited
The keyword iterator.
PvlObjectIterator
typedef QList<PvlObject>::iterator Isis::PvlObject::PvlObjectIterator inherited
The counter for objects.
Member Enumeration Documentation
FindOptions
enum Isis::PvlObject::FindOptions inherited
A collection of options to use when finding.
Enumerator
None
Search only the current level.
Traverse
Search child objects.
InsertMode
enum Isis::PvlContainer::InsertMode inherited
Contains both modes: Append or Replace.
Enumerator
Append
Replace
Constructor & Destructor Documentation
Plugin()
Isis::Plugin::Plugin ()
Constructs a Plugin object.
~Plugin()
virtual Isis::Plugin::~Plugin () inline virtual
Destroys the Plugin object.
Member Function Documentation
addComment()
void Isis::PvlContainer::addComment (const QString & comment) inline inherited
References Isis::PvlKeyword::addComment(), Isis::PvlContainer::comment(), and Isis::PvlContainer::m_name.
Referenced by Isis::Equalization::setResults(), Isis::Table::toBlob(), and Isis::ControlNetVersioner::write().
addGroup()
void Isis::PvlObject::addGroup (const Isis::PvlGroup & group) inline inherited
Add a group to the object.
Parameters
group The PvlGroup object to add.
References Isis::PvlObject::group().
Referenced by Isis::InterestOperator::addGroup(), Isis::ControlNetDiff::addUniqueMeasure(), Isis::Gruen::AlgorithmStatistics(), Isis::Application::AppendAndLog(), Isis::Camera::BasicMapping(), Isis::Camera::basicRingMapping(), Isis::NaifStatus::CheckErrors(), IsisAml::CommandLine(), Isis::ControlNetDiff::compareGroups(), Isis::TiffImporter::convertProjection(), Isis::Cube::copy(), Isis::Cube::create(), Isis::LabelTranslationManager::CreateContainer(), Isis::fitsToJson(), Isis::Application::History(), Isis::ImageImporter::import(), Isis::PvlObject::operator+=(), Isis::Process::PropagateLabels(), Isis::Cube::putGroup(), Isis::AutoReg::RegistrationStatistics(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::Stretch::Save(), Isis::UserInterface::SaveHistory(), Isis::Process::SetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), Isis::Equalization::setResults(), Isis::ControlNetVersioner::toPvl(), Isis::CameraStatistics::toPvl(), Isis::IException::toPvl(), Isis::MultivariateStatistics::toPvl(), Isis::OverlapStatistics::toPvl(), Isis::ProcessImportPds::TranslatePdsProjection(), Isis::AlphaCube::UpdateGroup(), and Isis::ControlNetVersioner::write().
addKeyword() [1/2]
void Isis::PvlContainer::addKeyword (const PvlKeyword & keyword, const InsertMode mode = Append) inherited
Add a keyword to the container.
Add a keyword to the PvlContainer object.
Parameters
keyword The PvlKeyword object to append.
mode Using the InsertMode value of Append.
key The PvlKeyword object to add.
mode The enum InsertMode has two possible values, Append or Replace. Use Append if you just want to add it to the end, Replace if you want to replace it.
References Isis::PvlKeyword::name().
Referenced by Isis::ControlNetDiff::addUniqueMeasure(), Isis::ControlNetDiff::addUniquePoint(), Isis::NaifStatus::CheckErrors(), Isis::ControlNetDiff::compare(), Isis::ControlNetDiff::compareGroups(), Isis::CameraFactory::Create(), Isis::ShapeModelFactory::create(), Isis::ProjectionFactory::CreateForCube(), Isis::ControlNetDiff::diff(), Isis::fitsToJson(), Isis::PvlContainer::operator+=(), Isis::operator<<(), Isis::GridPolygonSeeder::PluginParameters(), Isis::LimitPolygonSeeder::PluginParameters(), Isis::PolygonSeeder::PluginParameters(), Isis::StripPolygonSeeder::PluginParameters(), Isis::PvlObject::PvlObject(), Isis::Target::radiiGroup(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::Stretch::Save(), Isis::ProcessMapMosaic::SetOutputCube(), Isis::Projection::SetUpperLeftCorner(), Isis::ProcessMosaic::StartProcess(), Isis::SubArea::UpdateLabel(), Isis::CubeTileHandler::updateLabels(), Isis::CubeBsqHandler::updateLabels(), and Isis::ControlNetVersioner::write().
addKeyword() [2/2]
PvlContainer::PvlKeywordIterator Isis::PvlContainer::addKeyword (const PvlKeyword & keyword, PvlKeywordIterator pos) inherited
Insert a keyword at the specified iterator position.
This method provides the capability to insert a keyword at the specified iterator position. The process follows the description of the STL vector definition along with all the caveats (e.g., invalidation of iterators upon insert operations).
This method will not perform any checks for the existance of the keyword. This could lead to multiple instances of the same keyword in the same container. It is up to the caller to manage this issue.
Parameters
key Keyword to insert
pos Iterator position where to insert the new keyword
Returns
PvlContainer::PvlKeywordIterator Returns the position of the inserted keyword per the STL vector documentation.
addObject()
void Isis::PvlObject::addObject (const PvlObject & object) inline inherited
Add a PvlObject.
Parameters
object The PvlObject to add.
References Isis::PvlContainer::fileName().
Referenced by Isis::ControlNetDiff::addUniquePoint(), Isis::ControlNetDiff::compare(), Isis::Cube::copy(), Isis::Cube::create(), Isis::LabelTranslationManager::CreateContainer(), Isis::ProcessExportPds::ExportTable(), Isis::ProcessExportPds::FixedJP2ImageRoot(), Isis::PvlObject::operator+=(), Isis::Process::PropagateLabels(), Isis::Process::SetOutputCube(), Isis::Equalization::setResults(), Isis::ProcessExportPds::StreamJP2ImageRoot(), Isis::ControlNetVersioner::toPvl(), Isis::OverlapStatistics::toPvl(), Isis::Blob::Write(), and Isis::ControlNetVersioner::write().
append()
void Isis::Pvl::append (const QString & file) inherited
Appends PVL information to a file and handles the end of line sequence.
Parameters
file Name of the file to append to.
Exceptions
Isis::iException::Io
References _FILEINFO_, Isis::FileName::expanded(), Isis::Message::FileOpen(), Isis::PvlContainer::format(), Isis::PvlFormat::formatEOL(), Isis::IException::Io, Isis::PvlContainer::setFormat(), and Isis::Pvl::terminator().
begin() [1/2]
PvlKeywordIterator Isis::PvlContainer::begin () inline inherited
Return the beginning iterator.
Returns
The beginning iterator.
References Isis::PvlContainer::m_keywords.
Referenced by Isis::PvlToPvlTranslationManager::DoTranslation(), Isis::PvlObject::findKeyword(), Isis::PvlObject::hasKeyword(), Isis::PvlTranslationTable::InputGroup(), Isis::DbProfile::loadkeys(), Isis::pvlContainerToJSON(), Isis::PvlTranslationTable::Translate(), and Isis::XmlToPvlTranslationManager::Translate().
begin() [2/2]
ConstPvlKeywordIterator Isis::PvlContainer::begin () const inline inherited
Return the const beginning iterator.
Returns
The const beginning iterator.
References Isis::PvlContainer::m_keywords.
beginGroup() [1/2]
PvlGroupIterator Isis::PvlObject::beginGroup () inline inherited
Returns the beginning group index.
Returns
The iterator of the beginning group..
Referenced by Isis::PvlObject::deleteGroup(), Isis::PvlObject::findGroup(), Isis::Cube::fromLabel(), Isis::PvlObject::hasGroup(), Isis::DbAccess::load(), and Isis::BundleTargetBody::readFromPvl().
beginGroup() [2/2]
ConstPvlGroupIterator Isis::PvlObject::beginGroup () const inline inherited
Returns the beginning group index.
Returns
The iterator of the beginning group..
beginObject() [1/2]
PvlObjectIterator Isis::PvlObject::beginObject () inline inherited
Returns the index of the beginning object.
Returns
The beginning object's index.
Referenced by Isis::StretchTool::deleteFromCube(), Isis::PvlObject::deleteObject(), Isis::PvlObject::findObject(), Isis::Equalization::fromPvl(), Isis::Strategy::getObjectList(), Isis::PvlObject::hasObject(), Isis::StretchTool::loadStretchFromCube(), Isis::ImageReader::read(), Isis::ShapeReader::read(), and Isis::StretchTool::saveStretchToCube().
beginObject() [2/2]
ConstPvlObjectIterator Isis::PvlObject::beginObject () const inline inherited
Returns the const index of the beginning object.
Returns
The beginning object's index.
cleanDuplicateKeywords()
bool Isis::PvlContainer::cleanDuplicateKeywords () inherited
Removes keywords from the container that have BOTH the same name and value.
Returns
bool True if one or more keywords were deleted; False if no keywords were deleted.
clear()
void Isis::PvlObject::clear () inline inherited
Remove everything from the current PvlObject.
References Isis::PvlContainer::clear().
Referenced by IsisAml::CommandLine(), and Isis::QIsisApplication::QIsisApplication().
comment()
QString Isis::PvlContainer::comment (const int index) const inline inherited
References Isis::PvlKeyword::comment(), and Isis::PvlContainer::m_name.
Referenced by Isis::PvlContainer::addComment(), Isis::operator<<(), and Isis::pvlContainerToJSON().
comments()
int Isis::PvlContainer::comments () const inline inherited
References Isis::PvlKeyword::comments(), and Isis::PvlContainer::m_name.
Referenced by Isis::operator<<(), and Isis::pvlContainerToJSON().
deleteGroup() [1/2]
void Isis::PvlObject::deleteGroup (const int index) inherited
Remove a group from the current PvlObject.
Parameters
index The index of the PvlGroup to remove.
Exceptions
IException
References _FILEINFO_, Isis::PvlObject::beginGroup(), Isis::PvlContainer::m_filename, Isis::PvlContainer::name(), Isis::PvlContainer::type(), and Isis::IException::Unknown.
deleteGroup() [2/2]
void Isis::PvlObject::deleteGroup (const QString & name) inherited
Remove a group from the current PvlObject.
Parameters
name The name of the PvlGroup to remove.
Exceptions
IException
References _FILEINFO_, Isis::PvlObject::beginGroup(), Isis::PvlObject::endGroup(), Isis::PvlObject::findGroup(), Isis::PvlContainer::m_filename, Isis::PvlContainer::name(), Isis::PvlContainer::type(), and Isis::IException::Unknown.
Referenced by Isis::Cube::deleteGroup(), Isis::UserInterface::SaveHistory(), Isis::PvlObject::validateObject(), and Isis::Pvl::validatePvl().
deleteKeyword() [1/2]
void Isis::PvlContainer::deleteKeyword (const int index) inherited
Remove the specified keyword.
Parameters
index The index of the keyword to remove.
Exceptions
iException::Pvl Keyword doesn't exist.
References _FILEINFO_.
deleteKeyword() [2/2]
void Isis::PvlContainer::deleteKeyword (const QString & name) inherited
Remove a specified keyword.
Parameters
name The name of the keyword to remove.
Exceptions
iException::Pvl Keyword doesn't exist.
References _FILEINFO_.
Referenced by IsisAml::CommandLine(), Isis::ControlPointV0001::ControlPointV0001(), Isis::ControlPointV0002::ControlPointV0002(), Isis::ControlPointV0003::ControlPointV0003(), Isis::Preference::Load(), Isis::ObliqueCylindrical::ObliqueCylindrical(), Isis::PvlContainer::operator-=(), Isis::GridPolygonSeeder::Parse(), Isis::LimitPolygonSeeder::Parse(), Isis::PolygonSeeder::Parse(), Isis::StripPolygonSeeder::Parse(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), Isis::ProcessExportPds::StandardImageImage(), Isis::ProcessExportPds::StandardJP2Image(), Isis::SubArea::UpdateLabel(), Isis::PvlContainer::validateAllKeywords(), and Isis::PvlContainer::validateRepeatOption().
deleteObject() [1/2]
void Isis::PvlObject::deleteObject (const int index) inherited
Remove an object from the current PvlObject.
Parameters
index The index of the PvlObject to remove.
Exceptions
IException
References _FILEINFO_, Isis::PvlObject::beginObject(), Isis::PvlContainer::m_filename, Isis::PvlContainer::name(), Isis::PvlContainer::type(), and Isis::IException::Unknown.
deleteObject() [2/2]
void Isis::PvlObject::deleteObject (const QString & name) inherited
Remove an object from the current PvlObject.
Parameters
name The name of the PvlObject to remove.
Exceptions
IException
References _FILEINFO_, Isis::PvlObject::beginObject(), Isis::PvlObject::endObject(), Isis::PvlObject::findObject(), Isis::PvlContainer::m_filename, Isis::PvlContainer::name(), Isis::PvlContainer::type(), and Isis::IException::Unknown.
Referenced by Isis::Cube::attachSpiceFromIsd(), Isis::Cube::deleteBlob(), Isis::RemoveHiBlobs(), Isis::PvlObject::validateObject(), and Isis::Pvl::validatePvl().
end() [1/2]
PvlKeywordIterator Isis::PvlContainer::end () inline inherited
Return the ending iterator.
Returns
The ending iterator.
References Isis::PvlContainer::m_keywords.
Referenced by Isis::PvlToPvlTranslationManager::DoTranslation(), Isis::PvlObject::findGroup(), Isis::PvlObject::findKeyword(), Isis::PvlObject::findObject(), Isis::PvlObject::hasKeyword(), Isis::PvlTranslationTable::InputGroup(), Isis::DbProfile::loadkeys(), Isis::pvlContainerToJSON(), Isis::PvlTranslationTable::Translate(), and Isis::XmlToPvlTranslationManager::Translate().
end() [2/2]
ConstPvlKeywordIterator Isis::PvlContainer::end () const inline inherited
Return the const ending iterator.
Returns
The const ending iterator.
References Isis::PvlContainer::m_keywords.
endGroup() [1/2]
PvlGroupIterator Isis::PvlObject::endGroup () inline inherited
Returns the ending group index.
Returns
The iterator of the ending group.
Referenced by Isis::PvlObject::deleteGroup(), Isis::PvlObject::findGroup(), Isis::Cube::fromLabel(), Isis::PvlObject::hasGroup(), Isis::DbAccess::load(), and Isis::BundleTargetBody::readFromPvl().
endGroup() [2/2]
ConstPvlGroupIterator Isis::PvlObject::endGroup () const inline inherited
Returns the const ending group index.
Returns
The iterator of the ending group.
endObject() [1/2]
PvlObjectIterator Isis::PvlObject::endObject () inline inherited
Returns the index of the ending object.
Returns
The ending object's index.
Referenced by Isis::PvlObject::deleteObject(), Isis::PvlObject::findObject(), Isis::Equalization::fromPvl(), Isis::Strategy::getObjectList(), Isis::PvlObject::hasObject(), Isis::ImageReader::read(), and Isis::ShapeReader::read().
endObject() [2/2]
ConstPvlObjectIterator Isis::PvlObject::endObject () const inline inherited
Returns the const index of the ending object.
Returns
The ending object's index.
fileName()
QString Isis::PvlContainer::fileName () const inline inherited
Returns the filename used to initialise the Pvl object.
If the object was not initialized using a file, this string is empty.
Returns
The filename.
References Isis::PvlContainer::m_filename.
Referenced by Isis::PvlObject::addObject(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ObservationNumber::Compose(), Isis::SerialNumber::Compose(), Isis::ProjectionFactory::CreateForCube(), Isis::ProjectionFactory::CreateFromCube(), Isis::DawnVirCamera::DawnVirCamera(), Isis::PvlTranslationTable::findTranslationGroup(), Isis::PvlToPvlTranslationManager::InputKeyword(), Isis::PvlToXmlTranslationManager::InputKeyword(), Isis::InterestOperator::Parse(), Isis::AutoReg::Parse(), Isis::GridPolygonSeeder::Parse(), Isis::LimitPolygonSeeder::Parse(), Isis::PolygonSeeder::Parse(), Isis::StripPolygonSeeder::Parse(), Isis::PvlEditDialog::PvlEditDialog(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::ProjectionFactory::RingsCreateFromCube(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), and Isis::PvlTranslationTable::Translate().
findGroup() [1/4]
ConstPvlGroupIterator Isis::PvlObject::findGroup (const QString & name, ConstPvlGroupIterator beg, ConstPvlGroupIterator end) const inline inherited
Find a group with the specified name, within these indexes.
Parameters
name The name of the group to look for.
beg The lower index
end The higher index
References Isis::PvlContainer::end(), and Isis::PvlContainer::name().
findGroup() [2/4]
Isis::PvlGroup & Isis::PvlObject::findGroup (const QString & name, PvlObject::FindOptions opts = None) inherited
Finds a group within the current PvlObject.
Parameters
name The name of the group to look for.
opts The FindOptions option (None or Traverse).
Returns
The PvlGroup object sought for.
Exceptions
IException
References _FILEINFO_, Isis::PvlObject::beginGroup(), Isis::PvlObject::endGroup(), Isis::PvlContainer::m_filename, Isis::PvlContainer::name(), Isis::PvlObject::Traverse, and Isis::IException::Unknown.
findGroup() [3/4]
const Isis::PvlGroup & Isis::PvlObject::findGroup (const QString & name, PvlObject::FindOptions opts = None) const inherited
Finds a group within the current PvlObject.
Parameters
name The name of the group to look for.
opts The FindOptions option (None or Traverse).
Returns
The PvlGroup object sought for.
Exceptions
IException
References _FILEINFO_, Isis::PvlObject::beginGroup(), Isis::PvlObject::endGroup(), Isis::PvlContainer::m_filename, Isis::PvlContainer::name(), Isis::PvlObject::Traverse, and Isis::IException::Unknown.
findGroup() [4/4]
PvlGroupIterator Isis::PvlObject::findGroup (const QString & name, PvlGroupIterator beg, PvlGroupIterator end) inline inherited
Find a group with the specified name, within these indexes.
Parameters
name The name of the group to look for.
beg The lower index
end The higher index
References Isis::PvlContainer::end(), and Isis::PvlContainer::name().
Referenced by Isis::SerialNumberList::add(), Isis::ControlNetDiff::addTolerances(), Isis::AlphaCube::AlphaCube(), Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::BulletShapeModel::BulletShapeModel(), Isis::Camera::Camera(), Isis::CameraFactory::CameraVersion(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ClipperWacFcCamera::ClipperWacFcCamera(), Isis::TiffImporter::convertProjection(), Isis::CorrelationMatrix::CorrelationMatrix(), Isis::CameraFactory::Create(), Isis::ProjectionFactory::Create(), Isis::Gui::Create(), Isis::InterestOperatorFactory::Create(), Isis::AutoRegFactory::Create(), Isis::PolygonSeederFactory::Create(), Isis::ShapeModelFactory::create(), Isis::LabelTranslationManager::CreateContainer(), Isis::ProjectionFactory::CreateForCube(), Isis::ProjectionFactory::CreateFromCube(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::CubeIoHandler::CubeIoHandler(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::PvlObject::deleteGroup(), Isis::DemShape::DemShape(), Isis::PvlToPvlTranslationManager::DoTranslation(), Isis::EmbreeShapeModel::EmbreeShapeModel(), Isis::Equirectangular::Equirectangular(), Isis::KernelDb::findAll(), Isis::Cube::fromIsd(), Isis::MosaicSceneWidget::fromPvl(), Isis::Equalization::fromPvl(), Isis::CubeViewport::getBandFilterName(), Isis::PvlToPvlTranslationManager::GetContainer(), Isis::PvlToXmlTranslationManager::GetContainer(), GetPlugin(), Isis::GroundGrid::GroundGrid(), Isis::Camera::GroundRange(), Isis::Cube::group(), Isis::PvlObject::hasGroup(), Isis::Spice::hasKernels(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::Application::History(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IdealCamera::IdealCamera(), Isis::Equalization::importStatistics(), Isis::VimsGroundMap::Init(), Isis::VimsSkyMap::Init(), Isis::CameraFactory::initPlugin(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LambertConformal::LambertConformal(), Isis::Stretch::Load(), Isis::DbAccess::load(), Isis::KernelDb::loadSystemDb(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::LunarAzimuthalEqualArea::LunarAzimuthalEqualArea(), Isis::LwirCamera::LwirCamera(), Isis::MarciCamera::MarciCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::KernelDb::matches(), Isis::MdisCamera::MdisCamera(), Isis::Mercator::Mercator(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MiniRF::MiniRF(), Isis::Process::MissionData(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::Mollweide::Mollweide(), Isis::MsiCamera::MsiCamera(), Isis::NaifDskShape::NaifDskShape(), Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::NirCamera::NirCamera(), Isis::ObliqueCylindrical::ObliqueCylindrical(), Isis::Orthographic::Orthographic(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::InterestOperator::Parse(), Isis::AutoReg::Parse(), Isis::GridPolygonSeeder::Parse(), Isis::LimitPolygonSeeder::Parse(), Isis::PolygonSeeder::Parse(), Isis::StripPolygonSeeder::Parse(), Isis::ControlNetValidMeasure::Parse(), Isis::Planar::Planar(), Isis::PointPerspective::PointPerspective(), Isis::PolarStereographic::PolarStereographic(), Isis::Progress::Progress(), Isis::Projection::Projection(), Isis::Cube::putGroup(), Isis::Target::radiiGroup(), Isis::PvlKeyword::reform(), Isis::ReseauDistortionMap::ReseauDistortionMap(), Isis::RingCylindrical::RingCylindrical(), Isis::Camera::ringRange(), Isis::ProjectionFactory::RingsCreate(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::ProjectionFactory::RingsCreateFromCube(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::Robinson::Robinson(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::UserInterface::SaveHistory(), Isis::ProcessMosaic::SetInputCube(), Isis::ProcessMapMosaic::SetOutputCube(), Isis::ProcessGroundPolygons::SetStatCubes(), Isis::ControlNet::SetTarget(), Isis::SimpleCylindrical::SimpleCylindrical(), Isis::Sinusoidal::Sinusoidal(), Isis::Spice::Spice(), Isis::SsiCamera::SsiCamera(), Isis::ProcessExportPds4::StandardAllMapping(), Isis::ProcessExportPds::StandardAllMapping(), Isis::ProcessMosaic::StartProcess(), Isis::Target::Target(), Isis::Pipeline::TemporaryFolder(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::ThemisVisCamera::ThemisVisCamera(), Isis::XmlToPvlTranslationManager::Translate(), Isis::ProcessImportPds::TranslatePdsProjection(), Isis::TransverseMercator::TransverseMercator(), Isis::AlphaCube::UpdateGroup(), Isis::UvvisCamera::UvvisCamera(), Isis::PvlObject::validateObject(), Isis::Pvl::validatePvl(), Isis::VikingCamera::VikingCamera(), Isis::VimsCamera::VimsCamera(), and Isis::VoyagerCamera::VoyagerCamera().
findKeyword() [1/9]
PvlKeyword & Isis::PvlObject::findKeyword (const QString & kname, FindOptions opts) inherited
Finds a keyword in the current PvlObject, or deeper inside other PvlObjects and Pvlgroups within this one.
Note: This member has the same name as the PvlContainer and hides those implementations, but with the using statement the parents FindKeyword members ar made visible. Note: If more than one occurance of a Keyword appears below this Object no guarantee is made as to which one is returned.
Parameters
kname The name of the keyword to look for.
opts The FindOptions option (None or Traverse).
Returns
The keyword sought
Exceptions
IException
References _FILEINFO_, Isis::PvlContainer::begin(), Isis::PvlContainer::end(), Isis::PvlObject::findKeyword(), Isis::PvlObject::group(), Isis::PvlContainer::m_filename, Isis::PvlObject::None, and Isis::IException::Unknown.
Referenced by Isis::ControlNetDiff::compare(), Isis::CorrelationMatrix::CorrelationMatrix(), Isis::CSMCamera::CSMCamera(), Isis::CubeIoHandler::CubeIoHandler(), Isis::Cube::deleteBlob(), Isis::Blob::Find(), Isis::SpicePosition::LoadCache(), Isis::SpiceRotation::LoadCache(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::ProcessImportPds::ProcessLabel(), Isis::Target::radiiGroup(), Isis::SsiCamera::SsiCamera(), Isis::ProcessExportPds::StandardAllMapping(), Isis::PvlObject::validateObject(), and Isis::Pvl::validatePvl().
findKeyword() [2/9]
Isis::PvlKeyword & Isis::PvlContainer::findKeyword (const QString & name) inherited
Find a keyword with a specified name.
Parameters
name The name of the keyword to look for.
Returns
The PvlKeyword object.
Exceptions
iException::Pvl The keyword doesn't exist.
References _FILEINFO_.
Referenced by Isis::MosaicSceneWidget::addToPermanent(), Isis::BundleObservationSolveSettings::BundleObservationSolveSettings(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ControlNetDiff::compare(), Isis::ControlNetDiff::compareGroups(), Isis::CubeIoHandler::CubeIoHandler(), Isis::PvlToPvlTranslationManager::DoTranslation(), Isis::PvlToXmlTranslationManager::doTranslation(), Isis::fitsToJson(), Isis::CubeViewport::getBandFilterName(), Isis::PvlTranslationTable::InputGroup(), Isis::PvlToPvlTranslationManager::InputKeyword(), Isis::PvlToXmlTranslationManager::InputKeyword(), Isis::JunoCamera::JunoCamera(), Isis::Stretch::Load(), Isis::KernelDb::matches(), Isis::PvlContainer::operator[](), Isis::Target::radiiGroup(), Isis::ReseauDistortionMap::ReseauDistortionMap(), Isis::MosaicSceneWidget::setProjection(), Isis::CubeViewport::setTrackingCube(), Isis::ProcessExportPds4::StandardAllMapping(), Isis::ProcessExportPds::StandardAllMapping(), Isis::PvlTranslationTable::Translate(), Isis::XmlToPvlTranslationManager::Translate(), Isis::PvlContainer::validateAllKeywords(), Isis::PvlObject::validateObject(), and Isis::Pvl::validatePvl().
findKeyword() [3/9]
Isis::PvlKeyword & Isis::PvlContainer::findKeyword inherited
Find a keyword with a specified name.
Parameters
name The name of the keyword to look for.
Returns
The PvlKeyword object.
Exceptions
iException::Pvl The keyword doesn't exist.
Referenced by Isis::PvlObject::findKeyword().
findKeyword() [4/9]
const Isis::PvlKeyword & Isis::PvlContainer::findKeyword (const QString & name) const inherited
Find a keyword with a specified name.
Parameters
name The name of the keyword to look for.
Returns
The PvlKeyword object.
Exceptions
IException The keyword doesn't exist.
References _FILEINFO_.
findKeyword() [5/9]
const Isis::PvlKeyword & Isis::PvlContainer::findKeyword inherited
Find a keyword with a specified name.
Parameters
name The name of the keyword to look for.
Returns
The PvlKeyword object.
Exceptions
IException The keyword doesn't exist.
findKeyword() [6/9]
PvlContainer::ConstPvlKeywordIterator Isis::PvlContainer::findKeyword (const QString & name, PvlContainer::ConstPvlKeywordIterator beg, PvlContainer::ConstPvlKeywordIterator end) const inherited
Find the index of a keyword, using iterators.
Parameters
name The name of the keyword.
beg The beginning iterator.
end The ending iterator.
Returns
The keyword index.
findKeyword() [7/9]
PvlContainer::ConstPvlKeywordIterator Isis::PvlContainer::findKeyword inherited
Find the index of a keyword, using iterators.
Parameters
name The name of the keyword.
beg The beginning iterator.
end The ending iterator.
Returns
The keyword index.
findKeyword() [8/9]
PvlContainer::PvlKeywordIterator Isis::PvlContainer::findKeyword (const QString & name, PvlContainer::PvlKeywordIterator beg, PvlContainer::PvlKeywordIterator end) inherited
Find the index of a keyword, using iterators.
Parameters
name The name of the keyword.
beg The beginning iterator.
end The ending iterator.
Returns
The keyword index.
findKeyword() [9/9]
PvlContainer::PvlKeywordIterator Isis::PvlContainer::findKeyword inherited
Find the index of a keyword, using iterators.
Parameters
name The name of the keyword.
beg The beginning iterator.
end The ending iterator.
Returns
The keyword index.
findObject() [1/4]
ConstPvlObjectIterator Isis::PvlObject::findObject (const QString & name, ConstPvlObjectIterator beg, ConstPvlObjectIterator end) const inline inherited
Find the index of object with a specified name, between two indexes.
Parameters
name The name of the object to find.
beg The lower index.
end The higher index.
Returns
The index of the object.
References Isis::PvlContainer::end(), and Isis::PvlContainer::name().
findObject() [2/4]
PvlObject & Isis::PvlObject::findObject (const QString & name, PvlObject::FindOptions opts = None) inherited
Find an object within the current PvlObject.
Parameters
name The object name to look for.
opts The FindOptions option (None or Traverse).
Returns
The PvlObject sought for.
Exceptions
IException
References _FILEINFO_, Isis::PvlObject::beginObject(), Isis::PvlObject::endObject(), Isis::PvlContainer::m_filename, Isis::PvlContainer::name(), Isis::PvlObject::Traverse, and Isis::IException::Unknown.
findObject() [3/4]
const PvlObject & Isis::PvlObject::findObject (const QString & name, FindOptions opts = None) const inherited
Find an object within the current PvlObject.
Parameters
name The object name to look for.
opts The FindOptions option (None or Traverse).
Returns
The PvlObject sought for.
Exceptions
IException
References _FILEINFO_, Isis::PvlObject::beginObject(), Isis::PvlObject::endObject(), Isis::PvlContainer::m_filename, Isis::PvlContainer::name(), Isis::PvlObject::Traverse, and Isis::IException::Unknown.
findObject() [4/4]
PvlObjectIterator Isis::PvlObject::findObject (const QString & name, PvlObjectIterator beg, PvlObjectIterator end) inline inherited
Find the index of object with a specified name, between two indexes.
Parameters
name The name of the object to find.
beg The lower index.
end The higher index.
Returns
The index of the object.
References Isis::PvlContainer::end(), and Isis::PvlContainer::name().
Referenced by Isis::SerialNumberList::add(), Isis::Albedo::Albedo(), Isis::AlbedoAtm::AlbedoAtm(), Isis::PhotometricFunction::algorithmName(), Isis::AlphaCube::AlphaCube(), Isis::AtmosModel::AtmosModel(), Isis::AutoReg::AutoReg(), Isis::Camera::Camera(), Isis::ControlNetDiff::compare(), Isis::Cube::copy(), Isis::PhotoModelFactory::Create(), Isis::AtmosModelFactory::Create(), Isis::NormModelFactory::Create(), Isis::LabelTranslationManager::CreateContainer(), Isis::ProcessExportPds::CreateQubeLabel(), Isis::ProcessExportPds::CreateSpectralQubeLabel(), Isis::CubeIoHandler::CubeIoHandler(), Isis::CubeTileHandler::CubeTileHandler(), Isis::Cube::deleteGroup(), Isis::PvlObject::deleteObject(), Isis::Cube::externalCubeFileName(), Isis::ProcessExportPds4::fileAreaObservational(), Isis::KernelDb::findAll(), Isis::Cube::fromLabel(), Isis::MosaicSceneWidget::fromPvl(), Isis::Equalization::fromPvl(), Isis::Image::fromPvl(), Isis::Shape::fromPvl(), Isis::CubeViewport::getBandFilterName(), Isis::PvlToPvlTranslationManager::GetContainer(), Isis::PvlToXmlTranslationManager::GetContainer(), Isis::Cube::group(), Isis::Hapke::Hapke(), Isis::Cube::hasGroup(), Isis::PvlObject::hasObject(), Isis::ImageImporter::import(), Isis::Equalization::importStatistics(), Isis::DbAccess::load(), Isis::LunarLambert::LunarLambert(), Isis::LunarLambertEmpirical::LunarLambertEmpirical(), Isis::KernelDb::matches(), Isis::Minnaert::Minnaert(), Isis::MinnaertEmpirical::MinnaertEmpirical(), Isis::Mixed::Mixed(), Isis::MoonAlbedo::MoonAlbedo(), Isis::Cube::open(), Isis::AutoReg::Parse(), Isis::PhotoModel::PhotoModel(), Isis::ProcessImportPds::ProcessLabel(), Isis::Process::PropagateLabels(), Isis::Cube::putGroup(), Isis::Target::radiiGroup(), Isis::MosaicController::readProject(), Isis::BandSpinBox::setBandBin(), Isis::Process::SetOutputCube(), Isis::ProcessMosaic::SetOutputCube(), Isis::ControlNet::SetTarget(), Isis::Shade::Shade(), Isis::ShadeAtm::ShadeAtm(), Isis::ProcessExportPds4::StandardAllMapping(), Isis::ProcessExportPds::StandardAllMapping(), Isis::ProcessExportPds4::standardBandBin(), Isis::ProcessExportPds::StandardImageImage(), Isis::ProcessExportPds4::standardInstrument(), Isis::ProcessExportPds::StandardJP2Image(), Isis::ProcessMosaic::StartProcess(), Isis::Topo::Topo(), Isis::TopoAtm::TopoAtm(), Isis::ControlNetVersioner::toPvl(), Isis::ProcessExportPds4::translateBandBinSpectrumBinSet(), Isis::ProcessExportPds4::translateBandBinSpectrumUniform(), Isis::AlphaCube::UpdateGroup(), Isis::SubArea::UpdateLabel(), Isis::CubeTileHandler::updateLabels(), Isis::CubeBsqHandler::updateLabels(), Isis::SpectralPlotTool::updateTool(), Isis::PvlObject::validateObject(), Isis::Pvl::validatePvl(), and Isis::Blob::Write().
format()
PvlFormat* Isis::PvlContainer::format () inline inherited
References Isis::PvlKeyword::format(), and Isis::PvlContainer::m_name.
Referenced by Isis::Pvl::append(), Isis::ProcessExportPds::CreateImageLabel(), Isis::ProcessExportPds::FixedJP2ImageRoot(), Isis::operator<<(), Isis::PvlContainer::setFormat(), Isis::ProcessExportPds::StandardImageImage(), Isis::ProcessExportPds::StandardJP2Image(), Isis::ProcessExportPds::StreamJP2ImageRoot(), and Isis::Pvl::write().
formatTemplate()
PvlContainer* Isis::PvlContainer::formatTemplate () inline inherited
References Isis::PvlContainer::m_formatTemplate.
Referenced by Isis::operator<<().
fromString()
void Isis::Pvl::fromString (const std::string & str) inherited
Load PVL information from a string.
TODO: fully document
References _FILEINFO_, Isis::IException::Io, and Isis::IException::Unknown.
GetPlugin()
QFunctionPointer Isis::Plugin::GetPlugin (const QString & group)
This method returns a void pointer to a C function (i.e., the plugin) It does this by looking in itself (Pvl) for the keyword LIBRARY and the keyword ROUTINE.
When you write this function make sure to place extern "C" infront of it to eliminate C++ symbol mangling.
Parameters
group The group name.
Returns
A void pointer to a C function (i.e., the plugin)
History:
2010-03-16 Tracie Sucharski, Added paths to plugin. First try to load from current working directory, then from $ISISROOT/lib.
References _FILEINFO_, Isis::FileName::expanded(), Isis::PvlObject::findGroup(), Isis::PvlObject::group(), and Isis::IException::Unknown.
Referenced by Isis::InterestOperatorFactory::Create(), Isis::AutoRegFactory::Create(), Isis::PhotoModelFactory::Create(), Isis::PolygonSeederFactory::Create(), Isis::AtmosModelFactory::Create(), and Isis::NormModelFactory::Create().
group() [1/2]
Isis::PvlGroup & Isis::PvlObject::group (const int index) inherited
Return the group at the specified index.
Parameters
index The index of the group.
Returns
The PvlGroup sought for.
Exceptions
IException
References _FILEINFO_, Isis::Message::ArraySubscriptNotInRange(), and Isis::IException::Programmer.
Referenced by Isis::SessionLog::AddError(), Isis::PvlObject::addGroup(), Isis::LabelTranslationManager::Auto(), Isis::PvlToPvlTranslationManager::Auto(), Isis::PvlToXmlTranslationManager::Auto(), Isis::UserInterface::BuildNewCommandLineFromPvl(), Isis::ControlNetDiff::compare(), Isis::ControlPointV0001::ControlPointV0001(), Isis::ControlPointV0002::ControlPointV0002(), Isis::ControlPointV0003::ControlPointV0003(), Isis::Cube::copy(), Isis::ProcessExportPds4::createUnitMap(), Isis::KernelDb::findAll(), Isis::PvlObject::findKeyword(), Isis::Application::formatError(), GetPlugin(), Isis::PvlObject::hasKeyword(), Isis::Equalization::importStatistics(), Isis::Preference::Load(), Isis::PvlObject::operator+=(), Isis::Process::PropagateLabels(), Isis::Process::SetOutputCube(), Isis::Table::toBlob(), Isis::PvlObject::validateObject(), and Isis::Pvl::validatePvl().
group() [2/2]
const Isis::PvlGroup & Isis::PvlObject::group (const int index) const inherited
Return the group at the specified index.
Parameters
index The index of the group.
Returns
The PvlGroup sought for.
Exceptions
IException
References _FILEINFO_, Isis::Message::ArraySubscriptNotInRange(), and Isis::IException::Programmer.
groups()
int Isis::PvlObject::groups () const inline inherited
Returns the number of groups contained.
Returns
The number of groups.
Referenced by Isis::SessionLog::AddError(), Isis::LabelTranslationManager::Auto(), Isis::PvlToPvlTranslationManager::Auto(), Isis::PvlToXmlTranslationManager::Auto(), Isis::ControlNetDiff::compare(), Isis::ControlPointV0001::ControlPointV0001(), Isis::ControlPointV0002::ControlPointV0002(), Isis::ControlPointV0003::ControlPointV0003(), Isis::Cube::copy(), Isis::ProcessExportPds4::createUnitMap(), Isis::KernelDb::findAll(), Isis::Application::formatError(), Isis::Preference::Load(), Isis::Process::PropagateLabels(), Isis::UserInterface::SaveHistory(), Isis::Process::SetOutputCube(), Isis::IException::toString(), Isis::PvlObject::validateObject(), and Isis::Pvl::validatePvl().
hasFormatTemplate()
bool Isis::PvlContainer::hasFormatTemplate () inline inherited
References Isis::PvlContainer::m_formatTemplate.
Referenced by Isis::operator<<().
hasGroup()
bool Isis::PvlObject::hasGroup (const QString & name) const inline inherited
Returns a boolean value based on whether the object has the specified group or not.
Parameters
name The name of the group to look for.
Returns
True if the object has the group, false if not.
References Isis::PvlObject::beginGroup(), Isis::PvlObject::endGroup(), Isis::PvlObject::findGroup(), and Isis::PvlContainer::name().
Referenced by Isis::SerialNumberList::add(), Isis::ControlNetDiff::addTolerances(), Isis::AlphaCube::AlphaCube(), Isis::ControlNetValidMeasure::ControlNetValidMeasure(), Isis::LabelTranslationManager::CreateContainer(), Isis::Cube::deleteGroup(), Isis::KernelDb::findAll(), Isis::CubeViewport::getBandFilterName(), Isis::PvlToPvlTranslationManager::GetContainer(), Isis::PvlToXmlTranslationManager::GetContainer(), Isis::Cube::hasGroup(), Isis::AutoReg::Parse(), Isis::Cube::putGroup(), Isis::ProcessGroundPolygons::SetStatCubes(), Isis::ControlNet::SetTarget(), Isis::AlphaCube::UpdateGroup(), Isis::PvlObject::validateObject(), and Isis::Pvl::validatePvl().
hasKeyword() [1/3]
bool Isis::PvlObject::hasKeyword (const QString & kname, FindOptions opts) const inherited
See if a keyword is in the current PvlObject, or deeper inside other PvlObjects and Pvlgroups within this one.
Note: This member has the same name as the PvlContainer and hides those implementations, but with the using statement the parents FindKeyword members ar made visible.
Parameters
kname The name of the keyword to look for.
opts The FindOptions option (None or Traverse).
Returns
True if the Keyword exists False otherwise.
References Isis::PvlContainer::begin(), Isis::PvlContainer::end(), Isis::PvlObject::group(), Isis::PvlObject::hasKeyword(), and Isis::PvlObject::None.
Referenced by Isis::ControlPointV0001::ControlPointV0001(), Isis::ControlPointV0002::ControlPointV0002(), Isis::ControlPointV0003::ControlPointV0003(), Isis::CubeTileHandler::CubeTileHandler(), Isis::Blob::Find(), Isis::MosaicAreaTool::fromPvl(), Isis::MosaicControlNetTool::fromPvl(), Isis::MosaicGridTool::fromPvl(), Isis::Image::fromPvl(), Isis::Shape::fromPvl(), Isis::ImageFileListWidget::fromPvl(), Isis::Cube::hasBlob(), Isis::Image::isFootprintable(), Isis::Shape::isFootprintable(), Isis::SpicePosition::LoadCache(), Isis::SpiceRotation::LoadCache(), Isis::SpiceRotation::loadPCFromTable(), Isis::Cube::open(), Isis::Target::radiiGroup(), Isis::ProcessImportVicar::SetVicarFile(), Isis::ProcessExportPds::StandardAllMapping(), Isis::ProcessExportPds::StandardImageImage(), Isis::ProcessExportPds::StandardJP2Image(), Isis::Table::toBlob(), Isis::PvlObject::validateObject(), and Isis::Pvl::validatePvl().
hasKeyword() [2/3]
bool Isis::PvlContainer::hasKeyword (const QString & name) const inherited
Check to see if a keyword exists.
Parameters
name The name of the keyword to check for.
Returns
True if the keyword exists, false if it doesn't.
Referenced by Isis::Latitude::add(), Isis::SerialNumberList::add(), Isis::PvlTranslationTable::AddTable(), Isis::Albedo::Albedo(), Isis::AlbedoAtm::AlbedoAtm(), Isis::AtmosModel::AtmosModel(), Isis::BulletShapeModel::BulletShapeModel(), Isis::BundleObservationSolveSettings::BundleObservationSolveSettings(), Isis::Camera::Camera(), Isis::CameraFactory::CameraVersion(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), IsisAml::CommandLine(), Isis::ControlNetDiff::compareGroups(), Isis::ControlPointV0001::ControlPointV0001(), Isis::ControlPointV0002::ControlPointV0002(), Isis::ControlPointV0003::ControlPointV0003(), Isis::CameraFactory::Create(), Isis::Gui::Create(), Isis::PhotoModelFactory::Create(), Isis::AtmosModelFactory::Create(), Isis::NormModelFactory::Create(), Isis::ShapeModelFactory::create(), Isis::ProcessExportPds4::createUnitMap(), Isis::ControlNetFilter::CubeConvexHullFilter(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::ControlNetFilter::CubeNameExpressionFilter(), Isis::ControlNetFilter::CubeNumPointsFilter(), Isis::DemShape::DemShape(), Isis::PvlToPvlTranslationManager::DoTranslation(), Isis::PvlToXmlTranslationManager::doTranslation(), Isis::EmbreeShapeModel::EmbreeShapeModel(), Isis::Equirectangular::Equirectangular(), Isis::KernelDb::findAll(), Isis::fitsToJson(), Isis::CubeViewport::getBandFilterName(), Isis::UniversalGroundMap::GroundRange(), Isis::Camera::GroundRange(), Isis::Hapke::Hapke(), Isis::PvlTranslationTable::hasInputDefault(), Isis::Spice::hasKernels(), Isis::HiLab::HiLab(), Isis::IdealCamera::IdealCamera(), Isis::Equalization::importStatistics(), Isis::PvlTranslationTable::InputDefault(), Isis::PvlToPvlTranslationManager::InputHasKeyword(), Isis::PvlToXmlTranslationManager::InputHasKeyword(), Isis::PvlToPvlTranslationManager::InputKeyword(), Isis::PvlToXmlTranslationManager::InputKeyword(), Isis::PvlTranslationTable::InputKeywordName(), Isis::PvlTranslationTable::IsAuto(), Isis::PvlTranslationTable::IsOptional(), Isis::LambertConformal::LambertConformal(), Isis::Latitude::Latitude(), Isis::Preference::Load(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LunarLambert::LunarLambert(), Isis::LunarLambertEmpirical::LunarLambertEmpirical(), Isis::RingPlaneProjection::Mapping(), Isis::TProjection::Mapping(), Isis::KernelDb::matches(), Isis::Mercator::Mercator(), Isis::Minnaert::Minnaert(), Isis::MinnaertEmpirical::MinnaertEmpirical(), Isis::Mixed::Mixed(), Isis::Mollweide::Mollweide(), Isis::MoonAlbedo::MoonAlbedo(), Isis::NaifDskShape::NaifDskShape(), Isis::ObliqueCylindrical::ObliqueCylindrical(), Isis::operator<<(), Isis::Orthographic::Orthographic(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::Preference::outputErrorAsPvl(), Isis::PvlTranslationTable::OutputName(), Isis::PvlTranslationTable::OutputPosition(), Isis::AutoReg::Parse(), Isis::GridPolygonSeeder::Parse(), Isis::LimitPolygonSeeder::Parse(), Isis::PolygonSeeder::Parse(), Isis::StripPolygonSeeder::Parse(), Isis::PhotoModel::PhotoModel(), Isis::Planar::Planar(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointEditLockFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::ControlNetFilter::PointMeasurePropertiesFilter(), Isis::ControlNetFilter::PointMeasuresFilter(), Isis::ControlNetFilter::PointNumMeasuresEditLockFilter(), Isis::PointPerspective::PointPerspective(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::ControlNetFilter::PointPropertiesFilter(), Isis::ControlNetFilter::PointResMagnitudeFilter(), Isis::PolarStereographic::PolarStereographic(), Isis::Projection::Projection(), Isis::Target::radiiGroup(), Isis::AutoReg::RegTemplate(), Isis::Preference::reportFileLine(), Isis::RingCylindrical::RingCylindrical(), Isis::RingPlaneProjection::RingPlaneProjection(), Isis::Camera::ringRange(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::Robinson::Robinson(), Isis::ProcessImportFits::setFitsFile(), Isis::ProcessMapMosaic::SetOutputCube(), Isis::ProcessImportFits::setProcessFileStructure(), Isis::ControlNet::SetTarget(), Isis::Shade::Shade(), Isis::ShadeAtm::ShadeAtm(), Isis::SimpleCylindrical::SimpleCylindrical(), Isis::Sinusoidal::Sinusoidal(), Isis::ProcessExportPds::StandardAllMapping(), Isis::ProcessImportFits::standardInstrumentGroup(), Isis::Target::Target(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::Topo::Topo(), Isis::TopoAtm::TopoAtm(), Isis::TProjection::TProjection(), Isis::PvlTranslationTable::Translate(), Isis::PvlToPvlTranslationManager::Translate(), Isis::XmlToPvlTranslationManager::Translate(), Isis::PvlToXmlTranslationManager::Translate(), Isis::ProcessExportPds4::translateBandBinSpectrumBinSet(), Isis::ProcessExportPds4::translateBandBinSpectrumUniform(), Isis::TransverseMercator::TransverseMercator(), Isis::SubArea::UpdateLabel(), Isis::SpectralPlotTool::updateTool(), Isis::PvlContainer::validateAllKeywords(), Isis::PvlObject::validateObject(), Isis::Pvl::validatePvl(), Isis::ControlNetValidMeasure::ValidatePvlDN(), Isis::ControlNetValidMeasure::ValidatePvlEmissionAngle(), Isis::ControlNetValidMeasure::ValidatePvlFromEdge(), Isis::ControlNetValidMeasure::ValidatePvlIncidenceAngle(), Isis::ControlNetValidMeasure::ValidatePvlResidualTolerances(), Isis::ControlNetValidMeasure::ValidatePvlResolution(), and Isis::ControlNetValidMeasure::ValidatePvlShiftTolerances().
hasKeyword() [3/3]
bool Isis::PvlContainer::hasKeyword inherited
Check to see if a keyword exists.
Parameters
name The name of the keyword to check for.
Returns
True if the keyword exists, false if it doesn't.
Referenced by Isis::PvlObject::hasKeyword().
hasObject()
bool Isis::PvlObject::hasObject (const QString & name) const inline inherited
Returns a boolean value based on whether the object exists in the current PvlObject or not.
Parameters
name The name of the object to search for.
Returns
True if the current PvlObject has the specified object, false if it does not.
References Isis::PvlObject::beginObject(), Isis::PvlObject::endObject(), Isis::PvlObject::findObject(), and Isis::PvlContainer::name().
Referenced by Isis::LabelTranslationManager::CreateContainer(), Isis::ProjectionFactory::CreateForCube(), Isis::ProcessExportPds::CreateQubeLabel(), Isis::ProcessExportPds::CreateSpectralQubeLabel(), Isis::KernelDb::findAll(), Isis::MosaicSceneWidget::fromPvl(), Isis::PvlToPvlTranslationManager::GetContainer(), Isis::PvlToXmlTranslationManager::GetContainer(), Isis::Photometry::Photometry(), Isis::Process::PropagateLabels(), Isis::Target::radiiGroup(), Isis::MosaicController::readProject(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::ControlNet::SetTarget(), Isis::ProcessExportPds4::StandardAllMapping(), Isis::ProcessExportPds::StandardAllMapping(), Isis::PvlObject::validateObject(), and Isis::Pvl::validatePvl().
indent()
int Isis::PvlContainer::indent () inline inherited
References Isis::PvlKeyword::indent(), and Isis::PvlContainer::m_name.
Referenced by Isis::operator<<(), and Isis::PvlContainer::setIndent().
isNamed()
bool Isis::PvlContainer::isNamed (const QString & match) const inline inherited
Returns whether the given string is equal to the container name or not.
Parameters
match The string to compare to the name.
Returns
True if the name and string are the same, false if they are not.
References Isis::PvlContainer::m_name, and Isis::PvlKeyword::stringEqual().
Referenced by Isis::SessionLog::AddError(), Isis::Cube::attachSpiceFromIsd(), Isis::Cube::copy(), Isis::Blob::Find(), Isis::KernelDb::findAll(), Isis::Application::formatError(), Isis::Cube::hasBlob(), Isis::IsBlob(), Isis::Image::isFootprintable(), Isis::Shape::isFootprintable(), Isis::RemoveHiBlobs(), Isis::Process::SetOutputCube(), and Isis::Process::WriteHistory().
keywords()
int Isis::PvlContainer::keywords () const inline inherited
Returns the number of keywords contained in the PvlContainer.
Returns
The number of keywords.
References Isis::PvlContainer::m_keywords.
Referenced by Isis::PvlFormat::add(), Isis::PvlTranslationTable::AddTable(), Isis::ControlNetDiff::addTolerances(), Isis::UserInterface::BuildNewCommandLineFromPvl(), Isis::ControlNetDiff::compare(), Isis::ControlNetDiff::compareGroups(), Isis::ControlPointV0001::ControlPointV0001(), Isis::ControlPointV0002::ControlPointV0002(), Isis::ControlPointV0003::ControlPointV0003(), Isis::KernelDb::findAll(), Isis::MosaicSceneWidget::fromPvl(), Isis::ImageImporter::import(), Isis::Equalization::importStatistics(), Isis::Preference::Load(), Isis::KernelDb::matches(), Isis::operator<<(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::BandSpinBox::setBandBin(), Isis::ProcessImportVicar::SetVicarFile(), Isis::PvlGroup::validateGroup(), Isis::PvlObject::validateObject(), Isis::Pvl::validatePvl(), and Isis::PvlContainer::validateRepeatOption().
name()
QString Isis::PvlContainer::name () const inline inherited
Returns the container name.
Returns
The container name.
References Isis::PvlContainer::m_name.
Referenced by Isis::PvlTranslationTable::AddTable(), Isis::ControlNetDiff::addTolerances(), Isis::LabelTranslationManager::Auto(), Isis::PvlToPvlTranslationManager::Auto(), Isis::PvlToXmlTranslationManager::Auto(), Isis::ControlPointV0003::ControlPointV0003(), Isis::Cube::copy(), Isis::CorrelationMatrix::CorrelationMatrix(), Isis::ProcessExportPds4::createUnitMap(), Isis::Cube::deleteBlob(), Isis::PvlObject::deleteGroup(), Isis::PvlObject::deleteObject(), Isis::PvlToXmlTranslationManager::doTranslation(), Isis::PvlObject::findGroup(), Isis::PvlObject::findObject(), Isis::ImageFileListWidget::fromPvl(), Isis::PvlObject::hasGroup(), Isis::PvlObject::hasObject(), Isis::Preference::Load(), Isis::PvlContainer::operator-=(), Isis::operator<<(), Isis::PvlGroup::operator==(), Isis::PvlObject::operator==(), Isis::PvlContainer::operator[](), Isis::Cube::putGroup(), Isis::PvlObject::PvlObject(), Isis::BandSpinBox::setBandBin(), Isis::PvlContainer::setName(), Isis::Process::SetOutputCube(), Isis::OverlapStatistics::toPvl(), Isis::PvlGroup::validateGroup(), Isis::PvlObject::validateObject(), Isis::Pvl::validatePvl(), and Isis::Blob::Write().
nameKeyword() [1/2]
PvlKeyword& Isis::PvlContainer::nameKeyword () inline inherited
References Isis::PvlContainer::m_name.
Referenced by Isis::BundleObservationSolveSettings::BundleObservationSolveSettings().
nameKeyword() [2/2]
const PvlKeyword& Isis::PvlContainer::nameKeyword () const inline inherited
References Isis::PvlContainer::m_name.
object() [1/2]
PvlObject & Isis::PvlObject::object (const int index) inherited
Return the object at the specified index.
Parameters
index The index of the object.
Returns
The PvlObject sought for.
Exceptions
IException::Programmer
References _FILEINFO_, Isis::Message::ArraySubscriptNotInRange(), and Isis::IException::Programmer.
Referenced by Isis::Cube::attachSpiceFromIsd(), Isis::ControlNetDiff::compare(), Isis::Cube::copy(), Isis::ProcessExportPds4::createUnitMap(), Isis::Cube::deleteBlob(), Isis::Blob::Find(), Isis::KernelDb::findAll(), Isis::ImageFileListWidget::fromPvl(), Isis::Cube::hasBlob(), Isis::Image::isFootprintable(), Isis::Shape::isFootprintable(), Isis::Process::PropagateTables(), Isis::RemoveHiBlobs(), Isis::History::ReturnHist(), Isis::Process::SetOutputCube(), Isis::PvlObject::validateObject(), Isis::Pvl::validatePvl(), Isis::Blob::Write(), and Isis::Process::WriteHistory().
object() [2/2]
const PvlObject & Isis::PvlObject::object (const int index) const inherited
Return the object at the specified index.
Parameters
index The index of the object.
Returns
The PvlObject sought for.
Exceptions
IException::Programmer
References _FILEINFO_, Isis::Message::ArraySubscriptNotInRange(), and Isis::IException::Programmer.
objects()
int Isis::PvlObject::objects () const inline inherited
Returns the number of objects.
Returns
The number of objects.
Referenced by Isis::ProcessExportPds4::createUnitMap(), Isis::Blob::Find(), Isis::KernelDb::findAll(), Isis::ImageFileListWidget::fromPvl(), Isis::Image::isFootprintable(), Isis::Shape::isFootprintable(), Isis::Process::PropagateTables(), Isis::RemoveHiBlobs(), Isis::Process::SetOutputCube(), Isis::PvlObject::validateObject(), Isis::Pvl::validatePvl(), Isis::Blob::Write(), and Isis::Process::WriteHistory().
operator+=() [1/4]
void Isis::PvlObject::operator+= (const Isis::PvlGroup & group) inline inherited
References Isis::PvlObject::addGroup(), and Isis::PvlObject::group().
operator+=() [2/4]
void Isis::PvlObject::operator+= (const Isis::PvlObject & obj) inline inherited
References Isis::PvlObject::addObject().
operator+=() [3/4]
void Isis::PvlContainer::operator+= (const PvlKeyword & keyword) inline inherited
When you use the += operator with a PvlKeyword, it will call the addKeyword() method.
Parameters
keyword The PvlKeyword to be added.
References Isis::PvlContainer::addKeyword().
operator+=() [4/4]
void Isis::PvlContainer::operator+= inline inherited
When you use the += operator with a PvlKeyword, it will call the addKeyword() method.
Parameters
keyword The PvlKeyword to be added.
operator-=() [1/2]
void Isis::PvlContainer::operator-= (const PvlKeyword & key) inline inherited
When you use the -= operator with a PvlKeyword object, it will call the deleteKeyword() method.
Parameters
key The PvlKeyword object to remove.
References Isis::PvlContainer::deleteKeyword(), and Isis::PvlKeyword::name().
operator-=() [2/2]
void Isis::PvlContainer::operator-= (const QString & name) inline inherited
When you use the -= operator with a (string) name, it will call the deleteKeyword() method.
Parameters
name The name of the keyword to remove.
References Isis::PvlContainer::deleteKeyword(), and Isis::PvlContainer::name().
operator==()
bool Isis::PvlObject::operator== (const PvlObject & object) const inline inherited
Compares two PvlObjects.
Returns a boolean value based on the StringEqual() method.
Parameters
object The PvlObject to compare.
Returns
True if they are equal, false if not.
References Isis::PvlContainer::name(), and Isis::PvlKeyword::stringEqual().
operator[]() [1/6]
PvlKeyword& Isis::PvlContainer::operator[] (const char * name) inline inherited
When you use the [] operator with a (char) name, it will call the findKeyword() method.
Parameters
name The name of the keyword to find.
References Isis::PvlContainer::name(), and Isis::PvlContainer::operator[]().
operator[]() [2/6]
PvlKeyword Isis::PvlContainer::operator[] (const char * name) const inline inherited
When you use the [] operator with a (char) name, it will call the findKeyword() method.
Parameters
name The name of the keyword to find.
References Isis::PvlContainer::name(), and Isis::PvlContainer::operator[]().
operator[]() [3/6]
PvlKeyword & Isis::PvlContainer::operator[] (const int index) inherited
Return the PvlKeyword object at the specified index.
Parameters
index The index to use.
Returns
The PvlKeyword at the specified index.
Exceptions
iException::Message The index is out of bounds.
References _FILEINFO_, and Isis::Message::ArraySubscriptNotInRange().
operator[]() [4/6]
const Isis::PvlKeyword & Isis::PvlContainer::operator[] (const int index) const inherited
Return the PvlKeyword object at the specified index.
Parameters
index The index to use.
Returns
The PvlKeyword at the specified index.
Exceptions
iException::Message The index is out of bounds.
References _FILEINFO_, and Isis::Message::ArraySubscriptNotInRange().
operator[]() [5/6]
PvlKeyword& Isis::PvlContainer::operator[] (const QString & name) inline inherited
When you use the [] operator with a (string) name, it will call the findKeyword() method.
Parameters
name The name of the keyword to find.
References Isis::PvlContainer::findKeyword(), and Isis::PvlContainer::name().
Referenced by Isis::PvlContainer::operator[]().
operator[]() [6/6]
const PvlKeyword& Isis::PvlContainer::operator[] (const QString & name) const inline inherited
When you use the [] operator with a (string) name, it will call the findKeyword() method.
Parameters
name The name of the keyword to find.
References Isis::PvlContainer::findKeyword(), and Isis::PvlContainer::name().
read()
void Isis::Pvl::read (const QString & file) inherited
Loads PVL information from a stream.
Parameters
file A file containing PVL information
Exceptions
Isis::iException::Io
References _FILEINFO_, Isis::FileName::expanded(), Isis::Message::FileOpen(), Isis::IException::Io, Isis::PvlContainer::m_filename, and Isis::IException::Unknown.
Referenced by Isis::PvlTranslationTable::AddTable(), Isis::InterestOperatorFactory::Create(), Isis::AutoRegFactory::Create(), Isis::PhotoModelFactory::Create(), Isis::PolygonSeederFactory::Create(), Isis::AtmosModelFactory::Create(), Isis::NormModelFactory::Create(), Isis::Preference::Load(), Isis::Pvl::Pvl(), Isis::pvlToJSON(), Isis::Blob::Read(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::UserInterface::SaveHistory(), Isis::ProcessMapMosaic::SetOutputCube(), Isis::ProcessImportPds::SetPdsFile(), and Isis::ProcessExportPds4::translateUnits().
setFileName()
void Isis::PvlContainer::setFileName (const QString & filename) inline protected inherited
Sets the filename to the specified string.
Parameters
filename The new filename to use.
References Isis::PvlContainer::m_filename.
setFormat()
void Isis::PvlContainer::setFormat (PvlFormat * format) inline inherited
References Isis::PvlContainer::format(), Isis::PvlContainer::m_name, and Isis::PvlKeyword::setFormat().
Referenced by Isis::Pvl::append(), Isis::operator<<(), and Isis::Pvl::write().
setFormatTemplate() [1/3]
void Isis::Pvl::setFormatTemplate (const QString & filename) inherited
References Isis::PvlContainer::m_formatTemplate.
setFormatTemplate() [2/3]
void Isis::Pvl::setFormatTemplate (Isis::Pvl & temp) inherited
References Isis::PvlContainer::m_formatTemplate, and Isis::PvlContainer::setFormatTemplate().
setFormatTemplate() [3/3]
void Isis::PvlContainer::setFormatTemplate (PvlContainer & ref) inline inherited
References Isis::PvlContainer::m_formatTemplate.
Referenced by Isis::Pvl::setFormatTemplate().
setIndent()
void Isis::PvlContainer::setIndent (int indent) inline inherited
References Isis::PvlContainer::indent(), Isis::PvlContainer::m_name, and Isis::PvlKeyword::setIndent().
Referenced by Isis::operator<<().
setName()
void Isis::PvlContainer::setName (const QString & name) inline inherited
Set the name of the container.
References Isis::PvlContainer::m_name, Isis::PvlContainer::name(), and Isis::PvlKeyword::setValue().
Referenced by Isis::fitsToJson(), Isis::MosaicSceneWidget::save(), and Isis::MosaicSceneWidget::toPvl().
setTerminator()
void Isis::Pvl::setTerminator (const QString & term) inline inherited
Sets the terminator used to signify the end of the PVL informationDefaults to "END".
Parameters
term The user-defined terminator
Referenced by Isis::CameraStatistics::toPvl().
terminator()
QString Isis::Pvl::terminator () const inline inherited
Returns the terminator used to signify the end of the PVL informationDefaults to "END".
Returns
The terminator used by the Pvl object.
Referenced by Isis::Pvl::append(), and Isis::Pvl::write().
type()
QString Isis::PvlContainer::type () const inline inherited
Returns the container type.
Returns
The container type.
References Isis::PvlContainer::m_name, and Isis::PvlKeyword::name().
Referenced by Isis::PvlObject::deleteGroup(), Isis::PvlObject::deleteObject(), and Isis::operator<<().
validateAllKeywords()
void Isis::PvlContainer::validateAllKeywords (PvlContainer & pPvlCont) protected inherited
Validate All the Keywords in a Container comparing with the Template.
Validate all the PvlKeywords in this container.
Author
Sharmila Prasad (9/24/2010)
Parameters
pPvlCont - Container to be Validated
History:
2010-10-18 Sharmila Prasad - Added options "Type", "Range", "Value" for the keyword validation
References _FILEINFO_, Isis::PvlContainer::deleteKeyword(), Isis::PvlContainer::findKeyword(), Isis::PvlContainer::hasKeyword(), Isis::PvlKeyword::name(), and Isis::PvlKeyword::validateKeyword().
Referenced by Isis::PvlGroup::validateGroup(), Isis::PvlObject::validateObject(), and Isis::Pvl::validatePvl().
validateObject()
void Isis::PvlObject::validateObject (PvlObject & pPvlObj) inherited
Validate Object.
Validate a PvlObject, comparing against corresponding Template PvlObject.
If the Objects are nested, it will recursively validate the PvlObject.
Template PvlObject has the format: Object = (objectName, optional/required)
Author
Sharmila Prasad (9/22/2010)
Parameters
pvlObj- PvlObject to be validated
References _FILEINFO_, Isis::PvlObject::deleteGroup(), Isis::PvlObject::deleteObject(), Isis::PvlObject::findGroup(), Isis::PvlObject::findKeyword(), Isis::PvlContainer::findKeyword(), Isis::PvlObject::findObject(), Isis::PvlObject::group(), Isis::PvlObject::groups(), Isis::PvlObject::hasGroup(), Isis::PvlObject::hasKeyword(), Isis::PvlContainer::hasKeyword(), Isis::PvlObject::hasObject(), Isis::PvlContainer::keywords(), Isis::PvlContainer::name(), Isis::PvlObject::object(), Isis::PvlObject::objects(), Isis::IException::User, Isis::PvlContainer::validateAllKeywords(), Isis::PvlGroup::validateGroup(), and Isis::PvlObject::validateObject().
Referenced by Isis::PvlObject::validateObject(), and Isis::Pvl::validatePvl().
validatePvl()
void Isis::Pvl::validatePvl (const Pvl & pPvl, Pvl & pPvlResults) inherited
Validate a Pvl with the Template Pvl.
Validate a Pvl, comparing against corresponding Template Pvl It validates all the Objects, Groups and Keywords.
Author
Sharmila Prasad (9/22/2010)
Parameters
pPvl - User Pvl to be validated
pPvlResults - Contains the unvalidated Pvl
References _FILEINFO_, Isis::PvlObject::deleteGroup(), Isis::PvlObject::deleteObject(), Isis::PvlObject::findGroup(), Isis::PvlObject::findKeyword(), Isis::PvlContainer::findKeyword(), Isis::PvlObject::findObject(), Isis::PvlObject::group(), Isis::PvlObject::groups(), Isis::PvlObject::hasGroup(), Isis::PvlObject::hasKeyword(), Isis::PvlContainer::hasKeyword(), Isis::PvlObject::hasObject(), Isis::PvlContainer::keywords(), Isis::PvlContainer::name(), Isis::PvlObject::object(), Isis::PvlObject::objects(), Isis::Pvl::Pvl(), Isis::IException::User, Isis::PvlContainer::validateAllKeywords(), Isis::PvlGroup::validateGroup(), and Isis::PvlObject::validateObject().
validateRepeatOption()
void Isis::PvlContainer::validateRepeatOption (PvlKeyword & pPvlTmplKwrd, PvlContainer & pPvlCont) protected inherited
Validate the Repeat Option for a Keyword.
Validate Repeat Option in the Template Group.
This option indicates that a particular keyname can be repeated several times
Author
Sharmila Prasad (9/24/2010)
Parameters
pPvlTmplKwrd - Template Keyword wit
pPvlCont - Container with all the Keywords
History:
2010-10-18 Sharmila Prasad - Added option "Type" for the keyword validation
References Isis::PvlContainer::deleteKeyword(), Isis::PvlContainer::keywords(), Isis::PvlKeyword::name(), and Isis::PvlKeyword::validateKeyword().
write()
void Isis::Pvl::write (const QString & file) inherited
Opens and writes PVL information to a file and handles the end of line sequence.
Parameters
file Name of the file to create. The method will overwrite any existing file.
Exceptions
Isis::iException::Io
References _FILEINFO_, Isis::FileName::expanded(), Isis::Message::FileCreate(), Isis::PvlContainer::format(), Isis::PvlFormat::formatEOL(), Isis::IException::Io, Isis::PvlContainer::setFormat(), and Isis::Pvl::terminator().
Referenced by Isis::Stretch::Save(), Isis::UserInterface::SaveHistory(), Isis::FileTool::saveInfo(), Isis::MosaicController::saveProject(), Isis::SessionLog::Write(), Isis::Blob::Write(), and Isis::ControlNet::Write().
Member Data Documentation
m_filename
QString Isis::PvlContainer::m_filename protected inherited
This contains the filename used to initialize the pvl object.
If the object was not initialized using a filename the string is empty.
Referenced by Isis::PvlObject::deleteGroup(), Isis::PvlObject::deleteObject(), Isis::PvlContainer::fileName(), Isis::PvlObject::findGroup(), Isis::PvlObject::findKeyword(), Isis::PvlObject::findObject(), Isis::PvlContainer::operator=(), Isis::Pvl::read(), and Isis::PvlContainer::setFileName().
m_formatTemplate
PvlContainer* Isis::PvlContainer::m_formatTemplate protected inherited
Referenced by Isis::PvlContainer::formatTemplate(), Isis::PvlContainer::hasFormatTemplate(), Isis::PvlContainer::operator=(), Isis::Pvl::setFormatTemplate(), Isis::PvlContainer::setFormatTemplate(), and Isis::Pvl::~Pvl().
m_keywords
QList<PvlKeyword> Isis::PvlContainer::m_keywords protected inherited
This is the vector of PvlKeywords the container is holding.
Referenced by Isis::PvlContainer::begin(), Isis::PvlContainer::clear(), Isis::PvlContainer::end(), Isis::PvlContainer::keywords(), and Isis::PvlContainer::operator=().
m_name
PvlKeyword Isis::PvlContainer::m_name protected inherited
This is the name keyword.
Referenced by Isis::PvlContainer::addComment(), Isis::PvlContainer::comment(), Isis::PvlContainer::comments(), Isis::PvlContainer::format(), Isis::PvlContainer::indent(), Isis::PvlContainer::isNamed(), Isis::PvlContainer::name(), Isis::PvlContainer::nameKeyword(), Isis::PvlContainer::operator=(), Isis::PvlContainer::setFormat(), Isis::PvlContainer::setIndent(), Isis::PvlContainer::setName(), and Isis::PvlContainer::type().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Plugin/Plugin.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Plugin/Plugin.cpp