Isis Developer Reference: Isis::PaletteWindow Class Reference
Isis::PaletteWindow Class Reference
#include <PaletteWindow.h>
Public Member Functions
PaletteWindow (QWidget *parent=0)
PaletteWindow constructor.
void closeEvent (QCloseEvent *event)
This method is overridden so that we can be sure to write the current settings of the Palette window.
void hideEvent (QHideEvent *event)
This method ensure that the settings get written even if the Palette window was only hidden, not closed.
void readSettings ()
This method is called from the constructor so that when the Palette window is created, it know's it's size and location.
void writeSettings ()
This method is called when the Palette window is closed or hidden to write the size and location settings to a config file in the user's home directory.
Protected Member Functions
bool eventFilter (QObject *o, QEvent *e)
This event filter is installed on the parent of this window.
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
PaletteWindow()
Isis::PaletteWindow::PaletteWindow (QWidget * parent = 0)
PaletteWindow constructor.
Parameters
parent
References readSettings().
Member Function Documentation
closeEvent()
void Isis::PaletteWindow::closeEvent (QCloseEvent * event)
This method is overridden so that we can be sure to write the current settings of the Palette window.
Parameters
event
References writeSettings().
eventFilter()
bool Isis::PaletteWindow::eventFilter (QObject * o, QEvent * e) protected
This event filter is installed on the parent of this window.
When the user closes the main window of the application, the Palette windows will write their settings even though they did not receive the close event themselves.
Parameters
o
e
Returns
bool
References writeSettings().
hideEvent()
void Isis::PaletteWindow::hideEvent (QHideEvent * event)
This method ensure that the settings get written even if the Palette window was only hidden, not closed.
Parameters
event
References writeSettings().
readSettings()
void Isis::PaletteWindow::readSettings ()
This method is called from the constructor so that when the Palette window is created, it know's it's size and location.
References Isis::FileName::expanded().
Referenced by PaletteWindow().
writeSettings()
void Isis::PaletteWindow::writeSettings ()
This method is called when the Palette window is closed or hidden to write the size and location settings to a config file in the user's home directory.
References Isis::FileName::expanded().
Referenced by closeEvent(), eventFilter(), and hideEvent().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/PaletteWindow/PaletteWindow.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/PaletteWindow/PaletteWindow.cpp