Isis Developer Reference: Isis::PointParentItem Class Reference
Isis::PointParentItem Class Reference abstract
Tree item that is a parent and represents a control point.
#include <PointParentItem.h>
Public Types
enum Column {
Id = 0 , PointType = 1 , ChooserName = 2 , DateTime = 3 ,
EditLock = 4 , Ignored = 5 , Reference = 6 , AdjustedSPCoord1 = 7 ,
AdjustedSPCoord2 = 8 , AdjustedSPCoord3 = 9 , AdjustedSPCoord1Sigma = 10 , AdjustedSPCoord2Sigma = 11 ,
AdjustedSPCoord3Sigma = 12 , APrioriSPCoord1 = 13 , APrioriSPCoord2 = 14 , APrioriSPCoord3 = 15 ,
APrioriSPCoord1Sigma = 16 , APrioriSPCoord2Sigma = 17 , APrioriSPCoord3Sigma = 18 , APrioriSPSource = 19 ,
APrioriSPSourceFile = 20 , APrioriRadiusSource = 21 , APrioriRadiusSourceFile = 22 , JigsawRejected = 23
}
enum InternalPointerType { None , Point , Measure , ImageAndNet }
Public Member Functions
PointParentItem (ControlPoint *cp, int avgCharWidth, AbstractTreeItem *parent=0)
virtual ~PointParentItem ()
void addChild (AbstractTreeItem *child)
QVariant getData () const
QVariant getData (QString columnTitle) const
void setData (QString const &columnTitle, QString const &newData)
bool isDataEditable (QString columnTitle) const
void deleteSource ()
InternalPointerType getPointerType () const
void * getPointer () const
bool hasPoint (ControlPoint *) const
AbstractTreeItem * parent () const
void setParent (AbstractTreeItem *newParent)
int row () const
virtual QList< AbstractTreeItem * > getChildren () const =0
virtual AbstractTreeItem * childAt (int row) const =0
virtual int childCount () const =0
virtual AbstractTreeItem * getFirstVisibleChild () const =0
virtual AbstractTreeItem * getLastVisibleChild () const =0
virtual int indexOf (AbstractTreeItem *child) const =0
virtual void setFirstVisibleChild (AbstractTreeItem *child)=0
virtual void setLastVisibleChild (AbstractTreeItem *child)=0
virtual QString getFormattedData () const
virtual QString getFormattedData (QString columnTitle) const
virtual bool hasMeasure (ControlMeasure *) const
virtual bool hasImage (QString imageSerial) const
virtual AbstractTreeItem * getNextVisiblePeer () const
virtual void setNextVisiblePeer (AbstractTreeItem *next)
virtual void setExpanded (bool newState)
virtual bool isExpanded () const
virtual void setSelected (bool newState)
virtual void setSelectable (bool newSelectable)
virtual bool isSelected () const
virtual bool isSelectable () const
virtual void setVisible (bool newState)
virtual bool isVisible () const
virtual int getDataWidth () const
virtual int getDepth () const
virtual void setLastVisibleFilteredItem (AbstractTreeItem *item)
virtual const AbstractTreeItem * getLastVisibleFilteredItem () const
virtual AbstractTreeItem * childAt (int row) const
virtual QList< AbstractTreeItem * > getChildren () const
virtual AbstractTreeItem * getFirstVisibleChild () const
virtual AbstractTreeItem * getLastVisibleChild () const
virtual int indexOf (AbstractTreeItem *child) const
virtual int childCount () const
virtual void setFirstVisibleChild (AbstractTreeItem *child)
virtual void setLastVisibleChild (AbstractTreeItem *child)
Static Public Member Functions
static QString getColumnName (Column)
static Column getColumn (QString)
static TableColumnList * createColumns ()
static void resetColumnHeaders (TableColumnList *columns)
Resets pertinent point table column headers based on the active point coordinate display type (Lat/Lon/Radius or XYZ).
Static Public Attributes
static const int COLS = 24
Protected Member Functions
virtual void sourceDeleted ()
virtual void calcDataWidth (int avgCharWidth)
Static Protected Member Functions
static double catchNull (QString)
static QString catchNull (QVariant)
Detailed Description
Tree item that is a parent and represents a control point.
This class represents a parent item in a tree structure that holds control point data. It can have children items added to it, but they must be of type MeasureLeafItem.
Author
????-??-?? Eric Hyer
Member Enumeration Documentation
Column
enum Isis::AbstractPointItem::Column inherited
Enumerator
Id
PointType
ChooserName
DateTime
EditLock
Ignored
Reference
AdjustedSPCoord1
AdjustedSPCoord2
AdjustedSPCoord3
AdjustedSPCoord1Sigma
AdjustedSPCoord2Sigma
AdjustedSPCoord3Sigma
APrioriSPCoord1
APrioriSPCoord2
APrioriSPCoord3
APrioriSPCoord1Sigma
APrioriSPCoord2Sigma
APrioriSPCoord3Sigma
APrioriSPSource
APrioriSPSourceFile
APrioriRadiusSource
APrioriRadiusSourceFile
JigsawRejected
InternalPointerType
enum Isis::AbstractTreeItem::InternalPointerType inherited
Enumerator
None
Point
Measure
ImageAndNet
Constructor & Destructor Documentation
PointParentItem()
Isis::PointParentItem::PointParentItem (ControlPoint * cp, int avgCharWidth, AbstractTreeItem * parent = 0)
~PointParentItem()
Isis::PointParentItem::~PointParentItem () virtual
Member Function Documentation
addChild()
void Isis::PointParentItem::addChild (AbstractTreeItem * child) virtual
Reimplemented from Isis::AbstractParentItem.
References Isis::AbstractParentItem::addChild().
calcDataWidth()
void Isis::AbstractTreeItem::calcDataWidth (int avgCharWidth) protected virtual inherited
References _FILEINFO_, Isis::AbstractTreeItem::getFormattedData(), and Isis::IException::Programmer.
Referenced by Isis::AbstractImageItem::AbstractImageItem(), Isis::AbstractMeasureItem::AbstractMeasureItem(), Isis::AbstractPointItem::AbstractPointItem(), and Isis::BusyLeafItem::BusyLeafItem().
catchNull() [1/2]
double Isis::AbstractTreeItem::catchNull (QString str) static protected inherited
References Isis::Null.
Referenced by Isis::AbstractTreeItem::getFormattedData(), Isis::AbstractMeasureItem::setData(), and Isis::AbstractPointItem::setData().
catchNull() [2/2]
QString Isis::AbstractTreeItem::catchNull (QVariant data) static protected inherited
References Isis::Double, and Isis::Null.
childAt() [1/2]
AbstractTreeItem * Isis::AbstractParentItem::childAt (int row) const virtual inherited
Implements Isis::AbstractTreeItem.
References Isis::AbstractTreeItem::row().
childAt() [2/2]
virtual AbstractTreeItem* Isis::AbstractTreeItem::childAt (int row) const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::AbstractTreeItem::hasImage(), Isis::AbstractTreeItem::hasMeasure(), and Isis::AbstractTreeItem::hasPoint().
childCount() [1/2]
int Isis::AbstractParentItem::childCount () const virtual inherited
Implements Isis::AbstractTreeItem.
Referenced by Isis::AbstractTreeModel::getItems(), and Isis::AbstractTreeModel::getTopLevelItemCount().
childCount() [2/2]
virtual int Isis::AbstractTreeItem::childCount () const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::AbstractTreeItem::hasImage(), Isis::AbstractTreeItem::hasMeasure(), and Isis::AbstractTreeItem::hasPoint().
createColumns()
TableColumnList * Isis::AbstractPointItem::createColumns () static inherited
References Isis::AbstractPointItem::AdjustedSPCoord1, Isis::AbstractPointItem::AdjustedSPCoord1Sigma, Isis::AbstractPointItem::AdjustedSPCoord2, Isis::AbstractPointItem::AdjustedSPCoord2Sigma, Isis::AbstractPointItem::AdjustedSPCoord3, Isis::AbstractPointItem::AdjustedSPCoord3Sigma, Isis::TableColumnList::append(), Isis::AbstractPointItem::APrioriRadiusSource, Isis::AbstractPointItem::APrioriRadiusSourceFile, Isis::AbstractPointItem::APrioriSPCoord1, Isis::AbstractPointItem::APrioriSPCoord1Sigma, Isis::AbstractPointItem::APrioriSPCoord2, Isis::AbstractPointItem::APrioriSPCoord2Sigma, Isis::AbstractPointItem::APrioriSPCoord3, Isis::AbstractPointItem::APrioriSPCoord3Sigma, Isis::AbstractPointItem::APrioriSPSource, Isis::AbstractPointItem::APrioriSPSourceFile, Isis::AbstractPointItem::ChooserName, Isis::AbstractPointItem::DateTime, Isis::AbstractPointItem::EditLock, Isis::AbstractPointItem::getColumnName(), Isis::AbstractPointItem::Id, Isis::AbstractPointItem::Ignored, Isis::AbstractPointItem::JigsawRejected, Isis::AbstractPointItem::PointType, and Isis::AbstractPointItem::Reference.
Referenced by Isis::PointTableModel::createColumns().
deleteSource()
void Isis::AbstractPointItem::deleteSource () virtual inherited
Implements Isis::AbstractTreeItem.
References _FILEINFO_, Isis::ControlNet::DeletePoint(), Isis::AbstractTreeItem::getFormattedData(), Isis::ControlPoint::GetNumLockedMeasures(), Isis::ControlPoint::IsEditLocked(), Isis::ControlPoint::Parent(), and Isis::IException::User.
getChildren() [1/2]
QList< AbstractTreeItem * > Isis::AbstractParentItem::getChildren () const virtual inherited
Implements Isis::AbstractTreeItem.
Referenced by Isis::AbstractTreeModel::applyFilter().
getChildren() [2/2]
virtual QList< AbstractTreeItem * > Isis::AbstractTreeItem::getChildren () const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::TableViewContent::mouseMoveEvent(), Isis::TableViewContent::mousePressEvent(), and Isis::TreeViewContent::mousePressEvent().
getColumn()
AbstractPointItem::Column Isis::AbstractPointItem::getColumn (QString columnTitle) static inherited
References _FILEINFO_, Isis::AbstractPointItem::COLS, Isis::AbstractPointItem::getColumnName(), and Isis::IException::Programmer.
Referenced by Isis::AbstractPointItem::getData(), Isis::PointTableModel::getPointWarningMessage(), Isis::PointTableDelegate::getWidget(), Isis::AbstractPointItem::isDataEditable(), Isis::PointTableDelegate::readData(), Isis::PointTableDelegate::saveData(), and Isis::AbstractPointItem::setData().
getColumnName()
QString Isis::AbstractPointItem::getColumnName (Column col) static inherited
References Isis::AbstractPointItem::AdjustedSPCoord1, Isis::AbstractPointItem::AdjustedSPCoord1Sigma, Isis::AbstractPointItem::AdjustedSPCoord2, Isis::AbstractPointItem::AdjustedSPCoord2Sigma, Isis::AbstractPointItem::AdjustedSPCoord3, Isis::AbstractPointItem::AdjustedSPCoord3Sigma, Isis::AbstractPointItem::APrioriRadiusSource, Isis::AbstractPointItem::APrioriRadiusSourceFile, Isis::AbstractPointItem::APrioriSPCoord1, Isis::AbstractPointItem::APrioriSPCoord1Sigma, Isis::AbstractPointItem::APrioriSPCoord2, Isis::AbstractPointItem::APrioriSPCoord2Sigma, Isis::AbstractPointItem::APrioriSPCoord3, Isis::AbstractPointItem::APrioriSPCoord3Sigma, Isis::AbstractPointItem::APrioriSPSource, Isis::AbstractPointItem::APrioriSPSourceFile, Isis::AbstractPointItem::ChooserName, Isis::AbstractPointItem::DateTime, Isis::AbstractPointItem::EditLock, Isis::CnetDisplayProperties::getInstance(), Isis::AbstractPointItem::Id, Isis::AbstractPointItem::Ignored, Isis::AbstractPointItem::JigsawRejected, Isis::CnetDisplayProperties::LatLonRadius, Isis::AbstractPointItem::PointType, and Isis::AbstractPointItem::Reference.
Referenced by Isis::AbstractPointItem::createColumns(), Isis::AbstractPointItem::getColumn(), Isis::AbstractPointItem::getData(), Isis::CnetEditorWidget::readSettings(), Isis::AbstractPointItem::resetColumnHeaders(), and Isis::CnetEditorWidget::writeSettings().
getData() [1/2]
QVariant Isis::AbstractPointItem::getData () const virtual inherited
Implements Isis::AbstractTreeItem.
References Isis::AbstractPointItem::getColumnName(), and Isis::AbstractPointItem::Id.
getData() [2/2]
QVariant Isis::AbstractPointItem::getData (QString columnTitle) const virtual inherited
Implements Isis::AbstractTreeItem.
References Isis::AbstractPointItem::AdjustedSPCoord1, Isis::AbstractPointItem::AdjustedSPCoord1Sigma, Isis::AbstractPointItem::AdjustedSPCoord2, Isis::AbstractPointItem::AdjustedSPCoord2Sigma, Isis::AbstractPointItem::AdjustedSPCoord3, Isis::AbstractPointItem::AdjustedSPCoord3Sigma, Isis::AbstractPointItem::APrioriRadiusSource, Isis::AbstractPointItem::APrioriRadiusSourceFile, Isis::AbstractPointItem::APrioriSPCoord1, Isis::AbstractPointItem::APrioriSPCoord1Sigma, Isis::AbstractPointItem::APrioriSPCoord2, Isis::AbstractPointItem::APrioriSPCoord2Sigma, Isis::AbstractPointItem::APrioriSPCoord3, Isis::AbstractPointItem::APrioriSPCoord3Sigma, Isis::AbstractPointItem::APrioriSPSource, Isis::AbstractPointItem::APrioriSPSourceFile, Isis::AbstractPointItem::ChooserName, Isis::AbstractPointItem::DateTime, Isis::Angle::degrees(), Isis::AbstractPointItem::EditLock, Isis::ControlPoint::GetAdjustedSurfacePoint(), Isis::ControlPoint::GetAprioriRadiusSourceFile(), Isis::ControlPoint::GetAprioriSurfacePoint(), Isis::ControlPoint::GetAprioriSurfacePointSourceFile(), Isis::ControlPoint::GetChooserName(), Isis::AbstractPointItem::getColumn(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::ControlPoint::GetDateTime(), Isis::ControlPoint::GetId(), Isis::CnetDisplayProperties::getInstance(), Isis::SurfacePoint::GetLatitude(), Isis::SurfacePoint::GetLatSigmaDistance(), Isis::SurfacePoint::GetLocalRadius(), Isis::SurfacePoint::GetLocalRadiusSigma(), Isis::SurfacePoint::GetLongitude(), Isis::SurfacePoint::GetLonSigmaDistance(), Isis::ControlPoint::GetNumMeasures(), Isis::ControlPoint::GetPointTypeString(), Isis::ControlPoint::GetRadiusSourceString(), Isis::ControlPoint::GetRefMeasure(), Isis::ControlPoint::GetSurfacePointSourceString(), Isis::SurfacePoint::GetX(), Isis::SurfacePoint::GetXSigma(), Isis::SurfacePoint::GetY(), Isis::SurfacePoint::GetYSigma(), Isis::SurfacePoint::GetZ(), Isis::SurfacePoint::GetZSigma(), Isis::AbstractPointItem::Id, Isis::AbstractPointItem::Ignored, Isis::ControlPoint::IsEditLocked(), Isis::ControlPoint::IsIgnored(), Isis::ControlPoint::IsRejected(), Isis::AbstractPointItem::JigsawRejected, Isis::CnetDisplayProperties::LatLonRadius, Isis::Displacement::meters(), Isis::Distance::meters(), Isis::AbstractPointItem::PointType, and Isis::AbstractPointItem::Reference.
getDataWidth()
int Isis::AbstractTreeItem::getDataWidth () const virtual inherited
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by Isis::AbstractTreeModel::getVisibleSize().
getDepth()
int Isis::AbstractTreeItem::getDepth () const virtual inherited
References Isis::AbstractTreeItem::parent().
Referenced by Isis::AbstractTreeModel::getVisibleSize().
getFirstVisibleChild() [1/2]
AbstractTreeItem * Isis::AbstractParentItem::getFirstVisibleChild () const virtual inherited
Implements Isis::AbstractTreeItem.
Referenced by Isis::AbstractTreeModel::getItems(), Isis::AbstractTreeModel::getSelectedItems(), Isis::AbstractTreeModel::getVisibleItemCount(), Isis::AbstractTreeModel::getVisibleSize(), Isis::AbstractTreeModel::getVisibleTopLevelItemCount(), and Isis::AbstractTreeModel::indexOfVisibleItem().
getFirstVisibleChild() [2/2]
virtual AbstractTreeItem* Isis::AbstractTreeItem::getFirstVisibleChild () const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::TreeViewContent::mouseMoveEvent(), and Isis::TreeViewContent::mousePressEvent().
getFormattedData() [1/2]
QString Isis::AbstractTreeItem::getFormattedData () const virtual inherited
References Isis::AbstractTreeItem::catchNull(), and Isis::AbstractTreeItem::getData().
Referenced by Isis::AbstractTreeItem::calcDataWidth(), Isis::AbstractMeasureItem::deleteSource(), Isis::AbstractPointItem::deleteSource(), Isis::MeasureTableModel::getMeasureWarningMessage(), Isis::PointTableModel::getPointWarningMessage(), Isis::MeasureTableDelegate::readData(), and Isis::PointTableDelegate::readData().
getFormattedData() [2/2]
QString Isis::AbstractTreeItem::getFormattedData (QString columnTitle) const virtual inherited
References Isis::AbstractTreeItem::catchNull(), and Isis::AbstractTreeItem::getData().
getLastVisibleChild() [1/2]
AbstractTreeItem * Isis::AbstractParentItem::getLastVisibleChild () const virtual inherited
Implements Isis::AbstractTreeItem.
getLastVisibleChild() [2/2]
virtual AbstractTreeItem* Isis::AbstractTreeItem::getLastVisibleChild () const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::AbstractTreeModel::getItems().
getLastVisibleFilteredItem()
const AbstractTreeItem * Isis::AbstractTreeItem::getLastVisibleFilteredItem () const virtual inherited
Reimplemented in Isis::RootItem.
getNextVisiblePeer()
AbstractTreeItem * Isis::AbstractTreeItem::getNextVisiblePeer () const virtual inherited
Referenced by Isis::AbstractTreeModel::getVisibleTopLevelItemCount().
getPointer()
void * Isis::AbstractPointItem::getPointer () const virtual inherited
Implements Isis::AbstractTreeItem.
getPointerType()
AbstractTreeItem::InternalPointerType Isis::AbstractPointItem::getPointerType () const virtual inherited
Implements Isis::AbstractTreeItem.
References Isis::AbstractTreeItem::Point.
hasImage()
bool Isis::AbstractTreeItem::hasImage (QString imageSerial) const virtual inherited
Reimplemented in Isis::AbstractImageItem.
References Isis::AbstractTreeItem::childAt(), Isis::AbstractTreeItem::childCount(), and Isis::AbstractTreeItem::hasImage().
Referenced by Isis::AbstractImageItem::hasImage(), and Isis::AbstractTreeItem::hasImage().
hasMeasure()
bool Isis::AbstractTreeItem::hasMeasure (ControlMeasure * measure) const virtual inherited
Reimplemented in Isis::AbstractMeasureItem.
References Isis::AbstractTreeItem::childAt(), Isis::AbstractTreeItem::childCount(), and Isis::AbstractTreeItem::hasMeasure().
Referenced by Isis::AbstractTreeItem::hasMeasure().
hasPoint()
bool Isis::AbstractPointItem::hasPoint (ControlPoint * p) const virtual inherited
Reimplemented from Isis::AbstractTreeItem.
indexOf() [1/2]
int Isis::AbstractParentItem::indexOf (AbstractTreeItem * child) const virtual inherited
Implements Isis::AbstractTreeItem.
indexOf() [2/2]
virtual int Isis::AbstractTreeItem::indexOf (AbstractTreeItem * child) const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::AbstractTreeItem::row().
isDataEditable()
bool Isis::AbstractPointItem::isDataEditable (QString columnTitle) const virtual inherited
Implements Isis::AbstractTreeItem.
References Isis::AbstractPointItem::EditLock, Isis::AbstractPointItem::getColumn(), and Isis::ControlPoint::IsEditLocked().
isExpanded()
bool Isis::AbstractTreeItem::isExpanded () const virtual inherited
Referenced by Isis::TreeViewContent::mouseDoubleClickEvent(), and Isis::TreeViewContent::mouseReleaseEvent().
isSelectable()
bool Isis::AbstractTreeItem::isSelectable () const virtual inherited
Reimplemented in Isis::BusyLeafItem.
Referenced by Isis::TreeViewContent::mouseMoveEvent(), and Isis::TreeViewContent::mousePressEvent().
isSelected()
bool Isis::AbstractTreeItem::isSelected () const virtual inherited
Referenced by Isis::AbstractTreeModel::getSelectedItems(), Isis::TableViewContent::mousePressEvent(), and Isis::TreeViewContent::mousePressEvent().
isVisible()
bool Isis::AbstractTreeItem::isVisible () const virtual inherited
parent()
AbstractTreeItem * Isis::AbstractTreeItem::parent () const inherited
Referenced by Isis::AbstractTreeItem::getDepth(), Isis::AbstractTreeModel::getItems(), Isis::PointTableModel::handleTreeSelectionChanged(), and Isis::TableViewContent::mousePressEvent().
resetColumnHeaders()
void Isis::AbstractPointItem::resetColumnHeaders (TableColumnList * columns) static inherited
Resets pertinent point table column headers based on the active point coordinate display type (Lat/Lon/Radius or XYZ).
References Isis::AbstractPointItem::AdjustedSPCoord1, Isis::AbstractPointItem::AdjustedSPCoord1Sigma, Isis::AbstractPointItem::AdjustedSPCoord2, Isis::AbstractPointItem::AdjustedSPCoord2Sigma, Isis::AbstractPointItem::AdjustedSPCoord3, Isis::AbstractPointItem::AdjustedSPCoord3Sigma, Isis::AbstractPointItem::APrioriSPCoord1, Isis::AbstractPointItem::APrioriSPCoord1Sigma, Isis::AbstractPointItem::APrioriSPCoord2, Isis::AbstractPointItem::APrioriSPCoord2Sigma, Isis::AbstractPointItem::APrioriSPCoord3, Isis::AbstractPointItem::APrioriSPCoord3Sigma, Isis::AbstractPointItem::getColumnName(), and Isis::TableColumn::setTitle().
Referenced by Isis::PointTableModel::resetColumnHeaders().
row()
int Isis::AbstractTreeItem::row () const inherited
References Isis::AbstractTreeItem::indexOf().
Referenced by Isis::AbstractParentItem::childAt().
setData()
void Isis::AbstractPointItem::setData (QString const & columnTitle, QString const & newData) virtual inherited
Implements Isis::AbstractTreeItem.
References _FILEINFO_, Isis::AbstractPointItem::AdjustedSPCoord1, Isis::AbstractPointItem::AdjustedSPCoord1Sigma, Isis::AbstractPointItem::AdjustedSPCoord2, Isis::AbstractPointItem::AdjustedSPCoord2Sigma, Isis::AbstractPointItem::AdjustedSPCoord3, Isis::AbstractPointItem::AdjustedSPCoord3Sigma, Isis::AbstractPointItem::APrioriRadiusSource, Isis::AbstractPointItem::APrioriRadiusSourceFile, Isis::AbstractPointItem::APrioriSPCoord1, Isis::AbstractPointItem::APrioriSPCoord1Sigma, Isis::AbstractPointItem::APrioriSPCoord2, Isis::AbstractPointItem::APrioriSPCoord2Sigma, Isis::AbstractPointItem::APrioriSPCoord3, Isis::AbstractPointItem::APrioriSPCoord3Sigma, Isis::AbstractPointItem::APrioriSPSource, Isis::AbstractPointItem::APrioriSPSourceFile, Isis::AbstractTreeItem::catchNull(), Isis::AbstractPointItem::ChooserName, Isis::AbstractPointItem::DateTime, Isis::Angle::Degrees, Isis::AbstractPointItem::EditLock, Isis::ControlPoint::GetAdjustedSurfacePoint(), Isis::ControlPoint::GetAprioriSurfacePoint(), Isis::AbstractPointItem::getColumn(), Isis::CnetDisplayProperties::getInstance(), Isis::SurfacePoint::GetLatitude(), Isis::SurfacePoint::GetLatSigmaDistance(), Isis::SurfacePoint::GetLocalRadius(), Isis::SurfacePoint::GetLocalRadiusSigma(), Isis::SurfacePoint::GetLongitude(), Isis::SurfacePoint::GetLonSigmaDistance(), Isis::SurfacePoint::GetX(), Isis::SurfacePoint::GetXSigma(), Isis::SurfacePoint::GetY(), Isis::SurfacePoint::GetYSigma(), Isis::SurfacePoint::GetZ(), Isis::SurfacePoint::GetZSigma(), Isis::AbstractPointItem::Id, Isis::AbstractPointItem::Ignored, Isis::AbstractPointItem::JigsawRejected, Isis::CnetDisplayProperties::LatLonRadius, Isis::Distance::Meters, Isis::AbstractPointItem::PointType, Isis::IException::Programmer, Isis::AbstractPointItem::Reference, Isis::ControlPoint::SetAdjustedSurfacePoint(), Isis::ControlPoint::SetAprioriRadiusSource(), Isis::ControlPoint::SetAprioriRadiusSourceFile(), Isis::ControlPoint::SetAprioriSurfacePoint(), Isis::ControlPoint::SetAprioriSurfacePointSource(), Isis::ControlPoint::SetAprioriSurfacePointSourceFile(), Isis::ControlPoint::SetChooserName(), Isis::ControlPoint::SetDateTime(), Isis::ControlPoint::SetEditLock(), Isis::ControlPoint::SetId(), Isis::ControlPoint::SetIgnored(), Isis::SurfacePoint::SetRectangularCoordinates(), Isis::SurfacePoint::SetRectangularSigmas(), Isis::ControlPoint::SetRefMeasure(), Isis::SurfacePoint::SetSphericalCoordinates(), Isis::SurfacePoint::SetSphericalSigmasDistance(), Isis::ControlPoint::SetType(), Isis::ControlPoint::StringToPointType(), Isis::ControlPoint::StringToRadiusSource(), and Isis::ControlPoint::StringToSurfacePointSource().
setExpanded()
void Isis::AbstractTreeItem::setExpanded (bool newState) virtual inherited
Referenced by Isis::TreeViewContent::mouseDoubleClickEvent(), Isis::TreeViewContent::mouseReleaseEvent(), and Isis::RootItem::RootItem().
setFirstVisibleChild() [1/2]
void Isis::AbstractParentItem::setFirstVisibleChild (AbstractTreeItem * child) virtual inherited
Implements Isis::AbstractTreeItem.
setFirstVisibleChild() [2/2]
virtual void Isis::AbstractTreeItem::setFirstVisibleChild (AbstractTreeItem * child) pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
setLastVisibleChild() [1/2]
void Isis::AbstractParentItem::setLastVisibleChild (AbstractTreeItem * child) virtual inherited
Implements Isis::AbstractTreeItem.
setLastVisibleChild() [2/2]
virtual void Isis::AbstractTreeItem::setLastVisibleChild (AbstractTreeItem * child) pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
setLastVisibleFilteredItem()
void Isis::AbstractTreeItem::setLastVisibleFilteredItem (AbstractTreeItem * item) virtual inherited
Reimplemented in Isis::RootItem.
References _FILEINFO_, and Isis::IException::Programmer.
setNextVisiblePeer()
void Isis::AbstractTreeItem::setNextVisiblePeer (AbstractTreeItem * next) virtual inherited
setParent()
void Isis::AbstractTreeItem::setParent (AbstractTreeItem * newParent) inherited
Referenced by Isis::AbstractParentItem::addChild().
setSelectable()
void Isis::AbstractTreeItem::setSelectable (bool newSelectable) virtual inherited
setSelected()
void Isis::AbstractTreeItem::setSelected (bool newState) virtual inherited
Referenced by Isis::TableViewContent::mouseMoveEvent(), Isis::TableViewContent::mousePressEvent(), and Isis::TreeViewContent::mousePressEvent().
setVisible()
void Isis::AbstractTreeItem::setVisible (bool newState) virtual inherited
sourceDeleted()
void Isis::AbstractPointItem::sourceDeleted () protected virtual inherited
Implements Isis::AbstractTreeItem.
Referenced by Isis::AbstractPointItem::AbstractPointItem().
Member Data Documentation
COLS
const int Isis::AbstractPointItem::COLS = 24 static inherited
Referenced by Isis::AbstractPointItem::getColumn().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/PointParentItem.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/PointParentItem.cpp