Isis Developer Reference: Isis::AffineRadio Class Reference
Isis::AffineRadio Class Reference
Container for affine and radiometric parameters.
#include <GruenTypes.h>
Public Member Functions
AffineRadio ()
AffineRadio (const GMatrix &A)
AffineRadio (const GMatrix &M, const double &shift, const double &gain)
AffineRadio (const GVector &alpha)
AffineRadio (const Radiometric &radio)
~AffineRadio ()
AffineRadio & operator+= (const AffineRadio &other)
Define update procedure for accumulating Gruen iterations.
void Translate (const Coordinate &offset)
Apply a translation to the given offset.
Coordinate getPoint (const Coordinate &location) const
Applies the affine transfrom to a point and returns result.
Public Attributes
GMatrix m_affine
Radiometric m_radio
Detailed Description
Container for affine and radiometric parameters.
These parameters are provided for input and output results.
Author
2011-04-18 Kris Becker
Constructor & Destructor Documentation
AffineRadio() [1/5]
Isis::AffineRadio::AffineRadio () inline
AffineRadio() [2/5]
Isis::AffineRadio::AffineRadio (const GMatrix & A) inline
AffineRadio() [3/5]
Isis::AffineRadio::AffineRadio (const GMatrix & M, const double & shift, const double & gain) inline
AffineRadio() [4/5]
Isis::AffineRadio::AffineRadio (const GVector & alpha) inline
AffineRadio() [5/5]
Isis::AffineRadio::AffineRadio (const Radiometric & radio) inline
~AffineRadio()
Isis::AffineRadio::~AffineRadio () inline
Member Function Documentation
getPoint()
Coordinate Isis::AffineRadio::getPoint (const Coordinate & location) const inline
Applies the affine transfrom to a point and returns result.
References Isis::Coordinate::getLine(), Isis::Coordinate::getSample(), and m_affine.
Referenced by Isis::SmtkMatcher::Clone(), and Isis::MatchPoint::getAffinePoint().
operator+=()
AffineRadio& Isis::AffineRadio::operator+= (const AffineRadio & other) inline
Define update procedure for accumulating Gruen iterations.
References Isis::Affine::getIdentity(), m_affine, and m_radio.
Translate()
void Isis::AffineRadio::Translate (const Coordinate & offset) inline
Apply a translation to the given offset.
References Isis::Affine::getIdentity(), Isis::Coordinate::getLine(), Isis::Coordinate::getSample(), and m_affine.
Referenced by Isis::Gruen::Registration().
Member Data Documentation
m_affine
GMatrix Isis::AffineRadio::m_affine
Referenced by getPoint(), Isis::Threshold::hasConverged(), operator+=(), Isis::Gruen::Registration(), and Translate().
m_radio
Radiometric Isis::AffineRadio::m_radio
Referenced by operator+=(), and Isis::Gruen::Registration().
The documentation for this class was generated from the following file:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Gruen/GruenTypes.h