Isis Developer Reference: Isis::ProcessMosaic Class Reference
Isis::ProcessMosaic Class Reference
High Level Cube I/O
Mosaic two cubes together.
#include <ProcessMosaic.h>
Public Types
enum ImageOverlay {
PlaceImagesOnTop , PlaceImagesBeneath , UseBandPlacementCriteria , AverageImageWithMosaic ,
NumImageOverlayOptions
}
Enumeration for different Mosaic priorities (input, mosaic, band)
Public Member Functions
ProcessMosaic ()
ProcessMosaic Contructor.
virtual ~ProcessMosaic ()
Destroys the Mosaic object. It will close all opened cubes.
virtual void StartProcess (const int &piOutSample, const int &piOutLine, const int &piOutBand)
This method invokes the process by mosaic operation over a single input cube and single output cube.
virtual void EndProcess ()
Cleans up by closing input, output and tracking cubes.
PvlObject imagePositions ()
Accessor for the placed images and their locations.
virtual Isis::Cube * SetInputCube (const QString &parameter, const int ss, const int sl, const int sb, const int ns, const int nl, const int nb)
Opens an input cube specified by the user.
virtual Isis::Cube * SetInputCube (const QString &fname, Isis::CubeAttributeInput &att, const int ss=1, const int sl=1, const int sb=1, const int ns=-1, const int nl=-1, const int nb=-1)
Opens an input cube specified by the user.
Isis::Cube * SetOutputCube (const QString &psParameter)
Opens an output cube specified by the user.
Isis::Cube * SetOutputCube (const QString &psParameter, UserInterface &ui)
void SetBandBinMatch (bool enforceBandBinMatch)
void SetBandKeyword (QString bandPriorityKeyName, QString bandPriorityKeyValue)
Set the keyword/value to use for comparing when using band priority.
void SetBandNumber (int bandPriorityBandNumber)
Set the band to use for priorities when using band priority.
void SetBandUseMaxValue (bool useMax)
Set whether to take the image with the max or min value when using band priority.
void SetCreateFlag (bool createOutputMosaic)
Flag to indicate that the mosaic is being newly created Indication that the new label specific to the mosaic needs to be created.
void SetHighSaturationFlag (bool placeHighSatPixels)
When true, high saturation (HRS, HIS) will be considered valid data for the purposes of placing pixels in the output mosaic.
void SetImageOverlay (ImageOverlay placement)
void SetLowSaturationFlag (bool placeLowSatPixels)
When true, low saturation (LRS, LIS) will be considered valid data for the purposes of placing pixels in the output mosaic.
void SetMatchDEM (bool matchDEM)
Set the DEM match flag.
void SetNullFlag (bool placeNullPixels)
When true, Null pixels will be considered valid data for the purposes of placing pixels in the output mosaic.
void SetTrackFlag (bool trackingEnabled)
bool GetHighSaturationFlag () const
ImageOverlay GetImageOverlay () const
bool GetLowSaturationFlag () const
bool GetNullFlag () const
bool GetTrackFlag () const
int GetInputStartLineInMosaic () const
This is the line where the image was placed into the output mosaic.
int GetInputStartSampleInMosaic () const
This is the sample where the image was placed into the output mosaic.
int GetInputStartBandInMosaic () const
This is the band where the image was placed into the output mosaic.
virtual Isis::Cube * SetInputCube (const QString &parameter, const int requirements=0)
Opens an input cube specified by the user and verifies requirements are met.
virtual Isis::Cube * SetInputCube (const QString &fname, const Isis::CubeAttributeInput &att, int requirements=0)
Opens an input cube specified by the programmer and verifies requirements are met.
virtual void SetInputCube (Isis::Cube *inCube, int requirements=0)
Set the InputCube vector to an opened Cube which was dynamically allocated.
virtual void StartProcess (void funct())
In the base class, this method will invoked a user-specified function exactly one time.
virtual void Finalize ()
Cleans up by closing cubes and freeing memory for owned cubes.
virtual Isis::Cube * SetInputCube (const QString &parameter, const int requirements=0)
Opens an input cube specified by the user and verifies requirements are met.
virtual Isis::Cube * SetInputCube (const QString &fname, const Isis::CubeAttributeInput &att, int requirements=0)
Opens an input cube specified by the programmer and verifies requirements are met.
virtual void SetInputCube (Isis::Cube *inCube, int requirements=0)
Set the InputCube vector to an opened Cube which was dynamically allocated.
virtual Isis::Cube * SetOutputCube (const QString &parameter, const int nsamps, const int nlines, const int nbands=1)
Allocates a user specified output cube whose size is specified by the programmer.
virtual Isis::Cube * SetOutputCube (const QString &fname, const Isis::CubeAttributeOutput &att, const int nsamps, const int nlines, const int nbands=1)
Allocates a output cube whose name and size is specified by the programmer.
virtual Isis::Cube * SetOutputCubeStretch (const QString &parameter, UserInterface *ui=nullptr)
Allocates a user-specified output cube whose size matches the first input cube.
virtual Isis::Cube * SetOutputCubeStretch (const QString &parameter, const int nsamps, const int nlines, const int nbands=1, UserInterface *ui=nullptr)
Allocates a user specified output cube whose size is specified by the programmer.
void AddInputCube (Cube *cube, bool owned=true)
void AddOutputCube (Cube *cube, bool owned=true)
void CheckRequirements (const Cube *cube, const int requirements)
Checks to make sure the input cube meets the inputted requirements.
void ClearCubes ()
Close owned cubes from the list and clear the list.
void ClearInputCubes ()
Close owned input cubes from the list and clear the list.
void ClearOutputCubes ()
Close owned output cubes from the list and clear the list.
void PropagateLabels (const bool prop)
This method allows the programmer to turn on/off the propagation of labels from the 1st input cube to any of the output cubes.
void PropagateLabels (const QString &cube)
This method allows the programmer to propagate labels from a specific secondary cube.
void PropagateTables (const bool prop)
This method allows the programmer to propagate input tables to the output cube (default is true)
void PropagateTables (const QString &fromName, const QList< QString > &tableNames=QList< QString >())
Propagate the tables from the cube with the given filename to the output cube.
void PropagatePolygons (const bool prop)
This method allows the programmer to propagate input blobs to the output cube (default is true)
void PropagateHistory (const bool prop)
This method allows the programmer to propagate history to the output cube (default is true)
void PropagateOriginalLabel (const bool prop)
This method allows the programmer to propagate original labels to the output cube (default is true)
Isis::Progress * Progress ()
This method returns a pointer to a Progress object.
QString MissionData (const QString &mission, const QString &file, bool highestVersion=false)
This method reads the mission specific data directory from the user preference file, makes sure that mission is available in the Isis installation, and the attaches the provided input file to the directory in order to create a full file specification.
void WriteHistory (Cube &cube)
Writes out the History blob to the cube.
void CalculateStatistics ()
Calculates and stores off statistics on every band of every cube added to this process via the SetInputCube method.
std::vector< Isis::Statistics * > BandStatistics (const unsigned index)
Get the vector of Statistics objects for each band separately of a specified input cube.
Isis::Statistics * CubeStatistics (const unsigned index)
Get the Statistics object for all bands of a specified input cube.
Static Public Member Functions
static QString OverlayToString (ImageOverlay)
Convert an ImageOverlay to a QString.
static ImageOverlay StringToOverlay (QString)
Convert a QString to an ImageOverlay (case-insensitive).
Static Public Attributes
static const char * TRACKING_TABLE_NAME = "InputImages"
This is the name of the table in the Cube which will contain the image file names.
static const int FLOAT_STORE_INT_PRECISELY_MAX_VALUE = 16777216
static const int FLOAT_STORE_INT_PRECISELY_MIN_VALUE = -16777215
Protected Attributes
Isis::Progress * p_progress
Pointer to a Progress object.
bool p_propagateLabels
Flag indicating if labels are be propagated to output cubes.
bool p_propagateTables
Flag indicating if tables are be propagated to output cubes.
bool p_propagatePolygons
Flag indicating if blobs are be propagated to output cubes.
bool p_propagateHistory
Flag indicating if history is to be propagated to output cubes.
bool p_propagateOriginalLabel
Flag indicating if original lable is to be propagated to output cubes.
std::vector< std::vector< Isis::Statistics * > > p_bandStats
Holds the calculated statistics for each band separately of every input cubei after the CalculateStatistics method is called.
std::vector< Isis::Statistics * > p_cubeStats
Holds the calculated statistics for every band together of every input cubei after the CalculateStatistics method is called.
std::vector< Isis::Cube * > InputCubes
A vector of pointers to opened Cube objects.
std::vector< Isis::Cube * > OutputCubes
A vector of pointers to allocated Cube objects.
QSet< Isis::Cube * > * m_ownedCubes
A list of cubes owned by this instant.
Detailed Description
Mosaic two cubes together.
This class allows a programmer to develop a program which merges two cubes together. The application sets the position where input (child) cube will be placed in the mosaic (parent) cube and priority. The Mosaic object will merge the overlapping area.
The process has four priorities (input, mosaic, band, average) for how the input image has to be placed on the mosaic. Priority "input" will place the input image on top of the mosaic. Priority "mosaic" will place the input image beneath the mosaic. Priority "band" will place the input image on the mosaic based on the "Lessser" or "Greater" criteria between user defined band in the input and the mosaic images. Priority Average will average of valid pixels in the input and mosaic images. Choosing this priority will cause the mosaic to have twice the number of bands of the input image,with a count band for each band. The count band keeps track of number of images involved in the dn value of the mosaic. In case of special pixels and the special pixel flags being enabled, the details for each priority is described below.
This class also has the ability to track the origin of the pixel by storing the input image names in a table and assigning an index to each unique image in the order they were placed on the mosaic. If the priority is input or mosaic then tracking is done only for single band input image. Band priority can track the origin for multiple bands based on a specified band based on the criteria (Lesser or Greater). The specified band can be a number or any keyword in the label.
There are also options to copy High and Low Saturation both for Instrument and Representation and Null DN values from the input to the mosaic. These options are valid for only input(top) and band priorities.
Following are the values for the origin band depending on the pixel type
Pixel Type Default Start Value Max Value Total Images
(Bits) (No Origin) Supported
32 -16777216 -16777215 16777216 33549932 16 -32768 -32767 32767 65535 8 0 1 255 255
Tags: F(FALSE), T(TRUE), V(VALID), S(SPECIAL PIXEL HS, LS, NULL), N(NULL), I(INPUT), M(MOSAIC), HL(HS,LS)
For priority=mosaic (beneath), the input is placed beneath the mosaic i.e. the
input pixel will be copied to the mosaic only if the mosaic pixel is NULL.
Input Mosaic Output
V N I S,V HL,V M
For priority=input(on top), following is the criteria for pixel assignment:
—Options— —Images-—
HS LS NULL Input Mosaic Output
F F F V S,V I F F F S S,V M T OR T OR T V S,V I T OR T OR T S S,V I(H,L,N)
For priority=band, following is the criteria for pixel assignment:
—Options— —Images-—
HS LS NULL Input Mosaic Output
F F F V V Criteria based F F F V S I F F F S S,V M T OR T OR T S S,V I(H,L,N) T OR T OR T V V Criteria based T OR T OR T V S I
For priority=average, following is the criteria for pixel assignment:
—Options— —Images-—
HS LS NULL Input Mosaic Output Count
F F F V V Average count++ F F F V S I 1 F F F S S M 0 F F F S V M count T OR T OR T S S,V I(H,L,N) 0 T OR T OR T V V Average count++ T OR T OR T V S I 1
Author
2003-04-28 Stuart Sides
Member Enumeration Documentation
ImageOverlay
enum Isis::ProcessMosaic::ImageOverlay
Enumeration for different Mosaic priorities (input, mosaic, band)
Enumerator
PlaceImagesOnTop
ontop priority
PlaceImagesBeneath
beneath priority
UseBandPlacementCriteria
band priority
AverageImageWithMosaic
average priority
NumImageOverlayOptions
Constructor & Destructor Documentation
ProcessMosaic()
Isis::ProcessMosaic::ProcessMosaic ()
ProcessMosaic Contructor.
Initialize the class members to default
~ProcessMosaic()
Isis::ProcessMosaic::~ProcessMosaic () virtual
Destroys the Mosaic object. It will close all opened cubes.
Member Function Documentation
AddInputCube()
void Isis::Process::AddInputCube (Cube * cube, bool owned = true) inherited
AddOutputCube()
void Isis::Process::AddOutputCube (Cube * cube, bool owned = true) inherited
BandStatistics()
std::vector<Isis::Statistics *> Isis::Process::BandStatistics (const unsigned index) inline inherited
Get the vector of Statistics objects for each band separately of a specified input cube.
Parameters
index The index of the input cube in InputCubes
Returns
vector<Statistics*> A list of statistics ordered by band
References Isis::Process::p_bandStats.
CalculateStatistics()
void Isis::Process::CalculateStatistics () inherited
Calculates and stores off statistics on every band of every cube added to this process via the SetInputCube method.
The newly calculated statistics are stored in two ways: as a vector where each entry is a single Statistics object for every band of a particular input cube, and as a vector where each entry is a vector of Statistics objects, for each band separately, of a particular input cube.
References Isis::Statistics::AddData(), Isis::Cube::bandCount(), Isis::Progress::CheckStatus(), Isis::Buffer::DoubleBuffer(), Isis::Cube::lineCount(), Isis::Cube::read(), Isis::LineManager::SetLine(), Isis::Progress::SetMaximumSteps(), Isis::Progress::SetText(), Isis::Buffer::size(), and Isis::toString().
CheckRequirements()
void Isis::Process::CheckRequirements (const Cube * cube, const int requirements) inherited
Checks to make sure the input cube meets the inputted requirements.
Parameters
cube Cube to check
requirements Use to specify requirements for the input file. The following requirments are checked against 1) ic_base::SizeMatch checks to make sure the input cube has the same bands, samples, and lines as the first input cube open using this method, 2) ic_base::SpatialMatch checks to make sure the input cube has the same samples and lines as the first input cube, 3) ic_base::Georeferenced checks to make sure latitude/longitudes can be obtained from the input cube, 4) ic_base::FullyGeoreferenced checks to make sure latitude/longitude, phase/incidence/emission, and other geometric parameters can be obtained from the input cube, 5) ic_base::OneBand checks to make sure the input cube has exactly one band. Note, that these requirements can be logically or'ed. For example, ic_base::SpatialMatch | ic_base::georeferenced. Defaults to 0
Exceptions
Isis::iException::Message
References _FILEINFO_, Isis::AllMatchOrOne, Isis::Cube::bandCount(), Isis::BandMatchOrOne, Isis::Cube::fileName(), Isis::Cube::lineCount(), Isis::OneBand, Isis::Cube::sampleCount(), Isis::SizeMatch, and Isis::SpatialMatch.
ClearCubes()
void Isis::Process::ClearCubes () inherited
Close owned cubes from the list and clear the list.
ClearInputCubes()
void Isis::Process::ClearInputCubes () inherited
Close owned input cubes from the list and clear the list.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
ClearOutputCubes()
void Isis::Process::ClearOutputCubes () inherited
Close owned output cubes from the list and clear the list.
CubeStatistics()
Isis::Statistics* Isis::Process::CubeStatistics (const unsigned index) inline inherited
Get the Statistics object for all bands of a specified input cube.
Parameters
index The index of the input cube in InputCubes
Returns
Statistics* Collections of statistics gathered on all bands
References Isis::Process::p_cubeStats.
EndProcess()
void Isis::ProcessMosaic::EndProcess () virtual
Cleans up by closing input, output and tracking cubes.
Reimplemented from Isis::Process.
Finalize()
void Isis::Process::Finalize () virtual inherited
Cleans up by closing cubes and freeing memory for owned cubes.
Clears the lists for all cubes.
Reimplemented in Isis::ProcessPolygons, Isis::ProcessImportPds, Isis::ProcessGroundPolygons, Isis::ProcessByTile, Isis::ProcessByBrick, and Isis::ProcessByBoxcar.
Referenced by Isis::ProcessByBoxcar::Finalize().
GetHighSaturationFlag()
bool Isis::ProcessMosaic::GetHighSaturationFlag () const
See also
SetHighSaturationFlag()
GetImageOverlay()
ProcessMosaic::ImageOverlay Isis::ProcessMosaic::GetImageOverlay () const
GetInputStartBandInMosaic()
int Isis::ProcessMosaic::GetInputStartBandInMosaic () const
This is the band where the image was placed into the output mosaic.
GetInputStartLineInMosaic()
int Isis::ProcessMosaic::GetInputStartLineInMosaic () const
This is the line where the image was placed into the output mosaic.
GetInputStartSampleInMosaic()
int Isis::ProcessMosaic::GetInputStartSampleInMosaic () const
This is the sample where the image was placed into the output mosaic.
GetLowSaturationFlag()
bool Isis::ProcessMosaic::GetLowSaturationFlag () const
See also
SetLowSaturationFlag()
GetNullFlag()
bool Isis::ProcessMosaic::GetNullFlag () const
See also
SetNullFlag()
GetTrackFlag()
bool Isis::ProcessMosaic::GetTrackFlag () const
See also
SetTrackFlag()
imagePositions()
PvlObject Isis::ProcessMosaic::imagePositions ()
Accessor for the placed images and their locations.
Returns
The list of placed images
MissionData()
QString Isis::Process::MissionData (const QString & mission, const QString & file, bool highestVersion = false) inherited
This method reads the mission specific data directory from the user preference file, makes sure that mission is available in the Isis installation, and the attaches the provided input file to the directory in order to create a full file specification.
Parameters
mission Name of the mission data directory
file Name of the file to attach to the end of the directory
highestVersion If set to true the method will return the highest version number of the given file. Therefore, file must contain question marks such as "file???.dat". See the FileName class for more information on versioned files. Defaults to false.
References _FILEINFO_, Isis::FileName::expanded(), Isis::FileName::fileExists(), Isis::PvlObject::findGroup(), Isis::FileName::highestVersion(), Isis::FileName::original(), and Isis::Preference::Preferences().
OverlayToString()
QString Isis::ProcessMosaic::OverlayToString (ImageOverlay imageOverlay) static
Convert an ImageOverlay to a QString.
This is used to translate between mapmos, handmos, and automos' interfaces into an ImageOverlay.
References _FILEINFO_, and Isis::toString().
Progress()
Isis::Progress* Isis::Process::Progress () inline inherited
This method returns a pointer to a Progress object.
Returns
Progress*
References Isis::Process::p_progress.
Referenced by Isis::Equalization::applyCorrection(), Isis::Equalization::calculateBandStatistics(), Isis::HiEqualization::calculateStatistics(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::SpectralDefinition2D::SpectralDefinition2D().
PropagateHistory()
void Isis::Process::PropagateHistory (const bool prop) inherited
This method allows the programmer to propagate history to the output cube (default is true)
Parameters
prop Flag indicating if history is to be propagated to output cubes.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
PropagateLabels() [1/2]
void Isis::Process::PropagateLabels (const bool prop) inherited
This method allows the programmer to turn on/off the propagation of labels from the 1st input cube to any of the output cubes.
By default, propagation occurs automatically in the Process class when a call to either of the SetOutputCube methods is invoked. If the program * requires no propagation then utilize this method. This method can be invoked between successive calls of SetOutputCube so that some cube will have labels propagated while others will not.
Parameters
prop Flag indicating if labels are be propagated to output cubes.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
PropagateLabels() [2/2]
void Isis::Process::PropagateLabels (const QString & cube) inherited
This method allows the programmer to propagate labels from a specific secondary cube.
Parameters
cube IString containing the name of the cube containing the labels to propagate.
References Isis::PvlObject::addGroup(), Isis::PvlObject::addObject(), Isis::PvlObject::findObject(), Isis::PvlObject::group(), Isis::PvlObject::groups(), and Isis::PvlObject::hasObject().
PropagateOriginalLabel()
void Isis::Process::PropagateOriginalLabel (const bool prop) inherited
This method allows the programmer to propagate original labels to the output cube (default is true)
Parameters
prop Flag indicating if original labels is to be propagated to output cubes.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
PropagatePolygons()
void Isis::Process::PropagatePolygons (const bool prop) inherited
This method allows the programmer to propagate input blobs to the output cube (default is true)
Parameters
prop Flag indicating if input blobs are to be propagated to output cubes.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
PropagateTables() [1/2]
void Isis::Process::PropagateTables (const bool prop) inherited
This method allows the programmer to propagate input tables to the output cube (default is true)
Parameters
prop Flag indicating if input tables are to be propagated to output cubes.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube(), and Isis::ProcessMapMosaic::SetOutputCube().
PropagateTables() [2/2]
void Isis::Process::PropagateTables (const QString & fromName, const QList< QString > & tableNames = QList<QString>()) inherited
Propagate the tables from the cube with the given filename to the output cube.
This is done at the time this method is called, not during normal processing. The names of the tables to propagate can be provided through the second paramter, by specifing a list of table names. Not providing any list (or providing an empty list) will propagate all tables.
Parameters
fromName QString of the name of the cube containing the tables to propagate.
tableNames List of QStrings of the names of the tables to propagate; default is empty, which indicates that all tables will be propagated.
References Isis::Cube::close(), Isis::Cube::label(), Isis::PvlObject::object(), Isis::PvlObject::objects(), Isis::Cube::open(), and Isis::Cube::read().
SetBandBinMatch()
void Isis::ProcessMosaic::SetBandBinMatch (bool enforceBandBinMatch)
SetBandKeyword()
void Isis::ProcessMosaic::SetBandKeyword (QString bandPriorityKeyName, QString bandPriorityKeyValue)
Set the keyword/value to use for comparing when using band priority.
SetBandNumber()
void Isis::ProcessMosaic::SetBandNumber (int bandPriorityBandNumber)
Set the band to use for priorities when using band priority.
SetBandUseMaxValue()
void Isis::ProcessMosaic::SetBandUseMaxValue (bool useMax)
Set whether to take the image with the max or min value when using band priority.
SetCreateFlag()
void Isis::ProcessMosaic::SetCreateFlag (bool createOutputMosaic)
Flag to indicate that the mosaic is being newly created Indication that the new label specific to the mosaic needs to be created.
Author
Sharmila Prasad (1/19/2011)
Parameters
createOutputMosaic - Set Create Flag True/False
SetHighSaturationFlag()
void Isis::ProcessMosaic::SetHighSaturationFlag (bool placeHighSatPixels)
When true, high saturation (HRS, HIS) will be considered valid data for the purposes of placing pixels in the output mosaic.
SetImageOverlay()
void Isis::ProcessMosaic::SetImageOverlay (ImageOverlay placement)
SetInputCube() [1/8]
Isis::Cube * Isis::Process::SetInputCube (const QString & fname, const Isis::CubeAttributeInput & att, int requirements = 0) virtual inherited
Opens an input cube specified by the programmer and verifies requirements are met.
Parameters
fname Programmer specified work file. For example, "myfile.cub".
att The cube attributes to use when opening the input cube.
requirements Requirements to check that the input cube meets. See CheckRequirements().
Returns
Cube*
Exceptions
Isis::iException::Message
Reimplemented in Isis::ProcessByBrick.
References Isis::CubeAttributeInput::bands(), Isis::Cube::open(), Isis::ReadWrite, and Isis::Cube::setVirtualBands().
SetInputCube() [2/8]
Isis::Cube * Isis::Process::SetInputCube
Opens an input cube specified by the programmer and verifies requirements are met.
Parameters
fname Programmer specified work file. For example, "myfile.cub".
att The cube attributes to use when opening the input cube.
requirements Requirements to check that the input cube meets. See CheckRequirements().
Returns
Cube*
Exceptions
Isis::iException::Message
SetInputCube() [3/8]
Cube * Isis::ProcessMosaic::SetInputCube (const QString & fname, Isis::CubeAttributeInput & att, const int ss = 1, const int sl = 1, const int sb = 1, const int ns = -1, const int nl = -1, const int nb = -1) virtual
Opens an input cube specified by the user.
This method is overloaded and adds the requirement that only one input cube can be specified.
Returns
Cube*
Parameters
fname
att
ss The starting sample within the input cube. This allowd the application to choose a sub-area from the input cube to be place into the mosaic. Defaults to 1
sl The starting line within the input cube. This allowd the application to choose a sub-area from the input cube to be place into the mosaic. Defaults to 1
sb The starting band within the input cube. This allowd the application to choose a sub-area from the input cube to be place into the mosaic. Defaults to 1
ns The number of samples from the input cube. This allowd the application to choose a sub-area from the input cube to be place into the mosaic. Defaults to number of samples in the cube
nl The number of lines from the input cube. This allowd the application to choose a sub-area from the input cube to be place into the mosaic. Defaults to number of lines in the cube
nb The number of bands from the input cube. This allowd the application to choose a sub-area from the input cube to be place into the mosaic. Defaults to number of bands in the cube
Exceptions
IException
References _FILEINFO_, Isis::PvlObject::findGroup(), and Isis::toInt().
SetInputCube() [4/8]
Isis::Cube * Isis::Process::SetInputCube (const QString & parameter, const int requirements = 0) virtual inherited
Opens an input cube specified by the user and verifies requirements are met.
Returns
Cube*
Parameters
parameter User parameter to obtain file to open. Typically, the value is "FROM". For example, the user can specify on the command line FROM=myfile.cub and this method will attempt to open the cube "myfile.cub" if the parameter was set to "FROM".
requirements Requirements to check that the input cube meets. See CheckRequirements().
Exceptions
Isis::iException::Message
Reimplemented in Isis::ProcessBySample, Isis::ProcessByBrick, Isis::ProcessBySpectra, and Isis::ProcessByLine.
Referenced by Isis::ProcessGroundPolygons::SetStatCubes().
SetInputCube() [5/8]
Isis::Cube * Isis::Process::SetInputCube
Opens an input cube specified by the user and verifies requirements are met.
Returns
Cube*
Parameters
parameter User parameter to obtain file to open. Typically, the value is "FROM". For example, the user can specify on the command line FROM=myfile.cub and this method will attempt to open the cube "myfile.cub" if the parameter was set to "FROM".
requirements Requirements to check that the input cube meets. See CheckRequirements().
Exceptions
Isis::iException::Message
SetInputCube() [6/8]
Cube * Isis::ProcessMosaic::SetInputCube (const QString & parameter, const int ss, const int sl, const int sb, const int ns, const int nl, const int nb) virtual
Opens an input cube specified by the user.
This method is overloaded and adds the requirement that only one input cube can be specified.
Returns
Cube*
Parameters
parameter User parameter to obtain file to open. Typically, the value is "FROM". For example, the user can specify on the command line FROM=myfile.cub and this method will attempt to open the cube "myfile.cub" if the parameter was set to "FROM".
ss The starting sample within the input cube. This allowd the application to choose a sub-area from the input cube to be place into the mosaic. Defaults to 1
sl The starting line within the input cube. This allowd the application to choose a sub-area from the input cube to be place into the mosaic. Defaults to 1
sb The starting band within the input cube. This allowd the application to choose a sub-area from the input cube to be place into the mosaic. Defaults to 1
ns The number of samples from the input cube. This allowd the application to choose a sub-area from the input cube to be place into the mosaic. Defaults to number of samples in the cube
nl The number of lines from the input cube. This allowd the application to choose a sub-area from the input cube to be place into the mosaic. Defaults to number of lines in the cube
nb The number of bands from the input cube. This allowd the application to choose a sub-area from the input cube to be place into the mosaic. Defaults to number of bands in the cube
Exceptions
IException::Message
References _FILEINFO_, Isis::PvlObject::findGroup(), and Isis::toInt().
SetInputCube() [7/8]
void Isis::Process::SetInputCube (Isis::Cube * inCube, int requirements = 0) virtual inherited
Set the InputCube vector to an opened Cube which was dynamically allocated.
This is used if there already exists a valid opened cube
Author
Sharmila Prasad (5/7/2011)
Parameters
inCube - Pointer to input Cube
requirements Requirements to check that the input cube meets. See CheckRequirements().
References _FILEINFO_, and Isis::Cube::isOpen().
SetInputCube() [8/8]
void Isis::Process::SetInputCube
Set the InputCube vector to an opened Cube which was dynamically allocated.
This is used if there already exists a valid opened cube
Author
Sharmila Prasad (5/7/2011)
Parameters
inCube - Pointer to input Cube
requirements Requirements to check that the input cube meets. See CheckRequirements().
SetLowSaturationFlag()
void Isis::ProcessMosaic::SetLowSaturationFlag (bool placeLowSatPixels)
When true, low saturation (LRS, LIS) will be considered valid data for the purposes of placing pixels in the output mosaic.
SetMatchDEM()
void Isis::ProcessMosaic::SetMatchDEM (bool matchDEM)
Set the DEM match flag.
Parameters
matchDEM If true, the match is enforced between Input & Mosaic
SetNullFlag()
void Isis::ProcessMosaic::SetNullFlag (bool placeNullPixels)
When true, Null pixels will be considered valid data for the purposes of placing pixels in the output mosaic.
SetOutputCube() [1/4]
Isis::Cube * Isis::Process::SetOutputCube (const QString & fname, const Isis::CubeAttributeOutput & att, const int ns, const int nl, const int nb = 1) virtual inherited
Allocates a output cube whose name and size is specified by the programmer.
Returns
Cube*
Parameters
fname Name of the output cube to allocate
att The cube attributes to use when creating the output cube.
ns Number of samples to allocate
nl Number of lines to allocate
nb Number of bands to allocate
Exceptions
Isis::iException::Message
References _FILEINFO_, Isis::PvlObject::addGroup(), Isis::PvlObject::addObject(), Isis::AttachedLabel, Isis::CubeAttributeOutput::byteOrder(), Isis::Cube::create(), Isis::CubeAttributeOutput::fileFormat(), Isis::PvlObject::findObject(), Isis::PvlObject::group(), Isis::PvlObject::groups(), Isis::PvlContainer::isNamed(), Isis::Cube::label(), Isis::CubeAttributeOutput::labelAttachment(), Isis::Cube::labelSize(), Isis::CubeAttributeOutput::maximum(), Isis::CubeAttributeOutput::minimum(), Isis::PvlContainer::name(), Isis::PvlObject::object(), Isis::PvlObject::objects(), Isis::Cube::pixelType(), Isis::CubeAttributeOutput::pixelType(), Isis::CubeAttributeOutput::propagateMinimumMaximum(), Isis::CubeAttributeOutput::propagatePixelType(), Isis::Real, Isis::Cube::setBaseMultiplier(), Isis::Cube::setByteOrder(), Isis::Cube::setDimensions(), Isis::Cube::setFormat(), Isis::Cube::setLabelsAttached(), Isis::Cube::setLabelSize(), Isis::Cube::setMinMax(), Isis::Cube::setPixelType(), Isis::SignedInteger, Isis::SignedWord, Isis::UnsignedByte, Isis::UnsignedInteger, Isis::UnsignedWord, and Isis::Cube::write().
SetOutputCube() [2/4]
Isis::Cube * Isis::Process::SetOutputCube (const QString & parameter, const int ns, const int nl, const int nb = 1) virtual inherited
Allocates a user specified output cube whose size is specified by the programmer.
Returns
Cube*
Parameters
parameter User specified output file. For example, "TO" is a popular user parameter. If the user specified TO=output.cub, then this routine would allocate the file output.cub with size specified by the first opened input cube. The output pixel type will be propagated from the first loaded input cube or will use the value in the application XML file for pixelType.
ns Number of samples to allocate
nl Number of lines to allocate
nb Number of bands to allocate
Exceptions
Isis::iException::Message
References _FILEINFO_.
SetOutputCube() [3/4]
Cube * Isis::ProcessMosaic::SetOutputCube (const QString & psParameter) virtual
Opens an output cube specified by the user.
This method is overloaded and adds the requirement that only one output cube can be specified. The output cube must exist before calling SetOutputCube.
Returns
Cube*
Parameters
psParameter User parameter to obtain file to open. Typically, the value is "TO". For example, the user can specify on the command line TO=mosaic.cub and this method will attempt to open the cube "mosaic.cub" if the parameter was set to "TO". .
Exceptions
IException::Message
Reimplemented from Isis::Process.
SetOutputCube() [4/4]
Cube * Isis::ProcessMosaic::SetOutputCube (const QString & psParameter, UserInterface & ui)
References _FILEINFO_, Isis::PvlObject::findObject(), IsisAml::GetCubeName(), Isis::Cube::label(), and Isis::Cube::open().
SetOutputCubeStretch() [1/2]
Isis::Cube * Isis::Process::SetOutputCubeStretch (const QString & parameter, const int ns, const int nl, const int nb = 1, UserInterface * ui = nullptr) virtual inherited
Allocates a user specified output cube whose size is specified by the programmer.
Returns
Cube*
Parameters
parameter User specified output file. For example, "TO" is a popular user parameter. If the user specified TO=output.cub, then this routine would allocate the file output.cub with size specified by the first opened input cube. The output pixel type will be propagated from the first loaded input cube or will use the value in the application XML file for pixelType.
ns Number of samples to allocate
nl Number of lines to allocate
nb Number of bands to allocate
ui A user interface used to get the attributes needed. If null, the user interface will be obtained from the application.
Exceptions
Isis::iException::Message
References _FILEINFO_, IsisAml::GetCubeName(), and IsisAml::GetOutputAttribute().
SetOutputCubeStretch() [2/2]
Isis::Cube * Isis::Process::SetOutputCubeStretch (const QString & parameter, UserInterface * ui = nullptr) virtual inherited
Allocates a user-specified output cube whose size matches the first input cube.
Returns
Cube*
Parameters
parameter User specified output file. For example, "TO" is a popular user parameter. If the user specified TO=output.cub, then this routine would allocate the file output.cub with size specified by the first opened input cube. The output pixel type will be propagated from the first loaded input cube or will use the value in the application XML file for pixelType.
ui A user interface used to get the attributes needed for SetOutputCube.
Exceptions
Isis::iException::Message
References _FILEINFO_.
SetTrackFlag()
void Isis::ProcessMosaic::SetTrackFlag (bool trackingEnabled)
StartProcess() [1/2]
void Isis::ProcessMosaic::StartProcess (const int & os, const int & ol, const int & ob) virtual
This method invokes the process by mosaic operation over a single input cube and single output cube.
Unlike other Isis process objects, no application . function will be called. The processing is handled entirely within the mosaic object. The input cube must be pixel aligned with the output cube before mosaiking. If the input cube does not overlay any of the output cube, no processing takes place. There are 3 priorities input, mosaic and band. Has the ability to track the origin of the mosaic if the flag is set. Some conditions apply like tracking turned off for multiband input with input or mosaic priority.
Parameters
os The sample position of input cube starting sample relative to the output cube. The cordinate is in output cube space and may be any integer value negative or positive.
ol The line position of input cube starting line relative to the output cube. The cordinate is in output cube space and may be any integer value negative or positive.
ob The band position of input cube starting band relative to the output cube. The cordinate is in output cube space and must be a legal band number within the output cube.
Exceptions
IException::Message
Author
Sharmila Prasad (8/25/2009)
References _FILEINFO_, Isis::PvlContainer::addKeyword(), Isis::FileName::expanded(), Isis::TrackingTable::fileNameToPixel(), Isis::PvlObject::findGroup(), Isis::PvlObject::findObject(), Isis::IsHighPixel(), Isis::IsLowPixel(), Isis::IsNullPixel(), Isis::IsValidPixel(), Isis::FileName::path(), Isis::FileName::removeExtension(), Isis::Cube::setPixelType(), Isis::Portal::SetPosition(), Isis::PvlKeyword::setValue(), Isis::Buffer::size(), Isis::toString(), Isis::TrackingTable::toTable(), Isis::trackingTableName, Isis::UnsignedInteger, and Isis::VALID_MINUI4.
StartProcess() [2/2]
virtual void Isis::Process::StartProcess (void funct()) inline virtual inherited
In the base class, this method will invoked a user-specified function exactly one time.
In derived classes such as ProcessByLine, the StartProcess will invoke a user-specified function for every line in a cube.
Parameters
funct() Name of your processing function
StringToOverlay()
ProcessMosaic::ImageOverlay Isis::ProcessMosaic::StringToOverlay (QString imageOverlayString) static
Convert a QString to an ImageOverlay (case-insensitive).
This is used to translate between mapmos, handmos, and automos' interfaces into an ImageOverlay.
References _FILEINFO_.
WriteHistory()
void Isis::Process::WriteHistory (Cube & cube) inherited
Writes out the History blob to the cube.
References Isis::History::AddEntry(), Isis::iApp, Isis::PvlContainer::isNamed(), Isis::PvlObject::object(), Isis::PvlObject::objects(), Isis::Cube::readHistory(), and Isis::Cube::write().
Referenced by Isis::ImageImporter::import().
Member Data Documentation
FLOAT_STORE_INT_PRECISELY_MAX_VALUE
const int Isis::ProcessMosaic::FLOAT_STORE_INT_PRECISELY_MAX_VALUE = 16777216 static
FLOAT_STORE_INT_PRECISELY_MIN_VALUE
const int Isis::ProcessMosaic::FLOAT_STORE_INT_PRECISELY_MIN_VALUE = -16777215 static
InputCubes
std::vector<Isis::Cube *> Isis::Process::InputCubes protected inherited
A vector of pointers to opened Cube objects.
The pointers are established in the SetInputCube/SetInputWorkCube methods.
Referenced by Isis::ProcessExport::CreateWorldFile(), Isis::ProcessExport::GetBuffersBIL(), Isis::ProcessExport::GetBuffersBIP(), Isis::ProcessExport::GetBuffersBSQ(), Isis::ProcessByBrick::ProcessCube(), Isis::ProcessExport::ProcessCubes(), Isis::ProcessByBrick::ProcessCubes(), Isis::ProcessExport::SetInputRange(), Isis::ProcessExport::StartProcess(), and Isis::ProcessByQuickFilter::StartProcess().
m_ownedCubes
QSet<Isis::Cube *>* Isis::Process::m_ownedCubes protected inherited
A list of cubes owned by this instant.
These cubes will be deleted on finalization. Process will not take ownership of cubes allocated outside of Process. It is the caller's responsibility to delete such cubes.
OutputCubes
std::vector<Isis::Cube *> Isis::Process::OutputCubes protected inherited
A vector of pointers to allocated Cube objects.
The pointers are established in the SetOutputCube method.
Referenced by Isis::ProcessImport::ProcessBil(), Isis::ProcessImport::ProcessBip(), Isis::ProcessImport::ProcessBsq(), Isis::ProcessByBrick::ProcessCube(), Isis::ProcessByBrick::ProcessCubes(), Isis::ProcessImport::ProcessJp2(), and Isis::ProcessByQuickFilter::StartProcess().
p_bandStats
std::vector< std::vector< Isis::Statistics * > > Isis::Process::p_bandStats protected inherited
Holds the calculated statistics for each band separately of every input cubei after the CalculateStatistics method is called.
Referenced by Isis::Process::BandStatistics().
p_cubeStats
std::vector< Isis::Statistics * > Isis::Process::p_cubeStats protected inherited
Holds the calculated statistics for every band together of every input cubei after the CalculateStatistics method is called.
Referenced by Isis::Process::CubeStatistics().
p_progress
Isis::Progress* Isis::Process::p_progress protected inherited
Pointer to a Progress object.
Referenced by Isis::ProcessImport::ProcessBil(), Isis::ProcessImport::ProcessBip(), Isis::ProcessImport::ProcessBsq(), Isis::ProcessExport::ProcessCubes(), Isis::ProcessExport::ProcessExport(), Isis::ProcessImport::ProcessImport(), Isis::ProcessImport::ProcessJp2(), Isis::Process::Progress(), Isis::ProcessExport::StartProcess(), and Isis::ProcessByQuickFilter::StartProcess().
p_propagateHistory
bool Isis::Process::p_propagateHistory protected inherited
Flag indicating if history is to be propagated to output cubes.
p_propagateLabels
bool Isis::Process::p_propagateLabels protected inherited
Flag indicating if labels are be propagated to output cubes.
p_propagateOriginalLabel
bool Isis::Process::p_propagateOriginalLabel protected inherited
Flag indicating if original lable is to be propagated to output cubes.
p_propagatePolygons
bool Isis::Process::p_propagatePolygons protected inherited
Flag indicating if blobs are be propagated to output cubes.
p_propagateTables
bool Isis::Process::p_propagateTables protected inherited
Flag indicating if tables are be propagated to output cubes.
TRACKING_TABLE_NAME
const char * Isis::ProcessMosaic::TRACKING_TABLE_NAME = "InputImages" static
This is the name of the table in the Cube which will contain the image file names.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ProcessMosaic/ProcessMosaic.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ProcessMosaic/ProcessMosaic.cpp