Isis Developer Reference: Isis::Target Class Reference
Isis::Target Class Reference
This class is used to create and store valid Isis targets.
#include <Target.h>
Public Member Functions
Target (Spice *spice, Pvl &label)
Constructs a Target object and loads target information.
Target (Pvl &label)
Construct a Target without SPICE data.
Target ()
Constructs an empty Target object.
~Target ()
Destroys the Target.
void init ()
Initialize member variables.
bool isSky () const
Return if our target is the sky.
SpiceInt naifBodyCode () const
This returns the NAIF body code of the target.
SpiceInt naifPlanetSystemCode () const
This returns the NAIF planet system body code of the target.
QString name () const
Return target name.
QString systemName () const
Return planet system name.
std::vector< Distance > radii () const
Returns the radii of the body in km.
void restoreShape ()
Restores the shape to the original after setShapeEllipsoid has overridden it.
void setShapeEllipsoid ()
Set the shape to the ellipsoid and save the original shape.
void setRadii (std::vector< Distance > radii)
Sets the radii of the body.
void setName (QString name)
Set the name for the Target.
void setSpice (Spice *spice)
Set the Spice pointer for the Target.
ShapeModel * shape () const
Return the shape.
Spice * spice () const
Return the spice object.
int frameType ()
std::vector< Angle > poleRaCoefs ()
std::vector< Angle > poleDecCoefs ()
std::vector< Angle > pmCoefs ()
std::vector< double > poleRaNutPrecCoefs ()
std::vector< double > poleDecNutPrecCoefs ()
std::vector< double > pmNutPrecCoefs ()
std::vector< Angle > sysNutPrecConstants ()
std::vector< Angle > sysNutPrecCoefs ()
Static Public Member Functions
static SpiceInt lookupNaifBodyCode (QString name)
This returns the NAIF body code of the target indicated in the labels.
static PvlGroup radiiGroup (QString target)
Creates a Pvl Group with keywords TargetName, EquitorialRadius, and PolarRadius.
static PvlGroup radiiGroup (Pvl &cubeLab, const PvlGroup &mapGroup)
This method returns a Mapping group containing TargetName, EquatorialRadius, and PolarRadius in addition to all of the keywords that are in the given mapGroup.
Detailed Description
This class is used to create and store valid Isis targets.
Author
2012-03-20 Debbie A. Cook
Constructor & Destructor Documentation
Target() [1/3]
Isis::Target::Target (Spice * spice, Pvl & lab)
Constructs a Target object and loads target information.
Parameters
lab Label containing Instrument and Kernels groups.
Author
2012-03-20 Debbie A. Cook
References Isis::PvlObject::findGroup(), Isis::PvlContainer::hasKeyword(), and Isis::toInt().
Target() [2/3]
Isis::Target::Target (Pvl & label)
Construct a Target without SPICE data.
The label should contain an Instrument group with a TargetName and a Kernels group with a ShapeModel.
Parameters
label Label containing information about the Target.
References Isis::PvlObject::findGroup(), Isis::PvlContainer::hasKeyword(), and Isis::toInt().
Target() [3/3]
Isis::Target::Target ()
Constructs an empty Target object.
Author
2012-03-20 Debbie A. Cook
~Target()
Isis::Target::~Target ()
Destroys the Target.
Destroys the Target object.
Member Function Documentation
frameType()
int Isis::Target::frameType ()
Referenced by Isis::TargetBody::TargetBody().
init()
void Isis::Target::init ()
Initialize member variables.
Author
2012-03-20 Debbie A. Cook
isSky()
bool Isis::Target::isSky () const
Return if our target is the sky.
Referenced by Isis::ShapeModelFactory::create(), and Isis::FindTool::mouseButtonRelease().
lookupNaifBodyCode()
SpiceInt Isis::Target::lookupNaifBodyCode (QString name) static
This returns the NAIF body code of the target indicated in the labels.
Returns
SpiceInt NAIF body code
References _FILEINFO_.
naifBodyCode()
SpiceInt Isis::Target::naifBodyCode () const
This returns the NAIF body code of the target.
Returns
SpiceInt NAIF body code
Referenced by Isis::TargetBody::TargetBody().
naifPlanetSystemCode()
SpiceInt Isis::Target::naifPlanetSystemCode () const
This returns the NAIF planet system body code of the target.
Returns
SpiceInt NAIF system body code
e.g. Enceladus is in the Saturn system
Referenced by Isis::TargetBody::TargetBody().
name()
QString Isis::Target::name () const
Return target name.
Referenced by Isis::TargetBody::TargetBody(), and Isis::Spice::targetName().
pmCoefs()
std::vector< Angle > Isis::Target::pmCoefs ()
Referenced by Isis::BundleTargetBody::BundleTargetBody(), and Isis::TargetBody::TargetBody().
pmNutPrecCoefs()
std::vector< double > Isis::Target::pmNutPrecCoefs ()
Referenced by Isis::TargetBody::TargetBody().
poleDecCoefs()
std::vector< Angle > Isis::Target::poleDecCoefs ()
Referenced by Isis::BundleTargetBody::BundleTargetBody(), and Isis::TargetBody::TargetBody().
poleDecNutPrecCoefs()
std::vector< double > Isis::Target::poleDecNutPrecCoefs ()
Referenced by Isis::TargetBody::TargetBody().
poleRaCoefs()
std::vector< Angle > Isis::Target::poleRaCoefs ()
Referenced by Isis::BundleTargetBody::BundleTargetBody(), and Isis::TargetBody::TargetBody().
poleRaNutPrecCoefs()
std::vector< double > Isis::Target::poleRaNutPrecCoefs ()
Referenced by Isis::TargetBody::TargetBody().
radii()
std::vector< Distance > Isis::Target::radii () const
Returns the radii of the body in km.
The radii are obtained from the appropriate SPICE kernel for the body specified by TargetName in the Instrument group of the labels.
Referenced by Isis::Camera::BasicMapping(), Isis::BundleTargetBody::BundleTargetBody(), and Isis::TargetBody::TargetBody().
radiiGroup() [1/2]
PvlGroup Isis::Target::radiiGroup (Pvl & cubeLab, const PvlGroup & mapGroup) static
This method returns a Mapping group containing TargetName, EquatorialRadius, and PolarRadius in addition to all of the keywords that are in the given mapGroup.
Parameters
cubeLab Pvl labels for the image.
mapGroup A const reference to a PvlGroup that contains mapping parameters for the projection.
Returns
PvlGroup The Mapping Group for the projection including the keywords TargetName, EquatorialRadius, and PolarRadius.
References _FILEINFO_, Isis::PvlContainer::addKeyword(), Isis::PvlObject::findGroup(), Isis::PvlObject::findKeyword(), Isis::PvlContainer::findKeyword(), Isis::PvlObject::findObject(), Isis::PvlObject::hasKeyword(), Isis::PvlContainer::hasKeyword(), Isis::PvlObject::hasObject(), Isis::toDouble(), Isis::toString(), and Isis::IException::what().
radiiGroup() [2/2]
PvlGroup Isis::Target::radiiGroup (QString target) static
Creates a Pvl Group with keywords TargetName, EquitorialRadius, and PolarRadius.
The values for the radii will be retrieved from the most recent Target Attitude and Shape Naif kernel available in the Isis data area.
Parameters
target The name of the body for which the radii will be retrieved.
Exceptions
IException::Io - "Could not convert target name to NAIF code."
Returns
PvlGroup Group named "Mapping" with keywords TargetName, EquatorialRadius, and PolarRadius.
References _FILEINFO_, and Isis::PvlContainer::findKeyword().
Referenced by Isis::Latitude::add(), Isis::Latitude::Latitude(), and Isis::TProjection::TProjection().
restoreShape()
void Isis::Target::restoreShape ()
Restores the shape to the original after setShapeEllipsoid has overridden it.
Referenced by Isis::Sensor::IgnoreElevationModel().
setName()
void Isis::Target::setName (QString name)
Set the name for the Target.
This function should be used if the target name is not available on the label originally used to initialize the Target.
Parameters
name The new name of the Target
setRadii()
void Isis::Target::setRadii (std::vector< Distance > radii)
Sets the radii of the body.
Parameters
r[] Radii of the target in kilometers
Referenced by Isis::CSMCamera::setTarget().
setShapeEllipsoid()
void Isis::Target::setShapeEllipsoid ()
Set the shape to the ellipsoid and save the original shape.
Referenced by Isis::Sensor::IgnoreElevationModel().
setSpice()
void Isis::Target::setSpice (Spice * spice)
Set the Spice pointer for the Target.
This function should be used if the Target was initialized without SPICE data but is still needed by a sensor model.
Parameters
spice A pointer to the new Spice object
Referenced by Isis::CSMCamera::setTarget().
shape()
ShapeModel * Isis::Target::shape () const
Return the shape.
Referenced by Isis::Sensor::Coordinate(), Isis::CSMCamera::EmissionAngle(), Isis::Sensor::EmissionAngle(), Isis::Sensor::GetLatitude(), Isis::Camera::GetLocalNormal(), Isis::Sensor::GetLongitude(), Isis::Sensor::GetSurfacePoint(), Isis::UniversalGroundMap::GroundRange(), Isis::Sensor::HasSurfaceIntersection(), Isis::CSMCamera::IncidenceAngle(), Isis::Sensor::IncidenceAngle(), Isis::Sensor::LocalRadius(), Isis::CSMCamera::PhaseAngle(), Isis::VimsGroundMap::SetGround(), Isis::RadarGroundMap::SetGround(), Isis::Sensor::SetGround(), Isis::Camera::SetGround(), Isis::CSMCamera::SetGround(), Isis::Camera::SetImage(), Isis::CSMCamera::SetImage(), Isis::Sensor::SetLookDirection(), Isis::CSMCamera::SetLookDirection(), Isis::Sensor::setTime(), Isis::Camera::SetUniversalGround(), Isis::Sensor::SetUniversalGround(), Isis::Sensor::SlantDistance(), Isis::Camera::Slope(), and Isis::Sensor::SolarDistance().
spice()
Spice * Isis::Target::spice () const
Return the spice object.
sysNutPrecCoefs()
std::vector< Angle > Isis::Target::sysNutPrecCoefs ()
Referenced by Isis::TargetBody::TargetBody().
sysNutPrecConstants()
std::vector< Angle > Isis::Target::sysNutPrecConstants ()
Referenced by Isis::TargetBody::TargetBody().
systemName()
QString Isis::Target::systemName () const
Return planet system name.
Referenced by Isis::TargetBody::TargetBody().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Target/Target.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Target/Target.cpp