Isis Developer Reference: Isis::Spectel Class Reference
Isis::Spectel Class Reference
Stores information about a "Spectral pixel" or spectel.
#include <Spectel.h>
Public Member Functions
Spectel ()
Constructs an empty Spectel.
Spectel (int sample, int line, int band, double DN, double center, double width)
Constructs a Spectel using its l,s,b coordinates, its DN value, and its wavelength.
Spectel (Pixel pixel, double center, double width)
Constructs a Spectel, given a Pixel, center wavelength, and width.
Spectel (const Spectel &spectel)
Constructs a Spectel, given a Spectel.
virtual ~Spectel ()
Default destructor.
Spectel & operator= (const Spectel &other)
Copy assignment operator.
double centerWavelength () const
Gets central wavelength of spectel.
double filterWidth () const
Gets wavelength width associated with spectel.
int line () const
int sample () const
int band () const
double DN () const
unsigned char To8Bit ()
Converts internal pixel value to an unsigned char pixel with special pixel translations.
short int To16Bit ()
Converts internal pixel value to a short int pixel with special pixel translations.
short unsigned int To16Ubit ()
Converts internal pixel value to a short int pixel with special pixel translations.
float To32Bit ()
Converts internal pixel value to float with special pixel translations.
double ToDouble ()
Converts stored pixel value to a double.
float ToFloat ()
Converts internal pixel value to float with pixel translations and care for overflows (underflows are assumed to cast to 0!)
std::string ToString ()
Returns the name of the pixel type as a string.
bool IsSpecial ()
Returns true if the input pixel is special.
bool IsValid ()
Returns true if the input pixel is valid.
bool IsNull ()
Returns true if the input pixel is null.
bool IsHigh ()
Returns true if the input pixel is one of the high saturation types.
bool IsLow ()
Returns true if the input pixel is one of the low saturation types.
bool IsHrs ()
Returns true if the input pixel is high representation saturation.
bool IsHis ()
Returns true if the input pixel is high instrument saturation.
bool IsLis ()
Returns true if the input pixel is low instrument saturation.
bool IsLrs ()
Returns true if the input pixel is low representation saturation.
Static Public Member Functions
static unsigned char To8Bit (const double d)
Converts double pixels to unsigned char pixels with special pixel translations.
static short int To16Bit (const double d)
Converts double pixels to short int pixels with special pixel translations.
static short unsigned int To16UBit (const double d)
Converts double pixels to short unsigned int pixels with special pixel translations.
static float To32Bit (const double d)
Converts double pixels to float pixels with special pixel translations.
static double ToDouble (const unsigned char t)
Converts unsigned char pixels to double pixels with special pixel translations.
static double ToDouble (const short int t)
Converts short int pixels to double pixels with special pixel translations.
static double ToDouble (const short unsigned int t)
Converts short unsigned int pixels to double pixels with special pixel translations.
static double ToDouble (const float t)
Converts float pixels to double pixels with special pixel translations.
static float ToFloat (const unsigned char d)
Converts unsigned char to float with pixel translations and care for overflows (underflows are assumed to cast to 0!)
static float ToFloat (const short int d)
Converts short int to float with pixel translations and care for overflows (underflows are assumed to cast to 0!)
static float ToFloat (const short unsigned int d)
Converts short unsigned int to float with pixel translations and care for overflows (underflows are assumed to cast to 0!)
static float ToFloat (const double d)
Converts double to float with pixel translations and care for overflows (underflows are assumed to cast to 0!)
static std::string ToString (double d)
Takes a double pixel value and returns the name of the pixel type as a string.
static bool IsSpecial (const double d)
Returns true if the input pixel is special.
static bool IsSpecial (const float f)
Returns true if the input pixel is special.
static bool IsValid (const double d)
Returns true if the input pixel is valid.
static bool IsNull (const double d)
Returns true if the input pixel is null.
static bool IsHigh (const double d)
Returns true if the input pixel is one of the high saturation types.
static bool IsLow (const double d)
Returns true if the input pixel is one of the low saturation types.
static bool IsHrs (const double d)
Returns true if the input pixel is high representation saturation.
static bool IsHis (const double d)
Returns true if the input pixel is high instrument saturation.
static bool IsLis (const double d)
Returns true if the input pixel is low instrument saturation.
static bool IsLrs (const double d)
Returns true if the input pixel is low representation saturation.
Detailed Description
Stores information about a "Spectral pixel" or spectel.
Author
2015-05-11 Kristin Berry (5/11/2015)
Constructor & Destructor Documentation
Spectel() [1/4]
Isis::Spectel::Spectel ()
Constructs an empty Spectel.
Author
2015-06-11 Stuart Sides
References Isis::Null.
Spectel() [2/4]
Isis::Spectel::Spectel (int sample, int line, int band, double DN, double center, double width)
Constructs a Spectel using its l,s,b coordinates, its DN value, and its wavelength.
Author
2015-05-08 Kristin Berry (5/8/2015)
Parameters
line spectel line coordinate
sample spectel sample coordinate
band spectel band coordinate
DN spectel value
center center wavelength of spectel
width wavelength width of spectel
Spectel() [3/4]
Isis::Spectel::Spectel (Pixel pixel, double center, double width)
Constructs a Spectel, given a Pixel, center wavelength, and width.
Author
2015-08-09 Kristin Berry
Parameters
pixel Pixel used to create the Spectel
center Center wavelength of the Spectel
width Width of the Spectel
Spectel() [4/4]
Isis::Spectel::Spectel (const Spectel & spectel)
Constructs a Spectel, given a Spectel.
Author
2015-08-06 Kristin Berry
Parameters
spectel Spectel to copy
References centerWavelength(), and filterWidth().
~Spectel()
Isis::Spectel::~Spectel () virtual
Default destructor.
Member Function Documentation
band()
int Isis::Pixel::band () const inherited
Returns
int The band coordinate of the Pixel
Referenced by Isis::Pixel::operator=(), and Isis::Pixel::Pixel().
centerWavelength()
double Isis::Spectel::centerWavelength () const
Gets central wavelength of spectel.
Author
kberry (5/11/2015)
Returns
double center wavelength of spectel
Referenced by Isis::SpectralDefinition1D::findSpectel(), Isis::SpectralDefinition2D::findSpectel(), operator=(), Spectel(), and Isis::SpectralDefinition2D::toString().
DN()
double Isis::Pixel::DN () const inherited
Returns
double The DN value of the Pixel
Referenced by Isis::Pixel::operator=(), and Isis::Pixel::Pixel().
filterWidth()
double Isis::Spectel::filterWidth () const
Gets wavelength width associated with spectel.
Author
kberry (5/11/2015)
Returns
double wavelength width of spectel
Referenced by operator=(), Spectel(), and Isis::SpectralDefinition2D::toString().
IsHigh() [1/2]
bool Isis::Pixel::IsHigh () inline inherited
Returns true if the input pixel is one of the high saturation types.
Returns
bool
IsHigh() [2/2]
static bool Isis::Pixel::IsHigh (const double d) inline static inherited
Returns true if the input pixel is one of the high saturation types.
Parameters
d Pixel value to test
Returns
bool
References Isis::HIGH_INSTR_SAT8, and Isis::HIGH_REPR_SAT8.
IsHis() [1/2]
bool Isis::Pixel::IsHis () inline inherited
Returns true if the input pixel is high instrument saturation.
Returns
bool
IsHis() [2/2]
static bool Isis::Pixel::IsHis (const double d) inline static inherited
Returns true if the input pixel is high instrument saturation.
Parameters
d Pixel value to test
Returns
bool
References Isis::HIGH_INSTR_SAT8.
IsHrs() [1/2]
bool Isis::Pixel::IsHrs () inline inherited
Returns true if the input pixel is high representation saturation.
Returns
bool
IsHrs() [2/2]
static bool Isis::Pixel::IsHrs (const double d) inline static inherited
Returns true if the input pixel is high representation saturation.
Parameters
d Pixel value to test
Returns
bool
References Isis::HIGH_REPR_SAT8.
IsLis() [1/2]
bool Isis::Pixel::IsLis () inline inherited
Returns true if the input pixel is low instrument saturation.
Returns
bool
IsLis() [2/2]
static bool Isis::Pixel::IsLis (const double d) inline static inherited
Returns true if the input pixel is low instrument saturation.
Parameters
d Pixel value to test
Returns
bool
References Isis::LOW_INSTR_SAT8.
IsLow() [1/2]
bool Isis::Pixel::IsLow () inline inherited
Returns true if the input pixel is one of the low saturation types.
Returns
bool
IsLow() [2/2]
static bool Isis::Pixel::IsLow (const double d) inline static inherited
Returns true if the input pixel is one of the low saturation types.
Parameters
d Pixel value to test
Returns
bool
References Isis::LOW_INSTR_SAT8, and Isis::LOW_REPR_SAT8.
IsLrs() [1/2]
bool Isis::Pixel::IsLrs () inline inherited
Returns true if the input pixel is low representation saturation.
Returns
bool
IsLrs() [2/2]
static bool Isis::Pixel::IsLrs (const double d) inline static inherited
Returns true if the input pixel is low representation saturation.
Parameters
d Pixel value to test
Returns
bool
References Isis::LOW_REPR_SAT8.
IsNull() [1/2]
bool Isis::Pixel::IsNull () inline inherited
Returns true if the input pixel is null.
Returns
bool
IsNull() [2/2]
static bool Isis::Pixel::IsNull (const double d) inline static inherited
Returns true if the input pixel is null.
Parameters
d Pixel value to test
Returns
bool
References Isis::NULL8.
IsSpecial() [1/3]
bool Isis::Pixel::IsSpecial () inline inherited
Returns true if the input pixel is special.
Not special implies it is valid to use in computations.
Returns
bool
IsSpecial() [2/3]
static bool Isis::Pixel::IsSpecial (const double d) inline static inherited
Returns true if the input pixel is special.
Not special implies it is valid to use in computations.
Parameters
d Pixel value to test
Returns
bool
References Isis::VALID_MIN8.
IsSpecial() [3/3]
static bool Isis::Pixel::IsSpecial (const float f) inline static inherited
Returns true if the input pixel is special.
Not special implies it is valid to use in computations. This method applies to a 4-byte floating point rather than an 8-byte double.
Parameters
f Pixel value to test
Returns
bool
References Isis::VALID_MIN4.
IsValid() [1/2]
bool Isis::Pixel::IsValid () inline inherited
Returns true if the input pixel is valid.
Valid implies the pixel is neither hrs, lrs, his, lis, nor null.
Returns
bool
IsValid() [2/2]
static bool Isis::Pixel::IsValid (const double d) inline static inherited
Returns true if the input pixel is valid.
Valid implies the pixel is neither hrs, lrs, his, lis, nor null.
Parameters
d Pixel value to test
Returns
bool
References Isis::VALID_MIN8.
line()
int Isis::Pixel::line () const inherited
Returns
int The line coordinate of the Pixel
Referenced by Isis::Pixel::operator=(), and Isis::Pixel::Pixel().
operator=()
Spectel & Isis::Spectel::operator= (const Spectel & other)
Copy assignment operator.
References centerWavelength(), filterWidth(), and Isis::Pixel::operator=().
sample()
int Isis::Pixel::sample () const inherited
Returns
int The sample coordinate of the Pixel
Referenced by Isis::SpectralDefinition2D::findSpectel(), Isis::Pixel::operator=(), and Isis::Pixel::Pixel().
To16Bit() [1/2]
short int Isis::Pixel::To16Bit () inherited
Converts internal pixel value to a short int pixel with special pixel translations.
Returns
short int The short int pixel value
To16Bit() [2/2]
short int Isis::Pixel::To16Bit (const double d) static inherited
Converts double pixels to short int pixels with special pixel translations.
Parameters
d Double pixel value to be converted to a double
Returns
short int The short int pixel value
References Isis::HIGH_INSTR_SAT2, Isis::HIGH_INSTR_SAT8, Isis::HIGH_REPR_SAT2, Isis::HIGH_REPR_SAT8, Isis::LOW_INSTR_SAT2, Isis::LOW_INSTR_SAT8, Isis::LOW_REPR_SAT2, Isis::LOW_REPR_SAT8, Isis::NULL2, Isis::NULL8, Isis::VALID_MAX2, Isis::VALID_MIN2, and Isis::VALID_MIN8.
To16Ubit()
short unsigned int Isis::Pixel::To16Ubit () inherited
Converts internal pixel value to a short int pixel with special pixel translations.
Returns
short unsigned int The short int pixel value
To16UBit()
short unsigned int Isis::Pixel::To16UBit (const double d) static inherited
Converts double pixels to short unsigned int pixels with special pixel translations.
Parameters
d Double pixel value to be converted to a double
Returns
short unsigned int The short int pixel value
References Isis::HIGH_INSTR_SAT8, Isis::HIGH_INSTR_SATU2, Isis::HIGH_REPR_SAT8, Isis::HIGH_REPR_SATU2, Isis::LOW_INSTR_SAT8, Isis::LOW_INSTR_SATU2, Isis::LOW_REPR_SAT8, Isis::LOW_REPR_SATU2, Isis::NULL8, Isis::NULLU2, Isis::VALID_MAX2, Isis::VALID_MIN2, and Isis::VALID_MIN8.
To32Bit() [1/2]
float Isis::Pixel::To32Bit () inherited
Converts internal pixel value to float with special pixel translations.
Returns
float The float pixel value
To32Bit() [2/2]
float Isis::Pixel::To32Bit (const double d) static inherited
Converts double pixels to float pixels with special pixel translations.
Parameters
d Double pixel value to be converted to a double
Returns
float The float pixel value
References Isis::HIGH_INSTR_SAT4, Isis::HIGH_INSTR_SAT8, Isis::HIGH_REPR_SAT4, Isis::HIGH_REPR_SAT8, Isis::LOW_INSTR_SAT4, Isis::LOW_INSTR_SAT8, Isis::LOW_REPR_SAT4, Isis::LOW_REPR_SAT8, Isis::NULL4, Isis::NULL8, Isis::VALID_MAX8, and Isis::VALID_MIN8.
To8Bit() [1/2]
unsigned char Isis::Pixel::To8Bit () inherited
Converts internal pixel value to an unsigned char pixel with special pixel translations.
Returns
unsigned char The unsigned char pixel value
To8Bit() [2/2]
unsigned char Isis::Pixel::To8Bit (const double d) static inherited
Converts double pixels to unsigned char pixels with special pixel translations.
Parameters
d Double pixel value to be converted to a double
Returns
unsigned char The unsigned char pixel value
References Isis::HIGH_INSTR_SAT1, Isis::HIGH_INSTR_SAT8, Isis::HIGH_REPR_SAT1, Isis::HIGH_REPR_SAT8, Isis::LOW_INSTR_SAT1, Isis::LOW_INSTR_SAT8, Isis::LOW_REPR_SAT1, Isis::LOW_REPR_SAT8, Isis::NULL1, Isis::NULL8, Isis::VALID_MAX1, Isis::VALID_MIN1, and Isis::VALID_MIN8.
ToDouble() [1/5]
double Isis::Pixel::ToDouble () inherited
Converts stored pixel value to a double.
Returns
double The double pixel value
ToDouble() [2/5]
double Isis::Pixel::ToDouble (const float d) static inherited
Converts float pixels to double pixels with special pixel translations.
Parameters
d Float pixel value to be converted to a double
Returns
double The double pixel value
References Isis::HIGH_INSTR_SAT4, Isis::HIGH_INSTR_SAT8, Isis::HIGH_REPR_SAT4, Isis::HIGH_REPR_SAT8, Isis::LOW_INSTR_SAT4, Isis::LOW_INSTR_SAT8, Isis::LOW_REPR_SAT4, Isis::LOW_REPR_SAT8, Isis::NULL4, Isis::NULL8, Isis::VALID_MAX4, and Isis::VALID_MIN4.
ToDouble() [3/5]
double Isis::Pixel::ToDouble (const short int d) static inherited
Converts short int pixels to double pixels with special pixel translations.
Parameters
d Short int pixel value to be converted to a double
Returns
double The double pixel value
References Isis::HIGH_INSTR_SAT2, Isis::HIGH_INSTR_SAT8, Isis::HIGH_REPR_SAT2, Isis::HIGH_REPR_SAT8, Isis::LOW_INSTR_SAT2, Isis::LOW_INSTR_SAT8, Isis::LOW_REPR_SAT2, Isis::LOW_REPR_SAT8, Isis::NULL2, Isis::NULL8, and Isis::VALID_MIN2.
ToDouble() [4/5]
double Isis::Pixel::ToDouble (const short unsigned int d) static inherited
Converts short unsigned int pixels to double pixels with special pixel translations.
Parameters
d Short unsigned int pixel value to be converted to a double
Returns
double The double pixel value
References Isis::HIGH_INSTR_SAT8, Isis::HIGH_INSTR_SATU2, Isis::HIGH_REPR_SAT8, Isis::HIGH_REPR_SATU2, Isis::LOW_INSTR_SAT8, Isis::LOW_INSTR_SATU2, Isis::LOW_REPR_SAT8, Isis::LOW_REPR_SATU2, Isis::NULL8, Isis::NULLU2, and Isis::VALID_MINU2.
ToDouble() [5/5]
double Isis::Pixel::ToDouble (const unsigned char d) static inherited
Converts unsigned char pixels to double pixels with special pixel translations.
Parameters
d Unsigned char pixel value to be converted to a double
Returns
double The double pixel value
References Isis::HIGH_INSTR_SAT1, Isis::HIGH_INSTR_SAT8, Isis::HIGH_REPR_SAT1, Isis::HIGH_REPR_SAT8, Isis::LOW_INSTR_SAT1, Isis::LOW_INSTR_SAT8, Isis::LOW_REPR_SAT1, Isis::LOW_REPR_SAT8, Isis::NULL1, Isis::NULL8, Isis::VALID_MAX1, and Isis::VALID_MIN1.
ToFloat() [1/5]
float Isis::Pixel::ToFloat () inherited
Converts internal pixel value to float with pixel translations and care for overflows (underflows are assumed to cast to 0!)
Returns
float The float pixel value
ToFloat() [2/5]
float Isis::Pixel::ToFloat (const double t) static inherited
Converts double to float with pixel translations and care for overflows (underflows are assumed to cast to 0!)
Parameters
t Double pixel value to be converted to a float
Returns
float The float pixel value
References Isis::HIGH_INSTR_SAT4, Isis::HIGH_INSTR_SAT8, Isis::HIGH_REPR_SAT4, Isis::HIGH_REPR_SAT8, Isis::LOW_INSTR_SAT4, Isis::LOW_INSTR_SAT8, Isis::LOW_REPR_SAT4, Isis::LOW_REPR_SAT8, Isis::NULL4, Isis::NULL8, Isis::VALID_MAX8, and Isis::VALID_MIN8.
ToFloat() [3/5]
float Isis::Pixel::ToFloat (const short int t) static inherited
Converts short int to float with pixel translations and care for overflows (underflows are assumed to cast to 0!)
Parameters
t Short int pixel value to be converted to a float
Returns
float The float pixel value
References Isis::HIGH_INSTR_SAT2, Isis::HIGH_INSTR_SAT4, Isis::HIGH_REPR_SAT2, Isis::HIGH_REPR_SAT4, Isis::HIGH_REPR_SAT8, Isis::LOW_INSTR_SAT2, Isis::LOW_INSTR_SAT4, Isis::LOW_REPR_SAT2, Isis::LOW_REPR_SAT4, Isis::NULL2, Isis::NULL4, Isis::VALID_MAX2, and Isis::VALID_MIN2.
ToFloat() [4/5]
float Isis::Pixel::ToFloat (const short unsigned int t) static inherited
Converts short unsigned int to float with pixel translations and care for overflows (underflows are assumed to cast to 0!)
Parameters
t Short unsigned int pixel value to be converted to a float
Returns
float The float pixel value
References Isis::HIGH_INSTR_SAT4, Isis::HIGH_INSTR_SATU2, Isis::HIGH_REPR_SAT4, Isis::HIGH_REPR_SAT8, Isis::HIGH_REPR_SATU2, Isis::LOW_INSTR_SAT4, Isis::LOW_INSTR_SATU2, Isis::LOW_REPR_SAT4, Isis::LOW_REPR_SATU2, Isis::NULL4, Isis::NULLU2, Isis::VALID_MAXU2, and Isis::VALID_MINU2.
ToFloat() [5/5]
float Isis::Pixel::ToFloat (const unsigned char t) static inherited
Converts unsigned char to float with pixel translations and care for overflows (underflows are assumed to cast to 0!)
Parameters
t Unsigned char pixel value to be converted to a float
Returns
float The float pixel value
References Isis::HIGH_INSTR_SAT1, Isis::HIGH_INSTR_SAT4, Isis::HIGH_REPR_SAT1, Isis::HIGH_REPR_SAT4, Isis::HIGH_REPR_SAT8, Isis::LOW_INSTR_SAT1, Isis::LOW_INSTR_SAT4, Isis::LOW_REPR_SAT1, Isis::LOW_REPR_SAT4, Isis::NULL1, Isis::NULL4, Isis::VALID_MAX1, and Isis::VALID_MIN1.
ToString() [1/2]
string Isis::Pixel::ToString () inherited
Returns the name of the pixel type as a string.
Returns
string The name of the pixel type
References Isis::ToString().
ToString() [2/2]
string Isis::Pixel::ToString (double d) static inherited
Takes a double pixel value and returns the name of the pixel type as a string.
Parameters
d Pixel value
Returns
string The name of the pixel type
References Isis::IsSpecial().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Spectel/Spectel.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Spectel/Spectel.cpp