Isis Developer Reference: Isis::TableView Class Reference
Isis::TableView Class Reference
#include <TableView.h>
Public Slots
void displayWarning (AbstractTableModel::Warning)
Displays warnings for a table.
void handleModelSelectionChanged ()
Handles refreshing the content when the model selection is changed.
void handleModelSelectionChanged (QList< AbstractTreeItem * >)
Signals
void activated ()
void rebuildModels (QList< AbstractTreeItem * >)
void selectionChanged ()
void modelDataChanged ()
void tableSelectionChanged (QList< AbstractTreeItem * >)
void filterCountsChanged (int visibleRows, int totalRows)
void editControlPoint (ControlPoint *, QString)
Public Member Functions
TableView (AbstractTableModel *someModel, QString pathForSettigs, QString objName)
Constructor.
virtual ~TableView ()
Destructor.
QFont getContentFont () const
TableViewHeader * getHorizontalHeader ()
Returns the horizontal header.
QStringList getTitles () const
void setTitles (QStringList someTitle)
void setColumnVisible (QString, bool)
Sets the specified column visible or invisible.
AbstractTableModel * getModel ()
Returns the model.
void readSettings ()
void writeSettings ()
TableViewContent * content ()
Returns the content of the table.
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
TableView()
Isis::TableView::TableView (AbstractTableModel * someModel, QString pathForSettings, QString objName)
Constructor.
Parameters
someModel The abstract table model to view
pathForSettings The path to read/write settings to
objName The name of the object
References displayWarning(), editControlPoint(), filterCountsChanged(), Isis::AbstractTableModel::getColumns(), Isis::TableColumn::getTitle(), handleModelSelectionChanged(), modelDataChanged(), Isis::TableColumnList::prepend(), rebuildModels(), selectionChanged(), Isis::TableColumn::setSortAscending(), Isis::TableColumnList::setSortingOrder(), Isis::TableColumn::setWidth(), Isis::TableColumnList::size(), and tableSelectionChanged().
~TableView()
Isis::TableView::~TableView () virtual
Destructor.
References Isis::TableColumnList::getSortingOrderAsStrings(), Isis::TableColumn::getTitle(), Isis::TableColumn::getWidth(), Isis::TableColumnList::size(), and Isis::TableColumn::sortAscending().
Member Function Documentation
activated
void Isis::TableView::activated () signal
content()
TableViewContent * Isis::TableView::content ()
Returns the content of the table.
Returns
TableViewContent The content of the table
Referenced by Isis::Directory::addCnetEditorView().
displayWarning
void Isis::TableView::displayWarning (AbstractTableModel::Warning warning) slot
Displays warnings for a table.
Parameters
warning The waarning that will be displayed
References Isis::TableViewContent::getModel(), Isis::AbstractTableModel::getVisibleRowCount(), Isis::AbstractTableModel::None, Isis::AbstractTableModel::SortingDisabled, Isis::AbstractTableModel::SortingTableSizeLimitReached, and Isis::AbstractTableModel::sortLimit().
Referenced by TableView().
editControlPoint
void Isis::TableView::editControlPoint (ControlPoint * , QString) signal
Referenced by TableView().
filterCountsChanged
void Isis::TableView::filterCountsChanged (int visibleRows, int totalRows) signal
Referenced by TableView().
getContentFont()
QFont Isis::TableView::getContentFont () const
getHorizontalHeader()
TableViewHeader * Isis::TableView::getHorizontalHeader ()
Returns the horizontal header.
Returns
TableViewHeader The horizontal header
Referenced by Isis::CnetEditorWidget::readSettings(), and Isis::CnetEditorWidget::writeSettings().
getModel()
AbstractTableModel * Isis::TableView::getModel ()
Returns the model.
Returns
AbstractTableModel The model
References Isis::TableViewContent::getModel().
getTitles()
QStringList Isis::TableView::getTitles () const
handleModelSelectionChanged [1/2]
void Isis::TableView::handleModelSelectionChanged () slot
Handles refreshing the content when the model selection is changed.
References Isis::TableViewContent::refresh().
Referenced by TableView().
handleModelSelectionChanged [2/2]
void Isis::TableView::handleModelSelectionChanged (QList< AbstractTreeItem * > newlySelectedItems) slot
References Isis::TableViewContent::refresh(), and Isis::TableViewContent::scrollTo().
modelDataChanged
void Isis::TableView::modelDataChanged () signal
Referenced by TableView().
readSettings()
void Isis::TableView::readSettings ()
rebuildModels
void Isis::TableView::rebuildModels (QList< AbstractTreeItem * >) signal
Referenced by TableView().
selectionChanged
void Isis::TableView::selectionChanged () signal
Referenced by TableView().
setColumnVisible()
void Isis::TableView::setColumnVisible (QString column, bool visible)
Sets the specified column visible or invisible.
Parameters
column The column to change the visibility of
visible The visibility setting
References Isis::TableColumn::getTitle(), Isis::TableColumn::setVisible(), and Isis::TableColumnList::size().
setTitles()
void Isis::TableView::setTitles (QStringList someTitle)
tableSelectionChanged
void Isis::TableView::tableSelectionChanged (QList< AbstractTreeItem * >) signal
Referenced by TableView().
writeSettings()
void Isis::TableView::writeSettings ()
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/TableView.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/TableView.cpp