Isis Developer Reference: Isis::HiHistory Class Reference
Isis::HiHistory Class Reference
#include <HiCalTypes.h>
Public Member Functions
HiHistory ()
HiHistory (const HiHistory &h)
virtual ~HiHistory ()
int size () const
void add (const QString &event)
QString get (unsigned int index=0) const
void clear ()
PvlKeyword makekey (const QString &name="History") const
Friends
std::ostream & operator<< (std::ostream &o, const HiHistory &h)
Output operator for history events.
Constructor & Destructor Documentation
HiHistory() [1/2]
Isis::HiHistory::HiHistory () inline
HiHistory() [2/2]
Isis::HiHistory::HiHistory (const HiHistory & h) inline
~HiHistory()
virtual Isis::HiHistory::~HiHistory () inline virtual
Member Function Documentation
add()
void Isis::HiHistory::add (const QString & event) inline
Referenced by Isis::ZeroBufferFit::guess(), Isis::LoadCSV::History(), Isis::LowPassFilter::LowPassFilter(), Isis::ZeroBufferFit::Normalize(), Isis::LowPassFilter::Process(), Isis::SplineFill::Process(), Isis::ZeroBufferFit::Solve(), Isis::SplineFill::SplineFill(), and Isis::ZeroBufferFit::ZeroBufferFit().
clear()
void Isis::HiHistory::clear () inline
Referenced by Isis::LowPassFilter::Process(), and Isis::SplineFill::Process().
get()
QString Isis::HiHistory::get (unsigned int index = 0) const inline
makekey()
PvlKeyword Isis::HiHistory::makekey (const QString & name = "History") const inline
References Isis::PvlKeyword::addValue().
Referenced by Isis::Module::record().
size()
int Isis::HiHistory::size () const inline
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & o, const HiHistory & h) friend
Output operator for history events.
Parameters
o Output stream
h History class to write contents of
Returns
std::ostream& Returns new state of stream
The documentation for this class was generated from the following file:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/mro/objs/HiCal/HiCalTypes.h