Isis Developer Reference: Isis::IrregularBodyCameraGroundMap Class Reference
Isis::IrregularBodyCameraGroundMap Class Reference
Convert between undistorted focal plane and ground coordinates.
#include <IrregularBodyCameraGroundMap.h>
Public Types
enum PartialType {
WRT_Latitude , WRT_Longitude , WRT_Radius , WRT_MajorAxis ,
WRT_MinorAxis , WRT_PolarAxis
}
Radius axes types to use when computing partials.
Public Member Functions
IrregularBodyCameraGroundMap (Camera *parent, const bool clip_emission_angles=false)
Constructor.
virtual ~IrregularBodyCameraGroundMap ()
Destructor.
virtual bool GetXY (const SurfacePoint &spoint, double *cudx, double *cudy)
This method computes the undistorted focal plane coordinates for a ground position, using the current Spice settings (time and kernels) without resetting the current point values for lat/lon/radius/x/y.
virtual bool SetFocalPlane (const double ux, const double uy, const double uz)
Compute ground position from focal plane coordinate.
virtual bool SetGround (const Latitude &lat, const Longitude &lon)
Compute undistorted focal plane coordinate from ground position.
virtual bool SetGround (const SurfacePoint &surfacePoint)
Compute undistorted focal plane coordinate from ground position that includes a local radius.
virtual bool GetXY (const SurfacePoint &spoint, double *cudx, double *cudy, bool test=true)
Compute undistorted focal plane coordinate from ground position using current Spice from SetImage call.
virtual bool GetXY (const double lat, const double lon, const double radius, double *cudx, double *cudy)
Compute undistorted focal plane coordinate from ground position using current Spice from SetImage call.
virtual bool GetdXYdPosition (const SpicePosition::PartialType varType, int coefIndex, double *cudx, double *cudy)
Compute derivative w/r to position of focal plane coordinate from ground position using current Spice from SetImage call.
virtual bool GetdXYdOrientation (const SpiceRotation::PartialType varType, int coefIndex, double *cudx, double *cudy)
Compute derivative of focal plane coordinate w/r to instrument using current state from SetImage call.
virtual bool GetdXYdTOrientation (const SpiceRotation::PartialType varType, int coefIndex, double *cudx, double *cudy)
Compute derivative of focal plane coordinate w/r to target body using current state.
virtual bool GetdXYdPoint (std::vector< double > d_pB, double *dx, double *dy)
Compute derivative of focal plane coordinate w/r to ground point using current state.
std::vector< double > PointPartial (SurfacePoint spoint, PartialType wrt)
Compute derivative with respect to indicated variable of conversion function from lat/lon/rad to rectangular coord.
std::vector< double > EllipsoidPartial (SurfacePoint spoint, PartialType raxis)
Compute derivative of focal plane coordinate w/r to one of the ellipsoidal radii (a, b, or c)
std::vector< double > MeanRadiusPartial (SurfacePoint spoint, Distance meanRadius)
Compute derivative of focal plane coordinate w/r to mean of the ellipsoidal radii (a, b, c)
double DQuotient (std::vector< double > &look, std::vector< double > &dlook, int index)
Convenience method for quotient rule applied to look vector.
double FocalPlaneX () const
double FocalPlaneY () const
Protected Member Functions
void LookCtoFocalPlaneXY ()
Calculate focalplane x/y from lookvector in camera.
Protected Attributes
bool m_clip_emission
Camera * p_camera
Camera.
double p_focalPlaneX
Camera's x focal plane coordinate.
double p_focalPlaneY
Camera's y focal plane coordinate.
std::vector< double > m_pB
Surface point calculated from ground coordinates in GetXY and used for partials.
std::vector< double > m_lookJ
Look vector in J2000 calculated from ground coordinates in GetXY and used for partials.
Detailed Description
Convert between undistorted focal plane and ground coordinates.
This class is derived from CameraGroundMap to support the special case of irregular bodies. Particularly, only the GetXY() method is reimplemented here to never perform the "emission angle" (in places called "back-of-the- planet") test. This is because the test uses the ellipsoid to validate ground point visibility along the look vector to the surface. This is not adequate for most irregular bodies.
See also
CameraGroundMap
Author
2018-07-26 UA/OSIRIS-REx IPWG Team
Member Enumeration Documentation
PartialType
enum Isis::CameraGroundMap::PartialType inherited
Radius axes types to use when computing partials.
When computing partials, this enum represents the "with respect to" variable in the computation.
Enumerator
WRT_Latitude
WRT_Longitude
WRT_Radius
WRT_MajorAxis
WRT_MinorAxis
WRT_PolarAxis
Constructor & Destructor Documentation
IrregularBodyCameraGroundMap()
Isis::IrregularBodyCameraGroundMap::IrregularBodyCameraGroundMap (Camera * parent, const bool clip_emission_angles = false)
Constructor.
Parameters
parent Pointer to camera to be used for mapping with ground
~IrregularBodyCameraGroundMap()
virtual Isis::IrregularBodyCameraGroundMap::~IrregularBodyCameraGroundMap () inline virtual
Destructor.
Member Function Documentation
DQuotient()
double Isis::CameraGroundMap::DQuotient (std::vector< double > & look, std::vector< double > & dlook, int index) inherited
Convenience method for quotient rule applied to look vector.
This method will compute the derivative of the following function (coordinate x or y) / (coordinate z)
Parameters
look look vector in camera frame
dlook derivative of look vector in camera frame
index vector value to differentiate
Returns
double derivative Computed derivative
EllipsoidPartial()
vector< double > Isis::CameraGroundMap::EllipsoidPartial (SurfacePoint spoint, PartialType raxis) inherited
Compute derivative of focal plane coordinate w/r to one of the ellipsoidal radii (a, b, or c)
This method will compute the derivative of the undistorted focal plane coordinate for a ground position with respect to the a (major axis), b (minor axis), or c (polar axis) radius, using the current Spice settings (time and kernels) without resetting the current point values for lat/lon/radius/x/y.
Parameters
spoint Surface point whose derivative is to be evalutated
raxis Radius axis enumerated partial type (definitions in this header)
Exceptions
IException::Programmer "Invalid partial type for this method"
Returns
vector<double> partialDerivative of body-fixed point with respect to selected ellipsoid axis
References _FILEINFO_, Isis::SurfacePoint::GetLatitude(), Isis::SurfacePoint::GetLongitude(), and Isis::Angle::radians().
Referenced by Isis::IsisBundleObservation::computeTargetPartials().
FocalPlaneX()
double Isis::CameraGroundMap::FocalPlaneX () const inline inherited
Returns
The undistorted focal plane x
References Isis::CameraGroundMap::p_focalPlaneX.
FocalPlaneY()
double Isis::CameraGroundMap::FocalPlaneY () const inline inherited
Returns
The undistorted focal plane y
References Isis::CameraGroundMap::p_focalPlaneY.
GetdXYdOrientation()
bool Isis::CameraGroundMap::GetdXYdOrientation (const SpiceRotation::PartialType varType, int coefIndex, double * dx, double * dy) virtual inherited
Compute derivative of focal plane coordinate w/r to instrument using current state from SetImage call.
This method will compute the derivative of the undistorted focal plane coordinate for a ground position with respect to the instrument orientation, using the current Spice settings (time and kernels) without resetting the current point values for lat/lon/radius/x/y.
Parameters
varType enumerated partial type (definitions in SpicePosition)
coefIndex coefficient index of fit polynomial
*dx out] pointer to partial derivative of undistorted focal plane x
*dy [out] pointer to partial derivative of undistorted focal plane y
Returns
bool If conversion was successful
References Isis::SpiceRotation::ReferenceVector(), and Isis::SpiceRotation::ToReferencePartial().
Referenced by Isis::IsisBundleObservation::computeImagePartials().
GetdXYdPoint()
bool Isis::CameraGroundMap::GetdXYdPoint (std::vector< double > d_pB, double * dx, double * dy) virtual inherited
Compute derivative of focal plane coordinate w/r to ground point using current state.
This method will compute the derivative of the undistorted focal plane coordinate for a ground position with respect to lat, lon, or radius, using the current Spice settings (time and kernels) without resetting the current point values for lat/lon/radius/x/y.
Parameters
d_pB Point vector
*dx [out] pointer to partial derivative of undistorted focal plane x
*dy [out] pointer to partial derivative of undistorted focal plane y
Returns
conversion was successful
Reimplemented in Isis::RadarGroundMap.
References Isis::SpiceRotation::J2000Vector(), and Isis::SpiceRotation::ReferenceVector().
Referenced by Isis::IsisBundleObservation::computePoint3DPartials(), and Isis::IsisBundleObservation::computeTargetPartials().
GetdXYdPosition()
bool Isis::CameraGroundMap::GetdXYdPosition (const SpicePosition::PartialType varType, int coefIndex, double * dx, double * dy) virtual inherited
Compute derivative w/r to position of focal plane coordinate from ground position using current Spice from SetImage call.
This method will compute the derivative of the undistorted focal plane coordinate for a ground position with respect to a spacecraft position coordinate, using the current Spice settings (time and kernels) without resetting the current point values for lat/lon/radius/x/y.
Parameters
varType enumerated partial type (definitions in SpicePosition)
coefIndex coefficient index of fit polynomial
*dx [out] pointer to partial derivative of undistorted focal plane x
*dy [out] pointer to partial derivative of undistorted focal plane y
Returns
bool If conversion was successful
Reimplemented in Isis::RadarGroundMap.
References Isis::SpicePosition::CoordinatePartial(), and Isis::SpiceRotation::ReferenceVector().
Referenced by Isis::IsisBundleObservation::computeImagePartials().
GetdXYdTOrientation()
bool Isis::CameraGroundMap::GetdXYdTOrientation (const SpiceRotation::PartialType varType, int coefIndex, double * dx, double * dy) virtual inherited
Compute derivative of focal plane coordinate w/r to target body using current state.
This method will compute the derivative of the undistorted focal plane coordinate for a ground position with respect to the target body orientation, using the current Spice settings (time and kernels) without resetting the current point values for lat/lon/radius/x/y.
Parameters
varType enumerated partial type (definitions in SpicePosition)
coefIndex coefficient index of fit polynomial
*dx [out] pointer to partial derivative of undistorted focal plane x
*dy [out] pointer to partial derivative of undistorted focal plane y
Returns
bool If conversion was successful
References Isis::SpiceRotation::ReferenceVector(), and Isis::SpiceRotation::toJ2000Partial().
Referenced by Isis::IsisBundleObservation::computeTargetPartials().
GetXY() [1/3]
bool Isis::CameraGroundMap::GetXY (const double lat, const double lon, const double radius, double * cudx, double * cudy) virtual inherited
Compute undistorted focal plane coordinate from ground position using current Spice from SetImage call.
This method will compute the undistorted focal plane coordinate for a ground position, using the current Spice settings (time and kernels) without resetting the current point values for lat/lon/radius/m_pB/x/y. The class value for m_lookJ is set by this method.
Parameters
lat Latitude in degrees
lon Longitude in degrees
radius Radius in meters
cudx [out] Pointer to computed undistored x focal plane coordinate
cudy [out] Pointer to computed undistored y focal plane coordinate
Returns
bool If conversion was successful
See also
the application socetlinescankeywords
GetXY() [2/3]
bool Isis::IrregularBodyCameraGroundMap::GetXY (const SurfacePoint & point, double * cudx, double * cudy) virtual
This method computes the undistorted focal plane coordinates for a ground position, using the current Spice settings (time and kernels) without resetting the current point values for lat/lon/radius/x/y.
The class value value for m_pB and m_lookJ are set by this method.
This method has been reimplemented from the CameraGroundMap class to never perform the emission angle check. This is because it uses the ellipsoid for the check which is in general not adequate for irregular bodies.
Parameters
point Surface point (ground position)
cudx [out] Pointer to computed undistored x focal plane coordinate
cudy [out] Pointer to computed undistored y focal plane coordinate
Returns
bool If conversion was successful
References Isis::CameraGroundMap::GetXY(), and m_clip_emission.
GetXY() [3/3]
bool Isis::CameraGroundMap::GetXY (const SurfacePoint & point, double * cudx, double * cudy, bool test = true) virtual inherited
Compute undistorted focal plane coordinate from ground position using current Spice from SetImage call.
This method will compute the undistorted focal plane coordinate for a ground position, using the current Spice settings (time and kernels) without resetting the current point values for lat/lon/radius/m_pB/x/y. The class value for m_lookJ is set by this method.
Parameters
point Surface point (ground position)
cudx [out] Pointer to computed undistorted x focal plane coordinate
cudy [out] Pointer to computed undistorted y focal plane coordinate
test Optional parameter to indicate whether to do the back-of-planet test.
Returns
bool If conversion was successful
Reimplemented in Isis::RadarGroundMap.
References Isis::SurfacePoint::GetX(), Isis::SurfacePoint::GetY(), Isis::SurfacePoint::GetZ(), Isis::SpiceRotation::J2000Vector(), Isis::Displacement::kilometers(), Isis::PI, and Isis::SpiceRotation::ReferenceVector().
Referenced by Isis::ControlPoint::ComputeResiduals(), Isis::ControlPoint::ComputeResiduals_Millimeters(), Isis::IsisBundleObservation::computeRHSPartials(), and GetXY().
LookCtoFocalPlaneXY()
void Isis::CameraGroundMap::LookCtoFocalPlaneXY () protected inherited
Calculate focalplane x/y from lookvector in camera.
Compute undistorted focal plane coordinate from camera look vector.
MeanRadiusPartial()
vector< double > Isis::CameraGroundMap::MeanRadiusPartial (SurfacePoint spoint, Distance meanRadius) inherited
Compute derivative of focal plane coordinate w/r to mean of the ellipsoidal radii (a, b, c)
This method will compute the derivative of the undistorted focal plane coordinate for a ground position with respect to the mean of the a (major axis), b (minor axis), and c (polar axis) radius, using the current Spice settings (time and kernels) without resetting the current point values for lat/lon/radius/x/y.
Parameters
spoint Surface point whose derivative is to be evalutated
meanRadius Computed mean of radii
Returns
vector<double> partialDerivative of body-fixed point with respect to mean radius TODO This method assumes the radii of all points in the adjustment have been set identically to the ???
References Isis::SurfacePoint::GetX(), Isis::SurfacePoint::GetY(), Isis::SurfacePoint::GetZ(), Isis::Displacement::kilometers(), and Isis::Distance::kilometers().
Referenced by Isis::IsisBundleObservation::computeTargetPartials().
PointPartial()
vector< double > Isis::CameraGroundMap::PointPartial (SurfacePoint spoint, PartialType wrt) inherited
Compute derivative with respect to indicated variable of conversion function from lat/lon/rad to rectangular coord.
Parameters
spoint Surface point (ground position)
wrt take derivative with respect to this value
Returns
vector<double> partialDerivative Computed derivative
References Isis::SurfacePoint::GetLatitude(), Isis::SurfacePoint::GetLocalRadius(), Isis::SurfacePoint::GetLongitude(), Isis::Distance::kilometers(), and Isis::Angle::radians().
SetFocalPlane()
bool Isis::CameraGroundMap::SetFocalPlane (const double ux, const double uy, const double uz) virtual inherited
Compute ground position from focal plane coordinate.
This method will compute the ground position given an undistorted focal plane coordinate. Note that the latitude/longitude value can be obtained from the camera pointer passed into the constructor.
Parameters
ux undistorted focal plane x in millimeters
uy undistorted focal plane y in millimeters
uz undistorted focal plane z in millimeters
Returns
bool If conversion was successful
Reimplemented in Isis::VimsGroundMap, and Isis::RadarGroundMap.
Referenced by Isis::Camera::SetImage().
SetGround() [1/2]
bool Isis::CameraGroundMap::SetGround (const Latitude & lat, const Longitude & lon) virtual inherited
Compute undistorted focal plane coordinate from ground position.
Parameters
lat planetocentric latitude in degrees
lon planetocentric longitude in degrees
Returns
bool If conversion was successful
Reimplemented in Isis::VimsGroundMap, Isis::RadarGroundMap, Isis::PushFrameCameraGroundMap, and Isis::LineScanCameraGroundMap.
References Isis::Angle::degrees(), and Isis::Distance::isValid().
Referenced by Isis::PushFrameCameraGroundMap::SetGround(), Isis::Camera::SetGround(), and Isis::Camera::SetUniversalGround().
SetGround() [2/2]
bool Isis::CameraGroundMap::SetGround (const SurfacePoint & surfacePoint) virtual inherited
Compute undistorted focal plane coordinate from ground position that includes a local radius.
Parameters
surfacePoint Surface point (ground position)
Returns
bool If conversion was successful
Reimplemented in Isis::PushFrameCameraGroundMap, Isis::VimsGroundMap, Isis::RadarGroundMap, and Isis::LineScanCameraGroundMap.
Member Data Documentation
m_clip_emission
bool Isis::IrregularBodyCameraGroundMap::m_clip_emission protected
Referenced by GetXY().
m_lookJ
std::vector<double> Isis::CameraGroundMap::m_lookJ protected inherited
Look vector in J2000 calculated from ground coordinates in GetXY and used for partials.
m_pB
std::vector<double> Isis::CameraGroundMap::m_pB protected inherited
Surface point calculated from ground coordinates in GetXY and used for partials.
p_camera
Camera* Isis::CameraGroundMap::p_camera protected inherited
Camera.
Referenced by Isis::LineScanCameraGroundMap::FindFocalPlane(), Isis::LineScanCameraGroundMap::FindSpacecraftDistance(), Isis::VimsGroundMap::Init(), Isis::VimsGroundMap::SetFocalPlane(), Isis::LineScanCameraGroundMap::SetGround(), Isis::PushFrameCameraGroundMap::SetGround(), and Isis::VimsGroundMap::SetGround().
p_focalPlaneX
double Isis::CameraGroundMap::p_focalPlaneX protected inherited
Camera's x focal plane coordinate.
Referenced by Isis::LineScanCameraGroundMap::FindFocalPlane(), Isis::CameraGroundMap::FocalPlaneX(), Isis::VimsGroundMap::SetGround(), and Isis::RadarGroundMap::SetGround().
p_focalPlaneY
double Isis::CameraGroundMap::p_focalPlaneY protected inherited
Camera's y focal plane coordinate.
Referenced by Isis::LineScanCameraGroundMap::FindFocalPlane(), Isis::CameraGroundMap::FocalPlaneY(), Isis::VimsGroundMap::SetGround(), and Isis::RadarGroundMap::SetGround().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/IrregularBodyCameraGroundMap/IrregularBodyCameraGroundMap.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/IrregularBodyCameraGroundMap/IrregularBodyCameraGroundMap.cpp