Isis Developer Reference: Isis::ImageOverlap Class Reference
Isis::ImageOverlap Class Reference
Control Networks
Individual overlap container.
#include <ImageOverlap.h>
Public Member Functions
ImageOverlap ()
Construct an empty ImageOverlap object.
ImageOverlap (QString serialNumber, geos::geom::MultiPolygon &polygon)
Construct an ImageOverlap object and initialize it with the arguments.
ImageOverlap (std::istream &inputStream)
Construct an ImageOverlap object and initialize it from the istream.
virtual ~ImageOverlap ()
Destroy this ImageOverlap object.
virtual void SetPolygon (const geos::geom::MultiPolygon &polygon)
This method will replace the existing polygon that defines the overlap with a new one.
virtual void SetPolygon (const geos::geom::MultiPolygon *polygon)
This method will replace the existing polygon that defines the overlap with a new one.
void Add (QString &sn)
This method will add a new serial number to the list of serial numbers alread associated with the overlap.
int Size () const
QString operator[] (int index) const
const geos::geom::MultiPolygon * Polygon () const
virtual double Area ()
This method will return the area of the polygon.
bool HasAnySameSerialNumber (ImageOverlap &other) const
This method will return true if any serial number from this ImageOverlap is also in the other ImageOverlap.
bool HasSerialNumber (QString &sn) const
This method will return true if input serial number exists in the ImageOverlap.
void Write (std::ostream &outputStream)
Detailed Description
Individual overlap container.
Hold information about a single area of overlap. This includes the serial numbers of each cube that overlap this area and the polygon that defines this area.
Author
2005-08-03 Stuart Sides
Constructor & Destructor Documentation
ImageOverlap() [1/3]
Isis::ImageOverlap::ImageOverlap ()
Construct an empty ImageOverlap object.
ImageOverlap() [2/3]
Isis::ImageOverlap::ImageOverlap (QString serialNumber, geos::geom::MultiPolygon & polygon)
Construct an ImageOverlap object and initialize it with the arguments.
Parameters
serialNumber The initial serial number assiciated with the polygon.
polygon The polygon that defines the overlap area.
References Add(), and SetPolygon().
ImageOverlap() [3/3]
Isis::ImageOverlap::ImageOverlap (std::istream & inputStream)
Construct an ImageOverlap object and initialize it from the istream.
Parameters
inputStream A stream containing a representation of the image overlap
References Add(), and Isis::PolygonTools::MakeMultiPolygon().
~ImageOverlap()
Isis::ImageOverlap::~ImageOverlap () virtual
Destroy this ImageOverlap object.
Member Function Documentation
Add()
void Isis::ImageOverlap::Add (QString & sn)
This method will add a new serial number to the list of serial numbers alread associated with the overlap.
Parameters
sn The serial number to be added to the list.
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by Isis::ImageOverlapSet::AddSerialNumbers(), and ImageOverlap().
Area()
double Isis::ImageOverlap::Area () virtual
This method will return the area of the polygon.
This member does not assume any particular units of measure for the verticies of the polygon. It is provided as a convience.
HasAnySameSerialNumber()
bool Isis::ImageOverlap::HasAnySameSerialNumber (ImageOverlap & other) const
This method will return true if any serial number from this ImageOverlap is also in the other ImageOverlap.
References Size().
HasSerialNumber()
bool Isis::ImageOverlap::HasSerialNumber (QString & sn) const
This method will return true if input serial number exists in the ImageOverlap.
Parameters
[in] sn (QString &) Serial Number to search for
Returns
bool Returns true if the serial number exists in the ImageOverlap.
References Size().
Referenced by Isis::InterestOperator::FindOverlap().
operator[]()
QString Isis::ImageOverlap::operator[] (int index) const inline
Polygon()
const geos::geom::MultiPolygon* Isis::ImageOverlap::Polygon () const inline
SetPolygon() [1/2]
void Isis::ImageOverlap::SetPolygon (const geos::geom::MultiPolygon & polygon) virtual
This method will replace the existing polygon that defines the overlap with a new one.
Parameters
polygon The new polygon.
References Isis::PolygonTools::CopyMultiPolygon().
Referenced by ImageOverlap().
SetPolygon() [2/2]
void Isis::ImageOverlap::SetPolygon (const geos::geom::MultiPolygon * polygon) virtual
This method will replace the existing polygon that defines the overlap with a new one.
Parameters
polygon The new polygon.
References Isis::PolygonTools::CopyMultiPolygon().
Size()
int Isis::ImageOverlap::Size () const inline
Referenced by Isis::ImageOverlapSet::AddSerialNumbers(), Isis::InterestOperator::FindOverlap(), HasAnySameSerialNumber(), and HasSerialNumber().
Write()
void Isis::ImageOverlap::Write (std::ostream & outputStream)
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ImageOverlap/ImageOverlap.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ImageOverlap/ImageOverlap.cpp