Isis Developer Reference: Isis::RadarPulseMap Class Reference
Isis::RadarPulseMap Class Reference
Convert between alpha image coordinates and radar sample, time coordinates.
#include <RadarPulseMap.h>
Public Member Functions
RadarPulseMap (Camera *parent, const double etStart, const double lineRate)
Construct a detector map for line scan cameras.
virtual ~RadarPulseMap ()
Destructor.
void SetStartTime (const double etStart)
Reset the starting ephemeris time.
void SetLineRate (const double lineRate)
Reset the line rate.
double LineRate () const
Return the time in seconds between scan lines.
virtual bool SetParent (const double sample, const double line)
Compute radar (sample/time)from a alpha image coordinate.
virtual bool SetDetector (const double sample, const double line)
Compute alpha position from a detector coordinate.
void SetXAxisTimeDependent (bool on)
Set the time dependent axis, if never called y is the time dependent axis.
virtual bool SetParent (const double sample, const double line, const double deltaT)
Compute detector position from a parent image coordinate.
double AdjustedStartingSample () const
Return the starting detector sample adjusted for summation.
double AdjustedStartingLine () const
Return the starting detector line adjusted for summation.
double ParentSample () const
Return parent sample.
double ParentLine () const
Return parent line.
double DetectorSample () const
Return detector sample.
double DetectorLine () const
Return detector line.
void SetStartingDetectorSample (const double sample)
Set the starting detector sample.
void SetStartingDetectorLine (const double line)
Set the starting detector line.
void SetDetectorSampleSumming (const double summing)
Set sample summing mode.
void SetDetectorLineSumming (const double summing)
Set line summing mode.
virtual double SampleScaleFactor () const
Return scaling factor for computing sample resolution.
virtual double LineScaleFactor () const
Return scaling factor for computing line resolution.
virtual double exposureDuration (const double sample, const double line, const int band) const
This virtual method is for returning the exposure duration of a given pixel.
Protected Attributes
Camera * p_camera
Pointer to the camera.
double p_parentSample
The parent sample calculated from the detector.
double p_parentLine
The parent line calculated from the detector.
double p_detectorLine
Detector coordinate line value.
double p_detectorSample
Detector coordinate sample value.
double p_detectorSampleSumming
The scaling factor for computing sample resolution.
double p_detectorLineSumming
The scaling factor for computing line resolution.
double p_startingDetectorSample
Detector start coordinate sample value.
double p_startingDetectorLine
Detector start coordinate line value.
double p_ss
Start sample.
double p_sl
Start line.
Detailed Description
Convert between alpha image coordinates and radar sample, time coordinates.
This class is used to convert between alpha coordinates (sample/line) and radar pulse coordinates (sample,time) for a radar instrument.
See also
Camera
Author
2008-06-16 Jeff Anderson
Constructor & Destructor Documentation
RadarPulseMap()
Isis::RadarPulseMap::RadarPulseMap (Camera * parent, const double etStart, const double lineRate) inline
Construct a detector map for line scan cameras.
Parameters
parent The parent camera model for the detector map
etStart starting ephemeris time in seconds at the top of the first line
lineRate the time in seconds between lines
~RadarPulseMap()
virtual Isis::RadarPulseMap::~RadarPulseMap () inline virtual
Destructor.
Member Function Documentation
AdjustedStartingLine()
double Isis::CameraDetectorMap::AdjustedStartingLine () const inherited
Return the starting detector line adjusted for summation.
Returns
(double) The starting line
References Isis::CameraDetectorMap::p_sl.
AdjustedStartingSample()
double Isis::CameraDetectorMap::AdjustedStartingSample () const inherited
Return the starting detector sample adjusted for summation.
Returns
(double) The starting sample
References Isis::CameraDetectorMap::p_ss.
DetectorLine()
double Isis::CameraDetectorMap::DetectorLine () const inherited
Return detector line.
Returns
(double) The detector line
References Isis::CameraDetectorMap::p_detectorLine.
Referenced by Isis::Camera::SetImage().
DetectorSample()
double Isis::CameraDetectorMap::DetectorSample () const inherited
Return detector sample.
Returns
(double) The detector sample
References Isis::CameraDetectorMap::p_detectorSample.
Referenced by Isis::Camera::SetImage().
exposureDuration()
double Isis::CameraDetectorMap::exposureDuration (const double sample, const double line, const int band) const virtual inherited
This virtual method is for returning the exposure duration of a given pixel.
For framing cameras, exposure duration is not available so it throws an error.
Parameters
sample The sample of the desired pixel.
line The line of the desired pixel.
band The band of the desired pixel.
Returns
double The exposure duration for the desired pixel in seconds.
Exceptions
IException::Programmer "Exposure duration is only available for LineScan, VariableLineScan, and PushFrame Cameras."
Reimplemented in Isis::NirsDetectorMap, Isis::VariableLineScanCameraDetectorMap, Isis::PushFrameCameraDetectorMap, and Isis::LineScanCameraDetectorMap.
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by Isis::Camera::exposureDuration().
LineRate()
double Isis::RadarPulseMap::LineRate () const inline virtual
Return the time in seconds between scan lines.
Reimplemented from Isis::CameraDetectorMap.
LineScaleFactor()
double Isis::CameraDetectorMap::LineScaleFactor () const virtual inherited
Return scaling factor for computing line resolution.
Returns
(double) The scaling factor for line resolution
References Isis::CameraDetectorMap::p_detectorLineSumming.
Referenced by Isis::Camera::LineResolution(), Isis::Camera::ObliqueLineResolution(), Isis::ThemisIrCamera::SetBand(), Isis::PushFrameCameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetParent(), and Isis::PushFrameCameraDetectorMap::TotalFramelets().
ParentLine()
double Isis::CameraDetectorMap::ParentLine () const inherited
Return parent line.
Returns
(double) The parent line
References Isis::CameraDetectorMap::p_parentLine.
Referenced by Isis::Camera::SetRightAscensionDeclination().
ParentSample()
double Isis::CameraDetectorMap::ParentSample () const inherited
Return parent sample.
Returns
(double) The parent sample
References Isis::CameraDetectorMap::p_parentSample.
Referenced by Isis::Camera::SetRightAscensionDeclination().
SampleScaleFactor()
double Isis::CameraDetectorMap::SampleScaleFactor () const virtual inherited
Return scaling factor for computing sample resolution.
Returns
(double) The scaling factor for sample resolution
References Isis::CameraDetectorMap::p_detectorSampleSumming.
Referenced by Isis::Camera::ObliqueSampleResolution(), and Isis::Camera::SampleResolution().
SetDetector()
bool Isis::RadarPulseMap::SetDetector (const double sample, const double line) virtual
Compute alpha position from a detector coordinate.
This method will compute a alpha sample given a detector coordinate. The alpha line will be computed using the the time in the parent camera
Parameters
sample Sample number in the detector
line Line number in the detector (ignored)
Returns
conversion successful
Reimplemented from Isis::CameraDetectorMap.
References Isis::iTime::Et(), Isis::CameraDetectorMap::p_camera, Isis::CameraDetectorMap::p_parentLine, Isis::CameraDetectorMap::SetDetector(), and Isis::Spice::time().
SetDetectorLineSumming()
void Isis::CameraDetectorMap::SetDetectorLineSumming (const double summing) inline inherited
Set line summing mode.
Use this method to specify if detector lines are summed/averaged. That is, one image lines represents the average of N detectors. If not set the default is 1.
Parameters
summing Line summing mode
References Isis::CameraDetectorMap::p_detectorLineSumming.
Referenced by Isis::CrismCamera::CrismCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::MarciCamera::MarciCamera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), and Isis::ThemisVisCamera::ThemisVisCamera().
SetDetectorSampleSumming()
void Isis::CameraDetectorMap::SetDetectorSampleSumming (const double summing) inline inherited
Set sample summing mode.
Use this method to specify if detector samples are summed/averaged. That is, one image sample represents the average of N detectors. If not set the default is 1.
Parameters
summing Sample summing mode
References Isis::CameraDetectorMap::p_detectorSampleSumming.
Referenced by Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::MarciCamera::MarciCamera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), and Isis::ThemisVisCamera::ThemisVisCamera().
SetLineRate()
void Isis::RadarPulseMap::SetLineRate (const double lineRate) inline
Reset the line rate.
Use this method to reset the time between lines. Usually this will not need to be done unless the rate changes between bands.
Parameters
lineRate the time in seconds between lines
SetParent() [1/2]
bool Isis::RadarPulseMap::SetParent (const double sample, const double line) virtual
Compute radar (sample/time)from a alpha image coordinate.
This method will compute the radar position from the alpha line/sample coordinate. The alpha line will be used to set the appropriate time in the parent camera.
Parameters
sample Sample number in the alpha image
line Line number in the alpha image
Returns
conversion successful
Reimplemented from Isis::CameraDetectorMap.
References Isis::CameraDetectorMap::p_camera, Isis::CameraDetectorMap::p_detectorLine, Isis::CameraDetectorMap::SetParent(), and Isis::Sensor::setTime().
SetParent() [2/2]
bool Isis::CameraDetectorMap::SetParent (const double sample, const double line, const double deltaT) virtual inherited
Compute detector position from a parent image coordinate.
This method will compute the detector position from the parent line/sample coordinate and an offset from the currently set time in seconds. If the time has not already been set, the input offset is not applied.
Parameters
sample Sample number in the parent image
line Line number in the parent image
deltaT option time offset from center of exposure in seconds
Returns
conversion successful
Reimplemented in Isis::VariableLineScanCameraDetectorMap, Isis::RollingShutterCameraDetectorMap, Isis::PushFrameCameraDetectorMap, and Isis::LineScanCameraDetectorMap.
References Isis::iTime::Et(), Isis::Spice::isTimeSet(), Isis::CameraDetectorMap::p_camera, Isis::CameraDetectorMap::p_detectorLine, Isis::CameraDetectorMap::p_detectorLineSumming, Isis::CameraDetectorMap::p_detectorSample, Isis::CameraDetectorMap::p_detectorSampleSumming, Isis::CameraDetectorMap::p_parentLine, Isis::CameraDetectorMap::p_parentSample, Isis::CameraDetectorMap::p_sl, Isis::CameraDetectorMap::p_ss, Isis::Sensor::setTime(), and Isis::Spice::time().
SetStartingDetectorLine()
void Isis::CameraDetectorMap::SetStartingDetectorLine (const double line) inline inherited
Set the starting detector line.
Use this method to specify the starting detector that represents the first image line in the cube. If not set the default is 1.
Parameters
line Starting detector line
References Isis::CameraDetectorMap::p_startingDetectorLine.
Referenced by Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::JunoCamera::JunoCamera(), Isis::MdisCamera::MdisCamera(), and Isis::RosettaOsirisCamera::RosettaOsirisCamera().
SetStartingDetectorSample()
void Isis::CameraDetectorMap::SetStartingDetectorSample (const double sample) inline inherited
Set the starting detector sample.
Use this method to specify the starting detector that represents the first image sample in the cube. If not set the default is 1.
Parameters
sample Starting detector sample
References Isis::CameraDetectorMap::p_startingDetectorSample.
Referenced by Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::CTXCamera::CTXCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::MdisCamera::MdisCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), and Isis::RosettaOsirisCamera::RosettaOsirisCamera().
SetStartTime()
void Isis::RadarPulseMap::SetStartTime (const double etStart) inline
Reset the starting ephemeris time.
Use this method to reset the starting time of the top edge of the first line in the alpha image. That is the time, prior to cropping, scaling, or padding. Usually this will not need to be done unless the time changes between bands.
Parameters
etStart starting ephemeris time in seconds
SetXAxisTimeDependent()
void Isis::RadarPulseMap::SetXAxisTimeDependent (bool on) inline
Set the time dependent axis, if never called y is the time dependent axis.
Member Data Documentation
p_camera
Camera* Isis::CameraDetectorMap::p_camera protected inherited
Pointer to the camera.
Referenced by Isis::CameraDetectorMap::CameraDetectorMap(), Isis::LineScanCameraDetectorMap::SetDetector(), SetDetector(), Isis::VariableLineScanCameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetFramelet(), SetParent(), Isis::CameraDetectorMap::SetParent(), Isis::LineScanCameraDetectorMap::SetParent(), Isis::RollingShutterCameraDetectorMap::SetParent(), Isis::VariableLineScanCameraDetectorMap::SetParent(), and Isis::PushFrameCameraDetectorMap::TotalFramelets().
p_detectorLine
double Isis::CameraDetectorMap::p_detectorLine protected inherited
Detector coordinate line value.
Referenced by Isis::CameraDetectorMap::DetectorLine(), Isis::CameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), SetParent(), Isis::CameraDetectorMap::SetParent(), Isis::LineScanCameraDetectorMap::SetParent(), Isis::PushFrameCameraDetectorMap::SetParent(), Isis::RollingShutterCameraDetectorMap::SetParent(), and Isis::VariableLineScanCameraDetectorMap::SetParent().
p_detectorLineSumming
double Isis::CameraDetectorMap::p_detectorLineSumming protected inherited
The scaling factor for computing line resolution.
Referenced by Isis::CameraDetectorMap::CameraDetectorMap(), Isis::CameraDetectorMap::LineScaleFactor(), Isis::CameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetDetectorLineSumming(), Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_detectorSample
double Isis::CameraDetectorMap::p_detectorSample protected inherited
Detector coordinate sample value.
Referenced by Isis::CameraDetectorMap::DetectorSample(), Isis::CameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_detectorSampleSumming
double Isis::CameraDetectorMap::p_detectorSampleSumming protected inherited
The scaling factor for computing sample resolution.
Referenced by Isis::CameraDetectorMap::CameraDetectorMap(), Isis::CameraDetectorMap::SampleScaleFactor(), Isis::CameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetDetectorSampleSumming(), Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_parentLine
double Isis::CameraDetectorMap::p_parentLine protected inherited
The parent line calculated from the detector.
Referenced by Isis::CameraDetectorMap::ParentLine(), Isis::CameraDetectorMap::SetDetector(), Isis::LineScanCameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetDetector(), SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::VariableLineScanCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetParent(), Isis::PushFrameCameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_parentSample
double Isis::CameraDetectorMap::p_parentSample protected inherited
The parent sample calculated from the detector.
Referenced by Isis::CameraDetectorMap::ParentSample(), Isis::CameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetParent(), Isis::PushFrameCameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_sl
double Isis::CameraDetectorMap::p_sl protected inherited
Start line.
Referenced by Isis::CameraDetectorMap::AdjustedStartingLine(), Isis::CameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_ss
double Isis::CameraDetectorMap::p_ss protected inherited
Start sample.
Referenced by Isis::CameraDetectorMap::AdjustedStartingSample(), Isis::CameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_startingDetectorLine
double Isis::CameraDetectorMap::p_startingDetectorLine protected inherited
Detector start coordinate line value.
Referenced by Isis::CameraDetectorMap::CameraDetectorMap(), and Isis::CameraDetectorMap::SetStartingDetectorLine().
p_startingDetectorSample
double Isis::CameraDetectorMap::p_startingDetectorSample protected inherited
Detector start coordinate sample value.
Referenced by Isis::CameraDetectorMap::CameraDetectorMap(), and Isis::CameraDetectorMap::SetStartingDetectorSample().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/RadarPulseMap/RadarPulseMap.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/RadarPulseMap/RadarPulseMap.cpp