Isis Developer Reference: Isis::ObliqueCylindrical Class Reference
Isis::ObliqueCylindrical Class Reference
Map Projection
Oblique Cylindrical Map Projection.
#include <ObliqueCylindrical.h>
Public Types
enum LatitudeType { Planetocentric , Planetographic }
This enum defines the types of Latitude supported in this class.
enum LongitudeDirection { PositiveEast , PositiveWest }
This enum defines the types of Longitude directions supported in this class.
enum ProjectionType { Triaxial , RingPlane }
This enum defines the subclasses of Projection supported in Isis.
Public Member Functions
ObliqueCylindrical (Isis::Pvl &label, bool allowDefaults=false)
Constructs an ObliqueCylindrical object.
~ObliqueCylindrical ()
Destroys the ObliqueCylindrical object.
bool operator== (const Isis::Projection &proj)
Compares two Projection objects to see if they are equal.
QString Name () const
Returns the name of the map projection, "ObliqueCylindrical".
QString Version () const
Returns the version of the map projection.
bool SetGround (const double lat, const double lon)
This method is used to set the latitude/longitude (assumed to be of the correct LatitudeType, LongitudeDirection, and LongitudeDomain.
bool SetCoordinate (const double x, const double y)
This method is used to set the projection x/y.
bool XYRange (double &minX, double &maxX, double &minY, double &maxY)
This method is used to determine the x/y range which completely covers the area of interest specified by the lat/lon range.
PvlGroup Mapping ()
This function returns the keywords that this projection uses.
PvlGroup MappingLatitudes ()
This function returns the latitude keywords that this projection uses.
PvlGroup MappingLongitudes ()
This function returns the longitude keywords that this projection uses.
double poleLatitude () const
Returns the value of the pole latitude.
double poleLongitude () const
Returns the value of the pole longitude.
double poleRotation () const
Returns the value of the pole rotation.
double EquatorialRadius () const
This returns the equatorial radius of the target.
double PolarRadius () const
This returns the polar radius of the target.
double Eccentricity () const
This returns the eccentricity of the target,.
double LocalRadius (double lat) const
This method returns the local radius in meters at the specified latitude position.
double LocalRadius () const
This method returns the local radius in meters at the current latitude position.
virtual double TrueScaleLatitude () const
This method returns the latitude of true scale.
virtual bool IsEquatorialCylindrical ()
This method returns true if the projection is equatorial cylindrical.
bool IsPlanetocentric () const
This indicates if the latitude type is planetocentric (as opposed to planetographic).
bool IsPlanetographic () const
This indicates if the latitude type is planetographic (as opposed to planetocentric).
QString LatitudeTypeString () const
This method returns the latitude type as a string.
double ToPlanetocentric (const double lat) const
This method converts a planetographic latitude to a planetocentric latitude.
double ToPlanetographic (const double lat) const
This method converts a planetocentric latitude to a planetographic latitude.
bool IsPositiveEast () const
This indicates if the longitude direction type is positive west (as opposed to postive east).
bool IsPositiveWest () const
This indicates if the longitude direction type is positive east (as opposed to postive west).
QString LongitudeDirectionString () const
This method returns the longitude direction as a string.
bool Has180Domain () const
This indicates if the longitude domain is -180 to 180 (as opposed to 0 to 360).
bool Has360Domain () const
This indicates if the longitude domain is 0 to 360 (as opposed to -180 to 180).
QString LongitudeDomainString () const
This method returns the longitude domain as a string.
virtual double MinimumLatitude () const
This returns the minimum latitude of the area of interest.
virtual double MaximumLatitude () const
This returns the maximum latitude of the area of interest.
virtual double MinimumLongitude () const
This returns the minimum longitude of the area of interest.
virtual double MaximumLongitude () const
This returns the maximum longitude of the area of interest.
virtual double Latitude () const
This returns a latitude with correct latitude type as specified in the label object.
virtual double Longitude () const
This returns a longitude with correct longitude direction and domain as specified in the label object.
virtual bool SetUniversalGround (const double lat, const double lon)
This method is used to set the latitude/longitude which must be Planetocentric (latitude) and PositiveEast/Domain360 (longitude).
bool SetUnboundUniversalGround (const double coord1, const double coord2)
This method is used to set the latitude/longitude.
virtual double UniversalLatitude ()
This returns a universal latitude (planetocentric).
virtual double UniversalLongitude ()
This returns a universal longitude (positive east in 0 to 360 domain).
double Scale () const
This method returns the scale for mapping world coordinates into projection coordinates.
bool operator!= (const Projection &proj)
This method determines whether two map projection objects are not equal.
void setProjectionType (const ProjectionType ptype)
Sets the projection subclass type.
ProjectionType projectionType () const
Returns an enum value for the projection type.
bool IsSky () const
Returns true if projection is sky and false if it is land.
virtual bool HasGroundRange () const
This indicates if the longitude direction type is positive west (as opposed to postive east).
double Rotation () const
Returns the value of the Rotation keyword from the mapping group.
void SetWorldMapper (WorldMapper *mapper)
If desired the programmer can use this method to set a world mapper to be used in the SetWorld, WorldX, and WorldY methods.
bool IsGood () const
This indicates if the last invocation of SetGround, SetCoordinate, SetUniversalGround, or SetWorld was with successful or not.
double XCoord () const
This returns the projection X provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
double YCoord () const
This returns the projection Y provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
virtual bool SetWorld (const double x, const double y)
This method is used to set a world coordinate.
virtual double WorldX () const
This returns the world X coordinate provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
virtual double WorldY () const
This returns the world Y coordinate provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
double ToWorldX (const double projectionX) const
This method converts a projection x value to a world x value.
double ToWorldY (const double projectionY) const
This method converts a projection y value to a world y value.
double ToProjectionX (const double worldX) const
This method converts a world x value to a projection x value.
double ToProjectionY (const double worldY) const
This method converts a world y value to a projection y value.
double Resolution () const
This method returns the resolution for mapping world coordinates into projection coordinates.
void SetUpperLeftCorner (const Displacement &x, const Displacement &y)
This method searches for extreme (min/max/discontinuity) coordinate values along the constBorder line between minBorder and maxBorder (that is, across latitudes/longitudes).
Static Public Member Functions
static double ToPlanetocentric (double lat, double eRadius, double pRadius)
This method converts a planetographic latitude to a planetocentric latitude.
static double ToPlanetographic (double lat, double eRadius, double pRadius)
This method converts a planetocentric latitude to a planetographic latitude.
static double ToPositiveEast (const double lon, const int domain)
This method converts a longitude into the positive east direction.
static double ToPositiveWest (const double lon, const int domain)
This method converts a longitude into the positive west direction.
static double To180Domain (const double lon)
This method converts a longitude into the -180 to 180 domain.
static double To360Domain (const double lon)
This method converts a longitude into the 0 to 360 domain.
static double ToHours (double angle)
Converts the given angle (in degrees) to hours by using the ratio 15 degrees per hour.
static QString ToDMS (double angle)
Converts the given angle (in degrees) to degrees, minutes, seconds.
static QString ToHMS (double angle)
Converts the given angle (in degrees) to hours, minutes, seconds.
Protected Member Functions
void XYRangeCheck (const double latitude, const double longitude)
This convience function is established to assist in the development of the XYRange virtual method.
bool inLongitudeRange (double longitude)
Determine whether the given longitude is within the range of the MinimumLongitude and MaximumLongitude range of this projection.
bool inLongitudeRange (double minLon, double maxLon, double longitude)
Determine whether the given longitude is within the range of the given min and max longitudes.
bool inLatitudeRange (double latitude)
Determine whether the given latitude is within the range of the MinimumLatitude and MaximumLatitude range of this projection.
bool xyRangeOblique (double &minX, double &maxX, double &minY, double &maxY)
This method is used to find the XY range for oblique aspect projections (non-polar projections) by "walking" around each of the min/max lat/lon.
double qCompute (const double sinPhi) const
A convience method to compute Snyder's q equation (3-12) for a given latitude, \(\phi\).
double phi2Compute (const double t) const
A convience method to compute latitude angle phi2 given small t, from Syder's recursive equation (7-9)
double mCompute (const double sinphi, const double cosphi) const
A convience method to compute Snyder's m equation (14-15) for a given latitude, \(\phi\).
double tCompute (const double phi, const double sinphi) const
A convience method to compute Snyder's t equation (15-9) for a given latitude, \(\phi\).
double e4Compute () const
A convience method to compute.
void SetXY (double x, double y)
This protected method is a helper for derived classes.
void SetComputedXY (double x, double y)
This protected method is a helper for derived classes.
double GetX () const
Calculates the unrotated form of current x value.
double GetY () const
Calculates the unrotated form of the current y value.
double PixelResolution () const
Returns the pixel resolution value from the PVL mapping group in meters/pixel.
Protected Attributes
double m_latitude
This contains the currently set latitude value.
double m_longitude
This contains the currently set longitude value.
LatitudeType m_latitudeType
An enumerated type indicating the LatitudeType read from the labels.
LongitudeDirection m_longitudeDirection
An enumerated type indicating the LongitudeDirection read from the labels.
int m_longitudeDomain
This integer is either 180 or 360 and is read from the labels.
double m_equatorialRadius
Polar radius of the target.
double m_polarRadius
Polar radius of the target.
double m_eccentricity
The eccentricity of the target body.
double m_minimumLatitude
Contains the minimum latitude for the entire ground range.
double m_maximumLatitude
Contains the maximum latitude for the entire ground range.
double m_minimumLongitude
Contains the minimum longitude for the entire ground range.
double m_maximumLongitude
Contains the maximum longitude for the entire ground range.
WorldMapper * m_mapper
This points to a mapper passed into the SetWorldMapper method.
bool m_good
Indicates if the contents of m_x, m_y, m_latitude, and m_longitude are valid.
bool m_sky
Indicates whether projection is sky or land.
bool m_groundRangeGood
Indicates if the ground range (min/max lat/lons) were read from the labels.
double m_minimumX
The data elements m_minimumX, m_minimumY, m_maximumX, and m_maximumY are convience data elements when you write the XYRange virtual function.
double m_maximumX
See minimumX description.
double m_minimumY
See minimumX description.
double m_maximumY
See minimumX description.
PvlGroup m_mappingGrp
Mapping group that created this projection.
Detailed Description
Oblique Cylindrical Map Projection.
This class provides methods for the forward and inverse equations of an Oblique Cylindrical map projection (for a sphere).
This projection works by moving the north pole of the simple cylindrical projection. The pole latitude and longitude are the location of the new north pole, and the rotation is the equivalent to the center longitude in simple cylindrical.
The code was converted to C++ from the Fortran version of the USGS General Cartographic Transformation Package (GCTP). In particular it was modified from the Simple Cylindrical code. This class inherits Projection and provides the four virtual methods Name(), SetGround (forward) and SetCoordinate (inverse), XYRange (for obtaining projection coordinate coverage for a latitude/longitude window) and the == operator.
Please see the Projection class for a full accounting of all the methods available.
Author
2000-02-09 Jeff Anderson
Member Enumeration Documentation
LatitudeType
enum Isis::TProjection::LatitudeType inherited
This enum defines the types of Latitude supported in this class.
Enumerator
Planetocentric
Latitudes are measured as the angle from the equatorial plane to the plane through the center of the planet and a given point on the surface of the planet.
Planetographic
Latitudes are measured as the angle from the equatorial plane to the normal to the surface of the planet at a given point.
LongitudeDirection
enum Isis::TProjection::LongitudeDirection inherited
This enum defines the types of Longitude directions supported in this class.
Enumerator
PositiveEast
Longitude values increase in the easterly direction.
PositiveWest
Longitude values increase in the westerly direction.
ProjectionType
enum Isis::Projection::ProjectionType inherited
This enum defines the subclasses of Projection supported in Isis.
Enumerator
Triaxial
These projections are used to map triaxial and irregular-shaped bodies.
RingPlane
These projections are used to map ring planes.
Constructor & Destructor Documentation
ObliqueCylindrical()
Isis::ObliqueCylindrical::ObliqueCylindrical (Isis::Pvl & label, bool allowDefaults = false)
Constructs an ObliqueCylindrical object.
Parameters
label This argument must be a Label containing the proper mapping information as indicated in the Projection class. Additionally, the Oblique cylindrical projection requires the Pole latitude, longitude and rotation.
allowDefaults This does nothing currently
Exceptions
IException
References _FILEINFO_, Isis::NaifStatus::CheckErrors(), Isis::PvlContainer::deleteKeyword(), Isis::PvlObject::findGroup(), Isis::PvlContainer::hasKeyword(), Isis::IException::Io, Isis::TProjection::IsPlanetocentric(), Isis::PI, Isis::toDouble(), Isis::TProjection::ToPlanetographic(), Isis::toString(), Isis::PvlObject::Traverse, and Isis::IException::Unknown.
~ObliqueCylindrical()
Isis::ObliqueCylindrical::~ObliqueCylindrical ()
Destroys the ObliqueCylindrical object.
Member Function Documentation
e4Compute()
double Isis::TProjection::e4Compute () const protected inherited
A convience method to compute.
\[ e4 = \sqrt{(1+e)^{1+e}(1-e)^{1-e}} \]
where e is the eccentricity of the body.
Returns
double The value for the e4 formula.
References Isis::TProjection::Eccentricity().
Referenced by Isis::PolarStereographic::PolarStereographic().
Eccentricity()
double Isis::TProjection::Eccentricity () const inherited
This returns the eccentricity of the target,.
\[ e = \sqrt{1 - \frac{PR^2}{ER^2}} \]
where PR is the polar radius and ER is the equatorial radius. Since polar and equatorial radii are required to be greater than zero, it follows that \(0 \le e < 1 \) . Note that if the body is spherical, then PR = ER and so e = 0.
Returns
double
References Isis::TProjection::m_eccentricity.
Referenced by Isis::TProjection::e4Compute(), Isis::TProjection::mCompute(), Isis::Mercator::Mercator(), Isis::TProjection::phi2Compute(), Isis::TProjection::tCompute(), and Isis::TransverseMercator::TransverseMercator().
EquatorialRadius()
double Isis::TProjection::EquatorialRadius () const inherited
This returns the equatorial radius of the target.
The radius was obtained from the label during object construction.
Returns
double
References Isis::TProjection::m_equatorialRadius.
Referenced by Isis::MosaicGridTool::fromPvl(), Isis::GridGraphicsItem::GridGraphicsItem(), Isis::TProjection::operator==(), and Isis::MosaicGridTool::setLatExtents().
GetX()
double Isis::Projection::GetX () const protected inherited
Calculates the unrotated form of current x value.
Returns
double The unrotated x-value.
References Isis::PI.
Referenced by Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Mollweide::SetCoordinate(), SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::RingCylindrical::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), and Isis::TransverseMercator::SetCoordinate().
GetY()
double Isis::Projection::GetY () const protected inherited
Calculates the unrotated form of the current y value.
Returns
double The unrotated y-value.
References Isis::PI.
Referenced by Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::Mercator::SetCoordinate(), SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::RingCylindrical::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), and Isis::TransverseMercator::SetCoordinate().
Has180Domain()
bool Isis::TProjection::Has180Domain () const inherited
This indicates if the longitude domain is -180 to 180 (as opposed to 0 to 360).
The longitude domain was obtained from the label during object construction.
Returns
bool
References Isis::TProjection::m_longitudeDomain.
Referenced by Isis::GridGraphicsItem::GridGraphicsItem(), Isis::MosaicSceneItem::reproject(), and Isis::SubArea::UpdateLabel().
Has360Domain()
bool Isis::TProjection::Has360Domain () const inherited
This indicates if the longitude domain is 0 to 360 (as opposed to -180 to 180).
The longitude domain was obtained from the label during object construction.
Returns
bool
References Isis::TProjection::m_longitudeDomain.
Referenced by Isis::MosaicGridTool::domainMaxLon(), Isis::MosaicGridTool::domainMinLon(), and Isis::SubArea::UpdateLabel().
HasGroundRange()
bool Isis::Projection::HasGroundRange () const virtual inherited
This indicates if the longitude direction type is positive west (as opposed to postive east).
The longitude type was obtained from the label during object construction.
Returns
bool This indicates if the longitude direction type is positive east (as opposed to postive west). The longitude type was obtained from the label during object construction.
bool This method returns the longitude direction as a string. It will return either PositiveEast or PositiveWest.
string The longitude direction, "PositiveEast" or "PositiveWest". This indicates if the longitude domain is -180 to 180 (as opposed to 0 to 360). The longitude domain was obtained from the label during object construction.
bool This indicates if the longitude domain is 0 to 360 (as opposed to -180 to 180). The longitude domain was obtained from the label during object construction.
bool This method converts a longitude into the -180 to 180 domain. It will leave the longitude unchanged if it is already in the domain.
Parameters
lon Longitude to convert into the -180 to 180 domain.
Exceptions
IException::Unknown - "The given longitude is invalid."
Returns
double The longitude, converted to 180 domain. This method converts a longitude into the 0 to 360 domain. It will leave the longitude unchanged if it is already in the domain.
Parameters
lon Longitude to convert into the 0 to 360 domain.
Returns
double The longitude, converted to 360 domain. This method returns the longitude domain as a string. It will return either 180 or 360.
string The longitude domain, "180" or "360". This indicates that the labels contained minimum and maximum ground coordinatess (e.g., a ground range coverage). If the projection has ground range coverage then the MinimumLatitude, MaximumLatitude, MinimumLongitude, and MaximumLongitude methods or comparable methods for other projection types can be used. The ground range coverage essentially defines the area of user interest.
bool
References Isis::Projection::m_groundRangeGood.
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::RingPlaneProjection::Mapping(), Isis::TProjection::MappingLatitudes(), Isis::TProjection::MappingLongitudes(), Isis::Planar::MappingRingLongitudes(), Isis::RingCylindrical::MappingRingLongitudes(), Isis::RingPlaneProjection::MappingRingLongitudes(), Isis::Planar::MappingRingRadii(), Isis::RingCylindrical::MappingRingRadii(), Isis::RingPlaneProjection::MappingRingRadii(), Isis::ProjectionFactory::RingsCreateForCube(), and Isis::TProjection::xyRangeOblique().
inLatitudeRange()
bool Isis::TProjection::inLatitudeRange (double latitude) protected inherited
Determine whether the given latitude is within the range of the MinimumLatitude and MaximumLatitude range of this projection.
Note: It is a good habit to call this function to verify that a value is in range before passing it to XYRangeCheck.
See also
inLongitudeRange(minLon, maxLon, longitude)
inLongitudeRange(longitude)
XYRangeCheck(latitude, longitude)
Parameters
latitude The latitude to check.
Returns
bool Indicates whether MinimumLatitude <= latitude <= MaximumLatitude.
References Isis::TProjection::MaximumLatitude(), and Isis::TProjection::MinimumLatitude().
inLongitudeRange() [1/2]
bool Isis::TProjection::inLongitudeRange (double longitude) protected inherited
Determine whether the given longitude is within the range of the MinimumLongitude and MaximumLongitude range of this projection.
Note: It is a good habit to call this function to verify that a value is in range before passing it to XYRangeCheck.
See also
inLongitudeRange(minLon, maxLon, longitude)
inLatitudeRange(latitude)
XYRangeCheck(latitude, longitude)
Parameters
longitude The longitude to check.
Returns
bool Indicates whether MinimumLongitude <= longitude <= MaximumLongitude.
References Isis::TProjection::MaximumLongitude(), and Isis::TProjection::MinimumLongitude().
inLongitudeRange() [2/2]
bool Isis::TProjection::inLongitudeRange (double minLon, double maxLon, double longitude) protected inherited
Determine whether the given longitude is within the range of the given min and max longitudes.
Note: It is a good habit to call this function to verify that a value is in range before passing it to XYRangeCheck.
See also
inLongitudeRange(longitude)
inLatitudeRange(latitude)
XYRangeCheck(latitude, longitude)
Parameters
minLon The lower end of longitude range.
maxLon The upper end of longitude range.
longitude The longitude to check.
Returns
bool Indicates whether minLon <= longitude <= maxLon.
References Isis::TProjection::To360Domain().
IsEquatorialCylindrical()
bool Isis::TProjection::IsEquatorialCylindrical () virtual inherited
This method returns true if the projection is equatorial cylindrical.
In other words, if the projection is cylindrical and an image projected at 0 is the same as an image projected at 360.
Returns
bool true if the projection is equatorial cylindrical
Reimplemented from Isis::Projection.
Reimplemented in Isis::SimpleCylindrical, Isis::Mercator, and Isis::Equirectangular.
Referenced by Isis::SubArea::UpdateLabel().
IsGood()
bool Isis::Projection::IsGood () const inherited
This indicates if the last invocation of SetGround, SetCoordinate, SetUniversalGround, or SetWorld was with successful or not.
If there was success then the Latitude, Longitude, XCoord, YCoord, UniversalLatitude, UniversalLongitude, WorldX, and WorldY methods can be utilized.
Returns
bool True if the last call to SetGround, SetCoordinate, SetUniversalGround, or SetWorld was successful.
References Isis::Projection::m_good.
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::Chip::Load(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::SubArea::UpdateLabel(), Isis::TProjection::XYRangeCheck(), and Isis::RingPlaneProjection::XYRangeCheck().
IsPlanetocentric()
bool Isis::TProjection::IsPlanetocentric () const inherited
This indicates if the latitude type is planetocentric (as opposed to planetographic).
The latitude type was obtained from the label during object construction.
Returns
bool
References Isis::TProjection::m_latitudeType, and Isis::TProjection::Planetocentric.
Referenced by Isis::LambertConformal::LambertConformal(), Isis::Mercator::Mercator(), ObliqueCylindrical(), Isis::TProjection::operator==(), Isis::Orthographic::Orthographic(), Isis::PointPerspective::PointPerspective(), Isis::PolarStereographic::PolarStereographic(), Isis::LambertConformal::SetCoordinate(), Isis::LunarAzimuthalEqualArea::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::TransverseMercator::SetCoordinate(), Isis::LambertConformal::SetGround(), Isis::LunarAzimuthalEqualArea::SetGround(), Isis::Mercator::SetGround(), Isis::Orthographic::SetGround(), Isis::PointPerspective::SetGround(), Isis::PolarStereographic::SetGround(), Isis::TransverseMercator::SetGround(), and Isis::TransverseMercator::TransverseMercator().
IsPlanetographic()
bool Isis::TProjection::IsPlanetographic () const inherited
This indicates if the latitude type is planetographic (as opposed to planetocentric).
The latitude type was obtained from the label during object construction.
Returns
bool
References Isis::TProjection::m_latitudeType, and Isis::TProjection::Planetographic.
Referenced by Isis::SubArea::UpdateLabel().
IsPositiveEast()
bool Isis::TProjection::IsPositiveEast () const inherited
This indicates if the longitude direction type is positive west (as opposed to postive east).
The longitude type was obtained from the label during object construction.
Returns
bool
References Isis::TProjection::m_longitudeDirection, and Isis::TProjection::PositiveEast.
Referenced by Isis::SubArea::UpdateLabel().
IsPositiveWest()
bool Isis::TProjection::IsPositiveWest () const inherited
This indicates if the longitude direction type is positive east (as opposed to postive west).
The longitude type was obtained from the label during object construction.
Returns
bool
References Isis::TProjection::m_longitudeDirection, and Isis::TProjection::PositiveWest.
Referenced by Isis::GridGraphicsItem::GridGraphicsItem(), and Isis::TProjection::operator==().
IsSky()
bool Isis::Projection::IsSky () const inherited
Returns true if projection is sky and false if it is land.
Returns
bool
References Isis::Projection::m_sky.
Referenced by Isis::Camera::SetImage(), and Isis::Camera::SetRightAscensionDeclination().
Latitude()
double Isis::TProjection::Latitude () const virtual inherited
This returns a latitude with correct latitude type as specified in the label object.
The method can only be used if SetGround, SetCoordinate, SetUniversalGround, or SetWorld return with success. Success can also be checked using the IsGood method.
Returns
double
References Isis::TProjection::m_latitude.
Referenced by Isis::MosaicControlNetTool::mouseButtonRelease(), Isis::MosaicAreaTool::mouseButtonRelease(), Isis::MosaicFindTool::mouseButtonRelease(), Isis::MosaicGridTool::setLatExtents(), Isis::MosaicTrackTool::updateLabels(), and Isis::PolygonTools::XYToLatLon().
LatitudeTypeString()
QString Isis::TProjection::LatitudeTypeString () const inherited
This method returns the latitude type as a string.
It will return either Planetocentric or Planetographic.
Returns
string The latitude type, "Planetocentric" or "Planetographic".
References Isis::TProjection::m_latitudeType, and Isis::TProjection::Planetographic.
Referenced by Isis::MosaicGridTool::latType().
LocalRadius() [1/2]
double Isis::TProjection::LocalRadius () const virtual inherited
This method returns the local radius in meters at the current latitude position.
This is only usable if the use of SetGround or SetCoordinate was successful.
Returns
double The value for the local radius, in meters, at the current latitude.
Implements Isis::Projection.
References Isis::TProjection::m_latitude.
Referenced by Isis::Equirectangular::Equirectangular().
LocalRadius() [2/2]
double Isis::TProjection::LocalRadius (double latitude) const inherited
This method returns the local radius in meters at the specified latitude position.
For this method, the local radius is defined as the distance from the center of the planet to the surface of the planet at the given latitude.
\[ LR = \frac{ER*PR}{\sqrt{PR^2 \cos^2(LAT)+ER^2 \sin^2(LAT)}} \]
Parameters
latitude A latitude in degrees (assumed to be of the correct LatitudeType).
Exceptions
IException::Unknown - "The given latitude is invalid."
Returns
double The value for the local radius, in meters, at the given latitude.
References _FILEINFO_, Isis::TProjection::m_equatorialRadius, Isis::TProjection::m_polarRadius, Isis::Null, Isis::PI, Isis::toString(), and Isis::IException::Unknown.
Referenced by Isis::TiffImporter::convertProjection(), and Isis::ProjectionFactory::CreateForCube().
Longitude()
double Isis::TProjection::Longitude () const virtual inherited
This returns a longitude with correct longitude direction and domain as specified in the label object.
The method can only be used if SetGround, SetCoordinate, SetUniversalGround, or SetWorld return with success. Success can also be checked using the IsGood method.
Returns
double
References Isis::TProjection::m_longitude.
Referenced by Isis::MosaicControlNetTool::mouseButtonRelease(), Isis::MosaicAreaTool::mouseButtonRelease(), Isis::MosaicFindTool::mouseButtonRelease(), Isis::MosaicGridTool::setLonExtents(), Isis::SubArea::UpdateLabel(), Isis::MosaicTrackTool::updateLabels(), and Isis::PolygonTools::XYToLatLon().
LongitudeDirectionString()
QString Isis::TProjection::LongitudeDirectionString () const inherited
This method returns the longitude direction as a string.
It will return either PositiveEast or PositiveWest.
Returns
string The longitude direction, "PositiveEast" or "PositiveWest".
References Isis::TProjection::m_longitudeDirection, and Isis::TProjection::PositiveEast.
LongitudeDomainString()
QString Isis::TProjection::LongitudeDomainString () const inherited
This method returns the longitude domain as a string.
It will return either 180 or 360.
Returns
string The longitude domain, "180" or "360".
References Isis::TProjection::m_longitudeDomain.
Referenced by Isis::MosaicGridTool::lonDomain().
Mapping()
PvlGroup Isis::ObliqueCylindrical::Mapping () virtual
This function returns the keywords that this projection uses.
Returns
PvlGroup The keywords that this projection uses
Reimplemented from Isis::TProjection.
References Isis::Projection::m_mappingGrp, and Isis::TProjection::Mapping().
MappingLatitudes()
PvlGroup Isis::ObliqueCylindrical::MappingLatitudes () virtual
This function returns the latitude keywords that this projection uses.
Returns
PvlGroup The latitude keywords that this projection uses
Reimplemented from Isis::TProjection.
References Isis::TProjection::MappingLatitudes().
MappingLongitudes()
PvlGroup Isis::ObliqueCylindrical::MappingLongitudes () virtual
This function returns the longitude keywords that this projection uses.
Returns
PvlGroup The longitude keywords that this projection uses
Reimplemented from Isis::TProjection.
References Isis::TProjection::MappingLongitudes().
MaximumLatitude()
double Isis::TProjection::MaximumLatitude () const virtual inherited
This returns the maximum latitude of the area of interest.
The value was obtained from the labels during object construction. This method can only be used if HasGroundRange returns a true.
Returns
double
References Isis::TProjection::m_maximumLatitude.
Referenced by Isis::TProjection::inLatitudeRange(), Isis::MosaicGridTool::onProjectionChanged(), Isis::MosaicGridTool::setLatExtents(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::TProjection::xyRangeOblique().
MaximumLongitude()
double Isis::TProjection::MaximumLongitude () const virtual inherited
This returns the maximum longitude of the area of interest.
The value was obtained from the labels during object construction. This method can only be used if HasGroundRange returns a true.
Returns
double
References Isis::TProjection::m_maximumLongitude.
Referenced by Isis::TProjection::inLongitudeRange(), Isis::MosaicGridTool::onProjectionChanged(), Isis::MosaicGridTool::setLonExtents(), Isis::ProcessMapMosaic::SetOutputCube(), Isis::Orthographic::XYRange(), and Isis::TProjection::xyRangeOblique().
mCompute()
double Isis::TProjection::mCompute (const double sinphi, const double cosphi) const protected inherited
A convience method to compute Snyder's m equation (14-15) for a given latitude, \(\phi\).
\[ m = \frac{\cos(\phi)}{\sqrt{1-e^2 \sin^2(\phi)}} \]
where \(e\) is the eccentricity for the body.
Parameters
sinphi sine of phi
cosphi cosine of phi
Returns
double Value for Snyder's m variable.
References Isis::TProjection::Eccentricity().
Referenced by Isis::LambertConformal::LambertConformal(), and Isis::PolarStereographic::PolarStereographic().
MinimumLatitude()
double Isis::TProjection::MinimumLatitude () const virtual inherited
This returns the minimum latitude of the area of interest.
The value was obtained from the labels during object construction. This method can only be used if HasGroundRange returns a true.
Returns
double
References Isis::TProjection::m_minimumLatitude.
Referenced by Isis::TProjection::inLatitudeRange(), Isis::MosaicGridTool::onProjectionChanged(), Isis::MosaicGridTool::setLatExtents(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::TProjection::xyRangeOblique().
MinimumLongitude()
double Isis::TProjection::MinimumLongitude () const virtual inherited
This returns the minimum longitude of the area of interest.
The value was obtained from the labels during object construction. This method can only be used if HasGroundRange returns a true.
Returns
double
References Isis::TProjection::m_minimumLongitude.
Referenced by Isis::TProjection::inLongitudeRange(), Isis::MosaicGridTool::onProjectionChanged(), Isis::MosaicGridTool::setLonExtents(), Isis::ProcessMapMosaic::SetOutputCube(), Isis::Orthographic::XYRange(), and Isis::TProjection::xyRangeOblique().
Name()
QString Isis::ObliqueCylindrical::Name () const virtual
Returns the name of the map projection, "ObliqueCylindrical".
Returns
QString Name of projection, "ObliqueCylindrical"
Implements Isis::TProjection.
operator!=()
bool Isis::Projection::operator!= (const Projection & proj) inherited
This method determines whether two map projection objects are not equal.
True is returned if they have at least some differences in the radii, latitude type, longitude direction, resolution, or projection name.
Parameters
proj A reference to a Projection object to which this Projection will be compared.
Returns
bool Indicates whether the Projection objects are not equivalent.
operator==()
bool Isis::ObliqueCylindrical::operator== (const Isis::Projection & proj) virtual
Compares two Projection objects to see if they are equal.
Parameters
proj Projection object to do comparison on
Returns
bool Returns true if the Projection objects are equal, and false if they are not
Reimplemented from Isis::TProjection.
References poleLatitude(), poleLongitude(), and poleRotation().
phi2Compute()
double Isis::TProjection::phi2Compute (const double t) const protected inherited
A convience method to compute latitude angle phi2 given small t, from Syder's recursive equation (7-9)
\[ \phi_{i+1} = \frac{\pi}{2} - 2\arctan\left(t \left[\frac{1-e\sin(\phi_i)}{1+e\sin(\phi_i)}\right]^{e/2}\right) \]
where \(e\) is the eccentricity for the body and \(\phi_0 = \frac{\pi}{2} - 2\arctan(t) \) .
Parameters
t small t
Exceptions
IException::Unknown - "Failed to converge in Projection::phi2Compute()"
Returns
double The value for the latitude.
References _FILEINFO_, Isis::TProjection::Eccentricity(), Isis::HALFPI, and Isis::IException::Unknown.
Referenced by Isis::LambertConformal::SetCoordinate(), Isis::Mercator::SetCoordinate(), and Isis::PolarStereographic::SetCoordinate().
PixelResolution()
double Isis::Projection::PixelResolution () const protected inherited
Returns the pixel resolution value from the PVL mapping group in meters/pixel.
Returns
double pixel resolution in meters/pixel
Referenced by Isis::Planar::XYRange(), and Isis::RingCylindrical::XYRange().
PolarRadius()
double Isis::TProjection::PolarRadius () const inherited
This returns the polar radius of the target.
The radius was obtained from the label during object construction.
Returns
double
References Isis::TProjection::m_polarRadius.
Referenced by Isis::MosaicGridTool::fromPvl(), Isis::GridGraphicsItem::GridGraphicsItem(), Isis::TProjection::operator==(), and Isis::MosaicGridTool::setLatExtents().
poleLatitude()
double Isis::ObliqueCylindrical::poleLatitude () const
Returns the value of the pole latitude.
Returns
double The pole latitude.
Referenced by operator==(), SetCoordinate(), and SetGround().
poleLongitude()
double Isis::ObliqueCylindrical::poleLongitude () const
Returns the value of the pole longitude.
Returns
double The pole longitude.
Referenced by operator==(), SetCoordinate(), and SetGround().
poleRotation()
double Isis::ObliqueCylindrical::poleRotation () const
Returns the value of the pole rotation.
Returns
double The pole rotation.
Referenced by operator==(), SetCoordinate(), and SetGround().
projectionType()
Projection::ProjectionType Isis::Projection::projectionType () const inherited
Returns an enum value for the projection type.
Returns
projection subclass type
Referenced by Isis::MosaicGridTool::autoGrid(), Isis::MosaicGridTool::fromPvl(), Isis::MosaicFindTool::getUserGroundPoint(), Isis::GridGraphicsItem::GridGraphicsItem(), Isis::UniversalGroundMap::GroundRange(), Isis::MosaicControlNetTool::mouseButtonRelease(), Isis::MosaicFindTool::mouseButtonRelease(), Isis::MosaicGridTool::setLatExtents(), Isis::MosaicGridTool::setLonExtents(), Isis::Projection::SetUnboundUniversalGround(), Isis::Projection::SetUniversalGround(), Isis::UniversalGroundMap::UniversalLatitude(), Isis::UniversalGroundMap::UniversalLongitude(), Isis::MosaicTrackTool::updateLabels(), and Isis::MosaicAreaTool::userChangedBox().
qCompute()
double Isis::TProjection::qCompute (const double sinPhi) const protected inherited
A convience method to compute Snyder's q equation (3-12) for a given latitude, \(\phi\).
\[ q = (1 - e^2) \left[ \frac{\sin(\phi)}{1 - e^2 \sin^2(\phi)} - \frac{1}{2e} \ln\left(\frac{1 - e \sin(\phi)}{1 + e \sin(\phi)}\right) \right] \]
where \(e\) is the eccentricity for the body.
Parameters
sinPhi The sine value for a latitude, phi.
Exceptions
IException::Unknown - "Snyder's q variable should only be computed for ellipsoidal projections."
Returns
double Value for Snyder's q variable.
References _FILEINFO_, Isis::TProjection::m_eccentricity, and Isis::IException::Unknown.
Resolution()
double Isis::Projection::Resolution () const inherited
This method returns the resolution for mapping world coordinates into projection coordinates.
For example, if the world coordinate system is an image then this routine returns the number of meters per pixel. Likewise, if the world coordinate system is a piece of paper, it might return the number of meters per inch of paper. If the SetWorldMapper method is not invoked then this method returns 1.0
Returns
double The resolution, in appropriate units.
References Isis::Projection::m_mapper, and Isis::WorldMapper::Resolution().
Referenced by Isis::ProcessExport::CreateWorldFile(), Isis::Projection::operator==(), and Isis::UniversalGroundMap::Resolution().
Rotation()
double Isis::Projection::Rotation () const inherited
Returns the value of the Rotation keyword from the mapping group.
Returns
double The rotation of the map.
Scale()
double Isis::TProjection::Scale () const virtual inherited
This method returns the scale for mapping world coordinates into projection coordinates.
For example, if the world coordinate system is an image then this routine returns the number of pixels per degree. Likewise, if the world coordinate system is a piece of paper, it might return the number of inches of paper per degree. If the SetWorldMapper method is not invoked then this method returns 1.0
Returns
double The scale for mapping.
Implements Isis::Projection.
References Isis::TProjection::m_equatorialRadius, Isis::Projection::m_mapper, Isis::TProjection::m_polarRadius, Isis::PI, Isis::WorldMapper::Resolution(), and Isis::TProjection::TrueScaleLatitude().
SetComputedXY()
void Isis::Projection::SetComputedXY (double x, double y) protected inherited
This protected method is a helper for derived classes.
It takes unrotated x and y values, rotates them using the rotation angle data member, and stores the results in the current x and y data members.
Parameters
x The unrotated x coordinate.
y The unrotated y coordinate.
References Isis::Projection::m_good, Isis::Null, and Isis::PI.
Referenced by Isis::Equirectangular::SetGround(), Isis::LambertConformal::SetGround(), Isis::LunarAzimuthalEqualArea::SetGround(), Isis::Mercator::SetGround(), Isis::Mollweide::SetGround(), SetGround(), Isis::Orthographic::SetGround(), Isis::PointPerspective::SetGround(), Isis::PolarStereographic::SetGround(), Isis::Robinson::SetGround(), Isis::SimpleCylindrical::SetGround(), Isis::Sinusoidal::SetGround(), Isis::TProjection::SetGround(), Isis::TransverseMercator::SetGround(), Isis::Planar::SetGround(), Isis::RingCylindrical::SetGround(), and Isis::RingPlaneProjection::SetGround().
SetCoordinate()
bool Isis::ObliqueCylindrical::SetCoordinate (const double x, const double y) virtual
This method is used to set the projection x/y.
The Set forces an attempted calculation of the corresponding latitude/longitude position. This may or may not be successful and a status is returned as such.
Parameters
x X coordinate of the projection in units that are the same as the radii in the label
y Y coordinate of the projection in units that are the same as the radii in the label
Returns
bool
Reimplemented from Isis::TProjection.
References Isis::Projection::GetX(), Isis::Projection::GetY(), Isis::HALFPI, Isis::TProjection::m_equatorialRadius, Isis::Projection::m_good, Isis::TProjection::m_latitude, Isis::TProjection::m_longitude, Isis::TProjection::m_longitudeDirection, Isis::PI, poleLatitude(), poleLongitude(), poleRotation(), Isis::TProjection::PositiveWest, and Isis::Projection::SetXY().
SetGround()
bool Isis::ObliqueCylindrical::SetGround (const double lat, const double lon) virtual
This method is used to set the latitude/longitude (assumed to be of the correct LatitudeType, LongitudeDirection, and LongitudeDomain.
The Set forces an attempted calculation of the projection X/Y values. This may or may not be successful and a status is returned as such.
Parameters
lat Latitude value to project
lon Longitude value to project
Returns
bool
Reimplemented from Isis::TProjection.
References Isis::TProjection::m_equatorialRadius, Isis::Projection::m_good, Isis::TProjection::m_latitude, Isis::TProjection::m_longitude, Isis::TProjection::m_longitudeDirection, Isis::PI, poleLatitude(), poleLongitude(), poleRotation(), Isis::TProjection::PositiveWest, and Isis::Projection::SetComputedXY().
setProjectionType()
void Isis::Projection::setProjectionType (const ProjectionType ptype) inherited
Sets the projection subclass type.
Parameters
ptype The projection subclass type
Referenced by Isis::RingPlaneProjection::RingPlaneProjection(), and Isis::TProjection::TProjection().
SetUnboundUniversalGround()
bool Isis::TProjection::SetUnboundUniversalGround (const double lat, const double lon) virtual inherited
This method is used to set the latitude/longitude.
The Set forces an attempted calculation of the projection X/Y values. This may or may not be successful and a status is returned as such. This version does not adjust the longitude based on the longitude domain.
Parameters
lat Planetocentric Latitude value to project
lon PositiveEast, Domain360 Longitude value to project
Returns
bool Indicates whether the method was successful.
Reimplemented from Isis::Projection.
References Isis::Projection::m_good, Isis::TProjection::m_latitude, Isis::TProjection::m_latitudeType, Isis::TProjection::m_longitude, Isis::TProjection::m_longitudeDirection, Isis::Null, Isis::TProjection::Planetographic, Isis::TProjection::PositiveWest, Isis::TProjection::SetGround(), and Isis::TProjection::ToPlanetographic().
Referenced by Isis::Projection::SetUnboundUniversalGround().
SetUniversalGround()
bool Isis::TProjection::SetUniversalGround (const double lat, const double lon) virtual inherited
This method is used to set the latitude/longitude which must be Planetocentric (latitude) and PositiveEast/Domain360 (longitude).
The Set forces an attempted calculation of the projection X/Y values. This may or may not be successful and a status is returned as such.
Parameters
lat Planetocentric Latitude value to project
lon PositiveEast, Domain360 Longitude value to project
Returns
bool Indicates whether the method was successful.
Reimplemented from Isis::Projection.
References Isis::Projection::m_good, Isis::TProjection::m_latitude, Isis::TProjection::m_latitudeType, Isis::TProjection::m_longitude, Isis::TProjection::m_longitudeDirection, Isis::TProjection::m_longitudeDomain, Isis::Null, Isis::TProjection::Planetographic, Isis::TProjection::PositiveWest, Isis::TProjection::SetGround(), Isis::TProjection::To180Domain(), Isis::TProjection::To360Domain(), and Isis::TProjection::ToPlanetographic().
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::MosaicGridTool::setLatExtents(), and Isis::Projection::SetUniversalGround().
SetUpperLeftCorner()
void Isis::Projection::SetUpperLeftCorner (const Displacement & x, const Displacement & y) inherited
This method searches for extreme (min/max/discontinuity) coordinate values along the constBorder line between minBorder and maxBorder (that is, across latitudes/longitudes).
This method locates the extrema by utilizing the findExtreme() method until the coordinate values converge. Then, extremeVal parameter is updated with this value before returning.
Discontinuities are stored in m_specialLatCases and m_specialLonCases so they may be checked again later, which creates significantly more accuracy in some cases.
Parameters
minBorder Minimum latitude or longitude to search between.
maxBorder Maximum latitude or longitude to search between.
extremeVal The resulting global coordinate value (min or max value for x or y, depending on findMin and searchX) on the constBorder.
constBorder The latitude or longitude that remains constant. The method will step along this border.
searchX Indicates whether the method is searching for a min or max x-coordinate. If false the method searches for min or max y-coordinate.
searchLongitude Indicates whether the method will search along a longitude. If true, constBorder is longitude and all other borders are latitudes. If false, the method searches a latitude (constBorder is a lat, other borders lons).
findMin Indicates whether the method is looking for a minimum coordinate value. If false, the method is looking for a maximum value.
Author
Steven Lambright Searches for extreme (min/max/discontinuity) coordinate values across latitudes/longitudes.
This method looks for these extrema along the constBorder between minBorder and maxBorder by stepping along constBorder (10 times) from the minBorder and maxBorder. Then, the range of this extreme value is recorded in minBorder and maxBorder and the coordinate values corresponding to these new borders are stored in minBorderX, minBorderY, maxBorderX and maxBorderY.
This function should be used by calling it repeatedly until minBorderX and minBorderY do not equal maxBorderX and maxBorderY, respectively. Discontinuities will cause the minBorderX, minBorderY, maxBorderX and maxBorderY to never converge. If minBorderX never comes close to maxBorderX or minBorderY never comes close to maxBorderY, then between minBorder and maxBorder is the value of the most extreme value. In this case, either the smaller or larger of the x or y values found will be correct, depending on the values of findMin and searchX.
Parameters
minBorder Minimum latitude or longitude to search between. This value gets updated to a more precise range.
maxBorder Maximum latitude or longitude to search between. This value gets updated to a more precise range.
minBorderX The x-value corresponding to the lower resultant minBorder and the constBorder, which is more accurate when nearly equal to maxBorderX.
minBorderY The y-value corresponding to the lower resultant minBorder and the constBorder, which is more accurate when nearly equal to maxBorderY.
maxBorderX The x-value corresponding to the higher resultant maxBorder and the constBorder, which is more accurate when nearly equal to minBorderX.
maxBorderY The y-value corresponding to the higher resultant maxBorder and the constBorder, which is more accurate when nearly equal to minBorderY.
constBorder The latitude or longitude that remains constant. The method will step along this border.
searchX Indicates whether the method is searching for a min or max x-coordinate. If false the method searches for min or max y-coordinate.
searchLongitude Indicates whether the method will search along a longitude. If true, constBorder is longitude and all other borders are latitudes. If false, the method searches a latitude (constBorder is a lat, other borders lons).
findMin Indicates whether the method is looking for a minimum coordinate value. If false, the method is looking for a maximum value.
Author
Stephen Lambright This function sets the ground for the given border values. It calls the SetGround(lat, lon) method with the appropriate lat/lon values, depending on whether variableIsLat is true.
This method is used by doSearch and findExtreme in order to set the ground correctly each time.
Parameters
variableBorder The latitude or longitude that is variable in the search methods.
constBorder The latitude or longitude that is constant in the search methods.
variableIsLat Indicates whether variableBorder is the latittude value and constBorder is the longitude value. If false, variableBorder is the longitude value and constBorder is the latitude value.
Author
Stephen Lambright This method sets the UpperLeftCornerX and UpperLeftCornerY keywords in the projection mapping group, in meters.
Parameters
x the upper left corner x value
y the upper left corner y value
References Isis::PvlContainer::addKeyword(), Isis::Projection::m_mappingGrp, Isis::Displacement::meters(), Isis::PvlContainer::Replace, and Isis::toString().
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::ProjectionFactory::CreateFromCube(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::ProjectionFactory::RingsCreateFromCube(), and Isis::ProcessMapMosaic::SetOutputCube().
SetWorld()
bool Isis::Projection::SetWorld (const double worldX, const double worldY) virtual inherited
This method is used to set a world coordinate.
A world coordinate is a different coordinate type that has a one-to-one mapping to the projection coordinate system. For example, mapping pixel samples and lines to projection x's and y's. The Set forces an attempted calculation of the corresponding latitude/longitude position. This may or may not be successful and a status is returned as such. Note that is only applies if the Projection object was given an WorldMapper object during construction. If an WorldMapper was not supplied then SetWorld operates exactly the same as SetCoordinate (impling that world coordinate and projection coordinate are identical).
Parameters
worldX World X coordinate in units that are specified by the WorldMapper object (e.g., pixels, millimeters, etc)
worldY World Y coordinate in units that are specified by the WorldMapper object (e.g., pixels, millimeters, etc)
Returns
bool Indicates whether the method was successful.
References Isis::Projection::m_mapper, Isis::WorldMapper::ProjectionX(), Isis::WorldMapper::ProjectionY(), and Isis::Projection::SetCoordinate().
Referenced by Isis::ProcessExport::CreateWorldFile(), Isis::UniversalGroundMap::GroundRange(), Isis::Cube::latLonRange(), Isis::Chip::Load(), Isis::UniversalGroundMap::SetImage(), Isis::SubArea::UpdateLabel(), and Isis::PolygonTools::XYToLatLon().
SetWorldMapper()
void Isis::Projection::SetWorldMapper (WorldMapper * mapper) inherited
If desired the programmer can use this method to set a world mapper to be used in the SetWorld, WorldX, and WorldY methods.
Mappers typically transform a projection coordinate (x/y) into the desired working coordinate system, for example, cube pixels or inches on a piece of paper. They transform in both directions (world to projection and projection to world). This allows for conversions from line/sample to latitude/longitude and vice versa. This projection will take ownership of the WorldMapper pointer.
Parameters
mapper Pointer to the mapper
References Isis::Projection::m_mapper.
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::ProjectionFactory::CreateFromCube(), Isis::ProjectionFactory::RingsCreateForCube(), and Isis::ProjectionFactory::RingsCreateFromCube().
SetXY()
void Isis::Projection::SetXY (double x, double y) protected inherited
This protected method is a helper for derived classes.
It takes a rotated x,y and stores them in the current x and y data members.
Parameters
x The rotated x coordinate.
y The rotated y coordinate.
References Isis::Projection::m_good, and Isis::Null.
Referenced by Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::LunarAzimuthalEqualArea::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Mollweide::SetCoordinate(), SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::Planar::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::RingCylindrical::SetCoordinate(), Isis::RingPlaneProjection::SetCoordinate(), Isis::Robinson::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), Isis::TProjection::SetCoordinate(), and Isis::TransverseMercator::SetCoordinate().
tCompute()
double Isis::TProjection::tCompute (const double phi, const double sinphi) const protected inherited
A convience method to compute Snyder's t equation (15-9) for a given latitude, \(\phi\).
\[ t = \frac{\tan\left(\frac{\pi}{4} - \frac{\phi}{2}\right)} {\left[\frac{1-e\sin(\phi)} {1+e\sin(\phi)}\right]^{e/2}} \]
where \(e\) is the eccentricity for the body.
Parameters
phi phi
sinphi sin of phi
Returns
double The value for Snyder's t variable.
References Isis::TProjection::Eccentricity(), and Isis::HALFPI.
Referenced by Isis::LambertConformal::LambertConformal(), Isis::PolarStereographic::PolarStereographic(), Isis::LambertConformal::SetGround(), Isis::Mercator::SetGround(), and Isis::PolarStereographic::SetGround().
To180Domain()
double Isis::TProjection::To180Domain (const double lon) static inherited
This method converts a longitude into the -180 to 180 domain.
It will leave the longitude unchanged if it is already in the domain.
Parameters
lon Longitude to convert into the -180 to 180 domain.
Exceptions
IException::Unknown - "The given longitude is invalid."
Returns
double The longitude, converted to 180 domain.
References _FILEINFO_, Isis::Angle::Degrees, Isis::Angle::degrees(), Isis::Longitude::force180Domain(), Isis::Null, Isis::toString(), and Isis::IException::Unknown.
Referenced by Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::TransverseMercator::SetCoordinate(), Isis::TProjection::SetUniversalGround(), Isis::TProjection::ToPositiveEast(), Isis::TProjection::ToPositiveWest(), and Isis::SubArea::UpdateLabel().
To360Domain()
double Isis::TProjection::To360Domain (const double lon) static inherited
This method converts a longitude into the 0 to 360 domain.
It will leave the longitude unchanged if it is already in the domain.
Parameters
lon Longitude to convert into the 0 to 360 domain.
Returns
double The longitude, converted to 360 domain.
References _FILEINFO_, Isis::Angle::Degrees, Isis::Angle::degrees(), Isis::Longitude::force360Domain(), Isis::Null, Isis::toString(), and Isis::IException::Unknown.
Referenced by Isis::TProjection::inLongitudeRange(), Isis::Stereo::rectangular(), Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::TransverseMercator::SetCoordinate(), Isis::TProjection::SetUniversalGround(), Isis::TProjection::ToPositiveEast(), Isis::TProjection::ToPositiveWest(), Isis::TProjection::UniversalLongitude(), and Isis::Orthographic::XYRange().
ToDMS()
QString Isis::Projection::ToDMS (double angle) static inherited
Converts the given angle (in degrees) to degrees, minutes, seconds.
Outputs in the form xxx yym zz.zzzs, for example, 206.291 degrees is 206 17m 27.6s
Parameters
angle Angle in degrees to be converted to degrees, minutes, seconds
Returns
string The angle in Degrees, minutes, seconds
ToHMS()
QString Isis::Projection::ToHMS (double angle) static inherited
Converts the given angle (in degrees) to hours, minutes, seconds.
Outputs in the form xxh yym zz.zzzs For example, 206.291 will be 13h 45m 09.84s
Parameters
angle Angle in degrees to be converted to hours, minutes, seconds
Returns
string The angle in Hours, minutes, seconds
References Isis::Projection::ToHours().
ToHours()
double Isis::Projection::ToHours (double angle) static inherited
Converts the given angle (in degrees) to hours by using the ratio 15 degrees per hour.
Parameters
angle Angle in degrees to be converted to hours
Returns
double The number of hours for the given angle.
Referenced by Isis::Projection::ToHMS().
ToPlanetocentric() [1/2]
double Isis::TProjection::ToPlanetocentric (const double lat) const inherited
This method converts a planetographic latitude to a planetocentric latitude.
It utilizes the equatorial and polar radii found in the labels to perform the computation.
Parameters
lat Planetographic latitude to convert.
See also
ToPlanetocentric(lat, eRadius, pRadius)
Returns
double The latitude, converted to planetocentric.
References Isis::TProjection::m_equatorialRadius, and Isis::TProjection::m_polarRadius.
Referenced by Isis::LambertConformal::SetCoordinate(), Isis::LunarAzimuthalEqualArea::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::TransverseMercator::SetCoordinate(), and Isis::TProjection::UniversalLatitude().
ToPlanetocentric() [2/2]
double Isis::TProjection::ToPlanetocentric (double lat, double eRadius, double pRadius) static inherited
This method converts a planetographic latitude to a planetocentric latitude.
Parameters
lat Planetographic latitude to convert.
eRadius Equatorial radius.
pRadius Polar radius
Exceptions
IException::Unknown - "The given latitude is invalid."
Returns
double The latitude, converted to planetocentric.
References _FILEINFO_, Isis::Null, Isis::PI, Isis::toString(), and Isis::IException::Unknown.
ToPlanetographic() [1/2]
double Isis::TProjection::ToPlanetographic (const double lat) const inherited
This method converts a planetocentric latitude to a planetographic latitude.
It utilizes the equatorial and polar radii found in the labels to perform the computation.
Parameters
lat Planetocentric latitude to convert.
See also
ToPlanetographic(lat, eRadius, pRadius)
Returns
double The latitude, converted to planetographic.
References Isis::TProjection::m_equatorialRadius, and Isis::TProjection::m_polarRadius.
Referenced by Isis::LambertConformal::LambertConformal(), Isis::Mercator::Mercator(), ObliqueCylindrical(), Isis::Orthographic::Orthographic(), Isis::PointPerspective::PointPerspective(), Isis::PolarStereographic::PolarStereographic(), Isis::LambertConformal::SetGround(), Isis::LunarAzimuthalEqualArea::SetGround(), Isis::Mercator::SetGround(), Isis::Orthographic::SetGround(), Isis::PointPerspective::SetGround(), Isis::PolarStereographic::SetGround(), Isis::TransverseMercator::SetGround(), Isis::TProjection::SetUnboundUniversalGround(), Isis::TProjection::SetUniversalGround(), Isis::TransverseMercator::TransverseMercator(), and Isis::SubArea::UpdateLabel().
ToPlanetographic() [2/2]
double Isis::TProjection::ToPlanetographic (double lat, double eRadius, double pRadius) static inherited
This method converts a planetocentric latitude to a planetographic latitude.
It is static so that a projection object does not need to exist.
Parameters
lat Planetocentric latitude to convert.
eRadius Equatorial radius.
pRadius Polar radius
Exceptions
IException::Unknown - "The given latitude is invalid."
Returns
double The latitude, converted to planetographic.
References _FILEINFO_, Isis::Null, Isis::PI, Isis::toString(), and Isis::IException::Unknown.
ToPositiveEast()
double Isis::TProjection::ToPositiveEast (const double lon, const int domain) static inherited
This method converts a longitude into the positive east direction.
Parameters
lon Longitude to convert into the positive east direction.
domain Must be an integer value of 180 (for -180 to 180) or 360 (for 0 to 360).
Exceptions
IException::Unknown - "The given longitude is invalid."
IException::Unknown - "Unable to convert longitude. Domain is not 180 or 360."
Returns
double Longitude value, in positive east direction.
References _FILEINFO_, Isis::Null, Isis::TProjection::To180Domain(), Isis::TProjection::To360Domain(), Isis::toString(), and Isis::IException::Unknown.
ToPositiveWest()
double Isis::TProjection::ToPositiveWest (const double lon, const int domain) static inherited
This method converts a longitude into the positive west direction.
Parameters
lon Longitude to convert into the positive west direction.
domain Must be an integer value of 180 (for -180 to 180) or 360 (for 0 to 360).
Exceptions
IException::Unknown - "The given longitude is invalid."
IException::Unknown - "Unable to convert longitude. Domain is not 180 or 360."
Returns
double Longitude value, in positive west direction.
References _FILEINFO_, Isis::Null, Isis::TProjection::To180Domain(), Isis::TProjection::To360Domain(), Isis::toString(), and Isis::IException::Unknown.
Referenced by Isis::SubArea::UpdateLabel().
ToProjectionX()
double Isis::Projection::ToProjectionX (const double worldX) const inherited
This method converts a world x value to a projection x value.
For example, if the world coordinate system is an image then this method converts a sample position to a projection x value. Note that if SetWorldMapper is not used then this routine simply returns the value of the argument. That is, no mapping occurs.
Parameters
worldX World x coordinate
Exceptions
IException::Unknown - "The given x-value is invalid."
Returns
double The projection X coordinate value.
References _FILEINFO_, Isis::Projection::m_mapper, Isis::Null, Isis::WorldMapper::ProjectionX(), and Isis::IException::Unknown.
Referenced by Isis::OverlapStatistics::OverlapStatistics(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::ProcessMapMosaic::StartProcess().
ToProjectionY()
double Isis::Projection::ToProjectionY (const double worldY) const inherited
This method converts a world y value to a projection y value.
For example, if the world coordinate system is an image then this method converts a line position to a projection y value. Note that if SetWorldMapper is not used then this routine simply returns the value of the argument. That is, no mapping occurs.
Parameters
worldY World y coordinate
Exceptions
IException::Unknown - "The given y-value is invalid."
Returns
double The projection Y coordinate value.
References _FILEINFO_, Isis::Projection::m_mapper, Isis::Null, Isis::WorldMapper::ProjectionY(), and Isis::IException::Unknown.
Referenced by Isis::OverlapStatistics::OverlapStatistics(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::ProcessMapMosaic::StartProcess().
ToWorldX()
double Isis::Projection::ToWorldX (const double projectionX) const inherited
This method converts a projection x value to a world x value.
For example, if the world coordinate system is an image then this method converts a projection x to a sample position. Note that if SetWorldMapper is not used then this routine simply returns the value of the argument. That is, no mapping occurs.
Parameters
projectionX Projection x value in meters
Exceptions
IException::Unknown - "The given x-value is invalid."
Returns
double The world X coordinate value.
References _FILEINFO_, Isis::Projection::m_mapper, Isis::Null, Isis::IException::Unknown, and Isis::WorldMapper::WorldX().
Referenced by Isis::OverlapStatistics::OverlapStatistics(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::ProcessMapMosaic::StartProcess().
ToWorldY()
double Isis::Projection::ToWorldY (const double projectionY) const inherited
This method converts a projection y value to a world y value.
For example, if the world coordinate system is an image then this method converts a projection y to a line position. Note that if SetWorldMapper is not used then this routine simply returns the value of the argument. That is, no mapping occurs.
Parameters
projectionY Projection y value in meters
Exceptions
IException::Unknown - "The given y-value is invalid."
Returns
double The world Y coordinate value.
References _FILEINFO_, Isis::Projection::m_mapper, Isis::Null, Isis::IException::Unknown, and Isis::WorldMapper::WorldY().
Referenced by Isis::OverlapStatistics::OverlapStatistics(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::ProcessMapMosaic::StartProcess().
TrueScaleLatitude()
double Isis::TProjection::TrueScaleLatitude () const virtual inherited
This method returns the latitude of true scale.
It is a virtual function and if it is not overriden the default latitude of true scale is 0 (at the equator). Otherwise it is projection specific. For example, the center latitude for Mercator, Equidistant, or a parallel for conic projections. This method is used by the Scale routine to ensure the local radius is used in the computation.
Returns
double The latitude where the projection is not distorted.
Reimplemented in Isis::PolarStereographic, Isis::PointPerspective, Isis::Orthographic, Isis::Mercator, Isis::LambertConformal, Isis::LambertAzimuthalEqualArea, and Isis::Equirectangular.
Referenced by Isis::TiffImporter::convertProjection(), Isis::ProjectionFactory::CreateForCube(), and Isis::TProjection::Scale().
UniversalLatitude()
double Isis::TProjection::UniversalLatitude () virtual inherited
This returns a universal latitude (planetocentric).
The method can only be used if SetGround, SetCoordinate, SetUniversalGround, or SetWorld return with success. Success can also be checked using the IsGood method.
Returns
double The universal latitude.
References Isis::TProjection::m_latitude, Isis::TProjection::m_latitudeType, Isis::TProjection::Planetographic, and Isis::TProjection::ToPlanetocentric().
Referenced by Isis::UniversalGroundMap::GroundRange(), Isis::Cube::latLonRange(), Isis::Chip::Load(), Isis::UniversalGroundMap::UniversalLatitude(), and Isis::SubArea::UpdateLabel().
UniversalLongitude()
double Isis::TProjection::UniversalLongitude () virtual inherited
This returns a universal longitude (positive east in 0 to 360 domain).
The method can only be used if SetGround, SetCoordinate, SetUniversalGround, or SetWorld return with success. Success can also be checked using the IsGood method.
Returns
double The universal longitude.
References Isis::TProjection::m_longitude, Isis::TProjection::m_longitudeDirection, Isis::TProjection::PositiveWest, and Isis::TProjection::To360Domain().
Referenced by Isis::UniversalGroundMap::GroundRange(), Isis::Cube::latLonRange(), Isis::Chip::Load(), Isis::UniversalGroundMap::UniversalLongitude(), and Isis::SubArea::UpdateLabel().
Version()
QString Isis::ObliqueCylindrical::Version () const virtual
Returns the version of the map projection.
Returns
std::QString Version number
Implements Isis::TProjection.
WorldX()
double Isis::Projection::WorldX () const virtual inherited
This returns the world X coordinate provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
Success can also be checked using the IsGood method. The units of X will be in the units as specified by the WorldMapper object which was given to the SetWorldMapper method. If a mapper object was not given then world coordinates are the same as the projection coordinates (i.e., WorldX and XCoord will return the same value).
Returns
double The world X coordinate.
References Isis::Projection::m_mapper, and Isis::WorldMapper::WorldX().
Referenced by Isis::Chip::Load(), Isis::DemShape::localRadius(), Isis::UniversalGroundMap::Sample(), Isis::Camera::SetRightAscensionDeclination(), and Isis::ProcessMapMosaic::StartProcess().
WorldY()
double Isis::Projection::WorldY () const virtual inherited
This returns the world Y coordinate provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
Success can also be checked using the IsGood method. The units of Y will be in the units as specified by the WorldMapper object which was given to the SetWorldMapper. If a mapper object was not given then world coordinates are the same as the projection coordinates (i.e., WorldY and YCoord will return the same value).
Returns
double The world Y coordinate.
References Isis::Projection::m_mapper, and Isis::WorldMapper::WorldY().
Referenced by Isis::UniversalGroundMap::Line(), Isis::Chip::Load(), Isis::DemShape::localRadius(), and Isis::Camera::SetRightAscensionDeclination().
XCoord()
double Isis::Projection::XCoord () const inherited
This returns the projection X provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
Success can also be checked using the IsGood method. The units of X will be in the same . units as the radii obtained from the label.
Returns
double
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::ProcessExport::CreateWorldFile(), Isis::MosaicFindTool::getUserGroundPoint(), Isis::GridGraphicsItem::GridGraphicsItem(), Isis::PolygonTools::LatLonToXY(), Isis::MosaicSceneItem::reproject(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::RingPlaneProjection::SetCoordinate(), Isis::TProjection::SetCoordinate(), Isis::MosaicGridTool::setLatExtents(), Isis::SubArea::UpdateLabel(), Isis::MosaicAreaTool::userChangedBox(), Isis::LambertConformal::XYRange(), Isis::PointPerspective::XYRange(), Isis::TProjection::XYRangeCheck(), and Isis::RingPlaneProjection::XYRangeCheck().
XYRange()
bool Isis::ObliqueCylindrical::XYRange (double & minX, double & maxX, double & minY, double & maxY) virtual
This method is used to determine the x/y range which completely covers the area of interest specified by the lat/lon range.
The latitude/longitude range may be obtained from the labels. The purpose of this method is to return the x/y range so it can be used to compute how large a map may need to be. For example, how big a piece of paper is needed or how large of an image needs to be created. The method may fail as indicated by its return value.
This function works for most cases, especially on smaller areas. However, larger areas are likely to fail due to numerous discontinuities and a lack of a mathematical algorithm to solve the range. This method works by searching the boundaries, using DoSearch, and then searching lines tangent to discontinuities.
Parameters
minX Minimum x projection coordinate which covers the latitude longitude range specified in the labels.
maxX Maximum x projection coordinate which covers the latitude longitude range specified in the labels.
minY Minimum y projection coordinate which covers the latitude longitude range specified in the labels.
maxY Maximum y projection coordinate which covers the latitude longitude range specified in the labels.
Returns
bool
Reimplemented from Isis::TProjection.
References Isis::TProjection::xyRangeOblique().
XYRangeCheck()
void Isis::TProjection::XYRangeCheck (const double latitude, const double longitude) protected virtual inherited
This convience function is established to assist in the development of the XYRange virtual method.
It allows the developer to test ground points (lat/lon) to see if they produce a minimum/maximum projection coordinate.
This method will first verify that the given latitude and longitude values are not Null. If so, the method will change the status of the object to good=false before returning (i.e IsGood() returns false).
If both of those test pass, it attempts to set the ground to the given latitude and longitude and, if successful, compares the new x and y with the saved min/max x and y values.
For example in Sinusoidal this method is called in the following way:
 bool Sinusoidal::XYRange(double &minX, double &maxX,
                          double &minY, double &maxY) {
   // Check the corners of the lat/lon range
   XYRangeCheck (m_minimumLatitude,m_minimumLongitude);
   XYRangeCheck (m_maximumLatitude,m_minimumLongitude);
   XYRangeCheck (m_minimumLatitude,m_maximumLongitude);
   XYRangeCheck (m_maximumLatitude,m_maximumLongitude);
   // In case the latitude crosses the equator, check there
   if (inLatitudeRange(0.0)) {
     XYRangeCheck (0.0,m_minimumLongitude);
     XYRangeCheck (0.0,m_maximumLongitude);
   }
   // Make sure everything is ordered
   if (m_minimumX >= m_maximumX) return false;
   if (m_minimumY >= m_maximumY) return false;
   // Return X/Y min/maxs
   minX = m_minimumX;
   maxX = m_maximumX;
   minY = m_minimumY;
   maxY = m_maximumY;
   return true;
}
Note: It is a good habit to call the inLatitudeRange and inLongitudeRange functions to verify that the values are in range before passing it to XYRangeCheck.
See also
inLongitudeRange(minLon, maxLon, longitude)
inLongitudeRange(longitude)
inLatitudeRange(latitude)
Parameters
latitude Test for min/max projection coordinates at this latitude
longitude Test for min/max projection coordinates at this longitude
Implements Isis::Projection.
References Isis::Projection::IsGood(), Isis::Projection::m_good, Isis::Projection::m_maximumX, Isis::Projection::m_maximumY, Isis::Projection::m_minimumX, Isis::Projection::m_minimumY, Isis::Null, Isis::TProjection::SetGround(), Isis::Projection::XCoord(), and Isis::Projection::YCoord().
Referenced by Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::PolarStereographic::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), and Isis::TransverseMercator::XYRange().
xyRangeOblique()
bool Isis::TProjection::xyRangeOblique (double & minX, double & maxX, double & minY, double & maxY) protected inherited
This method is used to find the XY range for oblique aspect projections (non-polar projections) by "walking" around each of the min/max lat/lon.
Parameters
minX Minimum x projection coordinate which covers the latitude longitude range specified in the labels.
maxX Maximum x projection coordinate which covers the latitude longitude range specified in the labels.
minY Minimum y projection coordinate which covers the latitude longitude range specified in the labels.
maxY Maximum y projection coordinate which covers the latitude longitude range specified in the labels.
Returns
bool Indicates whether the method was successful.
See also
XYRange()
Author
Stephen Lambright
References Isis::Projection::HasGroundRange(), Isis::Projection::m_maximumX, Isis::Projection::m_maximumY, Isis::Projection::m_minimumX, Isis::Projection::m_minimumY, Isis::TProjection::MaximumLatitude(), Isis::TProjection::MaximumLongitude(), Isis::TProjection::MinimumLatitude(), Isis::TProjection::MinimumLongitude(), and Isis::Null.
Referenced by XYRange().
YCoord()
double Isis::Projection::YCoord () const inherited
This returns the projection Y provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
Success can also be checked using the IsGood method. The units of Y will be in the same units as the radii obtained from the label.
Returns
double
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::ProcessExport::CreateWorldFile(), Isis::MosaicFindTool::getUserGroundPoint(), Isis::GridGraphicsItem::GridGraphicsItem(), Isis::PolygonTools::LatLonToXY(), Isis::MosaicSceneItem::reproject(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::RingPlaneProjection::SetCoordinate(), Isis::TProjection::SetCoordinate(), Isis::MosaicGridTool::setLatExtents(), Isis::SubArea::UpdateLabel(), Isis::MosaicAreaTool::userChangedBox(), Isis::LambertConformal::XYRange(), Isis::PointPerspective::XYRange(), Isis::TProjection::XYRangeCheck(), and Isis::RingPlaneProjection::XYRangeCheck().
Member Data Documentation
m_eccentricity
double Isis::TProjection::m_eccentricity protected inherited
The eccentricity of the target body.
Referenced by Isis::TProjection::Eccentricity(), Isis::TProjection::qCompute(), and Isis::TProjection::TProjection().
m_equatorialRadius
double Isis::TProjection::m_equatorialRadius protected inherited
Polar radius of the target.
This is a unitless value so that if the radii are in inches then the m_x and m_y will be in inches. This value is set on construction. It is either read directly from the mapping group of the given PVL label or it is found in NAIF kernels by using the Target value in the given label. When pulled from NAIF kernels, the equatorial radius is the first value of NAIF's radii array.
Referenced by Isis::TProjection::EquatorialRadius(), Isis::LambertConformal::LambertConformal(), Isis::TProjection::LocalRadius(), Isis::PointPerspective::PointPerspective(), Isis::TProjection::Scale(), Isis::LambertConformal::SetCoordinate(), Isis::LunarAzimuthalEqualArea::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Mollweide::SetCoordinate(), SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::Robinson::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), Isis::TransverseMercator::SetCoordinate(), Isis::LambertConformal::SetGround(), Isis::LunarAzimuthalEqualArea::SetGround(), Isis::Mercator::SetGround(), Isis::Mollweide::SetGround(), SetGround(), Isis::Orthographic::SetGround(), Isis::PointPerspective::SetGround(), Isis::PolarStereographic::SetGround(), Isis::Robinson::SetGround(), Isis::SimpleCylindrical::SetGround(), Isis::Sinusoidal::SetGround(), Isis::TransverseMercator::SetGround(), Isis::TProjection::ToPlanetocentric(), Isis::TProjection::ToPlanetographic(), Isis::TProjection::TProjection(), Isis::TransverseMercator::TransverseMercator(), Isis::Orthographic::XYRange(), and Isis::PointPerspective::XYRange().
m_good
bool Isis::Projection::m_good protected inherited
Indicates if the contents of m_x, m_y, m_latitude, and m_longitude are valid.
Referenced by Isis::Projection::IsGood(), Isis::Projection::Projection(), Isis::Projection::SetComputedXY(), Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::LunarAzimuthalEqualArea::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Mollweide::SetCoordinate(), SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::Planar::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::RingCylindrical::SetCoordinate(), Isis::RingPlaneProjection::SetCoordinate(), Isis::Robinson::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), Isis::TProjection::SetCoordinate(), Isis::TransverseMercator::SetCoordinate(), Isis::Equirectangular::SetGround(), Isis::LambertConformal::SetGround(), Isis::LunarAzimuthalEqualArea::SetGround(), Isis::Mercator::SetGround(), Isis::Mollweide::SetGround(), SetGround(), Isis::Orthographic::SetGround(), Isis::PointPerspective::SetGround(), Isis::PolarStereographic::SetGround(), Isis::Robinson::SetGround(), Isis::SimpleCylindrical::SetGround(), Isis::Sinusoidal::SetGround(), Isis::TProjection::SetGround(), Isis::TransverseMercator::SetGround(), Isis::Planar::SetGround(), Isis::RingCylindrical::SetGround(), Isis::RingPlaneProjection::SetGround(), Isis::Projection::SetUnboundUniversalGround(), Isis::TProjection::SetUnboundUniversalGround(), Isis::Projection::SetUniversalGround(), Isis::TProjection::SetUniversalGround(), Isis::RingPlaneProjection::SetUniversalGround(), Isis::Projection::SetXY(), Isis::LambertConformal::XYRange(), Isis::TProjection::XYRangeCheck(), and Isis::RingPlaneProjection::XYRangeCheck().
m_groundRangeGood
bool Isis::Projection::m_groundRangeGood protected inherited
Indicates if the ground range (min/max lat/lons) were read from the labels.
Referenced by Isis::Projection::HasGroundRange(), Isis::RingPlaneProjection::RingPlaneProjection(), Isis::TProjection::TProjection(), Isis::RingPlaneProjection::XYRange(), and Isis::TProjection::XYRange().
m_latitude
double Isis::TProjection::m_latitude protected inherited
This contains the currently set latitude value.
The value is only usable if m_good is true.
Referenced by Isis::TProjection::Latitude(), Isis::TProjection::LocalRadius(), Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::LunarAzimuthalEqualArea::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Mollweide::SetCoordinate(), SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::Robinson::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), Isis::TProjection::SetCoordinate(), Isis::TransverseMercator::SetCoordinate(), Isis::Equirectangular::SetGround(), Isis::LambertConformal::SetGround(), Isis::LunarAzimuthalEqualArea::SetGround(), Isis::Mercator::SetGround(), Isis::Mollweide::SetGround(), SetGround(), Isis::Orthographic::SetGround(), Isis::PointPerspective::SetGround(), Isis::PolarStereographic::SetGround(), Isis::Robinson::SetGround(), Isis::SimpleCylindrical::SetGround(), Isis::Sinusoidal::SetGround(), Isis::TProjection::SetGround(), Isis::TransverseMercator::SetGround(), Isis::TProjection::SetUnboundUniversalGround(), Isis::TProjection::SetUniversalGround(), Isis::TProjection::TProjection(), Isis::TProjection::UniversalLatitude(), Isis::LambertConformal::XYRange(), and Isis::Orthographic::XYRange().
m_latitudeType
LatitudeType Isis::TProjection::m_latitudeType protected inherited
An enumerated type indicating the LatitudeType read from the labels.
It can be either Planetographic or Planetocentric.
Referenced by Isis::TProjection::IsPlanetocentric(), Isis::TProjection::IsPlanetographic(), Isis::TProjection::LatitudeTypeString(), Isis::TProjection::SetUnboundUniversalGround(), Isis::TProjection::SetUniversalGround(), Isis::TProjection::TProjection(), and Isis::TProjection::UniversalLatitude().
m_longitude
double Isis::TProjection::m_longitude protected inherited
This contains the currently set longitude value.
The value is only usable if m_good is true.
Referenced by Isis::TProjection::Longitude(), Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::LunarAzimuthalEqualArea::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Mollweide::SetCoordinate(), SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::Robinson::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), Isis::TProjection::SetCoordinate(), Isis::TransverseMercator::SetCoordinate(), Isis::Equirectangular::SetGround(), Isis::LambertConformal::SetGround(), Isis::LunarAzimuthalEqualArea::SetGround(), Isis::Mercator::SetGround(), Isis::Mollweide::SetGround(), SetGround(), Isis::Orthographic::SetGround(), Isis::PointPerspective::SetGround(), Isis::PolarStereographic::SetGround(), Isis::Robinson::SetGround(), Isis::SimpleCylindrical::SetGround(), Isis::Sinusoidal::SetGround(), Isis::TProjection::SetGround(), Isis::TransverseMercator::SetGround(), Isis::TProjection::SetUnboundUniversalGround(), Isis::TProjection::SetUniversalGround(), Isis::TProjection::TProjection(), Isis::TProjection::UniversalLongitude(), Isis::LambertConformal::XYRange(), and Isis::Orthographic::XYRange().
m_longitudeDirection
LongitudeDirection Isis::TProjection::m_longitudeDirection protected inherited
An enumerated type indicating the LongitudeDirection read from the labels.
It can be either PositiveEast or PositiveWest. Indicating which direction the positive axis for longitude is.
Referenced by Isis::Equirectangular::Equirectangular(), Isis::TProjection::IsPositiveEast(), Isis::TProjection::IsPositiveWest(), Isis::LambertConformal::LambertConformal(), Isis::TProjection::LongitudeDirectionString(), Isis::Mercator::Mercator(), Isis::Mollweide::Mollweide(), Isis::Orthographic::Orthographic(), Isis::PointPerspective::PointPerspective(), Isis::PolarStereographic::PolarStereographic(), Isis::Robinson::Robinson(), Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Mollweide::SetCoordinate(), SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::Robinson::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), Isis::TransverseMercator::SetCoordinate(), Isis::Equirectangular::SetGround(), Isis::LambertConformal::SetGround(), Isis::LunarAzimuthalEqualArea::SetGround(), Isis::Mercator::SetGround(), Isis::Mollweide::SetGround(), SetGround(), Isis::Orthographic::SetGround(), Isis::PointPerspective::SetGround(), Isis::PolarStereographic::SetGround(), Isis::Robinson::SetGround(), Isis::SimpleCylindrical::SetGround(), Isis::Sinusoidal::SetGround(), Isis::TransverseMercator::SetGround(), Isis::TProjection::SetUnboundUniversalGround(), Isis::TProjection::SetUniversalGround(), Isis::SimpleCylindrical::SimpleCylindrical(), Isis::Sinusoidal::Sinusoidal(), Isis::TProjection::TProjection(), Isis::TransverseMercator::TransverseMercator(), Isis::TProjection::UniversalLongitude(), Isis::LambertConformal::XYRange(), and Isis::PolarStereographic::XYRange().
m_longitudeDomain
int Isis::TProjection::m_longitudeDomain protected inherited
This integer is either 180 or 360 and is read from the labels.
It represents the longitude domain when returning values through Longitude method. The domain is either -180 to 180 or 0 to 360.
Referenced by Isis::TProjection::Has180Domain(), Isis::TProjection::Has360Domain(), Isis::TProjection::LongitudeDomainString(), Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::TransverseMercator::SetCoordinate(), Isis::TProjection::SetUniversalGround(), and Isis::TProjection::TProjection().
m_mapper
WorldMapper* Isis::Projection::m_mapper protected inherited
This points to a mapper passed into the SetWorldMapper method.
This mapper allows the programmer to specify a different world coordinate system. Thus the programmer could pass in line/sample positions in order to obtain a latitude/longitude or set a lat/lon and get a line/sample.
Referenced by Isis::Projection::Projection(), Isis::Projection::Resolution(), Isis::RingPlaneProjection::Scale(), Isis::TProjection::Scale(), Isis::Projection::SetWorld(), Isis::Projection::SetWorldMapper(), Isis::Projection::ToProjectionX(), Isis::Projection::ToProjectionY(), Isis::Projection::ToWorldX(), Isis::Projection::ToWorldY(), Isis::Projection::WorldX(), Isis::Projection::WorldY(), and Isis::Projection::~Projection().
m_mappingGrp
PvlGroup Isis::Projection::m_mappingGrp protected inherited
Mapping group that created this projection.
Referenced by Isis::Equirectangular::Mapping(), Isis::LambertConformal::Mapping(), Isis::LunarAzimuthalEqualArea::Mapping(), Isis::Mercator::Mapping(), Isis::Mollweide::Mapping(), Mapping(), Isis::Orthographic::Mapping(), Isis::PointPerspective::Mapping(), Isis::PolarStereographic::Mapping(), Isis::RingPlaneProjection::Mapping(), Isis::Robinson::Mapping(), Isis::SimpleCylindrical::Mapping(), Isis::Sinusoidal::Mapping(), Isis::TProjection::Mapping(), Isis::TransverseMercator::Mapping(), Isis::Equirectangular::MappingLatitudes(), Isis::LambertConformal::MappingLatitudes(), Isis::Mercator::MappingLatitudes(), Isis::Orthographic::MappingLatitudes(), Isis::PointPerspective::MappingLatitudes(), Isis::PolarStereographic::MappingLatitudes(), Isis::TProjection::MappingLatitudes(), Isis::TransverseMercator::MappingLatitudes(), Isis::Equirectangular::MappingLongitudes(), Isis::LambertConformal::MappingLongitudes(), Isis::Mercator::MappingLongitudes(), Isis::Mollweide::MappingLongitudes(), Isis::Orthographic::MappingLongitudes(), Isis::PointPerspective::MappingLongitudes(), Isis::PolarStereographic::MappingLongitudes(), Isis::Robinson::MappingLongitudes(), Isis::SimpleCylindrical::MappingLongitudes(), Isis::Sinusoidal::MappingLongitudes(), Isis::TProjection::MappingLongitudes(), Isis::TransverseMercator::MappingLongitudes(), Isis::Planar::MappingRingLongitudes(), Isis::RingCylindrical::MappingRingLongitudes(), Isis::RingPlaneProjection::MappingRingLongitudes(), Isis::Planar::MappingRingRadii(), Isis::RingCylindrical::MappingRingRadii(), Isis::RingPlaneProjection::MappingRingRadii(), Isis::Projection::Projection(), Isis::RingPlaneProjection::RingPlaneProjection(), Isis::Projection::SetUpperLeftCorner(), and Isis::TProjection::TProjection().
m_maximumLatitude
double Isis::TProjection::m_maximumLatitude protected inherited
Contains the maximum latitude for the entire ground range.
Only usable if m_groundRangeGood is true.
Referenced by Isis::Equirectangular::Equirectangular(), Isis::LambertConformal::LambertConformal(), Isis::TProjection::MaximumLatitude(), Isis::Mercator::Mercator(), Isis::Orthographic::Orthographic(), Isis::PointPerspective::PointPerspective(), Isis::PolarStereographic::PolarStereographic(), Isis::TProjection::TProjection(), Isis::TransverseMercator::TransverseMercator(), Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::PolarStereographic::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), Isis::TProjection::XYRange(), and Isis::TransverseMercator::XYRange().
m_maximumLongitude
double Isis::TProjection::m_maximumLongitude protected inherited
Contains the maximum longitude for the entire ground range.
Only usable if m_groundRangeGood is true.
Referenced by Isis::Equirectangular::Equirectangular(), Isis::LambertConformal::LambertConformal(), Isis::TProjection::MaximumLongitude(), Isis::Mercator::Mercator(), Isis::Mollweide::Mollweide(), Isis::Orthographic::Orthographic(), Isis::PointPerspective::PointPerspective(), Isis::PolarStereographic::PolarStereographic(), Isis::Robinson::Robinson(), Isis::SimpleCylindrical::SimpleCylindrical(), Isis::Sinusoidal::Sinusoidal(), Isis::TProjection::TProjection(), Isis::TransverseMercator::TransverseMercator(), Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::PolarStereographic::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), Isis::TProjection::XYRange(), and Isis::TransverseMercator::XYRange().
m_maximumX
double Isis::Projection::m_maximumX protected inherited
See minimumX description.
Referenced by Isis::Projection::Projection(), Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::Planar::XYRange(), Isis::PolarStereographic::XYRange(), Isis::RingCylindrical::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), Isis::TransverseMercator::XYRange(), Isis::TProjection::XYRangeCheck(), Isis::RingPlaneProjection::XYRangeCheck(), and Isis::TProjection::xyRangeOblique().
m_maximumY
double Isis::Projection::m_maximumY protected inherited
See minimumX description.
Referenced by Isis::Projection::Projection(), Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::Planar::XYRange(), Isis::PolarStereographic::XYRange(), Isis::RingCylindrical::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), Isis::TransverseMercator::XYRange(), Isis::TProjection::XYRangeCheck(), Isis::RingPlaneProjection::XYRangeCheck(), and Isis::TProjection::xyRangeOblique().
m_minimumLatitude
double Isis::TProjection::m_minimumLatitude protected inherited
Contains the minimum latitude for the entire ground range.
Only usable if m_groundRangeGood is true.
Referenced by Isis::Equirectangular::Equirectangular(), Isis::LambertConformal::LambertConformal(), Isis::Mercator::Mercator(), Isis::TProjection::MinimumLatitude(), Isis::Orthographic::Orthographic(), Isis::PointPerspective::PointPerspective(), Isis::PolarStereographic::PolarStereographic(), Isis::TProjection::TProjection(), Isis::TransverseMercator::TransverseMercator(), Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::PolarStereographic::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), Isis::TProjection::XYRange(), and Isis::TransverseMercator::XYRange().
m_minimumLongitude
double Isis::TProjection::m_minimumLongitude protected inherited
Contains the minimum longitude for the entire ground range.
Only usable if m_groundRangeGood is true.
Referenced by Isis::Equirectangular::Equirectangular(), Isis::LambertConformal::LambertConformal(), Isis::Mercator::Mercator(), Isis::TProjection::MinimumLongitude(), Isis::Mollweide::Mollweide(), Isis::Orthographic::Orthographic(), Isis::PointPerspective::PointPerspective(), Isis::PolarStereographic::PolarStereographic(), Isis::Robinson::Robinson(), Isis::SimpleCylindrical::SimpleCylindrical(), Isis::Sinusoidal::Sinusoidal(), Isis::TProjection::TProjection(), Isis::TransverseMercator::TransverseMercator(), Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::PolarStereographic::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), Isis::TProjection::XYRange(), and Isis::TransverseMercator::XYRange().
m_minimumX
double Isis::Projection::m_minimumX protected inherited
The data elements m_minimumX, m_minimumY, m_maximumX, and m_maximumY are convience data elements when you write the XYRange virtual function.
They are used in conjuction with the XYRangeCheck convience method. After utilizing XYRangeCheck to test boundary conditions in the XYRange method these values will contain the projection x/y coverage for the ground range specified by min/max lat/lon.
Referenced by Isis::Projection::Projection(), Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::Planar::XYRange(), Isis::PolarStereographic::XYRange(), Isis::RingCylindrical::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), Isis::TransverseMercator::XYRange(), Isis::TProjection::XYRangeCheck(), Isis::RingPlaneProjection::XYRangeCheck(), and Isis::TProjection::xyRangeOblique().
m_minimumY
double Isis::Projection::m_minimumY protected inherited
See minimumX description.
Referenced by Isis::Projection::Projection(), Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::Planar::XYRange(), Isis::PolarStereographic::XYRange(), Isis::RingCylindrical::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), Isis::TransverseMercator::XYRange(), Isis::TProjection::XYRangeCheck(), Isis::RingPlaneProjection::XYRangeCheck(), and Isis::TProjection::xyRangeOblique().
m_polarRadius
double Isis::TProjection::m_polarRadius protected inherited
Polar radius of the target.
This is a unitless value so that if the radii are in inches then the m_x and m_y will be in inches. Of course the units must be the same as the equatorial radius. This value is set on construction. It is either read directly from the mapping group of the given PVL label or it is found in NAIF kernels by using the Target value in the given label.When pulled from NAIF kernels, the equatorial radius is the third value of NAIF's radii array.
Referenced by Isis::TProjection::LocalRadius(), Isis::TProjection::PolarRadius(), Isis::TProjection::Scale(), Isis::TProjection::ToPlanetocentric(), Isis::TProjection::ToPlanetographic(), and Isis::TProjection::TProjection().
m_sky
bool Isis::Projection::m_sky protected inherited
Indicates whether projection is sky or land.
Referenced by Isis::Projection::IsSky(), and Isis::Projection::Projection().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ObliqueCylindrical/ObliqueCylindrical.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ObliqueCylindrical/ObliqueCylindrical.cpp