Isis Developer Reference: Isis::RubberBandComboBox Class Reference
Isis::RubberBandComboBox Class Reference
Combo box for choosing a rubber band type.
#include <RubberBandComboBox.h>
Public Types
enum RubberBandOptions {
Circle = 1 , Ellipse = 2 , Rectangle = 4 , RotatedRectangle = 8 ,
Polygon = 16 , Line = 32 , SegmentedLine = 64 , Angle = 128
}
Enum to store rubber band shapes.
Public Member Functions
RubberBandComboBox (Tool *tool, unsigned int bandingOptions, unsigned int defaultOption, bool showIndicatorColors=false)
RubberBandComboBox constructor.
QString toolIconDir () const
Returns the icon directory.
void reset ()
Resets the selection.
Protected Slots
void selectionChanged (int index)
This slot is called whenever the rubberband shape selection has changed.
Detailed Description
Combo box for choosing a rubber band type.
Author
2007-09-11 Steven Lambright
Member Enumeration Documentation
RubberBandOptions
enum Isis::RubberBandComboBox::RubberBandOptions
Enum to store rubber band shapes.
Enumerator
Circle
Circle.
Ellipse
Ellipse.
Rectangle
Rectangle.
RotatedRectangle
RotatedRectangle.
Polygon
Polygon.
Line
Line.
SegmentedLine
Segmented Line.
Angle
Angle.
Constructor & Destructor Documentation
RubberBandComboBox()
Isis::RubberBandComboBox::RubberBandComboBox (Tool * tool, unsigned int bandingOptions, unsigned int defaultOption, bool showIndicatorColors = false)
RubberBandComboBox constructor.
Parameters
bandingOptions
defaultOption
showIndicatorColors
References Circle, Line, Polygon, Rectangle, RotatedRectangle, Isis::Tool::rubberBandTool(), SegmentedLine, selectionChanged(), and toolIconDir().
Member Function Documentation
reset()
void Isis::RubberBandComboBox::reset ()
Resets the selection.
References selectionChanged().
Referenced by Isis::MeasureTool::enableRubberBandTool().
selectionChanged
void Isis::RubberBandComboBox::selectionChanged (int index) protected slot
This slot is called whenever the rubberband shape selection has changed.
Parameters
index
References Angle, Circle, Isis::RubberBandTool::disable(), Ellipse, Line, Polygon, Rectangle, RotatedRectangle, Isis::Tool::rubberBandTool(), SegmentedLine, and Isis::toInt().
Referenced by reset(), and RubberBandComboBox().
toolIconDir()
QString Isis::RubberBandComboBox::toolIconDir () const inline
Returns the icon directory.
References Isis::Tool::toolIconDir().
Referenced by RubberBandComboBox().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/RubberBandComboBox/RubberBandComboBox.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/RubberBandComboBox/RubberBandComboBox.cpp