Isis Developer Reference: Isis::SmtkPoint Class Reference
Isis::SmtkPoint Class Reference
Container for SMTK match points.
#include <SmtkPoint.h>
Public Member Functions
SmtkPoint ()
SmtkPoint (const PointPair &point, const PointPair &geom=PointPair())
SmtkPoint (const MatchPoint &mpt, const PointGeometry &regpnt, const PointPair &geom)
~SmtkPoint ()
bool isValid () const
Indicates the smtk portion of the point is valid.
double GoodnessOfFit () const
Returns goodness of the fit registration.
const PointPair & getPoints () const
Get initial left and right point pair.
const PointPair & getGeometry () const
Return left and right point geometry.
const Coordinate & getLeft () const
Returns the left point.
const Coordinate & getRight () const
Returns the registered right coordinate.
const AffineRadio & getAffine () const
Returns the affine transform and radiometic results.
bool isRegistered () const
Returns registration status.
Public Attributes
MatchPoint m_matchpt
PointGeometry m_regpnt
PointPair m_geom
bool m_registered
bool m_isValid
Detailed Description
Container for SMTK match points.
This container maintains the state of a SMTK point candidate. It will hold all the neccessary information to complete stereo processing and generation of other SMTK points.
Author
2011-05-24 Kris Becker
Constructor & Destructor Documentation
SmtkPoint() [1/3]
Isis::SmtkPoint::SmtkPoint () inline
SmtkPoint() [2/3]
Isis::SmtkPoint::SmtkPoint (const PointPair & point, const PointPair & geom = PointPair()) inline
SmtkPoint() [3/3]
Isis::SmtkPoint::SmtkPoint (const MatchPoint & mpt, const PointGeometry & regpnt, const PointPair & geom) inline
~SmtkPoint()
Isis::SmtkPoint::~SmtkPoint () inline
Member Function Documentation
getAffine()
const AffineRadio& Isis::SmtkPoint::getAffine () const inline
Returns the affine transform and radiometic results.
References Isis::MatchPoint::m_affine, and m_matchpt.
Referenced by Isis::SmtkMatcher::Clone().
getGeometry()
const PointPair& Isis::SmtkPoint::getGeometry () const inline
Return left and right point geometry.
References m_geom.
getLeft()
const Coordinate& Isis::SmtkPoint::getLeft () const inline
Returns the left point.
References getPoints().
Referenced by Isis::SmtkMatcher::Clone(), Isis::SmtkMatcher::isValid(), and Isis::SmtkMatcher::Register().
getPoints()
const PointPair& Isis::SmtkPoint::getPoints () const inline
Get initial left and right point pair.
This method returns the points used in the registration of the point. The right point contains the origin of registration and NOT the registered point.
See also
getRight()
Author
Kris Becker - 6/4/2011
Returns
const PointPair& Returns left/right point pair
References m_matchpt, and Isis::MatchPoint::m_point.
Referenced by getLeft().
getRight()
const Coordinate& Isis::SmtkPoint::getRight () const inline
Returns the registered right coordinate.
Use this method to get the registered right point coordinate. It should be the one used to compute the stereo match.
Author
Kris Becker - 6/4/2011
Returns
const Coordinate& Coordinate of the right registered point
References Isis::PointGeometry::getPoint(), and m_regpnt.
Referenced by Isis::SmtkMatcher::Clone(), Isis::SmtkMatcher::isValid(), and Isis::SmtkMatcher::Register().
GoodnessOfFit()
double Isis::SmtkPoint::GoodnessOfFit () const inline
Returns goodness of the fit registration.
References Isis::MatchPoint::getEigen(), and m_matchpt.
isRegistered()
bool Isis::SmtkPoint::isRegistered () const inline
Returns registration status.
If this method returns true, then the point set has been registered by the Gruen algorithm. If false, it is not registered. This could be because the point was unsuccessfully registered (see isValid()) or it was cloned from a registered point.
Author
Kris Becker - 5/26/2011
Returns
bool True if point has been registered, otherwise false.
References m_registered.
Referenced by Isis::SmtkMatcher::Register().
isValid()
bool Isis::SmtkPoint::isValid () const inline
Indicates the smtk portion of the point is valid.
References m_isValid.
Referenced by Isis::SmtkMatcher::isValid().
Member Data Documentation
m_geom
PointPair Isis::SmtkPoint::m_geom
Referenced by getGeometry().
m_isValid
bool Isis::SmtkPoint::m_isValid
Referenced by Isis::SmtkMatcher::Clone(), Isis::SmtkMatcher::Create(), and isValid().
m_matchpt
MatchPoint Isis::SmtkPoint::m_matchpt
Referenced by Isis::SmtkMatcher::Clone(), Isis::SmtkMatcher::Create(), getAffine(), getPoints(), and GoodnessOfFit().
m_registered
bool Isis::SmtkPoint::m_registered
Referenced by Isis::SmtkMatcher::Clone(), and isRegistered().
m_regpnt
PointGeometry Isis::SmtkPoint::m_regpnt
Referenced by getRight().
The documentation for this class was generated from the following file:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/SmtkMatcher/SmtkPoint.h