Isis Developer Reference: Isis::TiffImporter Class Reference
Isis::TiffImporter Class Reference
High Level Cube I/O
Imports TIFF images as Isis cubes.
#include <TiffImporter.h>
Public Member Functions
TiffImporter (FileName inputName)
Construct the importer.
virtual ~TiffImporter ()
Destruct the importer.
virtual PvlGroup convertProjection () const
Convert any projection information associated with the input image to an ISIS Mapping group in PVL form.
virtual bool isGrayscale () const
Tests to see if the input image has a "min is white" or "min is black" photometric interpretation, implying grayscale (no RGB/A).
virtual bool isRgb () const
Tests to see if the input image is neither grayscale nor has more than three samples per pixel, implying RGB (no alpha).
virtual bool isArgb () const
Tests to see if the input image is not grayscale and has more than three samples per pixel, implying RGBA.
void operator() (Buffer &out) const
The method for processing the output cube in place, called for each line of the output image.
Cube * import (FileName outputName)
Import the image with default output attributes.
Cube * import (FileName outputName, CubeAttributeOutput &att)
Import the input image this instance was constructed with into the given output Isis cube with the given output attributes.
void setNullRange (double min, double max)
Set the range of DN values within which a pixel from the input image will be set to Null in the output.
void setLrsRange (double min, double max)
Set the range of DN values within which a pixel from the input image will be set to LRS in the output.
void setHrsRange (double min, double max)
Set the range of DN values within which a pixel from the input image will be set to HRS in the output.
void setSamples (int s)
Set the sample dimension (width) of the output image.
void setLines (int l)
Set the line dimension (height) of the output image.
void setBands (int b)
Set the band dimension (depth) of the output image.
int samples () const
The sample dimension (width) of the output image.
int lines () const
The line dimension (height) of the output image.
int bands () const
The band dimension (depth) of the output image.
FileName filename () const
The filename of the input image this instance was constructed with.
Static Public Member Functions
static ImageImporter * fromFileName (FileName inputName)
A static (factory) method for constructing an ImageImporter instance from an input filename.
Protected Types
typedef int(ImageImporter::* GetChannelMethod) (int pixel) const
Friendly alias for a method used to get a particular color channel.
Protected Member Functions
int samplesPerPixel () const
The number of "samples" (bands in Isis terms) per pixel in the input image.
virtual void updateRawBuffer (int line, int band) const
Does nothing as LibTIFF reads the entire input image into memory, and therefore does not need to be updated throughout the import process.
virtual int getPixel (int s, int l) const
Returns a representation of a pixel for the input format that can then be broken down into specific gray or RGB/A components.
virtual int getGray (int pixel) const
Retrieves the gray component of the given pixel.
virtual int getRed (int pixel) const
Retrieves the red component of the given pixel.
virtual int getGreen (int pixel) const
Retrieves the green component of the given pixel.
virtual int getBlue (int pixel) const
Retrieves the blue component of the given pixel.
virtual int getAlpha (int pixel) const
Retrieves the alpha component of the given pixel.
Cube * createOutput (FileName outputName, CubeAttributeOutput &att)
Create the output cube from the given filename and attributes.
void setDefaultBands ()
Set the number of bands to be created for the output cube based on the number of color channels in the input image.
double testSpecial (double pixel) const
Tests a pixel against the Null, HRS, and LRS ranges defined by the importer's handler.
virtual GetChannelMethod getBandChannel (int band) const
Retrieve the method responsible for fetching the color channel from the input image corresponding to the current band out of output being filled.
virtual int convertRgbToGray (int pixel) const
Convert the current pixel, taken from an RGB/A image, and blend its RGB components into a single grayscale DN.
Detailed Description
Imports TIFF images as Isis cubes.
Takes a TIFF input image and imports it into Isis in the cube format. Unlike Qt's facilities for importing TIFFs, this class is capable of importing images >2GB, provided the user's machine has sufficient RAM to hold such an image in memory.
Author
2012-03-16 Travis Addair
Member Typedef Documentation
GetChannelMethod
typedef int(ImageImporter::* Isis::ImageImporter::GetChannelMethod) (int pixel) const protected inherited
Friendly alias for a method used to get a particular color channel.
Constructor & Destructor Documentation
TiffImporter()
Isis::TiffImporter::TiffImporter (FileName inputName)
Construct the importer.
Parameters
inputName The name of the input image
References _FILEINFO_, Isis::FileName::expanded(), Isis::ImageImporter::lines(), Isis::IException::Programmer, Isis::ImageImporter::samples(), Isis::ImageImporter::setDefaultBands(), Isis::ImageImporter::setLines(), and Isis::ImageImporter::setSamples().
~TiffImporter()
Isis::TiffImporter::~TiffImporter () virtual
Destruct the importer.
Member Function Documentation
bands()
int Isis::ImageImporter::bands () const inherited
The band dimension (depth) of the output image.
Returns
The band dimension
Referenced by Isis::ImageImporter::createOutput(), Isis::ImageImporter::getBandChannel(), Isis::ImageImporter::import(), and Isis::JP2Importer::JP2Importer().
convertProjection()
PvlGroup Isis::TiffImporter::convertProjection () const virtual
Convert any projection information associated with the input image to an ISIS Mapping group in PVL form.
Currently this routine only handles GeoTiff tags containing UTM projection parameters. NOTE: As written, this only works for a few projections. The tranlsation files can be extened to work for more, but the whole design needs to be generalized and thought out.
References: http://www.remotesensing.org/geotiff/spec/geotiffhome.html
Returns
The ISIS PVL mapping group
Reimplemented from Isis::ImageImporter.
References Isis::PvlObject::addGroup(), Isis::PvlToPvlTranslationManager::Auto(), Isis::ProjectionFactory::Create(), Isis::FileName::expanded(), Isis::FileName::fileExists(), Isis::PvlObject::findGroup(), Isis::TProjection::LocalRadius(), Isis::PI, Isis::toString(), and Isis::TProjection::TrueScaleLatitude().
convertRgbToGray()
int Isis::ImageImporter::convertRgbToGray (int pixel) const protected virtual inherited
Convert the current pixel, taken from an RGB/A image, and blend its RGB components into a single grayscale DN.
The three color components are weighted by the following formula:
gray = (red * 11 + green * 16 + blue * 5) / 32
This formula was taken from the Qt documentation on converting an RGB value to grayscale: http://qt-project.org/doc/qt-4.8/qcolor.html#qGray-2
Parameters
pixel The pixel value to be broken up into RGB components and converted to grayscale
Returns
The grayscale DN value
References Isis::ImageImporter::getBlue(), Isis::ImageImporter::getGreen(), and Isis::ImageImporter::getRed().
Referenced by Isis::JP2Importer::getGray(), and getGray().
createOutput()
Cube * Isis::ImageImporter::createOutput (FileName outputName, CubeAttributeOutput & att) protected inherited
Create the output cube from the given filename and attributes.
Set its dimensions based on those encapsulated by the importer.
Parameters
outputName The filename of the output cube
att The attributes for writing the output cube
Returns
The newly created cube handle devoid of any data
References Isis::ImageImporter::bands(), Isis::Cube::create(), Isis::FileName::expanded(), Isis::ImageImporter::lines(), Isis::ImageImporter::samples(), and Isis::Cube::setDimensions().
Referenced by Isis::ImageImporter::import().
filename()
FileName Isis::ImageImporter::filename () const inherited
The filename of the input image this instance was constructed with.
Returns
A copy of the input filename
Referenced by Isis::JP2Importer::JP2Importer().
fromFileName()
ImageImporter * Isis::ImageImporter::fromFileName (FileName inputName) static inherited
A static (factory) method for constructing an ImageImporter instance from an input filename.
The specific subclass of the returned instance is determined from the interpreted image format of the input image. Such tests are done by reading a minimal amount of the input data necessary to determine the format. It is the caller's responsibility to delete the importer instance when they are finished with it. Note that deleting the importer will also delete the cube handle returned by the import() method.
Parameters
inputName The filename of the input image to be imported
Returns
A pointer to the instantiated importer owned by the caller
References _FILEINFO_, Isis::FileName::expanded(), Isis::JP2Decoder::IsJP2(), and Isis::IException::Programmer.
getAlpha()
int Isis::TiffImporter::getAlpha (int pixel) const protected virtual
Retrieves the alpha component of the given pixel.
Parameters
pixel Representation of a LibTIFF pixel value
Returns
The alpha component
Implements Isis::ImageImporter.
getBandChannel()
ImageImporter::GetChannelMethod Isis::ImageImporter::getBandChannel (int band) const protected virtual inherited
Retrieve the method responsible for fetching the color channel from the input image corresponding to the current band out of output being filled.
This will always be the getGray() method for single band output images. For RGB/A images, band 1 will be red, band 2 green, band 3 blue, and band 4 alpha.
Parameters
band The current band of the output image
Returns
The method that converts input pixels into the current band's color component
References _FILEINFO_, Isis::ImageImporter::bands(), Isis::ImageImporter::getAlpha(), Isis::ImageImporter::getBlue(), Isis::ImageImporter::getGray(), Isis::ImageImporter::getGreen(), Isis::ImageImporter::getRed(), and Isis::IException::Programmer.
Referenced by Isis::ImageImporter::operator()().
getBlue()
int Isis::TiffImporter::getBlue (int pixel) const protected virtual
Retrieves the blue component of the given pixel.
Parameters
pixel Representation of a LibTIFF pixel value
Returns
The blue component
Implements Isis::ImageImporter.
getGray()
int Isis::TiffImporter::getGray (int pixel) const protected virtual
Retrieves the gray component of the given pixel.
In LibTIFF, even grayscale images are given RGB channels, so converts the RGB components into grayscale regardless of input photometric interpretation.
Parameters
pixel Representation of a LibTIFF pixel value
Returns
The gray component
Implements Isis::ImageImporter.
References Isis::ImageImporter::convertRgbToGray().
getGreen()
int Isis::TiffImporter::getGreen (int pixel) const protected virtual
Retrieves the green component of the given pixel.
Parameters
pixel Representation of a LibTIFF pixel value
Returns
The green component
Implements Isis::ImageImporter.
getPixel()
int Isis::TiffImporter::getPixel (int s, int l) const protected virtual
Returns a representation of a pixel for the input format that can then be broken down into specific gray or RGB/A components.
Parameters
s The sample of the desired pixel
l The line of the desired pixel
Returns
The pixel at the given sample and line of the input with all channel info
Implements Isis::ImageImporter.
References Isis::ImageImporter::lines(), and Isis::ImageImporter::samples().
getRed()
int Isis::TiffImporter::getRed (int pixel) const protected virtual
Retrieves the red component of the given pixel.
Parameters
pixel Representation of a LibTIFF pixel value
Returns
The red component
Implements Isis::ImageImporter.
import() [1/2]
Cube * Isis::ImageImporter::import (FileName outputName) inherited
Import the image with default output attributes.
Parameters
outputName The filename of the output cube
import() [2/2]
Cube * Isis::ImageImporter::import (FileName outputName, CubeAttributeOutput & att) inherited
Import the input image this instance was constructed with into the given output Isis cube with the given output attributes.
This will do a black-box import using a ProcessByLine routine. The BandBin group will be updated in the output cube with the names of the color channels included. The output cube will be returned on completion of the import process so the caller can continue to modify the labels. The importer instance will retain ownership of this cube, such that the cube handle will be deallocated upon destruction of the importer.
Parameters
outputName The filename of the output cube
att The attributes for writing the output cube
Returns
A handle on the newly imported Isis cube owned by the importer
References _FILEINFO_, Isis::PvlObject::addGroup(), Isis::ImageImporter::bands(), Isis::ProcessByBrick::BandsFirst, Isis::ImageImporter::convertProjection(), Isis::ImageImporter::createOutput(), Isis::ProcessByBrick::EndProcess(), Isis::PvlObject::findObject(), Isis::PvlContainer::keywords(), Isis::Cube::label(), Isis::ProcessByLine::ProcessCubeInPlace(), Isis::IException::Programmer, Isis::ProcessByLine::SetInputCube(), Isis::ProcessByBrick::SetProcessingDirection(), and Isis::Process::WriteHistory().
isArgb()
bool Isis::TiffImporter::isArgb () const virtual
Tests to see if the input image is not grayscale and has more than three samples per pixel, implying RGBA.
Returns
True if the image is RGBA, false otherwise
Implements Isis::ImageImporter.
References isGrayscale(), and samplesPerPixel().
isGrayscale()
bool Isis::TiffImporter::isGrayscale () const virtual
Tests to see if the input image has a "min is white" or "min is black" photometric interpretation, implying grayscale (no RGB/A).
Returns
True if the image is grayscale, false otherwise
Implements Isis::ImageImporter.
Referenced by isArgb(), and isRgb().
isRgb()
bool Isis::TiffImporter::isRgb () const virtual
Tests to see if the input image is neither grayscale nor has more than three samples per pixel, implying RGB (no alpha).
Returns
True if the image is RGB, false otherwise
Implements Isis::ImageImporter.
References isGrayscale(), and samplesPerPixel().
lines()
int Isis::ImageImporter::lines () const inherited
The line dimension (height) of the output image.
Returns
The line dimension
Referenced by Isis::ImageImporter::createOutput(), getPixel(), and TiffImporter().
operator()()
void Isis::ImageImporter::operator() (Buffer & out) const inherited
The method for processing the output cube in place, called for each line of the output image.
Enables the importer to be used as a functor in a custom ProcessByLine routine, bypassing the black-box import() method entirely. Care should be taken, however, to observe the requirements placed on the structure of such a processing routine by this method. For example, the JP2Importer child requires that the processing proceed in the direction of bands before lines, because its input data is structured in a BIL (band interlaced by line) format.
Parameters
out A reference to a line of output data to be written to
References Isis::Buffer::Band(), Isis::ImageImporter::getBandChannel(), Isis::ImageImporter::getPixel(), Isis::Buffer::Line(), Isis::Buffer::SampleDimension(), Isis::ImageImporter::testSpecial(), and Isis::ImageImporter::updateRawBuffer().
samples()
int Isis::ImageImporter::samples () const inherited
The sample dimension (width) of the output image.
Returns
The sample dimension
Referenced by Isis::ImageImporter::createOutput(), getPixel(), Isis::JP2Importer::JP2Importer(), and TiffImporter().
samplesPerPixel()
int Isis::TiffImporter::samplesPerPixel () const protected
The number of "samples" (bands in Isis terms) per pixel in the input image.
Combined with the photometric interpretation, this can be used to determine the color mode of the input image. We need both pieces of information because grayscale images are not guaranteed to have only one sample per pixel.
Returns
The samples per pixel
Referenced by isArgb(), and isRgb().
setBands()
void Isis::ImageImporter::setBands (int b) inherited
Set the band dimension (depth) of the output image.
Because this importer only works on Grayscale, RGB, and RGBA images, possible values are 1, 3, and 4 for the respective color modes.
Parameters
b The new band dimension
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by Isis::JP2Importer::JP2Importer(), and Isis::ImageImporter::setDefaultBands().
setDefaultBands()
void Isis::ImageImporter::setDefaultBands () protected inherited
Set the number of bands to be created for the output cube based on the number of color channels in the input image.
References Isis::ImageImporter::isArgb(), Isis::ImageImporter::isGrayscale(), and Isis::ImageImporter::setBands().
Referenced by Isis::QtImporter::QtImporter(), and TiffImporter().
setHrsRange()
void Isis::ImageImporter::setHrsRange (double min, double max) inherited
Set the range of DN values within which a pixel from the input image will be set to HRS in the output.
Parameters
min Any DN less than this value will not be set to HRS.
max Any DN greater than this value will not be set to HRS.
setLines()
void Isis::ImageImporter::setLines (int l) inherited
Set the line dimension (height) of the output image.
Parameters
l The new line dimension
Referenced by Isis::JP2Importer::JP2Importer(), Isis::QtImporter::QtImporter(), and TiffImporter().
setLrsRange()
void Isis::ImageImporter::setLrsRange (double min, double max) inherited
Set the range of DN values within which a pixel from the input image will be set to LRS in the output.
Parameters
min Any DN less than this value will not be set to LRS.
max Any DN greater than this value will not be set to LRS.
setNullRange()
void Isis::ImageImporter::setNullRange (double min, double max) inherited
Set the range of DN values within which a pixel from the input image will be set to Null in the output.
Parameters
min Any DN less than this value will not be set to Null.
max Any DN greater than this value will not be set to Null.
setSamples()
void Isis::ImageImporter::setSamples (int s) inherited
Set the sample dimension (width) of the output image.
Parameters
s The new sample dimension
Referenced by Isis::JP2Importer::JP2Importer(), Isis::QtImporter::QtImporter(), and TiffImporter().
testSpecial()
double Isis::ImageImporter::testSpecial (double pixel) const protected inherited
Tests a pixel against the Null, HRS, and LRS ranges defined by the importer's handler.
Any pixel value falling within one of these ranges will be converted into the given type of special pixel. In case of overlapping ranges, these tests will be performed in the order mentioned at the start of this description. By default, these ranges are set such that all incoming pixels will retain their original values.
Parameters
pixel The DN value to be tested
Returns
The valid DN or special pixel if it fell within the special ranges
References Isis::HIGH_REPR_SAT8, Isis::LOW_REPR_SAT8, and Isis::NULL8.
Referenced by Isis::ImageImporter::operator()().
updateRawBuffer()
void Isis::TiffImporter::updateRawBuffer (int line, int band) const protected virtual
Does nothing as LibTIFF reads the entire input image into memory, and therefore does not need to be updated throughout the import process.
Parameters
line Current line of the output buffer
band Current band of the output buffer
Implements Isis::ImageImporter.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/TiffImporter/TiffImporter.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/TiffImporter/TiffImporter.cpp