Isis Developer Reference: Isis::TreeViewContent Class Reference
Isis::TreeViewContent Class Reference
#include <TreeViewContent.h>
Public Slots
void refresh ()
Signals
void treeSelectionChanged ()
void treeSelectionChanged (QList< AbstractTreeItem * >)
Public Member Functions
TreeViewContent (QWidget *parent)
virtual ~TreeViewContent ()
QSize minimumSizeHint () const
QSize sizeHint () const
AbstractTreeModel * getModel ()
void setModel (AbstractTreeModel *someModel)
Protected Member Functions
bool eventFilter (QObject *target, QEvent *event)
void keyPressEvent (QKeyEvent *event)
void leaveEvent (QEvent *event)
void mouseDoubleClickEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void paintEvent (QPaintEvent *event)
void resizeEvent (QResizeEvent *event)
void scrollContentsBy (int dx, int dy)
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
TreeViewContent()
Isis::TreeViewContent::TreeViewContent (QWidget * parent)
~TreeViewContent()
Isis::TreeViewContent::~TreeViewContent () virtual
Member Function Documentation
eventFilter()
bool Isis::TreeViewContent::eventFilter (QObject * target, QEvent * event) protected
getModel()
AbstractTreeModel * Isis::TreeViewContent::getModel ()
Referenced by Isis::TreeView::getModel().
keyPressEvent()
void Isis::TreeViewContent::keyPressEvent (QKeyEvent * event) protected
References Isis::AbstractTreeModel::setGlobalSelection(), and treeSelectionChanged().
leaveEvent()
void Isis::TreeViewContent::leaveEvent (QEvent * event) protected
minimumSizeHint()
QSize Isis::TreeViewContent::minimumSizeHint () const
Referenced by sizeHint().
mouseDoubleClickEvent()
void Isis::TreeViewContent::mouseDoubleClickEvent (QMouseEvent * event) protected
References Isis::AbstractTreeItem::isExpanded(), refresh(), and Isis::AbstractTreeItem::setExpanded().
mouseMoveEvent()
void Isis::TreeViewContent::mouseMoveEvent (QMouseEvent * event) protected
References Isis::AbstractTreeItem::getFirstVisibleChild(), and Isis::AbstractTreeItem::isSelectable().
mousePressEvent()
void Isis::TreeViewContent::mousePressEvent (QMouseEvent * event) protected
References Isis::AbstractTreeItem::getChildren(), Isis::AbstractTreeItem::getFirstVisibleChild(), Isis::AbstractTreeModel::getItems(), Isis::AbstractTreeItem::getPointerType(), Isis::AbstractTreeItem::isSelectable(), Isis::AbstractTreeItem::isSelected(), Isis::AbstractTreeItem::Point, Isis::AbstractTreeModel::setGlobalSelection(), Isis::AbstractTreeItem::setSelected(), and treeSelectionChanged().
mouseReleaseEvent()
void Isis::TreeViewContent::mouseReleaseEvent (QMouseEvent * event) protected
References Isis::AbstractTreeItem::isExpanded(), refresh(), and Isis::AbstractTreeItem::setExpanded().
paintEvent()
void Isis::TreeViewContent::paintEvent (QPaintEvent * event) protected
refresh
void Isis::TreeViewContent::refresh () slot
References Isis::AbstractTreeModel::getVisibleSize(), and Isis::AbstractTreeModel::isFiltering().
Referenced by Isis::TreeView::handleModelSelectionChanged(), mouseDoubleClickEvent(), mouseReleaseEvent(), and setModel().
resizeEvent()
void Isis::TreeViewContent::resizeEvent (QResizeEvent * event) protected
scrollContentsBy()
void Isis::TreeViewContent::scrollContentsBy (int dx, int dy) protected
setModel()
void Isis::TreeViewContent::setModel (AbstractTreeModel * someModel)
References _FILEINFO_, Isis::IException::Programmer, refresh(), and treeSelectionChanged().
Referenced by Isis::TreeView::setModel().
sizeHint()
QSize Isis::TreeViewContent::sizeHint () const
References minimumSizeHint().
treeSelectionChanged [1/2]
void Isis::TreeViewContent::treeSelectionChanged () signal
Referenced by keyPressEvent(), mousePressEvent(), and setModel().
treeSelectionChanged [2/2]
void Isis::TreeViewContent::treeSelectionChanged (QList< AbstractTreeItem * >) signal
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/TreeViewContent.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/TreeViewContent.cpp