Isis Developer Reference: Isis::ExportPdsTable Class Reference
Isis::ExportPdsTable Class Reference
Utility
Export a PDS table from an ISIS Table.
#include <ExportPdsTable.h>
Public Member Functions
ExportPdsTable (Table isisTable)
Construct an ExportPdsTable object and set default member variable values.
~ExportPdsTable ()
Destructs for ExportPdsTable objects.
PvlObject exportTable (char *pdsTableBuffer, int pdsFileRecordBytes, QString pdsByteOrder)
This methods fills the given buffer with the binary PDS table data and returns label information.
QString formatPdsTableName ()
Format the PDS table object name using the ISIS table name.
Static Public Member Functions
static QString formatPdsTableName (QString isisTableName)
Static method that formats the given ISIS table name in PDS format.
Detailed Description
Export a PDS table from an ISIS Table.
This class ingests an ISIS Table and converts it to a PDS Table.
NOTE: This class exports BINARY format PDS tables. The PDS Standards Reference document indicates that for files containing multiple tables with binary data, the records should be FIXED_LENGTH (not STREAM) and that this value should be the length of the longest record in the file (Appendix A, PDS Standards, last updated February 27, 2009). This document also indicates that all table rows that are less than the fixed record length value should be padded (ususally with nulls).
See also
http://pds.nasa.gov/standards-reference.shtml
http://pds.nasa.gov/documents/sr/AppendixA.pdf
ExportPdsTable pdsTable(isisTable);
pdsTable.exportToPds(buffer, recordBytes, "LSB");
Author
2012-07-21 Jeannie Backer
Constructor & Destructor Documentation
ExportPdsTable()
Isis::ExportPdsTable::ExportPdsTable (Table isisTable)
Construct an ExportPdsTable object and set default member variable values.
This constructor sets the following defaults:
BYTEORDER = "LSB"
ROWS = Records
ROW_BYTES = RecordSize
Parameters
isisTable The ISIS Table object to be exported.
References Isis::Table::Records().
~ExportPdsTable()
Isis::ExportPdsTable::~ExportPdsTable ()
Destructs for ExportPdsTable objects.
Member Function Documentation
exportTable()
PvlObject Isis::ExportPdsTable::exportTable (char * pdsTableBuffer, int outputFileRecordBytes, QString pdsTableByteOrder)
This methods fills the given buffer with the binary PDS table data and returns label information.
Parameters
pdsTableBuffer This buffer will be filled with binary PDS table data.
pdsFileRecordBytes The number or RECORD_BYTES in the PDS file.
pdsByteOrder A string containing the byte order of the PDS file. Valid values are "LSB" or "MSB".
Returns
PvlObject A Pvl containing the PDS table's label information.
References _FILEINFO_, Isis::TableRecord::RecordSize(), and Isis::toString().
Referenced by Isis::ProcessExportPds::ExportTable().
formatPdsTableName() [1/2]
QString Isis::ExportPdsTable::formatPdsTableName ()
Format the PDS table object name using the ISIS table name.
Returns
QString containing the formatted PDS table name.
Referenced by Isis::ProcessExportPds::ExportTable().
formatPdsTableName() [2/2]
QString Isis::ExportPdsTable::formatPdsTableName (QString isisTableName) static
Static method that formats the given ISIS table name in PDS format.
This method takes the upper camel case Isis table name and returns a PDS table name that is underscore separated, all upper case and with "_TABLE" appended to the end of the name, if not already present.
Parameters
isisTableName An QString containing the ISIS upper camel case table name.
Returns
QString containing the formatted PDS table name.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ExportPdsTable/ExportPdsTable.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ExportPdsTable/ExportPdsTable.cpp