Isis Developer Reference: Isis::DataValue Class Reference
Isis::DataValue Class Reference
This class is used to define what kind of data is being pushed onto the cube calculator.
#include <CubeCalculator.h>
Public Types
enum DataValueType {
Constant , Sample , Line , Band ,
CubeData , InaData , EmaData , PhaData ,
LatData , LonData , ResData , RadiusData ,
InalData , EmalData , PhalData , InacData ,
EmacData , PhacData
}
This is used to tell what kind of data to push onto the RPN calculator.
Public Member Functions
DataValue ()
Constructs a default DataValue.
DataValue (DataValueType type)
Constructs a DataValue with a given type.
DataValue (DataValueType type, int cubeIndex)
Constructs a DataValue with a given type and associated cube index.
DataValue (DataValueType type, double value)
Constructs a DataValue with a given type and constant value.
DataValueType type ()
Accesses the type of the DataValue.
int cubeIndex ()
Accesses the cube index of the DataValue.
double constant ()
Accesses the constant value of the DataValue.
Detailed Description
This class is used to define what kind of data is being pushed onto the cube calculator.
Author
????-??-?? Unknown
Member Enumeration Documentation
DataValueType
enum Isis::DataValue::DataValueType
This is used to tell what kind of data to push onto the RPN calculator.
Enumerator
Constant
A single constant value.
Sample
Current sample number.
Line
Current line number.
Band
Current band number.
CubeData
A brick of cube data.
InaData
Incidence camera data.
EmaData
Emission camera data.
PhaData
Phase camera data.
LatData
Latitude camera data.
LonData
Longitude camera data.
ResData
Pixel resolution camera data.
RadiusData
DEM radius.
InalData
Local incidence camera data.
EmalData
Local emission camera data.
PhalData
Local phase camera data.
InacData
Center incidence camera data.
EmacData
Center emission camera data.
PhacData
Center phase camera data.
Constructor & Destructor Documentation
DataValue() [1/4]
Isis::DataValue::DataValue ()
Constructs a default DataValue.
This method constructs a default DataValue with its type, cube index, and constant value set to -1, -1, and 0.0, respectively.
DataValue() [2/4]
Isis::DataValue::DataValue (DataValueType type)
Constructs a DataValue with a given type.
This method constructs a DataValue with the passed type. The DataValue's constant value is set to 0.0 and its cube index is set to -1.
Parameters
type The DataValueType for the DataValue.
DataValue() [3/4]
Isis::DataValue::DataValue (DataValueType type, int cubeIndex)
Constructs a DataValue with a given type and associated cube index.
This method constructs a DataValue with the passed type and a cube index corresponding to the data's associated cube. The DataValue's constant value is set to 0.0.
Parameters
type The DataValueType for the DataValue.
cubeIndex Index of the associated cube the data corresponds with.
DataValue() [4/4]
Isis::DataValue::DataValue (DataValueType type, double value)
Constructs a DataValue with a given type and constant value.
This method constructs a DataValue with the passed type and passed constant value. The DataValue's cube index is set to -1. If the type passed is DataValue::Constant, then its constant value is set to the passed value.
Parameters
type The DataValueType for the DataValue.
value The constant value for the DataValue.
Member Function Documentation
constant()
double Isis::DataValue::constant ()
Accesses the constant value of the DataValue.
Returns
double Returns the DataValue's constant value.
Referenced by Isis::CubeCalculator::runCalculations().
cubeIndex()
int Isis::DataValue::cubeIndex ()
Accesses the cube index of the DataValue.
Returns
int Returns the DataValue's cube index.
Referenced by Isis::CubeCalculator::runCalculations().
type()
DataValue::DataValueType Isis::DataValue::type ()
Accesses the type of the DataValue.
Returns
DataValue::DataValueType Returns the DataValue's type.
Referenced by Isis::CubeCalculator::runCalculations().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/CubeCalculator/CubeCalculator.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/CubeCalculator/CubeCalculator.cpp