Isis Developer Reference: Isis::ImageTreeWidget Class Reference
Isis::ImageTreeWidget Class Reference
#include <ImageTreeWidget.h>
Classes
class ImagePosition
Public Types
enum TreeItemContainerType { ImageGroupType = 1 , ImageListNameType }
Signals
void queueSelectionChanged ()
void queueReadDisplayProperties ()
Public Member Functions
ImageTreeWidget (Directory *directory=0, QWidget *parent=0)
ImageTreeWidget constructor.
virtual ~ImageTreeWidget ()
QList< QAction * > actions ()
QTreeWidgetItem * addGroup (QString imageListName, QString groupName="", int index=-1)
QTreeWidgetItem * createGroup (QTreeWidgetItem *imageListItem, QString groupName="", int index=-1)
QTreeWidgetItem * createImageListNameItem (QString name)
void refit ()
void disableSort ()
void enqueueReadDisplayProperties (ImageTreeWidgetItem *)
QList< QAction * > getViewActions ()
bool groupInList (QList< QTreeWidgetItem * >)
void updateViewActs ()
ImageTreeWidgetItem * prepCube (ImageList *imageList, Image *image)
ImageList imagesInView ()
Protected Member Functions
void dropEvent (QDropEvent *event)
void mousePressEvent (QMouseEvent *event)
This is why we needed to subclass the QTreeWidget class.
void contextMenuEvent (QContextMenuEvent *event)
Detailed Description
Author
????-??-?? Unknown
Member Enumeration Documentation
TreeItemContainerType
enum Isis::ImageTreeWidget::TreeItemContainerType
Enumerator
ImageGroupType
ImageListNameType
Constructor & Destructor Documentation
ImageTreeWidget()
Isis::ImageTreeWidget::ImageTreeWidget (Directory * directory = 0, QWidget * parent = 0)
ImageTreeWidget constructor.
ImageTreeWidget is derived from QTreeWidget
Parameters
parent
References Isis::ImageTreeWidgetItem::AspectRatioColumn, Isis::ImageTreeWidgetItem::BlankColumn, Isis::ImageTreeWidgetItem::EmissionAngleColumn, Isis::ImageTreeWidgetItem::FootprintColumn, Isis::ImageTreeWidgetItem::ImageColumn, Isis::ImageTreeWidgetItem::IncidenceAngleColumn, Isis::ImageTreeWidgetItem::LabelColumn, Isis::ImageTreeWidgetItem::LineResolutionColumn, Isis::ImageTreeWidgetItem::NameColumn, Isis::ImageTreeWidgetItem::NorthAzimuthColumn, Isis::ImageTreeWidgetItem::PhaseAngleColumn, queueReadDisplayProperties(), queueSelectionChanged(), Isis::ImageTreeWidgetItem::ResolutionColumn, Isis::ImageTreeWidgetItem::SampleResolutionColumn, Isis::toBool(), and Isis::ImageTreeWidgetItem::treeColumnToString().
~ImageTreeWidget()
Isis::ImageTreeWidget::~ImageTreeWidget () virtual
References actions().
Member Function Documentation
actions()
QList< QAction * > Isis::ImageTreeWidget::actions ()
Referenced by Isis::ImageFileListWidget::actions(), and ~ImageTreeWidget().
addGroup()
QTreeWidgetItem * Isis::ImageTreeWidget::addGroup (QString imageListName, QString groupName = "", int index = -1)
References createGroup(), and disableSort().
Referenced by contextMenuEvent(), and Isis::ImageFileListWidget::fromPvl().
contextMenuEvent()
void Isis::ImageTreeWidget::contextMenuEvent (QContextMenuEvent * event) protected
References addGroup(), groupInList(), Isis::Directory::project(), Isis::Directory::supportedActions(), and Isis::ImageList::supportedActions().
createGroup()
QTreeWidgetItem * Isis::ImageTreeWidget::createGroup (QTreeWidgetItem * imageListItem, QString groupName = "", int index = -1)
References ImageGroupType.
Referenced by addGroup(), and Isis::ImageFileListWidget::addImages().
createImageListNameItem()
QTreeWidgetItem * Isis::ImageTreeWidget::createImageListNameItem (QString name)
References ImageListNameType.
Referenced by Isis::ImageFileListWidget::addImages().
disableSort()
void Isis::ImageTreeWidget::disableSort ()
References Isis::ImageTreeWidgetItem::BlankColumn.
Referenced by addGroup(), and dropEvent().
dropEvent()
void Isis::ImageTreeWidget::dropEvent (QDropEvent * event) protected
References disableSort(), and groupInList().
enqueueReadDisplayProperties()
void Isis::ImageTreeWidget::enqueueReadDisplayProperties (ImageTreeWidgetItem * item)
References queueReadDisplayProperties().
Referenced by Isis::ImageTreeWidgetItem::onDisplayPropertiesChanged().
getViewActions()
QList< QAction * > Isis::ImageTreeWidget::getViewActions ()
References Isis::ImageTreeWidgetItem::BlankColumn, Isis::ImageTreeWidgetItem::FootprintColumn, and updateViewActs().
Referenced by Isis::ImageFileListWidget::contextMenuEvent(), and Isis::ImageFileListWidget::getViewActions().
groupInList()
bool Isis::ImageTreeWidget::groupInList (QList< QTreeWidgetItem * > items)
Referenced by Isis::ImageFileListWidget::addImages(), contextMenuEvent(), and dropEvent().
imagesInView()
ImageList Isis::ImageTreeWidget::imagesInView ()
References Isis::ImageList::append(), and Isis::ImageTreeWidgetItem::image().
Referenced by Isis::ImageFileListWidget::addImages().
mousePressEvent()
void Isis::ImageTreeWidget::mousePressEvent (QMouseEvent * event) protected
This is why we needed to subclass the QTreeWidget class.
We needed our own dropEvent for the dragging and dropping of the tree widget items. This is re-implemented to make right clicks on white space also unselect the current selection.
prepCube()
ImageTreeWidgetItem * Isis::ImageTreeWidget::prepCube (ImageList * imageList, Image * image)
References Isis::Image::displayProperties(), and Isis::IException::print().
Referenced by Isis::ImageFileListWidget::addImages().
queueReadDisplayProperties
void Isis::ImageTreeWidget::queueReadDisplayProperties () signal
Referenced by enqueueReadDisplayProperties(), and ImageTreeWidget().
queueSelectionChanged
void Isis::ImageTreeWidget::queueSelectionChanged () signal
Referenced by ImageTreeWidget().
refit()
void Isis::ImageTreeWidget::refit ()
References Isis::ImageTreeWidgetItem::BlankColumn, and Isis::ImageTreeWidgetItem::NameColumn.
Referenced by Isis::ImageFileListWidget::addImages().
updateViewActs()
void Isis::ImageTreeWidget::updateViewActs ()
References Isis::ImageTreeWidgetItem::BlankColumn, Isis::ImageTreeWidgetItem::FootprintColumn, and Isis::ImageTreeWidgetItem::treeColumnToString().
Referenced by Isis::ImageFileListWidget::fromPvl(), and getViewActions().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ImageFileListWidget/ImageTreeWidget.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ImageFileListWidget/ImageTreeWidget.cpp