Isis Developer Reference: Isis::CubeBsqHandler Class Reference
Isis::CubeBsqHandler Class Reference
Low Level Cube I/O
IO Handler for Isis Cubes using the BSQ format.
#include <CubeBsqHandler.h>
Public Member Functions
CubeBsqHandler (QFile *dataFile, const QList< int > *virtualBandList, const Pvl &label, bool alreadyOnDisk)
Construct a BSQ IO handler.
~CubeBsqHandler ()
The destructor writes all cached data to disk.
void updateLabels (Pvl &labels)
Function to update the labels with a Pvl object.
void read (Buffer &bufferToFill) const
Read cube data from disk into the buffer.
void write (const Buffer &bufferToWrite)
Write buffer data into the cube data on disk.
void addCachingAlgorithm (CubeCachingAlgorithm *algorithm)
This will add the given caching algorithm to the list of attempted caching algorithms.
void clearCache (bool blockForWriteCache=true) const
Free all cube chunks (cached cube data) from memory and write them to disk.
BigInt getDataSize () const
void setVirtualBands (const QList< int > *virtualBandList)
This changes the virtual band list.
QMutex * dataFileMutex ()
Get the mutex that this IO handler is using around I/Os on the given data file.
Protected Member Functions
virtual void readRaw (RawCubeChunk &chunkToFill)
This needs to populate the chunkToFill with unswapped raw bytes from the disk.
virtual void writeRaw (const RawCubeChunk &chunkToWrite)
This needs to write the chunkToWrite directly to disk with no modifications to the data itself.
int bandCount () const
int getBandCountInChunk () const
BigInt getBytesPerChunk () const
int getChunkCountInBandDimension () const
int getChunkCountInLineDimension () const
int getChunkCountInSampleDimension () const
int getChunkIndex (const RawCubeChunk &) const
Given a chunk, what's its index in the file.
BigInt getDataStartByte () const
QFile * getDataFile ()
int lineCount () const
int getLineCountInChunk () const
PixelType pixelType () const
int sampleCount () const
int getSampleCountInChunk () const
void setChunkSizes (int numSamples, int numLines, int numBands)
This should be called once from the child constructor.
Detailed Description
IO Handler for Isis Cubes using the BSQ format.
This class is used to open, create, read, and write data from Isis cube files.
Author
2003-02-14 Jeff Anderson
Constructor & Destructor Documentation
CubeBsqHandler()
Isis::CubeBsqHandler::CubeBsqHandler (QFile * dataFile, const QList< int > * virtualBandList, const Pvl & labels, bool alreadyOnDisk)
Construct a BSQ IO handler.
This will determine a good chunk size to use that does not result in the cube being enlarged or misordered.
Parameters
dataFile The file with cube DN data in it
virtualBandList The mapping from virtual band to physical band, see CubeIoHandler's description.
labels The Pvl labels for the cube
alreadyOnDisk True if the cube is allocated on the disk, false otherwise
References Isis::CubeIoHandler::lineCount(), Isis::CubeIoHandler::pixelType(), Isis::CubeIoHandler::sampleCount(), Isis::CubeIoHandler::setChunkSizes(), and Isis::SizeOf().
~CubeBsqHandler()
Isis::CubeBsqHandler::~CubeBsqHandler ()
The destructor writes all cached data to disk.
References Isis::CubeIoHandler::clearCache().
Member Function Documentation
addCachingAlgorithm()
void Isis::CubeIoHandler::addCachingAlgorithm (CubeCachingAlgorithm * algorithm) inherited
This will add the given caching algorithm to the list of attempted caching algorithms.
The algorithms are tried in the opposite order that they were added - the first algorithm added is the last algorithm tried.
This method takes ownership of algorithm.
Parameters
algorithm The caching algorithm to add to the Cube for I/O
bandCount()
int Isis::CubeIoHandler::bandCount () const protected inherited
Returns
the number of physical bands in the cube.
clearCache()
void Isis::CubeIoHandler::clearCache (bool blockForWriteCache = true) const inherited
Free all cube chunks (cached cube data) from memory and write them to disk.
Child destructors need to call this method.
This method should only be called otherwise when lots of cubes are in memory and the many caches cause problems with system RAM limitations.
Parameters
blockForWriteCache This should be true unless this method is called from the write thread.
Referenced by ~CubeBsqHandler(), and Isis::CubeTileHandler::~CubeTileHandler().
dataFileMutex()
QMutex * Isis::CubeIoHandler::dataFileMutex () inherited
Get the mutex that this IO handler is using around I/Os on the given data file.
A lock should be acquired before doing any reads/writes on the data file externally.
Returns
A mutex that can guarantee exclusive access to the data file
getBandCountInChunk()
int Isis::CubeIoHandler::getBandCountInChunk () const protected inherited
Returns
the number of bands per chunk for this cube.
getBytesPerChunk()
BigInt Isis::CubeIoHandler::getBytesPerChunk () const protected inherited
Returns
the byte size of each chunk in the cube. Currently they must be constant size, but this is planned to be changed at some point in time.
Number of bytes in a cube chunk
References Isis::SizeOf().
getChunkCountInBandDimension()
int Isis::CubeIoHandler::getChunkCountInBandDimension () const protected inherited
Returns
the total number of chunks in the band (Z) dimension. This is always enough to contain every band in the cube.
getChunkCountInLineDimension()
int Isis::CubeIoHandler::getChunkCountInLineDimension () const protected inherited
Returns
the total number of chunks in the line (Y) dimension. This is always enough to contain every line in the cube.
getChunkCountInSampleDimension()
int Isis::CubeIoHandler::getChunkCountInSampleDimension () const protected inherited
Returns
the total number of chunks in the sample (X) dimension. This is always enough to contain every sample in the cube.
getChunkIndex()
int Isis::CubeIoHandler::getChunkIndex (const RawCubeChunk & chunk) const protected inherited
Given a chunk, what's its index in the file.
Chunks are ordered from left to right, then top to bottom, then front to back (BSQ). The first chunk is at the top left of band 1 and is index 0, for example. In other words, this is going from the value of m_rawData to the key.
Chunks which sit outside of the cube entirely must not be passed into this method; the results will be wrong.
Returns
The chunk's index into the file
References Isis::RawCubeChunk::getStartBand(), Isis::RawCubeChunk::getStartLine(), and Isis::RawCubeChunk::getStartSample().
getDataFile()
QFile * Isis::CubeIoHandler::getDataFile () protected inherited
Returns
the QFile containing cube data. This is what should be read from and written to.
The data file for I/O
Referenced by readRaw(), Isis::CubeTileHandler::readRaw(), writeRaw(), and Isis::CubeTileHandler::writeRaw().
getDataSize()
BigInt Isis::CubeIoHandler::getDataSize () const inherited
Returns
the number of bytes that the cube DNs will take up. This includes padding caused by the cube chunks not aligning with the cube dimensions.
getDataStartByte()
BigInt Isis::CubeIoHandler::getDataStartByte () const protected inherited
Returns
the byte offset to the beginning of the cube data.
getLineCountInChunk()
int Isis::CubeIoHandler::getLineCountInChunk () const protected inherited
Returns
the number of lines in each chunk of the cube.
Referenced by Isis::CubeTileHandler::updateLabels().
getSampleCountInChunk()
int Isis::CubeIoHandler::getSampleCountInChunk () const protected inherited
Returns
the number of samples in each chunk of the cube.
Referenced by Isis::CubeTileHandler::updateLabels().
lineCount()
int Isis::CubeIoHandler::lineCount () const protected inherited
Returns
the number of lines in the cube. This does not include lines created by the chunk overflowing the line dimension.
Referenced by CubeBsqHandler(), and Isis::CubeTileHandler::CubeTileHandler().
pixelType()
PixelType Isis::CubeIoHandler::pixelType () const protected inherited
Returns
the physical cube DN format.
Referenced by CubeBsqHandler(), and Isis::CubeTileHandler::CubeTileHandler().
read()
void Isis::CubeIoHandler::read (Buffer & bufferToFill) const inherited
Read cube data from disk into the buffer.
This is not const because it caches the read cube chunks from the disk.
Parameters
bufferToFill The buffer to populate with cube data.
References Isis::Buffer::Band(), Isis::Buffer::BandDimension(), Isis::Buffer::Line(), Isis::Buffer::LineDimension(), Isis::Null, Isis::Buffer::Sample(), Isis::Buffer::SampleDimension(), and Isis::Buffer::size().
readRaw()
void Isis::CubeBsqHandler::readRaw (RawCubeChunk & chunkToFill) protected virtual
This needs to populate the chunkToFill with unswapped raw bytes from the disk.
See also
CubeTileHandler::readRaw()
Parameters
chunkToFill The container that needs to be filled with cube data.
Implements Isis::CubeIoHandler.
References _FILEINFO_, Isis::RawCubeChunk::getByteCount(), Isis::CubeIoHandler::getDataFile(), Isis::IException::Io, and Isis::RawCubeChunk::setRawData().
sampleCount()
int Isis::CubeIoHandler::sampleCount () const protected inherited
Returns
the number of samples in the cube. This does not include samples created by the chunk overflowing the sample dimension.
Referenced by CubeBsqHandler(), and Isis::CubeTileHandler::CubeTileHandler().
setChunkSizes()
void Isis::CubeIoHandler::setChunkSizes (int numSamples, int numLines, int numBands) protected inherited
This should be called once from the child constructor.
This determines the chunk sizes used for the cube and often should remain constant for a particular cube (BSQ, for example, doesn't need it to be constant but Tile does). These being large can cause excessive use of disk space that stores no cube data. These being large can also drastically increase the amount of RAM consumed.
Parameters
numSamples The chunk size in the sample dimension
numLines The chunk size in the line dimension
numBands The chunk size in the band dimension
References _FILEINFO_.
Referenced by CubeBsqHandler(), and Isis::CubeTileHandler::CubeTileHandler().
setVirtualBands()
void Isis::CubeIoHandler::setVirtualBands (const QList< int > * virtualBandList) inherited
This changes the virtual band list.
Parameters
virtualBandList A list where the indices are the vbands and the values are the physical bands. The values are 1-based. This can be specified as NULL, in which case the vbands are the physical bands. The virtual band list is copied (the pointer provided isn't remembered).
updateLabels()
void Isis::CubeBsqHandler::updateLabels (Pvl & label) virtual
Function to update the labels with a Pvl object.
Parameters
label Pvl object to update with
Implements Isis::CubeIoHandler.
References Isis::PvlContainer::addKeyword(), Isis::PvlObject::findObject(), and Isis::PvlContainer::Replace.
write()
void Isis::CubeIoHandler::write (const Buffer & bufferToWrite) inherited
Write buffer data into the cube data on disk.
This could do no IO if the cube chunks required are already in memory and our caching algorithms say to not free any of the cube chunks afterwards.
Parameters
bufferToWrite The buffer to get cube data from.
writeRaw()
void Isis::CubeBsqHandler::writeRaw (const RawCubeChunk & chunkToWrite) protected virtual
This needs to write the chunkToWrite directly to disk with no modifications to the data itself.
See also
CubeTileHandler::writeRaw()
Parameters
chunkToWrite The container that needs to be put on disk.
Implements Isis::CubeIoHandler.
References _FILEINFO_, Isis::RawCubeChunk::getByteCount(), Isis::CubeIoHandler::getDataFile(), Isis::RawCubeChunk::getRawData(), and Isis::IException::Io.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Cube/CubeBsqHandler.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Cube/CubeBsqHandler.cpp