Isis Developer Reference: Isis::Blob Class Reference
Isis::Blob Class Reference
#include <Blob.h>
Public Member Functions
Blob (const QString &name, const QString &type)
Constructs a Blob object using a name and type.
Blob (const QString &name, const QString &type, const QString &file)
Constructs a Blob object using a name, type, and reading Pvl values from a file.
Blob (const Blob &other)
This copies the blob object.
Blob ()=default
Blob & operator= (const Blob &other)
This makes the two blob objects exactly the same (copies the blob)
virtual ~Blob ()
Destroys the Blob object.
QString Type () const
Accessor method that returns a string containing the Blob type.
QString Name () const
Accessor method that returns a string containing the Blob name.
int Size () const
Accessor method that returns the number of bytes in the blob data.
PvlObject & Label ()
Accessor method that returns a PvlObject containing the Blob label.
void Read (const QString &file, const std::vector< PvlKeyword > keywords=std::vector< PvlKeyword >())
This method reads Pvl values from a specified file.
void Read (const QString &file, const Pvl &pvlLabels, const std::vector< PvlKeyword > keywords=std::vector< PvlKeyword >())
This method reads the given a file and labels.
virtual void Read (const Pvl &pvl, std::istream &is, const std::vector< PvlKeyword > keywords=std::vector< PvlKeyword >())
This method reads the Blob data from an open input file stream.
void Write (const QString &file)
Write the blob data out to a file.
void Write (Pvl &pvl, std::fstream &stm, const QString &detachedFileName="", bool overwrite=true)
Write the blob data out to a Pvl object.
char * getBuffer ()
Get the internal data buff of the Blob.
void setData (const char *buffer, int nbytes)
Set the data stored in the BLOB.
void takeData (char *buffer, int nbytes)
Set the data stored in the BLOB without copying it.
Protected Member Functions
void Find (const Pvl &pvl, const std::vector< PvlKeyword > keywords=std::vector< PvlKeyword >())
This method searches the given Pvl for the Blob by the Blob's type and name.
virtual void ReadInit ()
This virtual method for classes that inherit Blob.
virtual void ReadData (std::istream &is)
Read binary data from an input stream into the Blob object.
virtual void WriteInit ()
This virtual method for classes that inherit Blob.
virtual void WriteData (std::fstream &os)
Writes blob data to a stream.
Protected Attributes
PvlObject p_blobPvl
Pvl Blob object.
QString p_blobName
Name of the Blob object.
char * p_buffer
Buffer blob data is stored in.
BigInt p_startByte
Byte blob data starts at in buffer.
int p_nbytes
Size of blob data (in bytes)
QString p_type
Type of data stored in the buffer.
QString p_detached
Used for reading detached blobs.
QString p_labelFile
The file containing the labels.
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
Blob() [1/4]
Isis::Blob::Blob (const QString & name, const QString & type)
Constructs a Blob object using a name and type.
Parameters
name The blob name
type The blob type
Blob() [2/4]
Isis::Blob::Blob (const QString & name, const QString & type, const QString & file)
Constructs a Blob object using a name, type, and reading Pvl values from a file.
Parameters
name The blob name
type The blob type
file The filename to read from.
References Isis::FileName::expanded().
Blob() [3/4]
Isis::Blob::Blob (const Blob & other)
This copies the blob object.
Parameters
other Blob to be copied
References p_blobName, p_blobPvl, p_buffer, p_detached, p_labelFile, p_nbytes, p_startByte, and p_type.
Blob() [4/4]
Isis::Blob::Blob () default
~Blob()
Isis::Blob::~Blob () virtual
Destroys the Blob object.
Member Function Documentation
Find()
void Isis::Blob::Find (const Pvl & pvl, const std::vector< PvlKeyword > keywords = std::vector<PvlKeyword>()) protected
This method searches the given Pvl for the Blob by the Blob's type and name.
If found, the start byte, number of bytes are read from the Pvl. Also, if a keyword label pointer is found, the filename for the detached blob is stored and the pointer is removed from the blob pvl.
Parameters
pvl The Pvl to be searched
keywords A list of keyword, value pairs to match inside the blob's PVL object. Only if all the keyword match is the blob processed. This is used when there are multiple blobs with the same name, but different keywords that define the exact blob (see Stretch with a band number)
References _FILEINFO_, Isis::PvlObject::findKeyword(), Isis::PvlObject::hasKeyword(), Isis::PvlKeyword::isEquivalent(), Isis::PvlContainer::isNamed(), Isis::PvlObject::object(), Isis::PvlObject::objects(), and Isis::FileName::path().
getBuffer()
char * Isis::Blob::getBuffer ()
Get the internal data buff of the Blob.
Returns
char* A data buffer containing Blob::Size bytes
Referenced by Isis::CSMCamera::CSMCamera(), Isis::CubeStretch::CubeStretch(), Isis::OriginalXmlLabel::fromBlob(), Isis::History::History(), Isis::ImagePolygon::ImagePolygon(), and Isis::Table::initFromBlob().
Label()
PvlObject & Isis::Blob::Label ()
Accessor method that returns a PvlObject containing the Blob label.
Returns
PvlObject The label of the blob.
Referenced by Isis::CSMCamera::CSMCamera(), Isis::CubeStretch::CubeStretch(), Isis::Table::initFromBlob(), Isis::CubeStretch::toBlob(), Isis::OriginalXmlLabel::toBlob(), and Isis::Table::toBlob().
Name()
QString Isis::Blob::Name () const
Accessor method that returns a string containing the Blob name.
Returns
string The name of the blob.
Referenced by Isis::Image::isFootprintable(), Isis::Shape::isFootprintable(), and Isis::Cube::write().
operator=()
Blob & Isis::Blob::operator= (const Blob & other)
This makes the two blob objects exactly the same (copies the blob)
Parameters
other Blob to be copied
Returns
Copied Blob
References p_blobName, p_blobPvl, p_buffer, p_detached, p_labelFile, p_nbytes, p_startByte, and p_type.
Read() [1/3]
void Isis::Blob::Read (const Pvl & pvl, std::istream & istm, const std::vector< PvlKeyword > keywords = std::vector<PvlKeyword>()) virtual
This method reads the Blob data from an open input file stream.
Parameters
pvl A Pvl containing the label information.
istm The input file stream containing the blob data to be read.
Exceptions
iException::Io - Unable to open file
References _FILEINFO_, and Isis::Message::FileOpen().
Read() [2/3]
void Isis::Blob::Read (const QString & file, const Pvl & pvlLabels, const std::vector< PvlKeyword > keywords = std::vector<PvlKeyword>())
This method reads the given a file and labels.
Parameters
file The filename to read from.
pvlLabels A Pvl containing the label information.
Exceptions
iException::Io - Unable to open file
References _FILEINFO_, and Isis::Message::FileOpen().
Read() [3/3]
void Isis::Blob::Read (const QString & file, const std::vector< PvlKeyword > keywords = std::vector<PvlKeyword>())
This method reads Pvl values from a specified file.
Parameters
file The filename to read from.
Exceptions
iException::Io - Unable to open file
iException::Pvl - Invalid label format
References _FILEINFO_, and Isis::Pvl::read().
Referenced by Isis::OriginalLabel::OriginalLabel(), Isis::OriginalXmlLabel::OriginalXmlLabel(), Isis::Cube::read(), and Isis::Table::Table().
ReadData()
void Isis::Blob::ReadData (std::istream & stream) protected virtual
Read binary data from an input stream into the Blob object.
Parameters
stream The input stream to read from.
Exceptions
IException::Io - Error reading data from stream
References _FILEINFO_.
ReadInit()
void Isis::Blob::ReadInit () protected virtual
This virtual method for classes that inherit Blob.
It is not defined in the Blob class.
setData()
void Isis::Blob::setData (const char * buffer, int nbytes)
Set the data stored in the BLOB.
This function will copy the data buffer, if you want to avoid that use takeData which will take ownership of the buffer.
Parameters
buffer The buffer of data. The BLOB does not take ownership of this, the caller is still responsible for cleaning it up.
nbytes The amount of data in the buffer
Referenced by Isis::OriginalLabel::toBlob(), Isis::CubeStretch::toBlob(), Isis::ImagePolygon::toBlob(), and Isis::OriginalXmlLabel::toBlob().
Size()
int Isis::Blob::Size () const
Accessor method that returns the number of bytes in the blob data.
Returns
int Number of bytes in the blob data.
Referenced by Isis::CSMCamera::CSMCamera(), Isis::CubeStretch::CubeStretch(), Isis::OriginalXmlLabel::fromBlob(), Isis::History::History(), and Isis::ImagePolygon::ImagePolygon().
takeData()
void Isis::Blob::takeData (char * buffer, int nbytes)
Set the data stored in the BLOB without copying it.
This function takes ownership of the data buffer and will delete is when the BLOB is cleaned up.
Parameters
buffer The buffer of data. The BLOB takes ownership of this.
nbytes The amount of data in the buffer
Referenced by Isis::Table::toBlob(), and Isis::History::toBlob().
Type()
QString Isis::Blob::Type () const
Accessor method that returns a string containing the Blob type.
Returns
string Type of blob.
Referenced by Isis::Image::isFootprintable(), Isis::Shape::isFootprintable(), and Isis::Cube::write().
Write() [1/2]
void Isis::Blob::Write (const QString & file)
Write the blob data out to a file.
Parameters
file The filename to write to.
Exceptions
IException::Io - Unable to open file
IException::Io - Error preparing to write data to file
IException::Io - Error creating file
References _FILEINFO_, Isis::PvlObject::addObject(), Isis::PvlObject::findObject(), Isis::toString(), and Isis::Pvl::write().
Referenced by Isis::Cube::write(), and Isis::Table::Write().
Write() [2/2]
void Isis::Blob::Write (Pvl & pvl, std::fstream & stm, const QString & detachedFileName = "", bool overwrite = true)
Write the blob data out to a Pvl object.
Parameters
pvl The pvl object to update
stm stream to write data to
detachedFileName If the stream is detached from the labels give the name of the file
References Isis::PvlObject::addObject(), Isis::PvlContainer::name(), Isis::PvlObject::object(), Isis::PvlObject::objects(), and Isis::toString().
WriteData()
void Isis::Blob::WriteData (std::fstream & stream) protected virtual
Writes blob data to a stream.
Parameters
stream Output steam blob data will be written to
Exceptions
IException::Io - Error writing data to stream
References _FILEINFO_.
WriteInit()
void Isis::Blob::WriteInit () protected virtual
This virtual method for classes that inherit Blob.
It is not defined in the Blob class.
Member Data Documentation
p_blobName
QString Isis::Blob::p_blobName protected
Name of the Blob object.
Referenced by Blob(), and operator=().
p_blobPvl
PvlObject Isis::Blob::p_blobPvl protected
Pvl Blob object.
Referenced by Blob(), and operator=().
p_buffer
char* Isis::Blob::p_buffer protected
Buffer blob data is stored in.
Referenced by Blob(), and operator=().
p_detached
QString Isis::Blob::p_detached protected
Used for reading detached blobs.
Referenced by Blob(), and operator=().
p_labelFile
QString Isis::Blob::p_labelFile protected
The file containing the labels.
Referenced by Blob(), and operator=().
p_nbytes
int Isis::Blob::p_nbytes protected
Size of blob data (in bytes)
Referenced by Blob(), and operator=().
p_startByte
BigInt Isis::Blob::p_startByte protected
Byte blob data starts at in buffer.
Referenced by Blob(), and operator=().
p_type
QString Isis::Blob::p_type protected
Type of data stored in the buffer.
Referenced by Blob(), and operator=().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Blob/Blob.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Blob/Blob.cpp