Isis Developer Reference: Isis::Gruen Class Reference
Isis::Gruen Class Reference
Pattern Matching
Gruen pattern matching algorithm.
#include <Gruen.h>
Public Types
enum RegisterStatus {
SuccessPixel , SuccessSubPixel , PatternChipNotEnoughValidData , FitChipNoData ,
FitChipToleranceNotMet , SurfaceModelNotEnoughValidData , SurfaceModelSolutionInvalid , SurfaceModelDistanceInvalid ,
PatternZScoreNotMet , AdaptiveAlgorithmFailed
}
Enumeration of the Register() method's return status.
enum GradientFilterType { None , Sobel }
Enumeration of the different types of gradient filters that can be applied to the pattern and search chips before matching them.
Public Member Functions
Gruen ()
Default constructor.
Gruen (Pvl &pvl)
Construct a Gruen search algorithm.
virtual ~Gruen ()
Destructor.
BigInt CallCount () const
Returns the current call count.
void WriteSubsearchChips (const QString &pattern="SubChip")
Set up for writing subsearch for a a given registration call.
AffineTolerance getAffineTolerance () const
Return set of tolerances for affine convergence.
double getSpiceConstraint () const
Returns the SPICE tolerance constraint as read from config file.
double getAffineConstraint () const
Returns the Affine tolerance constraint as read from config file.
void setAffineRadio (const AffineRadio &affrad)
Sets initial chip transformation.
void setAffineRadio ()
Set affine parameters to defaults.
const AffineRadio & getDefaultAffineRadio () const
Returns default settings for Affine/Radiometric parameters.
const AffineRadio & getAffineRadio () const
Return current state of Affine/Radio state
MatchPoint getLastMatch () const
Returns the register state of the last successful Gruen match.
Chip * PatternChip ()
Return pointer to pattern chip.
Chip * SearchChip ()
Return pointer to search chip.
Chip * FitChip ()
Return pointer to fit chip.
Chip * RegistrationPatternChip ()
Return pointer to pattern chip used in registration.
Chip * RegistrationSearchChip ()
Return pointer to search chip used in registration.
Chip * ReducedPatternChip ()
Return pointer to reduced pattern chip.
Chip * ReducedSearchChip ()
Return pointer to reduced search chip.
Chip * ReducedFitChip ()
Return pointer to reduced fit chip.
void SetSubPixelAccuracy (bool on)
If the sub-pixel accuracy is enabled, the Register() method will attempt to match the pattern chip to the search chip at sub-pixel accuracy, otherwise it will be registered at whole pixel accuracy.
void SetPatternValidPercent (const double percent)
Set the amount of data in the pattern chip that must be valid.
void SetSubsearchValidPercent (const double percent)
Set the amount of data in the search chip's subchip that must be valid.
void SetTolerance (double tolerance)
Set the tolerance for an acceptable goodness of fit.
void SetChipInterpolator (const QString &interpolator)
Sets the Chip class interpolator type to be used to load pattern and search chips.
void SetSurfaceModelWindowSize (int size)
Set the surface model window size.
void SetSurfaceModelDistanceTolerance (double distance)
Set a distance the surface model solution is allowed to move away from the best whole pixel fit in the fit chip.
void SetReductionFactor (int reductionFactor)
Set the reduction factor used to speed up the pattern matching algorithm.
void SetPatternZScoreMinimum (double minimum)
Set the minimum pattern zscore.
void SetGradientFilterType (const QString &gradientFilterType)
Set the gradient filter type to be applied to the search and pattern chips.
QString GradientFilterString () const
bool SubPixelAccuracy ()
Return whether this object will attempt to register to whole or sub-pixel accuracy.
int ReductionFactor ()
Return the reduction factor.
double PatternValidPercent () const
Return pattern chip valid percent. The default value is.
double SubsearchValidPercent () const
Return subsearch chip valid percent.
double Tolerance () const
Return match algorithm tolerance.
double WindowSize () const
Return window size.
double DistanceTolerance () const
Return distance tolerance.
void Distance (double &sampDistance, double &lineDistance)
Return the distance point moved.
AutoReg::RegisterStatus Register ()
Walk the pattern chip through the search chip to find the best registration.
bool Success () const
Return whether the match algorithm succeeded or not.
double GoodnessOfFit () const
Return the goodness of fit of the match algorithm.
bool IsIdeal (double fit)
Returns true if the fit parameter is arbitrarily close to the ideal fit value.
double ChipSample () const
Return the search chip sample that best matched.
double ChipLine () const
Return the search chip line that best matched.
double CubeSample () const
Return the search chip cube sample that best matched.
double CubeLine () const
Return the search chip cube line that best matched.
double MinimumZScore () const
Return minimumPatternZScore.
void ZScores (double &score1, double &score2) const
Return the ZScores of the pattern chip.
Pvl RegistrationStatistics ()
This returns the cumulative registration statistics.
virtual double MostLenientTolerance ()
Minimum tolerance specific to algorithm.
PvlGroup RegTemplate ()
This function returns the keywords that this object was created from.
PvlGroup UpdatedTemplate ()
Returns a PvlGroup containing the PvlKeywords of the parameters this object was most recently run with.
Protected Member Functions
virtual QString AlgorithmName () const
Returns the default name of the algorithm as Gruen.
int algorithm (Chip &pattern, Chip &subsearch, const Radiometric &radio, BigInt &ptsUsed, double &resid, GMatrix &atai, AffineRadio &affrad)
Real workhorse of the computational Gruen algorithm.
Analysis errorAnalysis (const BigInt &npts, const double &resid, const GMatrix &atai)
Compute the error analysis of convergent Gruen matrix.
virtual double MatchAlgorithm (Chip &pattern, Chip &subsearch)
Minimization of data set using Gruen algorithm.
virtual bool CompareFits (double fit1, double fit2)
This virtual method must return if the 1st fit is equal to or better than the second fit.
virtual double IdealFit () const
Returns the ideal fit for a perfect Gruen result.
virtual AutoReg::RegisterStatus Registration (Chip &sChip, Chip &pChip, Chip &fChip, int startSamp, int startLine, int endSamp, int endLine, int bestSamp, int bestLine)
Applies the adaptive Gruen algorithm to pattern and search chips.
virtual Pvl AlgorithmStatistics (Pvl &pvl)
Create Gruen error and processing statistics Pvl output.
void SetChipSample (double sample)
Sets the search chip subpixel sample that matches the pattern tack sample.
void SetChipLine (double line)
Sets the search chip subpixel line that matches the pattern tack line.
void SetGoodnessOfFit (double fit)
Sets the goodness of fit for adaptive algorithms.
void Parse (Pvl &pvl)
Initialize parameters in the AutoReg class using a PVL specification.
bool SetSubpixelPosition (Chip &window)
Set the search chip sample and line to subpixel values if possible.
Chip Reduce (Chip &chip, int reductionFactor)
This method reduces the given chip by the given reduction factor.
Protected Attributes
PvlObject p_template
AutoRegistration object that created this projection.
Detailed Description
Gruen pattern matching algorithm.
This class provides adaptive image (chip) registration using the AutoReg factory architecture. This algorithm uses an Affine transform to iteratively adjust the search chip at each iteration. Each iteration solves for new adjustments to the Affine transform until the 6 affine parameters fall below the tolerances as specified in AffineThreshHold1 and AffineThreshHold2.
This class minimizes the 6 specifiable Affine transform components of a 3x3 matrix. The three Affine components for X (sample) and Y (line) are scale, shear and translation. Gruen provides control over the maximum values these three components should attain in order for the registration to converge to a successful match. These limits are specified by AffineScaleTolerance, AffineShearTolerance and AffineTranslationTolerance. AffineShearTolerance is optional and if not specified, it defaults to the value of AffineScaleTolerance. These tolerances specify the maximum amount of translation pixels can be shifted between one Gruen iteration and another. For example, AffineTranslationTolerance = 0.2 means that a subsearch chip cannot move in sample or line direction more than 0.2 pixels in order to satisfy convergence. AffineScaleTolerance constrains the sample and line scale elements of the Affine transformation. And AffineShearTolerance constrains the sample and line shear elements of the Affine transformation. The scale and shear parameters are scaled by size of the Chip. The sample scale and shear Affine components maximum limit is computed as AffineScaleTolerance/((#Samples-1)/2) and AffineShearTolerance/((#Samples-1)/2). Likewise, the line scale and shear maximums are computed using #Lines in the preceding equation.
See also
MinimumGruen AdaptiveGruen AutoReg
Author
2009-09-09 Kris Becker
Member Enumeration Documentation
GradientFilterType
enum Isis::AutoReg::GradientFilterType inherited
Enumeration of the different types of gradient filters that can be applied to the pattern and search chips before matching them.
Enumerator
None
default, no gradient filter
Sobel
Sobel gradient filter.
RegisterStatus
enum Isis::AutoReg::RegisterStatus inherited
Enumeration of the Register() method's return status.
All of the enumerations describe a failure to register except "Success". These status values can be used to provide the user with more specific feedback on why registration did not succeed.
Enumerator
SuccessPixel
Success registering to whole pixel.
SuccessSubPixel
Success registering to sub-pixel accuracy.
PatternChipNotEnoughValidData
Not enough valid data in pattern chip.
FitChipNoData
Fit chip did not have any valid data.
FitChipToleranceNotMet
Goodness of fit tolerance not satisfied.
SurfaceModelNotEnoughValidData
Not enough points to fit a surface model for sub-pixel accuracy.
SurfaceModelSolutionInvalid
Could not model surface for sub-pixel accuracy.
SurfaceModelDistanceInvalid
Surface model moves registration more than one pixel.
PatternZScoreNotMet
Pattern data max or min does not pass the z-score test.
AdaptiveAlgorithmFailed
Error occured in Adaptive algorithm.
Constructor & Destructor Documentation
Gruen() [1/2]
Isis::Gruen::Gruen ()
Default constructor.
Default constructor sets up default Gruen parameters.
Author
Kris Becker - 5/22/2011
Gruen() [2/2]
Isis::Gruen::Gruen (Pvl & pvl)
Construct a Gruen search algorithm.
This will construct a minimum difference search algorith. It is recommended that you use a AutoRegFactory class as opposed to this constructor. Direct construction is used commonly in stereo matching.
Parameters
pvl A Pvl object that contains a valid automatic registration definition
~Gruen()
virtual Isis::Gruen::~Gruen () inline virtual
Destructor.
Member Function Documentation
algorithm()
int Isis::Gruen::algorithm (Chip & pattern, Chip & subsearch, const Radiometric & radio, BigInt & ptsUsed, double & resid, GMatrix & atai, AffineRadio & affrad) protected
Real workhorse of the computational Gruen algorithm.
This method is called for all registration requests and actually performs the registration of two chips.
The pattern chip is deemed constant. The subsearch chip is generally an extraction from the search chip that has had an affine transform applied to fill it.
At each iteration of the Gruen algorithm, the affine transform is incrementally updated based upon the results from this method. There are six affine parameters and two radiometric (shift and gain) parameters that are solved/computed here.
The algorithm itself is a first derivative computation of the subsearch chip with small radiometric adjustments applied to better tone match the two chips. This is intended to minimize the affine variability.
Parameters
pattern Fixed pattern chip which subsearch is trying to match
subsearch Affined extraction of the search chip
Returns
Returns 0 if successful, otherwise returns the error number associated with the problem encountered (see ErrorTypes)
References Isis::Radiometric::Gain(), Isis::Chip::GetValue(), Isis::Chip::IsValid(), Isis::Chip::Lines(), Isis::Chip::Samples(), Isis::Radiometric::Shift(), Isis::Chip::TackLine(), Isis::Chip::TackSample(), and Isis::IException::toString().
Referenced by MatchAlgorithm(), and Registration().
AlgorithmName()
virtual QString Isis::Gruen::AlgorithmName () const inline protected virtual
Returns the default name of the algorithm as Gruen.
Implements Isis::AutoReg.
Reimplemented in Isis::AdaptiveGruen.
Referenced by AlgorithmStatistics().
AlgorithmStatistics()
Pvl Isis::Gruen::AlgorithmStatistics (Pvl & pvl) protected virtual
Create Gruen error and processing statistics Pvl output.
This method generates two groups specific to the Gruen algorithm: The GruenFailures group which logs all the errors enountered during processing and the GruenStatistics group which logs selected statistics gathered during a registration run.
These groups are added to the AutoReg log output Pvl container for reporting to user/log files.
Parameters
pvl Input AutoReg Pvl container to add results to
Returns
Pvl Output Pvl container with Gruen information
Reimplemented from Isis::AutoReg.
References Isis::PvlObject::addGroup(), AlgorithmName(), Isis::CollectorMap< K, T, ComparePolicy, RemovalPolicy, CopyPolicy >::getNth(), Isis::CollectorMap< K, T, ComparePolicy, RemovalPolicy, CopyPolicy >::size(), and Isis::toString().
CallCount()
BigInt Isis::Gruen::CallCount () const inline
Returns the current call count.
ChipLine()
double Isis::AutoReg::ChipLine () const inline inherited
Return the search chip line that best matched.
ChipSample()
double Isis::AutoReg::ChipSample () const inline inherited
Return the search chip sample that best matched.
CompareFits()
bool Isis::Gruen::CompareFits (double fit1, double fit2) protected virtual
This virtual method must return if the 1st fit is equal to or better than the second fit.
Parameters
fit1 1st goodness of fit
fit2 2nd goodness of fit
Reimplemented from Isis::AutoReg.
CubeLine()
double Isis::AutoReg::CubeLine () const inline inherited
Return the search chip cube line that best matched.
CubeSample()
double Isis::AutoReg::CubeSample () const inline inherited
Return the search chip cube sample that best matched.
Distance()
void Isis::AutoReg::Distance (double & sampDistance, double & lineDistance) inline inherited
Return the distance point moved.
Parameters
sampDistance Sample movement
lineDistance Line movement
DistanceTolerance()
double Isis::AutoReg::DistanceTolerance () const inline inherited
Return distance tolerance.
errorAnalysis()
Analysis Isis::Gruen::errorAnalysis (const BigInt & npts, const double & resid, const GMatrix & atai) protected
Compute the error analysis of convergent Gruen matrix.
Author
kbecker (5/15/2011)
Parameters
npts
resid
atai
Returns
Analysis
References Isis::Analysis::m_kmat, Isis::Analysis::m_npts, Isis::Analysis::m_sevals, Isis::Analysis::m_status, Isis::Analysis::m_variance, and Isis::IException::toString().
Referenced by MatchAlgorithm(), and Registration().
FitChip()
Chip* Isis::AutoReg::FitChip () inline inherited
Return pointer to fit chip.
Referenced by Isis::ControlMeasureEditWidget::saveChips(), and Isis::ControlPointEdit::saveChips().
getAffineConstraint()
double Isis::Gruen::getAffineConstraint () const inline
Returns the Affine tolerance constraint as read from config file.
getAffineRadio()
const AffineRadio& Isis::Gruen::getAffineRadio () const inline
Return current state of Affine/Radio state
getAffineTolerance()
AffineTolerance Isis::Gruen::getAffineTolerance () const
Return set of tolerances for affine convergence.
Author
kbecker (5/15/2011)
Returns
Tolerance Affine tolerances from PVL setup
Referenced by Registration().
getDefaultAffineRadio()
const AffineRadio& Isis::Gruen::getDefaultAffineRadio () const inline
Returns default settings for Affine/Radiometric parameters.
Referenced by setAffineRadio().
getLastMatch()
MatchPoint Isis::Gruen::getLastMatch () const inline
Returns the register state of the last successful Gruen match.
This method returns the full match condition of the last call to Gruen Register function that was successful.
BEWARE: This is only valid if Register returns successfully! This is due to AutoReg returning conditions that occur prior to the actual Gruen algorithm being called.
Author
Kris Becker - 6/4/2011
Returns
MatchPoint
getSpiceConstraint()
double Isis::Gruen::getSpiceConstraint () const inline
Returns the SPICE tolerance constraint as read from config file.
GoodnessOfFit()
double Isis::AutoReg::GoodnessOfFit () const inline inherited
Return the goodness of fit of the match algorithm.
GradientFilterString()
QString Isis::AutoReg::GradientFilterString () const inherited
References _FILEINFO_, and Isis::None.
IdealFit()
virtual double Isis::Gruen::IdealFit () const inline protected virtual
Returns the ideal fit for a perfect Gruen result.
Implements Isis::AutoReg.
IsIdeal()
bool Isis::AutoReg::IsIdeal (double fit) inline inherited
Returns true if the fit parameter is arbitrarily close to the ideal fit value.
Parameters
fit Fit value to be compared to the ideal fit
Returns
bool Indicates whether the fit is ideal
MatchAlgorithm()
double Isis::Gruen::MatchAlgorithm (Chip & pattern, Chip & subsearch) protected virtual
Minimization of data set using Gruen algorithm.
This is a very minimal application of the Gruen algorithm that provides the ability to use it in a non-adaptive capacity. This method processes two chips of the same size, pattern and subsearch. The subsearch has typically been extracted in the same manner as the MinimumDifference or MaximumCorrelation routines are utilized.
It simply applies the algorithm to the current state of the two chips, computes the error analysis on it and returns the eigen vector solution as an indication of chip registration integrity.
Note that in this mode, most all the parameters found in the definition file that apply to the adaptive mode are ignored when utilizing the algorithm in this fashion.
Parameters
pattern [in] A Chip object usually containing an nxm area of a cube. Must be the same diminsions as subsearch.
subsearch [in] A Chip object usually containing an nxm area of a cube. Must be the same dimensions as pattern. This is normally a subarea of a larger portion of the image.
Returns
The square root of the eigen values of DN differences OR Isis::NULL if the Gruen algorithm fails.
Implements Isis::AutoReg.
References algorithm(), errorAnalysis(), Isis::Analysis::getEigen(), Isis::Analysis::isValid(), and Isis::Null.
MinimumZScore()
double Isis::AutoReg::MinimumZScore () const inline inherited
Return minimumPatternZScore.
MostLenientTolerance()
virtual double Isis::AutoReg::MostLenientTolerance () inline virtual inherited
Minimum tolerance specific to algorithm.
Reimplemented in Isis::MinimumDifference.
Parse()
void Isis::AutoReg::Parse (Pvl & pvl) protected inherited
Initialize parameters in the AutoReg class using a PVL specification.
An example of the PVL required for this is:
Object = AutoRegistration
  Group = Algorithm
    Name      = MaximumCorrelation
    Tolerance = 0.7
  EndGroup
  Group = PatternChip
    Samples = 21
    Lines   = 21
  EndGroup
  Group = SearchChip
    Samples = 51
    Lines = 51
  EndGroup
EndObject
There are many other options that can be set via the pvl and are described in other documentation (see below).
See also
patternMatch.doc under the coreg application
Parameters
pvl The pvl object containing the specification
Exceptions
iException::User "Improper format for AutoReg PVL."
References _FILEINFO_, Isis::PvlContainer::fileName(), Isis::PvlObject::findGroup(), Isis::PvlObject::findObject(), Isis::PvlObject::hasGroup(), Isis::PvlContainer::hasKeyword(), Isis::ValidMaximum, and Isis::ValidMinimum.
PatternChip()
Chip* Isis::AutoReg::PatternChip () inline inherited
Return pointer to pattern chip.
PatternValidPercent()
double Isis::AutoReg::PatternValidPercent () const inline inherited
Return pattern chip valid percent. The default value is.
Referenced by Isis::MaximumCorrelation::MatchAlgorithm().
Reduce()
Chip Isis::AutoReg::Reduce (Chip & chip, int reductionFactor) protected inherited
This method reduces the given chip by the given reduction factor.
Used to speed up the match algorithm.
Parameters
chip Chip to be reduced
reductionFactor Factor by which to reduce chip.
Returns
Chip Reduced chip object
References Isis::Statistics::AddData(), Isis::Statistics::Average(), Isis::Chip::GetValue(), Isis::Chip::Lines(), Isis::Null, Isis::Statistics::Reset(), Isis::Chip::Samples(), and Isis::Chip::SetValue().
ReducedFitChip()
Chip* Isis::AutoReg::ReducedFitChip () inline inherited
Return pointer to reduced fit chip.
ReducedPatternChip()
Chip* Isis::AutoReg::ReducedPatternChip () inline inherited
Return pointer to reduced pattern chip.
ReducedSearchChip()
Chip* Isis::AutoReg::ReducedSearchChip () inline inherited
Return pointer to reduced search chip.
ReductionFactor()
int Isis::AutoReg::ReductionFactor () inline inherited
Return the reduction factor.
Register()
AutoReg::RegisterStatus Isis::AutoReg::Register () inherited
Walk the pattern chip through the search chip to find the best registration.
Returns
AutoReg::RegisterStatus Returns the status of the registration.
Exceptions
iException::User - "Search chips samples must be at least N pixels wider than the pattern chip samples for successful surface modeling"
iException::User - "Search chips lines must be at least N pixels taller than the pattern chip lines for successful surface modeling"
iException::User - "Reduction factor is too large"
References _FILEINFO_, Isis::Chip::CubeLine(), Isis::Chip::CubeSample(), Isis::Chip::IsValid(), Isis::Chip::Lines(), Isis::None, Isis::Null, Isis::Chip::Samples(), Isis::Chip::SetChipPosition(), Isis::Chip::TackLine(), and Isis::Chip::TackSample().
Registration()
AutoReg::RegisterStatus Isis::Gruen::Registration (Chip & sChip, Chip & pChip, Chip & fChip, int startSamp, int startLine, int endSamp, int endLine, int bestSamp, int bestLine) protected virtual
Applies the adaptive Gruen algorithm to pattern and search chips.
This method computes the adaptive Gruen algorithm for a pattern chip and search chip. The search chip is assumed to be of a larger size than the pattern chip as dictated by the contents of the registration definition file.
This algorithm can be used with or without "fast geoming" the search chip. It works quite well where the two images are assumed to be nearly spatially registered. Its real intent is to compute parallax angles between two images taken at different viewing geometry. This provides an efficient process for deriving a digital elevation model (DEM) from two datasets.
The Gruen algorithm is applied to the chips until the algorithm converges (current iteration yields a detla affine within tolerance limits), an error is encountered, or the maximum number of iterations is exceeded.
Note that bestSamp and bestLine may not be the original center of the search chip. It is subject to chip reduction matching as specified by the user. All distance tolerances are compute from this postion. The process of chip reduction processing is handled by AutoReg prior to calling this routine.
See also
getThreshHold() for Affine limit information
Parameters
sChip Full search chip as rendered from the search image
pChip Full pattern chip as rendered from the pattern/match image
fChip Maintains the solution vector at each chip location
startSamp Starting sample of the search image range
startLine Starting line of the search image range
endSamp Ending sample of the search image range
endLine Ending line of the search image range
bestSamp Best registering sample of search chip
bestLine best registering line of search chip
Returns
AutoReg::RegisterStatus Returns AutoReg::Success if the chip is successfully registered, otherwise returns AutoReg::AdaptiveAlgorithmFailed.
Reimplemented from Isis::AutoReg.
References algorithm(), errorAnalysis(), Isis::Chip::Extract(), getAffineTolerance(), Isis::MatchPoint::getEigen(), Isis::Coordinate::getLine(), Isis::Coordinate::getSample(), Isis::Threshold::hasConverged(), Isis::MatchPoint::isValid(), Isis::Chip::Lines(), Isis::AffineRadio::m_affine, Isis::MatchPoint::m_affine, Isis::MatchPoint::m_analysis, Isis::MatchPoint::m_nIters, Isis::AffineRadio::m_radio, Isis::Analysis::m_status, Isis::Chip::Samples(), Isis::AutoReg::SetChipLine(), Isis::Chip::SetChipPosition(), Isis::AutoReg::SetChipSample(), Isis::AutoReg::SetGoodnessOfFit(), Isis::Chip::SetSize(), Isis::MatchPoint::setStatus(), Isis::Chip::TackLine(), Isis::Chip::TackSample(), Isis::AffineRadio::Translate(), and Isis::Chip::Write().
RegistrationPatternChip()
Chip* Isis::AutoReg::RegistrationPatternChip () inline inherited
Return pointer to pattern chip used in registration.
References Isis::AutoReg::None.
Referenced by Isis::ControlMeasureEditWidget::saveChips(), and Isis::ControlPointEdit::saveChips().
RegistrationSearchChip()
Chip* Isis::AutoReg::RegistrationSearchChip () inline inherited
Return pointer to search chip used in registration.
References Isis::AutoReg::None.
Referenced by Isis::ControlMeasureEditWidget::saveChips(), and Isis::ControlPointEdit::saveChips().
RegistrationStatistics()
Pvl Isis::AutoReg::RegistrationStatistics () inherited
This returns the cumulative registration statistics.
That is, the Register() method accumulates statistics regard the errors each time is called. Invoking this method returns a PVL summary of those statisitics
Author
janderson (3/26/2009)
Returns
Pvl
References Isis::PvlObject::addGroup(), and Isis::toString().
RegTemplate()
PvlGroup Isis::AutoReg::RegTemplate () inherited
This function returns the keywords that this object was created from.
Returns
PvlGroup The keywords this object used in initialization
References Isis::PvlContainer::hasKeyword().
SearchChip()
Chip* Isis::AutoReg::SearchChip () inline inherited
Return pointer to search chip.
setAffineRadio() [1/2]
void Isis::Gruen::setAffineRadio ()
Set affine parameters to defaults.
This method differs from the one above in that it uses the defaults as defined at construction. The basic difference is that this call sets the affine portion to the identity and the radiometric parameters to the defaults as provided in the user input auto-regististration parameters. It may have default shift and gain values to use.
Author
Kris Becker - 6/4/2011
References getDefaultAffineRadio().
setAffineRadio() [2/2]
void Isis::Gruen::setAffineRadio (const AffineRadio & affrad)
Sets initial chip transformation.
This method can be used with AutoReg registration to set initial affine transform parameters. This initial condition will be applied to the whole search chip extraction for the first subsearch chip. The caller must define the contents of the affine and radiometric parameters. See the AffineRadio construct for details.
Author
kbecker (5/14/2011)
Parameters
affrad Initial Affine/Radio parameters to apply on registration entry
SetChipInterpolator()
void Isis::AutoReg::SetChipInterpolator (const QString & interpolator) inherited
Sets the Chip class interpolator type to be used to load pattern and search chips.
Acceptable values for the interpolator parameter include:
NearestNeighborType
BiLinearType
CubicConvolutionType
If this method is not called, the chip interpolator type defaults to CubicConvolutionType in the Chip class.
Parameters
interpolator Name of interpolator type to be used. This is taken from the Pvl's ChipInterpolator keyword value.
Exceptions
iException::User - "Invalid Interpolator type."
Author
Jeannie Walldren
References _FILEINFO_, Isis::Interpolator::BiLinearType, Isis::Interpolator::CubicConvolutionType, and Isis::Interpolator::NearestNeighborType.
SetChipLine()
void Isis::AutoReg::SetChipLine (double line) inline protected inherited
Sets the search chip subpixel line that matches the pattern tack line.
Parameters
line Value to set for search chip subpixel line
Referenced by Registration().
SetChipSample()
void Isis::AutoReg::SetChipSample (double sample) inline protected inherited
Sets the search chip subpixel sample that matches the pattern tack sample.
Parameters
sample Value to set for search chip subpixel sample
Referenced by Registration().
SetGoodnessOfFit()
void Isis::AutoReg::SetGoodnessOfFit (double fit) inline protected inherited
Sets the goodness of fit for adaptive algorithms.
Parameters
fit Fit value to set
Referenced by Registration().
SetGradientFilterType()
void Isis::AutoReg::SetGradientFilterType (const QString & gradientFilterType) inherited
Set the gradient filter type to be applied to the search and pattern chips.
Parameters
gradientFilterType the gradient filter type to use
Exceptions
iException::User - "Invalid Gradient type."
References _FILEINFO_, and Isis::None.
SetPatternValidPercent()
void Isis::AutoReg::SetPatternValidPercent (const double percent) inherited
Set the amount of data in the pattern chip that must be valid.
For example, a 21x21 pattern chip has 441 pixels. If percent is 75 then at least 330 pixels pairs must be valid in order for a comparision between the pattern and search sub-region to occur. That is, both the pattern pixel and search pixel must be valid to be counted. Pixels are considered valid based on the min/max range specified on each of the Chips (see Chip::SetValidRange method).
If the pattern chip reduction option is used this percentage will apply to all reduced patterns. Additionally, the pattern sampling effects the pixel count. For example if pattern sampling is 50% then only 220 pixels in the 21x21 pattern are considered so 165 must be valid.
If this method is not called, the PatternChip ValidPercent defaults to 50 in the AutoReg object constructor.
See also
SetValidRange()
Parameters
percent Percentage of valid data between 0 and 100, default is 50% if never invoked
Exceptions
iException::User - "Invalid value for PatternChip ValidPercent."
References _FILEINFO_.
SetPatternZScoreMinimum()
void Isis::AutoReg::SetPatternZScoreMinimum (double minimum) inherited
Set the minimum pattern zscore.
This option is used to ignore pattern chips which are bland (low standard deviation). If the minimum or maximum pixel value in the pattern chip does not meet the minimum zscore value (see a statisitcs book for definition of zscore) then invalid registration will occur.
If this method is not called, the z-score minimum defaults to 1.0 in the AutoReg object constructor.
Parameters
minimum The minimum zscore value for the pattern chip. Default is 1.0
Exceptions
iException::User - "Invalid value for PatternChip MinimumZScore."
References _FILEINFO_.
SetReductionFactor()
void Isis::AutoReg::SetReductionFactor (int factor) inherited
Set the reduction factor used to speed up the pattern matching algorithm.
If this method is not called, the reduction factor defaults to 1 in the AutoReg object constructor.
Parameters
factor Reduction factor. Must be greater than or equal to 1.
Exceptions
iException::User - "Invalid value for Algorithm ReductionFactor."
References _FILEINFO_.
SetSubPixelAccuracy()
void Isis::AutoReg::SetSubPixelAccuracy (bool on) inherited
If the sub-pixel accuracy is enabled, the Register() method will attempt to match the pattern chip to the search chip at sub-pixel accuracy, otherwise it will be registered at whole pixel accuracy.
If this method is not called, the sub pixel accuracy defaults to on = true in the AutoReg object constructor.
Parameters
on Set the state of registration accuracy. The default is sub-pixel accuracy is on
SetSubpixelPosition()
bool Isis::AutoReg::SetSubpixelPosition (Chip & window) protected inherited
Set the search chip sample and line to subpixel values if possible.
This method uses a centroiding method to gravitate the whole pixel best fit to a subpixel extremum in the continuous image space. The weights of the centers of gravity in the centroiding algorithm are modeled by goodness of fit values within a discrete search window.
Parameters
window The search window extracted from the fit chip
Returns
bool Returns true if the subpixel solution is valid
References Isis::Chip::ChipLine(), Isis::Chip::ChipSample(), Isis::Chip::GetValue(), Isis::Chip::Lines(), Isis::Chip::Samples(), Isis::Centroid::setDNRange(), and Isis::Chip::SetValue().
SetSubsearchValidPercent()
void Isis::AutoReg::SetSubsearchValidPercent (const double percent) inherited
Set the amount of data in the search chip's subchip that must be valid.
If this method is not called, the SearchChip SubchipValidPercent defaults to 50 in the AutoReg object constructor.
Parameters
percent Percentage of valid data between 0 and 100, default is 50% if never invoked
See also
SetPatternValidPercent()
Exceptions
iException::User - "Invalid value for SearchChip SubchipValidPercent."
References _FILEINFO_.
SetSurfaceModelDistanceTolerance()
void Isis::AutoReg::SetSurfaceModelDistanceTolerance (double distance) inherited
Set a distance the surface model solution is allowed to move away from the best whole pixel fit in the fit chip.
If this method is not called, the distance tolerance defaults to 1.5 in the AutoReg object constructor.
Parameters
distance The distance allowed to move in pixels. Must be greater than 0.
Exceptions
iException::User - "Invalid value for SurfaceModel DistanceTolerance."
References _FILEINFO_.
SetSurfaceModelWindowSize()
void Isis::AutoReg::SetSurfaceModelWindowSize (int size) inherited
Set the surface model window size.
The pixels in this window will be used to fit a surface model in order to compute sub-pixel accuracy. In some cases the default (3x3) and produces erroneous sub-pixel accuracy values.
If this method is not called, the window size defaults to 5 in the AutoReg object constructor.
Parameters
size The size of the window must be three or greater and odd.
Exceptions
iException::User - "Invalid value for SurfaceModel WindowSize."
References _FILEINFO_.
SetTolerance()
void Isis::AutoReg::SetTolerance (double tolerance) inherited
Set the tolerance for an acceptable goodness of fit.
If this method is not called, the tolerance value defaults to Isis::Null in the AutoReg object constructor.
Parameters
tolerance This tolerance is used to test against the goodness of fit returned by the MatchAlgorith method after a surface model has been fit. See TestGoodnessOfFit
SubPixelAccuracy()
bool Isis::AutoReg::SubPixelAccuracy () inline inherited
Return whether this object will attempt to register to whole or sub-pixel accuracy.
Returns
on Is sub-pixel accuracy enabled?
SubsearchValidPercent()
double Isis::AutoReg::SubsearchValidPercent () const inline inherited
Return subsearch chip valid percent.
Success()
bool Isis::AutoReg::Success () const inline inherited
Return whether the match algorithm succeeded or not.
References Isis::AutoReg::SuccessPixel, and Isis::AutoReg::SuccessSubPixel.
Tolerance()
double Isis::AutoReg::Tolerance () const inline inherited
Return match algorithm tolerance.
UpdatedTemplate()
PvlGroup Isis::AutoReg::UpdatedTemplate () inherited
Returns a PvlGroup containing the PvlKeywords of the parameters this object was most recently run with.
Because of publically accessible mutators, AutoReg's runtime parameters can change, and this version of the template is designed to reflect the paramters it was actually run with, as opposed to simply initialized with. If no mutators were ever called externally, then this PvlGroup should be the same as the one received from RegTemplate().
Returns
PvlGroup The keywords this object was most recently run with
References Isis::Chip::Lines(), Isis::Chip::Samples(), and Isis::toString().
WindowSize()
double Isis::AutoReg::WindowSize () const inline inherited
Return window size.
WriteSubsearchChips()
void Isis::Gruen::WriteSubsearchChips (const QString & pattern = "SubChip")
Set up for writing subsearch for a a given registration call.
This method is provided to request the write of the subsearch chip at each iteration. This must be invoked prior to every call to AutoReg::Register() method. It will only write subchips from the Register() interface as it interates to a solution. Direct calls to Gruen methods don't iterate in the same fashion.
The "pattern" parameter is optional but is provided to direct the location and naming convention of each subsearch chip. The format for the output file name for each subsearch chip is comprised of the pattern parameter, call number, which can be retrieved by the CallCount() method and pertains to the call after the Register() method is invoked and the interation count. Below is a code example:
Gruen gruen(myPvldef);
// Set up pattern and search chips here
gruen.WriteSubsearchChips("/mydata/subchip");
gruen.Register();
Note that prior to each call to Register(), it must be called again in order for the subchips to be written. The last part of the parameter above, "subchip", cannot be a directory, but is a filename prefix. Assuming this is the first call to Register(), a series of cube subsearch chips will be written with the pattern "/work1/kbecker/subchipC000001IXXX.cub" where "C" indicates call count and the next 6 digits are the return of CallCount() method, "I" indicates the iteration count "XXX" of the algorithm() method. Note that the chip written for a particular iteration is what is provided as a parameter into the algorithm() method.
Parameters
pattern Specifies an optional directory and file pattern to write the subsearch chip at each algorithm iteration.
ZScores()
void Isis::AutoReg::ZScores (double & score1, double & score2) const inline inherited
Return the ZScores of the pattern chip.
Parameters
score1 First Z Score
score2 Second Z Score
Member Data Documentation
p_template
PvlObject Isis::AutoReg::p_template protected inherited
AutoRegistration object that created this projection.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Gruen/Gruen.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Gruen/Gruen.cpp