Isis Developer Reference: Isis::ControlPointGraphicsItem Class Reference
Isis::ControlPointGraphicsItem Class Reference
The visual display of a single control point.
#include <ControlPointGraphicsItem.h>
Public Member Functions
ControlPointGraphicsItem (QPointF center, QPointF apriori, ControlPoint *cp, SerialNumberList *snList, MosaicSceneWidget *scene, QGraphicsItem *parent)
Create a CP graphics item.
virtual ~ControlPointGraphicsItem ()
void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *widget=0)
This virtual paint method is called anytime an update() or paintEvent() is called.
ControlPoint * controlPoint ()
void setArrowVisible (bool visible, bool colorByMeasureCount, int measureCount, bool colorByResidualMagnitude, double residualMagnitude)
Protected Member Functions
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
Detailed Description
The visual display of a single control point.
The control point tries to always draw itself at a constant size and uses the scene pointer to accomplish this.
Author
2011-05-07 Steven Lambright
Constructor & Destructor Documentation
ControlPointGraphicsItem()
Isis::ControlPointGraphicsItem::ControlPointGraphicsItem (QPointF center, QPointF apriori, ControlPoint * cp, SerialNumberList * snList, MosaicSceneWidget * boundingRectSrc, QGraphicsItem * parent)
Create a CP graphics item.
This will colorize and set the appropriate toolTip for this control point.
References Isis::ControlPoint::Constrained, Isis::ControlPoint::Fixed, Isis::ControlPoint::GetType(), Isis::ControlPoint::IsIgnored(), and Isis::Null.
~ControlPointGraphicsItem()
Isis::ControlPointGraphicsItem::~ControlPointGraphicsItem () virtual
Member Function Documentation
contextMenuEvent()
void Isis::ControlPointGraphicsItem::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) protected
References Isis::ControlPoint::GetId().
controlPoint()
ControlPoint * Isis::ControlPointGraphicsItem::controlPoint ()
paint()
void Isis::ControlPointGraphicsItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * style, QWidget * widget = 0)
This virtual paint method is called anytime an update() or paintEvent() is called.
Parameters
painter (QPainter *) Painter used to draw
style (QStyleOptionGraphicsItem *) Describes parameters used to draw a QGraphicsItem
widget (QWidget *) Optional argument which indicates the widget that is being painted on
References Isis::Statistics::AddData(), Isis::Statistics::Average(), Isis::MosaicSceneWidget::directory(), Isis::Directory::editPointId(), Isis::ControlPoint::GetId(), Isis::ControlPoint::getMeasures(), Isis::ControlMeasure::GetResidualMagnitude(), Isis::IsSpecial(), Isis::Statistics::Maximum(), and Isis::Null.
setArrowVisible()
void Isis::ControlPointGraphicsItem::setArrowVisible (bool visible, bool colorByMeasureCount, int measureCount, bool colorByResidualMagnitude, double residualMagnitude)
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/ControlPointGraphicsItem.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/ControlPointGraphicsItem.cpp