Isis Developer Reference: Isis::LinearStretchType Class Reference
Isis::LinearStretchType Class Reference
This handles the advanced linear stretch.
#include <LinearStretchType.h>
Signals
void saveToCube ()
Emitted when a new Stretch object is available.
void deleteFromCube ()
void stretchChanged ()
void loadStretch ()
Public Member Functions
LinearStretchType (const Histogram &, const Stretch &, const QString &name, const QColor &color)
This constructs a linear stretch type.
~LinearStretchType ()
Destructor.
virtual CubeStretch getStretch ()
Returns the CubeStretch for this LinearStretch.
virtual void setStretch (Stretch)
Given an arbitrary stretch, this will re-interpret it, as best as possible, into a linear stretch.
virtual void setHistogram (const Histogram &)
This should be called when the visible area changes.
Protected Slots
void updateGraph ()
This updates the graph with the current stretch object.
void updateTable ()
This updates the table with the current stretch pairs.
Protected Member Functions
QTableWidget * createStretchTable ()
This creates the stretch pairs table.
Protected Attributes
QGridLayout * p_mainLayout
Main layout.
Histogram * p_cubeHist
Visible area histogram.
QTableWidget * p_table
Pairs table.
HistogramWidget * p_graph
Histogram graph.
Stretch * p_stretch
Current stretch pairs stored here.
Detailed Description
This handles the advanced linear stretch.
The linear stretch is what happens without the advanced stretch tool. This is useful for visualizing and making adjustments of the linear stretch with a histogram of the data.
Author
2010-05-20 Steven Lambright
Constructor & Destructor Documentation
LinearStretchType()
Isis::LinearStretchType::LinearStretchType (const Histogram & hist, const Stretch & stretch, const QString & name, const QColor & color)
This constructs a linear stretch type.
Parameters
hist
stretch
name
color
References Isis::StretchType::p_mainLayout, and setStretch().
~LinearStretchType()
Isis::LinearStretchType::~LinearStretchType ()
Destructor.
Member Function Documentation
createStretchTable()
QTableWidget * Isis::StretchType::createStretchTable () protected inherited
This creates the stretch pairs table.
Returns
QTableWidget*
Referenced by Isis::StretchType::StretchType().
deleteFromCube
void Isis::StretchType::deleteFromCube () signal inherited
Referenced by Isis::StretchType::StretchType().
getStretch()
CubeStretch Isis::LinearStretchType::getStretch () virtual
Returns the CubeStretch for this LinearStretch.
Returns
CubeStretch
Reimplemented from Isis::StretchType.
References Isis::StretchType::p_stretch.
loadStretch
void Isis::StretchType::loadStretch () signal inherited
Referenced by Isis::StretchType::StretchType().
saveToCube
void Isis::StretchType::saveToCube () signal inherited
Emitted when a new Stretch object is available.
Referenced by Isis::StretchType::StretchType().
setHistogram()
void Isis::StretchType::setHistogram (const Histogram & hist) virtual inherited
This should be called when the visible area changes.
It updates the graph and calls setStretch() so that the children have a chance to update their GUI elements too.
Parameters
hist
References Isis::StretchType::p_cubeHist, Isis::StretchType::p_graph, Isis::StretchType::p_stretch, Isis::HistogramWidget::setHistogram(), and Isis::StretchType::setStretch().
Referenced by Isis::AdvancedStretch::setHistogram().
setStretch()
void Isis::LinearStretchType::setStretch (Stretch newStretch) virtual
Given an arbitrary stretch, this will re-interpret it, as best as possible, into a linear stretch.
It is required that a stretch that represents a linear stretch always translate into itself and does not cause a stretchChanged().
It is necessary to always update slider positions in this method even if the stretch did not change.
Parameters
newStretch Stretch to interpret
Implements Isis::StretchType.
References Isis::Stretch::AddPair(), Isis::Statistics::BestMaximum(), Isis::Statistics::BestMinimum(), Isis::Histogram::BinSize(), Isis::Stretch::CopyPairs(), Isis::Stretch::Input(), Isis::StretchType::p_cubeHist, Isis::StretchType::p_stretch, Isis::Stretch::Pairs(), Isis::StretchType::stretchChanged(), and Isis::Stretch::Text().
Referenced by LinearStretchType().
stretchChanged
void Isis::StretchType::stretchChanged () signal inherited
Referenced by Isis::ManualStretchType::ManualStretchType(), Isis::BinaryStretchType::setStretch(), setStretch(), Isis::ManualStretchType::setStretch(), Isis::SawtoothStretchType::setStretch(), and Isis::StretchType::StretchType().
updateGraph
void Isis::StretchType::updateGraph () protected slot inherited
This updates the graph with the current stretch object.
References Isis::StretchType::p_graph, Isis::StretchType::p_stretch, and Isis::HistogramWidget::setStretch().
Referenced by Isis::StretchType::StretchType().
updateTable
void Isis::StretchType::updateTable () protected slot inherited
This updates the table with the current stretch pairs.
References Isis::StretchType::getStretch(), Isis::Stretch::Input(), Isis::Stretch::Output(), Isis::StretchType::p_table, and Isis::Stretch::Pairs().
Referenced by Isis::ManualStretchType::ManualStretchType(), Isis::ManualStretchType::setStretch(), and Isis::StretchType::StretchType().
Member Data Documentation
p_cubeHist
Histogram* Isis::StretchType::p_cubeHist protected inherited
Visible area histogram.
Referenced by Isis::BinaryStretchType::BinaryStretchType(), Isis::SawtoothStretchType::SawtoothStretchType(), Isis::StretchType::setHistogram(), Isis::BinaryStretchType::setStretch(), setStretch(), Isis::SawtoothStretchType::setStretch(), Isis::StretchType::StretchType(), and Isis::StretchType::~StretchType().
p_graph
HistogramWidget* Isis::StretchType::p_graph protected inherited
Histogram graph.
Referenced by Isis::StretchType::setHistogram(), Isis::StretchType::StretchType(), and Isis::StretchType::updateGraph().
p_mainLayout
QGridLayout* Isis::StretchType::p_mainLayout protected inherited
Main layout.
Referenced by Isis::BinaryStretchType::BinaryStretchType(), LinearStretchType(), Isis::ManualStretchType::ManualStretchType(), Isis::SawtoothStretchType::SawtoothStretchType(), and Isis::StretchType::StretchType().
p_stretch
Stretch* Isis::StretchType::p_stretch protected inherited
Current stretch pairs stored here.
Referenced by Isis::BinaryStretchType::getStretch(), getStretch(), Isis::ManualStretchType::getStretch(), Isis::SawtoothStretchType::getStretch(), Isis::StretchType::getStretch(), Isis::StretchType::setHistogram(), Isis::BinaryStretchType::setStretch(), setStretch(), Isis::ManualStretchType::setStretch(), Isis::SawtoothStretchType::setStretch(), Isis::StretchType::StretchType(), Isis::StretchType::updateGraph(), and Isis::StretchType::~StretchType().
p_table
QTableWidget* Isis::StretchType::p_table protected inherited
Pairs table.
Referenced by Isis::ManualStretchType::ManualStretchType(), Isis::StretchType::StretchType(), and Isis::StretchType::updateTable().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/StretchTool/LinearStretchType.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/StretchTool/LinearStretchType.cpp