Isis Developer Reference: Isis::Equalization::ImageAdjustment Class Reference
Isis::Equalization::ImageAdjustment Class Reference
#include <Equalization.h>
Public Member Functions
ImageAdjustment (OverlapNormalization::SolutionType sType)
~ImageAdjustment ()
void addGain (double gain)
void addOffset (double offset)
void addAverage (double average)
double getGain (int index) const
double getOffset (int index) const
double getAverage (int index) const
double evaluate (double dn, int index) const
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
ImageAdjustment()
Isis::Equalization::ImageAdjustment::ImageAdjustment (OverlapNormalization::SolutionType sType) inline
~ImageAdjustment()
Isis::Equalization::ImageAdjustment::~ImageAdjustment () inline
Member Function Documentation
addAverage()
void Isis::Equalization::ImageAdjustment::addAverage (double average) inline
Referenced by Isis::HiEqualization::calculateStatistics(), and Isis::Equalization::importStatistics().
addGain()
void Isis::Equalization::ImageAdjustment::addGain (double gain) inline
Referenced by Isis::HiEqualization::calculateStatistics(), and Isis::Equalization::importStatistics().
addOffset()
void Isis::Equalization::ImageAdjustment::addOffset (double offset) inline
Referenced by Isis::HiEqualization::calculateStatistics(), and Isis::Equalization::importStatistics().
evaluate()
double Isis::Equalization::ImageAdjustment::evaluate (double dn, int index) const inline
References Isis::Null.
getAverage()
double Isis::Equalization::ImageAdjustment::getAverage (int index) const inline
getGain()
double Isis::Equalization::ImageAdjustment::getGain (int index) const inline
getOffset()
double Isis::Equalization::ImageAdjustment::getOffset (int index) const inline
The documentation for this class was generated from the following file:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Equalization/Equalization.h