Isis Developer Reference: Isis::FilterWidget Class Reference
Isis::FilterWidget Class Reference
This widget contains filtering capabilities for a single filter type.
#include <FilterWidget.h>
Signals
void filterChanged ()
void scrollToBottom ()
Public Member Functions
FilterWidget (QString)
FilterWidget (const FilterWidget &)
virtual ~FilterWidget ()
template<typename T >
bool evaluate (const T *t, bool(AbstractFilter::*meth)() const) const
bool evaluate (const QPair< QString, ControlNet * > *) const
bool evaluate (const ControlPoint *point) const
bool evaluate (const ControlMeasure *measure) const
bool hasFilter (bool(AbstractFilter::*)() const) const
FilterWidget & operator= (FilterWidget other)
Detailed Description
This widget contains filtering capabilities for a single filter type.
The filter types are (strings containing exactly): Connections Images and Points Points and Measures
This class does the visualization and editing of the filter groups. An interface is provided for evaluating all of the contained filters.
Author
????-??-?? Eric Hyer
Constructor & Destructor Documentation
FilterWidget() [1/2]
Isis::FilterWidget::FilterWidget (QString type) explicit
FilterWidget() [2/2]
Isis::FilterWidget::FilterWidget (const FilterWidget & other)
~FilterWidget()
Isis::FilterWidget::~FilterWidget () virtual
Member Function Documentation
evaluate() [1/4]
bool Isis::FilterWidget::evaluate (const ControlMeasure * measure) const
References Isis::AbstractFilter::canFilterMeasures(), and evaluate().
evaluate() [2/4]
bool Isis::FilterWidget::evaluate (const ControlPoint * point) const
References Isis::AbstractFilter::canFilterPoints(), and evaluate().
evaluate() [3/4]
bool Isis::FilterWidget::evaluate (const QPair< QString, ControlNet * > * imageAndNet) const
References Isis::AbstractFilter::canFilterImages(), and evaluate().
evaluate() [4/4]
template<typename T > bool Isis::FilterWidget::evaluate (const T * t, bool(AbstractFilter::*)() const meth) const inline
References hasFilter().
Referenced by evaluate().
filterChanged
void Isis::FilterWidget::filterChanged () signal
hasFilter()
bool Isis::FilterWidget::hasFilter (bool(AbstractFilter::*)() const meth) const
Referenced by evaluate().
operator=()
FilterWidget & Isis::FilterWidget::operator= (FilterWidget other)
References _FILEINFO_, and Isis::IException::Programmer.
scrollToBottom
void Isis::FilterWidget::scrollToBottom () signal
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/FilterWidget.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/FilterWidget.cpp