Isis Developer Reference: Isis::ControlPointEdit Class Reference
Isis::ControlPointEdit Class Reference
Point Editor Widget.
#include <ControlPointEdit.h>
Public Slots
void setLeftMeasure (ControlMeasure *leftMeasure, Cube *leftCube, QString pointId)
Set the measure displayed in the left ChipViewport.
void setRightMeasure (ControlMeasure *rightMeasure, Cube *rightCube, QString pointId)
Set the measure displayed in the right ChipViewport.
void colorizeSaveButton ()
Turn "Save Measure" button text to red.
void refreshChips ()
void saveChips ()
Slot to save registration chips to files and fire off qview.
Signals
void updateLeftView (double sample, double line)
void updateRightView (double sample, double line)
void measureSaved ()
void newControlNetwork (ControlNet *)
void stretchChipViewport (Stretch *, CubeViewport *)
Public Member Functions
ControlPointEdit (ControlNet *cnet, QWidget *parent=0, bool allowLeftMouse=false, bool useGeometry=true)
Constructs a ControlPointEdit widget.
~ControlPointEdit ()
QString templateFileName ()
bool setTemplateFile (QString)
Allows user to choose a new template file by opening a window from which to select a filename.
void allowLeftMouse (bool allowMouse)
Set the option that allows mouse movements in the left ChipViewport.
Detailed Description
Point Editor Widget.
Author
2008-09-09 Tracie Sucharski
Constructor & Destructor Documentation
ControlPointEdit()
Isis::ControlPointEdit::ControlPointEdit (ControlNet * cnet, QWidget * parent = 0, bool allowLeftMouse = false, bool useGeometry = true)
Constructs a ControlPointEdit widget.
Parameters
parent Input Parent of widget
allowLeftMouse Input Allow/Disallow mouse events on Left ChipViewport
Author
Tracie Sucharski
References allowLeftMouse(), and newControlNetwork().
~ControlPointEdit()
Isis::ControlPointEdit::~ControlPointEdit ()
Member Function Documentation
allowLeftMouse()
void Isis::ControlPointEdit::allowLeftMouse (bool allowMouse)
Set the option that allows mouse movements in the left ChipViewport.
Author
Tracie Sucharski
Referenced by ControlPointEdit().
colorizeSaveButton
void Isis::ControlPointEdit::colorizeSaveButton () slot
Turn "Save Measure" button text to red.
Author
2011-06-14 Tracie Sucharski
measureSaved
void Isis::ControlPointEdit::measureSaved () signal
newControlNetwork
void Isis::ControlPointEdit::newControlNetwork (ControlNet *) signal
Referenced by ControlPointEdit().
refreshChips
void Isis::ControlPointEdit::refreshChips () slot
saveChips
void Isis::ControlPointEdit::saveChips () slot
Slot to save registration chips to files and fire off qview.
Author
2009-03-18 Tracie Sucharski
References Isis::AutoReg::FitChip(), Isis::ControlMeasure::GetLine(), Isis::ControlMeasure::GetSample(), Isis::AutoReg::RegistrationPatternChip(), Isis::AutoReg::RegistrationSearchChip(), Isis::ProgramLauncher::RunSystemCommand(), Isis::toString(), and Isis::Chip::Write().
setLeftMeasure
void Isis::ControlPointEdit::setLeftMeasure (ControlMeasure * leftMeasure, Cube * leftCube, QString pointId) slot
Set the measure displayed in the left ChipViewport.
Parameters
leftMeasure Input Measure displayed in left ChipViewport
leftCube Input Cube of measure displayed in left ChipViewport
Author
Tracie Sucharski
References Isis::ControlMeasure::GetLine(), Isis::ControlMeasure::GetSample(), Isis::Chip::Load(), Isis::ChipViewport::setChip(), and Isis::Chip::TackCube().
setRightMeasure
void Isis::ControlPointEdit::setRightMeasure (ControlMeasure * rightMeasure, Cube * rightCube, QString pointId) slot
Set the measure displayed in the right ChipViewport.
Parameters
rightMeasure Input Measure displayed in right ChipViewport
rightCube Input Cube of measure displayed in right ChipViewport
Author
Tracie Sucharski
References _FILEINFO_, Isis::ControlMeasure::GetLine(), Isis::ControlMeasure::GetSample(), Isis::Chip::Load(), Isis::ChipViewport::setChip(), Isis::Chip::TackCube(), Isis::IException::toString(), and Isis::IException::User.
setTemplateFile()
bool Isis::ControlPointEdit::setTemplateFile (QString fn)
Allows user to choose a new template file by opening a window from which to select a filename.
This file is then registered and set as the new template.
Author
Tracie Sucharski
References _FILEINFO_, Isis::AutoRegFactory::Create(), Isis::IException::Io, and Isis::IException::toString().
stretchChipViewport
void Isis::ControlPointEdit::stretchChipViewport (Stretch * , CubeViewport *) signal
templateFileName()
QString Isis::ControlPointEdit::templateFileName () inline
Referenced by Isis::MatchTool::deletePoint(), and Isis::MatchTool::modifyPoint().
updateLeftView
void Isis::ControlPointEdit::updateLeftView (double sample, double line) signal
updateRightView
void Isis::ControlPointEdit::updateRightView (double sample, double line) signal
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ControlPointEdit/ControlPointEdit.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ControlPointEdit/ControlPointEdit.cpp