Isis Developer Reference: Isis::StretchTool Class Reference
Isis::StretchTool Class Reference
Stretch image edit tool.
#include <StretchTool.h>
Public Types
enum StretchBand {
Gray , Red , Green , Blue ,
All
}
Enum to store the bands.
Public Slots
void stretchGlobal ()
Does a global stretch for the active viewport.
void stretchGlobal (CubeViewport *)
Does a global stretch for the specified viewport.
void stretchGlobalAllBands ()
This resets the stretch across all bands.
void stretchGlobalAllViewports ()
Does a global stretch for all the viewports.
void stretchRegional ()
Does a regional stretch for the active viewport.
void stretchRegional (CubeViewport *)
Does a regional stretch for the specified viewport.
void activate (bool)
Activates the tool.
void setCubeViewport (MdiCubeViewport *cvp)
Sets the current viewport to the given cvp.
Signals
void stretchChipViewport (Stretch *, CubeViewport *)
when a viewport is stretched, send the stretch and the viewport associated with it to any ChipViewport's that might be listening
void warningSignal (std::string &pStr, const std::string pExStr)
Shows a warning.
void clearWarningSignal ()
void toolActivated ()
void viewportChanged ()
Public Member Functions
StretchTool (QWidget *parent)
StretchTool constructor.
~StretchTool ()
Destructor.
void addTo (QMenu *menu)
Adds the stretch action to the given menu.
void updateAdvStretchDialogforAll (void)
Update the streches and corresponding histograms for all the colors Red, Green and Blue for Stretch All Mode.
QString menuName () const
This let's Tool know which Menu the actions this class has should be added to.
void addTo (ViewportMainWindow *mw)
Adds the tool to the application.
void addTo (ToolPad *toolpad)
Adds the tool to the toolpad.
virtual void addTo (Workspace *ws)
Adds the given workspace to the cubeviewport list.
virtual void addToPermanent (QToolBar *toolbar)
void addToActive (QToolBar *toolbar)
QString toolIconDir () const
returns the path to the icon directory.
virtual void paintViewport (MdiCubeViewport *vp, QPainter *painter)
RubberBandTool * rubberBandTool ()
void setList (ToolList *currentList)
Static Public Member Functions
static Stretch stretchBuffer (ViewportBuffer *buffer, QRect rect)
This method computes the stretch over a region using the viewport buffer.
static Stretch stretchBand (CubeViewport *cvp, StretchBand band)
This method computes the stretch over the entire cube.
static Statistics statsFromCube (Cube *cube, int band)
This method will calculate and return the statistics for a given cube and band.
static Statistics statsFromBuffer (ViewportBuffer *buffer, QRect rect)
This method will calculate and return the statistics for a given region and viewport buffer.
static Histogram histFromCube (Cube *cube, int band, double min, double max)
This method will calculate and return the histogram for a given cube and band.
static Histogram histFromBuffer (ViewportBuffer *buffer)
Given a viewport buffer, this calculates a histogram.
static Histogram histFromBuffer (ViewportBuffer *buffer, QRect rect, double min, double max)
This method will calculate and return the histogram for a given region and viewport buffer.
Protected Types
typedef QVector< MdiCubeViewport * > CubeViewportList
A list of cubeviewports.
Protected Slots
void mouseButtonRelease (QPoint p, Qt::MouseButton s)
This method will call a global stretch if the right mouse button is released.
void saveStretchToCube ()
Saves a strech to the cube.
void deleteFromCube ()
Deletes a saved stretch from the cube.
void loadStretchFromCube ()
Restores a saved stretch from the cube.
void enableRubberBandTool ()
This method enables the RubberBandTool.
void screenPixelsChanged ()
This is called when the visible area changes.
void updateHistograms ()
This updates the visible histograms in the advanced stretch, if present.
void rubberBandComplete ()
This method is called when the RubberBandTool is complete.
void setCubeViewport (CubeViewport *)
This updates the advanced stretch to use the given viewport.
virtual void mouseEnter ()
virtual void mouseMove (QPoint p)
virtual void mouseMove (QPoint p, Qt::MouseButton)
virtual void mouseLeave ()
Protected Member Functions
QAction * toolPadAction (ToolPad *pad)
Adds the stretch action to the toolpad.
QWidget * createToolBarWidget (QStackedWidget *parent)
Creates the widget to add to the tool bar.
void updateTool ()
Updates the stretch tool.
void stretchRequested (MdiCubeViewport *cvp, int bandId)
The cube viewport requested a stretch at this time, give it to the viewport.
virtual void mouseDoubleClick (QPoint p)
virtual void mouseButtonPress (QPoint p, Qt::MouseButton s)
virtual void updateMeasure ()
virtual void scaleChanged ()
void registerTool (MdiCubeViewport *viewport)
Registers the tool to the viewport.
MdiCubeViewport * cubeViewport () const
Return the current cubeviewport.
CubeViewportList * cubeViewportList () const
Return the list of cubeviewports.
virtual void addConnections (MdiCubeViewport *cvp)
Anytime a tool is created, you must add the connections for it.
virtual void removeConnections (MdiCubeViewport *cvp)
Anytime a tool is created, you must be able to remove it's connections.
Workspace * workspace ()
Detailed Description
Stretch image edit tool.
This tool is part of the Qisis namespace and allows interactive editing of displayed images.
Author
????-??-?? Unknown
Member Typedef Documentation
CubeViewportList
typedef QVector< MdiCubeViewport * > Isis::Tool::CubeViewportList protected inherited
A list of cubeviewports.
Member Enumeration Documentation
StretchBand
enum Isis::StretchTool::StretchBand
Enum to store the bands.
Enumerator
Gray
Gray Band.
Red
Red Band.
Green
Green Band.
Blue
Blue Band.
All
All Bands.
Constructor & Destructor Documentation
StretchTool()
Isis::StretchTool::StretchTool (QWidget * parent)
StretchTool constructor.
Parameters
parent
References deleteFromCube(), loadStretchFromCube(), saveStretchToCube(), stretchGlobal(), stretchRegional(), updateTool(), and warningSignal().
~StretchTool()
Isis::StretchTool::~StretchTool ()
Destructor.
Member Function Documentation
activate
void Isis::Tool::activate (bool on) slot inherited
Activates the tool.
Parameters
on
References Isis::Tool::clearWarningSignal(), and Isis::Tool::toolActivated().
Referenced by Isis::Tool::addTo(), Isis::AdvancedTrackTool::AdvancedTrackTool(), Isis::RubberBandTool::disable(), Isis::RubberBandTool::enable(), Isis::AdvancedTrackTool::eventFilter(), Isis::FileTool::FileTool(), Isis::RubberBandTool::RubberBandTool(), Isis::TrackTool::TrackTool(), Isis::WindowTool::WindowTool(), and Isis::Workspace::Workspace().
addConnections()
virtual void Isis::Tool::addConnections (MdiCubeViewport * cvp) inline protected virtual inherited
Anytime a tool is created, you must add the connections for it.
Parameters
cvp
Reimplemented in Isis::WindowTool, and Isis::TrackTool.
addTo() [1/4]
void Isis::StretchTool::addTo (QMenu * menu) virtual
Adds the stretch action to the given menu.
Parameters
menu
Reimplemented from Isis::Tool.
addTo() [2/4]
void Isis::Tool::addTo (ToolPad * toolpad) inherited
Adds the tool to the toolpad.
Parameters
toolpad
References Isis::Tool::activate(), Isis::ToolPad::addAction(), and Isis::Tool::toolPadAction().
addTo() [3/4]
void Isis::Tool::addTo (ViewportMainWindow * pViewPortMnWin) inherited
Adds the tool to the application.
Parameters
pViewPortMnWin
References Isis::ViewportMainWindow::activeToolBar(), Isis::Tool::addToActive(), Isis::Tool::addToPermanent(), Isis::ViewportMainWindow::getMenu(), Isis::Tool::menuName(), Isis::ViewportMainWindow::permanentToolBar(), Isis::ViewportMainWindow::toolPad(), and Isis::ViewportMainWindow::workspace().
Referenced by Isis::EditTool::addTo(), Isis::FileTool::addTo(), Isis::SpecialPixelTool::addTo(), Isis::WindowTool::addTo(), Isis::ViewportMainWindow::ViewportMainWindow(), and Isis::Workspace::Workspace().
addTo() [4/4]
void Isis::Tool::addTo (Workspace * ws) virtual inherited
Adds the given workspace to the cubeviewport list.
Parameters
ws
Reimplemented in Isis::WindowTool, Isis::SpecialPixelTool, Isis::FileTool, and Isis::EditTool.
References Isis::Tool::registerTool(), and Isis::Tool::setCubeViewport().
addToActive()
void Isis::Tool::addToActive (QToolBar * toolbar) inherited
Parameters
toolbar
References Isis::Tool::createToolBarWidget(), and Isis::ToolList::toolBarStack().
Referenced by Isis::Tool::addTo(), and Isis::Workspace::Workspace().
addToPermanent()
virtual void Isis::Tool::addToPermanent (QToolBar * toolbar) inline virtual inherited
Parameters
toolbar
Reimplemented in Isis::WindowTool, Isis::SpecialPixelTool, Isis::HelpTool, Isis::FileTool, Isis::BlinkTool, and Isis::AdvancedTrackTool.
Referenced by Isis::Tool::addTo(), and Isis::Workspace::Workspace().
clearWarningSignal
void Isis::Tool::clearWarningSignal () signal inherited
Referenced by Isis::Tool::activate(), Isis::Tool::mouseButtonPress(), Isis::Tool::mouseButtonRelease(), and Isis::Tool::mouseDoubleClick().
createToolBarWidget()
QWidget * Isis::StretchTool::createToolBarWidget (QStackedWidget * parent) protected virtual
Creates the widget to add to the tool bar.
Parameters
parent
Returns
QWidget*
Reimplemented from Isis::Tool.
References All, Blue, deleteFromCube(), Green, loadStretchFromCube(), Red, saveStretchToCube(), stretchGlobal(), stretchGlobalAllBands(), stretchGlobalAllViewports(), stretchRegional(), and Isis::Tool::toolIconDir().
cubeViewport()
MdiCubeViewport* Isis::Tool::cubeViewport () const inline protected inherited
Return the current cubeviewport.
Returns
CubeViewport*
Referenced by Isis::TrackTool::addConnections(), Isis::WindowTool::addConnections(), deleteFromCube(), Isis::FileTool::discard(), Isis::FileTool::exportToList(), Isis::FileTool::exportView(), loadStretchFromCube(), Isis::SunShadowTool::mouseButtonPress(), Isis::EditTool::mouseButtonRelease(), Isis::ControlNetTool::mouseButtonRelease(), Isis::FeatureNomenclatureTool::mouseButtonRelease(), Isis::FindTool::mouseButtonRelease(), Isis::MatchTool::mouseButtonRelease(), Isis::PanTool::mouseButtonRelease(), Isis::QnetTool::mouseButtonRelease(), Isis::RubberBandTool::mouseButtonRelease(), mouseButtonRelease(), Isis::AdvancedTrackTool::mouseLeave(), Isis::SunShadowTool::mouseMove(), Isis::TrackTool::mouseMove(), Isis::RubberBandTool::mouseMove(), Isis::ScatterPlotTool::mouseMove(), Isis::LatLonGridTool::paintViewport(), Isis::FindTool::paintViewport(), Isis::RubberBandTool::paintViewport(), Isis::SunShadowTool::paintViewport(), Isis::FileTool::print(), Isis::HistogramTool::refreshPlot(), Isis::SpatialPlotTool::refreshPlot(), Isis::SpectralPlotTool::refreshPlot(), Isis::TrackTool::removeConnections(), Isis::WindowTool::removeConnections(), Isis::EditTool::rubberBandComplete(), Isis::HistogramTool::rubberBandComplete(), Isis::MeasureTool::rubberBandComplete(), Isis::StereoTool::rubberBandComplete(), rubberBandComplete(), Isis::ZoomTool::rubberBandComplete(), Isis::FileTool::save(), Isis::FileTool::saveAs(), Isis::FileTool::saveAsCubeByOption(), Isis::FileTool::saveInfo(), saveStretchToCube(), Isis::ScatterPlotTool::showNewScatterPlotConfig(), stretchGlobal(), stretchGlobalAllBands(), stretchRegional(), updateAdvStretchDialogforAll(), updateHistograms(), Isis::MeasureTool::updateMeasure(), Isis::AbstractPlotTool::updateTool(), Isis::BandTool::updateTool(), Isis::BlinkTool::updateTool(), Isis::EditTool::updateTool(), Isis::FileTool::updateTool(), Isis::FindTool::updateTool(), Isis::LatLonGridTool::updateTool(), Isis::SpecialPixelTool::updateTool(), updateTool(), Isis::SunShadowTool::updateTool(), Isis::WindowTool::updateTool(), Isis::ZoomTool::updateTool(), and Isis::AbstractPlotTool::viewportsToPlot().
cubeViewportList()
Tool::CubeViewportList * Isis::Tool::cubeViewportList () const protected inherited
Return the list of cubeviewports.
Returns
CubeViewportList*
References Isis::Workspace::cubeViewportList().
Referenced by Isis::FileTool::closeAll(), Isis::MatchTool::createPoint(), Isis::BlinkTool::eventFilter(), Isis::PanTool::mouseButtonRelease(), Isis::RubberBandTool::mouseButtonRelease(), Isis::RubberBandTool::mouseMove(), Isis::ScatterPlotTool::repaintViewports(), Isis::AbstractPlotTool::repaintViewports(), Isis::ZoomTool::rubberBandComplete(), Isis::ControlNetTool::setControlNet(), Isis::FeatureNomenclatureTool::setFontColor(), Isis::FeatureNomenclatureTool::setFontSize(), Isis::FeatureNomenclatureTool::setShowApprovedOnly(), Isis::FeatureNomenclatureTool::setVectorType(), stretchGlobalAllViewports(), Isis::MeasureTool::updateMeasure(), Isis::BlinkTool::updateTool(), Isis::FindTool::updateTool(), Isis::WindowTool::updateTool(), and Isis::AbstractPlotTool::viewportsToPlot().
deleteFromCube
void Isis::StretchTool::deleteFromCube () protected slot
Deletes a saved stretch from the cube.
References Isis::PvlObject::beginObject(), Isis::CubeViewport::cube(), Isis::Tool::cubeViewport(), Isis::Cube::deleteBlob(), Isis::CubeViewport::grayBand(), Isis::Cube::isReadOnly(), Isis::Cube::label(), and Isis::Cube::reopen().
Referenced by createToolBarWidget(), and StretchTool().
enableRubberBandTool
void Isis::StretchTool::enableRubberBandTool () protected slot
This method enables the RubberBandTool.
References Isis::RubberBandTool::enable(), Isis::RubberBandTool::RectangleMode, Isis::Tool::rubberBandTool(), and Isis::RubberBandTool::setDrawActiveViewportOnly().
Referenced by mouseButtonRelease().
histFromBuffer() [1/2]
Histogram Isis::StretchTool::histFromBuffer (ViewportBuffer * buffer) static
Given a viewport buffer, this calculates a histogram.
Parameters
buffer
Returns
Histogram
References Isis::Statistics::BestMaximum(), Isis::Statistics::BestMinimum(), Isis::ViewportBuffer::bufferXYRect(), and statsFromBuffer().
Referenced by setCubeViewport(), stretchBuffer(), updateAdvStretchDialogforAll(), and updateHistograms().
histFromBuffer() [2/2]
Histogram Isis::StretchTool::histFromBuffer (ViewportBuffer * buffer, QRect rect, double min, double max) static
This method will calculate and return the histogram for a given region and viewport buffer.
Parameters
buffer
rect
min
max
Returns
Histogram
References _FILEINFO_, Isis::Histogram::AddData(), Isis::ViewportBuffer::bufferXYRect(), Isis::ViewportBuffer::getLine(), and Isis::IException::Unknown.
histFromCube()
Histogram Isis::StretchTool::histFromCube (Cube * cube, int band, double min, double max) static
This method will calculate and return the histogram for a given cube and band.
Parameters
cube
band
min
max
Returns
Histogram
References Isis::Histogram::AddData(), Isis::Buffer::DoubleBuffer(), Isis::Cube::lineCount(), Isis::Cube::pixelType(), Isis::Cube::read(), Isis::Cube::sampleCount(), and Isis::Brick::SetBasePosition().
Referenced by stretchBand().
loadStretchFromCube
void Isis::StretchTool::loadStretchFromCube () protected slot
Restores a saved stretch from the cube.
References Isis::PvlObject::beginObject(), Isis::CubeViewport::blueBand(), Isis::CubeViewport::blueStretch(), Isis::Stretch::CopyPairs(), Isis::CubeViewport::cube(), Isis::Tool::cubeViewport(), Isis::CubeViewport::grayBand(), Isis::CubeViewport::grayStretch(), Isis::CubeViewport::greenBand(), Isis::CubeViewport::greenStretch(), Isis::CubeViewport::isGray(), Isis::Cube::label(), Isis::Cube::readCubeStretch(), Isis::CubeViewport::redBand(), Isis::CubeViewport::redStretch(), Isis::AdvancedStretchDialog::restoreGrayStretch(), Isis::AdvancedStretchDialog::restoreRgbStretch(), Isis::CubeViewport::stretchBlue(), Isis::CubeViewport::stretchGray(), Isis::CubeViewport::stretchGreen(), and Isis::CubeViewport::stretchRed().
Referenced by createToolBarWidget(), and StretchTool().
menuName()
QString Isis::StretchTool::menuName () const inline virtual
This let's Tool know which Menu the actions this class has should be added to.
Removal of this results in "Ctrl+R" and "Ctrl+G" not working.
Returns
Name of the Menu
Reimplemented from Isis::Tool.
mouseButtonPress()
void Isis::Tool::mouseButtonPress (QPoint p, Qt::MouseButton s) protected virtual inherited
Parameters
p
s
References Isis::Tool::clearWarningSignal().
mouseButtonRelease
void Isis::StretchTool::mouseButtonRelease (QPoint start, Qt::MouseButton s) protected slot
This method will call a global stretch if the right mouse button is released.
Parameters
start
s
References Isis::Tool::cubeViewport(), enableRubberBandTool(), Isis::Tool::mouseButtonRelease(), stretchChipViewport(), and stretchGlobal().
mouseDoubleClick()
void Isis::Tool::mouseDoubleClick (QPoint p) protected virtual inherited
Parameters
p
References Isis::Tool::clearWarningSignal().
mouseEnter
virtual void Isis::Tool::mouseEnter () inline protected virtual slot inherited
mouseLeave
virtual void Isis::Tool::mouseLeave () inline protected virtual slot inherited
mouseMove [1/2]
void Isis::Tool::mouseMove (QPoint p) protected virtual slot inherited
Parameters
p
mouseMove [2/2]
virtual void Isis::Tool::mouseMove (QPoint p, Qt::MouseButton) inline protected virtual slot inherited
paintViewport()
virtual void Isis::Tool::paintViewport (MdiCubeViewport * vp, QPainter * painter) inline virtual inherited
Parameters
vp
painter
Reimplemented in Isis::SunShadowTool, Isis::ScatterPlotTool, Isis::RubberBandTool, Isis::FindTool, Isis::FeatureNomenclatureTool, Isis::AbstractPlotTool, Isis::MatchTool, Isis::LatLonGridTool, Isis::StereoTool, Isis::QnetTool, and Isis::ControlNetTool.
registerTool()
void Isis::Tool::registerTool (MdiCubeViewport * viewport) protected inherited
Registers the tool to the viewport.
Parameters
viewport
References Isis::MdiCubeViewport::registerTool(), and Isis::Tool::stretchRequested().
Referenced by Isis::Tool::addTo().
removeConnections()
virtual void Isis::Tool::removeConnections (MdiCubeViewport * cvp) inline protected virtual inherited
Anytime a tool is created, you must be able to remove it's connections.
Parameters
cvp
Reimplemented in Isis::WindowTool, Isis::TrackTool, and Isis::MeasureTool.
rubberBandComplete
void Isis::StretchTool::rubberBandComplete () protected slot
This method is called when the RubberBandTool is complete.
It will get a rectangle from the RubberBandTool and stretch accordingly.
References Isis::Tool::cubeViewport(), Isis::RubberBandTool::rectangle(), and Isis::Tool::rubberBandTool().
rubberBandTool()
RubberBandTool * Isis::Tool::rubberBandTool () inherited
References Isis::ToolList::rubberBandTool().
Referenced by Isis::MeasureTool::createToolBarWidget(), Isis::EditTool::enableRubberBandTool(), Isis::HistogramTool::enableRubberBandTool(), Isis::MeasureTool::enableRubberBandTool(), Isis::SpatialPlotTool::enableRubberBandTool(), Isis::SpectralPlotTool::enableRubberBandTool(), Isis::StereoTool::enableRubberBandTool(), enableRubberBandTool(), Isis::Tool::enableRubberBandTool(), Isis::ZoomTool::enableRubberBandTool(), Isis::HistogramTool::refreshPlot(), Isis::SpatialPlotTool::refreshPlot(), Isis::SpectralPlotTool::refreshPlot(), Isis::RubberBandComboBox::RubberBandComboBox(), Isis::EditTool::rubberBandComplete(), Isis::HistogramTool::rubberBandComplete(), Isis::MeasureTool::rubberBandComplete(), Isis::SpatialPlotTool::rubberBandComplete(), Isis::SpectralPlotTool::rubberBandComplete(), Isis::StereoTool::rubberBandComplete(), rubberBandComplete(), Isis::ZoomTool::rubberBandComplete(), and Isis::RubberBandComboBox::selectionChanged().
saveStretchToCube
void Isis::StretchTool::saveStretchToCube () protected slot
Saves a strech to the cube.
References Isis::PvlObject::beginObject(), Isis::CubeViewport::blueBand(), Isis::CubeViewport::blueStretch(), Isis::CubeViewport::cube(), Isis::Tool::cubeViewport(), Isis::AdvancedStretchDialog::getBluStretch(), Isis::AdvancedStretchDialog::getGrayStretch(), Isis::AdvancedStretchDialog::getGrnStretch(), Isis::AdvancedStretchDialog::getRedStretch(), Isis::CubeViewport::grayBand(), Isis::CubeViewport::grayStretch(), Isis::CubeViewport::greenBand(), Isis::CubeViewport::greenStretch(), Isis::CubeViewport::isGray(), Isis::Cube::isReadOnly(), Isis::Cube::label(), Isis::CubeViewport::redBand(), Isis::CubeViewport::redStretch(), Isis::Cube::reopen(), Isis::CubeStretch::setBandNumber(), Isis::CubeStretch::setName(), Isis::CubeStretch::toBlob(), and Isis::Cube::write().
Referenced by createToolBarWidget(), and StretchTool().
scaleChanged()
virtual void Isis::Tool::scaleChanged () inline protected virtual inherited
Reimplemented in Isis::RubberBandTool.
screenPixelsChanged
void Isis::StretchTool::screenPixelsChanged () protected slot
This is called when the visible area changes.
References updateHistograms().
Referenced by stretchRequested().
setCubeViewport [1/2]
void Isis::StretchTool::setCubeViewport (CubeViewport * cvp) protected slot
This updates the advanced stretch to use the given viewport.
Parameters
cvp
References Isis::CubeViewport::blueBuffer(), Isis::CubeViewport::blueStretch(), Isis::AdvancedStretchDialog::enable(), Isis::AdvancedStretchDialog::enableGrayMode(), Isis::AdvancedStretchDialog::enableRgbMode(), Isis::CubeViewport::grayBuffer(), Isis::CubeViewport::grayStretch(), Isis::CubeViewport::greenBuffer(), Isis::CubeViewport::greenStretch(), histFromBuffer(), Isis::CubeViewport::isGray(), Isis::CubeViewport::redBuffer(), Isis::CubeViewport::redStretch(), and Isis::ViewportBuffer::working().
Referenced by updateTool().
setCubeViewport [2/2]
void Isis::Tool::setCubeViewport (MdiCubeViewport * cvp) slot inherited
Sets the current viewport to the given cvp.
Parameters
cvp
References Isis::Tool::updateTool(), and Isis::Tool::viewportChanged().
Referenced by Isis::Tool::addTo(), and Isis::FileTool::closeAll().
setList()
void Isis::Tool::setList (ToolList * currentList) inherited
Referenced by Isis::ToolList::append().
statsFromBuffer()
Statistics Isis::StretchTool::statsFromBuffer (ViewportBuffer * buffer, QRect rect) static
This method will calculate and return the statistics for a given region and viewport buffer.
Parameters
buffer
rect
Returns
Statistics
References _FILEINFO_, Isis::Statistics::AddData(), Isis::ViewportBuffer::bufferXYRect(), Isis::ViewportBuffer::getLine(), Isis::IException::User, and Isis::ViewportBuffer::working().
Referenced by histFromBuffer(), and stretchBuffer().
statsFromCube()
Statistics Isis::StretchTool::statsFromCube (Cube * cube, int band) static
This method will calculate and return the statistics for a given cube and band.
Parameters
cube
band
Returns
Statistics
References Isis::Statistics::AddData(), Isis::Buffer::DoubleBuffer(), Isis::Cube::lineCount(), Isis::Cube::pixelType(), Isis::Cube::read(), Isis::Cube::sampleCount(), and Isis::Brick::SetBasePosition().
Referenced by stretchBand().
stretchBand()
Stretch Isis::StretchTool::stretchBand (CubeViewport * cvp, StretchBand band) static
This method computes the stretch over the entire cube.
Parameters
cvp
band Band to stretch
References Isis::Stretch::AddPair(), Isis::Statistics::BestMaximum(), Isis::Statistics::BestMinimum(), Blue, Isis::CubeViewport::blueBand(), Isis::CubeViewport::blueStretch(), Isis::Stretch::ClearPairs(), Isis::CubeViewport::cube(), Isis::CubeViewport::grayBand(), Isis::CubeViewport::grayStretch(), Green, Isis::CubeViewport::greenBand(), Isis::CubeViewport::greenStretch(), histFromCube(), Isis::Histogram::Percent(), Red, Isis::CubeViewport::redBand(), Isis::CubeViewport::redStretch(), and statsFromCube().
Referenced by Isis::IndependentCubeViewport::restretch(), and stretchRequested().
stretchBuffer()
Stretch Isis::StretchTool::stretchBuffer (ViewportBuffer * buffer, QRect rect) static
This method computes the stretch over a region using the viewport buffer.
Parameters
buffer
rect
References Isis::Stretch::AddPair(), Isis::Statistics::BestMaximum(), Isis::Statistics::BestMinimum(), histFromBuffer(), Isis::Statistics::Maximum(), Isis::Statistics::Minimum(), Isis::Stretch::Pairs(), Isis::Histogram::Percent(), statsFromBuffer(), and Isis::Statistics::ValidPixels().
Referenced by stretchRequested().
stretchChipViewport
void Isis::StretchTool::stretchChipViewport (Stretch * , CubeViewport *) signal
when a viewport is stretched, send the stretch and the viewport associated with it to any ChipViewport's that might be listening
Referenced by mouseButtonRelease().
stretchGlobal [1/2]
void Isis::StretchTool::stretchGlobal () slot
Does a global stretch for the active viewport.
References Isis::Tool::cubeViewport().
Referenced by createToolBarWidget(), mouseButtonRelease(), stretchGlobalAllBands(), stretchGlobalAllViewports(), and StretchTool().
stretchGlobal [2/2]
void Isis::StretchTool::stretchGlobal (CubeViewport * cvp) slot
Does a global stretch for the specified viewport.
References Isis::CubeViewport::stretchKnownGlobal().
stretchGlobalAllBands
void Isis::StretchTool::stretchGlobalAllBands () slot
This resets the stretch across all bands.
References Isis::Tool::cubeViewport(), Isis::CubeViewport::forgetStretches(), and stretchGlobal().
Referenced by createToolBarWidget().
stretchGlobalAllViewports
void Isis::StretchTool::stretchGlobalAllViewports () slot
Does a global stretch for all the viewports.
References Isis::Tool::cubeViewportList(), and stretchGlobal().
Referenced by createToolBarWidget().
stretchRegional [1/2]
void Isis::StretchTool::stretchRegional () slot
Does a regional stretch for the active viewport.
References Isis::Tool::cubeViewport().
Referenced by createToolBarWidget(), and StretchTool().
stretchRegional [2/2]
void Isis::StretchTool::stretchRegional (CubeViewport * cvp) slot
Does a regional stretch for the specified viewport.
stretchRequested()
void Isis::StretchTool::stretchRequested (MdiCubeViewport * cvp, int bandId) protected virtual
The cube viewport requested a stretch at this time, give it to the viewport.
Parameters
cvp
bandId
Reimplemented from Isis::Tool.
References All, Blue, Isis::CubeViewport::blueBuffer(), Isis::CubeViewport::blueStretch(), Isis::Stretch::CopyPairs(), Gray, Isis::CubeViewport::grayBuffer(), Isis::CubeViewport::grayStretch(), Green, Isis::CubeViewport::greenBuffer(), Isis::CubeViewport::greenStretch(), Isis::ViewportBuffer::hasEntireCube(), Red, Isis::CubeViewport::redBuffer(), Isis::CubeViewport::redStretch(), screenPixelsChanged(), stretchBand(), Isis::CubeViewport::stretchBlue(), stretchBuffer(), Isis::CubeViewport::stretchGray(), Isis::CubeViewport::stretchGreen(), Isis::CubeViewport::stretchRed(), and updateHistograms().
toolActivated
void Isis::Tool::toolActivated () signal inherited
Referenced by Isis::Tool::activate(), Isis::FeatureNomenclatureTool::FeatureNomenclatureTool(), Isis::MatchTool::MatchTool(), and Isis::StereoTool::StereoTool().
toolIconDir()
QString Isis::Tool::toolIconDir () const inline inherited
returns the path to the icon directory.
Returns
QString
Referenced by Isis::AdvancedTrackTool::AdvancedTrackTool(), Isis::BlinkTool::BlinkTool(), Isis::BandTool::createToolBarWidget(), Isis::EditTool::createToolBarWidget(), Isis::FindTool::createToolBarWidget(), Isis::MatchTool::createToolBarWidget(), Isis::PanTool::createToolBarWidget(), Isis::StereoTool::createToolBarWidget(), createToolBarWidget(), Isis::ZoomTool::createToolBarWidget(), Isis::FileTool::FileTool(), Isis::FindTool::FindTool(), Isis::HelpTool::HelpTool(), Isis::HistogramTool::HistogramTool(), Isis::PanTool::PanTool(), Isis::SpecialPixelTool::SpecialPixelTool(), Isis::RubberBandComboBox::toolIconDir(), Isis::BandTool::toolPadAction(), Isis::ControlNetTool::toolPadAction(), Isis::EditTool::toolPadAction(), Isis::FeatureNomenclatureTool::toolPadAction(), Isis::HistogramTool::toolPadAction(), Isis::LatLonGridTool::toolPadAction(), Isis::MatchTool::toolPadAction(), Isis::MeasureTool::toolPadAction(), Isis::PanTool::toolPadAction(), Isis::QnetTool::toolPadAction(), Isis::ScatterPlotTool::toolPadAction(), Isis::SpatialPlotTool::toolPadAction(), Isis::SpectralPlotTool::toolPadAction(), Isis::StereoTool::toolPadAction(), toolPadAction(), Isis::SunShadowTool::toolPadAction(), Isis::FindTool::toolPadAction(), Isis::StatisticsTool::toolPadAction(), Isis::ZoomTool::toolPadAction(), Isis::WindowTool::WindowTool(), and Isis::ZoomTool::ZoomTool().
toolPadAction()
QAction * Isis::StretchTool::toolPadAction (ToolPad * pad) protected virtual
Adds the stretch action to the toolpad.
Parameters
pad
Returns
QAction*
Reimplemented from Isis::Tool.
References Isis::Tool::toolIconDir().
updateAdvStretchDialogforAll()
void Isis::StretchTool::updateAdvStretchDialogforAll (void)
Update the streches and corresponding histograms for all the colors Red, Green and Blue for Stretch All Mode.
Author
Sharmila Prasad (3/14/2011)
References Isis::CubeViewport::blueBuffer(), Isis::CubeViewport::blueStretch(), Isis::Tool::cubeViewport(), Isis::CubeViewport::greenBuffer(), Isis::CubeViewport::greenStretch(), histFromBuffer(), Isis::CubeViewport::isGray(), Isis::CubeViewport::redBuffer(), Isis::CubeViewport::redStretch(), Isis::AdvancedStretchDialog::updateForRGBMode(), and Isis::ViewportBuffer::working().
updateHistograms
void Isis::StretchTool::updateHistograms () protected slot
This updates the visible histograms in the advanced stretch, if present.
References Isis::CubeViewport::blueBuffer(), Isis::Tool::cubeViewport(), Isis::CubeViewport::grayBuffer(), Isis::CubeViewport::greenBuffer(), histFromBuffer(), Isis::CubeViewport::isGray(), Isis::AdvancedStretchDialog::isRgbMode(), Isis::CubeViewport::redBuffer(), Isis::AdvancedStretchDialog::updateHistogram(), Isis::AdvancedStretchDialog::updateHistograms(), updateTool(), Isis::Statistics::ValidPixels(), and Isis::ViewportBuffer::working().
Referenced by screenPixelsChanged(), stretchRequested(), and updateTool().
updateMeasure()
virtual void Isis::Tool::updateMeasure () inline protected virtual inherited
updateTool()
void Isis::StretchTool::updateTool () protected virtual
Updates the stretch tool.
Reimplemented from Isis::Tool.
References Isis::Tool::cubeViewport(), Isis::AdvancedStretchDialog::enabled(), Isis::CubeViewport::isGray(), Isis::AdvancedStretchDialog::isRgbMode(), setCubeViewport(), and updateHistograms().
Referenced by StretchTool(), and updateHistograms().
viewportChanged
void Isis::Tool::viewportChanged () signal inherited
Referenced by Isis::Tool::setCubeViewport(), Isis::SpatialPlotTool::SpatialPlotTool(), Isis::SpectralPlotTool::SpectralPlotTool(), and Isis::SunShadowTool::SunShadowTool().
warningSignal
void Isis::StretchTool::warningSignal (std::string & pStr, const std::string pExStr) signal
Shows a warning.
This sends a signal (meant for when an exception occurs) to display the error using the warning object
Parameters
pStr
pExStr
Referenced by StretchTool().
workspace()
Workspace * Isis::Tool::workspace () protected inherited
Referenced by Isis::EditTool::addTo(), Isis::ControlNetTool::setControlNet(), and Isis::ScatterPlotTool::showNewScatterPlotConfig().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/StretchTool/StretchTool.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/StretchTool/StretchTool.cpp