Isis Developer Reference: Isis::HistogramWidget Class Reference
Isis::HistogramWidget Class Reference
Histogram widget used by AdvancedStretchTool.
#include <HistogramWidget.h>
Public Member Functions
HistogramWidget (const QString title, const QColor histColor=Qt::gray, const QColor stretchColor=Qt::darkGray)
HistogramWidget constructor.
void setHistogram (const Histogram &hist)
Creates a histogram curve from the given histogram and plots it.
void setStretch (Stretch stretch)
Creates a stretch curbe from the given stretch and plots it.
void clearStretch ()
Clears the stretch curve from the plot.
int heightForWidth (int w) const
Histograms have preferred sizes that keeps them all the same regardless of the contained data.
Detailed Description
Histogram widget used by AdvancedStretchTool.
The HistogramWidget displays a given histogram and stretch in a graph and contains inputs for changing the min/max of the histogram.
Author
2009-05-01 Noah Hilt
Constructor & Destructor Documentation
HistogramWidget()
Isis::HistogramWidget::HistogramWidget (const QString title, const QColor histColor = Qt::gray, const QColor stretchColor = Qt::darkGray)
HistogramWidget constructor.
Initializes all of the widgets and sets the plot title, histogram curve's color and stretch curve's color.
Parameters
title
histColor
stretchColor
References Isis::HistogramItem::setColor().
Member Function Documentation
clearStretch()
void Isis::HistogramWidget::clearStretch ()
Clears the stretch curve from the plot.
heightForWidth()
int Isis::HistogramWidget::heightForWidth (int w) const inline
Histograms have preferred sizes that keeps them all the same regardless of the contained data.
This causes that.
Prefer 1:1
Parameters
w
Returns
int
setHistogram()
void Isis::HistogramWidget::setHistogram (const Histogram & hist)
Creates a histogram curve from the given histogram and plots it.
Parameters
hist
References Isis::Histogram::BinCount(), Isis::Histogram::BinMiddle(), Isis::Histogram::Bins(), Isis::Histogram::BinSize(), Isis::Histogram::MaxBinCount(), Isis::Statistics::Maximum(), Isis::Statistics::Minimum(), and Isis::HistogramItem::setData().
Referenced by Isis::StretchType::setHistogram(), and Isis::StretchType::StretchType().
setStretch()
void Isis::HistogramWidget::setStretch (Stretch stretch)
Creates a stretch curbe from the given stretch and plots it.
Parameters
stretch
References Isis::Stretch::Input(), Isis::Stretch::Output(), and Isis::Stretch::Pairs().
Referenced by Isis::StretchType::updateGraph().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/StretchTool/HistogramWidget.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/StretchTool/HistogramWidget.cpp