Isis Developer Reference: Isis::Displacement Class Reference
Isis::Displacement Class Reference
Utility
Displacement is a signed length, usually in meters.
#include <Displacement.h>
Public Types
enum Units { Meters , Kilometers , Pixels }
This is a list of available units to access and store Distances in.
Public Member Functions
Displacement ()
This initializes the displacement to an invalid state.
Displacement (double displacement, Units distanceUnit)
This is the general purpose constructor for Displacement.
Displacement (double displacementInPixels, double pixelsPerMeter)
This is a constructor for Displacement given pixels with a conversion ratio.
Displacement (const Distance &distanceToCopy)
This creates a displacement equal to a distance.
~Displacement ()
Free the memory allocated by this instance of the displacement class.
double meters () const
Get the displacement in meters.
void setMeters (double displacementInMeters)
Set the displacement in meters.
double kilometers () const
Get the displacement in kilometers.
void setKilometers (double displacementInKilometers)
Set the displacement in kilometers.
double pixels (double pixelsPerMeter=1.0) const
Get the displacement in pixels using the given conversion ratio.
void setPixels (double distanceInPixels, double pixelsPerMeter=1.0)
Set the displacement in pixels.
bool isValid () const
Test if this displacement has been initialized or not.
bool operator> (const Displacement &otherDisplacement) const
Get the displacement in meters.
bool operator< (const Displacement &otherDisplacement) const
Compare two displacements with the less than operator.
bool operator>= (const Displacement &otherDisplacement) const
Compare the distances of 2 displacements with the >= operator.
bool operator<= (const Displacement &otherDisplacement) const
Compare the lengths of 2 displacements with the <= operator.
bool operator!= (const Displacement &otherDisplacement) const
Compare the lengths of 2 displacements with the != operator.
bool operator== (const Displacement &otherDisplacement) const
Compare the lengths of 2 displacements with the == operator.
Displacement operator+ (const Displacement &displacementToAdd) const
Add another displacement to this displacement (1km + 5m = 1005m)
Displacement operator- (const Displacement &displacementToSub) const
Subtract another displacement from this displacement (1km - 5m = 995m).
Displacement operator- (const Distance &distanceToSub) const
Subtract a distance from this displacement (1km - 5m = 995m).
double operator/ (const Displacement &displacementToDiv) const
Divide another displacement into this displacement (5m / 1m = 5).
Displacement operator/ (const double &valueToDiv) const
Divide a value from this displacement (5m / 2 = 2.5m).
Displacement operator* (const double &valueToMult) const
Multiply this displacement by a value (5m * 2 = 10m).
void operator+= (const Displacement &displacementToAdd)
Add and assign the given displacement to ourselves.
void operator-= (const Displacement &displacementToSub)
Subtract the given displacement from ourself and assign.
void operator-= (const Distance &distanceToSub)
Subtract the given distance from ourself and assign.
void operator/= (const double &valueToDiv)
Divide this displacement by a value and assign the result to ourself.
void operator*= (const double &valueToMult)
Multiply this displacement by a value and assign the result to ourself.
Protected Member Functions
double displacement (Units displacementUnit) const
This is a helper method to access displacements in a universal manner with uniform error checking.
void setDisplacement (const double &displacement, Units displacementUnit)
This is a helper method to set displacements in a universal manner with uniform error checking.
Friends
Displacement operator* (double mult, Displacement displacement)
Multiply displacement by a value (5m * 2 = 10m).
Detailed Description
Displacement is a signed length, usually in meters.
This class is designed to encapsulate the concept of a displacement. A displacement has a distance and a sense of direction indicated by a sign (+ or -). It is typically used for vectors or coordinates, but is also available as a general purpose class. This class does accept both positive and negative values.
Author
2010-10-12 Steven Lambright and Debbie A. Cook
Member Enumeration Documentation
Units
enum Isis::Displacement::Units
This is a list of available units to access and store Distances in.
These values can be passed to the constructor to specify which unit the double you are passing in is in.
Enumerator
Meters
The distance is being specified in meters.
Kilometers
The distance is being specified in kilometers.
Pixels
The distance is being specified in pixels.
Constructor & Destructor Documentation
Displacement() [1/4]
Isis::Displacement::Displacement ()
This initializes the displacement to an invalid state.
You must set the displacement later on with operator= or one of the Set methods.
References Meters, Isis::Null, and setDisplacement().
Referenced by operator*(), and operator/().
Displacement() [2/4]
Isis::Displacement::Displacement (double displacement, Units displacementUnit)
This is the general purpose constructor for Displacement.
This will initialize with the given displacement. If Pixels are supplied as the units, then a default pixels/meter = 1.0 will be used.
Parameters
displacement The initial displacement; must be in units of displacementUnit
displacementUnit The unit of displacement; can be any value in displacement::Units
References displacement(), Meters, Pixels, and setDisplacement().
Displacement() [3/4]
Isis::Displacement::Displacement (double displacementInPixels, double pixelsPerMeter)
This is a constructor for Displacement given pixels with a conversion ratio.
This will initialize with the pixels converted to meters.
Parameters
displacementInPixels The displacement to initialize with, must be in units of pixels and should not be negative
pixelsPerMeter The pixels/meter conversion factor
References Meters, and setDisplacement().
Displacement() [4/4]
Isis::Displacement::Displacement (const Distance & distanceToCopy)
This creates a displacement equal to a distance.
Parameters
distanceToCopy This is the distance we are duplicating
References Meters, Isis::Distance::meters(), and setDisplacement().
~Displacement()
Isis::Displacement::~Displacement () inline
Free the memory allocated by this instance of the displacement class.
Member Function Documentation
displacement()
double Isis::Displacement::displacement (Units displacementUnit) const protected
This is a helper method to access displacements in a universal manner with uniform error checking.
Parameters
displacementUnit Unit of the return value. If this is invalid, an exception will be thrown.
Returns
The displacement in units of displacementUnit
References _FILEINFO_, Kilometers, Meters, Isis::Null, Pixels, and Isis::IException::Programmer.
Referenced by Displacement(), isValid(), kilometers(), meters(), pixels(), and setDisplacement().
isValid()
bool Isis::Displacement::isValid () const
Test if this displacement has been initialized or not.
Returns
True if this displacement has been initialized.
References displacement(), Meters, and Isis::Null.
Referenced by Isis::ControlPoint::HasAprioriCoordinates(), operator*(), operator*=(), operator+=(), operator-=(), operator/(), operator/=(), operator<(), operator>(), and Isis::Area3D::setArea().
kilometers()
double Isis::Displacement::kilometers () const
Get the displacement in kilometers.
Returns
Current displacement, in kilometers
References displacement(), and Kilometers.
Referenced by Isis::DemShape::calculateDefaultNormal(), Isis::EllipsoidShape::calculateLocalNormal(), Isis::BundleLidarRangeConstraint::computeRange(), Isis::Sensor::Coordinate(), Isis::SurfacePoint::DisplacementToDouble(), Isis::PlaneShape::emissionAngle(), Isis::BundleControlPoint::formatBundleLatitudinalOutputDetailString(), Isis::BundleControlPoint::formatBundleRectangularOutputDetailString(), Isis::RadarGroundMap::GetXY(), Isis::CameraGroundMap::GetXY(), Isis::PlaneShape::incidenceAngle(), Isis::NaifDskShape::intersectSurface(), Isis::DemShape::intersectSurface(), Isis::Camera::LocalPhotometricAngles(), Isis::PlaneShape::localRadius(), Isis::CameraGroundMap::MeanRadiusPartial(), Isis::CSMCamera::SlantDistance(), Isis::Sensor::SlantDistance(), and Isis::Sensor::SolarDistance().
meters()
double Isis::Displacement::meters () const
Get the displacement in meters.
Returns
Current displacement, in meters.
References displacement(), and Meters.
Referenced by Isis::ControlPointV0001::ControlPointV0001(), Isis::SurfacePoint::DisplacementToDouble(), Isis::AdjustedXFilter::evaluate(), Isis::AdjustedYFilter::evaluate(), Isis::AdjustedZFilter::evaluate(), Isis::APrioriXFilter::evaluate(), Isis::APrioriYFilter::evaluate(), Isis::APrioriZFilter::evaluate(), Isis::AbstractPointItem::getData(), Isis::IsisShape::intersect(), operator*(), operator*=(), operator+=(), operator-=(), operator/(), operator/=(), operator<(), operator>(), Isis::Area3D::setArea(), Isis::Projection::SetUpperLeftCorner(), and Isis::ControlNetVersioner::toPvl().
operator!=()
bool Isis::Displacement::operator!= (const Displacement & otherDisplacement) const inline
Compare the lengths of 2 displacements with the != operator.
Two uninitialized displacements are equal to each other.
Parameters
otherDisplacement This is the displacement we are comparing to, i.e. it is on the right-hand-side of the operator when used
Returns
True if the length of this displacement is not equal to the given displacement
operator*()
Displacement Isis::Displacement::operator* (const double & valueToMult) const
Multiply this displacement by a value (5m * 2 = 10m).
Parameters
valueToMult This is the value to multiply by
Returns
Resulting value
References Displacement(), Isis::IsSpecial(), isValid(), Meters, and meters().
operator*=()
void Isis::Displacement::operator*= (const double & valueToMult)
Multiply this displacement by a value and assign the result to ourself.
Parameters
valueToMult This is the value we are going to multiply by
References Isis::IsSpecial(), isValid(), Meters, meters(), Isis::Null, and setDisplacement().
operator+()
Displacement Isis::Displacement::operator+ (const Displacement & displacementToAdd) const
Add another displacement to this displacement (1km + 5m = 1005m)
Parameters
displacementToAdd This is the displacement we are adding to ourselves
Returns
Resulting displacement, self not modified
operator+=()
void Isis::Displacement::operator+= (const Displacement & displacementToAdd)
Add and assign the given displacement to ourselves.
Parameters
displacementToAdd This is the displacement we are to add
References isValid(), Meters, meters(), Isis::Null, and setDisplacement().
operator-() [1/2]
Displacement Isis::Displacement::operator- (const Displacement & displacementToSub) const
Subtract another displacement from this displacement (1km - 5m = 995m).
Parameters
displacementToSub This is the displacement we are subtracting from ourself
Returns
Resulting displacement, self not modified
operator-() [2/2]
Displacement Isis::Displacement::operator- (const Distance & distanceToSub) const
Subtract a distance from this displacement (1km - 5m = 995m).
Parameters
distanceToSub This is the displacement we are subtracting from ourself
Returns
Resulting displacement, self not modified
operator-=() [1/2]
void Isis::Displacement::operator-= (const Displacement & displacementToSub)
Subtract the given displacement from ourself and assign.
Parameters
displacementToSub This is the displacement we are to subtract
References isValid(), Meters, meters(), Isis::Null, and setDisplacement().
operator-=() [2/2]
void Isis::Displacement::operator-= (const Distance & distanceToSub)
Subtract the given distance from ourself and assign.
Parameters
distanceToSub This is the distance we are to subtract
References isValid(), Isis::Distance::isValid(), Meters, meters(), Isis::Distance::meters(), Isis::Null, and setDisplacement().
operator/() [1/2]
double Isis::Displacement::operator/ (const Displacement & displacementToDiv) const
Divide another displacement into this displacement (5m / 1m = 5).
Parameters
displacementToDiv This is the divisor displacement (denominator)
Returns
Resulting value
References isValid(), meters(), and Isis::Null.
operator/() [2/2]
Displacement Isis::Displacement::operator/ (const double & valueToDiv) const
Divide a value from this displacement (5m / 2 = 2.5m).
Parameters
valueToDiv This is the divisor displacement (denominator)
Returns
Resulting value
References Displacement(), Isis::IsSpecial(), isValid(), Meters, and meters().
operator/=()
void Isis::Displacement::operator/= (const double & valueToDiv)
Divide this displacement by a value and assign the result to ourself.
Parameters
valueToDiv This is the value we are going to divide by
References Isis::IsSpecial(), isValid(), Meters, meters(), Isis::Null, and setDisplacement().
operator<()
bool Isis::Displacement::operator< (const Displacement & otherDisplacement) const
Compare two displacements with the less than operator.
Parameters
otherdisplacement This is the displacement we're comparing to, i.e. on the right-hand-side of the operator when used
Returns
True if the length of the displacement is less than the length of the given displacement
References _FILEINFO_, isValid(), meters(), and Isis::IException::Programmer.
operator<=()
bool Isis::Displacement::operator<= (const Displacement & otherDisplacement) const inline
Compare the lengths of 2 displacements with the <= operator.
Parameters
otherDisplacement This is the displacement we are comparing i.e. it is on the right-hand-side of the operator when used
Returns
True if the length of this displacement is less than or equal to the length of the given displacement.
operator==()
bool Isis::Displacement::operator== (const Displacement & otherDisplacement) const inline
Compare the lengths of 2 displacements with the == operator.
Two uninitialized displacements are equal to each other.
Parameters
otherDisplacement This is the displacement we are comparing to, i.e. it is on the right-hand-side of the operator when used
Returns
True if the length of this displacement is equal to the
given displacement
operator>()
bool Isis::Displacement::operator> (const Displacement & otherDisplacement) const
Get the displacement in meters.
Compare two displacements with the greater than operator.
This is equivalent to meters()
Returns
The displacement, as a number, in units of Meters
operator double() const { return meters(); }
Parameters
otherdisplacement This is the displacement we're comparing to, i.e. it is on the right-hand-side of the operator when used
Returns
True if the length of this displacement is greater than the length of the given displacement
References _FILEINFO_, isValid(), meters(), and Isis::IException::Programmer.
operator>=()
bool Isis::Displacement::operator>= (const Displacement & otherDisplacement) const inline
Compare the distances of 2 displacements with the >= operator.
Parameters
otherDisplacement This is the displacement we are comparing to, i.e. it is on the right-hand-side of the operator when used
Returns
True if the length (unsigned) of the displacement is greater than or equal to the length of the given displacement
pixels()
double Isis::Displacement::pixels (double pixelsPerMeter = 1.0) const
Get the displacement in pixels using the given conversion ratio.
Parameters
pixelsPerMeter Pixels/Meters conversion ratio to use, stored data is always in meters
Returns
Current displacement, in pixels
References displacement(), and Meters.
Referenced by Isis::RawCubeChunk::RawCubeChunk().
setDisplacement()
void Isis::Displacement::setDisplacement (const double & displacement, Units displacementUnit) protected
This is a helper method to set displacements in a universal manner with uniform error checking.
Parameters
displacement The displacement, in units of displacementUnit, to set this class to. If this is negative an exception will be thrown and the state unmodified.
displacementUnit Unit of displacement. If this is invalid, an exception will be thrown and the state left unmodified.
References _FILEINFO_, displacement(), Isis::IsSpecial(), Kilometers, Meters, Isis::Null, Pixels, and Isis::IException::Programmer.
Referenced by Displacement(), operator*=(), operator+=(), operator-=(), operator/=(), setKilometers(), setMeters(), and setPixels().
setKilometers()
void Isis::Displacement::setKilometers (double displacementInKilometers)
Set the displacement in kilometers.
Parameters
displacementInKilometers This is the value to set as the displacement, given in kilometers.
References Kilometers, and setDisplacement().
setMeters()
void Isis::Displacement::setMeters (double displacementInMeters)
Set the displacement in meters.
Parameters
displacementInMeters This is the value to set this displacement to, given in meters.
References Meters, and setDisplacement().
setPixels()
void Isis::Displacement::setPixels (double displacementInPixels, double pixelsPerMeter = 1.0)
Set the displacement in pixels.
Parameters
displacementInPixels This is the value to set this displacement to, given in pixels.
pixelsPerMeter Pixels/Meters conversion ratio to use, stored data is always in meters
References Meters, and setDisplacement().
Friends And Related Function Documentation
operator*
Displacement operator* (double mult, Displacement displacement) friend
Multiply displacement by a value (5m * 2 = 10m).
Parameters
mult This is the value to multiply by
displacement This is the distance to multiply into
Returns
Resulting value
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Displacement/Displacement.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Displacement/Displacement.cpp