Isis Developer Reference: Isis::TableColumn Class Reference
Isis::TableColumn Class Reference
#include <TableColumn.h>
Signals
void selected (TableColumn *)
void sortOutDated ()
void widthChanged ()
void visibilityChanged ()
Public Member Functions
TableColumn (QString, bool, bool)
TableColumn (const TableColumn &)
virtual ~TableColumn ()
QString getTitle () const
void setTitle (QString text)
TableColumn & operator= (TableColumn)
bool isVisible () const
void setVisible (bool)
int getWidth () const
void setWidth (int)
bool isReadOnly () const
void setReadOnly (bool)
bool hasNetworkStructureEffect () const
bool sortAscending () const
void setSortAscending (bool ascending)
Static Public Attributes
static const int EDGE_WIDTH = 4
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
TableColumn() [1/2]
Isis::TableColumn::TableColumn (QString text, bool m_readOnlyStatus, bool affectsNetStructure) explicit
TableColumn() [2/2]
Isis::TableColumn::TableColumn (const TableColumn & other)
~TableColumn()
Isis::TableColumn::~TableColumn () virtual
Member Function Documentation
getTitle()
QString Isis::TableColumn::getTitle () const
Referenced by Isis::MeasureTableModel::getMeasureWarningMessage(), Isis::PointTableModel::getPointWarningMessage(), Isis::MeasureTableDelegate::getWidget(), Isis::PointTableDelegate::getWidget(), Isis::TableViewHeader::handleFilterCountsChanged(), Isis::TableViewContent::mousePressEvent(), Isis::TableViewHeader::mouseReleaseEvent(), Isis::MeasureTableDelegate::readData(), Isis::PointTableDelegate::readData(), Isis::MeasureTableDelegate::saveData(), Isis::PointTableDelegate::saveData(), Isis::TableView::setColumnVisible(), Isis::TableView::TableView(), and Isis::TableView::~TableView().
getWidth()
int Isis::TableColumn::getWidth () const
Referenced by Isis::TableView::~TableView().
hasNetworkStructureEffect()
bool Isis::TableColumn::hasNetworkStructureEffect () const
isReadOnly()
bool Isis::TableColumn::isReadOnly () const
isVisible()
bool Isis::TableColumn::isVisible () const
operator=()
TableColumn & Isis::TableColumn::operator= (TableColumn other)
selected
void Isis::TableColumn::selected (TableColumn *) signal
setReadOnly()
void Isis::TableColumn::setReadOnly (bool)
setSortAscending()
void Isis::TableColumn::setSortAscending (bool ascending)
References sortOutDated().
Referenced by Isis::TableViewHeader::mouseReleaseEvent(), and Isis::TableView::TableView().
setTitle()
void Isis::TableColumn::setTitle (QString text)
Referenced by Isis::AbstractPointItem::resetColumnHeaders().
setVisible()
void Isis::TableColumn::setVisible (bool visibility)
References visibilityChanged().
Referenced by Isis::TableView::setColumnVisible().
setWidth()
void Isis::TableColumn::setWidth (int newWidth)
References widthChanged().
Referenced by Isis::TableViewHeader::handleFilterCountsChanged(), and Isis::TableView::TableView().
sortAscending()
bool Isis::TableColumn::sortAscending () const
Referenced by Isis::TableViewHeader::mouseReleaseEvent(), and Isis::TableView::~TableView().
sortOutDated
void Isis::TableColumn::sortOutDated () signal
Referenced by setSortAscending().
visibilityChanged
void Isis::TableColumn::visibilityChanged () signal
Referenced by setVisible().
widthChanged
void Isis::TableColumn::widthChanged () signal
Referenced by setWidth().
Member Data Documentation
EDGE_WIDTH
const int Isis::TableColumn::EDGE_WIDTH = 4 static
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/TableColumn.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/TableColumn.cpp