Isis Developer Reference: Isis::MinnaertEmpirical Class Reference
Isis::MinnaertEmpirical Class Reference
Empirical Minnaert photometric model Derive model albedo using phase dependent Minnaert equation and calculated empirically.
#include <MinnaertEmpirical.h>
Public Member Functions
MinnaertEmpirical (Pvl &pvl)
virtual ~MinnaertEmpirical ()
void SetPhotoPhaseList (QString phasestrlist)
Set the empirical Minnaert function phase angle list.
void SetPhotoPhaseList (PvlKeyword phaselist)
Set the empirical Minnaert function phase angle list.
void SetPhotoKList (QString kstrlist)
Set the empirical Minnaert function K exponent list.
void SetPhotoKList (PvlKeyword kstrlist)
Set the empirical Minnaert function K exponent list.
void SetPhotoPhaseCurveList (QString phasecurvestrlist)
Set the empirical Minnaert function phase curve list.
void SetPhotoPhaseCurveList (PvlKeyword phasecurvestrlist)
Set the empirical Minnaert function phase curve list.
virtual double PhotoModelAlgorithm (double phase, double incidence, double emission)
Return photometric phase angle list.
QString AlgorithmName () const
Return algorithm name found in Pvl file from constructor.
virtual void SetStandardConditions (bool standard)
Sets whether standard conditions will be used.
bool StandardConditions () const
Returns true if standard conditions are used, i.e., if SetStandardConditions(true) has been called. This is initialized to false in the constructor.
double PhtTopder (double phase, double incidence, double emission)
Obtain topographic derivative of an arbitrary photometric function.
double CalcSurfAlbedo (double pha, double inc, double ema)
Calculate the surface brightness using photometric angle information.
virtual void SetPhotoL (const double l)
double PhotoL () const
Return photometric L value.
virtual void SetPhotoK (const double k)
double PhotoK () const
Return photometric K value.
virtual void SetPhotoHg1 (const double hg1)
double PhotoHg1 () const
Return photometric Hg1 value.
virtual void SetPhotoHg2 (const double hg2)
double PhotoHg2 () const
Return photometric Hg2 value.
virtual void SetPhotoBh (const double bh)
double PhotoBh () const
Return photometric Bh value.
virtual void SetPhotoCh (const double ch)
double PhotoCh () const
Return photometric Ch value.
virtual void SetPhotoWh (const double wh)
double PhotoWh () const
Return photometric Wh value.
virtual void SetPhotoHh (const double hh)
double PhotoHh () const
Return photometric Hh value.
virtual void SetPhotoB0 (const double b0)
double PhotoB0 () const
Return photometric B0 value.
virtual void SetPhotoTheta (const double theta)
double PhotoTheta () const
Return photometric Theta value.
virtual void SetPhoto0B0Standard (const QString &b0standard)
QString Photo0B0Standard () const
Return photometric B0 standardization value.
double Hfunc (double u, double gamma)
Hapke's approximation to Chandra's H function.
virtual void SetPhotoLList (const QString)
std::vector< double > PhotoPhaseList () const
Return photometric phase angle list.
std::vector< double > PhotoKList () const
Return photometric k value list.
std::vector< double > PhotoLList () const
Return photometric l value list.
std::vector< double > PhotoPhaseCurveList () const
Return photometric phase curve value list.
Static Public Member Functions
static double PhtAcos (double cosang)
Obtain arccosine of input value.
Protected Attributes
double p_photoL
double p_photoK
double p_photoHg1
double p_photoHg2
double p_photoBh
double p_photoCh
double p_photoCott
double p_photoCot2t
double p_photoTant
double p_photoSr
double p_photoOsr
QString p_algName
QString p_photo0B0Standard
double p_photoWh
double p_photoHh
double p_photoB0
double p_photoB0save
double p_photoTheta
double p_photoThetaold
std::vector< double > p_photoPhaseList
std::vector< double > p_photoKList
std::vector< double > p_photoLList
std::vector< double > p_photoPhaseCurveList
int p_photoPhaseAngleCount
NumericalApproximation p_photoKSpline
NumericalApproximation p_photoLSpline
NumericalApproximation p_photoBSpline
Detailed Description
Empirical Minnaert photometric model Derive model albedo using phase dependent Minnaert equation and calculated empirically.
Limb-darkening k and phase function are arbitrary polynomials in phase angle.
albedo = brightness*[mu / (mu*munot)**k)]
assumptions:
  1. bidirectional reflectance
  2. semi-infinite medium
                                             k      k-1
reflectance (inc,ema,phase)=albedo  *  munot   * mu
         Minnaert               Minnaert
Where k is the Minnaert index, an empirical constant (called nu in Hapke)
If k (nu) = 1, Minnaert's law reduces to Lambert's law. See Theory of Reflectance and Emittance Spectroscopy, 1993; Bruce Hapke; pg. 191-192.
Author
1999-01-08 Randy Kirk
Constructor & Destructor Documentation
MinnaertEmpirical()
Isis::MinnaertEmpirical::MinnaertEmpirical (Pvl & pvl)
References _FILEINFO_, Isis::NumericalApproximation::AddData(), Isis::NumericalApproximation::CubicClamped, Isis::PvlObject::findObject(), Isis::PvlContainer::hasKeyword(), Isis::PhotoModel::p_photoBSpline, Isis::PhotoModel::p_photoKList, Isis::PhotoModel::p_photoKSpline, Isis::PhotoModel::p_photoPhaseAngleCount, Isis::PhotoModel::p_photoPhaseCurveList, Isis::PhotoModel::p_photoPhaseList, Isis::NumericalApproximation::Reset(), Isis::NumericalApproximation::SetCubicClampedEndptDeriv(), Isis::NumericalApproximation::SetInterpType(), SetPhotoKList(), SetPhotoPhaseCurveList(), SetPhotoPhaseList(), Isis::PvlObject::Traverse, and Isis::IException::User.
~MinnaertEmpirical()
Isis::MinnaertEmpirical::~MinnaertEmpirical () virtual
References Isis::PhotoModel::p_photoBSpline, Isis::PhotoModel::p_photoKList, Isis::PhotoModel::p_photoKSpline, Isis::PhotoModel::p_photoPhaseCurveList, Isis::PhotoModel::p_photoPhaseList, and Isis::NumericalApproximation::Reset().
Member Function Documentation
AlgorithmName()
QString Isis::PhotoModel::AlgorithmName () const inline inherited
Return algorithm name found in Pvl file from constructor.
Referenced by Isis::Hapke::Hapke().
CalcSurfAlbedo()
double Isis::PhotoModel::CalcSurfAlbedo (double pha, double inc, double ema) inherited
Calculate the surface brightness using photometric angle information.
Parameters
pha Phase angle
inc Incidence angle
ema Emission angle
Returns
double Surface brightness calculated by the photometric function
Referenced by Isis::Albedo::Albedo(), Isis::AlbedoAtm::AlbedoAtm(), Isis::NumericalAtmosApprox::InrFunc2Bint(), Isis::Mixed::Mixed(), Isis::Albedo::NormModelAlgorithm(), Isis::AlbedoAtm::NormModelAlgorithm(), Isis::Mixed::NormModelAlgorithm(), Isis::MoonAlbedo::NormModelAlgorithm(), Isis::NoNormalization::NormModelAlgorithm(), Isis::Shade::NormModelAlgorithm(), Isis::ShadeAtm::NormModelAlgorithm(), Isis::Topo::NormModelAlgorithm(), Isis::TopoAtm::NormModelAlgorithm(), and Isis::TopoAtm::TopoAtm().
Hfunc()
double Isis::PhotoModel::Hfunc (double u, double gamma) inline inherited
Hapke's approximation to Chandra's H function.
Referenced by Isis::Hapke::PhotoModelAlgorithm().
Photo0B0Standard()
QString Isis::PhotoModel::Photo0B0Standard () const inline inherited
Return photometric B0 standardization value.
References Isis::PhotoModel::p_photo0B0Standard.
PhotoB0()
double Isis::PhotoModel::PhotoB0 () const inline inherited
Return photometric B0 value.
References Isis::PhotoModel::p_photoB0.
PhotoBh()
double Isis::PhotoModel::PhotoBh () const inline inherited
Return photometric Bh value.
References Isis::PhotoModel::p_photoBh.
PhotoCh()
double Isis::PhotoModel::PhotoCh () const inline inherited
Return photometric Ch value.
References Isis::PhotoModel::p_photoCh.
PhotoHg1()
double Isis::PhotoModel::PhotoHg1 () const inline inherited
Return photometric Hg1 value.
References Isis::PhotoModel::p_photoHg1.
PhotoHg2()
double Isis::PhotoModel::PhotoHg2 () const inline inherited
Return photometric Hg2 value.
References Isis::PhotoModel::p_photoHg2.
PhotoHh()
double Isis::PhotoModel::PhotoHh () const inline inherited
Return photometric Hh value.
References Isis::PhotoModel::p_photoHh.
PhotoK()
double Isis::PhotoModel::PhotoK () const inline inherited
Return photometric K value.
References Isis::PhotoModel::p_photoK.
PhotoKList()
std::vector<double> Isis::PhotoModel::PhotoKList () const inline inherited
Return photometric k value list.
References Isis::PhotoModel::p_photoKList.
PhotoL()
double Isis::PhotoModel::PhotoL () const inline inherited
Return photometric L value.
References Isis::PhotoModel::p_photoL.
PhotoLList()
std::vector<double> Isis::PhotoModel::PhotoLList () const inline inherited
Return photometric l value list.
References Isis::PhotoModel::p_photoLList.
PhotoModelAlgorithm()
double Isis::MinnaertEmpirical::PhotoModelAlgorithm (double phase, double incidence, double emission) virtual
Return photometric phase angle list.
Return photometric k value list Return photometric phase curve value list
Implements Isis::PhotoModel.
References Isis::NumericalApproximation::Evaluate(), Isis::NumericalApproximation::Extrapolate, Isis::PhotoModel::p_photoBSpline, Isis::PhotoModel::p_photoKSpline, and Isis::PI.
PhotoPhaseCurveList()
std::vector<double> Isis::PhotoModel::PhotoPhaseCurveList () const inline inherited
Return photometric phase curve value list.
References Isis::PhotoModel::p_photoPhaseCurveList.
PhotoPhaseList()
std::vector<double> Isis::PhotoModel::PhotoPhaseList () const inline inherited
Return photometric phase angle list.
References Isis::PhotoModel::p_photoPhaseList.
PhotoTheta()
double Isis::PhotoModel::PhotoTheta () const inline inherited
Return photometric Theta value.
References Isis::PhotoModel::p_photoTheta.
PhotoWh()
double Isis::PhotoModel::PhotoWh () const inline inherited
Return photometric Wh value.
References Isis::PhotoModel::p_photoWh.
PhtAcos()
double Isis::PhotoModel::PhtAcos (double cosang) static inherited
Obtain arccosine of input value.
If the input value is outside of the valid range (-1 to 1), then obtain the arccosine of the closest valid value.
Parameters
cosang input value to obtain arccosine of (in radians)
Returns
double Arccosine of cosang, if valid.
History:
2008-11-05 Jeannie Walldren - This method was moved from NumericalMethods class.
PhtTopder()
double Isis::PhotoModel::PhtTopder (double phase, double incidence, double emission) inherited
Obtain topographic derivative of an arbitrary photometric function.
Parameters
phase Input phase angle
incidence Input incidence angle
emission Input emission angle
Returns
double Gradient
References Isis::PI.
Referenced by Isis::Mixed::Mixed(), Isis::Mixed::NormModelAlgorithm(), Isis::Topo::NormModelAlgorithm(), Isis::TopoAtm::NormModelAlgorithm(), and Isis::TopoAtm::TopoAtm().
SetPhoto0B0Standard()
virtual void Isis::PhotoModel::SetPhoto0B0Standard (const QString & b0standard) inline virtual inherited
Reimplemented in Isis::Hapke.
References Isis::PhotoModel::p_photo0B0Standard.
SetPhotoB0()
virtual void Isis::PhotoModel::SetPhotoB0 (const double b0) inline virtual inherited
Reimplemented in Isis::Hapke.
References Isis::PhotoModel::p_photoB0.
SetPhotoBh()
virtual void Isis::PhotoModel::SetPhotoBh (const double bh) inline virtual inherited
Reimplemented in Isis::Hapke.
References Isis::PhotoModel::p_photoBh.
SetPhotoCh()
virtual void Isis::PhotoModel::SetPhotoCh (const double ch) inline virtual inherited
Reimplemented in Isis::Hapke.
References Isis::PhotoModel::p_photoCh.
SetPhotoHg1()
virtual void Isis::PhotoModel::SetPhotoHg1 (const double hg1) inline virtual inherited
Reimplemented in Isis::Hapke.
References Isis::PhotoModel::p_photoHg1.
SetPhotoHg2()
virtual void Isis::PhotoModel::SetPhotoHg2 (const double hg2) inline virtual inherited
Reimplemented in Isis::Hapke.
References Isis::PhotoModel::p_photoHg2.
SetPhotoHh()
virtual void Isis::PhotoModel::SetPhotoHh (const double hh) inline virtual inherited
Reimplemented in Isis::Hapke.
References Isis::PhotoModel::p_photoHh.
SetPhotoK()
virtual void Isis::PhotoModel::SetPhotoK (const double k) inline virtual inherited
Reimplemented in Isis::Minnaert.
References Isis::PhotoModel::p_photoK.
SetPhotoKList() [1/2]
void Isis::MinnaertEmpirical::SetPhotoKList (PvlKeyword kstrList)
Set the empirical Minnaert function K exponent list.
This is used to govern the limb-darkening in the Minnaert photometric function. Values of the Minnaert exponent generally fall in the range from 0.5 ("lunar-like", almost no limb darkening) to 1.0 (Lambert function). This parameter is limited to values that are >=0.
Parameters
kstrList PvkKeyword containing List of Minnaert function exponents to interpolate
References Isis::PhotoModel::p_photoKList, SetPhotoKList(), Isis::PvlKeyword::size(), and Isis::toDouble().
SetPhotoKList() [2/2]
void Isis::MinnaertEmpirical::SetPhotoKList (QString kstrlist) virtual
Set the empirical Minnaert function K exponent list.
This is used to govern the limb-darkening in the Minnaert photometric function. Values of the Minnaert exponent generally fall in the range from 0.5 ("lunar-like", almost no limb darkening) to 1.0 (Lambert function). This parameter is limited to values that are >=0.
Parameters
kstrlist List of Minnaert function exponents to interpolate
Reimplemented from Isis::PhotoModel.
References _FILEINFO_, Isis::PhotoModel::p_photoKList, Isis::IString::Token(), and Isis::IException::User.
Referenced by MinnaertEmpirical(), and SetPhotoKList().
SetPhotoL()
virtual void Isis::PhotoModel::SetPhotoL (const double l) inline virtual inherited
Reimplemented in Isis::LunarLambert.
References Isis::PhotoModel::p_photoL.
SetPhotoLList()
virtual void Isis::PhotoModel::SetPhotoLList (const QString) inline virtual inherited
Reimplemented in Isis::LunarLambertEmpirical.
SetPhotoPhaseCurveList() [1/2]
void Isis::MinnaertEmpirical::SetPhotoPhaseCurveList (PvlKeyword photocurvestrList)
Set the empirical Minnaert function phase curve list.
This list provides the brightness values that correspond to the limb-darkening values in the empirical Minnaert photometric function.
Parameters
phasecurvelist PvlKeyword containing list of brightness values corresponding to Minnaert function exponents
References Isis::PhotoModel::p_photoPhaseCurveList, SetPhotoPhaseCurveList(), Isis::PvlKeyword::size(), and Isis::toDouble().
SetPhotoPhaseCurveList() [2/2]
void Isis::MinnaertEmpirical::SetPhotoPhaseCurveList (QString phasecurvestrlist) virtual
Set the empirical Minnaert function phase curve list.
This list provides the brightness values that correspond to the limb-darkening values in the empirical Minnaert photometric function.
Parameters
phasecurvelist List of brightness values corresponding to Minnaert function exponents
Reimplemented from Isis::PhotoModel.
References Isis::PhotoModel::p_photoPhaseCurveList, and Isis::IString::Token().
Referenced by MinnaertEmpirical(), and SetPhotoPhaseCurveList().
SetPhotoPhaseList() [1/2]
void Isis::MinnaertEmpirical::SetPhotoPhaseList (PvlKeyword phaseList)
Set the empirical Minnaert function phase angle list.
This is the list of phase angles that Minnaert K values and phase curve list values will be provided for. A spline curve will be used to interpolate K values and phase curve values that exist between the given phase angles. The values in the phase angle list are limited to values that are >=0 and <=180.
Parameters
phaselist PvlKeyword containing phase angles to interpolate
References _FILEINFO_, Isis::PhotoModel::p_photoPhaseList, SetPhotoPhaseList(), Isis::PvlKeyword::size(), Isis::toString(), and Isis::IException::User.
SetPhotoPhaseList() [2/2]
void Isis::MinnaertEmpirical::SetPhotoPhaseList (QString phasestrlist) virtual
Set the empirical Minnaert function phase angle list.
This is the list of phase angles that Minnaert K values and phase curve list values will be provided for. A spline curve will be used to interpolate K values and phase curve values that exist between the given phase angles. The values in the phase angle list are limited to values that are >=0 and <=180.
Parameters
phasestrlist List of phase angles to interpolate
Reimplemented from Isis::PhotoModel.
References _FILEINFO_, Isis::PhotoModel::p_photoPhaseList, Isis::IString::Token(), and Isis::IException::User.
Referenced by MinnaertEmpirical(), and SetPhotoPhaseList().
SetPhotoTheta()
virtual void Isis::PhotoModel::SetPhotoTheta (const double theta) inline virtual inherited
Reimplemented in Isis::Hapke.
References Isis::PhotoModel::p_photoTheta.
SetPhotoWh()
virtual void Isis::PhotoModel::SetPhotoWh (const double wh) inline virtual inherited
Reimplemented in Isis::Hapke.
References Isis::PhotoModel::p_photoWh.
SetStandardConditions()
void Isis::PhotoModel::SetStandardConditions (bool standard) virtual inherited
Sets whether standard conditions will be used.
Parameters
standard True if standard conditions are used.
Reimplemented in Isis::Hapke.
Referenced by Isis::Albedo::Albedo(), Isis::AlbedoAtm::AlbedoAtm(), Isis::Mixed::Mixed(), Isis::Shade::NormModelAlgorithm(), Isis::ShadeAtm::NormModelAlgorithm(), Isis::Topo::NormModelAlgorithm(), Isis::Hapke::SetStandardConditions(), and Isis::TopoAtm::TopoAtm().
StandardConditions()
bool Isis::PhotoModel::StandardConditions () const inline inherited
Returns true if standard conditions are used, i.e., if SetStandardConditions(true) has been called. This is initialized to false in the constructor.
Member Data Documentation
p_algName
QString Isis::PhotoModel::p_algName protected inherited
Referenced by Isis::Hapke::Hapke(), and Isis::Hapke::PhotoModelAlgorithm().
p_photo0B0Standard
QString Isis::PhotoModel::p_photo0B0Standard protected inherited
Referenced by Isis::PhotoModel::Photo0B0Standard(), Isis::Hapke::SetPhoto0B0Standard(), Isis::PhotoModel::SetPhoto0B0Standard(), and Isis::Hapke::SetStandardConditions().
p_photoB0
double Isis::PhotoModel::p_photoB0 protected inherited
Referenced by Isis::Hapke::Hapke(), Isis::PhotoModel::PhotoB0(), Isis::Hapke::PhotoModelAlgorithm(), Isis::Hapke::SetPhotoB0(), Isis::PhotoModel::SetPhotoB0(), and Isis::Hapke::SetStandardConditions().
p_photoB0save
double Isis::PhotoModel::p_photoB0save protected inherited
Referenced by Isis::Hapke::Hapke(), and Isis::Hapke::SetStandardConditions().
p_photoBh
double Isis::PhotoModel::p_photoBh protected inherited
Referenced by Isis::PhotoModel::PhotoBh(), Isis::Hapke::PhotoModelAlgorithm(), Isis::Hapke::SetPhotoBh(), and Isis::PhotoModel::SetPhotoBh().
p_photoBSpline
NumericalApproximation Isis::PhotoModel::p_photoBSpline protected inherited
Referenced by Isis::LunarLambertEmpirical::LunarLambertEmpirical(), MinnaertEmpirical(), Isis::LunarLambertEmpirical::PhotoModelAlgorithm(), PhotoModelAlgorithm(), Isis::LunarLambertEmpirical::~LunarLambertEmpirical(), and ~MinnaertEmpirical().
p_photoCh
double Isis::PhotoModel::p_photoCh protected inherited
Referenced by Isis::PhotoModel::PhotoCh(), Isis::Hapke::PhotoModelAlgorithm(), Isis::Hapke::SetPhotoCh(), and Isis::PhotoModel::SetPhotoCh().
p_photoCot2t
double Isis::PhotoModel::p_photoCot2t protected inherited
Referenced by Isis::Hapke::PhotoModelAlgorithm().
p_photoCott
double Isis::PhotoModel::p_photoCott protected inherited
Referenced by Isis::Hapke::PhotoModelAlgorithm().
p_photoHg1
double Isis::PhotoModel::p_photoHg1 protected inherited
Referenced by Isis::Hapke::Hapke(), Isis::PhotoModel::PhotoHg1(), Isis::Hapke::PhotoModelAlgorithm(), Isis::Hapke::SetPhotoHg1(), and Isis::PhotoModel::SetPhotoHg1().
p_photoHg2
double Isis::PhotoModel::p_photoHg2 protected inherited
Referenced by Isis::Hapke::Hapke(), Isis::PhotoModel::PhotoHg2(), Isis::Hapke::PhotoModelAlgorithm(), Isis::Hapke::SetPhotoHg2(), and Isis::PhotoModel::SetPhotoHg2().
p_photoHh
double Isis::PhotoModel::p_photoHh protected inherited
Referenced by Isis::Hapke::Hapke(), Isis::PhotoModel::PhotoHh(), Isis::Hapke::PhotoModelAlgorithm(), Isis::Hapke::SetPhotoHh(), and Isis::PhotoModel::SetPhotoHh().
p_photoK
double Isis::PhotoModel::p_photoK protected inherited
Referenced by Isis::PhotoModel::PhotoK(), Isis::Minnaert::PhotoModelAlgorithm(), Isis::Minnaert::SetPhotoK(), and Isis::PhotoModel::SetPhotoK().
p_photoKList
std::vector<double> Isis::PhotoModel::p_photoKList protected inherited
Referenced by MinnaertEmpirical(), Isis::PhotoModel::PhotoKList(), SetPhotoKList(), and ~MinnaertEmpirical().
p_photoKSpline
NumericalApproximation Isis::PhotoModel::p_photoKSpline protected inherited
Referenced by MinnaertEmpirical(), PhotoModelAlgorithm(), and ~MinnaertEmpirical().
p_photoL
double Isis::PhotoModel::p_photoL protected inherited
Referenced by Isis::PhotoModel::PhotoL(), Isis::LunarLambert::PhotoModelAlgorithm(), Isis::LunarLambert::SetPhotoL(), and Isis::PhotoModel::SetPhotoL().
p_photoLList
std::vector<double> Isis::PhotoModel::p_photoLList protected inherited
Referenced by Isis::LunarLambertEmpirical::LunarLambertEmpirical(), Isis::PhotoModel::PhotoLList(), Isis::LunarLambertEmpirical::SetPhotoLList(), and Isis::LunarLambertEmpirical::~LunarLambertEmpirical().
p_photoLSpline
NumericalApproximation Isis::PhotoModel::p_photoLSpline protected inherited
Referenced by Isis::LunarLambertEmpirical::LunarLambertEmpirical(), Isis::LunarLambertEmpirical::PhotoModelAlgorithm(), and Isis::LunarLambertEmpirical::~LunarLambertEmpirical().
p_photoOsr
double Isis::PhotoModel::p_photoOsr protected inherited
Referenced by Isis::Hapke::PhotoModelAlgorithm().
p_photoPhaseAngleCount
int Isis::PhotoModel::p_photoPhaseAngleCount protected inherited
Referenced by Isis::LunarLambertEmpirical::LunarLambertEmpirical(), and MinnaertEmpirical().
p_photoPhaseCurveList
std::vector<double> Isis::PhotoModel::p_photoPhaseCurveList protected inherited
Referenced by Isis::LunarLambertEmpirical::LunarLambertEmpirical(), MinnaertEmpirical(), Isis::PhotoModel::PhotoPhaseCurveList(), Isis::LunarLambertEmpirical::SetPhotoPhaseCurveList(), SetPhotoPhaseCurveList(), Isis::LunarLambertEmpirical::~LunarLambertEmpirical(), and ~MinnaertEmpirical().
p_photoPhaseList
std::vector<double> Isis::PhotoModel::p_photoPhaseList protected inherited
Referenced by Isis::LunarLambertEmpirical::LunarLambertEmpirical(), MinnaertEmpirical(), Isis::PhotoModel::PhotoPhaseList(), Isis::LunarLambertEmpirical::SetPhotoPhaseList(), SetPhotoPhaseList(), Isis::LunarLambertEmpirical::~LunarLambertEmpirical(), and ~MinnaertEmpirical().
p_photoSr
double Isis::PhotoModel::p_photoSr protected inherited
Referenced by Isis::Hapke::PhotoModelAlgorithm().
p_photoTant
double Isis::PhotoModel::p_photoTant protected inherited
Referenced by Isis::Hapke::PhotoModelAlgorithm().
p_photoTheta
double Isis::PhotoModel::p_photoTheta protected inherited
Referenced by Isis::Hapke::Hapke(), Isis::Hapke::PhotoModelAlgorithm(), Isis::PhotoModel::PhotoTheta(), Isis::Hapke::SetPhotoTheta(), and Isis::PhotoModel::SetPhotoTheta().
p_photoThetaold
double Isis::PhotoModel::p_photoThetaold protected inherited
Referenced by Isis::Hapke::Hapke(), Isis::Hapke::PhotoModelAlgorithm(), and Isis::Hapke::SetOldTheta().
p_photoWh
double Isis::PhotoModel::p_photoWh protected inherited
Referenced by Isis::Hapke::Hapke(), Isis::Hapke::PhotoModelAlgorithm(), Isis::PhotoModel::PhotoWh(), Isis::Hapke::SetPhotoWh(), and Isis::PhotoModel::SetPhotoWh().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/MinnaertEmpirical/MinnaertEmpirical.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/MinnaertEmpirical/MinnaertEmpirical.cpp