Isis Developer Reference: Isis::PointTableModel Class Reference
Isis::PointTableModel Class Reference
Table model for control points.
#include <PointTableModel.h>
Public Types
enum Warning { None = 0 , SortingDisabled , SortingTableSizeLimitReached }
Public Slots
void handleTreeSelectionChanged (QList< AbstractTreeItem * >)
void resetColumnHeaders ()
virtual void applyFilter ()
virtual void sort ()
virtual void reverseOrder (TableColumn *)
virtual void updateSort ()
virtual void rebuildSort ()
Signals
void modelModified ()
void filterProgressChanged (int)
void rebuildProgressChanged (int)
void sortProgressChanged (int)
void filterProgressRangeChanged (int, int)
void rebuildProgressRangeChanged (int, int)
void sortProgressRangeChanged (int, int)
void filterCountsChanged (int visibleRows, int totalRows)
void treeSelectionChanged (QList< AbstractTreeItem * >)
void tableSelectionChanged (QList< AbstractTreeItem * >)
void userWarning (AbstractTableModel::Warning)
Public Member Functions
PointTableModel (AbstractTreeModel *model)
virtual ~PointTableModel ()
virtual QList< AbstractTreeItem * > getItems (int, int)
virtual QList< AbstractTreeItem * > getItems (AbstractTreeItem *, AbstractTreeItem *)
virtual int getVisibleRowCount () const
virtual QList< AbstractTreeItem * > getSelectedItems ()
virtual QString getWarningMessage (AbstractTreeItem const *, TableColumn const *, QString valueToSave) const
virtual void setGlobalSelection (bool selected)
virtual int indexOfVisibleItem (AbstractTreeItem const *item) const
virtual bool isSorting () const
virtual bool isFiltering () const
virtual bool sortingIsEnabled () const
virtual void setSortingEnabled (bool)
virtual int sortLimit () const
virtual void setSortLimit (int)
virtual bool sortingOn () const
virtual TableColumnList * getColumns ()
virtual const AbstractTableDelegate * getDelegate () const
Static Public Member Functions
static QString getPointWarningMessage (AbstractTreeItem const *, TableColumn const *, QString valueToSave)
Protected Member Functions
virtual TableColumnList * createColumns ()
AbstractTreeModel * getDataModel ()
const AbstractTreeModel * getDataModel () const
virtual QList< AbstractTreeItem * > getSortedItems (int, int, AbstractTreeModel::InterestingItems)
virtual QList< AbstractTreeItem * > getSortedItems (AbstractTreeItem *, AbstractTreeItem *, AbstractTreeModel::InterestingItems)
void handleTreeSelectionChanged (QList< AbstractTreeItem * > newlySelectedItems, AbstractTreeItem::InternalPointerType)
Detailed Description
Table model for control points.
This class represents a model that provides access to control points in a table-like fashion. It acts as a proxy model to the underlying tree model by providing an interface to get items by index ranges, get selected items, etc.. Thus, users of the class can access all control points in the underlying tree model without having to worry about the details of traversing the tree structure to find the items of interest. The class also has knowledge of what columns should be in the control point table.
Author
????-??-?? Eric Hyer
Member Enumeration Documentation
Warning
enum Isis::AbstractTableModel::Warning inherited
Enumerator
None
SortingDisabled
SortingTableSizeLimitReached
Constructor & Destructor Documentation
PointTableModel()
Isis::PointTableModel::PointTableModel (AbstractTreeModel * model) explicit
References Isis::AbstractTableModel::filterCountsChanged(), handleTreeSelectionChanged(), and Isis::AbstractTableModel::treeSelectionChanged().
~PointTableModel()
Isis::PointTableModel::~PointTableModel () virtual
Member Function Documentation
applyFilter
void Isis::AbstractTableModel::applyFilter () virtual slot inherited
References Isis::AbstractTreeModel::applyFilter(), and Isis::AbstractTableModel::getDataModel().
createColumns()
TableColumnList * Isis::PointTableModel::createColumns () protected virtual
Implements Isis::AbstractTableModel.
References Isis::AbstractPointItem::createColumns().
filterCountsChanged
void Isis::AbstractTableModel::filterCountsChanged (int visibleRows, int totalRows) signal inherited
Referenced by Isis::AbstractTableModel::AbstractTableModel(), Isis::MeasureTableModel::MeasureTableModel(), and PointTableModel().
filterProgressChanged
void Isis::AbstractTableModel::filterProgressChanged (int) signal inherited
Referenced by Isis::AbstractTableModel::AbstractTableModel().
filterProgressRangeChanged
void Isis::AbstractTableModel::filterProgressRangeChanged (int , int) signal inherited
Referenced by Isis::AbstractTableModel::AbstractTableModel().
getColumns()
TableColumnList * Isis::AbstractTableModel::getColumns () virtual inherited
References Isis::AbstractTableModel::createColumns(), and Isis::AbstractTableModel::sort().
Referenced by resetColumnHeaders(), Isis::TableViewHeader::setModel(), Isis::TableView::TableView(), and Isis::TableViewContent::TableViewContent().
getDataModel() [1/2]
AbstractTreeModel * Isis::AbstractTableModel::getDataModel () protected inherited
Referenced by Isis::AbstractTableModel::applyFilter(), Isis::MeasureTableModel::getSelectedItems(), getSelectedItems(), Isis::AbstractTableModel::getSortedItems(), Isis::MeasureTableModel::getVisibleRowCount(), getVisibleRowCount(), Isis::MeasureTableModel::indexOfVisibleItem(), indexOfVisibleItem(), Isis::MeasureTableModel::setGlobalSelection(), and setGlobalSelection().
getDataModel() [2/2]
const AbstractTreeModel * Isis::AbstractTableModel::getDataModel () const protected inherited
getDelegate()
const AbstractTableDelegate * Isis::AbstractTableModel::getDelegate () const virtual inherited
Referenced by Isis::TableViewContent::keyPressEvent(), and Isis::TableViewContent::mouseDoubleClickEvent().
getItems() [1/2]
QList< AbstractTreeItem * > Isis::PointTableModel::getItems (AbstractTreeItem * item1, AbstractTreeItem * item2) virtual
Implements Isis::AbstractTableModel.
References Isis::AbstractTableModel::getSortedItems(), and Isis::AbstractTreeModel::PointItems.
getItems() [2/2]
QList< AbstractTreeItem * > Isis::PointTableModel::getItems (int start, int end) virtual
Implements Isis::AbstractTableModel.
References Isis::AbstractTableModel::getSortedItems(), and Isis::AbstractTreeModel::PointItems.
getPointWarningMessage()
QString Isis::PointTableModel::getPointWarningMessage (AbstractTreeItem const * row, TableColumn const * column, QString valueToSave) static
References Isis::AbstractPointItem::APrioriSPCoord1, Isis::AbstractPointItem::APrioriSPCoord1Sigma, Isis::AbstractPointItem::APrioriSPCoord2, Isis::AbstractPointItem::APrioriSPCoord2Sigma, Isis::AbstractPointItem::APrioriSPCoord3, Isis::AbstractPointItem::APrioriSPCoord3Sigma, Isis::AbstractPointItem::EditLock, Isis::ControlPoint::GetAprioriSurfacePoint(), Isis::AbstractPointItem::getColumn(), Isis::AbstractTreeItem::getFormattedData(), Isis::CnetDisplayProperties::getInstance(), Isis::AbstractTreeItem::getPointer(), Isis::TableColumn::getTitle(), and Isis::CnetDisplayProperties::LatLonRadius.
Referenced by getWarningMessage(), and Isis::PointTableDelegate::saveData().
getSelectedItems()
QList< AbstractTreeItem * > Isis::PointTableModel::getSelectedItems () virtual
Implements Isis::AbstractTableModel.
References Isis::AbstractTableModel::getDataModel(), Isis::AbstractTreeModel::getSelectedItems(), and Isis::AbstractTreeModel::PointItems.
getSortedItems() [1/2]
QList< AbstractTreeItem * > Isis::AbstractTableModel::getSortedItems (AbstractTreeItem * item1, AbstractTreeItem * item2, AbstractTreeModel::InterestingItems flags) protected virtual inherited
References _FILEINFO_, Isis::AbstractTableModel::getDataModel(), Isis::AbstractTreeModel::getItems(), Isis::IException::Programmer, and Isis::AbstractTableModel::sortingOn().
getSortedItems() [2/2]
QList< AbstractTreeItem * > Isis::AbstractTableModel::getSortedItems (int start, int end, AbstractTreeModel::InterestingItems flags) protected virtual inherited
References Isis::AbstractTableModel::getDataModel(), Isis::AbstractTreeModel::getItems(), Isis::AbstractTableModel::isFiltering(), and Isis::AbstractTableModel::sortingOn().
Referenced by Isis::MeasureTableModel::getItems(), and getItems().
getVisibleRowCount()
int Isis::PointTableModel::getVisibleRowCount () const virtual
Implements Isis::AbstractTableModel.
References Isis::AbstractTableModel::getDataModel(), Isis::AbstractTreeModel::getVisibleItemCount(), and Isis::AbstractTreeModel::PointItems.
getWarningMessage()
QString Isis::PointTableModel::getWarningMessage (AbstractTreeItem const * row, TableColumn const * column, QString valueToSave) const virtual
Implements Isis::AbstractTableModel.
References getPointWarningMessage().
handleTreeSelectionChanged() [1/2]
void Isis::AbstractTableModel::handleTreeSelectionChanged (QList< AbstractTreeItem * > newlySelectedItems, AbstractTreeItem::InternalPointerType pointerType) protected inherited
References Isis::AbstractTreeItem::getPointerType(), and Isis::AbstractTableModel::treeSelectionChanged().
Referenced by Isis::MeasureTableModel::handleTreeSelectionChanged(), and handleTreeSelectionChanged().
handleTreeSelectionChanged [2/2]
void Isis::PointTableModel::handleTreeSelectionChanged (QList< AbstractTreeItem * > newlySelectedItems) slot
References Isis::AbstractTreeItem::getPointerType(), Isis::AbstractTableModel::handleTreeSelectionChanged(), Isis::AbstractTreeItem::Measure, Isis::AbstractTreeItem::parent(), and Isis::AbstractTreeItem::Point.
Referenced by PointTableModel().
indexOfVisibleItem()
int Isis::PointTableModel::indexOfVisibleItem (AbstractTreeItem const * item) const virtual
Implements Isis::AbstractTableModel.
References Isis::AbstractTableModel::getDataModel(), Isis::AbstractTreeModel::indexOfVisibleItem(), and Isis::AbstractTreeModel::PointItems.
isFiltering()
bool Isis::AbstractTableModel::isFiltering () const virtual inherited
References Isis::AbstractTreeModel::isFiltering().
Referenced by Isis::AbstractTableModel::getSortedItems(), and Isis::TableViewContent::refresh().
isSorting()
bool Isis::AbstractTableModel::isSorting () const virtual inherited
Referenced by Isis::AbstractTableModel::sort().
modelModified
void Isis::AbstractTableModel::modelModified () signal inherited
Referenced by Isis::AbstractTableModel::AbstractTableModel(), Isis::AbstractTableModel::rebuildSort(), and Isis::AbstractTableModel::sort().
rebuildProgressChanged
void Isis::AbstractTableModel::rebuildProgressChanged (int) signal inherited
Referenced by Isis::AbstractTableModel::AbstractTableModel().
rebuildProgressRangeChanged
void Isis::AbstractTableModel::rebuildProgressRangeChanged (int , int) signal inherited
Referenced by Isis::AbstractTableModel::AbstractTableModel().
rebuildSort
void Isis::AbstractTableModel::rebuildSort () virtual slot inherited
References Isis::AbstractTableModel::getItems(), Isis::AbstractTableModel::modelModified(), Isis::AbstractTableModel::None, Isis::AbstractTableModel::sort(), Isis::AbstractTableModel::SortingDisabled, Isis::AbstractTableModel::sortingOn(), Isis::AbstractTableModel::SortingTableSizeLimitReached, and Isis::AbstractTableModel::userWarning().
Referenced by Isis::AbstractTableModel::AbstractTableModel(), Isis::AbstractTableModel::setSortingEnabled(), and Isis::AbstractTableModel::setSortLimit().
resetColumnHeaders
void Isis::PointTableModel::resetColumnHeaders () slot
References Isis::AbstractTableModel::getColumns(), and Isis::AbstractPointItem::resetColumnHeaders().
reverseOrder
void Isis::AbstractTableModel::reverseOrder (TableColumn * column) virtual slot inherited
setGlobalSelection()
void Isis::PointTableModel::setGlobalSelection (bool selected) virtual
Implements Isis::AbstractTableModel.
References Isis::AbstractTreeModel::AllItems, Isis::AbstractTableModel::getDataModel(), and Isis::AbstractTreeModel::setGlobalSelection().
setSortingEnabled()
void Isis::AbstractTableModel::setSortingEnabled (bool enabled) virtual inherited
References Isis::AbstractTableModel::rebuildSort().
Referenced by Isis::CnetEditorWidget::setMeasureTableSortingEnabled(), and Isis::CnetEditorWidget::setPointTableSortingEnabled().
setSortLimit()
void Isis::AbstractTableModel::setSortLimit (int limit) virtual inherited
References Isis::AbstractTableModel::rebuildSort().
Referenced by Isis::CnetEditorWidget::setMeasureTableSortLimit(), and Isis::CnetEditorWidget::setPointTableSortLimit().
sort
void Isis::AbstractTableModel::sort () virtual slot inherited
References Isis::TableColumnList::getSortingOrder(), Isis::AbstractTreeModel::isFiltering(), Isis::AbstractTreeModel::isRebuilding(), Isis::AbstractTableModel::isSorting(), Isis::AbstractTableModel::modelModified(), and Isis::AbstractTableModel::sortingOn().
Referenced by Isis::AbstractTableModel::getColumns(), and Isis::AbstractTableModel::rebuildSort().
sortingIsEnabled()
bool Isis::AbstractTableModel::sortingIsEnabled () const virtual inherited
Referenced by Isis::CnetEditorWidget::measureTableSortingEnabled(), Isis::CnetEditorWidget::pointTableSortingEnabled(), and Isis::AbstractTableModel::sortingOn().
sortingOn()
bool Isis::AbstractTableModel::sortingOn () const virtual inherited
References Isis::AbstractTableModel::getVisibleRowCount(), Isis::AbstractTableModel::sortingIsEnabled(), and Isis::AbstractTableModel::sortLimit().
Referenced by Isis::AbstractTableModel::getSortedItems(), Isis::TableViewHeader::mouseReleaseEvent(), Isis::AbstractTableModel::rebuildSort(), and Isis::AbstractTableModel::sort().
sortLimit()
int Isis::AbstractTableModel::sortLimit () const virtual inherited
Referenced by Isis::TableView::displayWarning(), Isis::CnetEditorWidget::measureTableSortLimit(), Isis::CnetEditorWidget::pointTableSortLimit(), Isis::CnetEditorSortConfigDialog::readSettings(), and Isis::AbstractTableModel::sortingOn().
sortProgressChanged
void Isis::AbstractTableModel::sortProgressChanged (int) signal inherited
sortProgressRangeChanged
void Isis::AbstractTableModel::sortProgressRangeChanged (int , int) signal inherited
tableSelectionChanged
void Isis::AbstractTableModel::tableSelectionChanged (QList< AbstractTreeItem * >) signal inherited
Referenced by Isis::AbstractTableModel::AbstractTableModel().
treeSelectionChanged
void Isis::AbstractTableModel::treeSelectionChanged (QList< AbstractTreeItem * >) signal inherited
Referenced by Isis::AbstractTableModel::handleTreeSelectionChanged(), Isis::MeasureTableModel::MeasureTableModel(), and PointTableModel().
updateSort
void Isis::AbstractTableModel::updateSort () virtual slot inherited
userWarning
void Isis::AbstractTableModel::userWarning (AbstractTableModel::Warning) signal inherited
Referenced by Isis::AbstractTableModel::rebuildSort().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/PointTableModel.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/PointTableModel.cpp