Isis Developer Reference: Isis::TableViewHeader Class Reference
Isis::TableViewHeader Class Reference
#include <TableViewHeader.h>
Public Slots
void handleFilterCountsChanged (int visibleTopLevelItemCount, int topLevelItemCount)
Updates the visible columns, and geometry when the filter count changes.
void updateHeaderOffset (int)
Updates the header offset.
void updateFilterProgress (int newProgress)
Updates the current filter progress value.
void updateFilterProgressRange (int min, int max)
Updates the range of the filter progress.
void updateRebuildProgress (int newProgress)
Updates the current rebuild progress value.
void updateRebuildProgressRange (int min, int max)
Updates the range of the rebuild progress.
void updateSortProgress (int newProgress)
Updates the current sort progress value.
void updateSortProgressRange (int min, int max)
Updates the range of the sort progress.
Signals
void columnResized (bool lastColumn)
void requestedGlobalSelection (bool select)
void requestedColumnSelection (int columnNum, bool select)
void sortingEnabled (bool)
Public Member Functions
TableViewHeader (AbstractTableModel *someModel)
Constructor.
virtual ~TableViewHeader ()
Destructor.
virtual void setColumns (TableColumnList *)
Sets the column list.
QSize minimumSizeHint () const
Returns the minimum size based on the font.
QSize sizeHint () const
Returns the minimum size based on the font.
void setModel (AbstractTableModel *someModel)
Connects the table model to the functions that handle changes.
Protected Member Functions
void mouseMoveEvent (QMouseEvent *event)
Overrides QWidget::mouseMoveEvent.
void mousePressEvent (QMouseEvent *event)
Overrides QWidget::mousePressEvent.
void mouseReleaseEvent (QMouseEvent *event)
Overrides QWidget::mouseReleaseEvent.
void paintEvent (QPaintEvent *event)
Repaints the header.
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
TableViewHeader()
Isis::TableViewHeader::TableViewHeader (AbstractTableModel * someModel) explicit
Constructor.
Parameters
someModel The table model
References setModel().
~TableViewHeader()
Isis::TableViewHeader::~TableViewHeader () virtual
Destructor.
Member Function Documentation
columnResized
void Isis::TableViewHeader::columnResized (bool lastColumn) signal
Referenced by mouseReleaseEvent().
handleFilterCountsChanged
void Isis::TableViewHeader::handleFilterCountsChanged (int visibleTopLevelItemCount, int topLevelItemCount) slot
Updates the visible columns, and geometry when the filter count changes.
Parameters
visibleTopLevelItemCount Number of visible top level items
topLevelItemCount Number of top level items
References Isis::TableColumn::getTitle(), Isis::TableColumnList::getVisibleColumns(), Isis::TableColumn::setWidth(), and Isis::TableColumnList::size().
Referenced by setModel().
minimumSizeHint()
QSize Isis::TableViewHeader::minimumSizeHint () const
Returns the minimum size based on the font.
Returns
QSize Minimum size allowed
Referenced by sizeHint().
mouseMoveEvent()
void Isis::TableViewHeader::mouseMoveEvent (QMouseEvent * event) protected
Overrides QWidget::mouseMoveEvent.
Parameters
event The mouse move event
References Isis::TableColumnList::getSortingOrder(), and Isis::TableColumnList::getVisibleColumns().
mousePressEvent()
void Isis::TableViewHeader::mousePressEvent (QMouseEvent * event) protected
Overrides QWidget::mousePressEvent.
Parameters
event The mouse press event
References Isis::TableColumnList::getVisibleColumns(), and requestedGlobalSelection().
mouseReleaseEvent()
void Isis::TableViewHeader::mouseReleaseEvent (QMouseEvent * event) protected
Overrides QWidget::mouseReleaseEvent.
Parameters
event The mouse release event
References columnResized(), Isis::TableColumnList::getSortingOrder(), Isis::TableColumn::getTitle(), Isis::TableColumnList::getVisibleColumns(), Isis::TableColumnList::raiseToTop(), Isis::TableColumn::setSortAscending(), Isis::TableColumnList::size(), Isis::TableColumn::sortAscending(), and Isis::AbstractTableModel::sortingOn().
paintEvent()
void Isis::TableViewHeader::paintEvent (QPaintEvent * event) protected
Repaints the header.
Parameters
event The paint event
requestedColumnSelection
void Isis::TableViewHeader::requestedColumnSelection (int columnNum, bool select) signal
requestedGlobalSelection
void Isis::TableViewHeader::requestedGlobalSelection (bool select) signal
Referenced by mousePressEvent(), and setModel().
setColumns()
void Isis::TableViewHeader::setColumns (TableColumnList * cols) virtual
Sets the column list.
Parameters
cols The column list
setModel()
void Isis::TableViewHeader::setModel (AbstractTableModel * someModel)
Connects the table model to the functions that handle changes.
Parameters
someModel The table model to connect
References Isis::AbstractTableModel::getColumns(), handleFilterCountsChanged(), requestedGlobalSelection(), Isis::TableColumnList::size(), updateFilterProgress(), updateFilterProgressRange(), updateRebuildProgress(), updateRebuildProgressRange(), updateSortProgress(), and updateSortProgressRange().
Referenced by TableViewHeader().
sizeHint()
QSize Isis::TableViewHeader::sizeHint () const
Returns the minimum size based on the font.
See also
minimumSizeHint
Returns
QSize Minimum size allowed
References minimumSizeHint().
sortingEnabled
void Isis::TableViewHeader::sortingEnabled (bool) signal
updateFilterProgress
void Isis::TableViewHeader::updateFilterProgress (int newProgress) slot
Updates the current filter progress value.
Parameters
newProgress New progress value
Referenced by setModel().
updateFilterProgressRange
void Isis::TableViewHeader::updateFilterProgressRange (int min, int max) slot
Updates the range of the filter progress.
Parameters
min The minimum progress
max The maximum progress
Referenced by setModel().
updateHeaderOffset
void Isis::TableViewHeader::updateHeaderOffset (int newOffset) slot
Updates the header offset.
Parameters
newOffset The new header offset
updateRebuildProgress
void Isis::TableViewHeader::updateRebuildProgress (int newProgress) slot
Updates the current rebuild progress value.
Parameters
newProgress New progress value
Referenced by setModel().
updateRebuildProgressRange
void Isis::TableViewHeader::updateRebuildProgressRange (int min, int max) slot
Updates the range of the rebuild progress.
Parameters
min The minimum progress
max The maximum progress
Referenced by setModel().
updateSortProgress
void Isis::TableViewHeader::updateSortProgress (int newProgress) slot
Updates the current sort progress value.
Parameters
newProgress New progress value
Referenced by setModel().
updateSortProgressRange
void Isis::TableViewHeader::updateSortProgressRange (int min, int max) slot
Updates the range of the sort progress.
Parameters
min The minimum progress
max The maximum progress
Referenced by setModel().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/TableViewHeader.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/TableViewHeader.cpp