Isis Developer Reference: Isis::QtExporter Class Reference
Isis::QtExporter Class Reference
High Level Cube I/O
Exports cubes into one of several formats with Qt facilities.
#include <QtExporter.h>
Public Member Functions
QtExporter (QString format)
Construct the Qt exporter.
virtual ~QtExporter ()
Destruct the exporter.
virtual void setGrayscale (ExportDescription &desc)
Set the input with the description generically, check the data size for a single-band image with the established dimensions, initialize the image with the Indexed8 format, and setup the color table from 0 to 256.
virtual void setRgb (ExportDescription &desc)
Set the input with the description generically, check the data size for a three-band image with the established dimensions, and initialize the image with the RGB32 format.
virtual void setRgba (ExportDescription &desc)
Set the input with the description generically, check the data size for a four-band image with the established dimensions, and initialize the image with the ARGB32 format.
virtual void write (FileName outputName, int quality=100, QString compression="none", UserInterface *ui=nullptr)
Let the base ImageExporter handle the generic black-box writing routine, then save the image to disk.
void operator() (vector< Buffer * > &in) const
The method for writing a line of input image data (with potentially several bands representing color channels) to the output image.
int samples () const
Number of samples (columns) in the output image.
int lines () const
Number of lines (rows) in the output image.
int bands () const
Number of bands (channels) in the output image.
double inputMinimum (int channel) const
Returns the input minimum for the given channel.
double inputMaximum (int channel) const
Returns the input maximum for the given channel.
void setOutputPixelRange (double outputPixelMinimum, double outputPixelMaximum)
Set the DN floor and ceiling for the exported image.
Static Public Member Functions
static bool canWriteFormat (QString format)
Returns true if the format is supported by QImageWriter.
static ImageExporter * fromFormat (QString format)
A static (factory) method for constructing an ImageExporter instance from an output format.
Protected Types
typedef void(ImageExporter::* WriteChannels) (vector< Buffer * > &in) const
Friendly alias for a method used to write a particular color channel.
Protected Member Functions
virtual void writeGrayscale (vector< Buffer * > &in) const
Write a line of grayscale data to the output image.
virtual void writeRgb (vector< Buffer * > &in) const
Write a line of RGB data to the output image.
virtual void writeRgba (vector< Buffer * > &in) const
Write a line of RGBA data to the output image.
void checkDataSize (BigInt samples, BigInt lines, int bands)
Checks that the data size for an image of the desired dimensions will be less than 2GB.
void setExtension (QString extension)
Sets the extension for the output image and generates the extension for the world file from it.
void setExportDescription (ExportDescription &desc)
Sets the description for the output image.
Cube * initializeProcess ()
Sets up the export process with the parameters described within the given description.
QString extension () const
Gets the extension for the output image.
ExportDescription & exportDescription () const
Gets the description for the output image.
ProcessExport & process () const
Get a reference to the process object, useful for subclasses to access and manipulate the process.
PixelType pixelType () const
Returns the pixel type.
virtual int outputPixelValue (double dn) const
Return the output clamped integer pixel value from the input double-precision DN.
Detailed Description
Exports cubes into one of several formats with Qt facilities.
Takes a series of single-banded Isis cubes and exports them into one of several possible standard image formats using Qt's QImage structure to handle reading the data into memory and setting individual pixel values. Set Qt's documentation on QImageWriter for a complete list of supported formats:
http://qt-project.org/doc/qt-4.8/qimagewriter.html#supportedImageFormats
While Qt can be used to export Isis cubes to TIFF images, it is generally recommended to use the TiffExporter class instead, which uses LibTIFF version 4 to import big TIFFs. Qt, as of version 4.8, can only import images <2GB in size.
Author
2012-04-03 Travis Addair
Member Typedef Documentation
WriteChannels
typedef void(ImageExporter::* Isis::ImageExporter::WriteChannels) (vector< Buffer * > &in) const protected inherited
Friendly alias for a method used to write a particular color channel.
Constructor & Destructor Documentation
QtExporter()
Isis::QtExporter::QtExporter (QString format)
Construct the Qt exporter.
Parameters
format The format to export to
References Isis::ImageExporter::setExtension().
~QtExporter()
Isis::QtExporter::~QtExporter () virtual
Destruct the exporter.
Member Function Documentation
bands()
int Isis::ImageExporter::bands () const inherited
Number of bands (channels) in the output image.
Returns
The depth of the output
Referenced by checkDataSize(), Isis::JP2Exporter::createBuffer(), Isis::TiffExporter::createBuffer(), Isis::TiffExporter::setBuffer(), Isis::JP2Exporter::write(), and Isis::TiffExporter::write().
canWriteFormat()
bool Isis::QtExporter::canWriteFormat (QString format) static
Returns true if the format is supported by QImageWriter.
Parameters
format Lowercase format abbreviation
Returns
True if supported in Qt, false otherwise
Referenced by Isis::ImageExporter::fromFormat().
checkDataSize()
void Isis::QtExporter::checkDataSize (BigInt samples, BigInt lines, int bands) protected
Checks that the data size for an image of the desired dimensions will be less than 2GB.
Parameters
samples Number of samples in the output
lines Number of lines in the output
bands Number of bands in the output
References _FILEINFO_, Isis::ImageExporter::bands(), Isis::ImageExporter::lines(), Isis::ImageExporter::samples(), Isis::toString(), and Isis::IException::User.
Referenced by setGrayscale(), setRgb(), and setRgba().
exportDescription()
ExportDescription & Isis::ImageExporter::exportDescription () const protected inherited
Gets the description for the output image.
Returns
The export description
extension()
QString Isis::ImageExporter::extension () const protected inherited
Gets the extension for the output image.
Returns
The extension for the output image
Referenced by Isis::JP2Exporter::write(), write(), and Isis::TiffExporter::write().
fromFormat()
ImageExporter * Isis::ImageExporter::fromFormat (QString format) static inherited
A static (factory) method for constructing an ImageExporter instance from an output format.
The specific subclass of the returned instance is determined from the desired output image format provided. Each subclass has knowledge of whether or not it can write a particular format. Because the ability to export an image format is not mutually exclusive amongst exporters, the order of condieration here matters. For example, using a TIFF exporter takes precedence over a Qt exporter for TIFF images, because the former can process cubes greater than 2GB while the latter cannot. It is the caller's responsibility to delete the exporter instance when they are finished with it.
Parameters
format The format for the output image to be created
Returns
A pointer to the instantiated exporter owned by the caller
References _FILEINFO_, Isis::JP2Exporter::canWriteFormat(), canWriteFormat(), Isis::TiffExporter::canWriteFormat(), and Isis::IException::Programmer.
initializeProcess()
Cube * Isis::ImageExporter::initializeProcess () protected inherited
Sets up the export process with the parameters described within the given description.
This method determines determines whether to write the data as grayscale, RGB, or RGBA. It then opens a cube for retrieving the input data and establishing the dimensions of the output image. Next, the ProcessExport format is set to BIL and the ProcessExport output pixel type, output valid data range, and output null are set based on the given export description. Last, the absolute output pixel range is set based on the given description (this is the smallest and largest allowed pixel values in the output, including "special" pixel values).
Returns
A cube pointer to the first channel created, owned by the process
References _FILEINFO_, Isis::ProcessExport::BIL, Isis::Cube::lineCount(), Isis::IException::Programmer, Isis::Cube::sampleCount(), Isis::ProcessExport::setFormat(), Isis::ProcessExport::SetOutputNull(), Isis::ProcessExport::SetOutputRange(), Isis::ProcessExport::SetOutputType(), Isis::ImageExporter::writeGrayscale(), Isis::ImageExporter::writeRgb(), and Isis::ImageExporter::writeRgba().
inputMaximum()
double Isis::ImageExporter::inputMaximum (int channel) const inherited
Returns the input maximum for the given channel.
Any value of max in the input cube will be mapped to the output max of the output channel.
Parameters
channel Index of the channel within the process
Returns
The maximum DN in the input mapped to the maximum of the output
inputMinimum()
double Isis::ImageExporter::inputMinimum (int channel) const inherited
Returns the input minimum for the given channel.
Any value of min in the input cube will be mapped to the output min of the output channel.
Parameters
channel Index of the channel within the process
Returns
The minimum DN in the input mapped to the minimum of the output
lines()
int Isis::ImageExporter::lines () const inherited
Number of lines (rows) in the output image.
Returns
The height of the output
Referenced by checkDataSize(), setGrayscale(), setRgb(), setRgba(), Isis::JP2Exporter::write(), and Isis::TiffExporter::write().
operator()()
void Isis::ImageExporter::operator() (vector< Buffer * > & in) const inherited
The method for writing a line of input image data (with potentially several bands representing color channels) to the output image.
It is called for each line of data in the input images (provides a vector containing the same line from each single-band input image). Enables the exporter to be used as a functor in a custom ProcessExport routine, bypassing the black-box write() method entirely.
Parameters
in Vector containing a line of input data from each input channel
outputPixelValue()
int Isis::ImageExporter::outputPixelValue (double dn) const protected virtual inherited
Return the output clamped integer pixel value from the input double-precision DN.
Parameters
dn The input DN
Returns
The pixel value for the output
Referenced by writeGrayscale(), Isis::StreamExporter::writeGrayscale(), writeRgb(), Isis::StreamExporter::writeRgb(), writeRgba(), and Isis::StreamExporter::writeRgba().
pixelType()
PixelType Isis::ImageExporter::pixelType () const protected inherited
Returns the pixel type.
Defaults to None if not set by the user.
Returns
The pixel type: {None, UnsignedByte, SignedWord, UnsignedWord}
References Isis::None.
Referenced by Isis::JP2Exporter::createBuffer(), Isis::TiffExporter::createBuffer(), Isis::JP2Exporter::setBuffer(), Isis::TiffExporter::setBuffer(), Isis::JP2Exporter::write(), Isis::TiffExporter::write(), and Isis::JP2Exporter::writeLine().
process()
ProcessExport & Isis::ImageExporter::process () const protected inherited
Get a reference to the process object, useful for subclasses to access and manipulate the process.
Returns
A reference to the process object
samples()
int Isis::ImageExporter::samples () const inherited
Number of samples (columns) in the output image.
Returns
The width of the output
Referenced by checkDataSize(), Isis::JP2Exporter::createBuffer(), Isis::TiffExporter::createBuffer(), setGrayscale(), setRgb(), setRgba(), Isis::JP2Exporter::write(), and Isis::TiffExporter::write().
setExportDescription()
void Isis::ImageExporter::setExportDescription (ExportDescription & desc) protected inherited
Sets the description for the output image.
Parameters
desc The export description
setExtension()
void Isis::ImageExporter::setExtension (QString extension) protected inherited
Sets the extension for the output image and generates the extension for the world file from it.
Parameters
extension The extension for the output image
Referenced by Isis::JP2Exporter::JP2Exporter(), QtExporter(), and Isis::TiffExporter::TiffExporter().
setGrayscale()
void Isis::QtExporter::setGrayscale (ExportDescription & desc) virtual
Set the input with the description generically, check the data size for a single-band image with the established dimensions, initialize the image with the Indexed8 format, and setup the color table from 0 to 256.
Parameters
desc Export description containing necessary channel information
Implements Isis::ImageExporter.
References checkDataSize(), Isis::ImageExporter::lines(), and Isis::ImageExporter::samples().
setOutputPixelRange()
void Isis::ImageExporter::setOutputPixelRange (double outputPixelMinimum, double outputPixelMaximum) inherited
Set the DN floor and ceiling for the exported image.
All DNs less than the min will be set to the min in the exported image. Similarly, all DNs greater than the max will be set to the max in the exported image.
Note: These values may be "special". For example, if Null pixels are exported to 0.0 and the minimum valid pixels are exported to 2.0, then 0.0 should be passed in for the value of the min parameter.
Parameters
min The absolute minimum output DN value.
max The absolute maximum output DN value.
setRgb()
void Isis::QtExporter::setRgb (ExportDescription & desc) virtual
Set the input with the description generically, check the data size for a three-band image with the established dimensions, and initialize the image with the RGB32 format.
Parameters
desc Export description containing necessary channel information
Implements Isis::ImageExporter.
References checkDataSize(), Isis::ImageExporter::lines(), and Isis::ImageExporter::samples().
setRgba()
void Isis::QtExporter::setRgba (ExportDescription & desc) virtual
Set the input with the description generically, check the data size for a four-band image with the established dimensions, and initialize the image with the ARGB32 format.
Parameters
desc Export description containing necessary channel information
Implements Isis::ImageExporter.
References checkDataSize(), Isis::ImageExporter::lines(), and Isis::ImageExporter::samples().
write()
void Isis::QtExporter::write (FileName outputName, int quality = 100, QString compression = "none", UserInterface * ui = nullptr) virtual
Let the base ImageExporter handle the generic black-box writing routine, then save the image to disk.
Parameters
outputName The filename of the output cube
quality The quality of the output.
compression The compression algorithm used. Not supported for Qt.
Reimplemented from Isis::ImageExporter.
References _FILEINFO_, Isis::FileName::addExtension(), Isis::FileName::expanded(), Isis::ImageExporter::extension(), Isis::IException::Programmer, and Isis::ImageExporter::write().
writeGrayscale()
void Isis::QtExporter::writeGrayscale (vector< Buffer * > & in) const protected virtual
Write a line of grayscale data to the output image.
Parameters
in Vector containing a single grayscale input line
Implements Isis::ImageExporter.
References _FILEINFO_, Isis::Buffer::Line(), Isis::ImageExporter::outputPixelValue(), Isis::Buffer::SampleDimension(), and Isis::IException::User.
writeRgb()
void Isis::QtExporter::writeRgb (vector< Buffer * > & in) const protected virtual
Write a line of RGB data to the output image.
Parameters
in Vector containing three input lines (red, green, blue)
Implements Isis::ImageExporter.
References Isis::Buffer::Line(), Isis::ImageExporter::outputPixelValue(), and Isis::Buffer::SampleDimension().
writeRgba()
void Isis::QtExporter::writeRgba (vector< Buffer * > & in) const protected virtual
Write a line of RGBA data to the output image.
Parameters
in Vector containing four input lines (red, green, blue, alpha)
Implements Isis::ImageExporter.
References Isis::Buffer::Line(), Isis::ImageExporter::outputPixelValue(), and Isis::Buffer::SampleDimension().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/QtExporter/QtExporter.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/QtExporter/QtExporter.cpp