Isis Developer Reference: Isis::PolygonSeederFactory Class Reference
Isis::PolygonSeederFactory Class Reference
Pattern Matching
This class is used to create PolygonSeeder objects.
#include <PolygonSeederFactory.h>
Static Public Member Functions
static PolygonSeeder * Create (Pvl &pvl)
Create a PolygonSeeder object using a PVL specification.
Detailed Description
This class is used to create PolygonSeeder objects.
Applications which use autoseeding of points in polygons can use different techniques such as Grid or ????. If this factory is given a Pvl object which contains a PolygonSeeder definition it will create that specific instance of the class. For example,
Object = PolygonSeeder
  Group = Algorithm
    Name = Grid
    ...
  EndGroup
  ...
EndObject
End
Will create a GridPolygonSeeder object (which is derived from PolygonSeeder). The simplest way to create an PolygonSeeder class is to use the static Create method
Pvl p("myPolygonSeeder.pvl");
PolygonSeeder *ps = PolygonSeederFactory::Create(p);
Author
2006-01-20 Stuart Sides
Member Function Documentation
Create()
PolygonSeeder * Isis::PolygonSeederFactory::Create (Pvl & pvl) static
Create a PolygonSeeder object using a PVL specification.
An example of the PVL required for this is:
Object = AutoSeed
  Group = PolygonSeederAlgorithm
    Name      = Grid
    Tolerance = 0.7
  EndGroup
  Group = InterestOperatorAlgorithm
    Name      = StandardDeviation
    Tolerance = 10
  EndGroup
EndObject
Parameters
pvl The pvl object containing the PolygonSeeder specification
References Isis::FileName::fileExists(), Isis::PvlObject::findGroup(), Isis::Plugin::GetPlugin(), Isis::Pvl::read(), and Isis::PvlObject::Traverse.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/PolygonSeederFactory/PolygonSeederFactory.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/PolygonSeederFactory/PolygonSeederFactory.cpp