Isis Developer Reference: Isis::OriginalXmlLabel Class Reference
Isis::OriginalXmlLabel Class Reference
Low Level Cube I/O
Read and store original Xml labels.
#include <OriginalXmlLabel.h>
Public Member Functions
OriginalXmlLabel ()
Constructors a default OriginalXmlLabel with an empty label.
OriginalXmlLabel (const QString &file)
Constructs an OriginalXmlLabel from a cube label file.
OriginalXmlLabel (Blob &blob)
Constructs an OriginalXmlLabel from a blob.
~OriginalXmlLabel ()
Destructor.
Blob toBlob () const
Serialize the OriginalXmlLabel to a Blob.
void fromBlob (Isis::Blob blob)
void readFromXmlFile (const FileName &xmlFileName)
Read the original label from an Xml file.
const QDomDocument & ReturnLabels () const
Returns the original Xml label.
Protected Member Functions
void ReadData (std::istream &stream)
Detailed Description
Read and store original Xml labels.
This class provides a means to read and store the Xml labels from the original source.
Author
2017-01-30 Jesse Mapel
Constructor & Destructor Documentation
OriginalXmlLabel() [1/3]
Isis::OriginalXmlLabel::OriginalXmlLabel ()
Constructors a default OriginalXmlLabel with an empty label.
OriginalXmlLabel() [2/3]
Isis::OriginalXmlLabel::OriginalXmlLabel (const QString & file)
Constructs an OriginalXmlLabel from a cube label file.
Parameters
file Xml file to read labels from
References Isis::Blob::Read().
OriginalXmlLabel() [3/3]
Isis::OriginalXmlLabel::OriginalXmlLabel (Isis::Blob & blob)
Constructs an OriginalXmlLabel from a blob.
Parameters
blob Blob from which to create the OriginalXmlLabel
~OriginalXmlLabel()
Isis::OriginalXmlLabel::~OriginalXmlLabel ()
Destructor.
Member Function Documentation
fromBlob()
void Isis::OriginalXmlLabel::fromBlob (Isis::Blob blob)
References _FILEINFO_, Isis::Blob::getBuffer(), Isis::Blob::Size(), and Isis::toString().
ReadData()
void Isis::OriginalXmlLabel::ReadData (std::istream & stream) protected
readFromXmlFile()
void Isis::OriginalXmlLabel::readFromXmlFile (const FileName & xmlFileName)
Read the original label from an Xml file.
Parameters
FileName The Xml file containing the original label.
Exceptions
IException::Io "Could not open label file."
IException::Unknown "XML read/parse error in file."
References _FILEINFO_, Isis::FileName::expanded(), and Isis::toString().
ReturnLabels()
const QDomDocument & Isis::OriginalXmlLabel::ReturnLabels () const
Returns the original Xml label.
Returns
QDomDocument The parsed original label
toBlob()
Blob Isis::OriginalXmlLabel::toBlob () const
Serialize the OriginalXmlLabel to a Blob.
Returns
Blob
References Isis::ByteOrderName(), Isis::IsLsb(), Isis::Blob::Label(), Isis::Lsb, Isis::Msb, and Isis::Blob::setData().
Referenced by Isis::Cube::write().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/OriginalXmlLabel/OriginalXmlLabel.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/OriginalXmlLabel/OriginalXmlLabel.cpp