Isis Developer Reference: Isis::PvlFormat Class Reference
Isis::PvlFormat Class Reference
Parsing
Formats a Pvl name value pair to Isis standards.
#include <PvlFormat.h>
Public Member Functions
PvlFormat ()
PvlFormat (const QString &file)
PvlFormat (Pvl &keymap)
virtual ~PvlFormat ()
void add (const QString &file)
void add (Pvl &keymap)
void setCharLimit (const unsigned int limit)
Sets the maximum number of characters in a keyword value that can be printed to a line before it wraps to the next line.
unsigned int charLimit () const
Retrieves the maximum number of characters in a keyword value that can be printed to a line before it wraps to the next line.
virtual QString formatValue (const PvlKeyword &keyword, int valueIndex=0)
virtual QString formatName (const PvlKeyword &keyword)
virtual QString formatEnd (const QString name, const PvlKeyword &keyword)
virtual QString formatEOL ()
virtual KeywordType type (const PvlKeyword &keyword)
virtual int accuracy (const PvlKeyword &keyword)
Protected Member Functions
virtual QString addQuotes (const QString value)
bool isSingleUnit (const PvlKeyword &keyword)
Returns true if the units are the same for all value in the keyword otherwise it returns false.
Protected Attributes
QString m_keywordMapFile
Pvl m_keywordMap
unsigned int m_charLimit
Maximum number of characters on a single line of a keyword value.
Detailed Description
Formats a Pvl name value pair to Isis standards.
This class is used to format a single PVL keyword-value pair using normal Isis formatting. The class serves as a base class for others to override and implement their own formatting.
This class uses a Pvl or Pvl formatted file to populate its internal data structure. This structure is used to lookup the type of a keyword and/or other information for another Pvl{Object|Group|Keyword}. The format of the file or Pvl is:
NAME=TYPE
NAME2=(TYPE,PLACES)
Example:
DESCRIPTION = STRING
MinimumLatitude = (REAL,5)
BITTYPE = ENUM
RECORDS = INTEGER
Where NAME is the name of a keyword in the Pvl to be formatted. TYPE is the type of keyword (STRING,BOOL,INTEGER,REAL,OCTAL,HEX,BINARY,ENUM) (see ToKeywordType). PLACES is the number of digits to the right of the decimal place for a keyword of TYPE REAL.
NOTE: The capabilities to use this Pvl are not implemented in this base class. They are provided as a convience for child classes only. This class only implements the normal Isis foramatting, which is not dependent on the type of the keyword. It is dependent on value of the keyword.
Author
2006-09-05 Stuart Sides
Constructor & Destructor Documentation
PvlFormat() [1/3]
Isis::PvlFormat::PvlFormat ()
PvlFormat() [2/3]
Isis::PvlFormat::PvlFormat (const QString & file)
PvlFormat() [3/3]
Isis::PvlFormat::PvlFormat (Pvl & keymap)
~PvlFormat()
virtual Isis::PvlFormat::~PvlFormat () inline virtual
Member Function Documentation
accuracy()
int Isis::PvlFormat::accuracy (const PvlKeyword & keyword) virtual
References Isis::PvlKeyword::name(), Isis::PvlKeyword::size(), and Isis::toInt().
Referenced by Isis::PvlFormatPds::formatValue().
add() [1/2]
void Isis::PvlFormat::add (const QString & file)
References _FILEINFO_.
Referenced by Isis::ProcessExportPds::CreateImageLabel(), Isis::ProcessExportPds::FixedJP2ImageRoot(), Isis::ProcessExportPds::StandardImageImage(), Isis::ProcessExportPds::StandardJP2Image(), and Isis::ProcessExportPds::StreamJP2ImageRoot().
add() [2/2]
void Isis::PvlFormat::add (Pvl & keymap)
References Isis::PvlKeyword::addValue(), Isis::PvlContainer::keywords(), Isis::PvlKeyword::name(), and Isis::PvlKeyword::size().
addQuotes()
QString Isis::PvlFormat::addQuotes (const QString value) protected virtual
Reimplemented in Isis::PvlFormatPds.
Referenced by Isis::PvlFormatPds::formatUnknown().
charLimit()
unsigned int Isis::PvlFormat::charLimit () const inline
Retrieves the maximum number of characters in a keyword value that can be printed to a line before it wraps to the next line.
By default, the limit is set to 80 characters.
Returns
unsigned int Maximum number of characters.
References m_charLimit.
Referenced by Isis::PvlKeyword::writeWithWrap().
formatEnd()
QString Isis::PvlFormat::formatEnd (const QString name, const PvlKeyword & keyword) virtual
Reimplemented in Isis::PvlFormatPds.
formatEOL()
virtual QString Isis::PvlFormat::formatEOL () inline virtual
Reimplemented in Isis::PvlFormatPds.
Referenced by Isis::Pvl::append(), Isis::operator<<(), Isis::Pvl::write(), and Isis::PvlKeyword::writeWithWrap().
formatName()
QString Isis::PvlFormat::formatName (const PvlKeyword & keyword) virtual
Reimplemented in Isis::PvlFormatPds.
References Isis::PvlKeyword::name().
formatValue()
QString Isis::PvlFormat::formatValue (const PvlKeyword & keyword, int valueIndex = 0) virtual
Reimplemented in Isis::PvlFormatPds.
References Isis::PvlKeyword::size(), and Isis::PvlKeyword::unit().
isSingleUnit()
bool Isis::PvlFormat::isSingleUnit (const PvlKeyword & keyword) protected
Returns true if the units are the same for all value in the keyword otherwise it returns false.
Parameters
keyword The PvlKeyword to be formatted
References Isis::PvlKeyword::size(), Isis::PvlKeyword::stringEqual(), and Isis::PvlKeyword::unit().
setCharLimit()
void Isis::PvlFormat::setCharLimit (const unsigned int limit) inline
Sets the maximum number of characters in a keyword value that can be printed to a line before it wraps to the next line.
By default, the limit is set to 80 characters.
Parameters
limit The new character limit.
References m_charLimit.
type()
KeywordType Isis::PvlFormat::type (const PvlKeyword & keyword) virtual
References Isis::PvlKeyword::name(), Isis::NoTypeKeyword, and Isis::toKeywordType().
Referenced by Isis::PvlFormatPds::formatValue().
Member Data Documentation
m_charLimit
unsigned int Isis::PvlFormat::m_charLimit protected
Maximum number of characters on a single line of a keyword value.
Referenced by charLimit(), and setCharLimit().
m_keywordMap
Pvl Isis::PvlFormat::m_keywordMap protected
m_keywordMapFile
QString Isis::PvlFormat::m_keywordMapFile protected
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/PvlFormat/PvlFormat.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/PvlFormat/PvlFormat.cpp