Isis Developer Reference: Isis::GuiBooleanParameter Class Reference
Isis::GuiBooleanParameter Class Reference
#include <GuiBooleanParameter.h>
Public Types
enum ParameterType {
IntegerWidget , DoubleWidget , StringWidget , ListWidget ,
FileNameWidget , CubeWidget , BooleanWidget , ComboWidget
}
Signals
void ValueChanged ()
void HelperTrigger (const QString &)
Public Member Functions
GuiBooleanParameter (QGridLayout *grid, UserInterface &ui, int group, int param)
~GuiBooleanParameter ()
QString Value ()
void Set (QString newValue)
virtual std::vector< QString > Exclusions ()
Return list of current exclusions.
bool IsModified ()
Return if the parameter value is different from the default value.
QString Name () const
Return the name of the parameter.
void SetToDefault ()
Change the parameter to the default value.
void SetToCurrent ()
Change the parameter to the current user interface value.
void SetEnabled (bool enabled, bool isParentCombo=false)
Enable or disable the parameter.
bool IsEnabled () const
Is the parameter enabled.
void Update ()
Update the value on the GUI with the value in the UI.
void RememberWidget (QWidget *w)
Add widgets to a list for enabling/disabling.
QWidget * AddHelpers (QObject *lo)
Sets up helper button.
ParameterType Type ()
Protected Attributes
QToolButton * p_fileButton
QLineEdit * p_lineEdit
int p_group
int p_param
QString p_name
UserInterface * p_ui
QLabel * p_label
QList< QWidget * > p_widgetList
ParameterType p_type
Detailed Description
Author
????-??-?? Unknown
Member Enumeration Documentation
ParameterType
enum Isis::GuiParameter::ParameterType inherited
Enumerator
IntegerWidget
DoubleWidget
StringWidget
ListWidget
FileNameWidget
CubeWidget
BooleanWidget
ComboWidget
Constructor & Destructor Documentation
GuiBooleanParameter()
Isis::GuiBooleanParameter::GuiBooleanParameter (QGridLayout * grid, UserInterface & ui, int group, int param)
References Isis::GuiParameter::AddHelpers(), Isis::GuiParameter::BooleanWidget, IsisAml::HelpersSize(), Isis::GuiParameter::p_type, Isis::GuiParameter::p_ui, IsisAml::ParamBrief(), Isis::GuiParameter::RememberWidget(), and Isis::GuiParameter::ValueChanged().
~GuiBooleanParameter()
Isis::GuiBooleanParameter::~GuiBooleanParameter ()
Member Function Documentation
AddHelpers()
QWidget * Isis::GuiParameter::AddHelpers (QObject * lo) inherited
Sets up helper button.
References _FILEINFO_, Isis::FileName::expanded(), IsisAml::HelperBrief(), IsisAml::HelperButtonName(), IsisAml::HelperDescription(), IsisAml::HelperFunction(), IsisAml::HelperIcon(), IsisAml::HelpersSize(), Isis::GuiParameter::HelperTrigger(), Isis::GuiParameter::p_group, Isis::GuiParameter::p_param, Isis::GuiParameter::p_ui, Isis::IException::Programmer, and Isis::GuiParameter::RememberWidget().
Referenced by GuiBooleanParameter(), Isis::GuiDoubleParameter::GuiDoubleParameter(), Isis::GuiFileNameParameter::GuiFileNameParameter(), Isis::GuiIntegerParameter::GuiIntegerParameter(), Isis::GuiListParameter::GuiListParameter(), and Isis::GuiStringParameter::GuiStringParameter().
Exclusions()
std::vector< QString > Isis::GuiBooleanParameter::Exclusions () virtual
Return list of current exclusions.
Reimplemented from Isis::GuiParameter.
References Isis::GuiParameter::p_group, Isis::GuiParameter::p_param, Isis::GuiParameter::p_ui, IsisAml::ParamExclude(), IsisAml::ParamExcludeSize(), IsisAml::ParamInclude(), IsisAml::ParamIncludeSize(), and Value().
HelperTrigger
void Isis::GuiParameter::HelperTrigger (const QString &) signal inherited
Referenced by Isis::GuiParameter::AddHelpers().
IsEnabled()
bool Isis::GuiParameter::IsEnabled () const inline inherited
Is the parameter enabled.
References Isis::GuiParameter::p_label.
Referenced by IsModified(), and Isis::GuiParameter::IsModified().
IsModified()
bool Isis::GuiBooleanParameter::IsModified () virtual
Return if the parameter value is different from the default value.
Reimplemented from Isis::GuiParameter.
References Isis::GuiParameter::IsEnabled(), Isis::GuiParameter::p_group, Isis::GuiParameter::p_param, Isis::GuiParameter::p_ui, IsisAml::ParamDefault(), and Value().
Name()
QString Isis::GuiParameter::Name () const inline inherited
Return the name of the parameter.
References Isis::GuiParameter::p_name.
RememberWidget()
void Isis::GuiParameter::RememberWidget (QWidget * w) inherited
Add widgets to a list for enabling/disabling.
References Isis::GuiParameter::p_widgetList.
Referenced by Isis::GuiParameter::AddHelpers(), GuiBooleanParameter(), Isis::GuiComboBoxParameter::GuiComboBoxParameter(), Isis::GuiDoubleParameter::GuiDoubleParameter(), Isis::GuiFileNameParameter::GuiFileNameParameter(), Isis::GuiIntegerParameter::GuiIntegerParameter(), Isis::GuiListParameter::GuiListParameter(), and Isis::GuiStringParameter::GuiStringParameter().
Set()
void Isis::GuiBooleanParameter::Set (QString newValue) virtual
Implements Isis::GuiParameter.
References Isis::GuiParameter::p_ui, IsisAml::StringToBool(), and Isis::GuiParameter::ValueChanged().
SetEnabled()
void Isis::GuiParameter::SetEnabled (bool enabled, bool isParentCombo = false) inherited
Enable or disable the parameter.
References Isis::GuiParameter::ComboWidget, Isis::GuiParameter::p_label, Isis::GuiParameter::p_type, and Isis::GuiParameter::p_widgetList.
SetToCurrent()
void Isis::GuiParameter::SetToCurrent () inherited
Change the parameter to the current user interface value.
References IsisAml::GetAsString(), Isis::GuiParameter::p_name, Isis::GuiParameter::p_ui, Isis::GuiParameter::Set(), Isis::GuiParameter::SetToDefault(), and IsisAml::WasEntered().
SetToDefault()
void Isis::GuiParameter::SetToDefault () inherited
Change the parameter to the default value.
References Isis::GuiParameter::p_group, Isis::GuiParameter::p_param, Isis::GuiParameter::p_ui, IsisAml::ParamDefault(), IsisAml::ParamInternalDefault(), and Isis::GuiParameter::Set().
Referenced by Isis::GuiParameter::SetToCurrent().
Type()
ParameterType Isis::GuiParameter::Type () inline inherited
References Isis::GuiParameter::p_type.
Update()
void Isis::GuiParameter::Update () inherited
Update the value on the GUI with the value in the UI.
References IsisAml::GetAsString(), Isis::GuiParameter::p_group, Isis::GuiParameter::p_name, Isis::GuiParameter::p_param, Isis::GuiParameter::p_ui, IsisAml::ParamDefault(), IsisAml::ParamInternalDefault(), Isis::GuiParameter::Set(), and IsisAml::WasEntered().
Referenced by Isis::Gui::Gui().
Value()
QString Isis::GuiBooleanParameter::Value () virtual
Implements Isis::GuiParameter.
Referenced by Exclusions(), and IsModified().
ValueChanged
void Isis::GuiParameter::ValueChanged () signal inherited
Referenced by GuiBooleanParameter(), Isis::GuiComboBoxParameter::GuiComboBoxParameter(), Isis::GuiDoubleParameter::GuiDoubleParameter(), Isis::GuiFileNameParameter::GuiFileNameParameter(), Isis::GuiIntegerParameter::GuiIntegerParameter(), Isis::GuiListParameter::GuiListParameter(), Isis::GuiStringParameter::GuiStringParameter(), Set(), Isis::GuiComboBoxParameter::Set(), and Isis::GuiListParameter::Set().
Member Data Documentation
p_fileButton
QToolButton* Isis::GuiParameter::p_fileButton protected inherited
Referenced by Isis::GuiCubeParameter::GuiCubeParameter(), Isis::GuiFileNameParameter::GuiFileNameParameter(), Isis::GuiParameter::GuiParameter(), and Isis::GuiFileNameParameter::SelectFile().
p_group
int Isis::GuiParameter::p_group protected inherited
Referenced by Isis::GuiParameter::AddHelpers(), Exclusions(), Isis::GuiComboBoxParameter::Exclusions(), Isis::GuiListParameter::Exclusions(), Isis::GuiParameter::GuiParameter(), IsModified(), Isis::GuiParameter::IsModified(), Isis::GuiFileNameParameter::SelectFile(), Isis::GuiComboBoxParameter::Set(), Isis::GuiListParameter::Set(), Isis::GuiParameter::SetToDefault(), Isis::GuiParameter::Update(), Isis::GuiComboBoxParameter::Value(), and Isis::GuiListParameter::Value().
p_label
QLabel* Isis::GuiParameter::p_label protected inherited
Referenced by Isis::GuiComboBoxParameter::GuiComboBoxParameter(), Isis::GuiListParameter::GuiListParameter(), Isis::GuiParameter::GuiParameter(), Isis::GuiParameter::IsEnabled(), and Isis::GuiParameter::SetEnabled().
p_lineEdit
QLineEdit* Isis::GuiParameter::p_lineEdit protected inherited
Referenced by Isis::GuiFileNameParameter::GuiFileNameParameter(), Isis::GuiParameter::GuiParameter(), Isis::GuiFileNameParameter::SelectFile(), Isis::GuiFileNameParameter::Set(), and Isis::GuiFileNameParameter::Value().
p_name
QString Isis::GuiParameter::p_name protected inherited
Referenced by Isis::GuiParameter::GuiParameter(), Isis::GuiParameter::Name(), Isis::GuiParameter::SetToCurrent(), and Isis::GuiParameter::Update().
p_param
int Isis::GuiParameter::p_param protected inherited
Referenced by Isis::GuiParameter::AddHelpers(), Exclusions(), Isis::GuiComboBoxParameter::Exclusions(), Isis::GuiListParameter::Exclusions(), Isis::GuiParameter::GuiParameter(), IsModified(), Isis::GuiParameter::IsModified(), Isis::GuiFileNameParameter::SelectFile(), Isis::GuiComboBoxParameter::Set(), Isis::GuiListParameter::Set(), Isis::GuiParameter::SetToDefault(), Isis::GuiParameter::Update(), Isis::GuiComboBoxParameter::Value(), and Isis::GuiListParameter::Value().
p_type
ParameterType Isis::GuiParameter::p_type protected inherited
Referenced by GuiBooleanParameter(), Isis::GuiComboBoxParameter::GuiComboBoxParameter(), Isis::GuiCubeParameter::GuiCubeParameter(), Isis::GuiDoubleParameter::GuiDoubleParameter(), Isis::GuiFileNameParameter::GuiFileNameParameter(), Isis::GuiIntegerParameter::GuiIntegerParameter(), Isis::GuiListParameter::GuiListParameter(), Isis::GuiStringParameter::GuiStringParameter(), Isis::GuiParameter::SetEnabled(), and Isis::GuiParameter::Type().
p_ui
UserInterface* Isis::GuiParameter::p_ui protected inherited
Referenced by Isis::GuiParameter::AddHelpers(), Exclusions(), Isis::GuiComboBoxParameter::Exclusions(), Isis::GuiListParameter::Exclusions(), GuiBooleanParameter(), Isis::GuiDoubleParameter::GuiDoubleParameter(), Isis::GuiFileNameParameter::GuiFileNameParameter(), Isis::GuiIntegerParameter::GuiIntegerParameter(), Isis::GuiListParameter::GuiListParameter(), Isis::GuiParameter::GuiParameter(), Isis::GuiStringParameter::GuiStringParameter(), IsModified(), Isis::GuiParameter::IsModified(), Isis::GuiFileNameParameter::SelectFile(), Set(), Isis::GuiComboBoxParameter::Set(), Isis::GuiListParameter::Set(), Isis::GuiParameter::SetToCurrent(), Isis::GuiParameter::SetToDefault(), Isis::GuiParameter::Update(), Isis::GuiComboBoxParameter::Value(), and Isis::GuiListParameter::Value().
p_widgetList
QList<QWidget *> Isis::GuiParameter::p_widgetList protected inherited
Referenced by Isis::GuiParameter::RememberWidget(), Isis::GuiParameter::SetEnabled(), and Isis::GuiParameter::~GuiParameter().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Gui/GuiBooleanParameter.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Gui/GuiBooleanParameter.cpp