Isis Developer Reference: Isis::MosaicZoomTool Class Reference
Isis::MosaicZoomTool Class Reference
Handles zoom operations for Isis qt apps.
#include <MosaicZoomTool.h>
Public Slots
void zoomIn2X (QPointF center=QPointF())
Zooms in 2 times.
void zoomOut2X (QPointF center=QPointF())
Zoom out 2 times.
void zoomActual (QPointF center=QPointF())
Zoom back to 1 to 1.
void zoomFit ()
Fits the in the graphics view.
void zoomFitWidth ()
Slot for the "Fit to Width" menu item on the Fit button.
void zoomFitHeight ()
Slot for the "Fit to Heighth" menu item on the Fit button.
void zoomManual ()
This method zooms by the value input in the line edit next to the zoom tools.
void activate (bool)
Activates the tool.
Signals
void activated (bool)
Public Member Functions
MosaicZoomTool (MosaicSceneWidget *)
MosaicZoomTool constructor.
void updateResolutionBox ()
Updates the text in the screen resolution display box to the current screen resolution, in meters per pixel.
QList< QAction * > getViewActions ()
bool isActive () const
Returns the activeness of this toool.
QPixmap getIcon (QString iconName) const
returns the path to the icon directory.
virtual void addTo (QMenu *menu)
virtual void addTo (ToolPad *toolPad)
virtual void addTo (QToolBar *toolBar)
virtual PvlObject toPvl () const
virtual void fromPvl (const PvlObject &obj)
virtual QString projectPvlObjectName () const
Protected Slots
void updateTool ()
This method updates the line edits text to the correct zoom value.
Protected Member Functions
QAction * getPrimaryAction ()
This method returns an action that is used to activate this tool.
QWidget * getToolBarWidget ()
Creates the widget to add to the tool bar.
void mouseButtonRelease (QPointF, Qt::MouseButton s)
void mouseWheel (QPointF, int)
void rubberBandComplete (QRectF r, Qt::MouseButton s)
This method is called when the RubberBandTool is complete.
virtual void mouseEnter ()
virtual void mouseMove (QPointF)
virtual void mouseLeave ()
virtual void mouseDoubleClick (QPointF)
virtual void mouseButtonPress (QPointF, Qt::MouseButton s)
void toolBarDestroyed (QObject *obj)
MosaicSceneWidget * getWidget ()
Detailed Description
Handles zoom operations for Isis qt apps.
Author
????-??-?? Stacy Alley
Constructor & Destructor Documentation
MosaicZoomTool()
Isis::MosaicZoomTool::MosaicZoomTool (MosaicSceneWidget * scene)
MosaicZoomTool constructor.
Parameters
parent
References Isis::MosaicTool::getIcon(), zoomFit(), zoomIn2X(), and zoomOut2X().
Member Function Documentation
activate
void Isis::MosaicTool::activate (bool on) slot inherited
Activates the tool.
Parameters
on
References Isis::MosaicTool::activated().
Referenced by Isis::MosaicTool::addTo().
activated
void Isis::MosaicTool::activated (bool) signal inherited
Referenced by Isis::MosaicTool::activate(), Isis::MosaicGridTool::getToolBarWidget(), and Isis::MosaicTool::MosaicTool().
addTo() [1/3]
virtual void Isis::MosaicTool::addTo (QMenu * menu) inline virtual inherited
Referenced by Isis::MosaicSceneWidget::addTo(), Isis::MosaicSceneWidget::getControlNetHelp(), and Isis::MosaicSceneWidget::getGridHelp().
addTo() [2/3]
void Isis::MosaicTool::addTo (QToolBar * toolBar) virtual inherited
References Isis::MosaicTool::getToolBarWidget(), and Isis::MosaicTool::toolBarDestroyed().
addTo() [3/3]
void Isis::MosaicTool::addTo (ToolPad * toolPad) virtual inherited
References Isis::MosaicTool::activate(), Isis::ToolPad::addAction(), and Isis::MosaicTool::getPrimaryAction().
fromPvl()
void Isis::MosaicTool::fromPvl (const PvlObject & obj) virtual inherited
Reimplemented in Isis::MosaicGridTool, Isis::MosaicFindTool, Isis::MosaicControlNetTool, and Isis::MosaicAreaTool.
References _FILEINFO_, Isis::IException::Programmer, and Isis::MosaicTool::projectPvlObjectName().
Referenced by Isis::MosaicSceneWidget::fromPvl().
getIcon()
QPixmap Isis::MosaicTool::getIcon (QString iconName) const inherited
returns the path to the icon directory.
Returns
QString
References Isis::FileName::expanded().
Referenced by Isis::MosaicAreaTool::getPrimaryAction(), Isis::MosaicControlNetTool::getPrimaryAction(), Isis::MosaicFindTool::getPrimaryAction(), Isis::MosaicGridTool::getPrimaryAction(), Isis::MosaicPanTool::getPrimaryAction(), Isis::MosaicSelectTool::getPrimaryAction(), getPrimaryAction(), and MosaicZoomTool().
getPrimaryAction()
QAction * Isis::MosaicZoomTool::getPrimaryAction () protected virtual
This method returns an action that is used to activate this tool.
This method will only be called once so it can new the action without a problem.
Implements Isis::MosaicTool.
References Isis::MosaicTool::getIcon().
getToolBarWidget()
QWidget * Isis::MosaicZoomTool::getToolBarWidget () protected virtual
Creates the widget to add to the tool bar.
Parameters
parent
Returns
QWidget*
Reimplemented from Isis::MosaicTool.
References zoomManual().
getViewActions()
QList< QAction * > Isis::MosaicZoomTool::getViewActions () virtual
Reimplemented from Isis::MosaicTool.
getWidget()
MosaicSceneWidget* Isis::MosaicTool::getWidget () inline protected inherited
Referenced by Isis::MosaicGridTool::autoGrid(), Isis::MosaicAreaTool::clearBox(), Isis::MosaicGridTool::clearGrid(), Isis::MosaicFindTool::clearPoint(), Isis::MosaicGridTool::domainMaxLon(), Isis::MosaicGridTool::domainMinLon(), Isis::MosaicGridTool::drawGrid(), Isis::MosaicGridTool::fromPvl(), Isis::MosaicGridTool::getToolBarWidget(), Isis::MosaicFindTool::getUserGroundPoint(), Isis::MosaicGridTool::latType(), Isis::MosaicControlNetTool::loadNetwork(), Isis::MosaicGridTool::lonDomain(), Isis::MosaicControlNetTool::MosaicControlNetTool(), Isis::MosaicGridTool::MosaicGridTool(), Isis::MosaicTrackTool::MosaicTrackTool(), Isis::MosaicControlNetTool::mouseButtonRelease(), Isis::MosaicAreaTool::mouseButtonRelease(), Isis::MosaicFindTool::mouseButtonRelease(), mouseWheel(), Isis::MosaicGridTool::onCubesChanged(), Isis::MosaicGridTool::onProjectionChanged(), rubberBandComplete(), Isis::MosaicGridTool::sceneWidget(), Isis::MosaicGridTool::setLatExtents(), Isis::MosaicGridTool::setLonExtents(), Isis::MosaicTrackTool::updateLabels(), updateResolutionBox(), Isis::MosaicPanTool::updateTool(), Isis::MosaicSelectTool::updateTool(), updateTool(), Isis::MosaicAreaTool::userChangedBox(), and zoomFit().
isActive()
bool Isis::MosaicTool::isActive () const inline inherited
Returns the activeness of this toool.
Returns
bool
Referenced by Isis::MosaicSceneWidget::isControlNetToolActive(), Isis::MosaicControlNetTool::mouseButtonRelease(), mouseButtonRelease(), Isis::MosaicAreaTool::mouseButtonRelease(), Isis::MosaicFindTool::mouseButtonRelease(), rubberBandComplete(), Isis::MosaicFindTool::updateTool(), Isis::MosaicPanTool::updateTool(), Isis::MosaicSelectTool::updateTool(), and updateTool().
mouseButtonPress()
void Isis::MosaicTool::mouseButtonPress (QPointF , Qt::MouseButton s) protected virtual inherited
Referenced by Isis::MosaicTool::MosaicTool().
mouseButtonRelease()
void Isis::MosaicZoomTool::mouseButtonRelease (QPointF mouseLoc, Qt::MouseButton s) protected virtual
Reimplemented from Isis::MosaicTool.
References Isis::MosaicTool::isActive(), zoomIn2X(), and zoomOut2X().
mouseDoubleClick()
void Isis::MosaicTool::mouseDoubleClick (QPointF) protected virtual inherited
Referenced by Isis::MosaicTool::MosaicTool().
mouseEnter()
virtual void Isis::MosaicTool::mouseEnter () inline protected virtual inherited
Referenced by Isis::MosaicTool::MosaicTool().
mouseLeave()
virtual void Isis::MosaicTool::mouseLeave () inline protected virtual inherited
Referenced by Isis::MosaicTool::MosaicTool().
mouseMove()
void Isis::MosaicTool::mouseMove (QPointF) protected virtual inherited
Referenced by Isis::MosaicTool::MosaicTool().
mouseWheel()
void Isis::MosaicZoomTool::mouseWheel (QPointF mouseLoc, int delta) protected virtual
Reimplemented from Isis::MosaicTool.
References Isis::MosaicSceneWidget::getView(), and Isis::MosaicTool::getWidget().
projectPvlObjectName()
QString Isis::MosaicTool::projectPvlObjectName () const virtual inherited
Reimplemented in Isis::MosaicGridTool, Isis::MosaicFindTool, Isis::MosaicControlNetTool, and Isis::MosaicAreaTool.
Referenced by Isis::MosaicSceneWidget::fromPvl(), Isis::MosaicTool::fromPvl(), Isis::MosaicSceneWidget::save(), Isis::MosaicSceneWidget::toPvl(), and Isis::MosaicTool::toPvl().
rubberBandComplete()
void Isis::MosaicZoomTool::rubberBandComplete (QRectF r, Qt::MouseButton s) protected virtual
This method is called when the RubberBandTool is complete.
The view is centered on the center point of the rubberband's rectangle, then zoomed based on the largest side of the rectange. (Width or height.)
Reimplemented from Isis::MosaicTool.
References Isis::MosaicSceneWidget::getView(), Isis::MosaicTool::getWidget(), Isis::MosaicTool::isActive(), and updateResolutionBox().
toolBarDestroyed()
void Isis::MosaicTool::toolBarDestroyed (QObject * obj) protected inherited
Referenced by Isis::MosaicTool::addTo().
toPvl()
PvlObject Isis::MosaicTool::toPvl () const virtual inherited
Reimplemented in Isis::MosaicGridTool, Isis::MosaicFindTool, Isis::MosaicControlNetTool, and Isis::MosaicAreaTool.
References _FILEINFO_, Isis::IException::Programmer, and Isis::MosaicTool::projectPvlObjectName().
Referenced by Isis::MosaicSceneWidget::save(), and Isis::MosaicSceneWidget::toPvl().
updateResolutionBox()
void Isis::MosaicZoomTool::updateResolutionBox ()
Updates the text in the screen resolution display box to the current screen resolution, in meters per pixel.
References Isis::MosaicSceneWidget::getView(), and Isis::MosaicTool::getWidget().
Referenced by rubberBandComplete(), updateTool(), and zoomFit().
updateTool
void Isis::MosaicZoomTool::updateTool () protected slot
This method updates the line edits text to the correct zoom value.
References Isis::MosaicSceneWidget::enableRubberBand(), Isis::MosaicSceneWidget::getView(), Isis::MosaicTool::getWidget(), Isis::MosaicTool::isActive(), Isis::MosaicSceneWidget::setCubesSelectable(), and updateResolutionBox().
zoomActual
void Isis::MosaicZoomTool::zoomActual (QPointF center = QPointF()) slot
Zoom back to 1 to 1.
zoomFit
void Isis::MosaicZoomTool::zoomFit () slot
Fits the in the graphics view.
References Isis::MosaicTool::getWidget(), Isis::MosaicSceneWidget::refit(), and updateResolutionBox().
Referenced by MosaicZoomTool().
zoomFitHeight
void Isis::MosaicZoomTool::zoomFitHeight () slot
Slot for the "Fit to Heighth" menu item on the Fit button.
This will display the cube so that the entire cube heighth is displayed.
zoomFitWidth
void Isis::MosaicZoomTool::zoomFitWidth () slot
Slot for the "Fit to Width" menu item on the Fit button.
zoomIn2X
void Isis::MosaicZoomTool::zoomIn2X (QPointF center = QPointF()) slot
Zooms in 2 times.
Referenced by MosaicZoomTool(), and mouseButtonRelease().
zoomManual
void Isis::MosaicZoomTool::zoomManual () slot
This method zooms by the value input in the line edit next to the zoom tools.
This method is called when the double spin box value has been changed. First we figure out what we need to scale the graphics view in order to achive the user's desired screen resolution.
Referenced by getToolBarWidget().
zoomOut2X
void Isis::MosaicZoomTool::zoomOut2X (QPointF center = QPointF()) slot
Zoom out 2 times.
Referenced by MosaicZoomTool(), and mouseButtonRelease().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/MosaicZoomTool.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/MosaicZoomTool.cpp