Isis Developer Reference: Isis::Equalization::CalculateFunctor Class Reference
Isis::Equalization::CalculateFunctor Class Reference
This class is used as a functor calculate image statistics.
#include <Equalization.h>
Public Member Functions
CalculateFunctor (Statistics *stats, double percent)
Constructs a CalculateFunctor.
virtual ~CalculateFunctor ()
void operator() (Buffer &in) const
Protected Member Functions
virtual void addStats (Buffer &in) const
Detailed Description
This class is used as a functor calculate image statistics.
Author
????-??-?? Unknown
Constructor & Destructor Documentation
CalculateFunctor()
Isis::Equalization::CalculateFunctor::CalculateFunctor (Statistics * stats, double percent) inline
Constructs a CalculateFunctor.
Parameters
stats Pointer to a Statistics object to add data to
percent Sampling percentage of the image, used to calculate a line increment, when calculating statistics
~CalculateFunctor()
virtual Isis::Equalization::CalculateFunctor::~CalculateFunctor () inline virtual
Member Function Documentation
addStats()
void Isis::Equalization::CalculateFunctor::addStats (Buffer & in) const protected virtual
Reimplemented in Isis::HiEqualization::HiCalculateFunctor.
References Isis::Buffer::size().
Referenced by Isis::HiEqualization::HiCalculateFunctor::addStats().
operator()()
void Isis::Equalization::CalculateFunctor::operator() (Buffer & in) const
References Isis::Buffer::Line(), and Isis::Buffer::LineDimension().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Equalization/Equalization.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Equalization/Equalization.cpp