Isis Developer Reference: Isis::TableRecord Class Reference
Isis::TableRecord Class Reference
Low Level Cube I/O
#include <TableRecord.h>
Public Member Functions
TableRecord ()
Constructs an empty TableRecord object. No member variables are set.
TableRecord (std::string tableRecordStr, char fieldDelimiter, std::vector< QString > fieldNames, int numOfFieldValues)
TableRecord constructor.
~TableRecord ()
Destroys the TableRecord object.
void operator+= (Isis::TableField &field)
Adds a TableField to a TableRecord.
TableField & operator[] (const int field)
Returns the TableField at the specified location in the TableRecord.
TableField & operator[] (const QString &field)
Returns the TableField in the record whose name corresponds to the input string.
int Fields () const
Returns the number of fields that are currently in the record.
int RecordSize () const
Returns the number of bytes per record.
void Pack (char *buf) const
Writes record information into the binary buffer.
void Unpack (const char *buf)
Reads record information from the binary buffer.
void Swap (char *buf) const
Swaps bytes of the buffer, depending on the TableField::Type.
Static Public Member Functions
static QString toString (TableRecord record, QString fieldDelimiter=",", bool fieldNames=false, bool endLine=true)
Detailed Description
Author
2004-09-01 Jeff Anderson
Constructor & Destructor Documentation
TableRecord() [1/2]
Isis::TableRecord::TableRecord ()
Constructs an empty TableRecord object. No member variables are set.
TableRecord() [2/2]
Isis::TableRecord::TableRecord (std::string tableRecordStr, char fieldDelimiter, std::vector< QString > fieldNames, int numOfFieldValues)
TableRecord constructor.
Parameters
tableRecordStr Table record string
fieldDelimiter The delimiter to separate fields with
fieldNames Table header names
numOfFieldValues Number of fields (rows)
References Isis::Double.
~TableRecord()
Isis::TableRecord::~TableRecord ()
Destroys the TableRecord object.
Member Function Documentation
Fields()
int Isis::TableRecord::Fields () const
Returns the number of fields that are currently in the record.
Returns
The number of fields in the record
Referenced by Isis::DawnVirCamera::DawnVirCamera(), Isis::SpicePosition::LoadCache(), Isis::SpiceRotation::LoadCache(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::Table::Table(), and toString().
operator+=()
void Isis::TableRecord::operator+= (Isis::TableField & field)
Adds a TableField to a TableRecord.
Parameters
field - TableField to be added to the record
operator[]() [1/2]
Isis::TableField & Isis::TableRecord::operator[] (const int field)
Returns the TableField at the specified location in the TableRecord.
Parameters
field Index of desired field
Returns
The TableField at specified location in the record
operator[]() [2/2]
TableField & Isis::TableRecord::operator[] (const QString & field)
Returns the TableField in the record whose name corresponds to the input string.
Parameters
field The name of desired TableField
Returns
The specified TableField
Exceptions
Isis::IException::Programmer - The field does not exist in the record
References _FILEINFO_, and Isis::IString::UpCase().
Pack()
void Isis::TableRecord::Pack (char * buf) const
Writes record information into the binary buffer.
Parameters
buf Buffer to fill with binary record information.
Exceptions
Isis::IException::Programmer - Invalid field type
References _FILEINFO_, Isis::TableField::isDouble(), Isis::TableField::isInteger(), Isis::TableField::isReal(), Isis::TableField::isText(), and Isis::TableField::size().
Referenced by Isis::Table::operator+=(), and Isis::Table::Update().
RecordSize()
int Isis::TableRecord::RecordSize () const
Returns the number of bytes per record.
Returns
Number of bytes per record
Referenced by Isis::ExportPdsTable::exportTable(), and Isis::Table::operator+=().
Swap()
void Isis::TableRecord::Swap (char * buf) const
Swaps bytes of the buffer, depending on the TableField::Type.
Parameters
buf Buffer containing record values to be swapped.
Exceptions
Isis::iException::Programmer - Invalid field type
References _FILEINFO_, Isis::TableField::bytes(), Isis::TableField::isDouble(), Isis::TableField::isInteger(), Isis::TableField::isReal(), Isis::TableField::isText(), and Isis::TableField::size().
toString()
QString Isis::TableRecord::toString (TableRecord record, QString fieldDelimiter = ",", bool fieldNames = false, bool endLine = true) static
References Fields(), and Isis::toString().
Unpack()
void Isis::TableRecord::Unpack (const char * buf)
Reads record information from the binary buffer.
Parameters
buf Buffer from which to read record field values.
References Isis::TableField::bytes().
Referenced by Isis::Table::operator[]().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/TableRecord/TableRecord.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/TableRecord/TableRecord.cpp