Isis Developer Reference: Isis::TemplateList Class Reference
Isis::TemplateList Class Reference
#include <TemplateList.h>
Public Member Functions
TemplateList (QString name, QString type, QString path, QObject *parent=NULL)
Create a template from a file name, type, and path.
TemplateList (QObject *parent=NULL)
Creates a blank template list.
TemplateList (const TemplateList &)
Copy constructor.
~TemplateList ()
Destructor.
QString name () const
Get the human-readable name of this TemplateList.
QString type () const
Get the type of template in this TemplateList.
QString path () const
Get the path to these Templates in the TemplateList (relative to project root).
void setName (QString newName)
Set the human-readable name of this TemplateList.
void setType (QString newType)
Set the type of template for of this TemplateList.
void setPath (QString newPath)
Set the relative path (from the project root) to this TemplateList's folder.
void deleteFromDisk (Project *project)
Delete all of the contained Templates from disk.
void save (QXmlStreamWriter &stream, const Project *project, FileName newProjectRoot) const
Convert this TemplateList into XML format for saving/restoring capabilities.
Detailed Description
Author
2017-11-01 Christopher Combs
Constructor & Destructor Documentation
TemplateList() [1/3]
Isis::TemplateList::TemplateList (QString name, QString type, QString path, QObject * parent = NULL)
Create a template from a file name, type, and path.
Parameters
name The TemplateList's name (i.e. import1, import2, ...)
type The TemplateList's folder name (i.e. maps, registrations, ...)
path Path to the TemplateList's folder from the template root
parent The Qt-relationship parent
References name(), path(), and type().
TemplateList() [2/3]
Isis::TemplateList::TemplateList (QObject * parent = NULL) explicit
Creates a blank template list.
Parameters
parent The Qt-relationship parent.
TemplateList() [3/3]
Isis::TemplateList::TemplateList (const TemplateList & other)
Copy constructor.
Parameters
other The TemplateList to copy
~TemplateList()
Isis::TemplateList::~TemplateList ()
Destructor.
Member Function Documentation
deleteFromDisk()
void Isis::TemplateList::deleteFromDisk (Project * project)
Delete all of the contained Templates from disk.
Parameters
project Project to delete templates from
See also
Template::deleteFromDisk()
References Isis::Template::deleteFromDisk(), and Isis::Project::templateRoot().
Referenced by Isis::ImportMapTemplateWorkOrder::undoExecution(), and Isis::ImportRegistrationTemplateWorkOrder::undoExecution().
name()
QString Isis::TemplateList::name () const
Get the human-readable name of this TemplateList.
Returns
QString The name of the TemplateList.
Referenced by Isis::ProjectItem::setTemplateList(), and TemplateList().
path()
QString Isis::TemplateList::path () const
Get the path to these Templates in the TemplateList (relative to project root).
Returns
QString The path to the Templates in the TemplateList.
Referenced by Isis::ProjectItem::setTemplateList(), and TemplateList().
save()
void Isis::TemplateList::save (QXmlStreamWriter & stream, const Project * project, FileName newProjectRoot) const
Convert this TemplateList into XML format for saving/restoring capabilities.
This writes:
  <templateList name="..." type= "..." path="...">
to the given xml stream, and creates an 'templates.xml' inside the folder with the templates. Inside the templates.xml, this writes:
  <templates>
    ...
  </templates>
Parameters
stream XML stream that contains the TemplateList data
project Project to save TemplateList from
newProjectRoot Filename root to save TemplateList to
Exceptions
IException::Io "Unable Failed to create directory"
IException::Io "Unable to save template information, could not be opened for writing"
References _FILEINFO_, Isis::FileName::dir(), Isis::Template::fileName(), Isis::IException::Io, Isis::FileName::name(), Isis::FileName::original(), Isis::FileName::path(), Isis::ReadWrite, Isis::Template::save(), Isis::Project::templateRoot(), and Isis::FileName::toString().
setName()
void Isis::TemplateList::setName (QString newName)
Set the human-readable name of this TemplateList.
Parameters
newName The name to give this TemplateList
setPath()
void Isis::TemplateList::setPath (QString newPath)
Set the relative path (from the project root) to this TemplateList's folder.
Parameters
newPath The path to the templates in this TemplateList
setType()
void Isis::TemplateList::setType (QString newType)
Set the type of template for of this TemplateList.
Parameters
newType The type to give this TemplateList
type()
QString Isis::TemplateList::type () const
Get the type of template in this TemplateList.
Returns
QString The type of template found in this TemplateList.
Referenced by Isis::Project::addTemplates(), Isis::ControlPointEditWidget::addTemplates(), and TemplateList().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/TemplateList/TemplateList.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/TemplateList/TemplateList.cpp