Isis Developer Reference: Isis::ViewportMainWindow Class Reference
Isis::ViewportMainWindow Class Reference
This was called the Qisis MainWindow.
#include <ViewportMainWindow.h>
Public Slots
void displayWarning (std::string &pStr, const std::string &pExStr)
Slot which receives the warning signal.
void resetWarning (void)
Slot which receives the message to reset warning status.
Signals
void closeWindow (QCloseEvent *event=NULL)
Signal called when the window receives a close event.
Public Member Functions
ViewportMainWindow (QString title, QWidget *parent=0)
Constructs a ViewportMainWindow object with windowTitle = title.
virtual ~ViewportMainWindow ()
Workspace * workspace ()
Returns the current workspace.
QToolBar * permanentToolBar ()
Returns the permanent toolbar.
QToolBar * activeToolBar ()
Returns the active toolbar.
ToolPad * toolPad ()
Returns the toolpad.
QMenu * getMenu (const QString &name)
Returns the menu with menu name = name.
TrackTool * getTrackTool ()
Static Public Member Functions
static QString settingsFileName (QString objectTitle)
Protected Member Functions
virtual void closeEvent (QCloseEvent *event)
This class is called when a close event occurs, it emits a signal and ignores the close event.
QString settingsFileName () const
virtual void readSettings (QSize defaultSize=QSize())
This method ensure that the settings get written even if the Main window was only hidden, not closed.
Detailed Description
This was called the Qisis MainWindow.
Now this is being subclassed from the mainwindow class which keeps track of the size and location of the qisis windows. qview and qnet are two applications that use WiewportMainWindow.
Author
????-??-?? Stacy Alley
Constructor & Destructor Documentation
ViewportMainWindow()
Isis::ViewportMainWindow::ViewportMainWindow (QString title, QWidget * parent = 0)
Constructs a ViewportMainWindow object with windowTitle = title.
Parameters
title
parent
References Isis::Tool::addTo(), and Isis::MainWindow::readSettings().
~ViewportMainWindow()
Isis::ViewportMainWindow::~ViewportMainWindow () virtual
Member Function Documentation
activeToolBar()
QToolBar* Isis::ViewportMainWindow::activeToolBar () inline
Returns the active toolbar.
Referenced by Isis::Tool::addTo().
closeEvent()
void Isis::ViewportMainWindow::closeEvent (QCloseEvent * event) protected virtual
This class is called when a close event occurs, it emits a signal and ignores the close event.
Parameters
event
Reimplemented from Isis::MainWindow.
References Isis::MainWindow::closeEvent(), closeWindow(), and Isis::Workspace::confirmClose().
closeWindow
void Isis::ViewportMainWindow::closeWindow (QCloseEvent * event = NULL) signal
Signal called when the window receives a close event.
Referenced by closeEvent().
displayWarning
void Isis::ViewportMainWindow::displayWarning (std::string & pStr, const std::string & pExStr) slot
Slot which receives the warning signal.
Calls the Track Tool to display the warning status
Parameters
pStr - Warning message
pExStr - Propagated exception message
References Isis::TrackTool::displayWarning().
getMenu()
QMenu * Isis::ViewportMainWindow::getMenu (const QString & name)
Returns the menu with menu name = name.
Parameters
name
Returns
QMenu*
Referenced by Isis::Tool::addTo().
getTrackTool()
TrackTool* Isis::ViewportMainWindow::getTrackTool () inline
permanentToolBar()
QToolBar* Isis::ViewportMainWindow::permanentToolBar () inline
Returns the permanent toolbar.
Referenced by Isis::Tool::addTo().
readSettings()
void Isis::MainWindow::readSettings (QSize defaultSize = QSize()) protected virtual inherited
This method ensure that the settings get written even if the Main window was only hidden, not closed.
Parameters
event This method is called from the constructor so that when the Main window is created, it know's it's size and location.
References Isis::MainWindow::settingsFileName().
Referenced by Isis::PlotWindow::PlotWindow(), Isis::TableMainWindow::TableMainWindow(), and ViewportMainWindow().
resetWarning
void Isis::ViewportMainWindow::resetWarning (void) slot
Slot which receives the message to reset warning status.
References Isis::TrackTool::resetStatusWarning().
settingsFileName() [1/2]
QString Isis::MainWindow::settingsFileName () const protected inherited
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by Isis::TableMainWindow::readColumnSettings(), Isis::TableMainWindow::readItemSettings(), Isis::BlinkTool::readSettings(), Isis::MainWindow::readSettings(), Isis::BlinkTool::writeSettings(), and Isis::TableMainWindow::writeSettings().
settingsFileName() [2/2]
QString Isis::MainWindow::settingsFileName (QString objectTitle) static inherited
References _FILEINFO_, and Isis::IException::Programmer.
toolPad()
ToolPad* Isis::ViewportMainWindow::toolPad () inline
Returns the toolpad.
Referenced by Isis::Tool::addTo().
workspace()
Workspace* Isis::ViewportMainWindow::workspace () inline
Returns the current workspace.
Referenced by Isis::Tool::addTo().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ViewportMainWindow/ViewportMainWindow.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ViewportMainWindow/ViewportMainWindow.cpp