Isis Developer Reference: Isis::HiCalData Class Reference
Isis::HiCalData Class Reference
Utility
Container for HiRISE calibration data.
#include <HiCalData.h>
Public Member Functions
HiCalData ()
HiCalData (Cube &cube)
virtual ~HiCalData ()
Destructor.
void load (Cube &cube)
HiMatrix getReverseClock ()
HiMatrix getMask ()
HiMatrix getRamp ()
HiMatrix getDark ()
HiMatrix getBuffer ()
HiMatrix getReverseClockExtended ()
HiMatrix getMaskExtended ()
HiMatrix getRampExtended ()
HiMatrix getDarkExtended ()
HiMatrix getBufferExtended ()
Detailed Description
Container for HiRISE calibration data.
Author
2007-10-09 Kris Becker
Constructor & Destructor Documentation
HiCalData() [1/2]
Isis::HiCalData::HiCalData () inline
HiCalData() [2/2]
Isis::HiCalData::HiCalData (Cube & cube) inline
References load().
~HiCalData()
virtual Isis::HiCalData::~HiCalData () inline virtual
Destructor.
Member Function Documentation
getBuffer()
HiMatrix Isis::HiCalData::getBuffer () inline
getBufferExtended()
HiMatrix Isis::HiCalData::getBufferExtended () inline
References Isis::appendLines().
getDark()
HiMatrix Isis::HiCalData::getDark () inline
getDarkExtended()
HiMatrix Isis::HiCalData::getDarkExtended () inline
References Isis::appendLines().
getMask()
HiMatrix Isis::HiCalData::getMask () inline
References Isis::cropLines().
getMaskExtended()
HiMatrix Isis::HiCalData::getMaskExtended () inline
References Isis::appendSamples(), and Isis::cropLines().
getRamp()
HiMatrix Isis::HiCalData::getRamp () inline
References Isis::cropLines().
getRampExtended()
HiMatrix Isis::HiCalData::getRampExtended () inline
References Isis::appendSamples(), and Isis::cropLines().
getReverseClock()
HiMatrix Isis::HiCalData::getReverseClock () inline
References Isis::cropLines().
getReverseClockExtended()
HiMatrix Isis::HiCalData::getReverseClockExtended () inline
References Isis::appendSamples(), and Isis::cropLines().
load()
void Isis::HiCalData::load (Cube & cube) inline
References Isis::HiBlob::buffer(), Isis::Cube::group(), and Isis::Progress::SetText().
Referenced by HiCalData().
The documentation for this class was generated from the following file:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/mro/objs/HiCal/HiCalData.h