Isis Developer Reference: Isis::BundleObservationSolveSettings Class Reference
Isis::BundleObservationSolveSettings Class Reference
Control Networks
This class is used to modify and manage solve settings for 1 to many BundleObservations.
#include <BundleObservationSolveSettings.h>
Public Types
enum CSMSolveOption { NoCSMParameters = 0 , Set = 1 , Type = 2 , List = 3 }
Options for how to solve for CSM parameters.
enum InstrumentPointingSolveOption {
NoPointingFactors = 0 , AnglesOnly = 1 , AnglesVelocity = 2 , AnglesVelocityAcceleration = 3 ,
AllPointingCoefficients = 4
}
Options for how to solve for instrument pointing.
enum InstrumentPositionSolveOption {
NoPositionFactors = 0 , PositionOnly = 1 , PositionVelocity = 2 , PositionVelocityAcceleration = 3 ,
AllPositionCoefficients = 4
}
Options for how to solve for instrument position.
Public Member Functions
BundleObservationSolveSettings ()
Constructor with default parameter initializations.
BundleObservationSolveSettings (QXmlStreamReader *xmlReader)
Construct this BundleObservationSolveSettings object from XML.
BundleObservationSolveSettings (FileName xmlFile, QXmlStreamReader *xmlReader)
BundleObservationSolveSettings (const BundleObservationSolveSettings &src)
Constructs a BundleObservationSolveSettings from another one.
BundleObservationSolveSettings (const PvlGroup &scParameterGroup)
~BundleObservationSolveSettings ()
Destructor.
BundleObservationSolveSettings & operator= (const BundleObservationSolveSettings &src)
Assigns the state of another BundleObservationSolveSettings to this one.
void initialize ()
Initializes the default state of this BundleObservationSolveSettings.
void setInstrumentId (QString instrumentId)
Sets the instrument id for this observation.
QString instrumentId () const
Accesses the instrument id for this observation.
void addObservationNumber (QString observationNumber)
Associates an observation number with these solve settings.
bool removeObservationNumber (QString observationNumber)
Removes an observation number from this solve settings.
QSet< QString > observationNumbers () const
Returns a list of observation numbers associated with these solve settings.
void setCSMSolveSet (csm::param::Set set)
Set the set of CSM parameters to solve for.
void setCSMSolveType (csm::param::Type type)
Set the type of CSM parameters to solve for.
void setCSMSolveParameterList (QStringList list)
Set an explicit list of CSM parameters to solve for.
CSMSolveOption csmSolveOption () const
Get how the CSM parameters to solve for are specified for this observation.
csm::param::Set csmParameterSet () const
Get the set of CSM parameters to solve for.
csm::param::Type csmParameterType () const
Get the type of CSM parameters to solve for.
QStringList csmParameterList () const
Get the list of CSM parameters to solve for.
void setInstrumentPointingSettings (InstrumentPointingSolveOption option, bool solveTwist, int ckDegree=2, int ckSolveDegree=2, bool solvePolynomialOverExisting=false, double anglesAprioriSigma=-1.0, double angularVelocityAprioriSigma=-1.0, double angularAccelerationAprioriSigma=-1.0, QList< double > *additionalPointingSigmas=nullptr)
Sets the instrument pointing settings.
InstrumentPointingSolveOption instrumentPointingSolveOption () const
Accesses the instrument pointing solve option.
bool solveTwist () const
Accesses the flag for solving for twist.
int ckDegree () const
Accesses the degree of polynomial fit to original camera angles (ckDegree).
int ckSolveDegree () const
Accesses the degree of the camera angles polynomial being fit to in the bundle adjustment (ckSolveDegree).
int numberCameraAngleCoefficientsSolved () const
Accesses the number of camera angle coefficients in the solution.
bool solvePolyOverPointing () const
Whether or not the solve polynomial will be fit over the existing pointing polynomial.
QList< double > aprioriPointingSigmas () const
Accesses the a priori pointing sigmas.
SpiceRotation::Source pointingInterpolationType () const
Accesses the SpiceRotation interpolation type for the instrument pointing.
void setInstrumentPositionSettings (InstrumentPositionSolveOption option, int spkDegree=2, int spkSolveDegree=2, bool positionOverHermite=false, double positionAprioriSigma=-1.0, double velocityAprioriSigma=-1.0, double accelerationAprioriSigma=-1.0, QList< double > *additionalPositionSigmas=nullptr)
Sets the instrument pointing settings.
InstrumentPositionSolveOption instrumentPositionSolveOption () const
Accesses the instrument position solve option.
int spkDegree () const
Accesses the degree of the polynomial fit to the original camera position (spkDegree).
int spkSolveDegree () const
Accesses the degree of thecamera position polynomial being fit to in the bundle adjustment (spkSolveDegree).
int numberCameraPositionCoefficientsSolved () const
Accesses the number of camera position coefficients in the solution.
bool solvePositionOverHermite () const
Whether or not the polynomial for solving will be fit over an existing Hermite spline.
QList< double > aprioriPositionSigmas () const
Accesses the a priori position sigmas.
SpicePosition::Source positionInterpolationType () const
Accesses the SpicePosition interpolation type for the spacecraft position.
void save (QXmlStreamWriter &stream, const Project *project) const
Saves this BundleObservationSolveSettings to an xml stream.
void readSolveSettings (QXmlStreamReader *xmlReader)
Static Public Member Functions
static CSMSolveOption stringToCSMSolveOption (QString option)
Convert a string to a CSM solve option enumeration value.
static QString csmSolveOptionToString (CSMSolveOption option)
Convert a CSM solve option enumeration value to a string.
static csm::param::Set stringToCSMSolveSet (QString set)
Convert a string to its CSM parameter set enumeration value.
static QString csmSolveSetToString (csm::param::Set set)
Convert a CSM parameter set enumeration value to a string.
static csm::param::Type stringToCSMSolveType (QString type)
Convert a string to its CSM parameter type enumeration value.
static QString csmSolveTypeToString (csm::param::Type type)
Convert a CSM parameter type enumeration value to a string.
static InstrumentPointingSolveOption stringToInstrumentPointingSolveOption (QString option)
Translates a QString InstrumentPointingSolveOption to its enumerated value.
static QString instrumentPointingSolveOptionToString (InstrumentPointingSolveOption option)
Tranlsates an enumerated InstrumentPointingSolveOption value to its string representation.
static InstrumentPositionSolveOption stringToInstrumentPositionSolveOption (QString option)
Translates a QString InstrumentPositionSolveOption to its enumerated value.
static QString instrumentPositionSolveOptionToString (InstrumentPositionSolveOption option)
Translates an enumerated InstrumentPositionSolveOption to its string representation.
Public Attributes
QUuid * m_id
A unique ID for this object (useful for others to reference this object when saving to disk).
QString m_instrumentId
The spacecraft instrument id for this observation.
QSet< QString > m_observationNumbers
Associated observation numbers for these settings.
CSMSolveOption m_csmSolveOption
How the CSM solution is specified.
csm::param::Set m_csmSolveSet
The CSM parameter set to solve for.
csm::param::Type m_csmSolveType
The CSM parameter type to solve for.
QStringList m_csmSolveList
The names of the CSM parameters to solve for.
InstrumentPointingSolveOption m_instrumentPointingSolveOption
Option for how to solve for instrument pointing.
int m_numberCamAngleCoefSolved
The number of camera angle coefficients in solution.
int m_ckDegree
Degree of the polynomial fit to the original camera angles.
int m_ckSolveDegree
Degree of the camera angles polynomial being fit to in the bundle adjustment.
bool m_solveTwist
Solve for "twist" angle.
bool m_solvePointingPolynomialOverExisting
The polynomial will be fit over the existing pointing polynomial.
QList< double > m_anglesAprioriSigma
The image position a priori sigmas.The size of the list is equal to the number of coefficients in the solution.
SpiceRotation::Source m_pointingInterpolationType
SpiceRotation interpolation type.
InstrumentPositionSolveOption m_instrumentPositionSolveOption
Option for how to solve for instrument position.
int m_numberCamPosCoefSolved
The number of camera position coefficients in the solution.
int m_spkDegree
Degree of the polynomial fit to the original camera position.
int m_spkSolveDegree
Degree of the camera position polynomial being fit to in the bundle adjustment.
bool m_solvePositionOverHermiteSpline
The polynomial will be fit over an existing Hermite spline.
QList< double > m_positionAprioriSigma
The instrument pointing a priori sigmas.
SpicePosition::Source m_positionInterpolationType
SpicePosition interpolation types.
Detailed Description
This class is used to modify and manage solve settings for 1 to many BundleObservations.
These settings indicate how any associated observations should be solved.
Author
2014-07-09 Ken Edmundson
Member Enumeration Documentation
CSMSolveOption
enum Isis::BundleObservationSolveSettings::CSMSolveOption
Options for how to solve for CSM parameters.
Enumerator
NoCSMParameters
Do not solve for CSM parameters.
Set
Solve for all CSM parameters belonging to a specific set.
Type
Solve for all CSM parameters of a specific type.
List
Solve for an explicit list of CSM parameters.
InstrumentPointingSolveOption
enum Isis::BundleObservationSolveSettings::InstrumentPointingSolveOption
Options for how to solve for instrument pointing.
Enumerator
NoPointingFactors
Solve for none of the pointing factors.
AnglesOnly
Solve for pointing angles: right ascension, declination and, optionally, twist.
AnglesVelocity
Solve for pointing angles and their angular velocities.
AnglesVelocityAcceleration
Solve for pointing angles, their velocities and their accelerations.
AllPointingCoefficients
Solve for all coefficients in the polynomials fit to the pointing angles.
InstrumentPositionSolveOption
enum Isis::BundleObservationSolveSettings::InstrumentPositionSolveOption
Options for how to solve for instrument position.
Enumerator
NoPositionFactors
Solve for none of the position factors.
PositionOnly
Solve for instrument positions only.
PositionVelocity
Solve for instrument positions and velocities.
PositionVelocityAcceleration
Solve for instrument positions, velocities, and accelerations.
AllPositionCoefficients
Solve for all coefficients in the polynomials fit to the instrument positions.
Constructor & Destructor Documentation
BundleObservationSolveSettings() [1/5]
Isis::BundleObservationSolveSettings::BundleObservationSolveSettings ()
Constructor with default parameter initializations.
References initialize().
BundleObservationSolveSettings() [2/5]
Isis::BundleObservationSolveSettings::BundleObservationSolveSettings (QXmlStreamReader * xmlReader)
Construct this BundleObservationSolveSettings object from XML.
Parameters
bundleSettingsFolder Where this settings XML resides - /work/.../projectRoot/images/import1
xmlReader An XML reader that's up to an <bundleSettings> tag.
References initialize(), and readSolveSettings().
BundleObservationSolveSettings() [3/5]
Isis::BundleObservationSolveSettings::BundleObservationSolveSettings (FileName xmlFile, QXmlStreamReader * xmlReader)
BundleObservationSolveSettings() [4/5]
Isis::BundleObservationSolveSettings::BundleObservationSolveSettings (const BundleObservationSolveSettings & other)
Constructs a BundleObservationSolveSettings from another one.
Parameters
other The BundleObservationSolveSettings to copy
References m_anglesAprioriSigma, m_ckDegree, m_ckSolveDegree, m_csmSolveList, m_csmSolveOption, m_csmSolveSet, m_csmSolveType, m_id, m_instrumentId, m_instrumentPointingSolveOption, m_instrumentPositionSolveOption, m_numberCamAngleCoefSolved, m_numberCamPosCoefSolved, m_observationNumbers, m_pointingInterpolationType, m_positionAprioriSigma, m_positionInterpolationType, m_solvePointingPolynomialOverExisting, m_solvePositionOverHermiteSpline, m_solveTwist, m_spkDegree, and m_spkSolveDegree.
BundleObservationSolveSettings() [5/5]
Isis::BundleObservationSolveSettings::BundleObservationSolveSettings (const PvlGroup & scParameterGroup)
References _FILEINFO_, AllPointingCoefficients, AllPositionCoefficients, AnglesOnly, AnglesVelocity, AnglesVelocityAcceleration, Isis::PvlContainer::findKeyword(), Isis::PvlContainer::hasKeyword(), initialize(), m_anglesAprioriSigma, m_ckDegree, m_ckSolveDegree, m_instrumentId, m_instrumentPointingSolveOption, m_instrumentPositionSolveOption, m_numberCamAngleCoefSolved, m_numberCamPosCoefSolved, m_pointingInterpolationType, m_positionAprioriSigma, m_positionInterpolationType, m_solvePointingPolynomialOverExisting, m_solvePositionOverHermiteSpline, m_solveTwist, m_spkDegree, m_spkSolveDegree, Isis::PvlContainer::nameKeyword(), NoPointingFactors, NoPositionFactors, Isis::Null, Isis::SpicePosition::PolyFunction, Isis::SpiceRotation::PolyFunction, Isis::SpicePosition::PolyFunctionOverHermiteConstant, Isis::SpiceRotation::PolyFunctionOverSpice, PositionOnly, PositionVelocity, PositionVelocityAcceleration, setCSMSolveParameterList(), setCSMSolveSet(), setCSMSolveType(), Isis::PvlKeyword::size(), stringToCSMSolveSet(), stringToCSMSolveType(), Isis::toDouble(), and Isis::IException::User.
~BundleObservationSolveSettings()
Isis::BundleObservationSolveSettings::~BundleObservationSolveSettings ()
Destructor.
References m_id.
Member Function Documentation
addObservationNumber()
void Isis::BundleObservationSolveSettings::addObservationNumber (QString observationNumber)
Associates an observation number with these solve settings.
These solve settings are to be applied to any associated observations.
Parameters
observationNumber QString observation number to associate with these settings.
References m_observationNumbers.
Referenced by Isis::JigsawSetupDialog::JigsawSetupDialog().
aprioriPointingSigmas()
QList< double > Isis::BundleObservationSolveSettings::aprioriPointingSigmas () const
Accesses the a priori pointing sigmas.
Returns
QList<double> Returns a QList of the a priori pointing sigmas
References m_anglesAprioriSigma.
Referenced by Isis::BundleSolutionInfo::outputHeader(), and Isis::JigsawSetupDialog::treeViewSelectionChanged().
aprioriPositionSigmas()
QList< double > Isis::BundleObservationSolveSettings::aprioriPositionSigmas () const
Accesses the a priori position sigmas.
Returns
QList<double> Returns a QList of the a priori position sigmas
References m_positionAprioriSigma.
Referenced by Isis::BundleSolutionInfo::outputHeader(), and Isis::JigsawSetupDialog::treeViewSelectionChanged().
ckDegree()
int Isis::BundleObservationSolveSettings::ckDegree () const
Accesses the degree of polynomial fit to original camera angles (ckDegree).
Returns
int Returns the degree of the polynomial fit to the original camera angles
References m_ckDegree.
Referenced by Isis::BundleSolutionInfo::outputHeader(), setInstrumentPointingSettings(), and Isis::JigsawSetupDialog::treeViewSelectionChanged().
ckSolveDegree()
int Isis::BundleObservationSolveSettings::ckSolveDegree () const
Accesses the degree of the camera angles polynomial being fit to in the bundle adjustment (ckSolveDegree).
Returns
int Returns the degree of the camera angles polynomial in the bundle adjustment
References m_ckSolveDegree.
Referenced by Isis::BundleSolutionInfo::outputHeader(), setInstrumentPointingSettings(), and Isis::JigsawSetupDialog::treeViewSelectionChanged().
csmParameterList()
QStringList Isis::BundleObservationSolveSettings::csmParameterList () const
Get the list of CSM parameters to solve for.
Returns
QStringList The names of the CSM parameters to solve for
References m_csmSolveList.
csmParameterSet()
csm::param::Set Isis::BundleObservationSolveSettings::csmParameterSet () const
Get the set of CSM parameters to solve for.
Returns
csm::param::Set The CSM parameter set to solve for
References m_csmSolveSet.
csmParameterType()
csm::param::Type Isis::BundleObservationSolveSettings::csmParameterType () const
Get the type of CSM parameters to solve for.
Returns
csm::param::Type The CSM parameter type to solve for
References m_csmSolveType.
csmSolveOption()
BundleObservationSolveSettings::CSMSolveOption Isis::BundleObservationSolveSettings::csmSolveOption () const
Get how the CSM parameters to solve for are specified for this observation.
Returns
CSMSolveOption
References m_csmSolveOption.
csmSolveOptionToString()
QString Isis::BundleObservationSolveSettings::csmSolveOptionToString (CSMSolveOption option) static
Convert a CSM solve option enumeration value to a string.
Parameters
option The option's enumeration value
Returns
QString The option as a string
References _FILEINFO_, List, NoCSMParameters, Isis::IException::Programmer, Set, Isis::toString(), and Type.
csmSolveSetToString()
QString Isis::BundleObservationSolveSettings::csmSolveSetToString (csm::param::Set set) static
Convert a CSM parameter set enumeration value to a string.
Parameters
set The set's enumeration value
Returns
QString The set's name
References _FILEINFO_, Isis::IException::Programmer, and Isis::toString().
csmSolveTypeToString()
QString Isis::BundleObservationSolveSettings::csmSolveTypeToString (csm::param::Type type) static
Convert a CSM parameter type enumeration value to a string.
Parameters
type The type's enumeration value
Returns
QString The type's name
References _FILEINFO_, Isis::IException::Programmer, and Isis::toString().
initialize()
void Isis::BundleObservationSolveSettings::initialize ()
Initializes the default state of this BundleObservationSolveSettings.
References AnglesOnly, m_csmSolveList, m_csmSolveOption, m_csmSolveSet, m_csmSolveType, m_id, m_instrumentId, NoCSMParameters, NoPositionFactors, setInstrumentPointingSettings(), and setInstrumentPositionSettings().
Referenced by BundleObservationSolveSettings(), and readSolveSettings().
instrumentId()
QString Isis::BundleObservationSolveSettings::instrumentId () const
Accesses the instrument id for this observation.
Returns
QString Returns the instrument id for this observation
References m_instrumentId.
Referenced by readSolveSettings(), save(), and setInstrumentId().
instrumentPointingSolveOption()
BundleObservationSolveSettings::InstrumentPointingSolveOption Isis::BundleObservationSolveSettings::instrumentPointingSolveOption () const
Accesses the instrument pointing solve option.
Returns
BundleObservationSolveSettings::InstrumentPointingSolveOption Returns the instrument pointing solve option
References m_instrumentPointingSolveOption.
Referenced by Isis::JigsawSetupDialog::treeViewSelectionChanged().
instrumentPointingSolveOptionToString()
QString Isis::BundleObservationSolveSettings::instrumentPointingSolveOptionToString (InstrumentPointingSolveOption option) static
Tranlsates an enumerated InstrumentPointingSolveOption value to its string representation.
Parameters
option Enumerated InstrumentPointingSolveOption value
Exceptions
IException::Programmer "Unknown pointing solve option enum."
Returns
QString Returns the QString representation of the passed InstrumentPointingSolveOption
References _FILEINFO_, AllPointingCoefficients, AnglesOnly, AnglesVelocity, AnglesVelocityAcceleration, NoPointingFactors, Isis::IException::Programmer, and Isis::toString().
Referenced by Isis::IsisBundleObservation::applyParameterCorrections(), and save().
instrumentPositionSolveOption()
BundleObservationSolveSettings::InstrumentPositionSolveOption Isis::BundleObservationSolveSettings::instrumentPositionSolveOption () const
Accesses the instrument position solve option.
Returns
BundleObservationSolveSettings::InstrumentPositionSolveOption Returns the instrument position solve option
References m_instrumentPositionSolveOption.
Referenced by Isis::JigsawSetupDialog::treeViewSelectionChanged().
instrumentPositionSolveOptionToString()
QString Isis::BundleObservationSolveSettings::instrumentPositionSolveOptionToString (InstrumentPositionSolveOption option) static
Translates an enumerated InstrumentPositionSolveOption to its string representation.
Parameters
option Enumerated InstrumentPositionSolveOption value
Exceptions
IException::Programmer "Unknown position solve option enum."
Returns
QString Returns the QString representation of the passed InstrumentPointingSolveOption
References _FILEINFO_, AllPositionCoefficients, NoPositionFactors, PositionOnly, PositionVelocity, PositionVelocityAcceleration, Isis::IException::Programmer, and Isis::toString().
Referenced by Isis::IsisBundleObservation::applyParameterCorrections(), and save().
numberCameraAngleCoefficientsSolved()
int Isis::BundleObservationSolveSettings::numberCameraAngleCoefficientsSolved () const
Accesses the number of camera angle coefficients in the solution.
Returns
int Returns the number of camera angle coefficients in the solution
References m_numberCamAngleCoefSolved.
Referenced by Isis::BundleSolutionInfo::outputHeader().
numberCameraPositionCoefficientsSolved()
int Isis::BundleObservationSolveSettings::numberCameraPositionCoefficientsSolved () const
Accesses the number of camera position coefficients in the solution.
Returns
int Returns the number of camera position coefficients.
References m_numberCamPosCoefSolved.
Referenced by Isis::BundleSolutionInfo::outputHeader().
observationNumbers()
QSet< QString > Isis::BundleObservationSolveSettings::observationNumbers () const
Returns a list of observation numbers associated with these solve settings.
Returns
QSet<QString> Returns a QSet containing the associated observation numbers.
References m_observationNumbers.
Referenced by Isis::JigsawSetupDialog::JigsawSetupDialog().
operator=()
BundleObservationSolveSettings & Isis::BundleObservationSolveSettings::operator= (const BundleObservationSolveSettings & other)
Assigns the state of another BundleObservationSolveSettings to this one.
Parameters
other The other BundleObservationSolveSettings to assign state from
References m_anglesAprioriSigma, m_ckDegree, m_ckSolveDegree, m_csmSolveList, m_csmSolveOption, m_csmSolveSet, m_csmSolveType, m_id, m_instrumentId, m_instrumentPointingSolveOption, m_instrumentPositionSolveOption, m_numberCamAngleCoefSolved, m_numberCamPosCoefSolved, m_observationNumbers, m_pointingInterpolationType, m_positionAprioriSigma, m_positionInterpolationType, m_solvePointingPolynomialOverExisting, m_solvePositionOverHermiteSpline, m_solveTwist, m_spkDegree, and m_spkSolveDegree.
pointingInterpolationType()
SpiceRotation::Source Isis::BundleObservationSolveSettings::pointingInterpolationType () const
Accesses the SpiceRotation interpolation type for the instrument pointing.
Returns
SpiceRotation::Source Returns the SpiceRotation interpolation type for pointing
References m_pointingInterpolationType.
positionInterpolationType()
SpicePosition::Source Isis::BundleObservationSolveSettings::positionInterpolationType () const
Accesses the SpicePosition interpolation type for the spacecraft position.
Returns
SpicePosition::Source Returns the SpicePositon interpolation type for position
References m_positionInterpolationType.
readSolveSettings()
void Isis::BundleObservationSolveSettings::readSolveSettings (QXmlStreamReader * xmlReader)
References initialize(), instrumentId(), m_anglesAprioriSigma, m_ckDegree, m_ckSolveDegree, m_instrumentPointingSolveOption, m_instrumentPositionSolveOption, m_numberCamAngleCoefSolved, m_numberCamPosCoefSolved, m_pointingInterpolationType, m_positionAprioriSigma, m_positionInterpolationType, m_solvePointingPolynomialOverExisting, m_solvePositionOverHermiteSpline, m_solveTwist, m_spkDegree, m_spkSolveDegree, Isis::Null, Isis::SpicePosition::PolyFunction, Isis::SpiceRotation::PolyFunction, Isis::SpicePosition::PolyFunctionOverHermiteConstant, Isis::SpiceRotation::PolyFunctionOverSpice, setInstrumentId(), solveTwist(), stringToInstrumentPointingSolveOption(), stringToInstrumentPositionSolveOption(), and Isis::toBool().
Referenced by BundleObservationSolveSettings().
removeObservationNumber()
bool Isis::BundleObservationSolveSettings::removeObservationNumber (QString observationNumber)
Removes an observation number from this solve settings.
The observation is no longer associated with this solve settings.
Parameters
QString observationNumber The observation number to remove from this solve settings.
Returns
bool Returns true if the observation number passed was actually removed; otherwise returns false.
References m_observationNumbers.
save()
void Isis::BundleObservationSolveSettings::save (QXmlStreamWriter & stream, const Project * project) const
Saves this BundleObservationSolveSettings to an xml stream.
Parameters
stream A QXmlStreamWriter to write to
project Pointer to the current project
References instrumentId(), instrumentPointingSolveOptionToString(), instrumentPositionSolveOptionToString(), Isis::IsSpecial(), m_anglesAprioriSigma, m_ckDegree, m_ckSolveDegree, m_id, m_instrumentPointingSolveOption, m_instrumentPositionSolveOption, m_numberCamAngleCoefSolved, m_numberCamPosCoefSolved, m_pointingInterpolationType, m_positionAprioriSigma, m_positionInterpolationType, m_solvePointingPolynomialOverExisting, m_solvePositionOverHermiteSpline, m_solveTwist, m_spkDegree, m_spkSolveDegree, and Isis::toString().
setCSMSolveParameterList()
void Isis::BundleObservationSolveSettings::setCSMSolveParameterList (QStringList list)
Set an explicit list of CSM parameters to solve for.
Parameters
list The names of the parameters to solve for
References List, m_csmSolveList, and m_csmSolveOption.
Referenced by BundleObservationSolveSettings().
setCSMSolveSet()
void Isis::BundleObservationSolveSettings::setCSMSolveSet (csm::param::Set set)
Set the set of CSM parameters to solve for.
See the CSM API documentation for what the different set values mean.
Parameters
set The set to solve for
References m_csmSolveOption, m_csmSolveSet, and Set.
Referenced by BundleObservationSolveSettings().
setCSMSolveType()
void Isis::BundleObservationSolveSettings::setCSMSolveType (csm::param::Type type)
Set the type of CSM parameters to solve for.
Parameters
type The parameter type to solve for
References m_csmSolveOption, m_csmSolveType, and Type.
Referenced by BundleObservationSolveSettings().
setInstrumentId()
void Isis::BundleObservationSolveSettings::setInstrumentId (QString instrumentId)
Sets the instrument id for this observation.
Parameters
instrumentId QString instrument id
References instrumentId(), and m_instrumentId.
Referenced by readSolveSettings().
setInstrumentPointingSettings()
void Isis::BundleObservationSolveSettings::setInstrumentPointingSettings (InstrumentPointingSolveOption option, bool solveTwist, int ckDegree = 2, int ckSolveDegree = 2, bool solvePolynomialOverExisting = false, double anglesAprioriSigma = -1.0, double angularVelocityAprioriSigma = -1.0, double angularAccelerationAprioriSigma = -1.0, QList< double > * additionalPointingSigmas = nullptr)
Sets the instrument pointing settings.
Parameters
option Option for how to solve for instrument pointing
solveTwist Whether or not to solve for twist
ckDegree
ckSolveDegree
solvePolynomialOverExisting Indicates whether the polynomial will be fit over an existing pointing polynomial
anglesAprioriSigma A priori angle values
angularVelocityAprioriSigma A priori angular velocity
angularAccelerationAprioriSigma A priori angular acceleration
References AllPointingCoefficients, ckDegree(), ckSolveDegree(), m_anglesAprioriSigma, m_ckDegree, m_ckSolveDegree, m_instrumentPointingSolveOption, m_numberCamAngleCoefSolved, m_pointingInterpolationType, m_solvePointingPolynomialOverExisting, m_solveTwist, Isis::Null, Isis::SpiceRotation::PolyFunction, Isis::SpiceRotation::PolyFunctionOverSpice, and solveTwist().
Referenced by initialize(), and Isis::JigsawSetupDialog::JigsawSetupDialog().
setInstrumentPositionSettings()
void Isis::BundleObservationSolveSettings::setInstrumentPositionSettings (InstrumentPositionSolveOption option, int spkDegree = 2, int spkSolveDegree = 2, bool positionOverHermite = false, double positionAprioriSigma = -1.0, double velocityAprioriSigma = -1.0, double accelerationAprioriSigma = -1.0, QList< double > * additionalPositionSigmas = nullptr)
Sets the instrument pointing settings.
Parameters
option Option for how to solve the instrument position
spkDegree
spkSolveDegree
positionOverHermite Whether or not the polynomial will be fit over an existing Hermite spline
positionAprioriSigma A priori position sigma
velocityAprioriSigma A priori velocity sigma
accelerationAprioriSigma A priori acceleration sigma
References AllPositionCoefficients, m_instrumentPositionSolveOption, m_numberCamPosCoefSolved, m_positionAprioriSigma, m_positionInterpolationType, m_solvePositionOverHermiteSpline, m_spkDegree, m_spkSolveDegree, Isis::Null, Isis::SpicePosition::PolyFunction, Isis::SpicePosition::PolyFunctionOverHermiteConstant, spkDegree(), and spkSolveDegree().
Referenced by initialize().
solvePolyOverPointing()
bool Isis::BundleObservationSolveSettings::solvePolyOverPointing () const
Whether or not the solve polynomial will be fit over the existing pointing polynomial.
Returns
bool Indicates whether the polynomial will be fit over the existing pointing polynomial
References m_solvePointingPolynomialOverExisting.
Referenced by Isis::BundleSolutionInfo::outputHeader(), and Isis::JigsawSetupDialog::treeViewSelectionChanged().
solvePositionOverHermite()
bool Isis::BundleObservationSolveSettings::solvePositionOverHermite () const
Whether or not the polynomial for solving will be fit over an existing Hermite spline.
Returns
bool Returns whether or not to fit the solve polynomial over an existing Hermite spline
References m_solvePositionOverHermiteSpline.
Referenced by Isis::BundleSolutionInfo::outputHeader(), and Isis::JigsawSetupDialog::treeViewSelectionChanged().
solveTwist()
bool Isis::BundleObservationSolveSettings::solveTwist () const
Accesses the flag for solving for twist.
Returns
bool Returns whether or not to solve for twist
References m_solveTwist.
Referenced by Isis::BundleSolutionInfo::outputHeader(), readSolveSettings(), setInstrumentPointingSettings(), and Isis::JigsawSetupDialog::treeViewSelectionChanged().
spkDegree()
int Isis::BundleObservationSolveSettings::spkDegree () const
Accesses the degree of the polynomial fit to the original camera position (spkDegree).
Returns
int Returns the degree of the original camera position polynomial.
References m_spkDegree.
Referenced by Isis::BundleSolutionInfo::outputHeader(), setInstrumentPositionSettings(), and Isis::JigsawSetupDialog::treeViewSelectionChanged().
spkSolveDegree()
int Isis::BundleObservationSolveSettings::spkSolveDegree () const
Accesses the degree of thecamera position polynomial being fit to in the bundle adjustment (spkSolveDegree).
Returns
int Returns the degree of the camera position polynomial in the bundle adjustment.
References m_spkSolveDegree.
Referenced by Isis::BundleSolutionInfo::outputHeader(), setInstrumentPositionSettings(), and Isis::JigsawSetupDialog::treeViewSelectionChanged().
stringToCSMSolveOption()
BundleObservationSolveSettings::CSMSolveOption Isis::BundleObservationSolveSettings::stringToCSMSolveOption (QString option) static
Convert a string to a CSM solve option enumeration value.
Parameters
option The option as a string
Returns
CSMSolveOption The option's enumeration value
References _FILEINFO_, List, NoCSMParameters, Set, Type, and Isis::IException::Unknown.
stringToCSMSolveSet()
csm::param::Set Isis::BundleObservationSolveSettings::stringToCSMSolveSet (QString set) static
Convert a string to its CSM parameter set enumeration value.
Parameters
set The set name
Returns
csm::param::Set The set's enumeration value
References _FILEINFO_, and Isis::IException::Unknown.
Referenced by BundleObservationSolveSettings().
stringToCSMSolveType()
csm::param::Type Isis::BundleObservationSolveSettings::stringToCSMSolveType (QString type) static
Convert a string to its CSM parameter type enumeration value.
Parameters
type The type name
Returns
csm::param::Type The types's enumeration value
References _FILEINFO_, and Isis::IException::Unknown.
Referenced by BundleObservationSolveSettings().
stringToInstrumentPointingSolveOption()
BundleObservationSolveSettings::InstrumentPointingSolveOption Isis::BundleObservationSolveSettings::stringToInstrumentPointingSolveOption (QString option) static
Translates a QString InstrumentPointingSolveOption to its enumerated value.
Parameters
option QString representation of the instrument pointing solve option
Exceptions
IException::Unknown "Unknown bundle instrument point solve option."
Returns
BundleObservationSolveSettings::InstrumentPointingSolveOption Returns the enumerated value of the instrument pointing solve option
References _FILEINFO_, AllPointingCoefficients, AnglesOnly, AnglesVelocity, AnglesVelocityAcceleration, NoPointingFactors, and Isis::IException::Unknown.
Referenced by readSolveSettings().
stringToInstrumentPositionSolveOption()
BundleObservationSolveSettings::InstrumentPositionSolveOption Isis::BundleObservationSolveSettings::stringToInstrumentPositionSolveOption (QString option) static
Translates a QString InstrumentPositionSolveOption to its enumerated value.
Parameters
option QString representation of an instrument position solve option
Exceptions
IExeption::Unknown "Unknown bundle instrument position solve option."
Returns
BundleObservationSolveSettings::InstrumentPositionSolveOption Returns the enumerated value of the instrument position solve option
References _FILEINFO_, AllPositionCoefficients, NoPositionFactors, PositionOnly, PositionVelocity, PositionVelocityAcceleration, and Isis::IException::Unknown.
Referenced by readSolveSettings().
Member Data Documentation
m_anglesAprioriSigma
QList<double> Isis::BundleObservationSolveSettings::m_anglesAprioriSigma
The image position a priori sigmas.The size of the list is equal to the number of coefficients in the solution.
An Isis::Null value implies no weighting will be applied.
Referenced by aprioriPointingSigmas(), BundleObservationSolveSettings(), operator=(), readSolveSettings(), save(), and setInstrumentPointingSettings().
m_ckDegree
int Isis::BundleObservationSolveSettings::m_ckDegree
Degree of the polynomial fit to the original camera angles.
Referenced by BundleObservationSolveSettings(), ckDegree(), operator=(), readSolveSettings(), save(), and setInstrumentPointingSettings().
m_ckSolveDegree
int Isis::BundleObservationSolveSettings::m_ckSolveDegree
Degree of the camera angles polynomial being fit to in the bundle adjustment.
Referenced by BundleObservationSolveSettings(), ckSolveDegree(), operator=(), readSolveSettings(), save(), and setInstrumentPointingSettings().
m_csmSolveList
QStringList Isis::BundleObservationSolveSettings::m_csmSolveList
The names of the CSM parameters to solve for.
Only valid if the solve option is List.
Referenced by BundleObservationSolveSettings(), csmParameterList(), initialize(), operator=(), and setCSMSolveParameterList().
m_csmSolveOption
CSMSolveOption Isis::BundleObservationSolveSettings::m_csmSolveOption
How the CSM solution is specified.
Referenced by BundleObservationSolveSettings(), csmSolveOption(), initialize(), operator=(), setCSMSolveParameterList(), setCSMSolveSet(), and setCSMSolveType().
m_csmSolveSet
csm::param::Set Isis::BundleObservationSolveSettings::m_csmSolveSet
The CSM parameter set to solve for.
Only valid if the solve option is Set.
Referenced by BundleObservationSolveSettings(), csmParameterSet(), initialize(), operator=(), and setCSMSolveSet().
m_csmSolveType
csm::param::Type Isis::BundleObservationSolveSettings::m_csmSolveType
The CSM parameter type to solve for.
Only valid if the solve option is Type.
Referenced by BundleObservationSolveSettings(), csmParameterType(), initialize(), operator=(), and setCSMSolveType().
m_id
QUuid* Isis::BundleObservationSolveSettings::m_id
A unique ID for this object (useful for others to reference this object when saving to disk).
Referenced by BundleObservationSolveSettings(), initialize(), operator=(), save(), and ~BundleObservationSolveSettings().
m_instrumentId
QString Isis::BundleObservationSolveSettings::m_instrumentId
The spacecraft instrument id for this observation.
Referenced by BundleObservationSolveSettings(), initialize(), instrumentId(), operator=(), and setInstrumentId().
m_instrumentPointingSolveOption
InstrumentPointingSolveOption Isis::BundleObservationSolveSettings::m_instrumentPointingSolveOption
Option for how to solve for instrument pointing.
Referenced by BundleObservationSolveSettings(), instrumentPointingSolveOption(), operator=(), readSolveSettings(), save(), and setInstrumentPointingSettings().
m_instrumentPositionSolveOption
InstrumentPositionSolveOption Isis::BundleObservationSolveSettings::m_instrumentPositionSolveOption
Option for how to solve for instrument position.
Referenced by BundleObservationSolveSettings(), instrumentPositionSolveOption(), operator=(), readSolveSettings(), save(), and setInstrumentPositionSettings().
m_numberCamAngleCoefSolved
int Isis::BundleObservationSolveSettings::m_numberCamAngleCoefSolved
The number of camera angle coefficients in solution.
Referenced by BundleObservationSolveSettings(), numberCameraAngleCoefficientsSolved(), operator=(), readSolveSettings(), save(), and setInstrumentPointingSettings().
m_numberCamPosCoefSolved
int Isis::BundleObservationSolveSettings::m_numberCamPosCoefSolved
The number of camera position coefficients in the solution.
Referenced by BundleObservationSolveSettings(), numberCameraPositionCoefficientsSolved(), operator=(), readSolveSettings(), save(), and setInstrumentPositionSettings().
m_observationNumbers
QSet<QString> Isis::BundleObservationSolveSettings::m_observationNumbers
Associated observation numbers for these settings.
Referenced by addObservationNumber(), BundleObservationSolveSettings(), observationNumbers(), operator=(), and removeObservationNumber().
m_pointingInterpolationType
SpiceRotation::Source Isis::BundleObservationSolveSettings::m_pointingInterpolationType
SpiceRotation interpolation type.
Defined in SpiceRotation.cpp, these types are: 1) Spice: directly from kernels, 2) Nadir: Nadir pointing, 3) Memcache: from cached table, 4) PolyFunction: from nth degree polynomial, 5) PolyFunctionOverSpice: kernels plus nth degree polynomial.
Referenced by BundleObservationSolveSettings(), operator=(), pointingInterpolationType(), readSolveSettings(), save(), and setInstrumentPointingSettings().
m_positionAprioriSigma
QList<double> Isis::BundleObservationSolveSettings::m_positionAprioriSigma
The instrument pointing a priori sigmas.
The size of the list is equal to the number of coefficients in the solution. An Isis:Null value implies no weighting will be applied.
Referenced by aprioriPositionSigmas(), BundleObservationSolveSettings(), operator=(), readSolveSettings(), save(), and setInstrumentPositionSettings().
m_positionInterpolationType
SpicePosition::Source Isis::BundleObservationSolveSettings::m_positionInterpolationType
SpicePosition interpolation types.
Defined in SpicePosition.cpp, these types are: 1) Spice: read directly from kernels, 2) Memcache: read from cached table, 3) HermiteCache: read from splined table, 4) PolyFunction: calced from nth degree polynomial, 5) PolyFunctionOverHermiteConstant: read from splined table and adding nth degree polynomial.
Referenced by BundleObservationSolveSettings(), operator=(), positionInterpolationType(), readSolveSettings(), save(), and setInstrumentPositionSettings().
m_solvePointingPolynomialOverExisting
bool Isis::BundleObservationSolveSettings::m_solvePointingPolynomialOverExisting
The polynomial will be fit over the existing pointing polynomial.
Referenced by BundleObservationSolveSettings(), operator=(), readSolveSettings(), save(), setInstrumentPointingSettings(), and solvePolyOverPointing().
m_solvePositionOverHermiteSpline
bool Isis::BundleObservationSolveSettings::m_solvePositionOverHermiteSpline
The polynomial will be fit over an existing Hermite spline.
Referenced by BundleObservationSolveSettings(), operator=(), readSolveSettings(), save(), setInstrumentPositionSettings(), and solvePositionOverHermite().
m_solveTwist
bool Isis::BundleObservationSolveSettings::m_solveTwist
Solve for "twist" angle.
Referenced by BundleObservationSolveSettings(), operator=(), readSolveSettings(), save(), setInstrumentPointingSettings(), and solveTwist().
m_spkDegree
int Isis::BundleObservationSolveSettings::m_spkDegree
Degree of the polynomial fit to the original camera position.
Referenced by BundleObservationSolveSettings(), operator=(), readSolveSettings(), save(), setInstrumentPositionSettings(), and spkDegree().
m_spkSolveDegree
int Isis::BundleObservationSolveSettings::m_spkSolveDegree
Degree of the camera position polynomial being fit to in the bundle adjustment.
Referenced by BundleObservationSolveSettings(), operator=(), readSolveSettings(), save(), setInstrumentPositionSettings(), and spkSolveDegree().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/BundleUtilities/BundleObservationSolveSettings.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/BundleUtilities/BundleObservationSolveSettings.cpp