Isis Developer Reference: Isis::AdjustedLatitudeSigmaFilter Class Reference
Isis::AdjustedLatitudeSigmaFilter Class Reference
Allows filtering by adjusted surface point latitude sigma.
#include <AdjustedLatitudeSigmaFilter.h>
Public Types
enum FilterEffectiveness { Images = 1 , Points = 2 , Measures = 4 }
Signals
void filterChanged ()
Public Member Functions
AdjustedLatitudeSigmaFilter (AbstractFilter::FilterEffectivenessFlag flag, int minimumForSuccess=-1)
AdjustedLatitudeSigmaFilter (const AdjustedLatitudeSigmaFilter &other)
virtual ~AdjustedLatitudeSigmaFilter ()
bool evaluate (const QPair< QString, ControlNet * > *) const
bool evaluate (const ControlPoint *) const
bool evaluate (const ControlMeasure *) const
AbstractFilter * clone () const
QString getImageDescription () const
QString getPointDescription () const
virtual bool canFilterImages () const
virtual bool canFilterPoints () const
virtual bool canFilterMeasures () const
virtual QString getMeasureDescription () const
Protected Member Functions
bool evaluate (double) const
virtual bool evaluate (const ControlPoint *, bool(ControlPoint::*)() const) const
virtual bool evaluate (const ControlMeasure *, bool(ControlMeasure::*)() const) const
QString descriptionSuffix () const
bool lessThan () const
bool inclusive () const
int getMinForSuccess () const
AbstractFilter::FilterEffectivenessFlag * getEffectivenessFlags () const
QBoxLayout * getMainLayout () const
QBoxLayout * getInclusiveExclusiveLayout () const
bool evaluateImageFromPointFilter (const QPair< QString, ControlNet * > *) const
bool evaluateImageFromMeasureFilter (const QPair< QString, ControlNet * > *) const
bool evaluatePointFromMeasureFilter (const ControlPoint *) const
Detailed Description
Allows filtering by adjusted surface point latitude sigma.
This class allows the user to filter control points and control measures by adjusted surface point latitude sigma. This allows the user to make a list of control points that are less than or greater than a certain adjusted surface point latitude sigma.
Author
2012-04-25 Jai Rideout
Member Enumeration Documentation
FilterEffectiveness
enum Isis::AbstractFilter::FilterEffectiveness inherited
Enumerator
Images
Points
Measures
Constructor & Destructor Documentation
AdjustedLatitudeSigmaFilter() [1/2]
Isis::AdjustedLatitudeSigmaFilter::AdjustedLatitudeSigmaFilter (AbstractFilter::FilterEffectivenessFlag flag, int minimumForSuccess = -1)
Referenced by clone().
AdjustedLatitudeSigmaFilter() [2/2]
Isis::AdjustedLatitudeSigmaFilter::AdjustedLatitudeSigmaFilter (const AdjustedLatitudeSigmaFilter & other)
~AdjustedLatitudeSigmaFilter()
Isis::AdjustedLatitudeSigmaFilter::~AdjustedLatitudeSigmaFilter () virtual
Member Function Documentation
canFilterImages()
bool Isis::AbstractFilter::canFilterImages () const virtual inherited
References Isis::AbstractFilter::Images.
Referenced by Isis::FilterWidget::evaluate(), Isis::AbstractFilter::evaluateImageFromMeasureFilter(), and Isis::AbstractFilter::evaluateImageFromPointFilter().
canFilterMeasures()
bool Isis::AbstractFilter::canFilterMeasures () const virtual inherited
References Isis::AbstractFilter::Measures.
Referenced by Isis::FilterWidget::evaluate().
canFilterPoints()
bool Isis::AbstractFilter::canFilterPoints () const virtual inherited
References Isis::AbstractFilter::Points.
Referenced by Isis::FilterWidget::evaluate(), and Isis::AbstractFilter::evaluatePointFromMeasureFilter().
clone()
AbstractFilter * Isis::AdjustedLatitudeSigmaFilter::clone () const virtual
Implements Isis::AbstractFilter.
References AdjustedLatitudeSigmaFilter().
descriptionSuffix()
QString Isis::AbstractNumberFilter::descriptionSuffix () const protected inherited
References Isis::AbstractFilter::inclusive(), and Isis::AbstractNumberFilter::lessThan().
Referenced by Isis::AdjustedLatitudeFilter::getImageDescription(), getImageDescription(), Isis::AdjustedLongitudeFilter::getImageDescription(), Isis::AdjustedLongitudeSigmaFilter::getImageDescription(), Isis::AdjustedRadiusFilter::getImageDescription(), Isis::AdjustedRadiusSigmaFilter::getImageDescription(), Isis::AdjustedXFilter::getImageDescription(), Isis::AdjustedXSigmaFilter::getImageDescription(), Isis::AdjustedYFilter::getImageDescription(), Isis::AdjustedYSigmaFilter::getImageDescription(), Isis::AdjustedZFilter::getImageDescription(), Isis::AdjustedZSigmaFilter::getImageDescription(), Isis::APrioriLatitudeFilter::getImageDescription(), Isis::APrioriLatitudeSigmaFilter::getImageDescription(), Isis::APrioriLongitudeFilter::getImageDescription(), Isis::APrioriLongitudeSigmaFilter::getImageDescription(), Isis::APrioriRadiusFilter::getImageDescription(), Isis::APrioriRadiusSigmaFilter::getImageDescription(), Isis::APrioriXFilter::getImageDescription(), Isis::APrioriXSigmaFilter::getImageDescription(), Isis::APrioriYFilter::getImageDescription(), Isis::APrioriYSigmaFilter::getImageDescription(), Isis::APrioriZFilter::getImageDescription(), Isis::APrioriZSigmaFilter::getImageDescription(), Isis::GoodnessOfFitFilter::getImageDescription(), Isis::LineFilter::getImageDescription(), Isis::LineResidualFilter::getImageDescription(), Isis::LineShiftFilter::getImageDescription(), Isis::ResidualMagnitudeFilter::getImageDescription(), Isis::SampleFilter::getImageDescription(), Isis::SampleResidualFilter::getImageDescription(), Isis::SampleShiftFilter::getImageDescription(), Isis::GoodnessOfFitFilter::getMeasureDescription(), Isis::LineFilter::getMeasureDescription(), Isis::LineResidualFilter::getMeasureDescription(), Isis::LineShiftFilter::getMeasureDescription(), Isis::ResidualMagnitudeFilter::getMeasureDescription(), Isis::SampleFilter::getMeasureDescription(), Isis::SampleResidualFilter::getMeasureDescription(), Isis::SampleShiftFilter::getMeasureDescription(), Isis::AdjustedLatitudeFilter::getPointDescription(), getPointDescription(), Isis::AdjustedLongitudeFilter::getPointDescription(), Isis::AdjustedLongitudeSigmaFilter::getPointDescription(), Isis::AdjustedRadiusFilter::getPointDescription(), Isis::AdjustedRadiusSigmaFilter::getPointDescription(), Isis::AdjustedXFilter::getPointDescription(), Isis::AdjustedXSigmaFilter::getPointDescription(), Isis::AdjustedYFilter::getPointDescription(), Isis::AdjustedYSigmaFilter::getPointDescription(), Isis::AdjustedZFilter::getPointDescription(), Isis::AdjustedZSigmaFilter::getPointDescription(), Isis::APrioriLatitudeFilter::getPointDescription(), Isis::APrioriLatitudeSigmaFilter::getPointDescription(), Isis::APrioriLongitudeFilter::getPointDescription(), Isis::APrioriLongitudeSigmaFilter::getPointDescription(), Isis::APrioriRadiusFilter::getPointDescription(), Isis::APrioriRadiusSigmaFilter::getPointDescription(), Isis::APrioriXFilter::getPointDescription(), Isis::APrioriXSigmaFilter::getPointDescription(), Isis::APrioriYFilter::getPointDescription(), Isis::APrioriYSigmaFilter::getPointDescription(), Isis::APrioriZFilter::getPointDescription(), and Isis::APrioriZSigmaFilter::getPointDescription().
evaluate() [1/6]
bool Isis::AdjustedLatitudeSigmaFilter::evaluate (const ControlMeasure * measure) const virtual
Implements Isis::AbstractFilter.
evaluate() [2/6]
bool Isis::AbstractFilter::evaluate (const ControlMeasure * measure, bool(ControlMeasure::*)() const meth) const protected virtual inherited
References Isis::AbstractFilter::inclusive().
evaluate() [3/6]
bool Isis::AdjustedLatitudeSigmaFilter::evaluate (const ControlPoint * point) const virtual
Implements Isis::AbstractFilter.
References Isis::AbstractNumberFilter::evaluate(), Isis::ControlPoint::GetAdjustedSurfacePoint(), Isis::SurfacePoint::GetLatSigmaDistance(), and Isis::Distance::meters().
evaluate() [4/6]
bool Isis::AbstractFilter::evaluate (const ControlPoint * point, bool(ControlPoint::*)() const meth) const protected virtual inherited
References Isis::AbstractFilter::inclusive().
evaluate() [5/6]
bool Isis::AdjustedLatitudeSigmaFilter::evaluate (const QPair< QString, ControlNet * > * imageAndNet) const virtual
Implements Isis::AbstractFilter.
References Isis::AbstractFilter::evaluateImageFromPointFilter().
evaluate() [6/6]
bool Isis::AbstractNumberFilter::evaluate (double number) const protected inherited
References Isis::AbstractFilter::inclusive(), and Isis::AbstractNumberFilter::lessThan().
Referenced by Isis::GoodnessOfFitFilter::evaluate(), Isis::LineFilter::evaluate(), Isis::LineResidualFilter::evaluate(), Isis::LineShiftFilter::evaluate(), Isis::ResidualMagnitudeFilter::evaluate(), Isis::SampleFilter::evaluate(), Isis::SampleResidualFilter::evaluate(), Isis::SampleShiftFilter::evaluate(), Isis::AdjustedLatitudeFilter::evaluate(), evaluate(), Isis::AdjustedLongitudeFilter::evaluate(), Isis::AdjustedLongitudeSigmaFilter::evaluate(), Isis::AdjustedRadiusFilter::evaluate(), Isis::AdjustedRadiusSigmaFilter::evaluate(), Isis::AdjustedXFilter::evaluate(), Isis::AdjustedXSigmaFilter::evaluate(), Isis::AdjustedYFilter::evaluate(), Isis::AdjustedYSigmaFilter::evaluate(), Isis::AdjustedZFilter::evaluate(), Isis::AdjustedZSigmaFilter::evaluate(), Isis::APrioriLatitudeFilter::evaluate(), Isis::APrioriLatitudeSigmaFilter::evaluate(), Isis::APrioriLongitudeFilter::evaluate(), Isis::APrioriLongitudeSigmaFilter::evaluate(), Isis::APrioriRadiusFilter::evaluate(), Isis::APrioriRadiusSigmaFilter::evaluate(), Isis::APrioriXFilter::evaluate(), Isis::APrioriXSigmaFilter::evaluate(), Isis::APrioriYFilter::evaluate(), Isis::APrioriYSigmaFilter::evaluate(), Isis::APrioriZFilter::evaluate(), and Isis::APrioriZSigmaFilter::evaluate().
evaluateImageFromMeasureFilter()
bool Isis::AbstractFilter::evaluateImageFromMeasureFilter (const QPair< QString, ControlNet * > * imageAndNet) const protected inherited
References Isis::AbstractFilter::canFilterImages().
Referenced by Isis::GoodnessOfFitFilter::evaluate(), Isis::LineFilter::evaluate(), Isis::LineResidualFilter::evaluate(), Isis::LineShiftFilter::evaluate(), Isis::MeasureIgnoredFilter::evaluate(), Isis::MeasureJigsawRejectedFilter::evaluate(), Isis::MeasureTypeFilter::evaluate(), Isis::ResidualMagnitudeFilter::evaluate(), Isis::SampleFilter::evaluate(), Isis::SampleResidualFilter::evaluate(), and Isis::SampleShiftFilter::evaluate().
evaluateImageFromPointFilter()
bool Isis::AbstractFilter::evaluateImageFromPointFilter (const QPair< QString, ControlNet * > * imageAndNet) const protected inherited
References Isis::AbstractFilter::canFilterImages().
Referenced by Isis::AdjustedLatitudeFilter::evaluate(), evaluate(), Isis::AdjustedLongitudeFilter::evaluate(), Isis::AdjustedLongitudeSigmaFilter::evaluate(), Isis::AdjustedRadiusFilter::evaluate(), Isis::AdjustedRadiusSigmaFilter::evaluate(), Isis::AdjustedXFilter::evaluate(), Isis::AdjustedXSigmaFilter::evaluate(), Isis::AdjustedYFilter::evaluate(), Isis::AdjustedYSigmaFilter::evaluate(), Isis::AdjustedZFilter::evaluate(), Isis::AdjustedZSigmaFilter::evaluate(), Isis::APrioriLatitudeFilter::evaluate(), Isis::APrioriLatitudeSigmaFilter::evaluate(), Isis::APrioriLongitudeFilter::evaluate(), Isis::APrioriLongitudeSigmaFilter::evaluate(), Isis::APrioriRadiusFilter::evaluate(), Isis::APrioriRadiusSigmaFilter::evaluate(), Isis::APrioriXFilter::evaluate(), Isis::APrioriXSigmaFilter::evaluate(), Isis::APrioriYFilter::evaluate(), Isis::APrioriYSigmaFilter::evaluate(), Isis::APrioriZFilter::evaluate(), Isis::APrioriZSigmaFilter::evaluate(), Isis::ChooserNameFilter::evaluate(), Isis::MeasureCountFilter::evaluate(), Isis::PointEditLockedFilter::evaluate(), Isis::PointIdFilter::evaluate(), Isis::PointIgnoredFilter::evaluate(), Isis::PointJigsawRejectedFilter::evaluate(), and Isis::PointTypeFilter::evaluate().
evaluatePointFromMeasureFilter()
bool Isis::AbstractFilter::evaluatePointFromMeasureFilter (const ControlPoint * point) const protected inherited
References Isis::AbstractFilter::canFilterPoints(), and Isis::ControlPoint::getMeasures().
Referenced by Isis::GoodnessOfFitFilter::evaluate(), Isis::ImageIdFilter::evaluate(), Isis::LineFilter::evaluate(), Isis::LineResidualFilter::evaluate(), Isis::LineShiftFilter::evaluate(), Isis::MeasureIgnoredFilter::evaluate(), Isis::MeasureJigsawRejectedFilter::evaluate(), Isis::MeasureTypeFilter::evaluate(), Isis::ResidualMagnitudeFilter::evaluate(), Isis::SampleFilter::evaluate(), Isis::SampleResidualFilter::evaluate(), and Isis::SampleShiftFilter::evaluate().
filterChanged
void Isis::AbstractFilter::filterChanged () signal inherited
getEffectivenessFlags()
AbstractFilter::FilterEffectivenessFlag * Isis::AbstractFilter::getEffectivenessFlags () const protected inherited
getImageDescription()
QString Isis::AdjustedLatitudeSigmaFilter::getImageDescription () const virtual
Reimplemented from Isis::AbstractFilter.
References Isis::AbstractNumberFilter::descriptionSuffix(), Isis::AbstractFilter::getImageDescription(), and Isis::AbstractFilter::getMinForSuccess().
getInclusiveExclusiveLayout()
QBoxLayout * Isis::AbstractFilter::getInclusiveExclusiveLayout () const protected inherited
getMainLayout()
QBoxLayout * Isis::AbstractFilter::getMainLayout () const protected inherited
Referenced by Isis::AbstractMultipleChoiceFilter::createWidget().
getMeasureDescription()
QString Isis::AbstractFilter::getMeasureDescription () const virtual inherited
Reimplemented in Isis::SampleShiftFilter, Isis::SampleResidualFilter, Isis::SampleFilter, Isis::ResidualMagnitudeFilter, Isis::MeasureTypeFilter, Isis::MeasureJigsawRejectedFilter, Isis::MeasureIgnoredFilter, Isis::LineShiftFilter, Isis::LineResidualFilter, Isis::LineFilter, Isis::ImageIdFilter, and Isis::GoodnessOfFitFilter.
getMinForSuccess()
int Isis::AbstractFilter::getMinForSuccess () const inline protected inherited
Referenced by Isis::AbstractFilter::getImageDescription(), Isis::AdjustedLatitudeFilter::getImageDescription(), getImageDescription(), Isis::AdjustedLongitudeFilter::getImageDescription(), Isis::AdjustedLongitudeSigmaFilter::getImageDescription(), Isis::AdjustedRadiusFilter::getImageDescription(), Isis::AdjustedRadiusSigmaFilter::getImageDescription(), Isis::AdjustedXFilter::getImageDescription(), Isis::AdjustedXSigmaFilter::getImageDescription(), Isis::AdjustedYFilter::getImageDescription(), Isis::AdjustedYSigmaFilter::getImageDescription(), Isis::AdjustedZFilter::getImageDescription(), Isis::AdjustedZSigmaFilter::getImageDescription(), Isis::APrioriLatitudeFilter::getImageDescription(), Isis::APrioriLatitudeSigmaFilter::getImageDescription(), Isis::APrioriLongitudeFilter::getImageDescription(), Isis::APrioriLongitudeSigmaFilter::getImageDescription(), Isis::APrioriRadiusFilter::getImageDescription(), Isis::APrioriRadiusSigmaFilter::getImageDescription(), Isis::APrioriXFilter::getImageDescription(), Isis::APrioriXSigmaFilter::getImageDescription(), Isis::APrioriYFilter::getImageDescription(), Isis::APrioriYSigmaFilter::getImageDescription(), Isis::APrioriZFilter::getImageDescription(), Isis::APrioriZSigmaFilter::getImageDescription(), Isis::ChooserNameFilter::getImageDescription(), Isis::GoodnessOfFitFilter::getImageDescription(), Isis::LineFilter::getImageDescription(), Isis::LineResidualFilter::getImageDescription(), Isis::LineShiftFilter::getImageDescription(), Isis::MeasureCountFilter::getImageDescription(), Isis::MeasureIgnoredFilter::getImageDescription(), Isis::MeasureJigsawRejectedFilter::getImageDescription(), Isis::MeasureTypeFilter::getImageDescription(), Isis::PointEditLockedFilter::getImageDescription(), Isis::PointIdFilter::getImageDescription(), Isis::PointIgnoredFilter::getImageDescription(), Isis::PointJigsawRejectedFilter::getImageDescription(), Isis::PointTypeFilter::getImageDescription(), Isis::ResidualMagnitudeFilter::getImageDescription(), Isis::SampleFilter::getImageDescription(), Isis::SampleResidualFilter::getImageDescription(), Isis::SampleShiftFilter::getImageDescription(), and Isis::ImageIdFilter::getPointDescription().
getPointDescription()
QString Isis::AdjustedLatitudeSigmaFilter::getPointDescription () const virtual
Reimplemented from Isis::AbstractFilter.
References Isis::AbstractNumberFilter::descriptionSuffix().
inclusive()
bool Isis::AbstractFilter::inclusive () const protected inherited
Referenced by Isis::AbstractNumberFilter::descriptionSuffix(), Isis::AbstractStringFilter::descriptionSuffix(), Isis::MeasureTypeFilter::evaluate(), Isis::PointTypeFilter::evaluate(), Isis::AbstractFilter::evaluate(), Isis::AbstractNumberFilter::evaluate(), Isis::AbstractStringFilter::evaluate(), Isis::MeasureCountFilter::getImageDescription(), Isis::MeasureIgnoredFilter::getImageDescription(), Isis::MeasureJigsawRejectedFilter::getImageDescription(), Isis::MeasureTypeFilter::getImageDescription(), Isis::PointEditLockedFilter::getImageDescription(), Isis::PointIgnoredFilter::getImageDescription(), Isis::PointJigsawRejectedFilter::getImageDescription(), Isis::PointTypeFilter::getImageDescription(), Isis::MeasureIgnoredFilter::getMeasureDescription(), Isis::MeasureJigsawRejectedFilter::getMeasureDescription(), Isis::MeasureTypeFilter::getMeasureDescription(), Isis::MeasureCountFilter::getPointDescription(), Isis::PointEditLockedFilter::getPointDescription(), Isis::PointIgnoredFilter::getPointDescription(), Isis::PointJigsawRejectedFilter::getPointDescription(), and Isis::PointTypeFilter::getPointDescription().
lessThan()
bool Isis::AbstractNumberFilter::lessThan () const protected inherited
Referenced by Isis::AbstractNumberFilter::descriptionSuffix(), and Isis::AbstractNumberFilter::evaluate().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/AdjustedLatitudeSigmaFilter.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/AdjustedLatitudeSigmaFilter.cpp