Isis Developer Reference: Isis::NormModel Class Reference
Isis::NormModel Class Reference abstract
#include <NormModel.h>
Public Member Functions
NormModel (Pvl &pvl, PhotoModel &pmodel)
Create a NormModel object.
NormModel (Pvl &pvl, PhotoModel &pmodel, AtmosModel &amodel)
Create a NormModel object.
virtual ~NormModel ()
std::string AlgorithmName () const
Return normalization algorithm name.
void CalcNrmAlbedo (double pha, double inc, double ema, double dn, double &albedo, double &mult, double &base)
Calculate the albedo normalization.
void CalcNrmAlbedo (double pha, double inc, double ema, double deminc, double demema, double dn, double &albedo, double &mult, double &base)
Calculate the normalization albedo using photometric angle information.
virtual void SetNormWavelength (double wavelength)
Set the wavelength parameter.
Protected Member Functions
virtual void NormModelAlgorithm (double pha, double inc, double ema, double dn, double &albedo, double &mult, double &base)=0
virtual void NormModelAlgorithm (double pha, double inc, double ema, double deminc, double demema, double dn, double &albedo, double &mult, double &base)=0
void SetAlgorithmName (std::string name)
PhotoModel * GetPhotoModel ()
AtmosModel * GetAtmosModel ()
Protected Attributes
double p_normWavelength
Detailed Description
Author
1998-12-21 Randy Kirk
Constructor & Destructor Documentation
NormModel() [1/2]
Isis::NormModel::NormModel (Pvl & pvl, PhotoModel & pmodel)
Create a NormModel object.
Because this is a pure virtual class you can not create a NormModel class directly. Instead, see the NormModelFactory class.
Parameters
pvl A pvl object containing a valid NormModel specification
See also
normalizationModels.doc
References p_normWavelength.
NormModel() [2/2]
Isis::NormModel::NormModel (Pvl & pvl, PhotoModel & pmodel, AtmosModel & amodel)
Create a NormModel object.
Because this is a pure virtual class you can not create a NormModel class directly. Instead, see the NormModelFactory class.
Parameters
pvl A pvl object containing a valid NormModel specification
See also
normalizationModels.doc
References p_normWavelength.
~NormModel()
virtual Isis::NormModel::~NormModel () inline virtual
Member Function Documentation
AlgorithmName()
std::string Isis::NormModel::AlgorithmName () const inline
Return normalization algorithm name.
CalcNrmAlbedo() [1/2]
void Isis::NormModel::CalcNrmAlbedo (double pha, double inc, double ema, double deminc, double demema, double dn, double & albedo, double & mult, double & base)
Calculate the normalization albedo using photometric angle information.
Parameters
pha input phase angle
inc input incidence angle for ellipsoid
ema input emission angle for ellipsoid
deminc input incidence angle for dem
demema input emission angle for dem
dn input albedo value
References NormModelAlgorithm().
CalcNrmAlbedo() [2/2]
void Isis::NormModel::CalcNrmAlbedo (double pha, double inc, double ema, double dn, double & albedo, double & mult, double & base)
Calculate the albedo normalization.
Calculate the normalization albedo using photometric angle information.
Parameters
pha input phase angle
inc input incidence angle
ema input emission angle
dn input albedo value
References NormModelAlgorithm().
Referenced by Isis::Photometry::Compute().
GetAtmosModel()
AtmosModel* Isis::NormModel::GetAtmosModel () inline protected
Referenced by Isis::AlbedoAtm::AlbedoAtm(), Isis::AlbedoAtm::NormModelAlgorithm(), Isis::ShadeAtm::NormModelAlgorithm(), Isis::TopoAtm::NormModelAlgorithm(), and Isis::TopoAtm::TopoAtm().
GetPhotoModel()
PhotoModel* Isis::NormModel::GetPhotoModel () inline protected
Referenced by Isis::Albedo::Albedo(), Isis::AlbedoAtm::AlbedoAtm(), Isis::Mixed::Mixed(), Isis::Albedo::NormModelAlgorithm(), Isis::AlbedoAtm::NormModelAlgorithm(), Isis::Mixed::NormModelAlgorithm(), Isis::MoonAlbedo::NormModelAlgorithm(), Isis::NoNormalization::NormModelAlgorithm(), Isis::Shade::NormModelAlgorithm(), Isis::ShadeAtm::NormModelAlgorithm(), Isis::Topo::NormModelAlgorithm(), Isis::TopoAtm::NormModelAlgorithm(), and Isis::TopoAtm::TopoAtm().
NormModelAlgorithm() [1/2]
virtual void Isis::NormModel::NormModelAlgorithm (double pha, double inc, double ema, double deminc, double demema, double dn, double & albedo, double & mult, double & base) protected pure virtual
Implemented in Isis::TopoAtm, Isis::Topo, Isis::ShadeAtm, Isis::Shade, Isis::NoNormalization, Isis::MoonAlbedo, Isis::Mixed, Isis::AlbedoAtm, and Isis::Albedo.
NormModelAlgorithm() [2/2]
virtual void Isis::NormModel::NormModelAlgorithm (double pha, double inc, double ema, double dn, double & albedo, double & mult, double & base) protected pure virtual
Implemented in Isis::TopoAtm, Isis::Topo, Isis::ShadeAtm, Isis::Shade, Isis::NoNormalization, Isis::MoonAlbedo, Isis::Mixed, Isis::AlbedoAtm, and Isis::Albedo.
Referenced by CalcNrmAlbedo().
SetAlgorithmName()
void Isis::NormModel::SetAlgorithmName (std::string name) inline protected
SetNormWavelength()
void Isis::NormModel::SetNormWavelength (double wavelength) virtual
Set the wavelength parameter.
This value is obtained from the BandBin Center keyword of the image. This must be set by the application.
References p_normWavelength.
Referenced by Isis::Photometry::SetPhotomWl().
Member Data Documentation
p_normWavelength
double Isis::NormModel::p_normWavelength protected
Referenced by Isis::MoonAlbedo::MoonAlbedo(), NormModel(), and SetNormWavelength().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/NormModel/NormModel.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/NormModel/NormModel.cpp