Isis Developer Reference: Isis::MosaicGridToolConfigDialog Class Reference
Isis::MosaicGridToolConfigDialog Class Reference
Configure user's settings for the grid tool.
#include <MosaicGridToolConfigDialog.h>
Public Slots
void applySettings ()
Slot that calls applySettings with true to call readSettings also.
void applySettings (bool shouldReadSettings)
Apply the user's current settings to the tool.
void readSettings ()
Read the tool's current settings and set the widget states to match.
void refreshWidgetStates ()
Calls the private method refreshWidgetStates with true as the argument in order to have refreshWidgetStates call apply settings.
void onBaseLatSliderChanged ()
Updates the corresponding line edit when the baseLatSlider changes.
void onBaseLonSliderChanged ()
Updates the corresponding line edit when the baseLonSlider changes.
void onLatIncSliderChanged ()
Updates the corresponding line edit when the latIncSlider changes.
void onLonIncSliderChanged ()
Updates the corresponding line edit when the lonIncSlider changes.
void onExtentTypeChanged ()
Updates the dialog when the lat or lon extent source is changed.
void onMinLatExtentSliderChanged ()
Updates the corresponding line edit when the minLatSlider changes.
void onMaxLatExtentSliderChanged ()
Updates the corresponding line edit when the maxLatSlider changes.
void onMinLonExtentSliderChanged ()
Updates the corresponding line edit when the minLonSlider changes.
void onMaxLonExtentSliderChanged ()
Updates the corresponding line edit when the maxLonSlider changes.
Public Member Functions
MosaicGridToolConfigDialog (MosaicGridTool *tool, QWidget *parent)
Create a config dialog that configures the given MosaicGridTool.
~MosaicGridToolConfigDialog ()
Clean up allocated memory.
Detailed Description
Configure user's settings for the grid tool.
This dialog enables the user to configure the given grid tool. You can show or hid the grid, draw an auto grid that is based on the open cubes or the user selected grid extents, and change the parameters of a custom drawn grid. It allows the user to select the source of the longitude and latitude ranges (from the map, from the open cubes, or manually entered). The widgets are enabled/disabled depending on the state of the tool. There is also an option to 'auto apply' the grid settings, which allows the user to see live updates of the grid as the parameters are changed. If the tool and dialog take too long to update the grid, the density will be reduced to increase the speed with which the grid is drawn. References #604.
Author
2012-07-25 Kimberly Oyama and Steven Lambright
Constructor & Destructor Documentation
MosaicGridToolConfigDialog()
Isis::MosaicGridToolConfigDialog::MosaicGridToolConfigDialog (MosaicGridTool * tool, QWidget * parent)
Create a config dialog that configures the given MosaicGridTool.
Parameters
tool The tool to read settings from and write settings to.
parent The qt-parent relationship parent.
References applySettings(), Isis::MosaicGridTool::Cubes, Isis::MosaicGridTool::latExtents(), Isis::MosaicGridTool::latType(), Isis::MosaicGridTool::lonDomain(), Isis::MosaicGridTool::lonExtents(), Isis::MosaicGridTool::Manual, Isis::MosaicGridTool::Map, onBaseLatSliderChanged(), onBaseLonSliderChanged(), onExtentTypeChanged(), onLatIncSliderChanged(), onLonIncSliderChanged(), onMaxLatExtentSliderChanged(), onMaxLonExtentSliderChanged(), onMinLatExtentSliderChanged(), onMinLonExtentSliderChanged(), readSettings(), and refreshWidgetStates().
~MosaicGridToolConfigDialog()
Isis::MosaicGridToolConfigDialog::~MosaicGridToolConfigDialog ()
Clean up allocated memory.
Member Function Documentation
applySettings [1/2]
void Isis::MosaicGridToolConfigDialog::applySettings () slot
Slot that calls applySettings with true to call readSettings also.
Referenced by MosaicGridToolConfigDialog(), and onExtentTypeChanged().
applySettings [2/2]
void Isis::MosaicGridToolConfigDialog::applySettings (bool shouldReadSettings) slot
Apply the user's current settings to the tool.
Draw or clear the grid depending on the settings.
References _FILEINFO_, Isis::MosaicGridTool::autoGrid(), Isis::MosaicGridTool::clearGrid(), Isis::Angle::Degrees, Isis::MosaicGridTool::drawGrid(), Isis::MosaicSceneWidget::getProjection(), Isis::Projection::Mapping(), readSettings(), Isis::MosaicGridTool::sceneWidget(), Isis::MosaicGridTool::setAutoGridCheckBox(), Isis::MosaicGridTool::setBaseLat(), Isis::MosaicGridTool::setBaseLon(), Isis::MosaicGridTool::setDensity(), Isis::MosaicGridTool::setLatExtents(), Isis::MosaicGridTool::setLatInc(), Isis::MosaicGridTool::setLonExtents(), Isis::MosaicGridTool::setLonInc(), Isis::MosaicGridTool::setShowGrid(), and Isis::IException::Unknown.
onBaseLatSliderChanged
void Isis::MosaicGridToolConfigDialog::onBaseLatSliderChanged () slot
Updates the corresponding line edit when the baseLatSlider changes.
Referenced by MosaicGridToolConfigDialog().
onBaseLonSliderChanged
void Isis::MosaicGridToolConfigDialog::onBaseLonSliderChanged () slot
Updates the corresponding line edit when the baseLonSlider changes.
Referenced by MosaicGridToolConfigDialog().
onExtentTypeChanged
void Isis::MosaicGridToolConfigDialog::onExtentTypeChanged () slot
Updates the dialog when the lat or lon extent source is changed.
This is necessary because the tools values will change and they need to be brought back to the dialog.
References applySettings(), and refreshWidgetStates().
Referenced by MosaicGridToolConfigDialog().
onLatIncSliderChanged
void Isis::MosaicGridToolConfigDialog::onLatIncSliderChanged () slot
Updates the corresponding line edit when the latIncSlider changes.
Referenced by MosaicGridToolConfigDialog().
onLonIncSliderChanged
void Isis::MosaicGridToolConfigDialog::onLonIncSliderChanged () slot
Updates the corresponding line edit when the lonIncSlider changes.
Referenced by MosaicGridToolConfigDialog().
onMaxLatExtentSliderChanged
void Isis::MosaicGridToolConfigDialog::onMaxLatExtentSliderChanged () slot
Updates the corresponding line edit when the maxLatSlider changes.
Referenced by MosaicGridToolConfigDialog().
onMaxLonExtentSliderChanged
void Isis::MosaicGridToolConfigDialog::onMaxLonExtentSliderChanged () slot
Updates the corresponding line edit when the maxLonSlider changes.
Referenced by MosaicGridToolConfigDialog().
onMinLatExtentSliderChanged
void Isis::MosaicGridToolConfigDialog::onMinLatExtentSliderChanged () slot
Updates the corresponding line edit when the minLatSlider changes.
Referenced by MosaicGridToolConfigDialog().
onMinLonExtentSliderChanged
void Isis::MosaicGridToolConfigDialog::onMinLonExtentSliderChanged () slot
Updates the corresponding line edit when the minLonSlider changes.
Referenced by MosaicGridToolConfigDialog().
readSettings
void Isis::MosaicGridToolConfigDialog::readSettings () slot
Read the tool's current settings and set the widget states to match.
References Isis::MosaicGridTool::autoGridCheckBox(), Isis::MosaicGridTool::baseLat(), Isis::MosaicGridTool::baseLon(), Isis::Angle::Degrees, Isis::Angle::degrees(), Isis::MosaicGridTool::density(), Isis::MosaicSceneWidget::getProjection(), Isis::MosaicGridTool::latExtents(), Isis::MosaicGridTool::latInc(), Isis::MosaicGridTool::lonExtents(), Isis::MosaicGridTool::lonInc(), Isis::Projection::Mapping(), Isis::MosaicGridTool::maxLat(), Isis::MosaicGridTool::maxLon(), Isis::MosaicGridTool::minLat(), Isis::MosaicGridTool::minLon(), Isis::Latitude::planetographic(), refreshWidgetStates(), Isis::MosaicGridTool::sceneWidget(), and Isis::MosaicGridTool::showGrid().
Referenced by applySettings(), and MosaicGridToolConfigDialog().
refreshWidgetStates
void Isis::MosaicGridToolConfigDialog::refreshWidgetStates () slot
Calls the private method refreshWidgetStates with true as the argument in order to have refreshWidgetStates call apply settings.
Referenced by MosaicGridToolConfigDialog(), onExtentTypeChanged(), and readSettings().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/MosaicGridToolConfigDialog.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/MosaicGridToolConfigDialog.cpp