Isis Developer Reference: Isis::ImageImporter Class Reference
Isis::ImageImporter Class Reference abstract
High Level Cube I/O
Imports images with standard formats into Isis as cubes.
#include <ImageImporter.h>
Public Member Functions
ImageImporter (FileName inputName)
Construct the importer.
virtual ~ImageImporter ()
Destruct the importer.
void operator() (Buffer &out) const
The method for processing the output cube in place, called for each line of the output image.
Cube * import (FileName outputName)
Import the image with default output attributes.
Cube * import (FileName outputName, CubeAttributeOutput &att)
Import the input image this instance was constructed with into the given output Isis cube with the given output attributes.
void setNullRange (double min, double max)
Set the range of DN values within which a pixel from the input image will be set to Null in the output.
void setLrsRange (double min, double max)
Set the range of DN values within which a pixel from the input image will be set to LRS in the output.
void setHrsRange (double min, double max)
Set the range of DN values within which a pixel from the input image will be set to HRS in the output.
void setSamples (int s)
Set the sample dimension (width) of the output image.
void setLines (int l)
Set the line dimension (height) of the output image.
void setBands (int b)
Set the band dimension (depth) of the output image.
int samples () const
The sample dimension (width) of the output image.
int lines () const
The line dimension (height) of the output image.
int bands () const
The band dimension (depth) of the output image.
FileName filename () const
The filename of the input image this instance was constructed with.
virtual PvlGroup convertProjection () const
Pure virtual method for converting projection information in the file being imported to an ISIS Mapping group.
virtual bool isGrayscale () const =0
Pure virtual method for returning true if the image is grayscale.
virtual bool isRgb () const =0
Pure virtual method for returning true if the image is RGB (no alpha).
virtual bool isArgb () const =0
Pure virtual method for returning true if the image is RGBA.
Static Public Member Functions
static ImageImporter * fromFileName (FileName inputName)
A static (factory) method for constructing an ImageImporter instance from an input filename.
Protected Types
typedef int(ImageImporter::* GetChannelMethod) (int pixel) const
Friendly alias for a method used to get a particular color channel.
Protected Member Functions
Cube * createOutput (FileName outputName, CubeAttributeOutput &att)
Create the output cube from the given filename and attributes.
void setDefaultBands ()
Set the number of bands to be created for the output cube based on the number of color channels in the input image.
double testSpecial (double pixel) const
Tests a pixel against the Null, HRS, and LRS ranges defined by the importer's handler.
virtual GetChannelMethod getBandChannel (int band) const
Retrieve the method responsible for fetching the color channel from the input image corresponding to the current band out of output being filled.
virtual int convertRgbToGray (int pixel) const
Convert the current pixel, taken from an RGB/A image, and blend its RGB components into a single grayscale DN.
virtual void updateRawBuffer (int line, int band) const =0
Pure virtual method that updates the buffer used to store chunks of the input data at a time.
virtual int getPixel (int s, int l) const =0
Pure virtual method that returns a representation of a pixel for the input format that can then be broken down into specific gray or RGB/A components.
virtual int getGray (int pixel) const =0
Pure virtual method for retrieving the gray component of the given pixel.
virtual int getRed (int pixel) const =0
Pure virtual method for retrieving the red component of the given pixel.
virtual int getGreen (int pixel) const =0
Pure virtual method for retrieving the green component of the given pixel.
virtual int getBlue (int pixel) const =0
Pure virtual method for retrieving the blue component of the given pixel.
virtual int getAlpha (int pixel) const =0
Pure virtual method for retrieving the alpha component of the given pixel.
Detailed Description
Imports images with standard formats into Isis as cubes.
Abstract base class for a series of image importers. Each importer handles a specialized suite of standard image formats, and can be used as a black-box with the import() method, or for finer control, the importer can act as a functor in a ProcessByLine routine.
Author
2012-03-16 Travis Addair
Member Typedef Documentation
GetChannelMethod
typedef int(ImageImporter::* Isis::ImageImporter::GetChannelMethod) (int pixel) const protected
Friendly alias for a method used to get a particular color channel.
Constructor & Destructor Documentation
ImageImporter()
Isis::ImageImporter::ImageImporter (FileName inputName)
Construct the importer.
Parameters
inputName The name of the input image
~ImageImporter()
Isis::ImageImporter::~ImageImporter () virtual
Destruct the importer.
Also deletes the output cube handle.
Member Function Documentation
bands()
int Isis::ImageImporter::bands () const
The band dimension (depth) of the output image.
Returns
The band dimension
Referenced by createOutput(), getBandChannel(), import(), and Isis::JP2Importer::JP2Importer().
convertProjection()
PvlGroup Isis::ImageImporter::convertProjection () const virtual
Pure virtual method for converting projection information in the file being imported to an ISIS Mapping group.
Returns
An ISIS Mapping group
Reimplemented in Isis::TiffImporter.
Referenced by import().
convertRgbToGray()
int Isis::ImageImporter::convertRgbToGray (int pixel) const protected virtual
Convert the current pixel, taken from an RGB/A image, and blend its RGB components into a single grayscale DN.
The three color components are weighted by the following formula:
gray = (red * 11 + green * 16 + blue * 5) / 32
This formula was taken from the Qt documentation on converting an RGB value to grayscale: http://qt-project.org/doc/qt-4.8/qcolor.html#qGray-2
Parameters
pixel The pixel value to be broken up into RGB components and converted to grayscale
Returns
The grayscale DN value
References getBlue(), getGreen(), and getRed().
Referenced by Isis::JP2Importer::getGray(), and Isis::TiffImporter::getGray().
createOutput()
Cube * Isis::ImageImporter::createOutput (FileName outputName, CubeAttributeOutput & att) protected
Create the output cube from the given filename and attributes.
Set its dimensions based on those encapsulated by the importer.
Parameters
outputName The filename of the output cube
att The attributes for writing the output cube
Returns
The newly created cube handle devoid of any data
References bands(), Isis::Cube::create(), Isis::FileName::expanded(), lines(), samples(), and Isis::Cube::setDimensions().
Referenced by import().
filename()
FileName Isis::ImageImporter::filename () const
The filename of the input image this instance was constructed with.
Returns
A copy of the input filename
Referenced by Isis::JP2Importer::JP2Importer().
fromFileName()
ImageImporter * Isis::ImageImporter::fromFileName (FileName inputName) static
A static (factory) method for constructing an ImageImporter instance from an input filename.
The specific subclass of the returned instance is determined from the interpreted image format of the input image. Such tests are done by reading a minimal amount of the input data necessary to determine the format. It is the caller's responsibility to delete the importer instance when they are finished with it. Note that deleting the importer will also delete the cube handle returned by the import() method.
Parameters
inputName The filename of the input image to be imported
Returns
A pointer to the instantiated importer owned by the caller
References _FILEINFO_, Isis::FileName::expanded(), Isis::JP2Decoder::IsJP2(), and Isis::IException::Programmer.
getAlpha()
virtual int Isis::ImageImporter::getAlpha (int pixel) const protected pure virtual
Pure virtual method for retrieving the alpha component of the given pixel.
Parameters
pixel Representation of a pixel for the input format
Returns
The alpha component
Implemented in Isis::TiffImporter, Isis::QtImporter, and Isis::JP2Importer.
Referenced by getBandChannel().
getBandChannel()
ImageImporter::GetChannelMethod Isis::ImageImporter::getBandChannel (int band) const protected virtual
Retrieve the method responsible for fetching the color channel from the input image corresponding to the current band out of output being filled.
This will always be the getGray() method for single band output images. For RGB/A images, band 1 will be red, band 2 green, band 3 blue, and band 4 alpha.
Parameters
band The current band of the output image
Returns
The method that converts input pixels into the current band's color component
References _FILEINFO_, bands(), getAlpha(), getBlue(), getGray(), getGreen(), getRed(), and Isis::IException::Programmer.
Referenced by operator()().
getBlue()
virtual int Isis::ImageImporter::getBlue (int pixel) const protected pure virtual
Pure virtual method for retrieving the blue component of the given pixel.
Parameters
pixel Representation of a pixel for the input format
Returns
The blue component
Implemented in Isis::TiffImporter, Isis::QtImporter, and Isis::JP2Importer.
Referenced by convertRgbToGray(), and getBandChannel().
getGray()
virtual int Isis::ImageImporter::getGray (int pixel) const protected pure virtual
Pure virtual method for retrieving the gray component of the given pixel.
Parameters
pixel Representation of a pixel for the input format
Returns
The gray component
Implemented in Isis::TiffImporter, Isis::QtImporter, and Isis::JP2Importer.
Referenced by getBandChannel().
getGreen()
virtual int Isis::ImageImporter::getGreen (int pixel) const protected pure virtual
Pure virtual method for retrieving the green component of the given pixel.
Parameters
pixel Representation of a pixel for the input format
Returns
The green component
Implemented in Isis::TiffImporter, Isis::QtImporter, and Isis::JP2Importer.
Referenced by convertRgbToGray(), and getBandChannel().
getPixel()
virtual int Isis::ImageImporter::getPixel (int s, int l) const protected pure virtual
Pure virtual method that returns a representation of a pixel for the input format that can then be broken down into specific gray or RGB/A components.
Parameters
s The sample of the desired pixel
l The line of the desired pixel
Returns
The format-specific pixel representation
Implemented in Isis::TiffImporter, Isis::QtImporter, and Isis::JP2Importer.
Referenced by operator()().
getRed()
virtual int Isis::ImageImporter::getRed (int pixel) const protected pure virtual
Pure virtual method for retrieving the red component of the given pixel.
Parameters
pixel Representation of a pixel for the input format
Returns
The red component
Implemented in Isis::TiffImporter, Isis::QtImporter, and Isis::JP2Importer.
Referenced by convertRgbToGray(), and getBandChannel().
import() [1/2]
Cube * Isis::ImageImporter::import (FileName outputName)
Import the image with default output attributes.
Parameters
outputName The filename of the output cube
import() [2/2]
Cube * Isis::ImageImporter::import (FileName outputName, CubeAttributeOutput & att)
Import the input image this instance was constructed with into the given output Isis cube with the given output attributes.
This will do a black-box import using a ProcessByLine routine. The BandBin group will be updated in the output cube with the names of the color channels included. The output cube will be returned on completion of the import process so the caller can continue to modify the labels. The importer instance will retain ownership of this cube, such that the cube handle will be deallocated upon destruction of the importer.
Parameters
outputName The filename of the output cube
att The attributes for writing the output cube
Returns
A handle on the newly imported Isis cube owned by the importer
References _FILEINFO_, Isis::PvlObject::addGroup(), bands(), Isis::ProcessByBrick::BandsFirst, convertProjection(), createOutput(), Isis::ProcessByBrick::EndProcess(), Isis::PvlObject::findObject(), Isis::PvlContainer::keywords(), Isis::Cube::label(), Isis::ProcessByLine::ProcessCubeInPlace(), Isis::IException::Programmer, Isis::ProcessByLine::SetInputCube(), Isis::ProcessByBrick::SetProcessingDirection(), and Isis::Process::WriteHistory().
isArgb()
virtual bool Isis::ImageImporter::isArgb () const pure virtual
Pure virtual method for returning true if the image is RGBA.
Returns
True if the image is RGBA, false otherwise
Implemented in Isis::TiffImporter, Isis::QtImporter, and Isis::JP2Importer.
Referenced by setDefaultBands().
isGrayscale()
virtual bool Isis::ImageImporter::isGrayscale () const pure virtual
Pure virtual method for returning true if the image is grayscale.
Returns
True if the image is grayscale, false otherwise
Implemented in Isis::TiffImporter, Isis::QtImporter, and Isis::JP2Importer.
Referenced by setDefaultBands().
isRgb()
virtual bool Isis::ImageImporter::isRgb () const pure virtual
Pure virtual method for returning true if the image is RGB (no alpha).
Returns
True if the image is RGB, false otherwise
Implemented in Isis::TiffImporter, Isis::QtImporter, and Isis::JP2Importer.
lines()
int Isis::ImageImporter::lines () const
The line dimension (height) of the output image.
Returns
The line dimension
Referenced by createOutput(), Isis::TiffImporter::getPixel(), and Isis::TiffImporter::TiffImporter().
operator()()
void Isis::ImageImporter::operator() (Buffer & out) const
The method for processing the output cube in place, called for each line of the output image.
Enables the importer to be used as a functor in a custom ProcessByLine routine, bypassing the black-box import() method entirely. Care should be taken, however, to observe the requirements placed on the structure of such a processing routine by this method. For example, the JP2Importer child requires that the processing proceed in the direction of bands before lines, because its input data is structured in a BIL (band interlaced by line) format.
Parameters
out A reference to a line of output data to be written to
References Isis::Buffer::Band(), getBandChannel(), getPixel(), Isis::Buffer::Line(), Isis::Buffer::SampleDimension(), testSpecial(), and updateRawBuffer().
samples()
int Isis::ImageImporter::samples () const
The sample dimension (width) of the output image.
Returns
The sample dimension
Referenced by createOutput(), Isis::TiffImporter::getPixel(), Isis::JP2Importer::JP2Importer(), and Isis::TiffImporter::TiffImporter().
setBands()
void Isis::ImageImporter::setBands (int b)
Set the band dimension (depth) of the output image.
Because this importer only works on Grayscale, RGB, and RGBA images, possible values are 1, 3, and 4 for the respective color modes.
Parameters
b The new band dimension
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by Isis::JP2Importer::JP2Importer(), and setDefaultBands().
setDefaultBands()
void Isis::ImageImporter::setDefaultBands () protected
Set the number of bands to be created for the output cube based on the number of color channels in the input image.
References isArgb(), isGrayscale(), and setBands().
Referenced by Isis::QtImporter::QtImporter(), and Isis::TiffImporter::TiffImporter().
setHrsRange()
void Isis::ImageImporter::setHrsRange (double min, double max)
Set the range of DN values within which a pixel from the input image will be set to HRS in the output.
Parameters
min Any DN less than this value will not be set to HRS.
max Any DN greater than this value will not be set to HRS.
setLines()
void Isis::ImageImporter::setLines (int l)
Set the line dimension (height) of the output image.
Parameters
l The new line dimension
Referenced by Isis::JP2Importer::JP2Importer(), Isis::QtImporter::QtImporter(), and Isis::TiffImporter::TiffImporter().
setLrsRange()
void Isis::ImageImporter::setLrsRange (double min, double max)
Set the range of DN values within which a pixel from the input image will be set to LRS in the output.
Parameters
min Any DN less than this value will not be set to LRS.
max Any DN greater than this value will not be set to LRS.
setNullRange()
void Isis::ImageImporter::setNullRange (double min, double max)
Set the range of DN values within which a pixel from the input image will be set to Null in the output.
Parameters
min Any DN less than this value will not be set to Null.
max Any DN greater than this value will not be set to Null.
setSamples()
void Isis::ImageImporter::setSamples (int s)
Set the sample dimension (width) of the output image.
Parameters
s The new sample dimension
Referenced by Isis::JP2Importer::JP2Importer(), Isis::QtImporter::QtImporter(), and Isis::TiffImporter::TiffImporter().
testSpecial()
double Isis::ImageImporter::testSpecial (double pixel) const protected
Tests a pixel against the Null, HRS, and LRS ranges defined by the importer's handler.
Any pixel value falling within one of these ranges will be converted into the given type of special pixel. In case of overlapping ranges, these tests will be performed in the order mentioned at the start of this description. By default, these ranges are set such that all incoming pixels will retain their original values.
Parameters
pixel The DN value to be tested
Returns
The valid DN or special pixel if it fell within the special ranges
References Isis::HIGH_REPR_SAT8, Isis::LOW_REPR_SAT8, and Isis::NULL8.
Referenced by operator()().
updateRawBuffer()
virtual void Isis::ImageImporter::updateRawBuffer (int line, int band) const protected pure virtual
Pure virtual method that updates the buffer used to store chunks of the input data at a time.
Does nothing for classes that read the entire input image into memory.
Parameters
line Current line of the output buffer
band Current band of the output buffer
Implemented in Isis::TiffImporter, Isis::QtImporter, and Isis::JP2Importer.
Referenced by operator()().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ImageImporter/ImageImporter.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ImageImporter/ImageImporter.cpp