Isis Developer Reference: Isis::TreeViewHeader Class Reference
Isis::TreeViewHeader Class Reference
#include <TreeViewHeader.h>
Public Slots
void setActive (bool)
void handleFilterCountsChanged (int visibleTopLevelItemCount, int topLevelItemCount)
Signals
void activated ()
Public Member Functions
TreeViewHeader (TreeViewContent *someContent, QWidget *parent)
TreeViewHeader (const TreeViewHeader &other)
virtual ~TreeViewHeader ()
QSize minimumSizeHint () const
QString getText ()
void setText (QString text)
QSize sizeHint () const
TreeViewHeader & operator= (const TreeViewHeader &other)
Protected Member Functions
void mouseReleaseEvent (QMouseEvent *event)
void paintEvent (QPaintEvent *event)
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
TreeViewHeader() [1/2]
Isis::TreeViewHeader::TreeViewHeader (TreeViewContent * someContent, QWidget * parent) explicit
TreeViewHeader() [2/2]
Isis::TreeViewHeader::TreeViewHeader (const TreeViewHeader & other)
~TreeViewHeader()
Isis::TreeViewHeader::~TreeViewHeader () virtual
Member Function Documentation
activated
void Isis::TreeViewHeader::activated () signal
Referenced by mouseReleaseEvent().
getText()
QString Isis::TreeViewHeader::getText ()
Referenced by Isis::TreeView::getTitle().
handleFilterCountsChanged
void Isis::TreeViewHeader::handleFilterCountsChanged (int visibleTopLevelItemCount, int topLevelItemCount) slot
minimumSizeHint()
QSize Isis::TreeViewHeader::minimumSizeHint () const
Referenced by sizeHint().
mouseReleaseEvent()
void Isis::TreeViewHeader::mouseReleaseEvent (QMouseEvent * event) protected
References activated(), and setActive().
operator=()
TreeViewHeader & Isis::TreeViewHeader::operator= (const TreeViewHeader & other)
paintEvent()
void Isis::TreeViewHeader::paintEvent (QPaintEvent * event) protected
setActive
void Isis::TreeViewHeader::setActive (bool newActiveState) slot
Referenced by Isis::TreeView::activate(), Isis::TreeView::deactivate(), and mouseReleaseEvent().
setText()
void Isis::TreeViewHeader::setText (QString text)
Referenced by Isis::TreeView::setTitle().
sizeHint()
QSize Isis::TreeViewHeader::sizeHint () const inline
References minimumSizeHint().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/TreeViewHeader.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/TreeViewHeader.cpp