Isis Developer Reference: Isis::LineEquation Class Reference
Isis::LineEquation Class Reference
Utility
Utility class for creating and using cartesean line equations.
#include <LineEquation.h>
Public Member Functions
LineEquation ()
Constructors.
LineEquation (double x1, double y1, double x2, double y2)
Construct and fill LineEquation object.
~LineEquation ()
Destroys the LineEquation object.
void AddPoint (double x, double y)
Add a point to the object.
double Slope ()
Compute the slope of the line.
double Intercept ()
Compute the intercept of the line.
int Points ()
bool HaveSlope ()
bool HaveIntercept ()
bool Defined ()
Detailed Description
Utility class for creating and using cartesean line equations.
This class contains utility methods for creating and using cartesean line equations. If both points have the same value for the independent variable (vertical line) an error is thrown.
Author
2006-10-19 Debbie A. Cook
Constructor & Destructor Documentation
LineEquation() [1/2]
Isis::LineEquation::LineEquation ()
Constructors.
Construct an empty LineEquation object.
LineEquation() [2/2]
Isis::LineEquation::LineEquation (double x1, double y1, double x2, double y2)
Construct and fill LineEquation object.
Parameters
x1 Double First independent variable
y1 Double First dependent variable
x2 Double Second independent variable
y2 Double Second dependent variable
~LineEquation()
Isis::LineEquation::~LineEquation () inline
Destroys the LineEquation object.
Member Function Documentation
AddPoint()
void Isis::LineEquation::AddPoint (double x, double y)
Add a point to the object.
The object is considered filled once 2 points have been added (the line is defined).
Parameters
x Double Independent variable
y Double Dependent variable
References _FILEINFO_.
Defined()
bool Isis::LineEquation::Defined () inline
HaveIntercept()
bool Isis::LineEquation::HaveIntercept () inline
HaveSlope()
bool Isis::LineEquation::HaveSlope () inline
Intercept()
double Isis::LineEquation::Intercept ()
Compute the intercept of the line.
Returns
double The y-intercept of the line if it exists
References _FILEINFO_.
Referenced by Isis::SpicePosition::SetPolynomial(), and Isis::SpiceRotation::SetPolynomial().
Points()
int Isis::LineEquation::Points () inline
Slope()
double Isis::LineEquation::Slope ()
Compute the slope of the line.
Returns
double The slope of the line if it exists
References _FILEINFO_.
Referenced by Isis::SpicePosition::SetPolynomial(), and Isis::SpiceRotation::SetPolynomial().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/LineEquation/LineEquation.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/LineEquation/LineEquation.cpp