Isis Developer Reference: Isis::RingPlaneProjection Class Reference
Isis::RingPlaneProjection Class Reference abstract
Map Projection
Base class for Map Projections of plane shapes.
#include <RingPlaneProjection.h>
Public Types
enum RingLongitudeDirection { Clockwise , CounterClockwise }
This enum defines the types of ring longitude directions supported in this class.
enum ProjectionType { Triaxial , RingPlane }
This enum defines the subclasses of Projection supported in Isis.
Public Member Functions
RingPlaneProjection (Pvl &label)
Constructs an empty RingPlaneProjection object.
virtual ~RingPlaneProjection ()
Destroys the Projection object.
virtual bool operator== (const Projection &proj)
This method determines whether two map projection objects are equal by comparing the ring longitude direction, resolution, and projection name.
double LocalRadius () const
This returns a local radius.
virtual QString Name () const =0
This method returns the name of the map projection.
virtual QString Version () const =0
This method returns the Version of the map projection.
virtual double TrueScaleRingRadius () const
This method returns the radius of true scale.
bool IsClockwise () const
This indicates if the longitude direction type is positive west (as opposed to postive east).
bool IsCounterClockwise () const
This indicates if the longitude direction type is positive east (as opposed to postive west).
std::string RingLongitudeDirectionString () const
This method returns the ring longitude direction as a string.
bool Has180Domain () const
This indicates if the longitude domain is -180 to 180 (as opposed to 0 to 360).
bool Has360Domain () const
This indicates if the ring longitude domain is 0 to 360 (as opposed to -180 to 180).
std::string RingLongitudeDomainString () const
This method returns the ring longitude domain as a string.
double MinimumRingRadius () const
This returns the minimum radius of the area of interest.
double MaximumRingRadius () const
This returns the maximum radius of the area of interest.
double MinimumRingLongitude () const
This returns the minimum ring longitude of the area of interest.
double MaximumRingLongitude () const
This returns the maximum ring longitude of the area of interest.
virtual bool SetGround (const double ringRadius, const double ringLongitude)
This method is used to set the ring radius/longitude (assumed to be of the correct LatitudeType, LongitudeDirection, and LongitudeDomain.
virtual bool SetCoordinate (const double x, const double y)
This method is used to set the projection x/y.
double RingRadius () const
This returns a radius.
double RingLongitude () const
This returns a ring longitude with correct ring longitude direction and domain as specified in the label object.
bool SetUniversalGround (const double ringRadius, const double ringLongitude)
This method is used to set the ring radius/longitude which must be PositiveEast/Domain360 (ring longitude).
double UniversalRingRadius ()
This returns a universal radius, which is just the radius in meters.
double UniversalRingLongitude ()
This returns a universal ring longitude (clockwise in 0 to 360 domain).
double Scale () const
This method returns the scale for mapping world coordinates into projection coordinates.
virtual bool XYRange (double &minX, double &maxX, double &minY, double &maxY)
This method is used to determine the x/y range which completely covers the area of interest specified by the ring radius/longitude range.
virtual PvlGroup Mapping ()
This method is used to find the XY range for oblique aspect projections (non-polar projections) by "walking" around each of the min/max ring rad/lon.
virtual PvlGroup MappingRingRadii ()
This function returns the ring radius keywords that this projection uses.
virtual PvlGroup MappingRingLongitudes ()
This function returns the ring longitude keywords that this projection uses.
bool operator!= (const Projection &proj)
This method determines whether two map projection objects are not equal.
void setProjectionType (const ProjectionType ptype)
Sets the projection subclass type.
ProjectionType projectionType () const
Returns an enum value for the projection type.
bool IsSky () const
Returns true if projection is sky and false if it is land.
virtual bool IsEquatorialCylindrical ()
This method returns true if the projection is equatorial cylindrical.
virtual bool HasGroundRange () const
This indicates if the longitude direction type is positive west (as opposed to postive east).
double Rotation () const
Returns the value of the Rotation keyword from the mapping group.
void SetWorldMapper (WorldMapper *mapper)
If desired the programmer can use this method to set a world mapper to be used in the SetWorld, WorldX, and WorldY methods.
bool IsGood () const
This indicates if the last invocation of SetGround, SetCoordinate, SetUniversalGround, or SetWorld was with successful or not.
double XCoord () const
This returns the projection X provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
double YCoord () const
This returns the projection Y provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
virtual bool SetUnboundUniversalGround (const double coord1, const double coord2)
This method is used to set the lat/lon or radius/azimuth (i.e.
virtual bool SetWorld (const double x, const double y)
This method is used to set a world coordinate.
virtual double WorldX () const
This returns the world X coordinate provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
virtual double WorldY () const
This returns the world Y coordinate provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
double ToWorldX (const double projectionX) const
This method converts a projection x value to a world x value.
double ToWorldY (const double projectionY) const
This method converts a projection y value to a world y value.
double ToProjectionX (const double worldX) const
This method converts a world x value to a projection x value.
double ToProjectionY (const double worldY) const
This method converts a world y value to a projection y value.
double Resolution () const
This method returns the resolution for mapping world coordinates into projection coordinates.
void SetUpperLeftCorner (const Displacement &x, const Displacement &y)
This method searches for extreme (min/max/discontinuity) coordinate values along the constBorder line between minBorder and maxBorder (that is, across latitudes/longitudes).
Static Public Member Functions
static double ToClockwise (const double ringLongitude, const int domain)
This method converts an ring longitude into the clockwise direction.
static double ToCounterClockwise (const double ringLongitude, const int domain)
This method converts an ring longitude into the counterclockwise direction.
static double To180Domain (const double lon)
This method converts a ring longitude into the -180 to 180 domain.
static double To360Domain (const double lon)
This method converts an ring longitude into the 0 to 360 domain.
static double ToHours (double angle)
Converts the given angle (in degrees) to hours by using the ratio 15 degrees per hour.
static QString ToDMS (double angle)
Converts the given angle (in degrees) to degrees, minutes, seconds.
static QString ToHMS (double angle)
Converts the given angle (in degrees) to hours, minutes, seconds.
Protected Member Functions
void XYRangeCheck (const double ringRadius, const double ringLongitude)
This convience function is established to assist in the development of the XYRange virtual method.
void SetXY (double x, double y)
This protected method is a helper for derived classes.
void SetComputedXY (double x, double y)
This protected method is a helper for derived classes.
double GetX () const
Calculates the unrotated form of current x value.
double GetY () const
Calculates the unrotated form of the current y value.
double PixelResolution () const
Returns the pixel resolution value from the PVL mapping group in meters/pixel.
Protected Attributes
double m_ringRadius
This contain a ring radius value in m.
double m_ringLongitude
This contain a ring longitude value.
RingLongitudeDirection m_ringLongitudeDirection
An enumerated type indicating the LongitudeDirection read from the labels.
int m_ringLongitudeDomain
This integer is either 180 or 360 and is read from the labels.
double m_minimumRingRadius
Contains the minimum ring radius for the entire ground range.
double m_maximumRingRadius
Contains the maximum ring radius for the entire ground range.
double m_minimumRingLongitude
Contains the minimum longitude for the entire ground range.
double m_maximumRingLongitude
Contains the maximum longitude for the entire ground range.
WorldMapper * m_mapper
This points to a mapper passed into the SetWorldMapper method.
bool m_good
Indicates if the contents of m_x, m_y, m_latitude, and m_longitude are valid.
bool m_sky
Indicates whether projection is sky or land.
bool m_groundRangeGood
Indicates if the ground range (min/max lat/lons) were read from the labels.
double m_minimumX
The data elements m_minimumX, m_minimumY, m_maximumX, and m_maximumY are convience data elements when you write the XYRange virtual function.
double m_maximumX
See minimumX description.
double m_minimumY
See minimumX description.
double m_maximumY
See minimumX description.
PvlGroup m_mappingGrp
Mapping group that created this projection.
Detailed Description
Base class for Map Projections of plane shapes.
This is a virtual base class for map projections of plane shape targets. It must be used to create specific map projection classes such as PlaneCylindrical, PlanePolar, etc. The foundation of this class is the ability to convert plane ground coordinates (ring radius and ring longitude) into projection coordinates (x and y) and vice versa. Options exist to allow conversion to and from programmer specified world coordinates. The world coordinates can be cube pixels, paper units in millimeters, or any other unit the program may need. Generally, you should never directly instantiate this class.
Here is an example of how to use RingPlaneProjection
Pvl lab;
lab.Read("projection.map");
Projection *p = ProjectionFactory::Create(lab);
If you would like to see Projection being used in implementation, see mappos.cpp
Author
2003-01-29 Jeff Anderson
Member Enumeration Documentation
ProjectionType
enum Isis::Projection::ProjectionType inherited
This enum defines the subclasses of Projection supported in Isis.
Enumerator
Triaxial
These projections are used to map triaxial and irregular-shaped bodies.
RingPlane
These projections are used to map ring planes.
RingLongitudeDirection
enum Isis::RingPlaneProjection::RingLongitudeDirection
This enum defines the types of ring longitude directions supported in this class.
Enumerator
Clockwise
Ring longitude values increase in the clockwise direction.
CounterClockwise
Ring longitude values increase in the counterclockwise direction.
Constructor & Destructor Documentation
RingPlaneProjection()
Isis::RingPlaneProjection::RingPlaneProjection (Pvl & label)
Constructs an empty RingPlaneProjection object.
Parameters
label A PVL object containing map projection labels. These labels are fully described in the Isis Map Projection Users Guide. A brief example follows:
  Group = Mapping
    RingLongitudeDirection = PositiveEast
    RingLongitudeDomain = 360
    MinimumRingRadius = 10.8920539924144
    MaximumRingRadius = 34.7603960060206
    MinimumRingLongitude = 219.72432466275
    MaximumRingLongitude = 236.186050244411
    PixelResolution = 1387.31209461362
    ProjectionName = Planar
    CenterRingLongitude = 220.0
  EndGroup
End
Exceptions
IException::Unknown - "Projection failed. Invalid value for keyword [RingLongitudeDirection] must be [Clockwise or CounterClockwise]"
IException::Unknown - "Projection failed. Invalid value for keyword [RingLongitudeDomain] must be [180 or 360]"
IException::Unknown - "Projection failed. [MinimumRingRadius] is not valid"
IException::Unknown - "Projection failed. [MaximumRingRadius] is not valid"
IException::Unknown - "Projection failed. [MinimumRingRadius,MaximumRingRadius] are not properly ordered"
IException::Unknown - "Projection failed. [MinimumRingLongitude,MaximumRingLongitude] are not properly ordered"
IException::Unknown - "Projection failed. Invalid label group [Mapping]"
References _FILEINFO_, Clockwise, CounterClockwise, Isis::PvlContainer::hasKeyword(), Isis::Projection::m_groundRangeGood, Isis::Projection::m_mappingGrp, m_maximumRingLongitude, m_maximumRingRadius, m_minimumRingLongitude, m_minimumRingRadius, m_ringLongitude, m_ringLongitudeDirection, m_ringLongitudeDomain, m_ringRadius, Isis::Null, Isis::Projection::RingPlane, Isis::Projection::setProjectionType(), and Isis::IException::Unknown.
~RingPlaneProjection()
Isis::RingPlaneProjection::~RingPlaneProjection () virtual
Destroys the Projection object.
Member Function Documentation
GetX()
double Isis::Projection::GetX () const protected inherited
Calculates the unrotated form of current x value.
Returns
double The unrotated x-value.
References Isis::PI.
Referenced by Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Mollweide::SetCoordinate(), Isis::ObliqueCylindrical::SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::RingCylindrical::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), and Isis::TransverseMercator::SetCoordinate().
GetY()
double Isis::Projection::GetY () const protected inherited
Calculates the unrotated form of the current y value.
Returns
double The unrotated y-value.
References Isis::PI.
Referenced by Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::ObliqueCylindrical::SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::RingCylindrical::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), and Isis::TransverseMercator::SetCoordinate().
Has180Domain()
bool Isis::RingPlaneProjection::Has180Domain () const
This indicates if the longitude domain is -180 to 180 (as opposed to 0 to 360).
The ring longitude domain was obtained from the label during object construction.
Returns
bool
References m_ringLongitudeDomain.
Referenced by operator==().
Has360Domain()
bool Isis::RingPlaneProjection::Has360Domain () const
This indicates if the ring longitude domain is 0 to 360 (as opposed to -180 to 180).
The ring longitude domain was obtained from the label during object construction.
Returns
bool
References m_ringLongitudeDomain.
HasGroundRange()
bool Isis::Projection::HasGroundRange () const virtual inherited
This indicates if the longitude direction type is positive west (as opposed to postive east).
The longitude type was obtained from the label during object construction.
Returns
bool This indicates if the longitude direction type is positive east (as opposed to postive west). The longitude type was obtained from the label during object construction.
bool This method returns the longitude direction as a string. It will return either PositiveEast or PositiveWest.
string The longitude direction, "PositiveEast" or "PositiveWest". This indicates if the longitude domain is -180 to 180 (as opposed to 0 to 360). The longitude domain was obtained from the label during object construction.
bool This indicates if the longitude domain is 0 to 360 (as opposed to -180 to 180). The longitude domain was obtained from the label during object construction.
bool This method converts a longitude into the -180 to 180 domain. It will leave the longitude unchanged if it is already in the domain.
Parameters
lon Longitude to convert into the -180 to 180 domain.
Exceptions
IException::Unknown - "The given longitude is invalid."
Returns
double The longitude, converted to 180 domain. This method converts a longitude into the 0 to 360 domain. It will leave the longitude unchanged if it is already in the domain.
Parameters
lon Longitude to convert into the 0 to 360 domain.
Returns
double The longitude, converted to 360 domain. This method returns the longitude domain as a string. It will return either 180 or 360.
string The longitude domain, "180" or "360". This indicates that the labels contained minimum and maximum ground coordinatess (e.g., a ground range coverage). If the projection has ground range coverage then the MinimumLatitude, MaximumLatitude, MinimumLongitude, and MaximumLongitude methods or comparable methods for other projection types can be used. The ground range coverage essentially defines the area of user interest.
bool
References Isis::Projection::m_groundRangeGood.
Referenced by Isis::ProjectionFactory::CreateForCube(), Mapping(), Isis::TProjection::MappingLatitudes(), Isis::TProjection::MappingLongitudes(), Isis::Planar::MappingRingLongitudes(), Isis::RingCylindrical::MappingRingLongitudes(), MappingRingLongitudes(), Isis::Planar::MappingRingRadii(), Isis::RingCylindrical::MappingRingRadii(), MappingRingRadii(), Isis::ProjectionFactory::RingsCreateForCube(), and Isis::TProjection::xyRangeOblique().
IsClockwise()
bool Isis::RingPlaneProjection::IsClockwise () const
This indicates if the longitude direction type is positive west (as opposed to postive east).
The longitude type was obtained from the label during object construction.
Returns
bool
References Clockwise, and m_ringLongitudeDirection.
Referenced by operator==().
IsCounterClockwise()
bool Isis::RingPlaneProjection::IsCounterClockwise () const
This indicates if the longitude direction type is positive east (as opposed to postive west).
The longitude type was obtained from the label during object construction.
Returns
bool
References CounterClockwise, and m_ringLongitudeDirection.
IsEquatorialCylindrical()
bool Isis::Projection::IsEquatorialCylindrical () virtual inherited
This method returns true if the projection is equatorial cylindrical.
In other words, if the projection is cylindrical and an image projected at 0 is the same as an image projected at 360.
Returns
bool true if the projection is equatorial cylindrical
Reimplemented in Isis::TProjection, Isis::SimpleCylindrical, Isis::RingCylindrical, Isis::Mercator, and Isis::Equirectangular.
Referenced by Isis::ShapeModelFactory::create(), and Isis::ProcessMapMosaic::StartProcess().
IsGood()
bool Isis::Projection::IsGood () const inherited
This indicates if the last invocation of SetGround, SetCoordinate, SetUniversalGround, or SetWorld was with successful or not.
If there was success then the Latitude, Longitude, XCoord, YCoord, UniversalLatitude, UniversalLongitude, WorldX, and WorldY methods can be utilized.
Returns
bool True if the last call to SetGround, SetCoordinate, SetUniversalGround, or SetWorld was successful.
References Isis::Projection::m_good.
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::Chip::Load(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::SubArea::UpdateLabel(), Isis::TProjection::XYRangeCheck(), and XYRangeCheck().
IsSky()
bool Isis::Projection::IsSky () const inherited
Returns true if projection is sky and false if it is land.
Returns
bool
References Isis::Projection::m_sky.
Referenced by Isis::Camera::SetImage(), and Isis::Camera::SetRightAscensionDeclination().
LocalRadius()
double Isis::RingPlaneProjection::LocalRadius () const virtual
This returns a local radius.
The method can only be used if SetGround, SetCoordinate, SetUniversalGround, or SetWorld return with success. Success can also be checked using the IsGood method.
Returns
double
Implements Isis::Projection.
References m_ringRadius.
Mapping()
PvlGroup Isis::RingPlaneProjection::Mapping () virtual
This method is used to find the XY range for oblique aspect projections (non-polar projections) by "walking" around each of the min/max ring rad/lon.
Parameters
minX Minimum x projection coordinate which covers the ring radius/longitude range specified in the labels.
maxX Maximum x projection coordinate which covers the ring radius/longitude range specified in the labels.
minY Minimum y projection coordinate which covers the ring radius/longitude range specified in the labels.
maxY Maximum y projection coordinate which covers the ring radius/longitude range specified in the labels.
Returns
bool Indicates whether the method was successful.
See also
XYRange()
Author
Stephen Lambright This method searches for extreme (min/max/discontinuity) coordinate values along the constBorder line between minBorder and maxBorder (that is, across ring radii/longitudes). This method locates the extrema by utilizing the findExtreme() method until the coordinate values converge. Then, extremeVal parameter is updated with this value before returning.
Discontinuities are stored in m_specialLatCases and m_specialLonCases so they may be checked again later, which creates significantly more accuracy in some cases.
Parameters
minBorder Minimum latitude or longitude to search between.
maxBorder Maximum latitude or longitude to search between.
extremeVal The resulting global coordinate value (min or max value for x or y, depending on findMin and searchX) on the constBorder.
constBorder The latitude or longitude that remains constant. The method will step along this border.
searchX Indicates whether the method is searching for a min or max x-coordinate. If false the method searches for min or max y-coordinate.
searchLongitude Indicates whether the method will search along a longitude. If true, constBorder is longitude and all other borders are latitudes. If false, the method searches a latitude (constBorder is a lat, other borders lons).
findMin Indicates whether the method is looking for a minimum coordinate value. If false, the method is looking for a maximum value.
Author
Steven Lambright Searches for extreme (min/max/discontinuity) coordinate values across latitudes/longitudes.
This method looks for these extrema along the constBorder between minBorder and maxBorder by stepping along constBorder (10 times) from the minBorder and maxBorder. Then, the range of this extreme value is recorded in minBorder and maxBorder and the coordinate values corresponding to these new borders are stored in minBorderX, minBorderY, maxBorderX and maxBorderY.
This function should be used by calling it repeatedly until minBorderX and minBorderY do not equal maxBorderX and maxBorderY, respectively. Discontinuities will cause the minBorderX, minBorderY, maxBorderX and maxBorderY to never converge. If minBorderX never comes close to maxBorderX or minBorderY never comes close to maxBorderY, then between minBorder and maxBorder is the value of the most extreme value. In this case, either the smaller or larger of the x or y values found will be correct, depending on the values of findMin and searchX.
Parameters
minBorder Minimum latitude or longitude to search between. This value gets updated to a more precise range.
maxBorder Maximum latitude or longitude to search between. This value gets updated to a more precise range.
minBorderX The x-value corresponding to the lower resultant minBorder and the constBorder, which is more accurate when nearly equal to maxBorderX.
minBorderY The y-value corresponding to the lower resultant minBorder and the constBorder, which is more accurate when nearly equal to maxBorderY.
maxBorderX The x-value corresponding to the higher resultant maxBorder and the constBorder, which is more accurate when nearly equal to minBorderX.
maxBorderY The y-value corresponding to the higher resultant maxBorder and the constBorder, which is more accurate when nearly equal to minBorderY.
constBorder The latitude or longitude that remains constant. The method will step along this border.
searchX Indicates whether the method is searching for a min or max x-coordinate. If false the method searches for min or max y-coordinate.
searchLongitude Indicates whether the method will search along a longitude. If true, constBorder is longitude and all other borders are latitudes. If false, the method searches a latitude (constBorder is a lat, other borders lons).
findMin Indicates whether the method is looking for a minimum coordinate value. If false, the method is looking for a maximum value.
Author
Stephen Lambright This function sets the ground for the given border values. It calls the SetGround(lat, lon) method with the appropriate lat/lon values, depending on whether variableIsLat is true.
This method is used by doSearch and findExtreme in order to set the ground correctly each time.
Parameters
variableBorder The latitude or longitude that is variable in the search methods.
constBorder The latitude or longitude that is constant in the search methods.
variableIsLat Indicates whether variableBorder is the latittude value and constBorder is the longitude value. If false, variableBorder is the longitude value and constBorder is the latitude value.
Author
Stephen Lambright This function returns the keywords that this projection uses.
Returns
PvlGroup The keywords that this projection uses
Implements Isis::Projection.
Reimplemented in Isis::RingCylindrical, and Isis::Planar.
References Isis::Projection::HasGroundRange(), Isis::PvlContainer::hasKeyword(), and Isis::Projection::m_mappingGrp.
Referenced by Isis::Planar::Mapping(), and Isis::RingCylindrical::Mapping().
MappingRingLongitudes()
PvlGroup Isis::RingPlaneProjection::MappingRingLongitudes () virtual
This function returns the ring longitude keywords that this projection uses.
Returns
PvlGroup The ring longitude keywords that this projection uses
Reimplemented in Isis::RingCylindrical, and Isis::Planar.
References Isis::Projection::HasGroundRange(), and Isis::Projection::m_mappingGrp.
Referenced by Isis::Planar::MappingRingLongitudes(), and Isis::RingCylindrical::MappingRingLongitudes().
MappingRingRadii()
PvlGroup Isis::RingPlaneProjection::MappingRingRadii () virtual
This function returns the ring radius keywords that this projection uses.
Returns
PvlGroup The ring radius keywords that this projection uses
Reimplemented in Isis::RingCylindrical, and Isis::Planar.
References Isis::Projection::HasGroundRange(), and Isis::Projection::m_mappingGrp.
Referenced by Isis::Planar::MappingRingRadii(), and Isis::RingCylindrical::MappingRingRadii().
MaximumRingLongitude()
double Isis::RingPlaneProjection::MaximumRingLongitude () const
This returns the maximum ring longitude of the area of interest.
The value was obtained from the labels during object construction. This method can only be used if HasGroundRange returns a true.
Returns
double
References m_maximumRingLongitude.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube().
MaximumRingRadius()
double Isis::RingPlaneProjection::MaximumRingRadius () const
This returns the maximum radius of the area of interest.
The value was obtained from the labels during object construction. This method can only be used if HasGroundRange returns a true.
Returns
double
References m_maximumRingRadius.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube().
MinimumRingLongitude()
double Isis::RingPlaneProjection::MinimumRingLongitude () const
This returns the minimum ring longitude of the area of interest.
The value was obtained from the labels during object construction. This method can only be used if HasGroundRange returns a true.
Returns
double
References m_minimumRingLongitude.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube().
MinimumRingRadius()
double Isis::RingPlaneProjection::MinimumRingRadius () const
This returns the minimum radius of the area of interest.
The value was obtained from the labels during object construction. This method can only be used if HasGroundRange returns a true.
Returns
double
References m_minimumRingRadius.
Referenced by Isis::ProcessMapMosaic::RingsSetOutputCube().
Name()
virtual QString Isis::RingPlaneProjection::Name () const pure virtual
This method returns the name of the map projection.
It is a pure virtual method (requires all subclasses to override).
Returns
string The name of the map projection.
Implements Isis::Projection.
Implemented in Isis::RingCylindrical, and Isis::Planar.
operator!=()
bool Isis::Projection::operator!= (const Projection & proj) inherited
This method determines whether two map projection objects are not equal.
True is returned if they have at least some differences in the radii, latitude type, longitude direction, resolution, or projection name.
Parameters
proj A reference to a Projection object to which this Projection will be compared.
Returns
bool Indicates whether the Projection objects are not equivalent.
operator==()
bool Isis::RingPlaneProjection::operator== (const Projection & proj) virtual
This method determines whether two map projection objects are equal by comparing the ring longitude direction, resolution, and projection name.
Parameters
proj A reference to a Projection object to which this Projection will be compared.
Returns
bool Indicates whether the Projection objects are equivalent.
Reimplemented from Isis::Projection.
Reimplemented in Isis::RingCylindrical, and Isis::Planar.
References Has180Domain(), and IsClockwise().
PixelResolution()
double Isis::Projection::PixelResolution () const protected inherited
Returns the pixel resolution value from the PVL mapping group in meters/pixel.
Returns
double pixel resolution in meters/pixel
Referenced by Isis::Planar::XYRange(), and Isis::RingCylindrical::XYRange().
projectionType()
Projection::ProjectionType Isis::Projection::projectionType () const inherited
Returns an enum value for the projection type.
Returns
projection subclass type
Referenced by Isis::MosaicGridTool::autoGrid(), Isis::MosaicGridTool::fromPvl(), Isis::MosaicFindTool::getUserGroundPoint(), Isis::GridGraphicsItem::GridGraphicsItem(), Isis::UniversalGroundMap::GroundRange(), Isis::MosaicControlNetTool::mouseButtonRelease(), Isis::MosaicFindTool::mouseButtonRelease(), Isis::MosaicGridTool::setLatExtents(), Isis::MosaicGridTool::setLonExtents(), Isis::Projection::SetUnboundUniversalGround(), Isis::Projection::SetUniversalGround(), Isis::UniversalGroundMap::UniversalLatitude(), Isis::UniversalGroundMap::UniversalLongitude(), Isis::MosaicTrackTool::updateLabels(), and Isis::MosaicAreaTool::userChangedBox().
Resolution()
double Isis::Projection::Resolution () const inherited
This method returns the resolution for mapping world coordinates into projection coordinates.
For example, if the world coordinate system is an image then this routine returns the number of meters per pixel. Likewise, if the world coordinate system is a piece of paper, it might return the number of meters per inch of paper. If the SetWorldMapper method is not invoked then this method returns 1.0
Returns
double The resolution, in appropriate units.
References Isis::Projection::m_mapper, and Isis::WorldMapper::Resolution().
Referenced by Isis::ProcessExport::CreateWorldFile(), Isis::Projection::operator==(), and Isis::UniversalGroundMap::Resolution().
RingLongitude()
double Isis::RingPlaneProjection::RingLongitude () const
This returns a ring longitude with correct ring longitude direction and domain as specified in the label object.
The method can only be used if SetGround, SetCoordinate, SetUniversalGround, or SetWorld return with success. Success can also be checked using the IsGood method.
Returns
double
References m_ringLongitude.
Referenced by Isis::UniversalGroundMap::UniversalLongitude().
RingLongitudeDirectionString()
string Isis::RingPlaneProjection::RingLongitudeDirectionString () const
This method returns the ring longitude direction as a string.
It will return either Clockwise or CounterClockwise.
Returns
string The ring longitude direction, "Clockwise" or "CounterClockwise".
References Clockwise, and m_ringLongitudeDirection.
RingLongitudeDomainString()
string Isis::RingPlaneProjection::RingLongitudeDomainString () const
This method returns the ring longitude domain as a string.
It will return either 180 or 360.
Returns
string The ring longitude domain, "180" or "360".
References m_ringLongitudeDomain.
RingRadius()
double Isis::RingPlaneProjection::RingRadius () const
This returns a radius.
The method can only be used if SetGround, SetCoordinate, SetUniversalGround, or SetWorld return with success. Success can also be checked using the IsGood method.
Returns
double
References m_ringRadius.
Referenced by Isis::UniversalGroundMap::UniversalLatitude().
Rotation()
double Isis::Projection::Rotation () const inherited
Returns the value of the Rotation keyword from the mapping group.
Returns
double The rotation of the map.
Scale()
double Isis::RingPlaneProjection::Scale () const virtual
This method returns the scale for mapping world coordinates into projection coordinates.
For example, if the world coordinate system is an image then this routine returns the number of pixels per degree. Likewise, if the world coordinate system is a piece of paper, it might return the number of inches of paper per degree. If the SetWorldMapper method is not invoked then this method returns 1.0
Returns
double The scale for mapping.
Implements Isis::Projection.
References Isis::DEG2RAD, Isis::Projection::m_mapper, Isis::WorldMapper::Resolution(), and TrueScaleRingRadius().
SetComputedXY()
void Isis::Projection::SetComputedXY (double x, double y) protected inherited
This protected method is a helper for derived classes.
It takes unrotated x and y values, rotates them using the rotation angle data member, and stores the results in the current x and y data members.
Parameters
x The unrotated x coordinate.
y The unrotated y coordinate.
References Isis::Projection::m_good, Isis::Null, and Isis::PI.
Referenced by Isis::Equirectangular::SetGround(), Isis::LambertConformal::SetGround(), Isis::LunarAzimuthalEqualArea::SetGround(), Isis::Mercator::SetGround(), Isis::Mollweide::SetGround(), Isis::ObliqueCylindrical::SetGround(), Isis::Orthographic::SetGround(), Isis::PointPerspective::SetGround(), Isis::PolarStereographic::SetGround(), Isis::Robinson::SetGround(), Isis::SimpleCylindrical::SetGround(), Isis::Sinusoidal::SetGround(), Isis::TProjection::SetGround(), Isis::TransverseMercator::SetGround(), Isis::Planar::SetGround(), Isis::RingCylindrical::SetGround(), and SetGround().
SetCoordinate()
bool Isis::RingPlaneProjection::SetCoordinate (const double x, const double y) virtual
This method is used to set the projection x/y.
The Set forces an attempted calculation of the corresponding ring radius/longitude position. This may or may not be successful and a status is returned as such. Usually this method is overridden in a dervied class, for example, Sinusoidal. If not the default method simply copies x/y to ring rad/lon to x/y which is no projection.
Parameters
x X coordinate of the projection in units that are the same as the radii in the label
y Y coordinate of the projection in units that are the same as the ring longitude in the label
Returns
bool Indicates whether the method was successful.
Implements Isis::Projection.
Reimplemented in Isis::RingCylindrical, and Isis::Planar.
References Isis::Projection::m_good, m_ringLongitude, m_ringRadius, Isis::Null, Isis::Projection::SetXY(), Isis::Projection::XCoord(), and Isis::Projection::YCoord().
SetGround()
bool Isis::RingPlaneProjection::SetGround (const double ringRadius, const double ringLongitude) virtual
This method is used to set the ring radius/longitude (assumed to be of the correct LatitudeType, LongitudeDirection, and LongitudeDomain.
The Set forces an attempted calculation of the projection X/Y values. This may or may not be successful and a status is returned as such. Usually this method is overridden in a dervied class, for example, Sinusoidal. If not the default method simply copies ring rad/lon to x/y which is no projection.
Parameters
ringRadius The ring radius value to project
ringLongitude The ring longitude value to project
Returns
bool Indicates whether the method was successful.
Implements Isis::Projection.
Reimplemented in Isis::RingCylindrical, and Isis::Planar.
References Isis::Projection::m_good, m_ringLongitude, m_ringRadius, Isis::Null, and Isis::Projection::SetComputedXY().
Referenced by Isis::ProjectionFactory::RingsCreateForCube(), SetUniversalGround(), and XYRangeCheck().
setProjectionType()
void Isis::Projection::setProjectionType (const ProjectionType ptype) inherited
Sets the projection subclass type.
Parameters
ptype The projection subclass type
Referenced by RingPlaneProjection(), and Isis::TProjection::TProjection().
SetUnboundUniversalGround()
bool Isis::Projection::SetUnboundUniversalGround (const double coord1, const double coord2) virtual inherited
This method is used to set the lat/lon or radius/azimuth (i.e.
ring longitude) coordinate, depending on the projection type. The Set forces an attempted calculation of the projection X/Y values. This may or may not be successful and a status is returned as such. This method will not adjust the longitude coordinate based on the longitude domain.
Parameters
coord1 Latitude (planetocentric) or ring radius to project
coord2 Longitude or ring longitude to project. The value passed in should be PositiveEast, Domain360.
Returns
bool Indicates whether the method was successful.
Reimplemented in Isis::TProjection.
References Isis::Projection::m_good, Isis::Null, Isis::Projection::projectionType(), Isis::TProjection::SetUnboundUniversalGround(), SetUniversalGround(), and Isis::Projection::Triaxial.
Referenced by Isis::UniversalGroundMap::SetUnboundGround().
SetUniversalGround()
bool Isis::RingPlaneProjection::SetUniversalGround (const double ringRadius, const double ringLongitude) virtual
This method is used to set the ring radius/longitude which must be PositiveEast/Domain360 (ring longitude).
The Set forces an attempted calculation of the projection X/Y values. This may or may not be successful and a status is returned as such.
Parameters
ringRadius The ring radius value to project
ringLongitude PositiveEast, Domain360 ring longitude value to project
Returns
bool Indicates whether the method was successful.
Reimplemented from Isis::Projection.
References Clockwise, Isis::Projection::m_good, m_ringLongitude, m_ringLongitudeDirection, m_ringLongitudeDomain, m_ringRadius, Isis::Null, SetGround(), To180Domain(), and To360Domain().
Referenced by Isis::Projection::SetUnboundUniversalGround(), and Isis::Projection::SetUniversalGround().
SetUpperLeftCorner()
void Isis::Projection::SetUpperLeftCorner (const Displacement & x, const Displacement & y) inherited
This method searches for extreme (min/max/discontinuity) coordinate values along the constBorder line between minBorder and maxBorder (that is, across latitudes/longitudes).
This method locates the extrema by utilizing the findExtreme() method until the coordinate values converge. Then, extremeVal parameter is updated with this value before returning.
Discontinuities are stored in m_specialLatCases and m_specialLonCases so they may be checked again later, which creates significantly more accuracy in some cases.
Parameters
minBorder Minimum latitude or longitude to search between.
maxBorder Maximum latitude or longitude to search between.
extremeVal The resulting global coordinate value (min or max value for x or y, depending on findMin and searchX) on the constBorder.
constBorder The latitude or longitude that remains constant. The method will step along this border.
searchX Indicates whether the method is searching for a min or max x-coordinate. If false the method searches for min or max y-coordinate.
searchLongitude Indicates whether the method will search along a longitude. If true, constBorder is longitude and all other borders are latitudes. If false, the method searches a latitude (constBorder is a lat, other borders lons).
findMin Indicates whether the method is looking for a minimum coordinate value. If false, the method is looking for a maximum value.
Author
Steven Lambright Searches for extreme (min/max/discontinuity) coordinate values across latitudes/longitudes.
This method looks for these extrema along the constBorder between minBorder and maxBorder by stepping along constBorder (10 times) from the minBorder and maxBorder. Then, the range of this extreme value is recorded in minBorder and maxBorder and the coordinate values corresponding to these new borders are stored in minBorderX, minBorderY, maxBorderX and maxBorderY.
This function should be used by calling it repeatedly until minBorderX and minBorderY do not equal maxBorderX and maxBorderY, respectively. Discontinuities will cause the minBorderX, minBorderY, maxBorderX and maxBorderY to never converge. If minBorderX never comes close to maxBorderX or minBorderY never comes close to maxBorderY, then between minBorder and maxBorder is the value of the most extreme value. In this case, either the smaller or larger of the x or y values found will be correct, depending on the values of findMin and searchX.
Parameters
minBorder Minimum latitude or longitude to search between. This value gets updated to a more precise range.
maxBorder Maximum latitude or longitude to search between. This value gets updated to a more precise range.
minBorderX The x-value corresponding to the lower resultant minBorder and the constBorder, which is more accurate when nearly equal to maxBorderX.
minBorderY The y-value corresponding to the lower resultant minBorder and the constBorder, which is more accurate when nearly equal to maxBorderY.
maxBorderX The x-value corresponding to the higher resultant maxBorder and the constBorder, which is more accurate when nearly equal to minBorderX.
maxBorderY The y-value corresponding to the higher resultant maxBorder and the constBorder, which is more accurate when nearly equal to minBorderY.
constBorder The latitude or longitude that remains constant. The method will step along this border.
searchX Indicates whether the method is searching for a min or max x-coordinate. If false the method searches for min or max y-coordinate.
searchLongitude Indicates whether the method will search along a longitude. If true, constBorder is longitude and all other borders are latitudes. If false, the method searches a latitude (constBorder is a lat, other borders lons).
findMin Indicates whether the method is looking for a minimum coordinate value. If false, the method is looking for a maximum value.
Author
Stephen Lambright This function sets the ground for the given border values. It calls the SetGround(lat, lon) method with the appropriate lat/lon values, depending on whether variableIsLat is true.
This method is used by doSearch and findExtreme in order to set the ground correctly each time.
Parameters
variableBorder The latitude or longitude that is variable in the search methods.
constBorder The latitude or longitude that is constant in the search methods.
variableIsLat Indicates whether variableBorder is the latittude value and constBorder is the longitude value. If false, variableBorder is the longitude value and constBorder is the latitude value.
Author
Stephen Lambright This method sets the UpperLeftCornerX and UpperLeftCornerY keywords in the projection mapping group, in meters.
Parameters
x the upper left corner x value
y the upper left corner y value
References Isis::PvlContainer::addKeyword(), Isis::Projection::m_mappingGrp, Isis::Displacement::meters(), Isis::PvlContainer::Replace, and Isis::toString().
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::ProjectionFactory::CreateFromCube(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::ProjectionFactory::RingsCreateFromCube(), and Isis::ProcessMapMosaic::SetOutputCube().
SetWorld()
bool Isis::Projection::SetWorld (const double worldX, const double worldY) virtual inherited
This method is used to set a world coordinate.
A world coordinate is a different coordinate type that has a one-to-one mapping to the projection coordinate system. For example, mapping pixel samples and lines to projection x's and y's. The Set forces an attempted calculation of the corresponding latitude/longitude position. This may or may not be successful and a status is returned as such. Note that is only applies if the Projection object was given an WorldMapper object during construction. If an WorldMapper was not supplied then SetWorld operates exactly the same as SetCoordinate (impling that world coordinate and projection coordinate are identical).
Parameters
worldX World X coordinate in units that are specified by the WorldMapper object (e.g., pixels, millimeters, etc)
worldY World Y coordinate in units that are specified by the WorldMapper object (e.g., pixels, millimeters, etc)
Returns
bool Indicates whether the method was successful.
References Isis::Projection::m_mapper, Isis::WorldMapper::ProjectionX(), Isis::WorldMapper::ProjectionY(), and Isis::Projection::SetCoordinate().
Referenced by Isis::ProcessExport::CreateWorldFile(), Isis::UniversalGroundMap::GroundRange(), Isis::Cube::latLonRange(), Isis::Chip::Load(), Isis::UniversalGroundMap::SetImage(), Isis::SubArea::UpdateLabel(), and Isis::PolygonTools::XYToLatLon().
SetWorldMapper()
void Isis::Projection::SetWorldMapper (WorldMapper * mapper) inherited
If desired the programmer can use this method to set a world mapper to be used in the SetWorld, WorldX, and WorldY methods.
Mappers typically transform a projection coordinate (x/y) into the desired working coordinate system, for example, cube pixels or inches on a piece of paper. They transform in both directions (world to projection and projection to world). This allows for conversions from line/sample to latitude/longitude and vice versa. This projection will take ownership of the WorldMapper pointer.
Parameters
mapper Pointer to the mapper
References Isis::Projection::m_mapper.
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::ProjectionFactory::CreateFromCube(), Isis::ProjectionFactory::RingsCreateForCube(), and Isis::ProjectionFactory::RingsCreateFromCube().
SetXY()
void Isis::Projection::SetXY (double x, double y) protected inherited
This protected method is a helper for derived classes.
It takes a rotated x,y and stores them in the current x and y data members.
Parameters
x The rotated x coordinate.
y The rotated y coordinate.
References Isis::Projection::m_good, and Isis::Null.
Referenced by Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::LunarAzimuthalEqualArea::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Mollweide::SetCoordinate(), Isis::ObliqueCylindrical::SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::Planar::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::RingCylindrical::SetCoordinate(), SetCoordinate(), Isis::Robinson::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), Isis::TProjection::SetCoordinate(), and Isis::TransverseMercator::SetCoordinate().
To180Domain()
double Isis::RingPlaneProjection::To180Domain (const double ringLongitude) static
This method converts a ring longitude into the -180 to 180 domain.
It will leave the ring longitude unchanged if it is already in the domain.
Parameters
ringLongitude A ring longitude to convert into the -180 to 180 domain.
Exceptions
IException::Unknown - "The given longitude is invalid."
Returns
double The ring longitude, converted to 180 domain.
References _FILEINFO_, Isis::Angle::Degrees, Isis::Angle::degrees(), Isis::Longitude::force180Domain(), Isis::Null, and Isis::IException::Unknown.
Referenced by Isis::Planar::SetCoordinate(), SetUniversalGround(), ToClockwise(), and ToCounterClockwise().
To360Domain()
double Isis::RingPlaneProjection::To360Domain (const double ringLongitude) static
This method converts an ring longitude into the 0 to 360 domain.
It will leave the ring longitude unchanged if it is already in the domain.
Parameters
ringLongitude The ring longitude to convert into the 0 to 360 domain.
Returns
double The ring longitude, converted to 360 domain.
References _FILEINFO_, Isis::Angle::Degrees, Isis::Angle::degrees(), Isis::Longitude::force360Domain(), Isis::Null, and Isis::IException::Unknown.
Referenced by Isis::Planar::SetCoordinate(), SetUniversalGround(), ToClockwise(), ToCounterClockwise(), and UniversalRingLongitude().
ToClockwise()
double Isis::RingPlaneProjection::ToClockwise (const double ringLongitude, const int domain) static
This method converts an ring longitude into the clockwise direction.
Parameters
ringLongitude The ring longitude to convert into the clockwise direction.
domain Must be an integer value of 180 (for -180 to 180) or 360 (for 0 to 360).
Exceptions
IException::Unknown - "The given ring longitude is invalid."
IException::Unknown - "Unable to convert ring longitude. Domain is not 180 or 360."
Returns
double The ring longitude value, in clockwise direction.
References _FILEINFO_, Isis::Null, To180Domain(), To360Domain(), Isis::toString(), and Isis::IException::Unknown.
ToCounterClockwise()
double Isis::RingPlaneProjection::ToCounterClockwise (const double ringLongitude, const int domain) static
This method converts an ring longitude into the counterclockwise direction.
Parameters
ringLongitude The ring Longitude to convert into the counterclockwise direction.
domain Must be an integer value of 180 (for -180 to 180) or 360 (for 0 to 360).
Exceptions
IException::Unknown - "The given ring longitude is invalid."
IException::Unknown - "Unable to convert ring longitude. Domain is not 180 or 360."
Returns
double The ring longitude value, in counterclockwise direction.
References _FILEINFO_, Isis::Null, To180Domain(), To360Domain(), and Isis::IException::Unknown.
ToDMS()
QString Isis::Projection::ToDMS (double angle) static inherited
Converts the given angle (in degrees) to degrees, minutes, seconds.
Outputs in the form xxx yym zz.zzzs, for example, 206.291 degrees is 206 17m 27.6s
Parameters
angle Angle in degrees to be converted to degrees, minutes, seconds
Returns
string The angle in Degrees, minutes, seconds
ToHMS()
QString Isis::Projection::ToHMS (double angle) static inherited
Converts the given angle (in degrees) to hours, minutes, seconds.
Outputs in the form xxh yym zz.zzzs For example, 206.291 will be 13h 45m 09.84s
Parameters
angle Angle in degrees to be converted to hours, minutes, seconds
Returns
string The angle in Hours, minutes, seconds
References Isis::Projection::ToHours().
ToHours()
double Isis::Projection::ToHours (double angle) static inherited
Converts the given angle (in degrees) to hours by using the ratio 15 degrees per hour.
Parameters
angle Angle in degrees to be converted to hours
Returns
double The number of hours for the given angle.
Referenced by Isis::Projection::ToHMS().
ToProjectionX()
double Isis::Projection::ToProjectionX (const double worldX) const inherited
This method converts a world x value to a projection x value.
For example, if the world coordinate system is an image then this method converts a sample position to a projection x value. Note that if SetWorldMapper is not used then this routine simply returns the value of the argument. That is, no mapping occurs.
Parameters
worldX World x coordinate
Exceptions
IException::Unknown - "The given x-value is invalid."
Returns
double The projection X coordinate value.
References _FILEINFO_, Isis::Projection::m_mapper, Isis::Null, Isis::WorldMapper::ProjectionX(), and Isis::IException::Unknown.
Referenced by Isis::OverlapStatistics::OverlapStatistics(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::ProcessMapMosaic::StartProcess().
ToProjectionY()
double Isis::Projection::ToProjectionY (const double worldY) const inherited
This method converts a world y value to a projection y value.
For example, if the world coordinate system is an image then this method converts a line position to a projection y value. Note that if SetWorldMapper is not used then this routine simply returns the value of the argument. That is, no mapping occurs.
Parameters
worldY World y coordinate
Exceptions
IException::Unknown - "The given y-value is invalid."
Returns
double The projection Y coordinate value.
References _FILEINFO_, Isis::Projection::m_mapper, Isis::Null, Isis::WorldMapper::ProjectionY(), and Isis::IException::Unknown.
Referenced by Isis::OverlapStatistics::OverlapStatistics(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::ProcessMapMosaic::StartProcess().
ToWorldX()
double Isis::Projection::ToWorldX (const double projectionX) const inherited
This method converts a projection x value to a world x value.
For example, if the world coordinate system is an image then this method converts a projection x to a sample position. Note that if SetWorldMapper is not used then this routine simply returns the value of the argument. That is, no mapping occurs.
Parameters
projectionX Projection x value in meters
Exceptions
IException::Unknown - "The given x-value is invalid."
Returns
double The world X coordinate value.
References _FILEINFO_, Isis::Projection::m_mapper, Isis::Null, Isis::IException::Unknown, and Isis::WorldMapper::WorldX().
Referenced by Isis::OverlapStatistics::OverlapStatistics(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::ProcessMapMosaic::StartProcess().
ToWorldY()
double Isis::Projection::ToWorldY (const double projectionY) const inherited
This method converts a projection y value to a world y value.
For example, if the world coordinate system is an image then this method converts a projection y to a line position. Note that if SetWorldMapper is not used then this routine simply returns the value of the argument. That is, no mapping occurs.
Parameters
projectionY Projection y value in meters
Exceptions
IException::Unknown - "The given y-value is invalid."
Returns
double The world Y coordinate value.
References _FILEINFO_, Isis::Projection::m_mapper, Isis::Null, Isis::IException::Unknown, and Isis::WorldMapper::WorldY().
Referenced by Isis::OverlapStatistics::OverlapStatistics(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::ProcessMapMosaic::SetOutputCube(), and Isis::ProcessMapMosaic::StartProcess().
TrueScaleRingRadius()
double Isis::RingPlaneProjection::TrueScaleRingRadius () const virtual
This method returns the radius of true scale.
It is a virtual function and if it is not overriden the default radius of true scale is 0 (at the equator). Otherwise it is projection specific. This method is used by the Scale routine to ensure the local radius is used in the computation.
Returns
double The radius where the projection is not distorted.
Reimplemented in Isis::RingCylindrical, and Isis::Planar.
Referenced by Isis::ProjectionFactory::RingsCreateForCube(), and Scale().
UniversalRingLongitude()
double Isis::RingPlaneProjection::UniversalRingLongitude ()
This returns a universal ring longitude (clockwise in 0 to 360 domain).
The method can only be used if SetGround, SetCoordinate, SetUniversalGround, or SetWorld return with success. Success can also be checked using the IsGood method.
Returns
double The universal ring longitude.
References Clockwise, m_ringLongitude, m_ringLongitudeDirection, and To360Domain().
UniversalRingRadius()
double Isis::RingPlaneProjection::UniversalRingRadius ()
This returns a universal radius, which is just the radius in meters.
Returns
double The universal radius.
References m_ringRadius.
Version()
virtual QString Isis::RingPlaneProjection::Version () const pure virtual
This method returns the Version of the map projection.
It is a pure virtual method (requires all subclasses to override).
Returns
string The Version number of the map projection.
Implements Isis::Projection.
Implemented in Isis::RingCylindrical, and Isis::Planar.
WorldX()
double Isis::Projection::WorldX () const virtual inherited
This returns the world X coordinate provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
Success can also be checked using the IsGood method. The units of X will be in the units as specified by the WorldMapper object which was given to the SetWorldMapper method. If a mapper object was not given then world coordinates are the same as the projection coordinates (i.e., WorldX and XCoord will return the same value).
Returns
double The world X coordinate.
References Isis::Projection::m_mapper, and Isis::WorldMapper::WorldX().
Referenced by Isis::Chip::Load(), Isis::DemShape::localRadius(), Isis::UniversalGroundMap::Sample(), Isis::Camera::SetRightAscensionDeclination(), and Isis::ProcessMapMosaic::StartProcess().
WorldY()
double Isis::Projection::WorldY () const virtual inherited
This returns the world Y coordinate provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
Success can also be checked using the IsGood method. The units of Y will be in the units as specified by the WorldMapper object which was given to the SetWorldMapper. If a mapper object was not given then world coordinates are the same as the projection coordinates (i.e., WorldY and YCoord will return the same value).
Returns
double The world Y coordinate.
References Isis::Projection::m_mapper, and Isis::WorldMapper::WorldY().
Referenced by Isis::UniversalGroundMap::Line(), Isis::Chip::Load(), Isis::DemShape::localRadius(), and Isis::Camera::SetRightAscensionDeclination().
XCoord()
double Isis::Projection::XCoord () const inherited
This returns the projection X provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
Success can also be checked using the IsGood method. The units of X will be in the same . units as the radii obtained from the label.
Returns
double
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::ProcessExport::CreateWorldFile(), Isis::MosaicFindTool::getUserGroundPoint(), Isis::GridGraphicsItem::GridGraphicsItem(), Isis::PolygonTools::LatLonToXY(), Isis::MosaicSceneItem::reproject(), Isis::ProjectionFactory::RingsCreateForCube(), SetCoordinate(), Isis::TProjection::SetCoordinate(), Isis::MosaicGridTool::setLatExtents(), Isis::SubArea::UpdateLabel(), Isis::MosaicAreaTool::userChangedBox(), Isis::LambertConformal::XYRange(), Isis::PointPerspective::XYRange(), Isis::TProjection::XYRangeCheck(), and XYRangeCheck().
XYRange()
bool Isis::RingPlaneProjection::XYRange (double & minX, double & maxX, double & minY, double & maxY) virtual
This method is used to determine the x/y range which completely covers the area of interest specified by the ring radius/longitude range.
The ring radius/ring longitude range may be obtained from the labels. This method should not be used if HasGroundRange is false. The purpose of this method is to return the x/y range so it can be used to compute how large a map may need to be. For example, how big a piece of paper is needed or how large of an image needs to be created. This is method and therefore must be written by the derived class (e.g., Planar). The method may fail as indicated by its return value.
Parameters
&minX Reference to the address where the minimum x coordinate value will be written. The Minimum x projection coordinate calculated by this method covers the ring radius/longitude range specified in the labels.
&maxX Reference to the address where the maximum x coordinate value will be written. The Maximum x projection coordinate calculated by this method covers the ring radius/longitude range specified in the labels.
&minY Reference to the address where the minimum y coordinate value will be written. The Minimum y projection coordinate calculated by this method covers the ring radius/longitude range specified in the labels.
&maxY Reference to the address where the maximum y coordinate value will be written. The Maximum y projection coordinate calculated by this method covers the ring radius/longitude range specified in the labels.
Returns
bool Indicates whether the method was able to determine the X/Y Range of the projection. If yes, minX, maxX, minY, maxY will be set with these values.
Implements Isis::Projection.
Reimplemented in Isis::RingCylindrical, and Isis::Planar.
References Isis::Projection::m_groundRangeGood, m_maximumRingLongitude, m_maximumRingRadius, m_minimumRingLongitude, m_minimumRingRadius, and Isis::Null.
Referenced by Isis::ProjectionFactory::RingsCreateForCube().
XYRangeCheck()
void Isis::RingPlaneProjection::XYRangeCheck (const double ringRadius, const double ringLongitude) protected virtual
This convience function is established to assist in the development of the XYRange virtual method.
It allows the developer to test ground points (ring radius/longitude) to see if they produce a minimum/maximum projection coordinate. For example in Planar,
 bool Planar::XYRange(double &minX, double &maxX,
                              double &minY, double &maxY) {
  // Check the corners of the ring rad/lon range
   XYRangeCheck (m_minimumRingRadius,m_minimumRingLongitude);
   XYRangeCheck (m_maximumRingRadius,m_minimumRingLongitude);
   XYRangeCheck (m_minimumRingRadius,m_maximumRingLongitude);
   XYRangeCheck (m_maximumRingRadius,m_maximumRingLongitude);
   // If the ring longitude crosses 0/360 check there
   if ((m_minimumRingLongitude < 0.0) && (m_maximumRingLongitude > 0.0)) ||
       (m_minimumRingLongitude < 360.0) && (m_maximumRingLongitude > 360.0)) {
     XYRangeCheck (minimumRingRadius, 0. or 360.);
     XYRangeCheck (maximumRingRadius, 0 or 360.);
   }
   // Make sure everything is ordered
   if (m_minimumX >= m_maximumX) return false;
   if (m_minimumY >= m_maximumY) return false;
   // Return X/Y min/maxs
   minX = m_minimumX;
   maxX = m_maximumX;
   minY = m_minimumY;
   maxY = m_maximumY;
   return true;
}
Parameters
ringRadius Test for min/max projection coordinates at this radius
ringLongitude Test for min/max projection coordinates at this ring longitude
Implements Isis::Projection.
References Isis::Projection::IsGood(), Isis::Projection::m_good, Isis::Projection::m_maximumX, Isis::Projection::m_maximumY, Isis::Projection::m_minimumX, Isis::Projection::m_minimumY, Isis::Null, SetGround(), Isis::Projection::XCoord(), and Isis::Projection::YCoord().
Referenced by Isis::Planar::XYRange(), and Isis::RingCylindrical::XYRange().
YCoord()
double Isis::Projection::YCoord () const inherited
This returns the projection Y provided SetGround, SetCoordinate, SetUniversalGround, or SetWorld returned with success.
Success can also be checked using the IsGood method. The units of Y will be in the same units as the radii obtained from the label.
Returns
double
Referenced by Isis::ProjectionFactory::CreateForCube(), Isis::ProcessExport::CreateWorldFile(), Isis::MosaicFindTool::getUserGroundPoint(), Isis::GridGraphicsItem::GridGraphicsItem(), Isis::PolygonTools::LatLonToXY(), Isis::MosaicSceneItem::reproject(), Isis::ProjectionFactory::RingsCreateForCube(), SetCoordinate(), Isis::TProjection::SetCoordinate(), Isis::MosaicGridTool::setLatExtents(), Isis::SubArea::UpdateLabel(), Isis::MosaicAreaTool::userChangedBox(), Isis::LambertConformal::XYRange(), Isis::PointPerspective::XYRange(), Isis::TProjection::XYRangeCheck(), and XYRangeCheck().
Member Data Documentation
m_good
bool Isis::Projection::m_good protected inherited
Indicates if the contents of m_x, m_y, m_latitude, and m_longitude are valid.
Referenced by Isis::Projection::IsGood(), Isis::Projection::Projection(), Isis::Projection::SetComputedXY(), Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::LunarAzimuthalEqualArea::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Mollweide::SetCoordinate(), Isis::ObliqueCylindrical::SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::Planar::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::RingCylindrical::SetCoordinate(), SetCoordinate(), Isis::Robinson::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), Isis::TProjection::SetCoordinate(), Isis::TransverseMercator::SetCoordinate(), Isis::Equirectangular::SetGround(), Isis::LambertConformal::SetGround(), Isis::LunarAzimuthalEqualArea::SetGround(), Isis::Mercator::SetGround(), Isis::Mollweide::SetGround(), Isis::ObliqueCylindrical::SetGround(), Isis::Orthographic::SetGround(), Isis::PointPerspective::SetGround(), Isis::PolarStereographic::SetGround(), Isis::Robinson::SetGround(), Isis::SimpleCylindrical::SetGround(), Isis::Sinusoidal::SetGround(), Isis::TProjection::SetGround(), Isis::TransverseMercator::SetGround(), Isis::Planar::SetGround(), Isis::RingCylindrical::SetGround(), SetGround(), Isis::Projection::SetUnboundUniversalGround(), Isis::TProjection::SetUnboundUniversalGround(), Isis::Projection::SetUniversalGround(), Isis::TProjection::SetUniversalGround(), SetUniversalGround(), Isis::Projection::SetXY(), Isis::LambertConformal::XYRange(), Isis::TProjection::XYRangeCheck(), and XYRangeCheck().
m_groundRangeGood
bool Isis::Projection::m_groundRangeGood protected inherited
Indicates if the ground range (min/max lat/lons) were read from the labels.
Referenced by Isis::Projection::HasGroundRange(), RingPlaneProjection(), Isis::TProjection::TProjection(), XYRange(), and Isis::TProjection::XYRange().
m_mapper
WorldMapper* Isis::Projection::m_mapper protected inherited
This points to a mapper passed into the SetWorldMapper method.
This mapper allows the programmer to specify a different world coordinate system. Thus the programmer could pass in line/sample positions in order to obtain a latitude/longitude or set a lat/lon and get a line/sample.
Referenced by Isis::Projection::Projection(), Isis::Projection::Resolution(), Scale(), Isis::TProjection::Scale(), Isis::Projection::SetWorld(), Isis::Projection::SetWorldMapper(), Isis::Projection::ToProjectionX(), Isis::Projection::ToProjectionY(), Isis::Projection::ToWorldX(), Isis::Projection::ToWorldY(), Isis::Projection::WorldX(), Isis::Projection::WorldY(), and Isis::Projection::~Projection().
m_mappingGrp
PvlGroup Isis::Projection::m_mappingGrp protected inherited
Mapping group that created this projection.
Referenced by Isis::Equirectangular::Mapping(), Isis::LambertConformal::Mapping(), Isis::LunarAzimuthalEqualArea::Mapping(), Isis::Mercator::Mapping(), Isis::Mollweide::Mapping(), Isis::ObliqueCylindrical::Mapping(), Isis::Orthographic::Mapping(), Isis::PointPerspective::Mapping(), Isis::PolarStereographic::Mapping(), Mapping(), Isis::Robinson::Mapping(), Isis::SimpleCylindrical::Mapping(), Isis::Sinusoidal::Mapping(), Isis::TProjection::Mapping(), Isis::TransverseMercator::Mapping(), Isis::Equirectangular::MappingLatitudes(), Isis::LambertConformal::MappingLatitudes(), Isis::Mercator::MappingLatitudes(), Isis::Orthographic::MappingLatitudes(), Isis::PointPerspective::MappingLatitudes(), Isis::PolarStereographic::MappingLatitudes(), Isis::TProjection::MappingLatitudes(), Isis::TransverseMercator::MappingLatitudes(), Isis::Equirectangular::MappingLongitudes(), Isis::LambertConformal::MappingLongitudes(), Isis::Mercator::MappingLongitudes(), Isis::Mollweide::MappingLongitudes(), Isis::Orthographic::MappingLongitudes(), Isis::PointPerspective::MappingLongitudes(), Isis::PolarStereographic::MappingLongitudes(), Isis::Robinson::MappingLongitudes(), Isis::SimpleCylindrical::MappingLongitudes(), Isis::Sinusoidal::MappingLongitudes(), Isis::TProjection::MappingLongitudes(), Isis::TransverseMercator::MappingLongitudes(), Isis::Planar::MappingRingLongitudes(), Isis::RingCylindrical::MappingRingLongitudes(), MappingRingLongitudes(), Isis::Planar::MappingRingRadii(), Isis::RingCylindrical::MappingRingRadii(), MappingRingRadii(), Isis::Projection::Projection(), RingPlaneProjection(), Isis::Projection::SetUpperLeftCorner(), and Isis::TProjection::TProjection().
m_maximumRingLongitude
double Isis::RingPlaneProjection::m_maximumRingLongitude protected
Contains the maximum longitude for the entire ground range.
Only usable if m_groundRangeGood is true.
Referenced by MaximumRingLongitude(), Isis::Planar::Planar(), Isis::RingCylindrical::RingCylindrical(), RingPlaneProjection(), Isis::Planar::XYRange(), Isis::RingCylindrical::XYRange(), and XYRange().
m_maximumRingRadius
double Isis::RingPlaneProjection::m_maximumRingRadius protected
Contains the maximum ring radius for the entire ground range.
Only usable if m_groundRangeGood is true.
Referenced by MaximumRingRadius(), Isis::Planar::Planar(), Isis::RingCylindrical::RingCylindrical(), RingPlaneProjection(), Isis::RingCylindrical::SetCoordinate(), Isis::Planar::XYRange(), Isis::RingCylindrical::XYRange(), and XYRange().
m_maximumX
double Isis::Projection::m_maximumX protected inherited
See minimumX description.
Referenced by Isis::Projection::Projection(), Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::Planar::XYRange(), Isis::PolarStereographic::XYRange(), Isis::RingCylindrical::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), Isis::TransverseMercator::XYRange(), Isis::TProjection::XYRangeCheck(), XYRangeCheck(), and Isis::TProjection::xyRangeOblique().
m_maximumY
double Isis::Projection::m_maximumY protected inherited
See minimumX description.
Referenced by Isis::Projection::Projection(), Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::Planar::XYRange(), Isis::PolarStereographic::XYRange(), Isis::RingCylindrical::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), Isis::TransverseMercator::XYRange(), Isis::TProjection::XYRangeCheck(), XYRangeCheck(), and Isis::TProjection::xyRangeOblique().
m_minimumRingLongitude
double Isis::RingPlaneProjection::m_minimumRingLongitude protected
Contains the minimum longitude for the entire ground range.
Only usable if m_groundRangeGood is true.
Referenced by MinimumRingLongitude(), Isis::Planar::Planar(), Isis::RingCylindrical::RingCylindrical(), RingPlaneProjection(), Isis::Planar::XYRange(), Isis::RingCylindrical::XYRange(), and XYRange().
m_minimumRingRadius
double Isis::RingPlaneProjection::m_minimumRingRadius protected
Contains the minimum ring radius for the entire ground range.
Only usable if m_groundRangeGood is true.
Referenced by MinimumRingRadius(), Isis::Planar::Planar(), Isis::RingCylindrical::RingCylindrical(), RingPlaneProjection(), Isis::Planar::XYRange(), Isis::RingCylindrical::XYRange(), and XYRange().
m_minimumX
double Isis::Projection::m_minimumX protected inherited
The data elements m_minimumX, m_minimumY, m_maximumX, and m_maximumY are convience data elements when you write the XYRange virtual function.
They are used in conjuction with the XYRangeCheck convience method. After utilizing XYRangeCheck to test boundary conditions in the XYRange method these values will contain the projection x/y coverage for the ground range specified by min/max lat/lon.
Referenced by Isis::Projection::Projection(), Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::Planar::XYRange(), Isis::PolarStereographic::XYRange(), Isis::RingCylindrical::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), Isis::TransverseMercator::XYRange(), Isis::TProjection::XYRangeCheck(), XYRangeCheck(), and Isis::TProjection::xyRangeOblique().
m_minimumY
double Isis::Projection::m_minimumY protected inherited
See minimumX description.
Referenced by Isis::Projection::Projection(), Isis::Equirectangular::XYRange(), Isis::LambertConformal::XYRange(), Isis::LunarAzimuthalEqualArea::XYRange(), Isis::Mercator::XYRange(), Isis::Mollweide::XYRange(), Isis::Orthographic::XYRange(), Isis::Planar::XYRange(), Isis::PolarStereographic::XYRange(), Isis::RingCylindrical::XYRange(), Isis::Robinson::XYRange(), Isis::SimpleCylindrical::XYRange(), Isis::Sinusoidal::XYRange(), Isis::TransverseMercator::XYRange(), Isis::TProjection::XYRangeCheck(), XYRangeCheck(), and Isis::TProjection::xyRangeOblique().
m_ringLongitude
double Isis::RingPlaneProjection::m_ringLongitude protected
This contain a ring longitude value.
The value is only usable if m_good is true.
Referenced by RingLongitude(), RingPlaneProjection(), Isis::Planar::SetCoordinate(), Isis::RingCylindrical::SetCoordinate(), SetCoordinate(), Isis::Planar::SetGround(), Isis::RingCylindrical::SetGround(), SetGround(), SetUniversalGround(), and UniversalRingLongitude().
m_ringLongitudeDirection
RingLongitudeDirection Isis::RingPlaneProjection::m_ringLongitudeDirection protected
An enumerated type indicating the LongitudeDirection read from the labels.
It can be either PositiveEast or PositiveWest. Indicating which direction the positive axis for longitude is.
Referenced by Isis::Planar::CenterRingLongitude(), Isis::RingCylindrical::CenterRingLongitude(), IsClockwise(), IsCounterClockwise(), Isis::Planar::Mapping(), Isis::RingCylindrical::Mapping(), Isis::Planar::Planar(), Isis::RingCylindrical::RingCylindrical(), RingLongitudeDirectionString(), RingPlaneProjection(), Isis::Planar::SetCoordinate(), Isis::RingCylindrical::SetCoordinate(), Isis::Planar::SetGround(), Isis::RingCylindrical::SetGround(), SetUniversalGround(), and UniversalRingLongitude().
m_ringLongitudeDomain
int Isis::RingPlaneProjection::m_ringLongitudeDomain protected
This integer is either 180 or 360 and is read from the labels.
It represents the ring longitude domain when returning values through RingLongitude() method. The domain is either -180 to 180 or 0 to 360.
Referenced by Has180Domain(), Has360Domain(), RingLongitudeDomainString(), RingPlaneProjection(), Isis::Planar::SetCoordinate(), and SetUniversalGround().
m_ringRadius
double Isis::RingPlaneProjection::m_ringRadius protected
This contain a ring radius value in m.
The value is only usable if m_good is true.
Referenced by LocalRadius(), Isis::Planar::Planar(), RingPlaneProjection(), RingRadius(), Isis::Planar::SetCoordinate(), Isis::RingCylindrical::SetCoordinate(), SetCoordinate(), Isis::Planar::SetGround(), Isis::RingCylindrical::SetGround(), SetGround(), SetUniversalGround(), and UniversalRingRadius().
m_sky
bool Isis::Projection::m_sky protected inherited
Indicates whether projection is sky or land.
Referenced by Isis::Projection::IsSky(), and Isis::Projection::Projection().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/RingPlaneProjection/RingPlaneProjection.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/RingPlaneProjection/RingPlaneProjection.cpp