Isis Developer Reference: Isis::ObservationNumber Class Reference
Isis::ObservationNumber Class Reference
Control Networks
Serial Number composer.
#include <ObservationNumber.h>
Public Member Functions
ObservationNumber ()
Create an empty SerialNumber object.
virtual ~ObservationNumber ()
Destroy a SerialNumber object.
std::vector< QString > PossibleSerial (const QString &on, SerialNumberList &list)
Creates a vector of plasible SerialNumbers from a string representing the ObservationNumber and a SerialList.
Static Public Member Functions
static QString Compose (Pvl &label, bool def2filename=false)
Compose a ObservationNumber from a PVL.
static QString Compose (Cube &cube, bool def2filename=false)
Compose a SerialNumber fPvlGroup snGrouprom a Cube.
static QString Compose (const QString &filename, bool def2filename=false)
Compose a SerialNumber from a file.
static QString ComposeObservation (const QString &sn, SerialNumberList &list, bool def2filename=false)
Creates the ObservationNumber from a string representing the SerialNumber and a SerialList.
Static Protected Member Functions
static QString CreateSerialNumber (PvlGroup &snGroup, int key)
Create the SerialNumber string by concatenating the keywords in the label with '/' in between serialNumber groups and the number of observationKeys.
Detailed Description
Serial Number composer.
A Serial Number is a unique identification for some object such as an Isis cube. A Serial Number for a specific object must be repeatable. This class is intended to be used to create all Serial Numbers for Isis.
Author
2008-??-?? Christopher Austin
Constructor & Destructor Documentation
ObservationNumber()
Isis::ObservationNumber::ObservationNumber ()
Create an empty SerialNumber object.
~ObservationNumber()
Isis::ObservationNumber::~ObservationNumber () virtual
Destroy a SerialNumber object.
Member Function Documentation
Compose() [1/3]
QString Isis::ObservationNumber::Compose (const QString & filename, bool def2filename = false) static
Compose a SerialNumber from a file.
Parameters
filename a filename to open
References Compose().
Compose() [2/3]
QString Isis::ObservationNumber::Compose (Cube & cube, bool def2filename = false) static
Compose a SerialNumber fPvlGroup snGrouprom a Cube.
Parameters
cube An opened Isis cube
References Compose(), and Isis::Cube::label().
Compose() [3/3]
QString Isis::ObservationNumber::Compose (Pvl & label, bool def2filename = false) static
Compose a ObservationNumber from a PVL.
Parameters
label A pvl formatted label to be used to generate the serial number
References Isis::SerialNumber::CreateSerialNumber(), Isis::PvlContainer::fileName(), and Isis::FileName::name().
Referenced by Isis::SerialNumberList::add(), Compose(), Isis::SerialNumber::ComposeObservation(), and Isis::Image::observationNumber().
ComposeObservation()
QString Isis::SerialNumber::ComposeObservation (const QString & sn, SerialNumberList & list, bool def2filename = false) static inherited
Creates the ObservationNumber from a string representing the SerialNumber and a SerialList.
Parameters
sn the string representing the SerialNumber
list the SerialNumberList
def2filename If a serial number could not be found, try to return the filename
Returns
Calculated SerialNumber or FileName
References Compose(), and Isis::SerialNumberList::fileName().
CreateSerialNumber()
QString Isis::SerialNumber::CreateSerialNumber (PvlGroup & snGroup, int keys) static protected inherited
Create the SerialNumber string by concatenating the keywords in the label with '/' in between serialNumber groups and the number of observationKeys.
Parameters
snGroup A PvlGroup containing the keywords to concatenate
keys the number of strings to contatenate
Referenced by Compose(), and Isis::SerialNumber::Compose().
PossibleSerial()
std::vector< QString > Isis::ObservationNumber::PossibleSerial (const QString & on, SerialNumberList & list)
Creates a vector of plasible SerialNumbers from a string representing the ObservationNumber and a SerialList.
Parameters
on the string representing the ObservationNumber
list the SerialNumberList
References Isis::SerialNumberList::serialNumber(), and Isis::SerialNumberList::size().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ObservationNumber/ObservationNumber.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ObservationNumber/ObservationNumber.cpp