Isis Developer Reference: Isis::JigsawSetupDialog Class Reference
Isis::JigsawSetupDialog Class Reference
Control Networks
#include <JigsawSetupDialog.h>
Public Slots
void slotTextChanged (const QString &text)
void checkIsValid ()
void treeViewSelectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Public Member Functions
JigsawSetupDialog (Project *project, bool useLastSettings=true, bool readOnly=false, QWidget *parent=0)
~JigsawSetupDialog ()
Control * selectedControl ()
QString selectedControlName ()
QString outputControlName ()
BundleSettingsQsp bundleSettings ()
void loadSettings (const BundleSettingsQsp settings)
Loads the passed bundle settings into the setup dialog.
void selectControl (const QString &controlName)
Selects a control in the control network combo box by trying to find an item with the matching name.
Detailed Description
Author
2014-04-21 Ken Edmundson
Constructor & Destructor Documentation
JigsawSetupDialog()
Isis::JigsawSetupDialog::JigsawSetupDialog (Project * project, bool useLastSettings = true, bool readOnly = false, QWidget * parent = 0) explicit
References Isis::BundleObservationSolveSettings::addObservationNumber(), Isis::BundleObservationSolveSettings::AnglesVelocityAcceleration, Isis::FileName::baseName(), Isis::Project::bundleSolutionInfo(), Isis::Cube::camera(), checkIsValid(), Isis::ProjectItem::child(), Isis::Project::controls(), Isis::Image::cube(), Isis::Project::directory(), Isis::DisplayProperties::displayName(), Isis::Control::displayProperties(), Isis::ProjectItemModel::findItemData(), Isis::Camera::GetCameraType(), Isis::ProjectItem::image(), Isis::ProjectItem::isImage(), Isis::ProjectItem::isImageList(), Isis::Camera::LineScan, Isis::Directory::model(), Isis::Image::observationNumber(), Isis::BundleObservationSolveSettings::observationNumbers(), Isis::ProjectItemModel::selectedItems(), Isis::BundleObservationSolveSettings::setInstrumentPointingSettings(), slotTextChanged(), and Isis::Project::targetBodies().
~JigsawSetupDialog()
Isis::JigsawSetupDialog::~JigsawSetupDialog ()
Member Function Documentation
bundleSettings()
BundleSettingsQsp Isis::JigsawSetupDialog::bundleSettings ()
References Isis::Angle::Degrees, Isis::Distance::Kilometers, Isis::SurfacePoint::Latitudinal, Isis::BundleTargetBody::MeanRadius, Isis::Distance::Meters, Isis::BundleTargetBody::PM, Isis::BundleTargetBody::PoleDec, Isis::BundleTargetBody::PoleRA, Isis::BundleSettings::Sigma0, Isis::MaximumLikelihoodWFunctions::stringToModel(), Isis::BundleTargetBody::TriaxialRadiusA, Isis::BundleTargetBody::TriaxialRadiusB, Isis::BundleTargetBody::TriaxialRadiusC, Isis::BundleTargetBody::VelocityPM, Isis::BundleTargetBody::VelocityPoleDec, and Isis::BundleTargetBody::VelocityPoleRA.
checkIsValid
void Isis::JigsawSetupDialog::checkIsValid () slot
Referenced by JigsawSetupDialog().
loadSettings()
void Isis::JigsawSetupDialog::loadSettings (const BundleSettingsQsp settings)
Loads the passed bundle settings into the setup dialog.
This is used by JigsawDialog to load its current settings when not using the last (most recent) bundle settings in the project.
Parameters
const BundleSettingsQsp settings Shared pointer to the settings to load up.
outputControlName()
QString Isis::JigsawSetupDialog::outputControlName ()
selectControl()
void Isis::JigsawSetupDialog::selectControl (const QString & controlName)
Selects a control in the control network combo box by trying to find an item with the matching name.
If the name is found in the combo box, the box's index is set to that found control network index. If the name is not found and the box is not empty, the current index is set to 0 (the first item). If the name is not found and the box is empty, the index is set to -1 (see Qt).
Parameters
const QString &controlName The name of the control to try to find in the combo box.
References Isis::FileName::name().
selectedControl()
Control * Isis::JigsawSetupDialog::selectedControl ()
selectedControlName()
QString Isis::JigsawSetupDialog::selectedControlName ()
slotTextChanged
void Isis::JigsawSetupDialog::slotTextChanged (const QString & text) slot
Referenced by JigsawSetupDialog().
treeViewSelectionChanged
void Isis::JigsawSetupDialog::treeViewSelectionChanged (const QItemSelection & selected, const QItemSelection & deselected) slot
References Isis::BundleObservationSolveSettings::aprioriPointingSigmas(), Isis::BundleObservationSolveSettings::aprioriPositionSigmas(), Isis::ProjectItem::child(), Isis::BundleObservationSolveSettings::ckDegree(), Isis::BundleObservationSolveSettings::ckSolveDegree(), Isis::ProjectItem::image(), Isis::BundleObservationSolveSettings::instrumentPointingSolveOption(), Isis::BundleObservationSolveSettings::instrumentPositionSolveOption(), Isis::ProjectItem::isImageList(), Isis::ProjectItemModel::itemFromIndex(), Isis::Null, Isis::Image::observationNumber(), Isis::BundleObservationSolveSettings::solvePolyOverPointing(), Isis::BundleObservationSolveSettings::solvePositionOverHermite(), Isis::BundleObservationSolveSettings::solveTwist(), Isis::BundleObservationSolveSettings::spkDegree(), and Isis::BundleObservationSolveSettings::spkSolveDegree().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/JigsawSetupDialog/JigsawSetupDialog.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/JigsawSetupDialog/JigsawSetupDialog.cpp