Isis Developer Reference: Isis::JigsawRunWidget Class Reference
Isis::JigsawRunWidget Class Reference
This dialog allows the user to select the bundle adjust parameters, run the bundle, and view the results.
#include <JigsawRunWidget.h>
Public Slots
void outputBundleStatus (QString status)
Update the label or text edit area with the most recent status update by appending to list and refreshing.
void errorString (QString error)
Update the label or text edit area with the error message by appending to list and refreshing.
void reportException (QString exception)
Update the label or text edit area with the error message by appending to list and refreshing.
void updateIteration (int iteration)
Update the label or text edit area with the error message by appending to list and refreshing.
void updatePoint (int point)
Update the label or text edit area with the error message by appending to list and refreshing.
void updateStatus (QString status)
Update the label or text edit area with the error message by appending to list and refreshing.
void bundleFinished (BundleSolutionInfo *bundleSolutionInfo)
This method will be called when the bundle is complete.
void notifyThreadFinished ()
Notifies the widget that the bundle thread has finished.
Public Member Functions
JigsawRunWidget (Project *project, QWidget *parent=0)
Constructor.
JigsawRunWidget (Project *project, BundleSettingsQsp bundleSettings, Control *selectedControl, QString outputControlFileName, QWidget *parent=0)
Constructor that takes bundle settings and a selected control.
~JigsawRunWidget ()
Destructor.
void closeEvent (QCloseEvent *event)
This method is called whenever the widget recieves a close request.
Protected Member Functions
void init ()
Constructor delegate.
Protected Attributes
BundleAdjust * m_bundleAdjust
Project * m_project
Control * m_selectedControl
QString m_selectedControlName
QString m_outputControlName
BundleSettingsQsp m_bundleSettings
Detailed Description
This dialog allows the user to select the bundle adjust parameters, run the bundle, and view the results.
Author
2014-??-?? Ken Edmundson
Constructor & Destructor Documentation
JigsawRunWidget() [1/2]
Isis::JigsawRunWidget::JigsawRunWidget (Project * project, QWidget * parent = 0) explicit
Constructor.
Creates a widget for running a jigsaw (bundle adjustment) and changing the solve settings.
Parameters
Project *project Pointer to the project this widget belongs to.
QWidget *parent Pointer to parent widget.
References init(), m_project, and m_selectedControl.
JigsawRunWidget() [2/2]
Isis::JigsawRunWidget::JigsawRunWidget (Project * project, BundleSettingsQsp bundleSettings, Control * selectedControl, QString outputControlFileName, QWidget * parent = 0) explicit
Constructor that takes bundle settings and a selected control.
Creates a widget after the jigsaw solve settings have been set up and a control has been selected.
Parameters
Project *project Pointer to the project this widget belongs to.
BundleSettingsQsp bundleSettings Settings to give to this widget to use for a jigsaw.
Control *selectedControl Pointer to the selected control to adjust.
QWidget *parent Pointer to the parent widget.
References Isis::Control::fileName(), init(), m_bundleSettings, m_outputControlName, m_project, m_selectedControl, m_selectedControlName, and Isis::FileName::name().
~JigsawRunWidget()
Isis::JigsawRunWidget::~JigsawRunWidget ()
Destructor.
References m_bundleAdjust.
Member Function Documentation
bundleFinished
void Isis::JigsawRunWidget::bundleFinished (BundleSolutionInfo * bundleSolutionInfo) slot
This method will be called when the bundle is complete.
This method will only be used when the bundle is threaded. It can be used when the bundle is not threaded but we don't need it because we have solveCholeskyBR().
Parameters
bundleSolutionInfo The results of the bundle run.
References Isis::iTime::CurrentLocalTime(), and Isis::BundleSolutionInfo::setRunTime().
closeEvent()
void Isis::JigsawRunWidget::closeEvent (QCloseEvent * event)
This method is called whenever the widget recieves a close request.
If a bundle is running, the user will be asked if they want to abort the bundle. In this case, the bundle thread must be scheduled to delete when it has finished aborting. Otherwise, the event will accept.
Parameters
event The close event being handled.
References Isis::BundleAdjust::abortBundle(), and m_bundleAdjust.
errorString
void Isis::JigsawRunWidget::errorString (QString error) slot
Update the label or text edit area with the error message by appending to list and refreshing.
Parameters
error Error status of bundle.
init()
void Isis::JigsawRunWidget::init () protected
Constructor delegate.
Delegate method that helps the constructors. This is used to reduce repeated code.
References Isis::Project::bundleSolutionInfo(), m_bundleAdjust, and m_project.
Referenced by JigsawRunWidget().
notifyThreadFinished
void Isis::JigsawRunWidget::notifyThreadFinished () slot
Notifies the widget that the bundle thread has finished.
This slot is used to notify the widget that the bundle has finished. The bundle thread finishes when the bundle adjust finishes (either successfully or unsuccessfully, or if the user aborts the run).
References Isis::BundleSolutionInfo::bundleResults(), Isis::BundleAdjust::isAborted(), m_bundleAdjust, m_bundleSettings, Isis::BundleResults::sigmaCoord1StatisticsRms(), Isis::BundleResults::sigmaCoord2StatisticsRms(), and Isis::BundleResults::sigmaCoord3StatisticsRms().
outputBundleStatus
void Isis::JigsawRunWidget::outputBundleStatus (QString status) slot
Update the label or text edit area with the most recent status update by appending to list and refreshing.
Parameters
status Current status of bundle.
reportException
void Isis::JigsawRunWidget::reportException (QString exception) slot
Update the label or text edit area with the error message by appending to list and refreshing.
Parameters
error Error status of bundle.
updateIteration
void Isis::JigsawRunWidget::updateIteration (int iteration) slot
Update the label or text edit area with the error message by appending to list and refreshing.
Parameters
error Error status of bundle.
updatePoint
void Isis::JigsawRunWidget::updatePoint (int point) slot
Update the label or text edit area with the error message by appending to list and refreshing.
Parameters
error Error status of bundle.
updateStatus
void Isis::JigsawRunWidget::updateStatus (QString status) slot
Update the label or text edit area with the error message by appending to list and refreshing.
Parameters
error Error status of bundle.
Member Data Documentation
m_bundleAdjust
BundleAdjust* Isis::JigsawRunWidget::m_bundleAdjust protected
Referenced by closeEvent(), init(), notifyThreadFinished(), and ~JigsawRunWidget().
m_bundleSettings
BundleSettingsQsp Isis::JigsawRunWidget::m_bundleSettings protected
Referenced by JigsawRunWidget(), and notifyThreadFinished().
m_outputControlName
QString Isis::JigsawRunWidget::m_outputControlName protected
Referenced by JigsawRunWidget().
m_project
Project* Isis::JigsawRunWidget::m_project protected
Referenced by init(), and JigsawRunWidget().
m_selectedControl
Control* Isis::JigsawRunWidget::m_selectedControl protected
Referenced by JigsawRunWidget().
m_selectedControlName
QString Isis::JigsawRunWidget::m_selectedControlName protected
Referenced by JigsawRunWidget().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/JigsawRunWidget/JigsawRunWidget.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/JigsawRunWidget/JigsawRunWidget.cpp