Isis Developer Reference: Isis::AbstractLeafItem Class Reference
Isis::AbstractLeafItem Class Reference abstract
Base class for leaf items in the tree.
#include <AbstractLeafItem.h>
Public Types
enum InternalPointerType { None , Point , Measure , ImageAndNet }
Public Member Functions
AbstractLeafItem (AbstractTreeItem *parent=0)
virtual ~AbstractLeafItem ()
virtual AbstractTreeItem * childAt (int row) const
virtual QList< AbstractTreeItem * > getChildren () const
virtual int indexOf (AbstractTreeItem *child) const
virtual int childCount () const
virtual void addChild (AbstractTreeItem *child)
virtual AbstractTreeItem * getFirstVisibleChild () const
virtual AbstractTreeItem * getLastVisibleChild () const
virtual void setFirstVisibleChild (AbstractTreeItem *)
virtual void setLastVisibleChild (AbstractTreeItem *)
AbstractTreeItem * parent () const
void setParent (AbstractTreeItem *newParent)
int row () const
virtual QVariant getData () const =0
virtual QVariant getData (QString columnTitle) const =0
virtual void setData (QString const &columnTitle, QString const &newData)=0
virtual bool isDataEditable (QString columnTitle) const =0
virtual void deleteSource ()=0
virtual InternalPointerType getPointerType () const =0
virtual void * getPointer () const =0
virtual QString getFormattedData () const
virtual QString getFormattedData (QString columnTitle) const
virtual bool hasMeasure (ControlMeasure *) const
virtual bool hasImage (QString imageSerial) const
virtual bool hasPoint (ControlPoint *) const
virtual AbstractTreeItem * getNextVisiblePeer () const
virtual void setNextVisiblePeer (AbstractTreeItem *next)
virtual void setExpanded (bool newState)
virtual bool isExpanded () const
virtual void setSelected (bool newState)
virtual void setSelectable (bool newSelectable)
virtual bool isSelected () const
virtual bool isSelectable () const
virtual void setVisible (bool newState)
virtual bool isVisible () const
virtual int getDataWidth () const
virtual int getDepth () const
virtual void setLastVisibleFilteredItem (AbstractTreeItem *item)
virtual const AbstractTreeItem * getLastVisibleFilteredItem () const
Protected Slots
virtual void sourceDeleted ()=0
Protected Member Functions
virtual void calcDataWidth (int avgCharWidth)
Static Protected Member Functions
static double catchNull (QString)
static QString catchNull (QVariant)
Detailed Description
Base class for leaf items in the tree.
This class represents a leaf item in the tree.
Author
????-??-?? Eric Hyer
Member Enumeration Documentation
InternalPointerType
enum Isis::AbstractTreeItem::InternalPointerType inherited
Enumerator
None
Point
Measure
ImageAndNet
Constructor & Destructor Documentation
AbstractLeafItem()
Isis::AbstractLeafItem::AbstractLeafItem (AbstractTreeItem * parent = 0)
~AbstractLeafItem()
Isis::AbstractLeafItem::~AbstractLeafItem () virtual
Member Function Documentation
addChild()
void Isis::AbstractLeafItem::addChild (AbstractTreeItem * child) virtual
Implements Isis::AbstractTreeItem.
References _FILEINFO_, and Isis::IException::Programmer.
calcDataWidth()
void Isis::AbstractTreeItem::calcDataWidth (int avgCharWidth) protected virtual inherited
References _FILEINFO_, Isis::AbstractTreeItem::getFormattedData(), and Isis::IException::Programmer.
Referenced by Isis::AbstractImageItem::AbstractImageItem(), Isis::AbstractMeasureItem::AbstractMeasureItem(), Isis::AbstractPointItem::AbstractPointItem(), and Isis::BusyLeafItem::BusyLeafItem().
catchNull() [1/2]
double Isis::AbstractTreeItem::catchNull (QString str) static protected inherited
References Isis::Null.
Referenced by Isis::AbstractTreeItem::getFormattedData(), Isis::AbstractMeasureItem::setData(), and Isis::AbstractPointItem::setData().
catchNull() [2/2]
QString Isis::AbstractTreeItem::catchNull (QVariant data) static protected inherited
References Isis::Double, and Isis::Null.
childAt()
AbstractTreeItem * Isis::AbstractLeafItem::childAt (int row) const virtual
Implements Isis::AbstractTreeItem.
References _FILEINFO_, and Isis::IException::Programmer.
childCount()
int Isis::AbstractLeafItem::childCount () const virtual
Implements Isis::AbstractTreeItem.
deleteSource()
virtual void Isis::AbstractTreeItem::deleteSource () pure virtual inherited
Implemented in Isis::AbstractPointItem, Isis::AbstractNullDataItem, Isis::AbstractMeasureItem, and Isis::AbstractImageItem.
getChildren()
QList< AbstractTreeItem * > Isis::AbstractLeafItem::getChildren () const virtual
Implements Isis::AbstractTreeItem.
References _FILEINFO_, and Isis::IException::Programmer.
getData() [1/2]
virtual QVariant Isis::AbstractTreeItem::getData () const pure virtual inherited
Implemented in Isis::BusyLeafItem, Isis::AbstractPointItem, Isis::AbstractNullDataItem, Isis::AbstractMeasureItem, and Isis::AbstractImageItem.
Referenced by Isis::AbstractTreeItem::getFormattedData().
getData() [2/2]
virtual QVariant Isis::AbstractTreeItem::getData (QString columnTitle) const pure virtual inherited
Implemented in Isis::AbstractPointItem, Isis::AbstractNullDataItem, Isis::AbstractMeasureItem, and Isis::AbstractImageItem.
getDataWidth()
int Isis::AbstractTreeItem::getDataWidth () const virtual inherited
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by Isis::AbstractTreeModel::getVisibleSize().
getDepth()
int Isis::AbstractTreeItem::getDepth () const virtual inherited
References Isis::AbstractTreeItem::parent().
Referenced by Isis::AbstractTreeModel::getVisibleSize().
getFirstVisibleChild()
AbstractTreeItem * Isis::AbstractLeafItem::getFirstVisibleChild () const virtual
Implements Isis::AbstractTreeItem.
getFormattedData() [1/2]
QString Isis::AbstractTreeItem::getFormattedData () const virtual inherited
References Isis::AbstractTreeItem::catchNull(), and Isis::AbstractTreeItem::getData().
Referenced by Isis::AbstractTreeItem::calcDataWidth(), Isis::AbstractMeasureItem::deleteSource(), Isis::AbstractPointItem::deleteSource(), Isis::MeasureTableModel::getMeasureWarningMessage(), Isis::PointTableModel::getPointWarningMessage(), Isis::MeasureTableDelegate::readData(), and Isis::PointTableDelegate::readData().
getFormattedData() [2/2]
QString Isis::AbstractTreeItem::getFormattedData (QString columnTitle) const virtual inherited
References Isis::AbstractTreeItem::catchNull(), and Isis::AbstractTreeItem::getData().
getLastVisibleChild()
AbstractTreeItem * Isis::AbstractLeafItem::getLastVisibleChild () const virtual
Implements Isis::AbstractTreeItem.
getLastVisibleFilteredItem()
const AbstractTreeItem * Isis::AbstractTreeItem::getLastVisibleFilteredItem () const virtual inherited
Reimplemented in Isis::RootItem.
getNextVisiblePeer()
AbstractTreeItem * Isis::AbstractTreeItem::getNextVisiblePeer () const virtual inherited
Referenced by Isis::AbstractTreeModel::getVisibleTopLevelItemCount().
getPointer()
virtual void* Isis::AbstractTreeItem::getPointer () const pure virtual inherited
Implemented in Isis::AbstractPointItem, Isis::AbstractNullDataItem, Isis::AbstractMeasureItem, and Isis::AbstractImageItem.
Referenced by Isis::PointTableModel::getPointWarningMessage(), Isis::MeasureTableDelegate::readData(), and Isis::PointTableDelegate::readData().
getPointerType()
virtual InternalPointerType Isis::AbstractTreeItem::getPointerType () const pure virtual inherited
Implemented in Isis::AbstractPointItem, Isis::AbstractNullDataItem, Isis::AbstractMeasureItem, and Isis::AbstractImageItem.
Referenced by Isis::AbstractTableModel::handleTreeSelectionChanged(), Isis::PointTableModel::handleTreeSelectionChanged(), Isis::TableViewContent::mouseMoveEvent(), Isis::TableViewContent::mousePressEvent(), and Isis::TreeViewContent::mousePressEvent().
hasImage()
bool Isis::AbstractTreeItem::hasImage (QString imageSerial) const virtual inherited
Reimplemented in Isis::AbstractImageItem.
References Isis::AbstractTreeItem::childAt(), Isis::AbstractTreeItem::childCount(), and Isis::AbstractTreeItem::hasImage().
Referenced by Isis::AbstractImageItem::hasImage(), and Isis::AbstractTreeItem::hasImage().
hasMeasure()
bool Isis::AbstractTreeItem::hasMeasure (ControlMeasure * measure) const virtual inherited
Reimplemented in Isis::AbstractMeasureItem.
References Isis::AbstractTreeItem::childAt(), Isis::AbstractTreeItem::childCount(), and Isis::AbstractTreeItem::hasMeasure().
Referenced by Isis::AbstractTreeItem::hasMeasure().
hasPoint()
bool Isis::AbstractTreeItem::hasPoint (ControlPoint * point) const virtual inherited
Reimplemented in Isis::AbstractPointItem.
References Isis::AbstractTreeItem::childAt(), Isis::AbstractTreeItem::childCount(), and Isis::AbstractTreeItem::hasPoint().
Referenced by Isis::AbstractTreeItem::hasPoint().
indexOf()
int Isis::AbstractLeafItem::indexOf (AbstractTreeItem * child) const virtual
Implements Isis::AbstractTreeItem.
References _FILEINFO_, and Isis::IException::Programmer.
isDataEditable()
virtual bool Isis::AbstractTreeItem::isDataEditable (QString columnTitle) const pure virtual inherited
Implemented in Isis::AbstractPointItem, Isis::AbstractNullDataItem, Isis::AbstractMeasureItem, and Isis::AbstractImageItem.
isExpanded()
bool Isis::AbstractTreeItem::isExpanded () const virtual inherited
Referenced by Isis::TreeViewContent::mouseDoubleClickEvent(), and Isis::TreeViewContent::mouseReleaseEvent().
isSelectable()
bool Isis::AbstractTreeItem::isSelectable () const virtual inherited
Reimplemented in Isis::BusyLeafItem.
Referenced by Isis::TreeViewContent::mouseMoveEvent(), and Isis::TreeViewContent::mousePressEvent().
isSelected()
bool Isis::AbstractTreeItem::isSelected () const virtual inherited
Referenced by Isis::AbstractTreeModel::getSelectedItems(), Isis::TableViewContent::mousePressEvent(), and Isis::TreeViewContent::mousePressEvent().
isVisible()
bool Isis::AbstractTreeItem::isVisible () const virtual inherited
parent()
AbstractTreeItem * Isis::AbstractTreeItem::parent () const inherited
Referenced by Isis::AbstractTreeItem::getDepth(), Isis::AbstractTreeModel::getItems(), Isis::PointTableModel::handleTreeSelectionChanged(), and Isis::TableViewContent::mousePressEvent().
row()
int Isis::AbstractTreeItem::row () const inherited
References Isis::AbstractTreeItem::indexOf().
Referenced by Isis::AbstractParentItem::childAt().
setData()
virtual void Isis::AbstractTreeItem::setData (QString const & columnTitle, QString const & newData) pure virtual inherited
Implemented in Isis::AbstractPointItem, Isis::AbstractNullDataItem, Isis::AbstractMeasureItem, and Isis::AbstractImageItem.
Referenced by Isis::MeasureTableDelegate::saveData(), and Isis::PointTableDelegate::saveData().
setExpanded()
void Isis::AbstractTreeItem::setExpanded (bool newState) virtual inherited
Referenced by Isis::TreeViewContent::mouseDoubleClickEvent(), Isis::TreeViewContent::mouseReleaseEvent(), and Isis::RootItem::RootItem().
setFirstVisibleChild()
void Isis::AbstractLeafItem::setFirstVisibleChild (AbstractTreeItem *) virtual
Implements Isis::AbstractTreeItem.
References _FILEINFO_, and Isis::IException::Programmer.
setLastVisibleChild()
void Isis::AbstractLeafItem::setLastVisibleChild (AbstractTreeItem *) virtual
Implements Isis::AbstractTreeItem.
References _FILEINFO_, and Isis::IException::Programmer.
setLastVisibleFilteredItem()
void Isis::AbstractTreeItem::setLastVisibleFilteredItem (AbstractTreeItem * item) virtual inherited
Reimplemented in Isis::RootItem.
References _FILEINFO_, and Isis::IException::Programmer.
setNextVisiblePeer()
void Isis::AbstractTreeItem::setNextVisiblePeer (AbstractTreeItem * next) virtual inherited
setParent()
void Isis::AbstractTreeItem::setParent (AbstractTreeItem * newParent) inherited
Referenced by Isis::AbstractParentItem::addChild().
setSelectable()
void Isis::AbstractTreeItem::setSelectable (bool newSelectable) virtual inherited
setSelected()
void Isis::AbstractTreeItem::setSelected (bool newState) virtual inherited
Referenced by Isis::TableViewContent::mouseMoveEvent(), Isis::TableViewContent::mousePressEvent(), and Isis::TreeViewContent::mousePressEvent().
setVisible()
void Isis::AbstractTreeItem::setVisible (bool newState) virtual inherited
sourceDeleted
virtual void Isis::AbstractTreeItem::sourceDeleted () protected pure virtual slot inherited
Implemented in Isis::AbstractPointItem, Isis::AbstractNullDataItem, Isis::AbstractMeasureItem, and Isis::AbstractImageItem.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/AbstractLeafItem.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/AbstractLeafItem.cpp