Isis Developer Reference: Isis::ShapeReader Class Reference
Isis::ShapeReader Class Reference
#include <ShapeReader.h>
Public Slots
void read (PvlObject shapesObj)
void read (QStringList shapeFileNames)
Handle opening cubes by filename.
void setSafeFileOpen (bool safeFileOpen)
Signals
void shapesReady (ShapeList shapes)
Public Member Functions
ShapeReader (QMutex *cameraMutex, bool requireFootprints=false, QObject *parent=NULL)
MosaicWidget constructor.
virtual ~ShapeReader ()
Free the allocated memory by this object.
QList< QAction * > actions (ShapeDisplayProperties::Property relevantDispProperties)
QProgressBar * progress ()
Detailed Description
Author
2016-07-25 Tracie Sucharski
Constructor & Destructor Documentation
ShapeReader()
Isis::ShapeReader::ShapeReader (QMutex * cameraMutex, bool requireFootprints = false, QObject * parent = NULL)
MosaicWidget constructor.
MosaicWidget is derived from QSplitter, the left side of the splitter is a QTreeWidget and the right side of the splitter is a QGraphicsView.
Parameters
parent
References shapesReady().
~ShapeReader()
Isis::ShapeReader::~ShapeReader () virtual
Free the allocated memory by this object.
Member Function Documentation
actions()
QList< QAction * > Isis::ShapeReader::actions (ShapeDisplayProperties::Property relevantDispProperties)
References setSafeFileOpen().
progress()
QProgressBar * Isis::ShapeReader::progress ()
read [1/2]
void Isis::ShapeReader::read (PvlObject shapesObj) slot
References Isis::PvlObject::beginObject(), and Isis::PvlObject::endObject().
Referenced by read().
read [2/2]
void Isis::ShapeReader::read (QStringList shapeFileNames) slot
Handle opening cubes by filename.
References read().
setSafeFileOpen
void Isis::ShapeReader::setSafeFileOpen (bool safeFileOpen) slot
Referenced by actions().
shapesReady
void Isis::ShapeReader::shapesReady (ShapeList shapes) signal
Referenced by ShapeReader().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ShapeReader/ShapeReader.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ShapeReader/ShapeReader.cpp