Isis Developer Reference: Isis::TargetBody Class Reference
Isis::TargetBody Class Reference
Container class for TargetBody.
#include <TargetBody.h>
Public Member Functions
TargetBody (Target *target, QObject *parent=0)
The first constructor for this class.
~TargetBody ()
The second constructor for this class.
bool operator== (const TargetBody &src) const
Compares two Target Body objects to see if they are equal.
TargetBodyDisplayProperties * displayProperties ()
Gets TargetBodyDisplayProperties.
const TargetBodyDisplayProperties * displayProperties () const
TargetBody::displayProperties.
QString id () const
Get a unique, identifying string associated with this TargetBody object.
QString targetName ()
Returns the value stored at TargetName in the original pvl label.
int frameType ()
Returns the frame type.
std::vector< Angle > poleRaCoefs ()
TargetBody::poleRaCoefs.
std::vector< Angle > poleDecCoefs ()
Returns coefficients of a quadratic polynomial fitting pole dec.
std::vector< Angle > pmCoefs ()
Returns coefficients of a quadratic polynomial fitting pole pm.
std::vector< double > poleRaNutPrecCoefs ()
Returns coefficients of pole right ascension nut/prec terms.
std::vector< double > poleDecNutPrecCoefs ()
TargetBody::poleDecNutPrecCoefs.
std::vector< double > pmNutPrecCoefs ()
Returns coefficients of the prime meridian nut/prec terms.
std::vector< Angle > sysNutPrecConstants ()
Returns constants of planetary system nut/prec periods.
std::vector< Angle > sysNutPrecCoefs ()
Returns Linear terms of planetary system nut/prec periods.
SpiceInt naifBodyCode () const
This returns the NAIF body code of the target.
SpiceInt naifPlanetSystemCode () const
This returns the NAIF body code of the target's planet system.
QString naifPlanetSystemName () const
This returns the body name of the target's planet system.
Distance radiusA () const
Returns "a" radius.
Distance radiusB () const
Returns "b" radius.
Distance radiusC () const
Returns the "c" radius.
Distance meanRadius () const
Returns the mean radius.
Distance sigmaRadiusA () const
Returns "a" radius sigma.
Distance sigmaRadiusB () const
Returns "b" radius sigma.
Distance sigmaRadiusC () const
Returns the "c" radius sigma.
Distance sigmaMeanRadius () const
Returns the mean radius sigma.
Detailed Description
Container class for TargetBody.
This class represents a target body in a project-based GUI interface. It encapsulates ideas about a target such as it's display name, how it should be viewed, where it is on disk, etc.
Author
2015-06-08 Ken Edmundson
Constructor & Destructor Documentation
TargetBody()
Isis::TargetBody::TargetBody (Target * target, QObject * parent = 0)
The first constructor for this class.
Parameters
target A traditional: Isis::Target object.
parent A pointer to the object instantiating this object.
References Isis::Target::frameType(), Isis::Distance::Kilometers, Isis::Target::naifBodyCode(), Isis::Target::naifPlanetSystemCode(), Isis::Target::name(), Isis::Target::pmCoefs(), Isis::Target::pmNutPrecCoefs(), Isis::Target::poleDecCoefs(), Isis::Target::poleDecNutPrecCoefs(), Isis::Target::poleRaCoefs(), Isis::Target::poleRaNutPrecCoefs(), Isis::Target::radii(), Isis::Target::sysNutPrecCoefs(), Isis::Target::sysNutPrecConstants(), and Isis::Target::systemName().
~TargetBody()
Isis::TargetBody::~TargetBody ()
The second constructor for this class.
Parameters
bundleTargetBody A QSharedPointer to a BundleTarget object.
parent A pointer to the object instantiating this object.
The destructor
Member Function Documentation
displayProperties() [1/2]
TargetBodyDisplayProperties * Isis::TargetBody::displayProperties ()
Gets TargetBodyDisplayProperties.
Returns
TargetBodyDisplayProperties * A pointer to the display properties for the TargetBody.
Referenced by Isis::TargetInfoWidget::TargetInfoWidget().
displayProperties() [2/2]
const TargetBodyDisplayProperties * Isis::TargetBody::displayProperties () const
TargetBody::displayProperties.
Returns
TargetBodyDisplayProperties * A pointer to the display properties for the TargetBody.
frameType()
int Isis::TargetBody::frameType ()
Returns the frame type.
Returns
Referenced by Isis::TargetInfoWidget::TargetInfoWidget().
id()
QString Isis::TargetBody::id () const
Get a unique, identifying string associated with this TargetBody object.
Returns
A unique ID for this TargetBody object.
meanRadius()
Distance Isis::TargetBody::meanRadius () const
Returns the mean radius.
Returns
Distance value of body mean radius.
Referenced by Isis::TargetInfoWidget::TargetInfoWidget().
naifBodyCode()
SpiceInt Isis::TargetBody::naifBodyCode () const
This returns the NAIF body code of the target.
Returns
SpiceInt NAIF body code
Referenced by operator==().
naifPlanetSystemCode()
SpiceInt Isis::TargetBody::naifPlanetSystemCode () const
This returns the NAIF body code of the target's planet system.
Returns
SpiceInt NAIF body code of target's planet system.
naifPlanetSystemName()
QString Isis::TargetBody::naifPlanetSystemName () const
This returns the body name of the target's planet system.
Returns
QString The body name of target's planet system.
Referenced by Isis::TargetInfoWidget::TargetInfoWidget().
operator==()
bool Isis::TargetBody::operator== (const TargetBody & src) const
Compares two Target Body objects to see if they are equal.
Parameters
src TargetBody object to compare against
Returns
bool Returns true if the objects are equal, false if not.
References naifBodyCode(), radiusA(), radiusB(), and radiusC().
pmCoefs()
std::vector< Angle > Isis::TargetBody::pmCoefs ()
Returns coefficients of a quadratic polynomial fitting pole pm.
Returns
std::vector<Angle>
pmNutPrecCoefs()
std::vector< double > Isis::TargetBody::pmNutPrecCoefs ()
Returns coefficients of the prime meridian nut/prec terms.
Returns
std::vector<double>
poleDecCoefs()
std::vector< Angle > Isis::TargetBody::poleDecCoefs ()
Returns coefficients of a quadratic polynomial fitting pole dec.
Returns
std::vector<Angle>
poleDecNutPrecCoefs()
std::vector< double > Isis::TargetBody::poleDecNutPrecCoefs ()
TargetBody::poleDecNutPrecCoefs.
Returns
std::vector<double>
poleRaCoefs()
std::vector< Angle > Isis::TargetBody::poleRaCoefs ()
TargetBody::poleRaCoefs.
Returns
std::vector<Angle>
poleRaNutPrecCoefs()
std::vector< double > Isis::TargetBody::poleRaNutPrecCoefs ()
Returns coefficients of pole right ascension nut/prec terms.
Returns
std::vector<double>
radiusA()
Distance Isis::TargetBody::radiusA () const
Returns "a" radius.
Returns
Distance The value of body radius "a"
Referenced by operator==(), and Isis::TargetInfoWidget::TargetInfoWidget().
radiusB()
Distance Isis::TargetBody::radiusB () const
Returns "b" radius.
Returns
Distance value of body radius "b".
Referenced by operator==(), and Isis::TargetInfoWidget::TargetInfoWidget().
radiusC()
Distance Isis::TargetBody::radiusC () const
Returns the "c" radius.
Returns
Distance value of body radius "c".
Referenced by operator==(), and Isis::TargetInfoWidget::TargetInfoWidget().
sigmaMeanRadius()
Distance Isis::TargetBody::sigmaMeanRadius () const
Returns the mean radius sigma.
Returns
Distance value of body mean radius
sigmaRadiusA()
Distance Isis::TargetBody::sigmaRadiusA () const
Returns "a" radius sigma.
Returns
Distance value of body radius "a" sigma
sigmaRadiusB()
Distance Isis::TargetBody::sigmaRadiusB () const
Returns "b" radius sigma.
Returns
Distance The value of body radius "b" sigma.
sigmaRadiusC()
Distance Isis::TargetBody::sigmaRadiusC () const
Returns the "c" radius sigma.
Returns
Distance value of body radius "c" sigma
sysNutPrecCoefs()
std::vector< Angle > Isis::TargetBody::sysNutPrecCoefs ()
Returns Linear terms of planetary system nut/prec periods.
Returns
std::vector<Angle>
sysNutPrecConstants()
std::vector< Angle > Isis::TargetBody::sysNutPrecConstants ()
Returns constants of planetary system nut/prec periods.
Returns
std::vector<Angle>
targetName()
QString Isis::TargetBody::targetName ()
Returns the value stored at TargetName in the original pvl label.
Returns
QString Returns m_targetName
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/TargetBody/TargetBody.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/TargetBody/TargetBody.cpp