Isis Developer Reference: Isis::WorldMapper Class Reference
Isis::WorldMapper Class Reference abstract
Map Projection
Create a mapping between a projection and other coordinate system.
#include <WorldMapper.h>
Public Member Functions
WorldMapper ()
Constructs an empty WorldMapper object.
virtual ~WorldMapper ()
Destroys the WorldMapper object.
virtual double ProjectionX (const double worldX) const =0
This pure virtual method will return a projection X coordinate in meters given a world X coordinate.
virtual double ProjectionY (const double worldY) const =0
This pure virtual method will return a projection Y coordinate in meters given a world Y coordinate.
virtual double WorldX (const double projectionX) const =0
This pure virtual method will return a world X coordinate given a projection Y coordinate in meters.
virtual double WorldY (const double projectionY) const =0
This pure virtual method will return a world Y coordinate given a projection Y coordinate in meters.
virtual double Resolution () const
This virtual method will the resolution of the world system relative to one unit in the projection system.
Detailed Description
Create a mapping between a projection and other coordinate system.
This class can be used to create a mapping between a projection coordinate system and a different coordinate system. Simple examples of this would be a mapping between projection x/y's to cube line/samples or a mapping between projection x/y's and paper x/y's in inches. The class is pure virtual and therefore should never be directly instantiated. Remember the basic premise is to use this class to create a new class which converts coordinates from one system to another (inches to meters and back, meters to pixels and back, etc).
If you would like to see WorldMapper being used in implementation, see the ProjectionFactory class
Author
2003-01-28 Jeff Anderson
Constructor & Destructor Documentation
WorldMapper()
Isis::WorldMapper::WorldMapper () inline
Constructs an empty WorldMapper object.
~WorldMapper()
virtual Isis::WorldMapper::~WorldMapper () inline virtual
Destroys the WorldMapper object.
Member Function Documentation
ProjectionX()
virtual double Isis::WorldMapper::ProjectionX (const double worldX) const pure virtual
This pure virtual method will return a projection X coordinate in meters given a world X coordinate.
For example, the worldX value could be an X in millimeters on a piece of paper. The value returned would be an X in map projection coordinates.
Parameters
worldX An X value in world coordinates.
Returns
double
Implemented in Isis::PFPixelMapper.
Referenced by Isis::Projection::SetWorld(), and Isis::Projection::ToProjectionX().
ProjectionY()
virtual double Isis::WorldMapper::ProjectionY (const double worldY) const pure virtual
This pure virtual method will return a projection Y coordinate in meters given a world Y coordinate.
For example, the worldY value could be an Y in millimeters on a piece of paper. The value returned would be an Y in map projection coordinates.
Parameters
worldY A Y value in world coordinates.
Returns
double
Implemented in Isis::PFPixelMapper.
Referenced by Isis::Projection::SetWorld(), and Isis::Projection::ToProjectionY().
Resolution()
virtual double Isis::WorldMapper::Resolution () const inline virtual
This virtual method will the resolution of the world system relative to one unit in the projection system.
For example, one meter in the projection system could be .001 inches on a piece of paper. Unless this method is overridden it will return 1
Returns
double
Reimplemented in Isis::PFPixelMapper.
Referenced by Isis::Projection::Resolution(), Isis::RingPlaneProjection::Scale(), and Isis::TProjection::Scale().
WorldX()
virtual double Isis::WorldMapper::WorldX (const double projectionX) const pure virtual
This pure virtual method will return a world X coordinate given a projection Y coordinate in meters.
For example, the worldY value could be an Y in millimeters on a piece of paper.
Parameters
projectionX A X value in projection coordinates.
Returns
double
Implemented in Isis::PFPixelMapper.
Referenced by Isis::Projection::ToWorldX(), and Isis::Projection::WorldX().
WorldY()
virtual double Isis::WorldMapper::WorldY (const double projectionY) const pure virtual
This pure virtual method will return a world Y coordinate given a projection Y coordinate in meters.
For example, the worldY value could be an Y in millimeters on a piece of paper.
Parameters
projectionY A Y value in projection coordinates.
Returns
double
Implemented in Isis::PFPixelMapper.
Referenced by Isis::Projection::ToWorldY(), and Isis::Projection::WorldY().
The documentation for this class was generated from the following file:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/WorldMapper/WorldMapper.h