Isis Developer Reference: Isis::BundleResults Class Reference
Isis::BundleResults Class Reference
A container class for statistical results from a BundleAdjust solution.
#include <BundleResults.h>
Public Member Functions
BundleResults (QObject *parent=0)
Constructs a BundleResults object.
BundleResults (QXmlStreamReader *xmlReader, QObject *parent=0)
Construct this BundleResults object from XML.
void readBundleResults (QXmlStreamReader *xmlReader)
void readCorrelationMatrix (QXmlStreamReader *xmlReader)
void readGenStatsValues (QXmlStreamReader *xmlReader)
void readRms (QXmlStreamReader *xmlReader)
void readImageResidualsLists (QXmlStreamReader *xmlReader)
void readSigmasLists (QXmlStreamReader *xmlReader)
void readStatsToList (QList< Statistics > &list, QXmlStreamReader *xmlReader)
void readStatsToVector (QVector< Statistics > &vec, QXmlStreamReader *xmlReader)
void readMinMaxSigmas (QXmlStreamReader *xmlReader)
void readSigma (Distance &dist, QString &pointId, QXmlStreamReader *xmlReader)
void readMaxLikelihoodEstimation (QXmlStreamReader *xmlReader)
BundleResults (const BundleResults &src)
Copy constructor for BundleResults.
~BundleResults ()
Destroys this BundleResults object.
BundleResults & operator= (const BundleResults &src)
Assignment operator for BundleResults.
void initialize ()
Initializes the BundleResults to a default state where all numeric members are set to 0 or another default value, all QString members are set to empty, all QVectors and QLists are cleared, and all other members are set to NULL.
void resizeSigmaStatisticsVectors (int numberImages)
Resizes all image sigma vectors.
void setRmsImageResidualLists (QList< Statistics > rmsImageLineResiduals, QList< Statistics > rmsImageSampleResiduals, QList< Statistics > rmsImageResiduals)
Sets the root mean square image residual Statistics lists.
void setRmsImageResidualLists (QVector< Statistics > rmsImageLineResiduals, QVector< Statistics > rmsImageSampleResiduals, QVector< Statistics > rmsImageResiduals)
void setRmsLidarImageResidualLists (QList< Statistics > rmsLidarImageLineResiduals, QList< Statistics > rmsLidarImageSampleResiduals, QList< Statistics > rmsLidarImageResiduals)
Sets the root mean square lidar image residual Statistics lists.
void setSigmaCoord1Range (Distance minCoord1Dist, Distance maxCoord1Dist, QString minCoord1PointId, QString maxCoord1PointId)
Sets the min and max sigma distances and point ids for coordinate 1.
void setSigmaCoord2Range (Distance minCoord2Dist, Distance maxCoord2Dist, QString minCoord2PointId, QString maxCoord2PointId)
Sets the min and max sigma distances and point ids for coordinate 2.
void setSigmaCoord3Range (Distance minCoord3Dist, Distance maxCoord3Dist, QString minCoord3PointId, QString maxCoord3PointId)
Sets the min and max sigma distances and point ids for coordinate 3.
void setRmsFromSigmaStatistics (double rmsFromSigmaCoord1Stats, double rmsFromSigmaCoord2Stats, double rmsFromSigmaCoord3Stats)
Sets the root mean square values of the adjusted sigmas for all three coordinates.
void maximumLikelihoodSetUp (QList< QPair< MaximumLikelihoodWFunctions::Model, double > > modelsWithQuantiles)
This method steps up the maximum likelihood estimation solution.
void printMaximumLikelihoodTierInformation ()
Prints out information about which tier the solution is in and the status of the residuals.
void initializeResidualsProbabilityDistribution (unsigned int nodes=20)
Initializes or resets the cumulative probability distribution of residuals used for reporting.
void initializeProbabilityDistribution (unsigned int nodes=20)
Initializes or resets the cumulative probability distribution of |R^2 residuals|.
void addResidualsProbabilityDistributionObservation (double obsValue)
Adds an observation to the cumulative probability distribution of residuals used for reporting.
void addProbabilityDistributionObservation (double obsValue)
Adds an observation to the cumulative probability distribution of |R^2 residuals|.
void addProbabilityDistributionObservation (double obsValue, bool residuals)
void incrementMaximumLikelihoodModelIndex ()
Increases the value that indicates which stage the maximum likelihood adjustment is currently on.
void incrementFixedPoints ()
Increase the number of 'fixed' (ground) points.
int numberFixedPoints () const
Returns the number of 'fixed' (ground) points.
void incrementHeldImages ()
Increases the number of 'held' images.
int numberHeldImages () const
Returns the number of 'held' images.
void incrementIgnoredPoints ()
Increase the number of ignored points.
int numberIgnoredPoints () const
Returns the number of ignored points.
void setRejectionLimit (double rejectionLimit)
Sets the rejection limit.
void setRmsXYResiduals (double rx, double ry, double rxy)
Sets the root mean square of the x and y residuals.
void setNumberRejectedObservations (int numberObservations)
Sets the number of rejected observations.
void setNumberImageObservations (int numberObservations)
Sets the number of photogrammetric image observations.
void setNumberLidarImageObservations (int numberLidarObservations)
Sets the number of lidar observations.
void setNumberObservations (int numberObservations)
Sets the number of observations.
void setNumberImageParameters (int numberParameters)
Sets the number of image parameters.
void setNumberConstrainedPointParameters (int numberParameters)
Set number of contrained point parameters.
void setNumberConstrainedLidarPointParameters (int numberParameters)
Set number of contrained point parameters.
void resetNumberConstrainedPointParameters ()
Resets the number of contrained point parameters to 0.
void incrementNumberConstrainedPointParameters (int incrementAmount)
Increase the number of contrained point parameters.
void resetNumberConstrainedImageParameters ()
Resets the number of constrained image parameters to 0.
void incrementNumberConstrainedImageParameters (int incrementAmount)
Increase the number of constrained image parameters.
void resetNumberConstrainedTargetParameters ()
Resets the number of constrained target parameters to 0.
void incrementNumberConstrainedTargetParameters (int incrementAmount)
Increases the number of constrained target parameters.
void setNumberLidarRangeConstraints (int numberLidarRangeConstraints)
Sets the total number of lidar range constraints.
void setNumberUnknownParameters (int numberParameters)
Sets the total number of parameters to solve for.
void computeDegreesOfFreedom ()
Computes the degrees of freedom of the bundle adjustment and stores it internally.
void computeSigma0 (double dvtpv, BundleSettings::ConvergenceCriteria criteria)
Computes the sigma0 and stores it internally.
void setDegreesOfFreedom (double degreesOfFreedom)
Sets the degrees of freedom.
void setSigma0 (double sigma0)
Sets the sigma0.
void setElapsedTime (double time)
Sets the elapsed time for the bundle adjustment.
void setElapsedTimeErrorProp (double time)
Sets the elapsed time for error propegation.
void setConverged (bool converged)
Sets if the bundle adjustment converged.
void setBundleControlPoints (QVector< BundleControlPointQsp > controlPoints)
Sets the bundle control point vector.
void setBundleLidarPoints (QVector< BundleLidarControlPointQsp > lidarPoints)
Sets the bundle lidar point vector.
void setOutputControlNet (ControlNetQsp outNet)
Sets the output ControlNet.
void setOutputLidarData (LidarDataQsp outLidarData)
Sets the output LidarData object.
void setIterations (int iterations)
Sets the number of iterations taken by the BundleAdjust.
void setObservations (BundleObservationVector observations)
Sets the vector of BundleObservations.
QList< Statistics > rmsImageSampleResiduals () const
Returns the list of RMS image sample residuals statistics.
QList< Statistics > rmsImageLineResiduals () const
Returns the list of RMS image line residuals statistics.
QList< Statistics > rmsImageResiduals () const
Returns the list of RMS image residuals statistics.
QList< Statistics > rmsLidarImageSampleResiduals () const
Returns the list of RMS image lidar sample residuals statistics.
QList< Statistics > rmsLidarImageLineResiduals () const
Returns the list of RMS image lidar line residuals statistics.
QList< Statistics > rmsLidarImageResiduals () const
Returns the list of RMS image lidar residuals statistics.
QVector< Statistics > rmsImageXSigmas () const
Returns the list of RMS image x sigma statistics.
QVector< Statistics > rmsImageYSigmas () const
Returns the list of RMS image y sigma statistics.
QVector< Statistics > rmsImageZSigmas () const
Returns the list of RMS image z sigma statistics.
QVector< Statistics > rmsImageRASigmas () const
Returns the list of RMS image right ascension sigma statistics.
QVector< Statistics > rmsImageDECSigmas () const
Returns the list of RMS image declination sigma statistics.
QVector< Statistics > rmsImageTWISTSigmas () const
Returns the list of RMS image twist sigma statistics.
SurfacePoint::CoordinateType coordTypeReports ()
Distance minSigmaCoord1Distance () const
Returns the minimum sigma distance for coordinate 1.
Distance maxSigmaCoord1Distance () const
Returns the maximum sigma distance for coordinate 1.
Distance minSigmaCoord2Distance () const
Returns the minimum sigma distance for coordinate 2.
Distance maxSigmaCoord2Distance () const
Returns the maximum sigma distance for coordinate 2.
Distance minSigmaCoord3Distance () const
Returns the minimum sigma distance for coordinate 3.
Distance maxSigmaCoord3Distance () const
Returns the maximum sigma distance for coordinate 3.
QString maxSigmaCoord1PointId () const
Returns the maximum sigma point id for coordinate 1.
QString minSigmaCoord1PointId () const
Returns the minimum sigma point id for coordinate 1.
QString minSigmaCoord2PointId () const
Returns the minimum sigma point id for coordinate 2.
QString maxSigmaCoord2PointId () const
Returns the maximum sigma point id for coordinate 2.
QString minSigmaCoord3PointId () const
Returns the minimum sigma point id for coordinate 3.
QString maxSigmaCoord3PointId () const
Returns the maximum sigma point id for coordinate 3.
double sigmaCoord1StatisticsRms () const
Returns the RMS of the adjusted sigmas for coordinate 1.
double sigmaCoord2StatisticsRms () const
Returns the RMS of the adjusted sigmas for coordinate 2.
double sigmaCoord3StatisticsRms () const
Returns the RMS of the adjusted sigmas for coordinate 3.
double rmsRx () const
Returns the RMS of the x residuals.
double rmsRy () const
Returns the RMS of the y residuals.
double rmsRxy () const
Returns the RMS of the x and y residuals.
double rejectionLimit () const
Returns the rejection limit.
int numberRejectedObservations () const
Returns the number of observation that were rejected.
int numberObservations () const
Returns the number of observations.
int numberImageObservations () const
Returns the number of observations.
int numberLidarImageObservations () const
Returns the number of lidar observations.
int numberImageParameters () const
Returns the total number of image parameters.
int numberConstrainedPointParameters () const
Returns the number of constrained point parameters.
int numberConstrainedImageParameters () const
Returns the number of constrained image parameters.
int numberConstrainedTargetParameters () const
Return the number of constrained target parameters.
int numberLidarRangeConstraintEquations () const
Return the number of lidar range constraint equations.
int numberUnknownParameters () const
Returns the number of unknown parameters.
int degreesOfFreedom () const
Returns the degrees of freedom.
double sigma0 () const
Returns the Sigma0 of the bundle adjustment.
double elapsedTime () const
Returns the elapsed time for the bundle adjustment.
double elapsedTimeErrorProp () const
Returns the elapsed time for error propagation.
bool converged () const
Returns whether or not the bundle adjustment converged.
QVector< BundleControlPointQsp > & bundleControlPoints ()
Returns a reference to the BundleControlPoint vector.
QVector< BundleLidarControlPointQsp > & bundleLidarControlPoints ()
Returns a reference to the BundleLidarControlPoint vector.
ControlNetQsp outputControlNet () const
Returns a shared pointer to the output control network.
LidarDataQsp outputLidarData () const
Returns a shared pointer to the output LidarData object.
int iterations () const
Returns the number of iterations taken by the BundleAdjust.
const BundleObservationVector & observations () const
Returns a reference to the observations used by the BundleAdjust.
int numberMaximumLikelihoodModels () const
Returns how many maximum likelihood models were used in the bundle adjustment.
int maximumLikelihoodModelIndex () const
Returns which step the bundle adjustment is on.
StatCumProbDistDynCalc cumulativeProbabilityDistribution () const
Returns the cumulative probability distribution of the |R^2 residuals|.
StatCumProbDistDynCalc residualsCumulativeProbabilityDistribution () const
Returns the cumulative probability distribution of the residuals used for reporting.
double maximumLikelihoodMedianR2Residuals () const
Returns the median of the |R^2 residuals|.
MaximumLikelihoodWFunctions maximumLikelihoodModelWFunc (int modelIndex) const
Returns the maximum likelihood model at the given index.
double maximumLikelihoodModelQuantile (int modelIndex) const
Returns the quantile of the maximum likelihood model at the given index.
QList< QPair< MaximumLikelihoodWFunctions, double > > maximumLikelihoodModels () const
bool setNumberHeldImages (SerialNumberList pHeldSnList, SerialNumberList *pSnList)
CorrelationMatrix correlationMatrix () const
Returns the Correlation Matrix.
void setCorrMatCovFileName (FileName name)
Set the covariance file name for the matrix used to calculate the correlation matrix.
void setCorrMatImgsAndParams (QMap< QString, QStringList > imgsAndParams)
Set the images and their associated parameters of the correlation matrix.
void save (QXmlStreamWriter &stream, const Project *project) const
Saves the BundleResults object to an XML file.
Public Attributes
CorrelationMatrix * m_correlationMatrix
The correlation matrix from the BundleAdjust.
int m_numberFixedPoints
number of 'fixed' (ground) points (define)
int m_numberIgnoredPoints
number of ignored points
int m_numberHeldImages
number of 'held' images (define)
double m_rmsXResiduals
rms of x residuals
double m_rmsYResiduals
rms of y residuals
double m_rmsXYResiduals
rms of all x and y residuals
double m_rejectionLimit
current rejection limit
int m_numberObservations
number of image coordinate observations
int m_numberImageObservations
photogrammetry image coords. (2 per measure)
int m_numberLidarImageObservations
lidar image coords. (2 per measure)
int m_numberRejectedObservations
number of rejected image coordinate observations
int m_numberLidarRangeConstraintEquations
int m_numberUnknownParameters
total number of parameters to solve for
int m_numberImageParameters
number of image parameters
int m_numberConstrainedImageParameters
number of constrained image parameters
int m_numberConstrainedPointParameters
number of constrained point parameters
int m_numberConstrainedLidarPointParameters
lidar points
int m_numberConstrainedTargetParameters
number of constrained target parameters
int m_degreesOfFreedom
degrees of freedom
double m_sigma0
std deviation of unit weight
double m_elapsedTime
elapsed time for bundle
double m_elapsedTimeErrorProp
elapsed time for error propagation
bool m_converged
QVector< BundleControlPointQsp > m_bundleControlPoints
The vector of BundleControlPoints from BundleAdjust.
QVector< BundleLidarControlPointQsp > m_bundleLidarPoints
ControlNetQsp m_outNet
The output control net from BundleAdjust.
LidarDataQsp m_outLidarData
Output lidar data from BundleAdjust.
int m_iterations
The number of iterations taken by BundleAdjust.
BundleObservationVector m_observations
The vector of BundleObservations from BundleAdjust.
QList< Statistics > m_rmsImageSampleResiduals
List of RMS image sample residual statistics for each image in the bundle
QList< Statistics > m_rmsImageLineResiduals
List of RMS image line residual statistics for each image in the bundle
QList< Statistics > m_rmsImageResiduals
RMS image sample and line residual statistics for each image in the bundle
QList< Statistics > m_rmsLidarImageSampleResiduals
List of RMS lidar sample residual stats for each image in the bundle
QList< Statistics > m_rmsLidarImageLineResiduals
List of RMS lidar line residual stats for each image in the bundle
QList< Statistics > m_rmsLidarImageResiduals
RMS image lidar sample & line residual stats for each image in the bundle
QVector< Statistics > m_rmsImageXSigmas
QVector< Statistics > m_rmsImageYSigmas
< The root mean square image y sigmas.
QVector< Statistics > m_rmsImageZSigmas
< The root mean square image z sigmas.
QVector< Statistics > m_rmsImageRASigmas
< The root mean square image right ascension sigmas.
QVector< Statistics > m_rmsImageDECSigmas
< The root mean square image declination sigmas.
QVector< Statistics > m_rmsImageTWISTSigmas
< The root mean square image twist sigmas.
Distance m_minSigmaCoord1Distance
The minimum sigma latitude distance.
Distance m_maxSigmaCoord1Distance
The maximum sigma latitude distance.
Distance m_minSigmaCoord2Distance
The minimum sigma longitude distance.
Distance m_maxSigmaCoord2Distance
The maximum sigma longitude distance.
Distance m_minSigmaCoord3Distance
The minimum sigma radius distance.
Distance m_maxSigmaCoord3Distance
The maximum sigma radius distance.
QString m_minSigmaCoord1PointId
The minimum sigma coordinate 1 point id.
QString m_maxSigmaCoord1PointId
The maximum sigma coordinate 1 point id.
QString m_minSigmaCoord2PointId
The minimum sigma coordinate 2 point id.
QString m_maxSigmaCoord2PointId
The maximum sigma coordinate2 point id.
QString m_minSigmaCoord3PointId
The minimum sigma coordinate 3 point id.
QString m_maxSigmaCoord3PointId
The maximum sigma coordinate 3 point id.
double m_rmsSigmaCoord1Stats
rms of adjusted Latitude sigmas
double m_rmsSigmaCoord2Stats
rms of adjusted Longitude sigmas
double m_rmsSigmaCoord3Stats
rms of adjusted Radius sigmas
QList< QPair< MaximumLikelihoodWFunctions, double > > m_maximumLikelihoodFunctions
< The maximum likelihood models and their quantiles.
int m_maximumLikelihoodIndex
This count keeps track of which stage of the maximum likelihood adjustment the bundle is currently on.
StatCumProbDistDynCalc * m_cumPro
This class will be used to calculate the cumulative probability distribution of |R^2 residuals|, quantiles of this distribution are used to adjust the maximum likelihood functions dynamically iteration by iteration.
StatCumProbDistDynCalc * m_cumProRes
This class keeps track of the cumulative probability distribution of residuals (in unweighted pixels), this is used for reporting, and not for computation.
double m_maximumLikelihoodMedianR2Residuals
Median of R^2 residuals.
Detailed Description
A container class for statistical results from a BundleAdjust solution.
Author
2014-07-01 Jeannie Backer
Constructor & Destructor Documentation
BundleResults() [1/3]
Isis::BundleResults::BundleResults (QObject * parent = 0)
Constructs a BundleResults object.
Parameters
parent The Qt-relationship parent.
References initialize(), initializeResidualsProbabilityDistribution(), m_correlationMatrix, m_cumPro, and m_cumProRes.
BundleResults() [2/3]
Isis::BundleResults::BundleResults (QXmlStreamReader * xmlReader, QObject * parent = 0)
Construct this BundleResults object from XML.
Parameters
bundleSettingsFolder Where the settings XML for this bundle adjustment resides - /work/.../projectRoot/images/import1
xmlReader An XML reader that's up to a <bundleSettings> tag.
parent The Qt-relationship parent.
References initialize(), and readBundleResults().
BundleResults() [3/3]
Isis::BundleResults::BundleResults (const BundleResults & src)
Copy constructor for BundleResults.
Creates this BundleResults object as a copy of another BundleResults object.
Parameters
src The other BundleResults object to be copied.
~BundleResults()
Isis::BundleResults::~BundleResults ()
Destroys this BundleResults object.
References m_correlationMatrix, m_cumPro, and m_cumProRes.
Member Function Documentation
addProbabilityDistributionObservation() [1/2]
void Isis::BundleResults::addProbabilityDistributionObservation (double observationValue)
Adds an observation to the cumulative probability distribution of |R^2 residuals|.
Parameters
observationValue The value of the added observation.
References Isis::StatCumProbDistDynCalc::addObs(), and m_cumPro.
addProbabilityDistributionObservation() [2/2]
void Isis::BundleResults::addProbabilityDistributionObservation (double obsValue, bool residuals)
addResidualsProbabilityDistributionObservation()
void Isis::BundleResults::addResidualsProbabilityDistributionObservation (double observationValue)
Adds an observation to the cumulative probability distribution of residuals used for reporting.
Parameters
observationValue The value of the added observation.
References Isis::StatCumProbDistDynCalc::addObs(), and m_cumProRes.
bundleControlPoints()
QVector< BundleControlPointQsp > & Isis::BundleResults::bundleControlPoints ()
Returns a reference to the BundleControlPoint vector.
Returns
QVector<BundleControlPointQsp>& The BundleControlPoint vector.
References m_bundleControlPoints.
Referenced by Isis::BundleSolutionInfo::outputPointsCSV(), Isis::BundleSolutionInfo::outputResiduals(), and Isis::BundleSolutionInfo::outputText().
bundleLidarControlPoints()
QVector< BundleLidarControlPointQsp > & Isis::BundleResults::bundleLidarControlPoints ()
Returns a reference to the BundleLidarControlPoint vector.
Returns
QVector<BundleLidarControlPointQsp>& The BundleLidarControlPoint vector.
References m_bundleLidarPoints.
Referenced by Isis::BundleSolutionInfo::outputLidarCSV(), Isis::BundleSolutionInfo::outputResiduals(), and Isis::BundleSolutionInfo::outputText().
computeDegreesOfFreedom()
void Isis::BundleResults::computeDegreesOfFreedom ()
Computes the degrees of freedom of the bundle adjustment and stores it internally.
References m_degreesOfFreedom, m_numberConstrainedImageParameters, m_numberConstrainedLidarPointParameters, m_numberConstrainedPointParameters, m_numberConstrainedTargetParameters, m_numberImageObservations, m_numberLidarImageObservations, m_numberLidarRangeConstraintEquations, and m_numberUnknownParameters.
Referenced by computeSigma0().
computeSigma0()
void Isis::BundleResults::computeSigma0 (double dvtpv, BundleSettings::ConvergenceCriteria criteria)
Computes the sigma0 and stores it internally.
Sigma0 is the standard deviation of an observation of unit weight. Sigma0^2 is the variance of an observation of unit weight (also reference variance or variance factor).
Sigma0^2 = vtpv/degrees of freedom.
Parameters
dvtpv The weighted sum of the squares of the residuals. Computed by V transpose * P * V, where V is the vector of residuals and P is the weight matrix.
criteria The convergence criteria for the bundle adjustment.
Exceptions
IException::Io "Computed degrees of freedom is invalid."
References _FILEINFO_, computeDegreesOfFreedom(), Isis::IException::Io, m_degreesOfFreedom, m_sigma0, Isis::BundleSettings::ParameterCorrections, and Isis::toString().
converged()
bool Isis::BundleResults::converged () const
Returns whether or not the bundle adjustment converged.
Returns
bool If the bundle adjustment converged.
References m_converged.
Referenced by Isis::BundleSolutionInfo::outputImagesCSV(), Isis::BundleSolutionInfo::outputText(), save(), and setConverged().
coordTypeReports()
SurfacePoint::CoordinateType Isis::BundleResults::coordTypeReports ()
References Isis::SurfacePoint::Latitudinal, m_outNet, and outputControlNet().
correlationMatrix()
CorrelationMatrix Isis::BundleResults::correlationMatrix () const
Returns the Correlation Matrix.
Returns
CorrelationMatrix The correlation matrix.
Exceptions
IException::Unknown "Correlation matrix for this bundle is NULL."
References _FILEINFO_, m_correlationMatrix, and Isis::IException::Unknown.
Referenced by save(), setCorrMatCovFileName(), and setCorrMatImgsAndParams().
cumulativeProbabilityDistribution()
StatCumProbDistDynCalc Isis::BundleResults::cumulativeProbabilityDistribution () const
Returns the cumulative probability distribution of the |R^2 residuals|.
Returns
StatCumProbDistDynCalc The cumulative probability distribution of the |R^2 residuals|.
References m_cumPro.
degreesOfFreedom()
int Isis::BundleResults::degreesOfFreedom () const
Returns the degrees of freedom.
Returns
int the degrees of freedom.
References m_degreesOfFreedom.
Referenced by Isis::BundleSolutionInfo::outputHeader(), save(), and setDegreesOfFreedom().
elapsedTime()
double Isis::BundleResults::elapsedTime () const
Returns the elapsed time for the bundle adjustment.
Returns
double The elapsed time for the bundle adjustment.
References m_elapsedTime.
Referenced by Isis::BundleSolutionInfo::outputHeader(), and save().
elapsedTimeErrorProp()
double Isis::BundleResults::elapsedTimeErrorProp () const
Returns the elapsed time for error propagation.
Returns
double The elapsed time for error propagation.
References m_elapsedTimeErrorProp.
Referenced by Isis::BundleSolutionInfo::outputHeader(), and save().
incrementFixedPoints()
void Isis::BundleResults::incrementFixedPoints ()
Increase the number of 'fixed' (ground) points.
References m_numberFixedPoints.
incrementHeldImages()
void Isis::BundleResults::incrementHeldImages ()
Increases the number of 'held' images.
References m_numberHeldImages.
incrementIgnoredPoints()
void Isis::BundleResults::incrementIgnoredPoints ()
Increase the number of ignored points.
References m_numberIgnoredPoints.
incrementMaximumLikelihoodModelIndex()
void Isis::BundleResults::incrementMaximumLikelihoodModelIndex ()
Increases the value that indicates which stage the maximum likelihood adjustment is currently on.
References m_maximumLikelihoodIndex.
incrementNumberConstrainedImageParameters()
void Isis::BundleResults::incrementNumberConstrainedImageParameters (int incrementAmount)
Increase the number of constrained image parameters.
Parameters
incrementAmount The amount to increase by.
References m_numberConstrainedImageParameters.
incrementNumberConstrainedPointParameters()
void Isis::BundleResults::incrementNumberConstrainedPointParameters (int incrementAmount)
Increase the number of contrained point parameters.
Parameters
incrementAmount The amount to increase by.
References m_numberConstrainedPointParameters.
incrementNumberConstrainedTargetParameters()
void Isis::BundleResults::incrementNumberConstrainedTargetParameters (int incrementAmount)
Increases the number of constrained target parameters.
Parameters
incrementAmount The amount to increase by.
References m_numberConstrainedTargetParameters.
initialize()
void Isis::BundleResults::initialize ()
Initializes the BundleResults to a default state where all numeric members are set to 0 or another default value, all QString members are set to empty, all QVectors and QLists are cleared, and all other members are set to NULL.
References m_converged, m_correlationMatrix, m_cumPro, m_cumProRes, m_degreesOfFreedom, m_elapsedTime, m_elapsedTimeErrorProp, m_iterations, m_maximumLikelihoodFunctions, m_maximumLikelihoodIndex, m_maximumLikelihoodMedianR2Residuals, m_maxSigmaCoord1Distance, m_maxSigmaCoord1PointId, m_maxSigmaCoord2Distance, m_maxSigmaCoord2PointId, m_maxSigmaCoord3Distance, m_maxSigmaCoord3PointId, m_minSigmaCoord1Distance, m_minSigmaCoord1PointId, m_minSigmaCoord2Distance, m_minSigmaCoord2PointId, m_minSigmaCoord3Distance, m_minSigmaCoord3PointId, m_numberConstrainedImageParameters, m_numberConstrainedLidarPointParameters, m_numberConstrainedPointParameters, m_numberConstrainedTargetParameters, m_numberFixedPoints, m_numberHeldImages, m_numberIgnoredPoints, m_numberImageObservations, m_numberImageParameters, m_numberLidarImageObservations, m_numberLidarRangeConstraintEquations, m_numberObservations, m_numberRejectedObservations, m_numberUnknownParameters, m_observations, m_outLidarData, m_outNet, m_rejectionLimit, m_rmsImageDECSigmas, m_rmsImageLineResiduals, m_rmsImageRASigmas, m_rmsImageResiduals, m_rmsImageSampleResiduals, m_rmsImageTWISTSigmas, m_rmsImageXSigmas, m_rmsImageYSigmas, m_rmsImageZSigmas, m_rmsLidarImageLineResiduals, m_rmsLidarImageResiduals, m_rmsLidarImageSampleResiduals, m_rmsSigmaCoord1Stats, m_rmsSigmaCoord2Stats, m_rmsSigmaCoord3Stats, m_rmsXResiduals, m_rmsXYResiduals, m_rmsYResiduals, m_sigma0, and Isis::Distance::setMeters().
Referenced by BundleResults().
initializeProbabilityDistribution()
void Isis::BundleResults::initializeProbabilityDistribution (unsigned int nodes = 20)
Initializes or resets the cumulative probability distribution of |R^2 residuals|.
Parameters
nodes The number of quantiles in the cumulative probability distribution.
References m_cumPro, and Isis::StatCumProbDistDynCalc::setQuantiles().
Referenced by maximumLikelihoodSetUp(), and printMaximumLikelihoodTierInformation().
initializeResidualsProbabilityDistribution()
void Isis::BundleResults::initializeResidualsProbabilityDistribution (unsigned int nodes = 20)
Initializes or resets the cumulative probability distribution of residuals used for reporting.
Parameters
nodes The number of quantiles in the cumulative probability distribution.
References m_cumProRes, and Isis::StatCumProbDistDynCalc::setQuantiles().
Referenced by BundleResults(), and maximumLikelihoodSetUp().
iterations()
int Isis::BundleResults::iterations () const
Returns the number of iterations taken by the BundleAdjust.
Returns
int The number of iterations.
References m_iterations.
Referenced by Isis::BundleSolutionInfo::outputHeader(), save(), and setIterations().
maximumLikelihoodMedianR2Residuals()
double Isis::BundleResults::maximumLikelihoodMedianR2Residuals () const
Returns the median of the |R^2 residuals|.
Returns
double The median of the |R^2 residuals|.
References m_maximumLikelihoodMedianR2Residuals.
Referenced by readMaxLikelihoodEstimation(), and save().
maximumLikelihoodModelIndex()
int Isis::BundleResults::maximumLikelihoodModelIndex () const
Returns which step the bundle adjustment is on.
Returns
int The maximum likelihood model that the bundle adjustment is currently using.
References m_maximumLikelihoodIndex.
Referenced by save().
maximumLikelihoodModelQuantile()
double Isis::BundleResults::maximumLikelihoodModelQuantile (int modelIndex) const
Returns the quantile of the maximum likelihood model at the given index.
Parameters
modelIndex The index of the maximum likelihood model whose quantile will be returned.
Returns
double The quantile of the desired maximum likelihood model.
References m_maximumLikelihoodFunctions.
Referenced by Isis::BundleSolutionInfo::outputHeader().
maximumLikelihoodModels()
QList< QPair< MaximumLikelihoodWFunctions, double > > Isis::BundleResults::maximumLikelihoodModels () const
maximumLikelihoodModelWFunc()
MaximumLikelihoodWFunctions Isis::BundleResults::maximumLikelihoodModelWFunc (int modelIndex) const
Returns the maximum likelihood model at the given index.
Parameters
modelIndex The index of the maximum likelihood model to be returned.
Returns
MaximumLikelihoodWFunctions The maximum likelihood model at the input index.
References m_maximumLikelihoodFunctions.
Referenced by Isis::BundleSolutionInfo::outputHeader().
maximumLikelihoodSetUp()
void Isis::BundleResults::maximumLikelihoodSetUp (QList< QPair< MaximumLikelihoodWFunctions::Model, double > > modelsWithQuantiles)
This method steps up the maximum likelihood estimation solution.
Up to three successive solutions models are available.
Parameters
modelsWithQuantiles The maixmum likelihood models and their quantiles. If empty, then maximum likelihood estimation will not be used.
References initializeProbabilityDistribution(), initializeResidualsProbabilityDistribution(), m_cumPro, m_cumProRes, m_maximumLikelihoodFunctions, m_maximumLikelihoodIndex, and m_maximumLikelihoodMedianR2Residuals.
maxSigmaCoord1Distance()
Distance Isis::BundleResults::maxSigmaCoord1Distance () const
Returns the maximum sigma distance for coordinate 1.
Returns
Distance The maximum sigma Coord1.
References m_maxSigmaCoord1Distance.
Referenced by Isis::BundleSolutionInfo::outputText(), and save().
maxSigmaCoord1PointId()
QString Isis::BundleResults::maxSigmaCoord1PointId () const
Returns the maximum sigma point id for coordinate 1.
Returns
@QString The maximum sigma Coord1 point id.
References m_maxSigmaCoord1PointId.
Referenced by Isis::BundleSolutionInfo::outputText(), and save().
maxSigmaCoord2Distance()
Distance Isis::BundleResults::maxSigmaCoord2Distance () const
Returns the maximum sigma distance for coordinate 2.
Returns
Distance The maximum sigma Coord2.
References m_maxSigmaCoord2Distance.
Referenced by Isis::BundleSolutionInfo::outputText(), and save().
maxSigmaCoord2PointId()
QString Isis::BundleResults::maxSigmaCoord2PointId () const
Returns the maximum sigma point id for coordinate 2.
Returns
@QString The maximum sigma Coord2 point id.
References m_maxSigmaCoord2PointId.
Referenced by Isis::BundleSolutionInfo::outputText(), and save().
maxSigmaCoord3Distance()
Distance Isis::BundleResults::maxSigmaCoord3Distance () const
Returns the maximum sigma distance for coordinate 3.
Returns
Distance The maximum sigma Coord3.
References m_maxSigmaCoord3Distance.
Referenced by Isis::BundleSolutionInfo::outputText(), and save().
maxSigmaCoord3PointId()
QString Isis::BundleResults::maxSigmaCoord3PointId () const
Returns the maximum sigma point id for coordinate 3.
Returns
@QString The maximum sigma Coord3 point id.
References m_maxSigmaCoord3PointId.
Referenced by Isis::BundleSolutionInfo::outputText(), and save().
minSigmaCoord1Distance()
Distance Isis::BundleResults::minSigmaCoord1Distance () const
Returns the minimum sigma distance for coordinate 1.
Returns
Distance The minimum sigma for Coord1.
References m_minSigmaCoord1Distance.
Referenced by Isis::BundleSolutionInfo::outputText(), and save().
minSigmaCoord1PointId()
QString Isis::BundleResults::minSigmaCoord1PointId () const
Returns the minimum sigma point id for coordinate 1.
Returns
@QString The minimum sigma Coord1 point id.
References m_minSigmaCoord1PointId.
Referenced by Isis::BundleSolutionInfo::outputText(), and save().
minSigmaCoord2Distance()
Distance Isis::BundleResults::minSigmaCoord2Distance () const
Returns the minimum sigma distance for coordinate 2.
Returns
Distance The minimum sigma Coord2.
References m_minSigmaCoord2Distance.
Referenced by Isis::BundleSolutionInfo::outputText(), and save().
minSigmaCoord2PointId()
QString Isis::BundleResults::minSigmaCoord2PointId () const
Returns the minimum sigma point id for coordinate 2.
Returns
@QString The minimum sigma longitude point id.
References m_minSigmaCoord2PointId.
Referenced by Isis::BundleSolutionInfo::outputText(), and save().
minSigmaCoord3Distance()
Distance Isis::BundleResults::minSigmaCoord3Distance () const
Returns the minimum sigma distance for coordinate 3.
Returns
Distance The minimum sigma Coord3.
References m_minSigmaCoord3Distance.
Referenced by Isis::BundleSolutionInfo::outputText(), and save().
minSigmaCoord3PointId()
QString Isis::BundleResults::minSigmaCoord3PointId () const
Returns the minimum sigma point id for coordinate 3.
Returns
@QString The minimum sigma Coord3 point id.
References m_minSigmaCoord3PointId.
Referenced by Isis::BundleSolutionInfo::outputText(), and save().
numberConstrainedImageParameters()
int Isis::BundleResults::numberConstrainedImageParameters () const
Returns the number of constrained image parameters.
Returns
int The number of constrained image parameters.
References m_numberConstrainedImageParameters.
Referenced by Isis::BundleSolutionInfo::outputHeader(), and save().
numberConstrainedPointParameters()
int Isis::BundleResults::numberConstrainedPointParameters () const
Returns the number of constrained point parameters.
Returns
int The number of constrained point parameters.
References m_numberConstrainedPointParameters.
Referenced by Isis::BundleSolutionInfo::outputHeader(), and save().
numberConstrainedTargetParameters()
int Isis::BundleResults::numberConstrainedTargetParameters () const
Return the number of constrained target parameters.
Returns
int The number of constrained target parameters.
References m_numberConstrainedTargetParameters.
Referenced by Isis::BundleSolutionInfo::outputHeader(), and save().
numberFixedPoints()
int Isis::BundleResults::numberFixedPoints () const
Returns the number of 'fixed' (ground) points.
Returns
int The number of fixed points.
References m_numberFixedPoints.
Referenced by save().
numberHeldImages()
int Isis::BundleResults::numberHeldImages () const
Returns the number of 'held' images.
Returns
int The number of held images.
References m_numberHeldImages.
Referenced by save().
numberIgnoredPoints()
int Isis::BundleResults::numberIgnoredPoints () const
Returns the number of ignored points.
Returns
int The number of ignored points.
References m_numberIgnoredPoints.
Referenced by save().
numberImageObservations()
int Isis::BundleResults::numberImageObservations () const
Returns the number of observations.
Returns
int The number of observations.
References m_numberImageObservations.
Referenced by save().
numberImageParameters()
int Isis::BundleResults::numberImageParameters () const
Returns the total number of image parameters.
Returns
int The total number of image parameters.
References m_numberImageParameters.
Referenced by save().
numberLidarImageObservations()
int Isis::BundleResults::numberLidarImageObservations () const
Returns the number of lidar observations.
Returns
int The number of lidar observations.
References m_numberLidarImageObservations.
Referenced by save().
numberLidarRangeConstraintEquations()
int Isis::BundleResults::numberLidarRangeConstraintEquations () const
Return the number of lidar range constraint equations.
Returns
int The number of lidar range constraint equations.
References m_numberLidarRangeConstraintEquations.
Referenced by Isis::BundleSolutionInfo::outputHeader(), and save().
numberMaximumLikelihoodModels()
int Isis::BundleResults::numberMaximumLikelihoodModels () const
Returns how many maximum likelihood models were used in the bundle adjustment.
Returns
int The number fo maximum likelihood models.
References m_maximumLikelihoodFunctions.
Referenced by printMaximumLikelihoodTierInformation(), and save().
numberObservations()
int Isis::BundleResults::numberObservations () const
Returns the number of observations.
Returns
int The number of observations.
References m_numberImageObservations, and m_numberLidarImageObservations.
Referenced by Isis::BundleSolutionInfo::outputHeader(), save(), setNumberImageObservations(), and setNumberObservations().
numberRejectedObservations()
int Isis::BundleResults::numberRejectedObservations () const
Returns the number of observation that were rejected.
Returns
int The number of rejected observations.
References m_numberRejectedObservations.
Referenced by Isis::BundleSolutionInfo::outputHeader(), save(), and setNumberRejectedObservations().
numberUnknownParameters()
int Isis::BundleResults::numberUnknownParameters () const
Returns the number of unknown parameters.
Returns
int The number of unknown parameters.
References m_numberUnknownParameters.
Referenced by Isis::BundleSolutionInfo::outputHeader(), and save().
observations()
const BundleObservationVector & Isis::BundleResults::observations () const
Returns a reference to the observations used by the BundleAdjust.
Returns
BundleObservationVector& A reference to the observation vector.
References m_observations.
Referenced by Isis::BundleSolutionInfo::outputHeader(), Isis::BundleSolutionInfo::outputImagesCSV(), Isis::BundleSolutionInfo::outputText(), and setObservations().
operator=()
BundleResults & Isis::BundleResults::operator= (const BundleResults & src)
Assignment operator for BundleResults.
Overwrites this BundleResults object with another BundleResults object.
Parameters
src The other BundleResults object to be copied from.
References m_bundleControlPoints, m_bundleLidarPoints, m_converged, m_correlationMatrix, m_cumPro, m_cumProRes, m_degreesOfFreedom, m_elapsedTime, m_elapsedTimeErrorProp, m_iterations, m_maximumLikelihoodFunctions, m_maximumLikelihoodIndex, m_maximumLikelihoodMedianR2Residuals, m_maxSigmaCoord1Distance, m_maxSigmaCoord1PointId, m_maxSigmaCoord2Distance, m_maxSigmaCoord2PointId, m_maxSigmaCoord3Distance, m_maxSigmaCoord3PointId, m_minSigmaCoord1Distance, m_minSigmaCoord1PointId, m_minSigmaCoord2Distance, m_minSigmaCoord2PointId, m_minSigmaCoord3Distance, m_minSigmaCoord3PointId, m_numberConstrainedImageParameters, m_numberConstrainedLidarPointParameters, m_numberConstrainedPointParameters, m_numberConstrainedTargetParameters, m_numberFixedPoints, m_numberHeldImages, m_numberIgnoredPoints, m_numberImageObservations, m_numberImageParameters, m_numberLidarImageObservations, m_numberLidarRangeConstraintEquations, m_numberObservations, m_numberRejectedObservations, m_numberUnknownParameters, m_observations, m_outLidarData, m_outNet, m_rejectionLimit, m_rmsImageDECSigmas, m_rmsImageLineResiduals, m_rmsImageRASigmas, m_rmsImageResiduals, m_rmsImageSampleResiduals, m_rmsImageTWISTSigmas, m_rmsImageXSigmas, m_rmsImageYSigmas, m_rmsImageZSigmas, m_rmsLidarImageLineResiduals, m_rmsLidarImageResiduals, m_rmsLidarImageSampleResiduals, m_rmsSigmaCoord1Stats, m_rmsSigmaCoord2Stats, m_rmsSigmaCoord3Stats, m_rmsXResiduals, m_rmsXYResiduals, m_rmsYResiduals, and m_sigma0.
outputControlNet()
ControlNetQsp Isis::BundleResults::outputControlNet () const
Returns a shared pointer to the output control network.
Returns
ControlNetQsp A shared pointer to the output control network.
Exceptions
IException::Programmer "Output Control Network has not been set."
References _FILEINFO_, m_outNet, and Isis::IException::Programmer.
Referenced by coordTypeReports(), Isis::BundleSolutionInfo::outputHeader(), and save().
outputLidarData()
LidarDataQsp Isis::BundleResults::outputLidarData () const
Returns a shared pointer to the output LidarData object.
Returns
LidarDataQsp A shared pointer to the output LidarData object.
Exceptions
IException::Programmer "Output LidarData object has not been set."
References m_outLidarData.
Referenced by Isis::BundleSolutionInfo::outputHeader().
printMaximumLikelihoodTierInformation()
void Isis::BundleResults::printMaximumLikelihoodTierInformation ()
Prints out information about which tier the solution is in and the status of the residuals.
References initializeProbabilityDistribution(), m_cumPro, m_maximumLikelihoodFunctions, m_maximumLikelihoodIndex, m_maximumLikelihoodMedianR2Residuals, numberMaximumLikelihoodModels(), and Isis::StatCumProbDistDynCalc::value().
readBundleResults()
void Isis::BundleResults::readBundleResults (QXmlStreamReader * xmlReader)
References m_elapsedTime, m_elapsedTimeErrorProp, readCorrelationMatrix(), readGenStatsValues(), readMaxLikelihoodEstimation(), readMinMaxSigmas(), and readRms().
Referenced by BundleResults(), and Isis::BundleSolutionInfo::readBundleSolutionInfo().
readCorrelationMatrix()
void Isis::BundleResults::readCorrelationMatrix (QXmlStreamReader * xmlReader)
References m_correlationMatrix, Isis::CorrelationMatrix::setCorrelationFileName(), and Isis::CorrelationMatrix::setCovarianceFileName().
Referenced by readBundleResults().
readGenStatsValues()
void Isis::BundleResults::readGenStatsValues (QXmlStreamReader * xmlReader)
References m_converged, m_degreesOfFreedom, m_iterations, m_numberConstrainedImageParameters, m_numberConstrainedPointParameters, m_numberConstrainedTargetParameters, m_numberFixedPoints, m_numberHeldImages, m_numberIgnoredPoints, m_numberImageObservations, m_numberImageParameters, m_numberLidarImageObservations, m_numberLidarRangeConstraintEquations, m_numberObservations, m_numberRejectedObservations, m_numberUnknownParameters, m_rejectionLimit, m_sigma0, Isis::toBool(), and Isis::toInt().
Referenced by readBundleResults().
readImageResidualsLists()
void Isis::BundleResults::readImageResidualsLists (QXmlStreamReader * xmlReader)
References m_rmsImageLineResiduals, m_rmsImageResiduals, m_rmsImageSampleResiduals, m_rmsLidarImageLineResiduals, m_rmsLidarImageResiduals, m_rmsLidarImageSampleResiduals, and readStatsToList().
Referenced by readRms().
readMaxLikelihoodEstimation()
void Isis::BundleResults::readMaxLikelihoodEstimation (QXmlStreamReader * xmlReader)
References m_cumPro, m_cumProRes, m_maximumLikelihoodFunctions, m_maximumLikelihoodIndex, m_maximumLikelihoodMedianR2Residuals, maximumLikelihoodMedianR2Residuals(), Isis::StatCumProbDistDynCalc::readStatistics(), and Isis::MaximumLikelihoodWFunctions::stringToModel().
Referenced by readBundleResults().
readMinMaxSigmas()
void Isis::BundleResults::readMinMaxSigmas (QXmlStreamReader * xmlReader)
References m_maxSigmaCoord1Distance, m_maxSigmaCoord1PointId, m_maxSigmaCoord2Distance, m_maxSigmaCoord2PointId, m_maxSigmaCoord3Distance, m_maxSigmaCoord3PointId, m_minSigmaCoord1Distance, m_minSigmaCoord1PointId, m_minSigmaCoord2Distance, m_minSigmaCoord2PointId, m_minSigmaCoord3Distance, m_minSigmaCoord3PointId, and readSigma().
Referenced by readBundleResults().
readRms()
void Isis::BundleResults::readRms (QXmlStreamReader * xmlReader)
References m_rmsSigmaCoord1Stats, m_rmsSigmaCoord2Stats, m_rmsSigmaCoord3Stats, m_rmsXResiduals, m_rmsXYResiduals, m_rmsYResiduals, readImageResidualsLists(), and readSigmasLists().
Referenced by readBundleResults().
readSigma()
void Isis::BundleResults::readSigma (Distance & dist, QString & pointId, QXmlStreamReader * xmlReader)
References Isis::Distance::setMeters().
Referenced by readMinMaxSigmas().
readSigmasLists()
void Isis::BundleResults::readSigmasLists (QXmlStreamReader * xmlReader)
References m_rmsImageDECSigmas, m_rmsImageRASigmas, m_rmsImageTWISTSigmas, m_rmsImageXSigmas, m_rmsImageYSigmas, m_rmsImageZSigmas, and readStatsToVector().
Referenced by readRms().
readStatsToList()
void Isis::BundleResults::readStatsToList (QList< Statistics > & list, QXmlStreamReader * xmlReader)
Referenced by readImageResidualsLists().
readStatsToVector()
void Isis::BundleResults::readStatsToVector (QVector< Statistics > & vec, QXmlStreamReader * xmlReader)
Referenced by readSigmasLists().
rejectionLimit()
double Isis::BundleResults::rejectionLimit () const
Returns the rejection limit.
Returns
double The rejection limit.
References m_rejectionLimit.
Referenced by save(), and setRejectionLimit().
resetNumberConstrainedImageParameters()
void Isis::BundleResults::resetNumberConstrainedImageParameters ()
Resets the number of constrained image parameters to 0.
References m_numberConstrainedImageParameters.
resetNumberConstrainedPointParameters()
void Isis::BundleResults::resetNumberConstrainedPointParameters ()
Resets the number of contrained point parameters to 0.
References m_numberConstrainedPointParameters.
resetNumberConstrainedTargetParameters()
void Isis::BundleResults::resetNumberConstrainedTargetParameters ()
Resets the number of constrained target parameters to 0.
References m_numberConstrainedTargetParameters.
residualsCumulativeProbabilityDistribution()
StatCumProbDistDynCalc Isis::BundleResults::residualsCumulativeProbabilityDistribution () const
Returns the cumulative probability distribution of the residuals used for reporting.
Returns
StatCumProbDistDynCalc the cumulative probability distribution of the residuals.
References m_cumProRes.
Referenced by Isis::BundleSolutionInfo::outputHeader().
resizeSigmaStatisticsVectors()
void Isis::BundleResults::resizeSigmaStatisticsVectors (int numberImages)
Resizes all image sigma vectors.
Parameters
numberImages The new size for the image sigma vectors.
References m_rmsImageDECSigmas, m_rmsImageRASigmas, m_rmsImageTWISTSigmas, m_rmsImageXSigmas, m_rmsImageYSigmas, and m_rmsImageZSigmas.
rmsImageDECSigmas()
QVector< Statistics > Isis::BundleResults::rmsImageDECSigmas () const
Returns the list of RMS image declination sigma statistics.
Returns
QList<Statistics> The RMS image declination sigma statistics.
References m_rmsImageDECSigmas.
Referenced by save().
rmsImageLineResiduals()
QList< Statistics > Isis::BundleResults::rmsImageLineResiduals () const
Returns the list of RMS image line residuals statistics.
Returns
QList<Statistics> The RMS image line residual statistics.
References m_rmsImageLineResiduals.
Referenced by Isis::BundleSolutionInfo::outputImagesCSV(), save(), and setRmsImageResidualLists().
rmsImageRASigmas()
QVector< Statistics > Isis::BundleResults::rmsImageRASigmas () const
Returns the list of RMS image right ascension sigma statistics.
Returns
QList<Statistics> The RMS image right ascension sigma statistics.
References m_rmsImageRASigmas.
Referenced by save().
rmsImageResiduals()
QList< Statistics > Isis::BundleResults::rmsImageResiduals () const
Returns the list of RMS image residuals statistics.
Returns
QList<Statistics> The RMS image residual statistics.
References m_rmsImageResiduals.
Referenced by Isis::BundleSolutionInfo::outputImagesCSV(), save(), and setRmsImageResidualLists().
rmsImageSampleResiduals()
QList< Statistics > Isis::BundleResults::rmsImageSampleResiduals () const
Returns the list of RMS image sample residuals statistics.
Returns
QList<Statistics> The RMS image sample residual statistics.
References m_rmsImageSampleResiduals.
Referenced by Isis::BundleSolutionInfo::outputImagesCSV(), save(), and setRmsImageResidualLists().
rmsImageTWISTSigmas()
QVector< Statistics > Isis::BundleResults::rmsImageTWISTSigmas () const
Returns the list of RMS image twist sigma statistics.
Returns
QList<Statistics> The RMS image twist sigma statistics.
References m_rmsImageTWISTSigmas.
Referenced by save().
rmsImageXSigmas()
QVector< Statistics > Isis::BundleResults::rmsImageXSigmas () const
Returns the list of RMS image x sigma statistics.
Returns
QList<Statistics> The RMS image x sigma statistics.
References m_rmsImageXSigmas.
Referenced by save().
rmsImageYSigmas()
QVector< Statistics > Isis::BundleResults::rmsImageYSigmas () const
Returns the list of RMS image y sigma statistics.
Returns
QList<Statistics> The RMS image y sigma statistics.
References m_rmsImageYSigmas.
Referenced by save().
rmsImageZSigmas()
QVector< Statistics > Isis::BundleResults::rmsImageZSigmas () const
Returns the list of RMS image z sigma statistics.
Returns
QList<Statistics> The RMS image z sigma statistics.
References m_rmsImageZSigmas.
Referenced by save().
rmsLidarImageLineResiduals()
QList< Statistics > Isis::BundleResults::rmsLidarImageLineResiduals () const
Returns the list of RMS image lidar line residuals statistics.
Returns
QList<Statistics> The RMS image lidar line residual statistics.
References m_rmsLidarImageLineResiduals.
Referenced by save(), and setRmsLidarImageResidualLists().
rmsLidarImageResiduals()
QList< Statistics > Isis::BundleResults::rmsLidarImageResiduals () const
Returns the list of RMS image lidar residuals statistics.
Returns
QList<Statistics> The RMS image lidar residual statistics.
References m_rmsLidarImageResiduals.
Referenced by save(), and setRmsLidarImageResidualLists().
rmsLidarImageSampleResiduals()
QList< Statistics > Isis::BundleResults::rmsLidarImageSampleResiduals () const
Returns the list of RMS image lidar sample residuals statistics.
Returns
QList<Statistics> The RMS image lidar sample residual statistics.
References m_rmsLidarImageSampleResiduals.
Referenced by save(), and setRmsLidarImageResidualLists().
rmsRx()
double Isis::BundleResults::rmsRx () const
Returns the RMS of the x residuals.
Returns
double The RMS of the x residuals.
References m_rmsXResiduals.
Referenced by save().
rmsRxy()
double Isis::BundleResults::rmsRxy () const
Returns the RMS of the x and y residuals.
Returns
double The RMS of the x and y residuals.
References m_rmsXYResiduals.
Referenced by save().
rmsRy()
double Isis::BundleResults::rmsRy () const
Returns the RMS of the y residuals.
Returns
double The RMS of the y residuals.
References m_rmsYResiduals.
Referenced by save().
save()
void Isis::BundleResults::save (QXmlStreamWriter & stream, const Project * project) const
Saves the BundleResults object to an XML file.
Parameters
stream The QXMLStreamWriter that will be used to write out the XML file.
project The project that the BundleResults object belongs to.
References _FILEINFO_, converged(), correlationMatrix(), degreesOfFreedom(), elapsedTime(), elapsedTimeErrorProp(), iterations(), Isis::SurfacePoint::Latitudinal, m_maximumLikelihoodFunctions, m_outNet, m_rmsImageDECSigmas, m_rmsImageLineResiduals, m_rmsImageRASigmas, m_rmsImageResiduals, m_rmsImageSampleResiduals, m_rmsImageTWISTSigmas, m_rmsImageXSigmas, m_rmsImageYSigmas, m_rmsImageZSigmas, m_rmsLidarImageLineResiduals, m_rmsLidarImageResiduals, m_rmsLidarImageSampleResiduals, maximumLikelihoodMedianR2Residuals(), maximumLikelihoodModelIndex(), maxSigmaCoord1Distance(), maxSigmaCoord1PointId(), maxSigmaCoord2Distance(), maxSigmaCoord2PointId(), maxSigmaCoord3Distance(), maxSigmaCoord3PointId(), minSigmaCoord1Distance(), minSigmaCoord1PointId(), minSigmaCoord2Distance(), minSigmaCoord2PointId(), minSigmaCoord3Distance(), minSigmaCoord3PointId(), Isis::MaximumLikelihoodWFunctions::modelToString(), numberConstrainedImageParameters(), numberConstrainedPointParameters(), numberConstrainedTargetParameters(), numberFixedPoints(), numberHeldImages(), numberIgnoredPoints(), numberImageObservations(), numberImageParameters(), numberLidarImageObservations(), numberLidarRangeConstraintEquations(), numberMaximumLikelihoodModels(), numberObservations(), numberRejectedObservations(), numberUnknownParameters(), outputControlNet(), Isis::IException::Programmer, Isis::SurfacePoint::Rectangular, rejectionLimit(), rmsImageDECSigmas(), rmsImageLineResiduals(), rmsImageRASigmas(), rmsImageResiduals(), rmsImageSampleResiduals(), rmsImageTWISTSigmas(), rmsImageXSigmas(), rmsImageYSigmas(), rmsImageZSigmas(), rmsLidarImageLineResiduals(), rmsLidarImageResiduals(), rmsLidarImageSampleResiduals(), rmsRx(), rmsRxy(), rmsRy(), sigma0(), sigmaCoord1StatisticsRms(), sigmaCoord2StatisticsRms(), sigmaCoord3StatisticsRms(), and Isis::toString().
Referenced by Isis::BundleSolutionInfo::save().
setBundleControlPoints()
void Isis::BundleResults::setBundleControlPoints (QVector< BundleControlPointQsp > controlPoints)
Sets the bundle control point vector.
Parameters
controlPoints The vector of BundleControlPointQsps.
References m_bundleControlPoints.
setBundleLidarPoints()
void Isis::BundleResults::setBundleLidarPoints (QVector< BundleLidarControlPointQsp > lidarPoints)
Sets the bundle lidar point vector.
Parameters
lidarPoints Vector of BundleLidarControlPointQsps.
References m_bundleLidarPoints.
setConverged()
void Isis::BundleResults::setConverged (bool converged)
Sets if the bundle adjustment converged.
Parameters
converged If the bundle adjustment converged.
References converged(), and m_converged.
setCorrMatCovFileName()
void Isis::BundleResults::setCorrMatCovFileName (FileName name)
Set the covariance file name for the matrix used to calculate the correlation matrix.
Parameters
name The name of the file used to store the covariance matrix.
References correlationMatrix(), m_correlationMatrix, and Isis::CorrelationMatrix::setCovarianceFileName().
setCorrMatImgsAndParams()
void Isis::BundleResults::setCorrMatImgsAndParams (QMap< QString, QStringList > imgsAndParams)
Set the images and their associated parameters of the correlation matrix.
Parameters
imgsAndParams The QMap with all the images and parameters used for this bundle.
References correlationMatrix(), m_correlationMatrix, and Isis::CorrelationMatrix::setImagesAndParameters().
Referenced by Isis::BundleSolutionInfo::outputText().
setDegreesOfFreedom()
void Isis::BundleResults::setDegreesOfFreedom (double degreesOfFreedom)
Sets the degrees of freedom.
Parameters
degreesOfFreedom The degrees of freedom.
References degreesOfFreedom(), and m_degreesOfFreedom.
setElapsedTime()
void Isis::BundleResults::setElapsedTime (double time)
Sets the elapsed time for the bundle adjustment.
Parameters
time The elapsed time.
References m_elapsedTime.
setElapsedTimeErrorProp()
void Isis::BundleResults::setElapsedTimeErrorProp (double time)
Sets the elapsed time for error propegation.
Parameters
time The elapsed time.
References m_elapsedTimeErrorProp.
setIterations()
void Isis::BundleResults::setIterations (int iterations)
Sets the number of iterations taken by the BundleAdjust.
Parameters
iterations The number of iterations.
References iterations(), and m_iterations.
setNumberConstrainedLidarPointParameters()
void Isis::BundleResults::setNumberConstrainedLidarPointParameters (int numberParameters)
Set number of contrained point parameters.
Parameters
numberParameters Number of contrained point parameters.
References m_numberConstrainedLidarPointParameters.
setNumberConstrainedPointParameters()
void Isis::BundleResults::setNumberConstrainedPointParameters (int numberParameters)
Set number of contrained point parameters.
Parameters
numberParameters Number of contrained point parameters.
References m_numberConstrainedPointParameters.
setNumberHeldImages()
bool Isis::BundleResults::setNumberHeldImages (SerialNumberList pHeldSnList, SerialNumberList * pSnList)
setNumberImageObservations()
void Isis::BundleResults::setNumberImageObservations (int numberObservations)
Sets the number of photogrammetric image observations.
Note in this terminology an image measurement contributes two observations to the adjustment (i.e. sample/line).
So, the number of observations divided by 2 should equal the number of image measures.
Parameters
numberObservations The number of photogrammetric image observations.
References m_numberImageObservations, and numberObservations().
setNumberImageParameters()
void Isis::BundleResults::setNumberImageParameters (int numberParameters)
Sets the number of image parameters.
Parameters
numberParameters The number of image parameters.
References m_numberImageParameters.
setNumberLidarImageObservations()
void Isis::BundleResults::setNumberLidarImageObservations (int numberLidarObservations)
Sets the number of lidar observations.
Parameters
numberLidarObservations The number of lidar observations.
References m_numberLidarImageObservations.
setNumberLidarRangeConstraints()
void Isis::BundleResults::setNumberLidarRangeConstraints (int numberLidarRangeConstraints)
Sets the total number of lidar range constraints.
Parameters
numberLidarRangeConstraints The total number of lidar range constraints.
References m_numberLidarRangeConstraintEquations.
setNumberObservations()
void Isis::BundleResults::setNumberObservations (int numberObservations)
Sets the number of observations.
Parameters
numberObservations The number of observations.
References m_numberObservations, and numberObservations().
setNumberRejectedObservations()
void Isis::BundleResults::setNumberRejectedObservations (int numberRejectedObservations)
Sets the number of rejected observations.
Parameters
numberRejectedObservations The number of rejected observations.
References m_numberRejectedObservations, and numberRejectedObservations().
setNumberUnknownParameters()
void Isis::BundleResults::setNumberUnknownParameters (int numberParameters)
Sets the total number of parameters to solve for.
Parameters
numberParameters The number of parameters to solve for.
References m_numberUnknownParameters.
setObservations()
void Isis::BundleResults::setObservations (BundleObservationVector observations)
Sets the vector of BundleObservations.
Parameters
observations The vector of BundleObservations.
References m_observations, and observations().
setOutputControlNet()
void Isis::BundleResults::setOutputControlNet (ControlNetQsp outNet)
Sets the output ControlNet.
Parameters
outNet A QSharedPointer to the output ControlNet.
References m_outNet.
setOutputLidarData()
void Isis::BundleResults::setOutputLidarData (LidarDataQsp outLidarData)
Sets the output LidarData object.
Parameters
outLidarData A QSharedPointer to the output LidarData object.
References m_outLidarData.
setRejectionLimit()
void Isis::BundleResults::setRejectionLimit (double rejectionLimit)
Sets the rejection limit.
Parameters
rejectionLimit The rejection limit.
References m_rejectionLimit, and rejectionLimit().
setRmsFromSigmaStatistics()
void Isis::BundleResults::setRmsFromSigmaStatistics (double rmsFromSigmaCoord1Stats, double rmsFromSigmaCoord2Stats, double rmsFromSigmaCoord3Stats)
Sets the root mean square values of the adjusted sigmas for all three coordinates.
Parameters
rmsFromSigmaCoord1Stats The new RMS value of the adjusted coord1 sigmas.
rmsFromSigmaCoord2Stats The new RMS value of the adjusted coord2 sigmas.
rmsFromSigmaCoord3Stats The new RMS value of the adjusted coord3 sigmas.
References m_rmsSigmaCoord1Stats, m_rmsSigmaCoord2Stats, and m_rmsSigmaCoord3Stats.
setRmsImageResidualLists() [1/2]
void Isis::BundleResults::setRmsImageResidualLists (QList< Statistics > rmsImageLineResiduals, QList< Statistics > rmsImageSampleResiduals, QList< Statistics > rmsImageResiduals)
Sets the root mean square image residual Statistics lists.
Parameters
rmsImageLineResiduals The new image line residuals list.
rmsImageSampleResiduals The new image sample residuals list.
rmsImageResiduals The new image residuals list.
References m_rmsImageLineResiduals, m_rmsImageResiduals, m_rmsImageSampleResiduals, rmsImageLineResiduals(), rmsImageResiduals(), and rmsImageSampleResiduals().
setRmsImageResidualLists() [2/2]
void Isis::BundleResults::setRmsImageResidualLists (QVector< Statistics > rmsImageLineResiduals, QVector< Statistics > rmsImageSampleResiduals, QVector< Statistics > rmsImageResiduals)
setRmsLidarImageResidualLists()
void Isis::BundleResults::setRmsLidarImageResidualLists (QList< Statistics > rmsLidarImageLineResiduals, QList< Statistics > rmsLidarImageSampleResiduals, QList< Statistics > rmsLidarImageResiduals)
Sets the root mean square lidar image residual Statistics lists.
Parameters
rmsLidarImageLineResiduals The new image line residuals list.
rmsLidarImageSampleResiduals The new image sample residuals list.
rmsLidarImageResiduals The new image residuals list.
References m_rmsLidarImageLineResiduals, m_rmsLidarImageResiduals, m_rmsLidarImageSampleResiduals, rmsLidarImageLineResiduals(), rmsLidarImageResiduals(), and rmsLidarImageSampleResiduals().
setRmsXYResiduals()
void Isis::BundleResults::setRmsXYResiduals (double rx, double ry, double rxy)
Sets the root mean square of the x and y residuals.
Parameters
rx The RMS value of the x residuals.
ry The RMS value of the y residuals.
rxy The RMS value of both the x and y residuals.
References m_rmsXResiduals, m_rmsXYResiduals, and m_rmsYResiduals.
setSigma0()
void Isis::BundleResults::setSigma0 (double sigma0)
Sets the sigma0.
Parameters
sigma0 The sigma0.
References m_sigma0, and sigma0().
setSigmaCoord1Range()
void Isis::BundleResults::setSigmaCoord1Range (Distance minCoord1Dist, Distance maxCoord1Dist, QString minCoord1PointId, QString maxCoord1PointId)
Sets the min and max sigma distances and point ids for coordinate 1.
Parameters
minLatDist The new minimum sigma latitude distance.
maxLatDist The new maximum sigma latitude distance.
minLatPointId The new minimum sigma latitude point id.
maxLatPointId The new maximum sigma latitude point id.
References m_maxSigmaCoord1Distance, m_maxSigmaCoord1PointId, m_minSigmaCoord1Distance, and m_minSigmaCoord1PointId.
setSigmaCoord2Range()
void Isis::BundleResults::setSigmaCoord2Range (Distance minCoord2Dist, Distance maxCoord2Dist, QString minCoord2PointId, QString maxCoord2PointId)
Sets the min and max sigma distances and point ids for coordinate 2.
Parameters
minLonDist The new minimum sigma longitude distance.
maxLonDist The new maximum sigma longitude distance.
minLonPointId The new minimum sigma longitude point id.
maxLonPointId The new maximum sigma longitude point id.
References m_maxSigmaCoord2Distance, m_maxSigmaCoord2PointId, m_minSigmaCoord2Distance, and m_minSigmaCoord2PointId.
setSigmaCoord3Range()
void Isis::BundleResults::setSigmaCoord3Range (Distance minCoord3Dist, Distance maxCoord3Dist, QString minCoord3PointId, QString maxCoord3PointId)
Sets the min and max sigma distances and point ids for coordinate 3.
Parameters
minRadDist The new minimum sigma radius distance.
maxRadDist The new maximum sigma radius distance.
minRadPointId The new minimum sigma radius point id.
maxRadPointId The new maximum sigma radius point id.
References m_maxSigmaCoord3Distance, m_maxSigmaCoord3PointId, m_minSigmaCoord3Distance, and m_minSigmaCoord3PointId.
sigma0()
double Isis::BundleResults::sigma0 () const
Returns the Sigma0 of the bundle adjustment.
Returns
double The Sigma0.
References m_sigma0.
Referenced by Isis::BundleSolutionInfo::outputHeader(), save(), and setSigma0().
sigmaCoord1StatisticsRms()
double Isis::BundleResults::sigmaCoord1StatisticsRms () const
Returns the RMS of the adjusted sigmas for coordinate 1.
Returns
double The RMS of the adjusted Coord1 sigmas.
References m_rmsSigmaCoord1Stats.
Referenced by Isis::JigsawRunWidget::notifyThreadFinished(), Isis::BundleSolutionInfo::outputText(), and save().
sigmaCoord2StatisticsRms()
double Isis::BundleResults::sigmaCoord2StatisticsRms () const
Returns the RMS of the adjusted sigmas for coordinate 2.
Returns
double The RMS of the adjusted Coord2 sigmas.
References m_rmsSigmaCoord2Stats.
Referenced by Isis::JigsawRunWidget::notifyThreadFinished(), Isis::BundleSolutionInfo::outputText(), and save().
sigmaCoord3StatisticsRms()
double Isis::BundleResults::sigmaCoord3StatisticsRms () const
Returns the RMS of the adjusted sigmas for coordinate 3.
Returns
double The RMS of the adjusted Coord3 sigmas.
References m_rmsSigmaCoord3Stats.
Referenced by Isis::JigsawRunWidget::notifyThreadFinished(), Isis::BundleSolutionInfo::outputText(), and save().
Member Data Documentation
m_bundleControlPoints
QVector<BundleControlPointQsp> Isis::BundleResults::m_bundleControlPoints
The vector of BundleControlPoints from BundleAdjust.
Equivalent to the output control net minus ignored points and measures. The contained points and members hold pointers to the points and measures in the output control net.
Referenced by bundleControlPoints(), operator=(), and setBundleControlPoints().
m_bundleLidarPoints
QVector<BundleLidarControlPointQsp> Isis::BundleResults::m_bundleLidarPoints
Referenced by bundleLidarControlPoints(), operator=(), and setBundleLidarPoints().
m_converged
bool Isis::BundleResults::m_converged
Referenced by converged(), initialize(), operator=(), readGenStatsValues(), and setConverged().
m_correlationMatrix
CorrelationMatrix* Isis::BundleResults::m_correlationMatrix
The correlation matrix from the BundleAdjust.
Referenced by BundleResults(), correlationMatrix(), initialize(), operator=(), readCorrelationMatrix(), setCorrMatCovFileName(), setCorrMatImgsAndParams(), and ~BundleResults().
m_cumPro
StatCumProbDistDynCalc* Isis::BundleResults::m_cumPro
This class will be used to calculate the cumulative probability distribution of |R^2 residuals|, quantiles of this distribution are used to adjust the maximum likelihood functions dynamically iteration by iteration.
Referenced by addProbabilityDistributionObservation(), BundleResults(), cumulativeProbabilityDistribution(), initialize(), initializeProbabilityDistribution(), maximumLikelihoodSetUp(), operator=(), printMaximumLikelihoodTierInformation(), readMaxLikelihoodEstimation(), and ~BundleResults().
m_cumProRes
StatCumProbDistDynCalc* Isis::BundleResults::m_cumProRes
This class keeps track of the cumulative probability distribution of residuals (in unweighted pixels), this is used for reporting, and not for computation.
Referenced by addResidualsProbabilityDistributionObservation(), BundleResults(), initialize(), initializeResidualsProbabilityDistribution(), maximumLikelihoodSetUp(), operator=(), readMaxLikelihoodEstimation(), residualsCumulativeProbabilityDistribution(), and ~BundleResults().
m_degreesOfFreedom
int Isis::BundleResults::m_degreesOfFreedom
degrees of freedom
Referenced by computeDegreesOfFreedom(), computeSigma0(), degreesOfFreedom(), initialize(), operator=(), readGenStatsValues(), and setDegreesOfFreedom().
m_elapsedTime
double Isis::BundleResults::m_elapsedTime
elapsed time for bundle
Referenced by elapsedTime(), initialize(), operator=(), readBundleResults(), and setElapsedTime().
m_elapsedTimeErrorProp
double Isis::BundleResults::m_elapsedTimeErrorProp
elapsed time for error propagation
Referenced by elapsedTimeErrorProp(), initialize(), operator=(), readBundleResults(), and setElapsedTimeErrorProp().
m_iterations
int Isis::BundleResults::m_iterations
The number of iterations taken by BundleAdjust.
Referenced by initialize(), iterations(), operator=(), readGenStatsValues(), and setIterations().
m_maximumLikelihoodFunctions
QList< QPair< MaximumLikelihoodWFunctions, double > > Isis::BundleResults::m_maximumLikelihoodFunctions
< The maximum likelihood models and their quantiles.
The number of maximum likelihood estimation models. Up to three different models can be used in succession. This class is used to reweight observations in order to achieve more robust parameter estimation, up to three different maximum likelihood estimation models can be used in succession. Quantiles of the |residual| distribution to be used for tweaking constants of the maximum probability models.
Referenced by initialize(), maximumLikelihoodModelQuantile(), maximumLikelihoodModelWFunc(), maximumLikelihoodSetUp(), numberMaximumLikelihoodModels(), operator=(), printMaximumLikelihoodTierInformation(), readMaxLikelihoodEstimation(), and save().
m_maximumLikelihoodIndex
int Isis::BundleResults::m_maximumLikelihoodIndex
This count keeps track of which stage of the maximum likelihood adjustment the bundle is currently on.
Referenced by incrementMaximumLikelihoodModelIndex(), initialize(), maximumLikelihoodModelIndex(), maximumLikelihoodSetUp(), operator=(), printMaximumLikelihoodTierInformation(), and readMaxLikelihoodEstimation().
m_maximumLikelihoodMedianR2Residuals
double Isis::BundleResults::m_maximumLikelihoodMedianR2Residuals
Median of R^2 residuals.
Referenced by initialize(), maximumLikelihoodMedianR2Residuals(), maximumLikelihoodSetUp(), operator=(), printMaximumLikelihoodTierInformation(), and readMaxLikelihoodEstimation().
m_maxSigmaCoord1Distance
Distance Isis::BundleResults::m_maxSigmaCoord1Distance
The maximum sigma latitude distance.
Referenced by initialize(), maxSigmaCoord1Distance(), operator=(), readMinMaxSigmas(), and setSigmaCoord1Range().
m_maxSigmaCoord1PointId
QString Isis::BundleResults::m_maxSigmaCoord1PointId
The maximum sigma coordinate 1 point id.
Referenced by initialize(), maxSigmaCoord1PointId(), operator=(), readMinMaxSigmas(), and setSigmaCoord1Range().
m_maxSigmaCoord2Distance
Distance Isis::BundleResults::m_maxSigmaCoord2Distance
The maximum sigma longitude distance.
Referenced by initialize(), maxSigmaCoord2Distance(), operator=(), readMinMaxSigmas(), and setSigmaCoord2Range().
m_maxSigmaCoord2PointId
QString Isis::BundleResults::m_maxSigmaCoord2PointId
The maximum sigma coordinate2 point id.
Referenced by initialize(), maxSigmaCoord2PointId(), operator=(), readMinMaxSigmas(), and setSigmaCoord2Range().
m_maxSigmaCoord3Distance
Distance Isis::BundleResults::m_maxSigmaCoord3Distance
The maximum sigma radius distance.
Referenced by initialize(), maxSigmaCoord3Distance(), operator=(), readMinMaxSigmas(), and setSigmaCoord3Range().
m_maxSigmaCoord3PointId
QString Isis::BundleResults::m_maxSigmaCoord3PointId
The maximum sigma coordinate 3 point id.
Referenced by initialize(), maxSigmaCoord3PointId(), operator=(), readMinMaxSigmas(), and setSigmaCoord3Range().
m_minSigmaCoord1Distance
Distance Isis::BundleResults::m_minSigmaCoord1Distance
The minimum sigma latitude distance.
Referenced by initialize(), minSigmaCoord1Distance(), operator=(), readMinMaxSigmas(), and setSigmaCoord1Range().
m_minSigmaCoord1PointId
QString Isis::BundleResults::m_minSigmaCoord1PointId
The minimum sigma coordinate 1 point id.
Referenced by initialize(), minSigmaCoord1PointId(), operator=(), readMinMaxSigmas(), and setSigmaCoord1Range().
m_minSigmaCoord2Distance
Distance Isis::BundleResults::m_minSigmaCoord2Distance
The minimum sigma longitude distance.
Referenced by initialize(), minSigmaCoord2Distance(), operator=(), readMinMaxSigmas(), and setSigmaCoord2Range().
m_minSigmaCoord2PointId
QString Isis::BundleResults::m_minSigmaCoord2PointId
The minimum sigma coordinate 2 point id.
Referenced by initialize(), minSigmaCoord2PointId(), operator=(), readMinMaxSigmas(), and setSigmaCoord2Range().
m_minSigmaCoord3Distance
Distance Isis::BundleResults::m_minSigmaCoord3Distance
The minimum sigma radius distance.
Referenced by initialize(), minSigmaCoord3Distance(), operator=(), readMinMaxSigmas(), and setSigmaCoord3Range().
m_minSigmaCoord3PointId
QString Isis::BundleResults::m_minSigmaCoord3PointId
The minimum sigma coordinate 3 point id.
Referenced by initialize(), minSigmaCoord3PointId(), operator=(), readMinMaxSigmas(), and setSigmaCoord3Range().
m_numberConstrainedImageParameters
int Isis::BundleResults::m_numberConstrainedImageParameters
number of constrained image parameters
Referenced by computeDegreesOfFreedom(), incrementNumberConstrainedImageParameters(), initialize(), numberConstrainedImageParameters(), operator=(), readGenStatsValues(), and resetNumberConstrainedImageParameters().
m_numberConstrainedLidarPointParameters
int Isis::BundleResults::m_numberConstrainedLidarPointParameters
lidar points
Referenced by computeDegreesOfFreedom(), initialize(), operator=(), and setNumberConstrainedLidarPointParameters().
m_numberConstrainedPointParameters
int Isis::BundleResults::m_numberConstrainedPointParameters
number of constrained point parameters
Referenced by computeDegreesOfFreedom(), incrementNumberConstrainedPointParameters(), initialize(), numberConstrainedPointParameters(), operator=(), readGenStatsValues(), resetNumberConstrainedPointParameters(), and setNumberConstrainedPointParameters().
m_numberConstrainedTargetParameters
int Isis::BundleResults::m_numberConstrainedTargetParameters
number of constrained target parameters
Referenced by computeDegreesOfFreedom(), incrementNumberConstrainedTargetParameters(), initialize(), numberConstrainedTargetParameters(), operator=(), readGenStatsValues(), and resetNumberConstrainedTargetParameters().
m_numberFixedPoints
int Isis::BundleResults::m_numberFixedPoints
number of 'fixed' (ground) points (define)
Referenced by incrementFixedPoints(), initialize(), numberFixedPoints(), operator=(), and readGenStatsValues().
m_numberHeldImages
int Isis::BundleResults::m_numberHeldImages
number of 'held' images (define)
Referenced by incrementHeldImages(), initialize(), numberHeldImages(), operator=(), and readGenStatsValues().
m_numberIgnoredPoints
int Isis::BundleResults::m_numberIgnoredPoints
number of ignored points
Referenced by incrementIgnoredPoints(), initialize(), numberIgnoredPoints(), operator=(), and readGenStatsValues().
m_numberImageObservations
int Isis::BundleResults::m_numberImageObservations
photogrammetry image coords. (2 per measure)
Referenced by computeDegreesOfFreedom(), initialize(), numberImageObservations(), numberObservations(), operator=(), readGenStatsValues(), and setNumberImageObservations().
m_numberImageParameters
int Isis::BundleResults::m_numberImageParameters
number of image parameters
Referenced by initialize(), numberImageParameters(), operator=(), readGenStatsValues(), and setNumberImageParameters().
m_numberLidarImageObservations
int Isis::BundleResults::m_numberLidarImageObservations
lidar image coords. (2 per measure)
Referenced by computeDegreesOfFreedom(), initialize(), numberLidarImageObservations(), numberObservations(), operator=(), readGenStatsValues(), and setNumberLidarImageObservations().
m_numberLidarRangeConstraintEquations
int Isis::BundleResults::m_numberLidarRangeConstraintEquations
lidar range constraint equations
Referenced by computeDegreesOfFreedom(), initialize(), numberLidarRangeConstraintEquations(), operator=(), readGenStatsValues(), and setNumberLidarRangeConstraints().
m_numberObservations
int Isis::BundleResults::m_numberObservations
number of image coordinate observations
Referenced by initialize(), operator=(), readGenStatsValues(), and setNumberObservations().
m_numberRejectedObservations
int Isis::BundleResults::m_numberRejectedObservations
number of rejected image coordinate observations
Referenced by initialize(), numberRejectedObservations(), operator=(), readGenStatsValues(), and setNumberRejectedObservations().
m_numberUnknownParameters
int Isis::BundleResults::m_numberUnknownParameters
total number of parameters to solve for
Referenced by computeDegreesOfFreedom(), initialize(), numberUnknownParameters(), operator=(), readGenStatsValues(), and setNumberUnknownParameters().
m_observations
BundleObservationVector Isis::BundleResults::m_observations
The vector of BundleObservations from BundleAdjust.
Referenced by initialize(), observations(), operator=(), and setObservations().
m_outLidarData
LidarDataQsp Isis::BundleResults::m_outLidarData
Output lidar data from BundleAdjust.
Referenced by initialize(), operator=(), outputLidarData(), and setOutputLidarData().
m_outNet
ControlNetQsp Isis::BundleResults::m_outNet
The output control net from BundleAdjust.
Referenced by coordTypeReports(), initialize(), operator=(), outputControlNet(), save(), and setOutputControlNet().
m_rejectionLimit
double Isis::BundleResults::m_rejectionLimit
current rejection limit
Referenced by initialize(), operator=(), readGenStatsValues(), rejectionLimit(), and setRejectionLimit().
m_rmsImageDECSigmas
QVector<Statistics> Isis::BundleResults::m_rmsImageDECSigmas
< The root mean square image declination sigmas.
Referenced by initialize(), operator=(), readSigmasLists(), resizeSigmaStatisticsVectors(), rmsImageDECSigmas(), and save().
m_rmsImageLineResiduals
QList<Statistics> Isis::BundleResults::m_rmsImageLineResiduals
List of RMS image line residual statistics for each image in the bundle
Referenced by initialize(), operator=(), readImageResidualsLists(), rmsImageLineResiduals(), save(), and setRmsImageResidualLists().
m_rmsImageRASigmas
QVector<Statistics> Isis::BundleResults::m_rmsImageRASigmas
< The root mean square image right ascension sigmas.
Referenced by initialize(), operator=(), readSigmasLists(), resizeSigmaStatisticsVectors(), rmsImageRASigmas(), and save().
m_rmsImageResiduals
QList<Statistics> Isis::BundleResults::m_rmsImageResiduals
RMS image sample and line residual statistics for each image in the bundle
Referenced by initialize(), operator=(), readImageResidualsLists(), rmsImageResiduals(), save(), and setRmsImageResidualLists().
m_rmsImageSampleResiduals
QList<Statistics> Isis::BundleResults::m_rmsImageSampleResiduals
List of RMS image sample residual statistics for each image in the bundle
Referenced by initialize(), operator=(), readImageResidualsLists(), rmsImageSampleResiduals(), save(), and setRmsImageResidualLists().
m_rmsImageTWISTSigmas
QVector<Statistics> Isis::BundleResults::m_rmsImageTWISTSigmas
< The root mean square image twist sigmas.
Referenced by initialize(), operator=(), readSigmasLists(), resizeSigmaStatisticsVectors(), rmsImageTWISTSigmas(), and save().
m_rmsImageXSigmas
QVector<Statistics> Isis::BundleResults::m_rmsImageXSigmas
Referenced by initialize(), operator=(), readSigmasLists(), resizeSigmaStatisticsVectors(), rmsImageXSigmas(), and save().
m_rmsImageYSigmas
QVector<Statistics> Isis::BundleResults::m_rmsImageYSigmas
< The root mean square image y sigmas.
Referenced by initialize(), operator=(), readSigmasLists(), resizeSigmaStatisticsVectors(), rmsImageYSigmas(), and save().
m_rmsImageZSigmas
QVector<Statistics> Isis::BundleResults::m_rmsImageZSigmas
< The root mean square image z sigmas.
Referenced by initialize(), operator=(), readSigmasLists(), resizeSigmaStatisticsVectors(), rmsImageZSigmas(), and save().
m_rmsLidarImageLineResiduals
QList<Statistics> Isis::BundleResults::m_rmsLidarImageLineResiduals
List of RMS lidar line residual stats for each image in the bundle
Referenced by initialize(), operator=(), readImageResidualsLists(), rmsLidarImageLineResiduals(), save(), and setRmsLidarImageResidualLists().
m_rmsLidarImageResiduals
QList<Statistics> Isis::BundleResults::m_rmsLidarImageResiduals
RMS image lidar sample & line residual stats for each image in the bundle
The root mean square image x sigmas.
Referenced by initialize(), operator=(), readImageResidualsLists(), rmsLidarImageResiduals(), save(), and setRmsLidarImageResidualLists().
m_rmsLidarImageSampleResiduals
QList<Statistics> Isis::BundleResults::m_rmsLidarImageSampleResiduals
List of RMS lidar sample residual stats for each image in the bundle
Referenced by initialize(), operator=(), readImageResidualsLists(), rmsLidarImageSampleResiduals(), save(), and setRmsLidarImageResidualLists().
m_rmsSigmaCoord1Stats
double Isis::BundleResults::m_rmsSigmaCoord1Stats
rms of adjusted Latitude sigmas
Referenced by initialize(), operator=(), readRms(), setRmsFromSigmaStatistics(), and sigmaCoord1StatisticsRms().
m_rmsSigmaCoord2Stats
double Isis::BundleResults::m_rmsSigmaCoord2Stats
rms of adjusted Longitude sigmas
Referenced by initialize(), operator=(), readRms(), setRmsFromSigmaStatistics(), and sigmaCoord2StatisticsRms().
m_rmsSigmaCoord3Stats
double Isis::BundleResults::m_rmsSigmaCoord3Stats
rms of adjusted Radius sigmas
Referenced by initialize(), operator=(), readRms(), setRmsFromSigmaStatistics(), and sigmaCoord3StatisticsRms().
m_rmsXResiduals
double Isis::BundleResults::m_rmsXResiduals
rms of x residuals
Referenced by initialize(), operator=(), readRms(), rmsRx(), and setRmsXYResiduals().
m_rmsXYResiduals
double Isis::BundleResults::m_rmsXYResiduals
rms of all x and y residuals
Referenced by initialize(), operator=(), readRms(), rmsRxy(), and setRmsXYResiduals().
m_rmsYResiduals
double Isis::BundleResults::m_rmsYResiduals
rms of y residuals
Referenced by initialize(), operator=(), readRms(), rmsRy(), and setRmsXYResiduals().
m_sigma0
double Isis::BundleResults::m_sigma0
std deviation of unit weight
Referenced by computeSigma0(), initialize(), operator=(), readGenStatsValues(), setSigma0(), and sigma0().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/BundleResults/BundleResults.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/BundleResults/BundleResults.cpp