Isis Developer Reference: Isis::MosaicSceneWidget Class Reference
Isis::MosaicSceneWidget Class Reference
This widget encompasses the entire mosaic scene.
#include <MosaicSceneWidget.h>
Public Slots
void addImages (ImageList)
void removeImages (ImageList)
void refit ()
This method refits t:he items in the graphics view.
void setCubesSelectable (bool)
void setProjection (Projection *)
This method takes ownership of proj.
void setOutlineRect (QRectF)
Signals
void mouseEnter ()
void mouseMove (QPointF)
void mouseLeave ()
void mouseDoubleClick (QPointF)
void mouseButtonPress (QPointF, Qt::MouseButton s)
void mouseButtonRelease (QPointF, Qt::MouseButton s)
void mouseWheel (QPointF, int delta)
void projectionChanged (Projection *)
void rubberBandComplete (QRectF r, Qt::MouseButton s)
void visibleRectChanged (QRectF)
void cubesChanged ()
void queueSelectionChanged ()
void modifyControlPoint (ControlPoint *controlPoint)
void deleteControlPoint (ControlPoint *controlPoint)
void createControlPoint (double latitude, double longitude)
void controlPointSelected (ControlPoint *)
void cnetModified ()
void controlPointChanged (QString pointId)
void controlPointDeleted ()
void mosCubeClosed (Image *)
Public Member Functions
MosaicSceneWidget (QStatusBar *status, bool showTools, bool internalizeToolBarsAndProgress, Directory *directory, QWidget *parent=0)
Create a scene widget.
virtual ~MosaicSceneWidget ()
MosaicGraphicsView * getView () const
QGraphicsScene * getScene () const
Projection * getProjection () const
QList< MosaicSceneItem * > allMosaicSceneItems ()
void addTo (QMenu *menu)
void addTo (ToolPad *toolPad)
void addToPermanent (QToolBar *toolBar)
void addTo (QToolBar *toolBar)
bool contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
This is called by MosaicGraphicsScene::contextMenuEvent.
MosaicSceneItem * cubeToMosaic (Image *)
bool cubesSelectable () const
void enableRubberBand (bool)
bool blockSelectionChange (bool)
bool userHasTools () const
QProgressBar * getProgress ()
PvlObject toPvl () const
void fromPvl (const PvlObject &)
Call this method after loading any cubes when loading a project.
void save (QXmlStreamWriter &stream, Project *project, FileName newProjectRoot) const
QRectF cubesBoundingRect () const
QStringList cubeFileNames ()
Directory * directory () const
ImageList images ()
ImageList selectedImages ()
Returns a list of all the cubes selected in the scene.
QList< QAction * > getExportActions ()
QList< QAction * > getViewActions ()
QList< QAction * > supportedActions (ImageList *)
Get a list of actions this scene can perform given "images".
double moveDownOne (MosaicSceneItem *)
double moveDownOne (Image *)
QList< double > moveDownOne (ImageList *)
double moveToBottom (MosaicSceneItem *)
This doesn't compress the Z values - the original Z values of this scene item is guaranteed to be empty after this operation.
double moveToBottom (Image *)
This doesn't compress the Z values - the original Z value of this image is guaranteed to be empty after this operation.
QList< double > moveToBottom (ImageList *)
This doesn't compress the Z values - the original Z values of these images are guaranteed to be empty after this operation.
double moveUpOne (MosaicSceneItem *)
double moveUpOne (Image *)
QList< double > moveUpOne (ImageList *)
double moveToTop (MosaicSceneItem *)
This doesn't compress the Z values - the original Z values of this scene item is guaranteed to be empty after this operation.
double moveToTop (Image *)
This doesn't compress the Z values - the original Z value of this image is guaranteed to be empty after this operation.
QList< double > moveToTop (ImageList *)
This doesn't compress the Z values - the original Z values of these images are guaranteed to be empty after this operation.
double moveZ (MosaicSceneItem *sceneItem, double newZ, bool newZValueMightExist=true)
This method moves the given scene item to the given Z value.
double moveZ (Image *image, double newZ, bool newZValueMightExist=true)
template<typename DataType >
QList< QAction * > supportedActions (DataType)
Return an empty list of actions for unknown data types.
bool isControlNetToolActive ()
Static Public Member Functions
static QWidget * getControlNetHelp (QWidget *cnetToolContainer=NULL)
static QWidget * getGridHelp (QWidget *gridToolContainer=NULL)
static QWidget * getLongHelp (QWidget *mosaicSceneContainer=NULL)
static QWidget * getMapHelp (QWidget *mapContainer=NULL)
static QWidget * getPreviewHelp (QWidget *worldViewContainer=NULL)
Protected Member Functions
virtual bool eventFilter (QObject *obj, QEvent *ev)
Detailed Description
This widget encompasses the entire mosaic scene.
This widget is a self-contained 2D footprint view using Qt's graphics scene/view framework.
Author
????-??-?? Stacy Alley
Constructor & Destructor Documentation
MosaicSceneWidget()
Isis::MosaicSceneWidget::MosaicSceneWidget (QStatusBar * status, bool showTools, bool internalizeToolBarsAndProgress, Directory * directory, QWidget * parent = 0)
Create a scene widget.
References addTo(), addToPermanent(), cnetModified(), createControlPoint(), deleteControlPoint(), directory(), Isis::MosaicGraphicsView::enableResizeZooming(), getScene(), getView(), modifyControlPoint(), and queueSelectionChanged().
~MosaicSceneWidget()
Isis::MosaicSceneWidget::~MosaicSceneWidget () virtual
Member Function Documentation
addImages
void Isis::MosaicSceneWidget::addImages (ImageList images) slot
References cubesChanged(), getView(), images(), Isis::IException::print(), refit(), Isis::ProgressBar::setText(), and Isis::toInt().
addTo() [1/3]
void Isis::MosaicSceneWidget::addTo (QMenu * menu)
References Isis::MosaicTool::addTo().
Referenced by Isis::Footprint2DView::Footprint2DView(), and MosaicSceneWidget().
addTo() [2/3]
void Isis::MosaicSceneWidget::addTo (QToolBar * toolBar)
References Isis::MosaicTool::addTo().
addTo() [3/3]
void Isis::MosaicSceneWidget::addTo (ToolPad * toolPad)
References Isis::MosaicTool::addTo().
addToPermanent()
void Isis::MosaicSceneWidget::addToPermanent (QToolBar * toolBar)
References Isis::PvlContainer::findKeyword(), and Isis::Projection::Mapping().
Referenced by Isis::Footprint2DView::Footprint2DView(), and MosaicSceneWidget().
allMosaicSceneItems()
QList<MosaicSceneItem *> Isis::MosaicSceneWidget::allMosaicSceneItems () inline
blockSelectionChange()
bool Isis::MosaicSceneWidget::blockSelectionChange (bool block)
Referenced by Isis::MosaicSceneItem::cubeDisplayChanged(), and Isis::MosaicSceneItem::updateSelection().
cnetModified
void Isis::MosaicSceneWidget::cnetModified () signal
Referenced by MosaicSceneWidget().
contextMenuEvent()
bool Isis::MosaicSceneWidget::contextMenuEvent (QGraphicsSceneContextMenuEvent * event)
This is called by MosaicGraphicsScene::contextMenuEvent.
Return false if not handled, true if handled.
References Isis::ImageList::append(), getScene(), Isis::MosaicSceneItem::image(), Isis::Directory::project(), selectedImages(), Isis::Directory::supportedActions(), and Isis::ImageList::supportedActions().
controlPointChanged
void Isis::MosaicSceneWidget::controlPointChanged (QString pointId) signal
controlPointDeleted
void Isis::MosaicSceneWidget::controlPointDeleted () signal
controlPointSelected
void Isis::MosaicSceneWidget::controlPointSelected (ControlPoint *) signal
createControlPoint
void Isis::MosaicSceneWidget::createControlPoint (double latitude, double longitude) signal
Referenced by MosaicSceneWidget().
cubeFileNames()
QStringList Isis::MosaicSceneWidget::cubeFileNames ()
References Isis::Image::fileName(), and Isis::MosaicSceneItem::image().
Referenced by Isis::ControlNetGraphicsItem::buildChildren().
cubesBoundingRect()
QRectF Isis::MosaicSceneWidget::cubesBoundingRect () const
References Isis::MosaicSceneItem::boundingRect().
Referenced by Isis::MosaicGridTool::autoGrid(), Isis::MosaicGridTool::getToolBarWidget(), Isis::MosaicGridTool::MosaicGridTool(), refit(), Isis::MosaicGridTool::setLatExtents(), and Isis::MosaicGridTool::setLonExtents().
cubesChanged
void Isis::MosaicSceneWidget::cubesChanged () signal
Referenced by addImages().
cubesSelectable()
bool Isis::MosaicSceneWidget::cubesSelectable () const inline
cubeToMosaic()
MosaicSceneItem * Isis::MosaicSceneWidget::cubeToMosaic (Image * image)
References _FILEINFO_, Isis::Image::displayProperties(), and Isis::IException::Programmer.
Referenced by moveDownOne(), moveToBottom(), moveToTop(), moveUpOne(), moveZ(), removeImages(), and supportedActions().
deleteControlPoint
void Isis::MosaicSceneWidget::deleteControlPoint (ControlPoint * controlPoint) signal
Referenced by MosaicSceneWidget().
directory()
Directory * Isis::MosaicSceneWidget::directory () const
Referenced by Isis::MosaicSceneItem::contextMenuEvent(), Isis::MosaicControlNetTool::loadNetwork(), MosaicSceneWidget(), and Isis::ControlPointGraphicsItem::paint().
enableRubberBand()
void Isis::MosaicSceneWidget::enableRubberBand (bool enable)
Referenced by Isis::MosaicZoomTool::updateTool().
eventFilter()
bool Isis::MosaicSceneWidget::eventFilter (QObject * obj, QEvent * ev) protected virtual
References getScene(), getView(), mouseButtonPress(), mouseButtonRelease(), mouseDoubleClick(), mouseEnter(), mouseLeave(), mouseMove(), mouseWheel(), and rubberBandComplete().
fromPvl()
void Isis::MosaicSceneWidget::fromPvl (const PvlObject & project)
Call this method after loading any cubes when loading a project.
Parameters
project The project Pvl
References Isis::PvlObject::findGroup(), Isis::PvlObject::findObject(), Isis::MosaicTool::fromPvl(), Isis::PvlObject::hasObject(), Isis::PvlContainer::keywords(), Isis::MosaicTool::projectPvlObjectName(), setProjection(), and Isis::toDouble().
getControlNetHelp()
QWidget * Isis::MosaicSceneWidget::getControlNetHelp (QWidget * cnetToolContainer = NULL) static
References Isis::MosaicTool::addTo().
getExportActions()
QList< QAction * > Isis::MosaicSceneWidget::getExportActions ()
getGridHelp()
QWidget * Isis::MosaicSceneWidget::getGridHelp (QWidget * gridToolContainer = NULL) static
References Isis::MosaicTool::addTo().
getLongHelp()
QWidget * Isis::MosaicSceneWidget::getLongHelp (QWidget * mosaicSceneContainer = NULL) static
getMapHelp()
QWidget * Isis::MosaicSceneWidget::getMapHelp (QWidget * mapContainer = NULL) static
getPreviewHelp()
QWidget * Isis::MosaicSceneWidget::getPreviewHelp (QWidget * worldViewContainer = NULL) static
getProgress()
QProgressBar * Isis::MosaicSceneWidget::getProgress ()
Referenced by Isis::ControlNetGraphicsItem::buildChildren().
getProjection()
Projection* Isis::MosaicSceneWidget::getProjection () const inline
Referenced by Isis::MosaicGridToolConfigDialog::applySettings(), Isis::MosaicGridTool::autoGrid(), Isis::MosaicGridTool::domainMaxLon(), Isis::MosaicGridTool::domainMinLon(), Isis::MosaicGridTool::fromPvl(), Isis::MosaicFindTool::getUserGroundPoint(), Isis::GridGraphicsItem::GridGraphicsItem(), Isis::MosaicGridTool::latType(), Isis::MosaicGridTool::lonDomain(), Isis::MosaicSceneItem::MosaicSceneItem(), Isis::MosaicControlNetTool::mouseButtonRelease(), Isis::MosaicAreaTool::mouseButtonRelease(), Isis::MosaicFindTool::mouseButtonRelease(), Isis::MosaicGridTool::onProjectionChanged(), Isis::MosaicGridToolConfigDialog::readSettings(), Isis::MosaicSceneItem::reproject(), Isis::MosaicGridTool::setLatExtents(), Isis::MosaicGridTool::setLonExtents(), Isis::MosaicTrackTool::updateLabels(), and Isis::MosaicAreaTool::userChangedBox().
getScene()
QGraphicsScene* Isis::MosaicSceneWidget::getScene () const inline
Referenced by Isis::MosaicAreaTool::clearBox(), Isis::MosaicGridTool::clearGrid(), Isis::MosaicFindTool::clearPoint(), contextMenuEvent(), Isis::ControlNetGraphicsItem::ControlNetGraphicsItem(), Isis::MosaicGridTool::drawGrid(), eventFilter(), Isis::Footprint2DView::Footprint2DView(), Isis::MosaicFindTool::getUserGroundPoint(), MosaicSceneWidget(), Isis::MosaicControlNetTool::mouseButtonRelease(), Isis::MosaicFindTool::mouseButtonRelease(), selectedImages(), setOutlineRect(), and Isis::MosaicAreaTool::userChangedBox().
getView()
MosaicGraphicsView* Isis::MosaicSceneWidget::getView () const inline
Referenced by addImages(), eventFilter(), Isis::ControlNetGraphicsItem::findClosestControlPoint(), Isis::Footprint2DView::Footprint2DView(), Isis::MosaicFindTool::getUserGroundPoint(), MosaicSceneWidget(), Isis::MosaicControlNetTool::mouseButtonRelease(), Isis::MosaicAreaTool::mouseButtonRelease(), Isis::MosaicFindTool::mouseButtonRelease(), Isis::MosaicZoomTool::mouseWheel(), Isis::MosaicGridTool::onCubesChanged(), refit(), Isis::MosaicZoomTool::rubberBandComplete(), save(), setOutlineRect(), toPvl(), Isis::MosaicZoomTool::updateResolutionBox(), Isis::MosaicPanTool::updateTool(), Isis::MosaicSelectTool::updateTool(), Isis::MosaicZoomTool::updateTool(), and Isis::MosaicAreaTool::userChangedBox().
getViewActions()
QList< QAction * > Isis::MosaicSceneWidget::getViewActions ()
References Isis::MosaicTool::getViewActions().
images()
ImageList Isis::MosaicSceneWidget::images ()
References Isis::ImageList::append(), and Isis::MosaicSceneItem::image().
Referenced by addImages(), moveDownOne(), moveToBottom(), moveToTop(), moveUpOne(), removeImages(), and supportedActions().
isControlNetToolActive()
bool Isis::MosaicSceneWidget::isControlNetToolActive ()
References Isis::MosaicTool::isActive().
modifyControlPoint
void Isis::MosaicSceneWidget::modifyControlPoint (ControlPoint * controlPoint) signal
Referenced by MosaicSceneWidget().
mosCubeClosed
void Isis::MosaicSceneWidget::mosCubeClosed (Image *) signal
mouseButtonPress
void Isis::MosaicSceneWidget::mouseButtonPress (QPointF , Qt::MouseButton s) signal
Referenced by eventFilter().
mouseButtonRelease
void Isis::MosaicSceneWidget::mouseButtonRelease (QPointF , Qt::MouseButton s) signal
Referenced by eventFilter().
mouseDoubleClick
void Isis::MosaicSceneWidget::mouseDoubleClick (QPointF) signal
Referenced by eventFilter().
mouseEnter
void Isis::MosaicSceneWidget::mouseEnter () signal
Referenced by eventFilter().
mouseLeave
void Isis::MosaicSceneWidget::mouseLeave () signal
Referenced by eventFilter().
mouseMove
void Isis::MosaicSceneWidget::mouseMove (QPointF) signal
Referenced by eventFilter().
mouseWheel
void Isis::MosaicSceneWidget::mouseWheel (QPointF , int delta) signal
Referenced by eventFilter().
moveDownOne() [1/3]
double Isis::MosaicSceneWidget::moveDownOne (Image * image)
References cubeToMosaic(), and moveDownOne().
moveDownOne() [2/3]
QList< double > Isis::MosaicSceneWidget::moveDownOne (ImageList * images)
References images(), and moveDownOne().
moveDownOne() [3/3]
double Isis::MosaicSceneWidget::moveDownOne (MosaicSceneItem * item)
References moveZ().
Referenced by moveDownOne().
moveToBottom() [1/3]
double Isis::MosaicSceneWidget::moveToBottom (Image * image)
This doesn't compress the Z values - the original Z value of this image is guaranteed to be empty after this operation.
References cubeToMosaic(), and moveToBottom().
moveToBottom() [2/3]
QList< double > Isis::MosaicSceneWidget::moveToBottom (ImageList * images)
This doesn't compress the Z values - the original Z values of these images are guaranteed to be empty after this operation.
References images(), and moveToBottom().
moveToBottom() [3/3]
double Isis::MosaicSceneWidget::moveToBottom (MosaicSceneItem * item)
This doesn't compress the Z values - the original Z values of this scene item is guaranteed to be empty after this operation.
Referenced by moveToBottom().
moveToTop() [1/3]
double Isis::MosaicSceneWidget::moveToTop (Image * image)
This doesn't compress the Z values - the original Z value of this image is guaranteed to be empty after this operation.
References cubeToMosaic(), and moveToTop().
moveToTop() [2/3]
QList< double > Isis::MosaicSceneWidget::moveToTop (ImageList * images)
This doesn't compress the Z values - the original Z values of these images are guaranteed to be empty after this operation.
References images(), and moveToTop().
moveToTop() [3/3]
double Isis::MosaicSceneWidget::moveToTop (MosaicSceneItem * item)
This doesn't compress the Z values - the original Z values of this scene item is guaranteed to be empty after this operation.
Referenced by moveToTop().
moveUpOne() [1/3]
double Isis::MosaicSceneWidget::moveUpOne (Image * image)
References cubeToMosaic(), and moveUpOne().
moveUpOne() [2/3]
QList< double > Isis::MosaicSceneWidget::moveUpOne (ImageList * images)
References images(), and moveUpOne().
moveUpOne() [3/3]
double Isis::MosaicSceneWidget::moveUpOne (MosaicSceneItem * item)
References moveZ().
Referenced by moveUpOne().
moveZ() [1/2]
double Isis::MosaicSceneWidget::moveZ (Image * image, double newZ, bool newZValueMightExist = true)
References cubeToMosaic(), and moveZ().
moveZ() [2/2]
double Isis::MosaicSceneWidget::moveZ (MosaicSceneItem * sceneItem, double newZ, bool newZValueMightExist = true)
This method moves the given scene item to the given Z value.
By default, this does not create gaps in the Z-values and makes the necessary room/adjustments for the new item to go to it's spot. If the last operation was moveToTop or moveToBottom, because those methods don't compress/adjust the surrounding Z values, we can avoid any and all adjustments here (significant performance boost) by using newZValueMightExist=false.
N = # items in the scene The time complexity of this method is N if newZValueMightExist. The time complexity of this method is constant if !newZValueMightExist.
Parameters
sceneItem The item in this scene to change the Z value
newZ The new Z value for the item
newZValueMightExist True if an item in the scene might occupy the new Z value
Referenced by moveDownOne(), moveUpOne(), moveZ(), and Isis::MosaicSceneWorkOrder::restoreZPositions().
projectionChanged
void Isis::MosaicSceneWidget::projectionChanged (Projection *) signal
Referenced by setProjection().
queueSelectionChanged
void Isis::MosaicSceneWidget::queueSelectionChanged () signal
Referenced by MosaicSceneWidget().
refit
void Isis::MosaicSceneWidget::refit () slot
This method refits t:he items in the graphics view.
References cubesBoundingRect(), and getView().
Referenced by addImages(), setOutlineRect(), and Isis::MosaicZoomTool::zoomFit().
removeImages
void Isis::MosaicSceneWidget::removeImages (ImageList images) slot
References cubeToMosaic(), images(), and Isis::IException::print().
rubberBandComplete
void Isis::MosaicSceneWidget::rubberBandComplete (QRectF r, Qt::MouseButton s) signal
Referenced by eventFilter().
save()
void Isis::MosaicSceneWidget::save (QXmlStreamWriter & stream, Project * project, FileName newProjectRoot) const
References getView(), Isis::Image::id(), Isis::MosaicSceneItem::image(), Isis::Projection::Mapping(), Isis::MosaicTool::projectPvlObjectName(), Isis::ReadWrite, Isis::PvlContainer::setName(), Isis::MosaicTool::toPvl(), and Isis::toString().
Referenced by Isis::Footprint2DView::save().
selectedImages()
ImageList Isis::MosaicSceneWidget::selectedImages ()
Returns a list of all the cubes selected in the scene.
Returns
QList<Cube *>
References Isis::ImageList::append(), getScene(), and Isis::MosaicSceneItem::image().
Referenced by contextMenuEvent().
setCubesSelectable
void Isis::MosaicSceneWidget::setCubesSelectable (bool selectable) slot
References Isis::MosaicSceneItem::scenePropertiesChanged().
Referenced by Isis::MosaicPanTool::updateTool(), and Isis::MosaicZoomTool::updateTool().
setOutlineRect
void Isis::MosaicSceneWidget::setOutlineRect (QRectF outline) slot
References getScene(), getView(), and refit().
setProjection
void Isis::MosaicSceneWidget::setProjection (Projection * proj) slot
This method takes ownership of proj.
References Isis::PvlContainer::findKeyword(), Isis::Projection::Mapping(), and projectionChanged().
Referenced by fromPvl().
supportedActions() [1/2]
template<typename DataType > QList<QAction *> Isis::MosaicSceneWidget::supportedActions (DataType) inline
Return an empty list of actions for unknown data types.
supportedActions() [2/2]
QList< QAction * > Isis::MosaicSceneWidget::supportedActions (ImageList * images)
Get a list of actions this scene can perform given "images".
References cubeToMosaic(), images(), Isis::Directory::project(), and Isis::WorkOrder::setData().
toPvl()
PvlObject Isis::MosaicSceneWidget::toPvl () const
References _FILEINFO_, getView(), Isis::Image::id(), Isis::MosaicSceneItem::image(), Isis::Projection::Mapping(), Isis::MosaicTool::projectPvlObjectName(), Isis::ReadWrite, Isis::PvlContainer::setName(), Isis::MosaicTool::toPvl(), Isis::toString(), and Isis::IException::User.
userHasTools()
bool Isis::MosaicSceneWidget::userHasTools () const inline
Referenced by Isis::MosaicSceneItem::MosaicSceneItem().
visibleRectChanged
void Isis::MosaicSceneWidget::visibleRectChanged (QRectF) signal
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/MosaicSceneWidget.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/MosaicSceneWidget.cpp