Isis Developer Reference: Isis::ExportDescription Class Reference
Isis::ExportDescription Class Reference
High Level Cube I/O
Describes how a series of cubes should be exported.
#include <ExportDescription.h>
Classes
class ChannelDescription
Describes how a cube as a single color channel to be exported.
Public Member Functions
ExportDescription ()
Construct the export description.
ExportDescription (const ExportDescription &descriptionToCopy)
Copy constructor for the export description.
virtual ~ExportDescription ()
Destruct the export description.
ExportDescription & operator= (const ExportDescription &descriptionToCopy)
Assignment operator for the export description.
void setPixelType (PixelType type)
Set the pixel type for the output image.
PixelType pixelType () const
Returns the pixel type.
double outputPixelNull () const
Returns the output pixel value for Null DNs.
double outputPixelValidMin () const
Returns the output pixel value for the valid minimum.
double outputPixelValidMax () const
Returns the output pixel value for the valid maximum.
double outputPixelAbsoluteMin () const
Returns the absolute minimum value for output pixels.
double outputPixelAbsoluteMax () const
Returns the absolute maximum value for output pixels.
int addChannel (FileName filename, CubeAttributeInput &att)
Add an export color channel for the given input cube and attributes (typically band number).
int addChannel (FileName filename, CubeAttributeInput &att, double min, double max)
Add an export color channel for the given input cube, attributes (typically band number), and input DN range.
const ChannelDescription & channel (int i) const
Return the channels description at the given index.
int channelCount () const
Count of the number of channels in the description.
Detailed Description
Describes how a series of cubes should be exported.
This container class encapsulates the parameters required to specify how an Isis cube should be exported to a standard image format. This encapsulation is useful to applications like "isis2std" for passing its user parameters down to processing classes such as ImageExporters without needing to create new method signatures that take a growing list of parameters. The ExportDescription contains top-level data about the export as a whole, such as bit type. It also contains a list of ChannelDescriptions, each describing the input cubes, attributes, and DN ranges for a channel of color information (gray, red, blue, green, or alpha).
Author
2012-04-03 Travis Addair
Constructor & Destructor Documentation
ExportDescription() [1/2]
Isis::ExportDescription::ExportDescription ()
Construct the export description.
References Isis::None.
ExportDescription() [2/2]
Isis::ExportDescription::ExportDescription (const ExportDescription & descriptionToCopy)
Copy constructor for the export description.
Parameters
descriptionToCopy ExportDescription to be copied.
References addChannel(), Isis::ExportDescription::ChannelDescription::attributes(), channel(), channelCount(), Isis::ExportDescription::ChannelDescription::filename(), Isis::ExportDescription::ChannelDescription::hasCustomRange(), Isis::ExportDescription::ChannelDescription::inputMaximum(), Isis::ExportDescription::ChannelDescription::inputMinimum(), and setPixelType().
~ExportDescription()
Isis::ExportDescription::~ExportDescription () virtual
Destruct the export description.
Also deletes the list of channels.
Member Function Documentation
addChannel() [1/2]
int Isis::ExportDescription::addChannel (FileName filename, CubeAttributeInput & att)
Add an export color channel for the given input cube and attributes (typically band number).
Parameters
filename The name of the cube
att The cube attributes such as band number
Returns
The index of the newly added channel
Referenced by ExportDescription(), and operator=().
addChannel() [2/2]
int Isis::ExportDescription::addChannel (FileName filename, CubeAttributeInput & att, double min, double max)
Add an export color channel for the given input cube, attributes (typically band number), and input DN range.
Parameters
filename The name of the cube
att The cube attributes such as band number
min The minimum DN in the input mapped to the minimum of the output
max The maximum DN in the input mapped to the maximum of the output
Returns
The index of the newly added channel
References Isis::ExportDescription::ChannelDescription::setInputRange().
channel()
const ExportDescription::ChannelDescription & Isis::ExportDescription::channel (int i) const
Return the channels description at the given index.
Parameters
i Index of the desired channel
Returns
Constant reference to the channel
Referenced by ExportDescription(), and operator=().
channelCount()
int Isis::ExportDescription::channelCount () const
Count of the number of channels in the description.
Returns
The channel count
Referenced by ExportDescription(), and operator=().
operator=()
ExportDescription & Isis::ExportDescription::operator= (const ExportDescription & descriptionToCopy)
Assignment operator for the export description.
Parameters
descriptionToCopy ExportDescription to be copied.
Returns
ExportDescription with same number of channels, type, and pixel values.
References addChannel(), Isis::ExportDescription::ChannelDescription::attributes(), channel(), channelCount(), Isis::ExportDescription::ChannelDescription::filename(), Isis::ExportDescription::ChannelDescription::hasCustomRange(), Isis::ExportDescription::ChannelDescription::inputMaximum(), Isis::ExportDescription::ChannelDescription::inputMinimum(), and setPixelType().
outputPixelAbsoluteMax()
double Isis::ExportDescription::outputPixelAbsoluteMax () const
Returns the absolute maximum value for output pixels.
Defaults to 255.0 if not set by the user.
Returns
The absolute maximum
outputPixelAbsoluteMin()
double Isis::ExportDescription::outputPixelAbsoluteMin () const
Returns the absolute minimum value for output pixels.
Defaults to 0.0 if not set by the user.
Returns
The absolute minimum
outputPixelNull()
double Isis::ExportDescription::outputPixelNull () const
Returns the output pixel value for Null DNs.
Defaults to 0.0 if not set by the user.
Returns
The output Null
outputPixelValidMax()
double Isis::ExportDescription::outputPixelValidMax () const
Returns the output pixel value for the valid maximum.
Defaults to 255.0 if not set by the user.
Returns
The valid maximum
outputPixelValidMin()
double Isis::ExportDescription::outputPixelValidMin () const
Returns the output pixel value for the valid minimum.
Defaults to 0.0 if not set by the user.
Returns
The valid minimum
pixelType()
PixelType Isis::ExportDescription::pixelType () const
Returns the pixel type.
Defaults to None if not set by the user.
Returns
The pixel type: {None, UnsignedByte, SignedWord, UnsignedWord}
setPixelType()
void Isis::ExportDescription::setPixelType (PixelType type)
Set the pixel type for the output image.
Automatically establishes valid output minimum, maximum, and null values based on the type.
Parameters
type The pixel type: {UnsignedByte, SignedWord, UnsignedWord}
References _FILEINFO_, Isis::IException::Programmer, Isis::SignedWord, Isis::toString(), Isis::UnsignedByte, and Isis::UnsignedWord.
Referenced by ExportDescription(), and operator=().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ExportDescription/ExportDescription.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/ExportDescription/ExportDescription.cpp