Isis Developer Reference: Isis::ImageTreeWidgetItem Class Reference
Isis::ImageTreeWidgetItem Class Reference
#include <ImageTreeWidgetItem.h>
Public Types
enum TreeColumn {
NameColumn = 0 , FootprintColumn , OutlineColumn , ImageColumn ,
LabelColumn , ResolutionColumn , EmissionAngleColumn , IncidenceAngleColumn ,
PhaseAngleColumn , AspectRatioColumn , SampleResolutionColumn , LineResolutionColumn ,
NorthAzimuthColumn , BlankColumn
}
Public Slots
void onDisplayPropertiesChanged ()
Public Member Functions
ImageTreeWidgetItem (ImageList *imageList, Image *image, QTreeWidget *parent=0)
ImageTreeWidget constructor.
virtual ~ImageTreeWidgetItem ()
Image * image ()
QString imageListName () const
void forgetImage ()
void update (bool save)
Static Public Member Functions
static QString treeColumnToString (TreeColumn)
Detailed Description
Author
????-??-?? Unknown
Member Enumeration Documentation
TreeColumn
enum Isis::ImageTreeWidgetItem::TreeColumn
Enumerator
NameColumn
FootprintColumn
OutlineColumn
ImageColumn
LabelColumn
ResolutionColumn
EmissionAngleColumn
IncidenceAngleColumn
PhaseAngleColumn
AspectRatioColumn
SampleResolutionColumn
LineResolutionColumn
NorthAzimuthColumn
BlankColumn
Constructor & Destructor Documentation
ImageTreeWidgetItem()
Isis::ImageTreeWidgetItem::ImageTreeWidgetItem (ImageList * imageList, Image * image, QTreeWidget * parent = 0)
ImageTreeWidget constructor.
ImageTreeWidget is derived from QTreeWidget
Parameters
parent
References Isis::DisplayProperties::addSupport(), Isis::Image::aspectRatio(), AspectRatioColumn, Isis::ImageDisplayProperties::Color, Isis::Angle::degrees(), Isis::DisplayProperties::displayName(), Isis::Image::displayProperties(), Isis::Image::emissionAngle(), EmissionAngleColumn, image(), Isis::Image::incidenceAngle(), IncidenceAngleColumn, Isis::Image::lineResolution(), LineResolutionColumn, NameColumn, Isis::Image::northAzimuth(), NorthAzimuthColumn, onDisplayPropertiesChanged(), Isis::Image::phaseAngle(), PhaseAngleColumn, Isis::Image::resolution(), ResolutionColumn, Isis::Image::sampleResolution(), SampleResolutionColumn, Isis::ImageDisplayProperties::Selected, and update().
~ImageTreeWidgetItem()
Isis::ImageTreeWidgetItem::~ImageTreeWidgetItem () virtual
Member Function Documentation
forgetImage()
void Isis::ImageTreeWidgetItem::forgetImage ()
image()
Image * Isis::ImageTreeWidgetItem::image ()
Referenced by Isis::ImageFileListWidget::filterFileList(), Isis::ImageTreeWidget::imagesInView(), ImageTreeWidgetItem(), Isis::ImageFileListWidget::removeImages(), and Isis::ImageFileListWidget::toPvl().
imageListName()
QString Isis::ImageTreeWidgetItem::imageListName () const
References Isis::ImageList::name().
onDisplayPropertiesChanged
void Isis::ImageTreeWidgetItem::onDisplayPropertiesChanged () slot
References Isis::ImageTreeWidget::enqueueReadDisplayProperties(), and update().
Referenced by ImageTreeWidgetItem().
treeColumnToString()
QString Isis::ImageTreeWidgetItem::treeColumnToString (TreeColumn column) static
References _FILEINFO_, AspectRatioColumn, BlankColumn, EmissionAngleColumn, FootprintColumn, ImageColumn, IncidenceAngleColumn, LabelColumn, LineResolutionColumn, NameColumn, NorthAzimuthColumn, OutlineColumn, PhaseAngleColumn, Isis::IException::Programmer, ResolutionColumn, and SampleResolutionColumn.
Referenced by Isis::ImageFileListWidget::fromPvl(), Isis::ImageTreeWidget::ImageTreeWidget(), Isis::ImageFileListWidget::save(), Isis::ImageFileListWidget::toPvl(), and Isis::ImageTreeWidget::updateViewActs().
update()
void Isis::ImageTreeWidgetItem::update (bool save)
References Isis::ImageDisplayProperties::Color, Isis::Image::displayProperties(), FootprintColumn, Isis::DisplayProperties::getValue(), ImageColumn, LabelColumn, NameColumn, OutlineColumn, Isis::ImageDisplayProperties::Selected, Isis::ImageDisplayProperties::setSelected(), Isis::ImageDisplayProperties::setShowDNs(), Isis::ImageDisplayProperties::setShowFill(), Isis::ImageDisplayProperties::setShowLabel(), Isis::ImageDisplayProperties::setShowOutline(), Isis::ImageDisplayProperties::ShowDNs, Isis::ImageDisplayProperties::ShowFill, Isis::ImageDisplayProperties::ShowLabel, Isis::ImageDisplayProperties::ShowOutline, and Isis::DisplayProperties::supports().
Referenced by ImageTreeWidgetItem(), and onDisplayPropertiesChanged().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ImageFileListWidget/ImageTreeWidgetItem.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ImageFileListWidget/ImageTreeWidgetItem.cpp