Isis Developer Reference: Isis::ImageReader Class Reference
Isis::ImageReader Class Reference
#include <ImageReader.h>
Public Slots
void askDefaultAlpha ()
void read (PvlObject imagesObj)
void read (QStringList imageFileNames)
Handle opening cubes by filename.
void setOpenFilled (bool openFilled)
void setSafeFileOpen (bool safeFileOpen)
Signals
void imagesReady (ImageList images)
Public Member Functions
ImageReader (QMutex *cameraMutex, bool requireFootprints=true, QObject *parent=NULL)
MosaicWidget constructor.
virtual ~ImageReader ()
Free the allocated memory by this object.
QList< QAction * > actions (ImageDisplayProperties::Property relevantDispProperties)
QProgressBar * progress ()
Detailed Description
Author
2012-??-?? ???
Constructor & Destructor Documentation
ImageReader()
Isis::ImageReader::ImageReader (QMutex * cameraMutex, bool requireFootprints = true, QObject * parent = NULL)
MosaicWidget constructor.
MosaicWidget is derived from QSplitter, the left side of the splitter is a QTreeWidget and the right side of the splitter is a QGraphicsView.
Parameters
parent
~ImageReader()
Isis::ImageReader::~ImageReader () virtual
Free the allocated memory by this object.
Member Function Documentation
actions()
QList< QAction * > Isis::ImageReader::actions (ImageDisplayProperties::Property relevantDispProperties)
References askDefaultAlpha(), Isis::ImageDisplayProperties::Color, setOpenFilled(), setSafeFileOpen(), and Isis::ImageDisplayProperties::ShowFill.
askDefaultAlpha
void Isis::ImageReader::askDefaultAlpha () slot
Referenced by actions().
imagesReady
void Isis::ImageReader::imagesReady (ImageList images) signal
progress()
QProgressBar * Isis::ImageReader::progress ()
read [1/2]
void Isis::ImageReader::read (PvlObject imagesObj) slot
References Isis::PvlObject::beginObject(), and Isis::PvlObject::endObject().
Referenced by read().
read [2/2]
void Isis::ImageReader::read (QStringList imageFileNames) slot
Handle opening cubes by filename.
References read().
setOpenFilled
void Isis::ImageReader::setOpenFilled (bool openFilled) slot
Referenced by actions().
setSafeFileOpen
void Isis::ImageReader::setSafeFileOpen (bool safeFileOpen) slot
Referenced by actions().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ImageReader/ImageReader.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ImageReader/ImageReader.cpp