Isis Developer Reference: Isis::ViewportBufferAction Class Reference
Isis::ViewportBufferAction Class Reference
#include <ViewportBufferAction.h>
Public Types
enum ActionType { none , transform , fill , stretch }
This uniquely identifies which child is instantiated.
Public Member Functions
ViewportBufferAction ()
Creates a new viewport buffer action.
virtual ~ViewportBufferAction ()
Destructor.
virtual ActionType getActionType ()
Returns the instantiated type.
bool started ()
Returns true if this is an action that takes time and has begun.
void started (bool started)
Sets started.
virtual void stop ()
Cancels the process, used if reinitialize requested for example.
Detailed Description
Author
????-??-?? Unknown
Member Enumeration Documentation
ActionType
enum Isis::ViewportBufferAction::ActionType
This uniquely identifies which child is instantiated.
Enumerator
none
Parent was instantiated.
transform
ViewportBufferTransform.
fill
ViewportBufferFill.
stretch
ViewportBufferStretch.
Constructor & Destructor Documentation
ViewportBufferAction()
Isis::ViewportBufferAction::ViewportBufferAction ()
Creates a new viewport buffer action.
~ViewportBufferAction()
Isis::ViewportBufferAction::~ViewportBufferAction () virtual
Destructor.
Member Function Documentation
getActionType()
virtual ActionType Isis::ViewportBufferAction::getActionType () inline virtual
Returns the instantiated type.
Reimplemented in Isis::ViewportBufferTransform, Isis::ViewportBufferStretch, and Isis::ViewportBufferFill.
References none.
Referenced by Isis::ViewportBuffer::DataReady(), and Isis::ViewportBuffer::totalUnfilledArea().
started() [1/2]
bool Isis::ViewportBufferAction::started () inline
Returns true if this is an action that takes time and has begun.
Referenced by Isis::ViewportBuffer::DataReady(), and started().
started() [2/2]
void Isis::ViewportBufferAction::started (bool started) inline
Sets started.
Parameters
started True if starting
References started().
stop()
virtual void Isis::ViewportBufferAction::stop () inline virtual
Cancels the process, used if reinitialize requested for example.
Reimplemented in Isis::ViewportBufferFill.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CubeViewport/ViewportBufferAction.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CubeViewport/ViewportBufferAction.cpp