Isis Developer Reference: Isis::TreeView Class Reference
Isis::TreeView Class Reference
#include <TreeView.h>
Public Slots
void deactivate ()
void activate ()
void handleModelSelectionChanged ()
Signals
void activated ()
void selectionChanged ()
Public Member Functions
TreeView (QWidget *parent=0)
virtual ~TreeView ()
QSize sizeHint () const
QFont getContentFont () const
void setModel (AbstractTreeModel *someModel)
AbstractTreeModel * getModel () const
bool isActive () const
QString getTitle () const
void setTitle (QString someTitle)
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
TreeView()
Isis::TreeView::TreeView (QWidget * parent = 0)
References activated(), and selectionChanged().
~TreeView()
Isis::TreeView::~TreeView () virtual
Member Function Documentation
activate
void Isis::TreeView::activate () slot
References Isis::TreeViewHeader::setActive().
activated
void Isis::TreeView::activated () signal
Referenced by TreeView().
deactivate
void Isis::TreeView::deactivate () slot
References Isis::TreeViewHeader::setActive().
getContentFont()
QFont Isis::TreeView::getContentFont () const
getModel()
AbstractTreeModel * Isis::TreeView::getModel () const
References Isis::TreeViewContent::getModel().
getTitle()
QString Isis::TreeView::getTitle () const
References Isis::TreeViewHeader::getText().
handleModelSelectionChanged
void Isis::TreeView::handleModelSelectionChanged () slot
References Isis::TreeViewContent::refresh().
isActive()
bool Isis::TreeView::isActive () const
selectionChanged
void Isis::TreeView::selectionChanged () signal
Referenced by setModel(), and TreeView().
setModel()
void Isis::TreeView::setModel (AbstractTreeModel * someModel)
References selectionChanged(), and Isis::TreeViewContent::setModel().
setTitle()
void Isis::TreeView::setTitle (QString someTitle)
References Isis::TreeViewHeader::setText().
sizeHint()
QSize Isis::TreeView::sizeHint () const
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/TreeView.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/TreeView.cpp