Isis Developer Reference: Isis::ControlPointEditWidget Class Reference
Isis::ControlPointEditWidget Class Reference
Gui for editing ControlPoints in ipce application.
#include <ControlPointEditWidget.h>
Public Slots
void setSerialNumberList (SerialNumberList *snList)
Set the serial number list.
void setControl (Control *control)
New control network being edited.
void setControlFromActive ()
New active control was set from ipce.
void setEditPoint (ControlPoint *controlPoint, QString serialNumber="")
Slot called by Directory to set the control point for editing.
void deletePoint (ControlPoint *controlPoint)
Gives user options for deleting a control point from the control network.
void createControlPoint (double latitude, double longitude, Cube *cube=0, bool isGroundSource=false)
Create a new control point at the given latitude, longitude.
void colorizeSaveNetButton (bool reset=false)
Turn "Save Net" button text to red.
void addTemplates (TemplateList *templateList)
Add registration TemplateList to combobox when imported to project.
Signals
void controlPointChanged (QString pointId)
void controlPointAdded (QString pointId)
void ignorePointChanged ()
void ignoreLeftChanged ()
void ignoreRightChanged ()
void cnetModified ()
void newControlNetwork (ControlNet *)
void stretchChipViewport (Stretch *, CubeViewport *)
void measureChanged ()
void saveControlNet ()
Public Member Functions
ControlPointEditWidget (Directory *directory, QWidget *parent, bool addMeasures=false)
Consructs the ControlPointEditWidget widget.
virtual ~ControlPointEditWidget ()
QString editPointId ()
ControlPoint * editPoint ()
Protected Member Functions
bool eventFilter (QObject *o, QEvent *e)
Event filter for ControlPointEditWidget.
Detailed Description
Gui for editing ControlPoints in ipce application.
Author
2014-06-25 Tracie Sucharski
Constructor & Destructor Documentation
ControlPointEditWidget()
Isis::ControlPointEditWidget::ControlPointEditWidget (Directory * directory, QWidget * parent, bool addMeasures = false)
Consructs the ControlPointEditWidget widget.
Parameters
parent Pointer to the parent widget for the ControlPointEditWidget
addMeasures Whether or not to add the Add Measure to Point button
References addTemplates(), newControlNetwork(), and Isis::Directory::project().
~ControlPointEditWidget()
Isis::ControlPointEditWidget::~ControlPointEditWidget () virtual
Member Function Documentation
addTemplates
void Isis::ControlPointEditWidget::addTemplates (TemplateList * templateList) slot
Add registration TemplateList to combobox when imported to project.
Parameters
templateList Reference to TemplateList that was imported
References Isis::FileName::name(), and Isis::TemplateList::type().
Referenced by ControlPointEditWidget().
cnetModified
void Isis::ControlPointEditWidget::cnetModified () signal
Referenced by deletePoint().
colorizeSaveNetButton
void Isis::ControlPointEditWidget::colorizeSaveNetButton (bool reset = false) slot
Turn "Save Net" button text to red.
TODO Need whoever is actually saving network to emit signal when net has been saved, so that button can be set back to black.
Author
2014-07-11 Tracie Sucharski
Referenced by deletePoint().
controlPointAdded
void Isis::ControlPointEditWidget::controlPointAdded (QString pointId) signal
Referenced by createControlPoint().
controlPointChanged
void Isis::ControlPointEditWidget::controlPointChanged (QString pointId) signal
createControlPoint
void Isis::ControlPointEditWidget::createControlPoint (double latitude, double longitude, Cube * cube = 0, bool isGroundSource = false) slot
Create a new control point at the given latitude, longitude.
Parameters
latitude The latitude position for the new control point
longitude The longitude position for the new control point
cube The cube that the user used to select position for new control point
isGroundSource Boolean indicating whether the cube used to choose position is a ground source
References Isis::ControlPoint::Add(), controlPointAdded(), Isis::Shape::cube(), Isis::ControlPoint::RadiusSource::DEM, Isis::FileName::expanded(), Isis::Cube::externalCubeFileName(), Isis::Shape::fileName(), Isis::SerialNumberList::fileName(), Isis::SerialNumberList::fileNameIndex(), Isis::ControlPoint::Free, Isis::ControlPoint::GetId(), Isis::NewControlPointDialog::groundSource(), Isis::Camera::Line(), Isis::ControlMeasure::Manual, Isis::ControlPoint::SurfacePointSource::None, Isis::NewControlPointDialog::pointId(), Isis::NewControlPointDialog::pointType(), Isis::Shape::radiusSource(), Isis::Camera::Sample(), Isis::NewControlPointDialog::selectedFiles(), Isis::SerialNumberList::serialNumber(), Isis::ControlMeasure::SetAprioriLine(), Isis::ControlMeasure::SetAprioriSample(), Isis::ControlPoint::SetAprioriSurfacePointSource(), Isis::ControlPoint::SetAprioriSurfacePointSourceFile(), Isis::ControlMeasure::SetCamera(), Isis::ControlMeasure::SetChooserName(), Isis::ControlPoint::SetChooserName(), Isis::ControlMeasure::SetCoordinate(), Isis::ControlMeasure::SetCubeSerialNumber(), setEditPoint(), Isis::NewControlPointDialog::setFiles(), Isis::NewControlPointDialog::setGroundSource(), Isis::NewControlPointDialog::setRadiusSource(), Isis::ControlMeasure::SetType(), Isis::ControlPoint::SetType(), Isis::Camera::SetUniversalGround(), Isis::SerialNumberList::size(), Isis::Shape::surfacePointSource(), and Isis::Application::UserName().
Referenced by Isis::Directory::createControlPoint().
deletePoint
void Isis::ControlPointEditWidget::deletePoint (ControlPoint * controlPoint) slot
Gives user options for deleting a control point from the control network.
Parameters
controlPoint (ControlPoint *) Control point to be deleted
References cnetModified(), colorizeSaveNetButton(), Isis::SerialNumberList::fileName(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::ControlMeasure::MeasureLocked, and Isis::ControlPoint::PointLocked.
Referenced by Isis::Directory::deleteControlPoint().
editPoint()
ControlPoint * Isis::ControlPointEditWidget::editPoint ()
editPointId()
QString Isis::ControlPointEditWidget::editPointId ()
Referenced by Isis::Directory::createControlPoint().
eventFilter()
bool Isis::ControlPointEditWidget::eventFilter (QObject * o, QEvent * e) protected
Event filter for ControlPointEditWidget.
Determines whether to update left or right measure info.
Parameters
o Pointer to QObject
e Pointer to QEvent
Returns
bool Indicates whether the event type is "Leave".
ignoreLeftChanged
void Isis::ControlPointEditWidget::ignoreLeftChanged () signal
ignorePointChanged
void Isis::ControlPointEditWidget::ignorePointChanged () signal
ignoreRightChanged
void Isis::ControlPointEditWidget::ignoreRightChanged () signal
measureChanged
void Isis::ControlPointEditWidget::measureChanged () signal
newControlNetwork
void Isis::ControlPointEditWidget::newControlNetwork (ControlNet *) signal
Referenced by ControlPointEditWidget(), setControl(), and setControlFromActive().
saveControlNet
void Isis::ControlPointEditWidget::saveControlNet () signal
setControl
void Isis::ControlPointEditWidget::setControl (Control * control) slot
New control network being edited.
Parameters
cnet (Control *) The control network to edit
References Isis::Control::controlNet(), Isis::Control::fileName(), and newControlNetwork().
Referenced by Isis::Directory::addControlPointEditView().
setControlFromActive
void Isis::ControlPointEditWidget::setControlFromActive () slot
New active control was set from ipce.
TODO: This will need to be redesigned with the ::setControl method to better handle editing points from different cnets.
References Isis::Project::activeControl(), newControlNetwork(), and Isis::Directory::project().
setEditPoint
void Isis::ControlPointEditWidget::setEditPoint (ControlPoint * controlPoint, QString serialNumber = "") slot
Slot called by Directory to set the control point for editing.
Parameters
controlPoint (ControlPoint *) ControlPoint that will be loaded into editor
serialNumber (QString) Optional parameter indicating the serial number of the cube that the point was chosen from
References Isis::ControlPoint::Parent().
Referenced by createControlPoint(), and Isis::Directory::modifyControlPoint().
setSerialNumberList
void Isis::ControlPointEditWidget::setSerialNumberList (SerialNumberList * snList) slot
Set the serial number list.
Parameters
snList Pointer to the SerialNumberList
Referenced by Isis::Directory::addControlPointEditView().
stretchChipViewport
void Isis::ControlPointEditWidget::stretchChipViewport (Stretch * , CubeViewport *) signal
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ControlPointEditWidget/ControlPointEditWidget.cpp