Isis Developer Reference: Isis::GuiOutputAttribute Class Reference
Isis::GuiOutputAttribute Class Reference
#include <GuiOutputAttribute.h>
Public Member Functions
GuiOutputAttribute (QWidget *parent=0)
Constuctor.
~GuiOutputAttribute ()
QString GetAttributes ()
void SetAttributes (const QString &value)
void SetPropagation (bool enabled)
Do we allow propagation.
Static Public Member Functions
static int GetAttributes (const QString &defaultAttribute, QString &newAttribute, const QString &title, bool allowProp, QWidget *parent)
Convenience access to dialog.
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
GuiOutputAttribute()
Isis::GuiOutputAttribute::GuiOutputAttribute (QWidget * parent = 0)
Constuctor.
Referenced by GetAttributes().
~GuiOutputAttribute()
Isis::GuiOutputAttribute::~GuiOutputAttribute ()
Member Function Documentation
GetAttributes() [1/2]
QString Isis::GuiOutputAttribute::GetAttributes ()
Referenced by GetAttributes().
GetAttributes() [2/2]
int Isis::GuiOutputAttribute::GetAttributes (const QString & defaultAttribute, QString & newAttribute, const QString & title, bool allowProp, QWidget * parent) static
Convenience access to dialog.
References GetAttributes(), GuiOutputAttribute(), SetAttributes(), and SetPropagation().
SetAttributes()
void Isis::GuiOutputAttribute::SetAttributes (const QString & value)
References Isis::AttachedLabel, Isis::CubeAttributeOutput::byteOrder(), Isis::CubeAttributeOutput::fileFormat(), Isis::CubeAttributeOutput::labelAttachment(), Isis::Lsb, Isis::CubeAttributeOutput::maximum(), Isis::CubeAttributeOutput::minimum(), Isis::CubeAttributeOutput::pixelType(), Isis::CubeAttributeOutput::propagateMinimumMaximum(), Isis::CubeAttributeOutput::propagatePixelType(), Isis::SignedInteger, Isis::SignedWord, Isis::Cube::Tile, Isis::UnsignedByte, Isis::UnsignedInteger, and Isis::UnsignedWord.
Referenced by GetAttributes().
SetPropagation()
void Isis::GuiOutputAttribute::SetPropagation (bool enabled)
Do we allow propagation.
Referenced by GetAttributes().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Gui/GuiOutputAttribute.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Gui/GuiOutputAttribute.cpp