Isis Developer Reference: Isis::GuiCamera Class Reference
Isis::GuiCamera Class Reference
Container class for GuiCamera.
#include <GuiCamera.h>
Public Member Functions
GuiCamera (Camera *camera, QObject *parent=0)
The constructor for this class.
~GuiCamera ()
The Destructor.
bool operator== (const GuiCamera &srcGuiCamera) const
Compares two Target Body objects to see if they are equal.
const GuiCameraDisplayProperties * displayProperties () const
Retrieves the display properties of the camera.
QString id () const
Retrieves a unique, identifying string associated with this GuiCamera object.
QString instrumentId ()
Retrieve the InstrumentId as appears in the original cube label.
QString instrumentNameShort ()
Retrieves an abbreviated version for the name of the instrument.
QString instrumentNameLong ()
Retrieves a long version for the name of the instrument.
QString spacecraftNameShort ()
Retrieves an abbbreviated name for the spacecraft.
QString spacecraftNameLong ()
Retrieves the full name of the spacecraft.
Detailed Description
Container class for GuiCamera.
This class represents a camera in a project-based GUI interface. It encapsulates ideas about a camera such as it's display name, how it should be viewed, where it is on disk, etc.
Author
2015-06-23 Ken Edmundson
Constructor & Destructor Documentation
GuiCamera()
Isis::GuiCamera::GuiCamera (Camera * camera, QObject * parent = 0)
The constructor for this class.
Parameters
camera A traditional Isis::Camera object which we are wrapping in this class.
parent A pointer to the object instantiating this object.
References Isis::Camera::instrumentId(), Isis::Camera::instrumentNameLong(), Isis::Camera::instrumentNameShort(), Isis::Camera::spacecraftNameLong(), and Isis::Camera::spacecraftNameShort().
~GuiCamera()
Isis::GuiCamera::~GuiCamera ()
The Destructor.
Member Function Documentation
displayProperties()
const GuiCameraDisplayProperties * Isis::GuiCamera::displayProperties () const
Retrieves the display properties of the camera.
Returns
GuiCameraDisplayProperties
Referenced by operator==(), and Isis::SensorInfoWidget::SensorInfoWidget().
id()
QString Isis::GuiCamera::id () const
Retrieves a unique, identifying string associated with this GuiCamera object.
Returns
QString returns m_id
instrumentId()
QString Isis::GuiCamera::instrumentId ()
Retrieve the InstrumentId as appears in the original cube label.
Returns
QString Returns m_instrumentId
instrumentNameLong()
QString Isis::GuiCamera::instrumentNameLong ()
Retrieves a long version for the name of the instrument.
Returns
QString Returns m_instrumentNameLong.
instrumentNameShort()
QString Isis::GuiCamera::instrumentNameShort ()
Retrieves an abbreviated version for the name of the instrument.
Returns
QString Returns m_instrumentNameShort.
operator==()
bool Isis::GuiCamera::operator== (const GuiCamera & srcGuiCamera) const
Compares two Target Body objects to see if they are equal.
Parameters
srcGuiCamera GuiCamera object to compare against
Returns
bool Returns True if the objects are equal, False if not.
References Isis::DisplayProperties::displayName(), and displayProperties().
spacecraftNameLong()
QString Isis::GuiCamera::spacecraftNameLong ()
Retrieves the full name of the spacecraft.
Returns
QString Returns m_spacecraftNameLong.
Referenced by Isis::SensorInfoWidget::SensorInfoWidget().
spacecraftNameShort()
QString Isis::GuiCamera::spacecraftNameShort ()
Retrieves an abbbreviated name for the spacecraft.
Returns
QString Returns m_spacecraftNameShort.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/GuiCamera/GuiCamera.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/GuiCamera/GuiCamera.cpp