Isis Developer Reference: Isis::PolynomialBivariate Class Reference
Isis::PolynomialBivariate Class Reference
Math
Nth degree Polynomial with two variables.
#include <PolynomialBivariate.h>
Public Member Functions
PolynomialBivariate (int degree)
Create a PolynomialBivariate object.
~PolynomialBivariate ()
Destroys the PolynomialBivariate object.
void Expand (const std::vector< double > &vars)
This is the the overriding virtual function that provides the expansion of the two input variables into the polynomial equation.
void SetCoefficients (const std::vector< double > &coefs)
Set the coefficients for the equation.
double Evaluate (const std::vector< double > &vars)
Compute the equation using the input variables.
double Evaluate (const double &var)
Compute the equation using the input variable.
int Coefficients () const
Returns the number of coefficients for the equation.
int Variables () const
Returns the number of variables in the equation.
QString Name () const
Returns the name of the equation.
double Term (int c) const
Returns the cth term.
double Coefficient (int i) const
Returns the ith coefficient.
Protected Attributes
QString p_name
The name of the equation. Call it by using Name()
int p_numVars
The number of variables in the equation. Call it by using Variables()
int p_numCoefs
The number of coefficients in the equation.
std::vector< double > p_coefs
A vector of the coefficients in the equation.
std::vector< double > p_terms
A vector of the terms in the equation.
Detailed Description
Nth degree Polynomial with two variables.
This is a derived class from BasisFunction which provides the capabilities of a polynomial equation in two variables with degree n, where n is specified during the object construction. For example, Degree = 1 z = a + b*x + c*y Degree = 2 z = a + b*x + c*y + d*x**2 + e*x*y + f*y**2 Degree = 3 z = a + b*x + c*y + d*x**2 + e*x*y + f*y**2 + g*x**3 + h*x**2*y
i*x*y**2 + j*y**3 In general the number of coefficients will be ((degree+1)*(degree+2))/2.
Author
2004-06-24 Jeff Anderson
Constructor & Destructor Documentation
PolynomialBivariate()
Isis::PolynomialBivariate::PolynomialBivariate (int degree)
Create a PolynomialBivariate object.
Parameters
degree The order/degree of the polynomial
~PolynomialBivariate()
Isis::PolynomialBivariate::~PolynomialBivariate () inline
Destroys the PolynomialBivariate object.
Member Function Documentation
Coefficient()
double Isis::BasisFunction::Coefficient (int i) const inline inherited
Returns the ith coefficient.
Parameters
i The index for the desired coefficient.
Returns
The ith coefficient
References Isis::BasisFunction::p_coefs.
Referenced by Isis::PolynomialUnivariate::DerivativeVar(), Isis::SpicePosition::LoadHermiteCache(), Isis::SurfaceModel::MinMax(), Isis::SpicePosition::SetPolynomial(), Isis::SpiceRotation::SetPolynomial(), and Isis::Affine::Solve().
Coefficients()
int Isis::BasisFunction::Coefficients () const inline inherited
Returns the number of coefficients for the equation.
Returns
The number of coefficients.
References Isis::BasisFunction::p_numCoefs.
Referenced by Isis::PolynomialUnivariate::DerivativeCoef(), Isis::PolynomialUnivariate::DerivativeVar(), Isis::SpicePosition::SetPolynomial(), and Isis::SpiceRotation::SetPolynomial().
Evaluate() [1/2]
double Isis::BasisFunction::Evaluate (const double & var) inherited
Compute the equation using the input variable.
Parameters
var A single double value to use for the equation.
Returns
The output double value resulting from the equation.
References Isis::BasisFunction::Evaluate().
Evaluate() [2/2]
double Isis::BasisFunction::Evaluate (const std::vector< double > & vars) inherited
Compute the equation using the input variables.
Parameters
vars A vector of double values to use for the equation. After setting the coefficients, this can be invoked many times to compute output values given input values.
Returns
The output value.
References _FILEINFO_, Isis::BasisFunction::Expand(), Isis::BasisFunction::p_coefs, Isis::BasisFunction::p_numCoefs, Isis::BasisFunction::p_numVars, Isis::BasisFunction::p_terms, Isis::IException::Programmer, and Isis::toString().
Referenced by Isis::BasisFunction::Evaluate(), Isis::LeastSquares::Evaluate(), Isis::SpiceRotation::EvaluatePolyFunction(), Isis::SpicePosition::LoadHermiteCache(), Isis::SpicePosition::SetEphemerisTimePolyFunction(), and Isis::SpiceRotation::setEphemerisTimePolyFunction().
Expand()
void Isis::PolynomialBivariate::Expand (const std::vector< double > & vars) virtual
This is the the overriding virtual function that provides the expansion of the two input variables into the polynomial equation.
See BasisFunction for more information.
Parameters
vars A vector of double values to use for the expansion.
Reimplemented from Isis::BasisFunction.
References Isis::BasisFunction::p_terms.
Name()
QString Isis::BasisFunction::Name () const inline inherited
Returns the name of the equation.
Returns
The name of the equation.
References Isis::BasisFunction::p_name.
Referenced by Isis::LeastSquares::AddKnown().
SetCoefficients()
void Isis::BasisFunction::SetCoefficients (const std::vector< double > & coefs) inherited
Set the coefficients for the equation.
Parameters
coefs A vector of coefficients for the equation.
References _FILEINFO_, Isis::BasisFunction::p_coefs, Isis::BasisFunction::p_numCoefs, Isis::IException::Programmer, and Isis::toString().
Referenced by Isis::SpiceRotation::DCJdt(), Isis::SpiceRotation::EvaluatePolyFunction(), Isis::SpicePosition::LoadHermiteCache(), Isis::PolynomialUnivariate::PolynomialUnivariate(), Isis::SpicePosition::SetEphemerisTimePolyFunction(), Isis::SpiceRotation::setEphemerisTimePolyFunction(), Isis::SpiceRotation::SetPolynomial(), and Isis::SpicePosition::SetPolynomial().
Term()
double Isis::BasisFunction::Term (int c) const inline inherited
Returns the cth term.
This is only valid after a Evalute/Expand has been invoked. It represents the expansion of the variables into the ith term. For example,
\[ x = C1 + C2*x + C3*y + C4*x*y \]
would return x*y for the 3rd term (zero-based)
Parameters
c The index for the desired coefficient.
Returns
The cth term.
References Isis::BasisFunction::p_terms.
Variables()
int Isis::BasisFunction::Variables () const inline inherited
Returns the number of variables in the equation.
Returns
The number of variables.
References Isis::BasisFunction::p_numVars.
Referenced by Isis::LeastSquares::AddKnown(), and Isis::NthOrderPolynomial::Expand().
Member Data Documentation
p_coefs
std::vector<double> Isis::BasisFunction::p_coefs protected inherited
A vector of the coefficients in the equation.
Call it by using Coefficient()
Referenced by Isis::BasisFunction::Coefficient(), Isis::BasisFunction::Evaluate(), and Isis::BasisFunction::SetCoefficients().
p_name
QString Isis::BasisFunction::p_name protected inherited
The name of the equation. Call it by using Name()
Referenced by Isis::BasisFunction::BasisFunction(), and Isis::BasisFunction::Name().
p_numCoefs
int Isis::BasisFunction::p_numCoefs protected inherited
The number of coefficients in the equation.
Call it by using Coefficients()
Referenced by Isis::BasisFunction::BasisFunction(), Isis::BasisFunction::Coefficients(), Isis::BasisFunction::Evaluate(), and Isis::BasisFunction::SetCoefficients().
p_numVars
int Isis::BasisFunction::p_numVars protected inherited
The number of variables in the equation. Call it by using Variables()
Referenced by Isis::BasisFunction::BasisFunction(), Isis::BasisFunction::Evaluate(), and Isis::BasisFunction::Variables().
p_terms
std::vector<double> Isis::BasisFunction::p_terms protected inherited
A vector of the terms in the equation.
Call it by using Term()
Referenced by Isis::BasisFunction::Evaluate(), Isis::BasisFunction::Expand(), Isis::NthOrderPolynomial::Expand(), Expand(), Isis::PolynomialUnivariate::Expand(), and Isis::BasisFunction::Term().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/PolynomialBivariate/PolynomialBivariate.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/PolynomialBivariate/PolynomialBivariate.cpp