Isis Developer Reference: Isis::CubeManager Class Reference
Isis::CubeManager Class Reference
Class for quick re-accessing of cubes based on file name.
#include <CubeManager.h>
Public Member Functions
CubeManager ()
This initializes a CubeManager object.
~CubeManager ()
This is the CubeManager destructor.
void SetNumOpenCubes (unsigned int numCubes)
This sets the maximum number of opened cubes for this instance of CubeManager.
void CleanCubes (const QString &cubeFileName)
This method removes a cube from memory, if it exists.
void CleanCubes ()
This method removes all cubes from memory.
Cube * OpenCube (const QString &cubeFileName)
This method opens a cube.
Static Public Member Functions
static Cube * Open (const QString &cubeFileName)
This method calls the method OpenCube() on the static instance.
static void CleanUp (const QString &cubeFileName)
This method calls CleanCubes(const QString &cubeFileName) on the static instance.
static void CleanUp ()
This method calls CleanCubes() on the static instance.
Protected Attributes
QMap< QString, Cube * > p_cubes
This keeps track of the open cubes.
QQueue< QString > p_opened
This keeps track of cubes that have been opened.
unsigned int p_currentLimit
The current limit regarding number of open files allowed.
unsigned int p_maxOpenFiles
60% of the maximum number of open files allowed by system resources
Static Protected Attributes
static CubeManager * p_instance = 0
There is always at least one instance of CubeManager around.
Detailed Description
Class for quick re-accessing of cubes based on file name.
This class holds cubes in static memory for reading. This is helpful to prevent reading of the same cube many times. Files will remain opened for reading, this is not for use with a cube that will ever be written to. You can either use the static methods of the class, in which case cubes will be cleaned up after IsisMain(...) is done executing, or you can instantiate the class for more control.
Author
2008-05-20 Steven Lambright
Constructor & Destructor Documentation
CubeManager()
Isis::CubeManager::CubeManager ()
This initializes a CubeManager object.
References _FILEINFO_, CleanUp(), p_currentLimit, p_maxOpenFiles, and Isis::IException::Programmer.
~CubeManager()
Isis::CubeManager::~CubeManager ()
This is the CubeManager destructor.
This method calls CleanCˇubes().
References CleanCubes().
Member Function Documentation
CleanCubes() [1/2]
void Isis::CubeManager::CleanCubes ()
This method removes all cubes from memory.
All pointers returned via OpenCube will be NULL.
References p_cubes.
Referenced by OpenCube(), and ~CubeManager().
CleanCubes() [2/2]
void Isis::CubeManager::CleanCubes (const QString & cubeFileName)
This method removes a cube from memory, if it exists.
If the cube is not loaded into memory, nothing happens. This will cause any pointers to this cube, obtained via OpenCube, to be NULL.
Parameters
cubeFileName The filename of the cube to remove from memory
References p_cubes.
Referenced by Isis::ControlNetValidMeasure::~ControlNetValidMeasure().
CleanUp() [1/2]
static void Isis::CubeManager::CleanUp () inline static
This method calls CleanCubes() on the static instance.
See also
CleanCubes
Referenced by CubeManager().
CleanUp() [2/2]
static void Isis::CubeManager::CleanUp (const QString & cubeFileName) inline static
This method calls CleanCubes(const QString &cubeFileName) on the static instance.
See also
CleanCubes(const QString &cubeFileName)
Parameters
cubeFileName The filename of the cube to destroy from memory
Open()
static Cube* Isis::CubeManager::Open (const QString & cubeFileName) inline static
This method calls the method OpenCube() on the static instance.
See also
OpenCube
Parameters
cubeFileName FileName of the cube to be opened
Returns
Cube* Pointer to the cube (guaranteed not null)
Referenced by Isis::DemShape::DemShape().
OpenCube()
Cube * Isis::CubeManager::OpenCube (const QString & cubeFileName)
This method opens a cube.
If the cube is already opened, this method will return the cube from memory. The CubeManager class retains ownership of this cube pointer, so do not close the cube, destroy the pointer, or otherwise modify the cube object or pointer such that another object using them would fail. This method does not guarantee you are the only one with this pointer, nor is it recommended to keep this pointer out of a local (method) scope.
Note that this method will allow for 60% of the system's maximum file limit + 1 cubes to be opened, since the cube passed is opened and then cleanup follows. However, since our maximum limit is 60% of the system limit, this will allow enough room for this extra file to be opened before the cleanup occurs.
Parameters
cubeFileName The filename of the cube you wish to open
Returns
Cube* A pointer to the cube object that CubeManager retains ownership to and may delete at any time
References CleanCubes(), Isis::FileName::expanded(), p_cubes, p_currentLimit, p_opened, and Isis::IString::ToQt().
Referenced by Isis::InterestOperator::FindCnetRef(), Isis::InterestOperator::FindOverlapByImageFootPrint(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::InterestOperator::InterestByPoint(), and Isis::InterestOperator::ProcessLocked_Point_Reference().
SetNumOpenCubes()
void Isis::CubeManager::SetNumOpenCubes (unsigned int numCubes) inline
This sets the maximum number of opened cubes for this instance of CubeManager.
The last "maxCubes" opened cubes are guaranteed to be valid as long as one of the CleanCubes(...) are not called. If the maximum number of open cubes specified exceeds 60% of system limitations, the maximum number of opened cubes will be set to a 60% of the system's open file limitation (this considers files used by the current process).
Parameters
numCubes Maximum number of open cubes
Referenced by Isis::ControlNetStatistics::GenerateImageStats(), and Isis::ControlNetValidMeasure::ReadSerialNumbers().
Member Data Documentation
p_cubes
QMap<QString, Cube *> Isis::CubeManager::p_cubes protected
This keeps track of the open cubes.
Referenced by CleanCubes(), and OpenCube().
p_currentLimit
unsigned int Isis::CubeManager::p_currentLimit protected
The current limit regarding number of open files allowed.
Referenced by CubeManager(), and OpenCube().
p_instance
CubeManager * Isis::CubeManager::p_instance = 0 static protected
There is always at least one instance of CubeManager around.
p_maxOpenFiles
unsigned int Isis::CubeManager::p_maxOpenFiles protected
60% of the maximum number of open files allowed by system resources
Referenced by CubeManager().
p_opened
QQueue<QString> Isis::CubeManager::p_opened protected
This keeps track of cubes that have been opened.
Referenced by OpenCube().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/CubeManager/CubeManager.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/CubeManager/CubeManager.cpp