Isis Developer Reference: Isis::MosaicSceneItem Class Reference
Isis::MosaicSceneItem Class Reference
A single cube in the mosaic scene.
#include <MosaicSceneItem.h>
Public Slots
void cubeDisplayChanged ()
Someone changed something in the cube display properties, re-read the whole thing.
Signals
void colorChanged ()
void changed (const QList< QRectF > &)
void mosaicCubeClosed (Image *)
Public Member Functions
MosaicSceneItem (Image *image, MosaicSceneWidget *parent)
MosaicSceneItem constructor.
~MosaicSceneItem ()
Mosaic Item destructor.
virtual QRectF boundingRect () const
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
Re-paints the item.
QColor color () const
Image * image ()
QGraphicsSimpleTextItem * getLabel () const
void reproject ()
Called anytime the user reprojects the cube.
bool contains (const QPointF &) const
Test if we contain the point.
void updateSelection (bool)
Update the selected state.
void scenePropertiesChanged ()
Protected Member Functions
virtual bool sceneEvent (QEvent *event)
This filters out events that happen within our polygons.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
The user right clicked on us (or otherwise requested a context menu).
Detailed Description
A single cube in the mosaic scene.
Author
????-??-?? Stacy Alley
Constructor & Destructor Documentation
MosaicSceneItem()
Isis::MosaicSceneItem::MosaicSceneItem (Image * image, MosaicSceneWidget * parent)
MosaicSceneItem constructor.
Parameters
cubeFileName
parent
References _FILEINFO_, Isis::DisplayProperties::addSupport(), Isis::ImageDisplayProperties::Color, cubeDisplayChanged(), Isis::DisplayProperties::displayName(), Isis::Image::displayProperties(), Isis::MosaicSceneWidget::getProjection(), image(), Isis::ImageDisplayProperties::Selected, Isis::ImageDisplayProperties::ShowDNs, Isis::ImageDisplayProperties::ShowFill, Isis::ImageDisplayProperties::ShowLabel, Isis::ImageDisplayProperties::ShowOutline, Isis::IException::User, Isis::MosaicSceneWidget::userHasTools(), Isis::ImageDisplayProperties::Zooming, and Isis::ImageDisplayProperties::ZOrdering.
~MosaicSceneItem()
Isis::MosaicSceneItem::~MosaicSceneItem ()
Mosaic Item destructor.
Member Function Documentation
boundingRect()
QRectF Isis::MosaicSceneItem::boundingRect () const virtual
Referenced by Isis::MosaicSceneWidget::cubesBoundingRect(), and reproject().
changed
void Isis::MosaicSceneItem::changed (const QList< QRectF > &) signal
color()
QColor Isis::MosaicSceneItem::color () const
References Isis::ImageDisplayProperties::Color, Isis::Image::displayProperties(), and Isis::DisplayProperties::getValue().
colorChanged
void Isis::MosaicSceneItem::colorChanged () signal
contains()
bool Isis::MosaicSceneItem::contains (const QPointF & p) const
Test if we contain the point.
Even though our rect is empty, return true if a child polygon contains it for toolTips and other events.
Referenced by sceneEvent().
contextMenuEvent()
void Isis::MosaicSceneItem::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) protected virtual
The user right clicked on us (or otherwise requested a context menu).
Give it to them.
References Isis::ImageList::append(), Isis::MosaicSceneWidget::directory(), Isis::DisplayProperties::displayName(), Isis::Image::displayProperties(), Isis::Directory::project(), Isis::Directory::supportedActions(), and Isis::ImageList::supportedActions().
cubeDisplayChanged
void Isis::MosaicSceneItem::cubeDisplayChanged () slot
Someone changed something in the cube display properties, re-read the whole thing.
References Isis::MosaicSceneWidget::blockSelectionChange(), Isis::Image::displayProperties(), Isis::DisplayProperties::getValue(), reproject(), Isis::ImageDisplayProperties::ShowLabel, and updateSelection().
Referenced by MosaicSceneItem().
getLabel()
QGraphicsSimpleTextItem* Isis::MosaicSceneItem::getLabel () const inline
image()
Image* Isis::MosaicSceneItem::image () inline
Referenced by Isis::MosaicSceneWidget::contextMenuEvent(), Isis::MosaicSceneWidget::cubeFileNames(), Isis::MosaicSceneWidget::images(), MosaicSceneItem(), Isis::MosaicControlNetTool::mouseButtonRelease(), Isis::MosaicSceneWidget::save(), Isis::MosaicSceneWidget::selectedImages(), and Isis::MosaicSceneWidget::toPvl().
mosaicCubeClosed
void Isis::MosaicSceneItem::mosaicCubeClosed (Image *) signal
paint()
void Isis::MosaicSceneItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) virtual
Re-paints the item.
Parameters
painter
option
widget
References Isis::Image::displayProperties(), Isis::DisplayProperties::getValue(), and Isis::ImageDisplayProperties::ShowDNs.
reproject()
void Isis::MosaicSceneItem::reproject ()
Called anytime the user reprojects the cube.
(Selects a new map file.) And everytime a mosaic item is created.
References boundingRect(), Isis::DisplayProperties::displayName(), Isis::Image::displayProperties(), Isis::MosaicSceneWidget::getProjection(), Isis::DisplayProperties::getValue(), Isis::TProjection::Has180Domain(), Isis::TProjection::SetGround(), Isis::ImageDisplayProperties::ShowLabel, Isis::PolygonTools::To180(), Isis::Projection::XCoord(), and Isis::Projection::YCoord().
Referenced by cubeDisplayChanged().
sceneEvent()
bool Isis::MosaicSceneItem::sceneEvent (QEvent * event) protected virtual
This filters out events that happen within our polygons.
This is necessary because usually events are filtered based on the bounding box alone.
Parameters
watched
event
Returns
bool
References contains().
scenePropertiesChanged()
void Isis::MosaicSceneItem::scenePropertiesChanged () inline
Referenced by Isis::MosaicSceneWidget::setCubesSelectable().
updateSelection()
void Isis::MosaicSceneItem::updateSelection (bool save)
Update the selected state.
Parameters
save True if we need to write to the DisplayProperties, false if we need to read from them.
References Isis::MosaicSceneWidget::blockSelectionChange(), Isis::Image::displayProperties(), Isis::DisplayProperties::getValue(), Isis::ImageDisplayProperties::Selected, and Isis::ImageDisplayProperties::setSelected().
Referenced by cubeDisplayChanged().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/MosaicSceneItem.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/MosaicSceneWidget/MosaicSceneItem.cpp