Isis Developer Reference: Isis::FeatureNomenclature::Feature Class Reference
Isis::FeatureNomenclature::Feature Class Reference
A named feature on a target.
#include <FeatureNomenclature.h>
Public Member Functions
Feature ()
Construct a feature with no data.
Feature (QDomElement searchResultFeature, IAUStatus status)
Construct a feature with the data encapsulated inside of the XML.
Feature (const Feature &other)
Copy a feature.
~Feature ()
Clean up allocated memory by this feature.
QWidget * toWidget () const
This converts the data in this feature to a widget.
QString id () const
QString name () const
QString cleanName () const
QString controlNet () const
QString displayName () const
QString target () const
QString system () const
Distance diameter () const
QString diameterString () const
Latitude centerLatitude () const
QString centerLatitudeString () const
Longitude centerLongitude () const
QString centerLongitudeString () const
Latitude northernLatitude () const
QString northernLatitudeString () const
Latitude southernLatitude () const
QString southernLatitudeString () const
Longitude easternLongitude () const
QString easternLongitudeString () const
Longitude westernLongitude () const
QString westernLongitudeString () const
QString originatingContinent () const
QString originatingEthnicity () const
QString approvalStatus () const
QString approvalDate () const
QString featureType () const
QString referenceString () const
QString origin () const
QString lastUpdated () const
QUrl referenceUrl () const
QString referenceUrlString () const
IAUStatus status () const
void swap (Feature &other)
Swap the member data of this feature with another feature.
Feature & operator= (const Feature &rhs)
Assign the values of this feature from the values of rhs.
Detailed Description
A named feature on a target.
This class encapsulates the idea of a single named feature on a target. The accessor methods will return empty strings/invalid data types if data is not present or available. These should be instantiated (originally) by the FeatureNomenclature class.
Author
2012-03-22 Steven Lambright
Constructor & Destructor Documentation
Feature() [1/3]
Isis::FeatureNomenclature::Feature::Feature ()
Construct a feature with no data.
References Isis::FeatureNomenclature::NoStatus.
Feature() [2/3]
Isis::FeatureNomenclature::Feature::Feature (QDomElement searchResultFeature, IAUStatus status)
Construct a feature with the data encapsulated inside of the XML.
Feature() [3/3]
Isis::FeatureNomenclature::Feature::Feature (const Feature & other)
Copy a feature.
This is a shallow copy.
Parameters
other The feature to copy
~Feature()
Isis::FeatureNomenclature::Feature::~Feature ()
Clean up allocated memory by this feature.
Member Function Documentation
approvalDate()
QString Isis::FeatureNomenclature::Feature::approvalDate () const
Returns
The approval date of the feature.
Referenced by toWidget().
approvalStatus()
QString Isis::FeatureNomenclature::Feature::approvalStatus () const
Returns
The IAU approval status of the feature.
Referenced by toWidget().
centerLatitude()
Latitude Isis::FeatureNomenclature::Feature::centerLatitude () const
Returns
The feature's center latitude.
References Isis::Angle::Degrees, and Isis::toDouble().
centerLatitudeString()
QString Isis::FeatureNomenclature::Feature::centerLatitudeString () const
Returns
The feature's center latitude as a human readable string.
Referenced by toWidget().
centerLongitude()
Longitude Isis::FeatureNomenclature::Feature::centerLongitude () const
Returns
The feature's center longitude.
References Isis::Angle::Degrees, and Isis::toDouble().
centerLongitudeString()
QString Isis::FeatureNomenclature::Feature::centerLongitudeString () const
Returns
The feature's center longitude as a human readable string.
Referenced by toWidget().
cleanName()
QString Isis::FeatureNomenclature::Feature::cleanName () const
Returns
The 'clean' feature name (non-ascii characters cleaned up)
controlNet()
QString Isis::FeatureNomenclature::Feature::controlNet () const
Returns
The source control network for the feature position information. This is implied by what's currently available for targets, since the database does not return this information.
Referenced by toWidget().
diameter()
Distance Isis::FeatureNomenclature::Feature::diameter () const
Returns
The feature's diameter
References Isis::Distance::Kilometers, and Isis::toDouble().
Referenced by Isis::FeatureNomenclature::featureDiameterGreaterThan().
diameterString()
QString Isis::FeatureNomenclature::Feature::diameterString () const
Returns
The feature's diameter as a human readable string.
Referenced by toWidget().
displayName()
QString Isis::FeatureNomenclature::Feature::displayName () const
Returns
The recommended feature name to display to the users
Referenced by toWidget().
easternLongitude()
Longitude Isis::FeatureNomenclature::Feature::easternLongitude () const
Returns
The feature's easternmost (max) longitude.
References Isis::Angle::Degrees, and Isis::toDouble().
easternLongitudeString()
QString Isis::FeatureNomenclature::Feature::easternLongitudeString () const
Returns
The feature's easternmost (max) longitude as a human readable string.
Referenced by toWidget().
featureType()
QString Isis::FeatureNomenclature::Feature::featureType () const
Returns
The type of feature (for example, crater)
Referenced by toWidget().
id()
QString Isis::FeatureNomenclature::Feature::id () const
Returns
The feature ID (typically a number)
Referenced by toWidget().
lastUpdated()
QString Isis::FeatureNomenclature::Feature::lastUpdated () const
Returns
The feature's last updated time as a string.
Referenced by toWidget().
name()
QString Isis::FeatureNomenclature::Feature::name () const
Returns
The feature name (not always compatible with QString)
northernLatitude()
Latitude Isis::FeatureNomenclature::Feature::northernLatitude () const
Returns
The feature's northernmost (max) latitude.
References Isis::Angle::Degrees, and Isis::toDouble().
northernLatitudeString()
QString Isis::FeatureNomenclature::Feature::northernLatitudeString () const
Returns
The feature's northernmost (max) latitude as a human readable string.
Referenced by toWidget().
operator=()
FeatureNomenclature::Feature & Isis::FeatureNomenclature::Feature::operator= (const Feature & rhs)
Assign the values of this feature from the values of rhs.
Parameters
rhs The feature on the right hand side of the '=' operator
Returns
*this
References Isis::FeatureNomenclature::swap().
origin()
QString Isis::FeatureNomenclature::Feature::origin () const
Returns
The feature's origin
Referenced by toWidget().
originatingContinent()
QString Isis::FeatureNomenclature::Feature::originatingContinent () const
Returns
The continent from which the person who named the feature originated.
Referenced by toWidget().
originatingEthnicity()
QString Isis::FeatureNomenclature::Feature::originatingEthnicity () const
Returns
The ethnicity of the person who named the feature.
Referenced by toWidget().
referenceString()
QString Isis::FeatureNomenclature::Feature::referenceString () const
Returns
The feature's reference (bibliography) information
Referenced by toWidget().
referenceUrl()
QUrl Isis::FeatureNomenclature::Feature::referenceUrl () const
Returns
The feature's online URL.
referenceUrlString()
QString Isis::FeatureNomenclature::Feature::referenceUrlString () const
Returns
The feature's online URL as a HTML string (it is hyperlinked).
Referenced by toWidget().
southernLatitude()
Latitude Isis::FeatureNomenclature::Feature::southernLatitude () const
Returns
The feature's southernmost (min) latitude.
References Isis::Angle::Degrees, and Isis::toDouble().
southernLatitudeString()
QString Isis::FeatureNomenclature::Feature::southernLatitudeString () const
Returns
The feature's southernmost (min) latitude as a human readable string.
Referenced by toWidget().
status()
FeatureNomenclature::IAUStatus Isis::FeatureNomenclature::Feature::status () const
Returns
The feature's enumerated approval status.
swap()
void Isis::FeatureNomenclature::Feature::swap (Feature & other)
Swap the member data of this feature with another feature.
Parameters
other The feature to swap with.
system()
QString Isis::FeatureNomenclature::Feature::system () const
Returns
The target's system (i.e. Target: Moon, System: Earth)
Referenced by toWidget().
target()
QString Isis::FeatureNomenclature::Feature::target () const
Returns
The target name
Referenced by toWidget().
toWidget()
QWidget * Isis::FeatureNomenclature::Feature::toWidget () const
This converts the data in this feature to a widget.
All of the information returned by the server is encapsulated in this widget. There are no controls, this is a display only.
Returns
A widget that displays all of the feature information
References approvalDate(), approvalStatus(), centerLatitudeString(), centerLongitudeString(), controlNet(), diameterString(), displayName(), easternLongitudeString(), featureType(), id(), lastUpdated(), northernLatitudeString(), origin(), originatingContinent(), originatingEthnicity(), referenceString(), referenceUrlString(), southernLatitudeString(), system(), target(), and westernLongitudeString().
westernLongitude()
Longitude Isis::FeatureNomenclature::Feature::westernLongitude () const
Returns
The feature's westernmost (min) longitude.
References Isis::Angle::Degrees, and Isis::toDouble().
westernLongitudeString()
QString Isis::FeatureNomenclature::Feature::westernLongitudeString () const
Returns
The feature's westernmost (min) longitude as a human readable string.
Referenced by toWidget().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/FeatureNomenclature/FeatureNomenclature.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/FeatureNomenclature/FeatureNomenclature.cpp