Isis Developer Reference: Isis::GainUnitConversion Class Reference
Isis::GainUnitConversion Class Reference
Utility
Computes units parameters for HiRISE data calibration (Ziof Module)
#include <GainUnitConversion.h>
Public Member Functions
GainUnitConversion ()
GainUnitConversion (HiCalConf &conf, const QString &units, Cube *cube)
virtual ~GainUnitConversion ()
Destructor.
QString name () const
Returns name of component.
QString getcsvFile () const
Returns expanded name of last CSV file loaded by loadCsv.
int size () const
Returns the size (number of elements) of data array.
virtual void Process (const Module &c)
Invokes the process method on the Module vector.
virtual void Process (const HiVector &v)
Default processing behavior makes a reference copy of data array.
HiVector loadCsv (const QString &csvBase, const HiCalConf &conf, const DbProfile &prof, const int &elements=0)
Provide generic loading of CSV file for all modules.
const HiVector & ref () const
Return data via a const reference.
double operator() (int index) const
Return individual element of the data vector.
const HiHistory & History () const
Return recorded history of events.
virtual void record (PvlGroup &pvl, const QString keyname="ModuleHistory") const
Record history in Pvl group object.
void Dump (const QString &fname) const
Dumps the component to a specified file.
Protected Types
enum { DefaultWidth = 10 , DefaultPrecision = 6 }
Protected Member Functions
QString formatDbl (const double &value) const
Properly format values that could be special pixels.
virtual void printOn (std::ostream &o) const
Default printing of data in module.
Protected Attributes
QString _name
Name of component.
QString _csvFile
Fully expanded name of CSV file if present.
HiVector _data
Data vector.
HiHistory _history
Hierarchial component history.
int _fmtWidth
Default field with of double.
int _fmtPrecision
Default field with of double.
Detailed Description
Computes units parameters for HiRISE data calibration (Ziof Module)
This class computes the HiRISE parameters necessary to derive the user selected calibration units of the image data.
Author
2010-04-19 Kris Becker
Member Enumeration Documentation
anonymous enum
anonymous enum protected inherited
Enumerator
DefaultWidth
DefaultPrecision
Constructor & Destructor Documentation
GainUnitConversion() [1/2]
Isis::GainUnitConversion::GainUnitConversion () inline
GainUnitConversion() [2/2]
Isis::GainUnitConversion::GainUnitConversion (HiCalConf & conf, const QString & units, Cube * cube) inline
~GainUnitConversion()
virtual Isis::GainUnitConversion::~GainUnitConversion () inline virtual
Destructor.
Member Function Documentation
Dump()
void Isis::Module::Dump (const QString & fname) const inline inherited
Dumps the component to a specified file.
Parameters
fname Name of file to dump contents to
References _FILEINFO_, Isis::FileName::expanded(), and Isis::IException::User.
formatDbl()
QString Isis::Module::formatDbl (const double & value) const inline protected inherited
Properly format values that could be special pixels.
This method applies ISIS special pixel value conventions to properly print pixel values.
Parameters
[in] (double) value Input value to test for specialness and print as requested by caller
[in] (int) width Width of field in which to print the value
[in] (int) prec Precision used to format the value
Returns
(string) Formatted double value
References Isis::Module::_fmtPrecision, Isis::Module::_fmtWidth, Isis::IsSpecial(), and Isis::PixelToString().
Referenced by Isis::Module::printOn().
getcsvFile()
QString Isis::Module::getcsvFile () const inline inherited
Returns expanded name of last CSV file loaded by loadCsv.
References Isis::Module::_csvFile.
History()
const HiHistory& Isis::Module::History () const inline inherited
Return recorded history of events.
References Isis::Module::_history.
loadCsv()
HiVector Isis::Module::loadCsv (const QString & csvBase, const HiCalConf & conf, const DbProfile & prof, const int & elements = 0) inline inherited
Provide generic loading of CSV file for all modules.
This method provides generalized access to CSV files through the standardized format.
Author
Kris Becker - 4/16/2010
Parameters
cvsBase Name of base keyword for CSV file
conf Configuration parameters
prof Module profile parameters
samples Number of expect elements to be read from CSV file
Returns
HiVector
References Isis::Module::_csvFile, Isis::Module::_history, Isis::LoadCSV::filename(), Isis::LoadCSV::getVector(), Isis::LoadCSV::History(), and Isis::LoadCSV::validateSize().
name()
QString Isis::Module::name () const inline inherited
Returns name of component.
References Isis::Module::_name.
operator()()
double Isis::Module::operator() (int index) const inline inherited
Return individual element of the data vector.
References Isis::Module::_data.
printOn()
virtual void Isis::Module::printOn (std::ostream & o) const inline protected virtual inherited
Default printing of data in module.
References Isis::Module::_data, Isis::Module::_history, and Isis::Module::formatDbl().
Process() [1/2]
virtual void Isis::Module::Process (const HiVector & v) inline virtual inherited
Default processing behavior makes a reference copy of data array.
Reimplemented in Isis::SplineFill, and Isis::LowPassFilter.
References Isis::Module::_data.
Process() [2/2]
virtual void Isis::Module::Process (const Module & c) inline virtual inherited
Invokes the process method on the Module vector.
References Isis::Module::ref().
record()
virtual void Isis::Module::record (PvlGroup & pvl, const QString keyname = "ModuleHistory") const inline virtual inherited
Record history in Pvl group object.
References Isis::Module::_history, and Isis::HiHistory::makekey().
ref()
const HiVector& Isis::Module::ref () const inline inherited
Return data via a const reference.
References Isis::Module::_data.
Referenced by Isis::ZeroBufferFit::guess(), Isis::LowPassFilter::LowPassFilter(), Isis::Module::Process(), and Isis::SplineFill::SplineFill().
size()
int Isis::Module::size () const inline inherited
Returns the size (number of elements) of data array.
References Isis::Module::_data.
Member Data Documentation
_csvFile
QString Isis::Module::_csvFile protected inherited
Fully expanded name of CSV file if present.
Referenced by Isis::Module::getcsvFile(), and Isis::Module::loadCsv().
_data
HiVector Isis::Module::_data protected inherited
Data vector.
Referenced by Isis::LowPassFilter::LowPassFilter(), Isis::Module::operator()(), Isis::Module::printOn(), Isis::LowPassFilter::Process(), Isis::Module::Process(), Isis::Module::ref(), and Isis::Module::size().
_fmtPrecision
int Isis::Module::_fmtPrecision protected inherited
Default field with of double.
Referenced by Isis::Module::formatDbl().
_fmtWidth
int Isis::Module::_fmtWidth protected inherited
Default field with of double.
Referenced by Isis::Module::formatDbl().
_history
HiHistory Isis::Module::_history protected inherited
Hierarchial component history.
Referenced by Isis::ZeroBufferFit::guess(), Isis::Module::History(), Isis::Module::loadCsv(), Isis::LowPassFilter::LowPassFilter(), Isis::ZeroBufferFit::Normalize(), Isis::Module::printOn(), Isis::LowPassFilter::Process(), Isis::SplineFill::Process(), Isis::Module::record(), Isis::ZeroBufferFit::Solve(), Isis::SplineFill::SplineFill(), and Isis::ZeroBufferFit::ZeroBufferFit().
_name
QString Isis::Module::_name protected inherited
Name of component.
Referenced by Isis::Module::name().
The documentation for this class was generated from the following file:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/mro/objs/HiCal/GainUnitConversion.h