Isis Developer Reference: Isis::TrackingTable Class Reference
Isis::TrackingTable Class Reference
Table to store tracking information for a mosaic.
#include <TrackingTable.h>
Public Member Functions
TrackingTable ()
Default constructor.
TrackingTable (Table table)
Constructs a TrackingTable given a Table object.
~TrackingTable ()
Destroys the TrackingTable object.
Table toTable ()
Constrcts and returns a Table object based on values in m_fileList.
FileName pixelToFileName (unsigned int pixel)
Returns the FileName that corresponds to a pixel value.
unsigned int fileNameToPixel (FileName file, QString serialNumber)
Returns the pixel value of the filename/serialnumber combination.
int fileNameToIndex (FileName file, QString serialNumber)
Returns the index of the filename/serialnumber combination.
QString pixelToSN (unsigned int pixel)
Returns the serial number that corresponds to a pixel value.
Detailed Description
Table to store tracking information for a mosaic.
This table will currently be stored in the label of a separate cube. This tracking cube will also contain a single tracking band. The DN values stored in this band will correlate to the indices in this table. Each record within this table will contain the filename of an associated cube, that cube's serial number, and the DN value associated with this cube within the tracking band (which should also be its index in the table).
Author
2018-07-19 Jesse Mapel & Summer Stapleton
Constructor & Destructor Documentation
TrackingTable() [1/2]
Isis::TrackingTable::TrackingTable ()
Default constructor.
TrackingTable() [2/2]
Isis::TrackingTable::TrackingTable (Table table)
Constructs a TrackingTable given a Table object.
The Table is used to populate m_fileList.
Parameters
table The Table object to pull the filenames and serial numbers from
References Isis::Table::Records().
~TrackingTable()
Isis::TrackingTable::~TrackingTable ()
Destroys the TrackingTable object.
Member Function Documentation
fileNameToIndex()
int Isis::TrackingTable::fileNameToIndex (FileName file, QString serialNumber)
Returns the index of the filename/serialnumber combination.
Parameters
file The FileName within m_fileList to find the index of
serialNumber The QString of the serial number within m_fileList to find the index of
Returns
int The index corresponding to the filename/serialnumber combination
fileNameToPixel()
unsigned int Isis::TrackingTable::fileNameToPixel (FileName file, QString serialNumber)
Returns the pixel value of the filename/serialnumber combination.
Parameters
file The FileName within m_fileList to find the pixel value of
serialNumber The QString of the serial number within m_fileList to find the pixel value of
Returns
unsigned int The pixel value corresponding to the filename/serialnumber combination
References Isis::FileName::name(), and Isis::VALID_MINUI4.
Referenced by Isis::ProcessMosaic::StartProcess().
pixelToFileName()
FileName Isis::TrackingTable::pixelToFileName (unsigned int pixel)
Returns the FileName that corresponds to a pixel value.
Parameters
pixel The pixel value to find the filename for
Returns
FileName The FileName represented by the pixel value
References _FILEINFO_, Isis::toString(), and Isis::VALID_MINUI4.
pixelToSN()
QString Isis::TrackingTable::pixelToSN (unsigned int pixel)
Returns the serial number that corresponds to a pixel value.
Parameters
pixel The pixel value to find the serial number for
Returns
QString The serial number represented by the pixel value
References _FILEINFO_, Isis::toString(), and Isis::VALID_MINUI4.
toTable()
Table Isis::TrackingTable::toTable ()
Constrcts and returns a Table object based on values in m_fileList.
Returns
Table The constructed table to be returned
References Isis::TableField::name(), Isis::trackingTableName, and Isis::VALID_MINUI4.
Referenced by Isis::ProcessMosaic::StartProcess().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/TrackingTable/TrackingTable.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/TrackingTable/TrackingTable.cpp