Isis Developer Reference: Isis::CnetDisplayProperties Class Reference
Isis::CnetDisplayProperties Class Reference
Handles how control networks should be displayed to the user.
#include <CnetDisplayProperties.h>
Public Types
enum coordinateDisplayType { LatLonRadius = 0 , XYZ = 1 }
Returns coordinate display type (0 = LatLonRadius, 1 = XYZ).
Signals
void composeProgressChanged (int)
void composeProgressRangeChanged (int, int)
void compositionFinished ()
Public Member Functions
virtual ~CnetDisplayProperties ()
bool currentlyComposing () const
QList< QString > getCubeList (ControlNet *cnet) const
TODO comment me.
QString getFileName (QString fileName, bool forceFullPaths=false) const
QString getImageName (QString cubeSerialNumber, bool forceFullPaths=false) const
QString getSerialNumber (QString imageId)
bool getShowsFullPaths () const
CnetDisplayProperties::coordinateDisplayType coordinateDisplayType ()
void setCubeList (QString fileName)
void setFileNameUsage (bool preferFileNames)
void setShowsFullPaths (bool newState)
void setCoordinateDisplayType (enum coordinateDisplayType coordDisplay)
Sets the coordinate display type (0 = LatLonRadius, 1 = XYZ).
Static Public Member Functions
static CnetDisplayProperties * getInstance ()
Detailed Description
Handles how control networks should be displayed to the user.
This class handles how control networks should be displayed to the user. For example, this class keeps track of whether cube serial numbers or file names should be displayed to the user, and provides an interface to translate between the two.
This class is a singleton.
Author
????-??-?? Eric Hyer
Member Enumeration Documentation
coordinateDisplayType
enum enum CnetDisplayProperties::coordinateDisplayType Isis::CnetDisplayProperties::coordinateDisplayType
Returns coordinate display type (0 = LatLonRadius, 1 = XYZ).
Returns
enum CnetDisplayProperties::coordinateDisplayType.
Enumerator
LatLonRadius
XYZ
Constructor & Destructor Documentation
~CnetDisplayProperties()
Isis::CnetDisplayProperties::~CnetDisplayProperties () virtual
Member Function Documentation
composeProgressChanged
void Isis::CnetDisplayProperties::composeProgressChanged (int) signal
composeProgressRangeChanged
void Isis::CnetDisplayProperties::composeProgressRangeChanged (int , int) signal
compositionFinished
void Isis::CnetDisplayProperties::compositionFinished () signal
coordinateDisplayType()
CnetDisplayProperties::coordinateDisplayType Isis::CnetDisplayProperties::coordinateDisplayType ()
currentlyComposing()
bool Isis::CnetDisplayProperties::currentlyComposing () const
Referenced by getCubeList().
getCubeList()
QList< QString > Isis::CnetDisplayProperties::getCubeList (ControlNet * cnet) const
TODO comment me.
If a cube list is currently being loaded, this method will return an empty list. If there is no cube list, it will also return an empty list.
This method is thread safe.
References currentlyComposing(), Isis::ControlNet::GetCubeSerials(), and getImageName().
getFileName()
QString Isis::CnetDisplayProperties::getFileName (QString fileName, bool forceFullPaths = false) const
References getShowsFullPaths().
Referenced by getImageName().
getImageName()
QString Isis::CnetDisplayProperties::getImageName (QString cubeSerialNumber, bool forceFullPaths = false) const
Parameters
cubeSerialNumber Cube serial number as a QString
Returns
The file name associated with the given cube serial number, or the given cube serial number if a file name can not be found in the current cube list.
See also
setCubeList()
This method is thread safe!
References getFileName().
Referenced by getCubeList().
getInstance()
CnetDisplayProperties * Isis::CnetDisplayProperties::getInstance () static
Referenced by Isis::PointMeasureFilterSelector::changeFilter(), Isis::CnetEditorWidget::CnetEditorWidget(), Isis::ImagePointFilterSelector::createSelector(), Isis::PointMeasureFilterSelector::createSelector(), Isis::ImageIdFilter::evaluate(), Isis::AbstractPointItem::getColumnName(), Isis::AbstractMeasureItem::getData(), Isis::AbstractPointItem::getData(), Isis::PointTableModel::getPointWarningMessage(), Isis::AbstractMeasureItem::setData(), Isis::AbstractPointItem::setData(), Isis::CnetEditorWidget::setLatLonRadiusCoordinateDisplay(), and Isis::CnetEditorWidget::setXYZCoordinateDisplay().
getSerialNumber()
QString Isis::CnetDisplayProperties::getSerialNumber (QString imageId)
Referenced by Isis::AbstractMeasureItem::setData().
getShowsFullPaths()
bool Isis::CnetDisplayProperties::getShowsFullPaths () const
Referenced by getFileName().
setCoordinateDisplayType()
void Isis::CnetDisplayProperties::setCoordinateDisplayType (enum coordinateDisplayType coordDisplay)
Sets the coordinate display type (0 = LatLonRadius, 1 = XYZ).
Parameters
coordDisplay coordinate display type.
Returns
void.
Referenced by Isis::CnetEditorWidget::setLatLonRadiusCoordinateDisplay(), and Isis::CnetEditorWidget::setXYZCoordinateDisplay().
setCubeList()
void Isis::CnetDisplayProperties::setCubeList (QString fileName)
References _FILEINFO_, and Isis::IException::Programmer.
setFileNameUsage()
void Isis::CnetDisplayProperties::setFileNameUsage (bool preferFileNames)
setShowsFullPaths()
void Isis::CnetDisplayProperties::setShowsFullPaths (bool newState)
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/CnetDisplayProperties.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/CnetDisplayProperties.cpp