Isis Developer Reference: Isis::CameraDetectorMap Class Reference
Isis::CameraDetectorMap Class Reference
Convert between parent image coordinates and detector coordinates.
#include <CameraDetectorMap.h>
Public Member Functions
CameraDetectorMap (Camera *parent=0)
Default constructor assumes no summing and starting detector offsets.
virtual ~CameraDetectorMap ()
Destructor.
virtual bool SetParent (const double sample, const double line)
Compute detector position from a parent image coordinate.
virtual bool SetParent (const double sample, const double line, const double deltaT)
Compute detector position from a parent image coordinate.
virtual bool SetDetector (const double sample, const double line)
Compute parent position from a detector coordinate.
double AdjustedStartingSample () const
Return the starting detector sample adjusted for summation.
double AdjustedStartingLine () const
Return the starting detector line adjusted for summation.
double ParentSample () const
Return parent sample.
double ParentLine () const
Return parent line.
double DetectorSample () const
Return detector sample.
double DetectorLine () const
Return detector line.
void SetStartingDetectorSample (const double sample)
Set the starting detector sample.
void SetStartingDetectorLine (const double line)
Set the starting detector line.
void SetDetectorSampleSumming (const double summing)
Set sample summing mode.
void SetDetectorLineSumming (const double summing)
Set line summing mode.
virtual double SampleScaleFactor () const
Return scaling factor for computing sample resolution.
virtual double LineScaleFactor () const
Return scaling factor for computing line resolution.
virtual double LineRate () const
Return the line collection rate (0 for framing cameras)
virtual double exposureDuration (const double sample, const double line, const int band) const
This virtual method is for returning the exposure duration of a given pixel.
Protected Attributes
Camera * p_camera
Pointer to the camera.
double p_parentSample
The parent sample calculated from the detector.
double p_parentLine
The parent line calculated from the detector.
double p_detectorLine
Detector coordinate line value.
double p_detectorSample
Detector coordinate sample value.
double p_detectorSampleSumming
The scaling factor for computing sample resolution.
double p_detectorLineSumming
The scaling factor for computing line resolution.
double p_startingDetectorSample
Detector start coordinate sample value.
double p_startingDetectorLine
Detector start coordinate line value.
double p_ss
Start sample.
double p_sl
Start line.
Detailed Description
Convert between parent image coordinates and detector coordinates.
This base class is used to convert between parent detector coordinates (sample/line) and detector coordinates for the camera.
See also
Camera
Author
2005-02-03 Jeff Anderson
Constructor & Destructor Documentation
CameraDetectorMap()
Isis::CameraDetectorMap::CameraDetectorMap (Camera * parent = 0)
Default constructor assumes no summing and starting detector offsets.
Parameters
parent Camera that will use this detector map
References p_camera, p_detectorLineSumming, p_detectorSampleSumming, p_startingDetectorLine, p_startingDetectorSample, and Isis::Camera::SetDetectorMap().
~CameraDetectorMap()
Isis::CameraDetectorMap::~CameraDetectorMap () virtual
Destructor.
Member Function Documentation
AdjustedStartingLine()
double Isis::CameraDetectorMap::AdjustedStartingLine () const
Return the starting detector line adjusted for summation.
Returns
(double) The starting line
References p_sl.
AdjustedStartingSample()
double Isis::CameraDetectorMap::AdjustedStartingSample () const
Return the starting detector sample adjusted for summation.
Returns
(double) The starting sample
References p_ss.
DetectorLine()
double Isis::CameraDetectorMap::DetectorLine () const
Return detector line.
Returns
(double) The detector line
References p_detectorLine.
Referenced by Isis::Camera::SetImage().
DetectorSample()
double Isis::CameraDetectorMap::DetectorSample () const
Return detector sample.
Returns
(double) The detector sample
References p_detectorSample.
Referenced by Isis::Camera::SetImage().
exposureDuration()
double Isis::CameraDetectorMap::exposureDuration (const double sample, const double line, const int band) const virtual
This virtual method is for returning the exposure duration of a given pixel.
For framing cameras, exposure duration is not available so it throws an error.
Parameters
sample The sample of the desired pixel.
line The line of the desired pixel.
band The band of the desired pixel.
Returns
double The exposure duration for the desired pixel in seconds.
Exceptions
IException::Programmer "Exposure duration is only available for LineScan, VariableLineScan, and PushFrame Cameras."
Reimplemented in Isis::NirsDetectorMap, Isis::VariableLineScanCameraDetectorMap, Isis::PushFrameCameraDetectorMap, and Isis::LineScanCameraDetectorMap.
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by Isis::Camera::exposureDuration().
LineRate()
double Isis::CameraDetectorMap::LineRate () const virtual
Return the line collection rate (0 for framing cameras)
Returns
(double) The line collection rate
Reimplemented in Isis::RadarPulseMap, Isis::LineScanCameraDetectorMap, and Isis::ApolloPanoramicDetectorMap.
LineScaleFactor()
double Isis::CameraDetectorMap::LineScaleFactor () const virtual
Return scaling factor for computing line resolution.
Returns
(double) The scaling factor for line resolution
References p_detectorLineSumming.
Referenced by Isis::Camera::LineResolution(), Isis::Camera::ObliqueLineResolution(), Isis::ThemisIrCamera::SetBand(), Isis::PushFrameCameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetParent(), and Isis::PushFrameCameraDetectorMap::TotalFramelets().
ParentLine()
double Isis::CameraDetectorMap::ParentLine () const
Return parent line.
Returns
(double) The parent line
References p_parentLine.
Referenced by Isis::Camera::SetRightAscensionDeclination().
ParentSample()
double Isis::CameraDetectorMap::ParentSample () const
Return parent sample.
Returns
(double) The parent sample
References p_parentSample.
Referenced by Isis::Camera::SetRightAscensionDeclination().
SampleScaleFactor()
double Isis::CameraDetectorMap::SampleScaleFactor () const virtual
Return scaling factor for computing sample resolution.
Returns
(double) The scaling factor for sample resolution
References p_detectorSampleSumming.
Referenced by Isis::Camera::ObliqueSampleResolution(), and Isis::Camera::SampleResolution().
SetDetector()
bool Isis::CameraDetectorMap::SetDetector (const double sample, const double line) virtual
Compute parent position from a detector coordinate.
This method will compute a parent sample/line given a detector coordinate
Parameters
sample Sample number in the detector
line Line number in the detector
Returns
conversion successful
Reimplemented in Isis::MocWideAngleDetectorMap, Isis::VariableLineScanCameraDetectorMap, Isis::RollingShutterCameraDetectorMap, Isis::RadarPulseMap, Isis::PushFrameCameraDetectorMap, Isis::LineScanCameraDetectorMap, and Isis::ApolloPanoramicDetectorMap.
References p_detectorLine, p_detectorLineSumming, p_detectorSample, p_detectorSampleSumming, p_parentLine, p_parentSample, p_sl, and p_ss.
Referenced by Isis::LineScanCameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetDetector(), Isis::RadarPulseMap::SetDetector(), Isis::VariableLineScanCameraDetectorMap::SetDetector(), and Isis::Camera::SetRightAscensionDeclination().
SetDetectorLineSumming()
void Isis::CameraDetectorMap::SetDetectorLineSumming (const double summing) inline
Set line summing mode.
Use this method to specify if detector lines are summed/averaged. That is, one image lines represents the average of N detectors. If not set the default is 1.
Parameters
summing Line summing mode
References p_detectorLineSumming.
Referenced by Isis::CrismCamera::CrismCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::MarciCamera::MarciCamera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), and Isis::ThemisVisCamera::ThemisVisCamera().
SetDetectorSampleSumming()
void Isis::CameraDetectorMap::SetDetectorSampleSumming (const double summing) inline
Set sample summing mode.
Use this method to specify if detector samples are summed/averaged. That is, one image sample represents the average of N detectors. If not set the default is 1.
Parameters
summing Sample summing mode
References p_detectorSampleSumming.
Referenced by Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::MarciCamera::MarciCamera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), and Isis::ThemisVisCamera::ThemisVisCamera().
SetParent() [1/2]
bool Isis::CameraDetectorMap::SetParent (const double sample, const double line) virtual
Compute detector position from a parent image coordinate.
This method will compute the detector position from the parent line/sample coordinate
Parameters
sample Sample number in the parent image
line Line number in the parent image
Returns
conversion successful
Reimplemented in Isis::MocWideAngleDetectorMap, Isis::VariableLineScanCameraDetectorMap, Isis::RollingShutterCameraDetectorMap, Isis::RadarPulseMap, Isis::PushFrameCameraDetectorMap, Isis::LineScanCameraDetectorMap, and Isis::ApolloPanoramicDetectorMap.
Referenced by Isis::LineScanCameraGroundMap::FindFocalPlane(), Isis::LineScanCameraGroundMap::FindSpacecraftDistance(), Isis::Camera::SetImage(), Isis::RadarPulseMap::SetParent(), Isis::LineScanCameraDetectorMap::SetParent(), Isis::PushFrameCameraDetectorMap::SetParent(), and Isis::VariableLineScanCameraDetectorMap::SetParent().
SetParent() [2/2]
bool Isis::CameraDetectorMap::SetParent (const double sample, const double line, const double deltaT) virtual
Compute detector position from a parent image coordinate.
This method will compute the detector position from the parent line/sample coordinate and an offset from the currently set time in seconds. If the time has not already been set, the input offset is not applied.
Parameters
sample Sample number in the parent image
line Line number in the parent image
deltaT option time offset from center of exposure in seconds
Returns
conversion successful
Reimplemented in Isis::VariableLineScanCameraDetectorMap, Isis::RollingShutterCameraDetectorMap, Isis::PushFrameCameraDetectorMap, and Isis::LineScanCameraDetectorMap.
References Isis::iTime::Et(), Isis::Spice::isTimeSet(), p_camera, p_detectorLine, p_detectorLineSumming, p_detectorSample, p_detectorSampleSumming, p_parentLine, p_parentSample, p_sl, p_ss, Isis::Sensor::setTime(), and Isis::Spice::time().
SetStartingDetectorLine()
void Isis::CameraDetectorMap::SetStartingDetectorLine (const double line) inline
Set the starting detector line.
Use this method to specify the starting detector that represents the first image line in the cube. If not set the default is 1.
Parameters
line Starting detector line
References p_startingDetectorLine.
Referenced by Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::JunoCamera::JunoCamera(), Isis::MdisCamera::MdisCamera(), and Isis::RosettaOsirisCamera::RosettaOsirisCamera().
SetStartingDetectorSample()
void Isis::CameraDetectorMap::SetStartingDetectorSample (const double sample) inline
Set the starting detector sample.
Use this method to specify the starting detector that represents the first image sample in the cube. If not set the default is 1.
Parameters
sample Starting detector sample
References p_startingDetectorSample.
Referenced by Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::CTXCamera::CTXCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::MdisCamera::MdisCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), and Isis::RosettaOsirisCamera::RosettaOsirisCamera().
Member Data Documentation
p_camera
Camera* Isis::CameraDetectorMap::p_camera protected
Pointer to the camera.
Referenced by CameraDetectorMap(), Isis::LineScanCameraDetectorMap::SetDetector(), Isis::RadarPulseMap::SetDetector(), Isis::VariableLineScanCameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetFramelet(), Isis::RadarPulseMap::SetParent(), SetParent(), Isis::LineScanCameraDetectorMap::SetParent(), Isis::RollingShutterCameraDetectorMap::SetParent(), Isis::VariableLineScanCameraDetectorMap::SetParent(), and Isis::PushFrameCameraDetectorMap::TotalFramelets().
p_detectorLine
double Isis::CameraDetectorMap::p_detectorLine protected
Detector coordinate line value.
Referenced by DetectorLine(), SetDetector(), Isis::PushFrameCameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::RadarPulseMap::SetParent(), SetParent(), Isis::LineScanCameraDetectorMap::SetParent(), Isis::PushFrameCameraDetectorMap::SetParent(), Isis::RollingShutterCameraDetectorMap::SetParent(), and Isis::VariableLineScanCameraDetectorMap::SetParent().
p_detectorLineSumming
double Isis::CameraDetectorMap::p_detectorLineSumming protected
The scaling factor for computing line resolution.
Referenced by CameraDetectorMap(), LineScaleFactor(), SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), SetDetectorLineSumming(), SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_detectorSample
double Isis::CameraDetectorMap::p_detectorSample protected
Detector coordinate sample value.
Referenced by DetectorSample(), SetDetector(), Isis::PushFrameCameraDetectorMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_detectorSampleSumming
double Isis::CameraDetectorMap::p_detectorSampleSumming protected
The scaling factor for computing sample resolution.
Referenced by CameraDetectorMap(), SampleScaleFactor(), SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), SetDetectorSampleSumming(), SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_parentLine
double Isis::CameraDetectorMap::p_parentLine protected
The parent line calculated from the detector.
Referenced by ParentLine(), SetDetector(), Isis::LineScanCameraDetectorMap::SetDetector(), Isis::PushFrameCameraDetectorMap::SetDetector(), Isis::RadarPulseMap::SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), Isis::VariableLineScanCameraDetectorMap::SetDetector(), SetParent(), Isis::PushFrameCameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_parentSample
double Isis::CameraDetectorMap::p_parentSample protected
The parent sample calculated from the detector.
Referenced by ParentSample(), SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), SetParent(), Isis::PushFrameCameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_sl
double Isis::CameraDetectorMap::p_sl protected
Start line.
Referenced by AdjustedStartingLine(), SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_ss
double Isis::CameraDetectorMap::p_ss protected
Start sample.
Referenced by AdjustedStartingSample(), SetDetector(), Isis::RollingShutterCameraDetectorMap::SetDetector(), SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
p_startingDetectorLine
double Isis::CameraDetectorMap::p_startingDetectorLine protected
Detector start coordinate line value.
Referenced by CameraDetectorMap(), and SetStartingDetectorLine().
p_startingDetectorSample
double Isis::CameraDetectorMap::p_startingDetectorSample protected
Detector start coordinate sample value.
Referenced by CameraDetectorMap(), and SetStartingDetectorSample().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/CameraDetectorMap/CameraDetectorMap.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/CameraDetectorMap/CameraDetectorMap.cpp