Isis Developer Reference: Isis::ChipViewport Class Reference
Isis::ChipViewport Class Reference
Viewport for Isis Chips.
#include <ChipViewport.h>
Public Slots
void autoStretch ()
Apply automatic stretch using data from entire chip.
void stretchFromCubeViewport (Stretch *, CubeViewport *)
Applies a new stretch to the specified cube viewport.
void changeStretchLock (int)
Locks or unlocks the stretch on the chip viewport during transformations (zoom, pan, etc.)
void setPoints (bool checked)
Slot to set whether control points are drawn.
void setCross (bool checked)
Slot to change state of crosshair.
void rotateChip (int rotation)
Slot to rotate chip.
void setCircle (bool checked)
Slot to change state of circle.
void setCircleSize (int size)
Set the size of the circle.
void geomChip (Chip *matchChip, Cube *matchChipCube)
Slot to geom chip (apply geometry transformation)
void nogeomChip ()
Slot to un-geom chip (revert geometry transformation)
void panUp ()
Pan up.
void panDown ()
Pan down.
void panLeft ()
Pan left.
void panRight ()
Pan right.
void zoomIn ()
Zoom in.
void zoomOut ()
Zoom out.
void zoom1 ()
Zoom by a factor of one.
void zoom (double zoomFactor)
Zoom by a specified factor.
void refreshView (double tackSample, double tackLine)
Slot to refresh viewport when the tack point has changed.
void setControlNet (ControlNet *newControlNet)
sets the ControlNet to be used for drawing measure locations
Signals
void tackPointChanged (double)
< Signal sent when tack point changes
void userMovedTackPoint ()
Public Member Functions
ChipViewport (int width, int height, QWidget *parent=0)
Construct an empty viewport.
virtual ~ChipViewport ()
Destructor.
bool cubeToViewport (double samp, double line, int &x, int &y)
Get viewport x and y from cube sample and line.
void setChip (Chip *chip, Cube *chipCube)
Set chip.
void loadView (ChipViewport &newView)
Load with another ChipViewport, used for blinking.
Chip * chip () const
Return chip.
Cube * chipCube () const
int chipSamples () const
Return the number of samples in the chip.
int chipLines () const
Return the number of lines in the chip.
int grayBand () const
Return the gray band currently viewed.
double tackSample ()
Return the position of cube under cross hair.
double tackLine ()
Returns tack line.
double zoomFactor ()
Return the zoom factor.
Stretch grayStretch () const
Draw X on point.
Protected Member Functions
void paintEvent (QPaintEvent *e)
Repaint the viewport.
void enterEvent (QEvent *e)
If mouse enters, make sure key events are processed w/o clicking.
void keyPressEvent (QKeyEvent *e)
Process arrow keystrokes on cube.
void mousePressEvent (QMouseEvent *event)
Process mouse events.
Detailed Description
Viewport for Isis Chips.
Author
2007-05-01 Tracie Sucharski
Constructor & Destructor Documentation
ChipViewport()
Isis::ChipViewport::ChipViewport (int width, int height, QWidget * parent = 0)
Construct an empty viewport.
Parameters
width The width of the viewport
height The height of the viewport
parent The parent widget
~ChipViewport()
Isis::ChipViewport::~ChipViewport () virtual
Destructor.
Member Function Documentation
autoStretch
void Isis::ChipViewport::autoStretch () slot
Apply automatic stretch using data from entire chip.
Referenced by geomChip(), nogeomChip(), rotateChip(), and setChip().
changeStretchLock
void Isis::ChipViewport::changeStretchLock (int newStatus) slot
Locks or unlocks the stretch on the chip viewport during transformations (zoom, pan, etc.)
Parameters
newStatus Non-zero locks the stretch
chip()
Chip* Isis::ChipViewport::chip () const inline
Return chip.
Referenced by setChip().
chipCube()
Cube* Isis::ChipViewport::chipCube () const inline
Referenced by setChip().
chipLines()
int Isis::ChipViewport::chipLines () const inline
Return the number of lines in the chip.
References Isis::Chip::Lines().
chipSamples()
int Isis::ChipViewport::chipSamples () const inline
Return the number of samples in the chip.
References Isis::Chip::Samples().
cubeToViewport()
bool Isis::ChipViewport::cubeToViewport (double samp, double line, int & x, int & y)
Get viewport x and y from cube sample and line.
Parameters
samp Sample in cube
line Line in cube
x Calcualated viewport x coordinate
y Calcualated viewport y coordinate
Returns
bool true if the point is contained in the viewport, false otherwise
References Isis::Chip::ChipLine(), Isis::Chip::ChipSample(), Isis::Chip::IsInsideChip(), and Isis::Chip::SetCubePosition().
Referenced by paintEvent().
enterEvent()
void Isis::ChipViewport::enterEvent (QEvent * e) protected
If mouse enters, make sure key events are processed w/o clicking.
Parameters
e QEvent
geomChip
void Isis::ChipViewport::geomChip (Chip * matchChip, Cube * matchChipCube) slot
Slot to geom chip (apply geometry transformation)
Parameters
matchChip The matching chip for the geometry
matchChipCube The matching chip's cube for the geometry
References autoStretch(), Isis::Chip::Load(), and Isis::IException::toString().
grayBand()
int Isis::ChipViewport::grayBand () const inline
Return the gray band currently viewed.
grayStretch()
Stretch Isis::ChipViewport::grayStretch () const inline
Draw X on point.
Return the gray band stretch
keyPressEvent()
void Isis::ChipViewport::keyPressEvent (QKeyEvent * e) protected
Process arrow keystrokes on cube.
Parameters
e QKeyEvent
References Isis::Chip::CubeLine(), Isis::Chip::CubeSample(), Isis::Chip::SetChipPosition(), Isis::Chip::TackLine(), Isis::Chip::TackSample(), and userMovedTackPoint().
loadView()
void Isis::ChipViewport::loadView (ChipViewport & newView)
Load with another ChipViewport, used for blinking.
Load with info from given ChipViewport.
Parameters
newView The chip viewport to load from
mousePressEvent()
void Isis::ChipViewport::mousePressEvent (QMouseEvent * event) protected
Process mouse events.
Parameters
event QMouseEvent
References Isis::Chip::CubeLine(), Isis::Chip::CubeSample(), Isis::Chip::SetChipPosition(), and userMovedTackPoint().
nogeomChip
void Isis::ChipViewport::nogeomChip () slot
Slot to un-geom chip (revert geometry transformation)
References autoStretch(), Isis::Chip::Load(), and Isis::IException::toString().
paintEvent()
void Isis::ChipViewport::paintEvent (QPaintEvent * e) protected
Repaint the viewport.
Parameters
e QPaintEvent
References Isis::SerialNumber::Compose(), cubeToViewport(), Isis::ControlPoint::Fixed, Isis::ControlNet::GetCubeSerials(), Isis::ControlMeasure::GetLine(), Isis::ControlNet::GetMeasuresInCube(), Isis::ControlNet::GetNumPoints(), Isis::ControlMeasure::GetSample(), Isis::ControlPoint::GetType(), Isis::ControlMeasure::IsIgnored(), Isis::ControlPoint::IsIgnored(), and Isis::ControlMeasure::Parent().
panDown
void Isis::ChipViewport::panDown () slot
Pan down.
References Isis::Chip::CubeLine(), Isis::Chip::CubeSample(), Isis::Chip::SetChipPosition(), Isis::Chip::TackLine(), and Isis::Chip::TackSample().
panLeft
void Isis::ChipViewport::panLeft () slot
Pan left.
References Isis::Chip::CubeLine(), Isis::Chip::CubeSample(), Isis::Chip::SetChipPosition(), Isis::Chip::TackLine(), and Isis::Chip::TackSample().
panRight
void Isis::ChipViewport::panRight () slot
Pan right.
References Isis::Chip::CubeLine(), Isis::Chip::CubeSample(), Isis::Chip::SetChipPosition(), Isis::Chip::TackLine(), and Isis::Chip::TackSample().
panUp
void Isis::ChipViewport::panUp () slot
Pan up.
References Isis::Chip::CubeLine(), Isis::Chip::CubeSample(), Isis::Chip::SetChipPosition(), Isis::Chip::TackLine(), and Isis::Chip::TackSample().
refreshView
void Isis::ChipViewport::refreshView (double tackSample, double tackLine) slot
Slot to refresh viewport when the tack point has changed.
Parameters
tackSample Sample on the cube to load the chip viewport at (center)
tackLine Line on the cube to load the chip viewport at (center)
References tackLine(), and tackSample().
rotateChip
void Isis::ChipViewport::rotateChip (int rotation) slot
Slot to rotate chip.
Parameters
rotation How much to rotate the chip
References autoStretch(), Isis::Chip::Load(), and Isis::IException::toString().
setChip()
void Isis::ChipViewport::setChip (Chip * chip, Cube * chipCube)
Set chip.
Set the chip for this ChipViewport.
Parameters
chip Pointer to the chip to set the viewport with
chipCube Pointer to the chip's cube
Exceptions
IException::Programmer "Can not view NULL chip pointer"
Author
Tracie Sucharski
References _FILEINFO_, autoStretch(), chip(), chipCube(), Isis::Chip::Lines(), Isis::IException::Programmer, Isis::Chip::Samples(), and tackPointChanged().
Referenced by Isis::ControlMeasureEditWidget::setLeftMeasure(), Isis::ControlPointEdit::setLeftMeasure(), Isis::ChipViewportsWidget::setPoint(), Isis::ControlMeasureEditWidget::setRightMeasure(), and Isis::ControlPointEdit::setRightMeasure().
setCircle
void Isis::ChipViewport::setCircle (bool checked) slot
Slot to change state of circle.
Parameters
checked Circle set to be drawn if true
setCircleSize
void Isis::ChipViewport::setCircleSize (int size) slot
Set the size of the circle.
Parameters
size The size of the circle
setControlNet
void Isis::ChipViewport::setControlNet (ControlNet * newControlNet) inline slot
sets the ControlNet to be used for drawing measure locations
Parameters
newControlNet The new ControlNet to be used
Referenced by Isis::ChipViewportsWidget::setPoint().
setCross
void Isis::ChipViewport::setCross (bool checked) slot
Slot to change state of crosshair.
Parameters
checked Crosshair set to be drawn if true
setPoints
void Isis::ChipViewport::setPoints (bool checked) slot
Slot to set whether control points are drawn.
Parameters
checked Control points are set to be drawn if true
Referenced by Isis::ChipViewportsWidget::setPoint().
stretchFromCubeViewport
void Isis::ChipViewport::stretchFromCubeViewport (Stretch * newStretch, CubeViewport * cvp) slot
Applies a new stretch to the specified cube viewport.
Parameters
newStretch Pointer to the new stretch to apply
cvp Pointer to the cube viewport to apply the stretch to
References Isis::CubeViewport::cube(), and Isis::Cube::fileName().
tackLine()
double Isis::ChipViewport::tackLine ()
Returns tack line.
Returns
double The tack line for the chip
References Isis::Chip::CubeLine(), Isis::Chip::SetChipPosition(), Isis::Chip::TackLine(), and Isis::Chip::TackSample().
Referenced by refreshView().
tackPointChanged
void Isis::ChipViewport::tackPointChanged (double) signal
< Signal sent when tack point changes
Referenced by setChip().
tackSample()
double Isis::ChipViewport::tackSample ()
Return the position of cube under cross hair.
Returns tack sample.
Returns
double The tack sample for the chip
References Isis::Chip::CubeSample(), Isis::Chip::SetChipPosition(), Isis::Chip::TackLine(), and Isis::Chip::TackSample().
Referenced by refreshView().
userMovedTackPoint
void Isis::ChipViewport::userMovedTackPoint () signal
Referenced by keyPressEvent(), and mousePressEvent().
zoom
void Isis::ChipViewport::zoom (double zoomFactor) slot
Zoom by a specified factor.
Parameters
zoomFactor The zoom factor
References zoomFactor().
zoom1
void Isis::ChipViewport::zoom1 () slot
Zoom by a factor of one.
zoomFactor()
double Isis::ChipViewport::zoomFactor ()
Return the zoom factor.
Returns the current zoom factor.
Returns
double The current zoom factor
Referenced by zoom().
zoomIn
void Isis::ChipViewport::zoomIn () slot
Zoom in.
zoomOut
void Isis::ChipViewport::zoomOut () slot
Zoom out.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ChipViewport/ChipViewport.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ChipViewport/ChipViewport.cpp