Isis Developer Reference: Isis::SparseBlockColumnMatrix Class Reference
Isis::SparseBlockColumnMatrix Class Reference
Utility
SparseBlockColumnMatrix.
#include <SparseBlockMatrix.h>
Public Member Functions
SparseBlockColumnMatrix ()
Default constructor.
~SparseBlockColumnMatrix ()
Destructor.
SparseBlockColumnMatrix (const SparseBlockColumnMatrix &src)
Copy constructor.
SparseBlockColumnMatrix & operator= (const SparseBlockColumnMatrix &src)
"Equals" operator.
void wipe ()
Deletes all pointer elements and removes them from the map.
void copy (const SparseBlockColumnMatrix &src)
Copy method.
void zeroBlocks ()
Sets all elements of all matrix blocks to zero.
bool insertMatrixBlock (int nColumnBlock, int nRows, int nCols)
Inserts a "newed" LinearAlgebra::Matrix pointer of size (nRows, nCols) into the map with the block column number as key.
void setStartColumn (int nStartColumn)
Sets starting column for block in full matrix.
int startColumn () const
Sets starting column for block in full matrix.
int numberOfElements ()
Returns total number of matrix elements in map (NOTE: NOT the number of matrix blocks).
int numberOfRows ()
Returns total number of rows in map (this needs to be clarified and maybe rewritten).
int numberOfColumns ()
Returns total number of columns in map (NOTE: NOT the number of matrix blocks).
void print (std::ostream &outstream)
Prints matrix blocks to std output stream out for debugging.
void printClean (std::ostream &outstream)
Prints matrix blocks to std output stream out for debugging.
Protected Attributes
int m_startColumn
starting column for this Block Column in full matrix e.g.
Detailed Description
SparseBlockColumnMatrix.
The SparseBlockMatrix class is a QList of SparseBlockColumnMatrix objects. Each SparseBlockColumnMatrix is a QMap of square matrix blocks and represents a column of square matrix blocks in the reduced normal equations matrix. The key into each column map is the block's row index. The value at each key is a square dense matrix (Boost matrix) with a dimension equivalent to the number of exterior orientation parameters used for the image. Zero blocks are not stored.
Author
2011-07-29 Ken Edmundson
Constructor & Destructor Documentation
SparseBlockColumnMatrix() [1/2]
Isis::SparseBlockColumnMatrix::SparseBlockColumnMatrix ()
Default constructor.
~SparseBlockColumnMatrix()
Isis::SparseBlockColumnMatrix::~SparseBlockColumnMatrix ()
Destructor.
See description of wipe method below.
SparseBlockColumnMatrix() [2/2]
Isis::SparseBlockColumnMatrix::SparseBlockColumnMatrix (const SparseBlockColumnMatrix & src)
Copy constructor.
Calls copy method immediately below.
Parameters
src SparseBlockColumnMatrix to copy
Member Function Documentation
copy()
void Isis::SparseBlockColumnMatrix::copy (const SparseBlockColumnMatrix & src)
Copy method.
Parameters
src SparseBlockColumnMatrix to copy
References startColumn().
insertMatrixBlock()
bool Isis::SparseBlockColumnMatrix::insertMatrixBlock (int nColumnBlock, int nRows, int nCols)
Inserts a "newed" LinearAlgebra::Matrix pointer of size (nRows, nCols) into the map with the block column number as key.
The clear call initializes the matrix elements to zero. If an entry exists at the key nColumnBlock, no insertion is made.
Parameters
nColumnBlock block column number of inserted matrix (key into map)
nRows number of rows in matrix to be inserted
nCols number of columns in matrix to be inserted
Returns
bool Returns true if insertion is successful or if block already exists at nColumnBlock Returns false if attempt to allocate new block fails
Referenced by Isis::operator>>().
numberOfColumns()
int Isis::SparseBlockColumnMatrix::numberOfColumns ()
Returns total number of columns in map (NOTE: NOT the number of matrix blocks).
Returns
int Total number of columns in SparseBlockColumnMatrix
numberOfElements()
int Isis::SparseBlockColumnMatrix::numberOfElements ()
Returns total number of matrix elements in map (NOTE: NOT the number of matrix blocks).
The sum of all the elements in all of the matrix blocks.
Returns
int Total number of matrix elements in SparseBlockColumnMatrix
numberOfRows()
int Isis::SparseBlockColumnMatrix::numberOfRows ()
Returns total number of rows in map (this needs to be clarified and maybe rewritten).
It's the number of rows in the block on the diagonal (the last one in the column).
Returns
int Total number of rows in SparseBlockColumnMatrix
operator=()
SparseBlockColumnMatrix & Isis::SparseBlockColumnMatrix::operator= (const SparseBlockColumnMatrix & src)
"Equals" operator.
Parameters
src SparseBlockColumnMatrix to check against
print()
void Isis::SparseBlockColumnMatrix::print (std::ostream & outstream)
Prints matrix blocks to std output stream out for debugging.
This version makes use of the Boost matrix library output of matrices as opposed to the printClean method below which explicitly prints the matrix elements for more control over the format.
Parameters
outstream output stream
Referenced by Isis::SparseBlockMatrix::print().
printClean()
void Isis::SparseBlockColumnMatrix::printClean (std::ostream & outstream)
Prints matrix blocks to std output stream out for debugging.
Explicitly prints the matrix elements for more control over the format as opposed to the print method above.
Parameters
outstream output stream
Referenced by Isis::SparseBlockMatrix::printClean().
setStartColumn()
void Isis::SparseBlockColumnMatrix::setStartColumn (int nStartColumn)
Sets starting column for block in full matrix.
Parameters
nStartColumn value for starting column in full matrix for this block columns
startColumn()
int Isis::SparseBlockColumnMatrix::startColumn () const
Sets starting column for block in full matrix.
Returns
int returns the starting column in the full matrix
Referenced by copy().
wipe()
void Isis::SparseBlockColumnMatrix::wipe ()
Deletes all pointer elements and removes them from the map.
Effectively, a destructor, and in fact, called by the ~SparseBlockColumnMatrix above.
zeroBlocks()
void Isis::SparseBlockColumnMatrix::zeroBlocks ()
Sets all elements of all matrix blocks to zero.
Member Data Documentation
m_startColumn
int Isis::SparseBlockColumnMatrix::m_startColumn protected
starting column for this Block Column in full matrix e.g.
for Block Column 4, if the preceding Block Columns each have 6 columns, then the starting column for Block Column 4 is 24
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/SparseBlockMatrix/SparseBlockMatrix.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/SparseBlockMatrix/SparseBlockMatrix.cpp