Isis Developer Reference: Isis::ViewportBufferTransform Class Reference
Isis::ViewportBufferTransform Class Reference
#include <ViewportBufferTransform.h>
Public Types
enum ActionType { none , transform , fill , stretch }
This uniquely identifies which child is instantiated.
Public Member Functions
ViewportBufferTransform ()
Constructor.
virtual ActionType getActionType ()
Returns the instance type.
void setTranslation (int x, int y)
Sets the translation amount in x and y.
int getXTranslation ()
Gets the amount the buffer should be translated in X.
int getYTranslation ()
Gets the amount the buffer should be translated in Y.
void setResize (int width, int height)
Sets the size the buffer should be resized to.
const int & getBufferWidth ()
Returns the new buffer width.
const int & getBufferHeight ()
Returns the new buffer height.
bool resizeFirst ()
Returns true if the resize should happen before the translation.
void resizeFirst (bool resizeFirst)
Sets whether the resize should happen before the translation.
bool started ()
Returns true if this is an action that takes time and has begun.
void started (bool started)
Sets started.
virtual void stop ()
Cancels the process, used if reinitialize requested for example.
Detailed Description
Author
????-??-?? Unknown
Member Enumeration Documentation
ActionType
enum Isis::ViewportBufferAction::ActionType inherited
This uniquely identifies which child is instantiated.
Enumerator
none
Parent was instantiated.
transform
ViewportBufferTransform.
fill
ViewportBufferFill.
stretch
ViewportBufferStretch.
Constructor & Destructor Documentation
ViewportBufferTransform()
Isis::ViewportBufferTransform::ViewportBufferTransform ()
Constructor.
Member Function Documentation
getActionType()
virtual ActionType Isis::ViewportBufferTransform::getActionType () inline virtual
Returns the instance type.
Reimplemented from Isis::ViewportBufferAction.
References Isis::ViewportBufferAction::transform.
getBufferHeight()
const int& Isis::ViewportBufferTransform::getBufferHeight () inline
Returns the new buffer height.
Returns
const int&
getBufferWidth()
const int& Isis::ViewportBufferTransform::getBufferWidth () inline
Returns the new buffer width.
Returns
const int&
getXTranslation()
int Isis::ViewportBufferTransform::getXTranslation () inline
Gets the amount the buffer should be translated in X.
Returns
int
getYTranslation()
int Isis::ViewportBufferTransform::getYTranslation () inline
Gets the amount the buffer should be translated in Y.
Returns
int
resizeFirst() [1/2]
bool Isis::ViewportBufferTransform::resizeFirst () inline
Returns true if the resize should happen before the translation.
Returns
bool
Referenced by Isis::ViewportBuffer::pan(), Isis::ViewportBuffer::resizedViewport(), and resizeFirst().
resizeFirst() [2/2]
void Isis::ViewportBufferTransform::resizeFirst (bool resizeFirst) inline
Sets whether the resize should happen before the translation.
Parameters
resizeFirst
References resizeFirst().
setResize()
void Isis::ViewportBufferTransform::setResize (int width, int height)
Sets the size the buffer should be resized to.
Parameters
width
height
Referenced by Isis::ViewportBuffer::pan(), and Isis::ViewportBuffer::resizedViewport().
setTranslation()
void Isis::ViewportBufferTransform::setTranslation (int x, int y)
Sets the translation amount in x and y.
Parameters
x
y
Referenced by Isis::ViewportBuffer::pan(), and Isis::ViewportBuffer::resizedViewport().
started() [1/2]
bool Isis::ViewportBufferAction::started () inline inherited
Returns true if this is an action that takes time and has begun.
Referenced by Isis::ViewportBuffer::DataReady(), and Isis::ViewportBufferAction::started().
started() [2/2]
void Isis::ViewportBufferAction::started (bool started) inline inherited
Sets started.
Parameters
started True if starting
References Isis::ViewportBufferAction::started().
stop()
virtual void Isis::ViewportBufferAction::stop () inline virtual inherited
Cancels the process, used if reinitialize requested for example.
Reimplemented in Isis::ViewportBufferFill.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CubeViewport/ViewportBufferTransform.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CubeViewport/ViewportBufferTransform.cpp