Isis Developer Reference: Isis::ControlMeasure Class Reference
Isis::ControlMeasure Class Reference
a control measurement
#include <ControlMeasure.h>
Public Types
enum MeasureType { Candidate , Manual , RegisteredPixel , RegisteredSubPixel }
Control network measurement types.
enum Status { Success , MeasureLocked }
enum ModType { IgnoredModified }
Control Measure Modification Types.
enum DataField {
AprioriLine = 1 , AprioriSample = 2 , ChooserName = 4 , CubeSerialNumber = 8 ,
Coordinate = 16 , DateTime = 32 , Diameter = 64 , EditLock = 128 ,
Rejected = 256 , FocalPlaneMeasured = 512 , FocalPlaneComputed = 1024 , Ignore = 2048 ,
SampleResidual = 4096 , LineResidual = 8192 , SampleSigma = 16384 , LineSigma = 32768 ,
Type = 65536
}
Public Member Functions
ControlMeasure ()
Create a new control measure and initialize it to nulls and zeros.
ControlMeasure (const ControlMeasure &other)
Copy the other control measure exactly.
~ControlMeasure ()
Free the memory allocated by a control.
ControlPoint * Parent ()
Status SetAprioriLine (double aprioriLine)
Status SetAprioriSample (double aprioriSample)
Status SetCamera (Isis::Camera *camera)
Set pointer to camera associated with a measure.
Status SetChooserName ()
Set chooser name to a user who last changed the coordinate.
Status SetChooserName (QString name)
Set the chooser name to an application that last changed the coordinate.
Status SetCoordinate (double sample, double line)
Set the coordinate of the measurement.
Status SetCoordinate (double sample, double line, MeasureType type)
Set the coordinate of the measurement.
Status SetCubeSerialNumber (QString newSerialNumber)
Set cube serial number.
Status SetDateTime ()
Date Time - Creation Time.
Status SetDateTime (QString datetime)
Set date/time the coordinate was last changed to specified date/time.
Status SetDiameter (double diameter)
Set the crater diameter at the coordinate.
Status SetEditLock (bool editLock)
Status SetFocalPlaneMeasured (double x, double y)
Set the focal plane x/y for the measured line/sample.
Status SetFocalPlaneComputed (double x, double y)
Set the computed focal plane x/y for the apriori lat/lon.
Status SetIgnored (bool newIgnoredStatus)
Status SetLineSigma (double lineSigma)
Status SetRejected (bool rejected)
Set "jigsaw" rejected flag for a measure.
Status SetResidual (double sampResidual, double lineResidual)
Set the BundleAdjust Residual of the coordinate.
Status SetSampleSigma (double sampleSigma)
Status SetType (MeasureType type)
Set how the coordinate was obtained.
void DeleteLogData (long dataType)
This deletes log data of the specified type.
QVariant GetLogValue (long dataType) const
Get the value of the log data with the specified type as a variant.
bool HasLogData (long dataType) const
Test if we have a valid log data value of the specified type.
void SetLogData (ControlMeasureLogData)
This adds or updates the log data information associated with data's type.
void UpdateLogData (ControlMeasureLogData)
This updates existing log data information associated with data's type.
double GetAprioriLine () const
double GetAprioriSample () const
Isis::Camera * Camera () const
QString GetChooserName () const
Return the chooser name.
bool HasChooserName () const
Returns true if the choosername is not empty.
QString GetCubeSerialNumber () const
Return the serial number of the cube containing the coordinate.
QString GetDateTime () const
Return the date/time the coordinate was last changed.
bool HasDateTime () const
Returns true if the datetime is not empty.
double GetDiameter () const
Return the diameter of the crater in pixels (0 implies no crater)
ControlMeasureLogData GetLogData (long dataType) const
bool IsEditLocked () const
Return value for p_editLock or implicit lock on reference measure.
bool IsRejected () const
double GetFocalPlaneComputedX () const
double GetFocalPlaneComputedY () const
double GetFocalPlaneMeasuredX () const
double GetFocalPlaneMeasuredY () const
double GetMeasureData (QString) const
One Getter to rule them all.
bool IsIgnored () const
bool IsMeasured () const
bool IsRegistered () const
bool IsStatisticallyRelevant (DataField field) const
double GetLine () const
double GetLineResidual () const
double GetLineSigma () const
QVector< ControlMeasureLogData > GetLogDataEntries () const
Return all of the log data for the measure.
QVector< ControlMeasureLogData > GetLastRunLogDataEntries () const
double GetResidualMagnitude () const
Return Residual magnitude.
double GetSample () const
double GetSampleResidual () const
double GetSampleSigma () const
MeasureType GetType () const
QString GetPointId () const
double GetSampleShift () const
double GetLineShift () const
double GetPixelShift () const
QList< QStringList > PrintableClassData () const
Data accessor method, provides access to string representations of all variable values and names.
QString GetMeasureTypeString () const
Obtain a string representation of the MeasureType.
const ControlMeasure & operator= (const ControlMeasure &other)
Assignment operator.
bool operator!= (const Isis::ControlMeasure &pMeasure) const
Compare 2 Control Measures for inequality.
bool operator== (const Isis::ControlMeasure &pMeasure) const
Check for Control Measures equality.
Static Public Member Functions
static QVector< QString > GetMeasureDataNames ()
Returns a list of all valid options to pass to GetMeasureData.
static QString MeasureTypeToString (MeasureType type)
Return the String Control Measure type.
static MeasureType StringToMeasureType (QString str)
Friends
class ControlPoint
Detailed Description
a control measurement
This class is used to record a coordinate (measurement) on a cube for a control point.
Author
2005-07-29 Jeff Anderson
See also
ControlPoint ControlNet
Member Enumeration Documentation
DataField
enum Isis::ControlMeasure::DataField
Enumerator
AprioriLine
AprioriSample
ChooserName
CubeSerialNumber
Coordinate
DateTime
Diameter
EditLock
Rejected
FocalPlaneMeasured
FocalPlaneComputed
Ignore
SampleResidual
LineResidual
SampleSigma
LineSigma
Type
MeasureType
enum Isis::ControlMeasure::MeasureType
Control network measurement types.
OLD VERSION: Manual implies the coordinate was selected by a human but still may be in error. It is subject to refinement by other computer programs.
Estimated implies the coordinate was selected by a computer program but has not been sub-pixel registered and is more than likely in error. It is subject to refinement by other computer programs
AutomaticPixel implies the coordinate was selected by a computer program and met registration criteria (but still may be in error). It is subject to refinement by other computer programs.
ValidatedManual implies the coordinate was manually selected by a human, was validated by a human, and should not be changed by any automated means.
ValidatedAutomatic implies the coordinate was automatically selected by a computer program, was validated by a human, and should not be changed by any automated means.
Enumerator
Candidate
(e.g., autoseed, interest) AKA predicted, unmeasured, unverified
Manual
Hand Measured (e.g., qnet)
RegisteredPixel
Registered to whole pixel (e.g.,pointreg)
RegisteredSubPixel
Registered to sub-pixel (e.g., pointreg)
ModType
enum Isis::ControlMeasure::ModType
Control Measure Modification Types.
This enum is designed to represent the different types of modifications that can be made to a ControlMeasure.
IgnoredModified means that the Control Measure had it's IGNORED flag changed.
Enumerator
IgnoredModified
Status
enum Isis::ControlMeasure::Status
Enumerator
Success
MeasureLocked
Constructor & Destructor Documentation
ControlMeasure() [1/2]
Isis::ControlMeasure::ControlMeasure ()
Create a new control measure and initialize it to nulls and zeros.
ControlMeasure() [2/2]
Isis::ControlMeasure::ControlMeasure (const ControlMeasure & other)
Copy the other control measure exactly.
Parameters
other The control measure to copy all of the values from
~ControlMeasure()
Isis::ControlMeasure::~ControlMeasure ()
Free the memory allocated by a control.
Member Function Documentation
Camera()
Isis::Camera * Isis::ControlMeasure::Camera () const
Referenced by Isis::BundleMeasure::camera(), Isis::ControlPoint::ComputeApriori(), Isis::ControlPoint::ComputeResiduals(), Isis::LidarControlPoint::ComputeResiduals(), Isis::ControlPoint::ComputeResiduals_Millimeters(), Isis::BundleMeasure::setImage(), and Isis::BundleMeasure::setSigma().
DeleteLogData()
void Isis::ControlMeasure::DeleteLogData (long dataType)
This deletes log data of the specified type.
If none exist, this does nothing.
Parameters
dataType A ControlMeasureLogData::NumericLogDataType
References Isis::ControlMeasureLogData::GetDataType().
GetAprioriLine()
double Isis::ControlMeasure::GetAprioriLine () const
Referenced by Isis::AbstractMeasureItem::getData(), and Isis::ControlNetVersioner::toPvl().
GetAprioriSample()
double Isis::ControlMeasure::GetAprioriSample () const
Referenced by Isis::AbstractMeasureItem::getData(), and Isis::ControlNetVersioner::toPvl().
GetChooserName()
QString Isis::ControlMeasure::GetChooserName () const
Return the chooser name.
References Isis::FileName::name().
Referenced by Isis::ControlNetVersioner::toPvl().
GetCubeSerialNumber()
QString Isis::ControlMeasure::GetCubeSerialNumber () const
Return the serial number of the cube containing the coordinate.
Referenced by Isis::ControlNetVitals::addMeasure(), Isis::ControlPoint::ComputeApriori(), Isis::ControlPoint::ComputeResiduals(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::BundleMeasure::cubeSerialNumber(), Isis::ControlPoint::Delete(), Isis::ControlNetVitals::deleteMeasure(), Isis::ControlPointEditWidget::deletePoint(), Isis::MatchTool::deletePoint(), Isis::QnetTool::deletePoint(), Isis::ImageIdFilter::evaluate(), Isis::QnetPointDistanceFilter::filter(), Isis::CnetEditorWidget::filteredNetwork(), Isis::InterestOperator::FindCnetRef(), Isis::InterestOperator::FindOverlap(), Isis::AbstractMeasureItem::getData(), Isis::AbstractPointItem::getData(), Isis::ControlPoint::GetReferenceSN(), Isis::ControlPoint::IndexOf(), Isis::ControlPoint::IndexOfRefMeasure(), Isis::InterestOperator::InterestByMeasure(), Isis::InterestOperator::InterestByPoint(), Isis::ControlNetVitals::measureModified(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::ControlNetFilter::PointMeasurePropertiesFilter(), Isis::ControlNetFilter::PrintCubeFileSerialNum(), Isis::InterestOperator::ProcessLocked_Point_Reference(), Isis::PointTableDelegate::readData(), Isis::LidarData::SetImages(), Isis::ControlNet::SetImages(), Isis::ChipViewportsWidget::setPoint(), Isis::ControlNetVersioner::toPvl(), and Isis::LidarData::write().
GetDateTime()
QString Isis::ControlMeasure::GetDateTime () const
Return the date/time the coordinate was last changed.
Referenced by Isis::ControlNetVersioner::toPvl().
GetDiameter()
double Isis::ControlMeasure::GetDiameter () const
Return the diameter of the crater in pixels (0 implies no crater)
Referenced by Isis::AbstractMeasureItem::getData(), and Isis::ControlNetVersioner::toPvl().
GetFocalPlaneComputedX()
double Isis::ControlMeasure::GetFocalPlaneComputedX () const
Referenced by Isis::ControlPoint::ComputeResiduals(), Isis::BundleMeasure::focalPlaneComputedX(), and Isis::BundleMeasure::setFocalPlaneResidualsMillimeters().
GetFocalPlaneComputedY()
double Isis::ControlMeasure::GetFocalPlaneComputedY () const
Referenced by Isis::ControlPoint::ComputeResiduals(), Isis::BundleMeasure::focalPlaneComputedY(), and Isis::BundleMeasure::setFocalPlaneResidualsMillimeters().
GetFocalPlaneMeasuredX()
double Isis::ControlMeasure::GetFocalPlaneMeasuredX () const
Referenced by Isis::ControlPoint::ComputeResiduals(), Isis::BundleMeasure::focalPlaneMeasuredX(), and Isis::BundleMeasure::setFocalPlaneResidualsMillimeters().
GetFocalPlaneMeasuredY()
double Isis::ControlMeasure::GetFocalPlaneMeasuredY () const
Referenced by Isis::ControlPoint::ComputeResiduals(), Isis::BundleMeasure::focalPlaneMeasuredY(), and Isis::BundleMeasure::setFocalPlaneResidualsMillimeters().
GetLastRunLogDataEntries()
QVector<ControlMeasureLogData> Isis::ControlMeasure::GetLastRunLogDataEntries () const
GetLine()
double Isis::ControlMeasure::GetLine () const
Referenced by Isis::ControlPoint::ComputeApriori(), Isis::ControlPoint::ComputeResiduals(), Isis::ControlPoint::ComputeResiduals_Millimeters(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::LineFilter::evaluate(), Isis::QnetCubeDistanceFilter::filter(), Isis::QnetPointDistanceFilter::filter(), Isis::ControlNet::FindClosest(), Isis::InterestOperator::FindCnetRef(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::AbstractMeasureItem::getData(), Isis::InterestOperator::InterestByMeasure(), Isis::BundleMeasure::line(), Isis::ChipViewport::paintEvent(), Isis::StereoTool::paintViewport(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::InterestOperator::ProcessLocked_Point_Reference(), Isis::ControlMeasureEditWidget::saveChips(), Isis::ControlPointEdit::saveChips(), Isis::AbstractMeasureItem::setData(), Isis::BundleMeasure::setImage(), Isis::ControlMeasureEditWidget::setLeftMeasure(), Isis::ControlPointEdit::setLeftMeasure(), Isis::ChipViewportsWidget::setPoint(), Isis::ControlMeasureEditWidget::setRightMeasure(), Isis::ControlPointEdit::setRightMeasure(), Isis::ControlNetVersioner::toPvl(), Isis::ControlNetValidMeasure::ValidStandardOptions(), and Isis::LidarData::write().
GetLineResidual()
double Isis::ControlMeasure::GetLineResidual () const
Referenced by Isis::LineResidualFilter::evaluate(), Isis::AbstractMeasureItem::getData(), Isis::ControlPoint::GetLineResidualRms(), Isis::ControlPoint::GetResidualRms(), Isis::BundleMeasure::lineResidual(), Isis::AbstractMeasureItem::setData(), Isis::ControlNetVersioner::toPvl(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
GetLineShift()
double Isis::ControlMeasure::GetLineShift () const
References Isis::Null.
Referenced by Isis::LineShiftFilter::evaluate(), Isis::AbstractMeasureItem::getData(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
GetLineSigma()
double Isis::ControlMeasure::GetLineSigma () const
Referenced by Isis::AbstractMeasureItem::getData(), and Isis::ControlNetVersioner::toPvl().
GetLogData()
ControlMeasureLogData Isis::ControlMeasure::GetLogData (long dataType) const
References Isis::ControlMeasureLogData::GetDataType().
Referenced by Isis::GoodnessOfFitFilter::evaluate(), Isis::AbstractMeasureItem::getData(), Isis::ControlPoint::GetStatistic(), and Isis::ControlNetFilter::PointGoodnessOfFitFilter().
GetLogDataEntries()
QVector< ControlMeasureLogData > Isis::ControlMeasure::GetLogDataEntries () const
Return all of the log data for the measure.
Returns
QVector<ControlMeasureLogData> All of the log data for the measure.
Referenced by Isis::ControlNetVersioner::toPvl().
GetLogValue()
QVariant Isis::ControlMeasure::GetLogValue (long dataType) const
Get the value of the log data with the specified type as a variant.
This should work for all types of log data.
References Isis::ControlMeasureLogData::GetDataType(), and Isis::ControlMeasureLogData::GetValue().
GetMeasureData()
double Isis::ControlMeasure::GetMeasureData (QString data) const
One Getter to rule them all.
References _FILEINFO_.
GetMeasureDataNames()
QVector< QString > Isis::ControlMeasure::GetMeasureDataNames () static
Returns a list of all valid options to pass to GetMeasureData.
GetMeasureTypeString()
QString Isis::ControlMeasure::GetMeasureTypeString () const
Obtain a string representation of the MeasureType.
Returns
A string representation of the MeasureType
Referenced by Isis::MeasureTypeFilter::evaluate(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointMeasurePropertiesFilter(), Isis::ControlNetFilter::PointMeasuresFilter(), Isis::ControlNetFilter::PointNumMeasuresEditLockFilter(), Isis::ControlNetFilter::PointPixelShiftFilter(), and Isis::ControlNetFilter::PointResMagnitudeFilter().
GetPixelShift()
double Isis::ControlMeasure::GetPixelShift () const
References Isis::Null.
Referenced by Isis::QnetPointRegistrationErrorFilter::filter(), Isis::ControlNetFilter::PointPixelShiftFilter(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
GetPointId()
QString Isis::ControlMeasure::GetPointId () const
References _FILEINFO_.
GetResidualMagnitude()
double Isis::ControlMeasure::GetResidualMagnitude () const
Return Residual magnitude.
Returns Isis:Null when p_lineResidual or p_sampleResidual not specifically set after call to constructor. (This calculation is normally done within the jigsaw app)
Returns
(double) The residual magnitude
References Isis::IsSpecial(), and Isis::Null.
Referenced by Isis::ResidualMagnitudeFilter::evaluate(), Isis::QnetPointJigsawErrorFilter::filter(), Isis::AbstractMeasureItem::getData(), Isis::ControlPointGraphicsItem::paint(), Isis::ControlNetFilter::PointResMagnitudeFilter(), Isis::BundleMeasure::residualMagnitude(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
GetSample()
double Isis::ControlMeasure::GetSample () const
Referenced by Isis::ControlPoint::ComputeApriori(), Isis::ControlPoint::ComputeResiduals(), Isis::ControlPoint::ComputeResiduals_Millimeters(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::SampleFilter::evaluate(), Isis::QnetCubeDistanceFilter::filter(), Isis::QnetPointDistanceFilter::filter(), Isis::ControlNet::FindClosest(), Isis::InterestOperator::FindCnetRef(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::AbstractMeasureItem::getData(), Isis::InterestOperator::InterestByMeasure(), Isis::ChipViewport::paintEvent(), Isis::StereoTool::paintViewport(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::InterestOperator::ProcessLocked_Point_Reference(), Isis::BundleMeasure::sample(), Isis::ControlMeasureEditWidget::saveChips(), Isis::ControlPointEdit::saveChips(), Isis::AbstractMeasureItem::setData(), Isis::BundleMeasure::setImage(), Isis::ControlMeasureEditWidget::setLeftMeasure(), Isis::ControlPointEdit::setLeftMeasure(), Isis::ChipViewportsWidget::setPoint(), Isis::ControlMeasureEditWidget::setRightMeasure(), Isis::ControlPointEdit::setRightMeasure(), Isis::ControlNetVersioner::toPvl(), Isis::ControlNetValidMeasure::ValidStandardOptions(), and Isis::LidarData::write().
GetSampleResidual()
double Isis::ControlMeasure::GetSampleResidual () const
Referenced by Isis::SampleResidualFilter::evaluate(), Isis::AbstractMeasureItem::getData(), Isis::ControlPoint::GetResidualRms(), Isis::ControlPoint::GetSampleResidualRms(), Isis::BundleMeasure::sampleResidual(), Isis::AbstractMeasureItem::setData(), Isis::ControlNetVersioner::toPvl(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
GetSampleShift()
double Isis::ControlMeasure::GetSampleShift () const
References Isis::Null.
Referenced by Isis::SampleShiftFilter::evaluate(), Isis::AbstractMeasureItem::getData(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
GetSampleSigma()
double Isis::ControlMeasure::GetSampleSigma () const
Referenced by Isis::AbstractMeasureItem::getData(), and Isis::ControlNetVersioner::toPvl().
GetType()
ControlMeasure::MeasureType Isis::ControlMeasure::GetType () const
Referenced by Isis::AbstractMeasureItem::getData(), Isis::ControlNetFilter::PointMeasurePropertiesFilter(), and Isis::ControlNetVersioner::toPvl().
HasChooserName()
bool Isis::ControlMeasure::HasChooserName () const
Returns true if the choosername is not empty.
HasDateTime()
bool Isis::ControlMeasure::HasDateTime () const
Returns true if the datetime is not empty.
HasLogData()
bool Isis::ControlMeasure::HasLogData (long dataType) const
Test if we have a valid log data value of the specified type.
Parameters
dataType A ControlMeasureLogData::NumericLogDataType
References Isis::ControlMeasureLogData::GetDataType().
Referenced by Isis::GoodnessOfFitFilter::evaluate().
IsEditLocked()
bool Isis::ControlMeasure::IsEditLocked () const
Return value for p_editLock or implicit lock on reference measure.
This method returns p_editLock unless the measure is a reference measure. In the case of a reference measure the value of the parent point's editLock is returned. An editLock on a control point implicitly locks the points reference measure as well.
Returns
value of p_editLock
Referenced by Isis::ControlPoint::Delete(), Isis::AbstractMeasureItem::deleteSource(), Isis::InterestOperator::FindCnetRef(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::AbstractMeasureItem::getData(), Isis::AbstractMeasureItem::isDataEditable(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointMeasurePropertiesFilter(), Isis::ControlNetFilter::PointMeasuresFilter(), Isis::ControlNetFilter::PointNumMeasuresEditLockFilter(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::ControlNetFilter::PointResMagnitudeFilter(), Isis::InterestOperator::ProcessLocked_Point_Reference(), Isis::MeasureTableDelegate::readData(), and Isis::ControlNetVersioner::toPvl().
IsIgnored()
bool Isis::ControlMeasure::IsIgnored () const
Referenced by Isis::BundleControlPoint::BundleControlPoint(), Isis::ControlPoint::ComputeApriori(), Isis::ControlPoint::ComputeResiduals(), Isis::LidarControlPoint::ComputeResiduals(), Isis::ControlPoint::ComputeResiduals_Millimeters(), Isis::ControlPoint::Delete(), Isis::MeasureIgnoredFilter::evaluate(), Isis::InterestOperator::FindCnetRef(), Isis::AbstractMeasureItem::getData(), Isis::ControlPoint::GetLineResidualRms(), Isis::ControlPoint::getMeasures(), Isis::ControlPoint::GetResidualRms(), Isis::ControlPoint::GetSampleResidualRms(), Isis::ControlPoint::GetStatistic(), Isis::LidarData::GetValidMeasuresInCube(), Isis::ControlNet::GetValidMeasuresInCube(), Isis::InterestOperator::InterestByPoint(), Isis::ChipViewport::paintEvent(), Isis::StereoTool::paintViewport(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointMeasurePropertiesFilter(), Isis::ControlNetFilter::PointMeasuresFilter(), Isis::ControlNetFilter::PointNumMeasuresEditLockFilter(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::ControlNetFilter::PointResMagnitudeFilter(), Isis::InterestOperator::ProcessLocked_Point_Reference(), Isis::MeasureTableDelegate::readData(), Isis::LidarData::SetImages(), Isis::ControlNet::SetImages(), Isis::ControlNet::sortedMeasureList(), and Isis::ControlNetVersioner::toPvl().
IsMeasured()
bool Isis::ControlMeasure::IsMeasured () const
IsRegistered()
bool Isis::ControlMeasure::IsRegistered () const
IsRejected()
bool Isis::ControlMeasure::IsRejected () const
Referenced by Isis::MeasureJigsawRejectedFilter::evaluate(), Isis::AbstractMeasureItem::getData(), Isis::ControlPoint::GetLineResidualRms(), Isis::ControlPoint::GetResidualRms(), Isis::ControlPoint::GetSampleResidualRms(), Isis::BundleMeasure::isRejected(), and Isis::ControlNetVersioner::toPvl().
IsStatisticallyRelevant()
bool Isis::ControlMeasure::IsStatisticallyRelevant (DataField field) const
References _FILEINFO_.
MeasureTypeToString()
QString Isis::ControlMeasure::MeasureTypeToString (MeasureType type) static
Return the String Control Measure type.
Returns
string - Measure Type
Author
Sharmila Prasad (10/1/2010)
References _FILEINFO_, and Isis::toString().
Referenced by Isis::AbstractMeasureItem::getData().
operator!=()
bool Isis::ControlMeasure::operator!= (const Isis::ControlMeasure & pMeasure) const
Compare 2 Control Measures for inequality.
Author
sprasad (4/20/2010)
Parameters
pMeasure
Returns
bool
operator=()
const ControlMeasure & Isis::ControlMeasure::operator= (const ControlMeasure & other)
Assignment operator.
operator==()
bool Isis::ControlMeasure::operator== (const Isis::ControlMeasure & pMeasure) const
Check for Control Measures equality.
Author
sprasad (4/20/2010)
Parent()
ControlPoint* Isis::ControlMeasure::Parent () inline
Referenced by Isis::AbstractMeasureItem::deleteSource(), Isis::CnetEditorWidget::filteredNetwork(), Isis::ControlNet::FindClosest(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::AbstractMeasureItem::getData(), Isis::AbstractMeasureItem::isDataEditable(), Isis::ChipViewport::paintEvent(), and Isis::StereoTool::paintViewport().
PrintableClassData()
QList< QStringList > Isis::ControlMeasure::PrintableClassData () const
Data accessor method, provides access to string representations of all variable values and names.
Returns
A QList containing QStringLists, the QStringLists contain name value pairs such that element 0 is the name and element 1 is the value of the variable.
SetAprioriLine()
ControlMeasure::Status Isis::ControlMeasure::SetAprioriLine (double aprioriLine)
Referenced by Isis::ControlPointEditWidget::createControlPoint(), Isis::QnetTool::createPoint(), and Isis::AbstractMeasureItem::setData().
SetAprioriSample()
ControlMeasure::Status Isis::ControlMeasure::SetAprioriSample (double aprioriSample)
Referenced by Isis::ControlPointEditWidget::createControlPoint(), Isis::QnetTool::createPoint(), and Isis::AbstractMeasureItem::setData().
SetCamera()
ControlMeasure::Status Isis::ControlMeasure::SetCamera (Isis::Camera * camera)
Set pointer to camera associated with a measure.
This method is used to set a pointer to the camera associated with a ControlMeasure.
Parameters
*camera Pointer to camera
Returns
Status Success
Referenced by Isis::ControlPointEditWidget::createControlPoint(), Isis::QnetTool::createFixedPoint(), Isis::QnetTool::createPoint(), Isis::LidarData::SetImages(), and Isis::ControlNet::SetImages().
SetChooserName() [1/2]
ControlMeasure::Status Isis::ControlMeasure::SetChooserName ()
Set chooser name to a user who last changed the coordinate.
Referenced by Isis::ControlPointEditWidget::createControlPoint(), Isis::QnetTool::createFixedPoint(), Isis::QnetTool::createPoint(), Isis::StereoTool::createPoint(), Isis::MatchTool::createPoint(), Isis::InterestOperator::FindCnetRef(), and Isis::InterestOperator::ProcessLocked_Point_Reference().
SetChooserName() [2/2]
ControlMeasure::Status Isis::ControlMeasure::SetChooserName (QString name)
Set the chooser name to an application that last changed the coordinate.
SetCoordinate() [1/2]
ControlMeasure::Status Isis::ControlMeasure::SetCoordinate (double sample, double line)
Set the coordinate of the measurement.
Parameters
sample Sample coordinate of the measurement
line Line coordinate of the measurement,
Referenced by Isis::LidarControlPoint::ComputeResiduals(), Isis::ControlPointEditWidget::createControlPoint(), Isis::QnetTool::createFixedPoint(), Isis::QnetTool::createPoint(), Isis::StereoTool::createPoint(), Isis::MatchTool::createPoint(), Isis::InterestOperator::FindCnetRef(), Isis::LidarData::read(), and Isis::AbstractMeasureItem::setData().
SetCoordinate() [2/2]
ControlMeasure::Status Isis::ControlMeasure::SetCoordinate (double sample, double line, MeasureType type)
Set the coordinate of the measurement.
Parameters
sample Sample coordinate of the measurement
line Line coordinate of the measurement
type The type of the coordinate
SetCubeSerialNumber()
ControlMeasure::Status Isis::ControlMeasure::SetCubeSerialNumber (QString newSerialNumber)
Set cube serial number.
This method is used to set the serial number of the cube. That is, the coordinate was selected from a cube with this unique serial number
Parameters
sn Serial number of the cube where the coordinate was selected
Returns
Status Success or MeasureLocked
Referenced by Isis::ControlPointEditWidget::createControlPoint(), Isis::QnetTool::createFixedPoint(), Isis::QnetTool::createPoint(), Isis::StereoTool::createPoint(), Isis::MatchTool::createPoint(), Isis::LidarData::read(), and Isis::AbstractMeasureItem::setData().
SetDateTime() [1/2]
ControlMeasure::Status Isis::ControlMeasure::SetDateTime ()
Date Time - Creation Time.
Referenced by Isis::StereoTool::createPoint(), Isis::MatchTool::createPoint(), Isis::InterestOperator::FindCnetRef(), and Isis::InterestOperator::ProcessLocked_Point_Reference().
SetDateTime() [2/2]
ControlMeasure::Status Isis::ControlMeasure::SetDateTime (QString datetime)
Set date/time the coordinate was last changed to specified date/time.
SetDiameter()
ControlMeasure::Status Isis::ControlMeasure::SetDiameter (double diameter)
Set the crater diameter at the coordinate.
This method sets the crater diameter at the coordinate. If left unset a diameter of 0 is assumed which implies no crater
Parameters
diameter The diameter of the crater in pixels
Referenced by Isis::AbstractMeasureItem::setData().
SetEditLock()
ControlMeasure::Status Isis::ControlMeasure::SetEditLock (bool editLock)
Referenced by Isis::CnetEditorWidget::filteredNetwork(), and Isis::AbstractMeasureItem::setData().
SetFocalPlaneComputed()
ControlMeasure::Status Isis::ControlMeasure::SetFocalPlaneComputed (double x, double y)
Set the computed focal plane x/y for the apriori lat/lon.
This is a convenience method for the BundleAdjustment class to avoid having to go redo the calculation.
Parameters
*camera Pointer to camera
Returns
Status Success
Referenced by Isis::LidarControlPoint::ComputeResiduals(), and Isis::ControlPoint::ComputeResiduals_Millimeters().
SetFocalPlaneMeasured()
ControlMeasure::Status Isis::ControlMeasure::SetFocalPlaneMeasured (double x, double y)
Set the focal plane x/y for the measured line/sample.
This is a convenience method for the BundleAdjustment class to avoid having to go redo the calculation.
Parameters
*camera Pointer to camera
Returns
Status Success
Referenced by Isis::ControlPoint::ComputeApriori(), and Isis::LidarControlPoint::ComputeResiduals().
SetIgnored()
ControlMeasure::Status Isis::ControlMeasure::SetIgnored (bool newIgnoredStatus)
Referenced by Isis::InterestOperator::FindCnetRef(), Isis::InterestOperator::ProcessLocked_Point_Reference(), and Isis::AbstractMeasureItem::setData().
SetLineSigma()
ControlMeasure::Status Isis::ControlMeasure::SetLineSigma (double lineSigma)
Referenced by Isis::AbstractMeasureItem::setData().
SetLogData()
void Isis::ControlMeasure::SetLogData (ControlMeasureLogData data)
This adds or updates the log data information associated with data's type.
In most cases, this is what you want to use to assign log data.
References _FILEINFO_, Isis::ControlMeasureLogData::GetDataType(), and Isis::ControlMeasureLogData::IsValid().
SetRejected()
ControlMeasure::Status Isis::ControlMeasure::SetRejected (bool reject)
Set "jigsaw" rejected flag for a measure.
This method is used to set the "jigsaw"-rejected flag for the current measure. It should only be used by jigsaw.
Parameters
*reject rejected flag
Returns
Status Success
Referenced by Isis::ControlPoint::ClearJigsawRejected(), Isis::LidarControlPoint::ComputeResiduals(), and Isis::BundleMeasure::setRejected().
SetResidual()
ControlMeasure::Status Isis::ControlMeasure::SetResidual (double sampResidual, double lineResidual)
Set the BundleAdjust Residual of the coordinate.
***Warning: This method should only be used by BundleAdjust and its applications.
Parameters
sampResidual Sample Residual
lineResidual Line Residual
Referenced by Isis::ControlPoint::ComputeResiduals(), Isis::LidarControlPoint::ComputeResiduals(), and Isis::AbstractMeasureItem::setData().
SetSampleSigma()
ControlMeasure::Status Isis::ControlMeasure::SetSampleSigma (double sampleSigma)
Referenced by Isis::AbstractMeasureItem::setData().
SetType()
ControlMeasure::Status Isis::ControlMeasure::SetType (MeasureType type)
Set how the coordinate was obtained.
Referenced by Isis::ControlPointEditWidget::createControlPoint(), Isis::QnetTool::createFixedPoint(), Isis::QnetTool::createPoint(), Isis::StereoTool::createPoint(), Isis::MatchTool::createPoint(), Isis::InterestOperator::FindCnetRef(), and Isis::AbstractMeasureItem::setData().
StringToMeasureType()
ControlMeasure::MeasureType Isis::ControlMeasure::StringToMeasureType (QString str) static
Parameters
str The string to get a MeasureType from
Returns
A Measure Type given a string
References _FILEINFO_.
Referenced by Isis::MeasureTableDelegate::readData(), and Isis::AbstractMeasureItem::setData().
UpdateLogData()
void Isis::ControlMeasure::UpdateLogData (ControlMeasureLogData newLogData)
This updates existing log data information associated with data's type.
If none exist, an error is thrown.
See also
SetLogData
References _FILEINFO_, Isis::ControlMeasureLogData::DataTypeToName(), and Isis::ControlMeasureLogData::GetDataType().
Friends And Related Function Documentation
ControlPoint
friend class ControlPoint friend
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/ControlMeasure/ControlMeasure.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/ControlMeasure/ControlMeasure.cpp