Isis Developer Reference: Isis::ChipViewportsWidget Class Reference
Isis::ChipViewportsWidget Class Reference
Scrolled widget for display ChipViewports.
#include <ChipViewportsWidget.h>
Public Slots
void setSerialNumberList (SerialNumberList *snList)
void setControlNet (ControlNet *cnet, QString cnetFilename)
New control network being edited.
void setPoint (ControlPoint *controlPoint)
Signals
void controlPointChanged (QString pointId)
void netChanged ()
void newControlNetwork (ControlNet *)
void stretchChipViewport (Stretch *, CubeViewport *)
void measureChanged ()
void saveControlNet ()
Public Member Functions
ChipViewportsWidget (QWidget *parent)
Consructs the ChipViewportsWidget widget.
virtual ~ChipViewportsWidget ()
bool eventFilter (QObject *object, QEvent *event)
Detailed Description
Scrolled widget for display ChipViewports.
Author
2016-06-15 Tracie Sucharski
Constructor & Destructor Documentation
ChipViewportsWidget()
Isis::ChipViewportsWidget::ChipViewportsWidget (QWidget * parent)
Consructs the ChipViewportsWidget widget.
Parameters
parent Pointer to the parent widget for the ChipViewportsWidget
~ChipViewportsWidget()
Isis::ChipViewportsWidget::~ChipViewportsWidget () virtual
Member Function Documentation
controlPointChanged
void Isis::ChipViewportsWidget::controlPointChanged (QString pointId) signal
eventFilter()
bool Isis::ChipViewportsWidget::eventFilter (QObject * object, QEvent * event)
measureChanged
void Isis::ChipViewportsWidget::measureChanged () signal
netChanged
void Isis::ChipViewportsWidget::netChanged () signal
newControlNetwork
void Isis::ChipViewportsWidget::newControlNetwork (ControlNet *) signal
Referenced by setControlNet().
saveControlNet
void Isis::ChipViewportsWidget::saveControlNet () signal
setControlNet
void Isis::ChipViewportsWidget::setControlNet (ControlNet * cnet, QString cnetFilename) slot
New control network being edited.
Parameters
cnet ControlNet *
filename Qstring, Need filename to write to widget label. ControlNet doesn't contain a filename.
References newControlNetwork().
setPoint
void Isis::ChipViewportsWidget::setPoint (ControlPoint * controlPoint) slot
References Isis::SerialNumberList::fileName(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::ControlMeasure::GetLine(), Isis::ControlMeasure::GetSample(), Isis::Chip::Load(), Isis::ChipViewport::setChip(), Isis::ChipViewport::setControlNet(), Isis::ChipViewport::setPoints(), Isis::Chip::TackCube(), and Isis::VIEWSIZE.
setSerialNumberList
void Isis::ChipViewportsWidget::setSerialNumberList (SerialNumberList * snList) slot
stretchChipViewport
void Isis::ChipViewportsWidget::stretchChipViewport (Stretch * , CubeViewport *) signal
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ChipViewportsWidget/ChipViewportsWidget.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ChipViewportsWidget/ChipViewportsWidget.cpp