Isis Developer Reference: Isis::ExportControlNetWorkOrder Class Reference
Isis::ExportControlNetWorkOrder Class Reference
Write a project control network to a user-specified location.
#include <ExportControlNetWorkOrder.h>
Public Types
enum WorkOrderStatus {
WorkOrderUnknownStatus = 0 , WorkOrderNotStarted , WorkOrderRedoing , WorkOrderRedone ,
WorkOrderUndoing , WorkOrderUndone , WorkOrderFinished , WorkOrderLastStatus = WorkOrderFinished
}
This enumeration is used by other functions to set and retrieve the current state of the WorkOrder.
enum Context { NoContext , ProjectContext }
This enumeration is for recording the context of the current Workorder (whether it is part of a project or not).
Public Slots
void enableWorkOrder ()
Enables the work order.
void disableWorkOrder ()
Disables the work order.
virtual void redo ()
Starts (or enqueues) a redo.
virtual void undo ()
Starts (or enqueues) an undo.
Signals
void creatingProgress (WorkOrder *)
void deletingProgress (WorkOrder *)
void finished (WorkOrder *)
void statusChanged (WorkOrder *)
Public Member Functions
ExportControlNetWorkOrder (Project *project)
Creates a work order for exporting a control network from the project.
ExportControlNetWorkOrder (const ExportControlNetWorkOrder &other)
Copy constructor.
~ExportControlNetWorkOrder ()
Destructor.
virtual ExportControlNetWorkOrder * clone () const
Clones this work order.
bool isExecutable (ControlList *controls)
Determines if we can export a control net.
virtual bool setupExecution ()
Prepares for exporting a control net by soliciting information from the user.
virtual void execute ()
Executes the work order.
virtual bool isExecutable (Context)
Re-implement this method if your work order utilizes controls for data in order to operate.
virtual bool isExecutable (ImageList *images)
Re-implement this method if your work order utilizes images for data in order to operate.
virtual bool isExecutable (ShapeList *shapes)
Re-implement this method if your work order utilizes shapes for data in order to operate.
virtual bool isExecutable (CorrelationMatrix)
virtual bool isExecutable (TargetBodyQsp targetBody)
Re-implement this method if your work order utilizes a control list (a list of control networks) for data in order to operate.
virtual bool isExecutable (Template *currentTemplate)
Re-implement this method if your work order utilizes a control list (a list of control networks) for data in order to operate.
virtual bool isExecutable (GuiCameraQsp guiCamera)
Re-implement this method if your WorkOrder utilizes GuiCameraQsp (a QSharedPointer to a GuiCamera object) for data in order to operate.
virtual bool isExecutable (FileItemQsp fileItem)
Re-implement this method if your WorkOrder utilizes FileItemQsp (a QSharedPointer to a FileItem object) for data in order to operate.
virtual bool isExecutable (ProjectItem *item)
Determines if the WorkOrder is execuatable on the data stored in a ProjectItem.
void save (QXmlStreamWriter &stream) const
: Saves a WorkOrder to a data stream.
virtual void setData (Context)
Sets the context data for this WorkOrder.
virtual void setData (QString data)
virtual void setData (ImageList *images)
Sets the ImageList data for this WorkOrder.
virtual void setData (ShapeList *shapes)
Sets the ShapeList data for this WorkOrder.
virtual void setData (ControlList *controls)
Sets the Control data for this WorkOrder.
virtual void setData (Template *currentTemplate)
Sets the TargetBody data for this WorkOrder.
virtual void setData (CorrelationMatrix)
Sets the CorrelationMatrix data for this WorkOrder.
virtual void setData (TargetBodyQsp targetBody)
Sets the TargetBody data for this WorkOrder.
virtual void setData (GuiCameraQsp guiCamera)
Sets the GuiCamera data for this WorkOrder.
virtual void setData (FileItemQsp fileItem)
Sets the FileItem data for this WorkOrder.
virtual void setData (ProjectItem *item)
Sets the internal data to the data stored in a ProjectItem.
void setNext (WorkOrder *nextWorkOrder)
Sets the next WorkOrder in the sequence.
void setPrevious (WorkOrder *previousWorkOrder)
Sets the previous WorkOrder in the sequence.
QString bestText () const
Generate unique action names We don't use action text anymore because Directory likes to rename our actions.
bool isUndoable () const
Returns true if this work order is undoable, otherwise false.
bool isSavedToHistory () const
Returns true if this work order is to be shown in History, otherwise false.
bool isSynchronous () const
Returns true if this work order is run synchronously, otherwise false.
bool createsCleanState () const
Returns the CleanState status (whether the Project has been saved to disk or not).
QDateTime executionTime () const
Gets the execution time of this WorkOrder.
bool isFinished () const
Returns the finished state of this WorkOrder.
bool isRedoing () const
Returns the redoing status of this WorkOrder.
bool isRedone () const
Returns the WorkOrder redone status.
bool isUndoing () const
Returns the WorkOrderUndoing state.
bool isUndone () const
Returns the WorkOrder undo status.
bool modifiesDiskState () const
Returns the modified disk state.
WorkOrder * next () const
Gets the next WorkOrder.
WorkOrder * previous () const
Gets the previous WorkOrder.
QString statusText () const
WorkOrder::statusText.
ProgressBar * progressBar ()
Returns the ProgressBar.
Static Public Member Functions
static WorkOrderStatus fromStatusString (QString)
Attempts to query the current status of the WorkOrder.
static QString toString (WorkOrderStatus)
Gets the current status of the WorkOrder.
Protected Slots
void addCloneToProject ()
Runs a copy of the current WorkOrder and stores it in the project.
Protected Member Functions
virtual void postExecution ()
Display any warnings that occurred during the asynchronous computations.
ImageList * imageList ()
Returns a pointer to the ImageList for this WorkOrder.
const ImageList * imageList () const
A thread-safe method for retrieving a pointer to the imageList.
ShapeList * shapeList ()
@briefReturns a pointer to the ShapeList for this WorkOrder.
const ShapeList * shapeList () const
A thread-safe method for retrieving a pointer to the shapeList.
CorrelationMatrix correlationMatrix ()
Returns the CorrleationMatrix for this WorkOrder.
QPointer< ControlList > controlList ()
Returns the Control List for this WorkOrder (a list of control networks).
Template * getTemplate ()
WorkOrder::getTemplate.
TargetBodyQsp targetBody ()
WorkOrder::targetBody.
GuiCameraQsp guiCamera ()
WorkOrder::guiCamera.
FileItemQsp fileItem ()
WorkOrder::fileItem.
virtual bool dependsOn (WorkOrder *other) const
Indicate workorder dependency This is a virtual function whose role in child classes is to determine if this WorkOrder depends on the WorkOrder passed in as an argument.
Directory * directory () const
return the workorder project directory Returns the Directory object of the Project this WorkOrder is attached to.
Project * project () const
Returns the Project this WorkOrder is attached to.
void setCreatesCleanState (bool createsCleanState)
Declare that this work order is saving the project.
void setModifiesDiskState (bool changesProjectOnDisk)
void setInternalData (QStringList data)
Sets the internal data for this WorkOrder.
int progressMin () const
Gets the minimum value of the progress range of the WorkOrder.
int progressMax () const
Gets the maximum value of the progress range of the WorkOrder.
int progressValue () const
Gets the current progress value of the WorkOrder.
void setProgressRange (int, int)
Sets the progress range of the WorkOrder.
void setProgressValue (int)
Sets the current progress value for the WorkOrder.
QStringList internalData () const
Gets the internal data for this WorkOrder.
virtual void undoExecution ()
Execute the steps necessary to undo this workorder.
virtual void postUndoExecution ()
Perform any steps necessary after an undo of a workorder.
Protected Attributes
bool m_isUndoable
Set the workorder to be undoable/redoable This is defaulted to true - his will allow the workorder to be redone.
bool m_isSynchronous
This is defaulted to true.
bool m_isSavedToHistory
Set the work order to be shown in the HistoryTreeWidget.
WorkOrderStatus m_status
Detailed Description
Write a project control network to a user-specified location.
Takes a control and writes it's controlNet to disk at a user-specified location. This works both with and without context (context menus and file menu).
internalData() stores: Control ID [OPTIONAL] - need context if this isn't present (see controlList()) Output File Name [REQUIRED]
Author
2012-09-26 Tracie Sucharski
Member Enumeration Documentation
Context
enum Isis::WorkOrder::Context inherited
This enumeration is for recording the context of the current Workorder (whether it is part of a project or not).
Enumerator
NoContext
ProjectContext
WorkOrderStatus
enum Isis::WorkOrder::WorkOrderStatus inherited
This enumeration is used by other functions to set and retrieve the current state of the WorkOrder.
Enumerator
WorkOrderUnknownStatus
WorkOrderNotStarted
WorkOrderRedoing
WorkOrderRedone
WorkOrderUndoing
WorkOrderUndone
WorkOrderFinished
This is used for work orders that will not undo or redo (See createsCleanState())
WorkOrderLastStatus
Constructor & Destructor Documentation
ExportControlNetWorkOrder() [1/2]
Isis::ExportControlNetWorkOrder::ExportControlNetWorkOrder (Project * project)
Creates a work order for exporting a control network from the project.
This work order is asynchronous and is not undoable.
Parameters
Project *project Pointer to the project to export from (the project this work order belongs to).
References Isis::WorkOrder::m_isSynchronous, and Isis::WorkOrder::m_isUndoable.
Referenced by clone().
ExportControlNetWorkOrder() [2/2]
Isis::ExportControlNetWorkOrder::ExportControlNetWorkOrder (const ExportControlNetWorkOrder & other)
Copy constructor.
Copies the work order.
Parameters
ExportControlNetWorkOrder &other The other work order to copy state from.
~ExportControlNetWorkOrder()
Isis::ExportControlNetWorkOrder::~ExportControlNetWorkOrder ()
Destructor.
Default destructor to clean up any memory this work order might allocate.
Member Function Documentation
addCloneToProject
void Isis::WorkOrder::addCloneToProject () protected slot inherited
Runs a copy of the current WorkOrder and stores it in the project.
References Isis::Project::addToProject(), Isis::WorkOrder::clone(), and Isis::WorkOrder::project().
Referenced by Isis::WorkOrder::WorkOrder().
bestText()
QString Isis::WorkOrder::bestText () const inherited
Generate unique action names We don't use action text anymore because Directory likes to rename our actions.
It converts a set of actions that have the same text, like Zoom Fit, to be in a menu named Zoom Fit with items that name their widgets. Widget names are unhelpful as a description of the action.
See also
Directory::restructureActions
Returns
QString A textual description of the action.
Referenced by Isis::WorkOrder::redo(), Isis::WorkOrder::save(), and Isis::WorkOrder::undo().
clone()
ExportControlNetWorkOrder * Isis::ExportControlNetWorkOrder::clone () const virtual
Clones this work order.
Allocate a new work order using this work order's state.
Returns
ExportControlNetWorkOrder* Returns a pointer to the newly cloned work order.
Implements Isis::WorkOrder.
References ExportControlNetWorkOrder().
controlList()
QPointer< ControlList > Isis::WorkOrder::controlList () protected inherited
Returns the Control List for this WorkOrder (a list of control networks).
Returns
QPointer<ControlList> Returns m_controlList.
References Isis::WorkOrder::project().
Referenced by Isis::CnetEditorViewWorkOrder::execute(), execute(), Isis::SetActiveControlWorkOrder::execute(), Isis::WorkOrder::isExecutable(), Isis::WorkOrder::setData(), Isis::CnetEditorViewWorkOrder::setupExecution(), Isis::ControlHealthMonitorWorkOrder::setupExecution(), setupExecution(), and Isis::SetActiveControlWorkOrder::setupExecution().
correlationMatrix()
CorrelationMatrix Isis::WorkOrder::correlationMatrix () protected inherited
Returns the CorrleationMatrix for this WorkOrder.
Returns
A CorrelationMatrix.
References Isis::WorkOrder::project().
Referenced by Isis::MatrixViewWorkOrder::execute(), Isis::WorkOrder::setData(), and Isis::MatrixViewWorkOrder::setupExecution().
createsCleanState()
bool Isis::WorkOrder::createsCleanState () const inherited
Returns the CleanState status (whether the Project has been saved to disk or not).
If this is set to true the work order will avoid being put on the undo stack, meaning it will not be undoable. It will also set the undo stack to a clean state, by doing this it makes all previous workorders done before the save to be no longer undoable.
Returns
Returns True if the Project has been saved to disk. False if it has not.
References Isis::WorkOrder::project().
Referenced by Isis::Project::addToProject(), Isis::WorkOrder::setCreatesCleanState(), and Isis::WorkOrder::setupExecution().
creatingProgress
void Isis::WorkOrder::creatingProgress (WorkOrder *) signal inherited
deletingProgress
void Isis::WorkOrder::deletingProgress (WorkOrder *) signal inherited
dependsOn()
bool Isis::WorkOrder::dependsOn (WorkOrder * other) const protected virtual inherited
Indicate workorder dependency This is a virtual function whose role in child classes is to determine if this WorkOrder depends on the WorkOrder passed in as an argument.
Parameters
WorkOrder * The WorkOrder we are checking for dependency with this one.
Returns
bool Returns True if there is a dependency, and False if there is no dependency.
Reimplemented in Isis::ViewControlNet3DWorkOrder, Isis::TemplateEditViewWorkOrder, Isis::TargetGetInfoWorkOrder, Isis::SensorGetInfoWorkOrder, Isis::RenameProjectWorkOrder, Isis::MatrixViewWorkOrder, Isis::JigsawWorkOrder, Isis::CubeDnViewWorkOrder, and Isis::CnetEditorViewWorkOrder.
Referenced by Isis::WorkOrder::redo().
directory()
Directory * Isis::WorkOrder::directory () const protected inherited
return the workorder project directory Returns the Directory object of the Project this WorkOrder is attached to.
Returns
(Directory *) A pointer to the Directory.
References Isis::Project::directory(), and Isis::WorkOrder::project().
Referenced by Isis::CubeDnViewWorkOrder::execute(), Isis::Footprint2DViewWorkOrder::execute(), Isis::ImageFileListViewWorkOrder::execute(), Isis::JigsawWorkOrder::isExecutable(), and Isis::MosaicSceneWorkOrder::scene().
disableWorkOrder
void Isis::WorkOrder::disableWorkOrder () slot inherited
Disables the work order.
Disables the work order so it cannot be triggered (grayed-out).
See also
Directory::initializeActions()
enableWorkOrder
void Isis::WorkOrder::enableWorkOrder () slot inherited
Enables the work order.
Enables the work order so that it can be triggered (clicked).
See also
Directory::initializeActions()
execute()
void Isis::ExportControlNetWorkOrder::execute () virtual
Executes the work order.
Uses internalData() and writes the control network into the output file. Stores errors in m_warning which will be reported in postExecution().
See also
WorkOrder::execute()
Reimplemented from Isis::WorkOrder.
References Isis::Project::control(), Isis::WorkOrder::controlList(), Isis::Control::fileName(), Isis::WorkOrder::internalData(), and Isis::WorkOrder::project().
executionTime()
QDateTime Isis::WorkOrder::executionTime () const inherited
Gets the execution time of this WorkOrder.
Returns
QDateTime The execution time.
References Isis::WorkOrder::project().
fileItem()
FileItemQsp Isis::WorkOrder::fileItem () protected inherited
WorkOrder::fileItem.
Returns
QSharedPointer Returns a shared pointer to the fileItem.
References Isis::WorkOrder::project().
Referenced by Isis::BundleObservationViewWorkOrder::execute(), Isis::BundleObservationViewWorkOrder::isExecutable(), and Isis::WorkOrder::setData().
finished
void Isis::WorkOrder::finished (WorkOrder *) signal inherited
Referenced by Isis::WorkOrder::redo(), Isis::WorkOrder::undo(), and Isis::WorkOrder::WorkOrder().
fromStatusString()
WorkOrder::WorkOrderStatus Isis::WorkOrder::fromStatusString (QString statusString) static inherited
Attempts to query the current status of the WorkOrder.
Parameters
statusString The status we want information about.
Returns
WorkOrderStatus Returns WorkOrderUnknownStatus if the statusString does not match the current status. If there is a result, then it returns the status which matches the statusString.
References Isis::WorkOrder::toString(), Isis::WorkOrder::WorkOrderLastStatus, and Isis::WorkOrder::WorkOrderUnknownStatus.
getTemplate()
Template * Isis::WorkOrder::getTemplate () protected inherited
WorkOrder::getTemplate.
Returns
QSharedPointer Returns a shared pointer to the Template.
References Isis::WorkOrder::project().
Referenced by Isis::TemplateEditViewWorkOrder::execute(), and Isis::TemplateEditViewWorkOrder::setupExecution().
guiCamera()
GuiCameraQsp Isis::WorkOrder::guiCamera () protected inherited
WorkOrder::guiCamera.
Returns
QSharedPointer Returns a shared pointer to the guiCamera.
References Isis::WorkOrder::project().
Referenced by Isis::SensorGetInfoWorkOrder::execute(), Isis::SensorGetInfoWorkOrder::isExecutable(), Isis::WorkOrder::setData(), and Isis::SensorGetInfoWorkOrder::setupExecution().
imageList() [1/2]
ImageList * Isis::WorkOrder::imageList () protected inherited
Returns a pointer to the ImageList for this WorkOrder.
Returns
(ImageList*) A pointer to the ImageList.
References Isis::Project::image(), and Isis::WorkOrder::project().
Referenced by Isis::ExportImagesWorkOrder::execute(), Isis::ImageFileListViewWorkOrder::execute(), Isis::RemoveImagesWorkOrder::execute(), Isis::SetActiveImageListWorkOrder::execute(), Isis::ImageListActionWorkOrder::execute(), Isis::MoveDownOneSceneWorkOrder::execute(), Isis::MoveToBottomSceneWorkOrder::execute(), Isis::MoveToTopSceneWorkOrder::execute(), Isis::MoveUpOneSceneWorkOrder::execute(), Isis::WorkOrder::imageList(), Isis::ImageListActionWorkOrder::ImageListActionWorkOrder(), Isis::SetActiveImageListWorkOrder::isExecutable(), Isis::WorkOrder::isExecutable(), Isis::ImageListActionWorkOrder::qualifyString(), Isis::WorkOrder::redo(), Isis::MosaicSceneWorkOrder::restoreZPositions(), Isis::ImageListActionWorkOrder::setData(), Isis::WorkOrder::setData(), Isis::ExportImagesWorkOrder::setupExecution(), Isis::Footprint2DViewWorkOrder::setupExecution(), Isis::ImageFileListViewWorkOrder::setupExecution(), Isis::RemoveImagesWorkOrder::setupExecution(), Isis::ImageListActionWorkOrder::setupExecution(), and Isis::ImageListActionWorkOrder::undoExecution().
imageList() [2/2]
const ImageList * Isis::WorkOrder::imageList () const protected inherited
A thread-safe method for retrieving a pointer to the imageList.
Returns
(ImageList *) A pointer to the image list for this WorkOrder.
References Isis::WorkOrder::imageList().
internalData()
QStringList Isis::WorkOrder::internalData () const protected inherited
Gets the internal data for this WorkOrder.
Returns
QStringList Returns the internal data object.
References Isis::WorkOrder::project().
Referenced by Isis::CubeDnViewWorkOrder::execute(), execute(), Isis::ExportImagesWorkOrder::execute(), Isis::Footprint2DViewWorkOrder::execute(), Isis::ImageFileListViewWorkOrder::execute(), Isis::ImportControlNetWorkOrder::execute(), Isis::ImportImagesWorkOrder::execute(), Isis::ImportMapTemplateWorkOrder::execute(), Isis::ImportRegistrationTemplateWorkOrder::execute(), Isis::ImportShapesWorkOrder::execute(), Isis::RenameProjectWorkOrder::execute(), Isis::SaveProjectAsWorkOrder::execute(), Isis::ImageListActionWorkOrder::execute(), Isis::ImageListActionWorkOrder::ImageListActionWorkOrder(), Isis::RenameProjectWorkOrder::RenameProjectWorkOrder(), Isis::MosaicSceneWorkOrder::restoreZPositions(), Isis::MosaicSceneWorkOrder::scene(), Isis::ImageListActionWorkOrder::setData(), Isis::CubeDnViewWorkOrder::setupExecution(), setupExecution(), Isis::ExportImagesWorkOrder::setupExecution(), Isis::Footprint2DViewWorkOrder::setupExecution(), Isis::ImageFileListViewWorkOrder::setupExecution(), Isis::ImportControlNetWorkOrder::setupExecution(), Isis::MatrixViewWorkOrder::setupExecution(), Isis::RenameProjectWorkOrder::setupExecution(), Isis::SensorGetInfoWorkOrder::setupExecution(), Isis::TargetGetInfoWorkOrder::setupExecution(), Isis::TemplateEditViewWorkOrder::setupExecution(), Isis::ImageListActionWorkOrder::setupExecution(), Isis::MosaicSceneWorkOrder::storeZPositions(), Isis::MatrixViewWorkOrder::undoExecution(), Isis::RenameProjectWorkOrder::undoExecution(), and Isis::ImageListActionWorkOrder::undoExecution().
isExecutable() [1/10]
bool Isis::WorkOrder::isExecutable (Context context) virtual inherited
Re-implement this method if your work order utilizes controls for data in order to operate.
For example, "CnetEditorViewWorkOrder" works sometimes on controls
the logic in side of CnetEditorViewWorkOrder::isExecutable() determines whethere or not a user is prompted with this work order as a possibility.
Parameters
context This is an enum variable with two values: NoContext,ProjectContext.
Returns
bool Upon re-implementation, returns True if the WorkOrder is executable, and False if it is not.
Reimplemented in Isis::RenameProjectWorkOrder.
Referenced by Isis::WorkOrder::isExecutable(), and Isis::Directory::supportedActions().
isExecutable() [2/10]
bool Isis::ExportControlNetWorkOrder::isExecutable (ControlList * controls) virtual
Determines if we can export a control net.
Currently, this work order only works with either no data (file menu) or with a single control network.
Parameters
ControList *controls The current context we're inquiring about.
Returns
bool Returns true if this work order functions with the given control list. Right now, true indicates that there is one control list in the project.
Reimplemented from Isis::WorkOrder.
isExecutable() [3/10]
bool Isis::WorkOrder::isExecutable (CorrelationMatrix correlationMatrix) virtual inherited
Reimplemented in Isis::MatrixViewWorkOrder.
isExecutable() [4/10]
bool Isis::WorkOrder::isExecutable (FileItemQsp fileItem) virtual inherited
Re-implement this method if your WorkOrder utilizes FileItemQsp (a QSharedPointer to a FileItem object) for data in order to operate.
Parameters
FileItemQsp
Returns
bool Upon re-implementation, returns True if the WorkOrder is executable, and False if it is not.
Reimplemented in Isis::BundleObservationViewWorkOrder.
isExecutable() [5/10]
bool Isis::WorkOrder::isExecutable (GuiCameraQsp guiCamera) virtual inherited
Re-implement this method if your WorkOrder utilizes GuiCameraQsp (a QSharedPointer to a GuiCamera object) for data in order to operate.
Parameters
GuiCameraQsp
Returns
bool Upon re-implementation, returns True if the WorkOrder is executable, and False if it is not.
Reimplemented in Isis::SensorGetInfoWorkOrder.
isExecutable() [6/10]
bool Isis::WorkOrder::isExecutable (ImageList * images) virtual inherited
Re-implement this method if your work order utilizes images for data in order to operate.
For example, "Footprint2DViewWorkOrder" works sometimes on images - the logic in side of Footprint2DViewWorkOrder::isExecutable(ImageList) determines whethere or not a user is prompted with this work order as a possibility.
Parameters
images An image list that this work order should execute on
Returns
bool Upon re-implementation, returns True if the WorkOrder is executable, and False if it is not.
Reimplemented in Isis::ImageListActionWorkOrder, Isis::RemoveImagesWorkOrder, Isis::ImageFileListViewWorkOrder, Isis::Footprint2DViewWorkOrder, Isis::ExportImagesWorkOrder, Isis::CubeDnViewWorkOrder, and Isis::SetActiveImageListWorkOrder.
isExecutable() [7/10]
bool Isis::WorkOrder::isExecutable (ProjectItem * item) virtual inherited
Determines if the WorkOrder is execuatable on the data stored in a ProjectItem.
Parameters
item (ProjectItem *) The item containing the data.
Returns
bool Returns True if the WorkOrder is executable on data stored in a ProjectItem.
Reimplemented in Isis::TemplateEditViewWorkOrder, Isis::ImportShapesWorkOrder, Isis::ImportRegistrationTemplateWorkOrder, Isis::ImportMapTemplateWorkOrder, Isis::ImportImagesWorkOrder, and Isis::ImportControlNetWorkOrder.
References Isis::ImageList::append(), Isis::ShapeList::append(), Isis::ProjectItem::control(), Isis::WorkOrder::controlList(), Isis::ProjectItem::correlationMatrix(), Isis::ProjectItem::fileItem(), Isis::ProjectItem::getTemplate(), Isis::ProjectItem::guiCamera(), Isis::ProjectItem::image(), Isis::WorkOrder::imageList(), Isis::ProjectItem::imageList(), Isis::ProjectItem::isControl(), Isis::ProjectItem::isControlList(), Isis::ProjectItem::isCorrelationMatrix(), Isis::WorkOrder::isExecutable(), Isis::ProjectItem::isFileItem(), Isis::ProjectItem::isGuiCamera(), Isis::ProjectItem::isImage(), Isis::ProjectItem::isImageList(), Isis::ProjectItem::isProject(), Isis::ProjectItem::isShape(), Isis::ProjectItem::isShapeList(), Isis::ProjectItem::isTargetBody(), Isis::ProjectItem::isTemplate(), Isis::WorkOrder::ProjectContext, Isis::ProjectItem::shape(), Isis::WorkOrder::shapeList(), Isis::ProjectItem::shapeList(), and Isis::ProjectItem::targetBody().
isExecutable() [8/10]
bool Isis::WorkOrder::isExecutable (ShapeList * shapes) virtual inherited
Re-implement this method if your work order utilizes shapes for data in order to operate.
For example, "ImportShapeWorkOrder" works on shapes - the logic in side of ImportShapeWorkOrder::isExecutable(ShapeList) determines whethere or not a user is prompted with this work order as a possibility.
Parameters
shapes A shape list that this work order should execute on
Returns
bool Upon re-implementation, returns True if the WorkOrder is executable, and False if it is not.
Reimplemented in Isis::Footprint2DViewWorkOrder, and Isis::CubeDnViewWorkOrder.
isExecutable() [9/10]
bool Isis::WorkOrder::isExecutable (TargetBodyQsp targetBody) virtual inherited
Re-implement this method if your work order utilizes a control list (a list of control networks) for data in order to operate.
Parameters
controls A list of control networks.
Returns
bool Upon re-implementation, returns True if the WorkOrder is executable, and False if it is not.
Reimplemented in Isis::TargetGetInfoWorkOrder.
isExecutable() [10/10]
bool Isis::WorkOrder::isExecutable (Template * currentTemplate) virtual inherited
Re-implement this method if your work order utilizes a control list (a list of control networks) for data in order to operate.
Parameters
controls A list of control networks.
Returns
bool Upon re-implementation, returns True if the WorkOrder is executable, and False if it is not.
isFinished()
bool Isis::WorkOrder::isFinished () const inherited
Returns the finished state of this WorkOrder.
Returns
bool Returns True if the WorkOrder is finished, False otherwise.
References Isis::WorkOrder::m_status, and Isis::WorkOrder::WorkOrderFinished.
Referenced by Isis::WorkOrder::redo(), and Isis::WorkOrder::undo().
isRedoing()
bool Isis::WorkOrder::isRedoing () const inherited
Returns the redoing status of this WorkOrder.
Returns
bool Returns True if the WorkOrder is executing a redo. Returns False if it is not.
References Isis::WorkOrder::m_status, Isis::WorkOrder::project(), and Isis::WorkOrder::WorkOrderRedoing.
Referenced by Isis::WorkOrder::redo(), and Isis::WorkOrder::undo().
isRedone()
bool Isis::WorkOrder::isRedone () const inherited
Returns the WorkOrder redone status.
Returns
bool Returns True if the WorkOrder has completed a Redo. False if it has not.
References Isis::WorkOrder::m_status, Isis::WorkOrder::project(), and Isis::WorkOrder::WorkOrderRedone.
Referenced by Isis::WorkOrder::redo().
isSavedToHistory()
bool Isis::WorkOrder::isSavedToHistory () const inherited
Returns true if this work order is to be shown in History, otherwise false.
Returns
(bool) Returns True if this work order is to be shown in History
References Isis::WorkOrder::m_isSavedToHistory, and Isis::WorkOrder::project().
Referenced by Isis::Project::addToProject().
isSynchronous()
bool Isis::WorkOrder::isSynchronous () const inherited
Returns true if this work order is run synchronously, otherwise false.
Returns
(bool) Returns True if this work order is run synchronously
References Isis::WorkOrder::m_isSynchronous, and Isis::WorkOrder::project().
Referenced by Isis::WorkOrder::redo(), and Isis::WorkOrder::undo().
isUndoable()
bool Isis::WorkOrder::isUndoable () const inherited
Returns true if this work order is undoable, otherwise false.
This needs to be set to true and createsCleanState needs to be set to false in order for a WorkOrder to appear on the undoStack. This should be done by setting the member variable and should not be overloading this function.
Returns
(bool) Returns True if this work order is undoable, false if it is not.
References Isis::WorkOrder::m_isUndoable, and Isis::WorkOrder::project().
Referenced by Isis::Project::addToProject(), and Isis::WorkOrder::setupExecution().
isUndoing()
bool Isis::WorkOrder::isUndoing () const inherited
Returns the WorkOrderUndoing state.
Returns
bool Returns True if the current status is WorkOrderUndoing, False otherwise.
References Isis::WorkOrder::m_status, Isis::WorkOrder::project(), and Isis::WorkOrder::WorkOrderUndoing.
Referenced by Isis::Project::lastNotUndoneWorkOrder(), Isis::WorkOrder::redo(), and Isis::WorkOrder::undo().
isUndone()
bool Isis::WorkOrder::isUndone () const inherited
Returns the WorkOrder undo status.
Returns
bool Returns True if the WorkOrder has been undone. False if it has not.
References Isis::WorkOrder::m_status, Isis::WorkOrder::project(), and Isis::WorkOrder::WorkOrderUndone.
Referenced by Isis::Project::lastNotUndoneWorkOrder(), and Isis::WorkOrder::undo().
modifiesDiskState()
bool Isis::WorkOrder::modifiesDiskState () const inherited
Returns the modified disk state.
Returns
Returns True if the WorkOrder has modified the Project on disk to perform it's actions. Returns False if it has not.
References Isis::WorkOrder::project().
next()
WorkOrder * Isis::WorkOrder::next () const inherited
Gets the next WorkOrder.
Returns
QPointer pointing to the next WorkOrder.
References Isis::WorkOrder::project().
Referenced by Isis::WorkOrder::undo().
postExecution()
void Isis::ExportControlNetWorkOrder::postExecution () protected virtual
Display any warnings that occurred during the asynchronous computations.
These warnings will be attached to the project.
See also
WorkOrder::postExecution()
Reimplemented from Isis::WorkOrder.
References Isis::WorkOrder::project(), and Isis::Project::warn().
postUndoExecution()
void Isis::WorkOrder::postUndoExecution () protected virtual inherited
Perform any steps necessary after an undo of a workorder.
State can be read from the parent WorkOrder class and from state set undoExecution() while in this method. You can not set state to be used in any of the redo code safely. This method is always executed in the GUI thread and has no progress.
Reimplemented in Isis::ImportShapesWorkOrder, and Isis::ImportImagesWorkOrder.
previous()
WorkOrder * Isis::WorkOrder::previous () const inherited
Gets the previous WorkOrder.
Returns
QPointer pointing to the previous WorkOrder.
References Isis::WorkOrder::project().
Referenced by Isis::Project::addToProject(), Isis::Project::lastNotUndoneWorkOrder(), and Isis::WorkOrder::redo().
progressBar()
ProgressBar * Isis::WorkOrder::progressBar () inherited
Returns the ProgressBar.
Returns
A QPointer to the ProgessBar.
References Isis::WorkOrder::project().
Referenced by Isis::OpenProjectWorkOrder::setupExecution().
progressMax()
int Isis::WorkOrder::progressMax () const protected inherited
Gets the maximum value of the progress range of the WorkOrder.
Returns
int The maximum value.
References Isis::WorkOrder::project().
progressMin()
int Isis::WorkOrder::progressMin () const protected inherited
Gets the minimum value of the progress range of the WorkOrder.
Returns
int The minimum value.
References Isis::WorkOrder::project().
progressValue()
int Isis::WorkOrder::progressValue () const protected inherited
Gets the current progress value of the WorkOrder.
Returns
int Returns the current progress value.
References Isis::WorkOrder::project().
project()
Project * Isis::WorkOrder::project () const protected inherited
Returns the Project this WorkOrder is attached to.
Returns
(Project *) A pointer to the Project.
Exceptions
IException::Programmer "This work order no longer has a project."
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by Isis::WorkOrder::addCloneToProject(), Isis::WorkOrder::controlList(), Isis::WorkOrder::correlationMatrix(), Isis::WorkOrder::createsCleanState(), Isis::WorkOrder::directory(), Isis::BundleObservationViewWorkOrder::execute(), Isis::CloseProjectWorkOrder::execute(), Isis::CnetEditorViewWorkOrder::execute(), Isis::ControlHealthMonitorWorkOrder::execute(), Isis::CubeDnViewWorkOrder::execute(), execute(), Isis::ExportImagesWorkOrder::execute(), Isis::Footprint2DViewWorkOrder::execute(), Isis::ImageFileListViewWorkOrder::execute(), Isis::ImportControlNetWorkOrder::execute(), Isis::ImportImagesWorkOrder::execute(), Isis::ImportMapTemplateWorkOrder::execute(), Isis::ImportRegistrationTemplateWorkOrder::execute(), Isis::ImportShapesWorkOrder::execute(), Isis::JigsawWorkOrder::execute(), Isis::MatrixViewWorkOrder::execute(), Isis::OpenProjectWorkOrder::execute(), Isis::RemoveImagesWorkOrder::execute(), Isis::RenameProjectWorkOrder::execute(), Isis::SaveProjectAsWorkOrder::execute(), Isis::SensorGetInfoWorkOrder::execute(), Isis::SetActiveControlWorkOrder::execute(), Isis::SetActiveImageListWorkOrder::execute(), Isis::TargetGetInfoWorkOrder::execute(), Isis::TemplateEditViewWorkOrder::execute(), Isis::WorkOrder::executionTime(), Isis::WorkOrder::fileItem(), Isis::WorkOrder::getTemplate(), Isis::WorkOrder::guiCamera(), Isis::WorkOrder::imageList(), Isis::WorkOrder::internalData(), Isis::JigsawWorkOrder::isExecutable(), Isis::SetActiveControlWorkOrder::isExecutable(), Isis::SensorGetInfoWorkOrder::isExecutable(), Isis::SetActiveImageListWorkOrder::isExecutable(), Isis::TemplateEditViewWorkOrder::isExecutable(), Isis::TargetGetInfoWorkOrder::isExecutable(), Isis::WorkOrder::isRedoing(), Isis::WorkOrder::isRedone(), Isis::WorkOrder::isSavedToHistory(), Isis::WorkOrder::isSynchronous(), Isis::WorkOrder::isUndoable(), Isis::WorkOrder::isUndoing(), Isis::WorkOrder::isUndone(), Isis::WorkOrder::modifiesDiskState(), Isis::WorkOrder::next(), postExecution(), Isis::ExportImagesWorkOrder::postExecution(), Isis::ImportControlNetWorkOrder::postExecution(), Isis::ImportImagesWorkOrder::postExecution(), Isis::ImportShapesWorkOrder::postExecution(), Isis::ImportImagesWorkOrder::postUndoExecution(), Isis::ImportShapesWorkOrder::postUndoExecution(), Isis::WorkOrder::previous(), Isis::WorkOrder::progressBar(), Isis::WorkOrder::progressMax(), Isis::WorkOrder::progressMin(), Isis::WorkOrder::progressValue(), Isis::WorkOrder::redo(), Isis::RenameProjectWorkOrder::RenameProjectWorkOrder(), Isis::CloseProjectWorkOrder::setupExecution(), Isis::CubeDnViewWorkOrder::setupExecution(), setupExecution(), Isis::ExportImagesWorkOrder::setupExecution(), Isis::Footprint2DViewWorkOrder::setupExecution(), Isis::ImageFileListViewWorkOrder::setupExecution(), Isis::ImportImagesWorkOrder::setupExecution(), Isis::MatrixViewWorkOrder::setupExecution(), Isis::OpenProjectWorkOrder::setupExecution(), Isis::RemoveImagesWorkOrder::setupExecution(), Isis::RenameProjectWorkOrder::setupExecution(), Isis::SaveProjectWorkOrder::setupExecution(), Isis::SetActiveControlWorkOrder::setupExecution(), Isis::WorkOrder::shapeList(), Isis::WorkOrder::statusText(), Isis::WorkOrder::targetBody(), Isis::CnetEditorViewWorkOrder::undoExecution(), Isis::ImportImagesWorkOrder::undoExecution(), Isis::ImportMapTemplateWorkOrder::undoExecution(), Isis::ImportRegistrationTemplateWorkOrder::undoExecution(), Isis::ImportShapesWorkOrder::undoExecution(), Isis::MatrixViewWorkOrder::undoExecution(), Isis::RenameProjectWorkOrder::undoExecution(), and Isis::WorkOrder::WorkOrder().
redo
void Isis::WorkOrder::redo () virtual slot inherited
Starts (or enqueues) a redo.
This should not be re-implemented by children.
References Isis::WorkOrder::bestText(), Isis::WorkOrder::dependsOn(), Isis::WorkOrder::execute(), Isis::WorkOrder::finished(), Isis::WorkOrder::imageList(), Isis::WorkOrder::isFinished(), Isis::WorkOrder::isRedoing(), Isis::WorkOrder::isRedone(), Isis::WorkOrder::isSynchronous(), Isis::WorkOrder::isUndoing(), Isis::WorkOrder::m_status, Isis::WorkOrder::previous(), Isis::WorkOrder::project(), Isis::WorkOrder::shapeList(), Isis::WorkOrder::statusChanged(), and Isis::WorkOrder::WorkOrderRedoing.
Referenced by Isis::Project::addToProject().
save()
void Isis::WorkOrder::save (QXmlStreamWriter & stream) const inherited
: Saves a WorkOrder to a data stream.
The XML output format looks like this:
  <workOrder actionText="..." undoText="..." type="..." status="...">
    <images>
      <image id="..." >
    </images>
    <internalDataValues>
      <dataValue value="..." >
    </internalDataValues>
  </workOrder>
Parameters
References _FILEINFO_, Isis::WorkOrder::bestText(), Isis::WorkOrder::m_status, Isis::WorkOrder::NoContext, Isis::IException::Programmer, and Isis::WorkOrder::toString().
Referenced by Isis::CloseProjectWorkOrder::setupExecution(), and Isis::OpenProjectWorkOrder::setupExecution().
setCreatesCleanState()
void Isis::WorkOrder::setCreatesCleanState (bool createsCleanState) protected inherited
Declare that this work order is saving the project.
This makes the work order not appear in the undo stack (cannot undo/redo), and instead it is marked as a 'clean' state of the project. The QUndoCommand undo/redo will never be called. The default for createsCleanState is false. If this is set to true all wrokorders before this call will be locked.
Parameters
createsCleanState True if this work order is going to save the project to disk, False otherwise.
References Isis::WorkOrder::createsCleanState().
Referenced by Isis::CloseProjectWorkOrder::CloseProjectWorkOrder(), Isis::OpenProjectWorkOrder::OpenProjectWorkOrder(), Isis::SaveProjectAsWorkOrder::SaveProjectAsWorkOrder(), and Isis::SaveProjectWorkOrder::SaveProjectWorkOrder().
setData() [1/11]
void Isis::WorkOrder::setData (Context context) virtual inherited
Sets the context data for this WorkOrder.
Parameters
context This is an enum variable with two values: NoContext,ProjectContext.
Referenced by Isis::ImageListActionWorkOrder::setData(), Isis::WorkOrder::setData(), setupExecution(), Isis::Directory::supportedActions(), and Isis::MosaicSceneWidget::supportedActions().
setData() [2/11]
void Isis::WorkOrder::setData (ControlList * controls) virtual inherited
Sets the Control data for this WorkOrder.
Parameters
controls. A pointer to the Control
Sets the ControlList data for this WorkOrder.
Parameters
controls. A pointer to the ControlList (which is a list of control networks).
setData() [3/11]
void Isis::WorkOrder::setData (CorrelationMatrix correlationMatrix) virtual inherited
Sets the CorrelationMatrix data for this WorkOrder.
Parameters
correlationMatrix The matrix data.
References Isis::WorkOrder::correlationMatrix().
setData() [4/11]
void Isis::WorkOrder::setData (FileItemQsp fileItem) virtual inherited
Sets the FileItem data for this WorkOrder.
Parameters
FileItem A QSharedPointer to the FileItem.
References Isis::WorkOrder::fileItem().
setData() [5/11]
void Isis::WorkOrder::setData (GuiCameraQsp guiCamera) virtual inherited
Sets the GuiCamera data for this WorkOrder.
Parameters
guiCamera A QSharedPointer to the GuiCamera.
References Isis::WorkOrder::guiCamera().
setData() [6/11]
void Isis::WorkOrder::setData (ImageList * images) virtual inherited
Sets the ImageList data for this WorkOrder.
Parameters
images A pointer to the updated ImageList.
Reimplemented in Isis::ImageListActionWorkOrder.
setData() [7/11]
void Isis::WorkOrder::setData (ProjectItem * item) virtual inherited
Sets the internal data to the data stored in a ProjectItem.
Parameters
item The item containing the data.
References Isis::ImageList::append(), Isis::ShapeList::append(), Isis::ProjectItem::control(), Isis::WorkOrder::controlList(), Isis::ProjectItem::controlList(), Isis::ProjectItem::correlationMatrix(), Isis::ProjectItem::fileItem(), Isis::ProjectItem::getTemplate(), Isis::ProjectItem::guiCamera(), Isis::ProjectItem::image(), Isis::WorkOrder::imageList(), Isis::ProjectItem::imageList(), Isis::ProjectItem::isControl(), Isis::ProjectItem::isControlList(), Isis::ProjectItem::isCorrelationMatrix(), Isis::ProjectItem::isFileItem(), Isis::ProjectItem::isGuiCamera(), Isis::ProjectItem::isImage(), Isis::ProjectItem::isImageList(), Isis::ProjectItem::isProject(), Isis::ProjectItem::isShape(), Isis::ProjectItem::isShapeList(), Isis::ProjectItem::isTargetBody(), Isis::ProjectItem::isTemplate(), Isis::WorkOrder::ProjectContext, Isis::WorkOrder::setData(), Isis::ProjectItem::shape(), Isis::WorkOrder::shapeList(), Isis::ProjectItem::shapeList(), and Isis::ProjectItem::targetBody().
setData() [8/11]
void Isis::WorkOrder::setData (QString data) virtual inherited
setData() [9/11]
void Isis::WorkOrder::setData (ShapeList * shapes) virtual inherited
Sets the ShapeList data for this WorkOrder.
Parameters
images A pointer to the updated ShapeList.
setData() [10/11]
void Isis::WorkOrder::setData (TargetBodyQsp targetBody) virtual inherited
Sets the TargetBody data for this WorkOrder.
Parameters
targetBody A QSharedPointer to the TargetBody.
References Isis::WorkOrder::targetBody().
setData() [11/11]
void Isis::WorkOrder::setData (Template * currentTemplate) virtual inherited
Sets the TargetBody data for this WorkOrder.
Parameters
targetBody A QSharedPointer to the TargetBody.
setInternalData()
void Isis::WorkOrder::setInternalData (QStringList data) protected inherited
Sets the internal data for this WorkOrder.
WorkOrders may not use member variables to store data. Any data needed for the workorder should be saved in to the base WorkOrder using setInternalData.
Parameters
data The data to set the internal data to.
Referenced by Isis::ImageListActionWorkOrder::execute(), Isis::ImageListActionWorkOrder::ImageListActionWorkOrder(), Isis::ImportMapTemplateWorkOrder::isExecutable(), Isis::ImportRegistrationTemplateWorkOrder::isExecutable(), Isis::MosaicSceneWorkOrder::MosaicSceneWorkOrder(), Isis::RenameProjectWorkOrder::RenameProjectWorkOrder(), Isis::CubeDnViewWorkOrder::setupExecution(), setupExecution(), Isis::ExportImagesWorkOrder::setupExecution(), Isis::Footprint2DViewWorkOrder::setupExecution(), Isis::ImageFileListViewWorkOrder::setupExecution(), Isis::ImportControlNetWorkOrder::setupExecution(), Isis::ImportImagesWorkOrder::setupExecution(), Isis::ImportMapTemplateWorkOrder::setupExecution(), Isis::ImportRegistrationTemplateWorkOrder::setupExecution(), Isis::ImportShapesWorkOrder::setupExecution(), Isis::MatrixViewWorkOrder::setupExecution(), Isis::RenameProjectWorkOrder::setupExecution(), Isis::SaveProjectAsWorkOrder::setupExecution(), Isis::SensorGetInfoWorkOrder::setupExecution(), Isis::TargetGetInfoWorkOrder::setupExecution(), Isis::TemplateEditViewWorkOrder::setupExecution(), Isis::ImageListActionWorkOrder::setupExecution(), Isis::MosaicSceneWorkOrder::storeZPositions(), and Isis::ImageListActionWorkOrder::undoExecution().
setModifiesDiskState()
void Isis::WorkOrder::setModifiesDiskState (bool changesProjectOnDisk) protected inherited
By default, m_modifiesDiskState is False. If a WorkOrder modifies the Project on disk as a result of it's action, this should be set to true.
Parameters
changesProjectOnDisk True if this WorkOrder modifies the Project on disk. False if it does not.
Referenced by Isis::ImportControlNetWorkOrder::ImportControlNetWorkOrder(), Isis::ImportImagesWorkOrder::ImportImagesWorkOrder(), Isis::ImportMapTemplateWorkOrder::ImportMapTemplateWorkOrder(), Isis::ImportRegistrationTemplateWorkOrder::ImportRegistrationTemplateWorkOrder(), Isis::ImportShapesWorkOrder::ImportShapesWorkOrder(), and Isis::RemoveImagesWorkOrder::RemoveImagesWorkOrder().
setNext()
void Isis::WorkOrder::setNext (WorkOrder * nextWorkOrder) inherited
Sets the next WorkOrder in the sequence.
Parameters
nextWorkOrder The next WorkOrder.
Referenced by Isis::Project::addToProject().
setPrevious()
void Isis::WorkOrder::setPrevious (WorkOrder * previousWorkOrder) inherited
Sets the previous WorkOrder in the sequence.
Parameters
previousWorkOrder The previous WorkOrder.
Referenced by Isis::Project::addToProject().
setProgressRange()
void Isis::WorkOrder::setProgressRange (int minValue, int maxValue) protected inherited
Sets the progress range of the WorkOrder.
Parameters
minValue The progress range minimum value.
maxValue The progress range maximum value.
Referenced by Isis::ExportImagesWorkOrder::execute(), and Isis::ImportControlNetWorkOrder::execute().
setProgressValue()
void Isis::WorkOrder::setProgressValue (int value) protected inherited
Sets the current progress value for the WorkOrder.
Parameters
int value The value to set the current progress to.
Referenced by Isis::ExportImagesWorkOrder::execute(), and Isis::ImportControlNetWorkOrder::execute().
setupExecution()
bool Isis::ExportControlNetWorkOrder::setupExecution () virtual
Prepares for exporting a control net by soliciting information from the user.
Prompts the user for input. If there is no context, we ask the user to select a control. Once we have a control (via context or asking the user), we then ask for a output cnet file name. The relevant data is stored in internalData(). The internal data will contain the control net id and the destination to export to.
Returns
bool Returns true if the setup is successful.
Reimplemented from Isis::WorkOrder.
References Isis::WorkOrder::controlList(), Isis::Project::controls(), Isis::DisplayProperties::displayName(), Isis::Control::displayProperties(), Isis::Control::fileName(), Isis::Control::id(), Isis::WorkOrder::internalData(), Isis::FileName::name(), Isis::ControlList::name(), Isis::WorkOrder::project(), Isis::WorkOrder::setData(), Isis::WorkOrder::setInternalData(), and Isis::WorkOrder::setupExecution().
shapeList() [1/2]
ShapeList * Isis::WorkOrder::shapeList () protected inherited
@briefReturns a pointer to the ShapeList for this WorkOrder.
Returns
(ShapeList*) A pointer to the ShapeList.
References Isis::WorkOrder::project(), and Isis::Project::shape().
Referenced by Isis::WorkOrder::isExecutable(), Isis::WorkOrder::redo(), Isis::WorkOrder::setData(), and Isis::WorkOrder::shapeList().
shapeList() [2/2]
const ShapeList * Isis::WorkOrder::shapeList () const protected inherited
A thread-safe method for retrieving a pointer to the shapeList.
Returns
(ShapeList *) A pointer to the shape list for this WorkOrder.
References Isis::WorkOrder::shapeList().
statusChanged
void Isis::WorkOrder::statusChanged (WorkOrder *) signal inherited
Referenced by Isis::WorkOrder::redo(), Isis::WorkOrder::setupExecution(), and Isis::WorkOrder::undo().
statusText()
QString Isis::WorkOrder::statusText () const inherited
WorkOrder::statusText.
Returns
QString A string representation of the current WorkOrder status.
References Isis::WorkOrder::m_status, Isis::WorkOrder::project(), and Isis::WorkOrder::toString().
targetBody()
TargetBodyQsp Isis::WorkOrder::targetBody () protected inherited
WorkOrder::targetBody.
Returns
QSharedPointer Returns a shared pointer to the TargetBody.
References Isis::WorkOrder::project().
Referenced by Isis::TargetGetInfoWorkOrder::execute(), Isis::TargetGetInfoWorkOrder::isExecutable(), Isis::WorkOrder::setData(), and Isis::TargetGetInfoWorkOrder::setupExecution().
toString()
QString Isis::WorkOrder::toString (WorkOrderStatus status) static inherited
Gets the current status of the WorkOrder.
Parameters
status An enumeration of all possible WorkOrder states.
Returns
QString Returns a string representation of the current status of the WorkOrder.
References Isis::WorkOrder::WorkOrderFinished, Isis::WorkOrder::WorkOrderNotStarted, Isis::WorkOrder::WorkOrderRedoing, Isis::WorkOrder::WorkOrderRedone, Isis::WorkOrder::WorkOrderUndoing, Isis::WorkOrder::WorkOrderUndone, and Isis::WorkOrder::WorkOrderUnknownStatus.
Referenced by Isis::WorkOrder::fromStatusString(), Isis::WorkOrder::save(), and Isis::WorkOrder::statusText().
undo
void Isis::WorkOrder::undo () virtual slot inherited
Starts (or enqueues) an undo.
This should not be re-implemented by children.
References Isis::WorkOrder::bestText(), Isis::WorkOrder::finished(), Isis::WorkOrder::isFinished(), Isis::WorkOrder::isRedoing(), Isis::WorkOrder::isSynchronous(), Isis::WorkOrder::isUndoing(), Isis::WorkOrder::isUndone(), Isis::WorkOrder::m_status, Isis::WorkOrder::next(), Isis::WorkOrder::statusChanged(), Isis::WorkOrder::undoExecution(), Isis::WorkOrder::WorkOrderNotStarted, and Isis::WorkOrder::WorkOrderUndoing.
undoExecution()
void Isis::WorkOrder::undoExecution () protected virtual inherited
Execute the steps necessary to undo this workorder.
The workorder should have all state necessary to undo itself stored in the workorder.
For synchronous workorders: State should only be read from the parent WorkOrder class in this method. You can set state to be used in postUndoExecution() safely. This method is always executed in the GUI thread and has no progress.
For Asynchronous workorders: State can be read from the parent WorkOrder class while in this method. You can set state to be used in postSyncUndo() safely. Please be wary of deleting QObjects inside of this method because they will cause unpredictable crashes. This method is never executed in the GUI thread. You can update progress by calling setProgressRange() and setProgressValue(). Do not manipulate any GUI objects here.
Reimplemented in Isis::MoveUpOneSceneWorkOrder, Isis::MoveToTopSceneWorkOrder, Isis::MoveToBottomSceneWorkOrder, Isis::MoveDownOneSceneWorkOrder, Isis::ImageListActionWorkOrder, Isis::ViewControlNet3DWorkOrder, Isis::SensorGetInfoWorkOrder, Isis::RenameProjectWorkOrder, Isis::MatrixViewWorkOrder, Isis::ImportShapesWorkOrder, Isis::ImportRegistrationTemplateWorkOrder, Isis::ImportMapTemplateWorkOrder, Isis::ImportImagesWorkOrder, and Isis::CnetEditorViewWorkOrder.
Referenced by Isis::WorkOrder::undo().
Member Data Documentation
m_isSavedToHistory
bool Isis::WorkOrder::m_isSavedToHistory protected inherited
Set the work order to be shown in the HistoryTreeWidget.
This is defaulted to true. If true the work order will be shown in the HistoryTreeWidget if false it will not be shown.
Referenced by Isis::BundleObservationViewWorkOrder::BundleObservationViewWorkOrder(), Isis::CloseProjectWorkOrder::CloseProjectWorkOrder(), Isis::CnetEditorViewWorkOrder::CnetEditorViewWorkOrder(), Isis::CubeDnViewWorkOrder::CubeDnViewWorkOrder(), Isis::Footprint2DViewWorkOrder::Footprint2DViewWorkOrder(), Isis::ImageFileListViewWorkOrder::ImageFileListViewWorkOrder(), Isis::ImageListActionWorkOrder::ImageListActionWorkOrder(), Isis::WorkOrder::isSavedToHistory(), Isis::MatrixViewWorkOrder::MatrixViewWorkOrder(), Isis::SensorGetInfoWorkOrder::SensorGetInfoWorkOrder(), Isis::TargetGetInfoWorkOrder::TargetGetInfoWorkOrder(), Isis::TemplateEditViewWorkOrder::TemplateEditViewWorkOrder(), Isis::ViewControlNet3DWorkOrder::ViewControlNet3DWorkOrder(), and Isis::WorkOrder::WorkOrder().
m_isSynchronous
bool Isis::WorkOrder::m_isSynchronous protected inherited
This is defaulted to true.
If true, the work order will be executed on the GUI thread synchronously. If false, then the work order will be queued for execution on a non-GUI thread and will not block the GUI.
Referenced by ExportControlNetWorkOrder(), Isis::ExportImagesWorkOrder::ExportImagesWorkOrder(), Isis::ImportControlNetWorkOrder::ImportControlNetWorkOrder(), Isis::ImportImagesWorkOrder::ImportImagesWorkOrder(), Isis::ImportShapesWorkOrder::ImportShapesWorkOrder(), Isis::WorkOrder::isSynchronous(), and Isis::WorkOrder::WorkOrder().
m_isUndoable
bool Isis::WorkOrder::m_isUndoable protected inherited
Set the workorder to be undoable/redoable This is defaulted to true - his will allow the workorder to be redone.
Note the workorder undoExecution() method must be implemented. This will result on the workorder being placed on the QUndoStack and being displayed in the history as being undoable. If set to false, the work order will not be put on the QUndoStack and the workorder will not be able to be undone.
Referenced by Isis::BundleObservationViewWorkOrder::BundleObservationViewWorkOrder(), Isis::CloseProjectWorkOrder::CloseProjectWorkOrder(), Isis::CnetEditorViewWorkOrder::CnetEditorViewWorkOrder(), Isis::ControlHealthMonitorWorkOrder::ControlHealthMonitorWorkOrder(), Isis::CubeDnViewWorkOrder::CubeDnViewWorkOrder(), ExportControlNetWorkOrder(), Isis::ExportImagesWorkOrder::ExportImagesWorkOrder(), Isis::Footprint2DViewWorkOrder::Footprint2DViewWorkOrder(), Isis::ImageFileListViewWorkOrder::ImageFileListViewWorkOrder(), Isis::ImportControlNetWorkOrder::ImportControlNetWorkOrder(), Isis::ImportMapTemplateWorkOrder::ImportMapTemplateWorkOrder(), Isis::ImportRegistrationTemplateWorkOrder::ImportRegistrationTemplateWorkOrder(), Isis::ImportShapesWorkOrder::ImportShapesWorkOrder(), Isis::WorkOrder::isUndoable(), Isis::JigsawWorkOrder::JigsawWorkOrder(), Isis::OpenProjectWorkOrder::OpenProjectWorkOrder(), Isis::RemoveImagesWorkOrder::RemoveImagesWorkOrder(), Isis::RenameProjectWorkOrder::RenameProjectWorkOrder(), Isis::SaveProjectAsWorkOrder::SaveProjectAsWorkOrder(), Isis::SensorGetInfoWorkOrder::SensorGetInfoWorkOrder(), Isis::SetActiveControlWorkOrder::SetActiveControlWorkOrder(), Isis::SetActiveImageListWorkOrder::SetActiveImageListWorkOrder(), Isis::TargetGetInfoWorkOrder::TargetGetInfoWorkOrder(), Isis::TemplateEditViewWorkOrder::TemplateEditViewWorkOrder(), and Isis::WorkOrder::WorkOrder().
m_status
WorkOrderStatus Isis::WorkOrder::m_status protected inherited
Referenced by Isis::ControlHealthMonitorWorkOrder::execute(), Isis::MatrixViewWorkOrder::execute(), Isis::SetActiveControlWorkOrder::execute(), Isis::SetActiveImageListWorkOrder::execute(), Isis::WorkOrder::isFinished(), Isis::WorkOrder::isRedoing(), Isis::WorkOrder::isRedone(), Isis::WorkOrder::isUndoing(), Isis::WorkOrder::isUndone(), Isis::ImportControlNetWorkOrder::postExecution(), Isis::ImportImagesWorkOrder::postExecution(), Isis::WorkOrder::redo(), Isis::WorkOrder::save(), Isis::WorkOrder::setupExecution(), Isis::WorkOrder::statusText(), Isis::WorkOrder::undo(), and Isis::WorkOrder::WorkOrder().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/Directory/ExportControlNetWorkOrder.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/Directory/ExportControlNetWorkOrder.cpp