Isis Developer Reference: Isis::EmbreeShapeModel Class Reference
Isis::EmbreeShapeModel Class Reference
General purpose Embree ray tracing model.
#include <EmbreeShapeModel.h>
Public Member Functions
EmbreeShapeModel ()
Default constructor sets type to a TIN.
EmbreeShapeModel (Target *target, Pvl &pvl, EmbreeTargetManager *targetManager)
Constructor provided for instantiation from an ISIS cube.
EmbreeShapeModel (Target *target, const QString &shapefile, EmbreeTargetManager *targetManager)
Constructor provided for instantiation from a file.
virtual ~EmbreeShapeModel ()
Destructor that notifies the target shape manager that the target shape is no longer in use.
virtual bool intersectSurface (std::vector< double > observerPos, std::vector< double > lookDirection)
This method computes an intercept point given an observer location and look direction using the Embree model.
virtual bool intersectSurface (const Latitude &lat, const Longitude &lon, const std::vector< double > &observerPos, const bool &backCheck=true)
Compute intersection of surface vector direction from observer with occulusion.
virtual bool intersectSurface (const SurfacePoint &surfpt, const std::vector< double > &observerPos, const bool &backCheck=true)
Compute intersection of surface point from observer with occulusion.
virtual void clearSurfacePoint ()
Flag that the ShapeModel does not have a surface point or normal.
virtual bool isDEM () const
Indicates that this shape model is not from a DEM.
double getTolerance () const
Get the tolerance used when checking if the stored surface point is visible.
void setTolerance (const double &tolerance)
Set the tolerance used when checking if the stored surface point is visible.
virtual void calculateDefaultNormal ()
Return the surface normal of the ellipsoid as the default.
virtual void calculateLocalNormal (QVector< double * > cornerNeighborPoints)
Compute the normal for a local region of surface points.
virtual void calculateSurfaceNormal ()
Return the surface normal of the ellipsoid.
QVector< double > ellipsoidNormal ()
Compute the true surface normal vector of an ellipsoid.
virtual double incidenceAngle (const std::vector< double > &uB)
Computes and returns incidence angle, in degrees, given the illuminator position.
virtual Distance localRadius (const Latitude &lat, const Longitude &lon)
Determine radius at a given lat/lon grid point.
virtual bool isVisibleFrom (const std::vector< double > observerPos, const std::vector< double > lookDirection)
Check if the current internalized surface point is visible from an observer position and look direction.
void Initialize ()
Initializes the ShapeModel private variables.
virtual SurfacePoint * surfaceIntersection () const
Returns the surface intersection for this ShapeModel.
bool hasIntersection ()
Returns intersection status.
bool hasNormal () const
Returns surface point normal status.
bool hasLocalNormal () const
Returns surface point local normal status.
virtual double emissionAngle (const std::vector< double > &sB)
Computes and returns emission angle, in degrees, given the observer position.
virtual double phaseAngle (const std::vector< double > &sB, const std::vector< double > &uB)
Computes and returns phase angle, in degrees, given the positions of the observer and illuminator.
QString name () const
Gets the shape name.
void setHasIntersection (bool b)
Sets the flag to indicate whether this ShapeModel has an intersection.
virtual void setSurfacePoint (const SurfacePoint &surfacePoint)
Set surface intersection point.
virtual std::vector< double > normal ()
Returns the surface normal at the current intersection point.
virtual std::vector< double > localNormal ()
Returns the local surface normal at the current intersection point.
Protected Member Functions
void setNormal (const std::vector< double >)
Sets the surface normal for the currect intersection point.
void setNormal (const double a, const double b, const double c)
Sets the surface normal for the currect intersection point.
void setLocalNormal (const std::vector< double >)
Sets the local normal for the currect intersection point.
void setLocalNormal (const double a, const double b, const double c)
Sets the local normal for the currect intersection point.
void setName (QString name)
Sets the shape name.
void calculateEllipsoidalSurfaceNormal ()
Calculates the ellipsoidal surface normal.
bool hasEllipsoidIntersection ()
Returns the status of the ellipsoid model intersection.
bool intersectEllipsoid (const std::vector< double > observerPosRelativeToTarget, const std::vector< double > &observerLookVectorToTarget)
Finds the intersection point on the ellipsoid model using the given position of the observer (spacecraft) and direction vector from the observer to the target (body).
bool hasValidTarget () const
Returns the status of the target.
std::vector< Distance > targetRadii () const
Returns the radii of the body in km.
void setHasNormal (bool status)
Sets the flag to indicate whether this ShapeModel has a surface normal.
void setHasLocalNormal (bool status)
Sets the flag to indicate whether this ShapeModel has a local normal.
double resolution ()
Convenience method to get pixel resolution (m/pix) at current intersection point.
Detailed Description
General purpose Embree ray tracing model.
Author
2017-04-22 Jesse Mapel and Jeannie Backer
Constructor & Destructor Documentation
EmbreeShapeModel() [1/3]
Isis::EmbreeShapeModel::EmbreeShapeModel ()
Default constructor sets type to a TIN.
References Isis::ShapeModel::setName().
EmbreeShapeModel() [2/3]
Isis::EmbreeShapeModel::EmbreeShapeModel (Target * target, Pvl & pvl, EmbreeTargetManager * targetManager)
Constructor provided for instantiation from an ISIS cube.
This constructor is typically used for and ISIS cube that has been initialized by spiceinit. The target shape file will be read from the Pvl label.
Parameters
target Target object describing the observed body
pvl ISIS Cube label. The target shape file will be extracted from the Kernels group
targetManager The target shape manager that will manage the target shape
References _FILEINFO_, Isis::EmbreeTargetManager::create(), Isis::PvlObject::findGroup(), Isis::PvlContainer::hasKeyword(), Isis::ShapeModel::setName(), Isis::PvlObject::Traverse, and Isis::IException::User.
EmbreeShapeModel() [3/3]
Isis::EmbreeShapeModel::EmbreeShapeModel (Target * target, const QString & shapefile, EmbreeTargetManager * targetManager)
Constructor provided for instantiation from a file.
Parameters
target Target object describing the observed body
shapefile The targe shape file to use
targetManager The target shape manager that will manage the target shape
References _FILEINFO_, Isis::EmbreeTargetManager::create(), Isis::ShapeModel::setName(), and Isis::IException::User.
~EmbreeShapeModel()
Isis::EmbreeShapeModel::~EmbreeShapeModel () virtual
Destructor that notifies the target shape manager that the target shape is no longer in use.
See also
EmbreeTargetManager::free
References Isis::EmbreeTargetManager::free().
Member Function Documentation
calculateDefaultNormal()
void Isis::EmbreeShapeModel::calculateDefaultNormal () virtual
Return the surface normal of the ellipsoid as the default.
Implements Isis::ShapeModel.
References calculateSurfaceNormal().
Referenced by incidenceAngle().
calculateEllipsoidalSurfaceNormal()
void Isis::ShapeModel::calculateEllipsoidalSurfaceNormal () protected inherited
Calculates the ellipsoidal surface normal.
References _FILEINFO_.
calculateLocalNormal()
void Isis::EmbreeShapeModel::calculateLocalNormal (QVector< double * > neighborPoints) virtual
Compute the normal for a local region of surface points.
This method will calculate the surface normal of an assumed very local region of points. This method is provided to fullfil the specs of the ShapeModel class but this approach is not the most efficent means to accomplish this for a pre-exising intercept point. See setLocalNormalFromIntercept() for this.
The ShapeModel class makes the assumption that the four pixel corners of the center intercept point forms a plane from which a surface normal can be computed. For the Naif DSK plate model, we have already identified the plate (see m_intercept) from the DSK plate model (m_model) of the intercept point that provides it directly. That is what setLocalNormalFromIntercept() provides.
So, this implementation will compute the centroid of the neighboring points and make a determination if it intercepts the current intercept plate as defined by m_intercept - if it is valid. If it does not exist or does not intercept the plate, a new intercept point is computed and returned here.
Author
2017-03-27 Kris Becker
Parameters
neighborPoints Input body-fixed points to compute normal for
Implements Isis::ShapeModel.
References _FILEINFO_, Isis::ShapeModel::hasIntersection(), and Isis::IException::Programmer.
calculateSurfaceNormal()
void Isis::EmbreeShapeModel::calculateSurfaceNormal () virtual
Return the surface normal of the ellipsoid.
Implements Isis::ShapeModel.
References ellipsoidNormal(), and Isis::ShapeModel::setNormal().
Referenced by calculateDefaultNormal().
clearSurfacePoint()
void Isis::EmbreeShapeModel::clearSurfacePoint () virtual
Flag that the ShapeModel does not have a surface point or normal.
Note
This does not actually delete the surface point or normal stored by the parent ShapeModel class, it just sets the flags to false.
Reimplemented from Isis::ShapeModel.
References Isis::ShapeModel::clearSurfacePoint(), Isis::ShapeModel::setHasLocalNormal(), and Isis::ShapeModel::setHasNormal().
Referenced by intersectSurface().
ellipsoidNormal()
QVector< double > Isis::EmbreeShapeModel::ellipsoidNormal ()
Compute the true surface normal vector of an ellipsoid.
This routine is used instead of the one provided by the ShapeModel implementation. This is primarly because ShapeModel::calculateEllipsoidalSurfaceNormal() it is only suitable for a spheroid. This implementation is intended for irregular bodies so we expect triaxial ellipsoids.
Author
2017-03-27 Kris Becker
Returns
QVector<double> Normal vector at the intercept point relative to the ellipsoid (not the plate model)
References _FILEINFO_, Isis::NaifStatus::CheckErrors(), Isis::ShapeModel::hasIntersection(), Isis::ShapeModel::hasValidTarget(), Isis::IException::Programmer, Isis::ShapeModel::surfaceIntersection(), Isis::ShapeModel::targetRadii(), and Isis::SurfacePoint::ToNaifArray().
Referenced by calculateSurfaceNormal().
emissionAngle()
double Isis::ShapeModel::emissionAngle (const std::vector< double > & observerBodyFixedPosition) virtual inherited
Computes and returns emission angle, in degrees, given the observer position.
Emission Angle: The angle between the surface normal vector at the intersection point and the vector from the intersection point to the observer (usually the spacecraft). The emission angle varies from 0 degrees when the observer is viewing the sub-spacecraft point (nadir viewing) to 90 degrees when the intercept is tangent to the surface of the target body. Thus, higher values of emission angle indicate more oblique viewing of the target.
Parameters
observerBodyFixedPosition Three dimensional position of the observer, in the coordinate system of the target body.
Returns
The emission angle, in decimal degrees.
Reimplemented in Isis::PlaneShape.
References Isis::RAD2DEG.
Referenced by Isis::CSMCamera::EmissionAngle(), and Isis::Sensor::EmissionAngle().
getTolerance()
double Isis::EmbreeShapeModel::getTolerance () const
Get the tolerance used when checking if the stored surface point is visible.
Returns
double The tolerance in kilometers
See also
isVisibleFrom
Referenced by isVisibleFrom().
hasEllipsoidIntersection()
bool Isis::ShapeModel::hasEllipsoidIntersection () protected inherited
Returns the status of the ellipsoid model intersection.
Returns
bool Indicates whether this shape model has a valid ellipsoid intersection.
hasIntersection()
bool Isis::ShapeModel::hasIntersection () inherited
Returns intersection status.
Returns
bool Indicates whether this ShapeModel has an intersection.
Referenced by Isis::DemShape::calculateDefaultNormal(), Isis::BulletShapeModel::calculateLocalNormal(), Isis::EllipsoidShape::calculateLocalNormal(), calculateLocalNormal(), Isis::NaifDskShape::calculateLocalNormal(), Isis::BulletShapeModel::ellipsoidNormal(), ellipsoidNormal(), Isis::NaifDskShape::ellipsoidNormal(), Isis::Camera::GetLocalNormal(), Isis::Sensor::HasSurfaceIntersection(), Isis::BulletShapeModel::intersectSurface(), Isis::DemShape::intersectSurface(), intersectSurface(), Isis::EquatorialCylindricalShape::intersectSurface(), Isis::CSMCamera::SetGround(), Isis::BulletShapeModel::setLocalNormalFromIntercept(), Isis::NaifDskShape::setLocalNormalFromIntercept(), and Isis::Camera::Slope().
hasLocalNormal()
bool Isis::ShapeModel::hasLocalNormal () const inherited
Returns surface point local normal status.
Returns
Indicates whether this ShapeModel has a surface normal.
Referenced by Isis::Camera::GetLocalNormal().
hasNormal()
bool Isis::ShapeModel::hasNormal () const inherited
Returns surface point normal status.
Returns
Indicates whether this ShapeModel has a surface normal.
Referenced by incidenceAngle(), and Isis::Camera::Slope().
hasValidTarget()
bool Isis::ShapeModel::hasValidTarget () const protected inherited
Returns the status of the target.
If it is NULL, this method returns false.
Returns
Indicates whether the target is valid.
Referenced by Isis::BulletShapeModel::ellipsoidNormal(), ellipsoidNormal(), and Isis::NaifDskShape::ellipsoidNormal().
incidenceAngle()
double Isis::EmbreeShapeModel::incidenceAngle (const std::vector< double > & illuminatorBodyFixedPosition) virtual
Computes and returns incidence angle, in degrees, given the illuminator position.
The surface normal vector is calculated using an ellipsoid, not the local normal of the actual target shape.
Incidence Angle: The angle between the surface normal vector at the intersection point and the vector from the intersection point to the illuminator (usually the sun).
Note: this method does not use the surface model.
Parameters
illuminatorBodyFixedPosition Three dimensional position for the illuminator, in the body-fixed coordinate system.
Returns
double Incidence angle, in degrees.
Reimplemented from Isis::ShapeModel.
References calculateDefaultNormal(), Isis::ShapeModel::hasNormal(), Isis::ShapeModel::incidenceAngle(), Isis::ShapeModel::localNormal(), Isis::ShapeModel::normal(), and Isis::ShapeModel::setNormal().
Initialize()
void Isis::ShapeModel::Initialize () inherited
Initializes the ShapeModel private variables.
intersectEllipsoid()
bool Isis::ShapeModel::intersectEllipsoid (const std::vector< double > observerBodyFixedPosition, const std::vector< double > & observerLookVectorToTarget) protected inherited
Finds the intersection point on the ellipsoid model using the given position of the observer (spacecraft) and direction vector from the observer to the target (body).
Parameters
observerBodyFixedPosition Three dimensional position of the observer, in the coordinate system of the target body.
observerLookVectorToTarget Three dimensional direction vector from the observer to the target.
Returns
bool Indicates whether this shape model found a valid ellipsoid intersection.
Referenced by Isis::DemShape::intersectSurface(), and Isis::EllipsoidShape::intersectSurface().
intersectSurface() [1/3]
bool Isis::EmbreeShapeModel::intersectSurface (const Latitude & lat, const Longitude & lon, const std::vector< double > & observerPos, const bool & backCheck = true) virtual
Compute intersection of surface vector direction from observer with occulusion.
This method computes a surface intersection point at a given latitude and longitude. All surface points at that latitude and longitude are collected and then the intersect that is non-occluded and closest to the observer is saved. The unit surface normal is also saved.
If occlusion is not checked, then the closest intersection to the observer is saved along with the unit surface normal.
Parameters
lat The latitude of the surface intersection
lon The longitude of the surface intersection
observerPos The position of the observer for occlusion checks
backCheck If occlusion should be checked
Returns
bool If an intersection was found
Reimplemented from Isis::ShapeModel.
References clearSurfacePoint(), Isis::ShapeModel::hasIntersection(), Isis::RTCOcclusionRay::ignorePrimID, Isis::EmbreeTargetShape::intersectRay(), Isis::EmbreeTargetShape::isOccluded(), Isis::RTCMultiHitRay::lastHit, Isis::LinearAlgebra::magnitude(), Isis::LinearAlgebra::normalize(), and Isis::LinearAlgebra::vector().
intersectSurface() [2/3]
bool Isis::EmbreeShapeModel::intersectSurface (const SurfacePoint & surfpt, const std::vector< double > & observerPos, const bool & backCheck = true) virtual
Compute intersection of surface point from observer with occulusion.
Compute the intersection point closest to a surface point. If occlusion is checked, then the intersection that is both closest to the surface point and non-occluded is saved. If occlusion is not checked, then the intersection closest to the surface point is saved.
The unit surface normal is also saved when an intersection is saved.
Parameters
surfpt Surface intercept point
observerPos Observer to check occlusion
backCheck If occlusion should be checked
Returns
bool If an intersection was found
Reimplemented from Isis::ShapeModel.
References clearSurfacePoint(), Isis::ShapeModel::hasIntersection(), Isis::RTCOcclusionRay::ignorePrimID, Isis::EmbreeTargetShape::intersectRay(), Isis::EmbreeTargetShape::isOccluded(), Isis::RTCMultiHitRay::lastHit, Isis::LinearAlgebra::magnitude(), Isis::LinearAlgebra::normalize(), Isis::SurfacePoint::ToNaifArray(), and Isis::LinearAlgebra::vector().
intersectSurface() [3/3]
bool Isis::EmbreeShapeModel::intersectSurface (std::vector< double > observerPos, std::vector< double > lookDirection) virtual
This method computes an intercept point given an observer location and look direction using the Embree model.
This also saves the surface normal.
Parameters
observerPos Position of observer in body-fixed kilometers
lookDirection Unit look direction from the observer
Returns
bool If an intercept was found
Implements Isis::ShapeModel.
References clearSurfacePoint(), Isis::EmbreeTargetShape::getHitInformation(), Isis::ShapeModel::hasIntersection(), Isis::EmbreeTargetShape::intersectRay(), Isis::RTCMultiHitRay::lastHit, and Isis::ShapeModel::setHasIntersection().
isDEM()
bool Isis::EmbreeShapeModel::isDEM () const virtual
Indicates that this shape model is not from a DEM.
Since this method returns false for this class, the Camera class will not calculate the local normal using neighbor points.
Returns
bool Indicates that this is not a DEM shape model.
Implements Isis::ShapeModel.
isVisibleFrom()
bool Isis::EmbreeShapeModel::isVisibleFrom (const std::vector< double > observerPos, const std::vector< double > lookDirection) virtual
Check if the current internalized surface point is visible from an observer position and look direction.
A new intersection is calculated using the observer and look direction. If, the distance between the surface point and new intersection is less than the tolerance, then the surface point is considered to be visible.
Parameters
observerPos The position of the observer
lookDirection The look direction of the observer
Reimplemented from Isis::ShapeModel.
References Isis::EmbreeTargetShape::getHitInformation(), getTolerance(), Isis::RayHitInformation::intersection, Isis::EmbreeTargetShape::intersectRay(), Isis::RTCMultiHitRay::lastHit, Isis::LinearAlgebra::magnitude(), Isis::ShapeModel::surfaceIntersection(), Isis::SurfacePoint::ToNaifArray(), and Isis::LinearAlgebra::vector().
localNormal()
std::vector< double > Isis::ShapeModel::localNormal () virtual inherited
Returns the local surface normal at the current intersection point.
Note: This method will throw an error if the normal doesn't exist. Use the hasLocalNormal() method to verify before calling this method.
See also
hasLocalNormal()
Returns
A local surface normal vector, if it exists.
References _FILEINFO_.
Referenced by Isis::EllipsoidShape::calculateSurfaceNormal(), Isis::Camera::GetLocalNormal(), and incidenceAngle().
localRadius()
Distance Isis::EmbreeShapeModel::localRadius (const Latitude & lat, const Longitude & lon) virtual
Determine radius at a given lat/lon grid point.
@NOTE this call does not update the internal state of the intercept point. Use intersectSurface(lat, lon) for that.
Parameters
lat Latitude coordinate of grid point
lon Longitude coordinate of grid point
Returns
Distance Radius value of the intercept grid point
Implements Isis::ShapeModel.
References Isis::EmbreeTargetShape::getHitInformation(), Isis::RayHitInformation::intersection, Isis::EmbreeTargetShape::intersectRay(), Isis::Distance::Kilometers, Isis::RTCMultiHitRay::lastHit, and Isis::LinearAlgebra::magnitude().
name()
QString Isis::ShapeModel::name () const inherited
Gets the shape name.
Returns
QString The name of the ShapeModel.
Referenced by Isis::UniversalGroundMap::GroundRange(), Isis::VimsGroundMap::SetGround(), Isis::Camera::SetGround(), and Isis::CSMCamera::SetGround().
normal()
std::vector< double > Isis::ShapeModel::normal () virtual inherited
Returns the surface normal at the current intersection point.
Note: This method will throw an error if the normal doesn't exist. Use the hasNormal() method to verify before calling this method.
See also
hasNormal()
Returns
A surface normal vector, if it exists.
References _FILEINFO_.
Referenced by Isis::DemShape::calculateDefaultNormal(), Isis::DemShape::calculateLocalNormal(), Isis::EllipsoidShape::calculateLocalNormal(), incidenceAngle(), Isis::BulletShapeModel::setLocalNormalFromIntercept(), and Isis::Camera::Slope().
phaseAngle()
double Isis::ShapeModel::phaseAngle (const std::vector< double > & observerBodyFixedPosition, const std::vector< double > & illuminatorBodyFixedPosition) virtual inherited
Computes and returns phase angle, in degrees, given the positions of the observer and illuminator.
Phase Angle: The angle between the vector from the intersection point to the observer (usually the spacecraft) and the vector from the intersection point to the illuminator (usually the sun).
Parameters
observerBodyFixedPosition Three dimensional position of the observer, in the coordinate system of the target body.
illuminatorBodyFixedPosition Three dimensional position for the illuminator, in the body-fixed coordinate system.
Returns
double Phase angle, in degrees.
References Isis::RAD2DEG.
Referenced by Isis::CSMCamera::PhaseAngle().
resolution()
double Isis::ShapeModel::resolution () protected inherited
Convenience method to get pixel resolution (m/pix) at current intersection point.
Returns
@double The pixel resolution at the surface intersection.
References _FILEINFO_.
Referenced by Isis::DemShape::intersectSurface().
setHasIntersection()
void Isis::ShapeModel::setHasIntersection (bool b) inherited
Sets the flag to indicate whether this ShapeModel has an intersection.
Parameters
b Indicates whether there is an intersection.
Referenced by Isis::DemShape::intersectSurface(), intersectSurface(), Isis::EquatorialCylindricalShape::intersectSurface(), Isis::PlaneShape::intersectSurface(), Isis::CSMCamera::SetGround(), Isis::CSMCamera::SetImage(), Isis::Sensor::SetLookDirection(), and Isis::CSMCamera::SetLookDirection().
setHasLocalNormal()
void Isis::ShapeModel::setHasLocalNormal (bool status) protected inherited
Sets the flag to indicate whether this ShapeModel has a local normal.
Parameters
status Indicates whether there is a normal.
Referenced by Isis::DemShape::calculateLocalNormal(), Isis::EllipsoidShape::calculateLocalNormal(), and clearSurfacePoint().
setHasNormal()
void Isis::ShapeModel::setHasNormal (bool status) protected inherited
Sets the flag to indicate whether this ShapeModel has a surface normal.
Parameters
status Indicates whether there is a normal.
Referenced by Isis::DemShape::calculateDefaultNormal(), and clearSurfacePoint().
setLocalNormal() [1/2]
void Isis::ShapeModel::setLocalNormal (const double a, const double b, const double c) protected inherited
Sets the local normal for the currect intersection point.
Note: This method will throw an error if this ShapeModel doesn't have and intersection. Use the hasIntersection() method to verify before calling this method.
See also
hasIntersection()
Parameters
a First coordinate value for the three dimensional local normal.
b Second coordinate value for the three dimensional local normal.
c Third coordinate value for the three dimensional local normal.
References _FILEINFO_.
setLocalNormal() [2/2]
void Isis::ShapeModel::setLocalNormal (const std::vector< double > normal) protected inherited
Sets the local normal for the currect intersection point.
Note: This method will throw an error if this ShapeModel doesn't have an intersection. Use the hasIntersection() method to verify before calling this method.
See also
hasIntersection()
Parameters
normal Three dimensional local normal vector.
References _FILEINFO_.
Referenced by Isis::DemShape::calculateLocalNormal(), Isis::EllipsoidShape::calculateLocalNormal(), Isis::BulletShapeModel::setLocalNormalFromIntercept(), and Isis::NaifDskShape::setLocalNormalFromIntercept().
setName()
void Isis::ShapeModel::setName (QString name) protected inherited
Sets the shape name.
Parameters
name The name of the ShapeModel.
Referenced by Isis::BulletShapeModel::BulletShapeModel(), Isis::DemShape::DemShape(), Isis::EllipsoidShape::EllipsoidShape(), EmbreeShapeModel(), Isis::EquatorialCylindricalShape::EquatorialCylindricalShape(), Isis::NaifDskShape::NaifDskShape(), and Isis::PlaneShape::PlaneShape().
setNormal() [1/2]
void Isis::ShapeModel::setNormal (const double a, const double b, const double c) protected inherited
Sets the surface normal for the currect intersection point.
Note: This method will throw an error if this ShapeModel doesn't have and intersection. Use the hasIntersection() method to verify before calling this method.
See also
hasIntersection()
Parameters
a First coordinate value for the three dimensional surface normal.
b Second coordinate value for the three dimensional surface normal.
c Third coordinate value for the three dimensional surface normal.
References _FILEINFO_.
setNormal() [2/2]
void Isis::ShapeModel::setNormal (const std::vector< double > normal) protected inherited
Sets the surface normal for the currect intersection point.
Note: This method will throw an error if this ShapeModel doesn't have an intersection. Use the hasIntersection() method to verify before calling this method.
See also
hasIntersection()
Parameters
normal Three dimensional surface normal vector.
References _FILEINFO_.
Referenced by Isis::DemShape::calculateDefaultNormal(), Isis::BulletShapeModel::calculateSurfaceNormal(), Isis::EllipsoidShape::calculateSurfaceNormal(), calculateSurfaceNormal(), Isis::NaifDskShape::calculateSurfaceNormal(), incidenceAngle(), and Isis::PlaneShape::intersectSurface().
setSurfacePoint()
void Isis::ShapeModel::setSurfacePoint (const SurfacePoint & surfacePoint) virtual inherited
Set surface intersection point.
Parameters
surfacePoint Position coordinate for the surface point.
Reimplemented in Isis::BulletShapeModel.
Referenced by Isis::NaifDskShape::intersectSurface(), and Isis::RadarGroundMap::SetGround().
setTolerance()
void Isis::EmbreeShapeModel::setTolerance (const double & tolerance)
Set the tolerance used when checking if the stored surface point is visible.
Parameters
tolerance The new tolerance in kilometers
See also
isVisibleFrom
Referenced by Isis::ShapeModelFactory::create().
surfaceIntersection()
SurfacePoint * Isis::ShapeModel::surfaceIntersection () const virtual inherited
Returns the surface intersection for this ShapeModel.
Returns
SurfacePoint Three dimensional position for the surface intersection, in body-fixed coordinate system.
Referenced by Isis::DemShape::calculateDefaultNormal(), Isis::DemShape::calculateLocalNormal(), Isis::EllipsoidShape::calculateLocalNormal(), Isis::Sensor::Coordinate(), Isis::BulletShapeModel::ellipsoidNormal(), ellipsoidNormal(), Isis::NaifDskShape::ellipsoidNormal(), Isis::PlaneShape::emissionAngle(), Isis::Sensor::GetLatitude(), Isis::Sensor::GetLongitude(), Isis::Sensor::GetSurfacePoint(), Isis::PlaneShape::incidenceAngle(), Isis::DemShape::intersectSurface(), Isis::EquatorialCylindricalShape::intersectSurface(), Isis::PlaneShape::intersectSurface(), isVisibleFrom(), Isis::Sensor::LocalRadius(), Isis::PlaneShape::localRadius(), Isis::Sensor::SlantDistance(), and Isis::Sensor::SolarDistance().
targetRadii()
std::vector< Distance > Isis::ShapeModel::targetRadii () const protected inherited
Returns the radii of the body in km.
The radii are obtained from the target. Note: This method will throw an error if the ShapeModel does not have a valid target. Use the hasValidTarget() method to verify before calling this method.
See also
hasValidTarget()
Returns
Three dimensional vector containing the ellipsoid radii values.
References _FILEINFO_.
Referenced by Isis::DemShape::calculateDefaultNormal(), Isis::EllipsoidShape::calculateLocalNormal(), Isis::BulletShapeModel::ellipsoidNormal(), ellipsoidNormal(), Isis::NaifDskShape::ellipsoidNormal(), Isis::EquatorialCylindricalShape::intersectSurface(), and Isis::EllipsoidShape::localRadius().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/EmbreeShapeModel/EmbreeShapeModel.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/EmbreeShapeModel/EmbreeShapeModel.cpp