Isis Developer Reference: Isis::Environment Class Reference
Isis::Environment Class Reference
#include <Environment.h>
Public Member Functions
~Environment ()
Static Public Member Functions
static QString userName ()
@Returns the user name.
static QString hostName ()
static QString isisVersion ()
static QString getEnvironmentValue (QString, QString)
Protected Member Functions
Environment ()
Detailed Description
Author
2011-04-01 Eric Hyer & Steven Lambright
Constructor & Destructor Documentation
~Environment()
Isis::Environment::~Environment () inline
Environment()
Isis::Environment::Environment () protected
References getEnvironmentValue(), and Isis::IString::ToQt().
Member Function Documentation
getEnvironmentValue()
QString Isis::Environment::getEnvironmentValue (QString variable, QString defaultValue) static
Parameters
variable The environment variable to get
defaultValue The returned value for variable if variable doesn't exist.
Returns
The value for the environment variable requested.
Referenced by Environment(), hostName(), QStartup(), and userName().
hostName()
QString Isis::Environment::hostName () static
Returns
the host name. Returns 'Unknown' if it cannot find the host name.
References getEnvironmentValue().
isisVersion()
QString Isis::Environment::isisVersion () static
Returns
the Isis version in the format isis?.?.?.?qualifier | date
References _FILEINFO_, Isis::TextFile::GetLine(), and Isis::IException::Programmer.
userName()
QString Isis::Environment::userName () static
@Returns the user name.
Returns 'Unknown' if it cannot find the user name.
References getEnvironmentValue().
Referenced by Isis::Project::clear(), and Isis::Project::Project().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Environment/Environment.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Environment/Environment.cpp