Isis Developer Reference: Isis::Selection Class Reference
Isis::Selection Class Reference abstract
Pure Virtual Parent Class for all Selection classes.
#include <Selection.h>
Public Member Functions
Selection ()
virtual ~Selection ()
virtual int select (Chip *inputChip, Chip *selectionChip)=0
virtual int elipticalReduction (Chip *selectionChip, double percent_selected, double play, int patience_limit)
int centerOfMass (Chip *selectionChip, double *sample, double *line)
int centerOfMassWeighted (Chip *inputChip, Chip *selectionChip, double *sample, double *line)
bool ellipseFrom5Pts (Ellipse *ell, double pts[5][2])
double elipsePercentSelected (Chip *selectionChip, Ellipse *ell)
std::vector< double > minimumBoundingElipse (std::vector< std::vector< int > > pts, Ellipse *ell)
bool ellipseFromCubic (Ellipse *ell, double cubic[6])
bool ellipseAxesAreaFromMatrix (Ellipse *ell)
bool bestFitEllipse (Ellipse *ell, std::vector< std::vector< int > > *pts, double play, unsigned int max_iter)
bool pointInEllipse (Ellipse *ell, double pt[2], double play)
bool ellipseInChip (Ellipse *ell, Chip *chip)
bool ellipseFromCenterAxesAngle (Ellipse *ell, double centerSample, double centerLine, double semiMajor, double semiMinor, double theta)
void selectionEdge (Chip *selectionChip, std::vector< std::vector< int > > *pts)
Detailed Description
Pure Virtual Parent Class for all Selection classes.
Create Selection object. Because this is a pure virtual class you can not create a Selection class directly.
Author
2011-10-12 Orrin Thomas
Constructor & Destructor Documentation
Selection()
Isis::Selection::Selection ()
~Selection()
Isis::Selection::~Selection () virtual
Member Function Documentation
bestFitEllipse()
bool Isis::Selection::bestFitEllipse (Ellipse * ell, std::vector< std::vector< int > > * pts, double play, unsigned int max_iter)
References Ellipse::A, Ellipse::cen, Isis::choleski_solve(), and Isis::isymp().
centerOfMass()
int Isis::Selection::centerOfMass (Chip * selectionChip, double * sample, double * line)
References Isis::Chip::GetValue(), Isis::Chip::Lines(), and Isis::Chip::Samples().
centerOfMassWeighted()
int Isis::Selection::centerOfMassWeighted (Chip * inputChip, Chip * selectionChip, double * sample, double * line)
References Isis::Chip::GetValue(), Isis::Chip::Lines(), and Isis::Chip::Samples().
elipsePercentSelected()
double Isis::Selection::elipsePercentSelected (Chip * selectionChip, Ellipse * ell)
References Isis::Chip::GetValue(), Isis::Chip::Lines(), and Isis::Chip::Samples().
elipticalReduction()
int Isis::Selection::elipticalReduction (Chip * selectionChip, double percent_selected, double play, int patience_limit) virtual
Reimplemented in Isis::CentroidApolloPan.
References Ellipse::A, Ellipse::area, Ellipse::cen, Isis::Chip::Lines(), Ellipse::majorAxis, Ellipse::minorAxis, Isis::Chip::Samples(), Ellipse::semiMajor, Ellipse::semiMinor, and Isis::Chip::SetValue().
ellipseAxesAreaFromMatrix()
bool Isis::Selection::ellipseAxesAreaFromMatrix (Ellipse * ell)
References Ellipse::A, Ellipse::area, Ellipse::majorAxis, Ellipse::minorAxis, Ellipse::semiMajor, and Ellipse::semiMinor.
ellipseFrom5Pts()
bool Isis::Selection::ellipseFrom5Pts (Ellipse * ell, double pts[5][2])
ellipseFromCenterAxesAngle()
bool Isis::Selection::ellipseFromCenterAxesAngle (Ellipse * ell, double centerSample, double centerLine, double semiMajor, double semiMinor, double theta)
References Ellipse::A, Ellipse::area, Ellipse::cen, Ellipse::majorAxis, Ellipse::minorAxis, Ellipse::semiMajor, and Ellipse::semiMinor.
ellipseFromCubic()
bool Isis::Selection::ellipseFromCubic (Ellipse * ell, double cubic[6])
References Ellipse::A, and Ellipse::cen.
ellipseInChip()
bool Isis::Selection::ellipseInChip (Ellipse * ell, Chip * chip)
References Ellipse::cen, Isis::Chip::Lines(), Ellipse::majorAxis, Isis::Chip::Samples(), Ellipse::semiMajor, and Ellipse::semiMinor.
minimumBoundingElipse()
std::vector< double > Isis::Selection::minimumBoundingElipse (std::vector< std::vector< int > > pts, Ellipse * ell)
References Ellipse::A, and Ellipse::cen.
pointInEllipse()
bool Isis::Selection::pointInEllipse (Ellipse * ell, double pt[2], double play)
References Ellipse::A, and Ellipse::cen.
select()
virtual int Isis::Selection::select (Chip * inputChip, Chip * selectionChip) pure virtual
Implemented in Isis::Centroid.
selectionEdge()
void Isis::Selection::selectionEdge (Chip * selectionChip, std::vector< std::vector< int > > * pts)
References Isis::Chip::GetValue(), Isis::Chip::Lines(), and Isis::Chip::Samples().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Selection/Selection.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Selection/Selection.cpp