Isis Developer Reference: Isis::ControlPoint Class Reference
Isis::ControlPoint Class Reference
A single control point.
#include <ControlPoint.h>
Classes
struct RadiusSource
struct SurfacePointSource
Public Types
enum PointType { Fixed = 0 , Constrained = 1 , Free = 2 }
These are the valid 'types' of point.
enum Status { Failure , Success , PointLocked }
This is a return status for many of the mutating (setter) method calls.
enum ConstraintStatus { Coord1Constrained = 0 , Coord2Constrained = 1 , Coord3Constrained = 2 }
This is a convenience member for checking number of constrained coordinates in the SurfacePoint.
enum ModType { EditLockModified , IgnoredModified , TypeModified }
Control Point Modification Types.
Public Member Functions
ControlPoint ()
Construct a control point.
ControlPoint (const ControlPoint &)
Copy the given control point into this instance.
ControlPoint (const QString &id)
Construct a control point with given Id.
virtual ~ControlPoint ()
This destroys the current instance and cleans up any and all allocated memory.
ControlNet * Parent ()
void Load (PvlObject &p)
Loads the PvlObject into a ControlPoint.
void Add (ControlMeasure *measure)
Add a measurement to the control point, taking ownership of the measure in the process.
int Delete (ControlMeasure *measure)
Remove a measurement from the control point, deleting reference measure is allowed.
int Delete (QString serialNumber)
Remove a measurement from the control point, deleting reference measure is allowed.
int Delete (int index)
Remove a measurement from the control point, deleting reference measure is allowed.
Status ResetApriori ()
Reset all the Apriori info to defaults.
const ControlMeasure * GetMeasure (QString serialNumber) const
Get a control measure based on its cube's serial number.
ControlMeasure * GetMeasure (QString serialNumber)
Get a control measure based on its cube's serial number.
const ControlMeasure * GetMeasure (int index) const
ControlMeasure * GetMeasure (int index)
bool HasRefMeasure () const
Checks to see if a reference measure is set.
const ControlMeasure * GetRefMeasure () const
Get the reference control measure.
ControlMeasure * GetRefMeasure ()
Get the measure that is the reference directly.
Status SetChooserName (QString name)
Set the point's chooser name.
Status SetDateTime (QString newDateTime)
Set the point's last modified time.
Status SetEditLock (bool editLock)
Set the EditLock state.
Status SetId (QString id)
Sets the Id of the control point.
Status SetRefMeasure (ControlMeasure *cm)
Set the point's reference measure.
Status SetRefMeasure (int index)
Set the point's reference measure.
Status SetRefMeasure (QString sn)
Set the points reference measure.
Status SetRejected (bool rejected)
Set the jigsawRejected state.
Status SetIgnored (bool newIgnoreStatus)
Set whether to ignore or use control point.
Status SetAdjustedSurfacePoint (SurfacePoint newSurfacePoint)
Set or update the surface point relating to this control point.
Status SetType (PointType newType)
Updates the control point's type.
Status SetAprioriRadiusSource (RadiusSource::Source source)
This updates the source of the radius of the apriori surface point.
Status SetAprioriRadiusSourceFile (QString sourceFile)
This updates the filename of the DEM that the apriori radius came from.
Status SetAprioriSurfacePoint (SurfacePoint aprioriSP)
This updates the apriori surface point.
Status SetAprioriSurfacePointSource (SurfacePointSource::Source source)
This updates the source of the surface point.
Status SetAprioriSurfacePointSourceFile (QString sourceFile)
This updates the filename of where the apriori surface point came from.
Status ComputeApriori ()
Computes a priori lat/lon/radius point coordinates by determining the average lat/lon/radius of all measures.
Status ComputeResiduals ()
This method computes the BundleAdjust residuals for a point.
Status ComputeResiduals_Millimeters ()
This method computes the residuals for a point.
SurfacePoint GetAdjustedSurfacePoint () const
SurfacePoint GetBestSurfacePoint () const
Returns the adjusted surface point if it exists, otherwise returns the a priori surface point.
QString GetChooserName () const
QString GetDateTime () const
bool IsEditLocked () const
bool IsRejected () const
QString GetId () const
Return the Id of the control point.
bool IsIgnored () const
bool IsValid () const
bool IsInvalid () const
bool IsFree () const
Return bool indicating if point is Free or not.
bool IsFixed () const
Return bool indicating if point is Fixed or not.
bool HasAprioriCoordinates ()
bool IsConstrained ()
Return bool indicating if point is Constrained or not.
bool IsCoord1Constrained ()
Return bool indicating if 1st coordinate is Constrained or not.
bool IsCoord2Constrained ()
Return bool indicating if 2nd coordinate is Constrained or not.
bool IsCoord3Constrained ()
Return bool indicating if 3rd coordinate is Constrained or not.
int NumberOfConstrainedCoordinates ()
Return bool indicating if point is Constrained or not.
QString GetPointTypeString () const
Obtain a string representation of the PointType.
PointType GetType () const
QString GetRadiusSourceString () const
Obtain a string representation of the RadiusSource.
QString GetSurfacePointSourceString () const
Obtain a string representation of the SurfacePointSource.
SurfacePoint GetAprioriSurfacePoint () const
RadiusSource::Source GetAprioriRadiusSource () const
bool HasAprioriRadiusSourceFile () const
Checks to see if the radius source file has been set.
QString GetAprioriRadiusSourceFile () const
SurfacePointSource::Source GetAprioriSurfacePointSource () const
bool HasAprioriSurfacePointSourceFile () const
Checks to see if the surface point source file has been set.
QString GetAprioriSurfacePointSourceFile () const
int GetNumMeasures () const
int GetNumValidMeasures () const
int GetNumLockedMeasures () const
Returns the number of locked control measures.
bool HasSerialNumber (QString serialNumber) const
Return true if given serial number exists in point.
bool HasChooserName () const
Returns true if the choosername is not empty.
bool HasDateTime () const
Returns true if the datetime is not empty.
int IndexOf (ControlMeasure *, bool throws=true) const
int IndexOf (QString sn, bool throws=true) const
int IndexOfRefMeasure () const
bool IsReferenceExplicit () const
QString GetReferenceSN () const
void emitMeasureModified (ControlMeasure *measure, ControlMeasure::ModType modType, QVariant oldValue, QVariant newValue)
This method is a wrapper to emit the measureModified() signal in the parent network is called whenever a change is made to a Control Measure.
Statistics GetStatistic (double(ControlMeasure::*statFunc)() const) const
This function will call a given method on every control measure that this point has.
Statistics GetStatistic (long dataType) const
QList< ControlMeasure * > getMeasures (bool excludeIgnored=false) const
QList< QString > getCubeSerialNumbers () const
const ControlMeasure * operator[] (QString serialNumber) const
Same as GetMeasure (provided for convenience)
ControlMeasure * operator[] (QString serialNumber)
Same as GetMeasure (provided for convenience)
const ControlMeasure * operator[] (int index) const
Same as GetMeasure (provided for convenience)
ControlMeasure * operator[] (int index)
Same as GetMeasure (provided for convenience)
bool operator!= (const ControlPoint &pPoint) const
Compare two Control Points for inequality.
bool operator== (const ControlPoint &pPoint) const
Compare two Control Points for equality.
const ControlPoint & operator= (const ControlPoint &pPoint)
void ZeroNumberOfRejectedMeasures ()
Initialize the number of rejected measures to 0.
void SetNumberOfRejectedMeasures (int numRejected)
Set (update) the number of rejected measures for the control point.
int GetNumberOfRejectedMeasures () const
Get the number of rejected measures on the control point.
double GetSampleResidualRms () const
Get rms of sample residuals.
double GetLineResidualRms () const
Get rms of line residuals.
double GetResidualRms () const
Get rms of residuals.
void ClearJigsawRejected ()
Set jigsaw rejected flag for all measures to false and set the jigsaw rejected flag for the point itself to false.
Static Public Member Functions
static QString PointTypeToString (PointType type)
Obtain a string representation of a given PointType.
static PointType StringToPointType (QString pointTypeString)
Obtain a PointType given a string representation of it.
static QString RadiusSourceToString (RadiusSource::Source source)
Obtain a string representation of a given RadiusSource.
static RadiusSource::Source StringToRadiusSource (QString str)
Obtain a RadiusSource::Source from a string.
static QString SurfacePointSourceToString (SurfacePointSource::Source source)
Obtain a string representation of a given SurfacePointSource.
static SurfacePointSource::Source StringToSurfacePointSource (QString str)
Obtain a SurfacePoint::Source from a string.
Static Public Attributes
static const int PointTypeCount = 3
Protected Member Functions
void PointModified ()
List of Control Measures.
Protected Attributes
QHash< QString, ControlMeasure * > * measures
Friends
class ControlNet
Detailed Description
A single control point.
A control point is one or more measurements that identify the same feature or location in different images.
Author
2005-07-29 Jeff Anderson
See also
ControlMeasure ControlNet
Member Enumeration Documentation
ConstraintStatus
enum Isis::ControlPoint::ConstraintStatus
This is a convenience member for checking number of constrained coordinates in the SurfacePoint.
Enumerator
Coord1Constrained
Coord2Constrained
Coord3Constrained
ModType
enum Isis::ControlPoint::ModType
Control Point Modification Types.
This enum is designed to represent the different types of modifications that can be made to a ControlPoint.
EditLockModified means that the Control Point had it's edit lock flag changed. IgnoredModified means that the Control Measure had it's ignored flag changed. TypeModified means that the ControlPoint::PointType for this control point was modified.
Enumerator
EditLockModified
IgnoredModified
TypeModified
PointType
enum Isis::ControlPoint::PointType
These are the valid 'types' of point.
A point type defines what a point is tying together.
Enumerator
Fixed
A Fixed point is a Control Point whose lat/lon is well established and should not be changed.
Some people will refer to this as a truth (i.e., ground truth). A fixed point can be identifed in one or more cubes. Historically this point was called a "Ground" point.
Constrained
A Constrained point is a Control Point whose lat/lon/radius is somewhat established and should not be changed.
Free
A Free point is a Control Point that identifies common measurements between two or more cubes.
While it could have a lat/lon, it is not necessarily correct and is subject to change. This is the most common type of control point. This point type floats freely in a bundle adjustment. Historically this point type was called "Tie".
Status
enum Isis::ControlPoint::Status
This is a return status for many of the mutating (setter) method calls.
We chose to use return status' because often times ignoring them is the behavior the caller wants.
Enumerator
Failure
This is returned when an operation cannot be performed due to a problem such as the point is ignored and the operation doesn't make sense.
Success
This is returned when the operation successfully took effect.
PointLocked
This is returned when the operation requires Edit Lock to be false but it is currently true.
The operation did not take effect.
Constructor & Destructor Documentation
ControlPoint() [1/3]
Isis::ControlPoint::ControlPoint ()
Construct a control point.
Author
tsucharski (5/5/2010)
References Free, measures, Isis::ControlPoint::SurfacePointSource::None, and Isis::ControlPoint::RadiusSource::None.
ControlPoint() [2/3]
Isis::ControlPoint::ControlPoint (const ControlPoint & other)
Copy the given control point into this instance.
Parameters
other The control point to duplicate
References GetMeasure(), measures, and SetRefMeasure().
ControlPoint() [3/3]
Isis::ControlPoint::ControlPoint (const QString & newId)
Construct a control point with given Id.
Parameters
id Control Point Id
References Free, measures, Isis::ControlPoint::SurfacePointSource::None, and Isis::ControlPoint::RadiusSource::None.
~ControlPoint()
Isis::ControlPoint::~ControlPoint () virtual
This destroys the current instance and cleans up any and all allocated memory.
References measures.
Member Function Documentation
Add()
void Isis::ControlPoint::Add (ControlMeasure * measure)
Add a measurement to the control point, taking ownership of the measure in the process.
Parameters
measure The ControlMeasure to add
References PointModified().
Referenced by Isis::ControlPointEditWidget::createControlPoint(), Isis::QnetTool::createFixedPoint(), Isis::QnetTool::createPoint(), Isis::StereoTool::createPoint(), and Isis::MatchTool::createPoint().
ClearJigsawRejected()
void Isis::ControlPoint::ClearJigsawRejected ()
Set jigsaw rejected flag for all measures to false and set the jigsaw rejected flag for the point itself to false.
References GetMeasure(), measures, Isis::ControlMeasure::SetRejected(), and SetRejected().
Referenced by Isis::ControlNet::ClearJigsawRejected().
ComputeApriori()
ControlPoint::Status Isis::ControlPoint::ComputeApriori ()
Computes a priori lat/lon/radius point coordinates by determining the average lat/lon/radius of all measures.
Note that this does not change ignored, fixed or constrained points.
Also, it does not use unmeasured or ignored measures when computing lat/lon/radius.
(KLE) Note this not a rigorous triangulation considering outliers. A better way would be to... a) use e.g. a closest approach algorithm to find intersection of all rays, regardless of whether the intersection lies on the surface in question, then; b) perform a rigorous triangulation with some sort outlier detection approach, a robust estimation technique (perhaps RANSAC)
References _FILEINFO_, Isis::ControlPoint::SurfacePointSource::AverageOfMeasures, Isis::ControlPoint::RadiusSource::AverageOfMeasures, Isis::ControlMeasure::Camera(), Isis::Sensor::Coordinate(), Isis::Camera::Csm, Isis::Camera::DistortionMap(), Free, Isis::Camera::GetCameraType(), Isis::ControlMeasure::GetCubeSerialNumber(), GetId(), Isis::ControlMeasure::GetLine(), GetMeasure(), Isis::ControlMeasure::GetSample(), GetType(), IsConstrained(), IsFixed(), Isis::ControlMeasure::IsIgnored(), Isis::Displacement::Kilometers, NumberOfConstrainedCoordinates(), PointModified(), Isis::IException::Programmer, SetAprioriRadiusSource(), SetAprioriSurfacePointSource(), Isis::ControlMeasure::SetFocalPlaneMeasured(), Isis::Camera::SetImage(), Isis::SurfacePoint::SetRectangular(), Success, Isis::CameraDistortionMap::UndistortedFocalPlaneX(), Isis::CameraDistortionMap::UndistortedFocalPlaneY(), Isis::IException::User, and Isis::SurfacePoint::Valid().
Referenced by Isis::ControlNet::ComputeApriori().
ComputeResiduals()
ControlPoint::Status Isis::ControlPoint::ComputeResiduals ()
This method computes the BundleAdjust residuals for a point.
*** Warning: Only BundleAdjust and its applications should be using this method.
History:
2008-07-17 Tracie Sucharski, Added ptid and measure serial number to the unable to map to surface error.
2009-12-06 Tracie Sucharski, Renamed from ComputeErrors
2010-08-05 Tracie Sucharski, Changed lat/lon/radius to x/y/z
2010-12-10 Debbie A. Cook, Revised error calculation for radar because it was always reporting line errors=0.
2011-03-17 Debbie A. Cook, Fixed typo in radar call to get longitude
2011-03-24 Debbie A. Cook, Removed IsMeasured check since it was really checking for Candidate measures.
2011-07-01 Debbie A. Cook, Removed editLock check to allow BundleAdjust to compute residuals for editLocked points
2012-01-18 Debbie A. Cook, Revised to call ComputeResidualsMillimeters() to avoid duplication of code.
2019-05-16 Debbie A. Cook, The calls to CameraGroundMap::GetXY were changed to allow not testing for points on the back side of the planet during bundle adjustment. Now, the instrument coordinates will be calculated and returned always to this method. In the future, a separate diagnostic tool may be helpful to check for non-visable points in a control net AFTER bundle adjustment. References #2591.
References _FILEINFO_, Isis::ControlMeasure::Camera(), ComputeResiduals_Millimeters(), Isis::Camera::Csm, Isis::CameraFocalPlaneMap::DetectorLine(), Isis::CameraFocalPlaneMap::DetectorSample(), Isis::Camera::DistortionMap(), Failure, Isis::Camera::FocalPlaneMap(), Isis::CameraDistortionMap::FocalPlaneX(), Isis::CameraDistortionMap::FocalPlaneY(), Isis::Camera::GetCameraType(), Isis::ControlMeasure::GetCubeSerialNumber(), Isis::ControlMeasure::GetFocalPlaneComputedX(), Isis::ControlMeasure::GetFocalPlaneComputedY(), Isis::ControlMeasure::GetFocalPlaneMeasuredX(), Isis::ControlMeasure::GetFocalPlaneMeasuredY(), GetId(), Isis::ControlMeasure::GetLine(), Isis::ControlMeasure::GetSample(), Isis::Sensor::GetSurfacePoint(), Isis::CameraGroundMap::GetXY(), Isis::Camera::GroundMap(), Isis::ControlMeasure::IsIgnored(), IsIgnored(), measures, PointModified(), Isis::IException::Programmer, Isis::Camera::Radar, Isis::CameraFocalPlaneMap::SetFocalPlane(), Isis::Camera::SetImage(), Isis::ControlMeasure::SetResidual(), Isis::CameraDistortionMap::SetUndistortedFocalPlane(), and Success.
Referenced by Isis::BundleControlPoint::computeResiduals().
ComputeResiduals_Millimeters()
ControlPoint::Status Isis::ControlPoint::ComputeResiduals_Millimeters ()
This method computes the residuals for a point.
History:
2008-07-17 Tracie Sucharski - Added ptid and measure serial number to the unable to map to surface error.
2010-12-06 Tracie Sucharski - Renamed from ComputeErrors
2011-03-19 Debbie A. Cook - Changed to use the Camera classes like ComputeResiduals and get the correct calculations for each camera type.
2011-03-24 Debbie A. Cook - Removed IsMeasured check since it was really checking for Candidate measures.
2012-01-18 Debbie A. Cook - Made radar case the same as other instruments and removed incorrect call to SetResidual, which was setting focal plane residuals in x and y instead of image residuals in sample and line.
References Isis::ControlMeasure::Camera(), Isis::Camera::Csm, Failure, GetAdjustedSurfacePoint(), Isis::Camera::GetCameraType(), Isis::ControlMeasure::GetLine(), Isis::ControlMeasure::GetSample(), Isis::CameraGroundMap::GetXY(), Isis::Camera::GroundMap(), Isis::ControlMeasure::IsIgnored(), IsIgnored(), Isis::Camera::Line(), measures, PointModified(), Isis::Camera::Sample(), Isis::ControlMeasure::SetFocalPlaneComputed(), Isis::Camera::SetGround(), Isis::Camera::SetImage(), and Success.
Referenced by ComputeResiduals().
Delete() [1/3]
int Isis::ControlPoint::Delete (ControlMeasure * measure)
Remove a measurement from the control point, deleting reference measure is allowed.
Parameters
measure The measure to delete
References Isis::ControlMeasure::GetCubeSerialNumber().
Referenced by Delete(), Isis::MatchTool::deletePoint(), Isis::ControlNet::DeletePoint(), Isis::AbstractMeasureItem::deleteSource(), Isis::CnetEditorWidget::filteredNetwork(), and operator=().
Delete() [2/3]
int Isis::ControlPoint::Delete (int index)
Remove a measurement from the control point, deleting reference measure is allowed.
Parameters
index The index of the control measure to delete
References _FILEINFO_, Delete(), and Isis::IException::Programmer.
Delete() [3/3]
int Isis::ControlPoint::Delete (QString serialNumber)
Remove a measurement from the control point, deleting reference measure is allowed.
Parameters
serialNumber The serial number of the measure to delete
References Isis::ControlMeasure::IsEditLocked(), Isis::ControlMeasure::IsIgnored(), IsIgnored(), Isis::ControlMeasure::MeasureLocked, measures, PointModified(), and Isis::ControlMeasure::Success.
emitMeasureModified()
void Isis::ControlPoint::emitMeasureModified (ControlMeasure * measure, ControlMeasure::ModType modType, QVariant oldValue, QVariant newValue)
This method is a wrapper to emit the measureModified() signal in the parent network is called whenever a change is made to a Control Measure.
Parameters
measure The ControlMeasure* that was modified.
type The ControlMeasure::ModType indicating which modification occured.
oldValue The oldValue before the change.
newValue The new value that the change incorporated.
GetAdjustedSurfacePoint()
SurfacePoint Isis::ControlPoint::GetAdjustedSurfacePoint () const
Referenced by Isis::BundleControlPoint::adjustedSurfacePoint(), ComputeResiduals_Millimeters(), Isis::AdjustedLatitudeFilter::evaluate(), Isis::AdjustedLatitudeSigmaFilter::evaluate(), Isis::AdjustedLongitudeFilter::evaluate(), Isis::AdjustedLongitudeSigmaFilter::evaluate(), Isis::AdjustedRadiusFilter::evaluate(), Isis::AdjustedRadiusSigmaFilter::evaluate(), Isis::AdjustedXFilter::evaluate(), Isis::AdjustedXSigmaFilter::evaluate(), Isis::AdjustedYFilter::evaluate(), Isis::AdjustedYSigmaFilter::evaluate(), Isis::AdjustedZFilter::evaluate(), Isis::AdjustedZSigmaFilter::evaluate(), Isis::BundleControlPoint::formatBundleLatitudinalOutputDetailString(), Isis::BundleControlPoint::formatBundleOutputSummaryString(), Isis::BundleControlPoint::formatBundleRectangularOutputDetailString(), Isis::AbstractPointItem::getData(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::AbstractPointItem::setData(), and Isis::ControlNetVersioner::toPvl().
GetAprioriRadiusSource()
ControlPoint::RadiusSource::Source Isis::ControlPoint::GetAprioriRadiusSource () const
Referenced by Isis::ControlNetVersioner::toPvl().
GetAprioriRadiusSourceFile()
QString Isis::ControlPoint::GetAprioriRadiusSourceFile () const
Referenced by Isis::AbstractPointItem::getData(), and Isis::ControlNetVersioner::toPvl().
GetAprioriSurfacePoint()
SurfacePoint Isis::ControlPoint::GetAprioriSurfacePoint () const
Referenced by Isis::APrioriLatitudeFilter::evaluate(), Isis::APrioriLatitudeSigmaFilter::evaluate(), Isis::APrioriLongitudeFilter::evaluate(), Isis::APrioriLongitudeSigmaFilter::evaluate(), Isis::APrioriRadiusFilter::evaluate(), Isis::APrioriRadiusSigmaFilter::evaluate(), Isis::APrioriXFilter::evaluate(), Isis::APrioriXSigmaFilter::evaluate(), Isis::APrioriYFilter::evaluate(), Isis::APrioriYSigmaFilter::evaluate(), Isis::APrioriZFilter::evaluate(), Isis::APrioriZSigmaFilter::evaluate(), Isis::AbstractPointItem::getData(), Isis::PointTableModel::getPointWarningMessage(), Isis::AbstractPointItem::setData(), Isis::BundleControlPoint::setSigmaWeightFromGlobals(), Isis::BundleControlPoint::setWeights(), Isis::ControlNetVersioner::toPvl(), and Isis::QnetTool::updatePointInfo().
GetAprioriSurfacePointSource()
ControlPoint::SurfacePointSource::Source Isis::ControlPoint::GetAprioriSurfacePointSource () const
Referenced by Isis::InterestOperator::FindCnetRef(), and Isis::ControlNetVersioner::toPvl().
GetAprioriSurfacePointSourceFile()
QString Isis::ControlPoint::GetAprioriSurfacePointSourceFile () const
Referenced by Isis::AbstractPointItem::getData(), and Isis::ControlNetVersioner::toPvl().
GetBestSurfacePoint()
SurfacePoint Isis::ControlPoint::GetBestSurfacePoint () const
Returns the adjusted surface point if it exists, otherwise returns the a priori surface point.
References Isis::SurfacePoint::Valid().
Referenced by Isis::QnetPointDistanceFilter::filter(), and Isis::QnetPointRangeFilter::filter().
GetChooserName()
QString Isis::ControlPoint::GetChooserName () const
References Isis::Application::Name(), and Isis::FileName::name().
Referenced by Isis::ChooserNameFilter::evaluate(), Isis::AbstractPointItem::getData(), and Isis::ControlNetVersioner::toPvl().
getCubeSerialNumbers()
QList< QString > Isis::ControlPoint::getCubeSerialNumbers () const
Returns
A list of cube serial numbers
Referenced by Isis::ControlNet::SetImages().
GetDateTime()
QString Isis::ControlPoint::GetDateTime () const
References Isis::Application::DateTime().
Referenced by Isis::AbstractPointItem::getData(), and Isis::ControlNetVersioner::toPvl().
GetId()
QString Isis::ControlPoint::GetId () const
Return the Id of the control point.
Returns
Control Point Id
Referenced by Isis::ControlNetVitals::addPoint(), Isis::ControlNet::AddPoint(), ComputeApriori(), ComputeResiduals(), Isis::ControlPointGraphicsItem::contextMenuEvent(), Isis::ControlPointEditWidget::createControlPoint(), Isis::QnetTool::createFixedPoint(), Isis::QnetTool::createPoint(), Isis::StereoTool::createPoint(), Isis::Directory::deleteControlPoint(), Isis::ControlNetVitals::deletePoint(), Isis::ControlNet::DeletePoint(), Isis::MatchTool::deletePoint(), Isis::StereoTool::deletePoint(), Isis::PointIdFilter::evaluate(), Isis::CnetEditorWidget::filteredNetwork(), Isis::InterestOperator::FindCnetRef(), Isis::ControlNetStatistics::GeneratePointStats(), Isis::AbstractMeasureItem::getData(), Isis::AbstractPointItem::getData(), GetReferenceSN(), GetRefMeasure(), Isis::ControlNet::GraphToString(), Isis::BundleControlPoint::id(), Isis::InterestOperator::InterestByPoint(), Isis::Directory::modifyControlPoint(), Isis::ControlPointGraphicsItem::paint(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointEditLockFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointIDFilter(), Isis::ControlNetVitals::pointModified(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::ControlNetFilter::PointResMagnitudeFilter(), Isis::ControlNetFilter::PointStats(), Isis::StereoTool::rubberBandComplete(), Isis::ControlNet::SetImages(), SetType(), Isis::ControlNetVersioner::toPvl(), and Isis::MatchTool::updatePointInfo().
GetLineResidualRms()
double Isis::ControlPoint::GetLineResidualRms () const
Get rms of line residuals.
Returns
The rms of line residuals
References Isis::Statistics::AddData(), Isis::ControlMeasure::GetLineResidual(), GetMeasure(), Isis::ControlMeasure::IsIgnored(), Isis::ControlMeasure::IsRejected(), measures, and Isis::Statistics::Rms().
GetMeasure() [1/4]
ControlMeasure * Isis::ControlPoint::GetMeasure (int index)
References _FILEINFO_, GetMeasure(), Isis::IException::Programmer, and Isis::toString().
GetMeasure() [2/4]
const ControlMeasure * Isis::ControlPoint::GetMeasure (int index) const
References _FILEINFO_, GetMeasure(), Isis::IException::Programmer, and Isis::toString().
GetMeasure() [3/4]
ControlMeasure * Isis::ControlPoint::GetMeasure (QString serialNumber)
Get a control measure based on its cube's serial number.
Parameters
serialNumber serial number of measure to get
Returns
control measure with matching serial number
References measures.
GetMeasure() [4/4]
const ControlMeasure * Isis::ControlPoint::GetMeasure (QString serialNumber) const
Get a control measure based on its cube's serial number.
Parameters
serialNumber serial number of measure to get
Returns
const control measure with matching serial number
References measures.
Referenced by Isis::BundleControlPoint::BundleControlPoint(), ClearJigsawRejected(), ComputeApriori(), ControlPoint(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::CnetEditorWidget::filteredNetwork(), Isis::InterestOperator::FindCnetRef(), GetLineResidualRms(), GetMeasure(), GetResidualRms(), GetSampleResidualRms(), operator[](), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointMeasurePropertiesFilter(), Isis::ControlNetFilter::PointMeasuresFilter(), Isis::ControlNetFilter::PointNumMeasuresEditLockFilter(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::ControlNetFilter::PointResMagnitudeFilter(), Isis::PointTableDelegate::readData(), Isis::ControlNet::sortedMeasureList(), and Isis::ControlNetVersioner::toPvl().
getMeasures()
QList< ControlMeasure * > Isis::ControlPoint::getMeasures (bool excludeIgnored = false) const
Parameters
excludeIgnored Ignored measures are excluded if this is true. It is false by default.
Returns
A list of this points measures
References Isis::ControlMeasure::IsIgnored(), and measures.
Referenced by Isis::ControlNet::DeletePoint(), Isis::MeasureCountFilter::evaluate(), Isis::AbstractFilter::evaluatePointFromMeasureFilter(), and Isis::ControlPointGraphicsItem::paint().
GetNumberOfRejectedMeasures()
int Isis::ControlPoint::GetNumberOfRejectedMeasures () const
Get the number of rejected measures on the control point.
Returns
The number of rejected measures on this control point
Referenced by Isis::BundleControlPoint::numberOfRejectedMeasures().
GetNumLockedMeasures()
int Isis::ControlPoint::GetNumLockedMeasures () const
Returns the number of locked control measures.
Returns
Number of locked control measures
References IsEditLocked(), and measures.
Referenced by Isis::AbstractPointItem::deleteSource(), Isis::InterestOperator::FindCnetRef(), Isis::ControlNetStatistics::GeneratePointStats(), Isis::ControlNet::GetNumEditLockMeasures(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::ControlNetFilter::PointEditLockFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointNumMeasuresEditLockFilter(), and Isis::ControlNetFilter::PointStats().
GetNumMeasures()
int Isis::ControlPoint::GetNumMeasures () const
References measures.
Referenced by Isis::BundleControlPoint::BundleControlPoint(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::MatchTool::deletePoint(), Isis::QnetCubeDistanceFilter::filter(), Isis::QnetCubePointsFilter::filter(), Isis::QnetPointCubeNameFilter::filter(), Isis::QnetPointGoodnessFilter::filter(), Isis::QnetPointImagesFilter::filter(), Isis::QnetPointMeasureFilter::filter(), Isis::QnetPointTypeFilter::filter(), Isis::CnetEditorWidget::filteredNetwork(), Isis::InterestOperator::FindCnetRef(), Isis::InterestOperator::FindOverlap(), Isis::InterestOperator::FindOverlapByImageFootPrint(), Isis::ControlNetStatistics::GeneratePointStats(), Isis::AbstractPointItem::getData(), Isis::ControlNet::GetNumIgnoredMeasures(), Isis::ControlNet::GetNumMeasures(), Isis::ControlNetVitals::getPointsBelowMeasureThreshold(), Isis::InterestOperator::InterestByPoint(), Isis::QnetFileTool::loadPointImages(), Isis::MatchTool::modifyPoint(), Isis::QnetTool::modifyPoint(), operator==(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::ControlNetFilter::PointEditLockFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointMeasurePropertiesFilter(), Isis::ControlNetFilter::PointMeasuresFilter(), Isis::ControlNetFilter::PointNumMeasuresEditLockFilter(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::ControlNetFilter::PointResMagnitudeFilter(), Isis::ControlNetFilter::PointStats(), Isis::InterestOperator::ProcessLocked_Point_Reference(), Isis::PointTableDelegate::readData(), Isis::ControlNet::sortedMeasureList(), Isis::ControlNetVersioner::toPvl(), and Isis::ControlNetVersioner::write().
GetNumValidMeasures()
int Isis::ControlPoint::GetNumValidMeasures () const
Returns
Number of valid control measures
References IsIgnored(), and measures.
Referenced by Isis::ControlNetVitals::addPoint(), Isis::ControlNetVitals::deletePoint(), Isis::ControlNetStatistics::GeneratePointStats(), Isis::ControlNet::GetNumIgnoredMeasures(), Isis::ControlNet::GetNumValidMeasures(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::ControlNetFilter::PointEditLockFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetVitals::pointModified(), and Isis::ControlNetFilter::PointStats().
GetPointTypeString()
QString Isis::ControlPoint::GetPointTypeString () const
Obtain a string representation of the PointType.
Returns
A string representation of the PointType
References GetType(), and PointTypeToString().
Referenced by Isis::PointTypeFilter::evaluate(), and Isis::AbstractPointItem::getData().
GetRadiusSourceString()
QString Isis::ControlPoint::GetRadiusSourceString () const
Obtain a string representation of the RadiusSource.
Returns
A string representation of the RadiusSource
References RadiusSourceToString().
Referenced by Isis::AbstractPointItem::getData().
GetReferenceSN()
QString Isis::ControlPoint::GetReferenceSN () const
Returns
The cube serial number of the reference measure
References _FILEINFO_, Isis::ControlMeasure::GetCubeSerialNumber(), GetId(), HasRefMeasure(), and Isis::IException::Programmer.
GetRefMeasure() [1/2]
ControlMeasure * Isis::ControlPoint::GetRefMeasure ()
Get the measure that is the reference directly.
References _FILEINFO_, GetId(), HasRefMeasure(), and Isis::IException::Programmer.
GetRefMeasure() [2/2]
const ControlMeasure * Isis::ControlPoint::GetRefMeasure () const
Get the reference control measure.
Returns
const reference measure for this point
References _FILEINFO_, GetId(), HasRefMeasure(), and Isis::IException::Programmer.
Referenced by Isis::MatchTool::deletePoint(), Isis::QnetPointDistanceFilter::filter(), Isis::InterestOperator::FindCnetRef(), Isis::AbstractMeasureItem::getData(), Isis::AbstractPointItem::getData(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::ControlNetFilter::PointMeasurePropertiesFilter(), Isis::ControlNetFilter::PointMeasuresFilter(), Isis::ControlNetFilter::PointNumMeasuresEditLockFilter(), Isis::ControlNetFilter::PointPixelShiftFilter(), and Isis::ControlNetFilter::PointResMagnitudeFilter().
GetResidualRms()
double Isis::ControlPoint::GetResidualRms () const
Get rms of residuals.
Returns
The rms of residuals
References Isis::Statistics::AddData(), Isis::ControlMeasure::GetLineResidual(), GetMeasure(), Isis::ControlMeasure::GetSampleResidual(), Isis::ControlMeasure::IsIgnored(), Isis::ControlMeasure::IsRejected(), measures, and Isis::Statistics::Rms().
Referenced by Isis::BundleControlPoint::residualRms().
GetSampleResidualRms()
double Isis::ControlPoint::GetSampleResidualRms () const
Get rms of sample residuals.
Returns
The rms of sample residuals
References Isis::Statistics::AddData(), GetMeasure(), Isis::ControlMeasure::GetSampleResidual(), Isis::ControlMeasure::IsIgnored(), Isis::ControlMeasure::IsRejected(), measures, and Isis::Statistics::Rms().
GetStatistic() [1/2]
Statistics Isis::ControlPoint::GetStatistic (double(ControlMeasure::*)() const statFunc) const
This function will call a given method on every control measure that this point has.
Parameters
statFunc The function to use for data collection
Returns
The gathered statistic
History:
2011-03-08 Debbie A. Cook - Changed to get statistics for all point types and not just Candidate.
References Isis::Statistics::AddData(), Isis::ControlMeasure::IsIgnored(), and measures.
Referenced by Isis::ControlNet::AverageResidual(), Isis::QnetPointJigsawErrorFilter::filter(), Isis::QnetPointRegistrationErrorFilter::filter(), and Isis::ControlNet::GetMaximumResidual().
GetStatistic() [2/2]
Statistics Isis::ControlPoint::GetStatistic (long dataType) const
References Isis::Statistics::AddData(), Isis::ControlMeasure::GetLogData(), Isis::ControlMeasureLogData::GetNumericalValue(), Isis::ControlMeasure::IsIgnored(), and measures.
GetSurfacePointSourceString()
QString Isis::ControlPoint::GetSurfacePointSourceString () const
Obtain a string representation of the SurfacePointSource.
Returns
A string representation of the SurfacePointSource
References SurfacePointSourceToString().
Referenced by Isis::AbstractPointItem::getData().
GetType()
ControlPoint::PointType Isis::ControlPoint::GetType () const
Returns
this point't type
Referenced by Isis::ControlNetVitals::addPoint(), ComputeApriori(), Isis::ControlPointGraphicsItem::ControlPointGraphicsItem(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::ControlNetVitals::deletePoint(), Isis::QnetPointTypeFilter::filter(), Isis::InterestOperator::FindCnetRef(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlNetStatistics::GeneratePointStats(), Isis::ControlNetVitals::getConstrainedPoints(), Isis::ControlNetVitals::getFixedPoints(), Isis::ControlNetVitals::getFreePoints(), GetPointTypeString(), Isis::ChipViewport::paintEvent(), Isis::StereoTool::paintViewport(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::ControlNetFilter::PointEditLockFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetVitals::pointModified(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::ControlNetFilter::PointPropertiesFilter(), Isis::ControlNetFilter::PointResMagnitudeFilter(), Isis::ControlNetFilter::PointStats(), Isis::BundleControlPoint::setWeights(), Isis::ControlNetVersioner::toPvl(), and Isis::BundleControlPoint::type().
HasAprioriCoordinates()
bool Isis::ControlPoint::HasAprioriCoordinates ()
References Isis::SurfacePoint::GetX(), Isis::SurfacePoint::GetY(), Isis::SurfacePoint::GetZ(), and Isis::Displacement::isValid().
HasAprioriRadiusSourceFile()
bool Isis::ControlPoint::HasAprioriRadiusSourceFile () const
Checks to see if the radius source file has been set.
Returns
bool True if the radius source file has been set.
Referenced by Isis::ControlNetVersioner::toPvl().
HasAprioriSurfacePointSourceFile()
bool Isis::ControlPoint::HasAprioriSurfacePointSourceFile () const
Checks to see if the surface point source file has been set.
Returns
bool True if the surface point source file has been set.
Referenced by Isis::ControlNetVersioner::toPvl().
HasChooserName()
bool Isis::ControlPoint::HasChooserName () const
Returns true if the choosername is not empty.
HasDateTime()
bool Isis::ControlPoint::HasDateTime () const
Returns true if the datetime is not empty.
HasRefMeasure()
bool Isis::ControlPoint::HasRefMeasure () const
Checks to see if a reference measure is set.
Returns
bool True if a reference measure is set.
Referenced by GetReferenceSN(), GetRefMeasure(), IndexOfRefMeasure(), and Isis::ControlNetVersioner::toPvl().
HasSerialNumber()
bool Isis::ControlPoint::HasSerialNumber (QString serialNumber) const
Return true if given serial number exists in point.
Parameters
serialNumber The serial number
Returns
True if point contains serial number, false if not
Referenced by Isis::StereoTool::paintViewport(), and Isis::QnetNewMeasureDialog::setFiles().
IndexOf() [1/2]
int Isis::ControlPoint::IndexOf (ControlMeasure * cm, bool throws = true) const
Parameters
cm The control measure to find the index of
throws Throws an exception on failure instead of returning -1. Be aware that by default this is true!
Returns
The index of the passed in measure, or -1 on failure if throws is false.
References Isis::ControlMeasure::GetCubeSerialNumber().
IndexOf() [2/2]
int Isis::ControlPoint::IndexOf (QString sn, bool throws = true) const
Parameters
sn The serial number of the control measure to find the index of
throws Throws an exception on failure instead of returning -1. Be aware that by default this is true!
Returns
The index of the measure with serial number matching sn, or -1 on failure if throws is false.
References _FILEINFO_, and Isis::IException::Programmer.
IndexOfRefMeasure()
int Isis::ControlPoint::IndexOfRefMeasure () const
Parameters
throws Throws an exception on failure instead of returning -1. Be aware that by default this is true!
Returns
The index of the reference measure, or -1 if no measures exist in the point (A point with at least one measure ALWAYS has a reference measure.
References _FILEINFO_, Isis::ControlMeasure::GetCubeSerialNumber(), HasRefMeasure(), and Isis::IException::Programmer.
Referenced by Isis::InterestOperator::FindCnetRef(), Isis::PointTableDelegate::readData(), and Isis::ControlNetVersioner::toPvl().
IsConstrained()
bool Isis::ControlPoint::IsConstrained ()
Return bool indicating if point is Constrained or not.
Returns
bool indicating if point is Constrained or not.
References Free.
Referenced by ComputeApriori().
IsCoord1Constrained()
bool Isis::ControlPoint::IsCoord1Constrained ()
Return bool indicating if 1st coordinate is Constrained or not.
This corresponds to Latitude for a Latitudinal solution or X for a Rectangular solution.
Returns
bool indicating if 1st coordinate is Constrained or not.
References Coord1Constrained.
Referenced by Isis::BundleControlPoint::setWeights(), and Isis::ControlNetVersioner::toPvl().
IsCoord2Constrained()
bool Isis::ControlPoint::IsCoord2Constrained ()
Return bool indicating if 2nd coordinate is Constrained or not.
This corresponds to Longitude for a Latitudinal solution or Y for a Rectangular solution.
Returns
bool indicating if 2nd coordinate is Constrained or not.
References Coord2Constrained.
Referenced by Isis::BundleControlPoint::setWeights(), and Isis::ControlNetVersioner::toPvl().
IsCoord3Constrained()
bool Isis::ControlPoint::IsCoord3Constrained ()
Return bool indicating if 3rd coordinate is Constrained or not.
This corresponds to Radius for a Latitudinal solution or Z for a Rectangular solution.
Returns
bool indicating if 3rd coordinate is Constrained or not.
References Coord3Constrained.
Referenced by Isis::BundleControlPoint::setWeights().
IsEditLocked()
bool Isis::ControlPoint::IsEditLocked () const
Referenced by Isis::ControlNetVitals::addPoint(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::ControlNetVitals::deletePoint(), Isis::ControlNet::DeletePoint(), Isis::AbstractMeasureItem::deleteSource(), Isis::AbstractPointItem::deleteSource(), Isis::PointEditLockedFilter::evaluate(), Isis::QnetPointMeasureFilter::filter(), Isis::QnetPointTypeFilter::filter(), Isis::InterestOperator::FindCnetRef(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlNetStatistics::GeneratePointStats(), Isis::AbstractPointItem::getData(), Isis::ControlNetVitals::getLockedPoints(), Isis::ControlNet::GetNumEditLockPoints(), GetNumLockedMeasures(), Isis::AbstractMeasureItem::isDataEditable(), Isis::AbstractPointItem::isDataEditable(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::ControlNetFilter::PointEditLockFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetVitals::pointModified(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::ControlNetFilter::PointResMagnitudeFilter(), Isis::ControlNetFilter::PointStats(), Isis::InterestOperator::ProcessLocked_Point_Reference(), Isis::PointTableDelegate::readData(), ResetApriori(), Isis::ControlNetVersioner::toPvl(), Isis::MatchTool::updatePointInfo(), and Isis::QnetTool::updatePointInfo().
IsFixed()
bool Isis::ControlPoint::IsFixed () const
Return bool indicating if point is Fixed or not.
Returns
bool indicating if point is Fixed or not.
References Fixed.
Referenced by ComputeApriori().
IsFree()
bool Isis::ControlPoint::IsFree () const
Return bool indicating if point is Free or not.
Returns
bool indicating if point is Free or not.
References Constrained, and Fixed.
IsIgnored()
bool Isis::ControlPoint::IsIgnored () const
Referenced by Isis::ControlNetVitals::addPoint(), Isis::ControlNet::AverageResidual(), Isis::ControlNet::ComputeApriori(), ComputeResiduals(), ComputeResiduals_Millimeters(), Isis::ControlPointGraphicsItem::ControlPointGraphicsItem(), Isis::ControlNetFilter::CubeDistanceFilter(), Delete(), Isis::ControlNetVitals::deletePoint(), Isis::ControlNet::DeletePoint(), Isis::PointIgnoredFilter::evaluate(), Isis::QnetPointMeasureFilter::filter(), Isis::QnetPointTypeFilter::filter(), Isis::InterestOperator::FindCnetRef(), Isis::ControlNetStatistics::GenerateImageStats(), Isis::ControlNetStatistics::GeneratePointStats(), Isis::ControlNetVitals::getConstrainedPoints(), Isis::AbstractPointItem::getData(), Isis::ControlNetVitals::getFixedPoints(), Isis::ControlNetVitals::getFreePoints(), Isis::ControlNetVitals::getIgnoredPoints(), Isis::ControlNetVitals::getLockedPoints(), Isis::ControlNet::GetNumValidMeasures(), GetNumValidMeasures(), Isis::ControlNet::GetNumValidPoints(), Isis::ControlNetVitals::getPointsBelowMeasureThreshold(), Isis::ControlNet::GraphToString(), Isis::ChipViewport::paintEvent(), Isis::StereoTool::paintViewport(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::ControlNetFilter::PointEditLockFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::ControlNetFilter::PointPropertiesFilter(), Isis::ControlNetFilter::PointResMagnitudeFilter(), Isis::ControlNetFilter::PointStats(), Isis::PointTableDelegate::readData(), Isis::ControlNet::sortedMeasureList(), Isis::ControlNetVersioner::toPvl(), Isis::MatchTool::updatePointInfo(), and Isis::QnetTool::updatePointInfo().
IsInvalid()
bool Isis::ControlPoint::IsInvalid () const
IsReferenceExplicit()
bool Isis::ControlPoint::IsReferenceExplicit () const
Returns
true Returns true if SetRefMeasure has ever been set on this point.
Referenced by Isis::MatchTool::deletePoint(), and Isis::ControlNetVersioner::toPvl().
IsRejected()
bool Isis::ControlPoint::IsRejected () const
Referenced by Isis::PointJigsawRejectedFilter::evaluate(), Isis::AbstractPointItem::getData(), and Isis::BundleControlPoint::isRejected().
IsValid()
bool Isis::ControlPoint::IsValid () const
Load()
void Isis::ControlPoint::Load (PvlObject & p)
Loads the PvlObject into a ControlPoint.
Parameters
p PvlObject containing ControlPoint information
forceBuild Allows invalid Control Measures to be added to this Control Point
Exceptions
Isis::iException::User - Invalid Point Type
Isis::iException::User - Unable to add ControlMeasure to Control Point
History:
2008-06-18 Tracie Sucharski/Jeannie Walldren, Fixed bug with checking for "True" vs "true", change to lower case for comparison.
2009-12-29 Tracie Sucharski - Added new ControlPoint information.
2010-01-13 Tracie Sucharski - Changed from Set methods to simply setting private variables to increase speed?
2010-07-30 Tracie Sucharski, Updated for changes made after additional working sessions for Control network design.
2010-09-01 Tracie Sucharski, Add checks for AprioriLatLonSource AprioriLatLonSourceFile. If there are AprioriSigmas,but no AprioriXYZ, use the XYZ values.
2010-09-15 Tracie Sucharski, It was decided after mtg with Debbie, Stuart, Ken and Tracie that ControlPoint will only function with x/y/z, not lat/lon/radius. It will be the responsibility of the application or class using ControlPoint to set up a SurfacePoint object to do conversions between x/y/z and lat/lon/radius. So... remove all conversion methods from this class. It was also decided that when importing old networks that contain Sigmas, the sigmas will not be imported , due to conflicts with the units of the sigmas,we cannot get accurate x,y,z sigmas from the lat,lon,radius sigmas without the covariance matrix.
2010-09-28 Tracie Sucharski, Added back the conversion methods from lat,lon,radius to x,y,z only for the point, since that is what most applications need.
2010-12-02 Debbie A. Cook, Added units to SurfacePoint.SetSpherical calls.
2011-03-12 Debbie A. Cook, Added targetRadius to do conversions
NumberOfConstrainedCoordinates()
int Isis::ControlPoint::NumberOfConstrainedCoordinates ()
Return bool indicating if point is Constrained or not.
Returns
bool indicating if point is Constrained or not.
Referenced by ComputeApriori().
operator!=()
bool Isis::ControlPoint::operator!= (const ControlPoint & other) const
Compare two Control Points for inequality.
Parameters
other The other point to compare this one to
Returns
true if the two points are not equal, and false otherwise
operator=()
const ControlPoint & Isis::ControlPoint::operator= (const ControlPoint & other)
Parameters
pPoint
Returns
ControlPoint&
References Delete(), measures, SetAdjustedSurfacePoint(), SetAprioriRadiusSource(), SetAprioriRadiusSourceFile(), SetAprioriSurfacePoint(), SetAprioriSurfacePointSource(), SetAprioriSurfacePointSourceFile(), SetChooserName(), SetDateTime(), SetEditLock(), SetId(), SetIgnored(), SetRefMeasure(), SetRejected(), and SetType().
operator==()
bool Isis::ControlPoint::operator== (const ControlPoint & other) const
Compare two Control Points for equality.
Parameters
other The other point to compare to
Returns
true if the two points are equal, and false otherwise
References GetNumMeasures(), and measures.
operator[]() [1/4]
ControlMeasure * Isis::ControlPoint::operator[] (int index)
Same as GetMeasure (provided for convenience)
Parameters
index If there are n measures, the measure returned will be the ith measure added to the point
Returns
The measure which has the provided serial number
References GetMeasure().
operator[]() [2/4]
const ControlMeasure * Isis::ControlPoint::operator[] (int index) const
Same as GetMeasure (provided for convenience)
Parameters
index If there are n measures, the measure returned will be the ith measure added to the point
Returns
const version of the measure which has the provided serial number
References GetMeasure().
operator[]() [3/4]
ControlMeasure * Isis::ControlPoint::operator[] (QString serialNumber)
Same as GetMeasure (provided for convenience)
Parameters
serialNumber Cube serial number of desired control measure
Returns
The measure which has the provided serial number
References GetMeasure().
operator[]() [4/4]
const ControlMeasure * Isis::ControlPoint::operator[] (QString serialNumber) const
Same as GetMeasure (provided for convenience)
Parameters
serialNumber Cube serial number of desired control measure
Returns
const version of the measure which has the provided serial number
References GetMeasure().
Parent()
ControlNet* Isis::ControlPoint::Parent () inline
Referenced by Isis::MatchTool::deletePoint(), Isis::AbstractPointItem::deleteSource(), Isis::MatchTool::modifyPoint(), and Isis::ControlPointEditWidget::setEditPoint().
PointModified()
void Isis::ControlPoint::PointModified () protected
List of Control Measures.
Signal to indicate the point has been modified.
Resets the last modified dateTime to null.
Referenced by Add(), ComputeApriori(), ComputeResiduals(), ComputeResiduals_Millimeters(), Delete(), SetAdjustedSurfacePoint(), SetAprioriRadiusSource(), SetAprioriRadiusSourceFile(), SetAprioriSurfacePoint(), SetAprioriSurfacePointSource(), SetAprioriSurfacePointSourceFile(), SetIgnored(), and SetType().
PointTypeToString()
QString Isis::ControlPoint::PointTypeToString (PointType pointType) static
Obtain a string representation of a given PointType.
Parameters
type PointType to convert to a string
Returns
A string representation of type
References Constrained, Fixed, and Free.
Referenced by Isis::BundleControlPoint::formatAprioriSigmaString(), Isis::BundleControlPoint::formatBundleLatitudinalOutputDetailString(), Isis::BundleControlPoint::formatBundleOutputSummaryString(), Isis::BundleControlPoint::formatBundleRectangularOutputDetailString(), GetPointTypeString(), Isis::PointTableDelegate::getWidget(), Isis::NewControlPointDialog::NewControlPointDialog(), and Isis::ControlNetVitals::pointModified().
RadiusSourceToString()
QString Isis::ControlPoint::RadiusSourceToString (RadiusSource::Source source) static
Obtain a string representation of a given RadiusSource.
Parameters
source RadiusSource to convert to string
Returns
A string representation of RadiusSource
References Isis::ControlPoint::RadiusSource::AverageOfMeasures, Isis::ControlPoint::RadiusSource::BundleSolution, Isis::ControlPoint::RadiusSource::DEM, Isis::ControlPoint::RadiusSource::Ellipsoid, Isis::ControlPoint::RadiusSource::None, and Isis::ControlPoint::RadiusSource::User.
Referenced by GetRadiusSourceString(), and Isis::Shape::save().
ResetApriori()
ControlPoint::Status Isis::ControlPoint::ResetApriori ()
Reset all the Apriori info to defaults.
Author
Sharmila Prasad (10/22/2010)
References IsEditLocked(), Isis::ControlPoint::SurfacePointSource::None, Isis::ControlPoint::RadiusSource::None, PointLocked, and Success.
SetAdjustedSurfacePoint()
ControlPoint::Status Isis::ControlPoint::SetAdjustedSurfacePoint (SurfacePoint newSurfacePoint)
Set or update the surface point relating to this control point.
This is the point on the surface of the planet that the measures are tied to. This updates the last modified attributes of this point. *** Warning: Only BundleAdjust and its applications should be using this method.
Parameters
newSurfacePoint The point on the target's surface the measures are tied to
References PointModified(), and Success.
Referenced by operator=(), Isis::BundleControlPoint::setAdjustedSurfacePoint(), and Isis::AbstractPointItem::setData().
SetAprioriRadiusSource()
ControlPoint::Status Isis::ControlPoint::SetAprioriRadiusSource (RadiusSource::Source source)
This updates the source of the radius of the apriori surface point.
See also
RadiusSource::Source
Parameters
source Where the radius came from
References PointLocked, PointModified(), and Success.
Referenced by ComputeApriori(), operator=(), and Isis::AbstractPointItem::setData().
SetAprioriRadiusSourceFile()
ControlPoint::Status Isis::ControlPoint::SetAprioriRadiusSourceFile (QString sourceFile)
This updates the filename of the DEM that the apriori radius came from.
It doesn't really make sense to call this unless the RadiusSource is DEM.
See also
RadiusSource::Source
Parameters
source Where the radius came from
References PointLocked, PointModified(), and Success.
Referenced by operator=(), and Isis::AbstractPointItem::setData().
SetAprioriSurfacePoint()
ControlPoint::Status Isis::ControlPoint::SetAprioriSurfacePoint (SurfacePoint aprioriSP)
This updates the apriori surface point.
See also
SetAprioriRadiusSource
SetAprioriRadiusSourceFile
SetAprioriPointSource
SetAprioriPointSourceFile
aprioriSurfacePoint
Parameters
aprioriSP The apriori surface point to remember
References Coord1Constrained, Coord2Constrained, Coord3Constrained, Isis::ControlNet::GetCoordType(), Isis::SurfacePoint::GetLatSigma(), Isis::SurfacePoint::GetLocalRadiusSigma(), Isis::SurfacePoint::GetLonSigma(), Isis::SurfacePoint::GetXSigma(), Isis::SurfacePoint::GetYSigma(), Isis::SurfacePoint::GetZSigma(), Isis::Angle::isValid(), Isis::Distance::isValid(), Isis::SurfacePoint::Latitudinal, PointLocked, PointModified(), Isis::SurfacePoint::Rectangular, and Success.
Referenced by Isis::QnetTool::createFixedPoint(), Isis::StereoTool::createPoint(), operator=(), and Isis::AbstractPointItem::setData().
SetAprioriSurfacePointSource()
ControlPoint::Status Isis::ControlPoint::SetAprioriSurfacePointSource (SurfacePointSource::Source source)
This updates the source of the surface point.
See also
SurfacePointSource::Source
Parameters
source Where the surface point came from
References PointLocked, PointModified(), and Success.
Referenced by ComputeApriori(), Isis::ControlPointEditWidget::createControlPoint(), operator=(), and Isis::AbstractPointItem::setData().
SetAprioriSurfacePointSourceFile()
ControlPoint::Status Isis::ControlPoint::SetAprioriSurfacePointSourceFile (QString sourceFile)
This updates the filename of where the apriori surface point came from.
See also
RadiusSource::Source
Parameters
sourceFile Where the surface point came from
References PointLocked, PointModified(), and Success.
Referenced by Isis::ControlPointEditWidget::createControlPoint(), operator=(), and Isis::AbstractPointItem::setData().
SetChooserName()
ControlPoint::Status Isis::ControlPoint::SetChooserName (QString name)
Set the point's chooser name.
This will be lost if any attributes relating to this point is later changed and the current user will be set. This is one of the 'last modified attributes' referred to in other comments.
Parameters
name The username of the person who last modified this control point
References PointLocked, and Success.
Referenced by Isis::ControlPointEditWidget::createControlPoint(), Isis::QnetTool::createFixedPoint(), Isis::QnetTool::createPoint(), Isis::MatchTool::createPoint(), operator=(), and Isis::AbstractPointItem::setData().
SetDateTime()
ControlPoint::Status Isis::ControlPoint::SetDateTime (QString newDateTime)
Set the point's last modified time.
This will be lost if any attributes relating to this point are later changed and the current time will be set. This is one of the 'last modified attributes' referred to in other comments.
Parameters
newDateTime The date and time this control point was last modified
References PointLocked, and Success.
Referenced by operator=(), and Isis::AbstractPointItem::setData().
SetEditLock()
ControlPoint::Status Isis::ControlPoint::SetEditLock (bool lock)
Set the EditLock state.
If edit lock is on, then most attributes relating to this point are not modifiable. Edit lock is like "Don't modify my attributes, but you can still modify my measures' attributes". The reference measure is implicitely edit locked if the point is edit locked.
Parameters
lock True to enable edit lock, false to disable it and allow the point to be modified.
References EditLockModified, and Success.
Referenced by Isis::CnetEditorWidget::filteredNetwork(), operator=(), Isis::AbstractPointItem::setData(), and Isis::MatchTool::updatePointInfo().
SetId()
ControlPoint::Status Isis::ControlPoint::SetId (QString newId)
Sets the Id of the control point.
Parameters
id Control Point Id
Returns
(int) status Success or PointLocked
References PointLocked, and Success.
Referenced by operator=(), and Isis::AbstractPointItem::setData().
SetIgnored()
ControlPoint::Status Isis::ControlPoint::SetIgnored (bool newIgnoreStatus)
Set whether to ignore or use control point.
Parameters
newIgnoreStatus True to ignore this Control Point, False to un-ignore
References IgnoredModified, PointLocked, PointModified(), and Success.
Referenced by Isis::InterestOperator::FindCnetRef(), operator=(), Isis::InterestOperator::ProcessLocked_Point_Reference(), Isis::AbstractPointItem::setData(), and Isis::MatchTool::updatePointInfo().
SetNumberOfRejectedMeasures()
void Isis::ControlPoint::SetNumberOfRejectedMeasures (int numRejected)
Set (update) the number of rejected measures for the control point.
Parameters
numRejected The number of rejected measures
Referenced by Isis::BundleControlPoint::setNumberOfRejectedMeasures().
SetRefMeasure() [1/3]
ControlPoint::Status Isis::ControlPoint::SetRefMeasure (ControlMeasure * cm)
Set the point's reference measure.
Parameters
cm The new reference measure
References PointLocked, and Success.
Referenced by ControlPoint(), Isis::InterestOperator::FindCnetRef(), operator=(), and Isis::AbstractPointItem::setData().
SetRefMeasure() [2/3]
ControlPoint::Status Isis::ControlPoint::SetRefMeasure (int index)
Set the point's reference measure.
Parameters
index The index of the new reference measure
References _FILEINFO_, measures, PointLocked, Isis::IException::Programmer, Success, and Isis::toString().
SetRefMeasure() [3/3]
ControlPoint::Status Isis::ControlPoint::SetRefMeasure (QString sn)
Set the points reference measure.
Parameters
sn The serial number of the new reference measure
References _FILEINFO_, measures, PointLocked, Isis::IException::Programmer, and Success.
SetRejected()
ControlPoint::Status Isis::ControlPoint::SetRejected (bool reject)
Set the jigsawRejected state.
If IsRejected is true, then this point should be ignored until the next iteration in the bundle adjustement. BundleAdjust decides when to reject or accept a point. The initial IsRejected state of a measure is false.
Parameters
reject True to reject a measure, false to include it in the adjustment
References Success.
Referenced by ClearJigsawRejected(), operator=(), and Isis::BundleControlPoint::setRejected().
SetType()
ControlPoint::Status Isis::ControlPoint::SetType (PointType newType)
Updates the control point's type.
This updates the last modified attributes of this point.
See also
PointType
Parameters
newType The new type this control point should be
References _FILEINFO_, Constrained, Fixed, Free, GetId(), PointLocked, PointModified(), Isis::IException::Programmer, Success, and TypeModified.
Referenced by Isis::ControlPointEditWidget::createControlPoint(), Isis::QnetTool::createFixedPoint(), Isis::StereoTool::createPoint(), Isis::MatchTool::createPoint(), operator=(), and Isis::AbstractPointItem::setData().
StringToPointType()
ControlPoint::PointType Isis::ControlPoint::StringToPointType (QString pointTypeString) static
Obtain a PointType given a string representation of it.
Parameters
pointTypeString for the requested PointType
Returns
the PointType for the given string
References _FILEINFO_, Constrained, Fixed, Free, and Isis::IException::Programmer.
Referenced by Isis::PointTableDelegate::readData(), and Isis::AbstractPointItem::setData().
StringToRadiusSource()
ControlPoint::RadiusSource::Source Isis::ControlPoint::StringToRadiusSource (QString str) static
Obtain a RadiusSource::Source from a string.
Parameters
str string to get a RadiusSource::Source from
Returns
The RadiusSource::Source matching the given string
References Isis::ControlPoint::RadiusSource::AverageOfMeasures, Isis::ControlPoint::RadiusSource::BundleSolution, Isis::ControlPoint::RadiusSource::DEM, Isis::ControlPoint::RadiusSource::Ellipsoid, Isis::ControlPoint::RadiusSource::None, and Isis::ControlPoint::RadiusSource::User.
Referenced by Isis::PointTableDelegate::readData(), and Isis::AbstractPointItem::setData().
StringToSurfacePointSource()
ControlPoint::SurfacePointSource::Source Isis::ControlPoint::StringToSurfacePointSource (QString str) static
Obtain a SurfacePoint::Source from a string.
Parameters
str string to get a SurfacePoint::Source from
Returns
The SurfacePint::Source matching the given string
References Isis::ControlPoint::SurfacePointSource::AverageOfMeasures, Isis::ControlPoint::SurfacePointSource::Basemap, Isis::ControlPoint::SurfacePointSource::BundleSolution, Isis::ControlPoint::SurfacePointSource::None, Isis::ControlPoint::SurfacePointSource::Reference, and Isis::ControlPoint::SurfacePointSource::User.
Referenced by Isis::PointTableDelegate::readData(), and Isis::AbstractPointItem::setData().
SurfacePointSourceToString()
QString Isis::ControlPoint::SurfacePointSourceToString (SurfacePointSource::Source source) static
Obtain a string representation of a given SurfacePointSource.
Parameters
souce SurfacePointSource to get a string representation of
Returns
A string representation of SurfacePointSource
References Isis::ControlPoint::SurfacePointSource::AverageOfMeasures, Isis::ControlPoint::SurfacePointSource::Basemap, Isis::ControlPoint::SurfacePointSource::BundleSolution, Isis::ControlPoint::SurfacePointSource::None, Isis::ControlPoint::SurfacePointSource::Reference, and Isis::ControlPoint::SurfacePointSource::User.
Referenced by GetSurfacePointSourceString(), and Isis::Shape::save().
ZeroNumberOfRejectedMeasures()
void Isis::ControlPoint::ZeroNumberOfRejectedMeasures ()
Initialize the number of rejected measures to 0.
Referenced by Isis::BundleControlPoint::zeroNumberOfRejectedMeasures().
Friends And Related Function Documentation
ControlNet
friend class ControlNet friend
Member Data Documentation
measures
QHash< QString, ControlMeasure * >* Isis::ControlPoint::measures protected
Referenced by ClearJigsawRejected(), ComputeResiduals(), ComputeResiduals_Millimeters(), ControlPoint(), Delete(), GetLineResidualRms(), GetMeasure(), getMeasures(), GetNumLockedMeasures(), GetNumMeasures(), GetNumValidMeasures(), GetResidualRms(), GetSampleResidualRms(), GetStatistic(), operator=(), operator==(), SetRefMeasure(), and ~ControlPoint().
PointTypeCount
const int Isis::ControlPoint::PointTypeCount = 3 static
Referenced by Isis::PointTableDelegate::getWidget(), and Isis::NewControlPointDialog::NewControlPointDialog().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/ControlPoint/ControlPoint.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/control/objs/ControlPoint/ControlPoint.cpp