Isis Developer Reference: Isis::StripPolygonSeeder Class Reference
Isis::StripPolygonSeeder Class Reference
Pattern Matching
Seed points using a grid with a staggered pattern.
#include <StripPolygonSeeder.h>
Public Member Functions
StripPolygonSeeder (Pvl &pvl)
Construct a StripPolygonSeeder algorithm.
virtual ~StripPolygonSeeder ()
Destructor.
std::vector< geos::geom::Point * > Seed (const geos::geom::MultiPolygon *mp)
Seed a polygon with points.
virtual PvlGroup PluginParameters (QString grpName)
Plugin parameters.
double MinimumThickness ()
Return the minimum allowed thickness of the polygon.
double MinimumArea ()
Return the minimum allowed area of the polygon.
QString Algorithm () const
The name of the algorithm, read from the Name Keyword in the PolygonSeeder Pvl passed into the constructor.
Pvl InvalidInput ()
This method returns a copy of the Pvl passed in by the constructor (from a def file probably) minus what was used.
Protected Member Functions
virtual void Parse (Pvl &pvl)
Parse the StripSeeder spicific parameters from the PVL.
QString StandardTests (const geos::geom::MultiPolygon *multiPoly, const geos::geom::Envelope *polyBoundBox)
Check the polygon to see if it meets standard criteria.
Protected Attributes
Pvl * invalidInput
The Pvl passed in by the constructor minus what was used.
Detailed Description
Seed points using a grid with a staggered pattern.
This class seeds the polygon with Control Points by creating a grid, centered on the overlap polygon. In each grid square two points are checked to see if they are inside the overlap polygon. One of these points lies 1/6 of a grid square up and left from the grid's center point, while the other point lies 1/6 down and right. Each point found that is within the overlap polygon is returned as a point.
Author
2006-01-20 Stuart Sides
Constructor & Destructor Documentation
StripPolygonSeeder()
Isis::StripPolygonSeeder::StripPolygonSeeder (Pvl & pvl)
Construct a StripPolygonSeeder algorithm.
Parameters
pvl A Pvl object that contains a valid polygon point seeding definition
References Parse().
~StripPolygonSeeder()
virtual Isis::StripPolygonSeeder::~StripPolygonSeeder () inline virtual
Destructor.
Member Function Documentation
Algorithm()
QString Isis::PolygonSeeder::Algorithm () const inherited
The name of the algorithm, read from the Name Keyword in the PolygonSeeder Pvl passed into the constructor.
Returns
QString The value of the Name Keyword in the Pvl.
Referenced by Isis::GridPolygonSeeder::PluginParameters(), Isis::LimitPolygonSeeder::PluginParameters(), and PluginParameters().
InvalidInput()
Pvl Isis::PolygonSeeder::InvalidInput () inherited
This method returns a copy of the Pvl passed in by the constructor (from a def file probably) minus what was used.
Returns
Pvl A copy of this pvl minus what was used.
References Isis::PolygonSeeder::invalidInput.
MinimumArea()
double Isis::PolygonSeeder::MinimumArea () inherited
Return the minimum allowed area of the polygon.
This value is set from the "MinimumArea" keyword in the PVL. The seeding algorithm will not seed polygons that have an area less than this.
Returns
double The value for the minimum area allowed.
Referenced by Isis::GridPolygonSeeder::PluginParameters(), Isis::LimitPolygonSeeder::PluginParameters(), PluginParameters(), and Isis::PolygonSeeder::StandardTests().
MinimumThickness()
double Isis::PolygonSeeder::MinimumThickness () inherited
Return the minimum allowed thickness of the polygon.
This value is set from the "MinimumThickness" keyword in the PVL. The seeding algorithm will not seed polygons that have a thickness ratio less than this
Returns
double The value for the minimum thickness allowed.
Referenced by Isis::GridPolygonSeeder::PluginParameters(), Isis::LimitPolygonSeeder::PluginParameters(), PluginParameters(), and Isis::PolygonSeeder::StandardTests().
Parse()
void Isis::StripPolygonSeeder::Parse (Pvl & pvl) protected virtual
Parse the StripSeeder spicific parameters from the PVL.
Parameters
pvl The PVL object containing the control parameters for this polygon seeder.
Reimplemented from Isis::PolygonSeeder.
References _FILEINFO_, Isis::PvlContainer::deleteKeyword(), Isis::PvlContainer::fileName(), Isis::PvlObject::findGroup(), Isis::PvlContainer::hasKeyword(), Isis::PolygonSeeder::invalidInput, Isis::PolygonSeeder::Parse(), Isis::PvlObject::Traverse, and Isis::IException::User.
Referenced by StripPolygonSeeder().
PluginParameters()
PvlGroup Isis::StripPolygonSeeder::PluginParameters (QString grpName) virtual
Plugin parameters.
This method will add the PvlKeyword values for algorithm name, minimum thickness, and minimum area of this object to a PvlGroup with the name that is passed in.
Parameters
grpName A string containing the PvlGroup name.
Returns
PvlGroup The PvlGroup with the appropriate parameters added.
Reimplemented from Isis::PolygonSeeder.
References Isis::PvlContainer::addKeyword(), Isis::PolygonSeeder::Algorithm(), Isis::PolygonSeeder::MinimumArea(), Isis::PolygonSeeder::MinimumThickness(), and Isis::toString().
Seed()
std::vector< geos::geom::Point * > Isis::StripPolygonSeeder::Seed (const geos::geom::MultiPolygon * multiPoly) virtual
Seed a polygon with points.
Seed the supplied polygon with points in a staggered pattern. The spacing is determined by the PVL group "PolygonSeederAlgorithm"
Parameters
lonLatPoly The polygon to be seeded with points.
Returns
A vector of points which have been seeded into the polygon. The caller assumes responsibility for deleteing these.
Implements Isis::PolygonSeeder.
References Isis::globalFactory, and Isis::PolygonSeeder::StandardTests().
StandardTests()
QString Isis::PolygonSeeder::StandardTests (const geos::geom::MultiPolygon * xymp, const geos::geom::Envelope * xyBoundBox) protected inherited
Check the polygon to see if it meets standard criteria.
Parameters
xymp The multipoly containing the coordinates in x/y units instead of lon/lat
xyBoundBox The bounding box of the multipoly
Returns
QString A string with an appropriate message to throw if a test was unsuccessful or an empty string if all tests passed.
References Isis::PolygonSeeder::MinimumArea(), Isis::PolygonSeeder::MinimumThickness(), and Isis::toString().
Referenced by Isis::LimitPolygonSeeder::Seed(), and Seed().
Member Data Documentation
invalidInput
Pvl* Isis::PolygonSeeder::invalidInput protected inherited
The Pvl passed in by the constructor minus what was used.
Referenced by Isis::PolygonSeeder::InvalidInput(), Isis::GridPolygonSeeder::Parse(), Isis::LimitPolygonSeeder::Parse(), Isis::PolygonSeeder::Parse(), Parse(), Isis::PolygonSeeder::PolygonSeeder(), and Isis::PolygonSeeder::~PolygonSeeder().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/StripPolygonSeeder/StripPolygonSeeder.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/StripPolygonSeeder/StripPolygonSeeder.cpp