Isis Developer Reference: Isis::Footprint2DView Class Reference
Isis::Footprint2DView Class Reference
View for displaying footprints of images in a QMos like way.
#include <Footprint2DView.h>
Public Slots
void enableControlNetTool (bool value)
A slot function that is called when directory emits a siganl that an active control network is set.
virtual void addItem (ProjectItem *item)
Adds an item to the view.
virtual void addItems (QList< ProjectItem * > items)
Adds several items to the view.
virtual void removeItem (ProjectItem *item)
Removes an item to the view.
virtual void removeItems (QList< ProjectItem * > items)
Removes several items from the view.
virtual void disableActions ()
Disables toolbars and toolpad actions.
Signals
void modifyControlPoint (ControlPoint *controlPoint)
void deleteControlPoint (ControlPoint *controlPoint)
void createControlPoint (double latitude, double longitude)
void redrawMeasures ()
void controlPointAdded (QString newPointId)
void windowChangeEvent (bool event)
Public Member Functions
Footprint2DView (Directory *directory, QWidget *parent=0)
Constructor.
~Footprint2DView ()
Destructor.
MosaicSceneWidget * mosaicSceneWidget ()
Accessor for the MosaicSceneWidget.
ImageFileListWidget * fileListWidget ()
Accessor for the FileListWidget.
void save (QXmlStreamWriter &stream, Project *project, FileName newProjectRoot) const
Save the footprint view widgets (ImageFileListWidget and MosaicSceneWidget to an XML file.
virtual QSize sizeHint () const
Returns the suggested size.
virtual void setModel (ProjectItemModel *model)
Sets the model used by the view.
virtual ProjectItemModel * model ()
Returns the model used by the view.
virtual void dragEnterEvent (QDragEnterEvent *event)
Accepts the drag enter event if the internal model can accept the mime data.
virtual void dragMoveEvent (QDragMoveEvent *event)
Accepts the drag event if the internal model can accept the mime data.
virtual void dropEvent (QDropEvent *event)
Drops the data into the internal model if it can accept the data.
virtual void moveEvent (QMoveEvent *event)
virtual void resizeEvent (QResizeEvent *event)
virtual void enterEvent (QEvent *event)
Enables actions when cursor enters the view.
virtual void leaveEvent (QEvent *event)
Disables actions when cursor leaves the view.
virtual QList< QAction * > contextMenuActions ()
Returns a list of actions appropriate for a context menu.
virtual ProjectItem * currentItem ()
Returns the current item of the model.
virtual QList< ProjectItem * > selectedItems ()
Return the selected items of the model.
virtual ProjectItemModel * internalModel ()
Returns the internal model of the view.
virtual void setInternalModel (ProjectItemModel *model)
Sets the internal model of the view.
Protected Member Functions
bool eventFilter (QObject *watched, QEvent *event)
Event filter to filter out drag and drop events.
Detailed Description
View for displaying footprints of images in a QMos like way.
Author
2016-01-13 Jeffrey Covington
Constructor & Destructor Documentation
Footprint2DView()
Isis::Footprint2DView::Footprint2DView (Directory * directory, QWidget * parent = 0)
Constructor.
Parameters
parent (QMainWindow *) Pointer to parent QMainWindow
References Isis::MosaicSceneWidget::addTo(), Isis::MosaicSceneWidget::addToPermanent(), createControlPoint(), deleteControlPoint(), Isis::AbstractProjectItemView::disableActions(), Isis::MosaicSceneWidget::getScene(), Isis::MosaicSceneWidget::getView(), Isis::AbstractProjectItemView::internalModel(), modifyControlPoint(), and redrawMeasures().
~Footprint2DView()
Isis::Footprint2DView::~Footprint2DView ()
Destructor.
Member Function Documentation
addItem
void Isis::AbstractProjectItemView::addItem (ProjectItem * item) virtual slot inherited
Adds an item to the view.
The item must be part of the view's model. This method can be overridden in a subclass to filter out unneeded items.
Parameters
[in] item (ProjectItem *) The item to add.
References Isis::AbstractProjectItemView::internalModel().
Referenced by Isis::CubeDnView::addItem().
addItems
void Isis::AbstractProjectItemView::addItems (QList< ProjectItem * > items) virtual slot inherited
Adds several items to the view.
The items must be a part of the view's model. This method can be overridden in a subclass to filter out unneeded items.
Parameters
[in] items (QList<ProjectItem *>) The items to add.
References Isis::AbstractProjectItemView::internalModel().
Referenced by Isis::CubeDnViewWorkOrder::execute(), and Isis::Footprint2DViewWorkOrder::execute().
contextMenuActions()
QList< QAction * > Isis::AbstractProjectItemView::contextMenuActions () virtual inherited
Returns a list of actions appropriate for a context menu.
Returns
QList<QAction *> The actions
controlPointAdded
void Isis::Footprint2DView::controlPointAdded (QString newPointId) signal
createControlPoint
void Isis::Footprint2DView::createControlPoint (double latitude, double longitude) signal
Referenced by Footprint2DView().
currentItem()
ProjectItem * Isis::AbstractProjectItemView::currentItem () virtual inherited
Returns the current item of the model.
Returns
ProjectItem * The item
References Isis::ProjectItemModel::currentItem(), and Isis::AbstractProjectItemView::model().
deleteControlPoint
void Isis::Footprint2DView::deleteControlPoint (ControlPoint * controlPoint) signal
Referenced by Footprint2DView().
disableActions
void Isis::AbstractProjectItemView::disableActions () virtual slot inherited
Disables toolbars and toolpad actions.
Referenced by Isis::CnetEditorView::CnetEditorView(), Footprint2DView(), and Isis::AbstractProjectItemView::leaveEvent().
dragEnterEvent()
void Isis::AbstractProjectItemView::dragEnterEvent (QDragEnterEvent * event) virtual inherited
Accepts the drag enter event if the internal model can accept the mime data.
Parameters
[in] event (QDragEnterEvent *) The drag event
References Isis::AbstractProjectItemView::internalModel().
Referenced by eventFilter().
dragMoveEvent()
void Isis::AbstractProjectItemView::dragMoveEvent (QDragMoveEvent * event) virtual inherited
Accepts the drag event if the internal model can accept the mime data.
Parameters
[in] event (QDragMoveEvent *) The drag event
References Isis::AbstractProjectItemView::internalModel().
Referenced by eventFilter().
dropEvent()
void Isis::AbstractProjectItemView::dropEvent (QDropEvent * event) virtual inherited
Drops the data into the internal model if it can accept the data.
Parameters
[in] event (QDropEvent *) The drop event
References Isis::AbstractProjectItemView::internalModel().
Referenced by eventFilter().
enableControlNetTool
void Isis::Footprint2DView::enableControlNetTool (bool value) slot
A slot function that is called when directory emits a siganl that an active control network is set.
It enables the control network editor tool in the toolpad.
Parameters
value The boolean that holds if a control network has been set.
References Isis::MosaicControlNetTool::loadNetwork().
enterEvent()
void Isis::AbstractProjectItemView::enterEvent (QEvent * event) virtual inherited
Enables actions when cursor enters the view.
Parameters
event The enter event
References Isis::AbstractProjectItemView::enableActions().
eventFilter()
bool Isis::Footprint2DView::eventFilter (QObject * watched, QEvent * event) protected
Event filter to filter out drag and drop events.
Parameters
[in] watched (QObject *) The object being filtered
[in] event (QEvent *) The event
Returns
bool True if the event was intercepted
References Isis::AbstractProjectItemView::dragEnterEvent(), Isis::AbstractProjectItemView::dragMoveEvent(), and Isis::AbstractProjectItemView::dropEvent().
fileListWidget()
ImageFileListWidget * Isis::Footprint2DView::fileListWidget ()
Accessor for the FileListWidget.
internalModel()
ProjectItemModel * Isis::AbstractProjectItemView::internalModel () virtual inherited
Returns the internal model of the view.
By default it is a proxy model.
Returns
ProjectItemModel * The internal model
Referenced by Isis::AbstractProjectItemView::addItem(), Isis::AbstractProjectItemView::addItems(), Isis::CubeDnView::CubeDnView(), Isis::AbstractProjectItemView::dragEnterEvent(), Isis::AbstractProjectItemView::dragMoveEvent(), Isis::AbstractProjectItemView::dropEvent(), Footprint2DView(), Isis::AbstractProjectItemView::model(), Isis::ProjectItemTreeView::ProjectItemTreeView(), Isis::AbstractProjectItemView::removeItem(), Isis::ProjectItemTreeView::setInternalModel(), and Isis::AbstractProjectItemView::setModel().
leaveEvent()
void Isis::AbstractProjectItemView::leaveEvent (QEvent * event) virtual inherited
Disables actions when cursor leaves the view.
Parameters
event The leave event
References Isis::AbstractProjectItemView::disableActions().
model()
ProjectItemModel * Isis::AbstractProjectItemView::model () virtual inherited
Returns the model used by the view.
If the internal model is a proxy model, it returns the source model.
Returns
ProjectItemModel * The model.
References Isis::AbstractProjectItemView::internalModel().
Referenced by Isis::AbstractProjectItemView::currentItem(), Isis::AbstractProjectItemView::selectedItems(), Isis::AbstractProjectItemView::setInternalModel(), Isis::ProjectItemTreeView::setInternalModel(), and Isis::AbstractProjectItemView::setModel().
modifyControlPoint
void Isis::Footprint2DView::modifyControlPoint (ControlPoint * controlPoint) signal
Referenced by Footprint2DView().
mosaicSceneWidget()
MosaicSceneWidget * Isis::Footprint2DView::mosaicSceneWidget ()
Accessor for the MosaicSceneWidget.
Referenced by Isis::Directory::addFootprint2DView().
moveEvent()
void Isis::AbstractProjectItemView::moveEvent (QMoveEvent * event) virtual inherited
References Isis::AbstractProjectItemView::windowChangeEvent().
redrawMeasures
void Isis::Footprint2DView::redrawMeasures () signal
Referenced by Footprint2DView().
removeItem
void Isis::AbstractProjectItemView::removeItem (ProjectItem * item) virtual slot inherited
Removes an item to the view.
The item must be part of the view's model. This method can be overriden in a subclass to filter out unneeded items.
Parameters
[in] item (ProjectItem *) The item to remove.
References Isis::AbstractProjectItemView::internalModel().
Referenced by Isis::AbstractProjectItemView::removeItems().
removeItems
void Isis::AbstractProjectItemView::removeItems (QList< ProjectItem * > items) virtual slot inherited
Removes several items from the view.
The items must be a part of the view's model.
Parameters
[in] items (QList<ProjectItem *>) The items to remove.
References Isis::AbstractProjectItemView::removeItem().
resizeEvent()
void Isis::AbstractProjectItemView::resizeEvent (QResizeEvent * event) virtual inherited
References Isis::AbstractProjectItemView::windowChangeEvent().
save()
void Isis::Footprint2DView::save (QXmlStreamWriter & stream, Project * project, FileName newProjectRoot) const
Save the footprint view widgets (ImageFileListWidget and MosaicSceneWidget to an XML file.
Parameters
stream The XML stream writer
newProjectRoot The FileName of the project this Directory is attached to.
References Isis::ImageFileListWidget::save(), and Isis::MosaicSceneWidget::save().
Referenced by Isis::Directory::save().
selectedItems()
QList< ProjectItem * > Isis::AbstractProjectItemView::selectedItems () virtual inherited
Return the selected items of the model.
Returns
QList<ProjectItem *> The items
References Isis::AbstractProjectItemView::model(), and Isis::ProjectItemModel::selectedItems().
setInternalModel()
void Isis::AbstractProjectItemView::setInternalModel (ProjectItemModel * model) virtual inherited
Sets the internal model of the view.
Parameters
[in] model (ProjectItemModel *) The new internal model
Reimplemented in Isis::ProjectItemTreeView.
References Isis::AbstractProjectItemView::model().
Referenced by Isis::ProjectItemTreeView::setInternalModel().
setModel()
void Isis::AbstractProjectItemView::setModel (ProjectItemModel * model) virtual inherited
Sets the model used by the view.
If the internal model is a proxy model, it sets the source model.
Parameters
[in] model (ProjectItemModel *) The new model
References Isis::AbstractProjectItemView::internalModel(), and Isis::AbstractProjectItemView::model().
Referenced by Isis::Directory::addCubeDnView(), Isis::Directory::addFootprint2DView(), and Isis::Directory::addProjectItemTreeView().
sizeHint()
QSize Isis::AbstractProjectItemView::sizeHint () const virtual inherited
Returns the suggested size.
Returns
QSize The size hint
Reimplemented in Isis::ProjectItemTreeView, and Isis::ControlHealthMonitorView.
windowChangeEvent
void Isis::AbstractProjectItemView::windowChangeEvent (bool event) signal inherited
Referenced by Isis::AbstractProjectItemView::moveEvent(), and Isis::AbstractProjectItemView::resizeEvent().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/Footprint2DView/Footprint2DView.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/Footprint2DView/Footprint2DView.cpp