Isis Developer Reference: Isis::BulletShapeModel Class Reference
Isis::BulletShapeModel Class Reference
Shape model that uses the Bullet library to perform ray tracing.
#include <BulletShapeModel.h>
Public Member Functions
BulletShapeModel ()
Default constructor that creates a shape model without any internal model.
BulletShapeModel (Target *target, Pvl &pvl)
Constructor provided for instantiation from an ISIS cube.
BulletShapeModel (const QString &shapefile, Target *target, Pvl &pvl)
BulletShapeModel (BulletTargetShape *shape, Target *target, Pvl &pvl)
Constructor for creating new shape model from an existing target shape.
BulletShapeModel (BulletWorldManager *model, Target *target, Pvl &pvl)
Constructor for creating a new shape model an existing Bullet World.
~BulletShapeModel ()
Destructor.
double getTolerance () const
Returns the occlusion tolerance in kilometers.
void setTolerance (const double &tolerance)
Sets the occlusion tolerance.
bool intersectSurface (std::vector< double > observerPos, std::vector< double > lookDirection)
This method computes a DEM intercept point given an observer location and look direction using the Bullet model.
virtual bool intersectSurface (const Latitude &lat, const Longitude &lon, const std::vector< double > &observerPos, const bool &checkOcclusion=true)
Compute the intersection at a specified latitude and longitude.
virtual bool intersectSurface (const SurfacePoint &surfpt, const std::vector< double > &observerPos, const bool &checkOcclusion=true)
Compute the intersection at surface point.
virtual void setSurfacePoint (const SurfacePoint &surfacePoint)
Set the internal surface point.
virtual void clearSurfacePoint ()
Clear the saved surface point and reset the saved intersection.
void calculateDefaultNormal ()
Calculate the surface normal of the ellipsoid as the default.
bool isDEM () const
Indicates that this shape model is not from a DEM.
void setLocalNormalFromIntercept ()
Set the normal vector to the intercept point normal.
void calculateLocalNormal (QVector< double * > cornerNeighborPoints)
Compute the normal for a local region of surface points.
void calculateSurfaceNormal ()
compute the ellipsoid surface normal of the target
Distance localRadius (const Latitude &lat, const Longitude &lon)
Compute the radius of the body at a lat/lon point.
QVector< double > ellipsoidNormal ()
Compute the true surface normal vector of an ellipsoid.
const BulletWorldManager & model () const
Returns a direct reference to the Bullet world that contains the target shape and can perform ray casts.
virtual bool isVisibleFrom (const std::vector< double > observerPos, const std::vector< double > lookDirection)
Check if the saved intercept is visible from a observer with a given look direction.
void Initialize ()
Initializes the ShapeModel private variables.
virtual SurfacePoint * surfaceIntersection () const
Returns the surface intersection for this ShapeModel.
bool hasIntersection ()
Returns intersection status.
bool hasNormal () const
Returns surface point normal status.
bool hasLocalNormal () const
Returns surface point local normal status.
virtual double emissionAngle (const std::vector< double > &sB)
Computes and returns emission angle, in degrees, given the observer position.
virtual double incidenceAngle (const std::vector< double > &uB)
Computes and returns incidence angle, in degrees, given the illuminator position.
virtual double phaseAngle (const std::vector< double > &sB, const std::vector< double > &uB)
Computes and returns phase angle, in degrees, given the positions of the observer and illuminator.
QString name () const
Gets the shape name.
void setHasIntersection (bool b)
Sets the flag to indicate whether this ShapeModel has an intersection.
virtual std::vector< double > normal ()
Returns the surface normal at the current intersection point.
virtual std::vector< double > localNormal ()
Returns the local surface normal at the current intersection point.
Protected Member Functions
void setNormal (const std::vector< double >)
Sets the surface normal for the currect intersection point.
void setNormal (const double a, const double b, const double c)
Sets the surface normal for the currect intersection point.
void setLocalNormal (const std::vector< double >)
Sets the local normal for the currect intersection point.
void setLocalNormal (const double a, const double b, const double c)
Sets the local normal for the currect intersection point.
void setName (QString name)
Sets the shape name.
void calculateEllipsoidalSurfaceNormal ()
Calculates the ellipsoidal surface normal.
bool hasEllipsoidIntersection ()
Returns the status of the ellipsoid model intersection.
bool intersectEllipsoid (const std::vector< double > observerPosRelativeToTarget, const std::vector< double > &observerLookVectorToTarget)
Finds the intersection point on the ellipsoid model using the given position of the observer (spacecraft) and direction vector from the observer to the target (body).
bool hasValidTarget () const
Returns the status of the target.
std::vector< Distance > targetRadii () const
Returns the radii of the body in km.
void setHasNormal (bool status)
Sets the flag to indicate whether this ShapeModel has a surface normal.
void setHasLocalNormal (bool status)
Sets the flag to indicate whether this ShapeModel has a local normal.
double resolution ()
Convenience method to get pixel resolution (m/pix) at current intersection point.
Detailed Description
Shape model that uses the Bullet library to perform ray tracing.
Author
2017-03-22 Kris Becker
Constructor & Destructor Documentation
BulletShapeModel() [1/5]
Isis::BulletShapeModel::BulletShapeModel ()
Default constructor that creates a shape model without any internal model.
References Isis::ShapeModel::setName().
BulletShapeModel() [2/5]
Isis::BulletShapeModel::BulletShapeModel (Target * target, Pvl & pvl)
Constructor provided for instantiation from an ISIS cube.
This constructor is typically used for and ISIS cube that has been initialized by spiceinit. The DEM name should be that of a NAIF DSK file. This constructor will throw an exception if it fails to open the DSK file.
Author
2014-02-12 Kris Becker
Parameters
target Target object describing the observed body
pvl ISIS Cube label. Extracts the name of the DEM from the Kernels group
References _FILEINFO_, Isis::PvlObject::findGroup(), Isis::PvlContainer::hasKeyword(), Isis::BulletTargetShape::load(), Isis::ShapeModel::setName(), Isis::PvlObject::Traverse, and Isis::IException::User.
BulletShapeModel() [3/5]
Isis::BulletShapeModel::BulletShapeModel (const QString & shapefile, Target * target, Pvl & pvl)
BulletShapeModel() [4/5]
Isis::BulletShapeModel::BulletShapeModel (BulletTargetShape * shape, Target * target, Pvl & pvl)
Constructor for creating new shape model from an existing target shape.
Parameters
shape The existing target shape to use with this shape model
target Target object describing the observed body
pvl Unused
Author
2014-02-12 Kris Becker
References Isis::BulletTargetShape::name(), and Isis::ShapeModel::setName().
BulletShapeModel() [5/5]
Isis::BulletShapeModel::BulletShapeModel (BulletWorldManager * model, Target * target, Pvl & pvl)
Constructor for creating a new shape model an existing Bullet World.
Assumes the world contains at least one active object
Parameters
model The existing Bullet world model to use
target Target object describing the observed body
pvl Unused
Author
2014-02-12 Kris Becker
~BulletShapeModel()
Isis::BulletShapeModel::~BulletShapeModel ()
Destructor.
Cleanup is handled by Bullet routines and QPointers.
Member Function Documentation
calculateDefaultNormal()
void Isis::BulletShapeModel::calculateDefaultNormal () virtual
Calculate the surface normal of the ellipsoid as the default.
Implements Isis::ShapeModel.
References calculateSurfaceNormal().
calculateEllipsoidalSurfaceNormal()
void Isis::ShapeModel::calculateEllipsoidalSurfaceNormal () protected inherited
Calculates the ellipsoidal surface normal.
References _FILEINFO_.
calculateLocalNormal()
void Isis::BulletShapeModel::calculateLocalNormal (QVector< double * > neighborPoints) virtual
Compute the normal for a local region of surface points.
This method will calculate the surface normal of an assumed very local region of points. This method is provided to fullfil the specs of the ShapeModel class but this approach is not the most efficent means to accomplish this for a pre-exising intercept point. See setLocalNormalFromIntercept() for this.
The ShapeModel class makes the assumption that the four pixel corners of the center intercept point forms a plane from which a surface normal can be computed. For the Naif DSK plate model, we have already identified the plate (see m_intercept) from the DSK plate model (m_model) of the intercept point that provides it directly. That is what setLocalNormalFromIntercept() provides.
So, this implementation will compute the centroid of the neighboring points and make a determination if it intercepts the current intercept plate as defined by m_intercept - if it is valid. If it does not exist or does not intercept the plate, a new intercept point is computed and returned here.
Author
2017-03-27 Kris Becker
Parameters
neighborPoints Input body-fixed points to compute normal for
Implements Isis::ShapeModel.
References _FILEINFO_, Isis::ShapeModel::hasIntersection(), Isis::IException::Programmer, and setLocalNormalFromIntercept().
calculateSurfaceNormal()
void Isis::BulletShapeModel::calculateSurfaceNormal () virtual
compute the ellipsoid surface normal of the target
Implements Isis::ShapeModel.
References ellipsoidNormal(), and Isis::ShapeModel::setNormal().
Referenced by calculateDefaultNormal().
clearSurfacePoint()
void Isis::BulletShapeModel::clearSurfacePoint () virtual
Clear the saved surface point and reset the saved intersection.
Reimplemented from Isis::ShapeModel.
Referenced by intersectSurface().
ellipsoidNormal()
QVector< double > Isis::BulletShapeModel::ellipsoidNormal ()
Compute the true surface normal vector of an ellipsoid.
This routine is used instead of the one provided by the ShapeModel implementation. This is primarly because ShapeModel::calculateEllipsoidalSurfaceNormal() is only suitable for a spheroid. This implementation is intended for irregular bodies so we expect triaxial ellipsoids.
Author
2017-03-27 Kris Becker
Returns
QVector<double> Normal vector at the intercept point relative to the ellipsoid (not the plate model)
References _FILEINFO_, Isis::NaifStatus::CheckErrors(), Isis::ShapeModel::hasIntersection(), Isis::ShapeModel::hasValidTarget(), Isis::IException::Programmer, Isis::ShapeModel::surfaceIntersection(), Isis::ShapeModel::targetRadii(), and Isis::SurfacePoint::ToNaifArray().
Referenced by calculateSurfaceNormal().
emissionAngle()
double Isis::ShapeModel::emissionAngle (const std::vector< double > & observerBodyFixedPosition) virtual inherited
Computes and returns emission angle, in degrees, given the observer position.
Emission Angle: The angle between the surface normal vector at the intersection point and the vector from the intersection point to the observer (usually the spacecraft). The emission angle varies from 0 degrees when the observer is viewing the sub-spacecraft point (nadir viewing) to 90 degrees when the intercept is tangent to the surface of the target body. Thus, higher values of emission angle indicate more oblique viewing of the target.
Parameters
observerBodyFixedPosition Three dimensional position of the observer, in the coordinate system of the target body.
Returns
The emission angle, in decimal degrees.
Reimplemented in Isis::PlaneShape.
References Isis::RAD2DEG.
Referenced by Isis::CSMCamera::EmissionAngle(), and Isis::Sensor::EmissionAngle().
getTolerance()
double Isis::BulletShapeModel::getTolerance () const
Returns the occlusion tolerance in kilometers.
Returns
double The occlusion tolerance in kilometers.
Referenced by isVisibleFrom().
hasEllipsoidIntersection()
bool Isis::ShapeModel::hasEllipsoidIntersection () protected inherited
Returns the status of the ellipsoid model intersection.
Returns
bool Indicates whether this shape model has a valid ellipsoid intersection.
hasIntersection()
bool Isis::ShapeModel::hasIntersection () inherited
Returns intersection status.
Returns
bool Indicates whether this ShapeModel has an intersection.
Referenced by Isis::DemShape::calculateDefaultNormal(), calculateLocalNormal(), Isis::EllipsoidShape::calculateLocalNormal(), Isis::EmbreeShapeModel::calculateLocalNormal(), Isis::NaifDskShape::calculateLocalNormal(), ellipsoidNormal(), Isis::EmbreeShapeModel::ellipsoidNormal(), Isis::NaifDskShape::ellipsoidNormal(), Isis::Camera::GetLocalNormal(), Isis::Sensor::HasSurfaceIntersection(), intersectSurface(), Isis::DemShape::intersectSurface(), Isis::EmbreeShapeModel::intersectSurface(), Isis::EquatorialCylindricalShape::intersectSurface(), Isis::CSMCamera::SetGround(), setLocalNormalFromIntercept(), Isis::NaifDskShape::setLocalNormalFromIntercept(), and Isis::Camera::Slope().
hasLocalNormal()
bool Isis::ShapeModel::hasLocalNormal () const inherited
Returns surface point local normal status.
Returns
Indicates whether this ShapeModel has a surface normal.
Referenced by Isis::Camera::GetLocalNormal().
hasNormal()
bool Isis::ShapeModel::hasNormal () const inherited
Returns surface point normal status.
Returns
Indicates whether this ShapeModel has a surface normal.
Referenced by Isis::EmbreeShapeModel::incidenceAngle(), and Isis::Camera::Slope().
hasValidTarget()
bool Isis::ShapeModel::hasValidTarget () const protected inherited
Returns the status of the target.
If it is NULL, this method returns false.
Returns
Indicates whether the target is valid.
Referenced by ellipsoidNormal(), Isis::EmbreeShapeModel::ellipsoidNormal(), and Isis::NaifDskShape::ellipsoidNormal().
incidenceAngle()
double Isis::ShapeModel::incidenceAngle (const std::vector< double > & illuminatorBodyFixedPosition) virtual inherited
Computes and returns incidence angle, in degrees, given the illuminator position.
Incidence Angle: The angle between the surface normal vector at the intersection point and the vector from the intersection point to the illuminator (usually the sun).
Note: this method does not use the surface model.
Parameters
illuminatorBodyFixedPosition Three dimensional position for the illuminator, in the body-fixed coordinate system.
Returns
double Incidence angle, in degrees.
Reimplemented in Isis::PlaneShape, and Isis::EmbreeShapeModel.
References Isis::RAD2DEG.
Referenced by Isis::CSMCamera::IncidenceAngle(), Isis::Sensor::IncidenceAngle(), and Isis::EmbreeShapeModel::incidenceAngle().
Initialize()
void Isis::ShapeModel::Initialize () inherited
Initializes the ShapeModel private variables.
intersectEllipsoid()
bool Isis::ShapeModel::intersectEllipsoid (const std::vector< double > observerBodyFixedPosition, const std::vector< double > & observerLookVectorToTarget) protected inherited
Finds the intersection point on the ellipsoid model using the given position of the observer (spacecraft) and direction vector from the observer to the target (body).
Parameters
observerBodyFixedPosition Three dimensional position of the observer, in the coordinate system of the target body.
observerLookVectorToTarget Three dimensional direction vector from the observer to the target.
Returns
bool Indicates whether this shape model found a valid ellipsoid intersection.
Referenced by Isis::DemShape::intersectSurface(), and Isis::EllipsoidShape::intersectSurface().
intersectSurface() [1/3]
bool Isis::BulletShapeModel::intersectSurface (const Latitude & lat, const Longitude & lon, const std::vector< double > & observerPos, const bool & checkOcclusion = true) virtual
Compute the intersection at a specified latitude and longitude.
The intersection can also be checked for occlusion from an observer.
If more than one intersection exist at the latitude and longitude, then the intersection closest to the observer is saved. If occlusion is being checked, then the closest non-occluded intersection is saved.
Author
2017-03-27 Kris Becker
Parameters
lat The latitude to compute the intersection at.
lon The longitude to compute the intersection at.
observerPos The observer used for occlusion and deciding between multiple intersections.
checkOcclusion If occlusion should be checked.
Returns
bool If an intersection was found and saved.
Reimplemented from Isis::ShapeModel.
References clearSurfacePoint(), and Isis::ShapeModel::hasIntersection().
intersectSurface() [2/3]
bool Isis::BulletShapeModel::intersectSurface (const SurfacePoint & surfpt, const std::vector< double > & observerPos, const bool & checkOcclusion = true) virtual
Compute the intersection at surface point.
The intersection can also be checked for occlusion from an observer.
The intersection is found by casting a ray from the center of the body through the surface point. If multiple intersections are found, then the intersection closest to the surface point is saved. If occlusion is being checked, then the closest non-occluded point is saved.
Author
2017-03-27 Kris Becker
Parameters
surfpt Surface point to find the intersection at
observerPos The observer used for occlusion and deciding between multiple intersections.
checkOcclusion If occlusion should be checked.
Returns
bool If an intersection was found and saved.
Reimplemented from Isis::ShapeModel.
References clearSurfacePoint(), and Isis::ShapeModel::hasIntersection().
intersectSurface() [3/3]
bool Isis::BulletShapeModel::intersectSurface (std::vector< double > observerPos, std::vector< double > lookDirection) virtual
This method computes a DEM intercept point given an observer location and look direction using the Bullet model.
Author
2014-02-13 Kris Becker
Parameters
observerPos Position of observer in body fixed coordiates
lookDirection Look direction (ray) from the observer
Returns
bool If an intersection was found and saved.
Implements Isis::ShapeModel.
References clearSurfacePoint().
Referenced by setSurfacePoint().
isDEM()
bool Isis::BulletShapeModel::isDEM () const virtual
Indicates that this shape model is not from a DEM.
Since this method returns false for this class, the Camera class will not calculate the local normal using neighbor points.
Returns
bool Indicates that this is not a DEM shape model.
Implements Isis::ShapeModel.
isVisibleFrom()
bool Isis::BulletShapeModel::isVisibleFrom (const std::vector< double > observerPos, const std::vector< double > lookDirection) virtual
Check if the saved intercept is visible from a observer with a given look direction.
Parameters
observerPos The position of the observer in body-fixed kilometers.
lookDirection The observer look direction inf body-fixed coordinates.
Returns
bool If the saved intercept is visible.
Reimplemented from Isis::ShapeModel.
References getTolerance(), Isis::BulletClosestRayCallback::isValid(), Isis::BulletClosestRayCallback::isVisible(), Isis::BulletClosestRayCallback::normal(), Isis::BulletClosestRayCallback::point(), and Isis::RAD2DEG.
localNormal()
std::vector< double > Isis::ShapeModel::localNormal () virtual inherited
Returns the local surface normal at the current intersection point.
Note: This method will throw an error if the normal doesn't exist. Use the hasLocalNormal() method to verify before calling this method.
See also
hasLocalNormal()
Returns
A local surface normal vector, if it exists.
References _FILEINFO_.
Referenced by Isis::EllipsoidShape::calculateSurfaceNormal(), Isis::Camera::GetLocalNormal(), and Isis::EmbreeShapeModel::incidenceAngle().
localRadius()
Distance Isis::BulletShapeModel::localRadius (const Latitude & lat, const Longitude & lon) virtual
Compute the radius of the body at a lat/lon point.
A ray is cast from the center of the body through the lat/lon point. The intersection closest to the center of the body is used to compute the radius.
NOTE this call does not update the internal state of the intercept point. Use intersectSurface(lat, lon) for that.
Author
2017-03-27 Kris Becker
Parameters
lat Latitude coordinate of grid point
lon Longitude coordinate of grid point
Returns
Distance Radius value of the intercept grid point. If no intersection is found, a default, invalid, Distance object is returned.
Implements Isis::ShapeModel.
References Isis::BulletAllHitsRayCallback::hit(), Isis::Distance::Kilometers, and Isis::BulletClosestRayCallback::point().
model()
const BulletWorldManager & Isis::BulletShapeModel::model () const
Returns a direct reference to the Bullet world that contains the target shape and can perform ray casts.
name()
QString Isis::ShapeModel::name () const inherited
Gets the shape name.
Returns
QString The name of the ShapeModel.
Referenced by Isis::UniversalGroundMap::GroundRange(), Isis::VimsGroundMap::SetGround(), Isis::Camera::SetGround(), and Isis::CSMCamera::SetGround().
normal()
std::vector< double > Isis::ShapeModel::normal () virtual inherited
Returns the surface normal at the current intersection point.
Note: This method will throw an error if the normal doesn't exist. Use the hasNormal() method to verify before calling this method.
See also
hasNormal()
Returns
A surface normal vector, if it exists.
References _FILEINFO_.
Referenced by Isis::DemShape::calculateDefaultNormal(), Isis::DemShape::calculateLocalNormal(), Isis::EllipsoidShape::calculateLocalNormal(), Isis::EmbreeShapeModel::incidenceAngle(), setLocalNormalFromIntercept(), and Isis::Camera::Slope().
phaseAngle()
double Isis::ShapeModel::phaseAngle (const std::vector< double > & observerBodyFixedPosition, const std::vector< double > & illuminatorBodyFixedPosition) virtual inherited
Computes and returns phase angle, in degrees, given the positions of the observer and illuminator.
Phase Angle: The angle between the vector from the intersection point to the observer (usually the spacecraft) and the vector from the intersection point to the illuminator (usually the sun).
Parameters
observerBodyFixedPosition Three dimensional position of the observer, in the coordinate system of the target body.
illuminatorBodyFixedPosition Three dimensional position for the illuminator, in the body-fixed coordinate system.
Returns
double Phase angle, in degrees.
References Isis::RAD2DEG.
Referenced by Isis::CSMCamera::PhaseAngle().
resolution()
double Isis::ShapeModel::resolution () protected inherited
Convenience method to get pixel resolution (m/pix) at current intersection point.
Returns
@double The pixel resolution at the surface intersection.
References _FILEINFO_.
Referenced by Isis::DemShape::intersectSurface().
setHasIntersection()
void Isis::ShapeModel::setHasIntersection (bool b) inherited
Sets the flag to indicate whether this ShapeModel has an intersection.
Parameters
b Indicates whether there is an intersection.
Referenced by Isis::DemShape::intersectSurface(), Isis::EmbreeShapeModel::intersectSurface(), Isis::EquatorialCylindricalShape::intersectSurface(), Isis::PlaneShape::intersectSurface(), Isis::CSMCamera::SetGround(), Isis::CSMCamera::SetImage(), Isis::Sensor::SetLookDirection(), and Isis::CSMCamera::SetLookDirection().
setHasLocalNormal()
void Isis::ShapeModel::setHasLocalNormal (bool status) protected inherited
Sets the flag to indicate whether this ShapeModel has a local normal.
Parameters
status Indicates whether there is a normal.
Referenced by Isis::DemShape::calculateLocalNormal(), Isis::EllipsoidShape::calculateLocalNormal(), and Isis::EmbreeShapeModel::clearSurfacePoint().
setHasNormal()
void Isis::ShapeModel::setHasNormal (bool status) protected inherited
Sets the flag to indicate whether this ShapeModel has a surface normal.
Parameters
status Indicates whether there is a normal.
Referenced by Isis::DemShape::calculateDefaultNormal(), and Isis::EmbreeShapeModel::clearSurfacePoint().
setLocalNormal() [1/2]
void Isis::ShapeModel::setLocalNormal (const double a, const double b, const double c) protected inherited
Sets the local normal for the currect intersection point.
Note: This method will throw an error if this ShapeModel doesn't have and intersection. Use the hasIntersection() method to verify before calling this method.
See also
hasIntersection()
Parameters
a First coordinate value for the three dimensional local normal.
b Second coordinate value for the three dimensional local normal.
c Third coordinate value for the three dimensional local normal.
References _FILEINFO_.
setLocalNormal() [2/2]
void Isis::ShapeModel::setLocalNormal (const std::vector< double > normal) protected inherited
Sets the local normal for the currect intersection point.
Note: This method will throw an error if this ShapeModel doesn't have an intersection. Use the hasIntersection() method to verify before calling this method.
See also
hasIntersection()
Parameters
normal Three dimensional local normal vector.
References _FILEINFO_.
Referenced by Isis::DemShape::calculateLocalNormal(), Isis::EllipsoidShape::calculateLocalNormal(), setLocalNormalFromIntercept(), and Isis::NaifDskShape::setLocalNormalFromIntercept().
setLocalNormalFromIntercept()
void Isis::BulletShapeModel::setLocalNormalFromIntercept ()
Set the normal vector to the intercept point normal.
This method will reassign the ShapeModel normal to the current intercept point shape (which is a triangular plate) normal. If an intercept point is not defined, an error will ensue.
Author
2017-03-27 Kris Becker
References _FILEINFO_, Isis::ShapeModel::hasIntersection(), Isis::ShapeModel::normal(), Isis::BulletClosestRayCallback::normal(), Isis::IException::Programmer, and Isis::ShapeModel::setLocalNormal().
Referenced by calculateLocalNormal().
setName()
void Isis::ShapeModel::setName (QString name) protected inherited
Sets the shape name.
Parameters
name The name of the ShapeModel.
Referenced by BulletShapeModel(), Isis::DemShape::DemShape(), Isis::EllipsoidShape::EllipsoidShape(), Isis::EmbreeShapeModel::EmbreeShapeModel(), Isis::EquatorialCylindricalShape::EquatorialCylindricalShape(), Isis::NaifDskShape::NaifDskShape(), and Isis::PlaneShape::PlaneShape().
setNormal() [1/2]
void Isis::ShapeModel::setNormal (const double a, const double b, const double c) protected inherited
Sets the surface normal for the currect intersection point.
Note: This method will throw an error if this ShapeModel doesn't have and intersection. Use the hasIntersection() method to verify before calling this method.
See also
hasIntersection()
Parameters
a First coordinate value for the three dimensional surface normal.
b Second coordinate value for the three dimensional surface normal.
c Third coordinate value for the three dimensional surface normal.
References _FILEINFO_.
setNormal() [2/2]
void Isis::ShapeModel::setNormal (const std::vector< double > normal) protected inherited
Sets the surface normal for the currect intersection point.
Note: This method will throw an error if this ShapeModel doesn't have an intersection. Use the hasIntersection() method to verify before calling this method.
See also
hasIntersection()
Parameters
normal Three dimensional surface normal vector.
References _FILEINFO_.
Referenced by Isis::DemShape::calculateDefaultNormal(), calculateSurfaceNormal(), Isis::EllipsoidShape::calculateSurfaceNormal(), Isis::EmbreeShapeModel::calculateSurfaceNormal(), Isis::NaifDskShape::calculateSurfaceNormal(), Isis::EmbreeShapeModel::incidenceAngle(), and Isis::PlaneShape::intersectSurface().
setSurfacePoint()
void Isis::BulletShapeModel::setSurfacePoint (const SurfacePoint & surfacePoint) virtual
Set the internal surface point.
A new intersection based on the surface point will be computed and saved.
Parameters
surfacePoint The new surface point
Reimplemented from Isis::ShapeModel.
References intersectSurface().
setTolerance()
void Isis::BulletShapeModel::setTolerance (const double & tolerance)
Sets the occlusion tolerance.
Parameters
tolerance The new occlusion tolerance in kilometers.
Referenced by Isis::ShapeModelFactory::create().
surfaceIntersection()
SurfacePoint * Isis::ShapeModel::surfaceIntersection () const virtual inherited
Returns the surface intersection for this ShapeModel.
Returns
SurfacePoint Three dimensional position for the surface intersection, in body-fixed coordinate system.
Referenced by Isis::DemShape::calculateDefaultNormal(), Isis::DemShape::calculateLocalNormal(), Isis::EllipsoidShape::calculateLocalNormal(), Isis::Sensor::Coordinate(), ellipsoidNormal(), Isis::EmbreeShapeModel::ellipsoidNormal(), Isis::NaifDskShape::ellipsoidNormal(), Isis::PlaneShape::emissionAngle(), Isis::Sensor::GetLatitude(), Isis::Sensor::GetLongitude(), Isis::Sensor::GetSurfacePoint(), Isis::PlaneShape::incidenceAngle(), Isis::DemShape::intersectSurface(), Isis::EquatorialCylindricalShape::intersectSurface(), Isis::PlaneShape::intersectSurface(), Isis::EmbreeShapeModel::isVisibleFrom(), Isis::Sensor::LocalRadius(), Isis::PlaneShape::localRadius(), Isis::Sensor::SlantDistance(), and Isis::Sensor::SolarDistance().
targetRadii()
std::vector< Distance > Isis::ShapeModel::targetRadii () const protected inherited
Returns the radii of the body in km.
The radii are obtained from the target. Note: This method will throw an error if the ShapeModel does not have a valid target. Use the hasValidTarget() method to verify before calling this method.
See also
hasValidTarget()
Returns
Three dimensional vector containing the ellipsoid radii values.
References _FILEINFO_.
Referenced by Isis::DemShape::calculateDefaultNormal(), Isis::EllipsoidShape::calculateLocalNormal(), ellipsoidNormal(), Isis::EmbreeShapeModel::ellipsoidNormal(), Isis::NaifDskShape::ellipsoidNormal(), Isis::EquatorialCylindricalShape::intersectSurface(), and Isis::EllipsoidShape::localRadius().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/BulletShapeModel/BulletShapeModel.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/BulletShapeModel/BulletShapeModel.cpp