Isis Developer Reference: Isis::AbstractNullDataItem Class Reference
Isis::AbstractNullDataItem Class Reference abstract
Base class for an item without data.
#include <AbstractNullDataItem.h>
Public Types
enum InternalPointerType { None , Point , Measure , ImageAndNet }
Public Member Functions
AbstractNullDataItem (AbstractTreeItem *parent=0)
virtual ~AbstractNullDataItem ()
virtual QVariant getData () const
virtual QVariant getData (QString columnTitle) const
virtual void setData (QString const &columnTitle, QString const &newData)
virtual bool isDataEditable (QString columnTitle) const
virtual void deleteSource ()
virtual InternalPointerType getPointerType () const
virtual void * getPointer () const
virtual bool operator< (AbstractTreeItem const &other) const
AbstractTreeItem * parent () const
void setParent (AbstractTreeItem *newParent)
int row () const
virtual void addChild (AbstractTreeItem *child)=0
virtual QList< AbstractTreeItem * > getChildren () const =0
virtual AbstractTreeItem * childAt (int row) const =0
virtual int childCount () const =0
virtual AbstractTreeItem * getFirstVisibleChild () const =0
virtual AbstractTreeItem * getLastVisibleChild () const =0
virtual int indexOf (AbstractTreeItem *child) const =0
virtual void setFirstVisibleChild (AbstractTreeItem *child)=0
virtual void setLastVisibleChild (AbstractTreeItem *child)=0
virtual QString getFormattedData () const
virtual QString getFormattedData (QString columnTitle) const
virtual bool hasMeasure (ControlMeasure *) const
virtual bool hasImage (QString imageSerial) const
virtual bool hasPoint (ControlPoint *) const
virtual AbstractTreeItem * getNextVisiblePeer () const
virtual void setNextVisiblePeer (AbstractTreeItem *next)
virtual void setExpanded (bool newState)
virtual bool isExpanded () const
virtual void setSelected (bool newState)
virtual void setSelectable (bool newSelectable)
virtual bool isSelected () const
virtual bool isSelectable () const
virtual void setVisible (bool newState)
virtual bool isVisible () const
virtual int getDataWidth () const
virtual int getDepth () const
virtual void setLastVisibleFilteredItem (AbstractTreeItem *item)
virtual const AbstractTreeItem * getLastVisibleFilteredItem () const
Protected Member Functions
virtual void sourceDeleted ()
virtual void calcDataWidth (int avgCharWidth)
Static Protected Member Functions
static double catchNull (QString)
static QString catchNull (QVariant)
Detailed Description
Base class for an item without data.
This class represents an item in the tree that has no data. For example, RootItem and BusyLeafItem are two types of items that do not have any data.
Author
????-??-?? Eric Hyer
Member Enumeration Documentation
InternalPointerType
enum Isis::AbstractTreeItem::InternalPointerType inherited
Enumerator
None
Point
Measure
ImageAndNet
Constructor & Destructor Documentation
AbstractNullDataItem()
Isis::AbstractNullDataItem::AbstractNullDataItem (AbstractTreeItem * parent = 0)
~AbstractNullDataItem()
Isis::AbstractNullDataItem::~AbstractNullDataItem () virtual
Member Function Documentation
addChild()
virtual void Isis::AbstractTreeItem::addChild (AbstractTreeItem * child) pure virtual inherited
Implemented in Isis::PointParentItem, Isis::ConnectionParentItem, Isis::AbstractParentItem, and Isis::AbstractLeafItem.
calcDataWidth()
void Isis::AbstractTreeItem::calcDataWidth (int avgCharWidth) protected virtual inherited
References _FILEINFO_, Isis::AbstractTreeItem::getFormattedData(), and Isis::IException::Programmer.
Referenced by Isis::AbstractImageItem::AbstractImageItem(), Isis::AbstractMeasureItem::AbstractMeasureItem(), Isis::AbstractPointItem::AbstractPointItem(), and Isis::BusyLeafItem::BusyLeafItem().
catchNull() [1/2]
double Isis::AbstractTreeItem::catchNull (QString str) static protected inherited
References Isis::Null.
Referenced by Isis::AbstractTreeItem::getFormattedData(), Isis::AbstractMeasureItem::setData(), and Isis::AbstractPointItem::setData().
catchNull() [2/2]
QString Isis::AbstractTreeItem::catchNull (QVariant data) static protected inherited
References Isis::Double, and Isis::Null.
childAt()
virtual AbstractTreeItem* Isis::AbstractTreeItem::childAt (int row) const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::AbstractTreeItem::hasImage(), Isis::AbstractTreeItem::hasMeasure(), and Isis::AbstractTreeItem::hasPoint().
childCount()
virtual int Isis::AbstractTreeItem::childCount () const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::AbstractTreeItem::hasImage(), Isis::AbstractTreeItem::hasMeasure(), and Isis::AbstractTreeItem::hasPoint().
deleteSource()
void Isis::AbstractNullDataItem::deleteSource () virtual
Implements Isis::AbstractTreeItem.
References _FILEINFO_, and Isis::IException::Programmer.
getChildren()
virtual QList< AbstractTreeItem * > Isis::AbstractTreeItem::getChildren () const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::TableViewContent::mouseMoveEvent(), Isis::TableViewContent::mousePressEvent(), and Isis::TreeViewContent::mousePressEvent().
getData() [1/2]
QVariant Isis::AbstractNullDataItem::getData () const virtual
Implements Isis::AbstractTreeItem.
Reimplemented in Isis::BusyLeafItem.
getData() [2/2]
QVariant Isis::AbstractNullDataItem::getData (QString columnTitle) const virtual
Implements Isis::AbstractTreeItem.
getDataWidth()
int Isis::AbstractTreeItem::getDataWidth () const virtual inherited
References _FILEINFO_, and Isis::IException::Programmer.
Referenced by Isis::AbstractTreeModel::getVisibleSize().
getDepth()
int Isis::AbstractTreeItem::getDepth () const virtual inherited
References Isis::AbstractTreeItem::parent().
Referenced by Isis::AbstractTreeModel::getVisibleSize().
getFirstVisibleChild()
virtual AbstractTreeItem* Isis::AbstractTreeItem::getFirstVisibleChild () const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::TreeViewContent::mouseMoveEvent(), and Isis::TreeViewContent::mousePressEvent().
getFormattedData() [1/2]
QString Isis::AbstractTreeItem::getFormattedData () const virtual inherited
References Isis::AbstractTreeItem::catchNull(), and Isis::AbstractTreeItem::getData().
Referenced by Isis::AbstractTreeItem::calcDataWidth(), Isis::AbstractMeasureItem::deleteSource(), Isis::AbstractPointItem::deleteSource(), Isis::MeasureTableModel::getMeasureWarningMessage(), Isis::PointTableModel::getPointWarningMessage(), Isis::MeasureTableDelegate::readData(), and Isis::PointTableDelegate::readData().
getFormattedData() [2/2]
QString Isis::AbstractTreeItem::getFormattedData (QString columnTitle) const virtual inherited
References Isis::AbstractTreeItem::catchNull(), and Isis::AbstractTreeItem::getData().
getLastVisibleChild()
virtual AbstractTreeItem* Isis::AbstractTreeItem::getLastVisibleChild () const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::AbstractTreeModel::getItems().
getLastVisibleFilteredItem()
const AbstractTreeItem * Isis::AbstractTreeItem::getLastVisibleFilteredItem () const virtual inherited
Reimplemented in Isis::RootItem.
getNextVisiblePeer()
AbstractTreeItem * Isis::AbstractTreeItem::getNextVisiblePeer () const virtual inherited
Referenced by Isis::AbstractTreeModel::getVisibleTopLevelItemCount().
getPointer()
void * Isis::AbstractNullDataItem::getPointer () const virtual
Implements Isis::AbstractTreeItem.
getPointerType()
AbstractTreeItem::InternalPointerType Isis::AbstractNullDataItem::getPointerType () const virtual
Implements Isis::AbstractTreeItem.
References Isis::AbstractTreeItem::None.
hasImage()
bool Isis::AbstractTreeItem::hasImage (QString imageSerial) const virtual inherited
Reimplemented in Isis::AbstractImageItem.
References Isis::AbstractTreeItem::childAt(), Isis::AbstractTreeItem::childCount(), and Isis::AbstractTreeItem::hasImage().
Referenced by Isis::AbstractImageItem::hasImage(), and Isis::AbstractTreeItem::hasImage().
hasMeasure()
bool Isis::AbstractTreeItem::hasMeasure (ControlMeasure * measure) const virtual inherited
Reimplemented in Isis::AbstractMeasureItem.
References Isis::AbstractTreeItem::childAt(), Isis::AbstractTreeItem::childCount(), and Isis::AbstractTreeItem::hasMeasure().
Referenced by Isis::AbstractTreeItem::hasMeasure().
hasPoint()
bool Isis::AbstractTreeItem::hasPoint (ControlPoint * point) const virtual inherited
Reimplemented in Isis::AbstractPointItem.
References Isis::AbstractTreeItem::childAt(), Isis::AbstractTreeItem::childCount(), and Isis::AbstractTreeItem::hasPoint().
Referenced by Isis::AbstractTreeItem::hasPoint().
indexOf()
virtual int Isis::AbstractTreeItem::indexOf (AbstractTreeItem * child) const pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
Referenced by Isis::AbstractTreeItem::row().
isDataEditable()
bool Isis::AbstractNullDataItem::isDataEditable (QString columnTitle) const virtual
Implements Isis::AbstractTreeItem.
isExpanded()
bool Isis::AbstractTreeItem::isExpanded () const virtual inherited
Referenced by Isis::TreeViewContent::mouseDoubleClickEvent(), and Isis::TreeViewContent::mouseReleaseEvent().
isSelectable()
bool Isis::AbstractTreeItem::isSelectable () const virtual inherited
Reimplemented in Isis::BusyLeafItem.
Referenced by Isis::TreeViewContent::mouseMoveEvent(), and Isis::TreeViewContent::mousePressEvent().
isSelected()
bool Isis::AbstractTreeItem::isSelected () const virtual inherited
Referenced by Isis::AbstractTreeModel::getSelectedItems(), Isis::TableViewContent::mousePressEvent(), and Isis::TreeViewContent::mousePressEvent().
isVisible()
bool Isis::AbstractTreeItem::isVisible () const virtual inherited
operator<()
bool Isis::AbstractNullDataItem::operator< (AbstractTreeItem const & other) const virtual
References _FILEINFO_, and Isis::IException::Programmer.
parent()
AbstractTreeItem * Isis::AbstractTreeItem::parent () const inherited
Referenced by Isis::AbstractTreeItem::getDepth(), Isis::AbstractTreeModel::getItems(), Isis::PointTableModel::handleTreeSelectionChanged(), and Isis::TableViewContent::mousePressEvent().
row()
int Isis::AbstractTreeItem::row () const inherited
References Isis::AbstractTreeItem::indexOf().
Referenced by Isis::AbstractParentItem::childAt().
setData()
void Isis::AbstractNullDataItem::setData (QString const & columnTitle, QString const & newData) virtual
Implements Isis::AbstractTreeItem.
References _FILEINFO_, and Isis::IException::Programmer.
setExpanded()
void Isis::AbstractTreeItem::setExpanded (bool newState) virtual inherited
Referenced by Isis::TreeViewContent::mouseDoubleClickEvent(), Isis::TreeViewContent::mouseReleaseEvent(), and Isis::RootItem::RootItem().
setFirstVisibleChild()
virtual void Isis::AbstractTreeItem::setFirstVisibleChild (AbstractTreeItem * child) pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
setLastVisibleChild()
virtual void Isis::AbstractTreeItem::setLastVisibleChild (AbstractTreeItem * child) pure virtual inherited
Implemented in Isis::AbstractParentItem, and Isis::AbstractLeafItem.
setLastVisibleFilteredItem()
void Isis::AbstractTreeItem::setLastVisibleFilteredItem (AbstractTreeItem * item) virtual inherited
Reimplemented in Isis::RootItem.
References _FILEINFO_, and Isis::IException::Programmer.
setNextVisiblePeer()
void Isis::AbstractTreeItem::setNextVisiblePeer (AbstractTreeItem * next) virtual inherited
setParent()
void Isis::AbstractTreeItem::setParent (AbstractTreeItem * newParent) inherited
Referenced by Isis::AbstractParentItem::addChild().
setSelectable()
void Isis::AbstractTreeItem::setSelectable (bool newSelectable) virtual inherited
setSelected()
void Isis::AbstractTreeItem::setSelected (bool newState) virtual inherited
Referenced by Isis::TableViewContent::mouseMoveEvent(), Isis::TableViewContent::mousePressEvent(), and Isis::TreeViewContent::mousePressEvent().
setVisible()
void Isis::AbstractTreeItem::setVisible (bool newState) virtual inherited
sourceDeleted()
void Isis::AbstractNullDataItem::sourceDeleted () protected virtual
Implements Isis::AbstractTreeItem.
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/AbstractNullDataItem.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/AbstractNullDataItem.cpp