Isis Developer Reference: Isis::TableColumnList Class Reference
Isis::TableColumnList Class Reference
#include <TableColumnList.h>
Signals
void sortOutDated ()
Public Member Functions
TableColumnList ()
TableColumnList (TableColumnList const &)
virtual ~TableColumnList ()
TableColumn *& operator[] (int index)
TableColumn *& operator[] (QString title)
void append (TableColumn *newCol)
void prepend (TableColumn *newCol)
int indexOf (TableColumn const *someCol) const
bool contains (TableColumn const *someCol) const
bool contains (QString columnTitle) const
QPair< int, int > getVisibleXRange (int visibleColumn)
TableColumnList getVisibleColumns ()
int getVisibleWidth () const
QList< TableColumn * > getSortingOrder ()
QStringList getSortingOrderAsStrings () const
void setSortingOrder (QStringList newOrder)
void lower (TableColumn *col, bool emitSortOutDated=true)
void raise (TableColumn *col, bool emitSortOutDated=true)
void raiseToTop (TableColumn *col)
int size () const
TableColumnList & operator= (TableColumnList other)
Detailed Description
Author
????-??-?? Unknown
Constructor & Destructor Documentation
TableColumnList() [1/2]
Isis::TableColumnList::TableColumnList ()
TableColumnList() [2/2]
Isis::TableColumnList::TableColumnList (TableColumnList const & other)
~TableColumnList()
Isis::TableColumnList::~TableColumnList () virtual
Member Function Documentation
append()
void Isis::TableColumnList::append (TableColumn * newCol)
References _FILEINFO_, Isis::IException::Programmer, and sortOutDated().
Referenced by Isis::AbstractMeasureItem::createColumns(), Isis::AbstractPointItem::createColumns(), and getVisibleColumns().
contains() [1/2]
bool Isis::TableColumnList::contains (QString columnTitle) const
contains() [2/2]
bool Isis::TableColumnList::contains (TableColumn const * someCol) const
References indexOf().
Referenced by getVisibleColumns(), and setSortingOrder().
getSortingOrder()
QList< TableColumn * > Isis::TableColumnList::getSortingOrder ()
Referenced by Isis::TableViewHeader::mouseMoveEvent(), Isis::TableViewHeader::mouseReleaseEvent(), and Isis::AbstractTableModel::sort().
getSortingOrderAsStrings()
QStringList Isis::TableColumnList::getSortingOrderAsStrings () const
Referenced by Isis::TableView::~TableView().
getVisibleColumns()
TableColumnList Isis::TableColumnList::getVisibleColumns ()
References append(), contains(), and size().
Referenced by getVisibleXRange(), Isis::TableViewHeader::handleFilterCountsChanged(), Isis::TableViewContent::keyPressEvent(), Isis::TableViewContent::mouseDoubleClickEvent(), Isis::TableViewHeader::mouseMoveEvent(), Isis::TableViewContent::mousePressEvent(), Isis::TableViewHeader::mousePressEvent(), Isis::TableViewHeader::mouseReleaseEvent(), and Isis::TableViewContent::updateHorizontalScrollBar().
getVisibleWidth()
int Isis::TableColumnList::getVisibleWidth () const
References size().
Referenced by Isis::TableViewContent::paintEvent().
getVisibleXRange()
QPair< int, int > Isis::TableColumnList::getVisibleXRange (int visibleColumn)
Returns
minX, maxX in a pair
References getVisibleColumns(), and size().
Referenced by Isis::TableViewContent::paintEvent().
indexOf()
int Isis::TableColumnList::indexOf (TableColumn const * someCol) const
Referenced by contains().
lower()
void Isis::TableColumnList::lower (TableColumn * col, bool emitSortOutDated = true)
References size(), and sortOutDated().
operator=()
TableColumnList & Isis::TableColumnList::operator= (TableColumnList other)
operator[]() [1/2]
TableColumn *& Isis::TableColumnList::operator[] (int index)
operator[]() [2/2]
TableColumn *& Isis::TableColumnList::operator[] (QString title)
References _FILEINFO_, and Isis::IException::Programmer.
prepend()
void Isis::TableColumnList::prepend (TableColumn * newCol)
Referenced by Isis::TableView::TableView().
raise()
void Isis::TableColumnList::raise (TableColumn * col, bool emitSortOutDated = true)
References sortOutDated().
raiseToTop()
void Isis::TableColumnList::raiseToTop (TableColumn * col)
References sortOutDated().
Referenced by Isis::TableViewHeader::mouseReleaseEvent(), and setSortingOrder().
setSortingOrder()
void Isis::TableColumnList::setSortingOrder (QStringList newOrder)
References contains(), and raiseToTop().
Referenced by Isis::TableView::TableView().
size()
int Isis::TableColumnList::size () const
Referenced by getVisibleColumns(), getVisibleWidth(), getVisibleXRange(), Isis::TableViewHeader::handleFilterCountsChanged(), lower(), Isis::TableViewHeader::mouseReleaseEvent(), Isis::TableView::setColumnVisible(), Isis::TableViewHeader::setModel(), Isis::TableView::TableView(), Isis::TableViewContent::TableViewContent(), Isis::TableViewContent::updateHorizontalScrollBar(), Isis::AbstractTableModel::~AbstractTableModel(), and Isis::TableView::~TableView().
sortOutDated
void Isis::TableColumnList::sortOutDated () signal
Referenced by append(), lower(), raise(), and raiseToTop().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/TableColumnList.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/CnetEditorWidget/TableColumnList.cpp