Isis Developer Reference: Isis::Sensor Class Reference
Isis::Sensor Class Reference abstract
Spice, Instruments, and Cameras
Class for computing sensor ground coordinates.
#include <Sensor.h>
Public Member Functions
Sensor (Cube &cube)
Constructs a Sensor object and loads SPICE kernels using information from the label object.
virtual ~Sensor ()
Destroys the Sensor.
void setTime (const iTime &time)
By setting the time you essential set the position of the spacecraft and body as indicated in the class Spice.
bool SetLookDirection (const double v[3])
Sets the look direction of the spacecraft.
bool SetRightAscensionDeclination (const double ra, const double dec)
Given the ra/dec compute the look direction.
bool SetUniversalGround (const double latitude, const double longitude, bool backCheck=true)
This is the opposite routine for SetLookDirection.
bool SetUniversalGround (const double latitude, const double longitude, const double radius, bool backCheck=true)
This overloaded method has the opposite function as SetLookDirection.
bool SetGround (const SurfacePoint &surfacePt, bool backCheck=true)
This overloaded method has the opposite function as SetLookDirection.
bool HasSurfaceIntersection () const
Returns if the last call to either SetLookDirection or SetUniversalGround had a valid intersection with the target.
void Coordinate (double p[3]) const
Returns the x,y,z of the surface intersection in BodyFixed km.
virtual double UniversalLatitude () const
Returns the planetocentric latitude, in degrees, at the surface intersection point in the body fixed coordinate system.
Latitude GetLatitude () const
Returns a planetocentric latitude object at the surface intersection point in body fixed.
virtual double UniversalLongitude () const
Returns the positive east, 0-360 domain longitude, in degrees, at the surface intersection point in the body fixed coordinate system.
Longitude GetLongitude () const
Returns a positive east, 0-360 domain longitude object at the surface intersection point in the body fixed coordinate system.
virtual SurfacePoint GetSurfacePoint () const
Returns the surface point (most efficient accessor).
Distance LocalRadius () const
Returns the local radius at the intersection point.
Distance LocalRadius (Latitude lat, Longitude lon)
Returns the local radius at the intersection point.
Distance LocalRadius (double lat, double lon)
Returns the local radius at the intersection point.
virtual double PhaseAngle () const
Returns the phase angle in degrees.
virtual double EmissionAngle () const
Returns the emission angle in degrees.
virtual double IncidenceAngle () const
Returns the incidence angle in degrees.
void LookDirection (double v[3]) const
Returns the look direction in the camera coordinate system.
virtual std::vector< double > lookDirectionJ2000 () const
Returns the look direction in the camera coordinate system.
virtual std::vector< double > lookDirectionBodyFixed () const
Returns the look direction in the body fixed coordinate system.
virtual double RightAscension ()
Returns the right ascension angle (sky longitude).
virtual double Declination ()
Returns the declination angle (sky latitude).
void SpacecraftSurfaceVector (double scSurfaceVector[3]) const
Sets the vector between the spacecraft and surface point in body-fixed.
virtual double SlantDistance () const
Return the distance between the spacecraft and surface point in kmv.
double LocalSolarTime ()
Return the local solar time in hours.
virtual double SolarDistance () const
Returns the distance between the sun and surface point in AU.
double SpacecraftAltitude ()
Returns the distance from the spacecraft to the subspacecraft point in km.
virtual double resolution ()
Virtual method that returns the pixel resolution of the sensor in meters/pix.
void IgnoreElevationModel (bool ignore)
This allows you to ignore the cube elevation model and use the ellipse.
virtual QList< QPointF > PixelIfovOffsets ()
This method is implemented in Camera which defaults to the (pixel pitch * summing mode) / 2.
virtual QString instrumentNameLong () const =0
virtual QString instrumentNameShort () const =0
virtual QString spacecraftNameLong () const =0
virtual QString spacecraftNameShort () const =0
void instrumentPosition (double p[3]) const
Returns the spacecraft position in body-fixed frame km units.
virtual SpicePosition * instrumentPosition () const
Accessor method for the instrument position.
virtual void instrumentBodyFixedPosition (double p[3]) const
Returns the spacecraft position in body-fixed frame km units.
virtual void sunPosition (double p[3]) const
Fills the input vector with sun position information, in either body-fixed or J2000 reference frame and km units.
virtual SpicePosition * sunPosition () const
Accessor method for the sun position.
virtual double targetCenterDistance () const
Calculates and returns the distance from the spacecraft to the target center.
virtual double sunToBodyDist () const
virtual Longitude solarLongitude ()
Returns the solar longitude.
virtual void instrumentBodyFixedVelocity (double v[3]) const
Returns the spacecraft velocity in body-fixed frame km/sec units.
virtual iTime time () const
Returns the ephemeris time in seconds which was used to obtain the spacecraft and sun positions.
void radii (Distance r[3]) const
Returns the radii of the body in km.
virtual void createCache (iTime startTime, iTime endTime, const int size, double tol)
This method creates an internal cache of spacecraft and sun positions over a specified time range.
virtual iTime cacheStartTime () const
Accessor method for the cache start time.
virtual iTime cacheEndTime () const
Accessor method for the cache end time.
virtual void subSpacecraftPoint (double &lat, double &lon)
Returns the sub-spacecraft latitude/longitude in universal coordinates (0-360 positive east, ocentric)
virtual void subSolarPoint (double &lat, double &lon)
Returns the sub-solar latitude/longitude in universal coordinates (0-360 positive east, ocentric)
virtual Target * target () const
Returns a pointer to the target object.
QString targetName () const
Returns the QString name of the target.
virtual iTime getClockTime (QString clockValue, int sclkCode=-1, bool clockTicks=false)
This converts the spacecraft clock ticks value (clockValue) to an iTime.
SpiceDouble getDouble (const QString &key, int index=0)
This returns a value from the NAIF text pool.
SpiceInt getInteger (const QString &key, int index=0)
This returns a value from the NAIF text pool.
QString getString (const QString &key, int index=0)
This returns a value from the NAIF text pool.
virtual SpiceRotation * bodyRotation () const
Accessor method for the body rotation.
virtual SpiceRotation * instrumentRotation () const
Accessor method for the instrument rotation.
bool isUsingAle ()
bool hasKernels (Pvl &lab)
Returns true if the kernel group has kernel files.
bool isTimeSet ()
Returns true if time has been initialized.
SpiceInt naifBodyCode () const
This returns the NAIF body code of the target indicated in the labels.
SpiceInt naifSpkCode () const
This returns the NAIF SPK code to use when reading from SPK kernels.
SpiceInt naifCkCode () const
This returns the NAIF CK code to use when reading from CK kernels.
SpiceInt naifIkCode () const
This returns the NAIF IK code to use when reading from instrument kernels.
SpiceInt naifSclkCode () const
This returns the NAIF SCLK code to use when reading from instrument kernels.
SpiceInt naifBodyFrameCode () const
This returns the NAIF body frame code.
PvlObject getStoredNaifKeywords () const
This returns the PvlObject that stores all of the requested Naif data and can be a replacement for furnishing text kernels.
Protected Types
enum SpiceValueType { SpiceDoubleType , SpiceStringType , SpiceIntType , SpiceByteCodeType }
NAIF value primitive type.
Protected Member Functions
QVariant readValue (QString key, SpiceValueType type, int index=0)
This should be used for reading ALL text naif kernel values.
void storeResult (QString name, SpiceValueType type, QVariant value)
QVariant getStoredResult (QString name, SpiceValueType type)
void storeValue (QString key, int index, SpiceValueType type, QVariant value)
QVariant readStoredValue (QString key, SpiceValueType type, int index)
virtual void computeSolarLongitude (iTime et)
Computes the solar longitude for the given ephemeris time.
Protected Attributes
SpiceDouble m_lookB [3]
Look direction in body fixed.
bool m_newLookB
flag to indicate we need to recompute ra/dec
SpiceDouble m_uB [3]
This contains the sun position (u) in the bodyfixed reference frame (B).
SpiceDouble m_BJ [3][3]
This contains the transformation matrix from J2000 (J) to Body fixed (B).
Target * m_target
Target of the observation.
iTime * m_et
Ephemeris time (read NAIF documentation for a detailed description)
Longitude * m_solarLongitude
Body rotation solar longitude value.
Detailed Description
Class for computing sensor ground coordinates.
The sensor class allows for the computation of parameters related to orbiting instruments. In particular, a time and look direction can be set and from those the ground coordinate (latitude/longitude) along with phase, incidence, and emission angles can be computed. Likewise, a ground point can be set and look direction can be computed. This class is derived from the Spice class.
An important capability of this class is the ability to use a surface model other than an ellipsoid when intersecting the look direction of the sensor with the planetary body. This allows for the generation of othrorectified products. The file containing the surface model is a cube and is obtained from the labels in the follow form:
Group = Kernels
  ElevationModel = file.cub
EndGroup
Author
2003-04-11 Jeff Anderson
Member Enumeration Documentation
SpiceValueType
enum Isis::Spice::SpiceValueType protected inherited
NAIF value primitive type.
Enumerator
SpiceDoubleType
SpiceDouble type.
SpiceStringType
SpiceString type.
SpiceIntType
SpiceInt type.
SpiceByteCodeType
SpiceByteCode type.
Constructor & Destructor Documentation
Sensor()
Isis::Sensor::Sensor (Cube & cube)
Constructs a Sensor object and loads SPICE kernels using information from the label object.
The constructor expects an Instrument and Kernels group to be in the labels (see Spice documentation).
Parameters
cube Cube whose label contains Instrument and Kernels groups.
References m_newLookB.
~Sensor()
Isis::Sensor::~Sensor () virtual
Destroys the Sensor.
Member Function Documentation
bodyRotation()
SpiceRotation * Isis::Spice::bodyRotation () const virtual inherited
Accessor method for the body rotation.
Returns
iTime Body rotation for the image.
Author
Steven Lambright
Reimplemented in Isis::CSMCamera.
Referenced by Isis::Cube::attachSpiceFromIsd(), EmissionAngle(), Isis::RadarGroundMap::GetdXYdPosition(), Isis::RadarGroundMap::GetXY(), lookDirectionJ2000(), Isis::MiniRF::MiniRF(), Isis::RadarGroundMap::SetFocalPlane(), Isis::RadarGroundMap::SetGround(), SetGround(), SetLookDirection(), and SetUniversalGround().
cacheEndTime()
iTime Isis::Spice::cacheEndTime () const virtual inherited
Accessor method for the cache end time.
Returns
iTime End time for the image.
Author
Steven Lambright
cacheStartTime()
iTime Isis::Spice::cacheStartTime () const virtual inherited
Accessor method for the cache start time.
Returns
iTime Start time for the image.
Author
Steven Lambright
computeSolarLongitude()
void Isis::Spice::computeSolarLongitude (iTime et) protected virtual inherited
Computes the solar longitude for the given ephemeris time.
If the target is sky, the longitude is set to -999.0.
Parameters
et Ephemeris time
Reimplemented in Isis::CSMCamera.
References Isis::iTime::Et(), and Isis::Longitude::force360Domain().
Coordinate()
void Isis::Sensor::Coordinate (double p[3]) const
Returns the x,y,z of the surface intersection in BodyFixed km.
Parameters
p[] The coordinate of the surface intersection.
References Isis::SurfacePoint::GetX(), Isis::SurfacePoint::GetY(), Isis::SurfacePoint::GetZ(), Isis::Displacement::kilometers(), Isis::Target::shape(), Isis::ShapeModel::surfaceIntersection(), and Isis::Spice::target().
Referenced by Isis::ControlPoint::ComputeApriori(), Isis::Camera::DetectorResolution(), EmissionAngle(), Isis::VimsGroundMap::Init(), Isis::Camera::OffNadirAngle(), PhaseAngle(), SetGround(), SetLookDirection(), and SetUniversalGround().
createCache()
void Isis::Spice::createCache (iTime startTime, iTime endTime, const int size, double tol) virtual inherited
This method creates an internal cache of spacecraft and sun positions over a specified time range.
The SPICE kernels are then immediately unloaded. This allows multiple instances of the Spice object to be created as the NAIF toolkit can clash if multiple sets of SPICE kernels are loaded. Note that the cache size is specified as an argument. Therefore, times requested via setTime() which are not directly loaded in the cache will be interpolated. If the instrument position is not cached and cacheSize is greater than 3, the tolerance is passed to the SpicePosition Memcache2HermiteCache() method.
Note: Before this method is called, the private variables m_cacheSize, m_startTime and m_endTime must be set. This is done in the Camera classes using the methods SetCacheSize() and SetStartEndEphemerisTime().
Parameters
startTime Starting ephemeris time to cache
endTime Ending ephemeris time to cache
size Size of the cache.
tol Tolerance.
Exceptions
Isis::IException::Programmer - "Argument cacheSize must be greater than zero"
Isis::IException::Programmer - "Argument startTime must be less than or equal to endTime"
Isis::IException::User - "This instrument does not support time padding"
References _FILEINFO_, Isis::iTime::Et(), and Isis::FileName::expanded().
Referenced by Isis::CrismCamera::CrismCamera(), Isis::Camera::LoadCache(), and Isis::MiniRF::MiniRF().
Declination()
double Isis::Sensor::Declination () virtual
Returns the declination angle (sky latitude).
Returns
double Declination angle, in degrees.
Reimplemented in Isis::CSMCamera.
References m_newLookB.
Referenced by Isis::Camera::CelestialNorthClockAngle(), Isis::VimsSkyMap::Init(), Isis::FindTool::mouseButtonRelease(), Isis::Camera::RaDecRange(), and Isis::Camera::RaDecResolution().
EmissionAngle()
double Isis::Sensor::EmissionAngle () const virtual
Returns the emission angle in degrees.
Returns
double Emission angle, in degrees.
Reimplemented in Isis::CSMCamera.
References Isis::Spice::bodyRotation(), Coordinate(), Isis::ShapeModel::emissionAngle(), Isis::Spice::instrumentPosition(), Isis::Target::shape(), and Isis::Spice::target().
Referenced by Isis::CameraStatistics::addStats(), Isis::InterestOperator::InterestByMeasure(), Isis::Camera::ObliqueDetectorResolution(), Isis::Camera::OffNadirAngle(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
getClockTime()
iTime Isis::Spice::getClockTime (QString clockValue, int sclkCode = -1, bool clockTicks = false) virtual inherited
This converts the spacecraft clock ticks value (clockValue) to an iTime.
If the clock ticks value is provided directly, rather than the spacecraft clock string, set clockTicks=true.
Use this when possible because naif calls (such as scs2e_c) cannot be called when not using naif.
References Isis::toString().
Referenced by Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::VimsGroundMap::Init(), Isis::VimsSkyMap::Init(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::MarciCamera::MarciCamera(), Isis::MdisCamera::MdisCamera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::ThemisVisCamera::ThemisVisCamera(), and Isis::VikingCamera::VikingCamera().
getDouble()
SpiceDouble Isis::Spice::getDouble (const QString & key, int index = 0) inherited
This returns a value from the NAIF text pool.
It is a static convience method
Parameters
key Name of NAIF keyword to obtain from the pool
index If the keyword is an array, the element to obtain. Defaults to 0
Returns
SpiceDouble Spice double from NAIF text pool
Exceptions
Isis::iException::Io - "Can not find key in instrument kernels."
Referenced by Isis::LroWideAngleCameraDistortionMap::addFilter(), Isis::LroWideAngleCameraFocalPlaneMap::addFilter(), Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::RosettaOsirisCamera::initDistortion(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::KaguyaTcCameraDistortionMap::KaguyaTcCameraDistortionMap(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::LwirCamera::LwirCamera(), Isis::MarciCamera::MarciCamera(), Isis::MarciDistortionMap::MarciDistortionMap(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::NirCamera::NirCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::OsirisRexTagcamsDistortionMap::OsirisRexTagcamsDistortionMap(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::KaguyaMiCameraDistortionMap::SetDistortion(), Isis::LroNarrowAngleDistortionMap::SetDistortion(), Isis::TaylorCameraDistortionMap::SetDistortion(), Isis::OsirisRexOcamsDistortionMap::SetDistortion(), Isis::Camera::SetFocalLength(), Isis::Camera::SetPixelPitch(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::TgoCassisDistortionMap::TgoCassisDistortionMap(), and Isis::UvvisCamera::UvvisCamera().
getInteger()
SpiceInt Isis::Spice::getInteger (const QString & key, int index = 0) inherited
This returns a value from the NAIF text pool.
It is a static convience
Parameters
key Name of NAIF keyword to obtain from the pool
index If the keyword is an array, the element to obtain. Defaults to 0
Returns
SpiceInt Spice integer from NAIF text pool
Exceptions
Isis::iException::Io - "Can not find key in instrument kernels
Referenced by Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), and Isis::LroWideAngleCamera::LroWideAngleCamera().
GetLatitude()
Latitude Isis::Sensor::GetLatitude () const
Returns a planetocentric latitude object at the surface intersection point in body fixed.
Returns
Latidude Universal latitude object.
References Isis::SurfacePoint::GetLatitude(), Isis::Target::shape(), Isis::ShapeModel::surfaceIntersection(), and Isis::Spice::target().
Referenced by UniversalLatitude().
GetLongitude()
Longitude Isis::Sensor::GetLongitude () const
Returns a positive east, 0-360 domain longitude object at the surface intersection point in the body fixed coordinate system.
Returns
Longitude Universal longitude object.
References Isis::SurfacePoint::GetLongitude(), Isis::Target::shape(), Isis::ShapeModel::surfaceIntersection(), and Isis::Spice::target().
Referenced by UniversalLongitude().
getStoredNaifKeywords()
PvlObject Isis::Spice::getStoredNaifKeywords () const inherited
This returns the PvlObject that stores all of the requested Naif data and can be a replacement for furnishing text kernels.
Referenced by Isis::Cube::attachSpiceFromIsd().
getStoredResult()
QVariant Isis::Spice::getStoredResult (QString name, SpiceValueType type) protected inherited
References Isis::EndianSwapper::Double().
getString()
QString Isis::Spice::getString (const QString & key, int index = 0) inherited
This returns a value from the NAIF text pool.
It is a static convience method
Parameters
key Name of NAIF keyword to obtain from the pool
index If the keyword is an array, the element to obtain. Defaults to 0
Returns
QString Value from the NAIF text pool
Exceptions
Isis::IException::Io - "Can not find key in instrument kernels."
Referenced by Isis::LightTimeCorrectionState::checkAberrationCorrection(), Isis::LightTimeCorrectionState::checkLightTimeToSurfaceCorrect(), Isis::LightTimeCorrectionState::checkObserverTargetSwap(), Isis::MdisCamera::MdisCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::OsirisRexTagcamsDistortionMap::OsirisRexTagcamsDistortionMap(), and Isis::OsirisRexOcamsDistortionMap::SetDistortion().
GetSurfacePoint()
SurfacePoint Isis::Sensor::GetSurfacePoint () const virtual
Returns the surface point (most efficient accessor).
Returns
SurfacePoint Coordinate for the surface intersection.
References Isis::Target::shape(), Isis::ShapeModel::surfaceIntersection(), and Isis::Spice::target().
Referenced by Isis::ControlPoint::ComputeResiduals(), Isis::QnetPointDistanceFilter::filter(), Isis::Camera::GetLocalNormal(), Isis::CSMCamera::GroundPartials(), Isis::CSMCamera::IncidenceAngle(), Isis::Camera::LocalPhotometricAngles(), Isis::CSMCamera::PhaseAngle(), and Isis::CSMCamera::SlantDistance().
hasKernels()
bool Isis::Spice::hasKernels (Pvl & lab) inherited
Returns true if the kernel group has kernel files.
Parameters
lab Label containing Instrument and Kernels groups.
Returns
bool status of kernel files in the kernel group
References Isis::PvlObject::findGroup(), Isis::PvlContainer::hasKeyword(), and Isis::PvlKeyword::size().
HasSurfaceIntersection()
bool Isis::Sensor::HasSurfaceIntersection () const
Returns if the last call to either SetLookDirection or SetUniversalGround had a valid intersection with the target.
If so then other methods such as Coordinate, UniversalLatitude, UniversalLongitude, etc can be used with confidence.
Returns
bool True if the look direction intersects with the target.
References Isis::ShapeModel::hasIntersection(), Isis::Target::shape(), and Isis::Spice::target().
Referenced by Isis::CameraStatistics::addStats(), Isis::Camera::DetectorResolution(), Isis::CSMCamera::DetectorResolution(), Isis::Stereo::elevation(), Isis::CSMCamera::LineResolution(), Isis::Chip::Load(), Isis::Camera::ObliqueDetectorResolution(), Isis::CSMCamera::SampleResolution(), and Isis::VimsGroundMap::SetGround().
IgnoreElevationModel()
void Isis::Sensor::IgnoreElevationModel (bool ignore)
This allows you to ignore the cube elevation model and use the ellipse.
Parameters
ignore Indicates whether the elevation model is ignored.
References Isis::Target::restoreShape(), Isis::Target::setShapeEllipsoid(), and Isis::Spice::target().
Referenced by Isis::ImagePolygon::Create(), and Isis::ImagePolygon::initCube().
IncidenceAngle()
double Isis::Sensor::IncidenceAngle () const virtual
Returns the incidence angle in degrees.
This does not use the surface model.
Returns
double Incidence angle, in degrees.
Reimplemented in Isis::CSMCamera.
References Isis::ShapeModel::incidenceAngle(), Isis::Spice::m_uB, Isis::Target::shape(), and Isis::Spice::target().
Referenced by Isis::CameraStatistics::addStats(), Isis::InterestOperator::InterestByMeasure(), and Isis::ControlNetValidMeasure::ValidStandardOptions().
instrumentBodyFixedPosition()
void Isis::Spice::instrumentBodyFixedPosition (double p[3]) const virtual inherited
Returns the spacecraft position in body-fixed frame km units.
Parameters
p[] Spacecraft position
See also
setTime()
Exceptions
Isis::iException::Programmer - "You must call SetTime first"
Reimplemented in Isis::CSMCamera.
References _FILEINFO_.
Referenced by Isis::Camera::LocalPhotometricAngles(), PhaseAngle(), and SlantDistance().
instrumentBodyFixedVelocity()
void Isis::Spice::instrumentBodyFixedVelocity (double v[3]) const virtual inherited
Returns the spacecraft velocity in body-fixed frame km/sec units.
Parameters
v[] Spacecraft velocity
References _FILEINFO_.
instrumentNameLong()
virtual QString Isis::Sensor::instrumentNameLong () const pure virtual
Implemented in Isis::IdealCamera, and Isis::Camera.
instrumentNameShort()
virtual QString Isis::Sensor::instrumentNameShort () const pure virtual
Implemented in Isis::IdealCamera, and Isis::Camera.
instrumentPosition() [1/2]
SpicePosition * Isis::Spice::instrumentPosition () const virtual inherited
Accessor method for the instrument position.
Returns
iTime Instrument position for the image.
Author
Steven Lambright
Reimplemented in Isis::CSMCamera.
Referenced by Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::Camera::DetectorResolution(), EmissionAngle(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MiniRF::MiniRF(), Isis::Camera::OffNadirAngle(), SetGround(), SetLookDirection(), SetUniversalGround(), and SpacecraftAltitude().
instrumentPosition() [2/2]
void Isis::Spice::instrumentPosition (double p[3]) const inherited
Returns the spacecraft position in body-fixed frame km units.
Parameters
p[] Spacecraft position
See also
setTime()
Exceptions
Isis::iException::Programmer - "You must call SetTime first"
Referenced by Isis::Cube::attachSpiceFromIsd(), Isis::RadarGroundMap::GetdXYdPosition(), Isis::RadarGroundMap::GetXY(), Isis::RadarGroundMap::SetFocalPlane(), and Isis::RadarGroundMap::SetGround().
instrumentRotation()
SpiceRotation * Isis::Spice::instrumentRotation () const virtual inherited
Accessor method for the instrument rotation.
Returns
iTime Instrument rotation for the image.
Author
Steven Lambright
Reimplemented in Isis::CSMCamera.
Referenced by Isis::Cube::attachSpiceFromIsd(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), LookDirection(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::RadarGroundMap::SetFocalPlane(), Isis::RadarGroundMap::SetGround(), SetLookDirection(), SetRightAscensionDeclination(), and Isis::TgoCassisCamera::TgoCassisCamera().
isTimeSet()
bool Isis::Spice::isTimeSet () inherited
Returns true if time has been initialized.
Author
2016-10-19 Kristin Berry
Returns
bool true if time has been set
Referenced by Isis::CameraDetectorMap::SetParent(), and Isis::RollingShutterCameraDetectorMap::SetParent().
isUsingAle()
bool Isis::Spice::isUsingAle () inherited
LocalRadius() [1/3]
Distance Isis::Sensor::LocalRadius () const
Returns the local radius at the intersection point.
This is either the radius on the ellipsoid, the radius from the surface model passed into the constructor, or the radius set with SetUniversalGround.
Returns
Distance The local radius at the surface intersection.
References Isis::SurfacePoint::GetLocalRadius(), Isis::Target::shape(), Isis::ShapeModel::surfaceIntersection(), and Isis::Spice::target().
Referenced by Isis::CameraStatistics::addStats(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::QnetCubeDistanceFilter::filter(), Isis::Camera::GetLocalNormal(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::LineScanCameraGroundMap::SetGround(), Isis::PushFrameCameraGroundMap::SetGround(), Isis::RadarGroundMap::SetGround(), Isis::VimsGroundMap::SetGround(), Isis::Camera::SetGround(), Isis::CSMCamera::SetGround(), and SpacecraftAltitude().
LocalRadius() [2/3]
Distance Isis::Sensor::LocalRadius (double lat, double lon)
Returns the local radius at the intersection point.
This is either the radius on the ellipsoid, the radius from the surface model passed into the constructor, or the radius set with SetUniversalGround.
Parameters
lat
lon
Returns
Distance The distance from the center of the planet to this lat,lon in meters.
References Isis::Angle::Degrees, Isis::ShapeModel::localRadius(), Isis::Target::shape(), and Isis::Spice::target().
LocalRadius() [3/3]
Distance Isis::Sensor::LocalRadius (Latitude lat, Longitude lon)
Returns the local radius at the intersection point.
This is either the radius on the ellipsoid, the radius from the surface model passed into the constructor, or the radius set with SetUniversalGround.
Parameters
lat
lon
Returns
Distance The distance from the center of the planet to this lat,lon in meters.
References Isis::ShapeModel::localRadius(), Isis::Target::shape(), and Isis::Spice::target().
LocalSolarTime()
double Isis::Sensor::LocalSolarTime ()
Return the local solar time in hours.
Returns
double Local solar time, in hours.
References Isis::Spice::subSolarPoint(), and UniversalLongitude().
Referenced by Isis::CameraStatistics::addStats().
LookDirection()
void Isis::Sensor::LookDirection (double v[3]) const
Returns the look direction in the camera coordinate system.
Parameters
v[] The look vector.
References Isis::Spice::instrumentRotation(), lookDirectionJ2000(), and Isis::SpiceRotation::ReferenceVector().
lookDirectionBodyFixed()
vector< double > Isis::Sensor::lookDirectionBodyFixed () const virtual
Returns the look direction in the body fixed coordinate system.
Returns
vector<double> Look direction in body fixed coordinate system.
References m_lookB.
Referenced by lookDirectionJ2000().
lookDirectionJ2000()
vector< double > Isis::Sensor::lookDirectionJ2000 () const virtual
Returns the look direction in the camera coordinate system.
Returns
vector<double> Look direction in J2000 cooridinate system.
References Isis::Spice::bodyRotation(), Isis::SpiceRotation::J2000Vector(), and lookDirectionBodyFixed().
Referenced by LookDirection().
naifBodyCode()
SpiceInt Isis::Spice::naifBodyCode () const inherited
This returns the NAIF body code of the target indicated in the labels.
Returns
SpiceInt NAIF body code
Referenced by Isis::Camera::SpkCenterId().
naifBodyFrameCode()
SpiceInt Isis::Spice::naifBodyFrameCode () const inherited
This returns the NAIF body frame code.
It is read from the labels, if it exists. Otherwise, it's calculated by the init() method.
Returns
SpiceInt NAIF body frame code
naifCkCode()
SpiceInt Isis::Spice::naifCkCode () const inherited
This returns the NAIF CK code to use when reading from CK kernels.
Returns
SpiceInt NAIF CK code
naifIkCode()
SpiceInt Isis::Spice::naifIkCode () const inherited
This returns the NAIF IK code to use when reading from instrument kernels.
Returns
SpiceInt NAIF IK code
Referenced by Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ClipperWacFcCamera::ClipperWacFcCamera(), Isis::CrismCamera::CrismCamera(), Isis::CTXCamera::CTXCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::HiriseCamera::HiriseCamera(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::LwirCamera::LwirCamera(), Isis::MarciCamera::MarciCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MiniRF::MiniRF(), Isis::MocNarrowAngleCamera::MocNarrowAngleCamera(), Isis::MocWideAngleCamera::MocWideAngleCamera(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::NirCamera::NirCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::Camera::SetFocalLength(), Isis::Camera::SetPixelPitch(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::ThemisVisCamera::ThemisVisCamera(), Isis::UvvisCamera::UvvisCamera(), Isis::VikingCamera::VikingCamera(), Isis::VimsCamera::VimsCamera(), and Isis::VoyagerCamera::VoyagerCamera().
naifSclkCode()
SpiceInt Isis::Spice::naifSclkCode () const inherited
This returns the NAIF SCLK code to use when reading from instrument kernels.
Returns
SpiceInt NAIF SCLK code
Referenced by Isis::CrismCamera::CrismCamera().
naifSpkCode()
SpiceInt Isis::Spice::naifSpkCode () const inherited
This returns the NAIF SPK code to use when reading from SPK kernels.
Returns
SpiceInt NAIF SPK code
Referenced by Isis::Camera::SpkTargetId().
PhaseAngle()
double Isis::Sensor::PhaseAngle () const virtual
Returns the phase angle in degrees.
This does not use the surface model.
Returns
double Phase angle, in degrees.
Reimplemented in Isis::CSMCamera.
References Coordinate(), Isis::Spice::instrumentBodyFixedPosition(), Isis::Spice::m_uB, and Isis::RAD2DEG.
Referenced by Isis::CameraStatistics::addStats().
PixelIfovOffsets()
QList< QPointF > Isis::Sensor::PixelIfovOffsets () virtual
This method is implemented in Camera which defaults to the (pixel pitch * summing mode) / 2.
If the instrument has a non-square ifov, it must implement this method to return offsets from the center of the pixel.
Author
tsucharski (3/8/2013)
Returns
QList<QPointF>
Reimplemented in Isis::HayabusaNirsCamera, Isis::VimsCamera, Isis::CSMCamera, and Isis::Camera.
References _FILEINFO_, and Isis::IException::Programmer.
radii()
void Isis::Spice::radii (Distance r[3]) const inherited
Returns the radii of the body in km.
The radii are obtained from the appropriate SPICE kernel for the body specified by TargetName in the Instrument group of the labels.
Parameters
r[] Radii of the target in kilometers
Referenced by Isis::Camera::BasicMapping(), Isis::Camera::GroundRange(), Isis::VimsGroundMap::Init(), Isis::MiniRF::MiniRF(), Isis::RadarGroundMap::SetFocalPlane(), and Isis::CSMCamera::setTarget().
readStoredValue()
QVariant Isis::Spice::readStoredValue (QString key, SpiceValueType type, int index) protected inherited
References Isis::IException::print(), Isis::toDouble(), and Isis::toInt().
readValue()
QVariant Isis::Spice::readValue (QString key, SpiceValueType type, int index = 0) protected inherited
This should be used for reading ALL text naif kernel values.
This will read it from Naif if we're using naif/not attached kernels. If we have attached kernels and a NaifKeywords label object we will grab it from there instead. This allows us to not furnish kernels after spiceinit.
Parameters
key The naif keyword,value name
type The naif value's primitive type
index The index into the naif keyword array to read
References _FILEINFO_.
Referenced by Isis::IdealCamera::IdealCamera().
resolution()
virtual double Isis::Sensor::resolution () inline virtual
Virtual method that returns the pixel resolution of the sensor in meters/pix.
Returns
double Resolution value of 1.0
Reimplemented from Isis::Spice.
Reimplemented in Isis::Camera.
RightAscension()
double Isis::Sensor::RightAscension () virtual
Returns the right ascension angle (sky longitude).
Returns
double The angle of right ascension, in degrees.
Reimplemented in Isis::CSMCamera.
References m_newLookB.
Referenced by Isis::Camera::CelestialNorthClockAngle(), Isis::VimsSkyMap::Init(), Isis::FindTool::mouseButtonRelease(), Isis::Camera::RaDecRange(), and Isis::Camera::RaDecResolution().
SetGround()
bool Isis::Sensor::SetGround (const SurfacePoint & surfacePt, bool backCheck = true)
This overloaded method has the opposite function as SetLookDirection.
Instead of computing a point on the target, a point is set and the look direction is computed. Other methods such as lat/lon, phase, incidence, etc. can be used if this method returns a true.
Parameters
backCheck If true this method will check the lat/lon point to see if it falls on the backside of the target (or beyond the horizon). If false this test will not occur. Defaults to true.
Returns
bool
References Isis::Spice::bodyRotation(), Isis::ShapeModel::clearSurfacePoint(), Coordinate(), Isis::Spice::instrumentPosition(), Isis::ShapeModel::intersectSurface(), Isis::Target::shape(), and Isis::Spice::target().
SetLookDirection()
bool Isis::Sensor::SetLookDirection (const double v[3])
Sets the look direction of the spacecraft.
This routine will then attempt to intersect the look direction with the target. If successful you can utilize the methods which return the lat/lon, phase, incidence, etc. This routine returns false if the look direction does not intersect the target.
Parameters
v[] A look vector in camera coordinates. For example, (0,0,1) is usually the look direction out of the boresight of a camera.
Returns
bool Indicates whether the given look direction intersects the target.
References Isis::Spice::bodyRotation(), Coordinate(), Isis::Spice::instrumentPosition(), Isis::Spice::instrumentRotation(), Isis::ShapeModel::intersectSurface(), Isis::SpiceRotation::J2000Vector(), m_lookB, m_newLookB, Isis::SpiceRotation::ReferenceVector(), Isis::ShapeModel::setHasIntersection(), Isis::Target::shape(), and Isis::Spice::target().
Referenced by Isis::CameraSkyMap::SetFocalPlane(), Isis::VimsGroundMap::SetFocalPlane(), Isis::VimsSkyMap::SetFocalPlane(), and SetRightAscensionDeclination().
SetRightAscensionDeclination()
bool Isis::Sensor::SetRightAscensionDeclination (const double ra, const double dec)
Given the ra/dec compute the look direction.
Parameters
ra Right ascension in degrees (sky longitude).
dec Declination in degrees (sky latitude).
Returns
bool True if successful.
References Isis::DEG2RAD, Isis::Spice::instrumentRotation(), Isis::SpiceRotation::ReferenceVector(), and SetLookDirection().
setTime()
void Isis::Sensor::setTime (const iTime & time) virtual
By setting the time you essential set the position of the spacecraft and body as indicated in the class Spice.
However, after this is invoked there will be no intersection point until SetLookDirection or SetUniversalGround is invoked. (Read NAIF documentation for a detailed description of ephemeris time.)
Parameters
time Ephemeris time.
Reimplemented from Isis::Spice.
References Isis::ShapeModel::clearSurfacePoint(), Isis::Spice::setTime(), Isis::Target::shape(), Isis::Spice::target(), and Isis::Spice::time().
Referenced by Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ClipperWacFcCamera::ClipperWacFcCamera(), Isis::CrismCamera::CrismCamera(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::IdealCamera::IdealCamera(), Isis::VimsGroundMap::Init(), Isis::VimsSkyMap::Init(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::Camera::LoadCache(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LwirCamera::LwirCamera(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MdisCamera::MdisCamera(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::MiniRF::MiniRF(), Isis::MsiCamera::MsiCamera(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NirCamera::NirCamera(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::ThemisVisCamera::SetBand(), Isis::NewHorizonsMvicFrameCamera::SetBand(), Isis::VimsGroundMap::SetFocalPlane(), Isis::VimsSkyMap::SetFocalPlane(), Isis::PushFrameCameraDetectorMap::SetFramelet(), Isis::RadarPulseMap::SetParent(), Isis::CameraDetectorMap::SetParent(), Isis::LineScanCameraDetectorMap::SetParent(), Isis::RollingShutterCameraDetectorMap::SetParent(), Isis::VariableLineScanCameraDetectorMap::SetParent(), Isis::SsiCamera::SsiCamera(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::UvvisCamera::UvvisCamera(), Isis::VikingCamera::VikingCamera(), and Isis::VoyagerCamera::VoyagerCamera().
SetUniversalGround() [1/2]
bool Isis::Sensor::SetUniversalGround (const double latitude, const double longitude, bool backCheck = true)
This is the opposite routine for SetLookDirection.
Instead of computing a point on the target, a point is set and the look direction is computed. Other methods such as lat/lon, phase, incidence, etc. can be used if this method returns a true.
Parameters
latitude Planetocentric latitude.
longitude Positive east longitude.
backCheck If true this method will check the lat/lon point to see if it falls on the backside of the target (or beyond the horizon). If false this test will not occur. Defaults to true.
Returns
bool True if the look direction intersects the target.
References Isis::Spice::bodyRotation(), Isis::ShapeModel::clearSurfacePoint(), Coordinate(), Isis::Angle::Degrees, Isis::Spice::instrumentPosition(), Isis::ShapeModel::intersectSurface(), Isis::Target::shape(), and Isis::Spice::target().
SetUniversalGround() [2/2]
bool Isis::Sensor::SetUniversalGround (const double latitude, const double longitude, const double radius, bool backCheck = true)
This overloaded method has the opposite function as SetLookDirection.
Instead of computing a point on the target, a point is set and the look direction is computed. Other methods such as lat/lon, phase, incidence, etc. can be used if this method returns a true.
Parameters
latitude Planetocentric latitude in degrees.
longitude Positive east longitude in degrees.
radius Radius in meters.
backCheck If true this method will check the lat/lon point to see if it falls on the backside of the target (or beyond the horizon). If false this test will not occur. Defaults to true.
Returns
bool True if the look direction intersects the target.
References Isis::Spice::bodyRotation(), Isis::ShapeModel::clearSurfacePoint(), Coordinate(), Isis::Angle::Degrees, Isis::Spice::instrumentPosition(), Isis::ShapeModel::intersectSurface(), Isis::Distance::Meters, Isis::Target::shape(), and Isis::Spice::target().
SlantDistance()
double Isis::Sensor::SlantDistance () const virtual
Return the distance between the spacecraft and surface point in kmv.
Returns
double Slant distance.
Reimplemented in Isis::CSMCamera.
References Isis::SurfacePoint::GetX(), Isis::SurfacePoint::GetY(), Isis::SurfacePoint::GetZ(), Isis::Spice::instrumentBodyFixedPosition(), Isis::Displacement::kilometers(), Isis::Target::shape(), Isis::ShapeModel::surfaceIntersection(), and Isis::Spice::target().
Referenced by Isis::LineScanCameraGroundMap::FindSpacecraftDistance().
SolarDistance()
double Isis::Sensor::SolarDistance () const virtual
Returns the distance between the sun and surface point in AU.
Returns
double Solar distance.
Reimplemented in Isis::CSMCamera.
References Isis::SurfacePoint::GetX(), Isis::SurfacePoint::GetY(), Isis::SurfacePoint::GetZ(), Isis::Displacement::kilometers(), Isis::Target::shape(), Isis::Spice::sunPosition(), Isis::ShapeModel::surfaceIntersection(), and Isis::Spice::target().
solarLongitude()
Longitude Isis::Spice::solarLongitude () virtual inherited
Returns the solar longitude.
Returns
double The Solar Longitude
Referenced by Isis::Cube::attachSpiceFromIsd().
SpacecraftAltitude()
double Isis::Sensor::SpacecraftAltitude ()
Returns the distance from the spacecraft to the subspacecraft point in km.
It uses the ellipsoid, not the shape model.
Returns
double Spacecraft altitude.
References Isis::Spice::instrumentPosition(), Isis::Distance::kilometers(), LocalRadius(), and Isis::Spice::subSpacecraftPoint().
Referenced by Isis::CrismCamera::CrismCamera(), Isis::Camera::LoadCache(), and Isis::MiniRF::MiniRF().
spacecraftNameLong()
virtual QString Isis::Sensor::spacecraftNameLong () const pure virtual
Implemented in Isis::IdealCamera, and Isis::Camera.
spacecraftNameShort()
virtual QString Isis::Sensor::spacecraftNameShort () const pure virtual
Implemented in Isis::IdealCamera, and Isis::Camera.
SpacecraftSurfaceVector()
void Isis::Sensor::SpacecraftSurfaceVector (double scSurfaceVector[3]) const
Sets the vector between the spacecraft and surface point in body-fixed.
Parameters
scSurfaceVector The direction vector from the observer to the surface intersection.
Author
2011-12-20 Tracie Sucharski
References m_lookB.
storeResult()
void Isis::Spice::storeResult (QString name, SpiceValueType type, QVariant value) protected inherited
References Isis::EndianSwapper::Double().
storeValue()
void Isis::Spice::storeValue (QString key, int index, SpiceValueType type, QVariant value) protected inherited
References _FILEINFO_, Isis::PvlKeyword::addValue(), Isis::PvlKeyword::size(), and Isis::toString().
Referenced by Isis::IdealCamera::IdealCamera().
subSolarPoint()
void Isis::Spice::subSolarPoint (double & lat, double & lon) virtual inherited
Returns the sub-solar latitude/longitude in universal coordinates (0-360 positive east, ocentric)
Parameters
lat Sub-solar latitude
lon Sub-solar longitude
See also
setTime()
Exceptions
Isis::IException::Programmer - "You must call SetTime first."
Reimplemented in Isis::CSMCamera.
References _FILEINFO_, and Isis::PI.
Referenced by LocalSolarTime(), and Isis::Camera::SunAzimuth().
subSpacecraftPoint()
void Isis::Spice::subSpacecraftPoint (double & lat, double & lon) virtual inherited
Returns the sub-spacecraft latitude/longitude in universal coordinates (0-360 positive east, ocentric)
Parameters
lat Sub-spacecraft latitude
lon Sub-spacecraft longitude
See also
setTime()
Exceptions
Isis::IException::Programmer - "You must call SetTime first."
Reimplemented in Isis::CSMCamera.
References _FILEINFO_, and Isis::PI.
Referenced by SpacecraftAltitude(), and Isis::Camera::SpacecraftAzimuth().
sunPosition() [1/2]
SpicePosition * Isis::Spice::sunPosition () const virtual inherited
Accessor method for the sun position.
Returns
iTime Sun position for the image.
Author
Steven Lambright
Reimplemented in Isis::CSMCamera.
Referenced by SolarDistance().
sunPosition() [2/2]
void Isis::Spice::sunPosition (double p[3]) const virtual inherited
Fills the input vector with sun position information, in either body-fixed or J2000 reference frame and km units.
Parameters
p[] Sun position
See also
setTime()
Reimplemented in Isis::CSMCamera.
References _FILEINFO_.
Referenced by Isis::Cube::attachSpiceFromIsd().
sunToBodyDist()
double Isis::Spice::sunToBodyDist () const virtual inherited
target()
Target * Isis::Spice::target () const virtual inherited
Returns a pointer to the target object.
Returns
string
Referenced by Isis::Camera::BasicMapping(), Isis::Camera::basicRingMapping(), Coordinate(), Isis::CSMCamera::EmissionAngle(), EmissionAngle(), GetLatitude(), Isis::Camera::GetLocalNormal(), GetLongitude(), GetSurfacePoint(), Isis::UniversalGroundMap::GroundRange(), HasSurfaceIntersection(), IgnoreElevationModel(), Isis::CSMCamera::IncidenceAngle(), IncidenceAngle(), Isis::Camera::LoadCache(), LocalRadius(), Isis::FindTool::mouseButtonRelease(), Isis::Camera::NorthAzimuth(), Isis::CSMCamera::PhaseAngle(), Isis::VimsGroundMap::SetGround(), Isis::RadarGroundMap::SetGround(), SetGround(), Isis::Camera::SetGround(), Isis::CSMCamera::SetGround(), Isis::Camera::SetImage(), Isis::CSMCamera::SetImage(), SetLookDirection(), Isis::CSMCamera::SetLookDirection(), Isis::Camera::SetRightAscensionDeclination(), Isis::CSMCamera::setTarget(), setTime(), Isis::Camera::SetUniversalGround(), SetUniversalGround(), SlantDistance(), Isis::Camera::Slope(), and SolarDistance().
targetCenterDistance()
double Isis::Spice::targetCenterDistance () const virtual inherited
Calculates and returns the distance from the spacecraft to the target center.
Returns
double Distance to the center of the target from the spacecraft
Reimplemented in Isis::CSMCamera.
targetName()
QString Isis::Spice::targetName () const inherited
Returns the QString name of the target.
Returns
QString
References Isis::Target::name().
time()
iTime Isis::Spice::time () const virtual inherited
Returns the ephemeris time in seconds which was used to obtain the spacecraft and sun positions.
Returns
iTime the currently set ephemeris time
Exceptions
IException::Programmer "Unable to retrieve the time Spice::setTime must be called first."
References _FILEINFO_.
Referenced by Isis::LineScanCameraGroundMap::FindFocalPlane(), Isis::HiresCamera::HiresCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::LoHighCamera::LoHighCamera(), Isis::LoMediumCamera::LoMediumCamera(), Isis::LwirCamera::LwirCamera(), Isis::NewHorizonsMvicFrameCamera::SetBand(), Isis::LineScanCameraDetectorMap::SetDetector(), Isis::RadarPulseMap::SetDetector(), Isis::VariableLineScanCameraDetectorMap::SetDetector(), Isis::RadarSlantRangeMap::SetFocalPlane(), Isis::CameraDetectorMap::SetParent(), Isis::RollingShutterCameraDetectorMap::SetParent(), setTime(), Isis::RadarSlantRangeMap::SetUndistortedFocalPlane(), Isis::ApolloMetricCamera::ShutterOpenCloseTimes(), Isis::IssNACamera::ShutterOpenCloseTimes(), Isis::IssWACamera::ShutterOpenCloseTimes(), Isis::HiresCamera::ShutterOpenCloseTimes(), Isis::LwirCamera::ShutterOpenCloseTimes(), Isis::NirCamera::ShutterOpenCloseTimes(), Isis::UvvisCamera::ShutterOpenCloseTimes(), Isis::ClipperWacFcCamera::ShutterOpenCloseTimes(), Isis::DawnFcCamera::ShutterOpenCloseTimes(), Isis::SsiCamera::ShutterOpenCloseTimes(), Isis::HayabusaAmicaCamera::ShutterOpenCloseTimes(), Isis::HayabusaNirsCamera::ShutterOpenCloseTimes(), Isis::Hyb2OncCamera::ShutterOpenCloseTimes(), Isis::JunoCamera::ShutterOpenCloseTimes(), Isis::LoHighCamera::ShutterOpenCloseTimes(), Isis::LoMediumCamera::ShutterOpenCloseTimes(), Isis::Mariner10Camera::ShutterOpenCloseTimes(), Isis::MdisCamera::ShutterOpenCloseTimes(), Isis::MexHrscSrcCamera::ShutterOpenCloseTimes(), Isis::MsiCamera::ShutterOpenCloseTimes(), Isis::NewHorizonsLorriCamera::ShutterOpenCloseTimes(), Isis::NewHorizonsMvicFrameCamera::ShutterOpenCloseTimes(), Isis::OsirisRexOcamsCamera::ShutterOpenCloseTimes(), Isis::OsirisRexTagcamsCamera::ShutterOpenCloseTimes(), Isis::RosettaOsirisCamera::ShutterOpenCloseTimes(), Isis::TgoCassisCamera::ShutterOpenCloseTimes(), Isis::VikingCamera::ShutterOpenCloseTimes(), Isis::VoyagerCamera::ShutterOpenCloseTimes(), Isis::FramingCamera::ShutterOpenCloseTimes(), Isis::Camera::StartEndEphemerisTimes(), and Isis::UvvisCamera::UvvisCamera().
UniversalLatitude()
double Isis::Sensor::UniversalLatitude () const virtual
Returns the planetocentric latitude, in degrees, at the surface intersection point in the body fixed coordinate system.
Returns
double Universal latitude, in degrees.
References Isis::Angle::degrees(), and GetLatitude().
Referenced by Isis::CameraStatistics::addStats(), Isis::ProjectionFactory::CreateForCube(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::QnetCubeDistanceFilter::filter(), Isis::InterestOperator::FindCnetRef(), Isis::Cube::latLonRange(), Isis::Chip::Load(), Isis::Camera::NorthAzimuth(), Isis::LatLonGridTool::paintViewport(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::Camera::SetRightAscensionDeclination(), and Isis::UniversalGroundMap::UniversalLatitude().
UniversalLongitude()
double Isis::Sensor::UniversalLongitude () const virtual
Returns the positive east, 0-360 domain longitude, in degrees, at the surface intersection point in the body fixed coordinate system.
Returns
double Universal longitude, in degrees.
References Isis::Angle::degrees(), and GetLongitude().
Referenced by Isis::CameraStatistics::addStats(), Isis::ProjectionFactory::CreateForCube(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::QnetCubeDistanceFilter::filter(), Isis::InterestOperator::FindCnetRef(), Isis::Cube::latLonRange(), Isis::Chip::Load(), LocalSolarTime(), Isis::LatLonGridTool::paintViewport(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::Camera::SetRightAscensionDeclination(), and Isis::UniversalGroundMap::UniversalLongitude().
Member Data Documentation
m_BJ
SpiceDouble Isis::Spice::m_BJ[3][3] protected inherited
This contains the transformation matrix from J2000 (J) to Body fixed (B).
Recall that the transpose of this matrix JB will convert from body-fixed to J2000. It is left in protected space so that conversions between double and SpiceDouble do not have to occur in inheriting classes.
m_et
iTime* Isis::Spice::m_et protected inherited
Ephemeris time (read NAIF documentation for a detailed description)
Referenced by Isis::CSMCamera::SetGround(), and Isis::CSMCamera::SetImage().
m_lookB
SpiceDouble Isis::Sensor::m_lookB[3] protected
Look direction in body fixed.
Referenced by lookDirectionBodyFixed(), Isis::CSMCamera::SetGround(), SetLookDirection(), Isis::CSMCamera::SetLookDirection(), and SpacecraftSurfaceVector().
m_newLookB
bool Isis::Sensor::m_newLookB protected
flag to indicate we need to recompute ra/dec
Referenced by Declination(), RightAscension(), Sensor(), Isis::CSMCamera::SetGround(), SetLookDirection(), and Isis::CSMCamera::SetLookDirection().
m_solarLongitude
Longitude* Isis::Spice::m_solarLongitude protected inherited
Body rotation solar longitude value.
m_target
Target* Isis::Spice::m_target protected inherited
Target of the observation.
Referenced by Isis::CSMCamera::setTarget().
m_uB
SpiceDouble Isis::Spice::m_uB[3] protected inherited
This contains the sun position (u) in the bodyfixed reference frame (B).
It is left protected so that conversions between double and SpiceDouble do not have to occur in inheriting classes. Units are km
Referenced by IncidenceAngle(), Isis::Camera::LocalPhotometricAngles(), and PhaseAngle().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Sensor/Sensor.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/base/objs/Sensor/Sensor.cpp