Isis Developer Reference: Isis::ControlHealthMonitorWidget Class Reference
Isis::ControlHealthMonitorWidget Class Reference
Interface that allows real-time evaluation of the state of a Control Network.
#include <ControlHealthMonitorWidget.h>
Public Slots
void emitOpenImageEditor ()
This method is designed to be called whenever a user double-clicks on an image in the image table of the images tab.
void emitOpenPointEditor ()
This method is designed to be called whenever a user double-clicks on a point in the point table of the points tab.
void historyEntry (QString, QString, QVariant, QVariant, QString)
This SLOT is designed to intercept the historyEntry() signal emitted from the ControlNetVitals class whenever a modification is made to the network.
void viewPointAll ()
void viewPointFree ()
void viewPointFixed ()
void viewPointConstrained ()
void viewPointIgnored ()
void viewPointEditLocked ()
void viewPointFewMeasures ()
void viewImageAll ()
void viewImageFewMeasures ()
void viewImageHullTolerance ()
void update ()
This SLOT is called whenever the is a change made to the network embedded in the Global m_vitals object.
Signals
void openPointEditor (ControlPoint *point)
void openImageEditor (QList< QString > serials)
Public Member Functions
ControlHealthMonitorWidget (ControlNetVitals *vitals, QWidget *parent=0)
This class is the front end representation of a ControlNetVitals object.
~ControlHealthMonitorWidget ()
Destructor.
void createGui ()
This method is responsible for creating all of the components that comprise the GUI.
QWidget * createImagesTab ()
QWidget * createPointsTab ()
QWidget * createOverviewTab ()
QWidget * createGraphTab ()
void setVitals (ControlNetVitals *vitals)
void initializeEverything ()
Initializes all member variables to NULL.
Detailed Description
Interface that allows real-time evaluation of the state of a Control Network.
Author
2018-05-28 Adam Goins
Constructor & Destructor Documentation
ControlHealthMonitorWidget()
Isis::ControlHealthMonitorWidget::ControlHealthMonitorWidget (ControlNetVitals * vitals, QWidget * parent = 0)
This class is the front end representation of a ControlNetVitals object.
It will accept a ControlNetVitals object upon initialization and reflects the current real-time status of the embedded ControlNet in the ControlNetVitals object.
Parameters
vitals (ControlNetVitals *) The ControlNetVitals object that contains the ControlNet.
parent (QWidget *) Pointer to parent widget
References createGui(), historyEntry(), and update().
~ControlHealthMonitorWidget()
Isis::ControlHealthMonitorWidget::~ControlHealthMonitorWidget ()
Destructor.
Member Function Documentation
createGraphTab()
QWidget * Isis::ControlHealthMonitorWidget::createGraphTab ()
createGui()
void Isis::ControlHealthMonitorWidget::createGui ()
This method is responsible for creating all of the components that comprise the GUI.
References createImagesTab(), createOverviewTab(), createPointsTab(), and initializeEverything().
Referenced by ControlHealthMonitorWidget().
createImagesTab()
QWidget * Isis::ControlHealthMonitorWidget::createImagesTab ()
References emitOpenImageEditor(), viewImageAll(), viewImageFewMeasures(), and viewImageHullTolerance().
Referenced by createGui().
createOverviewTab()
QWidget * Isis::ControlHealthMonitorWidget::createOverviewTab ()
Referenced by createGui().
createPointsTab()
QWidget * Isis::ControlHealthMonitorWidget::createPointsTab ()
References emitOpenPointEditor(), viewPointAll(), viewPointConstrained(), viewPointEditLocked(), viewPointFewMeasures(), viewPointFixed(), viewPointFree(), and viewPointIgnored().
Referenced by createGui().
emitOpenImageEditor
void Isis::ControlHealthMonitorWidget::emitOpenImageEditor () slot
This method is designed to be called whenever a user double-clicks on an image in the image table of the images tab.
It will grab the selected images and emit the openImageEditor() signal, emitting with it the images that were selected.
The openImageEditor() signal is intercepted by the ControlHealthMonitorView and opens the CubeDnView with the images selected.
References openImageEditor().
Referenced by createImagesTab().
emitOpenPointEditor
void Isis::ControlHealthMonitorWidget::emitOpenPointEditor () slot
This method is designed to be called whenever a user double-clicks on a point in the point table of the points tab.
It will grab the selected point and emit the openPointEditor() signal, emitting with it the point that was selected.
The openPointEditor() signal is intercepted by the ControlHealthMonitorView and opens the ControlPointEditWidget with that point selected.
References Isis::ControlNetVitals::getPoint(), and openPointEditor().
Referenced by createPointsTab().
historyEntry
void Isis::ControlHealthMonitorWidget::historyEntry (QString entry, QString id, QVariant oldValue, QVariant newValue, QString timeStamp) slot
This SLOT is designed to intercept the historyEntry() signal emitted from the ControlNetVitals class whenever a modification is made to the network.
The signal emits several details pertaining to the history entry.
Parameters
entry The history comment to be displayed.
id The id of the Control Point, Measure, or Network that was modified.
oldValue The old value before the modification was made.
newValue The new value after the modification was made.
timeStamp The timestamp of when the modification was made.
Referenced by ControlHealthMonitorWidget().
initializeEverything()
void Isis::ControlHealthMonitorWidget::initializeEverything ()
Initializes all member variables to NULL.
Referenced by createGui().
openImageEditor
void Isis::ControlHealthMonitorWidget::openImageEditor (QList< QString > serials) signal
Referenced by emitOpenImageEditor().
openPointEditor
void Isis::ControlHealthMonitorWidget::openPointEditor (ControlPoint * point) signal
Referenced by emitOpenPointEditor().
setVitals()
void Isis::ControlHealthMonitorWidget::setVitals (ControlNetVitals * vitals)
update
void Isis::ControlHealthMonitorWidget::update () slot
This SLOT is called whenever the is a change made to the network embedded in the Global m_vitals object.
Changes are detected via the networkChanged() signal which is emitted from the ControlNetVitals object which is triggered whenever networkStructureModified() is emitted from the embedded ControlNet.
References Isis::ControlNetVitals::getNetworkId(), Isis::ControlNetVitals::getStatus(), Isis::ControlNetVitals::getStatusDetails(), Isis::ControlNetVitals::numConstrainedPoints(), Isis::ControlNetVitals::numFixedPoints(), Isis::ControlNetVitals::numFreePoints(), Isis::ControlNetVitals::numIgnoredPoints(), Isis::ControlNetVitals::numImages(), Isis::ControlNetVitals::numImagesBelowHullTolerance(), Isis::ControlNetVitals::numImagesBelowMeasureThreshold(), Isis::ControlNetVitals::numLockedPoints(), Isis::ControlNetVitals::numMeasures(), Isis::ControlNetVitals::numPoints(), Isis::ControlNetVitals::numPointsBelowMeasureThreshold(), Isis::toString(), viewImageAll(), and viewPointAll().
Referenced by ControlHealthMonitorWidget().
viewImageAll
void Isis::ControlHealthMonitorWidget::viewImageAll () slot
References Isis::ControlNetVitals::getCubeSerials(), Isis::ControlNetVitals::numImages(), and Isis::toString().
Referenced by createImagesTab(), and update().
viewImageFewMeasures
void Isis::ControlHealthMonitorWidget::viewImageFewMeasures () slot
References Isis::ControlNetVitals::getImagesBelowMeasureThreshold(), Isis::ControlNetVitals::numImages(), Isis::ControlNetVitals::numImagesBelowMeasureThreshold(), and Isis::toString().
Referenced by createImagesTab().
viewImageHullTolerance
void Isis::ControlHealthMonitorWidget::viewImageHullTolerance () slot
References Isis::ControlNetVitals::getImagesBelowHullTolerance(), Isis::ControlNetVitals::numImages(), Isis::ControlNetVitals::numImagesBelowHullTolerance(), and Isis::toString().
Referenced by createImagesTab().
viewPointAll
void Isis::ControlHealthMonitorWidget::viewPointAll () slot
References Isis::ControlNetVitals::getAllPoints(), Isis::ControlNetVitals::numPoints(), and Isis::toString().
Referenced by createPointsTab(), and update().
viewPointConstrained
void Isis::ControlHealthMonitorWidget::viewPointConstrained () slot
References Isis::ControlNetVitals::getConstrainedPoints(), Isis::ControlNetVitals::numConstrainedPoints(), Isis::ControlNetVitals::numPoints(), and Isis::toString().
Referenced by createPointsTab().
viewPointEditLocked
void Isis::ControlHealthMonitorWidget::viewPointEditLocked () slot
References Isis::ControlNetVitals::getLockedPoints(), Isis::ControlNetVitals::numLockedPoints(), Isis::ControlNetVitals::numPoints(), and Isis::toString().
Referenced by createPointsTab().
viewPointFewMeasures
void Isis::ControlHealthMonitorWidget::viewPointFewMeasures () slot
References Isis::ControlNetVitals::getPointsBelowMeasureThreshold(), Isis::ControlNetVitals::numPoints(), Isis::ControlNetVitals::numPointsBelowMeasureThreshold(), and Isis::toString().
Referenced by createPointsTab().
viewPointFixed
void Isis::ControlHealthMonitorWidget::viewPointFixed () slot
References Isis::ControlNetVitals::getFixedPoints(), Isis::ControlNetVitals::numFixedPoints(), Isis::ControlNetVitals::numPoints(), and Isis::toString().
Referenced by createPointsTab().
viewPointFree
void Isis::ControlHealthMonitorWidget::viewPointFree () slot
References Isis::ControlNetVitals::getFreePoints(), Isis::ControlNetVitals::numFreePoints(), Isis::ControlNetVitals::numPoints(), and Isis::toString().
Referenced by createPointsTab().
viewPointIgnored
void Isis::ControlHealthMonitorWidget::viewPointIgnored () slot
References Isis::ControlNetVitals::getIgnoredPoints(), Isis::ControlNetVitals::numIgnoredPoints(), Isis::ControlNetVitals::numPoints(), and Isis::toString().
Referenced by createPointsTab().
The documentation for this class was generated from the following files:
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ControlHealthMonitorWidget/ControlHealthMonitorWidget.h
/home/gengxun/PlanetaryMapping/asp360_new/pyisis/ISIS3-9.0.0-ext/isis/src/qisis/objs/ControlHealthMonitorWidget/ControlHealthMonitorWidget.cpp