Isis Developer Reference: Mars Reconnaissance Orbiter
Mars Reconnaissance Orbiter
Mission Specific Objects
These objects provide functionality for manipulating data from the Mars Reconnaissance Orbiter mission.Mars Reconnaissance Orbiter, scheduled for launch in 2005, is on a search for evidence that water persisted on the surface of Mars for a long period of time.
Classes
class Isis::CrismCamera
MRO CRISM camera model.
class Isis::CTXCamera
MRO CTX Camera Model.
class Isis::HiBlob
BLOB extraction class.
class Isis::HiLab
Process HiRise label.
class Isis::HiriseCamera
Hirise Camera Model.
class Isis::MarciCamera
Marci Camera Model.
class Isis::MarciDistortionMap
Distort/undistort focal plane coordinates.
Functions
Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera (Cube &cube)
Constructs a Chandrayaan 1 M3 Camera object using the image labels.
Detailed Description
These objects provide functionality for manipulating data from the Mars Reconnaissance Orbiter mission.Mars Reconnaissance Orbiter, scheduled for launch in 2005, is on a search for evidence that water persisted on the surface of Mars for a long period of time.
While other Mars missions have shown that water flowed across the surface in Mars' history, it remains a mystery whether water was ever around long enough to provide a habitat for life.
Mission site: http://mars3.jpl.nasa.gov/mro/
Function Documentation
Chandrayaan1M3Camera()
Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera (Cube & cube)
Constructs a Chandrayaan 1 M3 Camera object using the image labels.
Author
2013-08-18 Stuart Sides and Tracie Sucharski
References Isis::NaifStatus::CheckErrors(), Isis::iTime::Et(), Isis::PvlObject::findGroup(), Isis::Spice::getClockTime(), Isis::Spice::getDouble(), Isis::Cube::label(), Isis::Camera::LoadCache(), Isis::Camera::m_instrumentNameLong, Isis::Camera::m_instrumentNameShort, Isis::Camera::m_spacecraftNameLong, Isis::Camera::m_spacecraftNameShort, Isis::Spice::naifIkCode(), Isis::CameraFocalPlaneMap::SetDetectorOffset(), Isis::CameraFocalPlaneMap::SetDetectorOrigin(), Isis::CameraDetectorMap::SetDetectorSampleSumming(), Isis::Camera::SetFocalLength(), Isis::Camera::SetPixelPitch(), Isis::toString(), and Isis::PvlObject::Traverse.