Isis Developer Reference: Isis Namespace Reference
Isis Namespace Reference
This is free and unencumbered software released into the public domain.
Namespaces
GSL
Lo
Namespace for all Isis Lunar Orbiter mission objects.
Lro
Namespace for all Isis Lunar Reconnaissance Orbiter mission objects.
Message
Namespace containing standardized Isis error messages.
Mgs
Namespace for all Isis Mars Global Surveyor mission objects.
Mro
Namespace for all Isis Mars Reconnaissance Orbiter mission objects.
Odyssey
Namespace for all Isis Mars Odyssey mission objects.
Radar
Classes
class Apollo
Reads user Apollos from a data file.
class ApolloMetricCamera
Apollo Metric Camera Model.
class ApolloMetricDistortionMap
Apollo Metric Distortion Map.
class ApolloPanIO
Calculates a series of affine transformations from the measured coordinates of the up to 90 fiducial marks on a complete (stiched) apollo panoramic cube.
class ApolloPanoramicCamera
Apollo Panoramic Camera.
class ApolloPanoramicDetectorMap
Convert between parent image (aka encoder aka machine) coordinates and detector coordinates.
class CentroidApolloPan
Selection class derived from the Pure Virtual Parent Class for all Selection classes.
class AbstractPlate
Abstract interface to a TIN plate.
class AdaptiveGruen
Gruen (adaptive) pattern matching.
class Affine
Affine basis function.
class Albedo
Albedo normalization.
class AlbedoAtm
Albedo normalization with atmosphere.
class AlphaCube
This class is used to rewrite the "alpha" keywords out of the AlphaCube group or Instrument group.
class Angle
Defines an angle and provides unit conversions.
class Anisotropic1
class Anisotropic2
class Application
class Area3D
Represents a 3D area (a 3D "cube")
class AtmosModel
Isotropic atmos scattering model.
class NumericalAtmosApprox
This class extends Isis::NumericalApproximation.
class AtmosModelFactory
This class is used to create AtmosModel objects.
class AutoReg
Auto Registration class.
class AutoRegFactory
This class is used to create AutoReg objects.
class BandManager
Buffer manager, for moving through a cube in bands.
class Basis1VariableFunction
Time based linear equation class.
class BasisFunction
Generic linear equation class.
class Blob
class Blobber
Base class for accessing ISIS blobs.
class BoxcarCachingAlgorithm
This algorithm is designed for applications that jump around between a couple of spots in the cube with a difficult to predict pattern but always the same places in the cube.
class BoxcarManager
Buffer manager, for moving through a cube by boxcar.
class Brick
Buffer for containing a three dimensional section of an image.
class Buffer
Buffer for reading and writing cube data.
class BufferManager
Manages a Buffer over a cube.
class BulletDskShape
Bullet Target Shape for NAIF type 2 DSK models.
class BulletAllHitsRayCallback
Bullet ray tracing callback to return all intersections along a ray's path.
class BulletClosestRayCallback
Bullet ray tracing callback for closest hit on target surface.
class BulletShapeModel
Shape model that uses the Bullet library to perform ray tracing.
class BulletTargetShape
Bullet Target Shape for planetary bodies.
class BulletWorldManager
Bullet World manager maintains a proper state for target bodies.
class Calculator
Calculator for arrays.
class Camera
class CameraDetectorMap
Convert between parent image coordinates and detector coordinates.
class CameraDistortionMap
Distort/undistort focal plane coordinates.
class CameraFactory
Initializes a Camera Model.
class CameraFocalPlaneMap
Convert between distorted focal plane and detector coordinates.
class CameraGroundMap
Convert between undistorted focal plane and ground coordinates.
class CameraPointInfo
CameraPointInfo provides quick access to the majority of information avaliable from a camera on a point.
class CameraSkyMap
Convert between undistorted focal plane and ra/dec coordinates.
class CameraStatistics
Calculates a series of statistics pertaining to a Camera.
class Centroid
Selection class derived from the Pure Virtual Parent Class for all Selection classes.
class Chip
A small chip of data used for pattern matching.
struct SimpleCompare
Provides a simple comparison between two values.
struct NoCaseStringCompare
Provides a case insensitive string comparison.
struct RobustFloatCompare
Provides a robust comparison of double/float values.
struct NoopRemoval
Supplies a NOOP default for removal of a CollectorMap entry.
struct PointerRemoval
Supplies a policy for deleting pointers that CollectorMap owns.
struct ArrayRemoval
Policy for deleting arrays that CollectorMap owns.
struct DefaultCopy
(Default) Policy for copying map elements
struct PointerCopy
Pointer to object policy for copying map elements.
class CollectorMap
Collector/container for arbitrary items.
class Color
This class is designed to serialize QColor in a human-readable form.
class Column
Format ascii tables.
class CSMCamera
class CSMSkyMap
Convert between undistorted focal plane and ra/dec coordinates.
class CSVParser
CSV Parser seperates fields (tokens) from a string with a delimeter.
class CSVReader
Reads strings and parses them into tokens separated by a delimiter character.
class Cube
IO Handler for Isis Cubes.
class CubeBsqHandler
IO Handler for Isis Cubes using the BSQ format.
class CubeIoHandler
Handles converting buffers to and from disk.
class CubeTileHandler
IO Handler for Isis Cubes using the tile format.
class RawCubeChunk
A section of raw data on the disk.
class RegionalCachingAlgorithm
This algorithm recommends chunks to be freed that are not within the last IO.
class CubeAttribute
Parent class for CubeAttributeInput and CubeAttributeOutput.
class CubeAttributeInput
Manipulate and parse attributes of input cube filenames.
class CubeAttributeOutput
Manipulate and parse attributes of output cube filenames.
class CubeCachingAlgorithm
This is the parent of the caching algorithms.
class CubeCalculator
Calculator for arrays.
class DataValue
This class is used to define what kind of data is being pushed onto the cube calculator.
class CameraBuffers
This class is used to manage buffers for calculating camera related information, such as angles, radii, and resolution.
class CubeDataThread
Encapsulation of Cube I/O with Change Notifications.
class CubeDataThreadTester
class CubeInfixToPostfix
Converter for math equations.
class CubeManager
Class for quick re-accessing of cubes based on file name.
class CubeStretch
Stores stretch information for a cube.
class DemShape
Define shapes and provide utilities for targets stored as ISIS maps.
class Displacement
Displacement is a signed length, usually in meters.
class Distance
Distance measurement, usually in meters.
class EllipsoidShape
Define shapes and provide utilities for ISIS targets.
class EmbreeShapeModel
General purpose Embree ray tracing model.
class EmbreeTargetManager
Class for managing the construction and destruction of EmbreeTargetShapes.
struct RTCMultiHitRay
Struct for capturing multiple intersections when using embree::rtcintersectscene.
struct RTCOcclusionRay
Struct for capturing occluded plates when using embree::rtcintersectscene.
struct RayHitInformation
Container that holds the body fixed intersection point and unit surface normal for a hit.
class EmbreeTargetShape
Embree Target Shape for planetary bodies.
class EndianSwapper
Byte swapper.
class Enlarge
Enlarge the pixel dimensions of an image.
class Environment
class Equalization
This class can be used to calculate, read in, and/or apply equalization statistics for a list of files.
class EquatorialCylindricalShape
Define shapes and provide utilities for shapes stored as ISIS EquatorialCylindrical map.
class Equirectangular
Equirectangular Map Projection.
class ExportDescription
Describes how a series of cubes should be exported.
class ExportPdsTable
Export a PDS table from an ISIS Table.
class FileList
Internalizes a list of files.
class FileName
File name manipulation and expansion.
class FilterCachingAlgorithm
This algorithm is designed for applications that use ProcessByQuickFilter or very similar I/O patterns to cache cube data appropriately.
class ForstnerOperator
Forstner interest operator.
class FourierTransform
Fourier Transform class.
class FramingCamera
Generic class for Framing Cameras.
class FunctionTools
A collection of tools for mathmatical function root finding, maximization, etc (eventually) This class contains only static methods, and cannot be instantiated.
class GaussianDistribution
gaussian distribution class
class GaussianStretch
Gaussian stretch class.
class GisGeometry
Encapsulation class provides support for GEOS-C API.
class GisTopology
This class models GIS topology.
class GradientOperator
Gradient interest operator.
class GridPolygonSeeder
Seed points using a grid.
class GroundGrid
Calculates a lat/lon grid over an area.
class GroupedStatistics
Grouped Statistics.
class Gruen
Gruen pattern matching algorithm.
class Coordinate
Define a generic Y/X container.
class PointPair
Define a point set of left, right and geometry at that location.
class Radiometric
Store for radiometric gain and shift parameters.
class AffineRadio
Container for affine and radiometric parameters.
struct AffineTolerance
Container for Affine limits parameters.
class Threshold
Compute/test the Affine convergence from given parameters/chip.
struct Analysis
Error analysis of Gruen match point solution.
class MatchPoint
Structure containing comprehensive registration info/results.
class Gui
Gui for Isis Applications.
class GuiBooleanParameter
class GuiComboBoxParameter
class GuiCubeParameter
class GuiDoubleParameter
class GuiEditFile
Opens a window in Gui Application to be able to edit, save and create text files.
class GuiFileNameParameter
class GuiHelperAction
class GuiInputAttribute
GUI interface for input cube file attributes.
class GuiIntegerParameter
class GuiListParameter
class GuiLog
class GuiOutputAttribute
class GuiParameter
class GuiParameterFactory
class GuiStringParameter
class Hapke
Hapke-Henyey-Greenstein photometric model.
class HapkeAtm1
Implements the Hapke Atmospheric Model.
class HapkeAtm2
class Hillshade
Calculate light intensity reflected off a local slope of DEM.
class Histogram
Container of a cube histogram.
class History
class ID
Creates sequential IDs.
class IdealCamera
Ideal Camera Model.
class IException
Isis exception class.
class ImageExporter
Export Isis cubes into standard formats.
class ImageHistogram
Container of a cube histogram.
class ImageImporter
Imports images with standard formats into Isis as cubes.
class ImageOverlap
Individual overlap container.
class ImageOverlapSet
This class is used to find the overlaps between all the images in a list of serial numbers.
class ImagePolygon
Create cube polygons, read/write polygons to blobs.
class ImportPdsTable
Import a PDS table file with a label description.
class InfixToPostfix
Converter for math equations.
class InfixOperator
InfixOperator and InfixFunction are helper classes for InfixToPostfix.
class InfixFunction
InfixOperator and InfixFunction are helper classes for InfixToPostfix.
class InlineCalculator
Provides a calculator for inline equations.
class CalculatorVariablePool
This is a simple class to model a Calculator Variable Pool.
class FxBinder
This is the parent class to the various function classes.
class InlineVoidFx
This class is used to bind function names with corresponding InlineCalculator functions that do not take parameters.
class ParameterFx
This class is used to bind function names with corresponding Calculator functions that take a parameter.
class VoidFx
This class is used to bind function names with corresponding Calculator functions that do not take parameters.
class InlineInfixToPostfix
A parser for converting equation strings to postfix.
class Intercept
Container for a intercept condition.
class Interpolator
Pixel interpolator.
class IrregularBodyCameraGroundMap
Convert between undistorted focal plane and ground coordinates.
class Isotropic1
class Isotropic2
class IString
Adds specific functionality to C++ strings.
class iTime
Parse and return pieces of a time string.
class JP2Decoder
JPEG2000 decoder class.
class JP2Encoder
JPEG2000 encoder class.
class JP2Error
Kakadu error messaging class.
class JP2Exporter
Exports cubes into JPEG 2000 images.
class JP2Importer
Imports JPEG 2000 images as Isis cubes.
class Kernels
Determine SPICE kernels defined in an ISIS file.
class LabelTranslationManager
Allows applications to translate simple text files.
class Lambert
class LambertAzimuthalEqualArea
Lambert Azimuthal Equal Area Map Projection.
class LambertConformal
Lambert Conformal Map Projection.
class Latitude
This class is designed to encapsulate the concept of a Latitude.
class LeastSquares
Generic least square fitting class.
class LidarData
LidarData class.
class LimitPolygonSeeder
Seed points using a grid.
class LinearAlgebra
This class holds all static methods to perform linear algebra operations on vectors and matrices.
class LineEquation
Utility class for creating and using cartesean line equations.
class LineManager
Buffer manager, for moving through a cube in lines.
class LineScanCamera
Generic class for Line Scan Cameras.
class LineScanCameraDetectorMap
Convert between parent image coordinates and detector coordinates.
class LineScanCameraGroundMap
Convert between undistorted focal plane and ground coordinates.
class LineScanCameraSkyMap
Convert between undistorted focal plane and ra/dec coordinates.
class LommelSeeliger
class Longitude
This class is designed to encapsulate the concept of a Longitude.
class LunarAzimuthalEqualArea
Modified Lambert Azimuthal Equal-Area Map Projection.
class LunarLambert
Lunar (Lommel-Seeliger)-Lambert law photometric model Derive model albedo for Lunar (Lommel-Seeliger)-Lambert law.
class LunarLambertEmpirical
Empirical Lunar Lambert photometric model Derive model albedo using phase dependent Minnaert equation and calculated empirically.
class LunarLambertMcEwen
Moonpr photometric model Computes normalized albedo for the Moon, normalized to 0 degrees emission angle and 30 degrees illumination and phase angles.
class Matrix
Matrix class.
class MaximumCorrelation
Maximum correlation pattern matching.
class Mercator
Mercator Map Projection.
class MinimumDifference
Minimum difference pattern matching.
class Minnaert
Minnaert photometric model Derive model albedo using Minnaert equation.
class MinnaertEmpirical
Empirical Minnaert photometric model Derive model albedo using phase dependent Minnaert equation and calculated empirically.
class Mixed
Mixed albedo/topo normalization without atmosphere.
class Mollweide
Mollweide Map Projection.
class MoonAlbedo
Albedo dependent phase function normalization for the Moon.
class MoravecOperator
Moravec Interest Operator.
class MultivariateStatistics
Container of multivariate statistics.
class NaifDskPlateModel
Implementation interface API for NAIF's DSK plate model.
class NaifDskShape
Provides support for NAIF's Digital Shape Kernel (DSK)
class NaifStatus
Class for checking for errors in the NAIF library.
class NoNormalization
NoNormalization - perform simple correction without normalization (a*dn +b)
class NoOperator
no interest operator
class NormModel
class NormModelFactory
This class is used to create NormModel objects.
class NthOrderPolynomial
NthOrderPolynomial basis function.
class NumericalApproximation
NumericalApproximation provides various numerical analysis methods of interpolation, extrapolation and approximation of a tabulated set of x, y data.
class ObliqueCylindrical
Oblique Cylindrical Map Projection.
class ObservationNumber
Serial Number composer.
class ObservationNumberList
Create a list of observation numbers from a file or serial number list.
class OriginalLabel
Read and store original labels.
class OriginalXmlLabel
Read and store original Xml labels.
class Orthographic
Orthographic Map Projection.
class OverlapNormalization
Calculate the bases and multipliers for normalizing overlapping "data sets" (e.g., cubes).
class OverlapStatistics
Calculates statistics in the area of overlap between two projected cubes.
class Photometry
class PhotoModel
class PhotoModelFactory
This class is used to create PhotoModel objects.
class Pipeline
This class helps to call other Isis Applications in a Pipeline.
class PipelineApplication
This class represents one application in the pipeline.
class PipelineParameter
This class represents a parameter of some type for the PipelineApplication.
class Pixel
Store and/or manipulate pixel values.
class PixelFOV
This class defines a field of view.
class Planar
Planar Map Projection.
class PlaneShape
Define plane shape model.
class Plugin
Loads plugins from a shared library.
class PointPerspective
PointPerspective Map Projection.
class PolarStereographic
Stereographic Map Projection for Polar Aspect.
class PolygonSeeder
This class is used as the base class for all PolygonSeeder objects.
class PolygonSeederFactory
This class is used to create PolygonSeeder objects.
class PolygonTools
Provides various tools to work with geos multipolygons.
class PolynomialBivariate
Nth degree Polynomial with two variables.
class PolynomialUnivariate
Nth degree Polynomial with one variable.
class Portal
Buffer for containing a two dimensional section of an image.
class Preference
Reads user preferences from a data file.
class PrincipalComponentAnalysis
Principal Component Analysis class.
class Process
Base class for all cube processing derivatives.
class ProcessByBoxcar
Process cubes by boxcar.
class ProcessByBrick
Process cubes by brick.
class ProcessByLine
Process cubes by line.
class ProcessByQuickFilter
Process cubes using a Filter Object.
class ProcessBySample
Process cubes by sample.
class ProcessBySpectra
Process cubes by spectra.
class ProcessByTile
Process cubes by tile.
class ProcessExport
Process class for exporting cubes.
class ProcessExportPds
Process class for exporting cubes to PDS standards.
class ProcessExportPds4
Process class for exporting cubes to PDS4 standards.
class ProcessGroundPolygons
Process cube polygons to map or camera projections.
class ProcessImport
Byte swapper.
class ProcessImportFits
Import a FITS file.
class ProcessImportPds
Convert PDS archive files to Isis format.
class ProcessImportVicar
Import a Vicar file.
class ProcessMapMosaic
Mosaic two cubs together.
class ProcessMosaic
Mosaic two cubes together.
class ProcessPolygons
class ProcessRubberSheet
Derivative of Process, designed for geometric transformations.
class ProgramLauncher
Execute External Programs and Commands.
class Progress
Program progress reporter.
class Projection
Base class for Map Projections.
class ProjectionFactory
Initialize a map projection.
class PFPixelMapper
class PushFrameCamera
Generic class for Push Frame Cameras.
class PushFrameCameraCcdLayout
Provide image coordinates that map to the push frame detector.
class PushFrameCameraDetectorMap
Convert between parent image coordinates and detector coordinates.
class PushFrameCameraGroundMap
Convert between undistorted focal plane and ground coordinates.
class Pvl
Container for cube-like labels.
class PvlContainer
Contains more than one keyword-value pair.
class PvlEditDialog
PvlEditDialog creates a QDialog window in which a QTextEdit box displays the contents of a pvl file.
class PvlConstraints
This class can be used to define import/export behavior of Pvl structures when used in the PvlFlatMap class.
class PvlFlatMap
Provides a flat map of PvlKeywords.
class PvlFormat
Formats a Pvl name value pair to Isis standards.
class PvlFormatPds
Formats the value of a PvlKeyword into a PDS complient string.
class PvlGroup
Contains multiple PvlContainers.
class PvlKeyword
A single keyword-value pair.
class PvlObject
Contains Pvl Groups and Pvl Objects.
class PvlSequence
Parse and return elements of a Pvl sequence.
class PvlToken
Container for Keyword-value pair.
class PvlTokenizer
Construct Token list from a stream.
class PvlToPvlTranslationManager
Allows applications to translate simple text files.
class PvlToXmlTranslationManager
Allows applications to translate simple text files.
class PvlTranslationTable
Internalizes a translation table.
class QtExporter
Exports cubes into one of several formats with Qt facilities.
class QtImporter
Imports a series of standard image formats with Qt facilities.
class Quaternion
Provide operations for quaternion arithmetic.
class QuickFilter
Container for boxcar statistics.
class RadarCamera
Generic class for Radar Cameras.
class RadarGroundMap
Convert between undistorted focal plane coordinate (slant range) and ground coordinates.
class RadarGroundRangeMap
Construct a mapping between image sample and Radar ground range.
class RadarPulseMap
Convert between alpha image coordinates and radar sample, time coordinates.
class RadarSkyMap
Convert between slantrange/groundrange and ra/dec coordinates.
class RadarSlantRangeMap
Convert between radar ground range and slant range.
class RadialDistortionMap
class Reduce
Reduce the pixel dimensions of an image.
class Nearest
Functor for reduce using near functionality.
class Average
Functor for reduce using average functionality.
class ReseauDistortionMap
Distort/undistort focal plane coordinates.
class Resource
This class provides a resource of PVL keywords for Strategy classes.
class RingCylindrical
Ring Cylindrical Map Projection.
class RingPlaneProjection
Base class for Map Projections of plane shapes.
class Robinson
Robinson Map Projection.
class RollingShutterCamera
Generic class for Rolling Shutter Cameras.
class RollingShutterCameraDetectorMap
Convert between parent image coordinates and detector coordinates.
class SampleManager
Buffer manager, for moving through a cube in samples.
class Selection
Pure Virtual Parent Class for all Selection classes.
class Sensor
Class for computing sensor ground coordinates.
class CsmSensor
Implementation of the SensorUtilities::Sensor interface for a CSM RasterGM model.
class IsisBody
Implementation of SensorUtilities::Body backed by an ISIS SpiceRotation.
class IsisIlluminator
Implementation of SensorUtilities::Illuminator backed by an ISIS SpicePosition.
class IsisSensor
Implementation of SensorUtilities::Sensor backed by an ISIS camera model.
class IsisShape
Implementation of SensorUtilities::Shape backed by an ISIS ShapeModel.
class SerialNumber
Serial Number composer.
class SerialNumberList
Serial Number list generator.
class SessionLog
class Shade
class ShadeAtm
class ShapeModel
Define shapes and provide utilities for Isis targets.
class ShapeModelFactory
This class is used to create ShapeModel objects.
class SimpleCylindrical
Simple Cylindrical Map Projection.
class Sinusoidal
Sinusoidal Map Projection.
class SmtkMatcher
Workhorse of stereo matcher.
class PointGeometry
Container for a point and its geometry.
class SmtkPoint
Container for SMTK match points.
class SparseBlockColumnMatrix
SparseBlockColumnMatrix.
class SparseBlockRowMatrix
SparseBlockRowMatrix.
class SparseBlockMatrix
SparseBlockMatrix.
class Spectel
Stores information about a "Spectral pixel" or spectel.
class SpectralDefinition
contains calibration info for spectral smile correction (center wavelengths and widths for the whole nxn chip)
class SpectralDefinition1D
A Spectral definition that includes wavelength and center values for each (line, sample) coordinate.
class SpectralDefinition2D
A Spectral definition that includes wavelength and center values for each (line, sample) coordinate.
class SpectralDefinitionFactory
Constructs a 2D or 1D spectral definition based on the file name extension.
class LightTimeCorrectionState
Provides interface to user configurable Light Time correction feature.
class SpacecraftPosition
Provides swap observer/target and improved light time correction.
class Spice
Obtain SPICE information for a spacecraft.
class SpicePosition
Obtain SPICE position information for a body.
class SpiceRotation
Obtain SPICE rotation information for a body.
class StandardDeviationOperator
Standard deviation interest operator.
class StatCumProbDistDynCalc
This class is used to approximate cumulative probibility distributions of a stream of observations without storing the observations or having any apriori knowlege of the range of the data.
class Statistics
This class is used to accumulate statistics on double arrays.
class Stereo
Provide stereo information/data for a point or relationship.
class Strategy
Strategy - Supports algorithm development.
class StreamExporter
Exports cubes into a standard format in incremental pieces.
class Stretch
Pixel value mapper.
class StripPolygonSeeder
Seed points using a grid with a staggered pattern.
class SubArea
Apply corrections to a cube label for subarea extraction.
class SurfaceModel
Model a 3-D surface.
class SurfacePoint
This class defines a body-fixed surface point.
class Table
Class for storing Table blobs information.
class TableField
Class for storing an Isis::Table's field information.
class TableRecord
class Target
This class is used to create and store valid Isis targets.
class TextFile
Provides access to sequential ASCII stream I/O.
class TiffExporter
Exports cubes into TIFF images.
class TiffImporter
Imports TIFF images as Isis cubes.
class TileManager
Buffer manager, for moving through a cube in tiles.
class Topo
Topographic derivative of an arbitrary photometric function.
class TopoAtm
As in the case without an atmosphere, processing proceeds in three steps, a pass 1 PHOTOM followed by a divide filter to is- olate topography from albedo variations followed by a pass 2 PHOTOM.
class TProjection
Base class for Map TProjections.
class TrackingTable
Table to store tracking information for a mosaic.
class Transform
Pixel transformation.
class TransverseMercator
TransverseMercator Map Projection.
class TriangularPlate
Specification for an abstract triangular plate.
class UniqueIOCachingAlgorithm
This algorithm is designed for applications that jump around between a couple of spots in the cube with a difficult to predict pattern but always the same places in the cube.
class UniversalGroundMap
Universal Ground Map.
class UpturnedEllipsoidTransverseAzimuthal
Upturned Ellipsoid Transverse Azimuthal Map Projection.
class UserInterface
Command Line and Xml loader, validation, and access.
class VariableLineScanCameraDetectorMap
Convert between parent image coordinates and detector coordinates.
class LineRateChange
Container class for storing timing information for a section of an image.
class VecFilter
This class is used to perform filter operations on vectors.
class WorldMapper
Create a mapping between a projection and other coordinate system.
class XmlToPvlTranslationManager
Allows applications to translate Xml label files.
class CisscalFile
Extends TextFile to handle Cassini ISS calibration files.
class CissLabels
Read values from Cassini ISS labels.
class IssNACamera
Cassini ISS Narrow Angle Camera Model.
class IssWACamera
Cassini ISS Wide Angle Camera Model.
class VimsCamera
Cassini Vims camera model.
class VimsGroundMap
Convert between undistorted focal plane and ground coordinates.
class VimsSkyMap
Convert between undistorted focal plane and ground coordinates.
class Chandrayaan1M3Camera
Chandrayaan1 M3 Camera Model.
class Chandrayaan1M3DistortionMap
Distortion map for the Chandrayaan1 M3 camera.
class HiresCamera
This is the camera model for the Clementine High-Resolution Camera.
class LwirCamera
This is the camera model for the Clementine Long-Wavelength Infrared Camera.
class NirCamera
This is the camera model for the Clementine Near Infrared Camera.
class ClementineUvvisDistortionMap
Distortion map for the Clementine UVVIS camera.
class UvvisCamera
This is the camera model for the Clementine Ultraviolet/Visible Camera.
class ClipperNacRollingShutterCamera
Clipper EIS Camera model.
class ClipperPushBroomCamera
This is the camera model for the Europa Clipper Push Broom Camera.
class ClipperWacFcCamera
This is the camera model for the Europa Clipper WAC Framing Camera.
class BundleAdjust
An image bundle adjustment object.
class BundleResults
A container class for statistical results from a BundleAdjust solution.
class BundleSettings
Container class for BundleAdjustment settings.
class BundleSolutionInfo
Container class for BundleAdjustment results.
class BundleControlPoint
This class holds information about a control point that BundleAdjust needs to run correctly.
class BundleImage
This class hold image information that BundleAdjust needs to run correctly.Definition for a BundleImageQsp, a shared pointer to a BundleImage.
class BundleLidarControlPoint
This class holds information about a lidar control point that BundleAdjust requires.
class BundleLidarPointVector
This class is a container class for BundleLidarControlPoints.
class BundleLidarRangeConstraint
Implements range constraint between image position and lidar point acquired simultaneously with the image.
class BundleMeasure
A container class for a ControlMeasure.
class BundleObservation
Abstract base class for an observation in bundle adjustment.
class BundleObservationSolveSettings
This class is used to modify and manage solve settings for 1 to many BundleObservations.
class BundleObservationVector
This class is a container class for BundleObservations.
class BundleTargetBody
This class is used to represent a target body in a bundle and how to solve for it.
class IsisBundleObservation
Class for observations that use ISIS camera models in bundle adjustment.
class ControlMeasure
a control measurement
class ControlMeasureLogData
Statistical and similar ControlMeasure associated information.
class ControlNet
a control network
class ControlNetDiff
Compares two Control Networks and reports their differences.
class ControlNetFilter
Filter Control Network.
class ControlNetStatistics
Control Network Stats.
class ControlNetValidMeasure
ControlNetValidMeasure class.
class MeasureValidationResults
MeasureValidationResults class.
class ControlNetVersioner
Handle various control network file format versions.
class ControlPointV0001
A container for the information stored in a version 1 ControlPoint.
class ControlPointV0002
A container for the information stored in a version 2 ControlPoint.
class ControlPointV0003
A container for the information stored in a version 3 and 4 ControlPoint.
class ControlNetVitals
ControlNetVitals.
class ControlPoint
A single control point.
class ControlPointList
Control Point List generator.
class CorrelationMatrix
This is a container for the correlation matrix that comes from a bundle adjust.
class CsmBundleObservation
Class for observations that use CSM camera models in bundle adjustment.
class InterestOperator
Interest Operator class.
class InterestOperatorFactory
This class is used to create InterestOperator objects.
class LidarControlPoint
A lidar control ControlPoint.
class MaximumLikelihoodWFunctions
Class provides maximum likelihood estimation functions for robust parameter estimation, e.g.
class Database
Isis database class providing generalized access to a variety of databases.
class DatabaseFactory
Create database interfaces using access profiles or generic drivers.
class DbAccess
DbAccess manages programatic access to a database through profiles.
class DbProfile
A DbProfile is a container for access parameters to a database.
class SqlQuery
Construct and execute a query on a database and manage result.
class SqlRecord
Provide simplified access to resulting SQL query row.
class DawnFcCamera
This is the camera model for the Dawn Framing Camera.
class DawnFcDistortionMap
class DawnVirCamera
Camera model for both Danw VIR VIS and IR instruments.
class SsiCamera
This is the camera model for the Galileo Solid State Imaging Camera.
class HayabusaAmicaCamera
This is the camera model for the Hayabusa AMICA camera.
class HayabusaNirsCamera
This is the camera model for the Hayabusa NIRS camera.
class NirsDetectorMap
The detector map class for the Hayabusa NIRS camera.
class Hyb2OncCamera
This is the camera model for the Hayabusa2 ONC camera.
class Hyb2OncDistortionMap
Distort/undistort focal plane coordinates for Hayabusa 2's ONC cameras.
class JunoCamera
Juno's JNC (JunoCam) camera model.
class JunoDistortionMap
Distort/undistort focal plane coordinates for Juno's JunoCam camera.
class KaguyaMiCamera
Kaguya MI Camera Model.
class KaguyaMiCameraDistortionMap
Distort/undistort focal plane coordinates.
class KaguyaTcCamera
This is the camera model for the Kaguya Terrain Cameras TC1 and TC2.
class KaguyaTcCameraDistortionMap
Distort/undistort focal plane coordinates for Kaguya's TC cameras.
class LoCameraFiducialMap
Computes map from image coordinates to focal plane based on fiducials.
class LoHighCamera
Defines the Lunar Orbiter High Resolution camera class.
class LoHighDistortionMap
Distort/undistort focal plane coordinates.
class LoMediumCamera
Defines the Lunar Orbiter Medium Resolution camera class.
class LoMediumDistortionMap
Distort/undistort focal plane coordinates.
class LroNarrowAngleCamera
LRO Narrow Angle Camera Model.
class LroNarrowAngleDistortionMap
Distort/undistort focal plane coordinates.
class LroWideAngleCamera
LRO Wide Angle Camera Model.
class LroWideAngleCameraDistortionMap
Distort/undistort focal plane coordinates.
class LroWideAngleCameraFocalPlaneMap
Distort/undistort focal plane coordinates.
class MiniRF
LRO Mini-RF SAR and Chandrayaan 1 Mini-RF SAR.
class PhotometricFunction
An abstract implementation of the photometric function.
class Mariner10Camera
Mariner10 Camera Model.
class MdisCamera
MESSENGER MDIS NAC and WAC Camera Model.
class TaylorCameraDistortionMap
Distort/undistort focal plane coordinates.
class HrscCamera
HRSC Camera Model.
class MexHrscSrcCamera
This is the camera model for the Mex HRSC SRC Framing Camera.
class MocLabels
Read values from MOC labels.
class MocNarrowAngleCamera
MOC Narrow Angle Camera Model.
class MocNarrowAngleSumming
Mars Global Surveyor MOC narrow angle summing class.
class MocWideAngleCamera
MOC Wide Angle Camera Model.
class MocWideAngleDetectorMap
Convert between parent image coordinates and detector coordinates.
class MocWideAngleDistortionMap
Distort/undistort focal plane coordinates.
class CrismCamera
MRO CRISM camera model.
class CTXCamera
MRO CTX Camera Model.
class GainChannelNormalize
Computes a gain correction for each sample GainChannelNormalize.
class GainFlatField
GainFlatField Module - Computes flat field correction for sample.
class GainLineDrift
Computes a gain correction for each line (Zg Module)
class GainNonLinearity
GainNonLinearity Module - Applies non-linear, line-dependant gain.
class GainTemperature
GaingTemperature Module - Applies temperature-dependant gain correction (column)
class GainUnitConversion
Computes units parameters for HiRISE data calibration (Ziof Module)
class HiBlob
BLOB extraction class.
class HiCalData
Container for HiRISE calibration data.
class HiHistory
class HiLineTimeEqn
Compute HiRISE line times.
class LoadCSV
Provides generalized access to HiRISE calibration CSV files.
class LowPassFilter
Compute a low pass filter from a Module class content.
class Module
Module manages HiRISE calibration vectors from various sources.
class NonLinearLSQ
NonLinearLSQ Computes a fit using a Levenberg-Marquardt algorithm.
class SplineFill
Compute a low pass filter from a Module class content.
class ZeroBufferFit
Computes non-linear lsq fit of HiRISE Drift (Zd module)
class ZeroBufferSmooth
Processes Buffer calibration data (ZeroBufferSmooth Module)
class ZeroDark
Computes a complex dark subtraction component (ZeroDark module)
class ZeroDarkRate
Computes a complex dark subtraction component (ZeroDarkRate module)
class ZeroReverse
Processes Reverse Clock calibration data (ZeroReverse Module)
class HiEqualization
class HiLab
Process HiRise label.
class HiriseCamera
Hirise Camera Model.
class MarciCamera
Marci Camera Model.
class MarciDistortionMap
Distort/undistort focal plane coordinates.
class MsiCamera
NEAR Shoemaker MSI Camera Model.
class NewHorizonsLeisaCamera
This is the camera model for LEISA, New Hoirzon's infrared Spectrometer.
class NewHorizonsLorriCamera
This is the camera model for the LORRI Framing Camera.
class NewHorizonsLorriDistortionMap
New Horizons LORRI Distortion Map.
class NewHorizonsMvicFrameCamera
This is the camera model for the New Horizons MVIC Frame mode Camera.
class NewHorizonsMvicFrameCameraDistortionMap
Distort/undistort focal plane coordinates for New Horizons/MVIC frame sensor.
class NewHorizonsMvicTdiCamera
New Horizons Mvic Camera, Tdi mode.
class NewHorizonsMvicTdiCameraDistortionMap
Distort/undistort focal plane coordinates for New Horizons/MVIC.
class ThemisIrCamera
THEMIS IR Camera.
class ThemisIrDistortionMap
Distort/undistort focal plane coordinates.
class ThemisVisCamera
THEMIS VIS Camera Model.
class ThemisVisDistortionMap
Distort/undistort focal plane coordinates.
class OsirisRexDistortionMap
Distort/undistort focal plane coordinates for OSIRIS REx's cameras.
class OsirisRexOcamsCamera
This class models the behavior and attributes of the OSIRIS-REx Cameras: Mapping Camera, PolyMath Camera, and Sample Camera.
class OsirisRexOcamsDistortionMap
Distort/undistort focal plane coordinates for OSIRIS REx's cameras.
class OsirisRexTagcamsCamera
This class models the behavior and attributes of the OSIRIS-REx Navigation cameras: NavCam, NFTCam, and StowCam.
class OsirisRexTagcamsDistortionMap
OsirisRexTagcamsDistortionMap camera distortion model for TAGCAMS.
class AbstractPlotTool
Parent class for plotting tools which provides common functionality.
class AbstractProjectItemView
AbstractProjectItemView is a base class for views of a ProjectItemModel in Qt's model-view framework.
class ProjectItemViewMenu
QMenu subclass that overrides the closeEvent.
class AdvancedTrackTool
Tool to display info for a point on a cube.
class BandSpinBox
class BandTool
class BlinkTool
class BrowseDialog
Class for browsing cubes.
class BundleObservationView
View for displaying BundleObservation CSV files.
class ChipViewport
Viewport for Isis Chips.
class ChipViewportsWidget
Scrolled widget for display ChipViewports.
class CnetEditorView
Ipce view containing the CnetEditorWidget.
class AbstractFilter
Base class for control net filters.
class AbstractFilterSelector
Base class for filter selectors.
class AbstractImageItem
Base class for an image item in the tree.
class AbstractLeafItem
Base class for leaf items in the tree.
class AbstractMeasureItem
Base class for a measure item in the tree.
class AbstractMultipleChoiceFilter
Base class for combo box type filters.
class AbstractNullDataItem
Base class for an item without data.
class AbstractNumberFilter
Base class for filters that are number-based.
class AbstractParentItem
Base class for an item that is a parent in the tree.
class AbstractPointItem
Base class for a point item in the tree.
class AbstractStringFilter
Base class for filters that are string-based.
class AbstractTableDelegate
Base class for delegates which create, read, and save data in the tables.
class AbstractTableModel
Translates the tree model into a table model.
class AbstractTreeItem
Base class for an item in the tree.
class AbstractTreeModel
Base class for tree models.
class AdjustedLatitudeFilter
Allows filtering by adjusted surface point latitude.
class AdjustedLatitudeSigmaFilter
Allows filtering by adjusted surface point latitude sigma.
class AdjustedLongitudeFilter
Allows filtering by adjusted surface point longitude.
class AdjustedLongitudeSigmaFilter
Allows filtering by adjusted surface point longitude sigma.
class AdjustedRadiusFilter
Allows filtering by adjusted surface point radius.
class AdjustedRadiusSigmaFilter
Allows filtering by adjusted surface point radius sigma.
class AdjustedXFilter
Allows filtering by adjusted surface point X.
class AdjustedXSigmaFilter
Allows filtering by adjusted surface point X sigma.
class AdjustedYFilter
Allows filtering by adjusted surface point Y.
class AdjustedYSigmaFilter
Allows filtering by adjusted surface point Y sigma.
class AdjustedZFilter
Allows filtering by adjusted surface point Z.
class AdjustedZSigmaFilter
Allows filtering by adjusted surface point Z sigma.
class APrioriLatitudeFilter
Allows filtering by a priori surface point latitude.
class APrioriLatitudeSigmaFilter
Allows filtering by a priori surface point latitude sigma.
class APrioriLongitudeFilter
Allows filtering by a priori surface point longitude.
class APrioriLongitudeSigmaFilter
Allows filtering by a priori surface point longitude sigma.
class APrioriRadiusFilter
Allows filtering by a priori surface point radius.
class APrioriRadiusSigmaFilter
Allows filtering by a priori surface point radius sigma.
class APrioriXFilter
Allows filtering by a priori surface point X.
class APrioriXSigmaFilter
Allows filtering by a priori surface point X sigma.
class APrioriYFilter
Allows filtering by a priori surface point Y.
class APrioriYSigmaFilter
Allows filtering by a priori surface point Y sigma.
class APrioriZFilter
Allows filtering by a priori surface point Z.
class APrioriZSigmaFilter
Allows filtering by a priori surface point Z sigma.
class BusyLeafItem
A leaf item that is not ready for user interaction.
class ChooserNameFilter
Allows filtering by the chooser name.
class CnetDisplayProperties
Handles how control networks should be displayed to the user.
class CnetEditorSortConfigDialog
Configure user's sorting settings for the cneteditor widget.
class CnetEditorWidget
This widget provides full editing, filtering and viewing capabilities for the raw data in a control network.
class ConnectionParentItem
Tree item that is a parent and represents an image.
class FilterGroup
This class provides an interface for a group of filters.
class FilterWidget
This widget contains filtering capabilities for a single filter type.
class GoodnessOfFitFilter
Allows filtering by goodness of fit.
class ImageIdFilter
Allows filtering by image ID.
class ImageImageFilterSelector
Allows users to choose filters for filtering connected images.
class ImageImageTreeModel
Tree model for images and images.
class ImageLeafItem
Tree item that is a leaf and represents an image.
class ImageParentItem
Tree item that is a parent and represents an image.
class ImagePointFilterSelector
Allows users to choose filters for filtering images and points.
class ImagePointTreeModel
Tree model for images and control points.
class LineFilter
Allows filtering by a control measure's line.
class LineResidualFilter
Allows filtering by the line residual.
class LineShiftFilter
Allows filtering by a control measure's line shift.
class MeasureCountFilter
Allows filtering by the number of measures in a control point.
class MeasureIgnoredFilter
Allows filtering by a control measure's ignored status.
class MeasureJigsawRejectedFilter
Allows filtering by a control measure's jigsaw rejected status.
class MeasureLeafItem
A leaf node in the tree structure that represents a control measure.
class MeasureTableDelegate
Delegate for creating, reading, and saving data in the measure table.
class MeasureTableModel
Table model for control measures.
class MeasureTypeFilter
Filters by measure type.
class PointEditLockedFilter
Allows filtering by a control point's edit lock status.
class PointIdFilter
Filter by control point id string.
class PointIgnoredFilter
Allows filtering by a control point's ignored status.
class PointJigsawRejectedFilter
Allows filtering by a control point's jigsaw rejected status.
class PointLeafItem
A leaf node in the tree structure that represents a control point.
class PointMeasureFilterSelector
Allows users to choose filters for filtering points and measures.
class PointMeasureTreeModel
Tree model for control points and control measures.
class PointParentItem
Tree item that is a parent and represents a control point.
class PointTableDelegate
Delegate for creating, reading, and saving data in the point table.
class PointTableModel
Table model for control points.
class PointTypeFilter
Filters by point type.
class ResidualMagnitudeFilter
Filters by residual magnitude.
class RootItem
The root of a tree.
class SampleFilter
Allows filtering by a control measure's sample.
class SampleResidualFilter
Allows filtering by the sample residual.
class SampleShiftFilter
Allows filtering by a control measure's sample shift.
class TableColumn
class TableColumnList
class TableView
class TableViewContent
class TableViewHeader
class TreeView
class TreeViewContent
class TreeViewHeader
class ConcurrentControlNetReader
This reads a control net in the background.
class Control
This represents an ISIS control net in a project-based GUI interface.
class ControlDisplayProperties
This is the GUI communication mechanism for cubes.
class ControlHealthMonitorView
View for the Control Net Health Monitor.
class ControlHealthMonitorWidget
Interface that allows real-time evaluation of the state of a Control Network.
class ControlList
Maintains a list of Controls so that control nets can easily be copied from one Project to another, saved to disk, or deleted from disk.
class ControlMeasureEditWidget
Point Editor Widget.
class ControlNetTool
ControlNetTool Handles mouse events on CubeDnViews for control point editing for the ipce app.
class ControlPointEdit
Point Editor Widget.
class ControlPointEditView
View for editing a single ControlPoint.
class ControlPointEditWidget
Gui for editing ControlPoints in ipce application.
class NewGroundSourceLocationDialog
Dialog used by ControlPointEditWidget to select a new location for ground source files.
class CubeDnView
View that displays cubes in a QView-like way.
class CubePlotCurve
This is a plot curve with information relating it to a particular cube or region of a cube.
class CubePlotCurveConfigureDialog
This should be an inner class for CubePlotCurve, but Qt doesn't support having a QObject as an inner class.
class CubeViewport
Widget to display Isis cubes for qt apps.
class ViewportBuffer
Reads and stores visible DN values.
class ViewportBufferAction
class ViewportBufferFill
class ViewportBufferStretch
class ViewportBufferTransform
class BundleObservationViewWorkOrder
This is a child of the WorkOrder class which is used for anything that performs an action in a Project.
class CloseProjectWorkOrder
This opens a project that's saved on disk.
class CnetEditorViewWorkOrder
This work order allows the user to open a cnet editor (table) view of a single control network.
class ControlHealthMonitorWorkOrder
This is a child of class WorkOrder which is used for anything that performs an action in a Project.
class CubeDnViewWorkOrder
This work order is designed to bring up a qview-like view for a small number of cubes.
class Directory
class ExportControlNetWorkOrder
Write a project control network to a user-specified location.
class ExportImagesWorkOrder
Write project images to a user-specified location.
class Footprint2DViewWorkOrder
View an image list's footprints in a footprint view.
class ImageFileListViewWorkOrder
View an image list in an image file list widget.
class ImportControlNetWorkOrder
Add control networks to a project c Asks the user for a list of control nets and copies them into the project.
class ImportImagesWorkOrder
Add cubes to a project.
class ImportMapTemplateWorkOrder
Add map templates to a project.
class ImportRegistrationTemplateWorkOrder
Add registration templates to a project.
class ImportShapesWorkOrder
Add shape model cubes to a project.
class JigsawWorkOrder
This work order allows the user to run a bundle adjustment (jigsaw).
class MatrixViewWorkOrder
This work order will open a MatrixSceneWidget and display the correlation matrix.
class OpenProjectWorkOrder
This opens a project that's saved on disk.
class RemoveImagesWorkOrder
Removes selected images from current project.
class RenameProjectWorkOrder
Change the project's GUI name.
class SaveProjectAsWorkOrder
Saves a project to disk (File->Save Project As...)
class SaveProjectWorkOrder
Saves a project to disk (File->Save Project...)
class SensorGetInfoWorkOrder
This is a child of class WorkOrder which is used for anything that performs an action in a Project.
class SetActiveControlWorkOrder
This is a child of class WorkOrder which is used for anything that performs an action in a Project.
class SetActiveImageListWorkOrder
This is a child of class WorkOrder which is used for anything that performs an action in a Project.
class TargetGetInfoWorkOrder
This work order allows the user to view target body info.
class TemplateEditViewWorkOrder
This work order allows the user to view and edit a template.
class ViewControlNet3DWorkOrder
This work order displays a control network in 3D in an OpenGL view.
class DisplayProperties
class EditTool
Interactive image edit tool.
class FeatureNomenclature
Feature nomenclature database querier.
class FeatureNomenclatureTool
Display nomenclature on MDI Cube Viewports.
class NomenclatureToolConfigDialog
Configure user's settings for the nomenclature tool.
class FileDialog
Class for browsing cubes.
class FileItem
A container for a filename to be represented as a ProjectItem on the project tree.
class FileTool
class GroundTab
class ImageTab
class FindTool
Tool to locate a point on a cube that is projected and/or has a camera model.
class Footprint2DView
View for displaying footprints of images in a QMos like way.
class GraphicsView
class GuiCamera
Container class for GuiCamera.
class GuiCameraDisplayProperties
The GUI communication mechanism for target body objects.
class GuiCameraList
List of GuiCameras saved as QSharedPointers.
class HelpTool
Qisis Help Tool.
class HistogramItem
This is the (qwt) plot item for a histogram.
class HistogramPlotWindow
class HistogramTool
Tool for histograms.
class HistoryTreeWidget
History Widget for ipce.
class Image
This represents a cube in a project-based GUI interface.
class ImageDisplayProperties
This is the GUI communication mechanism for cubes.
class ImageFileListWidget
A colored, grouped cube list.
class ImageTreeWidget
class ImageTreeWidgetItem
class ImageList
Internalizes a list of images and allows for operations on the entire list.
class ImageListActionWorkOrder
Work orders that can be performed on an image list that modifies internal state.
class ImageReader
class IndependentCubeViewport
General purpose Cube display widget.
class JigsawRunWidget
This dialog allows the user to select the bundle adjust parameters, run the bundle, and view the results.
class JigsawSetupDialog
class LatLonGridTool
Lat Lon Grid View Tool.
class MainWindow
Base class for the Qisis main windows.
class MatchTool
Match tool operations.
class MatchToolNewPointDialog
class MatrixGraphicsScene
A graphics scene with improved user-interaction for use with the MatrixSceneWidget.
class MatrixGraphicsView
A graphics view that resizes in a more friendly way.
class MatrixOptions
This class holds the matrix color and focus information.
class MatrixOptionsDialog
This widget allows the user to modify the matrix display.
class MatrixSceneWidget
This widget encompasses the entire matrixDisplay scene.
class MdiCubeViewport
Cube display widget for certain Isis MDI applications.
class MeasureTool
Tool for measuring distances.
class MosaicController
class MosaicMainWindow
class ControlNetGraphicsItem
Control Network Display on Mosaic Scene.
class ControlPointGraphicsItem
The visual display of a single control point.
class FindSpotGraphicsItem
The visual display of the find point.
class GridGraphicsItem
The visual display of the find point.
class MosaicAreaTool
This displays a box with a given distance from a point.
class MosaicControlNetTool
//TODO: Remove debug printout & comment // 2016-08-25 Tracie Sucharski - Checking Directory pointer for IPCE code not ideal.
class MosaicControlNetToolMovementConfigDialog
Configure qmos Control Net Tool's movement arrows.
class MosaicFindTool
This controls the 'Find' abilities in the MosaicSceneWidget.
class MosaicGraphicsScene
A graphics scene with improved user-interaction for use with the MosaicSceneWidget.
class MosaicGraphicsView
A graphics view that resizes in a more friendly way.
class MosaicGridTool
This controls the 'Grid' abilities in the MosaicSceneWidget.
class MosaicGridToolConfigDialog
Configure user's settings for the grid tool.
class MosaicPanTool
Handles panning operations for Isis qt apps.
class MosaicSceneItem
A single cube in the mosaic scene.
class MosaicSceneWidget
This widget encompasses the entire mosaic scene.
class MosaicSceneWorkOrder
Work order associated with a MosaicSceneWidget.
class MosaicSelectTool
Handles selection operations for Isis qt apps.
class MosaicTool
Base class for the MosaicTools.
class MosaicTrackTool
class MosaicZoomTool
Handles zoom operations for Isis qt apps.
class MoveDownOneSceneWorkOrder
Move images, one by one, below the immediately-below intersecting image in a scene This workorder is synchronous and undoable.
class MoveToBottomSceneWorkOrder
Move images below all other images in a mosaic scene This workorder is synchronous and undoable.
class MoveToTopSceneWorkOrder
Move images on top of all other images in a mosaic scene This workorder is synchronous and undoable.
class MoveUpOneSceneWorkOrder
Move images, one by one, on top of the immediately-above intersecting image in a scene This workorder is synchronous and undoable.
class ProjectionConfigDialog
This is the configuration dialog for the MosaicSceneWidget's projection parameters (map file).
class NewControlPointDialog
class PaletteWindow
class PanTool
class PlotCurve
class PlotWindow
class PlotWindowBestFitDialog
class ProgressBar
class Project
The main project for ipce.
class ProjectItem
Represents an item of a ProjectItemModel in Qt's model-view framework.
class ProjectItemModel
Provides access to data stored in a Project through Qt's model-view framework.
class ProjectItemProxyModel
Allows access to items in a ProjectItemModel through a proxy model.
class ProjectItemTreeView
A ProjectItemTreeView displays items from a ProjectItemProxyModel in a tree structure.
class QHistogram
Plot Histograms.
class QIsisApplication
Handles exceptions which the QT event handlers and QApplication do not handle.
class QnetCubeDistanceFilter
Defines the Distance filter for the QnetNavTool's Cubes section.
class QnetCubeNameFilter
Defines the Name filter for the QnetNavTool's Cubes section.
class QnetCubePointsFilter
Defines the Points filter for the QnetNavTool's Cubes section.
class QnetFileTool
Qnet File operations.
class QnetFilter
class QnetFixedPointDialog
class QnetNavTool
Qnet Navigation Tool.
class QnetNewMeasureDialog
class QnetPointCubeNameFilter
Defines the Cube Name filter for the QnetNavTool's Points section.
class QnetPointDistanceFilter
Defines the Distance filter for the QnetNavTool's Points section.
class QnetPointGoodnessFilter
Defines the Goodness of Fit filter for the QnetNavTool's Points section.
class QnetPointIdFilter
Defines the Point ID filter for the QnetNavTool's Points section.
class QnetPointImagesFilter
Defines the Images filter for the QnetNavTool's Points section, i.e.
class QnetPointJigsawErrorFilter
Defines the Jigsaw Error filter for the QnetNavTool's Points section.
class QnetPointMeasureFilter
Defines the Measure Properties filter for the QnetNavTool's Points section.
class QnetPointRangeFilter
Defines the Range filter for the QnetNavTool's Points section.
class QnetPointRegistrationErrorFilter
Defines the Registration Error filter for the QnetNavTool's Points section.
class QnetPointTypeFilter
Filter for control point type.
class QnetSetAprioriDialog
class QnetTool
Qnet tool operations.
class RubberBandComboBox
Combo box for choosing a rubber band type.
class RubberBandTool
Rubber banding tool.
class SaveAsDialog
Widget to save(Save As) Isis cubes(used in qview) to display the FileDialog to select the output cube.
class ScatterPlotAlarmConfigDialog
This is the configuration dialog for alarming scatter plots between the plot window and cube viewports.
class ScatterPlotConfigDialog
This configuration dialog is for users to determine the scatter plot parameters required to create a scatter plot.
class ScatterPlotData
This is the QwtRasterData for a scatter plot.
class ScatterPlotTool
Scatter Plot Tool.
class ScatterPlotWindow
Scatter Plot Window.
class SensorInfoWidget
Widget for displaying information about a sensor.
class Shape
This represents a shape in a project-based GUI interface.
class ShapeDisplayProperties
This is the GUI communication mechanism for shape objects.
class ShapeList
Internalizes a list of shapes and allows for operations on the entire list.
class ShapeReader
class SocketThread
class SortFilterProxyModel
class SpatialPlotTool
Spatial Plots.
class SpecialPixelTool
Sets the colors for the special pixel values.
class SpectralPlotTool
Plot cube DN statistics against the cube band numbers.
class SpectralPlotWindow
class VisualDisplay
Tool to visualize statistics in an n * m box.
class StatisticsTool
class StereoTool
Tool for computing parallax.
class AdvancedStretch
Advanced Stretch Dialog.
class AdvancedStretchDialog
Advanced Stretch Dialog.
class BinaryStretchType
This handles the advanced binary stretch.
class HistogramWidget
Histogram widget used by AdvancedStretchTool.
class LinearStretchType
This handles the advanced linear stretch.
class ManualStretchType
This handles arbitrary user-input stretches.
class QStretch
Abstract class for complex stretch objects.
class SawtoothStretchType
This handles the advanced sawtooth stretch.
class StretchTool
Stretch image edit tool.
class StretchType
This is the base class for advanced stretches.
class SubTreeProxyModel
class SunShadowTool
Tool for measuring shadow heights.
class Tab
A Tab is a QAction which shows or hides some other QWidget, which we call associatedWidget.
class TabBar
A TabBar is a QToolBar which is specifically designed to store and manage Tabs, which are specialized QToolButtons that can hide and show other QWidgets (see Tab).
class TableMainWindow
a subclass of the qisis mainwindow, tablemainwindow handles all of the table tasks.
class TargetBody
Container class for TargetBody.
class TargetBodyDisplayProperties
This is the GUI communication mechanism for target body objects.
class TargetBodyList
List for holding TargetBodies.
class TargetInfoWidget
Widget for displaying information about a target.
class Template
class TemplateEditorWidget
Widget for displaying information about a target.
class TemplateList
class Tool
Base class for the Qisis tools.
class ToolList
Allows tools to share data between each other.
class ToolPad
class TrackTool
This tool is part of the Qisis namespace and displays the statusbar of the window.
class ViewportMainWindow
This was called the Qisis MainWindow.
class ViewSubWindow
This class exists to contain detached views from ipce.
class WarningTreeWidget
Warning Widget for ipce.
class WarningWidget
Displays the NoWarning icon as default and the Warning icon in case of exception and also pops up a a menu when an exception occurs.
class WindowTool
class WorkOrder
Provide Undo/redo abilities, serialization, and history for an operation.
class WorkOrderFactory
Instantiate work orders from QString versions of the class name.
class ViewportMdiSubWindow
This is an actual viewport window in qview/qnet/etc.
class Workspace
class ZoomTool
Handles zoom operations for Isis qt apps.
class RosettaOsirisCamera
This is the camera model for the Osiris NAC Framing Camera.
class RosettaOsirisCameraDistortionMap
Distortion map for converting between undistorted focal plane and distorted focal plane coordinates for the Rosetta OSIRIS NAC and WAC.
class RosettaVirtisCamera
Camera model for both Rosetta VIRTIS-M instruments.
class Kernel
This class stores Kernel information, including Type and kernel file names.
class KernelDb
KernelDb class.
class TgoCassisCamera
TGO Cassis camera model.
class TgoCassisDistortionMap
Distort/undistort focal plane coordinates.
class VikingCamera
Viking Camera Model.
class VoyagerCamera
Voyager Camera Model.
Typedefs
typedef long long int BigInt
Big int.
typedef QSharedPointer< GisGeometry > SharedGisGeometry
Definition for a SharedGisGeometry, a shared pointer to a GisGeometry.
typedef Affine::AMatrix GMatrix
typedef TNT::Array1D< double > GVector
typedef QSharedPointer< LidarData > LidarDataQsp
Definition for a shared pointer to a LidarData object.
typedef TNT::Array1D< SpiceDouble > NaifVector
Namespace to contain type definitions of NAIF DSK fundamentals.
typedef TNT::Array1D< SpiceDouble > NaifVertex
1-D Buffer[3]
typedef TNT::Array2D< SpiceDouble > NaifTriangle
3-D triangle[3][3]
typedef QSharedPointer< Resource > SharedResource
Defintion of a SharedResource, a shared pointer to a Resource object.
typedef QList< SharedResource > ResourceList
Defintion of a ResourceList, a list of SharedResource types.
typedef QPair< int, int > SmtkQPair
typedef QHash< SmtkQPair, SmtkPoint > SmtkQStack
typedef SmtkQStack::iterator SmtkQStackIter
typedef SmtkQStack::const_iterator SmtkQStackConstIter
typedef QSharedPointer< Strategy > SharedStrategy
Definition for a SharedStrategy, a shared pointer to a Strategy.
typedef QList< SharedStrategy > StrategyList
Definition for a StrategyList, a list of SharedStrategy types.
typedef QSharedPointer< Target > TargetQsp
typedef QSharedPointer< BundleSettings > BundleSettingsQsp
Definition for a BundleSettingsQsp, a shared pointer to a BundleSettings object.
typedef QSharedPointer< BundleControlPoint > BundleControlPointQsp
Definition for BundleControlPointQSP, a shared pointer to a BundleControlPoint.
typedef QSharedPointer< BundleImage > BundleImageQsp
typedef QSharedPointer< BundleLidarRangeConstraint > BundleLidarRangeConstraintQsp
Typdef for BundleLidarRangeConstraint QSharedPointer.
typedef QSharedPointer< BundleLidarControlPoint > BundleLidarControlPointQsp
QSharedPointer to a BundleLidarControlPoint.
typedef QSharedPointer< BundleMeasure > BundleMeasureQsp
Definition for BundleMeasureQsp, a shared pointer to a BundleMeasure.
typedef QSharedPointer< BundleObservation > BundleObservationQsp
Typdef for BundleObservation QSharedPointer.
typedef QSharedPointer< BundleObservationSolveSettings > BundleObservationSolveSettingsQsp
Definition for BundleObservationSolveSettingsQsp, a QSharedPointer to a BundleObservationSolveSettings object.
typedef QSharedPointer< BundleTargetBody > BundleTargetBodyQsp
Definition for BundleTargetBodyQsp, a QSharedPointer to a BundleTargetBody.
typedef QSharedPointer< IsisBundleObservation > IsisBundleObservationQsp
Typdef for IsisBundleObservation QSharedPointer.
typedef QSharedPointer< ControlNet > ControlNetQsp
Typedef for QSharedPointer to control network. This typedef is for future implementation of target body.
typedef QSharedPointer< LidarControlPoint > LidarControlPointQsp
Definition for a shared pointer to a LidarControlPoint.
typedef TNT::Array1D< double > HiVector
1-D Buffer
typedef TNT::Array2D< double > HiMatrix
2-D buffer
typedef QSharedPointer< FileItem > FileItemQsp
A FileItem smart pointer.
typedef QSharedPointer< GuiCamera > GuiCameraQsp
GuiCameraQsp Represents a smart pointer to a GuiCamera object.
typedef QSharedPointer< TargetBody > TargetBodyQsp
Defines A smart pointer to a TargetBody obj.
Enumerations
enum LabelAttachment { AttachedLabel , DetachedLabel , ExternalLabel }
Input cube label type tracker.
enum ByteOrder { NoByteOrder = 0 , Lsb , Msb }
Tests the current architecture for byte order.
enum { NCONSTR = 8 }
enum PixelType {
None = 0 , UnsignedByte , SignedByte , UnsignedWord ,
SignedWord , UnsignedInteger , SignedInteger , Real ,
Double
}
Enumerations for Isis Pixel Types.
enum KeywordType {
NoTypeKeyword , StringKeyword , BoolKeyword , IntegerKeyword ,
RealKeyword , OctalKeyword , HexKeyword , BinaryKeyword ,
EnumKeyword
}
The different types of keywords that can be formatted.
Functions
Angle operator* (double mult, Angle angle)
Multiply this angle by a double and return the resulting angle.
bool IsBlob (PvlObject &obj)
Checks pvl object and returns whether or not it is a Blob.
int bt_MaxBodyParts ()
Maximum number of parts/object.
unsigned long bt_MaxTriangles ()
Maximum number of triangles/part.
int b3_MaxBodyParts ()
Maximum number of parts/object in the Bullet 3 API.
unsigned long b3_MaxTriangles ()
Maximum number of triangles/part in the Bullet 3 API.
double NegateOperator (double a)
Returns the nagative of the input parameter.
double MultiplyOperator (double a, double b)
Returns the result of a multiplied by b.
double DivideOperator (double a, double b)
Returns the result of dividing a by b.
double AddOperator (double a, double b)
Returns the result of additing a with b.
double SubtractOperator (double a, double b)
Returns the result of subtracting b from a.
double GreaterThanOperator (double a, double b)
Returns 1.0 if a is greater than b.
double LessThanOperator (double a, double b)
Returns 1.0 if a is less than b.
double EqualOperator (double a, double b)
Returns 1.0 if a is equal ot b.
double GreaterThanOrEqualOperator (double a, double b)
Returns 1.0 if a is greater than or equal to b.
double LessThanOrEqualOperator (double a, double b)
Returns 1.0 if a is less than or eqaul to b.
double NotEqualOperator (double a, double b)
Returns 1.0 is a is not equal to b.
double CosecantOperator (double a)
Returns the cosecant of the input a.
double SecantOperator (double a)
Returns the secant of the input a.
double CotangentOperator (double a)
Returns the cotangent of the input a.
int Round (double a)
Returns the result of rounding the input a to the closest integer.
double BitwiseAndOperator (double a, double b)
Returns the result of a bitwise AND accross a and b.
double BitwiseOrOperator (double a, double b)
Returns the result of a bitwise OR across a and b.
double ModulusOperator (double a, double b)
Returns the modulus of a by b.
double MaximumOperator (double a, double b)
Returns the max of a and b.
double MinimumOperator (double a, double b)
Returns the min of a and b.
json stateAsJson (std::string modelState)
void sanitize (std::string &input)
std::istream & operator>> (std::istream &is, CSVReader &csv)
Input read operator for input stream sources.
QString LabelAttachmentName (LabelAttachment labelType)
Return the string representation of the contents of a variable of type LabelAttachment.
LabelAttachment LabelAttachmentEnumeration (const QString &labelType)
Return the appropriate LabelType depending on which of the valid values the argument spells.
Displacement operator* (double mult, Displacement displacement)
Multiply displacement by a value (5m * 2 = 10m).
Distance operator* (double mult, Distance dist)
Multiply this distance by a value (5m * 2 = 10m).
QString ByteOrderName (Isis::ByteOrder byteOrder)
Isis::ByteOrder ByteOrderEnumeration (const QString &order)
bool IsLsb ()
Return true if this host is an LSB first machine and false if it is not.
bool IsMsb ()
Return true if this host is an MSB first machine and false if it is not.
bool IsLittleEndian ()
bool IsBigEndian ()
json fitsToJson (std::ifstream &fileStream)
Convert the contents of a stream to a JSON object.
json fitsToJson (FileName fitsFile)
Converts a FITS file to a json object.
Coordinate operator+ (const Coordinate &A, const Coordinate &B)
Summation operator for Coordinate.
Coordinate operator- (const Coordinate &A, const Coordinate &B)
Subtraction operator for Coordinate.
Radiometric operator+ (const Radiometric &A, const Radiometric &B)
Operator to sum two radiometric parameters.
QDebug operator<< (QDebug debug, const Hillshade &hillshade)
Print this class out to a QDebug object.
double floatModulusOperator (double a, double b)
Determines the remainder of the quotient a/b whose sign is the same as that of a.
bool toBool (const QString &string)
Global function to convert from a string to a boolean.
int toInt (const QString &string)
Global function to convert from a string to an integer.
BigInt toBigInt (const QString &string)
Global function to convert from a string to a "big" integer.
double toDouble (const QString &string)
Global function to convert from a string to a double.
QString toString (bool boolToConvert)
Global function to convert a boolean to a string.
QString toString (char charToConvert)
Global function to convert a character to a string.
QString toString (const int &intToConvert)
Global function to convert an integer to a string.
QString toString (const unsigned int &intToConvert)
Global function to convert an unsigned integer to a string.
QString toString (const BigInt &intToConvert)
Global function to convert a big integer to a string.
QString toString (double doubleToConvert, int precision)
Global function to convert a double to a string with the given precision (significant figures).
static bool nocase_compare (const char c1, const char c2)
Compare two characters without regard to case.
std::ostream & operator<< (std::ostream &outputStream, const QString &string)
Print an ASCII representation of the given QString to a stl stream (most commonly cout, cerr).
std::ostream & operator<< (std::ostream &outputStream, const QStringRef &string)
Print an ASCII representation of the given QStringRef to a stl stream (most commonly cout, cerr).
iTime operator+ (const double &secondsToAdd, iTime time)
iTime operator- (const double &secondsToSubtract, iTime time)
QDebug operator<< (QDebug dbg, const LinearAlgebra::Vector &vector)
A global function to format a LinearAlgebra::Vector as a QString and writes it to a QDebug stream.
QDebug operator<< (QDebug dbg, const LinearAlgebra::Matrix &matrix)
A global function to format a LinearAlgebra::Matrix as a QString and write it to a QDebug stream.
QString toString (const LinearAlgebra::Vector &vector, int precision)
A global function to format LinearAlgebra::Vector as a QString with the given precision.
ostream & operator<< (ostream &os, Matrix &matrix)
Write the matrix to the output stream.
std::ostream & operator<< (std::ostream &os, Matrix &matrix)
bool validate (const NaifVertex &v)
Verifies that the given NaifVector or NaifVertex is 3 dimensional.
bool validate (const NaifTriangle &t)
Verifies that the given NaifTriangle is 3 x 3.
QDebug operator<< (QDebug dbg, const TNT::Array1D< SpiceDouble > &tntArray)
Enables any TNT array of SpiceDoubles to be passed into qDebug() directly.
QDebug operator<< (QDebug dbg, const TNT::Array2D< SpiceDouble > &tntMatrix)
Enables any 2 dimensional TNT array of SpiceDoubles to be passed into qDebug() directly.
QString toString (const TNT::Array1D< SpiceDouble > &naifArray, int precision)
Formats any TNT array of SpiceDoubles as a string with given precision.
std::ostream & operator<< (std::ostream &os, Isis::OverlapStatistics &stats)
Creates a pvl of various useful data obtained by the overlap statistics class.
ostream & operator<< (ostream &os, Pipeline &pipeline)
This is the output operator for a Pipeline, which enables things such as:
int SizeOf (Isis::PixelType pixelType)
Returns the number of bytes of the specified PixelType.
QString PixelTypeName (Isis::PixelType pixelType)
Returns string name of PixelType enumeration entered as input parameter.
Isis::PixelType PixelTypeEnumeration (const QString &type)
Returns PixelType enumeration given a string.
ostream & operator<< (std::ostream &os, Pvl &pvl)
This stream will not handle the end of line sequence.
istream & operator>> (std::istream &is, Pvl &pvl)
Reads keywords from the instream and appends them to the Pvl object.
ostream & operator<< (std::ostream &os, PvlContainer &container)
Output the PvlContainer information.
KeywordType toKeywordType (const QString type)
Convert a string representing a type of keyword to the corresponding enumeration.
std::istream & operator>> (std::istream &is, PvlGroup &result)
Read in a group.
ostream & operator<< (std::ostream &os, PvlGroup &group)
Outputs the PvlGroup data to a specified output stream.
std::istream & operator>> (std::istream &is, PvlKeyword &result)
Read in a keyword.
ostream & operator<< (std::ostream &os, const Isis::PvlKeyword &keyword)
Write out the keyword.
ostream & operator<< (std::ostream &os, PvlObject &object)
Outputs the PvlObject data to a specified output stream.
std::istream & operator>> (std::istream &is, PvlObject &result)
This method reads a PvlObject from the input stream.
json pvlKeywordToJSON (PvlKeyword &keyword)
Convert the contents of a PvlKeyword to a JSON object.
json pvlContainerToJSON (PvlContainer &container)
Convert the contents of a PvlContainer to a JSON object.
json pvlGroupToJSON (PvlGroup &group)
Convert the contents of a PvlGroup to a JSON object.
json pvlObjectToJSON (PvlObject &object)
Convert the contents of a PvlObject to a JSON object.
json pvlToJSON (Pvl &pvl)
Convert the contents of a Pvl to a JSON object.
json pvlToJSON (QString pvlFile)
Converts an PVL file to a json object.
int choleski_solve (double *a, double *b, int nsize, int flag)
int inverse (double *a, int nsize)
int isymp (int row, int col)
int indeces_from_set (int *indeces, int set, int set_size, int n)
int binomial_coeficient (int n, int k)
int decompose (double *, int)
int foresub (double *, double *, int)
int backsub (double *, double *, int)
std::ostream & operator<< (std::ostream &os, Isis::SessionLog &log)
QDataStream & operator<< (QDataStream &stream, const SparseBlockColumnMatrix &sbcm)
Writes matrix to binary disk file pointed to by QDataStream stream.
QDataStream & operator>> (QDataStream &stream, SparseBlockColumnMatrix &sbcm)
Reads matrix from binary disk file pointed to by QDataStream stream.
QDebug operator<< (QDebug dbg, const SparseBlockColumnMatrix &sbcm)
Writes matrix to QDebug stream.
QDataStream & operator<< (QDataStream &stream, const SparseBlockRowMatrix &sbrm)
Writes matrix to binary disk file pointed to by QDataStream stream.
QDataStream & operator>> (QDataStream &stream, SparseBlockRowMatrix &sbrm)
Reads matrix from binary disk file pointed to by QDataStream stream.
QDebug operator<< (QDebug dbg, const SparseBlockRowMatrix &sbrm)
Writes matrix to QDebug stream.
QDataStream & operator<< (QDataStream &stream, const SparseBlockMatrix &sparseBlockMatrix)
Writes matrix to binary disk file pointed to by QDataStream stream.
QDataStream & operator>> (QDataStream &stream, SparseBlockMatrix &sparseBlockMatrix)
Reads matrix from binary disk file pointed to by QDataStream stream.
QDebug operator<< (QDebug dbg, const SparseBlockMatrix &m)
Writes matrix to QDebug stream.
bool IsSpecial (const double d)
Returns if the input pixel is special.
bool IsSpecial (const float f)
Returns if the input pixel is special.
bool IsValidPixel (const double d)
Returns if the input pixel is valid.
bool IsNullPixel (const double d)
Returns if the input pixel is null.
bool IsHighPixel (const double d)
Returns if the input pixel is one of the high saturation types.
bool IsLowPixel (const double d)
Returns if the input pixel is one of the low saturation types.
bool IsHrsPixel (const double d)
Returns if the input pixel is high representation saturation.
bool IsHisPixel (const double d)
Returns if the input pixel is high instrument saturation.
bool IsLisPixel (const double d)
Returns if the input pixel is low instrument saturation.
bool IsLrsPixel (const double d)
Returns if the input pixel is low representation saturation.
double TestPixel (const float t)
Converts float pixels to double pixels with special pixel translations.
float TestPixel (const double t)
Converts double to float with special pixel translations and care for overflows (underflows are assumed to cast to 0!)
QString PixelToString (double d, double precision=8)
Takes a double pixel value and returns the name of the pixel type as a string.
double StringToPixel (const QString &str)
Takes the name of the pixel type as a string and returns a double pixel value.
QDataStream & operator<< (QDataStream &stream, const StatCumProbDistDynCalc &scpddc)
QDataStream & operator>> (QDataStream &stream, StatCumProbDistDynCalc &scpddc)
QDataStream & operator<< (QDataStream &stream, const Statistics &statistics)
QDataStream & operator>> (QDataStream &stream, Statistics &statistics)
json convertLastChildNodeToJson (QDomElement &element)
Not intended to be used directly.
json convertXmlToJson (QDomElement &element, json &output)
Not intended to be used directly.
json xmlToJson (QString xmlFile)
Converts an XML file to a json object.
json xmlToJson (QDomDocument &doc)
Converts an XML document stored in a QDomDocument into a JSON object.
static void cholmodErrorHandler (int nStatus, const char *file, int nLineNo, const char *message)
Custom error handler for CHOLMOD.
void setStringAttribute (int locationId, QString locationName, QString attributeName, QString attributeValue)
QString getStringAttribute (int locationId, QString locationName, QString attributeName)
QDataStream & operator<< (QDataStream &stream, const MaximumLikelihoodWFunctions &mlwf)
QDataStream & operator>> (QDataStream &stream, MaximumLikelihoodWFunctions &mlwf)
QDataStream & operator<< (QDataStream &stream, const MaximumLikelihoodWFunctions::Model &modelEnum)
QDataStream & operator>> (QDataStream &stream, MaximumLikelihoodWFunctions::Model &modelEnum)
int ValidCount (const HiVector &v)
Counts number of valid pixels in vector.
int InValidCount (const HiVector &v)
Counts number of invalid pixels in vector.
int CpmmToCcd (int cpmm)
Convert HiRISE Cpmm number to Ccd number.
QString CcdToFilter (int ccd)
Convert HiRISE Ccd number to string filter name.
HiMatrix cropLines (const HiMatrix &m, int sline, int eline)
Crop specified lines from a buffer.
HiMatrix cropSamples (const HiMatrix &m, int ssamp, int esamp)
Crop specified samples from a buffer.
HiVector averageLines (const HiMatrix &m, int sline=0, int eline=-1)
Reduces by averaging specified lines from a buffer.
HiVector averageSamples (const HiMatrix &m, int ssamp=0, int esamp=-1)
Reduces by averaging specified samples from a buffer.
template<typename T >
T ConfKey (const DbProfile &conf, const QString &keyname, const T &defval, int index=0)
Find a keyword in a profile using default for non-existant keywords.
template<typename T >
int ToInteger (const T &value)
Helper function to convert values to Integers.
template<typename T >
double ToDouble (const T &value)
Helper function to convert values to doubles.
template<typename T >
QString ToString (const T &value)
Helper function to convert values to strings.
bool IsEqual (const QString &v1, const QString &v2="TRUE")
Shortened string equality test.
bool IsTrueValue (const DbProfile &prof, const QString &key, const QString &value="TRUE")
Determines if the keyword value is the expected value.
bool SkipModule (const DbProfile &prof)
Checks profile flag to skip the current Module.
HiMatrix appendLines (const HiMatrix &top, const HiMatrix &bottom)
HiMatrix appendSamples (const HiMatrix &left, const HiMatrix &right)
double HiTempEqn (const double temperature, const double napcm2=2.0, const double px=12.0)
Implements (classic) HiRISE temperature equation.
HiVector rebin (const HiVector &v, int n)
Rebins a vector to a different size.
void RemoveHiBlobs (Pvl &label)
Deletes HiRISE specific BLOBS from cube file.
double GainLineStat (std::vector< double > &data)
Return the statistics for a vector of data.
QDataStream & operator<< (QDataStream &stream, const TargetBody &TargetBody)
QDataStream & operator>> (QDataStream &stream, TargetBody &TargetBody)
Kernel::Type operator| (Kernel::Type a, Kernel::Type b)
Logical operator for combining Type flags.
Variables
Application * iApp = NULL
const double E = 2.7182818284590452354
Sets some basic constants for use in ISIS programming.
const double PI = 3.14159265358979323846
The mathematical constant PI.
const double HALFPI = 1.57079632679489661923
The mathematical constant PI/2.
const double TWOPI = 6.2831853071795864769253
Two * PI, a complete revolution.
const double DEG2RAD = 0.017453292519943295769237
Multiplier for converting from degrees to radians.
const double RAD2DEG = 57.29577951308232087679815481
Multiplier for converting from radians to degrees.
static geos::geom::GeometryFactory::Ptr globalFactory = geos::geom::GeometryFactory::create()
const int SizeMatch = 1
const int SpatialMatch = 2
const int OneBand = 16
const int BandMatchOrOne = 32
const int ReadWrite = 64
const int AllMatchOrOne = 128
const DBL_UNION IVALID_MIN8 = { DBL_INIT(0xFFEFFFFF, 0xFFFFFFFA) }
Manipulate special pixel values.
const double VALID_MIN8 = IVALID_MIN8.d
const double ValidMinimum = IVALID_MIN8.d
The minimum valid double value for Isis pixels.
const DBL_UNION INULL8 = { DBL_INIT(0xFFEFFFFF, 0xFFFFFFFB) }
const double NULL8 = INULL8.d
const double Null = INULL8.d
Value for an Isis Null pixel.
const DBL_UNION ILOW_REPR_SAT8 = { DBL_INIT(0xFFEFFFFF, 0xFFFFFFFC) }
const double LOW_REPR_SAT8 = ILOW_REPR_SAT8.d
const double Lrs = ILOW_REPR_SAT8.d
Value for an Isis Low Representation Saturation pixel.
const DBL_UNION ILOW_INSTR_SAT8 = { DBL_INIT(0xFFEFFFFF, 0xFFFFFFFD) }
const double LOW_INSTR_SAT8 = ILOW_INSTR_SAT8.d
const double Lis = ILOW_INSTR_SAT8.d
Value for an Isis Low Instrument Saturation pixel.
const DBL_UNION IHIGH_INSTR_SAT8 = { DBL_INIT(0xFFEFFFFF, 0xFFFFFFFE) }
const double HIGH_INSTR_SAT8 = IHIGH_INSTR_SAT8.d
const double His = IHIGH_INSTR_SAT8.d
Value for an Isis High Instrument Saturation pixel.
const DBL_UNION IHIGH_REPR_SAT8 = { DBL_INIT(0xFFEFFFFF, 0xFFFFFFFF) }
const double HIGH_REPR_SAT8 = IHIGH_REPR_SAT8.d
const double Hrs = IHIGH_REPR_SAT8.d
Value for an Isis High Representation Saturation pixel.
const double VALID_MAX8 = DBL_MAX
const double ValidMaximum = DBL_MAX
The maximum valid double value for Isis pixels.
const int IVALID_MIN4 = 0xFF7FFFFA
const float VALID_MIN4 = (*((const float *) &IVALID_MIN4))
const int INULL4 = 0xFF7FFFFB
const float NULL4 = (*((const float *) &INULL4))
const int ILOW_REPR_SAT4 = 0xFF7FFFFC
const float LOW_REPR_SAT4 = (*((const float *) &ILOW_REPR_SAT4))
const int ILOW_INSTR_SAT4 = 0xFF7FFFFD
const float LOW_INSTR_SAT4 = (*((const float *) &ILOW_INSTR_SAT4))
const int IHIGH_INSTR_SAT4 = 0xFF7FFFFE
const float HIGH_INSTR_SAT4 = (*((const float *) &IHIGH_INSTR_SAT4))
const int IHIGH_REPR_SAT4 = 0xFF7FFFFF
const float HIGH_REPR_SAT4 = (*((const float *) &IHIGH_REPR_SAT4))
const float VALID_MAX4 = FLT_MAX
const int IVALID_MAX4 = (*((const int *) &VALID_MAX4))
const short VALID_MIN2 = ((short)(-32752))
const short NULL2 = ((short)(-32768))
const short LOW_REPR_SAT2 = ((short)(-32767))
const short LOW_INSTR_SAT2 = ((short)(-32766))
const short HIGH_INSTR_SAT2 = ((short)(-32765))
const short HIGH_REPR_SAT2 = ((short)(-32764))
const short VALID_MAX2 = ((short) 32767)
const unsigned short VALID_MINU2 = ((unsigned short) 3)
const unsigned short NULLU2 = ((unsigned short) 0)
const unsigned short LOW_REPR_SATU2 = ((unsigned short) 1)
const unsigned short LOW_INSTR_SATU2 = ((unsigned short) 2)
const unsigned short HIGH_INSTR_SATU2 = ((unsigned short) 65534)
const unsigned short HIGH_REPR_SATU2 = ((unsigned short) 65535)
const unsigned short VALID_MAXU2 = ((unsigned short) 65522)
const unsigned int VALID_MINUI4 = ((unsigned int) 3)
const unsigned int NULLUI4 = ((unsigned int) 0)
const unsigned int LOW_REPR_SATUI4 = ((unsigned int) 1)
const unsigned int LOW_INSTR_SATUI4 = ((unsigned int) 2)
const unsigned int HIGH_INSTR_SATUI4 = ((unsigned int) 4294967294)
const unsigned int HIGH_REPR_SATUI4 = ((unsigned int) 4294967295)
const unsigned int VALID_MAXUI4 = ((unsigned int) 4294967282)
const unsigned char VALID_MIN1 = ((unsigned char) 1)
const unsigned char NULL1 = ((unsigned char) 0)
const unsigned char LOW_REPR_SAT1 = ((unsigned char) 0)
const unsigned char LOW_INSTR_SAT1 = ((unsigned char) 0)
const unsigned char HIGH_INSTR_SAT1 = ((unsigned char) 255)
const unsigned char HIGH_REPR_SAT1 = ((unsigned char) 255)
const unsigned char VALID_MAX1 = ((unsigned char) 254)
const QString trackingTableName = "InputImages"
QString sPointType [] = { "Fixed", "Constrained", "Free" }
String names for Point Type.
QString sBoolean [] = { "False", "True" }
String values for Boolean.
const int VIEWSIZE = 301
Constant representing the length and width of the chip viewports.
Detailed Description
This is free and unencumbered software released into the public domain.
Namespace for all Isis base objects.
Namespace for ISIS/Bullet specific routines
The authors of ISIS do not claim copyright on the contents of this file. For more details about the LICENSE terms and the AUTHORS, you will find files of those names at the top level of this repository.
The authors of ISIS do not claim copyright on the contents of this file. For more details about the LICENSE terms and the AUTHORS, you will find files of those names at the top level of this repository. Unless noted otherwise, the portions of Isis written by the USGS are public domain. See individual third-party library and package descriptions for intellectual property information, user agreements, and related information.
Although Isis has been used by the USGS, no warranty, expressed or implied, is made by the USGS as to the accuracy and functioning of such software and related material nor shall the fact of distribution constitute any such warranty, and no responsibility is assumed by the USGS in connection therewith.
For additional information, launch $ISISROOT/doc//documents/Disclaimers/Disclaimers.html in a browser or see the Privacy & Disclaimers page on the Isis website, http://isis.astrogeology.usgs.gov, and the USGS privacy and disclaimers on http://www.usgs.gov/privacy.html.
The authors of ISIS do not claim copyright on the contents of this file. For more details about the LICENSE terms and the AUTHORS, you will find files of those names at the top level of this repository.
Generic class for Rolling Shutter Cameras
This class is used to abstract out framing camera functionality from children classes.
Author
Makayla Shepherd 2018-04-02
The authors of ISIS do not claim copyright on the contents of this file. For more details about the LICENSE terms and the AUTHORS, you will find files of those names at the top level of this repository. This is free and unencumbered software released into the public domain.
The authors of ISIS do not claim copyright on the contents of this file. For more details about the LICENSE terms and the AUTHORS, you will find files of those names at the top level of this repository.
Typedef Documentation
BigInt
typedef long long int Isis::BigInt
Big int.
BundleControlPointQsp
typedef QSharedPointer<BundleControlPoint> Isis::BundleControlPointQsp
Definition for BundleControlPointQSP, a shared pointer to a BundleControlPoint.
BundleImageQsp
typedef QSharedPointer<BundleImage> Isis::BundleImageQsp
BundleLidarControlPointQsp
typedef QSharedPointer<BundleLidarControlPoint> Isis::BundleLidarControlPointQsp
QSharedPointer to a BundleLidarControlPoint.
BundleLidarRangeConstraintQsp
typedef QSharedPointer< BundleLidarRangeConstraint > Isis::BundleLidarRangeConstraintQsp
Typdef for BundleLidarRangeConstraint QSharedPointer.
BundleMeasureQsp
typedef QSharedPointer<BundleMeasure> Isis::BundleMeasureQsp
Definition for BundleMeasureQsp, a shared pointer to a BundleMeasure.
BundleObservationQsp
typedef QSharedPointer<BundleObservation> Isis::BundleObservationQsp
Typdef for BundleObservation QSharedPointer.
BundleObservationSolveSettingsQsp
typedef QSharedPointer<BundleObservationSolveSettings> Isis::BundleObservationSolveSettingsQsp
Definition for BundleObservationSolveSettingsQsp, a QSharedPointer to a BundleObservationSolveSettings object.
BundleSettingsQsp
typedef QSharedPointer< BundleSettings > Isis::BundleSettingsQsp
Definition for a BundleSettingsQsp, a shared pointer to a BundleSettings object.
BundleTargetBodyQsp
typedef QSharedPointer<BundleTargetBody> Isis::BundleTargetBodyQsp
Definition for BundleTargetBodyQsp, a QSharedPointer to a BundleTargetBody.
ControlNetQsp
typedef QSharedPointer<ControlNet> Isis::ControlNetQsp
Typedef for QSharedPointer to control network. This typedef is for future implementation of target body.
FileItemQsp
typedef QSharedPointer<FileItem> Isis::FileItemQsp
A FileItem smart pointer.
GMatrix
typedef Affine::AMatrix Isis::GMatrix
GuiCameraQsp
typedef QSharedPointer<GuiCamera> Isis::GuiCameraQsp
GuiCameraQsp Represents a smart pointer to a GuiCamera object.
It behaves exactly like a normal pointer, but it is thread-safe and it will delete the pointer it is holding when it goes out of scope, provided no other QSharedPointer objects are referencing it.
GVector
typedef TNT::Array1D<double> Isis::GVector
HiMatrix
typedef TNT::Array2D<double> Isis::HiMatrix
2-D buffer
HiVector
typedef TNT::Array1D<double> Isis::HiVector
1-D Buffer
IsisBundleObservationQsp
typedef QSharedPointer<IsisBundleObservation> Isis::IsisBundleObservationQsp
Typdef for IsisBundleObservation QSharedPointer.
LidarControlPointQsp
typedef QSharedPointer<LidarControlPoint> Isis::LidarControlPointQsp
Definition for a shared pointer to a LidarControlPoint.
LidarDataQsp
typedef QSharedPointer<LidarData> Isis::LidarDataQsp
Definition for a shared pointer to a LidarData object.
NaifTriangle
typedef TNT::Array2D<SpiceDouble> Isis::NaifTriangle
3-D triangle[3][3]
NaifVector
typedef TNT::Array1D<SpiceDouble> Isis::NaifVector
Namespace to contain type definitions of NAIF DSK fundamentals.
This NAIF DSK utility provides the means to a TIN. Needed are types that define efficient implemenations of vectors, vertices and triangles (plates). The TNT library is used to specify these fundamental types due to its efficeint passing and memory manaegement mechanisms.
Author
2013-12-05 Kris Becker 1-D Buffer[3]
NaifVertex
typedef TNT::Array1D<SpiceDouble> Isis::NaifVertex
1-D Buffer[3]
ResourceList
typedef QList<SharedResource> Isis::ResourceList
Defintion of a ResourceList, a list of SharedResource types.
SharedGisGeometry
typedef QSharedPointer<GisGeometry> Isis::SharedGisGeometry
Definition for a SharedGisGeometry, a shared pointer to a GisGeometry.
SharedResource
typedef QSharedPointer<Resource> Isis::SharedResource
Defintion of a SharedResource, a shared pointer to a Resource object.
SharedStrategy
typedef QSharedPointer<Strategy> Isis::SharedStrategy
Definition for a SharedStrategy, a shared pointer to a Strategy.
SmtkQPair
typedef QPair<int, int> Isis::SmtkQPair
SmtkQStack
typedef QHash<SmtkQPair, SmtkPoint> Isis::SmtkQStack
SmtkQStackConstIter
typedef SmtkQStack::const_iterator Isis::SmtkQStackConstIter
SmtkQStackIter
typedef SmtkQStack::iterator Isis::SmtkQStackIter
StrategyList
typedef QList<SharedStrategy> Isis::StrategyList
Definition for a StrategyList, a list of SharedStrategy types.
TargetBodyQsp
typedef QSharedPointer<TargetBody> Isis::TargetBodyQsp
Defines A smart pointer to a TargetBody obj.
TargetQsp
typedef QSharedPointer<Target> Isis::TargetQsp
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NCONSTR
KeywordType
enum Isis::KeywordType
The different types of keywords that can be formatted.
Enumerator
NoTypeKeyword
StringKeyword
BoolKeyword
IntegerKeyword
RealKeyword
OctalKeyword
HexKeyword
BinaryKeyword
EnumKeyword
LabelAttachment
enum Isis::LabelAttachment
Input cube label type tracker.
This enumeration and its functions are for the label type of an input cube. The enum defines the type of labels (i.e., Both the label and cube are in the same file and the label is in a separate file from the cube.
Enumerator
AttachedLabel
The input label is embedded in the image file.
DetachedLabel
The input label is in a separate data file from the image.
ExternalLabel
The label is pointing to an external DN file - the label is also external to the data.
This format implies that the output is a cube that contains everything except DN data (more similar to attached than detached).
PixelType
enum Isis::PixelType
Enumerations for Isis Pixel Types.
This enumeration is for defining pixel types of cubes. UnsignedByte, SignedWord, and Real are the only three pixel types currently supported. The range for UnsignedBytes is 0 to 255, the range for SignedWord is -32768 to 32767, and the range for Real is -FLT_MAX to FLT_MAX as defined in the include file, float.h.
Author
2004-10-14 Stuart Sides
Enumerator
None
UnsignedByte
SignedByte
UnsignedWord
SignedWord
UnsignedInteger
SignedInteger
Real
Double
Function Documentation
AddOperator()
double Isis::AddOperator (double a, double b)
Returns the result of additing a with b.
Parameters
a Input double
b Input double
Returns
double result of a+b
Referenced by Isis::Calculator::Add().
appendLines()
HiMatrix Isis::appendLines (const HiMatrix & top, const HiMatrix & bottom) inline
References _FILEINFO_, and Isis::IException::User.
Referenced by Isis::HiCalData::getBufferExtended(), and Isis::HiCalData::getDarkExtended().
appendSamples()
HiMatrix Isis::appendSamples (const HiMatrix & left, const HiMatrix & right) inline
References _FILEINFO_, and Isis::IException::User.
Referenced by Isis::HiCalData::getMaskExtended(), Isis::HiCalData::getRampExtended(), and Isis::HiCalData::getReverseClockExtended().
averageLines()
HiVector Isis::averageLines (const HiMatrix & m, int sline = 0, int eline = -1) inline
Reduces by averaging specified lines from a buffer.
This function produces a vector from a 2-D buffer of averaged lines at each vertical sample location
Parameters
m Buffer to reduce
sline Starting line number (first line is 0)
eline Last line to average (-1 means use all lines)
Returns
HiVector Buffer containing averaged lines
References Isis::Statistics::AddData(), and Isis::Statistics::Average().
averageSamples()
HiVector Isis::averageSamples (const HiMatrix & m, int ssamp = 0, int esamp = -1) inline
Reduces by averaging specified samples from a buffer.
This function produces a vector from a 2-D buffer of averaged samples at each horizontal line location
Parameters
m Buffer to reduce
ssamp Starting sample number (first sample is 0)
esamp Last sample to average (-1 means use all samples)
Returns
HiVector Buffer containing averaged samples
References Isis::Statistics::AddData(), and Isis::Statistics::Average().
b3_MaxBodyParts()
int Isis::b3_MaxBodyParts () inline
Maximum number of parts/object in the Bullet 3 API.
Returns
int The maximum number of parts allowed in each collision objects.
References bt_MaxBodyParts().
b3_MaxTriangles()
unsigned long Isis::b3_MaxTriangles () inline
Maximum number of triangles/part in the Bullet 3 API.
Returns
long The maximum number of triangles allowed in each collision objects.
References bt_MaxTriangles().
backsub()
int Isis::backsub (double * a, double * b, int nsize) inline
References NOT_SOLVABLE, and SOLVED.
Referenced by choleski_solve().
binomial_coeficient()
int Isis::binomial_coeficient (int n, int k) inline
Referenced by indeces_from_set().
BitwiseAndOperator()
double Isis::BitwiseAndOperator (double a, double b)
Returns the result of a bitwise AND accross a and b.
Parameters
a Input double
b Input double
Returns
the double result of a bitwise AND operation
References Round().
Referenced by Isis::Calculator::And().
BitwiseOrOperator()
double Isis::BitwiseOrOperator (double a, double b)
Returns the result of a bitwise OR across a and b.
Parameters
a Input double
b INput double
Returns
the double result of a bitwise OR operation
References Round().
Referenced by Isis::Calculator::Or().
bt_MaxBodyParts()
int Isis::bt_MaxBodyParts () inline
Maximum number of parts/object.
Returns
int The maximum number of parts allowed in each collision objects.
Referenced by b3_MaxBodyParts().
bt_MaxTriangles()
unsigned long Isis::bt_MaxTriangles () inline
Maximum number of triangles/part.
Returns
long The maximum number of triangles allowed in each collision objects.
Referenced by b3_MaxTriangles().
ByteOrderEnumeration()
Isis::ByteOrder Isis::ByteOrderEnumeration (const QString & order) inline
References Lsb, Msb, and NoByteOrder.
Referenced by Isis::Table::initFromBlob().
ByteOrderName()
QString Isis::ByteOrderName (Isis::ByteOrder byteOrder) inline
References Lsb, Msb, and NoByteOrder.
Referenced by Isis::CubeAttributeOutput::byteOrderString(), Isis::Cube::create(), Isis::ProcessExportPds::ExportTable(), Isis::ProcessImport::ProcessBil(), Isis::ProcessImport::ProcessBip(), Isis::ProcessImport::ProcessBsq(), Isis::OriginalXmlLabel::toBlob(), and Isis::Table::toBlob().
CcdToFilter()
QString Isis::CcdToFilter (int ccd) inline
Convert HiRISE Ccd number to string filter name.
Parameters
ccd Ccd number of device
References _FILEINFO_, toString(), and Isis::IException::User.
choleski_solve()
int Isis::choleski_solve (double * a, double * b, int nsize, int flag) inline
References backsub(), decompose(), foresub(), inverse(), NOT_SOLVABLE, and SOLVED.
Referenced by Isis::Selection::bestFitEllipse(), and Isis::ApolloPanIO::computeInteriorOrienation().
cholmodErrorHandler()
static void Isis::cholmodErrorHandler (int nStatus, const char * file, int nLineNo, const char * message) static
Custom error handler for CHOLMOD.
If CHOLMOD encounters an error then this will be called.
Parameters
status The CHOLMOD error status.
file The name of the source code file where the error occured.
lineNumber The line number in file where the error occured.
message The error message.
References toString().
ConfKey()
template<typename T > T Isis::ConfKey (const DbProfile & conf, const QString & keyname, const T & defval, int index = 0)
Find a keyword in a profile using default for non-existant keywords.
This template function will extract keyword values from a profile and provide the values at the indicated index. If the keyword does not exist or the indicated value at index, the provided default will be used instead.
References Isis::DbProfile::count(), Isis::DbProfile::exists(), and Isis::DbProfile::value().
Referenced by Isis::LoadCSV::load(), and Isis::ZeroBufferFit::ZeroBufferFit().
convertLastChildNodeToJson()
json Isis::convertLastChildNodeToJson (QDomElement & element)
Not intended to be used directly.
Converts a QDomElement to JSON and returns. Only called when a QDomElement has no further child nodes
Used for the following situations:
XML: <tag>value</tag> JSON: {tag: value}
XML: <tag attributeName="attributeValue">textValue</tag> JSON: {tag: {attrib_attributeName: "attributeValue, "_text":textValue } }
XML: <tag attributeName="attributeValue" > JSON: {tag: {attrib_attributeName: "attributeValue"} }
XML: <tag > JSON: tag: null
Parameters
element A QDomElement to be converted to JSON and added to the JSON object.
Referenced by convertXmlToJson().
convertXmlToJson()
json Isis::convertXmlToJson (QDomElement & element, json & output)
Not intended to be used directly.
Intended to be used by xmlToJson to convert an input XML document to JSON.
This function does the following conversions:
XML: val1val2 JSON: a : {b: val1, c: val2}
XML: <first>value1</first> <second>value2</second> JSON: a: [ {first:value1}, {second:value2} ]
XML: val1val2 JSON: a:[val1, val2]
Parameters
element A QDomElement representing the whole or some subset of a QDomDocument
output A JSON object constructed from XML input.
Returns
json
References convertLastChildNodeToJson().
Referenced by xmlToJson().
CosecantOperator()
double Isis::CosecantOperator (double a)
Returns the cosecant of the input a.
Parameters
a Input double
Returns
the double result of the cosecant of a
Referenced by Isis::Calculator::Cosecant().
CotangentOperator()
double Isis::CotangentOperator (double a)
Returns the cotangent of the input a.
Parameters
a Input double
Returns
the double result of the cotangent of a
Referenced by Isis::Calculator::Cotangent().
CpmmToCcd()
int Isis::CpmmToCcd (int cpmm) inline
Convert HiRISE Cpmm number to Ccd number.
Parameters
cpmm Cpmm number
References _FILEINFO_, toString(), and Isis::IException::User.
cropLines()
HiMatrix Isis::cropLines (const HiMatrix & m, int sline, int eline) inline
Crop specified lines from a buffer.
This function extracts lines from a buffer and returns a new buffer with the extracted lines.
Parameters
m Buffer to extract lines from
sline Starting line number (first line is 0)
eline Last line to extract
Returns
HiMatrix Buffer containing cropped lines
Referenced by Isis::HiCalData::getMask(), Isis::HiCalData::getMaskExtended(), Isis::HiCalData::getRamp(), Isis::HiCalData::getRampExtended(), Isis::HiCalData::getReverseClock(), and Isis::HiCalData::getReverseClockExtended().
cropSamples()
HiMatrix Isis::cropSamples (const HiMatrix & m, int ssamp, int esamp) inline
Crop specified samples from a buffer.
This function extracts samples from a buffer and returns a new buffer with the extracted samples.
Parameters
m Buffer to extract samples from
ssamp Startling sample (first sample 0)
esamp Ending sample to extract
Returns
HiMatrix Buffer with cropped samples
decompose()
int Isis::decompose (double * a, int nsize) inline
References NOT_SOLVABLE, and SOLVED.
Referenced by choleski_solve().
DivideOperator()
double Isis::DivideOperator (double a, double b)
Returns the result of dividing a by b.
Parameters
a Input double
b Intput double
Returns
double result of a/b
Referenced by Isis::Calculator::Divide().
EqualOperator()
double Isis::EqualOperator (double a, double b)
Returns 1.0 if a is equal ot b.
Parameters
a Input double
b Input double
Returns
1.0 if a==b
Referenced by Isis::Calculator::Equal().
fitsToJson() [1/2]
nlohmann::json Isis::fitsToJson (FileName fitsFile)
Converts a FITS file to a json object.
Parameters
fitsFile Path to a FITS file.
Returns
json The FITS file converted to a json object.
References _FILEINFO_, Isis::FileName::expanded(), fitsToJson(), Isis::FileName::toString(), and Isis::IException::User.
fitsToJson() [2/2]
nlohmann::json Isis::fitsToJson (std::ifstream & fileStream)
Convert the contents of a stream to a JSON object.
Parameters
the stream to convert
Returns
json The contents of the stream as a JSON object
This logic was taken from ProcessImportFits::extractFitsLabels
References _FILEINFO_, Isis::PvlKeyword::addComment(), Isis::PvlObject::addGroup(), Isis::PvlContainer::addKeyword(), Isis::PvlContainer::findKeyword(), Isis::PvlContainer::hasKeyword(), Isis::PvlKeyword::name(), pvlObjectToJSON(), Isis::PvlContainer::setName(), Isis::PvlKeyword::setName(), Isis::PvlKeyword::setUnits(), toInt(), Isis::IString::Token(), Isis::IString::ToQt(), Isis::IString::TrimHead(), Isis::IString::TrimTail(), and Isis::IException::User.
Referenced by fitsToJson().
floatModulusOperator()
double Isis::floatModulusOperator (double a, double b)
Determines the remainder of the quotient a/b whose sign is the same as that of a.
In other words, this method finds the value r = a - bq such that q is the integer found by truncating a/b.
Parameters
a The dividend (numerator).
b The divisor (denominator).
Returns
double The remainder of the quotient that has the same sign as the dividend.
Referenced by Isis::InlineCalculator::floatModulus().
foresub()
int Isis::foresub (double * a, double * b, int nsize) inline
References NOT_SOLVABLE, and SOLVED.
Referenced by choleski_solve().
GainLineStat()
double Isis::GainLineStat (std::vector< double > & data) inline
Return the statistics for a vector of data.
The default statistic returned is the median of the dataset but can be changed with a compile time change. The vector passed in will be sorted so that the median can be determined. If the vector has an even number of elements in it, the average of the two center values will be returned. The array is assumed to be clean data, no ISIS special pixels.
Parameters
data Vector containing data compute the statistic. It will be altered (sorted) upon return to the caller.
Returns
double The median (default) of the data
References Isis::Statistics::AddData(), and Null.
getStringAttribute()
QString Isis::getStringAttribute (int locationId, QString locationName, QString attributeName)
GreaterThanOperator()
double Isis::GreaterThanOperator (double a, double b)
Returns 1.0 if a is greater than b.
Otherwise 0.0 is returned.
Parameters
a Input double
b Input double
Returns
1.0 if a>b
Referenced by Isis::Calculator::GreaterThan().
GreaterThanOrEqualOperator()
double Isis::GreaterThanOrEqualOperator (double a, double b)
Returns 1.0 if a is greater than or equal to b.
Otherwise 0.0 is returned.
Parameters
a Input double
b Input double
Returns
1.0 if a>=b
Referenced by Isis::Calculator::GreaterThanOrEqual().
HiTempEqn()
double Isis::HiTempEqn (const double temperature, const double napcm2 = 2.0, const double px = 12.0) inline
Implements (classic) HiRISE temperature equation.
This function computes the dark current temperature and returns the results in electrons/sec/pixel.
Parameters
temperature Temperature (typically of the FPGA)
napcm2 Dark current for silicone diodes (nano-ampres/cm^2)
px Pixel size in microns
Returns
double Dark current temperature (electrons/sec/pixel)
indeces_from_set()
int Isis::indeces_from_set (int * indeces, int set, int set_size, int n) inline
References binomial_coeficient().
InValidCount()
int Isis::InValidCount (const HiVector & v) inline
Counts number of invalid pixels in vector.
Parameters
v Vector to inspect
Returns
int Number invalid (special) pixels in vector
References IsSpecial().
inverse()
int Isis::inverse (double * a, int nsize) inline
References SOLVED.
Referenced by choleski_solve().
IsBigEndian()
bool Isis::IsBigEndian () inline
Deprecated:
Test the architecture the application is running on.
Returns
True if it's BigEndian, False if it's not.
References IsLsb().
IsBlob()
bool Isis::IsBlob (PvlObject & obj)
Checks pvl object and returns whether or not it is a Blob.
Parameters
obj Pvl object
Returns
bool Returns true if the object is a blob, and false if it is not
References Isis::PvlContainer::isNamed().
IsEqual()
bool Isis::IsEqual (const QString & v1, const QString & v2 = "TRUE") inline
Shortened string equality test.
Parameters
v1 First value
v2 Second value
Returns
bool True if they are equal w/o regard to case
Referenced by IsTrueValue(), Isis::LoadCSV::load(), and Isis::ZeroBufferFit::ZeroBufferFit().
IsHighPixel()
bool Isis::IsHighPixel (const double d) inline
Returns if the input pixel is one of the high saturation types.
Parameters
d Pixel value to test
Returns
bool
References HIGH_INSTR_SAT8, and HIGH_REPR_SAT8.
Referenced by Isis::ProcessMosaic::StartProcess().
IsHisPixel()
bool Isis::IsHisPixel (const double d) inline
Returns if the input pixel is high instrument saturation.
Parameters
d Pixel value to test
Returns
bool
References HIGH_INSTR_SAT8.
Referenced by Isis::Statistics::AddData(), Isis::Stretch::Map(), PixelToString(), Isis::Calculator::Push(), and Isis::Statistics::RemoveData().
IsHrsPixel()
bool Isis::IsHrsPixel (const double d) inline
Returns if the input pixel is high representation saturation.
Parameters
d Pixel value to test
Returns
bool
References HIGH_REPR_SAT8.
Referenced by Isis::Statistics::AddData(), Isis::Stretch::Map(), PixelToString(), Isis::Calculator::Push(), and Isis::Statistics::RemoveData().
IsLisPixel()
bool Isis::IsLisPixel (const double d) inline
Returns if the input pixel is low instrument saturation.
Parameters
d Pixel value to test
Returns
bool
References LOW_INSTR_SAT8.
Referenced by Isis::Statistics::AddData(), Isis::Stretch::Map(), PixelToString(), Isis::Calculator::Push(), and Isis::Statistics::RemoveData().
IsLittleEndian()
bool Isis::IsLittleEndian () inline
Deprecated:
Test the architecture the application is running on.
Returns
True if it's LittleEndian, False if it's not.
References IsLsb().
IsLowPixel()
bool Isis::IsLowPixel (const double d) inline
Returns if the input pixel is one of the low saturation types.
Parameters
d Pixel value to test
Returns
bool
References LOW_INSTR_SAT8, and LOW_REPR_SAT8.
Referenced by Isis::ProcessMosaic::StartProcess().
IsLrsPixel()
bool Isis::IsLrsPixel (const double d) inline
Returns if the input pixel is low representation saturation.
Parameters
d Pixel value to test
Returns
bool
References LOW_REPR_SAT8.
Referenced by Isis::Statistics::AddData(), PixelToString(), Isis::Calculator::Push(), and Isis::Statistics::RemoveData().
IsLsb()
bool Isis::IsLsb () inline
Return true if this host is an LSB first machine and false if it is not.
Returns
bool - Returns true if host is LSB and false if it is MSB
Referenced by Isis::CubeAttributeOutput::byteOrder(), Isis::EndianSwapper::EndianSwapper(), Isis::Table::initFromBlob(), IsBigEndian(), IsLittleEndian(), IsMsb(), Isis::ProcessExport::ProcessExport(), Isis::OriginalXmlLabel::toBlob(), and Isis::Table::toBlob().
IsMsb()
bool Isis::IsMsb () inline
Return true if this host is an MSB first machine and false if it is not.
Returns
bool - Returns true if host is MSB and false if it is LSB
References IsLsb().
Referenced by Isis::EndianSwapper::EndianSwapper(), and Isis::Table::initFromBlob().
IsNullPixel()
bool Isis::IsNullPixel (const double d) inline
Returns if the input pixel is null.
Parameters
d Pixel value to test
Returns
bool
References NULL8.
Referenced by Isis::Statistics::AddData(), Isis::Stretch::Map(), PixelToString(), Isis::Calculator::Push(), Isis::Statistics::RemoveData(), and Isis::ProcessMosaic::StartProcess().
IsSpecial() [1/2]
bool Isis::IsSpecial (const double d) inline
Returns if the input pixel is special.
Not special implies it is valid to use in computations.
Parameters
d Pixel value to test
Returns
bool
References VALID_MIN8.
Referenced by Isis::PipelineApplication::BuildParamString(), Isis::IsisBundleObservation::bundleOutputCSV(), Isis::IsisBundleObservation::bundleOutputString(), Isis::CsmBundleObservation::bundleOutputString(), Isis::CameraStatistics::constructKeyword(), Isis::PlotWindowBestFitDialog::createBestFitLine(), Isis::OverlapNormalization::Evaluate(), Isis::PlotWindow::fillTable(), Isis::BundleControlPoint::formatAdjustedSigmaString(), Isis::BundleControlPoint::formatAprioriSigmaString(), Isis::BundleControlPoint::formatBundleLatitudinalOutputDetailString(), Isis::BundleControlPoint::formatBundleRectangularOutputDetailString(), Isis::Module::formatDbl(), Isis::BundleControlPoint::formatValue(), Isis::ControlMeasure::GetResidualMagnitude(), Isis::ForstnerOperator::Interest(), Isis::StandardDeviationOperator::Interest(), Isis::DemShape::intersectSurface(), Isis::EquatorialCylindricalShape::intersectSurface(), InValidCount(), Isis::Coordinate::isValid(), Isis::SurfacePoint::LatitudeToMeters(), Isis::SurfacePoint::LongitudeToMeters(), Isis::MinimumDifference::MatchAlgorithm(), Isis::Calculator::MaximumLine(), Isis::MosaicControlNetTool::maxMovementColorResidualMagnitude(), Isis::SurfacePoint::MetersToLatitude(), Isis::SurfacePoint::MetersToLongitude(), Isis::Calculator::MinimumLine(), Isis::VisualDisplay::mouseMoveEvent(), Isis::Equalization::ApplyFunctor::operator()(), Isis::Average::operator()(), Isis::Displacement::operator*(), Isis::Distance::operator*(), Isis::Displacement::operator*=(), Isis::Distance::operator*=(), Isis::iTime::operator+=(), Isis::iTime::operator-=(), Isis::Displacement::operator/(), Isis::Distance::operator/(), Isis::Displacement::operator/=(), Isis::Distance::operator/=(), operator<<(), Isis::BundleSolutionInfo::outputPointsCSV(), Isis::ScatterPlotWindow::paint(), Isis::ControlPointGraphicsItem::paint(), Isis::VisualDisplay::paintPixmap(), PixelToString(), Isis::Longitude::positiveWest(), Isis::Calculator::Push(), rebin(), Isis::SpectralPlotTool::refreshPlot(), Isis::BundleSettings::save(), Isis::BundleObservationSolveSettings::save(), Isis::Image::save(), Isis::Shape::save(), Isis::ScatterPlotData::ScatterPlotData(), Isis::Latitude::setAngle(), Isis::Angle::setAngle(), Isis::Displacement::setDisplacement(), Isis::Distance::setDistance(), Isis::iTime::setEt(), Isis::CubeAttributeOutput::setMaximum(), Isis::CubeAttributeOutput::setMinimum(), Isis::ScatterPlotWindow::setMousePosition(), Isis::Latitude::setPlanetographic(), Isis::Longitude::setPositiveWest(), Isis::BundleControlPoint::setWeights(), Isis::Hillshade::shadedValue(), Isis::Pixel::ToString(), ValidCount(), and Isis::ControlNetValidMeasure::ValidDnValue().
IsSpecial() [2/2]
bool Isis::IsSpecial (const float f) inline
Returns if the input pixel is special.
Not special implies it is valid to use in computations. This method applies to a 4-byte floating point rather than an 8-byte double
Parameters
f Pixel value to test
Returns
bool
References VALID_MIN4.
IsTrueValue()
bool Isis::IsTrueValue (const DbProfile & prof, const QString & key, const QString & value = "TRUE") inline
Determines if the keyword value is the expected value.
This function checks the existance of a keyword in a profile, extracts the first value and tests it for equivelance to the expected value. Note this test is case insensitive.
Parameters
prof Profile to find the expected keyword in
key Name of keyword in profile to test
value Value to test for in keyword
Returns
bool Returns true only if the keyword exists in the profile and it is the value expected.
References Isis::DbProfile::exists(), and IsEqual().
Referenced by SkipModule(), and Isis::ZeroBufferFit::ZeroBufferFit().
IsValidPixel()
bool Isis::IsValidPixel (const double d) inline
Returns if the input pixel is valid.
Parameters
d Pixel value to test
Returns
bool
References VALID_MIN8.
Referenced by Isis::Histogram::AddData(), Isis::ImageHistogram::AddData(), Isis::MultivariateStatistics::AddData(), Isis::QuickFilter::AddLine(), Isis::Stretch::Map(), Isis::Average::operator()(), Isis::ProcessImport::ProcessBil(), Isis::ProcessImport::ProcessBip(), Isis::ProcessImport::ProcessBsq(), Isis::ProcessImport::ProcessJp2(), Isis::Histogram::RemoveData(), Isis::ImageHistogram::RemoveData(), Isis::MultivariateStatistics::RemoveData(), Isis::QuickFilter::RemoveLine(), and Isis::ProcessMosaic::StartProcess().
isymp()
int Isis::isymp (int row, int col) inline
Referenced by Isis::Selection::bestFitEllipse(), and Isis::ApolloPanIO::computeInteriorOrienation().
LabelAttachmentEnumeration()
LabelAttachment Isis::LabelAttachmentEnumeration (const QString & labelType) inline
Return the appropriate LabelType depending on which of the valid values the argument spells.
Parameters
labelType
Returns
The RangeType enum corresponding to the string parameter
References _FILEINFO_, AttachedLabel, DetachedLabel, ExternalLabel, and Isis::IException::Unknown.
LabelAttachmentName()
QString Isis::LabelAttachmentName (LabelAttachment labelType) inline
Return the string representation of the contents of a variable of type LabelAttachment.
Parameters
labelType The LabelAttachment enum to be converted to a string
Returns
A string representation of the parameter
References _FILEINFO_, AttachedLabel, DetachedLabel, ExternalLabel, and Isis::IException::Programmer.
Referenced by Isis::CubeAttributeOutput::setLabelAttachment().
LessThanOperator()
double Isis::LessThanOperator (double a, double b)
Returns 1.0 if a is less than b.
Otherwise 0.0 is returned.
Parameters
a Input double
b Input double
Returns
1.0 if a<b
Referenced by Isis::Calculator::LessThan().
LessThanOrEqualOperator()
double Isis::LessThanOrEqualOperator (double a, double b)
Returns 1.0 if a is less than or eqaul to b.
Otherwise 0.0 is returned.
Parameters
a Input double
b Input double
Returns
1.0 if a<=b
Referenced by Isis::Calculator::LessThanOrEqual().
MaximumOperator()
double Isis::MaximumOperator (double a, double b)
Returns the max of a and b.
Parameters
a First input value
b Second input value
Returns
The larger of the two
Referenced by Isis::Calculator::MaximumPixel().
MinimumOperator()
double Isis::MinimumOperator (double a, double b)
Returns the min of a and b.
Parameters
a First input value
b Second input value
Returns
The smaller of the two
Referenced by Isis::Calculator::MinimumPixel().
ModulusOperator()
double Isis::ModulusOperator (double a, double b)
Returns the modulus of a by b.
Parameters
a Input modulee
b Input modulator
Returns
double result of ab
References Round().
Referenced by Isis::Calculator::Modulus().
MultiplyOperator()
double Isis::MultiplyOperator (double a, double b)
Returns the result of a multiplied by b.
Parameters
a Input double
b Input double
Returns
double result of a*b
Referenced by Isis::Calculator::Multiply().
NegateOperator()
double Isis::NegateOperator (double a)
Returns the nagative of the input parameter.
Parameters
a Input double
Returns
double negative of a
Referenced by Isis::Calculator::Negative().
nocase_compare()
static bool Isis::nocase_compare (const char c1, const char c2) static
Compare two characters without regard to case.
This small, internal function compares two characters while ignoring case. This is used in the STL equal function to compare the contents of two STL strings.
Deprecated:
Parameters
c1 First character to compare
c2 Second character to compare
Returns
true if the two characters are the same, false otherwise
Referenced by Isis::IString::Equal().
NotEqualOperator()
double Isis::NotEqualOperator (double a, double b)
Returns 1.0 is a is not equal to b.
Otherwise 0.0 is returned.
Parameters
a Input double
b Input double
Returns
1.0 if a!=b
Referenced by Isis::Calculator::NotEqual().
operator*() [1/3]
Angle Isis::operator* (double mult, Angle angle)
Multiply this angle by a double and return the resulting angle.
If this is an invalid angle, then the result will be an invalid angle.
Parameters
mult The value to multiply to this angle
angle The angle being multiplied by mult
Returns
Multiplied angle
operator*() [2/3]
Displacement Isis::operator* (double mult, Displacement displacement)
Multiply displacement by a value (5m * 2 = 10m).
Parameters
mult This is the value to multiply by
displacement This is the distance to multiply into
Returns
Resulting value
operator*() [3/3]
Distance Isis::operator* (double mult, Distance dist)
Multiply this distance by a value (5m * 2 = 10m).
Parameters
mult This is the value to multiply by
dist This is the distance to multiply into
Returns
Resulting value
operator+() [1/3]
Coordinate Isis::operator+ (const Coordinate & A, const Coordinate & B) inline
Summation operator for Coordinate.
Parameters
A First operand
B Second operand
Returns
Coordinate Returns the sum of the two coordinates if they are both valid otherwise returns invalid point
References Isis::Coordinate::isValid(), Isis::Coordinate::m_x, and Isis::Coordinate::m_y.
operator+() [2/3]
iTime Isis::operator+ (const double & secondsToAdd, iTime time)
operator+() [3/3]
Radiometric Isis::operator+ (const Radiometric & A, const Radiometric & B) inline
Operator to sum two radiometric parameters.
References Isis::Radiometric::m_gain, and Isis::Radiometric::m_shift.
operator-() [1/2]
Coordinate Isis::operator- (const Coordinate & A, const Coordinate & B) inline
Subtraction operator for Coordinate.
Parameters
A First operand
B Second operand
Returns
Coordinate Returns the difference between the two coordinates if they are both valid otherwise returns invalid point
References Isis::Coordinate::isValid(), Isis::Coordinate::m_x, and Isis::Coordinate::m_y.
operator-() [2/2]
iTime Isis::operator- (const double & secondsToSubtract, iTime time)
operator<<() [1/28]
ostream& Isis::operator<< (ostream & os, Matrix & matrix)
Write the matrix to the output stream.
References Isis::Matrix::Columns(), and Isis::Matrix::Rows().
operator<<() [2/28]
ostream& Isis::operator<< (ostream & os, Pipeline & pipeline)
This is the output operator for a Pipeline, which enables things such as:
Pipeline p;
cout <<  p << endl;
Parameters
os The output stream (usually cout)
pipeline The pipeline object to output
Returns
ostream& The modified output stream
References Isis::Pipeline::Application(), Isis::PipelineApplication::Enabled(), Isis::Pipeline::KeepTemporaryFiles(), Isis::Pipeline::Name(), Isis::PipelineApplication::Name(), Isis::PipelineApplication::ParamString(), Isis::Pipeline::Prepare(), Isis::Pipeline::Size(), and Isis::PipelineApplication::TemporaryFiles().
operator<<() [3/28]
QDataStream & Isis::operator<< (QDataStream & stream, const MaximumLikelihoodWFunctions & mlwf)
References Isis::MaximumLikelihoodWFunctions::write().
operator<<() [4/28]
QDataStream & Isis::operator<< (QDataStream & stream, const MaximumLikelihoodWFunctions::Model & modelEnum)
operator<<() [5/28]
QDataStream & Isis::operator<< (QDataStream & stream, const SparseBlockColumnMatrix & sbcm)
Writes matrix to binary disk file pointed to by QDataStream stream.
Parameters
stream stream pointing to binary disk file
sbcm SparseBlockColumnMatrix to write
operator<<() [6/28]
QDataStream & Isis::operator<< (QDataStream & stream, const SparseBlockMatrix & sparseBlockMatrix)
Writes matrix to binary disk file pointed to by QDataStream stream.
Parameters
stream stream pointing to binary disk file
sparseBlockMatrix SparseBlockMatrix to write
operator<<() [7/28]
QDataStream & Isis::operator<< (QDataStream & stream, const SparseBlockRowMatrix & sbrm)
Writes matrix to binary disk file pointed to by QDataStream stream.
Parameters
stream stream pointing to binary disk file
sbrm SparseBlockRowMatrix to write
operator<<() [8/28]
QDataStream & Isis::operator<< (QDataStream & stream, const StatCumProbDistDynCalc & scpddc)
References Isis::StatCumProbDistDynCalc::write().
operator<<() [9/28]
QDataStream & Isis::operator<< (QDataStream & stream, const Statistics & statistics)
References Isis::Statistics::write().
operator<<() [10/28]
QDataStream& Isis::operator<< (QDataStream & stream, const TargetBody & TargetBody)
operator<<() [11/28]
QDebug Isis::operator<< (QDebug dbg, const LinearAlgebra::Matrix & matrix)
A global function to format a LinearAlgebra::Matrix as a QString and write it to a QDebug stream.
There will be 4 spaces between each matrix entry and each row is written on a new line.
Parameters
dbg The stream where the vector will be written.
matrix The matrix to be written.
Returns
QDebug The stream with the QString-formatted matrix.
References toString().
operator<<() [12/28]
QDebug Isis::operator<< (QDebug dbg, const LinearAlgebra::Vector & vector)
A global function to format a LinearAlgebra::Vector as a QString and writes it to a QDebug stream.
See also
toString(LinearAlgebra::Vector)
Parameters
dbg The stream where the vector will be written.
vector The vector to be written.
Returns
QDebug The stream with the QString-formatted vector.
References toString().
operator<<() [13/28]
QDebug Isis::operator<< (QDebug dbg, const SparseBlockColumnMatrix & sbcm)
Writes matrix to QDebug stream.
Parameters
dbg debug stream
sbcm SparseBlockColumnMatrix to write to debug stream
operator<<() [14/28]
QDebug Isis::operator<< (QDebug dbg, const SparseBlockMatrix & m)
Writes matrix to QDebug stream.
Parameters
dbg debug stream
m SparseBlockMatrix to write to debug stream
operator<<() [15/28]
QDebug Isis::operator<< (QDebug dbg, const SparseBlockRowMatrix & sbrm)
Writes matrix to QDebug stream.
Parameters
dbt debug stream
sbcm SparseBlockRowMatrix to write to debug stream
operator<<() [16/28]
QDebug Isis::operator<< (QDebug dbg, const TNT::Array1D< SpiceDouble > & tntArray)
Enables any TNT array of SpiceDoubles to be passed into qDebug() directly.
Valid inputs include NaifVector and NaifVertex. Array values will be printed on a single line with precision=15 digits.
Parameters
tntArray TNT array to be printed.
References toString().
operator<<() [17/28]
QDebug Isis::operator<< (QDebug dbg, const TNT::Array2D< SpiceDouble > & tntMatrix)
Enables any 2 dimensional TNT array of SpiceDoubles to be passed into qDebug() directly.
Valid inputs include NaifTriangle. Each row will be indented 4 spaces and each entry will be printed with precision=15 digits.
Parameters
tntMatrix Two dimensional TNT array to be printed.
References toString().
operator<<() [18/28]
QDebug Isis::operator<< (QDebug debug, const Hillshade & hillshade)
Print this class out to a QDebug object.
References Isis::Hillshade::azimuth(), IsSpecial(), Isis::Hillshade::resolution(), toString(), Isis::Angle::toString(), and Isis::Hillshade::zenith().
operator<<() [19/28]
ostream& Isis::operator<< (std::ostream & os, const Isis::PvlKeyword & keyword)
Write out the keyword.
Parameters
os The output stream.
keyword The PvlKeyword object to output.
Returns
ostream& Reference to ostream.
See also
writeWithWrap()
operator<<() [20/28]
std::ostream & Isis::operator<< (std::ostream & os, Isis::OverlapStatistics & stats)
Creates a pvl of various useful data obtained by the overlap statistics class.
The pvl is returned in an output stream
Parameters
os The output stream to write to
stats The OverlapStatistics object to write to os
Returns
ostream Pvl of useful statistics
References Isis::OverlapStatistics::toPvl().
operator<<() [21/28]
std::ostream& Isis::operator<< (std::ostream & os, Isis::SessionLog & log)
operator<<() [22/28]
std::ostream& Isis::operator<< (std::ostream & os, Matrix & matrix)
operator<<() [23/28]
ostream& Isis::operator<< (std::ostream & os, Isis::Pvl & pvl)
This stream will not handle the end of line sequence.
Parameters
os
pvl
Returns
ostream&
operator<<() [24/28]
std::ostream & Isis::operator<< (std::ostream & os, PvlContainer & container)
Output the PvlContainer information.
Parameters
os The preferred output stream.
container The PvlContainer object to output.
References _FILEINFO_, Isis::PvlContainer::addKeyword(), Isis::PvlContainer::comment(), Isis::PvlContainer::comments(), Isis::FileName::expanded(), Isis::FileName::fileExists(), Isis::PvlContainer::format(), Isis::PvlFormat::formatEOL(), Isis::PvlContainer::formatTemplate(), Isis::PvlContainer::hasFormatTemplate(), Isis::PvlContainer::hasKeyword(), Isis::PvlContainer::indent(), Isis::PvlContainer::keywords(), Isis::PvlContainer::name(), Isis::PvlContainer::setFormat(), Isis::PvlContainer::setIndent(), and Isis::PvlContainer::type().
operator<<() [25/28]
ostream& Isis::operator<< (std::ostream & os, PvlGroup & group)
Outputs the PvlGroup data to a specified output stream.
Parameters
os The output stream to output to.
group The PvlGroup object to output.
operator<<() [26/28]
ostream& Isis::operator<< (std::ostream & os, Isis::PvlObject & object)
Outputs the PvlObject data to a specified output stream.
Parameters
os The output stream to write to.
object The PvlObject to send to the output stream.
operator<<() [27/28]
std::ostream & Isis::operator<< (std::ostream & outputStream, const QString & string)
Print an ASCII representation of the given QString to a stl stream (most commonly cout, cerr).
This is provided for convenience. No extra formatting is done; please see qDebug for a better way of printing out debug statements.
Parameters
outputStream The stream to write the string to
string The string to put into the stream
Returns
The modified output stream
operator<<() [28/28]
std::ostream & Isis::operator<< (std::ostream & outputStream, const QStringRef & string)
Print an ASCII representation of the given QStringRef to a stl stream (most commonly cout, cerr).
This is provided for convenience. No extra formatting is done; please see qDebug for a better way of printing out debug statements.
Parameters
outputStream The stream to write the string to
string The string to put into the stream
Returns
The modified output stream
References toString().
operator>>() [1/13]
QDataStream & Isis::operator>> (QDataStream & stream, MaximumLikelihoodWFunctions & mlwf)
References Isis::MaximumLikelihoodWFunctions::read().
operator>>() [2/13]
QDataStream & Isis::operator>> (QDataStream & stream, MaximumLikelihoodWFunctions::Model & modelEnum)
operator>>() [3/13]
QDataStream & Isis::operator>> (QDataStream & stream, SparseBlockColumnMatrix & sbcm)
Reads matrix from binary disk file pointed to by QDataStream stream.
Parameters
stream stream pointing to binary disk file
sbcm SparseBlockColumnMatrix to read
References Isis::SparseBlockColumnMatrix::insertMatrixBlock().
operator>>() [4/13]
QDataStream & Isis::operator>> (QDataStream & stream, SparseBlockMatrix & sparseBlockMatrix)
Reads matrix from binary disk file pointed to by QDataStream stream.
Parameters
stream stream pointing to binary disk file
sparseBlockMatrix SparseBlockMatrix to read
References Isis::SparseBlockMatrix::setNumberOfColumns().
operator>>() [5/13]
QDataStream & Isis::operator>> (QDataStream & stream, SparseBlockRowMatrix & sbrm)
Reads matrix from binary disk file pointed to by QDataStream stream.
Parameters
stream stream pointing to binary disk file
sbcm SparseBlockColumnMatrix to read
References Isis::SparseBlockRowMatrix::insertMatrixBlock().
operator>>() [6/13]
QDataStream & Isis::operator>> (QDataStream & stream, StatCumProbDistDynCalc & scpddc)
References Isis::StatCumProbDistDynCalc::read().
operator>>() [7/13]
QDataStream & Isis::operator>> (QDataStream & stream, Statistics & statistics)
References Isis::Statistics::read().
operator>>() [8/13]
QDataStream& Isis::operator>> (QDataStream & stream, TargetBody & TargetBody)
operator>>() [9/13]
std::istream& Isis::operator>> (std::istream & is, CSVReader & csv)
Input read operator for input stream sources.
This input operator can be invoked directly from the users environment to read the complete input source. It can also be used to augment an existing source as this technique does not discard existing data (lines).
It is presumed that any additional input sources are consistant to pre-established parsing guidelines otherwise, the integrity of the table is compromized.
Here is an example of how to use this method:
ifstream ifile("myfile.csv");
CSVReader csv;
ifile >> csv;
Parameters
is Input stream source
csv CSVReader object to read input source lines from
Returns
std::istream& Returns the state of the input stream at EOF or error
operator>>() [10/13]
istream& Isis::operator>> (std::istream & is, Pvl & pvl)
Reads keywords from the instream and appends them to the Pvl object.
Parameters
is A specified instream to read from.
pvl The Pvl object to append to.
Exceptions
iException Invalid PVL format specified.
Returns
Returns the entered instream after reading from it.
operator>>() [11/13]
std::istream& Isis::operator>> (std::istream & is, PvlGroup & result)
Read in a group.
Parameters
is The input stream
result The PvlGroup to read into (OUTPUT)
operator>>() [12/13]
std::istream& Isis::operator>> (std::istream & is, PvlKeyword & result)
Read in a keyword.
http://pds.jpl.nasa.gov/tools/standards-reference.shtml
Parameters
is The input stream
result The keyword to read into (OUTPUT)
operator>>() [13/13]
std::istream& Isis::operator>> (std::istream & is, PvlObject & result)
This method reads a PvlObject from the input stream.
operator|()
Kernel::Type Isis::operator| (Kernel::Type a, Kernel::Type b)
Logical operator for combining Type flags.
Parameters
a The first Type flag.
b The second Type flag.
Returns
Type flag that contains all Types in a and all Types in b.
PixelToString()
QString Isis::PixelToString (double d, double precision = 8) inline
Takes a double pixel value and returns the name of the pixel type as a string.
Parameters
d Pixel value
Returns
string The name of the pixel type
References IsHisPixel(), IsHrsPixel(), IsLisPixel(), IsLrsPixel(), IsNullPixel(), and IsSpecial().
Referenced by Isis::Module::formatDbl(), Isis::VisualDisplay::mouseMoveEvent(), Isis::Average::operator()(), and Isis::VisualDisplay::paintPixmap().
PixelTypeEnumeration()
Isis::PixelType Isis::PixelTypeEnumeration (const QString & type) inline
Returns PixelType enumeration given a string.
Parameters
type QString containing the name of pixel type. Acceptable values are UnsignedByte, SignedByte, UnsignedWord, SignedWord, UnsignedInteger, SignedInteger, Read, and Double (not case sensitive)
Returns
Isis::PixelType
References Double, None, Real, SignedByte, SignedInteger, SignedWord, UnsignedByte, UnsignedInteger, and UnsignedWord.
Referenced by Isis::CubeIoHandler::CubeIoHandler().
PixelTypeName()
QString Isis::PixelTypeName (Isis::PixelType pixelType) inline
Returns string name of PixelType enumeration entered as input parameter.
Parameters
pixelType PixelType enumeration
Returns
string Name of PixelType
References Double, None, Real, SignedByte, SignedInteger, SignedWord, UnsignedByte, UnsignedInteger, and UnsignedWord.
Referenced by Isis::Cube::create(), Isis::ProcessImport::SetAttributes(), Isis::ProcessImport::SetPixelType(), Isis::CubeAttributeOutput::setPixelType(), and Isis::ProcessImport::SetSuffixPixelType().
pvlContainerToJSON()
nlohmann::json Isis::pvlContainerToJSON (PvlContainer & container)
Convert the contents of a PvlContainer to a JSON object.
Any comments in the container will be stored in "Comment". Comments associated with keywords will be stored inside their json object. If a keyword is repeated in the container, then the instances will be packed into an array in the order that they occur.
This function is used by the PvlGroup, PvlObject, and Pvl conversion functions; see their documentation for examples.
Parameters
container The container to convert
Returns
json The contents of the container as a JSON object
References Isis::PvlContainer::begin(), Isis::PvlContainer::comment(), Isis::PvlContainer::comments(), Isis::PvlContainer::end(), and pvlKeywordToJSON().
Referenced by pvlGroupToJSON(), and pvlObjectToJSON().
pvlGroupToJSON()
nlohmann::json Isis::pvlGroupToJSON (PvlGroup & group)
Convert the contents of a PvlGroup to a JSON object.
Any comments in the group will be stored in "Comment". Comments associated with keywords will be stored inside their json object.
A simple example group
PvlGroup:
Group = TestGroup
  TestKey1 = A
  TestKey2 = 1
End_Group
JSON:
{"TestKey1":{"Value":"A"},
 "TestKey2":{"Value":"1"}}
If a keyword is repeated in the group, then the instances will be packed into an array in the order that they occur.
An example group with repeated keywords
PvlGroup:
Group = TestGroup
  TestKey1 = A
  TestKey2 = 1
  TestKey2 = 2
End_Group
JSON:
{"TestKey1":{"Value":"A"},
 "TestKey2":[{"Value":"1"},
             {"Value":"2"}]}
Parameters
group The group to convert
Returns
json The contents of the group as a JSON object
References pvlContainerToJSON().
Referenced by pvlObjectToJSON().
pvlKeywordToJSON()
nlohmann::json Isis::pvlKeywordToJSON (PvlKeyword & keyword)
Convert the contents of a PvlKeyword to a JSON object.
All values from the keyword will be stored in "Value", all units will be stored in "Units", and all comments will be stored in "Comment".
How a keyword with only a value is converted
PvlKeyword:
ExposureDuration = 10
JSON:
{"Value":"10"}
How single values, units, and comments are converted
PvlKeyword:
# The exposure duration of the image
ExposureDuration = 10 <ms>
JSON:
{"Comment":"# The exposure duration of the image",
 "Units":"ms",
 "Value":"10"}
How multiple values, units, and comments are converted
PvlKeyword:
# First comment
# Second comment
TestKey2 = ("This keyword has multiple comments" <first unit>,
            "It also has multiple values",
            "It even has values with and without units" <third unit>)
JSON:
{"Comment":["# First comment",
            "# Second comment"],
 "Units":["first unit",
          "",
          "third unit"],
 "Value":["This keyword has multiple comments",
          "It also has multiple values",
          "It even has values with and without units"]}
Parameters
keyword The keyword to convert
Returns
json The contents of the keyword as a JSON object
References Isis::PvlKeyword::comment(), Isis::PvlKeyword::comments(), Isis::PvlKeyword::size(), and Isis::PvlKeyword::unit().
Referenced by pvlContainerToJSON().
pvlObjectToJSON()
nlohmann::json Isis::pvlObjectToJSON (PvlObject & object)
Convert the contents of a PvlObject to a JSON object.
Any comments in the base object will be stored in "Comment". Comments associated with keywords, groups, or nested objects will be stored inside their associated JSON object.
An example demonstrating how nested objects and groups are converted
PvlObject:
Object = TestObject2
  TestKey3 = "hello world"
  Object = TestObject1
    TestKey1 = A
    TestKey2 = 1
  End_Object
  Group = TestGroup
    TestKey3 = "hello world"
  End_Group
End_Object
JSON:
{"TestGroup":{"TestKey3":{"Value":"hello world"}},
 "TestKey3":{"Value":"hello world"},
 "TestObject1":{"TestKey1":{"Value":"A"},
                "TestKey2":{"Value":"1"}}}
If there are keywords, groups, and/or nested objects with the same name at the same level in the object, then they will be stored in an array starting with the keywords, followed by the groups, and then finally the objects. Within each subset, the repeated elements will be ordered the same as they occur in the object.
An example with repeated element names at the same level
PvlObject:
Object = TestObject2
  TestKey3  = "hello world"
  TestGroup = Q
  Object = TestObject1
    TestKey1 = A
    TestKey2 = 1
  End_Object
  Object = TestGroup
    TestKey2 = 1
  End_Object
  Group = TestGroup
    TestKey3 = "hello world"
  End_Group
End_Object
JSON:
{"TestGroup":[{"Value":"Q"},
              {"TestKey3":{"Value":"hello world"}},
              {"TestKey2":{"Value":"1"}}],
 "TestKey3":{"Value":"hello world"},
 "TestObject1":{"TestKey1":{"Value":"A"},
                "TestKey2":{"Value":"1"}}}
Parameters
object The object to convert
Returns
json The contents of the object as a JSON object
References pvlContainerToJSON(), and pvlGroupToJSON().
Referenced by fitsToJson(), and pvlToJSON().
pvlToJSON() [1/2]
nlohmann::json Isis::pvlToJSON (Pvl & pvl)
Convert the contents of a Pvl to a JSON object.
Any comments in the root of the Pvl will be stored in "Comment". Comments associated with keywords, groups, or objects will be stored inside their associated JSON object. If there are keywords, groups, and/or objects with the same name at the same level in the Pvl, then they will be stored in an array starting with the keywords, followed by the groups, and then finally the objects. Within each subset, the repeated elements will be ordered the same as they occur in the object.
Parameters
pvl The Pvl to convert
Returns
json The contents of the Pvl as a JSON object
References pvlObjectToJSON().
pvlToJSON() [2/2]
nlohmann::json Isis::pvlToJSON (QString pvlFile)
Converts an PVL file to a json object.
Parameters
pvlFile Path to an PVL file.
Returns
json The pvl file converted to a json object.
References _FILEINFO_, and Isis::Pvl::read().
rebin()
HiVector Isis::rebin (const HiVector & v, int n) inline
Rebins a vector to a different size.
This function can rebin to both larger and smaller sizes. It fits the data to a cubic spline and then computes the value at the rebin pixel index. One advantage to this approach is that on input, special pixels are ignored - on output there will never be special pixels unless there are not enough points to conpute the cubic spline on which case this function throws an exception.
Parameters
v Input vector to rebin
n Size of the new output vector
Returns
HiVector
History:
2008-11-05 Jeannie Walldren Replaced references to DataInterp class with NumericalApproximation.
References Isis::NumericalApproximation::AddData(), Isis::NumericalApproximation::CubicNatural, Isis::NumericalApproximation::Evaluate(), IsSpecial(), and Isis::NumericalApproximation::NearestEndpoint.
RemoveHiBlobs()
void Isis::RemoveHiBlobs (Pvl & label) inline
Deletes HiRISE specific BLOBS from cube file.
Ths function removes only the HiRISE specific
Parameters
label Input label associated with file from which to remove the HiRISE blobs
References Isis::PvlObject::deleteObject(), Isis::PvlContainer::isNamed(), Isis::PvlObject::object(), and Isis::PvlObject::objects().
Round()
int Isis::Round (double a)
Returns the result of rounding the input a to the closest integer.
Parameters
a Inut double
Returns
the int result of rounding a to the closest whole number
Referenced by BitwiseAndOperator(), BitwiseOrOperator(), and ModulusOperator().
sanitize()
void Isis::sanitize (std::string & input)
Referenced by stateAsJson().
SecantOperator()
double Isis::SecantOperator (double a)
Returns the secant of the input a.
Parameters
a Input double
Returns
the double result of the secant of a
Referenced by Isis::Calculator::Secant().
setStringAttribute()
void Isis::setStringAttribute (int locationId, QString locationName, QString attributeName, QString attributeValue)
SizeOf()
int Isis::SizeOf (Isis::PixelType pixelType) inline
Returns the number of bytes of the specified PixelType.
Parameters
pixelType PixelType enumeration
Returns
int Size of pixel type byte
References Double, None, Real, SignedByte, SignedInteger, SignedWord, UnsignedByte, UnsignedInteger, and UnsignedWord.
Referenced by Isis::Buffer::Allocate(), Isis::Buffer::Copy(), Isis::Cube::create(), Isis::CubeBsqHandler::CubeBsqHandler(), Isis::CubeTileHandler::CubeTileHandler(), Isis::CubeIoHandler::getBytesPerChunk(), Isis::JP2Importer::JP2Importer(), Isis::ProcessExportPds::LineBytes(), Isis::ProcessImport::ProcessBil(), Isis::ProcessImport::ProcessBip(), Isis::ProcessImport::ProcessBsq(), Isis::ProcessImport::ProcessJp2(), and Isis::ProcessImportFits::setProcessFileStructure().
SkipModule()
bool Isis::SkipModule (const DbProfile & prof) inline
Checks profile flag to skip the current Module.
This function looks for the keyword Debug::SkipModule and checks its value. True is returned if the value is TRUE (case insensentive).
Parameters
prof Module profile from config file
Returns
bool True if the value of the Debug::SkipModule keyword is TRUE, otherwise it returns false for all other values.
References IsTrueValue().
stateAsJson()
json Isis::stateAsJson (std::string modelState)
References sanitize().
StringToPixel()
double Isis::StringToPixel (const QString & str) inline
Takes the name of the pixel type as a string and returns a double pixel value.
Parameters
str The name of the pixel type
Returns
double Pixel value
References _FILEINFO_, His, Hrs, Lis, Lrs, Null, toDouble(), and Isis::IException::User.
Referenced by Isis::Average::operator()().
SubtractOperator()
double Isis::SubtractOperator (double a, double b)
Returns the result of subtracting b from a.
Parameters
a Input subtractee
b Input subtractor
Returns
double result of a-b
Referenced by Isis::Calculator::Subtract().
TestPixel() [1/2]
float Isis::TestPixel (const double t) inline
Converts double to float with special pixel translations and care for overflows (underflows are assumed to cast to 0!)
Parameters
t Double pixel value to be converted to a float
Returns
float The float pixel value
References HIGH_INSTR_SAT4, HIGH_INSTR_SAT8, HIGH_REPR_SAT4, HIGH_REPR_SAT8, LOW_INSTR_SAT4, LOW_INSTR_SAT8, LOW_REPR_SAT4, LOW_REPR_SAT8, NULL4, NULL8, VALID_MAX4, and VALID_MIN4.
TestPixel() [2/2]
double Isis::TestPixel (const float t) inline
Converts float pixels to double pixels with special pixel translations.
Parameters
t Float pixel value to be converted to a double
Returns
double The double pixel value
References HIGH_INSTR_SAT4, HIGH_INSTR_SAT8, HIGH_REPR_SAT4, HIGH_REPR_SAT8, LOW_INSTR_SAT4, LOW_INSTR_SAT8, LOW_REPR_SAT4, LOW_REPR_SAT8, NULL4, NULL8, VALID_MAX4, and VALID_MIN4.
toBigInt()
BigInt Isis::toBigInt (const QString & string)
Global function to convert from a string to a "big" integer.
This function will throw an IException if the conversion is unsuccessful.
Parameters
string QString to be converted to a big integer.
Returns
The BigInt equivalent to the string
References _FILEINFO_.
Referenced by Isis::PvlFormatPds::formatBinary(), Isis::PvlFormatPds::formatHex(), Isis::PvlKeyword::operator Isis::BigInt(), and Isis::Statistics::readStatistics().
toBool()
bool Isis::toBool (const QString & string)
Global function to convert from a string to a boolean.
Known string values include anything that remotely looks like a true or false. For example, the following strings will return true: "true", "t", "yes", "y", "on", "1".
This function will throw an IException if the conversion is unsuccessful.
Parameters
string QString to be converted to a boolean.
Returns
The boolean equivalent to the string
References _FILEINFO_.
Referenced by Isis::MosaicAreaTool::fromPvl(), Isis::MosaicControlNetTool::fromPvl(), Isis::MosaicFindTool::fromPvl(), Isis::MosaicGridTool::fromPvl(), Isis::ImageFileListWidget::fromPvl(), IsisAml::GetBoolean(), Isis::ImageTreeWidget::ImageTreeWidget(), Isis::Strategy::importGeometry(), Isis::Strategy::initProgress(), Isis::OsirisRexTagcamsDistortionMap::OsirisRexTagcamsDistortionMap(), Isis::BundleSettings::readBundleSettings(), Isis::BundleResults::readGenStatsValues(), Isis::BundleObservationSolveSettings::readSolveSettings(), Isis::Statistics::readStatistics(), Isis::OsirisRexOcamsDistortionMap::SetDistortion(), and Isis::Strategy::Strategy().
toDouble()
double Isis::toDouble (const QString & string)
Global function to convert from a string to a double.
If the string begins with 16# and ends with #, the function will assume it is hexadecimal and attempt to convert to a double. This function is preferred over the QString::toDouble() method since this function will throw an IException if the conversion is unsuccessful.
Parameters
string QString to be converted to a double. This may be a hexadecimal string.
Returns
The double equivalent to the string
References _FILEINFO_.
Referenced by Isis::Latitude::add(), Isis::ControlNetDiff::addTolerances(), Isis::MosaicControlNetToolMovementConfigDialog::applySettings(), Isis::BundleObservationSolveSettings::BundleObservationSolveSettings(), Isis::FeatureNomenclature::Feature::centerLatitude(), Isis::FeatureNomenclature::Feature::centerLongitude(), Isis::ClipperNacRollingShutterCamera::ClipperNacRollingShutterCamera(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::ControlNetDiff::compare(), Isis::ControlMeasureLogData::ControlMeasureLogData(), Isis::ControlPointV0001::ControlPointV0001(), Isis::ControlPointV0002::ControlPointV0002(), Isis::ControlPointV0003::ControlPointV0003(), Isis::CSVReader::convert(), Isis::InfixToPostfix::convert(), Isis::ShapeModelFactory::create(), Isis::DawnVirCamera::DawnVirCamera(), Isis::FeatureNomenclature::Feature::diameter(), Isis::FeatureNomenclature::Feature::easternLongitude(), Isis::PlotWindow::fillTable(), Isis::PvlFormatPds::formatReal(), Isis::MosaicSceneWidget::fromPvl(), Isis::MosaicControlNetTool::fromPvl(), Isis::MosaicGridTool::fromPvl(), Isis::GroundGrid::GroundGrid(), Isis::Camera::GroundRange(), Isis::IdealCamera::IdealCamera(), Isis::Strategy::importGeometry(), Isis::Equalization::importStatistics(), Isis::VimsGroundMap::Init(), Isis::VimsSkyMap::Init(), Isis::InlineCalculator::isScalar(), Isis::Latitude::Latitude(), Isis::Stretch::Load(), Isis::SpicePosition::LoadCache(), Isis::SpiceRotation::LoadCache(), Isis::SpiceRotation::loadPCFromTable(), Isis::LroWideAngleCamera::LroWideAngleCamera(), Isis::CubeAttributeOutput::maximum(), Isis::CubeAttributeOutput::minimum(), Isis::FeatureNomenclature::Feature::northernLatitude(), Isis::ObliqueCylindrical::ObliqueCylindrical(), Isis::PvlKeyword::operator double(), Isis::Target::radiiGroup(), Isis::StatCumProbDistDynCalc::readStatistics(), Isis::Statistics::readStatistics(), Isis::Spice::readStoredValue(), Isis::ReseauDistortionMap::ReseauDistortionMap(), Isis::MosaicSceneWorkOrder::restoreZPositions(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::InlineCalculator::scalar(), Isis::RadarSlantRangeMap::SetCoefficients(), Isis::MinnaertEmpirical::SetPhotoKList(), Isis::LunarLambertEmpirical::SetPhotoLList(), Isis::LunarLambertEmpirical::SetPhotoPhaseCurveList(), Isis::MinnaertEmpirical::SetPhotoPhaseCurveList(), Isis::ProcessImportFits::setProcessFileStructure(), Isis::FeatureNomenclature::Feature::southernLatitude(), Isis::SpectralDefinition1D::SpectralDefinition1D(), Isis::ProcessExportPds4::StandardAllMapping(), StringToPixel(), Isis::TgoCassisCamera::TgoCassisCamera(), ToDouble(), Isis::SubArea::UpdateLabel(), Isis::PvlKeyword::validateKeyword(), Isis::FeatureNomenclature::Feature::westernLongitude(), and Isis::ZeroBufferFit::ZeroBufferFit().
ToDouble()
template<typename T > double Isis::ToDouble (const T & value)
Helper function to convert values to doubles.
Parameters
T Type of value to convert
value Value to convert
Returns
double Converted value
References toDouble().
Referenced by Isis::LoadCSV::load(), and Isis::ZeroBufferFit::ZeroBufferFit().
toInt()
int Isis::toInt (const QString & string)
Global function to convert from a string to an integer.
This function is preferred over the QString::toInt() method since this function will throw an IException if the conversion is unsuccessful.
Parameters
string QString to be converted to an integer.
Returns
The integer equivalent to the string
References _FILEINFO_.
Referenced by Isis::PvlFormat::accuracy(), Isis::MosaicSceneWidget::addImages(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::MosaicControlNetToolMovementConfigDialog::applySettings(), Isis::CubePlotCurveConfigureDialog::applySettingsToCurve(), Isis::CubeAttributeInput::bands(), Isis::Database::configureAccess(), Isis::ControlNetFilter::CubeNumPointsFilter(), Isis::ImageListActionWorkOrder::execute(), fitsToJson(), Isis::PvlFormatPds::formatHex(), Isis::MosaicControlNetTool::fromPvl(), Isis::MosaicGridTool::fromPvl(), Isis::Color::fromRGBAString(), Isis::LoadCSV::load(), Isis::ImportPdsTable::load(), Isis::SpiceRotation::LoadCache(), Isis::NewHorizonsLeisaCamera::NewHorizonsLeisaCamera(), Isis::NewHorizonsMvicFrameCamera::NewHorizonsMvicFrameCamera(), Isis::PvlKeyword::operator int(), Isis::ControlNetFilter::PointMeasuresFilter(), Isis::ControlNetFilter::PointNumMeasuresEditLockFilter(), Isis::BundleResults::readGenStatsValues(), Isis::Spice::readStoredValue(), Isis::MosaicControlNetToolMovementConfigDialog::refreshWidgetStates(), Isis::UserInterface::SaveHistory(), Isis::RubberBandComboBox::selectionChanged(), Isis::UserInterface::SetBatchList(), Isis::ProcessMosaic::SetInputCube(), Isis::ProcessImportFits::setProcessFileStructure(), Isis::Cube::setVirtualBands(), Isis::Target::Target(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::ThemisIrCamera::ThemisIrCamera(), Isis::ThemisVisCamera::ThemisVisCamera(), ToInteger(), Isis::SpatialPlotTool::updateTool(), Isis::SpectralPlotTool::updateTool(), Isis::PvlKeyword::validateKeyword(), and Isis::ZeroBufferFit::ZeroBufferFit().
ToInteger()
template<typename T > int Isis::ToInteger (const T & value)
Helper function to convert values to Integers.
Parameters
T Type of value to convert
value Value to convert
Returns
int Converted value
References toInt().
Referenced by Isis::LoadCSV::load(), and Isis::ZeroBufferFit::ZeroBufferFit().
toKeywordType()
KeywordType Isis::toKeywordType (const QString type) inline
Convert a string representing a type of keyword to the corresponding enumeration.
All white space, quotes, underscores, and dashes will be removed from the input string.
Parameters
type The string to be converted.
Returns
The corresponding KeywordType enum.
References BinaryKeyword, BoolKeyword, EnumKeyword, HexKeyword, IntegerKeyword, NoTypeKeyword, OctalKeyword, RealKeyword, and StringKeyword.
Referenced by Isis::PvlFormat::type().
toString() [1/8]
QString Isis::toString (bool boolToConvert)
Global function to convert a boolean to a string.
The resulting string will be "Yes" (true) or "No" (false).
Parameters
boolToConvert Boolean value to be converted to a QString.
Returns
string Converted QString (Yes or No).
Referenced by Isis::LinearAlgebra::add(), Isis::LroWideAngleCameraFocalPlaneMap::addFilter(), Isis::Gruen::AlgorithmStatistics(), Isis::ApolloMetricCamera::ApolloMetricCamera(), Isis::ApolloPanoramicCamera::ApolloPanoramicCamera(), Isis::Application::Application(), Isis::Equalization::applyCorrection(), Isis::BundleControlPoint::applyParameterCorrections(), Isis::Strategy::applyToIntersectedGeometry(), Isis::Message::ArraySubscriptNotInRange(), Isis::Cube::attachSpiceFromIsd(), Isis::CubeAttributeInput::bands(), Isis::Camera::BasicMapping(), Isis::Camera::basicRingMapping(), Isis::FunctionTools::brentsRootFinder(), Isis::IsisBundleObservation::bundleOutputCSV(), Isis::CsmBundleObservation::bundleOutputCSV(), Isis::IsisBundleObservation::bundleOutputString(), Isis::CsmBundleObservation::bundleOutputString(), Isis::SpiceRotation::CacheLabel(), Isis::Equalization::calculateBandStatistics(), Isis::Equalization::calculateOverlapStatistics(), Isis::Process::CalculateStatistics(), Isis::HiEqualization::calculateStatistics(), Isis::PushFrameCameraCcdLayout::ccdLines(), Isis::PushFrameCameraCcdLayout::ccdSamples(), CcdToFilter(), Isis::Chandrayaan1M3Camera::Chandrayaan1M3Camera(), Isis::LightTimeCorrectionState::checkAberrationCorrection(), Isis::QtExporter::checkDataSize(), Isis::XmlToPvlTranslationManager::checkDependencies(), Isis::LightTimeCorrectionState::checkLightTimeToSurfaceCorrect(), Isis::LightTimeCorrectionState::checkObserverTargetSwap(), Isis::ProcessImport::CheckPixelRange(), cholmodErrorHandler(), Isis::ClipperPushBroomCamera::ClipperPushBroomCamera(), Isis::LinearAlgebra::column(), Isis::ControlNetDiff::compare(), Isis::CsmBundleObservation::computePoint3DPartials(), Isis::BundleResults::computeSigma0(), Isis::CameraStatistics::constructKeyword(), Isis::ControlPointList::ControlPointId(), Isis::ControlPointList::ControlPointList(), Isis::ControlPointV0003::ControlPointV0003(), Isis::BundleSettings::convergenceCriteriaToString(), Isis::TiffImporter::convertProjection(), Isis::SurfacePoint::coordinateTypeToString(), Isis::Control::copyToNewProjectRoot(), CpmmToCcd(), Isis::Cube::create(), Isis::ShapeModelFactory::create(), Isis::ProjectionFactory::CreateForCube(), IsisAml::CreatePVL(), Isis::CrismCamera::CrismCamera(), Isis::LinearAlgebra::crossProduct(), Isis::BundleObservationSolveSettings::csmSolveOptionToString(), Isis::BundleObservationSolveSettings::csmSolveSetToString(), Isis::BundleObservationSolveSettings::csmSolveTypeToString(), Isis::CTXCamera::CTXCamera(), Isis::ControlNetFilter::CubeDistanceFilter(), Isis::ControlMeasureLogData::DataTypeToName(), Isis::DawnFcCamera::DawnFcCamera(), Isis::DawnVirCamera::DawnVirCamera(), Isis::iTime::DayOfYearString(), Isis::iTime::DayString(), Isis::PolynomialUnivariate::DerivativeCoef(), Isis::LinearAlgebra::determinant(), Isis::SpiceRotation::DPckPolynomial(), Isis::SpicePosition::DPolynomial(), Isis::SpiceRotation::DPolynomial(), Isis::ControlNetVitals::emitHistoryEntry(), Isis::Equirectangular::Equirectangular(), Isis::Equalization::errorCheck(), Isis::HiEqualization::errorCheck(), Isis::iTime::EtString(), Isis::BasisFunction::Evaluate(), Isis::ExportPdsTable::exportTable(), Isis::ProcessExportPds::ExportTable(), Isis::Chip::Extract(), Isis::ProcessExportPds4::fileAreaObservational(), Isis::SerialNumberList::fileName(), Isis::PlotWindow::fillTable(), Isis::InterestOperator::FindCnetRef(), Isis::ProcessExportPds::FixedJP2ImageRoot(), Isis::BundleControlPoint::formatBundleLatitudinalOutputDetailString(), Isis::BundleControlPoint::formatBundleOutputDetailString(), Isis::BundleTargetBody::formatBundleOutputString(), Isis::BundleControlPoint::formatBundleRectangularOutputDetailString(), Isis::SpiceRotation::FrameTrace(), Isis::OriginalXmlLabel::fromBlob(), Isis::ControlNetStatistics::GenerateControlNetStats(), Isis::PvlFlatMap::get(), Isis::CubeViewport::getAllWhatsThisInfo(), Isis::Spice::getClockTime(), Isis::ImportPdsTable::getColumnName(), Isis::SurfacePoint::GetCoord(), Isis::LeastSquares::GetExpected(), Isis::PushFrameCameraCcdLayout::getFrameInfo(), Isis::EmbreeTargetShape::getHitInformation(), Isis::LeastSquares::GetInput(), Isis::ControlPoint::GetMeasure(), Isis::Equalization::getResults(), Isis::SurfacePoint::GetSigma(), Isis::SurfacePoint::GetSigmaDistance(), Isis::SqlRecord::getValue(), Isis::SurfacePoint::GetWeight(), Isis::ControlNet::GraphToString(), Isis::HayabusaAmicaCamera::HayabusaAmicaCamera(), Isis::HayabusaNirsCamera::HayabusaNirsCamera(), Isis::HiresCamera::HiresCamera(), Isis::iTime::HourString(), Isis::HrscCamera::HrscCamera(), Isis::Hyb2OncCamera::Hyb2OncCamera(), Isis::LinearAlgebra::identity(), Isis::Strategy::importGeometry(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::LinearAlgebra::innerProduct(), Isis::BundleObservationSolveSettings::instrumentPointingSolveOptionToString(), Isis::BundleObservationSolveSettings::instrumentPositionSolveOptionToString(), Isis::IssNACamera::IssNACamera(), Isis::IssWACamera::IssWACamera(), Isis::JunoCamera::JunoCamera(), Isis::KaguyaMiCamera::KaguyaMiCamera(), Isis::KaguyaTcCamera::KaguyaTcCamera(), Isis::KaguyaTcCameraDistortionMap::KaguyaTcCameraDistortionMap(), Isis::LambertConformal::LambertConformal(), Isis::Equalization::loadInputs(), Isis::Equalization::loadOutputs(), Isis::SpiceRotation::loadPCFromSpice(), Isis::TProjection::LocalRadius(), Isis::ControlNetValidMeasure::LocationString(), Isis::LroNarrowAngleCamera::LroNarrowAngleCamera(), Isis::LroWideAngleCameraDistortionMap::LroWideAngleCameraDistortionMap(), Isis::LwirCamera::LwirCamera(), Isis::ControlNetDiff::makeKeyword(), Isis::Planar::Mapping(), Isis::RingCylindrical::Mapping(), Isis::MarciCamera::MarciCamera(), Isis::MarciDistortionMap::MarciDistortionMap(), Isis::Mariner10Camera::Mariner10Camera(), Isis::MdisCamera::MdisCamera(), Isis::ControlMeasure::MeasureTypeToString(), Isis::Mercator::Mercator(), Isis::MexHrscSrcCamera::MexHrscSrcCamera(), Isis::iTime::MinuteString(), Isis::Message::MissingDelimiter(), Isis::BundleAdjust::modelState(), Isis::MaximumLikelihoodWFunctions::modelToString(), Isis::Mollweide::Mollweide(), Isis::iTime::MonthString(), Isis::MsiCamera::MsiCamera(), Isis::LinearAlgebra::multiply(), Isis::NewHorizonsLorriCamera::NewHorizonsLorriCamera(), Isis::NewHorizonsMvicTdiCamera::NewHorizonsMvicTdiCamera(), Isis::NirCamera::NirCamera(), Isis::ObliqueCylindrical::ObliqueCylindrical(), Isis::ObservationNumberList::observationNumber(), Isis::SerialNumberList::observationNumber(), Isis::ObservationNumberList::observationNumberMapIndex(), Isis::BundleSettings::observationSolveSettings(), Isis::PvlSequence::operator+=(), Isis::Table::operator+=(), operator<<(), Isis::TableField::operator=(), Isis::Orthographic::Orthographic(), Isis::OsirisRexOcamsCamera::OsirisRexOcamsCamera(), Isis::OsirisRexTagcamsCamera::OsirisRexTagcamsCamera(), Isis::OsirisRexTagcamsDistortionMap::OsirisRexTagcamsDistortionMap(), Isis::LinearAlgebra::outerProduct(), Isis::BundleSolutionInfo::outputHeader(), Isis::BundleSolutionInfo::outputImagesCSV(), Isis::ProcessExportPds::OutputLabel(), Isis::ProcessMosaic::OverlayToString(), Isis::LatLonGridTool::paintViewport(), Isis::IsisBundleObservation::parameterList(), Isis::InterestOperator::Parse(), Isis::XmlToPvlTranslationManager::parseFile(), Isis::SurfacePoint::Partial(), Isis::Cube::physicalBand(), Isis::TrackingTable::pixelToFileName(), Isis::TrackingTable::pixelToSN(), Isis::Planar::Planar(), Isis::GridPolygonSeeder::PluginParameters(), Isis::LimitPolygonSeeder::PluginParameters(), Isis::PolygonSeeder::PluginParameters(), Isis::StripPolygonSeeder::PluginParameters(), Isis::PointPerspective::PointPerspective(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::PolarStereographic::PolarStereographic(), Isis::ProcessImport::ProcessBil(), Isis::ProcessImport::ProcessBip(), Isis::ProcessImport::ProcessBsq(), Isis::LinearAlgebra::project(), Isis::Project::Project(), IsisAml::PutDouble(), IsisAml::PutInteger(), Isis::TableField::pvlGroup(), Isis::Target::radiiGroup(), Isis::EmbreeTargetShape::readDSK(), Isis::OriginalXmlLabel::readFromXmlFile(), Isis::MosaicControlNetToolMovementConfigDialog::readSettings(), Isis::ControlPointList::RegisterStatistics(), Isis::AutoReg::RegistrationStatistics(), Isis::RingCylindrical::RingCylindrical(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::ProcessMapMosaic::RingsSetOutputCube(), Isis::Robinson::Robinson(), Isis::RosettaOsirisCamera::RosettaOsirisCamera(), Isis::RosettaVirtisCamera::RosettaVirtisCamera(), Isis::LinearAlgebra::rotate(), Isis::LinearAlgebra::row(), Isis::ProgramLauncher::RunIsisProgram(), Isis::ProgramLauncher::RunSystemCommand(), Isis::Stretch::Save(), Isis::StatCumProbDistDynCalc::save(), Isis::Statistics::save(), Isis::BundleResults::save(), Isis::BundleSettings::save(), Isis::BundleObservationSolveSettings::save(), Isis::MosaicSceneWidget::save(), Isis::ControlMeasureEditWidget::saveChips(), Isis::ControlPointEdit::saveChips(), Isis::SerialNumberList::serialNumber(), Isis::SerialNumberList::SerialNumberList(), Isis::Latitude::setAngle(), Isis::AtmosModel::SetAtmosHnorm(), Isis::JP2Exporter::setBuffer(), Isis::TiffExporter::setBuffer(), Isis::BasisFunction::SetCoefficients(), Isis::LinearAlgebra::setColumn(), Isis::ProcessImport::SetDataHeaderBytes(), Isis::ProcessImport::SetDataPrefixBytes(), Isis::ProcessImport::SetDataSuffixBytes(), Isis::ProcessImport::SetDataTrailerBytes(), Isis::ProcessImport::SetDimensions(), Isis::KaguyaMiCameraDistortionMap::SetDistortion(), Isis::LoHighDistortionMap::SetDistortion(), Isis::LoMediumDistortionMap::SetDistortion(), Isis::LroNarrowAngleDistortionMap::SetDistortion(), Isis::TaylorCameraDistortionMap::SetDistortion(), Isis::CameraDistortionMap::SetDistortion(), Isis::JunoDistortionMap::SetDistortion(), Isis::OsirisRexOcamsDistortionMap::SetDistortion(), Isis::OsirisRexDistortionMap::SetDistortion(), Isis::ProcessImport::SetFileHeaderBytes(), Isis::ProcessImport::SetFileTrailerBytes(), Isis::Camera::SetFocalLength(), Isis::Pipeline::SetInputListFile(), Isis::LineManager::SetLine(), Isis::SurfacePoint::SetMatrix(), Isis::CubeAttributeOutput::setMaximum(), Isis::CubeAttributeOutput::setMinimum(), Isis::ProcessMapMosaic::SetOutputCube(), Isis::MinnaertEmpirical::SetPhotoPhaseList(), Isis::LunarLambertEmpirical::SetPhotoPhaseList(), Isis::Camera::SetPixelPitch(), Isis::ExportDescription::setPixelType(), Isis::Latitude::setPlanetographic(), Isis::Chip::SetReadInterpolator(), Isis::ControlPoint::SetRefMeasure(), Isis::Equalization::setResults(), Isis::LinearAlgebra::setRow(), Isis::BundleControlPoint::setSigmaWeightFromGlobals(), Isis::Chip::SetSize(), Isis::Projection::SetUpperLeftCorner(), Isis::Chip::SetValidRange(), Isis::Statistics::SetValidRange(), Isis::SimpleCylindrical::SimpleCylindrical(), Isis::Sinusoidal::Sinusoidal(), Isis::SerialNumberList::spacecraftInstrumentId(), Isis::SpiceRotation::SpiceRotation(), Isis::SsiCamera::SsiCamera(), Isis::ProcessExportPds4::StandardAllMapping(), Isis::ProcessExportPds::StandardAllMapping(), Isis::ProcessExportPds::StandardImageImage(), Isis::ProcessExportPds::StandardJP2Image(), Isis::PolygonSeeder::StandardTests(), Isis::ProcessMosaic::StartProcess(), Isis::Spice::storeValue(), Isis::ProcessExportPds::StreamJP2ImageRoot(), Isis::LinearAlgebra::subtract(), Isis::BundleSolutionInfo::surfacePointCoordName(), Isis::BundleTargetBody::targetRadiiOptionToString(), Isis::Stretch::Text(), Isis::TgoCassisCamera::TgoCassisCamera(), Isis::TgoCassisDistortionMap::TgoCassisDistortionMap(), Isis::TProjection::To180Domain(), Isis::TProjection::To360Domain(), Isis::LinearAlgebra::toAxisAngle(), Isis::Table::toBlob(), Isis::RingPlaneProjection::ToClockwise(), Isis::LinearAlgebra::toEulerAngles(), Isis::ControlMeasureLogData::ToKeyword(), Isis::LinearAlgebra::toMatrix(), Isis::TProjection::ToPlanetocentric(), Isis::TProjection::ToPlanetographic(), Isis::TProjection::ToPositiveEast(), Isis::TProjection::ToPositiveWest(), Isis::ControlNetVersioner::toPvl(), Isis::CameraStatistics::toPvl(), Isis::IException::toPvl(), Isis::ImageFileListWidget::toPvl(), Isis::MosaicAreaTool::toPvl(), Isis::MosaicControlNetTool::toPvl(), Isis::MosaicFindTool::toPvl(), Isis::MosaicGridTool::toPvl(), Isis::MosaicSceneWidget::toPvl(), Isis::MultivariateStatistics::toPvl(), Isis::OverlapStatistics::toPvl(), Isis::Statistics::toPvl(), Isis::LinearAlgebra::toQuaternion(), Isis::Distance::toString(), Isis::Angle::toString(), Isis::IException::toString(), toString(), ToString(), Isis::TableField::toString(), Isis::Table::toString(), Isis::TableRecord::toString(), Isis::TProjection::TProjection(), Isis::XmlToPvlTranslationManager::Translate(), Isis::ProcessExportPds4::translateBandBinSpectrumUniform(), Isis::ProcessImportPds::TranslatePdsProjection(), Isis::TransverseMercator::TransverseMercator(), Isis::ControlHealthMonitorWidget::update(), Isis::AutoReg::UpdatedTemplate(), Isis::AlphaCube::UpdateGroup(), Isis::SubArea::UpdateLabel(), Isis::CubeTileHandler::updateLabels(), Isis::Enlarge::UpdateOutputLabel(), Isis::Reduce::UpdateOutputLabel(), Isis::UvvisCamera::UvvisCamera(), Isis::StatCumProbDistDynCalc::validate(), Isis::ControlNetVitals::validate(), Isis::ControlNetValidMeasure::ValidatePvlDN(), Isis::ControlNetValidMeasure::ValidatePvlEmissionAngle(), Isis::ControlNetValidMeasure::ValidatePvlFromEdge(), Isis::ControlNetValidMeasure::ValidatePvlIncidenceAngle(), Isis::ControlNetValidMeasure::ValidatePvlResidualTolerances(), Isis::ControlNetValidMeasure::ValidatePvlResolution(), Isis::ControlNetValidMeasure::ValidatePvlShiftTolerances(), Isis::ControlNetValidMeasure::ValidStandardOptions(), Isis::StatCumProbDistDynCalc::value(), Isis::TriangularPlate::vertex(), Isis::ControlHealthMonitorWidget::viewImageAll(), Isis::ControlHealthMonitorWidget::viewImageFewMeasures(), Isis::ControlHealthMonitorWidget::viewImageHullTolerance(), Isis::ControlHealthMonitorWidget::viewPointAll(), Isis::ControlHealthMonitorWidget::viewPointConstrained(), Isis::ControlHealthMonitorWidget::viewPointEditLocked(), Isis::ControlHealthMonitorWidget::viewPointFewMeasures(), Isis::ControlHealthMonitorWidget::viewPointFixed(), Isis::ControlHealthMonitorWidget::viewPointFree(), Isis::ControlHealthMonitorWidget::viewPointIgnored(), Isis::VikingCamera::VikingCamera(), Isis::MaximumLikelihoodWFunctions::weightedResidualCutoff(), Isis::Blob::Write(), Isis::ControlNetVersioner::write(), Isis::iTime::YearString(), and Isis::Statistics::ZScore().
toString() [2/8]
QString Isis::toString (char charToConvert)
Global function to convert a character to a string.
The resulting string will be a string with length 1 which contains only the given ASCII character.
Parameters
charToConvert Character value to be converted to a QString.
Returns
string Converted QString.
toString() [3/8]
QString Isis::toString (const BigInt & intToConvert)
Global function to convert a big integer to a string.
Parameters
intToConvert Big integer value to be converted to a QString.
Returns
string Converted QString.
toString() [4/8]
QString Isis::toString (const int & intToConvert)
Global function to convert an integer to a string.
Parameters
intToConvert Integer value to be converted to a QString.
Returns
string Converted QString.
toString() [5/8]
QString Isis::toString (const LinearAlgebra::Vector & vector, int precision)
A global function to format LinearAlgebra::Vector as a QString with the given precision.
The string will be comma-separated entries encased by parentheses.
Parameters
vector The vector to be converted.
precision Number of significant figures to convert.
Returns
QString The string-formatted vector.
References toString().
ToString()
template<typename T > QString Isis::ToString (const T & value)
Helper function to convert values to strings.
Parameters
T Type of value to convert
value Value to convert
Returns
string Converted value
References toString().
Referenced by Isis::ZeroBufferFit::guess(), Isis::LoadCSV::load(), Isis::ZeroBufferFit::Normalize(), Isis::ZeroBufferFit::Solve(), Isis::Pixel::ToString(), and Isis::ZeroBufferFit::ZeroBufferFit().
toString() [6/8]
QString Isis::toString (const TNT::Array1D< SpiceDouble > & naifArray, int precision)
Formats any TNT array of SpiceDoubles as a string with given precision.
Valid inputs include NaifVector and NaifVertex. The array in the output string will be comma separated and enclosed in parentheses.
Parameters
tntArray TNT array to be formatted as a string.
precision Number of digits each value in the array will be stored with.
Returns
QString A string containing the array values in parentheses and comma separated.
References toString().
toString() [7/8]
QString Isis::toString (const unsigned int & intToConvert)
Global function to convert an unsigned integer to a string.
Parameters
intToConvert Unsigned integer value to be converted to a QString.
Returns
string Converted QString.
toString() [8/8]
QString Isis::toString (double doubleToConvert, int precision)
Global function to convert a double to a string with the given precision (significant figures).
The conversion is handled in the following manner: If (log10(num) < -3.0) it is presented in scientific notation If (log10(num) > 13.0) it is presented in scientific notation If (log10(num) >= -3 && log10(num) <= 13) it is presented in normal notation Trailing zeros are removed such that 5.000 is presented as 5.0
Parameters
doubleToConvert Double value to be converted to a QString.
precision Number of significant figures to convert.
Returns
string Converted QString.
validate() [1/2]
bool Isis::validate (const NaifTriangle & t)
Verifies that the given NaifTriangle is 3 x 3.
Parameters
t NaifTriangle to validate.
Returns
bool Indicates whether the given 2D array is 3 x 3.
validate() [2/2]
bool Isis::validate (const NaifVertex & v)
Verifies that the given NaifVector or NaifVertex is 3 dimensional.
Also acceptable: bool validate(const NaifVector &v).
Parameters
v Input can be a NaifVertex or NaifVector to validate.
Returns
bool Indicates whether the given array is size 3.
Referenced by Isis::Intercept::isValid(), Isis::NaifDskPlateModel::plateIdOfIntercept(), and Isis::BundleSettings::setValidateNetwork().
ValidCount()
int Isis::ValidCount (const HiVector & v) inline
Counts number of valid pixels in vector.
Parameters
v Vector to inspect
Returns
int Number valid pixels in vector
References IsSpecial().
xmlToJson() [1/2]
nlohmann::json Isis::xmlToJson (QDomDocument & doc)
Converts an XML document stored in a QDomDocument into a JSON object.
Parameters
doc A QDomDocument with an XML file loaded into it.
Returns
json The XMl file converted to a json object.
References convertXmlToJson().
xmlToJson() [2/2]
nlohmann::json Isis::xmlToJson (QString xmlFile)
Converts an XML file to a json object.
Please see other functions for details about how XML elements are converted to corresponding json elements.
Parameters
xmlFile Path to an XML file.
Returns
json The xml file converted to a json object.
References _FILEINFO_, and Isis::IException::Io.
Variable Documentation
AllMatchOrOne
const int Isis::AllMatchOrOne = 128
Referenced by Isis::Process::CheckRequirements(), and Isis::ProcessByBrick::SetInputCube().
BandMatchOrOne
const int Isis::BandMatchOrOne = 32
Referenced by Isis::Process::CheckRequirements(), Isis::ProcessByLine::SetInputCube(), and Isis::ProcessBySample::SetInputCube().
DEG2RAD
const double Isis::DEG2RAD = 0.017453292519943295769237
Multiplier for converting from degrees to radians.
Referenced by Isis::BundleControlPoint::formatBundleLatitudinalOutputDetailString(), Isis::EquatorialCylindricalShape::intersectSurface(), Isis::Camera::ObliqueDetectorResolution(), Isis::BundleSolutionInfo::outputPointsCSV(), Isis::Planar::Planar(), Isis::RingCylindrical::RingCylindrical(), Isis::Robinson::Robinson(), Isis::RingPlaneProjection::Scale(), Isis::Angle::setAngle(), Isis::SpiceRotation::setEphemerisTimePckPolyFunction(), Isis::Robinson::SetGround(), Isis::Planar::SetGround(), Isis::RingCylindrical::SetGround(), Isis::CSMCamera::SetRightAscensionDeclination(), and Isis::Sensor::SetRightAscensionDeclination().
globalFactory
geos::geom::GeometryFactory::Ptr Isis::globalFactory = geos::geom::GeometryFactory::create() static
Referenced by Isis::PolygonTools::CopyMultiPolygon(), Isis::ImagePolygon::Create(), Isis::PolygonTools::Despike(), Isis::ImageOverlapSet::FindAllOverlaps(), Isis::PolygonTools::FixSeam(), Isis::RubberBandTool::geometry(), Isis::ImagePolygon::ImagePolygon(), Isis::PolygonTools::LatLonToSampleLine(), Isis::PolygonTools::LatLonToXY(), Isis::PolygonTools::MakeMultiPolygon(), Isis::ProcessGroundPolygons::Rasterize(), Isis::PolygonTools::ReducePrecision(), Isis::HistogramTool::refreshPlot(), Isis::LimitPolygonSeeder::Seed(), Isis::StripPolygonSeeder::Seed(), Isis::ProcessPolygons::SetStatCubes(), Isis::PolygonTools::SplitPolygonOn360(), Isis::PolygonTools::To180(), Isis::ProcessGroundPolygons::Vectorize(), and Isis::PolygonTools::XYToLatLon().
HALFPI
const double Isis::HALFPI = 1.57079632679489661923
The mathematical constant PI/2.
Referenced by Isis::Camera::ObliqueDetectorResolution(), Isis::TProjection::phi2Compute(), Isis::PolarStereographic::PolarStereographic(), Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::LunarAzimuthalEqualArea::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Mollweide::SetCoordinate(), Isis::ObliqueCylindrical::SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), Isis::TransverseMercator::SetCoordinate(), Isis::SpiceRotation::setEphemerisTimePckPolyFunction(), Isis::LambertConformal::SetGround(), Isis::LunarAzimuthalEqualArea::SetGround(), Isis::TransverseMercator::SetGround(), and Isis::TProjection::tCompute().
HIGH_INSTR_SAT1
const unsigned char Isis::HIGH_INSTR_SAT1 = ((unsigned char) 255)
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), Isis::Pixel::To8Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
HIGH_INSTR_SAT2
const short Isis::HIGH_INSTR_SAT2 = ((short)(-32765))
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), Isis::Pixel::To16Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
HIGH_INSTR_SAT4
const float Isis::HIGH_INSTR_SAT4 = (*((const float *) &IHIGH_INSTR_SAT4))
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), TestPixel(), Isis::Pixel::To32Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
HIGH_INSTR_SAT8
const double Isis::HIGH_INSTR_SAT8 = IHIGH_INSTR_SAT8.d
Referenced by Isis::Pixel::IsHigh(), IsHighPixel(), Isis::Pixel::IsHis(), IsHisPixel(), Isis::Stretch::Stretch(), Isis::ProcessImport::TestPixel(), TestPixel(), Isis::Pixel::To16Bit(), Isis::Pixel::To16UBit(), Isis::Pixel::To32Bit(), Isis::Pixel::To8Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
HIGH_INSTR_SATU2
const unsigned short Isis::HIGH_INSTR_SATU2 = ((unsigned short) 65534)
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), Isis::Pixel::To16UBit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
HIGH_INSTR_SATUI4
const unsigned int Isis::HIGH_INSTR_SATUI4 = ((unsigned int) 4294967294)
HIGH_REPR_SAT1
const unsigned char Isis::HIGH_REPR_SAT1 = ((unsigned char) 255)
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), Isis::Pixel::To8Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
HIGH_REPR_SAT2
const short Isis::HIGH_REPR_SAT2 = ((short)(-32764))
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), Isis::Pixel::To16Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
HIGH_REPR_SAT4
const float Isis::HIGH_REPR_SAT4 = (*((const float *) &IHIGH_REPR_SAT4))
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), TestPixel(), Isis::Pixel::To32Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
HIGH_REPR_SAT8
const double Isis::HIGH_REPR_SAT8 = IHIGH_REPR_SAT8.d
Referenced by Isis::Pixel::IsHigh(), IsHighPixel(), Isis::Pixel::IsHrs(), IsHrsPixel(), Isis::Stretch::Stretch(), Isis::ProcessImport::TestPixel(), TestPixel(), Isis::ImageImporter::testSpecial(), Isis::Pixel::To16Bit(), Isis::Pixel::To16UBit(), Isis::Pixel::To32Bit(), Isis::Pixel::To8Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
HIGH_REPR_SATU2
const unsigned short Isis::HIGH_REPR_SATU2 = ((unsigned short) 65535)
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), Isis::Pixel::To16UBit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
HIGH_REPR_SATUI4
const unsigned int Isis::HIGH_REPR_SATUI4 = ((unsigned int) 4294967295)
His
const double Isis::His = IHIGH_INSTR_SAT8.d
Value for an Isis High Instrument Saturation pixel.
Referenced by StringToPixel().
Hrs
const double Isis::Hrs = IHIGH_REPR_SAT8.d
Value for an Isis High Representation Saturation pixel.
Referenced by Isis::Calculator::Pop(), and StringToPixel().
iApp
Application * Isis::iApp = NULL
Referenced by Isis::History::AddEntry(), Isis::Application::Application(), Isis::Progress::CheckStatus(), Isis::Application::GetUserInterface(), Isis::Application::GuiLog(), Isis::Application::HasParent(), Isis::Application::Log(), Isis::BundleAdjust::outputBundleStatus(), Isis::Gui::ShowWarning(), and Isis::Process::WriteHistory().
IHIGH_INSTR_SAT4
const int Isis::IHIGH_INSTR_SAT4 = 0xFF7FFFFE
Referenced by Isis::ProcessExportPds::StandardImageImage(), and Isis::ProcessExportPds::StandardJP2Image().
IHIGH_INSTR_SAT8
const DBL_UNION Isis::IHIGH_INSTR_SAT8 = { DBL_INIT(0xFFEFFFFF, 0xFFFFFFFE) }
IHIGH_REPR_SAT4
const int Isis::IHIGH_REPR_SAT4 = 0xFF7FFFFF
Referenced by Isis::ProcessExportPds::StandardImageImage(), and Isis::ProcessExportPds::StandardJP2Image().
IHIGH_REPR_SAT8
const DBL_UNION Isis::IHIGH_REPR_SAT8 = { DBL_INIT(0xFFEFFFFF, 0xFFFFFFFF) }
ILOW_INSTR_SAT4
const int Isis::ILOW_INSTR_SAT4 = 0xFF7FFFFD
Referenced by Isis::ProcessExportPds::StandardImageImage(), and Isis::ProcessExportPds::StandardJP2Image().
ILOW_INSTR_SAT8
const DBL_UNION Isis::ILOW_INSTR_SAT8 = { DBL_INIT(0xFFEFFFFF, 0xFFFFFFFD) }
ILOW_REPR_SAT4
const int Isis::ILOW_REPR_SAT4 = 0xFF7FFFFC
Referenced by Isis::ProcessExportPds::StandardImageImage(), and Isis::ProcessExportPds::StandardJP2Image().
ILOW_REPR_SAT8
const DBL_UNION Isis::ILOW_REPR_SAT8 = { DBL_INIT(0xFFEFFFFF, 0xFFFFFFFC) }
INULL4
const int Isis::INULL4 = 0xFF7FFFFB
Referenced by Isis::ProcessExportPds::StandardImageImage(), and Isis::ProcessExportPds::StandardJP2Image().
INULL8
const DBL_UNION Isis::INULL8 = { DBL_INIT(0xFFEFFFFF, 0xFFFFFFFB) }
IVALID_MAX4
const int Isis::IVALID_MAX4 = (*((const int *) &VALID_MAX4))
Referenced by Isis::ProcessImport::SetAttributes().
IVALID_MIN4
const int Isis::IVALID_MIN4 = 0xFF7FFFFA
Referenced by Isis::ProcessImport::SetAttributes().
Lis
const double Isis::Lis = ILOW_INSTR_SAT8.d
Value for an Isis Low Instrument Saturation pixel.
Referenced by StringToPixel().
LOW_INSTR_SAT1
const unsigned char Isis::LOW_INSTR_SAT1 = ((unsigned char) 0)
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), Isis::Pixel::To8Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
LOW_INSTR_SAT2
const short Isis::LOW_INSTR_SAT2 = ((short)(-32766))
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), Isis::Pixel::To16Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
LOW_INSTR_SAT4
const float Isis::LOW_INSTR_SAT4 = (*((const float *) &ILOW_INSTR_SAT4))
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), TestPixel(), Isis::Pixel::To32Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
LOW_INSTR_SAT8
const double Isis::LOW_INSTR_SAT8 = ILOW_INSTR_SAT8.d
Referenced by Isis::Pixel::IsLis(), IsLisPixel(), Isis::Pixel::IsLow(), IsLowPixel(), Isis::Stretch::Stretch(), Isis::ProcessImport::TestPixel(), TestPixel(), Isis::Pixel::To16Bit(), Isis::Pixel::To16UBit(), Isis::Pixel::To32Bit(), Isis::Pixel::To8Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
LOW_INSTR_SATU2
const unsigned short Isis::LOW_INSTR_SATU2 = ((unsigned short) 2)
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), Isis::Pixel::To16UBit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
LOW_INSTR_SATUI4
const unsigned int Isis::LOW_INSTR_SATUI4 = ((unsigned int) 2)
LOW_REPR_SAT1
const unsigned char Isis::LOW_REPR_SAT1 = ((unsigned char) 0)
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), Isis::Pixel::To8Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
LOW_REPR_SAT2
const short Isis::LOW_REPR_SAT2 = ((short)(-32767))
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), Isis::Pixel::To16Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
LOW_REPR_SAT4
const float Isis::LOW_REPR_SAT4 = (*((const float *) &ILOW_REPR_SAT4))
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), TestPixel(), Isis::Pixel::To32Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
LOW_REPR_SAT8
const double Isis::LOW_REPR_SAT8 = ILOW_REPR_SAT8.d
Referenced by Isis::Pixel::IsLow(), IsLowPixel(), Isis::Pixel::IsLrs(), IsLrsPixel(), Isis::Stretch::Stretch(), Isis::ProcessImport::TestPixel(), TestPixel(), Isis::ImageImporter::testSpecial(), Isis::Pixel::To16Bit(), Isis::Pixel::To16UBit(), Isis::Pixel::To32Bit(), Isis::Pixel::To8Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
LOW_REPR_SATU2
const unsigned short Isis::LOW_REPR_SATU2 = ((unsigned short) 1)
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), Isis::Pixel::To16UBit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
LOW_REPR_SATUI4
const unsigned int Isis::LOW_REPR_SATUI4 = ((unsigned int) 1)
Lrs
const double Isis::Lrs = ILOW_REPR_SAT8.d
Value for an Isis Low Representation Saturation pixel.
Referenced by Isis::Calculator::Pop(), and StringToPixel().
Null
const double Isis::Null = INULL8.d
Value for an Isis Null pixel.
Referenced by Isis::Angle::Angle(), Isis::Angle::angle(), Isis::MosaicControlNetToolMovementConfigDialog::applySettings(), Isis::AutoReg::AutoReg(), Isis::BundleControlPoint::BundleControlPoint(), Isis::BundleObservationSolveSettings::BundleObservationSolveSettings(), Isis::AbstractTreeItem::catchNull(), Isis::GisGeometry::centroid(), Isis::PhotometricFunction::compute(), Isis::ControlPointGraphicsItem::ControlPointGraphicsItem(), Isis::PlotWindowBestFitDialog::createBestFitLine(), Isis::QnetTool::createFixedPoint(), Isis::ProjectionFactory::CreateForCube(), Isis::Camera::DetectorResolution(), Isis::CSMCamera::DetectorResolution(), Isis::Displacement::Displacement(), Isis::Displacement::displacement(), Isis::Distance::Distance(), Isis::GisGeometry::distance(), Isis::Distance::distance(), Isis::EditTool::EditTool(), Isis::Stereo::elevation(), Isis::GoodnessOfFitFilter::evaluate(), Isis::Equalization::ImageAdjustment::evaluate(), Isis::Chip::Extract(), Isis::PlotWindow::fillTable(), Isis::QnetPointGoodnessFilter::filter(), Isis::SpectralDefinition1D::findSpectelByWavelength(), Isis::BundleControlPoint::formatAdjustedSigmaString(), Isis::BundleControlPoint::formatBundleLatitudinalOutputDetailString(), Isis::BundleControlPoint::formatBundleRectangularOutputDetailString(), GainLineStat(), Isis::ControlNetStatistics::GenerateControlNetStats(), Isis::ControlMeasure::GetLineShift(), Isis::ControlMeasure::GetPixelShift(), Isis::ControlMeasure::GetResidualMagnitude(), Isis::ControlMeasure::GetSampleShift(), Isis::Hillshade::Hillshade(), Isis::Image::Image(), Isis::VimsGroundMap::Init(), Isis::InterestOperator::InitInterestResults(), Isis::InterestOperator::InterestByMeasure(), Isis::InterestOperator::InterestByPoint(), Isis::Angle::isValid(), Isis::Displacement::isValid(), Isis::Distance::isValid(), Isis::ControlMeasureLogData::IsValid(), Isis::SurfacePoint::LatitudeToMeters(), Isis::CSMCamera::LineResolution(), Isis::LoadCSV::load(), Isis::TProjection::LocalRadius(), Isis::SurfacePoint::LongitudeToMeters(), main(), Isis::Gruen::MatchAlgorithm(), Isis::MaximumCorrelation::MatchAlgorithm(), Isis::CubeAttributeOutput::maximum(), Isis::MosaicControlNetTool::maxMovementColorResidualMagnitude(), Isis::SurfacePoint::MetersToLatitude(), Isis::SurfacePoint::MetersToLongitude(), Isis::CubeAttributeOutput::minimum(), Isis::SunShadowTool::mouseButtonPress(), Isis::Camera::ObliqueDetectorResolution(), Isis::Camera::ObliquePixelResolution(), Isis::InterestOperator::Operate(), Isis::Average::operator()(), Isis::Displacement::operator*=(), Isis::Distance::operator*=(), Isis::Coordinate::operator+=(), Isis::Displacement::operator+=(), Isis::Distance::operator+=(), Isis::Coordinate::operator-=(), Isis::Displacement::operator-=(), Isis::Distance::operator-=(), Isis::Angle::operator/(), Isis::Displacement::operator/(), Isis::Distance::operator/(), Isis::Displacement::operator/=(), Isis::Distance::operator/=(), Isis::BundleSolutionInfo::outputHeader(), Isis::BundleSolutionInfo::outputPointsCSV(), Isis::ScatterPlotWindow::paint(), Isis::ControlPointGraphicsItem::paint(), Isis::SunShadowTool::paintViewport(), Isis::Pixel::Pixel(), Isis::Camera::PixelResolution(), Isis::ControlNetFilter::PointDistanceFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::ControlNetFilter::PointResMagnitudeFilter(), Isis::Calculator::Pop(), Isis::ProcessRubberSheet::ProcessRubberSheet(), Isis::Projection::Projection(), Isis::CubeIoHandler::read(), Isis::BundleSettings::readBundleSettings(), Isis::MosaicControlNetToolMovementConfigDialog::readSettings(), Isis::BundleObservationSolveSettings::readSolveSettings(), Isis::AutoReg::Reduce(), Isis::AutoReg::Register(), Isis::AutoReg::Registration(), Isis::RingPlaneProjection::RingPlaneProjection(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::CSMCamera::SampleResolution(), Isis::ScatterPlotWindow::ScatterPlotWindow(), Isis::Angle::setAngle(), Isis::Projection::SetComputedXY(), Isis::RingPlaneProjection::SetCoordinate(), Isis::TProjection::SetCoordinate(), Isis::Displacement::setDisplacement(), Isis::Distance::setDistance(), Isis::TProjection::SetGround(), Isis::RingPlaneProjection::SetGround(), Isis::BundleObservationSolveSettings::setInstrumentPointingSettings(), Isis::BundleObservationSolveSettings::setInstrumentPositionSettings(), Isis::ScatterPlotWindow::setMousePosition(), Isis::BundleSettings::setSolveOptions(), Isis::IsisBundleObservation::setSolveSettings(), Isis::Projection::SetUnboundUniversalGround(), Isis::TProjection::SetUnboundUniversalGround(), Isis::Projection::SetUniversalGround(), Isis::TProjection::SetUniversalGround(), Isis::RingPlaneProjection::SetUniversalGround(), Isis::Projection::SetXY(), Isis::Hillshade::shadedValue(), Isis::Spectel::Spectel(), StringToPixel(), Isis::RingPlaneProjection::To180Domain(), Isis::TProjection::To180Domain(), Isis::RingPlaneProjection::To360Domain(), Isis::TProjection::To360Domain(), Isis::RingPlaneProjection::ToClockwise(), Isis::RingPlaneProjection::ToCounterClockwise(), Isis::TProjection::ToPlanetocentric(), Isis::TProjection::ToPlanetographic(), Isis::TProjection::ToPositiveEast(), Isis::TProjection::ToPositiveWest(), Isis::Projection::ToProjectionX(), Isis::Projection::ToProjectionY(), Isis::ControlNetVersioner::toPvl(), Isis::MosaicControlNetTool::toPvl(), Isis::Projection::ToWorldX(), Isis::Projection::ToWorldY(), Isis::TProjection::TProjection(), Isis::JigsawSetupDialog::treeViewSelectionChanged(), Isis::ControlNetValidMeasure::ValidStandardOptions(), Isis::VisualDisplay::VisualDisplay(), Isis::RingPlaneProjection::XYRange(), Isis::TProjection::XYRange(), Isis::TProjection::XYRangeCheck(), Isis::RingPlaneProjection::XYRangeCheck(), Isis::TProjection::xyRangeOblique(), Isis::Angle::~Angle(), Isis::Distance::~Distance(), and Isis::Hillshade::~Hillshade().
NULL1
const unsigned char Isis::NULL1 = ((unsigned char) 0)
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), Isis::Pixel::To8Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
NULL2
const short Isis::NULL2 = ((short)(-32768))
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), Isis::Pixel::To16Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
NULL4
const float Isis::NULL4 = (*((const float *) &INULL4))
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), TestPixel(), Isis::Pixel::To32Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
NULL8
const double Isis::NULL8 = INULL8.d
Referenced by Isis::Statistics::Average(), Isis::QuickFilter::Average(), Isis::Statistics::BestMaximum(), Isis::Statistics::BestMinimum(), Isis::Statistics::ChebyshevMaximum(), Isis::Statistics::ChebyshevMinimum(), Isis::MultivariateStatistics::Correlation(), Isis::MultivariateStatistics::Covariance(), Isis::VimsSkyMap::Init(), Isis::Pixel::IsNull(), IsNullPixel(), Isis::Statistics::Maximum(), Isis::Statistics::Minimum(), Isis::Histogram::Mode(), Isis::Albedo::NormModelAlgorithm(), Isis::Mixed::NormModelAlgorithm(), Isis::MoonAlbedo::NormModelAlgorithm(), Isis::Topo::NormModelAlgorithm(), Isis::SpectralDefinition2D::operator()(), Isis::Histogram::Percent(), Isis::Statistics::Rms(), Isis::ProcessExport::SetInputRange(), Isis::VimsSkyMap::SetSky(), Isis::Histogram::Skew(), Isis::SpectralDefinition1D::SpectralDefinition1D(), Isis::Statistics::StandardDeviation(), Isis::Stretch::Stretch(), Isis::ProcessImport::TestPixel(), TestPixel(), Isis::ImageImporter::testSpecial(), Isis::Pixel::To16Bit(), Isis::Pixel::To16UBit(), Isis::Pixel::To32Bit(), Isis::Pixel::To8Bit(), Isis::Pixel::ToDouble(), Isis::Pixel::ToFloat(), Isis::ProcessImportPds::TranslatePdsProjection(), Isis::Statistics::Variance(), and Isis::QuickFilter::Variance().
NULLU2
const unsigned short Isis::NULLU2 = ((unsigned short) 0)
Referenced by Isis::ProcessExportPds4::fileAreaObservational(), Isis::Pixel::To16UBit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
NULLUI4
const unsigned int Isis::NULLUI4 = ((unsigned int) 0)
OneBand
const int Isis::OneBand = 16
Referenced by Isis::Process::CheckRequirements().
PI
const double Isis::PI = 3.14159265358979323846
The mathematical constant PI.
Referenced by Isis::AlbedoAtm::AlbedoAtm(), Isis::RubberBandTool::angle(), Isis::Anisotropic1::AtmosModelAlgorithm(), Isis::Anisotropic2::AtmosModelAlgorithm(), Isis::HapkeAtm1::AtmosModelAlgorithm(), Isis::HapkeAtm2::AtmosModelAlgorithm(), Isis::Isotropic1::AtmosModelAlgorithm(), Isis::Isotropic2::AtmosModelAlgorithm(), Isis::Camera::CelestialNorthClockAngle(), Isis::CSMCamera::CelestialNorthClockAngle(), Isis::TiffImporter::convertProjection(), Isis::ProjectionFactory::CreateForCube(), Isis::GaussianDistribution::CumulativeDistribution(), Isis::Equirectangular::Equirectangular(), Isis::AtmosModel::G11Prime(), Isis::AtmosModel::GenerateAhTable(), Isis::AtmosModel::GenerateHahgTables(), Isis::AtmosModel::GenerateHahgTablesShadow(), Isis::SurfacePoint::GetLongitude(), Isis::Projection::GetX(), Isis::CameraGroundMap::GetXY(), Isis::Projection::GetY(), Isis::Camera::GroundAzimuth(), Isis::Camera::GroundRange(), Isis::Longitude::inRange(), Isis::NumericalAtmosApprox::InrFunc2Bint(), Isis::NoOperator::Interest(), Isis::EquatorialCylindricalShape::intersectSurface(), Isis::GaussianDistribution::InverseCumulativeDistribution(), Isis::LambertConformal::LambertConformal(), Isis::TProjection::LocalRadius(), Isis::LunarAzimuthalEqualArea::LunarAzimuthalEqualArea(), Isis::LunarLambertMcEwen::LunarLambertMcEwen(), Isis::Mercator::Mercator(), Isis::SurfacePoint::MetersToLongitude(), Isis::MiniRF::MiniRF(), Isis::Mollweide::Mollweide(), Isis::MoonAlbedo::MoonAlbedo(), Isis::Mollweide::newton_rapheson(), Isis::AlbedoAtm::NormModelAlgorithm(), Isis::MoonAlbedo::NormModelAlgorithm(), Isis::ShadeAtm::NormModelAlgorithm(), Isis::TopoAtm::NormModelAlgorithm(), Isis::ObliqueCylindrical::ObliqueCylindrical(), Isis::Orthographic::Orthographic(), Isis::NumericalAtmosApprox::OutrFunc2Bint(), Isis::Hapke::PhotoModelAlgorithm(), Isis::Lambert::PhotoModelAlgorithm(), Isis::LommelSeeliger::PhotoModelAlgorithm(), Isis::LunarLambert::PhotoModelAlgorithm(), Isis::LunarLambertEmpirical::PhotoModelAlgorithm(), Isis::LunarLambertMcEwen::PhotoModelAlgorithm(), Isis::Minnaert::PhotoModelAlgorithm(), Isis::MinnaertEmpirical::PhotoModelAlgorithm(), Isis::PhotoModel::PhtTopder(), Isis::PointPerspective::PointPerspective(), Isis::PolarStereographic::PolarStereographic(), Isis::CubeCalculator::prepareCalculations(), Isis::GaussianDistribution::Probability(), Isis::CSMCamera::RightAscension(), Isis::ProjectionFactory::RingsCreateForCube(), Isis::Affine::Rotate(), Isis::TProjection::Scale(), Isis::AtmosModel::SetAtmosInc(), Isis::AtmosModel::SetAtmosPhi(), Isis::Projection::SetComputedXY(), Isis::Equirectangular::SetCoordinate(), Isis::LambertConformal::SetCoordinate(), Isis::LunarAzimuthalEqualArea::SetCoordinate(), Isis::Mercator::SetCoordinate(), Isis::Mollweide::SetCoordinate(), Isis::ObliqueCylindrical::SetCoordinate(), Isis::Orthographic::SetCoordinate(), Isis::PointPerspective::SetCoordinate(), Isis::PolarStereographic::SetCoordinate(), Isis::SimpleCylindrical::SetCoordinate(), Isis::Sinusoidal::SetCoordinate(), Isis::TransverseMercator::SetCoordinate(), Isis::RadarGroundMap::SetFocalPlane(), Isis::Equirectangular::SetGround(), Isis::LambertConformal::SetGround(), Isis::LunarAzimuthalEqualArea::SetGround(), Isis::Mercator::SetGround(), Isis::Mollweide::SetGround(), Isis::ObliqueCylindrical::SetGround(), Isis::Orthographic::SetGround(), Isis::PointPerspective::SetGround(), Isis::PolarStereographic::SetGround(), Isis::SimpleCylindrical::SetGround(), Isis::Sinusoidal::SetGround(), Isis::TransverseMercator::SetGround(), Isis::SimpleCylindrical::SimpleCylindrical(), Isis::Sinusoidal::Sinusoidal(), Isis::Spice::subSolarPoint(), Isis::Spice::subSpacecraftPoint(), Isis::LinearAlgebra::toAxisAngle(), Isis::TProjection::ToPlanetocentric(), Isis::TProjection::ToPlanetographic(), Isis::TopoAtm::TopoAtm(), Isis::FourierTransform::Transform(), Isis::TransverseMercator::TransverseMercator(), Isis::Equirectangular::TrueScaleLatitude(), Isis::LambertConformal::TrueScaleLatitude(), Isis::Mercator::TrueScaleLatitude(), Isis::Orthographic::TrueScaleLatitude(), Isis::PointPerspective::TrueScaleLatitude(), Isis::PolarStereographic::TrueScaleLatitude(), Isis::Angle::unitWrapValue(), Isis::LambertConformal::XYRange(), Isis::Orthographic::XYRange(), Isis::PolarStereographic::XYRange(), and Isis::TransverseMercator::XYRange().
RAD2DEG
const double Isis::RAD2DEG = 57.29577951308232087679815481
Multiplier for converting from radians to degrees.
Referenced by Isis::Angle::angle(), Isis::IsisBundleObservation::bundleOutputCSV(), Isis::IsisBundleObservation::bundleOutputString(), Isis::Planar::CenterRingLongitude(), Isis::RingCylindrical::CenterRingLongitude(), Isis::CSMCamera::Declination(), Isis::PlaneShape::emissionAngle(), Isis::ShapeModel::emissionAngle(), Isis::BundleControlPoint::formatBundleLatitudinalOutputDetailString(), Isis::BundleControlPoint::formatBundleRectangularOutputDetailString(), Isis::PlaneShape::incidenceAngle(), Isis::ShapeModel::incidenceAngle(), Isis::DemShape::intersectSurface(), Isis::EquatorialCylindricalShape::intersectSurface(), Isis::BulletShapeModel::isVisibleFrom(), Isis::Planar::Mapping(), Isis::RingCylindrical::Mapping(), Isis::Camera::OffNadirAngle(), Isis::BundleSolutionInfo::outputPointsCSV(), Isis::Sensor::PhaseAngle(), Isis::ShapeModel::phaseAngle(), Isis::CSMCamera::RightAscension(), Isis::Planar::SetCoordinate(), Isis::RingCylindrical::SetCoordinate(), Isis::Robinson::SetCoordinate(), and Isis::Camera::Slope().
ReadWrite
const int Isis::ReadWrite = 64
Referenced by Isis::GuiEditFile::clearFile(), Isis::Cube::create(), Isis::PlotCurve::fromByteArray(), Isis::Cube::isReadOnly(), Isis::Cube::open(), Isis::GuiEditFile::OpenFile(), Isis::Project::save(), Isis::ControlDisplayProperties::save(), Isis::ControlList::save(), Isis::DisplayProperties::save(), Isis::GuiCameraDisplayProperties::save(), Isis::ImageList::save(), Isis::ShapeDisplayProperties::save(), Isis::ShapeList::save(), Isis::TargetBodyDisplayProperties::save(), Isis::TemplateList::save(), Isis::MosaicSceneWidget::save(), Isis::GuiEditFile::saveAsFile(), Isis::Process::SetInputCube(), Isis::PlotCurve::toByteArray(), Isis::DisplayProperties::toPvl(), Isis::Image::toPvl(), Isis::MosaicSceneWidget::toPvl(), and Isis::Shape::toPvl().
sBoolean
QString Isis::sBoolean = { "False", "True" }
String values for Boolean.
Referenced by Isis::ControlNetStatistics::GeneratePointStats(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::ControlNetFilter::PointEditLockFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointMeasurePropertiesFilter(), Isis::ControlNetFilter::PointMeasuresFilter(), Isis::ControlNetFilter::PointNumMeasuresEditLockFilter(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::ControlNetFilter::PointResMagnitudeFilter(), and Isis::ControlNetFilter::PointStats().
SizeMatch
const int Isis::SizeMatch = 1
Referenced by Isis::Process::CheckRequirements().
SpatialMatch
const int Isis::SpatialMatch = 2
Referenced by Isis::Process::CheckRequirements(), Isis::ProcessByLine::SetInputCube(), Isis::ProcessBySpectra::SetInputCube(), Isis::ProcessBySample::SetInputCube(), and Isis::ProcessByBrick::VerifyCubes().
sPointType
QString Isis::sPointType = { "Fixed", "Constrained", "Free" }
String names for Point Type.
Referenced by Isis::ControlNetStatistics::GeneratePointStats(), Isis::ControlNetFilter::PointCubeNamesFilter(), Isis::ControlNetFilter::PointEditLockFilter(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::ControlNetFilter::PointResMagnitudeFilter(), and Isis::ControlNetFilter::PointStats().
trackingTableName
const QString Isis::trackingTableName = "InputImages"
Referenced by Isis::ProcessMosaic::StartProcess(), and Isis::TrackingTable::toTable().
TWOPI
const double Isis::TWOPI = 6.2831853071795864769253
Two * PI, a complete revolution.
Referenced by Isis::FunctionTools::realCubicRoots().
VALID_MAX1
const unsigned char Isis::VALID_MAX1 = ((unsigned char) 254)
Referenced by Isis::ProcessImport::SetAttributes(), Isis::Cube::setMinMax(), Isis::ProcessExport::SetOutputType(), Isis::Pixel::To8Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
VALID_MAX2
const short Isis::VALID_MAX2 = ((short) 32767)
Referenced by Isis::ControlNetFilter::CubeNumPointsFilter(), Isis::ControlNetFilter::PointMeasuresFilter(), Isis::ControlNetFilter::PointNumMeasuresEditLockFilter(), Isis::ProcessImport::SetAttributes(), Isis::Cube::setMinMax(), Isis::ProcessExport::SetOutputType(), Isis::Pixel::To16Bit(), Isis::Pixel::To16UBit(), and Isis::Pixel::ToFloat().
VALID_MAX4
const float Isis::VALID_MAX4 = FLT_MAX
Referenced by Isis::ProcessImport::SetAttributes(), TestPixel(), and Isis::Pixel::ToDouble().
VALID_MAX8
const double Isis::VALID_MAX8 = DBL_MAX
Referenced by Isis::Pixel::To32Bit(), and Isis::Pixel::ToFloat().
VALID_MAXU2
const unsigned short Isis::VALID_MAXU2 = ((unsigned short) 65522)
Referenced by Isis::ProcessImport::SetAttributes(), Isis::Cube::setMinMax(), Isis::ProcessExport::SetOutputType(), and Isis::Pixel::ToFloat().
VALID_MAXUI4
const unsigned int Isis::VALID_MAXUI4 = ((unsigned int) 4294967282)
Referenced by Isis::ProcessImport::SetAttributes().
VALID_MIN1
const unsigned char Isis::VALID_MIN1 = ((unsigned char) 1)
Referenced by Isis::ProcessImport::SetAttributes(), Isis::Cube::setMinMax(), Isis::ProcessExport::SetOutputType(), Isis::Pixel::To8Bit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
VALID_MIN2
const short Isis::VALID_MIN2 = ((short)(-32752))
Referenced by Isis::ProcessImport::SetAttributes(), Isis::Cube::setMinMax(), Isis::ProcessExport::SetOutputType(), Isis::Pixel::To16Bit(), Isis::Pixel::To16UBit(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
VALID_MIN4
const float Isis::VALID_MIN4 = (*((const float *) &IVALID_MIN4))
Referenced by Isis::Pixel::IsSpecial(), IsSpecial(), Isis::ProcessImport::SetAttributes(), TestPixel(), and Isis::Pixel::ToDouble().
VALID_MIN8
const double Isis::VALID_MIN8 = IVALID_MIN8.d
Referenced by Isis::Pixel::IsSpecial(), IsSpecial(), Isis::Pixel::IsValid(), IsValidPixel(), Isis::Pixel::To16Bit(), Isis::Pixel::To16UBit(), Isis::Pixel::To32Bit(), Isis::Pixel::To8Bit(), and Isis::Pixel::ToFloat().
VALID_MINU2
const unsigned short Isis::VALID_MINU2 = ((unsigned short) 3)
Referenced by Isis::ProcessImport::SetAttributes(), Isis::Cube::setMinMax(), Isis::ProcessExport::SetOutputType(), Isis::Pixel::ToDouble(), and Isis::Pixel::ToFloat().
VALID_MINUI4
const unsigned int Isis::VALID_MINUI4 = ((unsigned int) 3)
Referenced by Isis::TrackingTable::fileNameToPixel(), Isis::TrackingTable::pixelToFileName(), Isis::TrackingTable::pixelToSN(), Isis::ProcessImport::SetAttributes(), Isis::ProcessMosaic::StartProcess(), and Isis::TrackingTable::toTable().
ValidMaximum
const double Isis::ValidMaximum = DBL_MAX
The maximum valid double value for Isis pixels.
Referenced by Isis::ControlNetFilter::CubeConvexHullFilter(), Isis::Cube::histogram(), Isis::Histogram::Histogram(), Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::AutoReg::Parse(), Isis::ControlNetFilter::PointGoodnessOfFitFilter(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::ControlNetFilter::PointPixelShiftFilter(), Isis::ControlNetFilter::PointResMagnitudeFilter(), Isis::Statistics::readStatistics(), Isis::Cube::statistics(), and Isis::ControlNetValidMeasure::ValidatePvlDN().
ValidMinimum
const double Isis::ValidMinimum = IVALID_MIN8.d
The minimum valid double value for Isis pixels.
All special pixels have a value lower than this minimum.
Referenced by Isis::Cube::histogram(), Isis::Histogram::Histogram(), Isis::InterestOperator::InitInterestResults(), Isis::ControlNetValidMeasure::InitStdOptions(), Isis::ControlNetValidMeasure::InitStdOptionsGroup(), Isis::AutoReg::Parse(), Isis::ControlNetFilter::PointLatLonFilter(), Isis::Statistics::readStatistics(), Isis::Cube::statistics(), and Isis::ControlNetValidMeasure::ValidatePvlDN().
VIEWSIZE
const int Isis::VIEWSIZE = 301
Constant representing the length and width of the chip viewports.
Referenced by Isis::ChipViewportsWidget::setPoint().