Isis Developer Reference: Isis::Message Namespace Reference
Isis::Message Namespace Reference
Namespace containing standardized Isis error messages.
Functions
QString ArraySubscriptNotInRange (int index)
This error should be used when an Isis object or application is checking array bounds and the legal range has been violated.
QString KeywordAmbiguous (const QString &key)
This error should be used when a supplied keyword for an Isis application parameter does not contain enough characters to distinguish it from another keyword.
QString KeywordUnrecognized (const QString &key)
This error should be used when a supplied keyword for an Isis application parameter does not match any of the parameters for that application.
QString KeywordDuplicated (const QString &key)
This error should be used when a supplied keyword for an Isis application parameter is the same as one previously supplied.
QString KeywordNotArray (const QString &key)
This error should be used when a supplied keyword is being used as an array (i.e., with a subscript) but is only a scaler entity.
QString KeywordNotFound (const QString &key)
This error should be used when a supplied keyword is not defined in the application.
QString KeywordBlockInvalid (const QString &block)
This error has been deprecated and should not be used in new code.
QString KeywordBlockStartMissing (const QString &block, const QString &found)
This error has been deprecated and should not be used in new code.
QString KeywordBlockEndMissing (const QString &block, const QString &found)
This error has been deprecated and should not be used in new code.
QString KeywordValueBad (const QString &key)
This error should be used when a supplied keyword does not appear in the list (e.g., an Isis cube label).
QString KeywordValueBad (const QString &key, const QString &value)
This error should be used when the value of a supplied keyword is incorrect.
QString KeywordValueExpected (const QString &key)
This error should be used when the value of a supplied keyword was expected but not present.
QString KeywordValueNotInRange (const QString &key, const QString &value, const QString &range)
This error should be used when the value of a supplied keyword is not within a specific range.
QString KeywordValueNotInList (const QString &key, const QString &value, const std::vector< QString > &list)
This error should be used when the value of a supplied keyword is not one of a specific list of possible values.
QString MissingDelimiter (const char delimiter)
This error should be used when a delimiter is missing.
QString MissingDelimiter (const char delimiter, const QString &near)
This error should be used when a delimiter is missing.
QString FileOpen (const QString &filename)
This error should be used when a file could not be opened.
QString FileCreate (const QString &filename)
This error should be used when a file could not be created.
QString FileRead (const QString &filename)
This error should be used when an error accrues during a read of a file.
QString FileWrite (const QString &filename)
This error should be used when an error accrues during a write to a file.
QString MemoryAllocationFailed ()
This error should be used when an error accrues during a memory allocation such as "new".
Detailed Description
Namespace containing standardized Isis error messages.
IsisMessage is not a class. It only contains a namespace which consists of all the standardized Isis error messages. These messages should be used when applicable instead of constructing the message string inside the object or application.
Function Documentation
ArraySubscriptNotInRange()
QString Isis::Message::ArraySubscriptNotInRange (int index)
This error should be used when an Isis object or application is checking array bounds and the legal range has been violated.
Parameters
index - Array index which is out of bounds
Returns
QString - A standardized Isis error message with the parameter inserted
References Isis::toString().
Referenced by Isis::Buffer::at(), Isis::Histogram::BinCount(), Isis::Histogram::BinMiddle(), Isis::Histogram::BinRange(), Isis::ImageHistogram::BinRange(), Isis::PvlKeyword::comment(), Isis::PvlObject::group(), Isis::Buffer::Index(), Isis::PvlKeyword::isEquivalent(), Isis::PvlKeyword::isNull(), Isis::PvlObject::object(), Isis::PvlContainer::operator[](), Isis::PvlKeyword::operator[](), Isis::PvlKeyword::unit(), Isis::PvlToken::value(), and Isis::PvlToken::valueUpper().
FileCreate()
QString Isis::Message::FileCreate (const QString & filename)
This error should be used when a file could not be created.
Parameters
filename - The name of the file
Returns
QString - A standardized Isis error message with the parameter inserted
Referenced by Isis::Pvl::write().
FileOpen()
QString Isis::Message::FileOpen (const QString & filename)
This error should be used when a file could not be opened.
Parameters
filename - The name of the file
Returns
QString - A standardized Isis error message with the parameter inserted
Referenced by Isis::Pvl::append(), Isis::Application::Application(), Isis::Pvl::read(), Isis::Blob::Read(), Isis::FileList::read(), and Isis::FileList::write().
FileRead()
QString Isis::Message::FileRead (const QString & filename)
This error should be used when an error accrues during a read of a file.
Parameters
filename - The name of the file
Returns
QString - A standardized Isis error message with the parameter inserted
FileWrite()
QString Isis::Message::FileWrite (const QString & filename)
This error should be used when an error accrues during a write to a file.
Parameters
filename - The name of the file
Returns
QString - A standardized Isis error message with the parameter inserted
KeywordAmbiguous()
QString Isis::Message::KeywordAmbiguous (const QString & key)
This error should be used when a supplied keyword for an Isis application parameter does not contain enough characters to distinguish it from another keyword.
Parameters
key - The name of the keyword which is ambiguous
Returns
QString - A standardized Isis error message with the parameter inserted
KeywordBlockEndMissing()
QString Isis::Message::KeywordBlockEndMissing (const QString & block, const QString & found)
This error has been deprecated and should not be used in new code.
Parameters
block - The name of the block with the missing end tag
found - The QString found in the place of the missing block end
Returns
QString - A standardized Isis error message with the parameter inserted
KeywordBlockInvalid()
QString Isis::Message::KeywordBlockInvalid (const QString & block)
This error has been deprecated and should not be used in new code.
Parameters
block - The name of the invalid keyword block
Returns
QString - A standardized Isis error message with the parameter inserted
KeywordBlockStartMissing()
QString Isis::Message::KeywordBlockStartMissing (const QString & block, const QString & found)
This error has been deprecated and should not be used in new code.
Parameters
block - The name of the block with the missing start tag
found - The QString found in the place of the missing block start
Returns
QString - A standardized Isis error message with the parameter inserted
KeywordDuplicated()
QString Isis::Message::KeywordDuplicated (const QString & key)
This error should be used when a supplied keyword for an Isis application parameter is the same as one previously supplied.
Parameters
key - The name of the keyword which has been duplicated
Returns
QString - A standardized Isis error message with the parameter inserted
KeywordNotArray()
QString Isis::Message::KeywordNotArray (const QString & key)
This error should be used when a supplied keyword is being used as an array (i.e., with a subscript) but is only a scaler entity.
Parameters
key - The name of the keyword which is not an array
Returns
QString - A standardized Isis error message with the parameter inserted
KeywordNotFound()
QString Isis::Message::KeywordNotFound (const QString & key)
This error should be used when a supplied keyword is not defined in the application.
Parameters
key - The name of the keyword which was not found
Returns
QString - A standardized Isis error message with the parameter inserted
KeywordUnrecognized()
QString Isis::Message::KeywordUnrecognized (const QString & key)
This error should be used when a supplied keyword for an Isis application parameter does not match any of the parameters for that application.
Parameters
key - The name of the keyword which is unrecognized
Returns
QString - A standardized Isis error message with the parameter inserted
KeywordValueBad() [1/2]
QString Isis::Message::KeywordValueBad (const QString & key)
This error should be used when a supplied keyword does not appear in the list (e.g., an Isis cube label).
Parameters
key - The name of the keyword which is bad
Returns
QString - A standardized Isis error message with the parameter inserted
Referenced by Isis::PvlTokenizer::Load().
KeywordValueBad() [2/2]
QString Isis::Message::KeywordValueBad (const QString & key, const QString & value)
This error should be used when the value of a supplied keyword is incorrect.
Parameters
key - The keyword name which is bad
value - The value of the keyword which is bad
Returns
QString - A standardized Isis error message with the parameter inserted
KeywordValueExpected()
QString Isis::Message::KeywordValueExpected (const QString & key)
This error should be used when the value of a supplied keyword was expected but not present.
Parameters
key - The keyword name which is bad
Returns
QString - A standardized Isis error message with the parameter inserted
KeywordValueNotInList()
QString Isis::Message::KeywordValueNotInList (const QString & key, const QString & value, const std::vector< QString > & list)
This error should be used when the value of a supplied keyword is not one of a specific list of possible values.
Parameters
key - The keyword name which has a bad value
value - The value of the keyword
list - A vector of all the legal values for the keyword
Returns
QString - A standardized Isis error message with the parameter inserted
KeywordValueNotInRange()
QString Isis::Message::KeywordValueNotInRange (const QString & key, const QString & value, const QString & range)
This error should be used when the value of a supplied keyword is not within a specific range.
Parameters
key - The keyword name which has a bad value
value - The value of the keyword
range - The minimum and maximum allowed values for the keyword formatted and inserted into a QString
Returns
QString - A standardized Isis error message with the parameter inserted
MemoryAllocationFailed()
QString Isis::Message::MemoryAllocationFailed ()
This error should be used when an error accrues during a memory allocation such as "new".
Returns
QString - A standardized Isis error message with the parameter inserted
Referenced by Isis::Buffer::Allocate().
MissingDelimiter() [1/2]
QString Isis::Message::MissingDelimiter (const char delimiter)
This error should be used when a delimiter is missing.
Parameters
delimiter - The delimiter that is missing
Returns
QString - A standardized Isis error message with the parameter inserted
References Isis::toString().
Referenced by Isis::PvlTokenizer::ReadToBrace(), Isis::PvlTokenizer::ReadToDoubleQuote(), Isis::PvlTokenizer::ReadToParen(), and Isis::PvlTokenizer::ReadToSingleQuote().
MissingDelimiter() [2/2]
QString Isis::Message::MissingDelimiter (const char delimiter, const QString & near)
This error should be used when a delimiter is missing.
Parameters
delimiter - The delimiter that is missing
near - The value the missing delimiter is near
Returns
QString - A standardized Isis error message with the parameter inserted
References Isis::toString().